import type { Metadata } from "next";
import Link from "next/link";
import EnglishSensibleHeatRateCalculator from "../../../../components/EnglishSensibleHeatRateCalculator";
import { buildSiteUrl } from "../../../../siteConfig";

const pagePath = "/en/engineering-calculators/heat-transfer/sensible-heat-rate-calculator";

export const metadata: Metadata = { title: "Sensible Heat Rate Calculator (ṁcₚΔT)", description: "Calculate fluid heating or cooling rate from mass flow, specific heat and temperature change.", alternates: { canonical: pagePath, languages: { en: pagePath } }, openGraph: { title: "Sensible Heat Rate Calculator", description: "Calculate Q̇ = ṁcₚΔT for a stated fluid mass flow, specific heat and temperature difference.", url: buildSiteUrl(pagePath), siteName: "BirimCeviri.app", locale: "en_US", type: "article" } };

export default function SensibleHeatRateCalculatorPage() {
  return <main className="all-conversions-page"><div className="all-conversions-shell"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/en">Home</Link><span aria-hidden="true">›</span><Link href="/en/engineering-calculators">Engineering Calculators</Link><span aria-hidden="true">›</span><Link href="/en/engineering-calculators/heat-transfer">Heat Transfer</Link><span aria-hidden="true">›</span><span>Sensible Heat Rate Calculator</span></nav><header className="all-conversions-header"><h1>Sensible Heat Rate Calculator</h1><p>Calculate steady fluid heating or cooling rate from mass flow, specific heat and temperature change.</p></header><EnglishSensibleHeatRateCalculator /><article className="category-article-content"><h2>Method</h2><p>For a fluid with no phase change, Q̇ = ṁ × c<sub>p</sub> × ΔT. The heat-capacity rate ṁc<sub>p</sub> is useful when comparing the hot and cold streams of a heat exchanger.</p><h2>Worked example</h2><p>Water flowing at 1 kg/s with c<sub>p</sub> = 4.186 kJ/(kg·K) and a 20 K temperature rise requires 1 × 4.186 × 20 = 83.72 kW.</p><h2>Important limits</h2><p>Use enthalpy rather than this relation for boiling, condensation, steam, refrigerants or another phase-change process. Check fluid properties at the expected operating condition if temperature or pressure varies substantially.</p><h2>Related tools</h2><p><Link href="/en/engineering-calculators/heat-transfer/lmtd-heat-exchanger-calculator">LMTD Heat Exchanger Calculator</Link> · <Link href="/en/calculators/heat-energy">Heat Energy Calculator</Link> · <Link href="/en/engineering-calculators/heat-transfer">Heat Transfer Calculators</Link></p></article></div></main>;
}
