export type EnglishChemistryTool = {
  slug: string;
  title: string;
  description: string;
  variables: Array<{ symbol: string; label: string; unit?: string }>;
  assumptions: string;
  limitations: string;
};

export const englishChemistryTools: EnglishChemistryTool[] = [
  { slug: "molarity", title: "Molarity Calculator", description: "Solve M = n / V for molarity, amount of solute or solution volume.", variables: [{ symbol: "M", label: "amount concentration", unit: "mol/L" }, { symbol: "n", label: "amount of solute", unit: "mol" }, { symbol: "V", label: "final solution volume", unit: "L" }], assumptions: "The entered volume is the final solution volume.", limitations: "This ideal calculation does not correct concentration for activity, temperature or volume change on mixing." },
  { slug: "ph", title: "pH Calculator", description: "Find pH, pOH, hydrogen-ion or hydroxide-ion concentration.", variables: [{ symbol: "pH", label: "negative base-10 logarithm of hydrogen-ion concentration" }, { symbol: "[H+]", label: "hydrogen-ion concentration", unit: "mol/L" }, { symbol: "[OH-]", label: "hydroxide-ion concentration", unit: "mol/L" }], assumptions: "The common aqueous relationship pH + pOH = 14 is used at 25 C.", limitations: "Rigorous pH is based on activity, not simply concentration; this is not a buffer or equilibrium model." },
  { slug: "dilution", title: "Dilution Calculator", description: "Solve the dilution equation for one missing value.", variables: [{ symbol: "C1, C2", label: "stock and target concentration" }, { symbol: "V1, V2", label: "stock and final volume" }], assumptions: "Solute amount is unchanged during a simple dilution.", limitations: "Concentration units and volume units must be internally consistent; reactions and non-ideal mixing are not modeled." },
  { slug: "mole", title: "Mole Calculator", description: "Calculate moles, mass and particle count from a molar mass.", variables: [{ symbol: "n", label: "amount of substance", unit: "mol" }, { symbol: "m", label: "mass", unit: "g" }, { symbol: "M", label: "molar mass", unit: "g/mol" }], assumptions: "The supplied molar mass represents the substance being calculated.", limitations: "The calculator does not identify a compound or validate its formula or molar mass." },
  { slug: "molality", title: "Molality Calculator", description: "Solve molality, solute amount or solvent mass.", variables: [{ symbol: "m", label: "molality", unit: "mol/kg" }, { symbol: "n", label: "amount of solute", unit: "mol" }, { symbol: "kg solvent", label: "mass of solvent", unit: "kg" }], assumptions: "The denominator is solvent mass, not total solution mass.", limitations: "This does not calculate activity coefficients or account for chemical reactions." },
  { slug: "ppm", title: "PPM Calculator", description: "Calculate mass-based parts per million concentration.", variables: [{ symbol: "ppm", label: "mass fraction multiplied by one million" }, { symbol: "solute mass", label: "mass of dissolved substance" }, { symbol: "solution mass", label: "total solution mass" }], assumptions: "Both mass inputs use the same unit.", limitations: "Usage of ppm differs by field; this page uses a mass-based definition only." },
  { slug: "stoichiometry", title: "Stoichiometry Calculator", description: "Use a balanced-equation mole ratio to find theoretical product amount.", variables: [{ symbol: "n", label: "known or target amount", unit: "mol" }, { symbol: "coefficient", label: "balanced-equation stoichiometric coefficient" }, { symbol: "M", label: "target molar mass", unit: "g/mol" }], assumptions: "The supplied equation coefficients are balanced and the known reactant is available in the required amount.", limitations: "It does not find a limiting reagent, model side reactions or apply an experimental yield." },
  { slug: "percent-yield", title: "Percent Yield Calculator", description: "Calculate percent, actual or theoretical reaction yield.", variables: [{ symbol: "actual yield", label: "observed product amount" }, { symbol: "theoretical yield", label: "maximum predicted product amount" }, { symbol: "% yield", label: "actual divided by theoretical yield", unit: "%" }], assumptions: "Actual and theoretical yields use the same unit and refer to the same product.", limitations: "The tool does not determine theoretical yield from a chemical equation." },
  { slug: "titration", title: "Titration Calculator", description: "Solve a simple acid-base equivalence relationship.", variables: [{ symbol: "C", label: "concentration", unit: "mol/L" }, { symbol: "V", label: "volume" }, { symbol: "equivalents", label: "acid/base reacting equivalents per formula unit" }], assumptions: "At equivalence, the reacting acid and base equivalents are equal.", limitations: "It is not a titration curve, pH-at-equivalence or indicator-selection calculator." },
  { slug: "half-life", title: "Half-Life Calculator", description: "Calculate quantities and time for exponential radioactive decay.", variables: [{ symbol: "N", label: "remaining amount" }, { symbol: "N0", label: "initial amount" }, { symbol: "t", label: "elapsed time" }, { symbol: "t1/2", label: "half-life" }], assumptions: "The decay rate and half-life are constant over the interval.", limitations: "It is a learning model only and must not be used to assess radiation exposure, handling or safety." },
  { slug: "kc", title: "Equilibrium Constant (Kc) Calculator", description: "Calculate Kc from concentrations at equilibrium.", variables: [{ symbol: "Kc", label: "concentration equilibrium constant" }, { symbol: "[A], [B], [C], [D]", label: "equilibrium concentrations" }, { symbol: "coefficient", label: "balanced-equation stoichiometric coefficient" }], assumptions: "Entries represent equilibrium concentrations for the species included in the expression.", limitations: "Activities, solids, pure liquids, temperature dependence and reaction balancing are not evaluated." },
  { slug: "cell-potential", title: "Cell Potential Calculator", description: "Calculate standard cell potential from reduction potentials.", variables: [{ symbol: "E cell", label: "standard cell potential", unit: "V" }, { symbol: "E cathode", label: "cathode standard reduction potential", unit: "V" }, { symbol: "E anode", label: "anode standard reduction potential", unit: "V" }], assumptions: "Both supplied values are standard reduction potentials under standard conditions.", limitations: "It does not calculate non-standard potentials, cell current, resistance or battery capacity." },
];

export const englishChemistryHubPath = "/en/chemistry-calculators";
