"use client";

import { useMemo, useState } from "react";
import { calculateSolarPaybackEstimate } from "../converter/solarPanelPayback";
type Currency = "USD" | "EUR" | "GBP" | "CAD" | "AUD";
const parse = (value: string) => { const number = Number(value.trim().replace(/,/g, ".")); return Number.isFinite(number) ? number : Number.NaN; };

export default function EnglishSolarPaybackCalculator() {
  const [size, setSize] = useState("5"); const [yieldValue, setYieldValue] = useState("1300"); const [selfConsumption, setSelfConsumption] = useState("65"); const [importPrice, setImportPrice] = useState("0.18"); const [exportPrice, setExportPrice] = useState("0.06"); const [cost, setCost] = useState("10000"); const [currency, setCurrency] = useState<Currency>("USD");
  const result = useMemo(() => calculateSolarPaybackEstimate({ systemSizeKwp: parse(size), annualYieldKwhPerKwp: parse(yieldValue), selfConsumptionPercent: parse(selfConsumption), importedElectricityPricePerKwh: parse(importPrice), exportElectricityPricePerKwh: parse(exportPrice), systemCost: parse(cost) }), [size, yieldValue, selfConsumption, importPrice, exportPrice, cost]);
  const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 0 }).format(value); const number = (value: number) => new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(value);
  return <div className="category-general-converter"><div className="engineering-calculator-card"><div className="paint-calculator-grid">
    <label className="category-general-converter-field"><span>System size (kWp)</span><input type="text" inputMode="decimal" value={size} onChange={(event) => setSize(event.target.value)} /></label>
    <label className="category-general-converter-field"><span>Annual yield (kWh/kWp)</span><input type="text" inputMode="decimal" value={yieldValue} onChange={(event) => setYieldValue(event.target.value)} /><small className="calculator-field-note">Use an installer quote or a location-specific production estimate.</small></label>
    <label className="category-general-converter-field"><span>Self-consumed production (%)</span><input type="text" inputMode="decimal" value={selfConsumption} onChange={(event) => setSelfConsumption(event.target.value)} /></label>
    <label className="category-general-converter-field"><span>Display currency</span><select value={currency} onChange={(event) => setCurrency(event.target.value as Currency)}><option value="USD">USD ($)</option><option value="EUR">EUR (€)</option><option value="GBP">GBP (£)</option><option value="CAD">CAD (CA$)</option><option value="AUD">AUD (A$)</option></select></label>
    <label className="category-general-converter-field"><span>Grid electricity price ({currency}/kWh)</span><input type="text" inputMode="decimal" value={importPrice} onChange={(event) => setImportPrice(event.target.value)} /></label>
    <label className="category-general-converter-field"><span>Export compensation ({currency}/kWh)</span><input type="text" inputMode="decimal" value={exportPrice} onChange={(event) => setExportPrice(event.target.value)} /></label>
    <label className="category-general-converter-field"><span>Installed system cost ({currency})</span><input type="text" inputMode="decimal" value={cost} onChange={(event) => setCost(event.target.value)} /></label>
  </div></div><div aria-live="polite" className="category-general-converter-result paint-calculator-result">{!result ? <strong>Enter valid values to see the estimate.</strong> : <div className="conversion-table-wrap"><table className="conversion-table"><tbody><tr><td>Estimated annual production</td><td>{number(result.annualProductionKwh)} kWh</td></tr><tr><td>Used on site</td><td>{number(result.selfConsumedKwh)} kWh</td></tr><tr><td>Exported to grid</td><td>{number(result.exportedKwh)} kWh</td></tr><tr className="is-active"><td><strong>Estimated annual value</strong></td><td><strong>{money(result.annualValue)}</strong></td></tr><tr><td>Simple payback</td><td>{result.breakEvenYears === null ? "No payback estimate available" : `${new Intl.NumberFormat("en-US", { maximumFractionDigits: 1 }).format(result.breakEvenYears)} years`}</td></tr></tbody></table></div>}</div><p className="calculator-usage-hint"><strong>Important:</strong> this does not include financing, tax credits, maintenance, system degradation, battery costs or future tariff changes. Production depends on roof orientation, shade and local weather.</p></div>;
}
