"use client";

import { useMemo, useState } from "react";
import { calculateBiotNumber } from "../converter/dimensionlessNumbers";

function readNumber(value: string) { const result = Number(value.trim().replace(",", ".")); return Number.isFinite(result) ? result : Number.NaN; }
function format(value: number, digits = 4) { return new Intl.NumberFormat("en-US", { maximumFractionDigits: digits }).format(value); }

export default function EnglishBiotNumberCalculator() {
  const [coefficient, setCoefficient] = useState("25"); const [coefficientUnit, setCoefficientUnit] = useState<"wm2k" | "btuhrft2f">("wm2k");
  const [length, setLength] = useState("0.01"); const [lengthUnit, setLengthUnit] = useState<"m" | "mm" | "in" | "ft">("m");
  const [conductivity, setConductivity] = useState("15"); const [conductivityUnit, setConductivityUnit] = useState<"wmk" | "btuhrftf">("wmk");
  const result = useMemo(() => calculateBiotNumber({ convectionCoefficientWM2K: readNumber(coefficient) * (coefficientUnit === "btuhrft2f" ? 5.678263 : 1), characteristicLengthM: readNumber(length) * (lengthUnit === "mm" ? 0.001 : lengthUnit === "in" ? 0.0254 : lengthUnit === "ft" ? 0.3048 : 1), solidConductivityWMK: readNumber(conductivity) * (conductivityUnit === "btuhrftf" ? 1.730735 : 1) }), [coefficient, coefficientUnit, conductivity, conductivityUnit, length, lengthUnit]);
  const interpretation = result === null ? "" : result <= 0.1 ? "Bi ≤ 0.1: internal conduction resistance is often small enough for a lumped-capacitance first approximation." : "Bi > 0.1: internal temperature gradients may be significant; a spatial or transient-conduction model may be needed.";
  return <div className="category-general-converter"><div className="paint-calculator-grid"><label className="category-general-converter-field"><span>Convection coefficient (h)</span><div className="category-general-converter-input-row"><input type="text" inputMode="decimal" value={coefficient} onChange={(event) => setCoefficient(event.target.value)} /><select value={coefficientUnit} onChange={(event) => setCoefficientUnit(event.target.value as "wm2k" | "btuhrft2f")}><option value="wm2k">W/(m²·K)</option><option value="btuhrft2f">Btu/(h·ft²·°F)</option></select></div></label><label className="category-general-converter-field"><span>Characteristic length (L<sub>c</sub>)</span><div className="category-general-converter-input-row"><input type="text" inputMode="decimal" value={length} onChange={(event) => setLength(event.target.value)} /><select value={lengthUnit} onChange={(event) => setLengthUnit(event.target.value as "m" | "mm" | "in" | "ft")}><option value="m">m</option><option value="mm">mm</option><option value="in">in</option><option value="ft">ft</option></select></div></label><label className="category-general-converter-field"><span>Solid thermal conductivity (k<sub>s</sub>)</span><div className="category-general-converter-input-row"><input type="text" inputMode="decimal" value={conductivity} onChange={(event) => setConductivity(event.target.value)} /><select value={conductivityUnit} onChange={(event) => setConductivityUnit(event.target.value as "wmk" | "btuhrftf")}><option value="wmk">W/(m·K)</option><option value="btuhrftf">Btu/(h·ft·°F)</option></select></div></label></div><div aria-live="polite" className="category-general-converter-result paint-calculator-result">{result === null ? <strong>Enter valid positive heat-transfer and material values.</strong> : <div className="paint-calculator-result-grid"><div><span>Biot number (Bi)</span><strong>{format(result)}</strong><small>Dimensionless · Bi = hL<sub>c</sub>/k<sub>s</sub></small></div><div><span>Interpretation</span><strong>{interpretation}</strong><small>Use L<sub>c</sub> = volume / exposed surface area when that definition applies.</small></div></div>}</div><p className="calculator-usage-hint"><strong>Scope:</strong> the usual Bi ≤ 0.1 rule is a first screening criterion, not a design approval. Geometry, boundary condition, property variation and the actual definition of characteristic length still matter.</p></div>;
}
