"use client";

import { useMemo, useState } from "react";
import { calculateBitrateFromFileSize, calculateFileSizeFromBitrate } from "../converter/videoBitrateCalculator";

function number(value: string) { const parsed = Number(value.trim().replace(/,/g, ".")); return Number.isFinite(parsed) ? parsed : null; }
function format(value: number) { return new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 }).format(value); }

export default function EnglishVideoBitrateCalculator() {
  const [target, setTarget] = useState<"file-size" | "bitrate">("file-size"); const [bitrate, setBitrate] = useState("8"); const [fileSize, setFileSize] = useState("600"); const [duration, setDuration] = useState("600");
  const result = useMemo(() => { const seconds = number(duration); if (seconds === null) return null; return target === "file-size" ? (number(bitrate) === null ? null : calculateFileSizeFromBitrate(number(bitrate)!, seconds)) : (number(fileSize) === null ? null : calculateBitrateFromFileSize(number(fileSize)!, seconds)); }, [target, bitrate, fileSize, duration]);
  return <div className="category-general-converter"><div className="engineering-calculator-card"><div className="engineering-targets"><span>Calculate</span><div className="engineering-target-grid hydrostatic-target-grid"><button type="button" className={`engineering-target-button${target === "file-size" ? " is-active" : ""}`} onClick={() => setTarget("file-size")}>File size</button><button type="button" className={`engineering-target-button${target === "bitrate" ? " is-active" : ""}`} onClick={() => setTarget("bitrate")}>Video bitrate</button></div></div><div className="paint-calculator-grid">{target === "file-size" ? <label className="category-general-converter-field"><span>Video bitrate (Mbps)</span><input inputMode="decimal" type="text" value={bitrate} onChange={(event) => setBitrate(event.target.value)} /></label> : <label className="category-general-converter-field"><span>File size (MB)</span><input inputMode="decimal" type="text" value={fileSize} onChange={(event) => setFileSize(event.target.value)} /></label>}<label className="category-general-converter-field"><span>Duration (seconds)</span><input inputMode="decimal" type="text" value={duration} onChange={(event) => setDuration(event.target.value)} /></label></div></div><div aria-live="polite" className="category-general-converter-result paint-calculator-result">{result === null ? <strong>Enter valid positive values to calculate the estimate.</strong> : <strong>{target === "file-size" ? `Estimated file size: ${format(result)} MB` : `Estimated video bitrate: ${format(result)} Mbps`}</strong>}</div><p className="calculator-usage-hint">The estimate treats Mbps as decimal megabits per second and MB as decimal megabytes. Audio, containers, variable bitrate, metadata and encoder overhead can change the final file size.</p></div>;
}
