"use client";

import { useMemo, useState } from "react";
import { calculateHeatingSystemComparison } from "../converter/heatPumpVsBoilerPayback";
type Currency = "USD" | "EUR" | "GBP" | "CAD" | "AUD"; type GasUnit = "m3" | "therm";
const parse = (value: string) => { const number = Number(value.trim().replace(/,/g, ".")); return Number.isFinite(number) ? number : Number.NaN; };

export default function EnglishHeatPumpVsBoilerCalculator() {
  const [gasUnit, setGasUnit] = useState<GasUnit>("m3"); const [gasPrice, setGasPrice] = useState("0.60"); const [boilerEfficiency, setBoilerEfficiency] = useState("90"); const [electricityPrice, setElectricityPrice] = useState("0.18"); const [cop, setCop] = useState("3.2"); const [heatNeed, setHeatNeed] = useState("12000"); const [premium, setPremium] = useState("5000"); const [currency, setCurrency] = useState<Currency>("USD");
  const energyPerUnit = gasUnit === "m3" ? 10.6 : 29.3;
  const result = useMemo(() => calculateHeatingSystemComparison({ fuelCostPerKwhFuel: parse(gasPrice) / energyPerUnit, boilerEfficiencyPercent: parse(boilerEfficiency), electricityPricePerKwh: parse(electricityPrice), heatPumpCop: parse(cop), annualHeatNeedKwh: parse(heatNeed), initialCostDifference: parse(premium) }), [gasPrice, energyPerUnit, boilerEfficiency, electricityPrice, cop, heatNeed, premium]);
  const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 0 }).format(value); const rate = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 3 }).format(value);
  return <div className="category-general-converter"><div className="engineering-calculator-card"><div className="paint-calculator-grid">
    <label className="category-general-converter-field"><span>Display currency</span><select value={currency} onChange={(event) => setCurrency(event.target.value as Currency)}><option value="USD">USD ($)</option><option value="EUR">EUR (€)</option><option value="GBP">GBP (£)</option><option value="CAD">CAD (CA$)</option><option value="AUD">AUD (A$)</option></select></label>
    <label className="category-general-converter-field"><span>Gas billing unit</span><select value={gasUnit} onChange={(event) => setGasUnit(event.target.value as GasUnit)}><option value="m3">Cubic metre (m³)</option><option value="therm">Therm</option></select></label>
    <label className="category-general-converter-field"><span>Gas price ({currency}/{gasUnit === "m3" ? "m³" : "therm"})</span><input type="text" inputMode="decimal" value={gasPrice} onChange={(event) => setGasPrice(event.target.value)} /></label>
    <label className="category-general-converter-field"><span>Boiler efficiency (%)</span><input type="text" inputMode="decimal" value={boilerEfficiency} onChange={(event) => setBoilerEfficiency(event.target.value)} /></label>
    <label className="category-general-converter-field"><span>Electricity price ({currency}/kWh)</span><input type="text" inputMode="decimal" value={electricityPrice} onChange={(event) => setElectricityPrice(event.target.value)} /></label>
    <label className="category-general-converter-field"><span>Seasonal heat-pump COP</span><input type="text" inputMode="decimal" value={cop} onChange={(event) => setCop(event.target.value)} /></label>
    <label className="category-general-converter-field"><span>Annual useful heat need (kWh)</span><input type="text" inputMode="decimal" value={heatNeed} onChange={(event) => setHeatNeed(event.target.value)} /></label>
    <label className="category-general-converter-field"><span>Heat-pump installation premium ({currency})</span><input type="text" inputMode="decimal" value={premium} onChange={(event) => setPremium(event.target.value)} /></label>
  </div></div><div aria-live="polite" className="category-general-converter-result paint-calculator-result">{!result ? <strong>Enter valid values to see the annual comparison.</strong> : <div className="conversion-table-wrap"><table className="conversion-table"><tbody><tr><td>Boiler heat cost</td><td>{rate(result.fuelCostPerKwhHeat)}/kWh</td></tr><tr><td>Heat-pump heat cost</td><td>{rate(result.heatPumpCostPerKwhHeat)}/kWh</td></tr><tr><td>Annual boiler cost</td><td>{money(result.annualFuelCost)}</td></tr><tr><td>Annual heat-pump cost</td><td>{money(result.annualHeatPumpCost)}</td></tr><tr className="is-active"><td><strong>Annual operating difference</strong></td><td><strong>{money(Math.abs(result.annualSaving))} {result.annualSaving >= 0 ? "less with the heat pump" : "more with the heat pump"}</strong></td></tr><tr><td>Simple payback</td><td>{result.breakEvenYears === null ? "No payback from these operating costs" : `${new Intl.NumberFormat("en-US", { maximumFractionDigits: 1 }).format(result.breakEvenYears)} years`}</td></tr></tbody></table></div>}</div><p className="calculator-usage-hint"><strong>Important:</strong> use a seasonal COP rather than a best-case rating. Gas energy content, tariff structure, equipment sizing, maintenance and extreme-weather performance can change the real result.</p></div>;
}
