"use client";

import { useMemo, useState } from "react";
import { calculateProportion, type ProportionTarget } from "../converter/ratioProportionCalculator";

function number(value: string) { const parsed = Number(value.trim().replace(/,/g, ".")); return Number.isFinite(parsed) ? parsed : Number.NaN; }
function format(value: number) { return new Intl.NumberFormat("en-US", { maximumFractionDigits: 8 }).format(value); }

export default function EnglishRatioProportionCalculator() {
  const [target, setTarget] = useState<ProportionTarget>("d"); const [values, setValues] = useState({ a: "2", b: "4", c: "3", d: "6" });
  const set = (key: ProportionTarget) => (value: string) => setValues((current) => ({ ...current, [key]: value }));
  const result = useMemo(() => calculateProportion({ target, a: number(values.a), b: number(values.b), c: number(values.c), d: number(values.d) }), [target, values]);
  const known = result ? { a: result.a, b: result.b, c: result.c, d: result.d } : null;
  const solution = result ? target === "a" ? `a = (b x c) / d = (${format(result.b)} x ${format(result.c)}) / ${format(result.d)} = ${format(result.a)}` : target === "b" ? `b = (a x d) / c = (${format(result.a)} x ${format(result.d)}) / ${format(result.c)} = ${format(result.b)}` : target === "c" ? `c = (a x d) / b = (${format(result.a)} x ${format(result.d)}) / ${format(result.b)} = ${format(result.c)}` : `d = (b x c) / a = (${format(result.b)} x ${format(result.c)}) / ${format(result.a)} = ${format(result.d)}` : null;
  return <div className="category-general-converter"><div className="engineering-calculator-card"><p className="calculator-usage-hint">For a/b = c/d, choose the unknown and enter the other three values. The calculator uses cross multiplication.</p><div className="engineering-targets"><span>Find</span><div className="engineering-target-grid hydrostatic-target-grid">{(["a", "b", "c", "d"] as ProportionTarget[]).map((item) => <button key={item} type="button" className={`engineering-target-button${target === item ? " is-active" : ""}`} onClick={() => setTarget(item)}>{item}</button>)}</div></div><div className="fraction-pair"><div className="fraction-input-block">{target === "a" ? <span className="fraction-unknown-slot">?</span> : <input aria-label="a" inputMode="decimal" type="text" value={values.a} onChange={(event) => set("a")(event.target.value)} />}<div className="fraction-divider-line" aria-hidden="true" />{target === "b" ? <span className="fraction-unknown-slot">?</span> : <input aria-label="b" inputMode="decimal" type="text" value={values.b} onChange={(event) => set("b")(event.target.value)} />}</div><span className="fraction-operation-symbol" aria-hidden="true">=</span><div className="fraction-input-block">{target === "c" ? <span className="fraction-unknown-slot">?</span> : <input aria-label="c" inputMode="decimal" type="text" value={values.c} onChange={(event) => set("c")(event.target.value)} />}<div className="fraction-divider-line" aria-hidden="true" />{target === "d" ? <span className="fraction-unknown-slot">?</span> : <input aria-label="d" inputMode="decimal" type="text" value={values.d} onChange={(event) => set("d")(event.target.value)} />}</div></div></div><div aria-live="polite" className="category-general-converter-result paint-calculator-result">{!result ? <strong>Enter valid values for the three known terms. A divisor cannot be zero.</strong> : <div className="paint-calculator-result-grid"><div><span>{target}</span><strong>{format(result[target])}</strong></div><div><span>Completed proportion</span><strong>{format(result.a)} / {format(result.b)} = {format(result.c)} / {format(result.d)}</strong></div></div>}</div>{known && solution && <div className="calculator-steps"><h3>Show the steps</h3><div className="calculator-step"><p className="calculator-step-title">1. Cross multiply</p><p className="calculator-step-line">a x d = b x c; {format(known.a)} x {format(known.d)} = {format(known.b)} x {format(known.c)}.</p></div><div className="calculator-step"><p className="calculator-step-title">2. Isolate the unknown</p><p className="calculator-step-line">{solution}</p></div></div>}</div>;
}
