"use client";

import { useMemo, useState } from "react";

type Shape = "rectangle" | "circle";
type LengthUnit = "mm" | "in";

function number(value: string) { const parsed = Number(value.trim().replace(",", ".")); return Number.isFinite(parsed) ? parsed : null; }
function format(value: number, digits = 3) { return new Intl.NumberFormat("en-US", { maximumFractionDigits: digits }).format(value); }

export default function EnglishSectionPropertiesCalculator() {
  const [shape, setShape] = useState<Shape>("rectangle"); const [width, setWidth] = useState("50"); const [depth, setDepth] = useState("100"); const [diameter, setDiameter] = useState("50"); const [unit, setUnit] = useState<LengthUnit>("mm");
  const result = useMemo(() => {
    const factor = unit === "in" ? 25.4 : 1;
    if (shape === "rectangle") { const bInput = number(width), hInput = number(depth); if (bInput === null || hInput === null || bInput <= 0 || hInput <= 0) return null; const b = bInput * factor, h = hInput * factor; const area = b * h, inertiaStrong = b * h ** 3 / 12, inertiaWeak = h * b ** 3 / 12; return { area, inertiaStrong, inertiaWeak, sectionStrong: inertiaStrong / (h / 2), sectionWeak: inertiaWeak / (b / 2), polarJ: inertiaStrong + inertiaWeak }; }
    const dInput = number(diameter); if (dInput === null || dInput <= 0) return null; const d = dInput * factor, area = Math.PI * d ** 2 / 4, inertia = Math.PI * d ** 4 / 64; return { area, inertiaStrong: inertia, inertiaWeak: inertia, sectionStrong: inertia / (d / 2), sectionWeak: inertia / (d / 2), polarJ: Math.PI * d ** 4 / 32 };
  }, [depth, diameter, shape, unit, width]);
  return <div className="category-general-converter"><div className="engineering-calculator-card"><div className="engineering-targets"><span>Section shape</span><div className="engineering-target-grid hydrostatic-target-grid"><button type="button" className={`engineering-target-button${shape === "rectangle" ? " is-active" : ""}`} onClick={() => setShape("rectangle")}>Rectangle</button><button type="button" className={`engineering-target-button${shape === "circle" ? " is-active" : ""}`} onClick={() => setShape("circle")}>Solid circle</button></div></div><div className="paint-calculator-grid">{shape === "rectangle" ? <><label className="category-general-converter-field"><span>Width (b)</span><div className="category-general-converter-input-row"><input type="text" inputMode="decimal" value={width} onChange={(event) => setWidth(event.target.value)} /><select value={unit} onChange={(event) => setUnit(event.target.value as LengthUnit)}><option value="mm">mm</option><option value="in">in</option></select></div></label><label className="category-general-converter-field"><span>Depth (h)</span><div className="category-general-converter-input-row"><input type="text" inputMode="decimal" value={depth} onChange={(event) => setDepth(event.target.value)} /><span>{unit}</span></div></label></> : <label className="category-general-converter-field"><span>Diameter (d)</span><div className="category-general-converter-input-row"><input type="text" inputMode="decimal" value={diameter} onChange={(event) => setDiameter(event.target.value)} /><select value={unit} onChange={(event) => setUnit(event.target.value as LengthUnit)}><option value="mm">mm</option><option value="in">in</option></select></div></label>}</div></div><div aria-live="polite" className="category-general-converter-result paint-calculator-result">{!result ? <strong>Enter positive section dimensions.</strong> : <div className="paint-calculator-result-grid"><div><span>Area (A)</span><strong>{format(result.area)} mm²</strong><small>{format(result.area / 645.16, 4)} in²</small></div><div><span>Strong-axis I</span><strong>{format(result.inertiaStrong)} mm⁴</strong><small>{format(result.inertiaStrong / 25.4 ** 4, 4)} in⁴</small></div><div><span>Weak-axis I</span><strong>{format(result.inertiaWeak)} mm⁴</strong><small>{format(result.inertiaWeak / 25.4 ** 4, 4)} in⁴</small></div><div><span>Strong-axis section modulus (S)</span><strong>{format(result.sectionStrong)} mm³</strong><small>{format(result.sectionStrong / 25.4 ** 3, 4)} in³</small></div><div><span>Polar moment (J)</span><strong>{format(result.polarJ)} mm⁴</strong><small>Centroidal axes</small></div></div>}</div><p className="calculator-usage-hint"><strong>Scope:</strong> centroidal properties for an ideal solid rectangle or circle only. Built-up, hollow, composite, rotated or asymmetric sections need their own section-property method.</p></div>;
}
