"use client";

import { useMemo, useState } from "react";
import { calculatePixelSize, type PixelSolveFor, type SizeUnit } from "../converter/pixelCalculator";

function number(value: string) { const parsed = Number(value.trim().replace(/,/g, ".")); return Number.isFinite(parsed) ? parsed : Number.NaN; }
function format(value: number, digits = 2) { return new Intl.NumberFormat("en-US", { maximumFractionDigits: digits }).format(value); }

export default function EnglishPixelCalculator() {
  const [solveFor, setSolveFor] = useState<PixelSolveFor>("pixels"); const [pixels, setPixels] = useState("1000"); const [size, setSize] = useState("10"); const [unit, setUnit] = useState<SizeUnit>("cm"); const [dpi, setDpi] = useState("300");
  const result = useMemo(() => calculatePixelSize({ solveFor, pixels: number(pixels), sizeValue: number(size), sizeUnit: unit, dpi: number(dpi) }), [solveFor, pixels, size, unit, dpi]);
  return <div className="category-general-converter"><div className="engineering-calculator-card"><label className="category-general-converter-field"><span>Calculate</span><select value={solveFor} onChange={(event) => setSolveFor(event.target.value as PixelSolveFor)}><option value="pixels">Pixel count</option><option value="size">Physical size</option><option value="dpi">DPI / PPI</option></select></label><div className="paint-calculator-grid">{solveFor !== "pixels" && <label className="category-general-converter-field"><span>Pixel count</span><input inputMode="decimal" type="text" value={pixels} onChange={(event) => setPixels(event.target.value)} /></label>}{solveFor !== "size" && <label className="category-general-converter-field"><span>Physical size</span><div className="paint-calculator-checkbox-row"><input inputMode="decimal" type="text" value={size} onChange={(event) => setSize(event.target.value)} /><select value={unit} onChange={(event) => setUnit(event.target.value as SizeUnit)}><option value="cm">cm</option><option value="inch">in</option></select></div></label>}{solveFor !== "dpi" && <label className="category-general-converter-field"><span>DPI / PPI</span><input inputMode="decimal" type="text" value={dpi} onChange={(event) => setDpi(event.target.value)} list="english-dpi-presets" /><datalist id="english-dpi-presets">{[72, 96, 150, 300, 600].map((preset) => <option key={preset} value={preset} />)}</datalist></label>}</div></div><div aria-live="polite" className="category-general-converter-result paint-calculator-result">{!result ? <strong>Enter valid positive values to calculate the missing measurement.</strong> : <div className="paint-calculator-result-grid"><div><span>Pixel count</span><strong>{format(result.pixels, 0)} px</strong></div><div><span>Physical size</span><strong>{format(result.sizeCm)} cm / {format(result.sizeInch)} in</strong></div><div><span>DPI / PPI</span><strong>{format(result.dpi)}</strong></div></div>}</div><p className="calculator-usage-hint">Formula: pixels = physical size in inches x DPI. DPI/PPI expresses density; it does not change the pixels already contained in a digital image.</p></div>;
}
