"use client";

import { useMemo, useState } from "react";
import { calculateInsulationPaybackEstimate } from "../converter/insulationPayback";

const walls = [{ id: "brick", label: "Brick", conductivity: 0.4 }, { id: "concrete", label: "Concrete", conductivity: 1.4 }, { id: "wood", label: "Wood", conductivity: 0.13 }];
const insulation = [{ id: "glass-wool", label: "Glass wool", conductivity: 0.035 }, { id: "rock-wool", label: "Rock wool", conductivity: 0.04 }, { id: "eps", label: "EPS", conductivity: 0.038 }, { id: "xps", label: "XPS", conductivity: 0.035 }];
type Currency = "USD" | "EUR" | "GBP" | "CAD" | "AUD";
const parse = (value: string) => { const number = Number(value.trim().replace(/,/g, ".")); return Number.isFinite(number) ? number : Number.NaN; };

export default function EnglishInsulationPaybackCalculator() {
  const [area, setArea] = useState("100"); const [wallId, setWallId] = useState("brick"); const [wallThickness, setWallThickness] = useState("20"); const [insulationId, setInsulationId] = useState("rock-wool"); const [insulationThickness, setInsulationThickness] = useState("10"); const [temperatureDifference, setTemperatureDifference] = useState("12"); const [heatingDays, setHeatingDays] = useState("180"); const [energyPrice, setEnergyPrice] = useState("0.12"); const [cost, setCost] = useState("5000"); const [currency, setCurrency] = useState<Currency>("USD");
  const wall = walls.find((item) => item.id === wallId) ?? walls[0]; const insulationMaterial = insulation.find((item) => item.id === insulationId) ?? insulation[0];
  const result = useMemo(() => calculateInsulationPaybackEstimate({ wallAreaM2: parse(area), existingWallThicknessCm: parse(wallThickness), existingWallConductivityWmK: wall.conductivity, insulationThicknessCm: parse(insulationThickness), insulationConductivityWmK: insulationMaterial.conductivity, avgTempDifferenceC: parse(temperatureDifference), heatingDaysPerYear: parse(heatingDays), heatingEnergyPricePerKwh: parse(energyPrice), insulationCost: parse(cost) }), [area, wallThickness, wall.conductivity, insulationThickness, insulationMaterial.conductivity, temperatureDifference, heatingDays, energyPrice, cost]);
  const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 0 }).format(value); const number = (value: number) => new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(value);
  return <div className="category-general-converter"><div className="engineering-calculator-card"><div className="paint-calculator-grid">
    <label className="category-general-converter-field"><span>Wall area (m²)</span><input type="text" inputMode="decimal" value={area} onChange={(event) => setArea(event.target.value)} /></label>
    <label className="category-general-converter-field"><span>Existing wall material</span><select value={wallId} onChange={(event) => setWallId(event.target.value)}>{walls.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label>
    <label className="category-general-converter-field"><span>Existing wall thickness (cm)</span><input type="text" inputMode="decimal" value={wallThickness} onChange={(event) => setWallThickness(event.target.value)} /></label>
    <label className="category-general-converter-field"><span>Insulation material</span><select value={insulationId} onChange={(event) => setInsulationId(event.target.value)}>{insulation.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label>
    <label className="category-general-converter-field"><span>Insulation thickness (cm)</span><input type="text" inputMode="decimal" value={insulationThickness} onChange={(event) => setInsulationThickness(event.target.value)} /></label>
    <label className="category-general-converter-field"><span>Average indoor-outdoor difference (°C)</span><input type="text" inputMode="decimal" value={temperatureDifference} onChange={(event) => setTemperatureDifference(event.target.value)} /></label>
    <label className="category-general-converter-field"><span>Heating days per year</span><input type="text" inputMode="decimal" value={heatingDays} onChange={(event) => setHeatingDays(event.target.value)} /></label>
    <label className="category-general-converter-field"><span>Display currency</span><select value={currency} onChange={(event) => setCurrency(event.target.value as Currency)}><option value="USD">USD ($)</option><option value="EUR">EUR (€)</option><option value="GBP">GBP (£)</option><option value="CAD">CAD (CA$)</option><option value="AUD">AUD (A$)</option></select></label>
    <label className="category-general-converter-field"><span>Heating energy cost ({currency}/kWh)</span><input type="text" inputMode="decimal" value={energyPrice} onChange={(event) => setEnergyPrice(event.target.value)} /></label>
    <label className="category-general-converter-field"><span>Installed insulation cost ({currency})</span><input type="text" inputMode="decimal" value={cost} onChange={(event) => setCost(event.target.value)} /></label>
  </div></div><div aria-live="polite" className="category-general-converter-result paint-calculator-result">{!result ? <strong>Enter valid positive values to see the estimate.</strong> : <div className="conversion-table-wrap"><table className="conversion-table"><tbody><tr><td>Annual wall heat loss before</td><td>{number(result.annualHeatLossKwhBefore)} kWh</td></tr><tr><td>Annual wall heat loss after</td><td>{number(result.annualHeatLossKwhAfter)} kWh</td></tr><tr className="is-active"><td><strong>Estimated annual saving</strong></td><td><strong>{number(result.annualSavingsKwh)} kWh · {money(result.annualCostSaving)}</strong></td></tr><tr><td>Simple payback</td><td>{result.breakEvenYears === null ? "No payback estimate available" : `${new Intl.NumberFormat("en-US", { maximumFractionDigits: 1 }).format(result.breakEvenYears)} years`}</td></tr></tbody></table></div>}</div><p className="calculator-usage-hint"><strong>Important:</strong> this is a wall-conduction estimate only. It excludes windows, roofs, floors, air leakage, thermal bridges and cooling effects; use it for early planning, not a final building specification.</p></div>;
}
