"use client";

import { useMemo, useState } from "react";
import { calculateFourierNumber } from "../converter/dimensionlessNumbers";

function readNumber(value: string) { const result = Number(value.trim().replace(",", ".")); return Number.isFinite(result) ? result : Number.NaN; }
function format(value: number, digits = 4) { return new Intl.NumberFormat("en-US", { maximumFractionDigits: digits }).format(value); }

export default function EnglishFourierNumberCalculator() {
  const [diffusivity, setDiffusivity] = useState("1.2e-5"); const [diffusivityUnit, setDiffusivityUnit] = useState<"m2s" | "mm2s" | "ft2s">("m2s");
  const [time, setTime] = useState("60"); const [timeUnit, setTimeUnit] = useState<"s" | "min" | "h">("s");
  const [length, setLength] = useState("0.01"); const [lengthUnit, setLengthUnit] = useState<"m" | "mm" | "in" | "ft">("m");
  const result = useMemo(() => calculateFourierNumber({ thermalDiffusivityM2S: readNumber(diffusivity) * (diffusivityUnit === "mm2s" ? 0.000001 : diffusivityUnit === "ft2s" ? 0.09290304 : 1), timeS: readNumber(time) * (timeUnit === "min" ? 60 : timeUnit === "h" ? 3600 : 1), characteristicLengthM: readNumber(length) * (lengthUnit === "mm" ? 0.001 : lengthUnit === "in" ? 0.0254 : lengthUnit === "ft" ? 0.3048 : 1) }), [diffusivity, diffusivityUnit, length, lengthUnit, time, timeUnit]);
  const interpretation = result === null ? "" : result < 0.1 ? "Small Fourier number: diffusion has progressed a short distance relative to the chosen characteristic length." : result < 1 ? "Intermediate Fourier number: transient temperature gradients are likely still important." : "Larger Fourier number: diffusion has had more time relative to the chosen characteristic length.";
  return <div className="category-general-converter"><div className="paint-calculator-grid"><label className="category-general-converter-field"><span>Thermal diffusivity (α)</span><div className="category-general-converter-input-row"><input type="text" inputMode="decimal" value={diffusivity} onChange={(event) => setDiffusivity(event.target.value)} /><select value={diffusivityUnit} onChange={(event) => setDiffusivityUnit(event.target.value as "m2s" | "mm2s" | "ft2s")}><option value="m2s">m²/s</option><option value="mm2s">mm²/s</option><option value="ft2s">ft²/s</option></select></div></label><label className="category-general-converter-field"><span>Elapsed time (t)</span><div className="category-general-converter-input-row"><input type="text" inputMode="decimal" value={time} onChange={(event) => setTime(event.target.value)} /><select value={timeUnit} onChange={(event) => setTimeUnit(event.target.value as "s" | "min" | "h")}><option value="s">s</option><option value="min">min</option><option value="h">h</option></select></div></label><label className="category-general-converter-field"><span>Characteristic length (L)</span><div className="category-general-converter-input-row"><input type="text" inputMode="decimal" value={length} onChange={(event) => setLength(event.target.value)} /><select value={lengthUnit} onChange={(event) => setLengthUnit(event.target.value as "m" | "mm" | "in" | "ft")}><option value="m">m</option><option value="mm">mm</option><option value="in">in</option><option value="ft">ft</option></select></div></label></div><div aria-live="polite" className="category-general-converter-result paint-calculator-result">{result === null ? <strong>Enter valid positive diffusivity, time and length values.</strong> : <div className="paint-calculator-result-grid"><div><span>Fourier number (Fo)</span><strong>{format(result)}</strong><small>Dimensionless · Fo = αt/L²</small></div><div><span>Interpretation</span><strong>{interpretation}</strong><small>Its meaning depends on the geometry and transient-conduction solution used next.</small></div></div>}</div><p className="calculator-usage-hint"><strong>Scope:</strong> Fourier number is a time-scale ratio. It does not return temperature, heat loss or heating time on its own, and it does not replace the geometry-specific transient solution or boundary condition.</p></div>;
}
