import {
  Activity,
  AirVent,
  AlertTriangle,
  Antenna,
  Anvil,
  Aperture,
  ArrowLeftRight,
  AudioWaveform,
  Baby,
  Battery,
  BatteryCharging,
  Binary,
  Bolt,
  Brain,
  Blocks,
  BookOpen,
  Building2,
  BookOpenCheck,
  Cable,
  DollarSign,
  Euro,
  PoundSterling,
  Lightbulb,
  PiggyBank,
  Sun,
  ThermometerSun,
  Cake,
  CalendarX2,
  Camera,
  Car,
  ChefHat,
  Anchor,
  BarChart3,
  CircleGauge,
  CircuitBoard,
  Clapperboard,
  Cylinder,
  GitCompare,
  ClipboardList,
  Clock,
  CloudRain,
  Code2,
  Cog,
  Coins,
  Construction,
  Cpu,
  Disc,
  DraftingCompass,
  Dumbbell,
  Expand,
  MoveVertical,
  Paintbrush2,
  Droplet,
  Droplets,
  FlaskConical,
  Flame,
  Footprints,
  Focus,
  Fuel,
  Gauge,
  Gem,
  GlassWater,
  Globe,
  GraduationCap,
  Grid3x3,
  Hammer,
  Heart,
  HeartPulse,
  Layers,
  Leaf,
  Martini,
  Megaphone,
  MonitorSmartphone,
  MoonStar,
  Music2,
  Package,
  PackageSearch,
  PaintRoller,
  Palette,
  PawPrint,
  Pill,
  Pipette,
  Plane,
  PlugZap,
  Puzzle,
  Radio,
  ReceiptTurkishLira,
  Navigation,
  Rocket,
  Rows3,
  RotateCw,
  Ruler,
  Scale,
  Scissors,
  Search,
  Shapes,
  Snowflake,
  Sprout,
  Stethoscope,
  Shirt,
  ShieldCheck,
  Sigma,
  Sparkles,
  Syringe,
  TestTube,
  Thermometer,
  Timer,
  Tractor,
  TreeDeciduous,
  TrendingDown,
  Trophy,
  Truck,
  Video,
  Wallpaper,
  Waves,
  Wheat,
  Wind,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const iconMap = {
  length: Ruler,
  mass: Scale,
  pressure: Gauge,
  temperature: Thermometer,
  energy: Zap,
  speed: Gauge,
  pressureForceArea: CircleGauge,
  hydrostaticPressure: Waves,
  unitGuide: BookOpen,
  allConversions: ArrowLeftRight,
  search: Search,
  flowRate: Droplets,
  density: Layers,
  force: Anvil,
  torque: RotateCw,
  momentum: Rocket,
  viscosity: Droplet,
  resistance: CircuitBoard,
  capacitance: Battery,
  inductance: Cable,
  charge: Sparkles,
  shoeSize: Footprints,
  kitchenMeasures: ChefHat,
  recipe: ClipboardList,
  ringSize: Gem,
  embed: Puzzle,
  paintCalculator: PaintRoller,
  tileCalculator: Grid3x3,
  brickCalculator: Blocks,
  dateCalculator: Cake,
  vatCalculator: ReceiptTurkishLira,
  bmiCalculator: Activity,
  pregnancyCalculator: Baby,
  acCapacityCalculator: AirVent,
  electricityConsumptionCalculator: PlugZap,
  sleepCalculator: MoonStar,
  paceCalculator: Timer,
  fuelConsumptionCalculator: Fuel,
  laminateCalculator: Rows3,
  wallpaperCalculator: Wallpaper,
  movingBoxCalculator: Package,
  naturalGasCalculator: Flame,
  evChargingCalculator: BatteryCharging,
  numberBaseCalculator: Binary,
  chemistryCalculator: FlaskConical,
  mathCalculator: Sigma,
  geometryCalculator: Shapes,
  concreteCalculator: Construction,
  attendanceCalculator: CalendarX2,
  plasterCalculator: Paintbrush2,
  stairCalculator: MoveVertical,
  hasCalculator: Coins,
  excavationCalculator: Truck,
  insulationCalculator: ShieldCheck,
  jewelerHub: Gem,
  electricianHub: Zap,
  builderHub: Construction,
  automotiveHub: Car,
  chefHub: ChefHat,
  dietitianHub: HeartPulse,
  bodyFatCalculator: Activity,
  idealWeightCalculator: Scale,
  terziHub: Scissors,
  clothingSizeCalculator: Shirt,
  realtorHub: Building2,
  commissionCalculator: ReceiptTurkishLira,
  pilotHub: Plane,
  kaptanHub: Anchor,
  transitTimeCalculator: Navigation,
  densityAltitudeCalculator: Thermometer,
  crosswindCalculator: Wind,
  descentRateCalculator: TrendingDown,
  weightBalanceCalculator: Scale,
  greatCircleCalculator: Globe,
  doctorHub: Stethoscope,
  bsaCalculator: Activity,
  creatinineClearanceCalculator: Droplet,
  ivDripRateCalculator: Droplets,
  gcsCalculator: Brain,
  apgarCalculator: Baby,
  cha2ds2Calculator: Heart,
  wellsScoreCalculator: ClipboardList,
  qsofaCalculator: AlertTriangle,
  sofaCalculator: Activity,
  meldCalculator: FlaskConical,
  morseFallScaleCalculator: Footprints,
  bradenScaleCalculator: Layers,
  nakliyeciHub: Truck,
  cbmCalculator: PackageSearch,
  tesisatciHub: Wrench,
  pipeFlowCalculator: Waves,
  pressureLossCalculator: Gauge,
  muhasebeciHub: ClipboardList,
  amortismanCalculator: TrendingDown,
  marangozHub: Hammer,
  keresteCalculator: TreeDeciduous,
  grafikTasarimciHub: Palette,
  pixelCalculator: Grid3x3,
  tireSizeCalculator: Gauge,
  unitDisaster: AlertTriangle,
  spaceDisaster: Rocket,
  yazilimciHub: Code2,
  unixTimestampCalculator: Clock,
  colorCodeCalculator: Pipette,
  muzisyenHub: Music2,
  bpmCalculator: AudioWaveform,
  veterinerHub: PawPrint,
  vetDoseCalculator: Syringe,
  fotografciHub: Camera,
  exposureCalculator: Aperture,
  focalLengthCalculator: Focus,
  antrenorHub: Dumbbell,
  oneRepMaxCalculator: Trophy,
  ciftciHub: Tractor,
  fertilizerCalculator: Leaf,
  seedRateCalculator: Wheat,
  eczaciHub: Pill,
  alcoholDilutionCalculator: TestTube,
  barmenHub: Martini,
  barVolumeCalculator: GlassWater,
  abvCalculator: Wine,
  kaynakciHub: Flame,
  weldingCurrentCalculator: Zap,
  heatInputCalculator: Thermometer,
  cncHub: Cog,
  cuttingSpeedCalculator: Disc,
  peyzajHub: Sprout,
  irrigationCalculator: CloudRain,
  havuzHub: Waves,
  poolVolumeCalculator: Waves,
  chlorineDoseCalculator: Droplet,
  amatorTelsizHub: Radio,
  antennaCalculator: Antenna,
  bilgisayarDonanimciHub: MonitorSmartphone,
  psuCalculator: Cpu,
  videoEditorHub: Clapperboard,
  videoBitrateCalculator: Video,
  dijitalPazarlamaciHub: Megaphone,
  adMetricsCalculator: BarChart3,
  klimaSogutmaHub: Snowflake,
  superheatSubcoolingCalculator: Thermometer,
  materialWeightCalculator: Scale,
  awgConverter: Cable,
  thermalExpansionCalculator: Expand,
  elongationCalculator: Ruler,
  boltTorqueCalculator: Bolt,
  elementMeltingBoilingCalculator: Thermometer,
  hardnessConversionCalculator: Gauge,
  pipeNominalSizeCalculator: Cylinder,
  evVsIceComparisonCalculator: GitCompare,
  insulationPaybackCalculator: PiggyBank,
  ledSavingsCalculator: Lightbulb,
  heatingCostComparisonCalculator: ThermometerSun,
  solarPanelPaybackCalculator: Sun,
  currencyConverterCalculator: Coins,
  currencyUsd: DollarSign,
  currencyEur: Euro,
  currencyGbp: PoundSterling,
  mimarHub: DraftingCompass,
  zoningCalculator: Building2,
  ogretmenHub: GraduationCap,
  letterGradeCalculator: BookOpenCheck,
} as const satisfies Record<string, LucideIcon>;

export type SiteIconName = keyof typeof iconMap;

const categoryIconMap = {
  uzunluk: "length",
  length: "length",
  kutle: "mass",
  mass: "mass",
  basinc: "pressure",
  pressure: "pressure",
  sicaklik: "temperature",
  temperature: "temperature",
  enerji: "energy",
  energy: "energy",
  hiz: "speed",
  speed: "speed",
  debi: "flowRate",
  yogunluk: "density",
  kuvvet: "force",
  tork: "torque",
  momentum: "momentum",
  viskozite_dinamik: "viscosity",
  elektrik: "resistance",
  elektrik_direnc: "resistance",
  kapasitans: "capacitance",
  enduktans: "inductance",
  elektrik_yuk: "charge",
} as const satisfies Record<string, SiteIconName>;

const calculatorIconMap = {
  "isi-enerjisi": "energy",
  "heat-energy": "energy",
  "isi-iletimi": "temperature",
  "heat-conduction": "temperature",
  "reynolds-sayisi": "speed",
  "reynolds-number": "speed",
  "basinc-kuvvet-alan": "pressureForceArea",
  "pressure-force-area": "pressureForceArea",
  "hidrostatik-basinc": "hydrostaticPressure",
  "hydrostatic-pressure": "hydrostaticPressure",
  "kw-to-amper-hesaplama": "energy",
  "amper-to-kw-hesaplama": "energy",
  "gerilim-dusumu-hesaplama": "energy",
  "kablo-kesiti-hesaplama": "energy",
  "motor-akimi-hesaplama": "energy",
  "ohm-yasasi": "resistance",
  "ohms-law": "resistance",
} as const satisfies Record<string, SiteIconName>;

export function getCategoryIconName(category: string) {
  return (
    categoryIconMap[category as keyof typeof categoryIconMap] ??
    "allConversions"
  );
}

export function getCalculatorIconName(slug: string) {
  return (
    calculatorIconMap[slug as keyof typeof calculatorIconMap] ??
    "allConversions"
  );
}

export function DecorativeIcon({
  name,
  size = 20,
  className,
}: {
  name: SiteIconName;
  size?: number;
  className?: string;
}) {
  const Icon = iconMap[name];

  return (
    <Icon
      aria-hidden="true"
      className={className}
      size={size}
      strokeWidth={1.7}
    />
  );
}
