// Deutsche Laendernamen, Hauptstaedte und Amtssprachen fuer /de/laender.
// Quellen: world-countries (mledoze/countries, ODbL 1.0), Hauptstadtnamen nach CLDR und Auswaertigem Amt.
// Bu veri dosyasi ODbL 1.0 lisansi altindadir.
export type WorldCountryDe = {
  id: string;
  name: string;
  capital: string;
  note: string | null;
  languages: string[];
};

export const worldCountriesDe: Record<string, WorldCountryDe> = {
  AFG: {
    id: "afghanistan",
    name: "Afghanistan",
    capital: "Kabul",
    note: null,
    languages: ["Dari", "Paschtu", "Turkmenisch"],
  },
  AGO: {
    id: "angola",
    name: "Angola",
    capital: "Luanda",
    note: null,
    languages: ["Portugiesisch"],
  },
  ALB: {
    id: "albanien",
    name: "Albanien",
    capital: "Tirana",
    note: null,
    languages: ["Albanisch"],
  },
  AND: {
    id: "andorra",
    name: "Andorra",
    capital: "Andorra la Vella",
    note: null,
    languages: ["Katalanisch"],
  },
  ARE: {
    id: "vereinigte-arabische-emirate",
    name: "Vereinigte Arabische Emirate",
    capital: "Abu Dhabi",
    note: null,
    languages: ["Arabisch"],
  },
  ARG: {
    id: "argentinien",
    name: "Argentinien",
    capital: "Buenos Aires",
    note: null,
    languages: ["Guaraní", "Spanisch"],
  },
  ARM: {
    id: "armenien",
    name: "Armenien",
    capital: "Eriwan",
    note: null,
    languages: ["Armenisch"],
  },
  ATG: {
    id: "antigua-und-barbuda",
    name: "Antigua und Barbuda",
    capital: "St. John's",
    note: null,
    languages: ["Englisch"],
  },
  AUS: {
    id: "australien",
    name: "Australien",
    capital: "Canberra",
    note: null,
    languages: ["Englisch"],
  },
  AUT: {
    id: "oesterreich",
    name: "Österreich",
    capital: "Wien",
    note: null,
    languages: ["Bairisch"],
  },
  AZE: {
    id: "aserbaidschan",
    name: "Aserbaidschan",
    capital: "Baku",
    note: null,
    languages: ["Aserbaidschanisch", "Russisch"],
  },
  BDI: {
    id: "burundi",
    name: "Burundi",
    capital: "Gitega",
    note: null,
    languages: ["Französisch", "Rundi"],
  },
  BEL: {
    id: "belgien",
    name: "Belgien",
    capital: "Brüssel",
    note: null,
    languages: ["Deutsch", "Französisch", "Niederländisch"],
  },
  BEN: {
    id: "benin",
    name: "Benin",
    capital: "Porto-Novo",
    note: "Hauptstadt ist Porto-Novo, Regierungssitz ist Cotonou.",
    languages: ["Französisch"],
  },
  BFA: {
    id: "burkina-faso",
    name: "Burkina Faso",
    capital: "Ouagadougou",
    note: null,
    languages: ["Französisch"],
  },
  BGD: {
    id: "bangladesch",
    name: "Bangladesch",
    capital: "Dhaka",
    note: null,
    languages: ["Bengalisch"],
  },
  BGR: {
    id: "bulgarien",
    name: "Bulgarien",
    capital: "Sofia",
    note: null,
    languages: ["Bulgarisch"],
  },
  BHR: {
    id: "bahrain",
    name: "Bahrain",
    capital: "Manama",
    note: null,
    languages: ["Arabisch"],
  },
  BHS: {
    id: "bahamas",
    name: "Bahamas",
    capital: "Nassau",
    note: null,
    languages: ["Englisch"],
  },
  BIH: {
    id: "bosnien-und-herzegowina",
    name: "Bosnien und Herzegowina",
    capital: "Sarajevo",
    note: null,
    languages: ["Bosnisch", "Kroatisch", "Serbisch"],
  },
  BLR: {
    id: "belarus",
    name: "Belarus",
    capital: "Minsk",
    note: null,
    languages: ["Belarussisch", "Russisch"],
  },
  BLZ: {
    id: "belize",
    name: "Belize",
    capital: "Belmopan",
    note: null,
    languages: ["bjz", "Englisch", "Spanisch"],
  },
  BOL: {
    id: "bolivien",
    name: "Bolivien",
    capital: "Sucre",
    note: "Verfassungsmäßige Hauptstadt ist Sucre, Regierungssitz ist La Paz.",
    languages: ["Aymara", "Guaraní", "Quechua", "Spanisch"],
  },
  BRA: {
    id: "brasilien",
    name: "Brasilien",
    capital: "Brasília",
    note: null,
    languages: ["Portugiesisch"],
  },
  BRB: {
    id: "barbados",
    name: "Barbados",
    capital: "Bridgetown",
    note: null,
    languages: ["Englisch"],
  },
  BRN: {
    id: "brunei",
    name: "Brunei",
    capital: "Bandar Seri Begawan",
    note: null,
    languages: ["Malaiisch"],
  },
  BTN: {
    id: "bhutan",
    name: "Bhutan",
    capital: "Thimphu",
    note: null,
    languages: ["Dzongkha"],
  },
  BWA: {
    id: "botswana",
    name: "Botswana",
    capital: "Gaborone",
    note: null,
    languages: ["Englisch", "Tswana"],
  },
  CAF: {
    id: "zentralafrikanische-republik",
    name: "Zentralafrikanische Republik",
    capital: "Bangui",
    note: null,
    languages: ["Französisch", "Sango"],
  },
  CAN: {
    id: "kanada",
    name: "Kanada",
    capital: "Ottawa",
    note: null,
    languages: ["Englisch", "Französisch"],
  },
  CHE: {
    id: "schweiz",
    name: "Schweiz",
    capital: "Bern",
    note: "Die Schweiz hat keine Hauptstadt im rechtlichen Sinn; Bern ist die Bundesstadt und Sitz von Regierung und Parlament.",
    languages: [
      "Französisch",
      "Schweizerdeutsch",
      "Italienisch",
      "Rätoromanisch",
    ],
  },
  CHL: {
    id: "chile",
    name: "Chile",
    capital: "Santiago de Chile",
    note: null,
    languages: ["Spanisch"],
  },
  CHN: {
    id: "china",
    name: "China",
    capital: "Peking",
    note: null,
    languages: ["Chinesisch"],
  },
  CIV: {
    id: "cote-d-ivoire",
    name: "Côte d'Ivoire",
    capital: "Yamoussoukro",
    note: "Hauptstadt ist Yamoussoukro, die meisten Behörden und Botschaften befinden sich in Abidjan.",
    languages: ["Französisch"],
  },
  CMR: {
    id: "kamerun",
    name: "Kamerun",
    capital: "Jaunde",
    note: null,
    languages: ["Englisch", "Französisch"],
  },
  COD: {
    id: "demokratische-republik-kongo",
    name: "Demokratische Republik Kongo",
    capital: "Kinshasa",
    note: null,
    languages: [
      "Französisch",
      "Kongolesisch",
      "Lingala",
      "Luba-Lulua",
      "Suaheli",
    ],
  },
  COG: {
    id: "republik-kongo",
    name: "Republik Kongo",
    capital: "Brazzaville",
    note: null,
    languages: ["Französisch", "Kongolesisch", "Lingala"],
  },
  COL: {
    id: "kolumbien",
    name: "Kolumbien",
    capital: "Bogotá",
    note: null,
    languages: ["Spanisch"],
  },
  COM: {
    id: "komoren",
    name: "Komoren",
    capital: "Moroni",
    note: null,
    languages: ["Arabisch", "Französisch", "zdj"],
  },
  CPV: {
    id: "cabo-verde",
    name: "Cabo Verde",
    capital: "Praia",
    note: null,
    languages: ["Portugiesisch"],
  },
  CRI: {
    id: "costa-rica",
    name: "Costa Rica",
    capital: "San José",
    note: null,
    languages: ["Spanisch"],
  },
  CUB: {
    id: "kuba",
    name: "Kuba",
    capital: "Havanna",
    note: null,
    languages: ["Spanisch"],
  },
  CYP: {
    id: "zypern",
    name: "Zypern",
    capital: "Nikosia",
    note: "Die Republik Zypern kontrolliert den Süden der Insel; der Norden steht seit 1974 unter türkisch-zyprischer Verwaltung.",
    languages: ["Griechisch", "Türkisch"],
  },
  CZE: {
    id: "tschechien",
    name: "Tschechien",
    capital: "Prag",
    note: null,
    languages: ["Tschechisch", "Slowakisch"],
  },
  DEU: {
    id: "deutschland",
    name: "Deutschland",
    capital: "Berlin",
    note: null,
    languages: ["Deutsch"],
  },
  DJI: {
    id: "dschibuti",
    name: "Dschibuti",
    capital: "Dschibuti",
    note: null,
    languages: ["Arabisch", "Französisch"],
  },
  DMA: {
    id: "dominica",
    name: "Dominica",
    capital: "Roseau",
    note: null,
    languages: ["Englisch"],
  },
  DNK: {
    id: "daenemark",
    name: "Dänemark",
    capital: "Kopenhagen",
    note: null,
    languages: ["Dänisch"],
  },
  DOM: {
    id: "dominikanische-republik",
    name: "Dominikanische Republik",
    capital: "Santo Domingo",
    note: null,
    languages: ["Spanisch"],
  },
  DZA: {
    id: "algerien",
    name: "Algerien",
    capital: "Algier",
    note: null,
    languages: ["Arabisch"],
  },
  ECU: {
    id: "ecuador",
    name: "Ecuador",
    capital: "Quito",
    note: null,
    languages: ["Spanisch"],
  },
  EGY: {
    id: "aegypten",
    name: "Ägypten",
    capital: "Kairo",
    note: null,
    languages: ["Arabisch"],
  },
  ERI: {
    id: "eritrea",
    name: "Eritrea",
    capital: "Asmara",
    note: null,
    languages: ["Arabisch", "Englisch", "Tigrinya"],
  },
  ESP: {
    id: "spanien",
    name: "Spanien",
    capital: "Madrid",
    note: null,
    languages: ["Spanisch"],
  },
  EST: {
    id: "estland",
    name: "Estland",
    capital: "Tallinn",
    note: null,
    languages: ["Estnisch"],
  },
  ETH: {
    id: "aethiopien",
    name: "Äthiopien",
    capital: "Addis Abeba",
    note: null,
    languages: ["Amharisch"],
  },
  FIN: {
    id: "finnland",
    name: "Finnland",
    capital: "Helsinki",
    note: null,
    languages: ["Finnisch", "Schwedisch"],
  },
  FJI: {
    id: "fidschi",
    name: "Fidschi",
    capital: "Suva",
    note: null,
    languages: ["Englisch", "Fidschi", "Fidschi-Hindi"],
  },
  FRA: {
    id: "frankreich",
    name: "Frankreich",
    capital: "Paris",
    note: null,
    languages: ["Französisch"],
  },
  FSM: {
    id: "mikronesien",
    name: "Mikronesien",
    capital: "Palikir",
    note: null,
    languages: ["Englisch"],
  },
  GAB: {
    id: "gabun",
    name: "Gabun",
    capital: "Libreville",
    note: null,
    languages: ["Französisch"],
  },
  GBR: {
    id: "vereinigtes-koenigreich",
    name: "Vereinigtes Königreich",
    capital: "London",
    note: null,
    languages: ["Englisch"],
  },
  GEO: {
    id: "georgien",
    name: "Georgien",
    capital: "Tiflis",
    note: null,
    languages: ["Georgisch"],
  },
  GHA: {
    id: "ghana",
    name: "Ghana",
    capital: "Accra",
    note: null,
    languages: ["Englisch"],
  },
  GIN: {
    id: "guinea",
    name: "Guinea",
    capital: "Conakry",
    note: null,
    languages: ["Französisch"],
  },
  GMB: {
    id: "gambia",
    name: "Gambia",
    capital: "Banjul",
    note: null,
    languages: ["Englisch"],
  },
  GNB: {
    id: "guinea-bissau",
    name: "Guinea-Bissau",
    capital: "Bissau",
    note: null,
    languages: ["Portugiesisch", "pov"],
  },
  GNQ: {
    id: "aequatorialguinea",
    name: "Äquatorialguinea",
    capital: "Malabo",
    note: null,
    languages: ["Französisch", "Portugiesisch", "Spanisch"],
  },
  GRC: {
    id: "griechenland",
    name: "Griechenland",
    capital: "Athen",
    note: null,
    languages: ["Griechisch"],
  },
  GRD: {
    id: "grenada",
    name: "Grenada",
    capital: "St. George's",
    note: null,
    languages: ["Englisch"],
  },
  GTM: {
    id: "guatemala",
    name: "Guatemala",
    capital: "Guatemala-Stadt",
    note: null,
    languages: ["Spanisch"],
  },
  GUY: {
    id: "guyana",
    name: "Guyana",
    capital: "Georgetown",
    note: null,
    languages: ["Englisch"],
  },
  HND: {
    id: "honduras",
    name: "Honduras",
    capital: "Tegucigalpa",
    note: null,
    languages: ["Spanisch"],
  },
  HRV: {
    id: "kroatien",
    name: "Kroatien",
    capital: "Zagreb",
    note: null,
    languages: ["Kroatisch"],
  },
  HTI: {
    id: "haiti",
    name: "Haiti",
    capital: "Port-au-Prince",
    note: null,
    languages: ["Französisch", "Haiti-Kreolisch"],
  },
  HUN: {
    id: "ungarn",
    name: "Ungarn",
    capital: "Budapest",
    note: null,
    languages: ["Ungarisch"],
  },
  IDN: {
    id: "indonesien",
    name: "Indonesien",
    capital: "Jakarta",
    note: null,
    languages: ["Indonesisch"],
  },
  IND: {
    id: "indien",
    name: "Indien",
    capital: "Neu-Delhi",
    note: null,
    languages: ["Englisch", "Hindi", "Tamil"],
  },
  IRL: {
    id: "irland",
    name: "Irland",
    capital: "Dublin",
    note: null,
    languages: ["Englisch", "Irisch"],
  },
  IRN: {
    id: "iran",
    name: "Iran",
    capital: "Teheran",
    note: null,
    languages: ["Persisch"],
  },
  IRQ: {
    id: "irak",
    name: "Irak",
    capital: "Bagdad",
    note: null,
    languages: ["Arabisch", "Aramäisch", "Zentralkurdisch"],
  },
  ISL: {
    id: "island",
    name: "Island",
    capital: "Reykjavík",
    note: null,
    languages: ["Isländisch"],
  },
  ISR: {
    id: "israel",
    name: "Israel",
    capital: "Jerusalem",
    note: "Israel betrachtet Jerusalem als Hauptstadt; der Status ist international umstritten, die deutsche Botschaft befindet sich in Tel Aviv.",
    languages: ["Arabisch", "Hebräisch"],
  },
  ITA: {
    id: "italien",
    name: "Italien",
    capital: "Rom",
    note: null,
    languages: ["Italienisch"],
  },
  JAM: {
    id: "jamaika",
    name: "Jamaika",
    capital: "Kingston",
    note: null,
    languages: ["Englisch", "Jamaikanisch-Kreolisch"],
  },
  JOR: {
    id: "jordanien",
    name: "Jordanien",
    capital: "Amman",
    note: null,
    languages: ["Arabisch"],
  },
  JPN: {
    id: "japan",
    name: "Japan",
    capital: "Tokio",
    note: null,
    languages: ["Japanisch"],
  },
  KAZ: {
    id: "kasachstan",
    name: "Kasachstan",
    capital: "Astana",
    note: null,
    languages: ["Kasachisch", "Russisch"],
  },
  KEN: {
    id: "kenia",
    name: "Kenia",
    capital: "Nairobi",
    note: null,
    languages: ["Englisch", "Suaheli"],
  },
  KGZ: {
    id: "kirgisistan",
    name: "Kirgisistan",
    capital: "Bischkek",
    note: null,
    languages: ["Kirgisisch", "Russisch"],
  },
  KHM: {
    id: "kambodscha",
    name: "Kambodscha",
    capital: "Phnom Penh",
    note: null,
    languages: ["Khmer"],
  },
  KIR: {
    id: "kiribati",
    name: "Kiribati",
    capital: "Süd-Tarawa",
    note: null,
    languages: ["Englisch", "Kiribatisch"],
  },
  KNA: {
    id: "st-kitts-und-nevis",
    name: "St. Kitts und Nevis",
    capital: "Basseterre",
    note: null,
    languages: ["Englisch"],
  },
  KOR: {
    id: "suedkorea",
    name: "Südkorea",
    capital: "Seoul",
    note: null,
    languages: ["Koreanisch"],
  },
  KWT: {
    id: "kuwait",
    name: "Kuwait",
    capital: "Kuwait-Stadt",
    note: null,
    languages: ["Arabisch"],
  },
  LAO: {
    id: "laos",
    name: "Laos",
    capital: "Vientiane",
    note: null,
    languages: ["Laotisch"],
  },
  LBN: {
    id: "libanon",
    name: "Libanon",
    capital: "Beirut",
    note: null,
    languages: ["Arabisch", "Französisch"],
  },
  LBR: {
    id: "liberia",
    name: "Liberia",
    capital: "Monrovia",
    note: null,
    languages: ["Englisch"],
  },
  LBY: {
    id: "libyen",
    name: "Libyen",
    capital: "Tripolis",
    note: null,
    languages: ["Arabisch"],
  },
  LCA: {
    id: "st-lucia",
    name: "St. Lucia",
    capital: "Castries",
    note: null,
    languages: ["Englisch"],
  },
  LIE: {
    id: "liechtenstein",
    name: "Liechtenstein",
    capital: "Vaduz",
    note: null,
    languages: ["Deutsch"],
  },
  LKA: {
    id: "sri-lanka",
    name: "Sri Lanka",
    capital: "Colombo",
    note: "Offizielle Hauptstadt ist Sri Jayawardenepura Kotte, ein Vorort von Colombo; Colombo ist die größte Stadt.",
    languages: ["Singhalesisch", "Tamil"],
  },
  LSO: {
    id: "lesotho",
    name: "Lesotho",
    capital: "Maseru",
    note: null,
    languages: ["Englisch", "Süd-Sotho"],
  },
  LTU: {
    id: "litauen",
    name: "Litauen",
    capital: "Vilnius",
    note: null,
    languages: ["Litauisch"],
  },
  LUX: {
    id: "luxemburg",
    name: "Luxemburg",
    capital: "Luxemburg",
    note: null,
    languages: ["Deutsch", "Französisch", "Luxemburgisch"],
  },
  LVA: {
    id: "lettland",
    name: "Lettland",
    capital: "Riga",
    note: null,
    languages: ["Lettisch"],
  },
  MAR: {
    id: "marokko",
    name: "Marokko",
    capital: "Rabat",
    note: null,
    languages: ["Arabisch", "ber"],
  },
  MCO: {
    id: "monaco",
    name: "Monaco",
    capital: "Monaco",
    note: null,
    languages: ["Französisch"],
  },
  MDA: {
    id: "moldau",
    name: "Moldau",
    capital: "Chișinău",
    note: null,
    languages: ["Rumänisch"],
  },
  MDG: {
    id: "madagaskar",
    name: "Madagaskar",
    capital: "Antananarivo",
    note: null,
    languages: ["Französisch", "Malagasy"],
  },
  MDV: {
    id: "malediven",
    name: "Malediven",
    capital: "Malé",
    note: null,
    languages: ["Dhivehi"],
  },
  MEX: {
    id: "mexiko",
    name: "Mexiko",
    capital: "Mexiko-Stadt",
    note: null,
    languages: ["Spanisch"],
  },
  MHL: {
    id: "marshallinseln",
    name: "Marshallinseln",
    capital: "Majuro",
    note: null,
    languages: ["Englisch", "Marschallesisch"],
  },
  MKD: {
    id: "nordmazedonien",
    name: "Nordmazedonien",
    capital: "Skopje",
    note: null,
    languages: ["Mazedonisch"],
  },
  MLI: {
    id: "mali",
    name: "Mali",
    capital: "Bamako",
    note: null,
    languages: ["Französisch"],
  },
  MLT: {
    id: "malta",
    name: "Malta",
    capital: "Valletta",
    note: null,
    languages: ["Englisch", "Maltesisch"],
  },
  MMR: {
    id: "myanmar",
    name: "Myanmar",
    capital: "Naypyidaw",
    note: null,
    languages: ["Birmanisch"],
  },
  MNE: {
    id: "montenegro",
    name: "Montenegro",
    capital: "Podgorica",
    note: null,
    languages: ["Serbisch (Montenegro)"],
  },
  MNG: {
    id: "mongolei",
    name: "Mongolei",
    capital: "Ulan-Bator",
    note: null,
    languages: ["Mongolisch"],
  },
  MOZ: {
    id: "mosambik",
    name: "Mosambik",
    capital: "Maputo",
    note: null,
    languages: ["Portugiesisch"],
  },
  MRT: {
    id: "mauretanien",
    name: "Mauretanien",
    capital: "Nouakchott",
    note: null,
    languages: ["Arabisch"],
  },
  MUS: {
    id: "mauritius",
    name: "Mauritius",
    capital: "Port Louis",
    note: null,
    languages: ["Englisch", "Französisch", "Morisyen"],
  },
  MWI: {
    id: "malawi",
    name: "Malawi",
    capital: "Lilongwe",
    note: null,
    languages: ["Englisch", "Nyanja"],
  },
  MYS: {
    id: "malaysia",
    name: "Malaysia",
    capital: "Kuala Lumpur",
    note: "Kuala Lumpur ist Hauptstadt und Parlamentssitz, die Regierung sitzt überwiegend in Putrajaya.",
    languages: ["Englisch", "Malaiisch"],
  },
  NAM: {
    id: "namibia",
    name: "Namibia",
    capital: "Windhoek",
    note: null,
    languages: [
      "Afrikaans",
      "Deutsch",
      "Englisch",
      "Herero",
      "hgm",
      "kwn",
      "Lozi",
      "Ndonga",
      "Tswana",
    ],
  },
  NER: {
    id: "niger",
    name: "Niger",
    capital: "Niamey",
    note: null,
    languages: ["Französisch"],
  },
  NGA: {
    id: "nigeria",
    name: "Nigeria",
    capital: "Abuja",
    note: null,
    languages: ["Englisch"],
  },
  NIC: {
    id: "nicaragua",
    name: "Nicaragua",
    capital: "Managua",
    note: null,
    languages: ["Spanisch"],
  },
  NLD: {
    id: "niederlande",
    name: "Niederlande",
    capital: "Amsterdam",
    note: "Hauptstadt ist Amsterdam, Regierung und Parlament sitzen in Den Haag.",
    languages: ["Niederländisch"],
  },
  NOR: {
    id: "norwegen",
    name: "Norwegen",
    capital: "Oslo",
    note: null,
    languages: ["Norwegisch (Nynorsk)", "Norwegisch (Bokmål)", "smi"],
  },
  NPL: {
    id: "nepal",
    name: "Nepal",
    capital: "Kathmandu",
    note: null,
    languages: ["Nepalesisch"],
  },
  NRU: {
    id: "nauru",
    name: "Nauru",
    capital: "Yaren",
    note: null,
    languages: ["Englisch", "Nauruisch"],
  },
  NZL: {
    id: "neuseeland",
    name: "Neuseeland",
    capital: "Wellington",
    note: null,
    languages: ["Englisch", "Māori", "nzs"],
  },
  OMN: {
    id: "oman",
    name: "Oman",
    capital: "Maskat",
    note: null,
    languages: ["Arabisch"],
  },
  PAK: {
    id: "pakistan",
    name: "Pakistan",
    capital: "Islamabad",
    note: null,
    languages: ["Englisch", "Urdu"],
  },
  PAN: {
    id: "panama",
    name: "Panama",
    capital: "Panama-Stadt",
    note: null,
    languages: ["Spanisch"],
  },
  PER: {
    id: "peru",
    name: "Peru",
    capital: "Lima",
    note: null,
    languages: ["Aymara", "Quechua", "Spanisch"],
  },
  PHL: {
    id: "philippinen",
    name: "Philippinen",
    capital: "Manila",
    note: null,
    languages: ["Englisch", "Filipino"],
  },
  PLW: {
    id: "palau",
    name: "Palau",
    capital: "Ngerulmud",
    note: null,
    languages: ["Englisch", "Palau"],
  },
  PNG: {
    id: "papua-neuguinea",
    name: "Papua-Neuguinea",
    capital: "Port Moresby",
    note: null,
    languages: ["Englisch", "Hiri-Motu", "Neumelanesisch"],
  },
  POL: {
    id: "polen",
    name: "Polen",
    capital: "Warschau",
    note: null,
    languages: ["Polnisch"],
  },
  PRK: {
    id: "nordkorea",
    name: "Nordkorea",
    capital: "Pjöngjang",
    note: null,
    languages: ["Koreanisch"],
  },
  PRT: {
    id: "portugal",
    name: "Portugal",
    capital: "Lissabon",
    note: null,
    languages: ["Portugiesisch"],
  },
  PRY: {
    id: "paraguay",
    name: "Paraguay",
    capital: "Asunción",
    note: null,
    languages: ["Guaraní", "Spanisch"],
  },
  PSE: {
    id: "palaestina",
    name: "Palästina",
    capital: "Ramallah",
    note: "Palästina beansprucht Ost-Jerusalem als Hauptstadt; Verwaltungssitz ist Ramallah.",
    languages: ["Arabisch"],
  },
  QAT: {
    id: "katar",
    name: "Katar",
    capital: "Doha",
    note: null,
    languages: ["Arabisch"],
  },
  ROU: {
    id: "rumaenien",
    name: "Rumänien",
    capital: "Bukarest",
    note: null,
    languages: ["Rumänisch"],
  },
  RUS: {
    id: "russland",
    name: "Russland",
    capital: "Moskau",
    note: null,
    languages: ["Russisch"],
  },
  RWA: {
    id: "ruanda",
    name: "Ruanda",
    capital: "Kigali",
    note: null,
    languages: ["Englisch", "Französisch", "Kinyarwanda"],
  },
  SAU: {
    id: "saudi-arabien",
    name: "Saudi-Arabien",
    capital: "Riad",
    note: null,
    languages: ["Arabisch"],
  },
  SDN: {
    id: "sudan",
    name: "Sudan",
    capital: "Khartum",
    note: null,
    languages: ["Arabisch", "Englisch"],
  },
  SEN: {
    id: "senegal",
    name: "Senegal",
    capital: "Dakar",
    note: null,
    languages: ["Französisch"],
  },
  SGP: {
    id: "singapur",
    name: "Singapur",
    capital: "Singapur",
    note: null,
    languages: ["Englisch", "Malaiisch", "Tamil", "Chinesisch"],
  },
  SLB: {
    id: "salomonen",
    name: "Salomonen",
    capital: "Honiara",
    note: null,
    languages: ["Englisch"],
  },
  SLE: {
    id: "sierra-leone",
    name: "Sierra Leone",
    capital: "Freetown",
    note: null,
    languages: ["Englisch"],
  },
  SLV: {
    id: "el-salvador",
    name: "El Salvador",
    capital: "San Salvador",
    note: null,
    languages: ["Spanisch"],
  },
  SMR: {
    id: "san-marino",
    name: "San Marino",
    capital: "San Marino",
    note: null,
    languages: ["Italienisch"],
  },
  SOM: {
    id: "somalia",
    name: "Somalia",
    capital: "Mogadischu",
    note: null,
    languages: ["Arabisch", "Somali"],
  },
  SRB: {
    id: "serbien",
    name: "Serbien",
    capital: "Belgrad",
    note: null,
    languages: ["Serbisch"],
  },
  SSD: {
    id: "suedsudan",
    name: "Südsudan",
    capital: "Juba",
    note: null,
    languages: ["Englisch"],
  },
  STP: {
    id: "sao-tome-und-principe",
    name: "São Tomé und Príncipe",
    capital: "São Tomé",
    note: null,
    languages: ["Portugiesisch"],
  },
  SUR: {
    id: "suriname",
    name: "Suriname",
    capital: "Paramaribo",
    note: null,
    languages: ["Niederländisch"],
  },
  SVK: {
    id: "slowakei",
    name: "Slowakei",
    capital: "Bratislava",
    note: null,
    languages: ["Slowakisch"],
  },
  SVN: {
    id: "slowenien",
    name: "Slowenien",
    capital: "Ljubljana",
    note: null,
    languages: ["Slowenisch"],
  },
  SWE: {
    id: "schweden",
    name: "Schweden",
    capital: "Stockholm",
    note: null,
    languages: ["Schwedisch"],
  },
  SWZ: {
    id: "eswatini",
    name: "Eswatini",
    capital: "Lobamba",
    note: "Lobamba ist königliche und legislative Hauptstadt, Regierungssitz ist Mbabane.",
    languages: ["Englisch", "Swazi"],
  },
  SYC: {
    id: "seychellen",
    name: "Seychellen",
    capital: "Victoria",
    note: null,
    languages: ["Seychellenkreol", "Englisch", "Französisch"],
  },
  SYR: {
    id: "syrien",
    name: "Syrien",
    capital: "Damaskus",
    note: null,
    languages: ["Arabisch"],
  },
  TCD: {
    id: "tschad",
    name: "Tschad",
    capital: "N'Djamena",
    note: null,
    languages: ["Arabisch", "Französisch"],
  },
  TGO: {
    id: "togo",
    name: "Togo",
    capital: "Lomé",
    note: null,
    languages: ["Französisch"],
  },
  THA: {
    id: "thailand",
    name: "Thailand",
    capital: "Bangkok",
    note: null,
    languages: ["Thailändisch"],
  },
  TJK: {
    id: "tadschikistan",
    name: "Tadschikistan",
    capital: "Duschanbe",
    note: null,
    languages: ["Russisch", "Tadschikisch"],
  },
  TKM: {
    id: "turkmenistan",
    name: "Turkmenistan",
    capital: "Aschgabat",
    note: null,
    languages: ["Russisch", "Turkmenisch"],
  },
  TLS: {
    id: "timor-leste",
    name: "Timor-Leste",
    capital: "Dili",
    note: null,
    languages: ["Portugiesisch", "Tetum"],
  },
  TON: {
    id: "tonga",
    name: "Tonga",
    capital: "Nuku'alofa",
    note: null,
    languages: ["Englisch", "Tongaisch"],
  },
  TTO: {
    id: "trinidad-und-tobago",
    name: "Trinidad und Tobago",
    capital: "Port of Spain",
    note: null,
    languages: ["Englisch"],
  },
  TUN: {
    id: "tunesien",
    name: "Tunesien",
    capital: "Tunis",
    note: null,
    languages: ["Arabisch"],
  },
  TUR: {
    id: "tuerkei",
    name: "Türkei",
    capital: "Ankara",
    note: null,
    languages: ["Türkisch"],
  },
  TUV: {
    id: "tuvalu",
    name: "Tuvalu",
    capital: "Funafuti",
    note: null,
    languages: ["Englisch", "Tuvaluisch"],
  },
  TZA: {
    id: "tansania",
    name: "Tansania",
    capital: "Dodoma",
    note: "Hauptstadt ist Dodoma, viele Behörden und Botschaften befinden sich noch in Daressalam.",
    languages: ["Englisch", "Suaheli"],
  },
  UGA: {
    id: "uganda",
    name: "Uganda",
    capital: "Kampala",
    note: null,
    languages: ["Englisch", "Suaheli"],
  },
  UKR: {
    id: "ukraine",
    name: "Ukraine",
    capital: "Kyjiw",
    note: null,
    languages: ["Ukrainisch"],
  },
  URY: {
    id: "uruguay",
    name: "Uruguay",
    capital: "Montevideo",
    note: null,
    languages: ["Spanisch"],
  },
  USA: {
    id: "vereinigte-staaten",
    name: "Vereinigte Staaten",
    capital: "Washington, D.C.",
    note: null,
    languages: ["Englisch"],
  },
  UZB: {
    id: "usbekistan",
    name: "Usbekistan",
    capital: "Taschkent",
    note: null,
    languages: ["Russisch", "Usbekisch"],
  },
  VAT: {
    id: "vatikanstadt",
    name: "Vatikanstadt",
    capital: "Vatikanstadt",
    note: null,
    languages: ["Italienisch", "Latein"],
  },
  VCT: {
    id: "st-vincent-und-die-grenadinen",
    name: "St. Vincent und die Grenadinen",
    capital: "Kingstown",
    note: null,
    languages: ["Englisch"],
  },
  VEN: {
    id: "venezuela",
    name: "Venezuela",
    capital: "Caracas",
    note: null,
    languages: ["Spanisch"],
  },
  VNM: {
    id: "vietnam",
    name: "Vietnam",
    capital: "Hanoi",
    note: null,
    languages: ["Vietnamesisch"],
  },
  VUT: {
    id: "vanuatu",
    name: "Vanuatu",
    capital: "Port Vila",
    note: null,
    languages: ["Bislama", "Englisch", "Französisch"],
  },
  WSM: {
    id: "samoa",
    name: "Samoa",
    capital: "Apia",
    note: null,
    languages: ["Englisch", "Samoanisch"],
  },
  YEM: {
    id: "jemen",
    name: "Jemen",
    capital: "Sanaa",
    note: null,
    languages: ["Arabisch"],
  },
  ZAF: {
    id: "suedafrika",
    name: "Südafrika",
    capital: "Pretoria",
    note: "Südafrika hat drei Hauptstädte: Pretoria (Regierung), Kapstadt (Parlament) und Bloemfontein (Oberstes Berufungsgericht).",
    languages: [
      "Afrikaans",
      "Englisch",
      "Süd-Ndebele",
      "Nord-Sotho",
      "Süd-Sotho",
      "Swazi",
      "Tswana",
      "Tsonga",
      "Venda",
      "Xhosa",
      "Zulu",
    ],
  },
  ZMB: {
    id: "sambia",
    name: "Sambia",
    capital: "Lusaka",
    note: null,
    languages: ["Englisch"],
  },
  ZWE: {
    id: "simbabwe",
    name: "Simbabwe",
    capital: "Harare",
    note: null,
    languages: [
      "bwg",
      "Englisch",
      "kck",
      "khi",
      "ndc",
      "Nord-Ndebele",
      "Nyanja",
      "Shona",
      "Süd-Sotho",
      "toi",
      "Tswana",
      "Tsonga",
      "Venda",
      "Xhosa",
      "zib",
    ],
  },
};

export const WORLD_REGIONS_DE: Record<string, string> = {
  Asya: "Asien",
  Afrika: "Afrika",
  Avrupa: "Europa",
  Amerika: "Amerika",
  Okyanusya: "Ozeanien",
};
