// Ulke verilerinin Ingilizce eki: Ingilizce URL, baskent, bolge, resmi diller.
// Kaynak: world-countries (mledoze/countries, ODbL 1.0). Bu veri dosyasi ODbL 1.0 lisansi altindadir.
export type WorldCountryEn = {
  iso3: string;
  id: string;
  capital: string;
  note: string | null;
  region: string;
  subregion: string;
  languages: string[];
  demonym: string;
};

export const worldCountriesEn: Record<string, WorldCountryEn> = {
  AFG: {
    iso3: "AFG",
    id: "afghanistan",
    capital: "Kabul",
    note: null,
    region: "Asia",
    subregion: "Southern Asia",
    languages: ["Dari", "Pashto", "Turkmen"],
    demonym: "Afghan",
  },
  AGO: {
    iso3: "AGO",
    id: "angola",
    capital: "Luanda",
    note: null,
    region: "Africa",
    subregion: "Middle Africa",
    languages: ["Portuguese"],
    demonym: "Angolan",
  },
  ALB: {
    iso3: "ALB",
    id: "albania",
    capital: "Tirana",
    note: null,
    region: "Europe",
    subregion: "Southeast Europe",
    languages: ["Albanian"],
    demonym: "Albanian",
  },
  AND: {
    iso3: "AND",
    id: "andorra",
    capital: "Andorra la Vella",
    note: null,
    region: "Europe",
    subregion: "Southern Europe",
    languages: ["Catalan"],
    demonym: "Andorran",
  },
  ARE: {
    iso3: "ARE",
    id: "united-arab-emirates",
    capital: "Abu Dhabi",
    note: null,
    region: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic"],
    demonym: "Emirati",
  },
  ARG: {
    iso3: "ARG",
    id: "argentina",
    capital: "Buenos Aires",
    note: null,
    region: "Americas",
    subregion: "South America",
    languages: ["Guaraní", "Spanish"],
    demonym: "Argentine",
  },
  ARM: {
    iso3: "ARM",
    id: "armenia",
    capital: "Yerevan",
    note: null,
    region: "Asia",
    subregion: "Western Asia",
    languages: ["Armenian"],
    demonym: "Armenian",
  },
  ATG: {
    iso3: "ATG",
    id: "antigua-and-barbuda",
    capital: "Saint John's",
    note: null,
    region: "Americas",
    subregion: "Caribbean",
    languages: ["English"],
    demonym: "Antiguan, Barbudan",
  },
  AUS: {
    iso3: "AUS",
    id: "australia",
    capital: "Canberra",
    note: null,
    region: "Oceania",
    subregion: "Australia and New Zealand",
    languages: ["English"],
    demonym: "Australian",
  },
  AUT: {
    iso3: "AUT",
    id: "austria",
    capital: "Vienna",
    note: null,
    region: "Europe",
    subregion: "Central Europe",
    languages: ["Austro-Bavarian German"],
    demonym: "Austrian",
  },
  AZE: {
    iso3: "AZE",
    id: "azerbaijan",
    capital: "Baku",
    note: null,
    region: "Asia",
    subregion: "Western Asia",
    languages: ["Azerbaijani", "Russian"],
    demonym: "Azerbaijani",
  },
  BDI: {
    iso3: "BDI",
    id: "burundi",
    capital: "Gitega",
    note: null,
    region: "Africa",
    subregion: "Eastern Africa",
    languages: ["French", "Kirundi"],
    demonym: "Burundian",
  },
  BEL: {
    iso3: "BEL",
    id: "belgium",
    capital: "Brussels",
    note: null,
    region: "Europe",
    subregion: "Western Europe",
    languages: ["German", "French", "Dutch"],
    demonym: "Belgian",
  },
  BEN: {
    iso3: "BEN",
    id: "benin",
    capital: "Porto-Novo",
    note: null,
    region: "Africa",
    subregion: "Western Africa",
    languages: ["French"],
    demonym: "Beninese",
  },
  BFA: {
    iso3: "BFA",
    id: "burkina-faso",
    capital: "Ouagadougou",
    note: null,
    region: "Africa",
    subregion: "Western Africa",
    languages: ["French"],
    demonym: "Burkinabe",
  },
  BGD: {
    iso3: "BGD",
    id: "bangladesh",
    capital: "Dhaka",
    note: null,
    region: "Asia",
    subregion: "Southern Asia",
    languages: ["Bengali"],
    demonym: "Bangladeshi",
  },
  BGR: {
    iso3: "BGR",
    id: "bulgaria",
    capital: "Sofia",
    note: null,
    region: "Europe",
    subregion: "Southeast Europe",
    languages: ["Bulgarian"],
    demonym: "Bulgarian",
  },
  BHR: {
    iso3: "BHR",
    id: "bahrain",
    capital: "Manama",
    note: null,
    region: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic"],
    demonym: "Bahraini",
  },
  BHS: {
    iso3: "BHS",
    id: "bahamas",
    capital: "Nassau",
    note: null,
    region: "Americas",
    subregion: "Caribbean",
    languages: ["English"],
    demonym: "Bahamian",
  },
  BIH: {
    iso3: "BIH",
    id: "bosnia-and-herzegovina",
    capital: "Sarajevo",
    note: null,
    region: "Europe",
    subregion: "Southeast Europe",
    languages: ["Bosnian", "Croatian", "Serbian"],
    demonym: "Bosnian, Herzegovinian",
  },
  BLR: {
    iso3: "BLR",
    id: "belarus",
    capital: "Minsk",
    note: null,
    region: "Europe",
    subregion: "Eastern Europe",
    languages: ["Belarusian", "Russian"],
    demonym: "Belarusian",
  },
  BLZ: {
    iso3: "BLZ",
    id: "belize",
    capital: "Belmopan",
    note: null,
    region: "Americas",
    subregion: "Central America",
    languages: ["Belizean Creole", "English", "Spanish"],
    demonym: "Belizean",
  },
  BOL: {
    iso3: "BOL",
    id: "bolivia",
    capital: "Sucre",
    note: null,
    region: "Americas",
    subregion: "South America",
    languages: ["Aymara", "Guaraní", "Quechua", "Spanish"],
    demonym: "Bolivian",
  },
  BRA: {
    iso3: "BRA",
    id: "brazil",
    capital: "Brasília",
    note: null,
    region: "Americas",
    subregion: "South America",
    languages: ["Portuguese"],
    demonym: "Brazilian",
  },
  BRB: {
    iso3: "BRB",
    id: "barbados",
    capital: "Bridgetown",
    note: null,
    region: "Americas",
    subregion: "Caribbean",
    languages: ["English"],
    demonym: "Barbadian",
  },
  BRN: {
    iso3: "BRN",
    id: "brunei",
    capital: "Bandar Seri Begawan",
    note: null,
    region: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["Malay"],
    demonym: "Bruneian",
  },
  BTN: {
    iso3: "BTN",
    id: "bhutan",
    capital: "Thimphu",
    note: null,
    region: "Asia",
    subregion: "Southern Asia",
    languages: ["Dzongkha"],
    demonym: "Bhutanese",
  },
  BWA: {
    iso3: "BWA",
    id: "botswana",
    capital: "Gaborone",
    note: null,
    region: "Africa",
    subregion: "Southern Africa",
    languages: ["English", "Tswana"],
    demonym: "Motswana",
  },
  CAF: {
    iso3: "CAF",
    id: "central-african-republic",
    capital: "Bangui",
    note: null,
    region: "Africa",
    subregion: "Middle Africa",
    languages: ["French", "Sango"],
    demonym: "Central African",
  },
  CAN: {
    iso3: "CAN",
    id: "canada",
    capital: "Ottawa",
    note: null,
    region: "Americas",
    subregion: "North America",
    languages: ["English", "French"],
    demonym: "Canadian",
  },
  CHE: {
    iso3: "CHE",
    id: "switzerland",
    capital: "Bern",
    note: null,
    region: "Europe",
    subregion: "Western Europe",
    languages: ["French", "Swiss German", "Italian", "Romansh"],
    demonym: "Swiss",
  },
  CHL: {
    iso3: "CHL",
    id: "chile",
    capital: "Santiago",
    note: null,
    region: "Americas",
    subregion: "South America",
    languages: ["Spanish"],
    demonym: "Chilean",
  },
  CHN: {
    iso3: "CHN",
    id: "china",
    capital: "Beijing",
    note: null,
    region: "Asia",
    subregion: "Eastern Asia",
    languages: ["Chinese"],
    demonym: "Chinese",
  },
  CIV: {
    iso3: "CIV",
    id: "ivory-coast",
    capital: "Yamoussoukro",
    note: null,
    region: "Africa",
    subregion: "Western Africa",
    languages: ["French"],
    demonym: "Ivorian",
  },
  CMR: {
    iso3: "CMR",
    id: "cameroon",
    capital: "Yaoundé",
    note: null,
    region: "Africa",
    subregion: "Middle Africa",
    languages: ["English", "French"],
    demonym: "Cameroonian",
  },
  COD: {
    iso3: "COD",
    id: "dr-congo",
    capital: "Kinshasa",
    note: null,
    region: "Africa",
    subregion: "Middle Africa",
    languages: ["French", "Kikongo", "Lingala", "Tshiluba", "Swahili"],
    demonym: "Congolese",
  },
  COG: {
    iso3: "COG",
    id: "republic-of-the-congo",
    capital: "Brazzaville",
    note: null,
    region: "Africa",
    subregion: "Middle Africa",
    languages: ["French", "Kikongo", "Lingala"],
    demonym: "Congolese",
  },
  COL: {
    iso3: "COL",
    id: "colombia",
    capital: "Bogotá",
    note: null,
    region: "Americas",
    subregion: "South America",
    languages: ["Spanish"],
    demonym: "Colombian",
  },
  COM: {
    iso3: "COM",
    id: "comoros",
    capital: "Moroni",
    note: null,
    region: "Africa",
    subregion: "Eastern Africa",
    languages: ["Arabic", "French", "Comorian"],
    demonym: "Comoran",
  },
  CPV: {
    iso3: "CPV",
    id: "cape-verde",
    capital: "Praia",
    note: null,
    region: "Africa",
    subregion: "Western Africa",
    languages: ["Portuguese"],
    demonym: "Cape Verdian",
  },
  CRI: {
    iso3: "CRI",
    id: "costa-rica",
    capital: "San José",
    note: null,
    region: "Americas",
    subregion: "Central America",
    languages: ["Spanish"],
    demonym: "Costa Rican",
  },
  CUB: {
    iso3: "CUB",
    id: "cuba",
    capital: "Havana",
    note: null,
    region: "Americas",
    subregion: "Caribbean",
    languages: ["Spanish"],
    demonym: "Cuban",
  },
  CYP: {
    iso3: "CYP",
    id: "cyprus",
    capital: "Nicosia",
    note: "The Republic of Cyprus controls the south of the island. Türkiye does not recognize it as the government of the whole island.",
    region: "Europe",
    subregion: "Southern Europe",
    languages: ["Greek", "Turkish"],
    demonym: "Cypriot",
  },
  CZE: {
    iso3: "CZE",
    id: "czechia",
    capital: "Prague",
    note: null,
    region: "Europe",
    subregion: "Central Europe",
    languages: ["Czech", "Slovak"],
    demonym: "Czech",
  },
  DEU: {
    iso3: "DEU",
    id: "germany",
    capital: "Berlin",
    note: null,
    region: "Europe",
    subregion: "Western Europe",
    languages: ["German"],
    demonym: "German",
  },
  DJI: {
    iso3: "DJI",
    id: "djibouti",
    capital: "Djibouti",
    note: null,
    region: "Africa",
    subregion: "Eastern Africa",
    languages: ["Arabic", "French"],
    demonym: "Djibouti",
  },
  DMA: {
    iso3: "DMA",
    id: "dominica",
    capital: "Roseau",
    note: null,
    region: "Americas",
    subregion: "Caribbean",
    languages: ["English"],
    demonym: "Dominican",
  },
  DNK: {
    iso3: "DNK",
    id: "denmark",
    capital: "Copenhagen",
    note: null,
    region: "Europe",
    subregion: "Northern Europe",
    languages: ["Danish"],
    demonym: "Danish",
  },
  DOM: {
    iso3: "DOM",
    id: "dominican-republic",
    capital: "Santo Domingo",
    note: null,
    region: "Americas",
    subregion: "Caribbean",
    languages: ["Spanish"],
    demonym: "Dominican",
  },
  DZA: {
    iso3: "DZA",
    id: "algeria",
    capital: "Algiers",
    note: null,
    region: "Africa",
    subregion: "Northern Africa",
    languages: ["Arabic"],
    demonym: "Algerian",
  },
  ECU: {
    iso3: "ECU",
    id: "ecuador",
    capital: "Quito",
    note: null,
    region: "Americas",
    subregion: "South America",
    languages: ["Spanish"],
    demonym: "Ecuadorean",
  },
  EGY: {
    iso3: "EGY",
    id: "egypt",
    capital: "Cairo",
    note: null,
    region: "Africa",
    subregion: "Northern Africa",
    languages: ["Arabic"],
    demonym: "Egyptian",
  },
  ERI: {
    iso3: "ERI",
    id: "eritrea",
    capital: "Asmara",
    note: null,
    region: "Africa",
    subregion: "Eastern Africa",
    languages: ["Arabic", "English", "Tigrinya"],
    demonym: "Eritrean",
  },
  ESP: {
    iso3: "ESP",
    id: "spain",
    capital: "Madrid",
    note: null,
    region: "Europe",
    subregion: "Southern Europe",
    languages: ["Spanish"],
    demonym: "Spanish",
  },
  EST: {
    iso3: "EST",
    id: "estonia",
    capital: "Tallinn",
    note: null,
    region: "Europe",
    subregion: "Northern Europe",
    languages: ["Estonian"],
    demonym: "Estonian",
  },
  ETH: {
    iso3: "ETH",
    id: "ethiopia",
    capital: "Addis Ababa",
    note: null,
    region: "Africa",
    subregion: "Eastern Africa",
    languages: ["Amharic"],
    demonym: "Ethiopian",
  },
  FIN: {
    iso3: "FIN",
    id: "finland",
    capital: "Helsinki",
    note: null,
    region: "Europe",
    subregion: "Northern Europe",
    languages: ["Finnish", "Swedish"],
    demonym: "Finnish",
  },
  FJI: {
    iso3: "FJI",
    id: "fiji",
    capital: "Suva",
    note: null,
    region: "Oceania",
    subregion: "Melanesia",
    languages: ["English", "Fijian", "Fiji Hindi"],
    demonym: "Fijian",
  },
  FRA: {
    iso3: "FRA",
    id: "france",
    capital: "Paris",
    note: null,
    region: "Europe",
    subregion: "Western Europe",
    languages: ["French"],
    demonym: "French",
  },
  FSM: {
    iso3: "FSM",
    id: "micronesia",
    capital: "Palikir",
    note: null,
    region: "Oceania",
    subregion: "Micronesia",
    languages: ["English"],
    demonym: "Micronesian",
  },
  GAB: {
    iso3: "GAB",
    id: "gabon",
    capital: "Libreville",
    note: null,
    region: "Africa",
    subregion: "Middle Africa",
    languages: ["French"],
    demonym: "Gabonese",
  },
  GBR: {
    iso3: "GBR",
    id: "united-kingdom",
    capital: "London",
    note: null,
    region: "Europe",
    subregion: "Northern Europe",
    languages: ["English"],
    demonym: "British",
  },
  GEO: {
    iso3: "GEO",
    id: "georgia",
    capital: "Tbilisi",
    note: null,
    region: "Asia",
    subregion: "Western Asia",
    languages: ["Georgian"],
    demonym: "Georgian",
  },
  GHA: {
    iso3: "GHA",
    id: "ghana",
    capital: "Accra",
    note: null,
    region: "Africa",
    subregion: "Western Africa",
    languages: ["English"],
    demonym: "Ghanaian",
  },
  GIN: {
    iso3: "GIN",
    id: "guinea",
    capital: "Conakry",
    note: null,
    region: "Africa",
    subregion: "Western Africa",
    languages: ["French"],
    demonym: "Guinean",
  },
  GMB: {
    iso3: "GMB",
    id: "gambia",
    capital: "Banjul",
    note: null,
    region: "Africa",
    subregion: "Western Africa",
    languages: ["English"],
    demonym: "Gambian",
  },
  GNB: {
    iso3: "GNB",
    id: "guinea-bissau",
    capital: "Bissau",
    note: null,
    region: "Africa",
    subregion: "Western Africa",
    languages: ["Portuguese", "Upper Guinea Creole"],
    demonym: "Guinea-Bissauan",
  },
  GNQ: {
    iso3: "GNQ",
    id: "equatorial-guinea",
    capital: "Malabo",
    note: null,
    region: "Africa",
    subregion: "Middle Africa",
    languages: ["French", "Portuguese", "Spanish"],
    demonym: "Equatorial Guinean",
  },
  GRC: {
    iso3: "GRC",
    id: "greece",
    capital: "Athens",
    note: null,
    region: "Europe",
    subregion: "Southern Europe",
    languages: ["Greek"],
    demonym: "Greek",
  },
  GRD: {
    iso3: "GRD",
    id: "grenada",
    capital: "St. George's",
    note: null,
    region: "Americas",
    subregion: "Caribbean",
    languages: ["English"],
    demonym: "Grenadian",
  },
  GTM: {
    iso3: "GTM",
    id: "guatemala",
    capital: "Guatemala City",
    note: null,
    region: "Americas",
    subregion: "Central America",
    languages: ["Spanish"],
    demonym: "Guatemalan",
  },
  GUY: {
    iso3: "GUY",
    id: "guyana",
    capital: "Georgetown",
    note: null,
    region: "Americas",
    subregion: "South America",
    languages: ["English"],
    demonym: "Guyanese",
  },
  HND: {
    iso3: "HND",
    id: "honduras",
    capital: "Tegucigalpa",
    note: null,
    region: "Americas",
    subregion: "Central America",
    languages: ["Spanish"],
    demonym: "Honduran",
  },
  HRV: {
    iso3: "HRV",
    id: "croatia",
    capital: "Zagreb",
    note: null,
    region: "Europe",
    subregion: "Southeast Europe",
    languages: ["Croatian"],
    demonym: "Croatian",
  },
  HTI: {
    iso3: "HTI",
    id: "haiti",
    capital: "Port-au-Prince",
    note: null,
    region: "Americas",
    subregion: "Caribbean",
    languages: ["French", "Haitian Creole"],
    demonym: "Haitian",
  },
  HUN: {
    iso3: "HUN",
    id: "hungary",
    capital: "Budapest",
    note: null,
    region: "Europe",
    subregion: "Central Europe",
    languages: ["Hungarian"],
    demonym: "Hungarian",
  },
  IDN: {
    iso3: "IDN",
    id: "indonesia",
    capital: "Jakarta",
    note: null,
    region: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["Indonesian"],
    demonym: "Indonesian",
  },
  IND: {
    iso3: "IND",
    id: "india",
    capital: "New Delhi",
    note: null,
    region: "Asia",
    subregion: "Southern Asia",
    languages: ["English", "Hindi", "Tamil"],
    demonym: "Indian",
  },
  IRL: {
    iso3: "IRL",
    id: "ireland",
    capital: "Dublin",
    note: null,
    region: "Europe",
    subregion: "Northern Europe",
    languages: ["English", "Irish"],
    demonym: "Irish",
  },
  IRN: {
    iso3: "IRN",
    id: "iran",
    capital: "Tehran",
    note: null,
    region: "Asia",
    subregion: "Southern Asia",
    languages: ["Persian (Farsi)"],
    demonym: "Iranian",
  },
  IRQ: {
    iso3: "IRQ",
    id: "iraq",
    capital: "Baghdad",
    note: null,
    region: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic", "Aramaic", "Sorani"],
    demonym: "Iraqi",
  },
  ISL: {
    iso3: "ISL",
    id: "iceland",
    capital: "Reykjavik",
    note: null,
    region: "Europe",
    subregion: "Northern Europe",
    languages: ["Icelandic"],
    demonym: "Icelander",
  },
  ISR: {
    iso3: "ISR",
    id: "israel",
    capital: "Jerusalem (disputed)",
    note: "Israel proclaims Jerusalem as its capital; its status is disputed internationally and many countries keep their embassies in Tel Aviv.",
    region: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic", "Hebrew"],
    demonym: "Israeli",
  },
  ITA: {
    iso3: "ITA",
    id: "italy",
    capital: "Rome",
    note: null,
    region: "Europe",
    subregion: "Southern Europe",
    languages: ["Italian"],
    demonym: "Italian",
  },
  JAM: {
    iso3: "JAM",
    id: "jamaica",
    capital: "Kingston",
    note: null,
    region: "Americas",
    subregion: "Caribbean",
    languages: ["English", "Jamaican Patois"],
    demonym: "Jamaican",
  },
  JOR: {
    iso3: "JOR",
    id: "jordan",
    capital: "Amman",
    note: null,
    region: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic"],
    demonym: "Jordanian",
  },
  JPN: {
    iso3: "JPN",
    id: "japan",
    capital: "Tokyo",
    note: null,
    region: "Asia",
    subregion: "Eastern Asia",
    languages: ["Japanese"],
    demonym: "Japanese",
  },
  KAZ: {
    iso3: "KAZ",
    id: "kazakhstan",
    capital: "Astana",
    note: null,
    region: "Asia",
    subregion: "Central Asia",
    languages: ["Kazakh", "Russian"],
    demonym: "Kazakhstani",
  },
  KEN: {
    iso3: "KEN",
    id: "kenya",
    capital: "Nairobi",
    note: null,
    region: "Africa",
    subregion: "Eastern Africa",
    languages: ["English", "Swahili"],
    demonym: "Kenyan",
  },
  KGZ: {
    iso3: "KGZ",
    id: "kyrgyzstan",
    capital: "Bishkek",
    note: null,
    region: "Asia",
    subregion: "Central Asia",
    languages: ["Kyrgyz", "Russian"],
    demonym: "Kirghiz",
  },
  KHM: {
    iso3: "KHM",
    id: "cambodia",
    capital: "Phnom Penh",
    note: null,
    region: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["Khmer"],
    demonym: "Cambodian",
  },
  KIR: {
    iso3: "KIR",
    id: "kiribati",
    capital: "South Tarawa",
    note: null,
    region: "Oceania",
    subregion: "Micronesia",
    languages: ["English", "Gilbertese"],
    demonym: "I-Kiribati",
  },
  KNA: {
    iso3: "KNA",
    id: "saint-kitts-and-nevis",
    capital: "Basseterre",
    note: null,
    region: "Americas",
    subregion: "Caribbean",
    languages: ["English"],
    demonym: "Kittitian or Nevisian",
  },
  KOR: {
    iso3: "KOR",
    id: "south-korea",
    capital: "Seoul",
    note: null,
    region: "Asia",
    subregion: "Eastern Asia",
    languages: ["Korean"],
    demonym: "South Korean",
  },
  KWT: {
    iso3: "KWT",
    id: "kuwait",
    capital: "Kuwait City",
    note: null,
    region: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic"],
    demonym: "Kuwaiti",
  },
  LAO: {
    iso3: "LAO",
    id: "laos",
    capital: "Vientiane",
    note: null,
    region: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["Lao"],
    demonym: "Laotian",
  },
  LBN: {
    iso3: "LBN",
    id: "lebanon",
    capital: "Beirut",
    note: null,
    region: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic", "French"],
    demonym: "Lebanese",
  },
  LBR: {
    iso3: "LBR",
    id: "liberia",
    capital: "Monrovia",
    note: null,
    region: "Africa",
    subregion: "Western Africa",
    languages: ["English"],
    demonym: "Liberian",
  },
  LBY: {
    iso3: "LBY",
    id: "libya",
    capital: "Tripoli",
    note: null,
    region: "Africa",
    subregion: "Northern Africa",
    languages: ["Arabic"],
    demonym: "Libyan",
  },
  LCA: {
    iso3: "LCA",
    id: "saint-lucia",
    capital: "Castries",
    note: null,
    region: "Americas",
    subregion: "Caribbean",
    languages: ["English"],
    demonym: "Saint Lucian",
  },
  LIE: {
    iso3: "LIE",
    id: "liechtenstein",
    capital: "Vaduz",
    note: null,
    region: "Europe",
    subregion: "Western Europe",
    languages: ["German"],
    demonym: "Liechtensteiner",
  },
  LKA: {
    iso3: "LKA",
    id: "sri-lanka",
    capital: "Colombo",
    note: null,
    region: "Asia",
    subregion: "Southern Asia",
    languages: ["Sinhala", "Tamil"],
    demonym: "Sri Lankan",
  },
  LSO: {
    iso3: "LSO",
    id: "lesotho",
    capital: "Maseru",
    note: null,
    region: "Africa",
    subregion: "Southern Africa",
    languages: ["English", "Sotho"],
    demonym: "Mosotho",
  },
  LTU: {
    iso3: "LTU",
    id: "lithuania",
    capital: "Vilnius",
    note: null,
    region: "Europe",
    subregion: "Northern Europe",
    languages: ["Lithuanian"],
    demonym: "Lithuanian",
  },
  LUX: {
    iso3: "LUX",
    id: "luxembourg",
    capital: "Luxembourg",
    note: null,
    region: "Europe",
    subregion: "Western Europe",
    languages: ["German", "French", "Luxembourgish"],
    demonym: "Luxembourger",
  },
  LVA: {
    iso3: "LVA",
    id: "latvia",
    capital: "Riga",
    note: null,
    region: "Europe",
    subregion: "Northern Europe",
    languages: ["Latvian"],
    demonym: "Latvian",
  },
  MAR: {
    iso3: "MAR",
    id: "morocco",
    capital: "Rabat",
    note: null,
    region: "Africa",
    subregion: "Northern Africa",
    languages: ["Arabic", "Berber"],
    demonym: "Moroccan",
  },
  MCO: {
    iso3: "MCO",
    id: "monaco",
    capital: "Monaco",
    note: null,
    region: "Europe",
    subregion: "Western Europe",
    languages: ["French"],
    demonym: "Monegasque",
  },
  MDA: {
    iso3: "MDA",
    id: "moldova",
    capital: "Chișinău",
    note: null,
    region: "Europe",
    subregion: "Eastern Europe",
    languages: ["Moldavian"],
    demonym: "Moldovan",
  },
  MDG: {
    iso3: "MDG",
    id: "madagascar",
    capital: "Antananarivo",
    note: null,
    region: "Africa",
    subregion: "Eastern Africa",
    languages: ["French", "Malagasy"],
    demonym: "Malagasy",
  },
  MDV: {
    iso3: "MDV",
    id: "maldives",
    capital: "Malé",
    note: null,
    region: "Asia",
    subregion: "Southern Asia",
    languages: ["Maldivian"],
    demonym: "Maldivan",
  },
  MEX: {
    iso3: "MEX",
    id: "mexico",
    capital: "Mexico City",
    note: null,
    region: "Americas",
    subregion: "North America",
    languages: ["Spanish"],
    demonym: "Mexican",
  },
  MHL: {
    iso3: "MHL",
    id: "marshall-islands",
    capital: "Majuro",
    note: null,
    region: "Oceania",
    subregion: "Micronesia",
    languages: ["English", "Marshallese"],
    demonym: "Marshallese",
  },
  MKD: {
    iso3: "MKD",
    id: "north-macedonia",
    capital: "Skopje",
    note: null,
    region: "Europe",
    subregion: "Southeast Europe",
    languages: ["Macedonian"],
    demonym: "Macedonian",
  },
  MLI: {
    iso3: "MLI",
    id: "mali",
    capital: "Bamako",
    note: null,
    region: "Africa",
    subregion: "Western Africa",
    languages: ["French"],
    demonym: "Malian",
  },
  MLT: {
    iso3: "MLT",
    id: "malta",
    capital: "Valletta",
    note: null,
    region: "Europe",
    subregion: "Southern Europe",
    languages: ["English", "Maltese"],
    demonym: "Maltese",
  },
  MMR: {
    iso3: "MMR",
    id: "myanmar",
    capital: "Naypyidaw",
    note: null,
    region: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["Burmese"],
    demonym: "Burmese",
  },
  MNE: {
    iso3: "MNE",
    id: "montenegro",
    capital: "Podgorica",
    note: null,
    region: "Europe",
    subregion: "Southeast Europe",
    languages: ["Montenegrin"],
    demonym: "Montenegrin",
  },
  MNG: {
    iso3: "MNG",
    id: "mongolia",
    capital: "Ulan Bator",
    note: null,
    region: "Asia",
    subregion: "Eastern Asia",
    languages: ["Mongolian"],
    demonym: "Mongolian",
  },
  MOZ: {
    iso3: "MOZ",
    id: "mozambique",
    capital: "Maputo",
    note: null,
    region: "Africa",
    subregion: "Eastern Africa",
    languages: ["Portuguese"],
    demonym: "Mozambican",
  },
  MRT: {
    iso3: "MRT",
    id: "mauritania",
    capital: "Nouakchott",
    note: null,
    region: "Africa",
    subregion: "Western Africa",
    languages: ["Arabic"],
    demonym: "Mauritanian",
  },
  MUS: {
    iso3: "MUS",
    id: "mauritius",
    capital: "Port Louis",
    note: null,
    region: "Africa",
    subregion: "Eastern Africa",
    languages: ["English", "French", "Mauritian Creole"],
    demonym: "Mauritian",
  },
  MWI: {
    iso3: "MWI",
    id: "malawi",
    capital: "Lilongwe",
    note: null,
    region: "Africa",
    subregion: "Eastern Africa",
    languages: ["English", "Chewa"],
    demonym: "Malawian",
  },
  MYS: {
    iso3: "MYS",
    id: "malaysia",
    capital: "Kuala Lumpur",
    note: null,
    region: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["English", "Malay"],
    demonym: "Malaysian",
  },
  NAM: {
    iso3: "NAM",
    id: "namibia",
    capital: "Windhoek",
    note: null,
    region: "Africa",
    subregion: "Southern Africa",
    languages: [
      "Afrikaans",
      "German",
      "English",
      "Herero",
      "Khoekhoe",
      "Kwangali",
      "Lozi",
      "Ndonga",
      "Tswana",
    ],
    demonym: "Namibian",
  },
  NER: {
    iso3: "NER",
    id: "niger",
    capital: "Niamey",
    note: null,
    region: "Africa",
    subregion: "Western Africa",
    languages: ["French"],
    demonym: "Nigerien",
  },
  NGA: {
    iso3: "NGA",
    id: "nigeria",
    capital: "Abuja",
    note: null,
    region: "Africa",
    subregion: "Western Africa",
    languages: ["English"],
    demonym: "Nigerian",
  },
  NIC: {
    iso3: "NIC",
    id: "nicaragua",
    capital: "Managua",
    note: null,
    region: "Americas",
    subregion: "Central America",
    languages: ["Spanish"],
    demonym: "Nicaraguan",
  },
  NLD: {
    iso3: "NLD",
    id: "netherlands",
    capital: "Amsterdam",
    note: null,
    region: "Europe",
    subregion: "Western Europe",
    languages: ["Dutch"],
    demonym: "Dutch",
  },
  NOR: {
    iso3: "NOR",
    id: "norway",
    capital: "Oslo",
    note: null,
    region: "Europe",
    subregion: "Northern Europe",
    languages: ["Norwegian Nynorsk", "Norwegian Bokmål", "Sami"],
    demonym: "Norwegian",
  },
  NPL: {
    iso3: "NPL",
    id: "nepal",
    capital: "Kathmandu",
    note: null,
    region: "Asia",
    subregion: "Southern Asia",
    languages: ["Nepali"],
    demonym: "Nepalese",
  },
  NRU: {
    iso3: "NRU",
    id: "nauru",
    capital: "Yaren",
    note: null,
    region: "Oceania",
    subregion: "Micronesia",
    languages: ["English", "Nauru"],
    demonym: "Nauruan",
  },
  NZL: {
    iso3: "NZL",
    id: "new-zealand",
    capital: "Wellington",
    note: null,
    region: "Oceania",
    subregion: "Australia and New Zealand",
    languages: ["English", "Māori", "New Zealand Sign Language"],
    demonym: "New Zealander",
  },
  OMN: {
    iso3: "OMN",
    id: "oman",
    capital: "Muscat",
    note: null,
    region: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic"],
    demonym: "Omani",
  },
  PAK: {
    iso3: "PAK",
    id: "pakistan",
    capital: "Islamabad",
    note: null,
    region: "Asia",
    subregion: "Southern Asia",
    languages: ["English", "Urdu"],
    demonym: "Pakistani",
  },
  PAN: {
    iso3: "PAN",
    id: "panama",
    capital: "Panama City",
    note: null,
    region: "Americas",
    subregion: "Central America",
    languages: ["Spanish"],
    demonym: "Panamanian",
  },
  PER: {
    iso3: "PER",
    id: "peru",
    capital: "Lima",
    note: null,
    region: "Americas",
    subregion: "South America",
    languages: ["Aymara", "Quechua", "Spanish"],
    demonym: "Peruvian",
  },
  PHL: {
    iso3: "PHL",
    id: "philippines",
    capital: "Manila",
    note: null,
    region: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["English", "Filipino"],
    demonym: "Filipino",
  },
  PLW: {
    iso3: "PLW",
    id: "palau",
    capital: "Ngerulmud",
    note: null,
    region: "Oceania",
    subregion: "Micronesia",
    languages: ["English", "Palauan"],
    demonym: "Palauan",
  },
  PNG: {
    iso3: "PNG",
    id: "papua-new-guinea",
    capital: "Port Moresby",
    note: null,
    region: "Oceania",
    subregion: "Melanesia",
    languages: ["English", "Hiri Motu", "Tok Pisin"],
    demonym: "Papua New Guinean",
  },
  POL: {
    iso3: "POL",
    id: "poland",
    capital: "Warsaw",
    note: null,
    region: "Europe",
    subregion: "Central Europe",
    languages: ["Polish"],
    demonym: "Polish",
  },
  PRK: {
    iso3: "PRK",
    id: "north-korea",
    capital: "Pyongyang",
    note: null,
    region: "Asia",
    subregion: "Eastern Asia",
    languages: ["Korean"],
    demonym: "North Korean",
  },
  PRT: {
    iso3: "PRT",
    id: "portugal",
    capital: "Lisbon",
    note: null,
    region: "Europe",
    subregion: "Southern Europe",
    languages: ["Portuguese"],
    demonym: "Portuguese",
  },
  PRY: {
    iso3: "PRY",
    id: "paraguay",
    capital: "Asunción",
    note: null,
    region: "Americas",
    subregion: "South America",
    languages: ["Guaraní", "Spanish"],
    demonym: "Paraguayan",
  },
  PSE: {
    iso3: "PSE",
    id: "palestine",
    capital: "Ramallah (administrative seat)",
    note: "Palestine proclaims East Jerusalem as its capital; the administrative seat is Ramallah.",
    region: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic"],
    demonym: "Palestinian",
  },
  QAT: {
    iso3: "QAT",
    id: "qatar",
    capital: "Doha",
    note: null,
    region: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic"],
    demonym: "Qatari",
  },
  ROU: {
    iso3: "ROU",
    id: "romania",
    capital: "Bucharest",
    note: null,
    region: "Europe",
    subregion: "Southeast Europe",
    languages: ["Romanian"],
    demonym: "Romanian",
  },
  RUS: {
    iso3: "RUS",
    id: "russia",
    capital: "Moscow",
    note: null,
    region: "Europe",
    subregion: "Eastern Europe",
    languages: ["Russian"],
    demonym: "Russian",
  },
  RWA: {
    iso3: "RWA",
    id: "rwanda",
    capital: "Kigali",
    note: null,
    region: "Africa",
    subregion: "Eastern Africa",
    languages: ["English", "French", "Kinyarwanda"],
    demonym: "Rwandan",
  },
  SAU: {
    iso3: "SAU",
    id: "saudi-arabia",
    capital: "Riyadh",
    note: null,
    region: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic"],
    demonym: "Saudi Arabian",
  },
  SDN: {
    iso3: "SDN",
    id: "sudan",
    capital: "Khartoum",
    note: null,
    region: "Africa",
    subregion: "Northern Africa",
    languages: ["Arabic", "English"],
    demonym: "Sudanese",
  },
  SEN: {
    iso3: "SEN",
    id: "senegal",
    capital: "Dakar",
    note: null,
    region: "Africa",
    subregion: "Western Africa",
    languages: ["French"],
    demonym: "Senegalese",
  },
  SGP: {
    iso3: "SGP",
    id: "singapore",
    capital: "Singapore",
    note: null,
    region: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["English", "Malay", "Tamil", "Chinese"],
    demonym: "Singaporean",
  },
  SLB: {
    iso3: "SLB",
    id: "solomon-islands",
    capital: "Honiara",
    note: null,
    region: "Oceania",
    subregion: "Melanesia",
    languages: ["English"],
    demonym: "Solomon Islander",
  },
  SLE: {
    iso3: "SLE",
    id: "sierra-leone",
    capital: "Freetown",
    note: null,
    region: "Africa",
    subregion: "Western Africa",
    languages: ["English"],
    demonym: "Sierra Leonean",
  },
  SLV: {
    iso3: "SLV",
    id: "el-salvador",
    capital: "San Salvador",
    note: null,
    region: "Americas",
    subregion: "Central America",
    languages: ["Spanish"],
    demonym: "Salvadoran",
  },
  SMR: {
    iso3: "SMR",
    id: "san-marino",
    capital: "City of San Marino",
    note: null,
    region: "Europe",
    subregion: "Southern Europe",
    languages: ["Italian"],
    demonym: "Sammarinese",
  },
  SOM: {
    iso3: "SOM",
    id: "somalia",
    capital: "Mogadishu",
    note: null,
    region: "Africa",
    subregion: "Eastern Africa",
    languages: ["Arabic", "Somali"],
    demonym: "Somali",
  },
  SRB: {
    iso3: "SRB",
    id: "serbia",
    capital: "Belgrade",
    note: null,
    region: "Europe",
    subregion: "Southeast Europe",
    languages: ["Serbian"],
    demonym: "Serbian",
  },
  SSD: {
    iso3: "SSD",
    id: "south-sudan",
    capital: "Juba",
    note: null,
    region: "Africa",
    subregion: "Middle Africa",
    languages: ["English"],
    demonym: "South Sudanese",
  },
  STP: {
    iso3: "STP",
    id: "sao-tome-and-principe",
    capital: "São Tomé",
    note: null,
    region: "Africa",
    subregion: "Middle Africa",
    languages: ["Portuguese"],
    demonym: "Sao Tomean",
  },
  SUR: {
    iso3: "SUR",
    id: "suriname",
    capital: "Paramaribo",
    note: null,
    region: "Americas",
    subregion: "South America",
    languages: ["Dutch"],
    demonym: "Surinamer",
  },
  SVK: {
    iso3: "SVK",
    id: "slovakia",
    capital: "Bratislava",
    note: null,
    region: "Europe",
    subregion: "Central Europe",
    languages: ["Slovak"],
    demonym: "Slovak",
  },
  SVN: {
    iso3: "SVN",
    id: "slovenia",
    capital: "Ljubljana",
    note: null,
    region: "Europe",
    subregion: "Central Europe",
    languages: ["Slovene"],
    demonym: "Slovene",
  },
  SWE: {
    iso3: "SWE",
    id: "sweden",
    capital: "Stockholm",
    note: null,
    region: "Europe",
    subregion: "Northern Europe",
    languages: ["Swedish"],
    demonym: "Swedish",
  },
  SWZ: {
    iso3: "SWZ",
    id: "eswatini",
    capital: "Lobamba",
    note: null,
    region: "Africa",
    subregion: "Southern Africa",
    languages: ["English", "Swazi"],
    demonym: "Swazi",
  },
  SYC: {
    iso3: "SYC",
    id: "seychelles",
    capital: "Victoria",
    note: null,
    region: "Africa",
    subregion: "Eastern Africa",
    languages: ["Seychellois Creole", "English", "French"],
    demonym: "Seychellois",
  },
  SYR: {
    iso3: "SYR",
    id: "syria",
    capital: "Damascus",
    note: null,
    region: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic"],
    demonym: "Syrian",
  },
  TCD: {
    iso3: "TCD",
    id: "chad",
    capital: "N'Djamena",
    note: null,
    region: "Africa",
    subregion: "Middle Africa",
    languages: ["Arabic", "French"],
    demonym: "Chadian",
  },
  TGO: {
    iso3: "TGO",
    id: "togo",
    capital: "Lomé",
    note: null,
    region: "Africa",
    subregion: "Western Africa",
    languages: ["French"],
    demonym: "Togolese",
  },
  THA: {
    iso3: "THA",
    id: "thailand",
    capital: "Bangkok",
    note: null,
    region: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["Thai"],
    demonym: "Thai",
  },
  TJK: {
    iso3: "TJK",
    id: "tajikistan",
    capital: "Dushanbe",
    note: null,
    region: "Asia",
    subregion: "Central Asia",
    languages: ["Russian", "Tajik"],
    demonym: "Tadzhik",
  },
  TKM: {
    iso3: "TKM",
    id: "turkmenistan",
    capital: "Ashgabat",
    note: null,
    region: "Asia",
    subregion: "Central Asia",
    languages: ["Russian", "Turkmen"],
    demonym: "Turkmen",
  },
  TLS: {
    iso3: "TLS",
    id: "timor-leste",
    capital: "Dili",
    note: null,
    region: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["Portuguese", "Tetum"],
    demonym: "East Timorese",
  },
  TON: {
    iso3: "TON",
    id: "tonga",
    capital: "Nuku'alofa",
    note: null,
    region: "Oceania",
    subregion: "Polynesia",
    languages: ["English", "Tongan"],
    demonym: "Tongan",
  },
  TTO: {
    iso3: "TTO",
    id: "trinidad-and-tobago",
    capital: "Port of Spain",
    note: null,
    region: "Americas",
    subregion: "Caribbean",
    languages: ["English"],
    demonym: "Trinidadian",
  },
  TUN: {
    iso3: "TUN",
    id: "tunisia",
    capital: "Tunis",
    note: null,
    region: "Africa",
    subregion: "Northern Africa",
    languages: ["Arabic"],
    demonym: "Tunisian",
  },
  TUR: {
    iso3: "TUR",
    id: "turkiye",
    capital: "Ankara",
    note: null,
    region: "Asia",
    subregion: "Western Asia",
    languages: ["Turkish"],
    demonym: "Turkish",
  },
  TUV: {
    iso3: "TUV",
    id: "tuvalu",
    capital: "Funafuti",
    note: null,
    region: "Oceania",
    subregion: "Polynesia",
    languages: ["English", "Tuvaluan"],
    demonym: "Tuvaluan",
  },
  TZA: {
    iso3: "TZA",
    id: "tanzania",
    capital: "Dodoma",
    note: null,
    region: "Africa",
    subregion: "Eastern Africa",
    languages: ["English", "Swahili"],
    demonym: "Tanzanian",
  },
  UGA: {
    iso3: "UGA",
    id: "uganda",
    capital: "Kampala",
    note: null,
    region: "Africa",
    subregion: "Eastern Africa",
    languages: ["English", "Swahili"],
    demonym: "Ugandan",
  },
  UKR: {
    iso3: "UKR",
    id: "ukraine",
    capital: "Kyiv",
    note: null,
    region: "Europe",
    subregion: "Eastern Europe",
    languages: ["Ukrainian"],
    demonym: "Ukrainian",
  },
  URY: {
    iso3: "URY",
    id: "uruguay",
    capital: "Montevideo",
    note: null,
    region: "Americas",
    subregion: "South America",
    languages: ["Spanish"],
    demonym: "Uruguayan",
  },
  USA: {
    iso3: "USA",
    id: "united-states",
    capital: "Washington D.C.",
    note: null,
    region: "Americas",
    subregion: "North America",
    languages: ["English"],
    demonym: "American",
  },
  UZB: {
    iso3: "UZB",
    id: "uzbekistan",
    capital: "Tashkent",
    note: null,
    region: "Asia",
    subregion: "Central Asia",
    languages: ["Russian", "Uzbek"],
    demonym: "Uzbekistani",
  },
  VAT: {
    iso3: "VAT",
    id: "vatican-city",
    capital: "Vatican City",
    note: null,
    region: "Europe",
    subregion: "Southern Europe",
    languages: ["Italian", "Latin"],
    demonym: "Vatican",
  },
  VCT: {
    iso3: "VCT",
    id: "saint-vincent-and-the-grenadines",
    capital: "Kingstown",
    note: null,
    region: "Americas",
    subregion: "Caribbean",
    languages: ["English"],
    demonym: "Saint Vincentian",
  },
  VEN: {
    iso3: "VEN",
    id: "venezuela",
    capital: "Caracas",
    note: null,
    region: "Americas",
    subregion: "South America",
    languages: ["Spanish"],
    demonym: "Venezuelan",
  },
  VNM: {
    iso3: "VNM",
    id: "vietnam",
    capital: "Hanoi",
    note: null,
    region: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["Vietnamese"],
    demonym: "Vietnamese",
  },
  VUT: {
    iso3: "VUT",
    id: "vanuatu",
    capital: "Port Vila",
    note: null,
    region: "Oceania",
    subregion: "Melanesia",
    languages: ["Bislama", "English", "French"],
    demonym: "Ni-Vanuatu",
  },
  WSM: {
    iso3: "WSM",
    id: "samoa",
    capital: "Apia",
    note: null,
    region: "Oceania",
    subregion: "Polynesia",
    languages: ["English", "Samoan"],
    demonym: "Samoan",
  },
  YEM: {
    iso3: "YEM",
    id: "yemen",
    capital: "Sana'a",
    note: null,
    region: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic"],
    demonym: "Yemeni",
  },
  ZAF: {
    iso3: "ZAF",
    id: "south-africa",
    capital: "Pretoria, Bloemfontein, Cape Town",
    note: null,
    region: "Africa",
    subregion: "Southern Africa",
    languages: [
      "Afrikaans",
      "English",
      "Southern Ndebele",
      "Northern Sotho",
      "Southern Sotho",
      "Swazi",
      "Tswana",
      "Tsonga",
      "Venda",
      "Xhosa",
      "Zulu",
    ],
    demonym: "South African",
  },
  ZMB: {
    iso3: "ZMB",
    id: "zambia",
    capital: "Lusaka",
    note: null,
    region: "Africa",
    subregion: "Eastern Africa",
    languages: ["English"],
    demonym: "Zambian",
  },
  ZWE: {
    iso3: "ZWE",
    id: "zimbabwe",
    capital: "Harare",
    note: null,
    region: "Africa",
    subregion: "Eastern Africa",
    languages: [
      "Chibarwe",
      "English",
      "Kalanga",
      "Khoisan",
      "Ndau",
      "Northern Ndebele",
      "Chewa",
      "Shona",
      "Sotho",
      "Tonga",
      "Tswana",
      "Tsonga",
      "Venda",
      "Xhosa",
      "Zimbabwean Sign Language",
    ],
    demonym: "Zimbabwean",
  },
  CYN: {
    iso3: "CYN",
    id: "northern-cyprus",
    capital: "North Nicosia",
    note: "Declared in 1983 and recognized only by Türkiye.",
    region: "Europe",
    subregion: "Southern Europe",
    languages: ["Turkish"],
    demonym: "Turkish Cypriot",
  },
};

export const WORLD_REGIONS_EN: Record<string, string> = {
  Asya: "Asia",
  Afrika: "Africa",
  Avrupa: "Europe",
  Amerika: "Americas",
  Okyanusya: "Oceania",
};
