import type { Metadata } from "next";
import Link from "next/link";
import EnglishMachNumberCalculator from "../../../../components/EnglishMachNumberCalculator";
import { buildFaqSchema, type FaqItem } from "../../../../converter/faqSchema";
import { buildSiteUrl } from "../../../../siteConfig";

const pagePath = "/en/engineering-calculators/dimensionless-numbers/mach-number-calculator";
const faqItems: FaqItem[] = [
  { question: "What is Mach number?", answer: "Mach number is the ratio of an object's or flow's speed to the local speed of sound: M = V/a. It is dimensionless." },
  { question: "Why does this calculator ask for static temperature?", answer: "In the ideal-gas mode, it calculates the local speed of sound as a = sqrt(gamma R T). That relation requires absolute static temperature, not total or stagnation temperature." },
  { question: "Is Mach 1 always 343 m/s?", answer: "No. The speed of sound changes with gas composition and local thermodynamic state. About 343 m/s is a familiar dry-air value near 20 °C, not a universal constant." },
];

export const metadata: Metadata = { title: "Mach Number Calculator (M = V / a)", description: "Calculate Mach number from a known local speed of sound, or estimate it for an ideal gas from static temperature and gas properties.", alternates: { canonical: pagePath, languages: { en: pagePath } }, openGraph: { title: "Mach Number Calculator", description: "Find Mach number from speed and a local or ideal-gas speed of sound.", url: buildSiteUrl(pagePath), siteName: "BirimCeviri.app", locale: "en_US", type: "article" } };
function serializeJsonLd(data: object) { return JSON.stringify(data).replace(/</g, "\\u003c"); }

export default function EnglishMachNumberPage() {
  const breadcrumbSchema = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: buildSiteUrl("/en") }, { "@type": "ListItem", position: 2, name: "Dimensionless Numbers", item: buildSiteUrl("/en/engineering-calculators/dimensionless-numbers") }, { "@type": "ListItem", position: 3, name: "Mach Number Calculator", item: buildSiteUrl(pagePath) }] };
  return <main className="all-conversions-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(breadcrumbSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(buildFaqSchema(faqItems)) }} /><div className="all-conversions-shell"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/en">Home</Link><span aria-hidden="true">›</span><Link href="/en/engineering-calculators/dimensionless-numbers">Dimensionless Numbers</Link><span aria-hidden="true">›</span><span>Mach Number Calculator</span></nav><header className="all-conversions-header"><h1>Mach Number Calculator</h1><p>Calculate Mach number from a known local speed of sound, or estimate the sound speed from ideal-gas properties and static temperature.</p></header><EnglishMachNumberCalculator /><article className="category-article-content"><h2>Method and variables</h2><p><strong>Mach number:</strong> M = V/a, where <strong>V</strong> is the object or flow speed and <strong>a</strong> is the local speed of sound. In ideal-gas mode, this page uses a = √(γRT).</p><ul><li><strong>γ</strong> — heat-capacity ratio (Cp/Cv)</li><li><strong>R</strong> — specific gas constant for the gas</li><li><strong>T</strong> — absolute static temperature in kelvin</li></ul><h2>Worked example</h2><p>For air approximated as γ = 1.4 and R = 287.05 J/(kg·K) at 15 °C (288.15 K), the calculated sound speed is about 340.3 m/s. A speed of 250 m/s therefore gives M ≈ 0.735.</p><h2>How to read the result</h2><p>Mach is a ratio, not a speed unit. Labels such as low subsonic, subsonic, transonic, supersonic and hypersonic are useful shorthand; their exact boundaries vary by application. Near Mach 1, compressibility effects and the details of the geometry quickly become important.</p><h2>Important limits</h2><p>The ideal-gas calculation assumes a calorically perfect gas and uses static temperature. It does not model humidity, atmospheric pressure variation directly, shocks, local acceleration around a body, temperature recovery, high-temperature dissociation, real-gas effects or structural/aerodynamic safety margins. Use a validated flow model and applicable standards for design work.</p><h2>Reference</h2><ul><li><a href="https://www1.grc.nasa.gov/beginners-guide-to-aeronautics/mass-flow-rate-equations/" target="_blank" rel="noreferrer">NASA Glenn: Mach number and ideal-gas speed-of-sound relation</a></li><li><a href="https://www.nist.gov/pml/special-publication-811" target="_blank" rel="noreferrer">NIST Guide for the Use of the International System of Units</a></li></ul><h2>Related tools</h2><p><Link href="/en/calculators/reynolds-number">Reynolds Number Calculator</Link> · <Link href="/en/engineering-calculators/dimensionless-numbers/prandtl-number-calculator">Prandtl Number Calculator</Link> · <Link href="/en/engineering-calculators/dimensionless-numbers">Dimensionless Numbers Calculators</Link></p></article></div></main>;
}
