import type { Metadata } from "next";
import Link from "next/link";
import StaticPageLayout from "../../../components/StaticPageLayout";
import { buildSiteUrl } from "../../../siteConfig";

const pagePath = "/en/engineering-calculators/mechanics-materials";
const tools = [
  { href: "/en/engineering-calculators/mechanics-materials/thin-wall-cylinder-stress-calculator", title: "Thin-Wall Cylinder Stress Calculator", description: "Estimate ideal hoop and longitudinal stress for a thin-walled cylinder under internal pressure." },
  { href: "/en/engineering-calculators/mechanics-materials/section-properties-calculator", title: "Section Properties Calculator", description: "Calculate area, second moment of area, section modulus and polar moment for an ideal solid rectangle or circle." },
  { href: "/en/engineering-calculators/mechanics-materials/euler-buckling-calculator", title: "Euler Buckling Calculator", description: "Calculate ideal elastic critical load for a slender column from support condition, length, modulus and second moment of area." },
  { href: "/en/engineering-calculators/mechanics-materials/shaft-torsion-calculator", title: "Shaft Torsion Calculator", description: "Calculate shear stress and angle of twist for a uniform solid circular shaft under a stated torque." },
  { href: "/en/engineering-calculators/mechanics-materials/cantilever-beam-deflection-calculator", title: "Cantilever Beam Deflection Calculator", description: "Estimate tip deflection, bending stress and end rotation for a rectangular cantilever with one free-end point load." },
  { href: "/en/engineering-calculators/mechanics-materials/stress-strain-calculator", title: "Stress & Strain Calculator", description: "Calculate engineering stress, strain and a secant modulus from force, area and measured extension." },
  { href: "/en/calculators/elastic-elongation", title: "Elastic Elongation Calculator", description: "Estimate axial stress and linear-elastic length change using a selected Young's modulus." },
  { href: "/en/calculators/thermal-expansion", title: "Thermal Expansion Calculator", description: "Estimate a material's free linear length change caused by heating or cooling." },
];
export const metadata: Metadata = { title: "Mechanics & Materials Calculators", description: "Engineering calculators for stress and strain, beam deflection, shaft torsion, buckling, section properties and thin-wall cylinder stress.", alternates: { canonical: pagePath, languages: { en: pagePath } }, openGraph: { title: "Mechanics & Materials Calculators", description: "A focused engineering hub for material response, member loading and simplified structural-mechanics checks.", url: buildSiteUrl(pagePath), siteName: "BirimCeviri.app", locale: "en_US", type: "website" } };
function serializeJsonLd(data: object) { return JSON.stringify(data).replace(/</g, "\\u003c"); }
export default function MechanicsMaterialsHubPage() { const schema = { "@context": "https://schema.org", "@type": "CollectionPage", name: "Mechanics & Materials Calculators", description: "Engineering calculators for stress and strain, beam deflection, shaft torsion, buckling, section properties and thin-wall cylinder stress.", url: buildSiteUrl(pagePath), inLanguage: "en-US", mainEntity: { "@type": "ItemList", numberOfItems: tools.length, itemListElement: tools.map((tool, index) => ({ "@type": "ListItem", position: index + 1, name: tool.title, url: buildSiteUrl(tool.href) })) } }; return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(schema) }} /><StaticPageLayout locale="en" breadcrumbAriaLabel="Breadcrumb" breadcrumbs={[{ href: "/en", label: "Home" }, { href: "/en/engineering-calculators", label: "Engineering Calculators" }, { label: "Mechanics & Materials" }]} title="Mechanics & Materials Calculators" description="A focused engineering cluster for simple checks of material response, member loading, bending, torsion and stability." sections={[{ heading: "Live calculators", content: <ul className="category-calculator-list">{tools.map((tool) => <li key={tool.href}><Link className="category-calculator-card" href={tool.href}><strong>{tool.title}</strong><span>{tool.description}</span></Link></li>)}</ul> }, { heading: "Use these as first checks", content: <ol className="engineering-hub-steps"><li>State the material, loading direction, actual cross-section and governing design standard.</li><li>Use elastic formulas only while response is plausibly linear and the geometry remains valid.</li><li>Check yield, buckling, fatigue, connections and safety factors separately before a design decision.</li></ol> }]} /></>; }
