import type { Metadata } from "next";
import Link from "next/link";
import EnglishPrandtlNumberCalculator from "../../../../components/EnglishPrandtlNumberCalculator";
import { buildFaqSchema, type FaqItem } from "../../../../converter/faqSchema";
import { buildSiteUrl } from "../../../../siteConfig";

const pagePath = "/en/engineering-calculators/dimensionless-numbers/prandtl-number-calculator";
const faqItems: FaqItem[] = [
  { question: "What does the Prandtl number represent?", answer: "It is the ratio of momentum diffusivity to thermal diffusivity. It helps compare the relative development of velocity and thermal boundary layers in a fluid." },
  { question: "How is Prandtl number calculated?", answer: "Use Pr = μCp/k when dynamic viscosity, specific heat and thermal conductivity are known. The equivalent form is Pr = ν/α." },
  { question: "Does Prandtl number calculate heat transfer coefficient?", answer: "No. It is an input to many convection correlations. A heat-transfer coefficient additionally depends on geometry, flow conditions and an applicable correlation." },
];

export const metadata: Metadata = { title: "Prandtl Number Calculator (Pr = μCp / k)", description: "Calculate the dimensionless Prandtl number from fluid properties or from momentum and thermal diffusivity, with SI and common Imperial units.", alternates: { canonical: pagePath, languages: { en: pagePath } }, openGraph: { title: "Prandtl Number Calculator", description: "Calculate Prandtl number from fluid thermophysical properties.", url: buildSiteUrl(pagePath), siteName: "BirimCeviri.app", locale: "en_US", type: "article" } };
function serializeJsonLd(data: object) { return JSON.stringify(data).replace(/</g, "\\u003c"); }

export default function EnglishPrandtlNumberPage() {
  const breadcrumbSchema = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: buildSiteUrl("/en") }, { "@type": "ListItem", position: 2, name: "Dimensionless Numbers", item: buildSiteUrl("/en/engineering-calculators/dimensionless-numbers") }, { "@type": "ListItem", position: 3, name: "Prandtl Number Calculator", item: buildSiteUrl(pagePath) }] };
  return <main className="all-conversions-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(breadcrumbSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(buildFaqSchema(faqItems)) }} /><div className="all-conversions-shell"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/en">Home</Link><span aria-hidden="true">›</span><Link href="/en/engineering-calculators/dimensionless-numbers">Dimensionless Numbers</Link><span aria-hidden="true">›</span><span>Prandtl Number Calculator</span></nav><header className="all-conversions-header"><h1>Prandtl Number Calculator</h1><p>Calculate the dimensionless Prandtl number from consistent fluid properties. Choose direct thermophysical properties or the equivalent diffusivity form.</p></header><EnglishPrandtlNumberCalculator /><article className="category-article-content"><h2>Method and variables</h2><p><strong>Property form:</strong> Pr = μC<sub>p</sub>/k. <strong>Diffusivity form:</strong> Pr = ν/α.</p><ul><li><strong>μ</strong> — dynamic viscosity</li><li><strong>C<sub>p</sub></strong> — specific heat capacity at constant pressure</li><li><strong>k</strong> — fluid thermal conductivity</li><li><strong>ν</strong> — kinematic viscosity</li><li><strong>α</strong> — thermal diffusivity</li></ul><h2>Worked example</h2><p>For water near 20 °C, μ = 1.002 mPa·s, C<sub>p</sub> = 4182 J/(kg·K), and k = 0.598 W/(m·K). The result is Pr ≈ 7.01.</p><h2>How it connects to other tools</h2><p>Prandtl number is usually paired with Reynolds number in forced-convection correlations, or Rayleigh number in natural-convection correlations. It is an input to a correlation, not a complete heat-transfer design result.</p><h2>Important limits</h2><p>Properties vary with temperature, pressure and composition. Enter all values at the same reference state. This calculator does not choose a correlation, validate its range or calculate a heat-transfer coefficient.</p><h2>References</h2><ul><li><a href="https://openstax.org/books/college-physics/pages/12-4-viscosity-and-laminar-flow-poiseuilles-law" target="_blank" rel="noreferrer">OpenStax: Viscosity and Laminar Flow</a></li><li><a href="https://www.nist.gov/pml/special-publication-811" target="_blank" rel="noreferrer">NIST Guide for the Use of the International System of Units</a></li></ul><h2>Related tools</h2><p><Link href="/en/calculators/reynolds-number">Reynolds Number Calculator</Link> · <Link href="/en/calculators/heat-conduction">Heat Conduction Calculator</Link> · <Link href="/en/engineering-calculators/dimensionless-numbers">Dimensionless Numbers Calculators</Link></p></article></div></main>;
}
