export type CompoundEditorial = {
  id: string;
  contextTr: string;
  usesTr: string[];
  safetyTr: string;
  contextDe: string;
  usesDe: string[];
  safetyDe: string;
};

// A compound profile is indexable only after it has compound-specific
// editorial context in addition to its calculated molar-mass data.
export const compoundEditorial: CompoundEditorial[] = [
  {
    id: "su",
    contextTr: "Su, iki hidrojen ve bir oksijen atomundan oluşan yaygın bir bileşiktir. Molar kütle hesabında formüldeki iki hidrojen atomunun ayrı ayrı hesaba katılması gerekir.",
    usesTr: ["Çözücü ve proses sıvısı", "Isı transferi ve soğutma", "Gıda, temizlik ve günlük kullanım"],
    safetyTr: "Bu sayfadaki değer saf H₂O formülü içindir; içme suyu uygunluğu çözünmüş maddelere ve yerel kalite kontrollerine bağlıdır.",
    contextDe: "Wasser besteht aus zwei Wasserstoff- und einem Sauerstoffatom. Bei der Molmassenrechnung müssen die beiden Wasserstoffatome jeweils berücksichtigt werden.",
    usesDe: ["Lösungsmittel und Prozessflüssigkeit", "Wärmeübertragung und Kühlung", "Lebensmittel, Reinigung und Alltag"],
    safetyDe: "Der Wert auf dieser Seite gilt für die Formel H₂O; die Trinkwasserqualität hängt von gelösten Stoffen und lokalen Kontrollen ab.",
  },
  {
    id: "sofra-tuzu",
    contextTr: "Sodyum klorür iyonik yapılı bir tuzdur; formülündeki sodyum ve klor oranı bire birdir. Bu nedenle molar kütle, Na ve Cl atomik kütlelerinin toplamından oluşur.",
    usesTr: ["Gıda üretimi ve koruma", "Kimyasal proseslerde hammadde", "Buz çözme ve su yumuşatma"],
    safetyTr: "Gıda amaçlı kullanım ile endüstriyel kalite aynı değildir; ürün saflığı ve kullanım koşulu ayrıca değerlendirilmelidir.",
    contextDe: "Natriumchlorid ist ein Salz mit ionischer Struktur; Natrium und Chlor stehen in der Formel im Verhältnis eins zu eins. Seine Molmasse ist daher die Summe beider Atommassen.",
    usesDe: ["Lebensmittelverarbeitung und Konservierung", "Rohstoff für chemische Prozesse", "Enteisung und Wasserenthärtung"],
    safetyDe: "Lebensmittelqualität und technische Qualität sind nicht gleichzusetzen; Reinheit und Verwendungszweck müssen separat beurteilt werden.",
  },
  {
    id: "karbondioksit",
    contextTr: "Karbondioksit bir karbon ve iki oksijen atomu içerir. Gazın moleküler yapısı molar kütle ve gaz miktarı hesaplarında doğrudan kullanılır.",
    usesTr: ["İçeceklerde kontrollü karbonlama", "Yangın söndürme sistemleri", "Soğutma ve proses uygulamaları"],
    safetyTr: "Karbondioksit yanıcı değildir ancak kapalı alanlarda oksijeni seyreltebilir; gazla çalışma ortamları uygun havalandırma gerektirir.",
    contextDe: "Kohlendioxid enthält ein Kohlenstoff- und zwei Sauerstoffatome. Seine Molekülstruktur wird direkt für Molmassen- und Gasmengenrechnungen verwendet.",
    usesDe: ["Kontrollierte Karbonisierung von Getränken", "Feuerlöschanlagen", "Kühl- und Prozessanwendungen"],
    safetyDe: "Kohlendioxid ist nicht brennbar, kann in geschlossenen Räumen aber Sauerstoff verdrängen; Arbeitsbereiche benötigen geeignete Lüftung.",
  },
  {
    id: "oksijen-gazi",
    contextTr: "Oksijen gazı iki oksijen atomundan oluşan O₂ molekülüdür. Elementin tek atomlu molar kütlesi ile O₂ gazının molar kütlesi bu nedenle aynı değildir.",
    usesTr: ["Tıbbi oksijen sistemleri", "Metal ve çelik prosesleri", "Kimyasal oksidasyon"],
    safetyTr: "Oksijen yanıcı değildir fakat yanmayı hızlandırır; oksijen zengin ortamlar için özel yangın güvenliği gerekir.",
    contextDe: "Sauerstoffgas ist das zweiatomige Molekül O₂. Die Molmasse des Gases unterscheidet sich deshalb von der eines einzelnen Sauerstoffatoms.",
    usesDe: ["Medizinische Sauerstoffsysteme", "Metall- und Stahlprozesse", "Chemische Oxidation"],
    safetyDe: "Sauerstoff ist nicht brennbar, beschleunigt aber Verbrennungen; sauerstoffangereicherte Bereiche brauchen besonderen Brandschutz.",
  },
  {
    id: "sodyum-hidroksit",
    contextTr: "Sodyum hidroksit, NaOH formüllü güçlü bir bazdır. Bir formül biriminde sodyum, oksijen ve hidrojenin her birinden birer atom bulunur.",
    usesTr: ["Sabun ve deterjan üretimi", "pH ayarı ve kimyasal prosesler", "Kâğıt ve tekstil işlemleri"],
    safetyTr: "Aşındırıcı bir maddedir; çözeltinin derişimi ne olursa olsun uygun kişisel koruyucu ekipman ve ürün güvenlik bilgisi gerekir.",
    contextDe: "Natriumhydroxid ist eine starke Base mit der Formel NaOH. Eine Formeleinheit enthält je ein Natrium-, Sauerstoff- und Wasserstoffatom.",
    usesDe: ["Herstellung von Seifen und Reinigungsmitteln", "pH-Einstellung und Chemieprozesse", "Papier- und Textilverarbeitung"],
    safetyDe: "Der Stoff ist ätzend; unabhängig von der Konzentration sind geeignete Schutzausrüstung und das Sicherheitsdatenblatt erforderlich.",
  },
  {
    id: "hidroklorik-asit",
    contextTr: "Hidroklorik asit, suda çözünmüş hidrojen klorürle ilişkilendirilen HCl formüllü bir asittir. Molar kütle hesabı H ve Cl atomlarının toplamına dayanır.",
    usesTr: ["Metal yüzey temizleme", "pH kontrolü", "Laboratuvar ve proses reaktifi"],
    safetyTr: "Aşındırıcı çözeltiler ve buharlar oluşturabilir; başka temizlik ürünleriyle karıştırılmamalı, güvenlik bilgisi izlenmelidir.",
    contextDe: "Salzsäure ist eine mit in Wasser gelöstem Chlorwasserstoff verbundene Säure mit der Formel HCl. Ihre Molmasse ergibt sich aus Wasserstoff und Chlor.",
    usesDe: ["Reinigung von Metalloberflächen", "pH-Kontrolle", "Labor- und Prozessreagenz"],
    safetyDe: "Es können ätzende Lösungen und Dämpfe entstehen; nicht mit anderen Reinigungsmitteln mischen und Sicherheitsinformationen beachten.",
  },
  {
    id: "glikoz",
    contextTr: "Glikoz, C₆H₁₂O₆ formüllü bir karbonhidrattır. Formüldeki yüksek karbon, hidrojen ve oksijen sayısı molar kütlesinin küçük inorganik bileşiklerden daha yüksek olmasına yol açar.",
    usesTr: ["Gıda bileşeni", "Biyoteknoloji fermantasyonu", "Laboratuvar ve eğitim deneyleri"],
    safetyTr: "Biyolojik veya tıbbi kullanım için bu hesap sayfası doz bilgisi yerine geçmez; ürün saflığı ve uygulama koşulları ayrıca belirlenmelidir.",
    contextDe: "Glucose ist ein Kohlenhydrat mit der Formel C₆H₁₂O₆. Die hohe Zahl an Kohlenstoff-, Wasserstoff- und Sauerstoffatomen führt zu einer höheren Molmasse als bei kleinen anorganischen Verbindungen.",
    usesDe: ["Lebensmittelbestandteil", "Biotechnologische Fermentation", "Labor- und Unterrichtsversuche"],
    safetyDe: "Für biologische oder medizinische Anwendungen ersetzt diese Rechenseite keine Dosierungsinformation; Reinheit und Einsatzbedingungen müssen separat festgelegt werden.",
  },
  {
    id: "amonyak",
    contextTr: "Amonyak NH₃ formüllü, bir azot ve üç hidrojen atomu içeren bir bileşiktir. Gaz ve sulu çözelti biçimleri uygulama ve güvenlik bakımından farklı koşullar yaratır.",
    usesTr: ["Gübre üretimi", "Soğutma sistemleri", "Kimyasal hammadde"],
    safetyTr: "Amonyak tahriş edici ve yüksek derişimde tehlikeli olabilir; sızıntı, havalandırma ve kişisel koruma prosedürleri önemlidir.",
    contextDe: "Ammoniak hat die Formel NH₃ und enthält ein Stickstoff- und drei Wasserstoffatome. Gasförmige und wässrige Formen unterscheiden sich in Anwendung und Gefährdung.",
    usesDe: ["Düngemittelherstellung", "Kälteanlagen", "Chemischer Grundstoff"],
    safetyDe: "Ammoniak wirkt reizend und kann in hoher Konzentration gefährlich sein; Leckage-, Lüftungs- und Schutzmaßnahmen sind wesentlich.",
  },
  {
    id: "sulfurik-asit",
    contextTr: "Sülfürik asit H₂SO₄ formüllüdür ve iki hidrojen, bir kükürt ile dört oksijen atomu içerir. Molar kütle hesabında özellikle dört oksijen atomunun katkısı belirgindir.",
    usesTr: ["Gübre ve kimyasal üretimi", "Akü elektroliti", "Petrol ve metal prosesleri"],
    safetyTr: "Çok aşındırıcıdır; seyreltme ve transfer işlemleri eğitimli kişilerce, ürün güvenlik bilgisine göre yapılmalıdır.",
    contextDe: "Schwefelsäure hat die Formel H₂SO₄ und enthält zwei Wasserstoff-, ein Schwefel- und vier Sauerstoffatome. Besonders die vier Sauerstoffatome tragen zur Molmasse bei.",
    usesDe: ["Düngemittel- und Chemieproduktion", "Batterieelektrolyt", "Erdöl- und Metallprozesse"],
    safetyDe: "Der Stoff ist stark ätzend; Verdünnung und Umfüllung gehören in geschulte Hände und müssen dem Sicherheitsdatenblatt folgen.",
  },
  {
    id: "kalsiyum-karbonat",
    contextTr: "Kalsiyum karbonat CaCO₃ formüllü yaygın bir mineraldir; kireçtaşı, mermer ve tebeşir gibi malzemelerde bulunur. Bir kalsiyum, bir karbon ve üç oksijen atomu içerir.",
    usesTr: ["Çimento ve yapı malzemeleri", "Kâğıt ve plastik dolgu maddesi", "Tarım ve su işlemleri"],
    safetyTr: "Doğal mineral, gıda sınıfı ve endüstriyel ürünler farklı saflıkta olabilir; kullanım uygunluğu ürün spesifikasyonuyla belirlenmelidir.",
    contextDe: "Calciumcarbonat ist ein verbreitetes Mineral mit der Formel CaCO₃ und kommt etwa in Kalkstein, Marmor und Kreide vor. Es enthält ein Calcium-, ein Kohlenstoff- und drei Sauerstoffatome.",
    usesDe: ["Zement und Baustoffe", "Füllstoff für Papier und Kunststoffe", "Landwirtschaft und Wasserbehandlung"],
    safetyDe: "Natürliches Mineral, Lebensmittelqualität und technische Produkte können sich in der Reinheit unterscheiden; die Eignung richtet sich nach der Produktspezifikation.",
  },
  {
    id: "etanol",
    contextTr: "Etanol C₂H₆O formüllü organik bir bileşiktir. Aynı atom sayısına sahip farklı düzenlenmeler farklı maddeler oluşturabileceğinden, formülün yanında maddenin adı da önemlidir.",
    usesTr: ["Çözücü ve temizlik ürünleri", "Yakıt harmanları", "Gıda ve ilaç prosesleri"],
    safetyTr: "Etanol yanıcıdır; konsantrasyon, ürün sınıfı ve havalandırma koşulları kullanım güvenliği açısından değerlendirilmelidir.",
    contextDe: "Ethanol ist eine organische Verbindung mit der Formel C₂H₆O. Da verschiedene Anordnungen gleicher Atome unterschiedliche Stoffe ergeben können, ist neben der Formel auch der Stoffname wichtig.",
    usesDe: ["Lösungsmittel und Reinigungsprodukte", "Kraftstoffmischungen", "Lebensmittel- und Pharmaprozesse"],
    safetyDe: "Ethanol ist entzündbar; Konzentration, Produktqualität und Lüftung müssen für einen sicheren Einsatz berücksichtigt werden.",
  },
  {
    id: "hidrojen-peroksit",
    contextTr: "Hidrojen peroksit H₂O₂ formüllüdür; suya göre bir ek oksijen atomu içerir. Bu yapı, bileşiğin oksitleyici özellikleri ve molar kütlesi açısından önemlidir.",
    usesTr: ["Ağartma ve yüzey işlemleri", "Su ve atık su prosesleri", "Laboratuvar oksidasyonu"],
    safetyTr: "Derişim arttıkça tehlike artabilir; ürün etiketindeki saklama, karıştırmama ve koruyucu ekipman talimatlarına uyulmalıdır.",
    contextDe: "Wasserstoffperoxid hat die Formel H₂O₂ und enthält im Vergleich zu Wasser ein zusätzliches Sauerstoffatom. Diese Struktur ist für seine oxidierenden Eigenschaften und die Molmasse wichtig.",
    usesDe: ["Bleichen und Oberflächenprozesse", "Wasser- und Abwasserbehandlung", "Oxidationen im Labor"],
    safetyDe: "Mit steigender Konzentration kann die Gefährdung zunehmen; Lager-, Misch- und Schutzanweisungen des Produktetiketts sind zu beachten.",
  },
  {
    id: "metan",
    contextTr: "Metan CH₄ formüllü en basit hidrokarbonlardan biridir. Bir karbon atomuna bağlı dört hidrojen atomu, molar kütle hesabının temelini oluşturur.",
    usesTr: ["Doğal gazın ana bileşeni", "Enerji ve ısı üretimi", "Kimyasal hammadde"],
    safetyTr: "Metan yanıcı bir gazdır ve kapalı alanlarda patlama veya oksijen azalması riski doğurabilir; gaz tesisatı uygun standartlarla kurulmalıdır.",
    contextDe: "Methan ist einer der einfachsten Kohlenwasserstoffe mit der Formel CH₄. Vier an ein Kohlenstoffatom gebundene Wasserstoffatome bestimmen seine Molmasse.",
    usesDe: ["Hauptbestandteil von Erdgas", "Energie- und Wärmeerzeugung", "Chemischer Grundstoff"],
    safetyDe: "Methan ist brennbar und kann in geschlossenen Räumen Explosions- oder Sauerstoffmangelrisiken verursachen; Gasanlagen müssen den passenden Standards entsprechen.",
  },
  {
    id: "potasyum-nitrat",
    contextTr: "Potasyum nitrat KNO₃ formüllü iyonik bir tuzdur. Formül biriminde potasyum ile nitrat grubundaki bir azot ve üç oksijen atomu bulunur.",
    usesTr: ["Gübre formülasyonları", "Gıda ve proses kimyası", "Laboratuvar reaktifi"],
    safetyTr: "Oksitleyici özellik gösterebilir; yanıcı maddelerden uzak tutulmalı ve ürün güvenlik talimatlarına göre kullanılmalıdır.",
    contextDe: "Kaliumnitrat ist ein ionisches Salz mit der Formel KNO₃. Eine Formeleinheit enthält Kalium sowie in der Nitratgruppe ein Stickstoff- und drei Sauerstoffatome.",
    usesDe: ["Düngemittelformulierungen", "Lebensmittel- und Prozesschemie", "Laborreagenz"],
    safetyDe: "Der Stoff kann oxidierende Eigenschaften haben; von brennbaren Materialien fernhalten und die Sicherheitsanweisungen des Produkts befolgen.",
  },
  {
    id: "aluminyum-oksit",
    contextTr: "Alüminyum oksit Al₂O₃ formüllü, sert ve ısıl açıdan dayanıklı bir seramik bileşiğidir. Formülde iki alüminyum ile üç oksijen atomu bulunur.",
    usesTr: ["Aşındırıcı ve parlatıcı malzemeler", "Teknik seramik", "Refrakter ve elektrik yalıtımı"],
    safetyTr: "Toz oluşan işlemlerde solunum maruziyeti kontrol edilmelidir; uygun sınıf ve tane boyutu uygulamaya göre seçilmelidir.",
    contextDe: "Aluminiumoxid ist eine harte, temperaturbeständige Keramikverbindung mit der Formel Al₂O₃. Die Formel enthält zwei Aluminium- und drei Sauerstoffatome.",
    usesDe: ["Schleif- und Poliermittel", "Technische Keramik", "Feuerfeste Werkstoffe und elektrische Isolierung"],
    safetyDe: "Bei staubbildenden Arbeiten muss die Exposition der Atemwege kontrolliert werden; Güte und Korngröße sind an die Anwendung anzupassen.",
  },
  {
    id: "kalsiyum-hidroksit",
    contextTr: "Kalsiyum hidroksit Ca(OH)₂ formüllü bir bazdır. Formüldeki parantez, hidroksit grubunun iki kez bulunduğunu ve molar kütle hesabında iki oksijen ile iki hidrojenin hesaba katıldığını gösterir.",
    usesTr: ["Harç ve yapı uygulamaları", "Su ve atık su pH kontrolü", "Şeker ve kimyasal prosesler"],
    safetyTr: "Alkali ve tahriş edici olabilir; toz ve çözeltiyle çalışırken göz, cilt ve solunum koruması ürün güvenlik bilgisine göre seçilmelidir.",
    contextDe: "Calciumhydroxid ist eine Base mit der Formel Ca(OH)₂. Die Klammer zeigt zwei Hydroxidgruppen; für die Molmasse werden daher zwei Sauerstoff- und zwei Wasserstoffatome berücksichtigt.",
    usesDe: ["Mörtel und Bauanwendungen", "pH-Kontrolle in Wasser und Abwasser", "Zucker- und Chemieprozesse"],
    safetyDe: "Der Stoff kann alkalisch und reizend wirken; Augen-, Haut- und Atemschutz richten sich bei Staub und Lösungen nach dem Sicherheitsdatenblatt.",
  },
  {
    id: "nitrik-asit",
    contextTr: "Nitrik asit HNO₃ formüllü bir mineral asittir. Bir hidrojen, bir azot ve üç oksijen atomunun toplamı, bileşiğin referans molar kütlesini verir.",
    usesTr: ["Gübre ve kimyasal üretimi", "Metal yüzey işlemleri", "Laboratuvar analitiği"],
    safetyTr: "Aşındırıcı ve oksitleyici özellik gösterebilir; yalnızca uygun ekipman, havalandırma ve ürün güvenlik prosedürleriyle kullanılmalıdır.",
    contextDe: "Salpetersäure ist eine Mineralsäure mit der Formel HNO₃. Ein Wasserstoff-, ein Stickstoff- und drei Sauerstoffatome ergeben die Referenzmolmasse.",
    usesDe: ["Düngemittel- und Chemieproduktion", "Metalloberflächenprozesse", "Laboranalytik"],
    safetyDe: "Der Stoff kann ätzend und oxidierend wirken; Einsatz nur mit geeigneter Ausrüstung, Lüftung und Sicherheitsverfahren.",
  },
  {
    id: "fosforik-asit",
    contextTr: "Fosforik asit H₃PO₄ formüllü bir oksiasittir. Üç hidrojen, bir fosfor ve dört oksijen atomu, formülün molar kütle bileşimini oluşturur.",
    usesTr: ["Gıda ve içecek prosesleri", "Gübre üretimi", "Metal yüzeyi hazırlama"],
    safetyTr: "Ticari çözeltilerin derişimi ve amaçlanan kullanım alanı değişir; gıda, teknik ve laboratuvar sınıfları birbirinin yerine kullanılmamalıdır.",
    contextDe: "Phosphorsäure ist eine Oxosäure mit der Formel H₃PO₄. Drei Wasserstoff-, ein Phosphor- und vier Sauerstoffatome bilden die Molmassen-Zusammensetzung.",
    usesDe: ["Lebensmittel- und Getränkeprozesse", "Düngemittelproduktion", "Vorbereitung von Metalloberflächen"],
    safetyDe: "Handelslösungen unterscheiden sich in Konzentration und Zweck; Lebensmittel-, technische und Laborqualitäten sind nicht austauschbar.",
  },
  {
    id: "asetik-asit",
    contextTr: "Asetik asit CH₃COOH formüllü organik bir asittir ve sirkenin karakteristik asidik bileşenidir. Yoğunlaştırılmış ürün ile gıdada bulunan seyreltilmiş çözelti aynı risk düzeyinde değildir.",
    usesTr: ["Gıda prosesleri", "Polimer ve kimyasal üretim", "Laboratuvar çözücü ve reaktifi"],
    safetyTr: "Derişim yükseldikçe aşındırıcı ve yanıcı risk artabilir; ürün sınıfı ile güvenlik bilgisi birlikte değerlendirilmelidir.",
    contextDe: "Essigsäure ist eine organische Säure mit der Formel CH₃COOH und die charakteristische saure Verbindung in Essig. Konzentrierte Produkte und verdünnte Lebensmittel-Lösungen haben nicht dasselbe Risiko.",
    usesDe: ["Lebensmittelprozesse", "Polymer- und Chemieproduktion", "Lösungsmittel und Reagenz im Labor"],
    safetyDe: "Mit steigender Konzentration können Ätz- und Entzündungsrisiken zunehmen; Produktqualität und Sicherheitsinformation gehören zusammen bewertet.",
  },
  {
    id: "potasyum-hidroksit",
    contextTr: "Potasyum hidroksit KOH formüllü güçlü bir bazdır. Formül birimindeki potasyum, oksijen ve hidrojen atomlarının her biri molar kütleye bir kez katkı yapar.",
    usesTr: ["Sıvı sabun ve deterjan üretimi", "pH düzenleme", "Kimyasal sentez"],
    safetyTr: "Aşındırıcıdır; nemle temasında ısı açığa çıkarabilen çözeltiler oluşturabilir ve yalnızca uygun koruma ile işlenmelidir.",
    contextDe: "Kaliumhydroxid ist eine starke Base mit der Formel KOH. Kalium, Sauerstoff und Wasserstoff tragen jeweils einmal zur Molmasse einer Formeleinheit bei.",
    usesDe: ["Herstellung flüssiger Seifen und Reinigungsmittel", "pH-Einstellung", "Chemische Synthese"],
    safetyDe: "Der Stoff ist ätzend; mit Feuchtigkeit können sich Wärme entwickelnde Lösungen bilden und er darf nur mit geeignetem Schutz verarbeitet werden.",
  },
  {
    id: "kalsiyum-klorur",
    contextTr: "Kalsiyum klorür CaCl₂ formüllü iyonik bir tuzdur. Bir kalsiyum atomuna karşılık iki klor atomu bulunması, formüldeki alt indisle gösterilir.",
    usesTr: ["Nem alma ve kurutma", "Yol buz çözme", "Soğutma ve gıda prosesleri"],
    safetyTr: "Suyla çözünmesi ısı açığa çıkarabilir; ürünün saflığı ve kullanım amacı teknik talimatlara göre doğrulanmalıdır.",
    contextDe: "Calciumchlorid ist ein ionisches Salz mit der Formel CaCl₂. Der Index zeigt, dass auf ein Calciumatom zwei Chloratome kommen.",
    usesDe: ["Feuchtigkeitsbindung und Trocknung", "Enteisung von Straßen", "Kühl- und Lebensmittelprozesse"],
    safetyDe: "Beim Lösen in Wasser kann Wärme frei werden; Reinheit und Verwendungszweck müssen anhand der technischen Angaben geprüft werden.",
  },
  {
    id: "sodyum-bikarbonat",
    contextTr: "Sodyum bikarbonat NaHCO₃ formüllü bir tuzdur. Karbonat sistemiyle ilişkili yapısı, asitlerle temasında gaz oluşumu görülebilmesini açıklar.",
    usesTr: ["Hamur kabartma", "Hafif temizlik uygulamaları", "Yangın söndürme tozları"],
    safetyTr: "Gıda ve teknik ürünler farklı saflıkta olabilir; ilaç veya beslenme amacı için bu hesap sayfası doz önerisi değildir.",
    contextDe: "Natriumhydrogencarbonat ist ein Salz mit der Formel NaHCO₃. Seine Beziehung zum Carbonatsystem erklärt, warum bei Kontakt mit Säuren Gas entstehen kann.",
    usesDe: ["Backtriebmittel", "Milde Reinigungsanwendungen", "Löschpulver"],
    safetyDe: "Lebensmittel- und technische Produkte können unterschiedliche Reinheiten haben; diese Rechenseite ist keine Dosierungsempfehlung für Medizin oder Ernährung.",
  },
  {
    id: "sodyum-karbonat",
    contextTr: "Sodyum karbonat Na₂CO₃ formüllü alkalin bir tuzdur. İki sodyum atomu ile karbonat grubunun birleşimi, molar kütle hesabında her atom sayısının önemli olmasını sağlar.",
    usesTr: ["Cam üretimi", "Deterjan formülasyonları", "Su yumuşatma"],
    safetyTr: "Toz ve çözelti gözleri veya cildi tahriş edebilir; kullanım derişimi ve çalışma yöntemi ürünün güvenlik bilgisinden alınmalıdır.",
    contextDe: "Natriumcarbonat ist ein alkalisches Salz mit der Formel Na₂CO₃. Zwei Natriumatome und die Carbonatgruppe machen die korrekte Atomzahl für die Molmassenrechnung wichtig.",
    usesDe: ["Glasherstellung", "Waschmittelformulierungen", "Wasserenthärtung"],
    safetyDe: "Staub und Lösungen können Augen oder Haut reizen; Konzentration und Arbeitsweise sind dem Sicherheitsdatenblatt zu entnehmen.",
  },
  {
    id: "gumus-nitrat",
    contextTr: "Gümüş nitrat AgNO₃ formüllü, gümüş içeren iyonik bir bileşiktir. Işığa duyarlı özellikleri ve gümüş iyonu içeriği bazı özel uygulamalarda önem taşır.",
    usesTr: ["Analitik kimya", "Fotoğrafçılıkta tarihsel prosesler", "Özel yüzey ve laboratuvar işlemleri"],
    safetyTr: "Oksitleyici ve aşındırıcı etkiler gösterebilir, ciltte kalıcı lekelenmeye yol açabilir; yalnızca uygun laboratuvar prosedürleriyle kullanılmalıdır.",
    contextDe: "Silbernitrat ist eine ionische Silberverbindung mit der Formel AgNO₃. Seine Lichtempfindlichkeit und der Gehalt an Silberionen sind für einige Spezialanwendungen bedeutsam.",
    usesDe: ["Analytische Chemie", "Historische fotografische Prozesse", "Spezielle Oberflächen- und Laborverfahren"],
    safetyDe: "Der Stoff kann oxidierend und ätzend wirken sowie dauerhafte Flecken auf der Haut verursachen; Verwendung nur nach geeigneten Laborverfahren.",
  },
  {
    id: "bakir-sulfat",
    contextTr: "Bakır(II) sülfat CuSO₄ formüllü bir tuzdur. Ticari ürünlerde susuz ve hidratlı biçimler bulunabilir; hidratlı biçimlerin gerçek molar kütlesi kristal suyuna göre değişir.",
    usesTr: ["Analitik ve eğitim laboratuvarları", "Elektrokaplama prosesleri", "Özel tarımsal ve endüstriyel uygulamalar"],
    safetyTr: "Bakır tuzları çevresel ve sağlık açısından risk taşıyabilir; ürün etiketi, yerel mevzuat ve atık prosedürleri izlenmelidir.",
    contextDe: "Kupfer(II)-sulfat ist ein Salz mit der Formel CuSO₄. Handelsprodukte können wasserfrei oder hydratisiert sein; bei Hydraten verändert Kristallwasser die tatsächliche Molmasse.",
    usesDe: ["Analytik- und Unterrichtslabore", "Galvanische Prozesse", "Spezielle landwirtschaftliche und industrielle Anwendungen"],
    safetyDe: "Kupfersalze können Umwelt- und Gesundheitsrisiken bergen; Produktetikett, lokale Vorschriften und Entsorgungswege sind zu beachten.",
  },
  {
    id: "potasyum-klorur",
    contextTr: "Potasyum klorür KCl formüllü, potasyum ve klorun bire bir oranla bulunduğu iyonik bir tuzdur. Molar kütlesi iki elementin atomik kütlelerinin toplamıdır.",
    usesTr: ["Gübreler", "Kimyasal prosesler", "Özel gıda ve laboratuvar uygulamaları"],
    safetyTr: "Ürün sınıfı ve miktar uygulamaya göre değişir; beslenme veya tıbbi amaç için uzman tavsiyesi ve ürün etiketi esas alınmalıdır.",
    contextDe: "Kaliumchlorid ist ein ionisches Salz mit der Formel KCl, in der Kalium und Chlor im Verhältnis eins zu eins vorliegen. Seine Molmasse ist die Summe beider Atommassen.",
    usesDe: ["Düngemittel", "Chemische Prozesse", "Spezielle Lebensmittel- und Laboranwendungen"],
    safetyDe: "Produktqualität und Menge hängen von der Anwendung ab; bei Ernährung oder Medizin sind fachliche Beratung und Produktkennzeichnung maßgeblich.",
  },
  {
    id: "kalsiyum-sulfat",
    contextTr: "Kalsiyum sülfat CaSO₄ formüllü bir tuzdur ve alçı taşı gibi doğal veya işlenmiş malzemelerde bulunur. Hidratlı alçı türlerinde kristal suyu ek bir bileşen olduğundan formül ayrımı önemlidir.",
    usesTr: ["Alçı ve yapı malzemeleri", "Kalıp ve seramik işlemleri", "Gıda ve proses katkıları"],
    safetyTr: "Tozlu malzemelerde solunum maruziyeti kontrol edilmelidir; ürünün hidrat formu ve kullanım sınıfı teknik dokümanlardan doğrulanmalıdır.",
    contextDe: "Calciumsulfat ist ein Salz mit der Formel CaSO₄ und kommt etwa in Gipsstein vor. Bei hydratisierten Gipsarten ist Kristallwasser ein zusätzlicher Bestandteil, weshalb die Formelunterscheidung wichtig ist.",
    usesDe: ["Gips und Baustoffe", "Formenbau und Keramikprozesse", "Lebensmittel- und Prozesszusätze"],
    safetyDe: "Bei staubenden Materialien muss die Atemwegsexposition kontrolliert werden; Hydratform und Produktklasse sind in den technischen Unterlagen zu prüfen.",
  },
  {
    id: "kukurt-dioksit",
    contextTr: "Kükürt dioksit SO₂ formüllü bir gazdır ve bir kükürt ile iki oksijen atomu içerir. Molar kütle hesabı gaz miktarı, emisyon ve proses hesaplarında kullanılabilir.",
    usesTr: ["Kimyasal üretim", "Koruyucu ve ağartma prosesleri", "Emisyon ölçümü ve kontrolü"],
    safetyTr: "Tahriş edici ve solunum için zararlı olabilir; gaz sızıntısı veya çalışma ortamı riskleri uygun havalandırma ve izleme gerektirir.",
    contextDe: "Schwefeldioxid ist ein Gas mit der Formel SO₂ und enthält ein Schwefel- sowie zwei Sauerstoffatome. Die Molmasse wird für Gasmengen-, Emissions- und Prozessrechnungen genutzt.",
    usesDe: ["Chemieproduktion", "Konservierungs- und Bleichprozesse", "Emissionsmessung und -kontrolle"],
    safetyDe: "Der Stoff kann reizend und atemwegsschädlich wirken; Leckagen und Arbeitsplatzrisiken erfordern geeignete Lüftung und Überwachung.",
  },
  {
    id: "azot-dioksit",
    contextTr: "Azot dioksit NO₂ formüllü reaktif bir gazdır. Atmosfer kimyası ve yanma emisyonlarında önemli olduğundan, formülü ve molar kütlesi çevresel hesaplarda kullanılır.",
    usesTr: ["Emisyon ve hava kalitesi izleme", "Kimyasal ara ürün", "Laboratuvar gaz analizi"],
    safetyTr: "Solunum yolları için tehlikeli olabilir; maruziyet riski yalnızca uygun ölçüm, havalandırma ve uzman prosedürlerle yönetilmelidir.",
    contextDe: "Stickstoffdioxid ist ein reaktives Gas mit der Formel NO₂. Da es in Atmosphärenchemie und Verbrennungsemissionen wichtig ist, werden Formel und Molmasse in Umweltrechnungen verwendet.",
    usesDe: ["Emissions- und Luftqualitätsüberwachung", "Chemisches Zwischenprodukt", "Labor-Gasanalytik"],
    safetyDe: "Der Stoff kann die Atemwege stark schädigen; Expositionsrisiken dürfen nur mit Messung, Lüftung und fachlichen Verfahren beherrscht werden.",
  },
  {
    id: "demir-oksit",
    contextTr: "Demir(III) oksit Fe₂O₃ formüllü bir demir oksittir ve pasın önemli bileşenlerinden biridir. İki demir ve üç oksijen atomu, bileşiğin referans molar kütlesini belirler.",
    usesTr: ["Kırmızı-kahverengi pigmentler", "Demir ve çelik prosesleri", "Aşındırıcı ve seramik uygulamalar"],
    safetyTr: "Toz halinde çalışma solunum maruziyeti yaratabilir; pigment, mineral ve endüstriyel ürün sınıfları kullanım koşullarına göre seçilmelidir.",
    contextDe: "Eisen(III)-oxid ist ein Eisenoxid mit der Formel Fe₂O₃ und ein wichtiger Bestandteil von Rost. Zwei Eisen- und drei Sauerstoffatome bestimmen die Referenzmolmasse.",
    usesDe: ["Rotbraune Pigmente", "Eisen- und Stahlprozesse", "Schleif- und Keramikanwendungen"],
    safetyDe: "Bei staubförmiger Verarbeitung kann eine Atemwegsexposition entstehen; Pigment-, Mineral- und technische Qualitäten müssen passend zur Anwendung gewählt werden.",
  },
  {
    id: "magnezyum-oksit",
    contextTr: "Magnezyum oksit MgO formüllü, magnezyum ve oksijenin bire bir oranla bulunduğu inorganik bir bileşiktir. Yüksek sıcaklığa dayanımı birçok teknik kullanımın temelidir.",
    usesTr: ["Refrakter tuğla ve fırın kaplamaları", "Teknik seramik", "Özel kimyasal ve proses uygulamaları"],
    safetyTr: "Tozlu ürünlerde solunum maruziyeti kontrol edilmelidir; gıda, farmasötik ve teknik kalite ürünler birbirinin yerine kullanılmamalıdır.",
    contextDe: "Magnesiumoxid ist eine anorganische Verbindung mit der Formel MgO, in der Magnesium und Sauerstoff im Verhältnis eins zu eins vorliegen. Seine Temperaturbeständigkeit ist die Grundlage vieler technischer Einsätze.",
    usesDe: ["Feuerfeste Steine und Ofenauskleidungen", "Technische Keramik", "Spezielle Chemie- und Prozessanwendungen"],
    safetyDe: "Bei pulverförmigen Produkten muss die Atemwegsexposition kontrolliert werden; Lebensmittel-, pharmazeutische und technische Qualitäten sind nicht austauschbar.",
  },
  {
    id: "silisyum-dioksit",
    contextTr: "Silisyum dioksit SiO₂ formüllü yaygın bir bileşiktir ve kuvars, kum ile pek çok cam ve seramik malzemenin temel bileşenidir. Bir silisyum ve iki oksijen atomu içerir.",
    usesTr: ["Cam ve seramik üretimi", "Döküm ve yapı malzemeleri", "Elektronik ve optik uygulamalar"],
    safetyTr: "Kristalin silisyum dioksit tozu solunursa sağlık riski oluşturabilir; toz kontrolü ve çalışma standartları malzemenin biçimine göre uygulanmalıdır.",
    contextDe: "Siliciumdioxid ist eine verbreitete Verbindung mit der Formel SiO₂ und ein Grundbestandteil von Quarz, Sand sowie vielen Glas- und Keramikmaterialien. Es enthält ein Silicium- und zwei Sauerstoffatome.",
    usesDe: ["Glas- und Keramikherstellung", "Gießerei- und Baustoffe", "Elektronik und Optik"],
    safetyDe: "Kristalliner Siliciumdioxidstaub kann beim Einatmen ein Gesundheitsrisiko darstellen; Staubkontrolle und Arbeitsstandards richten sich nach der Materialform.",
  },
  {
    id: "kalsiyum-oksit",
    contextTr: "Kalsiyum oksit CaO formüllü güçlü alkali karakterli bir oksittir. Su ile tepkimesi ısı açığa çıkarır ve bu nedenle kireç çevrimi proseslerinde önem taşır.",
    usesTr: ["Çimento ve yapı malzemeleri", "Çelik ve metalurji", "Su ve baca gazı işlemleri"],
    safetyTr: "Su ile temasında ısınır ve aşındırıcı çözelti oluşturabilir; nemden korunmalı ve uygun koruyucu ekipmanla kullanılmalıdır.",
    contextDe: "Calciumoxid ist ein stark basisches Oxid mit der Formel CaO. Die Reaktion mit Wasser setzt Wärme frei und ist für Kalkkreislaufprozesse wichtig.",
    usesDe: ["Zement und Baustoffe", "Stahl und Metallurgie", "Wasser- und Rauchgasbehandlung"],
    safetyDe: "Beim Kontakt mit Wasser erwärmt sich der Stoff und kann ätzende Lösungen bilden; vor Feuchtigkeit schützen und geeignete Schutzausrüstung verwenden.",
  },
  {
    id: "sukroz",
    contextTr: "Sükroz C₁₂H₂₂O₁₁ formüllü bir disakkarittir ve sofra şekerinin ana bileşenidir. Çok sayıda atom içeren formülü, küçük moleküllere göre daha yüksek molar kütle verir.",
    usesTr: ["Gıda ve içecek üretimi", "Fermantasyon prosesleri", "Farmasötik ve teknik formülasyonlar"],
    safetyTr: "Beslenme veya sağlık değerlendirmesi bu molar kütle hesabından çıkarılamaz; porsiyon ve bireysel gereksinimler ayrı konulardır.",
    contextDe: "Saccharose ist ein Disaccharid mit der Formel C₁₂H₂₂O₁₁ und der Hauptbestandteil von Haushaltszucker. Die hohe Atomzahl führt im Vergleich zu kleinen Molekülen zu einer größeren Molmasse.",
    usesDe: ["Lebensmittel- und Getränkeherstellung", "Fermentationsprozesse", "Pharmazeutische und technische Formulierungen"],
    safetyDe: "Eine Ernährungs- oder Gesundheitsbewertung lässt sich nicht aus dieser Molmassenrechnung ableiten; Portionsgröße und individuelle Bedürfnisse sind getrennte Fragen.",
  },
  {
    id: "etilen",
    contextTr: "Etilen C₂H₄ formüllü doymamış bir hidrokarbondur. Karbon atomları arasındaki çift bağ, bileşiğin kimyasal tepkimelerde ve polimer üretiminde önemli olmasını sağlar.",
    usesTr: ["Polietilen üretimi", "Kimyasal ara ürün", "Kontrollü meyve olgunlaştırma"],
    safetyTr: "Yanıcı bir gazdır; depolama ve proses alanlarında sızıntı, tutuşturucu kaynaklar ve havalandırma kontrol edilmelidir.",
    contextDe: "Ethylen ist ein ungesättigter Kohlenwasserstoff mit der Formel C₂H₄. Die Doppelbindung zwischen den Kohlenstoffatomen macht die Verbindung für Reaktionen und Polymerherstellung wichtig.",
    usesDe: ["Herstellung von Polyethylen", "Chemisches Zwischenprodukt", "Kontrollierte Fruchtreifung"],
    safetyDe: "Das Gas ist entzündbar; Leckagen, Zündquellen und Lüftung müssen in Lager- und Prozessbereichen kontrolliert werden.",
  },
  {
    id: "benzen",
    contextTr: "Benzen C₆H₆ formüllü aromatik bir hidrokarbondur. Altı karbon atomlu halka yapısı, onu pek çok kimyasal sentez için önemli bir başlangıç maddesi yapar.",
    usesTr: ["Kontrollü endüstriyel kimyasal sentez", "Polimer ara ürünleri", "Laboratuvar ve analitik referanslar"],
    safetyTr: "Benzen kanserojen olarak sınıflandırılır; tüketici veya ev kullanımı için uygun değildir ve maruziyet sıkı biçimde kontrol edilmelidir.",
    contextDe: "Benzol ist ein aromatischer Kohlenwasserstoff mit der Formel C₆H₆. Seine sechsgliedrige Kohlenstoffringstruktur macht es zu einem wichtigen Ausgangsstoff vieler Synthesen.",
    usesDe: ["Kontrollierte industrielle Chemiesynthese", "Zwischenprodukte für Polymere", "Labor- und Analytikreferenzen"],
    safetyDe: "Benzol ist als krebserzeugend eingestuft; es ist nicht für Verbraucher- oder Haushaltsanwendungen geeignet und die Exposition muss streng kontrolliert werden.",
  },
  {
    id: "metanol",
    contextTr: "Metanol CH₃OH formüllü en basit alkollerden biridir. Etanolle benzer formül ailesinde olsa da toksikolojik özellikleri farklıdır ve birbirinin yerine kullanılamaz.",
    usesTr: ["Kimyasal hammadde", "Çözücü ve yakıt uygulamaları", "Formaldehit ve türevleri üretimi"],
    safetyTr: "Zehirli ve yanıcıdır; yutulması veya buharına maruz kalınması ciddi zarar verebilir, yalnızca uygun endüstriyel prosedürlerle ele alınmalıdır.",
    contextDe: "Methanol ist einer der einfachsten Alkohole mit der Formel CH₃OH. Obwohl es zur gleichen Stofffamilie wie Ethanol gehört, unterscheiden sich die toxikologischen Eigenschaften grundlegend.",
    usesDe: ["Chemischer Grundstoff", "Lösungsmittel- und Kraftstoffanwendungen", "Herstellung von Formaldehyd und Derivaten"],
    safetyDe: "Der Stoff ist giftig und entzündbar; Verschlucken oder Dämpfe können schwere Schäden verursachen, daher nur nach geeigneten Industrieprozessen handhaben.",
  },
  {
    id: "azot-gazi",
    contextTr: "Azot gazı N₂ formüllü iki atomlu bir moleküldür ve havanın büyük bölümünü oluşturur. Azot atomunun molar kütlesi ile N₂ molekülünün molar kütlesi bu nedenle farklıdır.",
    usesTr: ["Koruyucu atmosferler", "Gıda ambalajlama", "Sıvı azotla soğutma"],
    safetyTr: "Yanıcı değildir ancak kapalı alanlarda oksijeni seyreltebilir; özellikle sıvı azot kullanımında havalandırma ve eğitim gereklidir.",
    contextDe: "Stickstoffgas ist ein zweiatomiges Molekül mit der Formel N₂ und macht den größten Teil der Luft aus. Die Molmasse eines Stickstoffatoms unterscheidet sich deshalb von der des N₂-Moleküls.",
    usesDe: ["Schutzatmosphären", "Lebensmittelverpackung", "Kühlung mit flüssigem Stickstoff"],
    safetyDe: "Das Gas ist nicht brennbar, kann in geschlossenen Räumen aber Sauerstoff verdrängen; besonders bei flüssigem Stickstoff sind Lüftung und Schulung erforderlich.",
  },
  {
    id: "hidrojen-gazi",
    contextTr: "Hidrojen gazı H₂ formüllü iki atomlu bir moleküldür. Çok düşük molar kütlesi, gaz miktarı ve depolama hesaplarında diğer gazlara göre farklı davranışlar doğurur.",
    usesTr: ["Amonyak ve kimyasal üretimi", "Rafineri prosesleri", "Yakıt hücresi uygulamaları"],
    safetyTr: "Son derece yanıcıdır; kaçak algılama, havalandırma ve tutuşturucu kaynakların kontrolü hidrojen sistemlerinin temel güvenlik gereğidir.",
    contextDe: "Wasserstoffgas ist ein zweiatomiges Molekül mit der Formel H₂. Seine sehr geringe Molmasse führt bei Gasmengen- und Speicherrechnungen zu einem anderen Verhalten als bei vielen anderen Gasen.",
    usesDe: ["Ammoniak- und Chemieproduktion", "Raffinerieprozesse", "Brennstoffzellenanwendungen"],
    safetyDe: "Das Gas ist sehr leicht entzündbar; Leckageerkennung, Lüftung und Kontrolle von Zündquellen sind grundlegende Sicherheitsanforderungen.",
  },
  {
    id: "klor-gazi",
    contextTr: "Klor gazı Cl₂ formüllü iki atomlu bir halojen molekülüdür. Elementin atomik kütlesi ile Cl₂ gazının molar kütlesi arasındaki fark hesaplarda dikkate alınmalıdır.",
    usesTr: ["Su arıtma kimyasının üretimi", "PVC ve ara kimyasallar", "Kontrollü endüstriyel prosesler"],
    safetyTr: "Zehirli ve aşındırıcı bir gazdır; üretim ve kullanım yalnızca kapalı, denetimli sistemlerde ve uzman personelle yapılmalıdır.",
    contextDe: "Chlorgas ist ein zweiatomiges Halogenmolekül mit der Formel Cl₂. Bei Rechnungen muss zwischen der Atommasse von Chlor und der Molmasse des Cl₂-Gases unterschieden werden.",
    usesDe: ["Herstellung von Wasseraufbereitungschemikalien", "PVC und chemische Zwischenprodukte", "Kontrollierte Industrieprozesse"],
    safetyDe: "Das Gas ist giftig und ätzend; Herstellung und Einsatz gehören ausschließlich in geschlossene, überwachte Systeme mit Fachpersonal.",
  },
  {
    id: "karbonik-asit",
    contextTr: "Karbonik asit H₂CO₃, karbondioksitin suda çözünmesiyle ilişkili zayıf bir asittir. Sulu dengelerde çözünmüş CO₂, bikarbonat ve karbonat türleri birlikte değerlendirilir.",
    usesTr: ["Su kimyası ve pH dengesi", "İçecek karbonlaması", "Çevresel ve jeokimyasal hesaplar"],
    safetyTr: "Gerçek çözelti davranışı sıcaklık, basınç ve diğer çözünmüş maddelere bağlıdır; bu sayfanın değeri yalnızca H₂CO₃ formülüne ait referans molar kütledir.",
    contextDe: "Kohlensäure H₂CO₃ ist eine schwache Säure, die mit gelöstem Kohlendioxid in Wasser zusammenhängt. In wässrigen Gleichgewichten werden CO₂, Hydrogencarbonat und Carbonat gemeinsam betrachtet.",
    usesDe: ["Wasserchemie und pH-Gleichgewichte", "Karbonisierung von Getränken", "Umwelt- und geochemische Rechnungen"],
    safetyDe: "Das Verhalten realer Lösungen hängt von Temperatur, Druck und weiteren gelösten Stoffen ab; der Wert dieser Seite ist nur die Referenzmolmasse der Formel H₂CO₃.",
  },
  {
    id: "hidroflorik-asit",
    contextTr: "Hidroflorik asit HF formüllü bir hidrojen halojenür asididir. Formülü basit olsa da cam, silikat ve biyolojik dokularla etkileşimi onu diğer yaygın asitlerden ayırır.",
    usesTr: ["Cam ve silikat yüzey işlemleri", "Flor kimyasının üretimi", "Kontrollü endüstriyel temizleme"],
    safetyTr: "Çok tehlikelidir; deri yoluyla derin doku hasarı oluşturabilir. Ev veya genel laboratuvar kullanımı için uygun değildir, özel eğitim ve acil durum prosedürü gerektirir.",
    contextDe: "Flusssäure ist eine Halogenwasserstoffsäure mit der Formel HF. Trotz der einfachen Formel unterscheidet sie sich durch ihre Wechselwirkung mit Glas, Silikaten und biologischem Gewebe von vielen anderen Säuren.",
    usesDe: ["Oberflächenbehandlung von Glas und Silikaten", "Herstellung von Fluorchemikalien", "Kontrollierte industrielle Reinigung"],
    safetyDe: "Der Stoff ist äußerst gefährlich und kann tiefe Gewebeschäden verursachen. Er ist nicht für Haushalt oder allgemeine Labore geeignet und erfordert spezielle Schulung und Notfallverfahren.",
  },
  {
    id: "hidrojen-sulfur",
    contextTr: "Hidrojen sülfür H₂S formüllü, iki hidrojen ve bir kükürt atomundan oluşan bir gazdır. Petrol, doğal gaz ve biyolojik ayrışma süreçlerinde izlenmesi önem taşır.",
    usesTr: ["Endüstriyel gaz izleme", "Kükürt ve kimyasal prosesler", "Laboratuvar analizleri"],
    safetyTr: "Zehirli ve yanıcıdır; kokuya güvenmek güvenli değildir çünkü yüksek derişimde koku alma duyusunu baskılayabilir. Ölçüm ve havalandırma zorunludur.",
    contextDe: "Schwefelwasserstoff ist ein Gas mit der Formel H₂S aus zwei Wasserstoff- und einem Schwefelatom. Seine Überwachung ist in Erdöl-, Erdgas- und biologischen Zersetzungsprozessen wichtig.",
    usesDe: ["Industrielle Gasüberwachung", "Schwefel- und Chemieprozesse", "Laboranalytik"],
    safetyDe: "Das Gas ist giftig und brennbar; auf den Geruch ist kein Verlass, da er bei hoher Konzentration ausfallen kann. Messung und Lüftung sind erforderlich.",
  },
  {
    id: "baryum-hidroksit",
    contextTr: "Baryum hidroksit Ba(OH)₂ formüllü güçlü bir bazdır. Parantezli hidroksit grubu iki kez yer aldığı için formüldeki oksijen ve hidrojen sayıları iki olarak hesaplanır.",
    usesTr: ["Analitik kimya", "Özel kimyasal sentez", "Laboratuvar pH ve titrasyon işlemleri"],
    safetyTr: "Aşındırıcı olabilir ve çözünür baryum bileşikleri toksik risk taşıyabilir; yalnızca kontrollü laboratuvar veya endüstriyel koşullarda kullanılmalıdır.",
    contextDe: "Bariumhydroxid ist eine starke Base mit der Formel Ba(OH)₂. Da die Hydroxidgruppe zweimal vorkommt, werden zwei Sauerstoff- und zwei Wasserstoffatome berechnet.",
    usesDe: ["Analytische Chemie", "Spezielle chemische Synthese", "Labor-pH- und Titrationsverfahren"],
    safetyDe: "Der Stoff kann ätzend sein und lösliche Bariumverbindungen können toxische Risiken bergen; Verwendung nur unter kontrollierten Labor- oder Industriebedingungen.",
  },
  {
    id: "aluminyum-hidroksit",
    contextTr: "Alüminyum hidroksit Al(OH)₃ formüllü bir hidroksittir. Üç hidroksit grubu, formülde üç oksijen ve üç hidrojen atomu bulunduğu anlamına gelir.",
    usesTr: ["Alev geciktirici dolgu maddeleri", "Su arıtma prosesleri", "Özel farmasötik ve endüstriyel ürünler"],
    safetyTr: "Uygulama performansı tane boyutu, saflık ve ürün sınıfına bağlıdır; teknik ürünler tıbbi veya gıda amaçlı kullanılmamalıdır.",
    contextDe: "Aluminiumhydroxid ist ein Hydroxid mit der Formel Al(OH)₃. Drei Hydroxidgruppen bedeuten, dass die Formel drei Sauerstoff- und drei Wasserstoffatome enthält.",
    usesDe: ["Flammschutz-Füllstoffe", "Wasseraufbereitungsprozesse", "Spezielle pharmazeutische und technische Produkte"],
    safetyDe: "Die Leistung hängt von Korngröße, Reinheit und Produktklasse ab; technische Produkte dürfen nicht für medizinische oder Lebensmittelzwecke verwendet werden.",
  },
  {
    id: "magnezyum-klorur",
    contextTr: "Magnezyum klorür MgCl₂ formüllü iyonik bir tuzdur. Bir magnezyum atomuna iki klor atomunun eşlik etmesi, formüldeki alt indisle ve molar kütle hesabında görünür.",
    usesTr: ["Toz kontrolü ve yol uygulamaları", "Magnezyum kimyası", "Özel su ve proses işlemleri"],
    safetyTr: "Susuz ve hidratlı ürünlerin bileşimi farklıdır; gerçek ürün formu, saflık ve uygulama koşulu teknik dokümandan doğrulanmalıdır.",
    contextDe: "Magnesiumchlorid ist ein ionisches Salz mit der Formel MgCl₂. Auf ein Magnesiumatom kommen zwei Chloratome, was sich im Index und in der Molmassenrechnung zeigt.",
    usesDe: ["Staubbindung und Straßenanwendungen", "Magnesiumchemie", "Spezielle Wasser- und Prozessverfahren"],
    safetyDe: "Wasserfreie und hydratisierte Produkte haben unterschiedliche Zusammensetzungen; Produktform, Reinheit und Einsatzbedingungen sind in den technischen Unterlagen zu prüfen.",
  },
  {
    id: "demir-klorur",
    contextTr: "Demir(III) klorür FeCl₃ formüllü bir demir tuzudur. Üç klor atomu içeren formül, demirin yükseltgenme basamağı ve iyonik bileşenleriyle ilişkilidir.",
    usesTr: ["Su arıtma pıhtılaştırma prosesleri", "Metal aşındırma", "Laboratuvar ve kimyasal sentez"],
    safetyTr: "Aşındırıcı çözeltiler oluşturabilir ve metalleri etkileyebilir; depolama malzemesi ve kişisel koruma ürün güvenlik bilgisine göre seçilmelidir.",
    contextDe: "Eisen(III)-chlorid ist ein Eisensalz mit der Formel FeCl₃. Die drei Chloratome stehen mit der Oxidationsstufe des Eisens und den ionischen Bestandteilen in Beziehung.",
    usesDe: ["Flockung in der Wasseraufbereitung", "Metallätzen", "Labor und chemische Synthese"],
    safetyDe: "Der Stoff kann ätzende Lösungen bilden und Metalle angreifen; Lagermaterial und Schutzausrüstung sind nach dem Sicherheitsdatenblatt auszuwählen.",
  },
  {
    id: "sodyum-sulfat",
    contextTr: "Sodyum sülfat Na₂SO₄ formüllü bir tuzdur. İki sodyum atomu ile sülfat grubundaki bir kükürt ve dört oksijen atomu hesaplamada birlikte değerlendirilir.",
    usesTr: ["Deterjan üretimi", "Cam ve kâğıt prosesleri", "Tekstil boyama"],
    safetyTr: "Susuz ve hidratlı biçimler farklı molar kütlelere sahiptir; bu sayfadaki değer yalnızca Na₂SO₄ formülünü ifade eder.",
    contextDe: "Natriumsulfat ist ein Salz mit der Formel Na₂SO₄. Zwei Natriumatome sowie ein Schwefel- und vier Sauerstoffatome der Sulfatgruppe werden gemeinsam berechnet.",
    usesDe: ["Waschmittelherstellung", "Glas- und Papierprozesse", "Textilfärbung"],
    safetyDe: "Wasserfreie und hydratisierte Formen haben unterschiedliche Molmassen; der Wert dieser Seite bezieht sich nur auf die Formel Na₂SO₄.",
  },
  {
    id: "amonyum-nitrat",
    contextTr: "Amonyum nitrat NH₄NO₃ formüllü bir amonyum ve nitrat tuzudur. Formülde iki azot atomu bulunur: biri amonyum, diğeri nitrat grubundadır.",
    usesTr: ["Gübre üretimi", "Kontrollü endüstriyel kimya", "Laboratuvar referansları"],
    safetyTr: "Oksitleyici özellikleri ve yanlış kullanım riski nedeniyle depolama, taşıma ve kullanım sıkı mevzuat ile ürün güvenlik prosedürlerine tabidir.",
    contextDe: "Ammoniumnitrat ist ein Ammonium- und Nitratsalz mit der Formel NH₄NO₃. Es enthält zwei Stickstoffatome: eines im Ammonium- und eines im Nitratteil.",
    usesDe: ["Düngemittelherstellung", "Kontrollierte Industriechemie", "Laborreferenzen"],
    safetyDe: "Wegen oxidierender Eigenschaften und Missbrauchsrisiken unterliegen Lagerung, Transport und Einsatz strengen Vorschriften und Sicherheitsverfahren.",
  },
  {
    id: "potasyum-permanganat",
    contextTr: "Potasyum permanganat KMnO₄ formüllü, manganez içeren güçlü oksitleyici bir tuzdur. Mor rengi ve redoks tepkimelerindeki davranışı analitik uygulamalarda bilinir.",
    usesTr: ["Laboratuvar titrasyonları", "Kontrollü su ve proses işlemleri", "Kimyasal oksidasyon"],
    safetyTr: "Oksitleyicidir ve organik ya da yanıcı malzemelerle uyumsuz olabilir; yalnızca ürün güvenlik talimatlarına göre kullanılmalıdır.",
    contextDe: "Kaliumpermanganat ist ein stark oxidierendes Mangansalz mit der Formel KMnO₄. Seine violette Farbe und sein Redoxverhalten sind in der Analytik bekannt.",
    usesDe: ["Titrationen im Labor", "Kontrollierte Wasser- und Prozessverfahren", "Chemische Oxidation"],
    safetyDe: "Der Stoff ist oxidierend und kann mit organischen oder brennbaren Materialien unverträglich sein; Verwendung nur nach Sicherheitsanweisungen.",
  },
  {
    id: "sodyum-hipoklorit",
    contextTr: "Sodyum hipoklorit NaOCl formüllü klor içeren bir tuzdur. Sulu çözeltilerdeki etkinliği derişim, pH, sıcaklık ve ürün yaşına bağlı olarak değişebilir.",
    usesTr: ["Yüzey dezenfeksiyonu", "Su işlemleri", "Tekstil ve temizlik prosesleri"],
    safetyTr: "Asitler veya amonyak içeren ürünlerle karıştırılmamalıdır; tehlikeli gazlar oluşabilir. Etiket ve havalandırma talimatları izlenmelidir.",
    contextDe: "Natriumhypochlorit ist ein chlorhaltiges Salz mit der Formel NaOCl. Die Wirksamkeit wässriger Lösungen kann von Konzentration, pH-Wert, Temperatur und Produktalter abhängen.",
    usesDe: ["Oberflächendesinfektion", "Wasserbehandlung", "Textil- und Reinigungsprozesse"],
    safetyDe: "Nicht mit Säuren oder ammoniakhaltigen Produkten mischen, da gefährliche Gase entstehen können. Kennzeichnung und Lüftungshinweise beachten.",
  },
  {
    id: "kalsiyum-florur",
    contextTr: "Kalsiyum florür CaF₂ formüllü iyonik bir bileşiktir ve doğal flüorit mineralinin ana bileşenidir. Bir kalsiyum atomuna iki flor atomu eşlik eder.",
    usesTr: ["Metalurji akı maddeleri", "Optik malzemeler", "Flor kimyasına hammadde"],
    safetyTr: "Doğal mineral ve işlenmiş ürünlerin saflığı değişebilir; toz kontrolü ve ürün sınıfı uygulamaya uygun seçilmelidir.",
    contextDe: "Calciumfluorid ist eine ionische Verbindung mit der Formel CaF₂ und der Hauptbestandteil des Minerals Fluorit. Auf ein Calciumatom kommen zwei Fluoratome.",
    usesDe: ["Flussmittel in der Metallurgie", "Optische Materialien", "Rohstoff für Fluorchemie"],
    safetyDe: "Reinheit natürlicher Minerale und verarbeiteter Produkte kann variieren; Staubkontrolle und Produktklasse müssen zur Anwendung passen.",
  },
  {
    id: "gumus-klorur",
    contextTr: "Gümüş klorür AgCl formüllü, ışığa duyarlı bir gümüş tuzudur. Suda düşük çözünürlüğü ve ışıkla davranışı analitik ve tarihsel fotoğrafçılık uygulamalarında önem taşır.",
    usesTr: ["Analitik kimya", "Elektrot ve referans sistemleri", "Tarihsel fotoğrafçılık"],
    safetyTr: "Gümüş içeren atıklar çevreye bırakılmamalıdır; ışık duyarlılığı ve atık toplama gereksinimleri laboratuvar prosedürleriyle yönetilmelidir.",
    contextDe: "Silberchlorid ist ein lichtempfindliches Silbersalz mit der Formel AgCl. Seine geringe Wasserlöslichkeit und sein Verhalten bei Licht sind in Analytik und historischer Fotografie bedeutsam.",
    usesDe: ["Analytische Chemie", "Elektroden- und Referenzsysteme", "Historische Fotografie"],
    safetyDe: "Silberhaltige Abfälle dürfen nicht in die Umwelt gelangen; Lichtempfindlichkeit und Abfallsammlung sind nach Laborverfahren zu behandeln.",
  },
  {
    id: "baryum-sulfat",
    contextTr: "Baryum sülfat BaSO₄ formüllü, suda çok az çözünen bir tuzdur. Bu düşük çözünürlük onu çözünür baryum tuzlarından hem kullanım hem risk bakımından ayırır.",
    usesTr: ["Röntgen kontrast süspansiyonları", "Boya ve plastik dolgu maddesi", "Sondaj akışkanları"],
    safetyTr: "Tıbbi kullanım yalnızca uygun formülasyon ve sağlık profesyoneli gözetiminde olur; diğer baryum bileşiklerinin özellikleri farklı olabilir.",
    contextDe: "Bariumsulfat ist ein in Wasser sehr schwer lösliches Salz mit der Formel BaSO₄. Diese geringe Löslichkeit unterscheidet es in Anwendung und Risiko von löslichen Bariumsalzen.",
    usesDe: ["Röntgenkontrast-Suspensionen", "Füllstoff für Farben und Kunststoffe", "Bohrspülungen"],
    safetyDe: "Medizinische Verwendung erfolgt nur in geeigneter Formulierung und unter Fachaufsicht; andere Bariumverbindungen können andere Eigenschaften haben.",
  },
  {
    id: "sodyum-fosfat",
    contextTr: "Sodyum fosfat Na₃PO₄ formüllü alkalin bir fosfat tuzudur. Üç sodyum atomu ile fosfat grubu, formüldeki atom sayılarının hesaplamaya etkisini açıkça gösterir.",
    usesTr: ["Temizlik ve yüzey işlemleri", "Su yumuşatma", "Kontrollü gıda ve proses uygulamaları"],
    safetyTr: "Farklı sodyum fosfat türleri ve hidratları vardır; Na₃PO₄ değeri başka fosfat tuzları için kullanılmamalıdır.",
    contextDe: "Natriumphosphat ist ein alkalisches Phosphatsalz mit der Formel Na₃PO₄. Drei Natriumatome und die Phosphatgruppe zeigen deutlich, wie Atomzahlen die Rechnung beeinflussen.",
    usesDe: ["Reinigung und Oberflächenprozesse", "Wasserenthärtung", "Kontrollierte Lebensmittel- und Prozessanwendungen"],
    safetyDe: "Es gibt verschiedene Natriumphosphate und Hydrate; der Wert für Na₃PO₄ darf nicht auf andere Phosphatsalze übertragen werden.",
  },
  {
    id: "diazot-monoksit",
    contextTr: "Diazot monoksit N₂O formüllü bir gazdır; iki azot ve bir oksijen atomu içerir. Azot oksitleri benzer isimlere sahip olsa da formülleri ve etkileri farklı olabilir.",
    usesTr: ["Tıbbi anestezi sistemleri", "Gıda sektöründe özel uygulamalar", "Laboratuvar ve proses gazları"],
    safetyTr: "Tıbbi veya gıda amaçlı kullanım, yalnızca ilgili kalite standardı ve uzman prosedürleriyle yapılmalıdır; kapalı alanlarda gaz güvenliği önemlidir.",
    contextDe: "Distickstoffmonoxid ist ein Gas mit der Formel N₂O aus zwei Stickstoff- und einem Sauerstoffatom. Stickoxide haben ähnliche Namen, können aber unterschiedliche Formeln und Wirkungen besitzen.",
    usesDe: ["Medizinische Anästhesiesysteme", "Spezielle Anwendungen in der Lebensmittelbranche", "Labor- und Prozessgase"],
    safetyDe: "Medizinische oder lebensmitteltechnische Nutzung erfolgt nur nach passender Qualitätsnorm und Fachverfahren; in geschlossenen Räumen ist Gassicherheit wichtig.",
  },
  {
    id: "azot-monoksit",
    contextTr: "Azot monoksit NO formüllü reaktif bir gazdır. Havada oksijenle tepkimeye girebildiği için çevresel ve yanma emisyonu değerlendirmelerinde çoğunlukla azot dioksitle birlikte ele alınır.",
    usesTr: ["Emisyon analizi", "Kimyasal sentez", "Biyomedikal araştırma"],
    safetyTr: "Solunum ve maruziyet riskleri nedeniyle gazla çalışma yalnızca ölçüm, havalandırma ve uzman kontrolü bulunan ortamlarda yapılmalıdır.",
    contextDe: "Stickstoffmonoxid ist ein reaktives Gas mit der Formel NO. Da es an Luft mit Sauerstoff reagieren kann, wird es bei Umwelt- und Verbrennungsemissionen oft zusammen mit Stickstoffdioxid betrachtet.",
    usesDe: ["Emissionsanalyse", "Chemische Synthese", "Biomedizinische Forschung"],
    safetyDe: "Wegen Atemwegs- und Expositionsrisiken darf mit dem Gas nur in Umgebungen mit Messung, Lüftung und Fachkontrolle gearbeitet werden.",
  },
  {
    id: "bakir-oksit",
    contextTr: "Bakır(II) oksit CuO formüllü siyah renkli bir bakır oksididir. Bakır ve oksijenin bire bir oranı, molar kütle hesabını doğrudan belirler.",
    usesTr: ["Seramik sırları ve pigmentler", "Kataliz", "Elektronik ve yarı iletken araştırmaları"],
    safetyTr: "Toz maruziyeti ve bakır içeren atıklar kontrol edilmelidir; ürünün kullanım sınıfı ile çevresel gereklilikler birlikte değerlendirilmelidir.",
    contextDe: "Kupfer(II)-oxid ist ein schwarzes Kupferoxid mit der Formel CuO. Das Verhältnis von Kupfer zu Sauerstoff eins zu eins bestimmt die Molmassenrechnung direkt.",
    usesDe: ["Keramikglasuren und Pigmente", "Katalyse", "Elektronik- und Halbleiterforschung"],
    safetyDe: "Staubexposition und kupferhaltige Abfälle müssen kontrolliert werden; Produktklasse und Umweltanforderungen sind gemeinsam zu berücksichtigen.",
  },
  {
    id: "mangan-dioksit",
    contextTr: "Mangan dioksit MnO₂ formüllü bir manganez oksididir. İki oksijen atomu içeren yapı, bileşiğin oksidasyon davranışı ve molar kütlesi açısından belirleyicidir.",
    usesTr: ["Piller", "Cam ve seramik işlemleri", "Katalitik ve su arıtma uygulamaları"],
    safetyTr: "Toz ve mangan bileşiklerine uzun süreli maruziyet kontrol edilmelidir; işyeri prosedürleri ve ürün güvenlik bilgisi izlenmelidir.",
    contextDe: "Mangandioxid ist ein Manganoxid mit der Formel MnO₂. Die Struktur mit zwei Sauerstoffatomen ist für Oxidationsverhalten und Molmasse entscheidend.",
    usesDe: ["Batterien", "Glas- und Keramikprozesse", "Katalytische und Wasseraufbereitungsanwendungen"],
    safetyDe: "Eine langfristige Exposition gegenüber Staub und Manganverbindungen muss kontrolliert werden; Arbeitsplatzverfahren und Sicherheitsdatenblatt beachten.",
  },
  {
    id: "titanyum-dioksit",
    contextTr: "Titanyum dioksit TiO₂ formüllü beyaz bir titanyum oksididir. Yüksek kırılma indisi ve opaklığı, onu kaplama ve pigment uygulamalarında önemli kılar.",
    usesTr: ["Boya ve plastik pigmentleri", "Güneş koruyucu ve kozmetik formülasyonlar", "Fotokatalitik yüzeyler"],
    safetyTr: "Ürünün tane boyutu, kaplaması ve kullanım biçimi önemlidir; özellikle toz ve nano ölçekteki ürünlerde üreticinin güvenlik bilgisi izlenmelidir.",
    contextDe: "Titandioxid ist ein weißes Titanoxid mit der Formel TiO₂. Sein hoher Brechungsindex und seine Deckkraft machen es für Beschichtungen und Pigmente bedeutsam.",
    usesDe: ["Pigmente für Farben und Kunststoffe", "Sonnenschutz- und Kosmetikformulierungen", "Photokatalytische Oberflächen"],
    safetyDe: "Korngröße, Beschichtung und Verwendungsform sind wichtig; besonders bei Pulver- und Nanoprodukten sind die Sicherheitsinformationen des Herstellers zu beachten.",
  },
  {
    id: "difosfor-pentoksit",
    contextTr: "Difosfor pentoksit P₂O₅ olarak yazılsa da pratik kimyada fosfor pentoksit terimi farklı moleküler yapıları kapsayabilir. Bu sayfadaki hesap, belirtilen P₂O₅ ampirik formülüne göre yapılır.",
    usesTr: ["Kimyasal sentez", "Kurutucu ve su çekici prosesler", "Fosfat kimyası"],
    safetyTr: "Su ile şiddetli ısı açığa çıkarabilir ve aşındırıcı ürünler oluşturabilir; nemden korunmalı, yalnızca uygun endüstriyel koşullarda kullanılmalıdır.",
    contextDe: "Diphosphorpentoxid wird oft als P₂O₅ geschrieben, obwohl der Begriff in der Praxis verschiedene Molekülstrukturen umfassen kann. Diese Seite rechnet mit der angegebenen empirischen Formel P₂O₅.",
    usesDe: ["Chemische Synthese", "Trocknungs- und Wasserentzugprozesse", "Phosphatchemie"],
    safetyDe: "Mit Wasser kann starke Wärmeentwicklung auftreten und es können ätzende Produkte entstehen; vor Feuchtigkeit schützen und nur unter geeigneten Industriebedingungen verwenden.",
  },
  {
    id: "aseton",
    contextTr: "Aseton C₃H₆O formüllü yaygın bir organik çözücüdür. Aynı elementleri içeren bazı başka bileşikler farklı yapıya sahip olabilir; bu nedenle isim ve formül birlikte değerlendirilir.",
    usesTr: ["Çözücü ve yüzey temizleme", "Polimer ve kimyasal üretim", "Laboratuvar işlemleri"],
    safetyTr: "Çok yanıcıdır ve buharı havayla yanıcı karışım oluşturabilir; tutuşturucu kaynaklardan uzak tutulmalı, yeterli havalandırma sağlanmalıdır.",
    contextDe: "Aceton ist ein verbreitetes organisches Lösungsmittel mit der Formel C₃H₆O. Andere Verbindungen mit denselben Elementen können eine andere Struktur besitzen, daher gehören Name und Formel zusammen betrachtet.",
    usesDe: ["Lösungsmittel und Oberflächenreinigung", "Polymer- und Chemieproduktion", "Laborarbeiten"],
    safetyDe: "Der Stoff ist leicht entzündbar und seine Dämpfe können mit Luft brennbare Gemische bilden; von Zündquellen fernhalten und ausreichend lüften.",
  },
  {
    id: "formaldehit",
    contextTr: "Formaldehit CH₂O formüllü en basit aldehitlerden biridir. Suda bulunan çözeltiler, gaz hâlindeki formaldehitten farklı derişim ve kullanım koşullarına sahip olabilir.",
    usesTr: ["Reçine ve ahşap ürünleri", "Kimyasal ara ürün", "Laboratuvar ve endüstriyel prosesler"],
    safetyTr: "Tahriş edici ve kanserojen risk taşıyan bir maddedir; maruziyet azaltılmalı ve kullanım yalnızca kontrollü endüstriyel veya laboratuvar ortamında yapılmalıdır.",
    contextDe: "Formaldehyd ist einer der einfachsten Aldehyde mit der Formel CH₂O. Wässrige Lösungen können andere Konzentrationen und Einsatzbedingungen als gasförmiger Formaldehyd haben.",
    usesDe: ["Harze und Holzwerkstoffe", "Chemisches Zwischenprodukt", "Labor- und Industrieprozesse"],
    safetyDe: "Der Stoff ist reizend und mit krebserzeugenden Risiken verbunden; Exposition minimieren und nur in kontrollierten Industrie- oder Laborumgebungen einsetzen.",
  },
  {
    id: "asetilen",
    contextTr: "Asetilen C₂H₂ formüllü, karbon atomları arasında üçlü bağ taşıyan bir hidrokarbondur. Bu bağ yapısı, onu reaksiyonlar ve yüksek sıcaklıklı alev uygulamaları için farklı kılar.",
    usesTr: ["Metal kesme ve kaynak", "Kimyasal sentez", "Özel aydınlatma ve laboratuvar gazları"],
    safetyTr: "Çok yanıcıdır; depolama ve kullanım ekipmanları gazın özelliklerine uygun olmalı, sızıntı ve tutuşturucu kaynaklar kontrol edilmelidir.",
    contextDe: "Acetylen ist ein Kohlenwasserstoff mit der Formel C₂H₂ und einer Dreifachbindung zwischen den Kohlenstoffatomen. Diese Bindung macht es für Reaktionen und Hochtemperaturflammen besonders.",
    usesDe: ["Metallschneiden und Schweißen", "Chemische Synthese", "Spezielle Beleuchtung und Laborgase"],
    safetyDe: "Das Gas ist sehr entzündbar; Lager- und Nutzungsgeräte müssen dazu passen sowie Leckagen und Zündquellen kontrolliert werden.",
  },
  {
    id: "ure",
    contextTr: "Üre CO(NH₂)₂ formüllü, karbonil ve iki amino grubu içeren organik bir bileşiktir. Parantez, NH₂ grubunun iki kez bulunduğunu gösterir ve atom sayısı hesabını etkiler.",
    usesTr: ["Gübre üretimi", "Reçine ve kimyasal prosesler", "Laboratuvar ve biyoteknoloji"],
    safetyTr: "Tarım, teknik ve laboratuvar ürünleri farklı saflık ve katkılar içerebilir; kullanım amacı için uygun ürün sınıfı seçilmelidir.",
    contextDe: "Harnstoff ist eine organische Verbindung mit der Formel CO(NH₂)₂ aus einer Carbonyl- und zwei Aminogruppen. Die Klammer zeigt die doppelte NH₂-Gruppe und beeinflusst die Atomzahl.",
    usesDe: ["Düngemittelproduktion", "Harz- und Chemieprozesse", "Labor und Biotechnologie"],
    safetyDe: "Landwirtschaftliche, technische und Laborprodukte können sich in Reinheit und Zusätzen unterscheiden; die Produktklasse muss zum Einsatzzweck passen.",
  },
  {
    id: "fenol",
    contextTr: "Fenol C₆H₅OH formüllü aromatik bir organik bileşiktir. Aromatik halka ve hidroksil grubu, çözücülük ve tepkime davranışını birlikte belirler.",
    usesTr: ["Reçine ve plastik üretimi", "Kimyasal ara ürün", "Kontrollü laboratuvar sentezi"],
    safetyTr: "Toksik ve aşındırıcı olabilir; deriyle temas ciddi zarar verebilir. Sadece uygun mühendislik kontrolleri olan ortamlarda kullanılmalıdır.",
    contextDe: "Phenol ist eine aromatische organische Verbindung mit der Formel C₆H₅OH. Aromatischer Ring und Hydroxylgruppe bestimmen gemeinsam Löslichkeit und Reaktionsverhalten.",
    usesDe: ["Herstellung von Harzen und Kunststoffen", "Chemisches Zwischenprodukt", "Kontrollierte Laborsynthese"],
    safetyDe: "Der Stoff kann giftig und ätzend sein; Hautkontakt kann schwere Schäden verursachen. Verwendung nur in Umgebungen mit geeigneten technischen Schutzmaßnahmen.",
  },
  {
    id: "kloroform",
    contextTr: "Kloroform CHCl₃ formüllü, bir karbon, bir hidrojen ve üç klor atomu içeren halojenli bir bileşiktir. Molar kütlesinde klor atomlarının katkısı büyüktür.",
    usesTr: ["Kontrollü kimyasal sentez", "Laboratuvar çözücüsü", "Tarihsel ve özel teknik uygulamalar"],
    safetyTr: "Zararlı buharlar oluşturabilir ve sağlık riski taşır; tüketici kullanımı için uygun değildir, yalnızca havalandırılmış profesyonel ortamlarda ele alınmalıdır.",
    contextDe: "Chloroform ist eine halogenierte Verbindung mit der Formel CHCl₃ aus einem Kohlenstoff-, einem Wasserstoff- und drei Chloratomen. Die Chloratome tragen stark zur Molmasse bei.",
    usesDe: ["Kontrollierte chemische Synthese", "Lösungsmittel im Labor", "Historische und spezielle technische Anwendungen"],
    safetyDe: "Es können schädliche Dämpfe entstehen und Gesundheitsrisiken bestehen; nicht für Verbraucher geeignet und nur in belüfteten professionellen Bereichen handhaben.",
  },
  {
    id: "gliserin",
    contextTr: "Gliserin veya gliserol C₃H₈O₃ formüllü, üç hidroksil grubu taşıyan bir organik bileşiktir. Bu yapı suyla etkileşimi ve viskozitesi açısından önemlidir.",
    usesTr: ["Kozmetik ve kişisel bakım", "Gıda ve ilaç formülasyonları", "Kimyasal hammadde"],
    safetyTr: "Ürün saflığı uygulamaya göre değişir; gıda veya farmasötik kullanımda yalnızca ilgili standarttaki ürünler tercih edilmelidir.",
    contextDe: "Glycerin oder Glycerol ist eine organische Verbindung mit der Formel C₃H₈O₃ und drei Hydroxylgruppen. Diese Struktur ist für Wasserwechselwirkung und Viskosität wichtig.",
    usesDe: ["Kosmetik und Körperpflege", "Lebensmittel- und Pharmarezepturen", "Chemischer Grundstoff"],
    safetyDe: "Die Produktreinheit ist anwendungsabhängig; für Lebensmittel oder Pharmazie dürfen nur Produkte nach der entsprechenden Norm verwendet werden.",
  },
  {
    id: "aspirin",
    contextTr: "Aspirin olarak bilinen asetilsalisilik asit C₉H₈O₄ formüllü bir organik bileşiktir. Bu sayfa yalnızca bileşiğin molar kütlesini ve formül kompozisyonunu hesaplar.",
    usesTr: ["Farmasötik üretim", "Analitik kalite kontrol", "Kimya eğitimi ve laboratuvar çalışmaları"],
    safetyTr: "İlaç dozu, uygunluğu veya tedavi kararı bu hesap sayfasından çıkarılamaz; sağlık konularında hekim veya eczacı yönlendirmesi gerekir.",
    contextDe: "Acetylsalicylsäure, bekannt als Aspirin, ist eine organische Verbindung mit der Formel C₉H₈O₄. Diese Seite berechnet nur Molmasse und Formelzusammensetzung.",
    usesDe: ["Pharmazeutische Herstellung", "Analytische Qualitätskontrolle", "Chemieunterricht und Laborarbeit"],
    safetyDe: "Dosis, Eignung oder Therapieentscheidungen lassen sich nicht aus dieser Rechenseite ableiten; gesundheitliche Fragen gehören zu Arzt oder Apotheke.",
  },
  {
    id: "parasetamol",
    contextTr: "Parasetamol C₈H₉NO₂ formüllü bir organik bileşiktir. Formülde bulunan azot ve oksijen atomları, benzer hidrokarbonlardan farklı bir molar kütle ve işlevsel grup yapısı oluşturur.",
    usesTr: ["Farmasötik üretim", "Analitik kalite kontrol", "Kimyasal eğitim"],
    safetyTr: "İlaç kullanımı, doz veya birlikte kullanım hakkında bu sayfa tıbbi tavsiye değildir; ürün prospektüsü ve sağlık uzmanı yönlendirmesi esas alınmalıdır.",
    contextDe: "Paracetamol ist eine organische Verbindung mit der Formel C₈H₉NO₂. Stickstoff und Sauerstoff in der Formel führen zu einer anderen Molmasse und funktionellen Gruppenstruktur als bei ähnlichen Kohlenwasserstoffen.",
    usesDe: ["Pharmazeutische Herstellung", "Analytische Qualitätskontrolle", "Chemieunterricht"],
    safetyDe: "Diese Seite ist keine medizinische Beratung zu Einnahme, Dosis oder Kombinationen; Packungsinformation und Fachberatung sind maßgeblich.",
  },
  {
    id: "flor-gazi",
    contextTr: "Flor gazı F₂ formüllü iki atomlu bir halojen molekülüdür. Flor atomunun kütlesi ile F₂ gazının molar kütlesi, atom sayısı nedeniyle birbirinden farklıdır.",
    usesTr: ["Flor kimyasının üretimi", "Kontrollü malzeme işlemleri", "Özel endüstriyel sentez"],
    safetyTr: "Aşırı reaktif ve çok tehlikelidir; yalnızca özel tasarlanmış tesislerde uzman personel tarafından ele alınmalıdır.",
    contextDe: "Fluorgas ist ein zweiatomiges Halogenmolekül mit der Formel F₂. Wegen der Atomzahl unterscheiden sich Atommasse von Fluor und Molmasse des F₂-Gases.",
    usesDe: ["Herstellung von Fluorchemikalien", "Kontrollierte Materialprozesse", "Spezielle Industriesynthese"],
    safetyDe: "Das Gas ist extrem reaktiv und hochgefährlich; Umgang nur durch Fachpersonal in speziell ausgelegten Anlagen.",
  },
  {
    id: "argon-gazi",
    contextTr: "Argon Ar formüllü tek atomlu bir soy gazdır. Bu nedenle atomik kütlesi ile bir mol argon gazının molar kütlesi sayısal olarak aynıdır.",
    usesTr: ["Kaynak koruyucu gazı", "Isı yalıtım camı", "Metalurji ve elektronik atmosferleri"],
    safetyTr: "Yanıcı veya toksik değildir ancak kapalı alanlarda oksijeni seyreltebilir; özellikle tank ve çukur alanlarda oksijen izlemesi gerekir.",
    contextDe: "Argon ist ein einatomiges Edelgas mit der Formel Ar. Deshalb sind Atommasse und Molmasse eines Mols Argongas zahlenmäßig gleich.",
    usesDe: ["Schutzgas beim Schweißen", "Wärmedämmendes Isolierglas", "Atmosphären in Metallurgie und Elektronik"],
    safetyDe: "Das Gas ist nicht brennbar oder giftig, kann in geschlossenen Räumen aber Sauerstoff verdrängen; besonders in Behältern und Gruben ist Sauerstoffüberwachung nötig.",
  },
  {
    id: "sitrik-asit",
    contextTr: "Sitrik asit C₆H₈O₇ formüllü, birden çok karboksil grubu içeren organik bir asittir. Doğal kaynaklarda bulunmasına rağmen ticari ürünün saflığı ve derişimi uygulamaya göre değişir.",
    usesTr: ["Gıda asitliği düzenleme", "Temizlik ve kireç çözme", "İlaç ve kozmetik formülasyonları"],
    safetyTr: "Seyreltilmiş ürünler ile konsantre toz veya çözeltiler aynı etkiye sahip değildir; göz ve cilt tahrişini önlemek için etiket talimatları izlenmelidir.",
    contextDe: "Citronensäure ist eine organische Säure mit mehreren Carboxylgruppen und der Formel C₆H₈O₇. Sie kommt natürlich vor, doch Reinheit und Konzentration eines Handelsprodukts hängen von der Anwendung ab.",
    usesDe: ["Säureregulierung in Lebensmitteln", "Reinigung und Entkalkung", "Pharma- und Kosmetikformulierungen"],
    safetyDe: "Verdünnte Produkte und konzentrierte Pulver oder Lösungen haben nicht dieselbe Wirkung; Kennzeichnung beachten, um Augen- und Hautreizungen zu vermeiden.",
  },
  {
    id: "laktik-asit",
    contextTr: "Laktik asit C₃H₆O₃ formüllü organik bir asittir ve fermantasyon süreçleriyle ilişkilidir. Aynı formüle sahip optik izomerler bulunabileceği için uygulamada maddenin tam türü önemlidir.",
    usesTr: ["Gıda fermantasyonu", "Kozmetik ve kişisel bakım", "Polilaktik asit üretimi"],
    safetyTr: "Derişim ve ürün sınıfı uygulamaya göre değişir; gıda, kozmetik ve teknik ürünler kendi uygunluk standartlarına göre kullanılmalıdır.",
    contextDe: "Milchsäure ist eine organische Säure mit der Formel C₃H₆O₃ und steht mit Fermentationsprozessen in Verbindung. Da optische Isomere existieren, ist in Anwendungen die genaue Form wichtig.",
    usesDe: ["Lebensmittelfermentation", "Kosmetik und Körperpflege", "Herstellung von Polymilchsäure"],
    safetyDe: "Konzentration und Produktklasse sind anwendungsabhängig; Lebensmittel-, Kosmetik- und technische Produkte müssen nach ihren jeweiligen Normen verwendet werden.",
  },
  {
    id: "hidrobromik-asit",
    contextTr: "Hidrobromik asit HBr formüllü, suda çözünmüş hidrojen bromürle ilişkili güçlü bir asittir. Formüldeki bir hidrojen ve bir brom atomu, referans molar kütleyi oluşturur.",
    usesTr: ["Bromür kimyası", "Kimyasal sentez", "Kontrollü yüzey ve proses işlemleri"],
    safetyTr: "Aşındırıcı buhar ve çözeltiler oluşturabilir; asit işlemleri yalnızca uygun havalandırma, malzeme uyumluluğu ve korumayla yapılmalıdır.",
    contextDe: "Bromwasserstoffsäure ist eine starke Säure, die mit in Wasser gelöstem Bromwasserstoff der Formel HBr zusammenhängt. Ein Wasserstoff- und ein Bromatom ergeben die Referenzmolmasse.",
    usesDe: ["Bromidchemie", "Chemische Synthese", "Kontrollierte Oberflächen- und Prozessverfahren"],
    safetyDe: "Es können ätzende Dämpfe und Lösungen entstehen; Säurearbeiten nur mit geeigneter Lüftung, Werkstoffverträglichkeit und Schutzmaßnahmen durchführen.",
  },
  {
    id: "lityum-hidroksit",
    contextTr: "Lityum hidroksit LiOH formüllü güçlü bir bazdır. Bir lityum, bir oksijen ve bir hidrojen atomundan oluşan formül, hesaplamadaki atomik katkıları doğrudan gösterir.",
    usesTr: ["Pil ve enerji sistemleri", "Karbon dioksit tutma prosesleri", "Kimyasal sentez"],
    safetyTr: "Aşındırıcıdır ve nemle temasında ısı açığa çıkarabilir; depolama, çözündürme ve kişisel koruma ürün güvenlik bilgisine göre yapılmalıdır.",
    contextDe: "Lithiumhydroxid ist eine starke Base mit der Formel LiOH. Ein Lithium-, ein Sauerstoff- und ein Wasserstoffatom zeigen die atomaren Beiträge zur Rechnung direkt.",
    usesDe: ["Batterie- und Energiesysteme", "Kohlendioxidbindung in Prozessen", "Chemische Synthese"],
    safetyDe: "Der Stoff ist ätzend und kann mit Feuchtigkeit Wärme entwickeln; Lagerung, Lösen und Schutzausrüstung müssen dem Sicherheitsdatenblatt folgen.",
  },
  {
    id: "magnezyum-sulfat",
    contextTr: "Magnezyum sülfat MgSO₄ formüllü bir tuzdur. Epsom tuzu olarak bilinen hidratlı türlerinde kristal suyu bulunduğundan, anhidrat ve hidrat formülleri aynı molar kütleye sahip değildir.",
    usesTr: ["Tarım ve gübre uygulamaları", "Tekstil ve proses kimyası", "Laboratuvar ve özel formülasyonlar"],
    safetyTr: "Ürün sınıfı kullanım amacına göre değişir; tıbbi veya beslenme amaçları için yalnızca ilgili standarttaki ürünler ve uzman önerisi kullanılmalıdır.",
    contextDe: "Magnesiumsulfat ist ein Salz mit der Formel MgSO₄. Bei hydratisierten Formen, bekannt etwa als Bittersalz, verändert Kristallwasser die Molmasse gegenüber der wasserfreien Form.",
    usesDe: ["Landwirtschaft und Düngung", "Textil- und Prozesschemie", "Labor und Spezialformulierungen"],
    safetyDe: "Die Produktklasse hängt vom Einsatzzweck ab; für Medizin oder Ernährung dürfen nur geeignete Normprodukte und Fachberatung herangezogen werden.",
  },
  {
    id: "sodyum-florur",
    contextTr: "Sodyum florür NaF formüllü, sodyum ve florun bire bir oranla bulunduğu iyonik bir tuzdur. Küçük formülüne rağmen uygulama alanı ve güvenlik gereksinimleri ürün derişimine bağlıdır.",
    usesTr: ["Kontrollü ağız bakım ürünleri", "Cam ve metal prosesleri", "Laboratuvar reaktifi"],
    safetyTr: "Fazla maruziyet zararlı olabilir; gıda, diş ürünü ve teknik kalite ürünler kesinlikle birbirinin yerine kullanılmamalıdır.",
    contextDe: "Natriumfluorid ist ein ionisches Salz mit der Formel NaF, in der Natrium und Fluor im Verhältnis eins zu eins vorliegen. Trotz der kleinen Formel hängen Anwendung und Sicherheit von der Konzentration ab.",
    usesDe: ["Kontrollierte Mundpflegeprodukte", "Glas- und Metallprozesse", "Laborreagenz"],
    safetyDe: "Übermäßige Exposition kann schädlich sein; Lebensmittel-, Dental- und technische Qualitäten dürfen keinesfalls ausgetauscht werden.",
  },
  {
    id: "potasyum-iyodur",
    contextTr: "Potasyum iyodür KI formüllü iyonik bir tuzdur. Potasyum ve iyodun bire bir atom oranı, molar kütleyi iki elementin atomik kütleleri toplamına indirger.",
    usesTr: ["Laboratuvar ve analitik kimya", "Fotoğrafçılıkta özel uygulamalar", "Kontrollü farmasötik üretim"],
    safetyTr: "İyot ve sağlıkla ilgili kullanımlarda doz kritik olabilir; bu sayfa tıbbi kullanım veya doz önerisi değildir.",
    contextDe: "Kaliumiodid ist ein ionisches Salz mit der Formel KI. Das Verhältnis eins zu eins reduziert die Molmasse auf die Summe der Atommassen von Kalium und Iod.",
    usesDe: ["Labor und analytische Chemie", "Spezielle Anwendungen in der Fotografie", "Kontrollierte pharmazeutische Herstellung"],
    safetyDe: "Bei Iod- und Gesundheitsanwendungen kann die Dosis entscheidend sein; diese Seite ist keine Empfehlung zur medizinischen Verwendung oder Dosierung.",
  },
  {
    id: "sodyum-tiyosulfat",
    contextTr: "Sodyum tiyosülfat Na₂S₂O₃ formüllü bir kükürt oksianyon tuzudur. İki sodyum, iki kükürt ve üç oksijen atomu, formülün sıradan sülfattan farklı olduğunu gösterir.",
    usesTr: ["Fotoğrafçılıkta sabitleme", "Analitik iyodometri", "Su ve kimyasal prosesler"],
    safetyTr: "Hidratlı ürünler yaygındır; gerçek ürün formülü ve molar kütlesi satın alınan malzemenin teknik belgesinden teyit edilmelidir.",
    contextDe: "Natriumthiosulfat ist ein Salz des Schwefel-Oxyanions mit der Formel Na₂S₂O₃. Zwei Natrium-, zwei Schwefel- und drei Sauerstoffatome unterscheiden die Formel von gewöhnlichem Sulfat.",
    usesDe: ["Fixieren in der Fotografie", "Iodometrie in der Analytik", "Wasser- und Chemieprozesse"],
    safetyDe: "Hydratisierte Produkte sind verbreitet; tatsächliche Formel und Molmasse müssen in der technischen Dokumentation des gekauften Materials geprüft werden.",
  },
  {
    id: "potasyum-dikromat",
    contextTr: "Potasyum dikromat K₂Cr₂O₇ formüllü, krom içeren güçlü oksitleyici bir tuzdur. İki krom atomu ve yedi oksijen atomu içeren dikromat grubu, sıradan krom tuzlarından farklıdır.",
    usesTr: ["Tarihsel analitik kimya", "Kontrollü yüzey işlemleri", "Referans ve araştırma uygulamaları"],
    safetyTr: "Altı değerlikli krom bileşikleri ciddi sağlık ve çevre riski taşır; birçok kullanım kısıtlıdır ve yalnızca sıkı kontrol altında ele alınmalıdır.",
    contextDe: "Kaliumdichromat ist ein stark oxidierendes Chromsalz mit der Formel K₂Cr₂O₇. Die Dichromatgruppe mit zwei Chrom- und sieben Sauerstoffatomen unterscheidet sich von einfachen Chromsalzen.",
    usesDe: ["Historische analytische Chemie", "Kontrollierte Oberflächenprozesse", "Referenz- und Forschungsanwendungen"],
    safetyDe: "Sechswertige Chromverbindungen bergen erhebliche Gesundheits- und Umweltrisiken; viele Anwendungen sind eingeschränkt und nur unter strenger Kontrolle zulässig.",
  },
  {
    id: "demir-ii-klorur",
    contextTr: "Demir(II) klorür FeCl₂ formüllü bir demir tuzudur. Demir(II) ve demir(III) klorür farklı formül, yükseltgenme basamağı ve uygulama davranışına sahiptir.",
    usesTr: ["Su ve atık su prosesleri", "Kimyasal sentez", "Laboratuvar redoks işlemleri"],
    safetyTr: "Hava ve nem, demir(II) bileşiklerinin davranışını değiştirebilir; depolama koşulu ve ürün saflığı teknik talimata göre izlenmelidir.",
    contextDe: "Eisen(II)-chlorid ist ein Eisensalz mit der Formel FeCl₂. Eisen(II)- und Eisen(III)-chlorid unterscheiden sich in Formel, Oxidationsstufe und Anwendungsverhalten.",
    usesDe: ["Wasser- und Abwasserprozesse", "Chemische Synthese", "Redoxverfahren im Labor"],
    safetyDe: "Luft und Feuchtigkeit können das Verhalten von Eisen(II)-Verbindungen verändern; Lagerbedingungen und Reinheit sind nach technischen Vorgaben zu beachten.",
  },
  {
    id: "cinko-klorur",
    contextTr: "Çinko klorür ZnCl₂ formüllü, çinko ve iki klor atomu içeren iyonik bir bileşiktir. Suda çözünürlüğü ve nem çekiciliği bazı teknik uygulamalarda önemlidir.",
    usesTr: ["Metal yüzey işlemleri", "Ahşap ve tekstil prosesleri", "Lehim ve kimyasal üretim"],
    safetyTr: "Aşındırıcı ve çevresel açıdan zararlı olabilir; çözelti ve atıklar yerel güvenlik ile bertaraf prosedürlerine göre yönetilmelidir.",
    contextDe: "Zinkchlorid ist eine ionische Verbindung mit der Formel ZnCl₂ aus Zink und zwei Chloratomen. Wasserlöslichkeit und Feuchtigkeitsaufnahme sind für einige technische Anwendungen bedeutsam.",
    usesDe: ["Metalloberflächenprozesse", "Holz- und Textilverarbeitung", "Löten und Chemieproduktion"],
    safetyDe: "Der Stoff kann ätzend und umweltschädlich sein; Lösungen und Abfälle müssen nach lokalen Sicherheits- und Entsorgungsverfahren behandelt werden.",
  },
  {
    id: "cinko-sulfat",
    contextTr: "Çinko sülfat ZnSO₄ formüllü bir çinko tuzudur. Hidratlı türleri bulunduğundan, kullanılan malzemenin kristal suyu içeriği gerçek molar kütle için önem taşır.",
    usesTr: ["Tarım ve mikro besin formülasyonları", "Elektrokaplama", "Laboratuvar analizi"],
    safetyTr: "Çinko bileşikleri su ortamına kontrolsüz bırakılmamalıdır; uygulama dozu ve ürün sınıfı teknik veya uzman bilgisine göre belirlenmelidir.",
    contextDe: "Zinksulfat ist ein Zinksalz mit der Formel ZnSO₄. Da hydratisierte Formen vorkommen, ist der Kristallwasseranteil des Materials für die tatsächliche Molmasse wichtig.",
    usesDe: ["Landwirtschaft und Mikronährstoffformulierungen", "Galvanik", "Laboranalytik"],
    safetyDe: "Zinkverbindungen dürfen nicht unkontrolliert in Gewässer gelangen; Anwendungsmengen und Produktklasse sind nach technischen oder fachlichen Vorgaben festzulegen.",
  },
  {
    id: "potasyum-sulfat",
    contextTr: "Potasyum sülfat K₂SO₄ formüllü bir potasyum tuzudur. İki potasyum atomu ve sülfat grubunun birlikte hesaplanması, formülün molar kütlesini verir.",
    usesTr: ["Klorüre duyarlı ürünler için gübre", "Cam ve kimyasal prosesler", "Özel laboratuvar uygulamaları"],
    safetyTr: "Tarım ürünlerinde formülasyon ve miktar önemlidir; bu sayfa gübreleme programı veya uygulama dozu önermez.",
    contextDe: "Kaliumsulfat ist ein Kaliumsalz mit der Formel K₂SO₄. Zwei Kaliumatome und die Sulfatgruppe ergeben gemeinsam die Molmasse der Formel.",
    usesDe: ["Dünger für chloridempfindliche Kulturen", "Glas- und Chemieprozesse", "Spezielle Laboranwendungen"],
    safetyDe: "Bei landwirtschaftlichen Produkten sind Formulierung und Menge wichtig; diese Seite empfiehlt weder Düngungsprogramme noch Ausbringmengen.",
  },
  {
    id: "magnezyum-karbonat",
    contextTr: "Magnezyum karbonat MgCO₃ formüllü bir karbonat tuzudur. Doğal veya ticari ürünlerde hidratlar ve karışımlar bulunabileceğinden, malzeme tanımı formül kadar önemlidir.",
    usesTr: ["Spor ve tutuş uygulamaları", "Refrakter malzemeler", "Dolgu ve proses kimyası"],
    safetyTr: "Tozlu ürünlerde solunum maruziyeti azaltılmalıdır; gıda, kozmetik ve teknik kalite ürünler uygunluk bakımından ayrıdır.",
    contextDe: "Magnesiumcarbonat ist ein Carbonatsalz mit der Formel MgCO₃. Da natürliche oder Handelsprodukte Hydrate und Mischungen enthalten können, ist die Materialbezeichnung ebenso wichtig wie die Formel.",
    usesDe: ["Sport- und Griffanwendungen", "Feuerfeste Materialien", "Füllstoff und Prozesschemie"],
    safetyDe: "Bei Pulverprodukten sollte die Atemwegsexposition verringert werden; Lebensmittel-, Kosmetik- und technische Qualitäten unterscheiden sich in ihrer Eignung.",
  },
  {
    id: "baryum-karbonat",
    contextTr: "Baryum karbonat BaCO₃ formüllü, suda az çözünen bir baryum tuzudur. Çözünürlük düşük olsa da diğer baryum bileşikleriyle aynı güvenlik değerlendirmesine tabi tutulmamalıdır.",
    usesTr: ["Seramik ve cam sırları", "Tuğla ve refrakter malzemeler", "Özel kimyasal üretim"],
    safetyTr: "Zararlı olabilir; toz kontrolü, kişisel koruma ve atık yönetimi yalnızca endüstriyel güvenlik prosedürleriyle yürütülmelidir.",
    contextDe: "Bariumcarbonat ist ein schwer lösliches Bariumsalz mit der Formel BaCO₃. Trotz geringer Löslichkeit darf es nicht pauschal wie andere Bariumverbindungen bewertet werden.",
    usesDe: ["Keramik- und Glasglasuren", "Ziegel und feuerfeste Materialien", "Spezielle Chemieproduktion"],
    safetyDe: "Der Stoff kann schädlich sein; Staubkontrolle, Schutzausrüstung und Abfallmanagement gehören in industrielle Sicherheitsverfahren.",
  },
  {
    id: "bakir-ii-klorur",
    contextTr: "Bakır(II) klorür CuCl₂ formüllü, bakır ve iki klor atomu içeren bir tuzdur. Susuz ve hidratlı biçimler renk ve molar kütle bakımından farklılık gösterebilir.",
    usesTr: ["Katalitik kimya", "Pigment ve yüzey işlemleri", "Laboratuvar sentezi"],
    safetyTr: "Bakır ve klorür içeren çözeltiler çevresel risk taşıyabilir; kullanım ve bertaraf işlemleri ürün güvenlik dokümanına göre yapılmalıdır.",
    contextDe: "Kupfer(II)-chlorid ist ein Salz mit der Formel CuCl₂ aus Kupfer und zwei Chloratomen. Wasserfreie und hydratisierte Formen können sich in Farbe und Molmasse unterscheiden.",
    usesDe: ["Katalytische Chemie", "Pigment- und Oberflächenprozesse", "Laborsynthese"],
    safetyDe: "Kupfer- und chloridhaltige Lösungen können Umweltrisiken bergen; Nutzung und Entsorgung müssen dem Sicherheitsdatenblatt folgen.",
  },
  {
    id: "kursun-ii-nitrat",
    contextTr: "Kurşun(II) nitrat Pb(NO₃)₂ formüllü bir kurşun tuzudur. Parantezli nitrat grubu iki kez bulunduğundan formülde iki azot ve altı oksijen atomu yer alır.",
    usesTr: ["Tarihsel ve özel analitik uygulamalar", "Kontrollü malzeme araştırması", "Referans kimyası"],
    safetyTr: "Kurşun bileşikleri toksiktir ve nitrat grubu oksitleyici davranış gösterebilir; kullanım birçok alanda kısıtlıdır ve sadece uzman kontrolünde yapılmalıdır.",
    contextDe: "Blei(II)-nitrat ist ein Bleisalz mit der Formel Pb(NO₃)₂. Die Nitratgruppe steht zweimal in Klammern, daher enthält die Formel zwei Stickstoff- und sechs Sauerstoffatome.",
    usesDe: ["Historische und spezielle Analytik", "Kontrollierte Materialforschung", "Referenzchemie"],
    safetyDe: "Bleiverbindungen sind giftig und die Nitratgruppe kann oxidierendes Verhalten zeigen; der Einsatz ist vielerorts eingeschränkt und nur unter Fachkontrolle zulässig.",
  },
  {
    id: "sodyum-sulfur",
    contextTr: "Sodyum sülfür Na₂S formüllü bir sodyum ve sülfür tuzudur. Su ve asitlerle etkileşiminde farklı kükürt türleri veya gazlar oluşabileceğinden proses koşulları önemlidir.",
    usesTr: ["Deri ve tekstil prosesleri", "Cevher zenginleştirme", "Kimyasal sentez"],
    safetyTr: "Asitlerle temasında zehirli hidrojen sülfür gazı açığa çıkabilir; yalnızca uygun havalandırma ve kontrollü endüstriyel sistemlerde kullanılmalıdır.",
    contextDe: "Natriumsulfid ist ein Salz aus Natrium und Schwefel mit der Formel Na₂S. Bei Kontakt mit Wasser und Säuren können unterschiedliche Schwefelspezies oder Gase entstehen, daher sind Prozessbedingungen wichtig.",
    usesDe: ["Leder- und Textilprozesse", "Erzaufbereitung", "Chemische Synthese"],
    safetyDe: "Bei Kontakt mit Säuren kann giftiger Schwefelwasserstoff entstehen; Verwendung nur in geeigneter Lüftung und kontrollierten Industriesystemen.",
  },
  {
    id: "kalsiyum-karbur",
    contextTr: "Kalsiyum karbür CaC₂ formüllü bir kalsiyum-karbon bileşiğidir. Su ile tepkimesi asetilen gazı oluşturabildiğinden, formülün kendisi proses güvenliği açısından da önem taşır.",
    usesTr: ["Kontrollü asetilen üretimi", "Metalurji", "Kimyasal sentez"],
    safetyTr: "Su veya nemle temasında yanıcı gaz oluşabilir; kapalı, kuru ve uygun havalandırmalı endüstriyel koşullar dışında kullanılmamalıdır.",
    contextDe: "Calciumcarbid ist eine Calcium-Kohlenstoff-Verbindung mit der Formel CaC₂. Da die Reaktion mit Wasser Acetylen erzeugen kann, ist die Formel auch für die Prozesssicherheit bedeutsam.",
    usesDe: ["Kontrollierte Acetylenherstellung", "Metallurgie", "Chemische Synthese"],
    safetyDe: "Bei Kontakt mit Wasser oder Feuchtigkeit kann brennbares Gas entstehen; nur in trockenen, geschlossenen und ausreichend belüfteten Industriebedingungen verwenden.",
  },
  {
    id: "sodyum-bromur",
    contextTr: "Sodyum bromür NaBr formüllü, sodyum ve bromun bire bir oranla bulunduğu iyonik bir tuzdur. Formül basit olsa da ürün sınıfı uygulamaya göre önemli ölçüde değişebilir.",
    usesTr: ["Özel kimyasal üretim", "Fotoğrafçılıkta tarihsel uygulamalar", "Laboratuvar analizi"],
    safetyTr: "Tıbbi, gıda ve teknik kullanım sınıfları birbirinden farklıdır; kullanım amacı için yalnızca uygun etiketli ürünler değerlendirilmelidir.",
    contextDe: "Natriumbromid ist ein ionisches Salz mit der Formel NaBr, in der Natrium und Brom im Verhältnis eins zu eins vorliegen. Trotz der einfachen Formel kann die Produktklasse je nach Anwendung stark variieren.",
    usesDe: ["Spezielle Chemieproduktion", "Historische Anwendungen in der Fotografie", "Laboranalytik"],
    safetyDe: "Medizinische, Lebensmittel- und technische Qualitäten sind unterschiedlich; für einen Zweck dürfen nur passend gekennzeichnete Produkte verwendet werden.",
  },
  {
    id: "sodyum-oksit",
    contextTr: "Sodyum oksit Na₂O formüllü güçlü bazik karakterli bir oksittir. Su ile tepkimesinde sodyum hidroksit oluşabileceği için nem ve süreç koşulları önemlidir.",
    usesTr: ["Cam ve seramik kimyası", "Özel malzeme sentezi", "Laboratuvar araştırması"],
    safetyTr: "Su ile şiddetle tepkime verebilir ve aşındırıcı ürünler oluşturabilir; genel kullanım için uygun değildir.",
    contextDe: "Natriumoxid ist ein stark basisches Oxid mit der Formel Na₂O. Da bei der Reaktion mit Wasser Natriumhydroxid entstehen kann, sind Feuchtigkeit und Prozessbedingungen wichtig.",
    usesDe: ["Glas- und Keramikchemie", "Spezielle Materialsynthese", "Laborforschung"],
    safetyDe: "Der Stoff kann mit Wasser heftig reagieren und ätzende Produkte bilden; er ist nicht für allgemeine Anwendungen geeignet.",
  },
  {
    id: "potasyum-oksit",
    contextTr: "Potasyum oksit K₂O formüllü, iki potasyum ve bir oksijen atomu içeren bazik bir oksittir. Suya karşı yüksek tepkimesi, serbest bileşiğin sınırlı kullanımını açıklar.",
    usesTr: ["Cam ve seramik bileşimleri", "Özel kimyasal sentez", "Malzeme araştırması"],
    safetyTr: "Nem ve suyla temasında aşındırıcı potasyum hidroksit oluşabilir; yalnızca uzman proseslerde ele alınmalıdır.",
    contextDe: "Kaliumoxid ist ein basisches Oxid mit der Formel K₂O aus zwei Kalium- und einem Sauerstoffatom. Seine hohe Reaktivität mit Wasser erklärt die begrenzte Nutzung der freien Verbindung.",
    usesDe: ["Glas- und Keramikzusammensetzungen", "Spezielle chemische Synthese", "Materialforschung"],
    safetyDe: "Bei Kontakt mit Feuchtigkeit und Wasser kann ätzendes Kaliumhydroxid entstehen; Handhabung nur in Fachprozessen.",
  },
  {
    id: "baryum-oksit",
    contextTr: "Baryum oksit BaO formüllü bazik bir metal oksittir. Su ve karbondioksitle etkileşimi, depolama koşullarının ve gerçek ürün bileşiminin önemli olmasına neden olur.",
    usesTr: ["Özel cam ve seramik", "Elektronik malzemeler", "Kimyasal sentez"],
    safetyTr: "Aşındırıcı ve baryum kaynaklı toksik risk taşıyabilir; yalnızca kontrollü endüstriyel veya laboratuvar koşullarında kullanılmalıdır.",
    contextDe: "Bariumoxid ist ein basisches Metalloxid mit der Formel BaO. Die Wechselwirkung mit Wasser und Kohlendioxid macht Lagerbedingungen und tatsächliche Produktzusammensetzung wichtig.",
    usesDe: ["Spezialglas und Keramik", "Elektronische Materialien", "Chemische Synthese"],
    safetyDe: "Der Stoff kann ätzende und bariumbezogene toxische Risiken bergen; Verwendung nur unter kontrollierten Industrie- oder Laborbedingungen.",
  },
  {
    id: "krom-oksit",
    contextTr: "Krom(III) oksit Cr₂O₃ formüllü, kararlı yeşil renkli bir krom oksididir. Kromun değerliği önemlidir; krom(III) oksit, altı değerlikli krom bileşiklerinden farklı özellik taşır.",
    usesTr: ["Yeşil pigmentler", "Aşındırıcı ve parlatıcı ürünler", "Refrakter seramik"],
    safetyTr: "Toz maruziyeti azaltılmalı ve krom bileşiklerinin türü net biçimde ayrılmalıdır; her krom ürünü aynı risk profiline sahip değildir.",
    contextDe: "Chrom(III)-oxid ist ein stabiles grünes Chromoxid mit der Formel Cr₂O₃. Die Oxidationsstufe ist wichtig: Es besitzt andere Eigenschaften als sechswertige Chromverbindungen.",
    usesDe: ["Grüne Pigmente", "Schleif- und Polierprodukte", "Feuerfeste Keramik"],
    safetyDe: "Staubexposition reduzieren und die Art der Chromverbindung klar unterscheiden; nicht jedes Chromprodukt hat dasselbe Risikoprofil.",
  },
  {
    id: "kursun-ii-oksit",
    contextTr: "Kurşun(II) oksit PbO formüllü bir kurşun oksididir. Kurşunun oksitlenme basamağı bileşiğin renk, tepkime ve malzeme davranışı üzerinde etkili olabilir.",
    usesTr: ["Tarihsel cam ve seramik uygulamaları", "Özel elektronik ve malzeme araştırması", "Kontrollü kimyasal prosesler"],
    safetyTr: "Kurşun bileşikleri toksiktir; kullanım birçok alanda sınırlandırılmıştır ve atıklar kesinlikle uygun toplama sistemleriyle yönetilmelidir.",
    contextDe: "Blei(II)-oxid ist ein Bleioxid mit der Formel PbO. Die Oxidationsstufe von Blei kann Farbe, Reaktivität und Werkstoffverhalten der Verbindung beeinflussen.",
    usesDe: ["Historische Glas- und Keramikanwendungen", "Spezielle Elektronik- und Materialforschung", "Kontrollierte chemische Prozesse"],
    safetyDe: "Bleiverbindungen sind giftig; ihr Einsatz ist vielfach eingeschränkt und Abfälle müssen zwingend über geeignete Sammelsysteme entsorgt werden.",
  },
  {
    id: "kafein",
    contextTr: "Kafein C₈H₁₀N₄O₂ formüllü, azot içeren doğal bir alkaloiddir. Molar kütle, laboratuvar standartları ve formülasyon hesaplarında maddenin miktarını mol cinsinden ilişkilendirmek için kullanılır.",
    usesTr: ["Gıda ve içecek ürünleri", "Farmasötik üretim", "Analitik kalite kontrol"],
    safetyTr: "Tüketim miktarı kişiye ve ürüne göre etkili olabilir; bu hesap sayfası kafein dozu veya sağlık önerisi sunmaz.",
    contextDe: "Koffein ist ein stickstoffhaltiges natürliches Alkaloid mit der Formel C₈H₁₀N₄O₂. Die Molmasse verbindet in Laborstandards und Formulierungsrechnungen Stoffmenge und Masse.",
    usesDe: ["Lebensmittel- und Getränkeprodukte", "Pharmazeutische Herstellung", "Analytische Qualitätskontrolle"],
    safetyDe: "Die Wirkung der Aufnahme kann von Person und Produkt abhängen; diese Rechenseite gibt keine Dosis- oder Gesundheitsempfehlung für Koffein.",
  },
  {
    id: "toluen",
    contextTr: "Toluen C₇H₈ formüllü aromatik bir hidrokarbondur. Benzen halkasına bağlı metil grubu, çözücü özellikleri ve kimyasal sentezdeki rolü açısından önemlidir.",
    usesTr: ["Boya ve kaplama çözücüleri", "Kimyasal ara ürün", "Laboratuvar ve malzeme prosesleri"],
    safetyTr: "Yanıcıdır ve buharı sağlık riski oluşturabilir; profesyonel havalandırma, maruziyet kontrolü ve uygun kişisel koruma gerekir.",
    contextDe: "Toluol ist ein aromatischer Kohlenwasserstoff mit der Formel C₇H₈. Die an den Benzolring gebundene Methylgruppe ist für Lösungsmittelverhalten und Syntheserolle wichtig.",
    usesDe: ["Lösungsmittel für Farben und Beschichtungen", "Chemisches Zwischenprodukt", "Labor- und Materialprozesse"],
    safetyDe: "Der Stoff ist entzündbar und seine Dämpfe können ein Gesundheitsrisiko darstellen; professionelle Lüftung, Expositionskontrolle und passende Schutzausrüstung sind erforderlich.",
  },
  {
    id: "karbon-tetraklorur",
    contextTr: "Karbon tetraklorür CCl₄ formüllü, bir karbon ve dört klor atomu içeren halojenli bir bileşiktir. Klor atomlarının yüksek kütlesi, molar kütlenin büyük bölümünü oluşturur.",
    usesTr: ["Tarihsel endüstriyel çözücü uygulamaları", "Referans ve araştırma çalışmaları", "Kontrollü kimyasal analiz"],
    safetyTr: "Zehirli ve çevre için zararlı olabilir; birçok kullanım kısıtlanmıştır. Tüketici kullanımı için uygun değildir.",
    contextDe: "Tetrachlorkohlenstoff ist eine halogenierte Verbindung mit der Formel CCl₄ aus einem Kohlenstoff- und vier Chloratomen. Die Chloratome machen den größten Teil der Molmasse aus.",
    usesDe: ["Historische industrielle Lösungsmittelanwendungen", "Referenz- und Forschungsarbeiten", "Kontrollierte chemische Analyse"],
    safetyDe: "Der Stoff kann giftig und umweltschädlich sein; viele Anwendungen sind eingeschränkt. Er ist nicht für Verbraucher geeignet.",
  },
  {
    id: "oktan",
    contextTr: "Oktan C₈H₁₈ formüllü bir alkandır. Aynı formüle sahip farklı yapısal izomerler bulunabildiği için teknik yakıt verilerinde hangi oktan izomerinin kastedildiği önemlidir.",
    usesTr: ["Yakıt ve hidrokarbon araştırmaları", "Kimyasal model bileşik", "Laboratuvar ve proses analizleri"],
    safetyTr: "Yanıcı sıvıdır; buharı havayla yanıcı karışım oluşturabilir. Yakıt ürünleri teknik spesifikasyon ve güvenlik kurallarına göre ele alınmalıdır.",
    contextDe: "Octan ist ein Alkan mit der Formel C₈H₁₈. Da verschiedene Strukturisomere dieselbe Formel besitzen, ist bei technischen Kraftstoffdaten entscheidend, welches Octan-Isomer gemeint ist.",
    usesDe: ["Kraftstoff- und Kohlenwasserstoffforschung", "Chemische Modellverbindung", "Labor- und Prozessanalytik"],
    safetyDe: "Die Flüssigkeit ist entzündbar und ihre Dämpfe können mit Luft brennbare Gemische bilden. Kraftstoffprodukte müssen nach Spezifikation und Sicherheitsregeln behandelt werden.",
  },
  {
    id: "sikloheksan",
    contextTr: "Sikloheksan C₆H₁₂ formüllü halkalı bir hidrokarbondur. Açık zincirli C₆H₁₂ bileşiklerinden farklı yapıya sahip olsa da aynı toplam atom sayısını taşıyabilir.",
    usesTr: ["Naylon ara ürünlerinin üretimi", "Endüstriyel çözücü", "Kimyasal sentez"],
    safetyTr: "Yanıcıdır ve buharına maruziyet zararlı olabilir; yalnızca iyi havalandırılan profesyonel süreçlerde kullanılmalıdır.",
    contextDe: "Cyclohexan ist ein ringförmiger Kohlenwasserstoff mit der Formel C₆H₁₂. Es kann sich strukturell von offenkettigen C₆H₁₂-Verbindungen unterscheiden, obwohl die Gesamtatomzahl gleich ist.",
    usesDe: ["Herstellung von Nylon-Zwischenprodukten", "Industrielles Lösungsmittel", "Chemische Synthese"],
    safetyDe: "Der Stoff ist entzündbar und Dämpfe können schädlich sein; Einsatz nur in gut belüfteten professionellen Prozessen.",
  },
  {
    id: "vanilin",
    contextTr: "Vanilin C₈H₈O₃ formüllü aromatik bir bileşiktir ve karakteristik vanilya kokusuyla ilişkilidir. Doğal ve sentetik kaynaklı ürünler aynı temel molekülü içerebilir ancak ürün bileşimi değişebilir.",
    usesTr: ["Gıda aromaları", "Koku ve kozmetik formülasyonları", "Kimyasal sentez ve kalite kontrol"],
    safetyTr: "Gıda veya kozmetik uygulamalarında yalnızca ilgili mevzuat ve saflık standardını karşılayan ürünler kullanılmalıdır.",
    contextDe: "Vanillin ist eine aromatische Verbindung mit der Formel C₈H₈O₃ und dem charakteristischen Vanilleduft. Natur- und Syntheseprodukte können dasselbe Grundmolekül enthalten, sich aber in der Produktzusammensetzung unterscheiden.",
    usesDe: ["Lebensmittelaromen", "Duft- und Kosmetikformulierungen", "Chemische Synthese und Qualitätskontrolle"],
    safetyDe: "Für Lebensmittel oder Kosmetik dürfen nur Produkte verwendet werden, die die passende Rechts- und Reinheitsanforderung erfüllen.",
  },
  {
    id: "ozon",
    contextTr: "Ozon O₃ formüllü, üç oksijen atomundan oluşan reaktif bir gazdır. Aynı elementten oluşmasına rağmen O₂ gazından farklı fiziksel ve kimyasal özellik gösterir.",
    usesTr: ["Kontrollü su arıtma", "Koku ve oksidasyon prosesleri", "Atmosfer araştırmaları"],
    safetyTr: "Solunum yollarını tahriş edebilir; ozon üreten cihazlar kapalı alanlarda yalnızca uygun ölçüm ve havalandırma ile kullanılmalıdır.",
    contextDe: "Ozon ist ein reaktives Gas aus drei Sauerstoffatomen mit der Formel O₃. Obwohl es aus demselben Element besteht, hat es andere physikalische und chemische Eigenschaften als O₂.",
    usesDe: ["Kontrollierte Wasseraufbereitung", "Geruchs- und Oxidationsprozesse", "Atmosphärenforschung"],
    safetyDe: "Das Gas kann die Atemwege reizen; ozonerzeugende Geräte dürfen in Innenräumen nur mit geeigneter Messung und Lüftung eingesetzt werden.",
  },
  {
    id: "kripton",
    contextTr: "Kripton Kr formüllü tek atomlu bir soy gazdır. Atomik kütlesi ile bir mol kripton gazının molar kütlesi bu nedenle sayısal olarak aynıdır.",
    usesTr: ["Özel aydınlatma", "Yalıtım camı", "Lazer ve ölçüm teknolojisi"],
    safetyTr: "Yanıcı değildir ancak büyük miktarlarda oksijeni seyreltebilir; basınçlı gaz tüpleri uygun depolama ve havalandırma gerektirir.",
    contextDe: "Krypton ist ein einatomiges Edelgas mit der Formel Kr. Daher sind Atommasse und Molmasse eines Mols Kryptongas zahlenmäßig gleich.",
    usesDe: ["Spezialbeleuchtung", "Isolierglas", "Laser- und Messtechnik"],
    safetyDe: "Das Gas ist nicht brennbar, kann aber in großen Mengen Sauerstoff verdrängen; Druckgasflaschen benötigen passende Lagerung und Lüftung.",
  },
  {
    id: "ksenon",
    contextTr: "Ksenon Xe formüllü ağır, tek atomlu bir soy gazdır. Tek atomlu yapısı nedeniyle atomik kütle ve molar kütle değeri sayısal olarak aynıdır.",
    usesTr: ["Yüksek yoğunluklu lambalar", "Uzay araçlarında iyon itki", "Özel görüntüleme ve araştırma"],
    safetyTr: "Yanıcı değildir ancak basınçlı gaz olarak ve kapalı alanlarda oksijen azaltma riski bakımından uygun prosedürlerle ele alınmalıdır.",
    contextDe: "Xenon ist ein schweres, einatomiges Edelgas mit der Formel Xe. Wegen der einatomigen Struktur sind Atommasse und Molmasse zahlenmäßig gleich.",
    usesDe: ["Hochintensive Lampen", "Ionenantriebe in Raumfahrzeugen", "Spezielle Bildgebung und Forschung"],
    safetyDe: "Das Gas ist nicht brennbar, muss aber als Druckgas und wegen möglicher Sauerstoffverdrängung in geschlossenen Räumen nach geeigneten Verfahren gehandhabt werden.",
  },
];

export function findCompoundEditorial(id: string) {
  return compoundEditorial.find((article) => article.id === id);
}
