import type { CompoundCategory } from "./compoundsDatabase";

export const compoundCategoryLabelsDe: Record<CompoundCategory, string> = {
  asit: "Säuren",
  baz: "Basen",
  tuz: "Salze",
  oksit: "Oxide",
  organik: "Organische Verbindungen",
  gaz: "Elementare Gase",
};

export const compoundNamesDe: Record<string, string> = {
  su: "Wasser",
  "sofra-tuzu": "Kochsalz (Natriumchlorid)",
  karbondioksit: "Kohlendioxid",
  "oksijen-gazi": "Sauerstoffgas",
  "sodyum-hidroksit": "Natriumhydroxid",
  "hidroklorik-asit": "Salzsäure",
  glikoz: "Glukose",
  amonyak: "Ammoniak",
  "sulfurik-asit": "Schwefelsäure",
  "kalsiyum-karbonat": "Calciumcarbonat",
  etanol: "Ethanol",
  "hidrojen-peroksit": "Wasserstoffperoxid",
  metan: "Methan",
  "potasyum-nitrat": "Kaliumnitrat",
  "aluminyum-oksit": "Aluminiumoxid",
  "kalsiyum-hidroksit": "Calciumhydroxid",
  "nitrik-asit": "Salpetersäure",
  "fosforik-asit": "Phosphorsäure",
  "asetik-asit": "Essigsäure",
  "potasyum-hidroksit": "Kaliumhydroxid",
  "kalsiyum-klorur": "Calciumchlorid",
  "sodyum-bikarbonat": "Natriumbicarbonat (Natron)",
  "sodyum-karbonat": "Natriumcarbonat",
  "gumus-nitrat": "Silbernitrat",
  "bakir-sulfat": "Kupfer(II)-sulfat",
  "potasyum-klorur": "Kaliumchlorid",
  "kalsiyum-sulfat": "Calciumsulfat (Gips)",
  "kukurt-dioksit": "Schwefeldioxid",
  "azot-dioksit": "Stickstoffdioxid",
  "demir-oksit": "Eisen(III)-oxid (Rost)",
  "magnezyum-oksit": "Magnesiumoxid",
  "silisyum-dioksit": "Siliciumdioxid (Quarz)",
  "kalsiyum-oksit": "Calciumoxid (Branntkalk)",
  sukroz: "Saccharose (Haushaltszucker)",
  etilen: "Ethylen",
  benzen: "Benzol",
  metanol: "Methanol",
  "azot-gazi": "Stickstoffgas",
  "hidrojen-gazi": "Wasserstoffgas",
  "klor-gazi": "Chlorgas",
  "karbonik-asit": "Kohlensäure",
  "hidroflorik-asit": "Flusssäure",
  "hidrojen-sulfur": "Schwefelwasserstoff",
  "baryum-hidroksit": "Bariumhydroxid",
  "aluminyum-hidroksit": "Aluminiumhydroxid",
  "magnezyum-klorur": "Magnesiumchlorid",
  "demir-klorur": "Eisen(III)-chlorid",
  "sodyum-sulfat": "Natriumsulfat",
  "amonyum-nitrat": "Ammoniumnitrat",
  "potasyum-permanganat": "Kaliumpermanganat",
  "sodyum-hipoklorit": "Natriumhypochlorit (Bleichmittel)",
  "kalsiyum-florur": "Calciumfluorid (Flussspat)",
  "gumus-klorur": "Silberchlorid",
  "baryum-sulfat": "Bariumsulfat",
  "sodyum-fosfat": "Natriumphosphat",
  "diazot-monoksit": "Distickstoffmonoxid (Lachgas)",
  "azot-monoksit": "Stickstoffmonoxid",
  "bakir-oksit": "Kupfer(II)-oxid",
  "mangan-dioksit": "Mangandioxid",
  "titanyum-dioksit": "Titandioxid",
  "difosfor-pentoksit": "Diphosphorpentoxid",
  aseton: "Aceton",
  formaldehit: "Formaldehyd",
  asetilen: "Acetylen",
  ure: "Harnstoff",
  fenol: "Phenol",
  kloroform: "Chloroform",
  gliserin: "Glycerin",
  aspirin: "Aspirin (Acetylsalicylsäure)",
  parasetamol: "Paracetamol",
  "flor-gazi": "Fluorgas",
  "argon-gazi": "Argon",
  "sitrik-asit": "Zitronensäure",
  "laktik-asit": "Milchsäure",
  "hidrobromik-asit": "Bromwasserstoffsäure",
  "lityum-hidroksit": "Lithiumhydroxid",
  "magnezyum-sulfat": "Magnesiumsulfat (Bittersalz)",
  "sodyum-florur": "Natriumfluorid",
  "potasyum-iyodur": "Kaliumiodid",
  "sodyum-tiyosulfat": "Natriumthiosulfat",
  "potasyum-dikromat": "Kaliumdichromat",
  "demir-ii-klorur": "Eisen(II)-chlorid",
  "cinko-klorur": "Zinkchlorid",
  "cinko-sulfat": "Zinksulfat",
  "potasyum-sulfat": "Kaliumsulfat",
  "magnezyum-karbonat": "Magnesiumcarbonat",
  "baryum-karbonat": "Bariumcarbonat",
  "bakir-ii-klorur": "Kupfer(II)-chlorid",
  "kursun-ii-nitrat": "Blei(II)-nitrat",
  "sodyum-sulfur": "Natriumsulfid",
  "kalsiyum-karbur": "Calciumcarbid",
  "sodyum-bromur": "Natriumbromid",
  "sodyum-oksit": "Natriumoxid",
  "potasyum-oksit": "Kaliumoxid",
  "baryum-oksit": "Bariumoxid",
  "krom-oksit": "Chrom(III)-oxid",
  "kursun-ii-oksit": "Blei(II)-oxid",
  kafein: "Koffein",
  toluen: "Toluol",
  "karbon-tetraklorur": "Tetrachlorkohlenstoff",
  oktan: "Oktan",
  sikloheksan: "Cyclohexan",
  vanilin: "Vanillin",
  ozon: "Ozon",
  kripton: "Krypton",
  ksenon: "Xenon",
};

// Elementnamen werden zentral in periodicTableDataDe.ts gepflegt
// (vollständige 118-Elemente-Lokalisierung); hier nur re-exportiert
// für Rückwärtskompatibilität mit bestehenden Imports.
export { elementNamesDeBySymbol as elementNamesDe } from "./periodicTableDataDe";
