// Esmâ-i Hüsnâ: Tirmizî'nin (Daavât 82) rivayetindeki sırayla 99 isim.
// Türkçe yazım ve kısa anlamlar Diyanet kaynaklarındaki yaygın açıklamalara
// göre sadeleştirilmiştir.

export type Esma = { no: number; ad: string; anlam: string };

const LISTE: Array<[string, string]> = [
  ["Allah", "Eşi ve benzeri olmayan, bütün güzel isimleri kendinde toplayan tek ilah"],
  ["Er-Rahmân", "Dünyada bütün yaratılmışlara merhamet eden"],
  ["Er-Rahîm", "Ahirette müminlere merhamet eden"],
  ["El-Melik", "Bütün varlıkların gerçek sahibi ve hükümdarı"],
  ["El-Kuddûs", "Her türlü eksiklikten uzak, tertemiz"],
  ["Es-Selâm", "Kullarını tehlikelerden kurtaran, esenlik veren"],
  ["El-Mü'min", "Güven veren, vaadine sadık olan"],
  ["El-Müheymin", "Her şeyi gözetip koruyan"],
  ["El-Azîz", "İzzet sahibi, her şeye galip gelen"],
  ["El-Cebbâr", "Dilediğini yaptırmaya gücü yeten"],
  ["El-Mütekebbir", "Büyüklükte eşi olmayan"],
  ["El-Hâlık", "Yaratan, yoktan var eden"],
  ["El-Bâri", "Her şeyi kusursuz ve uyumlu yaratan"],
  ["El-Musavvir", "Varlıklara şekil ve suret veren"],
  ["El-Gaffâr", "Günahları çokça örten ve bağışlayan"],
  ["El-Kahhâr", "Her şeye üstün gelen, karşı konulamayan"],
  ["El-Vehhâb", "Karşılıksız bol bol veren"],
  ["Er-Rezzâk", "Bütün canlıların rızkını veren"],
  ["El-Fettâh", "Her türlü darlığı açan, hayır kapılarını açan"],
  ["El-Alîm", "Her şeyi en ince ayrıntısıyla bilen"],
  ["El-Kâbıd", "Dilediğine darlık veren"],
  ["El-Bâsıt", "Dilediğine bolluk veren"],
  ["El-Hâfıd", "Dilediğini alçaltan"],
  ["Er-Râfi", "Dilediğini yükselten"],
  ["El-Muizz", "Dilediğine izzet ve şeref veren"],
  ["El-Müzil", "Dilediğini zillete düşüren"],
  ["Es-Semî", "Her şeyi işiten"],
  ["El-Basîr", "Her şeyi gören"],
  ["El-Hakem", "Mutlak hakim, hak ile batılı ayıran"],
  ["El-Adl", "Mutlak adalet sahibi"],
  ["El-Latîf", "Lütfu bol, en ince işleri bilen"],
  ["El-Habîr", "Her şeyin iç yüzünden haberdar olan"],
  ["El-Halîm", "Cezalandırmada acele etmeyen, yumuşak davranan"],
  ["El-Azîm", "Pek büyük ve yüce"],
  ["El-Gafûr", "Bağışlaması çok olan"],
  ["Eş-Şekûr", "Az amele çok sevap veren"],
  ["El-Aliyy", "Yüceler yücesi"],
  ["El-Kebîr", "Büyüklüğü sınırsız olan"],
  ["El-Hafîz", "Her şeyi koruyup gözeten"],
  ["El-Mukît", "Bütün yaratılmışların gıdasını veren"],
  ["El-Hasîb", "Kullarını hesaba çeken"],
  ["El-Celîl", "Celâl ve azamet sahibi"],
  ["El-Kerîm", "Keremi, ikramı bol olan"],
  ["Er-Rakîb", "Her an gözetleyen"],
  ["El-Mucîb", "Duaları kabul eden"],
  ["El-Vâsi", "Rahmeti ve ilmi her şeyi kuşatan"],
  ["El-Hakîm", "Her işi hikmetli olan"],
  ["El-Vedûd", "Kullarını seven ve sevilmeye layık olan"],
  ["El-Mecîd", "Şanı yüce, şerefi büyük olan"],
  ["El-Bâis", "Ölüleri dirilten"],
  ["Eş-Şehîd", "Her zaman her yerde hazır ve nazır olan"],
  ["El-Hak", "Varlığı hiç değişmeden duran, gerçek olan"],
  ["El-Vekîl", "Kendisine güvenilip dayanılan"],
  ["El-Kaviyy", "Kuvveti sınırsız olan"],
  ["El-Metîn", "Çok sağlam, kudreti sarsılmaz"],
  ["El-Veliyy", "İnananların dostu ve yardımcısı"],
  ["El-Hamîd", "Övülmeye layık olan"],
  ["El-Muhsî", "Her şeyin sayısını bilen"],
  ["El-Mübdi", "Maddesiz ve örneksiz ilk defa yaratan"],
  ["El-Muîd", "Yok ettiğini yeniden yaratan"],
  ["El-Muhyî", "Can veren, dirilten"],
  ["El-Mümît", "Ölümü yaratan"],
  ["El-Hayy", "Ezelî ve ebedî diri olan"],
  ["El-Kayyûm", "Her şeyi ayakta tutan, varlığı kendinden olan"],
  ["El-Vâcid", "İstediğini istediği anda bulan"],
  ["El-Mâcid", "Kadri ve şanı büyük, keremi bol olan"],
  ["El-Vâhid", "Zatında, sıfatlarında ve işlerinde tek olan"],
  ["Es-Samed", "Hiçbir şeye muhtaç olmayan, herkesin muhtaç olduğu"],
  ["El-Kâdir", "Dilediğini dilediği gibi yapmaya gücü yeten"],
  ["El-Muktedir", "Kudret sahiplerinin üstünde kudret sahibi"],
  ["El-Mukaddim", "Dilediğini öne alan"],
  ["El-Muahhir", "Dilediğini geriye bırakan"],
  ["El-Evvel", "Başlangıcı olmayan, ilk"],
  ["El-Âhir", "Sonu olmayan, son"],
  ["Ez-Zâhir", "Varlığı delilleriyle apaçık olan"],
  ["El-Bâtın", "Zatının mahiyeti akıllarca kavranamayan"],
  ["El-Vâlî", "Bütün kâinatı yöneten"],
  ["El-Müteâlî", "Yaratılmışlara benzemekten uzak, pek yüce"],
  ["El-Berr", "İyiliği bol olan"],
  ["Et-Tevvâb", "Tövbeleri kabul eden"],
  ["El-Müntakim", "Suçluları adaletle cezalandıran"],
  ["El-Afüvv", "Affı çok olan"],
  ["Er-Raûf", "Çok şefkatli"],
  ["Mâlikü'l-Mülk", "Mülkün ebedî sahibi"],
  ["Zü'l-Celâli ve'l-İkrâm", "Celâl ve ikram sahibi"],
  ["El-Muksit", "Bütün işlerini denk ve adaletle yapan"],
  ["El-Câmi", "İstediğini istediği yerde toplayan"],
  ["El-Ganiyy", "Hiçbir şeye muhtaç olmayan, zengin"],
  ["El-Muğnî", "Dilediğini zengin eden"],
  ["El-Mâni", "Dilemediği şeye engel olan"],
  ["Ed-Dârr", "Elem ve zarar verecek şeyleri de yaratan"],
  ["En-Nâfi", "Fayda verecek şeyleri yaratan"],
  ["En-Nûr", "Âlemleri nurlandıran"],
  ["El-Hâdî", "Hidayet veren, doğru yolu gösteren"],
  ["El-Bedî", "Eşi benzeri olmayan güzellikte yaratan"],
  ["El-Bâkî", "Varlığının sonu olmayan"],
  ["El-Vâris", "Her şeyin asıl sahibi; her şey yok olduktan sonra kalan"],
  ["Er-Reşîd", "Doğru yolu gösteren, her işi isabetli olan"],
  ["Es-Sabûr", "Çok sabırlı, cezalandırmada acele etmeyen"],
];

export const ESMAUL_HUSNA: Esma[] = LISTE.map(([ad, anlam], i) => ({ no: i + 1, ad, anlam }));
