import type {
  KitchenIngredientKey,
  KitchenUnit,
} from "./kitchenMeasures";

export type KitchenLocale = "tr" | "en" | "de" | "ar";

export const kitchenIngredientLabels: Record<
  KitchenLocale,
  Record<KitchenIngredientKey, string>
> = {
  tr: {
    un: "Un (Bugday Unu)",
    "tam-bugday-unu": "Tam Bugday Unu",
    "pirinc-unu": "Pirinc Unu",
    "misir-unu": "Misir Unu",
    irmik: "Irmik",
    "galeta-unu": "Galeta Unu",
    "toz-seker": "Toz Seker",
    "pudra-sekeri": "Pudra Sekeri",
    "esmer-seker": "Esmer Seker",
    tuz: "Tuz (Sofra Tuzu)",
    pirinc: "Pirinc",
    bulgur: "Bulgur (Ince)",
    nohut: "Nohut (Kuru)",
    "kirmizi-mercimek": "Kirmizi Mercimek",
    "yesil-mercimek": "Yesil Mercimek",
    "kuru-fasulye": "Kuru Fasulye",
    sut: "Sut",
    yogurt: "Yogurt",
    krema: "Krema",
    tereyagi: "Tereyagi",
    margarin: "Margarin",
    zeytinyagi: "Zeytinyagi",
    "sivi-yag": "Sivi Yag (Bitkisel)",
    bal: "Bal",
    pekmez: "Pekmez",
    kakao: "Kakao (Toz)",
    "yulaf-ezmesi": "Yulaf Ezmesi",
    nisasta: "Nisasta (Misir)",
    "kabartma-tozu": "Kabartma Tozu",
    karbonat: "Karbonat",
    susam: "Susam",
    "ceviz-ici": "Ceviz Ici (Kirik)",
    "findik-ici": "Findik Ici",
    badem: "Badem",
    "antep-fistigi": "Antep Fistigi",
    "kuru-uzum": "Kuru Uzum",
    "hindistan-cevizi": "Hindistan Cevizi (Rende)",
    mayonez: "Mayonez",
    ketcap: "Ketcap",
    sirke: "Sirke",
    "limon-suyu": "Limon Suyu",
    tarcin: "Tarcin (Toz)",
    "kirmizi-biber": "Kirmizi Biber (Toz)",
    karabiber: "Karabiber (Toz)",
    kimyon: "Kimyon (Toz)",
  },
  en: {
    un: "Flour (Wheat)",
    "tam-bugday-unu": "Whole Wheat Flour",
    "pirinc-unu": "Rice Flour",
    "misir-unu": "Corn Flour",
    irmik: "Semolina",
    "galeta-unu": "Breadcrumbs",
    "toz-seker": "Granulated Sugar",
    "pudra-sekeri": "Powdered Sugar",
    "esmer-seker": "Brown Sugar",
    tuz: "Salt (Table Salt)",
    pirinc: "Rice",
    bulgur: "Bulgur (Fine)",
    nohut: "Chickpeas (Dry)",
    "kirmizi-mercimek": "Red Lentils",
    "yesil-mercimek": "Green Lentils",
    "kuru-fasulye": "Dry Beans",
    sut: "Milk",
    yogurt: "Yogurt",
    krema: "Heavy Cream",
    tereyagi: "Butter",
    margarin: "Margarine",
    zeytinyagi: "Olive Oil",
    "sivi-yag": "Vegetable Oil",
    bal: "Honey",
    pekmez: "Grape Molasses",
    kakao: "Cocoa Powder",
    "yulaf-ezmesi": "Rolled Oats",
    nisasta: "Cornstarch",
    "kabartma-tozu": "Baking Powder",
    karbonat: "Baking Soda",
    susam: "Sesame Seeds",
    "ceviz-ici": "Walnuts (Chopped)",
    "findik-ici": "Hazelnuts",
    badem: "Almonds",
    "antep-fistigi": "Pistachios",
    "kuru-uzum": "Raisins",
    "hindistan-cevizi": "Desiccated Coconut",
    mayonez: "Mayonnaise",
    ketcap: "Ketchup",
    sirke: "Vinegar",
    "limon-suyu": "Lemon Juice",
    tarcin: "Ground Cinnamon",
    "kirmizi-biber": "Ground Red Pepper",
    karabiber: "Ground Black Pepper",
    kimyon: "Ground Cumin",
  },
  de: {
    un: "Weizenmehl",
    "tam-bugday-unu": "Vollkornmehl",
    "pirinc-unu": "Reismehl",
    "misir-unu": "Maismehl",
    irmik: "Griess",
    "galeta-unu": "Paniermehl",
    "toz-seker": "Kristallzucker",
    "pudra-sekeri": "Puderzucker",
    "esmer-seker": "Brauner Zucker",
    tuz: "Salz",
    pirinc: "Reis",
    bulgur: "Bulgur",
    nohut: "Kichererbsen",
    "kirmizi-mercimek": "Rote Linsen",
    "yesil-mercimek": "Gruene Linsen",
    "kuru-fasulye": "Getrocknete Bohnen",
    sut: "Milch",
    yogurt: "Joghurt",
    krema: "Sahne",
    tereyagi: "Butter",
    margarin: "Margarine",
    zeytinyagi: "Olivenoel",
    "sivi-yag": "Pflanzenoel",
    bal: "Honig",
    pekmez: "Traubenmelasse",
    kakao: "Kakaopulver",
    "yulaf-ezmesi": "Haferflocken",
    nisasta: "Maisstaerke",
    "kabartma-tozu": "Backpulver",
    karbonat: "Natron",
    susam: "Sesam",
    "ceviz-ici": "Walnuesse",
    "findik-ici": "Haselnuesse",
    badem: "Mandeln",
    "antep-fistigi": "Pistazien",
    "kuru-uzum": "Rosinen",
    "hindistan-cevizi": "Kokosraspeln",
    mayonez: "Mayonnaise",
    ketcap: "Ketchup",
    sirke: "Essig",
    "limon-suyu": "Zitronensaft",
    tarcin: "Zimt",
    "kirmizi-biber": "Paprikapulver",
    karabiber: "Schwarzer Pfeffer",
    kimyon: "Kreuzkuemmel",
  },
  ar: {
    un: "دقيق القمح",
    "tam-bugday-unu": "دقيق القمح الكامل",
    "pirinc-unu": "دقيق الأرز",
    "misir-unu": "دقيق الذرة",
    irmik: "سميد",
    "galeta-unu": "بقسماط",
    "toz-seker": "سكر أبيض",
    "pudra-sekeri": "سكر بودرة",
    "esmer-seker": "سكر بني",
    tuz: "ملح",
    pirinc: "أرز",
    bulgur: "برغل ناعم",
    nohut: "حمص جاف",
    "kirmizi-mercimek": "عدس أحمر",
    "yesil-mercimek": "عدس أخضر",
    "kuru-fasulye": "فاصولياء جافة",
    sut: "حليب",
    yogurt: "زبادي",
    krema: "كريمة",
    tereyagi: "زبدة",
    margarin: "مارغرين",
    zeytinyagi: "زيت زيتون",
    "sivi-yag": "زيت نباتي",
    bal: "عسل",
    pekmez: "دبس",
    kakao: "كاكاو بودرة",
    "yulaf-ezmesi": "شوفان",
    nisasta: "نشا الذرة",
    "kabartma-tozu": "بيكنج باودر",
    karbonat: "بيكربونات الصوديوم",
    susam: "سمسم",
    "ceviz-ici": "جوز مفروم",
    "findik-ici": "بندق",
    badem: "لوز",
    "antep-fistigi": "فستق",
    "kuru-uzum": "زبيب",
    "hindistan-cevizi": "جوز هند مبشور",
    mayonez: "مايونيز",
    ketcap: "كاتشب",
    sirke: "خل",
    "limon-suyu": "عصير ليمون",
    tarcin: "قرفة مطحونة",
    "kirmizi-biber": "فلفل أحمر مطحون",
    karabiber: "فلفل أسود مطحون",
    kimyon: "كمون مطحون",
  },
};

export const kitchenUnitLabels: Record<
  KitchenLocale,
  Record<KitchenUnit, string>
> = {
  tr: {
    bardak: "Su Bardagi",
    yemekKasigi: "Yemek Kasigi",
    cayKasigi: "Cay Kasigi",
    ml: "Mililitre (ml)",
    litre: "Litre",
    gram: "Gram",
  },
  en: {
    bardak: "Cup",
    yemekKasigi: "Tablespoon",
    cayKasigi: "Teaspoon",
    ml: "Milliliter (ml)",
    litre: "Liter",
    gram: "Gram",
  },
  de: {
    bardak: "Tasse",
    yemekKasigi: "Essloeffel",
    cayKasigi: "Teeloeffel",
    ml: "Milliliter (ml)",
    litre: "Liter",
    gram: "Gramm",
  },
  ar: {
    bardak: "كوب",
    yemekKasigi: "ملعقة كبيرة",
    cayKasigi: "ملعقة صغيرة",
    ml: "ملليلتر",
    litre: "لتر",
    gram: "غرام",
  },
};
