import type {
  KitchenIngredientKey,
  KitchenUnit,
} from "./kitchenMeasures";

export type KitchenLocale = "tr" | "en" | "de" | "ar" | "uz" | "bn" | "fr" | "es" | "es-419" | "pt";

export const kitchenIngredientLabels: Record<
  KitchenLocale,
  Record<KitchenIngredientKey, string>
> = {
  tr: {
    un: "Un (Bugday Unu)",
    "tam-bugday-unu": "Tam Bugday Unu",
    "pirinc-unu": "Pirinc Unu",
    "misir-unu": "Misir Unu",
    irmik: "Irmik",
    "galeta-unu": "Galeta Unu",
    "toz-seker": "Toz Seker",
    "pudra-sekeri": "Pudra Sekeri",
    "esmer-seker": "Esmer Seker",
    tuz: "Tuz (Sofra Tuzu)",
    pirinc: "Pirinc",
    bulgur: "Bulgur (Ince)",
    nohut: "Nohut (Kuru)",
    "kirmizi-mercimek": "Kirmizi Mercimek",
    "yesil-mercimek": "Yesil Mercimek",
    "kuru-fasulye": "Kuru Fasulye",
    sut: "Sut",
    yogurt: "Yogurt",
    krema: "Krema",
    tereyagi: "Tereyagi",
    margarin: "Margarin",
    zeytinyagi: "Zeytinyagi",
    "sivi-yag": "Sivi Yag (Bitkisel)",
    bal: "Bal",
    pekmez: "Pekmez",
    kakao: "Kakao (Toz)",
    "yulaf-ezmesi": "Yulaf Ezmesi",
    nisasta: "Nisasta (Misir)",
    "kabartma-tozu": "Kabartma Tozu",
    karbonat: "Karbonat",
    susam: "Susam",
    "ceviz-ici": "Ceviz Ici (Kirik)",
    "findik-ici": "Findik Ici",
    badem: "Badem",
    "antep-fistigi": "Antep Fistigi",
    "kuru-uzum": "Kuru Uzum",
    "hindistan-cevizi": "Hindistan Cevizi (Rende)",
    mayonez: "Mayonez",
    ketcap: "Ketcap",
    sirke: "Sirke",
    "limon-suyu": "Limon Suyu",
    tarcin: "Tarcin (Toz)",
    "kirmizi-biber": "Kirmizi Biber (Toz)",
    karabiber: "Karabiber (Toz)",
    kimyon: "Kimyon (Toz)",
  },
  en: {
    un: "Flour (Wheat)",
    "tam-bugday-unu": "Whole Wheat Flour",
    "pirinc-unu": "Rice Flour",
    "misir-unu": "Corn Flour",
    irmik: "Semolina",
    "galeta-unu": "Breadcrumbs",
    "toz-seker": "Granulated Sugar",
    "pudra-sekeri": "Powdered Sugar",
    "esmer-seker": "Brown Sugar",
    tuz: "Salt (Table Salt)",
    pirinc: "Rice",
    bulgur: "Bulgur (Fine)",
    nohut: "Chickpeas (Dry)",
    "kirmizi-mercimek": "Red Lentils",
    "yesil-mercimek": "Green Lentils",
    "kuru-fasulye": "Dry Beans",
    sut: "Milk",
    yogurt: "Yogurt",
    krema: "Heavy Cream",
    tereyagi: "Butter",
    margarin: "Margarine",
    zeytinyagi: "Olive Oil",
    "sivi-yag": "Vegetable Oil",
    bal: "Honey",
    pekmez: "Grape Molasses",
    kakao: "Cocoa Powder",
    "yulaf-ezmesi": "Rolled Oats",
    nisasta: "Cornstarch",
    "kabartma-tozu": "Baking Powder",
    karbonat: "Baking Soda",
    susam: "Sesame Seeds",
    "ceviz-ici": "Walnuts (Chopped)",
    "findik-ici": "Hazelnuts",
    badem: "Almonds",
    "antep-fistigi": "Pistachios",
    "kuru-uzum": "Raisins",
    "hindistan-cevizi": "Desiccated Coconut",
    mayonez: "Mayonnaise",
    ketcap: "Ketchup",
    sirke: "Vinegar",
    "limon-suyu": "Lemon Juice",
    tarcin: "Ground Cinnamon",
    "kirmizi-biber": "Ground Red Pepper",
    karabiber: "Ground Black Pepper",
    kimyon: "Ground Cumin",
  },
  de: {
    un: "Weizenmehl",
    "tam-bugday-unu": "Vollkornmehl",
    "pirinc-unu": "Reismehl",
    "misir-unu": "Maismehl",
    irmik: "Griess",
    "galeta-unu": "Paniermehl",
    "toz-seker": "Kristallzucker",
    "pudra-sekeri": "Puderzucker",
    "esmer-seker": "Brauner Zucker",
    tuz: "Salz",
    pirinc: "Reis",
    bulgur: "Bulgur",
    nohut: "Kichererbsen",
    "kirmizi-mercimek": "Rote Linsen",
    "yesil-mercimek": "Gruene Linsen",
    "kuru-fasulye": "Getrocknete Bohnen",
    sut: "Milch",
    yogurt: "Joghurt",
    krema: "Sahne",
    tereyagi: "Butter",
    margarin: "Margarine",
    zeytinyagi: "Olivenoel",
    "sivi-yag": "Pflanzenoel",
    bal: "Honig",
    pekmez: "Traubenmelasse",
    kakao: "Kakaopulver",
    "yulaf-ezmesi": "Haferflocken",
    nisasta: "Maisstaerke",
    "kabartma-tozu": "Backpulver",
    karbonat: "Natron",
    susam: "Sesam",
    "ceviz-ici": "Walnuesse",
    "findik-ici": "Haselnuesse",
    badem: "Mandeln",
    "antep-fistigi": "Pistazien",
    "kuru-uzum": "Rosinen",
    "hindistan-cevizi": "Kokosraspeln",
    mayonez: "Mayonnaise",
    ketcap: "Ketchup",
    sirke: "Essig",
    "limon-suyu": "Zitronensaft",
    tarcin: "Zimt",
    "kirmizi-biber": "Paprikapulver",
    karabiber: "Schwarzer Pfeffer",
    kimyon: "Kreuzkuemmel",
  },
  ar: {
    un: "دقيق القمح",
    "tam-bugday-unu": "دقيق القمح الكامل",
    "pirinc-unu": "دقيق الأرز",
    "misir-unu": "دقيق الذرة",
    irmik: "سميد",
    "galeta-unu": "بقسماط",
    "toz-seker": "سكر أبيض",
    "pudra-sekeri": "سكر بودرة",
    "esmer-seker": "سكر بني",
    tuz: "ملح",
    pirinc: "أرز",
    bulgur: "برغل ناعم",
    nohut: "حمص جاف",
    "kirmizi-mercimek": "عدس أحمر",
    "yesil-mercimek": "عدس أخضر",
    "kuru-fasulye": "فاصولياء جافة",
    sut: "حليب",
    yogurt: "زبادي",
    krema: "كريمة",
    tereyagi: "زبدة",
    margarin: "مارغرين",
    zeytinyagi: "زيت زيتون",
    "sivi-yag": "زيت نباتي",
    bal: "عسل",
    pekmez: "دبس",
    kakao: "كاكاو بودرة",
    "yulaf-ezmesi": "شوفان",
    nisasta: "نشا الذرة",
    "kabartma-tozu": "بيكنج باودر",
    karbonat: "بيكربونات الصوديوم",
    susam: "سمسم",
    "ceviz-ici": "جوز مفروم",
    "findik-ici": "بندق",
    badem: "لوز",
    "antep-fistigi": "فستق",
    "kuru-uzum": "زبيب",
    "hindistan-cevizi": "جوز هند مبشور",
    mayonez: "مايونيز",
    ketcap: "كاتشب",
    sirke: "خل",
    "limon-suyu": "عصير ليمون",
    tarcin: "قرفة مطحونة",
    "kirmizi-biber": "فلفل أحمر مطحون",
    karabiber: "فلفل أسود مطحون",
    kimyon: "كمون مطحون",
  },
  uz: {
    un: "Un (Bug'doy Uni)",
    "tam-bugday-unu": "To'liq Bug'doy Uni",
    "pirinc-unu": "Guruch Uni",
    "misir-unu": "Makkajo'xori Uni",
    irmik: "Manka Yormasi (Irmik)",
    "galeta-unu": "Suxari (Non Uvog'i)",
    "toz-seker": "Shakar (Kristall)",
    "pudra-sekeri": "Pudra Shakar",
    "esmer-seker": "Jigarrang Shakar",
    tuz: "Tuz (Osh Tuzi)",
    pirinc: "Guruch",
    bulgur: "Bulg'ur (Mayda)",
    nohut: "No'xat (Quruq)",
    "kirmizi-mercimek": "Qizil Yasmiq",
    "yesil-mercimek": "Yashil Yasmiq",
    "kuru-fasulye": "Quruq Loviya",
    sut: "Sut",
    yogurt: "Yogurt (Qatiq)",
    krema: "Krem (Slivki)",
    tereyagi: "Sariyog'",
    margarin: "Margarin",
    zeytinyagi: "Zaytun Yog'i",
    "sivi-yag": "Suyuq Yog' (O'simlik Yog'i)",
    bal: "Asal",
    pekmez: "Pekmez (Uzum Shinnisi)",
    kakao: "Kakao (Kukun)",
    "yulaf-ezmesi": "Suli Yormasi (Yulaf)",
    nisasta: "Kraxmal (Makkajo'xori)",
    "kabartma-tozu": "Pishirish Kukuni (Razrixlitel)",
    karbonat: "Soda (Ichimlik Sodasi)",
    susam: "Kunjut",
    "ceviz-ici": "Yong'oq Mag'zi (Maydalangan)",
    "findik-ici": "Funduq Mag'zi",
    badem: "Bodom",
    "antep-fistigi": "Pista",
    "kuru-uzum": "Mayiz (Kishmish)",
    "hindistan-cevizi": "Kokos Kuki (Rendalangan)",
    mayonez: "Mayonez",
    ketcap: "Ketchup",
    sirke: "Sirka",
    "limon-suyu": "Limon Sharbati",
    tarcin: "Dolchin (Kukun)",
    "kirmizi-biber": "Qizil Qalampir (Kukun)",
    karabiber: "Qora Qalampir (Kukun)",
    kimyon: "Zira (Kukun)",
  },
  bn: {
    un: "ময়দা (গমের)",
    "tam-bugday-unu": "লাল আটা (গোটা গম)",
    "pirinc-unu": "চালের গুঁড়া",
    "misir-unu": "ভুট্টার আটা",
    irmik: "সুজি",
    "galeta-unu": "ব্রেডক্রাম্ব",
    "toz-seker": "চিনি (দানাদার)",
    "pudra-sekeri": "গুঁড়া চিনি",
    "esmer-seker": "বাদামি চিনি",
    tuz: "লবণ (টেবিল লবণ)",
    pirinc: "চাল",
    bulgur: "বুলগুর (মিহি)",
    nohut: "ছোলা (শুকনো)",
    "kirmizi-mercimek": "মসুর ডাল (লাল)",
    "yesil-mercimek": "মসুর ডাল (সবুজ)",
    "kuru-fasulye": "শুকনো মটরশুঁটি",
    sut: "দুধ",
    yogurt: "দই",
    krema: "ক্রিম",
    tereyagi: "মাখন",
    margarin: "মার্জারিন",
    zeytinyagi: "জলপাই তেল",
    "sivi-yag": "তরল তেল (উদ্ভিজ্জ)",
    bal: "মধু",
    pekmez: "আঙুরের গুড়",
    kakao: "কোকো (গুঁড়া)",
    "yulaf-ezmesi": "ওটস",
    nisasta: "কর্নস্টার্চ",
    "kabartma-tozu": "বেকিং পাউডার",
    karbonat: "বেকিং সোডা",
    susam: "তিল",
    "ceviz-ici": "আখরোট (কুচি)",
    "findik-ici": "হ্যাজেলনাট",
    badem: "বাদাম",
    "antep-fistigi": "পেস্তা",
    "kuru-uzum": "কিশমিশ",
    "hindistan-cevizi": "নারকেল (কোরানো)",
    mayonez: "মেয়োনিজ",
    ketcap: "কেচাপ",
    sirke: "ভিনেগার",
    "limon-suyu": "লেবুর রস",
    tarcin: "দারুচিনি (গুঁড়া)",
    "kirmizi-biber": "লাল মরিচ (গুঁড়া)",
    karabiber: "কালো মরিচ (গুঁড়া)",
    kimyon: "জিরা (গুঁড়া)",
  },
  fr: {
    un: "Farine (de ble)",
    "tam-bugday-unu": "Farine complete",
    "pirinc-unu": "Farine de riz",
    "misir-unu": "Farine de mais",
    irmik: "Semoule",
    "galeta-unu": "Chapelure",
    "toz-seker": "Sucre en poudre",
    "pudra-sekeri": "Sucre glace",
    "esmer-seker": "Sucre roux",
    tuz: "Sel (sel de table)",
    pirinc: "Riz",
    bulgur: "Boulgour (fin)",
    nohut: "Pois chiches (secs)",
    "kirmizi-mercimek": "Lentilles corail",
    "yesil-mercimek": "Lentilles vertes",
    "kuru-fasulye": "Haricots secs",
    sut: "Lait",
    yogurt: "Yaourt",
    krema: "Creme fraiche",
    tereyagi: "Beurre",
    margarin: "Margarine",
    zeytinyagi: "Huile d'olive",
    "sivi-yag": "Huile vegetale",
    bal: "Miel",
    pekmez: "Melasse de raisin",
    kakao: "Cacao en poudre",
    "yulaf-ezmesi": "Flocons d'avoine",
    nisasta: "Fecule de mais",
    "kabartma-tozu": "Levure chimique",
    karbonat: "Bicarbonate de soude",
    susam: "Graines de sesame",
    "ceviz-ici": "Noix (concassees)",
    "findik-ici": "Noisettes",
    badem: "Amandes",
    "antep-fistigi": "Pistaches",
    "kuru-uzum": "Raisins secs",
    "hindistan-cevizi": "Noix de coco rapee",
    mayonez: "Mayonnaise",
    ketcap: "Ketchup",
    sirke: "Vinaigre",
    "limon-suyu": "Jus de citron",
    tarcin: "Cannelle moulue",
    "kirmizi-biber": "Piment rouge moulu",
    karabiber: "Poivre noir moulu",
    kimyon: "Cumin moulu",
  },
  es: {
    un: "Harina (de trigo)",
    "tam-bugday-unu": "Harina integral",
    "pirinc-unu": "Harina de arroz",
    "misir-unu": "Harina de maiz",
    irmik: "Semola",
    "galeta-unu": "Pan rallado",
    "toz-seker": "Azucar blanco",
    "pudra-sekeri": "Azucar glas",
    "esmer-seker": "Azucar moreno",
    tuz: "Sal (sal de mesa)",
    pirinc: "Arroz",
    bulgur: "Bulgur (fino)",
    nohut: "Garbanzos (secos)",
    "kirmizi-mercimek": "Lentejas rojas",
    "yesil-mercimek": "Lentejas verdes",
    "kuru-fasulye": "Alubias secas",
    sut: "Leche",
    yogurt: "Yogur",
    krema: "Nata",
    tereyagi: "Mantequilla",
    margarin: "Margarina",
    zeytinyagi: "Aceite de oliva",
    "sivi-yag": "Aceite vegetal",
    bal: "Miel",
    pekmez: "Melaza de uva",
    kakao: "Cacao en polvo",
    "yulaf-ezmesi": "Copos de avena",
    nisasta: "Maicena",
    "kabartma-tozu": "Levadura en polvo",
    karbonat: "Bicarbonato de sodio",
    susam: "Semillas de sesamo",
    "ceviz-ici": "Nueces (troceadas)",
    "findik-ici": "Avellanas",
    badem: "Almendras",
    "antep-fistigi": "Pistachos",
    "kuru-uzum": "Pasas",
    "hindistan-cevizi": "Coco rallado",
    mayonez: "Mayonesa",
    ketcap: "Ketchup",
    sirke: "Vinagre",
    "limon-suyu": "Zumo de limon",
    tarcin: "Canela molida",
    "kirmizi-biber": "Pimenton rojo molido",
    karabiber: "Pimienta negra molida",
    kimyon: "Comino molido",
  },
  "es-419": {
    un: "Harina (de trigo)",
    "tam-bugday-unu": "Harina integral",
    "pirinc-unu": "Harina de arroz",
    "misir-unu": "Harina de maiz",
    irmik: "Semola",
    "galeta-unu": "Pan molido",
    "toz-seker": "Azucar blanca",
    "pudra-sekeri": "Azucar glas",
    "esmer-seker": "Azucar morena",
    tuz: "Sal (sal de mesa)",
    pirinc: "Arroz",
    bulgur: "Bulgur (fino)",
    nohut: "Garbanzos (secos)",
    "kirmizi-mercimek": "Lentejas rojas",
    "yesil-mercimek": "Lentejas verdes",
    "kuru-fasulye": "Frijoles secos",
    sut: "Leche",
    yogurt: "Yogur",
    krema: "Crema",
    tereyagi: "Mantequilla",
    margarin: "Margarina",
    zeytinyagi: "Aceite de oliva",
    "sivi-yag": "Aceite vegetal",
    bal: "Miel",
    pekmez: "Melaza de uva",
    kakao: "Cacao en polvo",
    "yulaf-ezmesi": "Copos de avena",
    nisasta: "Maicena",
    "kabartma-tozu": "Polvo para hornear",
    karbonat: "Bicarbonato de sodio",
    susam: "Ajonjoli",
    "ceviz-ici": "Nueces (troceadas)",
    "findik-ici": "Avellanas",
    badem: "Almendras",
    "antep-fistigi": "Pistachos",
    "kuru-uzum": "Pasas",
    "hindistan-cevizi": "Coco rallado",
    mayonez: "Mayonesa",
    ketcap: "Catsup",
    sirke: "Vinagre",
    "limon-suyu": "Jugo de limon",
    tarcin: "Canela molida",
    "kirmizi-biber": "Pimenton rojo molido",
    karabiber: "Pimienta negra molida",
    kimyon: "Comino molido",
  },
  pt: {
    un: "Farinha de Trigo",
    "tam-bugday-unu": "Farinha Integral",
    "pirinc-unu": "Farinha de Arroz",
    "misir-unu": "Farinha de Milho",
    irmik: "Semolina",
    "galeta-unu": "Farinha de Rosca",
    "toz-seker": "Acucar Refinado",
    "pudra-sekeri": "Acucar de Confeiteiro",
    "esmer-seker": "Acucar Mascavo",
    tuz: "Sal (Sal de Cozinha)",
    pirinc: "Arroz",
    bulgur: "Trigo para Quibe (Bulgur)",
    nohut: "Grao-de-Bico (Seco)",
    "kirmizi-mercimek": "Lentilha Vermelha",
    "yesil-mercimek": "Lentilha Verde",
    "kuru-fasulye": "Feijao Seco",
    sut: "Leite",
    yogurt: "Iogurte",
    krema: "Creme de Leite Fresco",
    tereyagi: "Manteiga",
    margarin: "Margarina",
    zeytinyagi: "Azeite de Oliva",
    "sivi-yag": "Oleo Vegetal",
    bal: "Mel",
    pekmez: "Melaco de Uva",
    kakao: "Cacau em Po",
    "yulaf-ezmesi": "Aveia em Flocos",
    nisasta: "Amido de Milho",
    "kabartma-tozu": "Fermento em Po",
    karbonat: "Bicarbonato de Sodio",
    susam: "Gergelim",
    "ceviz-ici": "Noz (Picada)",
    "findik-ici": "Avela",
    badem: "Amendoa",
    "antep-fistigi": "Pistache",
    "kuru-uzum": "Uva Passa",
    "hindistan-cevizi": "Coco Ralado",
    mayonez: "Maionese",
    ketcap: "Ketchup",
    sirke: "Vinagre",
    "limon-suyu": "Suco de Limao",
    tarcin: "Canela em Po",
    "kirmizi-biber": "Pimenta Vermelha em Po",
    karabiber: "Pimenta-do-Reino Preta",
    kimyon: "Cominho em Po",
  },
};

export const kitchenUnitLabels: Record<
  KitchenLocale,
  Record<KitchenUnit, string>
> = {
  tr: {
    bardak: "Su Bardagi",
    yemekKasigi: "Yemek Kasigi",
    cayKasigi: "Cay Kasigi",
    ml: "Mililitre (ml)",
    litre: "Litre",
    gram: "Gram",
  },
  en: {
    bardak: "Cup",
    yemekKasigi: "Tablespoon",
    cayKasigi: "Teaspoon",
    ml: "Milliliter (ml)",
    litre: "Liter",
    gram: "Gram",
  },
  de: {
    bardak: "Tasse",
    yemekKasigi: "Essloeffel",
    cayKasigi: "Teeloeffel",
    ml: "Milliliter (ml)",
    litre: "Liter",
    gram: "Gramm",
  },
  ar: {
    bardak: "كوب",
    yemekKasigi: "ملعقة كبيرة",
    cayKasigi: "ملعقة صغيرة",
    ml: "ملليلتر",
    litre: "لتر",
    gram: "غرام",
  },
  uz: {
    bardak: "Stakan",
    yemekKasigi: "Osh Qoshiq",
    cayKasigi: "Choy Qoshiq",
    ml: "Millilitr (ml)",
    litre: "Litr",
    gram: "Gramm",
  },
  bn: {
    bardak: "গ্লাস (পানির)",
    yemekKasigi: "টেবিল চামচ",
    cayKasigi: "চা চামচ",
    ml: "মিলিলিটার (ml)",
    litre: "লিটার",
    gram: "গ্রাম",
  },
  fr: {
    bardak: "Tasse",
    yemekKasigi: "Cuillere a soupe",
    cayKasigi: "Cuillere a cafe",
    ml: "Millilitre (ml)",
    litre: "Litre",
    gram: "Gramme",
  },
  es: {
    bardak: "Taza",
    yemekKasigi: "Cucharada",
    cayKasigi: "Cucharadita",
    ml: "Mililitro (ml)",
    litre: "Litro",
    gram: "Gramo",
  },
  "es-419": {
    bardak: "Taza",
    yemekKasigi: "Cucharada",
    cayKasigi: "Cucharadita",
    ml: "Mililitro (ml)",
    litre: "Litro",
    gram: "Gramo",
  },
  pt: {
    bardak: "Xicara",
    yemekKasigi: "Colher de Sopa",
    cayKasigi: "Colher de Cha",
    ml: "Mililitro (ml)",
    litre: "Litro",
    gram: "Grama",
  },
};
