// Paginas de unidade em portugues (Brasil) -- integradas ao novo sistema
// i18n. Arquivo independente e novo (nao modifica os arquivos existentes
// de tr/en/de/ar/uz/bn/fr/es).
// Escopo limitado as 13 categorias fundamentais que, junto com as 4
// ferramentas universais (pagina inicial), formam os 17 elementos da
// identidade do site.

export type LocalizedPortugueseUnitPage = {
  locale: "pt";
  sourceSlug: string;
  slug: string;
  category: string;
  categoryName: string;
  unit: string;
  name: string;
  symbol: string;
  shortDescription: string;
  historySummary: string;
  measurementSystem: string;
  siEquivalent: string;
  commonUses: string;
};

export const portugueseUnitPages: LocalizedPortugueseUnitPage[] = [
  // Comprimento
  {
    locale: "pt",
    sourceSlug: "metre",
    slug: "metro",
    category: "uzunluk",
    categoryName: "Comprimento",
    unit: "m",
    name: "Metro",
    symbol: "m",
    shortDescription: "O metro e a unidade basica do SI para o comprimento.",
    historySummary: "Desde 1983, o metro e definido com precisao a partir da distancia percorrida pela luz no vacuo em 1/299.792.458 de segundo.",
    measurementSystem: "Sistema Internacional de Unidades (SI)",
    siEquivalent: "Unidade basica do SI para o comprimento",
    commonUses: "Construcao, esporte, ciencia e medicao de distancias cotidianas",
  },
  {
    locale: "pt",
    sourceSlug: "kilometre",
    slug: "quilometro",
    category: "uzunluk",
    categoryName: "Comprimento",
    unit: "km",
    name: "Quilometro",
    symbol: "km",
    shortDescription: "O quilometro equivale a 1000 metros e e usado para expressar a distancia entre cidades.",
    historySummary: "O quilometro se consolidou como multiplo do metro dentro da estrutura decimal do sistema metrico, tornando-se a unidade padrao de estradas e mapas.",
    measurementSystem: "Sistema Internacional (SI, multiplo)",
    siEquivalent: "1 km = 1000 m",
    commonUses: "Distancias rodoviarias, geografia, cartografia e infraestrutura",
  },
  {
    locale: "pt",
    sourceSlug: "santimetre",
    slug: "centimetro",
    category: "uzunluk",
    categoryName: "Comprimento",
    unit: "cm",
    name: "Centimetro",
    symbol: "cm",
    shortDescription: "O centimetro equivale a centesima parte de um metro e e usado para medicoes precisas cotidianas.",
    historySummary: "Introduzido com o sistema metrico, o centimetro se tornou a unidade pratica para medir objetos de tamanho pequeno e medio.",
    measurementSystem: "Sistema Internacional (SI, submultiplo)",
    siEquivalent: "1 cm = 0,01 m",
    commonUses: "Costura, medidas corporais, objetos cotidianos",
  },
  {
    locale: "pt",
    sourceSlug: "milimetre",
    slug: "milimetro",
    category: "uzunluk",
    categoryName: "Comprimento",
    unit: "mm",
    name: "Milimetro",
    symbol: "mm",
    shortDescription: "O milimetro equivale a milesima parte de um metro, usado para medicoes de alta precisao.",
    historySummary: "O milimetro e um submultiplo do sistema metrico adotado para engenharia e fabricacao de precisao.",
    measurementSystem: "Sistema Internacional (SI, submultiplo)",
    siEquivalent: "1 mm = 0,001 m",
    commonUses: "Engenharia mecanica, desenhos tecnicos, precisao industrial",
  },
  {
    locale: "pt",
    sourceSlug: "fit",
    slug: "pe",
    category: "uzunluk",
    categoryName: "Comprimento",
    unit: "ft",
    name: "Pe",
    symbol: "ft",
    shortDescription: "O pe e uma unidade de comprimento do sistema imperial, ainda usada nos Estados Unidos e no Reino Unido.",
    historySummary: "Historicamente baseado no comprimento do pe humano, foi padronizado exatamente em 0,3048 metro em 1959 por um acordo internacional.",
    measurementSystem: "Sistema imperial/norte-americano",
    siEquivalent: "1 ft = 0,3048 m",
    commonUses: "Imobiliario, aviacao (altitude), construcao nos Estados Unidos",
  },
  {
    locale: "pt",
    sourceSlug: "inc",
    slug: "polegada",
    category: "uzunluk",
    categoryName: "Comprimento",
    unit: "in",
    name: "Polegada",
    symbol: "in",
    shortDescription: "A polegada e uma pequena unidade de comprimento imperial, muito usada para telas e tubulacoes.",
    historySummary: "A polegada leva o nome da largura do polegar humano e foi fixada exatamente em 2,54 centimetros em 1959.",
    measurementSystem: "Sistema imperial/norte-americano",
    siEquivalent: "1 in = 2,54 cm",
    commonUses: "Tamanho de telas, diametro de tubulacoes, ferramentas",
  },
  {
    locale: "pt",
    sourceSlug: "yarda",
    slug: "jarda",
    category: "uzunluk",
    categoryName: "Comprimento",
    unit: "yd",
    name: "Jarda",
    symbol: "yd",
    shortDescription: "A jarda equivale a 3 pes e e usada especialmente no futebol americano e no golfe.",
    historySummary: "De origem inglesa, a jarda foi padronizada exatamente em 0,9144 metro no acordo internacional de unidades de 1959.",
    measurementSystem: "Sistema imperial/norte-americano",
    siEquivalent: "1 yd = 0,9144 m",
    commonUses: "Esporte (futebol americano, golfe), textil",
  },
  {
    locale: "pt",
    sourceSlug: "mil",
    slug: "milha",
    category: "uzunluk",
    categoryName: "Comprimento",
    unit: "mi",
    name: "Milha",
    symbol: "mi",
    shortDescription: "A milha terrestre e a unidade de distancia rodoviaria nos Estados Unidos e no Reino Unido.",
    historySummary: "Derivada da milha romana, a milha moderna (milha terrestre) foi fixada exatamente em 1609,344 metros.",
    measurementSystem: "Sistema imperial/norte-americano",
    siEquivalent: "1 mi = 1609,344 m",
    commonUses: "Distancias rodoviarias nos Estados Unidos e no Reino Unido",
  },

  // Area
  {
    locale: "pt",
    sourceSlug: "metrekare",
    slug: "metro-quadrado",
    category: "alan",
    categoryName: "Area",
    unit: "m²",
    name: "Metro quadrado",
    symbol: "m²",
    shortDescription: "O metro quadrado e a unidade basica do SI para area, a de um quadrado de um metro de lado.",
    historySummary: "Desde a introducao do sistema metrico, o metro quadrado e a unidade padrao em medicoes de construcao e terrenos.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidade basica do SI para a area",
    commonUses: "Area de edificios, extensao de terrenos, plantas de construcao",
  },
  {
    locale: "pt",
    sourceSlug: "hektar",
    slug: "hectare",
    category: "alan",
    categoryName: "Area",
    unit: "ha",
    name: "Hectare",
    symbol: "ha",
    shortDescription: "O hectare e uma grande unidade de area igual a 10.000 metros quadrados, usada sobretudo em terras agricolas.",
    historySummary: "O hectare foi amplamente adotado para expressar facilmente grandes areas na agricultura e na gestao de terrenos.",
    measurementSystem: "Sistema metrico (fora do SI, unidade comum)",
    siEquivalent: "1 ha = 10.000 m²",
    commonUses: "Terras agricolas, silvicultura, planejamento urbano",
  },
  {
    locale: "pt",
    sourceSlug: "akre",
    slug: "acre",
    category: "alan",
    categoryName: "Area",
    unit: "ac",
    name: "Acre",
    symbol: "ac",
    shortDescription: "O acre e uma unidade de area do sistema imperial, muito usada no mercado imobiliario dos Estados Unidos.",
    historySummary: "Historicamente, o acre representava a area que uma junta de bois conseguia arar em um dia; hoje equivale exatamente a 4046,8564224 m².",
    measurementSystem: "Sistema imperial/norte-americano",
    siEquivalent: "1 ac ≈ 4046,86 m²",
    commonUses: "Terrenos imobiliarios e agricolas nos Estados Unidos e no Reino Unido",
  },

  // Volume
  {
    locale: "pt",
    sourceSlug: "litre",
    slug: "litro",
    category: "hacim",
    categoryName: "Volume",
    unit: "L",
    name: "Litro",
    symbol: "L",
    shortDescription: "O litro e a unidade pratica de volume mais usada no dia a dia, igual a 0,001 metro cubico.",
    historySummary: "O litro foi introduzido com o sistema metrico e continua sendo a unidade padrao para liquidos no mundo todo.",
    measurementSystem: "Sistema metrico (fora do SI, unidade comum)",
    siEquivalent: "1 L = 0,001 m³",
    commonUses: "Bebidas, combustivel, medidas de cozinha",
  },
  {
    locale: "pt",
    sourceSlug: "mililitre",
    slug: "mililitro",
    category: "hacim",
    categoryName: "Volume",
    unit: "mL",
    name: "Mililitro",
    symbol: "mL",
    shortDescription: "O mililitro equivale a milesima parte de um litro, usado para pequenas quantidades de liquido.",
    historySummary: "Submultiplo do litro, o mililitro se tornou a unidade padrao em medicina e culinaria para pequenas doses.",
    measurementSystem: "Sistema metrico (fora do SI, submultiplo)",
    siEquivalent: "1 mL = 0,001 L",
    commonUses: "Medicamentos, cosmeticos, medidas culinarias precisas",
  },
  {
    locale: "pt",
    sourceSlug: "metrekup",
    slug: "metro-cubico",
    category: "hacim",
    categoryName: "Volume",
    unit: "m³",
    name: "Metro cubico",
    symbol: "m³",
    shortDescription: "O metro cubico e a unidade de referencia do SI para o volume.",
    historySummary: "O metro cubico deriva diretamente do metro, a unidade basica de comprimento, elevada ao cubo.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidade de referencia do SI para o volume",
    commonUses: "Gas natural, concreto, grandes volumes industriais",
  },
  {
    locale: "pt",
    sourceSlug: "galon",
    slug: "galao",
    category: "hacim",
    categoryName: "Volume",
    unit: "gal",
    name: "Galao (US)",
    symbol: "gal",
    shortDescription: "O galao norte-americano e a unidade de volume liquido usada nos Estados Unidos, especialmente para gasolina.",
    historySummary: "O galao norte-americano (liquido) deriva de antigas medidas inglesas e difere do galao imperial britanico.",
    measurementSystem: "Sistema norte-americano (US customary)",
    siEquivalent: "1 gal (US) ≈ 3,785 L",
    commonUses: "Combustivel e bebidas nos Estados Unidos",
  },

  // Massa
  {
    locale: "pt",
    sourceSlug: "kilogram",
    slug: "quilograma",
    category: "kutle",
    categoryName: "Massa",
    unit: "kg",
    name: "Quilograma",
    symbol: "kg",
    shortDescription: "O quilograma e a unidade basica do SI para a massa.",
    historySummary: "Desde 2019, o quilograma e definido a partir da constante de Planck, substituindo o antigo protótipo metalico guardado em Paris.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidade basica do SI para a massa",
    commonUses: "Peso corporal, encomendas, culinaria",
  },
  {
    locale: "pt",
    sourceSlug: "gram",
    slug: "grama",
    category: "kutle",
    categoryName: "Massa",
    unit: "g",
    name: "Grama",
    symbol: "g",
    shortDescription: "O grama equivale a milesima parte de um quilograma e e usado para pequenas quantidades de materia.",
    historySummary: "O grama foi originalmente definido como a massa de um centimetro cubico de agua a 4 °C.",
    measurementSystem: "Sistema Internacional (SI, submultiplo)",
    siEquivalent: "1 g = 0,001 kg",
    commonUses: "Culinaria, joalheria, laboratorio",
  },
  {
    locale: "pt",
    sourceSlug: "miligram",
    slug: "miligrama",
    category: "kutle",
    categoryName: "Massa",
    unit: "mg",
    name: "Miligrama",
    symbol: "mg",
    shortDescription: "O miligrama equivale a milesima parte de um grama, usado principalmente em farmacia e quimica.",
    historySummary: "Submultiplo do grama, o miligrama se tornou essencial para a dosagem precisa de medicamentos.",
    measurementSystem: "Sistema Internacional (SI, submultiplo)",
    siEquivalent: "1 mg = 0,001 g",
    commonUses: "Dosagem de medicamentos, quimica analitica",
  },
  {
    locale: "pt",
    sourceSlug: "ton",
    slug: "tonelada",
    category: "kutle",
    categoryName: "Massa",
    unit: "t",
    name: "Tonelada",
    symbol: "t",
    shortDescription: "A tonelada equivale a 1000 quilogramas e e usada para medir grandes massas.",
    historySummary: "A tonelada metrica se consolidou para expressar facilmente grandes massas na industria e no transporte.",
    measurementSystem: "Sistema metrico (fora do SI, multiplo)",
    siEquivalent: "1 t = 1000 kg",
    commonUses: "Transporte maritimo, industria pesada, agricultura",
  },
  {
    locale: "pt",
    sourceSlug: "pound",
    slug: "libra",
    category: "kutle",
    categoryName: "Massa",
    unit: "lb",
    name: "Libra",
    symbol: "lb",
    shortDescription: "A libra e a unidade de massa do sistema imperial, muito usada nos Estados Unidos.",
    historySummary: "A libra avoirdupois moderna foi fixada exatamente em 0,45359237 quilograma em 1959.",
    measurementSystem: "Sistema imperial/norte-americano",
    siEquivalent: "1 lb = 0,45359237 kg",
    commonUses: "Peso corporal e alimentacao nos Estados Unidos",
  },
  {
    locale: "pt",
    sourceSlug: "ons",
    slug: "onca",
    category: "kutle",
    categoryName: "Massa",
    unit: "oz",
    name: "Onca",
    symbol: "oz",
    shortDescription: "A onca equivale a um dezesseis avos de libra e e usada para massas pequenas no sistema imperial.",
    historySummary: "A onca avoirdupois e usada ha seculos na Inglaterra para pequenas quantidades de mercadorias.",
    measurementSystem: "Sistema imperial/norte-americano",
    siEquivalent: "1 oz ≈ 28,3495 g",
    commonUses: "Alimentacao e cosmeticos nos Estados Unidos",
  },

  // Temperatura
  {
    locale: "pt",
    sourceSlug: "santigrat",
    slug: "celsius",
    category: "sicaklik",
    categoryName: "Temperatura",
    unit: "C",
    name: "Celsius",
    symbol: "°C",
    shortDescription: "A escala Celsius e usada na maior parte do mundo, com 0 °C como ponto de congelamento e 100 °C como ponto de ebulicao da agua.",
    historySummary: "Proposta pelo astronomo sueco Anders Celsius em 1742, a escala foi invertida depois para adotar sua forma atual.",
    measurementSystem: "Sistema metrico (escala comum)",
    siEquivalent: "K = °C + 273,15",
    commonUses: "Meteorologia, culinaria, ciencia na maior parte do mundo",
  },
  {
    locale: "pt",
    sourceSlug: "fahrenhayt",
    slug: "fahrenheit",
    category: "sicaklik",
    categoryName: "Temperatura",
    unit: "F",
    name: "Fahrenheit",
    symbol: "°F",
    shortDescription: "A escala Fahrenheit e usada principalmente nos Estados Unidos para a temperatura cotidiana.",
    historySummary: "Proposta em 1724 pelo fisico alemao Daniel Gabriel Fahrenheit, baseada inicialmente em uma mistura refrigerante.",
    measurementSystem: "Sistema norte-americano (escala comum)",
    siEquivalent: "°C = (°F − 32) × 5/9",
    commonUses: "Meteorologia e culinaria nos Estados Unidos",
  },
  {
    locale: "pt",
    sourceSlug: "kelvin",
    slug: "kelvin",
    category: "sicaklik",
    categoryName: "Temperatura",
    unit: "K",
    name: "Kelvin",
    symbol: "K",
    shortDescription: "O kelvin e a unidade basica do SI para temperatura, sem valores negativos.",
    historySummary: "Recebeu esse nome em homenagem ao fisico William Thomson (Lord Kelvin), o kelvin parte do zero absoluto, a temperatura mais baixa possivel.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidade basica do SI para a temperatura",
    commonUses: "Pesquisa cientifica, fisica, astronomia",
  },

  // Tempo
  {
    locale: "pt",
    sourceSlug: "saniye",
    slug: "segundo",
    category: "zaman",
    categoryName: "Tempo",
    unit: "s",
    name: "Segundo",
    symbol: "s",
    shortDescription: "O segundo e a unidade basica do SI para o tempo.",
    historySummary: "Desde 1967, o segundo e definido a partir de 9.192.631.770 periodos de radiacao do atomo de cesio-133.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidade basica do SI para o tempo",
    commonUses: "Cronometragem esportiva, ciencia, computacao",
  },
  {
    locale: "pt",
    sourceSlug: "dakika",
    slug: "minuto",
    category: "zaman",
    categoryName: "Tempo",
    unit: "min",
    name: "Minuto",
    symbol: "min",
    shortDescription: "O minuto equivale a 60 segundos e e a unidade de tempo mais usada no dia a dia.",
    historySummary: "A divisao em 60 unidades vem do sistema sexagesimal babilonico, ainda usado hoje.",
    measurementSystem: "Aceito junto ao SI",
    siEquivalent: "1 min = 60 s",
    commonUses: "Horarios, culinaria, esporte",
  },
  {
    locale: "pt",
    sourceSlug: "saat",
    slug: "hora",
    category: "zaman",
    categoryName: "Tempo",
    unit: "h",
    name: "Hora",
    symbol: "h",
    shortDescription: "A hora equivale a 60 minutos e serve para organizar o dia.",
    historySummary: "A divisao do dia em 24 horas remonta ao Antigo Egito.",
    measurementSystem: "Aceito junto ao SI",
    siEquivalent: "1 h = 3600 s",
    commonUses: "Tempo de trabalho, tempo de viagem, horarios",
  },
  {
    locale: "pt",
    sourceSlug: "gun",
    slug: "dia",
    category: "zaman",
    categoryName: "Tempo",
    unit: "day",
    name: "Dia",
    symbol: "d",
    shortDescription: "O dia corresponde a uma rotacao completa da Terra em torno de si mesma, ou seja, 24 horas.",
    historySummary: "A duracao do dia se baseia no ciclo dia-noite observado desde a antiguidade.",
    measurementSystem: "Aceito junto ao SI",
    siEquivalent: "1 dia = 86.400 s",
    commonUses: "Calendario, planejamento, calculo de duracoes",
  },

  // Velocidade
  {
    locale: "pt",
    sourceSlug: "kilometre-saat",
    slug: "quilometro-hora",
    category: "hiz",
    categoryName: "Velocidade",
    unit: "km/h",
    name: "Quilometro por hora",
    symbol: "km/h",
    shortDescription: "O quilometro por hora e a unidade padrao de velocidade rodoviaria na maioria dos paises.",
    historySummary: "Adotada com o sistema metrico, essa unidade se tornou a referencia dos limites de velocidade no mundo todo.",
    measurementSystem: "Sistema metrico (unidade comum)",
    siEquivalent: "1 km/h ≈ 0,278 m/s",
    commonUses: "Velocidade de veiculos, limites de velocidade",
  },
  {
    locale: "pt",
    sourceSlug: "metre-saniye",
    slug: "metro-segundo",
    category: "hiz",
    categoryName: "Velocidade",
    unit: "m/s",
    name: "Metro por segundo",
    symbol: "m/s",
    shortDescription: "O metro por segundo e a unidade SI de velocidade, usada em fisica e meteorologia.",
    historySummary: "Unidade derivada diretamente do metro e do segundo, padrao em calculos cientificos.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidade SI derivada da velocidade",
    commonUses: "Velocidade do vento, calculos fisicos",
  },
  {
    locale: "pt",
    sourceSlug: "mil-saat",
    slug: "milha-hora",
    category: "hiz",
    categoryName: "Velocidade",
    unit: "mph",
    name: "Milha por hora",
    symbol: "mph",
    shortDescription: "A milha por hora e a unidade de velocidade rodoviaria nos Estados Unidos e no Reino Unido.",
    historySummary: "Derivada da milha terrestre, essa unidade continua sendo o padrao das placas de transito em ambos os paises.",
    measurementSystem: "Sistema imperial/norte-americano",
    siEquivalent: "1 mph ≈ 0,447 m/s",
    commonUses: "Velocidade de veiculos nos Estados Unidos e no Reino Unido",
  },
  {
    locale: "pt",
    sourceSlug: "knot",
    slug: "no",
    category: "hiz",
    categoryName: "Velocidade",
    unit: "knot",
    name: "No",
    symbol: "kn",
    shortDescription: "O no (milha nautica por hora) e a unidade padrao de velocidade na navegacao maritima e aerea.",
    historySummary: "O nome vem do metodo historico de contar os nos de uma corda jogada na agua para medir a velocidade de um navio.",
    measurementSystem: "Navegacao maritima/aerea",
    siEquivalent: "1 kn ≈ 0,514 m/s",
    commonUses: "Velocidade de navios e avioes",
  },

  // Pressao
  {
    locale: "pt",
    sourceSlug: "pascal",
    slug: "pascal",
    category: "basinc",
    categoryName: "Pressao",
    unit: "Pa",
    name: "Pascal",
    symbol: "Pa",
    shortDescription: "O pascal e a unidade SI de pressao, igual a um newton por metro quadrado.",
    historySummary: "Recebeu esse nome em homenagem a Blaise Pascal, adotado como unidade SI de pressao em 1971.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "1 Pa = 1 N/m²",
    commonUses: "Calculos cientificos e de engenharia",
  },
  {
    locale: "pt",
    sourceSlug: "bar",
    slug: "bar",
    category: "basinc",
    categoryName: "Pressao",
    unit: "bar",
    name: "Bar",
    symbol: "bar",
    shortDescription: "O bar e uma unidade de pressao pratica proxima da pressao atmosferica media, muito usada na industria.",
    historySummary: "Introduzido no inicio do seculo XX pelo meteorologista Vilhelm Bjerknes, o bar continua amplamente usado apesar da adocao do pascal.",
    measurementSystem: "Sistema metrico (fora do SI)",
    siEquivalent: "1 bar = 100.000 Pa",
    commonUses: "Sistemas industriais, compressores, meteorologia",
  },
  {
    locale: "pt",
    sourceSlug: "psi",
    slug: "psi",
    category: "basinc",
    categoryName: "Pressao",
    unit: "psi",
    name: "PSI",
    symbol: "psi",
    shortDescription: "O PSI (libra-forca por polegada quadrada) e a unidade de pressao do sistema imperial, comum em pneus.",
    historySummary: "O PSI se consolidou com o sistema imperial norte-americano, especialmente para pressao de pneus e sistemas hidraulicos.",
    measurementSystem: "Sistema imperial/norte-americano",
    siEquivalent: "1 psi ≈ 6894,76 Pa",
    commonUses: "Pressao de pneus, sistemas hidraulicos e pneumaticos",
  },
  {
    locale: "pt",
    sourceSlug: "atmosfer",
    slug: "atmosfera",
    category: "basinc",
    categoryName: "Pressao",
    unit: "atm",
    name: "Atmosfera padrao",
    symbol: "atm",
    shortDescription: "A atmosfera padrao representa aproximadamente a pressao atmosferica media ao nivel do mar.",
    historySummary: "Definida a partir das medicoes barometricas de Torricelli no seculo XVII, serve de referencia para as condicoes padrao.",
    measurementSystem: "Fora do SI (unidade de referencia)",
    siEquivalent: "1 atm = 101.325 Pa",
    commonUses: "Condicoes atmosfericas e de referencia",
  },

  // Energia
  {
    locale: "pt",
    sourceSlug: "joule",
    slug: "joule",
    category: "enerji",
    categoryName: "Energia",
    unit: "J",
    name: "Joule",
    symbol: "J",
    shortDescription: "O joule e a unidade SI de energia, igual ao trabalho de uma forca de um newton ao longo de um metro.",
    historySummary: "Recebeu esse nome em homenagem ao fisico ingles James Prescott Joule por seus trabalhos sobre energia e calor.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "1 J = 1 N·m",
    commonUses: "Calculos cientificos e fisicos de energia",
  },
  {
    locale: "pt",
    sourceSlug: "kilovatsaat",
    slug: "quilowatt-hora",
    category: "enerji",
    categoryName: "Energia",
    unit: "kWh",
    name: "Quilowatt-hora",
    symbol: "kWh",
    shortDescription: "O quilowatt-hora e a unidade padrao de cobranca do consumo eletrico no mundo.",
    historySummary: "Adotado com a generalizacao da eletricidade domestica, o quilowatt-hora continua sendo a unidade de referencia dos medidores eletricos.",
    measurementSystem: "Sistema metrico (eletricidade)",
    siEquivalent: "1 kWh = 3.600.000 J",
    commonUses: "Cobranca de energia eletrica",
  },
  {
    locale: "pt",
    sourceSlug: "kalori",
    slug: "caloria",
    category: "enerji",
    categoryName: "Energia",
    unit: "cal",
    name: "Caloria",
    symbol: "cal",
    shortDescription: "A caloria e a energia necessaria para elevar em um grau Celsius a temperatura de um grama de agua.",
    historySummary: "Definida no seculo XIX para estudos termicos, a caloria hoje esta associada sobretudo a nutricao.",
    measurementSystem: "Sistema metrico (tradicional)",
    siEquivalent: "1 cal = 4,184 J",
    commonUses: "Nutricao e quimica",
  },
  {
    locale: "pt",
    sourceSlug: "btu",
    slug: "btu",
    category: "enerji",
    categoryName: "Energia",
    unit: "Btu",
    name: "BTU",
    symbol: "BTU",
    shortDescription: "O BTU (British Thermal Unit) expressa a capacidade de sistemas de aquecimento e ar-condicionado.",
    historySummary: "De origem britanica, o BTU continua sendo muito usado nos Estados Unidos para aparelhos termicos.",
    measurementSystem: "Sistema imperial/norte-americano",
    siEquivalent: "1 Btu ≈ 1055,06 J",
    commonUses: "Climatizacao e aquecimento",
  },

  // Armazenamento de dados
  {
    locale: "pt",
    sourceSlug: "bayt",
    slug: "byte",
    category: "veri",
    categoryName: "Armazenamento de dados",
    unit: "B",
    name: "Byte",
    symbol: "B",
    shortDescription: "O byte (8 bits) e a unidade basica para representar caracteres e dados digitais.",
    historySummary: "O byte se consolidou com o desenvolvimento dos primeiros computadores como unidade padrao de processamento de dados.",
    measurementSystem: "Computacao",
    siEquivalent: "1 B = 8 bits",
    commonUses: "Tamanho de arquivos, memoria, armazenamento",
  },
  {
    locale: "pt",
    sourceSlug: "megabayt",
    slug: "megabyte",
    category: "veri",
    categoryName: "Armazenamento de dados",
    unit: "MB",
    name: "Megabyte",
    symbol: "MB",
    shortDescription: "O megabyte e usado para expressar o tamanho de arquivos medios, como fotos ou documentos.",
    historySummary: "Com o crescimento das capacidades de armazenamento, o megabyte se tornou a unidade habitual para arquivos digitais.",
    measurementSystem: "Computacao (base 1000 ou 1024)",
    siEquivalent: "1 MB = 1.000.000 B (ou 1024² B em base binaria)",
    commonUses: "Tamanho de fotos, documentos e aplicativos",
  },
  {
    locale: "pt",
    sourceSlug: "gigabayt",
    slug: "gigabyte",
    category: "veri",
    categoryName: "Armazenamento de dados",
    unit: "GB",
    name: "Gigabyte",
    symbol: "GB",
    shortDescription: "O gigabyte e a unidade padrao para expressar a capacidade de armazenamento de celulares e computadores.",
    historySummary: "O gigabyte se consolidou com o crescimento do armazenamento digital massivo (discos rigidos, pendrives, celulares).",
    measurementSystem: "Computacao (base 1000 ou 1024)",
    siEquivalent: "1 GB = 1.000.000.000 B (ou 1024³ B em base binaria)",
    commonUses: "Armazenamento de celulares, computadores e planos de internet",
  },

  // Eletricidade
  {
    locale: "pt",
    sourceSlug: "volt",
    slug: "volt",
    category: "elektrik",
    categoryName: "Eletricidade",
    unit: "V",
    name: "Volt",
    symbol: "V",
    shortDescription: "O volt e a unidade SI de diferenca de potencial eletrico.",
    historySummary: "Recebeu esse nome em homenagem ao fisico italiano Alessandro Volta, inventor da primeira pilha eletrica.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidade SI de tensao eletrica",
    commonUses: "Pilhas, tomadas, circuitos eletronicos",
  },
  {
    locale: "pt",
    sourceSlug: "amper",
    slug: "ampere",
    category: "elektrik",
    categoryName: "Eletricidade",
    unit: "A",
    name: "Ampere",
    symbol: "A",
    shortDescription: "O ampere e a unidade basica do SI para a corrente eletrica.",
    historySummary: "Recebeu esse nome em homenagem ao fisico frances Andre-Marie Ampere, pioneiro do eletromagnetismo.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidade basica do SI para a corrente eletrica",
    commonUses: "Circuitos eletricos, disjuntores, carregadores",
  },
  {
    locale: "pt",
    sourceSlug: "miliamper",
    slug: "miliampere",
    category: "elektrik",
    categoryName: "Eletricidade",
    unit: "mA",
    name: "Miliampere",
    symbol: "mA",
    shortDescription: "O miliampere equivale a milesima parte de um ampere e e usado para medir pequenas correntes em eletronica.",
    historySummary: "Submultiplo do ampere, o miliampere se tornou essencial com o desenvolvimento da eletronica de precisao.",
    measurementSystem: "Sistema Internacional (SI, submultiplo)",
    siEquivalent: "1 mA = 0,001 A",
    commonUses: "Baterias de celular, sensores, circuitos eletronicos",
  },

  // Quilate de ouro
  {
    locale: "pt",
    sourceSlug: "24-ayar-altin",
    slug: "ouro-24-quilates",
    category: "altin_ayar",
    categoryName: "Quilate de ouro",
    unit: "24K",
    name: "Ouro de 24 quilates",
    symbol: "24K",
    shortDescription: "O ouro de 24 quilates e ouro puro a 99,9%, a referencia do sistema de quilates.",
    historySummary: "O ouro de 24 quilates e tradicionalmente usado em lingotes de investimento devido a sua maxima pureza.",
    measurementSystem: "Sistema de quilates",
    siEquivalent: "99,9% de ouro puro",
    commonUses: "Lingotes e investimento em ouro",
  },
  {
    locale: "pt",
    sourceSlug: "22-ayar-altin",
    slug: "ouro-22-quilates",
    category: "altin_ayar",
    categoryName: "Quilate de ouro",
    unit: "22K",
    name: "Ouro de 22 quilates",
    symbol: "22K",
    shortDescription: "O ouro de 22 quilates contem cerca de 91,6% de ouro puro e e popular na joalheria tradicional.",
    historySummary: "Muito usado no sul da Asia e no Oriente Medio, equilibra pureza e resistencia para a fabricacao de joias.",
    measurementSystem: "Sistema de quilates",
    siEquivalent: "≈91,6% de ouro puro",
    commonUses: "Joalheria tradicional",
  },
  {
    locale: "pt",
    sourceSlug: "18-ayar-altin",
    slug: "ouro-18-quilates",
    category: "altin_ayar",
    categoryName: "Quilate de ouro",
    unit: "18K",
    name: "Ouro de 18 quilates",
    symbol: "18K",
    shortDescription: "O ouro de 18 quilates contem 75% de ouro puro e e o padrao mais comum na joalheria ocidental.",
    historySummary: "Seu bom equilibrio entre dureza e pureza o torna a referencia das joalherias na Europa e nas Americas.",
    measurementSystem: "Sistema de quilates",
    siEquivalent: "75% de ouro puro",
    commonUses: "Joalheria ocidental, aliancas de casamento",
  },

  // Teor de prata
  {
    locale: "pt",
    sourceSlug: "999-ayar-gumus",
    slug: "prata-999",
    category: "gumus_ayar",
    categoryName: "Teor de prata",
    unit: "999",
    name: "Prata 999 (fina)",
    symbol: "999",
    shortDescription: "A prata 999 e prata pura a 99,9%, usada principalmente em lingotes de investimento.",
    historySummary: "Sua maxima pureza a torna o padrao preferido para produtos de investimento e lingotes de prata.",
    measurementSystem: "Sistema de milesimos",
    siEquivalent: "99,9% de prata pura",
    commonUses: "Lingotes e prata de investimento",
  },
  {
    locale: "pt",
    sourceSlug: "925-ayar-gumus",
    slug: "prata-esterlina-925",
    category: "gumus_ayar",
    categoryName: "Teor de prata",
    unit: "925",
    name: "Prata esterlina (925)",
    symbol: "925",
    shortDescription: "A prata esterlina contem 92,5% de prata pura e e o padrao mundial da joalheria de prata.",
    historySummary: "O padrao da prata esterlina remonta a Inglaterra do seculo XII e continua sendo a norma mais reconhecida do mundo.",
    measurementSystem: "Sistema de milesimos",
    siEquivalent: "92,5% de prata pura",
    commonUses: "Joalheria e talheres",
  },
];

export function findPortugueseUnitPageBySourceSlug(sourceSlug: string) {
  return portugueseUnitPages.find((page) => page.sourceSlug === sourceSlug);
}

export function findPortugueseUnitPage(category: string, unit: string) {
  return portugueseUnitPages.find(
    (page) => page.category === category && page.unit === unit
  );
}
