// Pages d'unite francaises -- integrees au nouveau systeme i18n
// Fichier independant et nouveau (ne touche pas aux fichiers tr/en/de/ar/uz/bn existants).
// Portee volontairement limitee aux 13 categories fondamentales qui, avec
// les 4 outils universels (page d'accueil), forment les 17 elements de
// l'identite du site -- pas de categories techniques/medicales annexes
// (tork, kan sekeri, etc.) a ce stade.

export type LocalizedFrenchUnitPage = {
  locale: "fr";
  sourceSlug: string;
  slug: string;
  category: string;
  categoryName: string;
  unit: string;
  name: string;
  symbol: string;
  shortDescription: string;
  historySummary: string;
  measurementSystem: string;
  siEquivalent: string;
  commonUses: string;
};

export const frenchUnitPages: LocalizedFrenchUnitPage[] = [
  // Longueur
  {
    locale: "fr",
    sourceSlug: "metre",
    slug: "metre",
    category: "uzunluk",
    categoryName: "Longueur",
    unit: "m",
    name: "Mètre",
    symbol: "m",
    shortDescription: "Le mètre est l’unité SI de base de la longueur.",
    historySummary:
      "Depuis 1983, le mètre est défini avec précision à partir de la distance parcourue par la lumière dans le vide en 1/299 792 458 de seconde.",
    measurementSystem: "Système international d’unités (SI)",
    siEquivalent: "Unité SI de base de la longueur",
    commonUses: "Construction, sport, sciences et mesure de distance au quotidien",
  },
  {
    locale: "fr",
    sourceSlug: "kilometre",
    slug: "kilometre",
    category: "uzunluk",
    categoryName: "Longueur",
    unit: "km",
    name: "Kilomètre",
    symbol: "km",
    shortDescription: "Le kilomètre vaut 1 000 mètres et sert à exprimer la distance entre les villes.",
    historySummary:
      "Le kilomètre s’est imposé comme multiple du mètre dans la structure décimale du système métrique, devenant l’unité standard des routes et des cartes.",
    measurementSystem: "Système international (SI, multiple)",
    siEquivalent: "1 km = 1000 m",
    commonUses: "Distance routiere, geographie, cartographie et infrastructure",
  },
  {
    locale: "fr",
    sourceSlug: "santimetre",
    slug: "centimetre",
    category: "uzunluk",
    categoryName: "Longueur",
    unit: "cm",
    name: "Centimètre",
    symbol: "cm",
    shortDescription: "Le centimètre vaut un centième de mètre et sert aux mesures précises du quotidien.",
    historySummary:
      "Introduit avec le système métrique, le centimètre est devenu l’unité pratique pour mesurer des objets de petite et moyenne taille.",
    measurementSystem: "Système international (SI, sous-multiple)",
    siEquivalent: "1 cm = 0,01 m",
    commonUses: "Couture, mesures corporelles, objets du quotidien",
  },
  {
    locale: "fr",
    sourceSlug: "milimetre",
    slug: "millimetre",
    category: "uzunluk",
    categoryName: "Longueur",
    unit: "mm",
    name: "Millimètre",
    symbol: "mm",
    shortDescription: "Le millimètre vaut un millième de mètre, utilisé pour les mesures de haute précision.",
    historySummary:
      "Le millimètre est un sous-multiple du système métrique adopté pour l’ingénierie et la fabrication de précision.",
    measurementSystem: "Système international (SI, sous-multiple)",
    siEquivalent: "1 mm = 0,001 m",
    commonUses: "Ingénierie mécanique, plans techniques, précision industrielle",
  },
  {
    locale: "fr",
    sourceSlug: "fit",
    slug: "pied",
    category: "uzunluk",
    categoryName: "Longueur",
    unit: "ft",
    name: "Pied",
    symbol: "ft",
    shortDescription: "Le pied est une unité de longueur du système impérial, encore utilisée aux États-Unis et au Royaume-Uni.",
    historySummary:
      "Historiquement basé sur la longueur du pied humain, le pied a été standardisé à exactement 0,3048 mètre en 1959 par accord international.",
    measurementSystem: "Système impérial/américain",
    siEquivalent: "1 ft = 0,3048 m",
    commonUses: "Immobilier, aviation (altitude), construction aux Etats-Unis",
  },
  {
    locale: "fr",
    sourceSlug: "inc",
    slug: "pouce",
    category: "uzunluk",
    categoryName: "Longueur",
    unit: "in",
    name: "Pouce",
    symbol: "in",
    shortDescription: "Le pouce est une petite unité de longueur impériale, très utilisée pour les écrans et les tuyaux.",
    historySummary:
      "Le pouce tire son nom de la largeur du pouce humain et a été fixé à exactement 2,54 centimètres en 1959.",
    measurementSystem: "Système impérial/américain",
    siEquivalent: "1 in = 2,54 cm",
    commonUses: "Taille des écrans, diamètre des tuyaux, outillage",
  },
  {
    locale: "fr",
    sourceSlug: "yarda",
    slug: "yard",
    category: "uzunluk",
    categoryName: "Longueur",
    unit: "yd",
    name: "Yard",
    symbol: "yd",
    shortDescription: "Le yard vaut 3 pieds et est utilisé notamment au football américain et au golf.",
    historySummary:
      "D’origine anglaise, le yard a été standardisé à exactement 0,9144 mètre lors de l’accord international de 1959 sur les unités.",
    measurementSystem: "Système impérial/américain",
    siEquivalent: "1 yd = 0,9144 m",
    commonUses: "Sport (football americain, golf), textile",
  },
  {
    locale: "fr",
    sourceSlug: "mil",
    slug: "mile",
    category: "uzunluk",
    categoryName: "Longueur",
    unit: "mi",
    name: "Mile",
    symbol: "mi",
    shortDescription: "Le mile terrestre est l'unite de distance routiere aux Etats-Unis et au Royaume-Uni.",
    historySummary:
      "Derive du mille romain, le mile moderne (mile terrestre) a ete fixe a 1609,344 metres exactement.",
    measurementSystem: "Systeme imperial/americain",
    siEquivalent: "1 mi = 1609,344 m",
    commonUses: "Distances routieres aux Etats-Unis et au Royaume-Uni",
  },

  // Surface
  {
    locale: "fr",
    sourceSlug: "metrekare",
    slug: "metre-carre",
    category: "alan",
    categoryName: "Surface",
    unit: "m²",
    name: "Mètre carré",
    symbol: "m²",
    shortDescription: "Le mètre carré est l’unité SI de base de la surface, celle d’un carré d’un mètre de côté.",
    historySummary: "Depuis l’introduction du système métrique, le mètre carré est l’unité standard des mesures de construction et de terrain.",
    measurementSystem: "Système international (SI)",
    siEquivalent: "Unité SI de base de la surface",
    commonUses: "Surface des bâtiments, superficie des terrains, plans de construction",
  },
  {
    locale: "fr",
    sourceSlug: "hektar",
    slug: "hectare",
    category: "alan",
    categoryName: "Surface",
    unit: "ha",
    name: "Hectare",
    symbol: "ha",
    shortDescription: "L’hectare est une grande unité de surface égale à 10 000 mètres carrés, surtout utilisée pour les terres agricoles.",
    historySummary: "L’hectare a été largement adopté pour exprimer facilement de grandes surfaces en agriculture et en gestion foncière.",
    measurementSystem: "Système métrique (hors SI, unité courante)",
    siEquivalent: "1 ha = 10 000 m²",
    commonUses: "Terres agricoles, foresterie, urbanisme",
  },
  {
    locale: "fr",
    sourceSlug: "akre",
    slug: "acre",
    category: "alan",
    categoryName: "Surface",
    unit: "ac",
    name: "Acre",
    symbol: "ac",
    shortDescription: "L’acre est une unité de surface du système impérial, très utilisée dans l’immobilier aux États-Unis.",
    historySummary: "Historiquement, l’acre représentait la surface qu’une paire de bœufs pouvait labourer en un jour ; elle vaut aujourd’hui exactement 4 046,8564224 m².",
    measurementSystem: "Système impérial/américain",
    siEquivalent: "1 ac ≈ 4046,86 m²",
    commonUses: "Immobilier et terrains agricoles aux Etats-Unis et au Royaume-Uni",
  },

  // Volume
  {
    locale: "fr",
    sourceSlug: "litre",
    slug: "litre",
    category: "hacim",
    categoryName: "Volume",
    unit: "L",
    name: "Litre",
    symbol: "L",
    shortDescription: "Le litre est l’unité pratique de volume la plus utilisée au quotidien, égale à 0,001 mètre cube.",
    historySummary: "Le litre a été introduit avec le système métrique et reste l’unité standard des liquides dans le monde entier.",
    measurementSystem: "Système métrique (hors SI, unité courante)",
    siEquivalent: "1 L = 0,001 m³",
    commonUses: "Boissons, carburant, mesures de cuisine",
  },
  {
    locale: "fr",
    sourceSlug: "mililitre",
    slug: "millilitre",
    category: "hacim",
    categoryName: "Volume",
    unit: "mL",
    name: "Millilitre",
    symbol: "mL",
    shortDescription: "Le millilitre vaut un millième de litre, utilisé pour les petites quantités de liquide.",
    historySummary: "Sous-multiple du litre, le millilitre est devenu l’unité standard en médecine et en cuisine pour les petites doses.",
    measurementSystem: "Système métrique (hors SI, sous-multiple)",
    siEquivalent: "1 mL = 0,001 L",
    commonUses: "Médicaments, cosmétiques, mesures culinaires précises",
  },
  {
    locale: "fr",
    sourceSlug: "metrekup",
    slug: "metre-cube",
    category: "hacim",
    categoryName: "Volume",
    unit: "m³",
    name: "Mètre cube",
    symbol: "m³",
    shortDescription: "Le mètre cube est l’unité SI de référence du volume.",
    historySummary: "Le mètre cube découle directement du mètre, l’unité de base de longueur, élevé au cube.",
    measurementSystem: "Système international (SI)",
    siEquivalent: "Unité SI de référence du volume",
    commonUses: "Gaz naturel, béton, grands volumes industriels",
  },
  {
    locale: "fr",
    sourceSlug: "galon",
    slug: "gallon",
    category: "hacim",
    categoryName: "Volume",
    unit: "gal",
    name: "Gallon (US)",
    symbol: "gal",
    shortDescription: "Le gallon américain est l’unité de volume liquide utilisée aux États-Unis, notamment pour l’essence.",
    historySummary: "Le gallon américain (liquide) dérive d’anciennes mesures anglaises et diffère du gallon impérial britannique.",
    measurementSystem: "Système américain (US customary)",
    siEquivalent: "1 gal (US) ≈ 3,785 L",
    commonUses: "Carburant et boissons aux États-Unis",
  },

  // Masse
  {
    locale: "fr",
    sourceSlug: "kilogram",
    slug: "kilogramme",
    category: "kutle",
    categoryName: "Masse",
    unit: "kg",
    name: "Kilogramme",
    symbol: "kg",
    shortDescription: "Le kilogramme est l’unité SI de base de la masse.",
    historySummary: "Depuis 2019, le kilogramme est défini à partir de la constante de Planck, remplaçant l’ancien prototype en métal conservé à Paris.",
    measurementSystem: "Système international (SI)",
    siEquivalent: "Unité SI de base de la masse",
    commonUses: "Poids corporel, expédition, cuisine",
  },
  {
    locale: "fr",
    sourceSlug: "gram",
    slug: "gramme",
    category: "kutle",
    categoryName: "Masse",
    unit: "g",
    name: "Gramme",
    symbol: "g",
    shortDescription: "Le gramme vaut un millième de kilogramme et sert aux petites quantités de matière.",
    historySummary: "Le gramme a été défini à l’origine comme la masse d’un centimètre cube d’eau à 4 °C.",
    measurementSystem: "Système international (SI, sous-multiple)",
    siEquivalent: "1 g = 0,001 kg",
    commonUses: "Cuisine, bijouterie, laboratoire",
  },
  {
    locale: "fr",
    sourceSlug: "miligram",
    slug: "milligramme",
    category: "kutle",
    categoryName: "Masse",
    unit: "mg",
    name: "Milligramme",
    symbol: "mg",
    shortDescription: "Le milligramme vaut un millième de gramme et est principalement utilisé en pharmacie et en chimie.",
    historySummary: "Sous-multiple du gramme, le milligramme est devenu essentiel pour le dosage précis des médicaments.",
    measurementSystem: "Système international (SI, sous-multiple)",
    siEquivalent: "1 mg = 0,001 g",
    commonUses: "Dosage des médicaments et chimie analytique",
  },
  {
    locale: "fr",
    sourceSlug: "ton",
    slug: "tonne",
    category: "kutle",
    categoryName: "Masse",
    unit: "t",
    name: "Tonne",
    symbol: "t",
    shortDescription: "La tonne vaut 1 000 kilogrammes et sert à mesurer de grandes masses.",
    historySummary: "La tonne métrique s’est imposée pour exprimer facilement les grandes masses dans l’industrie et le transport.",
    measurementSystem: "Système métrique (hors SI, multiple)",
    siEquivalent: "1 t = 1000 kg",
    commonUses: "Fret maritime, industrie lourde, agriculture",
  },
  {
    locale: "fr",
    sourceSlug: "pound",
    slug: "livre",
    category: "kutle",
    categoryName: "Masse",
    unit: "lb",
    name: "Livre",
    symbol: "lb",
    shortDescription: "La livre est une unité de masse du système impérial, très utilisée aux États-Unis.",
    historySummary: "La livre avoirdupois moderne a été fixée à exactement 0,453 592 37 kilogramme en 1959.",
    measurementSystem: "Système impérial/américain",
    siEquivalent: "1 lb = 0,45359237 kg",
    commonUses: "Poids corporel et alimentation aux États-Unis",
  },
  {
    locale: "fr",
    sourceSlug: "ons",
    slug: "once",
    category: "kutle",
    categoryName: "Masse",
    unit: "oz",
    name: "Once",
    symbol: "oz",
    shortDescription: "L’once vaut un seizième de livre et sert à mesurer de petites masses dans le système impérial.",
    historySummary: "L’once avoirdupois est utilisée depuis des siècles en Angleterre pour les petites quantités de marchandises.",
    measurementSystem: "Système impérial/américain",
    siEquivalent: "1 oz ≈ 28,3495 g",
    commonUses: "Alimentation et cosmétiques aux États-Unis",
  },

  // Température
  {
    locale: "fr",
    sourceSlug: "santigrat",
    slug: "celsius",
    category: "sicaklik",
    categoryName: "Température",
    unit: "C",
    name: "Celsius",
    symbol: "°C",
    shortDescription: "L’échelle Celsius est utilisée dans la majorité du monde, avec 0 °C pour le point de congélation et 100 °C pour l’ébullition de l’eau.",
    historySummary: "Proposée par l’astronome suédois Anders Celsius en 1742, l’échelle a ensuite été inversée pour prendre sa forme actuelle.",
    measurementSystem: "Système métrique (échelle courante)",
    siEquivalent: "K = °C + 273,15",
    commonUses: "Météorologie, cuisine, sciences dans la majorité du monde",
  },
  {
    locale: "fr",
    sourceSlug: "fahrenhayt",
    slug: "fahrenheit",
    category: "sicaklik",
    categoryName: "Température",
    unit: "F",
    name: "Fahrenheit",
    symbol: "°F",
    shortDescription: "L’échelle Fahrenheit est utilisée principalement aux États-Unis pour la température quotidienne.",
    historySummary: "Proposée en 1724 par le physicien allemand Daniel Gabriel Fahrenheit, initialement basée sur un mélange réfrigérant.",
    measurementSystem: "Système américain (échelle courante)",
    siEquivalent: "°C = (°F − 32) × 5/9",
    commonUses: "Meteorologie et cuisine aux Etats-Unis",
  },
  {
    locale: "fr",
    sourceSlug: "kelvin",
    slug: "kelvin",
    category: "sicaklik",
    categoryName: "Température",
    unit: "K",
    name: "Kelvin",
    symbol: "K",
    shortDescription: "Le kelvin est l’unité SI de base de la température, sans valeurs négatives.",
    historySummary: "Nommé d’après le physicien William Thomson (Lord Kelvin), le kelvin part du zéro absolu, la température la plus basse possible.",
    measurementSystem: "Système international (SI)",
    siEquivalent: "Unité SI de base de la température",
    commonUses: "Recherche scientifique, physique, astronomie",
  },

  // Temps
  {
    locale: "fr",
    sourceSlug: "saniye",
    slug: "seconde",
    category: "zaman",
    categoryName: "Temps",
    unit: "s",
    name: "Seconde",
    symbol: "s",
    shortDescription: "La seconde est l’unité SI de base du temps.",
    historySummary: "Depuis 1967, la seconde est définie à partir de 9 192 631 770 périodes de radiation de l’atome de césium-133.",
    measurementSystem: "Système international (SI)",
    siEquivalent: "Unité SI de base du temps",
    commonUses: "Chronométrage sportif, sciences, informatique",
  },
  {
    locale: "fr",
    sourceSlug: "dakika",
    slug: "minute",
    category: "zaman",
    categoryName: "Temps",
    unit: "min",
    name: "Minute",
    symbol: "min",
    shortDescription: "La minute vaut 60 secondes et est l’unité de temps la plus utilisée au quotidien.",
    historySummary: "La division en 60 unités provient du système sexagésimal babylonien, encore utilisé aujourd’hui.",
    measurementSystem: "Acceptée avec le SI",
    siEquivalent: "1 min = 60 s",
    commonUses: "Emplois du temps, cuisine, sport",
  },
  {
    locale: "fr",
    sourceSlug: "saat",
    slug: "heure",
    category: "zaman",
    categoryName: "Temps",
    unit: "h",
    name: "Heure",
    symbol: "h",
    shortDescription: "L’heure vaut 60 minutes et sert à organiser la journée.",
    historySummary: "La division du jour en 24 heures remonte à l’Égypte antique.",
    measurementSystem: "Acceptée avec le SI",
    siEquivalent: "1 h = 3600 s",
    commonUses: "Temps de travail, temps de trajet, emplois du temps",
  },
  {
    locale: "fr",
    sourceSlug: "gun",
    slug: "jour",
    category: "zaman",
    categoryName: "Temps",
    unit: "day",
    name: "Jour",
    symbol: "j",
    shortDescription: "Le jour correspond à une rotation complète de la Terre sur elle-même, soit 24 heures.",
    historySummary: "La durée du jour est basée sur le cycle jour-nuit observé depuis l’Antiquité.",
    measurementSystem: "Acceptée avec le SI",
    siEquivalent: "1 jour = 86 400 s",
    commonUses: "Calendrier, planification, calcul de durée",
  },

  // Vitesse
  {
    locale: "fr",
    sourceSlug: "kilometre-saat",
    slug: "kilometre-heure",
    category: "hiz",
    categoryName: "Vitesse",
    unit: "km/h",
    name: "Kilomètre par heure",
    symbol: "km/h",
    shortDescription: "Le kilomètre par heure est l’unité standard de vitesse routière dans la plupart des pays.",
    historySummary: "Adoptée avec le système métrique, cette unité est devenue la référence des limitations de vitesse dans le monde entier.",
    measurementSystem: "Système métrique (unité courante)",
    siEquivalent: "1 km/h ≈ 0,278 m/s",
    commonUses: "Vitesse des véhicules, limitations de vitesse",
  },
  {
    locale: "fr",
    sourceSlug: "metre-saniye",
    slug: "metre-seconde",
    category: "hiz",
    categoryName: "Vitesse",
    unit: "m/s",
    name: "Mètre par seconde",
    symbol: "m/s",
    shortDescription: "Le mètre par seconde est l’unité SI de vitesse, utilisée en physique et en météorologie.",
    historySummary: "Unité dérivée directement du mètre et de la seconde, standard dans les calculs scientifiques.",
    measurementSystem: "Système international (SI)",
    siEquivalent: "Unité SI dérivée de la vitesse",
    commonUses: "Vitesse du vent, calculs physiques",
  },
  {
    locale: "fr",
    sourceSlug: "mil-saat",
    slug: "mile-heure",
    category: "hiz",
    categoryName: "Vitesse",
    unit: "mph",
    name: "Mile par heure",
    symbol: "mph",
    shortDescription: "Le mile par heure est l’unité de vitesse routière aux États-Unis et au Royaume-Uni.",
    historySummary: "Dérivée du mile terrestre, cette unité reste la norme des panneaux de signalisation américains et britanniques.",
    measurementSystem: "Système impérial/américain",
    siEquivalent: "1 mph ≈ 0,447 m/s",
    commonUses: "Vitesse des vehicules aux Etats-Unis et au Royaume-Uni",
  },
  {
    locale: "fr",
    sourceSlug: "knot",
    slug: "noeud",
    category: "hiz",
    categoryName: "Vitesse",
    unit: "knot",
    name: "Nœud",
    symbol: "kn",
    shortDescription: "Le nœud (mille marin par heure) est l’unité standard de vitesse en navigation maritime et aérienne.",
    historySummary: "Le nom vient de la méthode historique consistant à compter les nœuds d’une corde jetée à l’eau pour mesurer la vitesse d’un navire.",
    measurementSystem: "Navigation maritime/aérienne",
    siEquivalent: "1 kn ≈ 0,514 m/s",
    commonUses: "Vitesse des navires et des avions",
  },

  // Pression
  {
    locale: "fr",
    sourceSlug: "pascal",
    slug: "pascal",
    category: "basinc",
    categoryName: "Pression",
    unit: "Pa",
    name: "Pascal",
    symbol: "Pa",
    shortDescription: "Le pascal est l’unité SI de pression, égale à un newton par mètre carré.",
    historySummary: "Nommé d’après Blaise Pascal, il a été adopté comme unité SI de pression en 1971.",
    measurementSystem: "Système international (SI)",
    siEquivalent: "1 Pa = 1 N/m²",
    commonUses: "Calculs scientifiques et d’ingénierie",
  },
  {
    locale: "fr",
    sourceSlug: "bar",
    slug: "bar",
    category: "basinc",
    categoryName: "Pression",
    unit: "bar",
    name: "Bar",
    symbol: "bar",
    shortDescription: "Le bar est une unité de pression pratique, proche de la pression atmosphérique moyenne et très utilisée dans l’industrie.",
    historySummary: "Introduit au début du XXe siècle par le météorologue Vilhelm Bjerknes, le bar reste largement utilisé malgré l’adoption du pascal.",
    measurementSystem: "Système métrique (hors SI)",
    siEquivalent: "1 bar = 100 000 Pa",
    commonUses: "Systèmes industriels, compresseurs et météorologie",
  },
  {
    locale: "fr",
    sourceSlug: "psi",
    slug: "psi",
    category: "basinc",
    categoryName: "Pression",
    unit: "psi",
    name: "PSI",
    symbol: "psi",
    shortDescription: "Le PSI (livre-force par pouce carré) est une unité de pression du système impérial, courante pour les pneus.",
    historySummary: "Le PSI s’est imposé avec le système impérial américain, notamment pour la pression des pneus et les systèmes hydrauliques.",
    measurementSystem: "Système impérial/américain",
    siEquivalent: "1 psi ≈ 6894,76 Pa",
    commonUses: "Pression des pneus et systèmes hydrauliques ou pneumatiques",
  },
  {
    locale: "fr",
    sourceSlug: "atmosfer",
    slug: "atmosphere",
    category: "basinc",
    categoryName: "Pression",
    unit: "atm",
    name: "Atmosphère standard",
    symbol: "atm",
    shortDescription: "L’atmosphère standard représente approximativement la pression atmosphérique moyenne au niveau de la mer.",
    historySummary: "Définie à partir des mesures barométriques de Torricelli au XVIIe siècle, elle sert de référence pour les conditions standard.",
    measurementSystem: "Hors SI (unité de référence)",
    siEquivalent: "1 atm = 101 325 Pa",
    commonUses: "Conditions atmosphériques et de référence",
  },

  // Energie
  {
    locale: "fr",
    sourceSlug: "joule",
    slug: "joule",
    category: "enerji",
    categoryName: "Énergie",
    unit: "J",
    name: "Joule",
    symbol: "J",
    shortDescription: "Le joule est l’unité SI d’énergie, égale au travail d’une force d’un newton sur une distance d’un mètre.",
    historySummary: "Nommé d’après le physicien anglais James Prescott Joule, il honore ses travaux sur l’énergie et la chaleur.",
    measurementSystem: "Système international (SI)",
    siEquivalent: "1 J = 1 N·m",
    commonUses: "Calculs scientifiques et physiques d’énergie",
  },
  {
    locale: "fr",
    sourceSlug: "kilovatsaat",
    slug: "kilowattheure",
    category: "enerji",
    categoryName: "Énergie",
    unit: "kWh",
    name: "Kilowattheure",
    symbol: "kWh",
    shortDescription: "Le kilowattheure est l’unité standard de facturation de la consommation électrique dans le monde.",
    historySummary: "Adopté avec la généralisation de l’électricité domestique, le kilowattheure reste l’unité de référence des compteurs électriques.",
    measurementSystem: "Système métrique (électricité)",
    siEquivalent: "1 kWh = 3 600 000 J",
    commonUses: "Facturation électrique",
  },
  {
    locale: "fr",
    sourceSlug: "kalori",
    slug: "calorie",
    category: "enerji",
    categoryName: "Énergie",
    unit: "cal",
    name: "Calorie",
    symbol: "cal",
    shortDescription: "La calorie est l’énergie nécessaire pour élever d’un degré Celsius la température d’un gramme d’eau.",
    historySummary: "Définie au XIXe siècle pour les études thermiques, la calorie est aujourd’hui surtout associée à la nutrition.",
    measurementSystem: "Système métrique (traditionnel)",
    siEquivalent: "1 cal = 4,184 J",
    commonUses: "Nutrition et chimie",
  },
  {
    locale: "fr",
    sourceSlug: "btu",
    slug: "btu",
    category: "enerji",
    categoryName: "Énergie",
    unit: "Btu",
    name: "BTU",
    symbol: "BTU",
    shortDescription: "Le BTU (British Thermal Unit) exprime la capacité des systèmes de chauffage et de climatisation.",
    historySummary: "D’origine britannique, le BTU reste largement utilisé aux États-Unis pour les équipements thermiques.",
    measurementSystem: "Système impérial/américain",
    siEquivalent: "1 Btu ≈ 1055,06 J",
    commonUses: "Climatisation et chauffage",
  },

  // Stockage de données
  {
    locale: "fr",
    sourceSlug: "bayt",
    slug: "octet",
    category: "veri",
    categoryName: "Stockage de données",
    unit: "B",
    name: "Octet",
    symbol: "o",
    shortDescription: "L’octet (8 bits) est l’unité de base utilisée pour représenter les caractères et les données numériques.",
    historySummary: "L’octet s’est imposé avec le développement des premiers ordinateurs comme unité standard de traitement des données.",
    measurementSystem: "Informatique",
    siEquivalent: "1 o = 8 bits",
    commonUses: "Taille des fichiers, mémoire et stockage",
  },
  {
    locale: "fr",
    sourceSlug: "megabayt",
    slug: "megaoctet",
    category: "veri",
    categoryName: "Stockage de données",
    unit: "MB",
    name: "Mégaoctet",
    symbol: "Mo",
    shortDescription: "Le mégaoctet est utilisé pour exprimer la taille de fichiers de volume moyen, comme les photos ou les documents.",
    historySummary: "Avec la croissance des capacités de stockage, le mégaoctet est devenu une unité courante pour les fichiers numériques.",
    measurementSystem: "Informatique (base 1000 ou 1024)",
    siEquivalent: "1 Mo = 1 000 000 o (ou 1024² o en base binaire)",
    commonUses: "Taille des photos, des documents et des applications",
  },
  {
    locale: "fr",
    sourceSlug: "gigabayt",
    slug: "gigaoctet",
    category: "veri",
    categoryName: "Stockage de données",
    unit: "GB",
    name: "Gigaoctet",
    symbol: "Go",
    shortDescription: "Le gigaoctet est une unité courante pour exprimer la capacité de stockage des smartphones et des ordinateurs.",
    historySummary: "Le gigaoctet s’est imposé avec l’essor du stockage numérique de masse, des disques durs aux smartphones.",
    measurementSystem: "Informatique (base 1000 ou 1024)",
    siEquivalent: "1 Go = 1 000 000 000 o (ou 1024³ o en base binaire)",
    commonUses: "Stockage des smartphones, des ordinateurs et des forfaits Internet",
  },

  // Électricité
  {
    locale: "fr",
    sourceSlug: "volt",
    slug: "volt",
    category: "elektrik",
    categoryName: "Électricité",
    unit: "V",
    name: "Volt",
    symbol: "V",
    shortDescription: "Le volt est l’unité SI de différence de potentiel électrique.",
    historySummary: "Nommé d’après le physicien italien Alessandro Volta, inventeur de la première pile électrique.",
    measurementSystem: "Système international (SI)",
    siEquivalent: "Unité SI de tension électrique",
    commonUses: "Piles, prises électriques et circuits électroniques",
  },
  {
    locale: "fr",
    sourceSlug: "amper",
    slug: "ampere",
    category: "elektrik",
    categoryName: "Électricité",
    unit: "A",
    name: "Ampère",
    symbol: "A",
    shortDescription: "L’ampère est l’unité SI de base du courant électrique.",
    historySummary: "Nommé d’après le physicien français André-Marie Ampère, pionnier de l’électromagnétisme.",
    measurementSystem: "Système international (SI)",
    siEquivalent: "Unité SI de base du courant électrique",
    commonUses: "Circuits électriques, disjoncteurs et chargeurs",
  },
  {
    locale: "fr",
    sourceSlug: "miliamper",
    slug: "milliampere",
    category: "elektrik",
    categoryName: "Électricité",
    unit: "mA",
    name: "Milliampère",
    symbol: "mA",
    shortDescription: "Le milliampère vaut un millième d’ampère et sert à mesurer les faibles courants en électronique.",
    historySummary: "Sous-multiple de l’ampère, le milliampère est devenu essentiel avec le développement de l’électronique de précision.",
    measurementSystem: "Système international (SI, sous-multiple)",
    siEquivalent: "1 mA = 0,001 A",
    commonUses: "Batteries de smartphones, capteurs et circuits électroniques",
  },

  // Carat d’or
  {
    locale: "fr",
    sourceSlug: "24-ayar-altin",
    slug: "or-24-carats",
    category: "altin_ayar",
    categoryName: "Carat d’or",
    unit: "24K",
    name: "Or 24 carats",
    symbol: "24k",
    shortDescription: "L’or 24 carats est de l’or pur à 99,9 %, la référence du système des carats.",
    historySummary: "L’or 24 carats est traditionnellement utilisé pour les lingots d’investissement en raison de sa pureté maximale.",
    measurementSystem: "Système des carats",
    siEquivalent: "99,9 % d’or pur",
    commonUses: "Lingots et investissement dans l’or",
  },
  {
    locale: "fr",
    sourceSlug: "22-ayar-altin",
    slug: "or-22-carats",
    category: "altin_ayar",
    categoryName: "Carat d’or",
    unit: "22K",
    name: "Or 22 carats",
    symbol: "22k",
    shortDescription: "L’or 22 carats contient environ 91,6 % d’or pur et est très utilisé en bijouterie traditionnelle.",
    historySummary: "Très utilisé en Asie du Sud et au Moyen-Orient, il équilibre pureté et résistance pour la fabrication de bijoux.",
    measurementSystem: "Système des carats",
    siEquivalent: "≈91,6 % d’or pur",
    commonUses: "Bijouterie traditionnelle",
  },
  {
    locale: "fr",
    sourceSlug: "18-ayar-altin",
    slug: "or-18-carats",
    category: "altin_ayar",
    categoryName: "Carat d’or",
    unit: "18K",
    name: "Or 18 carats",
    symbol: "18k",
    shortDescription: "L’or 18 carats contient 75 % d’or pur et est le titre le plus courant dans la bijouterie occidentale.",
    historySummary: "Son bon compromis entre dureté et pureté en fait une référence des bijouteries en Europe et en Amérique.",
    measurementSystem: "Système des carats",
    siEquivalent: "75 % d’or pur",
    commonUses: "Bijouterie occidentale et bagues de mariage",
  },

  // Titre d’argent
  {
    locale: "fr",
    sourceSlug: "999-ayar-gumus",
    slug: "argent-999",
    category: "gumus_ayar",
    categoryName: "Titre d’argent",
    unit: "999",
    name: "Argent 999 (fin)",
    symbol: "999",
    shortDescription: "L’argent 999 est de l’argent pur à 99,9 %, principalement utilisé pour les lingots d’investissement.",
    historySummary: "Sa pureté maximale en fait la référence privilégiée des produits d’investissement et des lingots d’argent.",
    measurementSystem: "Système des millièmes",
    siEquivalent: "99,9 % d’argent pur",
    commonUses: "Lingots et argent d’investissement",
  },
  {
    locale: "fr",
    sourceSlug: "925-ayar-gumus",
    slug: "argent-sterling-925",
    category: "gumus_ayar",
    categoryName: "Titre d’argent",
    unit: "925",
    name: "Argent sterling (925)",
    symbol: "925",
    shortDescription: "L’argent sterling contient 92,5 % d’argent pur et constitue le standard mondial de la bijouterie en argent.",
    historySummary: "Le standard de l’argent sterling remonte à l’Angleterre du XIIe siècle et reste la norme la plus reconnue au monde.",
    measurementSystem: "Système des millièmes",
    siEquivalent: "92,5 % d’argent pur",
    commonUses: "Bijouterie et orfèvrerie de table",
  },

];

export function findFrenchUnitPageBySourceSlug(sourceSlug: string) {
  return frenchUnitPages.find((page) => page.sourceSlug === sourceSlug);
}

export function findFrenchUnitPage(category: string, unit: string) {
  return frenchUnitPages.find(
    (page) => page.category === category && page.unit === unit
  );
}
