// Norske enhetssider -- integrert i det nye i18n-systemet.
// Frittstaende, ny fil (endrer ingen eksisterende tr/en/de/ar/uz/bn/fr/es/pt/it/nl/sv-filer).
// Innholdet er oversatt direkte fra den tyrkiske kilden
// (app/converter/unitPages.ts, unitDescriptions-tabellen), ikke fra et
// mellomsprak, for a bevare samme dybde og faktainnhold som flaggskipet.
// Omfanget er bevisst begrenset til de 13 karnekategoriene som, sammen med
// de 4 universelle verktoyene (forsiden), utgjor de 17 elementene som
// definerer sidens identitet.

export type LocalizedNorwegianUnitPage = {
  locale: "no";
  sourceSlug: string;
  slug: string;
  category: string;
  categoryName: string;
  unit: string;
  name: string;
  symbol: string;
  shortDescription: string;
  historySummary: string;
  measurementSystem: string;
  siEquivalent: string;
  commonUses: string;
};

export const norwegianUnitPages: LocalizedNorwegianUnitPage[] = [
  // Lengde
  {
    locale: "no",
    sourceSlug: "metre",
    slug: "meter",
    category: "uzunluk",
    categoryName: "Lengde",
    unit: "m",
    name: "Meter",
    symbol: "m",
    shortDescription: "Meter er grunnenheten for lengde i Det internasjonale enhetssystemet. Den brukes til å måle avstand og størrelse, fra dagliglivet til ingeniørfag.",
    historySummary: "Meteren oppsto under den franske revolusjonen, med mål om å erstatte måleenhetene som frem til da varierte fra region til region, med en enkelt universell og naturbasert standard. Man vurderte først en definisjon basert på svingningstiden til en pendel, men denne ideen ble forkastet da man innså at en pendel påvirkes av lokal tyngdekraft. I stedet definerte den franske nasjonalforsamlingen i 1791 meteren som en titimillionte del av avstanden fra Nordpolen til ekvator langs meridianen gjennom Paris -- en avstand beregnet gjennom flerårige geodetiske målinger utført av Delambre og Mechain. I 1799 ble definisjonen basert på en platinastav kalt 'Metre des Archives'; i 1889 ble denne staven erstattet av en ny standard i platina-iridiumlegering, med 29 kopier utplassert over hele verden. I 1960 ble meteren ikke lenger definert ut fra et fysisk objekt, men ut fra bølgelengden til lyset som sendes ut av et krypton-86-atom. Siden 1983 er meteren definert som strekningen lyset tilbakelegger i vakuum på 1/299 792 458 sekund -- dette gjør at meteren kan reproduseres med ekstremt høy presisjon i hvilket som helst laboratorium i verden, uten å trenge en fysisk prototype.",
    measurementSystem: "Det internasjonale enhetssystemet (SI)",
    siEquivalent: "SIs grunnleggende lengdeenhet",
    commonUses: "Bygg, vitenskap, produksjon, geometri og generell måling",
  },
  {
    locale: "no",
    sourceSlug: "kilometre",
    slug: "kilometer",
    category: "uzunluk",
    categoryName: "Lengde",
    unit: "km",
    name: "Kilometer",
    symbol: "km",
    shortDescription: "Kilometer er en lengdeenhet lik 1000 meter. Den brukes til å uttrykke avstander mellom byer og geografiske avstander.",
    historySummary: "Kilometeren etablerte seg som et multiplum av meteren innenfor det metriske systemets desimale struktur. Den ble en standard betegnelse for veier og kartmålestokker.",
    measurementSystem: "Det internasjonale enhetssystemet (SI, multiplum)",
    siEquivalent: "1 km = 1000 m",
    commonUses: "Veiavstander, geografi, kartografi og infrastruktur",
  },
  {
    locale: "no",
    sourceSlug: "santimetre",
    slug: "centimeter",
    category: "uzunluk",
    categoryName: "Lengde",
    unit: "cm",
    name: "Centimeter",
    symbol: "cm",
    shortDescription: "Centimeter er en lengdeenhet lik en hundredel av en meter. Den er vanlig for å uttrykke små gjenstander og hverdagsmal.",
    historySummary: "Centimeteren utviklet seg som en desimal delenhet i det metriske systemet. Den fikk bred bruk fordi den gjorde målinger praktiske og raske å beregne.",
    measurementSystem: "Det internasjonale enhetssystemet (SI, delenhet)",
    siEquivalent: "1 cm = 0,01 m",
    commonUses: "Møbler, tekstil, antropometri og hverdagslige målinger",
  },
  {
    locale: "no",
    sourceSlug: "milimetre",
    slug: "millimeter",
    category: "uzunluk",
    categoryName: "Lengde",
    unit: "mm",
    name: "Millimeter",
    symbol: "mm",
    shortDescription: "Millimeter er en lengdeenhet lik en tusendel av en meter. Den brukes ofte i presise tekniske målinger.",
    historySummary: "Millimeteren ble utbredt etter hvert som industri og ingeniørfag fikk behov for å måle mindre toleranser. Den ble en grunnleggende delenhet, særlig i produksjons- og tegningsstandarder.",
    measurementSystem: "Det internasjonale enhetssystemet (SI, delenhet)",
    siEquivalent: "1 mm = 0,001 m",
    commonUses: "Mekanisk produksjon, tekniske tegninger, bearbeidingstoleranser",
  },
  {
    locale: "no",
    sourceSlug: "fit",
    slug: "fot",
    category: "uzunluk",
    categoryName: "Lengde",
    unit: "ft",
    name: "Fot",
    symbol: "ft",
    shortDescription: "Fot er en lengdeenhet brukt i det britiske og amerikanske målesystemet. En internasjonal fot tilsvarer nøyaktig 0,3048 meter.",
    historySummary: "Fot (foot) var, som navnet tilsier, historisk et omtrentlig mål basert på lengden av en menneskefot, og siden den romerske enheten 'pes' har titalls ulike 'fot'-definisjoner variert mellom 250 og 335 mm avhengig av region og tidsperiode. Foten som etter hvert ble stabil i England, ble endelig fastsatt til nøyaktig 0,3048 meter (altså nøyaktig 12 tommer) gjennom en internasjonal avtale i 1959 (samme år som tomme og engelsk mil også ble fastsatt) mellom USA, Storbritannia og samveldelandene.",
    measurementSystem: "Britisk og amerikansk målesystem",
    siEquivalent: "1 ft = 0,3048 m",
    commonUses: "Arkitektur, byggehøyder, luftfart og feltmålinger",
  },
  {
    locale: "no",
    sourceSlug: "inc",
    slug: "tomme",
    category: "uzunluk",
    categoryName: "Lengde",
    unit: "in",
    name: "Tomme",
    symbol: "in",
    shortDescription: "Tomme er en kort lengdeenhet brukt i det britiske og amerikanske målesystemet. En tomme tilsvarer nøyaktig 2,54 centimeter.",
    historySummary: "Ordet 'inch' stammer fra det latinske 'uncia', som betyr 'en tolvtedel'. Den eldste definisjonen ble gitt i 1324 av kong Edward II av England, som 'tre byggkorn lagt ende mot ende', og denne definisjonen ble brukt i århundrer. Det fortelles også at kong David I av Skottland (1100-tallet) definerte tommen som bredden ved neglebunnen på en manns tommel. Et vendepunkt kom i 1896 da den svenske ingeniøren Carl Edvard Johansson, ved produksjon av presisjonsmåleklosser, i praksis fastsatte tommen til nøyaktig 25,4 mm -- denne 'industrielle tommen' ble tatt i bruk av britiske standardorganer i 1930 og amerikanske i 1933. Den endelige internasjonale avtalen trådte i kraft i 1959 (1. juli i USA), og siden den gang er tommen definert som nøyaktig 25,4 millimeter.",
    measurementSystem: "Britisk og amerikansk målesystem",
    siEquivalent: "1 in = 25,4 mm = 2,54 cm",
    commonUses: "Skjermstørrelser, rørlegging, festeelementer og tekniske kataloger",
  },
  {
    locale: "no",
    sourceSlug: "yarda",
    slug: "yard",
    category: "uzunluk",
    categoryName: "Lengde",
    unit: "yd",
    name: "Yard",
    symbol: "yd",
    shortDescription: "Yard er en lengdeenhet brukt i det britiske og amerikanske målesystemet. En yard tilsvarer nøyaktig 0,9144 meter.",
    historySummary: "Opphavet til yarden er ikke helt klarlagt, men ifølge en utbredt fortelling definerte kong Henrik I av England på 1100-tallet yarden som avstanden fra hans egen nesetipp til tommelen på den utstrakte armen. En mer veldokumentert utvikling er at offisielle 'yardstenger' i bronse ble produsert som standardreferanse ved det britiske finansdepartementet på 1500-tallet. I likhet med fot og tomme ble også yarden endelig fastsatt til nøyaktig 0,9144 meter (3 fot) gjennom den internasjonale avtalen i 1959.",
    measurementSystem: "Britisk og amerikansk målesystem",
    siEquivalent: "1 yd = 0,9144 m",
    commonUses: "Idrettsbaner, tekstil, landskapsarbeid og feltplanlegging",
  },
  {
    locale: "no",
    sourceSlug: "mil",
    slug: "engelsk-mil",
    category: "uzunluk",
    categoryName: "Lengde",
    unit: "mi",
    name: "Engelsk mil",
    symbol: "mi",
    shortDescription: "Engelsk mil er en lengdeenhet brukt særlig i USA og Storbritannia. En internasjonal mil tilsvarer 1609,344 meter.",
    historySummary: "Ordet 'mile' kommer fra det latinske uttrykket 'mille passus' (tusen skritt) -- et 'skritt' ble regnet som avstanden mellom to nedtramp av samme fot. Den romerske milen ble indirekte fastsatt da Marcus Agrippa definerte en standard romersk fot i 29 f.Kr. (1 skritt = 5 romerske fot, 1 mil = 5000 romerske fot ≈ 1479 meter). I middelalderens England var den 'gamle engelske milen' et upresist mål på om lag 2,1 km som varierte fra region til region. Det avgjørende vendepunktet kom i 1593: en parlamentslov om vekt og mål under dronning Elisabeth I beholdt den tradisjonelle milestrukturen på 8 furlong, men økte antall fot slik at milen ble fastsatt til nøyaktig 5280 fot (1760 yard) -- denne definisjonen spredte seg gjennom det britiske imperiet og dannet grunnlaget for dagens internasjonale mil. Den moderne internasjonale milen ble endelig fastsatt til nøyaktig 1609,344 meter i 1959.",
    measurementSystem: "Britisk og amerikansk målesystem",
    siEquivalent: "1 mi = 1609,344 m",
    commonUses: "Veiavstander, navigasjon og feltmålestokker",
  },
  {
    locale: "no",
    sourceSlug: "skandinavisk-mil",
    slug: "mil",
    category: "uzunluk",
    categoryName: "Lengde",
    unit: "mil",
    name: "Mil",
    symbol: "mil",
    shortDescription: "En mil er en norsk lengdeenhet som i dag tilsvarer nøyaktig 10 kilometer (10 000 meter). Den brukes i dagligtalen i Norge og Sverige for å angi avstander og drivstofforbruk (liter per mil).",
    historySummary: "Den gamle norske milen var lengre, omtrent 11,3 km. Etter overgangen til det metriske systemet ble milen i dagligtalen satt til nøyaktig 10 km, og det er denne milen som brukes i dag. En norsk mil må ikke forveksles med den engelske milen (1,609 km) eller nautisk mil (1,852 km).",
    measurementSystem: "Metrisk (norsk dagligtale, ikke SI)",
    siEquivalent: "1 mil = 10 000 m = 10 km",
    commonUses: "Avstander i dagligtale, reiseplanlegging og drivstofforbruk (liter per mil)",
  },
  // Areal
  {
    locale: "no",
    sourceSlug: "metrekare",
    slug: "kvadratmeter",
    category: "alan",
    categoryName: "Areal",
    unit: "m²",
    name: "Kvadratmeter",
    symbol: "m²",
    shortDescription: "Kvadratmeter er SIs avledede enhet for areal. Den brukes som grunnleggende referanse i beregning av gulv, tverrsnitt og overflater.",
    historySummary: "Kvadratmeteren etablerte seg i det metriske systemet som den todimensjonale utvidelsen av meteren. Den ble et standard arealspråk i bygg-, tomte- og ingeniørtegninger.",
    measurementSystem: "Det internasjonale enhetssystemet (SI)",
    siEquivalent: "SIs grunnleggende arealenhet",
    commonUses: "Arkitektur, interiør, panelflater og tverrsnittsareal",
  },
  {
    locale: "no",
    sourceSlug: "hektar",
    slug: "hektar",
    category: "alan",
    categoryName: "Areal",
    unit: "ha",
    name: "Hektar",
    symbol: "ha",
    shortDescription: "Hektar er en stor arealenhet brukt særlig ved eiendomsmåling. 1 hektar tilsvarer nøyaktig 10 000 kvadratmeter.",
    historySummary: "Hektaren ble, som en del av det metriske systemet innført av den franske revolusjonen, i 1795 definert som 100 ganger enheten 'ar' (100 m²) og fikk navnet sitt fra prefikset 'hekto-' (hundre). Fordi den viste seg langt mer praktisk enn år for å uttrykke store jordbruks- og skogsarealer, ble den etter hvert den globale standardenheten for arealmåling. Som en intuitiv sammenligning: en standard fotballbane er om lag 0,7 hektar stor -- noe som gjør hektaren lett å forstå i dagliglivet.",
    measurementSystem: "Metrisk system, kompatibelt med SI",
    siEquivalent: "1 ha = 10 000 m²",
    commonUses: "Jordbruksarealer, reguleringsplaner og store tomteregistre",
  },
  {
    locale: "no",
    sourceSlug: "akre",
    slug: "acre",
    category: "alan",
    categoryName: "Areal",
    unit: "ac",
    name: "Acre",
    symbol: "ac",
    shortDescription: "Acre er en stor arealenhet brukt særlig i det britiske og amerikanske målesystemet ved eiendomsmåling. Den tilsvarer 4046,8564224 kvadratmeter.",
    historySummary: "Acre har historisk utviklet seg fra en tilnærming basert på størrelsen på jordet et par okser kunne pluye på en dag, og brukes fortsatt som standard arealenhet i det britiske målesystemet.",
    measurementSystem: "Britisk og amerikansk målesystem",
    siEquivalent: "1 acre = 4046,8564224 m²",
    commonUses: "Kjøp og salg av eiendom og jord, måling av jordbruksareal og eiendomsannonser",
  },
  // Volum
  {
    locale: "no",
    sourceSlug: "litre",
    slug: "liter",
    category: "hacim",
    categoryName: "Volum",
    unit: "L",
    name: "Liter",
    symbol: "L",
    shortDescription: "Liter er en svært utbredt volumenhet for å uttrykke væsker og kapasiteter. 1 liter tilsvarer 0,001 kubikkmeter.",
    historySummary: "Liter ble i 1795 i Frankrike definert som 'en kubikk desimeter', som en del av det nye målesystemet innført av den franske revolusjonen. I 1901 definerte Generalkonferansen for mål og vekt liter på nytt som 'volumet til 1 kg rent vann ved sin tetthetsmaksimum-temperatur (3,98 °C) ved 1 atmosfæres trykk' -- men denne definisjonen gjorde liter noe større (om lag 1,000028 ganger) enn en kubikk desimeter, fordi platina-iridium-kilogramprototypen som ble brukt som referanse, viste seg å være 28 deler per million større enn forventet. Dette 63 år lange avviket ble rettet opp i 1964, da Generalkonferansen igjen definerte liter direkte knyttet til meteren, som nøyaktig 'en kubikk desimeter'.",
    measurementSystem: "Metrisk system, kompatibelt med SI",
    siEquivalent: "1 L = 0,001 m³",
    commonUses: "Væsker, tankvolum, laboratoriebeholdere og hverdagslige mål",
  },
  {
    locale: "no",
    sourceSlug: "mililitre",
    slug: "milliliter",
    category: "hacim",
    categoryName: "Volum",
    unit: "mL",
    name: "Milliliter",
    symbol: "mL",
    shortDescription: "Milliliter er en liten volumenhet lik en tusendel av en liter. Den brukes til presise væskemålinger.",
    historySummary: "Milliliter ble utbredt for å uttrykke små volumer pålitelig innen medisin, laboratorium og kjøkkenmål.",
    measurementSystem: "Metrisk system, kompatibelt med SI",
    siEquivalent: "1 mL = 0,000001 m³",
    commonUses: "Medisindoser, laboratorieprøver og små væskevolumer",
  },
  {
    locale: "no",
    sourceSlug: "metrekup",
    slug: "kubikkmeter",
    category: "hacim",
    categoryName: "Volum",
    unit: "m³",
    name: "Kubikkmeter",
    symbol: "m³",
    shortDescription: "Kubikkmeter er SIs avledede enhet for volum. Den er grunnreferansen for store volumer og tekniske kapasiteter.",
    historySummary: "Kubikkmeteren defineres som det indre volumet til en kube der hver side er nøyaktig 1 meter, og fremkommer direkte ved å utvide meteren til tre dimensjoner. Fordi den tilsvarer 1000 liter (1 m³ = 1000 L), brukes den verden over som standardenhet ved fakturering av naturgass- og vannforbruk -- også i Norge vises forbruk på naturgass- og vannregninger i kubikkmeter. Innen byggebransjen uttrykkes også betong- og masseflyttingsmengder, og i industrien tank- og lagerkapasiteter, ofte i denne enheten.",
    measurementSystem: "Det internasjonale enhetssystemet (SI)",
    siEquivalent: "SIs grunnleggende volumenhet",
    commonUses: "Lagringsvolum, bygningsvolum, prosesstanker og strømningsberegninger",
  },
  {
    locale: "no",
    sourceSlug: "galon",
    slug: "gallon",
    category: "hacim",
    categoryName: "Volum",
    unit: "gal",
    name: "Gallon",
    symbol: "gal",
    shortDescription: "Gallon er en enhet brukt særlig i USA for å måle væskevolum. En amerikansk gallon tilsvarer 3,78541 liter.",
    historySummary: "Gallonen som brukes i USA, bygger på 'vingallon'-tradisjonen fra middelalderens engelske handel, og ble endelig fastsatt til nøyaktig 231 kubikktommer (3,785411784 L) under dronning Anne i 1706 -- USA tok offisielt i bruk denne definisjonen i 1836. Storbritannia gikk derimot en helt annen vei i 1824 og definerte på nytt sin egen 'britiske gallon' (imperial gallon) som 'volumet tilsvarende vekten av 10 pund destillert vann' (om lag 4,546 L), og opphevet samtidig alle andre gallondefinisjoner. På grunn av disse ulike opprinnelsesvalgene er den britiske gallonen om lag 20 % større enn den amerikanske.",
    measurementSystem: "Amerikansk målesystem (US liquid gallon)",
    siEquivalent: "1 gallon (US) = 3,78541 L = 0,00378541 m³",
    commonUses: "Drivstofforbruk, amerikanske væskeproduktetiketter og kjøkkenmål",
  },
  // Masse
  {
    locale: "no",
    sourceSlug: "kilogram",
    slug: "kilogram",
    category: "kutle",
    categoryName: "Masse",
    unit: "kg",
    name: "Kilogram",
    symbol: "kg",
    shortDescription: "Kilogram er SI-grunnenheten for masse. Den brukes mye innen handel, laboratorium og ingeniørfag.",
    historySummary: "Opprinnelsen til kilogrammet går også tilbake til den franske revolusjonen: i 1795 ble gram definert som massen til 1 kubikkcentimeter vann ved isens smeltepunkt (0 °C) -- altså tilsvarte 1 kilogram 1 liter vann under disse forholdene. Men da man oppdaget at vannets tetthet endrer seg med temperaturen, ble det i 1799 laget en platinaprototype kalt 'Kilogramme des Archives'; denne gangen var referansen massen til 1 kubikk desimeter vann ved om lag 4 °C, der vannet er tettest. I 1889 ble denne prototypen erstattet av en ny sylinder i platina-iridiumlegering kjent som 'Le Grand K', og denne ble oppbevart som verdens referansekilogram ved Det internasjonale byrå for mål og vekt i Frankrike i 130 år. Etter hvert ble det oppdaget at denne sylinderen hadde avveket om lag 50 mikrogram fra kopiene laget på samme tid -- en uunngåelig svakhet ved å basere seg på et fysisk objekt. Den 16. november 2018 vedtok Generalkonferansen for mål og vekt å innføre en ny definisjon av kilogrammet basert på Plancks konstant; denne nye definisjonen trådte i kraft 20. mai 2019, og kilogrammet kan nå reproduseres i hvilket som helst laboratorium i verden uten å trenge en fysisk prototype.",
    measurementSystem: "Det internasjonale enhetssystemet (SI)",
    siEquivalent: "SIs grunnleggende masseenhet",
    commonUses: "Handel, transport, laboratorium og prosessberegninger",
  },
  {
    locale: "no",
    sourceSlug: "gram",
    slug: "gram",
    category: "kutle",
    categoryName: "Masse",
    unit: "g",
    name: "Gram",
    symbol: "g",
    shortDescription: "Gram er en masseenhet lik en tusendel av et kilogram. Den brukes til å uttrykke mat, laboratorie- og små stoffmengder.",
    historySummary: "Gram var den opprinnelige grunnleggende masseenheten i den første definisjonen av det franske metriske systemet i 1795, og ble definert som massen til 1 kubikkcentimeter vann ved isens smeltepunkt. Men fordi det i praksis var vanskelig å omdanne en så liten masse til en presis og reproduserbar standardprototype, ble kilogrammet -- 1000 ganger større (massen til 1 kubikk desimeter vann) -- valgt som referanseprototype i 1799. Dette historiske valget førte til at kilogram er det eneste av SIs sju grunnenheter som har et prefiks ('kilo-') i navnet -- mens gram, til tross for å være hovedenheten navnet er avledet fra, i dag står som en sekundær enhet definert som en delenhet av kilogrammet.",
    measurementSystem: "Det internasjonale enhetssystemet (SI, delenhet)",
    siEquivalent: "1 g = 0,001 kg",
    commonUses: "Mat, kjemi, farmasi og presisjonsmåling",
  },
  {
    locale: "no",
    sourceSlug: "miligram",
    slug: "milligram",
    category: "kutle",
    categoryName: "Masse",
    unit: "mg",
    name: "Milligram",
    symbol: "mg",
    shortDescription: "Milligram er en svært liten masseenhet lik en tusendel av et gram. Den har kritisk betydning i medisin- og laboratoriemålinger.",
    historySummary: "Milligrammet fikk økt betydning særlig innen helse og kjemi etter hvert som presisjonsvekter og analytiske laboratorier ble utviklet.",
    measurementSystem: "Det internasjonale enhetssystemet (SI, delenhet)",
    siEquivalent: "1 mg = 0,000001 kg",
    commonUses: "Medisindoser, analyser og presise formuleringer",
  },
  {
    locale: "no",
    sourceSlug: "ton",
    slug: "tonn",
    category: "kutle",
    categoryName: "Masse",
    unit: "t",
    name: "Tonn",
    symbol: "t",
    shortDescription: "Metrisk tonn er en stor masseenhet lik 1000 kilogram. Den brukes til å uttrykke tunge laster og industrielle mengder.",
    historySummary: "Ordet 'tonn' stammer fra det middelalderengelske ordet 'tun', som betyr en stor vintønne; fordi en fylt tønne veide omtrent en 'long ton', begynte ordet også å brukes som masseenhet. I dag kan tre ulike 'tonn'-definisjoner skape forvirring: det metriske tonnet (nøyaktig 1000 kg, standard i verden og i Norge), det amerikanske 'short ton' (2000 pund ≈ 907,18 kg), og det historisk britiske 'long ton' (2240 pund ≈ 1016,05 kg). Selv om forskjellen mellom disse tre verdiene kan virke liten, er det viktig å tydelig angi hvilken 'tonn'-definisjon som brukes i internasjonale handels- og logistikkavtaler.",
    measurementSystem: "Metrisk system, kompatibelt med SI",
    siEquivalent: "1 t = 1000 kg",
    commonUses: "Logistikk, produksjon, råvarehandel og tungindustri",
  },
  {
    locale: "no",
    sourceSlug: "pound",
    slug: "pund",
    category: "kutle",
    categoryName: "Masse",
    unit: "lb",
    name: "Pund",
    symbol: "lb",
    shortDescription: "Pund er en masseenhet brukt i det britiske og amerikanske målesystemet. Et internasjonalt pund tilsvarer nøyaktig 0,45359237 kilogram.",
    historySummary: "Pund stammer fra den romerske enheten 'libra' (om lag 328,9 gram, delt i 12 'uncia') -- forkortelsen 'lb' kommer direkte herfra; selve ordet 'pound' kommer fra uttrykket 'libra pondo' (vekt målt med libra). For den normanniske erobringen (1066) brukte England det 'saksiske pundet', definert ut fra sølv under kong Offa (757-796), der 1 pund sølv gå 240 penny. Rundt 1300 ble 'avoirdupois-pundet', som ble utbredt i handel, opprinnelig fastsatt til 6992 troy grain, men ble under dronning Elisabeth I fastsatt til nøyaktig 7000 troy grain (delt i 16 ounce). Med veiloven av 1878 ble en platinasylinder erklært offisiell standardprototype. Den endelige internasjonale avtalen ble signert 1. juli 1959: pundet regnes nå som nøyaktig 0,45359237 kilogram; Storbritannia tok offisielt i bruk denne definisjonen gjennom loven av 1963.",
    measurementSystem: "Britisk og amerikansk målesystem",
    siEquivalent: "1 lb = 0,45359237 kg",
    commonUses: "Detaljhandel, transport, ernæring og industrikataloger",
  },
  {
    locale: "no",
    sourceSlug: "ons",
    slug: "ounce",
    category: "kutle",
    categoryName: "Masse",
    unit: "oz",
    name: "Ounce",
    symbol: "oz",
    shortDescription: "Ounce er en liten masseenhet brukt i det britiske og amerikanske målesystemet. En avoirdupois-ounce tilsvarer 28,349523125 gram.",
    historySummary: "Ordet 'ounce' stammer fra den romerske enheten 'uncia', som delte 'libra' (forløperen til pundet) i tolv like deler. Ounce brukt i dagliglivet, avoirdupois-ounce (28,349523125 g), tilsvarer 1/16 av et pund; men troy-ounce, brukt i edelmetallhandel, er annerledes og tyngre (31,1034768 g) -- derfor tilsvarer 'pris per ounce' oppgitt for gull/sølv en enhet som er om lag 10 % tyngre enn ouncen man møter i dagligvarehandelen. Troy-ounce har navnet sitt fra Troyes, en viktig handelsbyen i middelalderens Frankrike.",
    measurementSystem: "Britisk og amerikansk målesystem",
    siEquivalent: "1 oz = 28,349523125 g",
    commonUses: "Emballasje, mat og andre lette kommersielle mål enn smykker",
  },
  // Temperatur
  {
    locale: "no",
    sourceSlug: "santigrat",
    slug: "celsius",
    category: "sicaklik",
    categoryName: "Temperatur",
    unit: "°C",
    name: "Celsius",
    symbol: "°C",
    shortDescription: "Celsius-skalaen er en av de mest brukte temperaturvisningene i dagliglivet og ingeniørfag.",
    historySummary: "Celsius-skalaen ble oppfunnet i 1742 av den svenske astronomen Anders Celsius -- men interessant nok var hans opprinnelige skala det motsatte av dagens: 0 grader representerte vannets kokepunkt, og 100 grader frysepunktet. Skalaen ble snudd i 1743 av den franske fysikeren Jean-Pierre Christin (i utformingen av 'Lyon-termometeret') til dagens ordning med 0 °C for frysing og 100 °C for koking; den svenske botanikeren Carl Linnaeus gjorde også den samme ombyttingen uavhengig i 1744 for sitt eget veksthustermometer. Skalaen ble lenge kalt 'centigrade'; i 1948 endret Den internasjonale komiteen for mål og vekt offisielt navnet til 'grad Celsius', både for å hedre Celsius og for å unngå at ordet 'centigrade' i enkelte språk ble forvekslet med en hundredel av en vinkelenhet.",
    measurementSystem: "Temperaturskala brukt sammen med SI",
    siEquivalent: "Ved temperaturforskjell: 1 °C = 1 K",
    commonUses: "Vær, HVAC, prosessovervåking og daglige temperaturverdier",
  },
  {
    locale: "no",
    sourceSlug: "fahrenhayt",
    slug: "fahrenheit",
    category: "sicaklik",
    categoryName: "Temperatur",
    unit: "°F",
    name: "Fahrenheit",
    symbol: "°F",
    shortDescription: "Fahrenheit er en temperaturskala som særlig er utbredt i USA.",
    historySummary: "Fahrenheit-skalaen ble utviklet i 1724 av den polskfødte, nederlandske fysikeren Daniel Gabriel Fahrenheit. Han satte nullpunktet til den kaldeste temperaturen der en blanding av is, vann og ammoniumklorid (eller sjøsalt) stabiliserte seg; 32 grader tilsvarte rent vanns frysepunkt, og 96 grader (etter hans egen måling) menneskekroppens temperatur. Fahrenheit hadde tatt verdiene fra den tidligere Romer-skalaen og multiplisert dem med 4 for å få en finere, brøkfri inndeling. I 1776-77 standardiserte en komité i Royal Society, ledet av Henry Cavendish, skalaen; vannets frysepunkt ble fastsatt til nøyaktig 32 °F og kokepunktet til nøyaktig 212 °F -- denne korreksjonen førte også til at normal kroppstemperatur endte på dagens kjente 98,6 °F.",
    measurementSystem: "Britisk og amerikansk måletradisjon",
    siEquivalent: "Ved temperaturforskjell: 1 °F = 5/9 K",
    commonUses: "Amerikanske værdata, innetemperaturer og enkelte tekniske kataloger",
  },
  {
    locale: "no",
    sourceSlug: "kelvin",
    slug: "kelvin",
    category: "sicaklik",
    categoryName: "Temperatur",
    unit: "K",
    name: "Kelvin",
    symbol: "K",
    shortDescription: "Kelvin er SI-grunnenheten for temperatur og representerer den absolutte temperaturskalaen.",
    historySummary: "Grunnlaget for Kelvin-skalaen ble lagt i 1848 av den skotske fysikeren William Thomson (senere Lord Kelvin); i artikkelen 'On an Absolute Thermometric Scale' beregnet han, ved å bruke den termiske ekspansjonskoeffisienten til ideelle gasser, at det absolutte nullpunktet lag på om lag -273 °C -- overraskende nær dagens verdi på -273,15 °C. I 1854 samarbeidet han med James Prescott Joule for å gjøre skalaen mer praktisk og kompatibel med lufttermometre. Enheten ble formalisert i 1954 ved den 10. Generalkonferansen for mål og vekt, da vannets trippelpunkt ble definert til nøyaktig 273,16 K; i 1967/68 gå den 13. konferansen enheten navnet 'kelvin'. I 2019 ble definisjonen endret enda mer fundamentalt: kelvin bygger nå ikke lenger på vannets trippelpunkt, men direkte på Boltzmann-konstanten (fastsatt til 1,380649×10⁻²³ J/K).",
    measurementSystem: "Det internasjonale enhetssystemet (SI)",
    siEquivalent: "SIs grunnleggende temperaturenhet",
    commonUses: "Termodynamikk, vitenskapelige beregninger og analyser som krever absolutt temperatur",
  },
  // Tid
  {
    locale: "no",
    sourceSlug: "saniye",
    slug: "sekund",
    category: "zaman",
    categoryName: "Tid",
    unit: "s",
    name: "Sekund",
    symbol: "s",
    shortDescription: "Sekund er SI-grunnenheten for tid. Den ligger til grunn for alle beregninger av varighet og hastighet.",
    historySummary: "Sekundet ble historisk definert som 1/86 400 av en dag; men man innså at små uregelmessigheter i jordens rotasjonshastighet gjorde denne definisjonen for ustabil. I 1967, på det 13. møte til Generalkonferansen for mål og vekt, ble sekundet fullstendig omdefinert: det defineres nå som nøyaktig 9 192 631 770 perioder av strålingen som svarer til overgangen mellom to grunnenerginivåer i cesium-133-atomet. Denne definisjonen gjorde det mulig for atomklokker å reproduseres med samme presisjon (på milliarddelsnivå) overalt i verden, og knyttet sekundet til en universell referanse uavhengig av himmellegemenes bevegelse.",
    measurementSystem: "Det internasjonale enhetssystemet (SI)",
    siEquivalent: "SIs grunnleggende tidsenhet",
    commonUses: "Eksperimenttider, bevegelsesanalyse, dataregistrering og tidtaking",
  },
  {
    locale: "no",
    sourceSlug: "dakika",
    slug: "minutt",
    category: "zaman",
    categoryName: "Tid",
    unit: "min",
    name: "Minutt",
    symbol: "min",
    shortDescription: "Minutt er en praktisk tidsenhet lik 60 sekunder.",
    historySummary: "Minuttet er en mellomenhet som historisk har blitt utbredt både i daglig planlegging og ikke-vitenskapelig tidsfølging.",
    measurementSystem: "Utenfor SI, tidsenhet brukt sammen med SI",
    siEquivalent: "1 min = 60 s",
    commonUses: "Møter, korte tidsrom, trening og prosessykluser",
  },
  {
    locale: "no",
    sourceSlug: "saat",
    slug: "time",
    category: "zaman",
    categoryName: "Tid",
    unit: "t",
    name: "Time",
    symbol: "t",
    shortDescription: "Time er en utbredt tidsenhet lik 3600 sekunder.",
    historySummary: "Timeenheten har blitt overført fra himmelske og mekaniske tidsmålingstradisjoner til moderne kalender- og skiftsystemer.",
    measurementSystem: "Utenfor SI, tidsenhet brukt sammen med SI",
    siEquivalent: "1 t = 3600 s",
    commonUses: "Arbeidstid, reise, energiforbruk og daglig planlegging",
  },
  {
    locale: "no",
    sourceSlug: "gun",
    slug: "dogn",
    category: "zaman",
    categoryName: "Tid",
    unit: "d",
    name: "Døgn",
    symbol: "d",
    shortDescription: "Døgn er en grunnleggende tidsenhet lik 24 timer (86 400 sekunder), basert på en full omdreining av jorden om sin egen akse (soldøgnet).",
    historySummary: "Begrepet døgn er menneskehetens eldste og mest universelle tidsmål; det bygger på syklusen med soloppgang og solnedgang. I den moderne definisjonen er 1 døgn fastsatt til nøyaktig 86 400 SI-sekunder (gjennomsnittlig soldøgn).",
    measurementSystem: "Det internasjonale enhetssystemet (SI, skalert enhet)",
    siEquivalent: "1 døgn = 86 400 s = 24 timer",
    commonUses: "Kalenderberegninger, varighets-/alderberegninger, reise- og prosjektplanlegging",
  },
  // Hastighet
  {
    locale: "no",
    sourceSlug: "metre-saniye",
    slug: "meter-per-sekund",
    category: "hiz",
    categoryName: "Hastighet",
    unit: "m/s",
    name: "Meter per sekund",
    symbol: "m/s",
    shortDescription: "Meter per sekund er SIs avledede enhet for hastighet. Den regnes som grunnleggende referanse i ingeniørfag og fysikk.",
    historySummary: "Denne betegnelsen, som fremkommer ved å kombinere meter og sekund, er det standard vitenskapelige språket for moderne hastighetsmåling.",
    measurementSystem: "Det internasjonale enhetssystemet (SI)",
    siEquivalent: "SIs grunnleggende hastighetsenhet",
    commonUses: "Strømningslære, mekanisk bevegelse og vitenskapelige målinger",
  },
  {
    locale: "no",
    sourceSlug: "kilometre-saat",
    slug: "kilometer-i-timen",
    category: "hiz",
    categoryName: "Hastighet",
    unit: "km/t",
    name: "Kilometer i timen",
    symbol: "km/t",
    shortDescription: "Kilometer i timen er en praktisk hastighetsenhet mye brukt i landtransport.",
    historySummary: "Etter hvert som vei- og transportsystemer ble utbredt, ble km/t standard betegnelse for kjøring og reise.",
    measurementSystem: "Metrisk praktisk bruk",
    siEquivalent: "1 km/t ≈ 0,277778 m/s",
    commonUses: "Kjøretøyhastighet, trafikkskilt og feltmålinger",
  },
  {
    locale: "no",
    sourceSlug: "mil-saat",
    slug: "engelsk-mil-i-timen",
    category: "hiz",
    categoryName: "Hastighet",
    unit: "mph",
    name: "Engelske mil i timen",
    symbol: "mph",
    shortDescription: "Engelske mil i timen er en hastighetsenhet brukt særlig i USA og Storbritannia.",
    historySummary: "Kombinasjonen av mil og time har dannet det grunnleggende hastighetsspråket i den angloamerikanske måletradisjonen for landtransport.",
    measurementSystem: "Britisk og amerikansk målesystem",
    siEquivalent: "1 mph = 1,609344 km/t",
    commonUses: "Veihastigheter, bilindustri og feltrapporter",
  },
  {
    locale: "no",
    sourceSlug: "knot",
    slug: "knop",
    category: "hiz",
    categoryName: "Hastighet",
    unit: "knop",
    name: "Knop",
    symbol: "knop",
    shortDescription: "Knop (nautiske mil i timen) er standard hastighetsenhet i sjøfart og luftfart, lik 1 nautisk mil (1852 meter) per time.",
    historySummary: "Navnet knop stammer historisk fra en trebit festet til et knutet tau ('chip log') som ble kastet ut i vannet for å måle fartøyets hastighet; tauet, som var knutet med jevne mellomrom, gå fartøyets hastighet ved å telle hvor mange knuter som gikk ut i løpet av en bestemt tid.",
    measurementSystem: "Utenfor SI, standardenhet i sjøfart/luftfart",
    siEquivalent: "1 knop = 1852/3600 m/s ≈ 0,5144 m/s",
    commonUses: "Skips- og flyhastighet, vindhastighet (i meteorologi), navigasjonsberegninger",
  },
  // Trykk
  {
    locale: "no",
    sourceSlug: "pascal",
    slug: "pascal",
    category: "basinc",
    categoryName: "Trykk",
    unit: "Pa",
    name: "Pascal",
    symbol: "Pa",
    shortDescription: "Pascal er SIs avledede enhet for trykk. Den defineres ved sammenhengen 1 På = 1 N/m².",
    historySummary: "Enheten er oppkalt etter den franske vitenskapsmannen Blaise Pascal fra 1600-tallet -- Pascal er kjent for sitt arbeid innen hydrodynamikk og hydrostatikk, og for sine banebrytende trykkforsøk med barometeret. Pascals funn om at 'trykk påført en lukket væske overføres likt i alle retninger' (Pascals lov) danner grunnlaget for hydrauliske systemer. Enheten ble formelt vedtatt som SI-enhet på det 14. møte til Generalkonferansen for mål og vekt i 1971, og definert som newton per kvadratmeter (N/m²).",
    measurementSystem: "Det internasjonale enhetssystemet (SI)",
    siEquivalent: "SIs grunnleggende trykkenhet, 1 På = 1 N/m²",
    commonUses: "Vitenskapelige beregninger, materialanalyse og referanseomregninger",
  },
  {
    locale: "no",
    sourceSlug: "bar",
    slug: "bar",
    category: "basinc",
    categoryName: "Trykk",
    unit: "bar",
    name: "Bar",
    symbol: "bar",
    shortDescription: "Bar er en trykkenhet lik 100 000 pascal. Den er en svært utbredt praktisk visning på industri- og utstyrsmålere.",
    historySummary: "Bar-enheten ble lansert av den norske meteorologen Vilhelm Bjerknes, en av pionerene innen moderne værvarsling; navnet kommer fra det oldgreske ordet 'baros', som betyr 'vekt' (interessant nok ble ordet 'bar' også brukt mellom 1793 og 1795 i det tidlige metriske systemet, om en masseenhet tilsvarende dagens tonn). 1 bar tilsvarer nøyaktig 100 000 pascal og ligger svært nær gjennomsnittlig atmosfæretrykk ved havnivå (om lag 1,013 bar). Selv om bar ikke er en offisiell SI-enhet, brukes den fortsatt mye av meteorologer og luftfartsbransjen i dag, fordi den tallmessig tilsvarer millibar/hektopascal og er praktisk i bruk.",
    measurementSystem: "Metrisk ingeniørenhet utenfor SI",
    siEquivalent: "1 bar = 100 000 På",
    commonUses: "Kompressorer, hydraulikk, pneumatikk og servicemanometre",
  },
  {
    locale: "no",
    sourceSlug: "psi",
    slug: "psi",
    category: "basinc",
    categoryName: "Trykk",
    unit: "psi",
    name: "PSI",
    symbol: "psi",
    shortDescription: "PSI er forkortelsen for pound-force per square inch. Den er en utbredt trykkenhet i angloamerikanske tekniske systemer.",
    historySummary: "PSI er, som navnet tilsier, en sammensatt enhet dannet ved å dele en kraftenhet (pound-force) på en arealenhet (kvadrattomme), og ble utbredt i britisk ingeniørtradisjon på 1800-tallet for å angi kjeletrykk i dampmaskinenes tidsalder. Selv om det metriske systemet er blitt globalt standard, er PSI fortsatt den de facto bransjestandarden innen bilindustri (dekktrykk), hydrauliske systemer og amerikanskproduserte industrikataloger.",
    measurementSystem: "Britisk og amerikansk ingeniørbruk",
    siEquivalent: "1 psi = 6894,757293168 På",
    commonUses: "Dekktrykk, hydrauliske systemer og teknisk service",
  },
  {
    locale: "no",
    sourceSlug: "atmosfer",
    slug: "atmosfar",
    category: "basinc",
    categoryName: "Trykk",
    unit: "atm",
    name: "Atmosfære",
    symbol: "atm",
    shortDescription: "Atmosfære er en trykkenhet basert på en referanseverdi nær gjennomsnittlig trykk i jordens atmosfære ved havnivå. Også kalt standard atmosfære.",
    historySummary: "Atmosfære-enheten ble utbredt etter hvert som barometriske målinger og havnivåreferansetrykk ble brukt som standard sammenligningspunkt i tekniske og vitenskapelige arbeider. I 1954 definerte den 10. Generalkonferansen for mål og vekt (CGPM) standard atmosfære til nøyaktig 101 325 På.",
    measurementSystem: "Utenfor SI, referanseenhet i meteorologi og ingeniørfag",
    siEquivalent: "1 atm = 101 325 På (definert verdi)",
    commonUses: "Referanseforhold, meteorologi, vakuum- og trykkmålinger",
  },
  // Energi
  {
    locale: "no",
    sourceSlug: "joule",
    slug: "joule",
    category: "enerji",
    categoryName: "Energi",
    unit: "J",
    name: "Joule",
    symbol: "J",
    shortDescription: "Joule er SIs avledede enhet for energi. Den brukes til å uttrykke mengder av arbeid, varme og energi.",
    historySummary: "Enheten ble oppkalt etter den britiske fysikeren James Prescott Joule (1818-1889), etter hans arbeid som klarla sammenhengen mellom mekanisk arbeid og varme. Navnet ble først foreslått 23. august 1882, i William Siemens sin presidenttale for British Association for the Advancement of Science; Siemens foreslo å kalle den 'joule', til ære for 'mannen som har bidratt så mye til å utvikle den dynamiske varmeteorien'. Enheten ble formelt vedtatt 31. august 1889, ved den andre internasjonale elektriske kongress, sammen med enheten watt -- ved et interessant sammentreff døde Joule senere samme år (11. oktober 1889). Definisjonen ble oppdatert i 1946 innenfor Giorgi-systemet, og ble nå uttrykt direkte og uavhengig av elektromagnetiske enheter, som 'arbeidet en kraft utfører over en strekning på en meter'.",
    measurementSystem: "Det internasjonale enhetssystemet (SI)",
    siEquivalent: "SIs grunnleggende energienhet",
    commonUses: "Termodynamikk, energibalanser og vitenskapelige beregninger",
  },
  {
    locale: "no",
    sourceSlug: "kilovatsaat",
    slug: "kilowattime",
    category: "enerji",
    categoryName: "Energi",
    unit: "kWh",
    name: "Kilowattime",
    symbol: "kWh",
    shortDescription: "Kilowattime er en energienhet mye brukt for å måle strømforbruk.",
    historySummary: "På grunn av strømmålere og faktureringssystemer har kilowattime blitt en av de mest kjente enhetene for praktisk energibruk.",
    measurementSystem: "Teknisk og kommersiell energienhet",
    siEquivalent: "1 kWh = 3,6 MJ",
    commonUses: "Strømregninger, batterikapasitet og forbrukssammenligninger",
  },
  {
    locale: "no",
    sourceSlug: "kalori",
    slug: "kalori",
    category: "enerji",
    categoryName: "Energi",
    unit: "cal",
    name: "Kalori",
    symbol: "cal",
    shortDescription: "Kalori (cal) er en energienhet utenfor SI, definert som energimengden som kreves for å heve temperaturen til ett gram vann med 1 °C. Ifølge den termokjemiske kaloridefinisjonen tilsvarer 1 kalori 4,184 joule.",
    historySummary: "Kaloribegrepet ble lansert på 1800-tallet av den franske kjemikeren Nicolas Clement for å måle varmemengde, og ble utbredt i termodynamikkens utviklingsperiode. Selv om SI-enheten joule i stor grad forventes å erstatte den, brukes den fortsatt mye (som kilokalori) i ernæringsvitenskapen.",
    measurementSystem: "Utenfor SI, tradisjonell energienhet",
    siEquivalent: "1 cal = 4,184 J (termokjemisk definisjon)",
    commonUses: "Kjemiske og termodynamiske beregninger, matenergi (via kilokalori)",
  },
  {
    locale: "no",
    sourceSlug: "btu",
    slug: "btu",
    category: "enerji",
    categoryName: "Energi",
    unit: "Btu",
    name: "BTU",
    symbol: "Btu",
    shortDescription: "BTU (British Thermal Unit) er en energienhet brukt i det britiske/amerikanske målesystemet, definert som energimengden som kreves for å heve temperaturen til ett pund vann med 1 °F.",
    historySummary: "BTU ble utviklet i England i dampmaskinenes tidsalder for å måle varmeenergi, og ble etter hvert standardenheten for oppvarmings-/kjølebransjen i angloamerikanske land, særlig USA.",
    measurementSystem: "Britisk og amerikansk målesystem",
    siEquivalent: "1 Btu = 1055,056 J",
    commonUses: "Klimaanlegg- og varmerkapasitet (kjøle-/varmeeffekt), naturgassregninger (USA)",
  },
  // Datalagring
  {
    locale: "no",
    sourceSlug: "bayt",
    slug: "byte",
    category: "veri",
    categoryName: "Datalagring",
    unit: "B",
    name: "Byte",
    symbol: "B",
    shortDescription: "Byte er den grunnleggende måleenheten for digital data. Den består av 8 bit og brukes til å representere ett tegn (bokstav, tall osv.).",
    historySummary: "Betegnelsen 'byte' ble bevisst avledet i 1956 av ingeniøren Werner Buchholz ved IBM, som arbeidet med Stretch-datamaskinen, ved å endre skrivemåten til ordet 'bite' for å unngå forveksling med ordet 'bit'. I de første årene kunne en byte være ulik lengde -- fra 1 til 6 bit -- avhengig av datamaskinarkitekturen som ble brukt; standarden på 8-bits byte ble den de facto bransjestandarden med IBMs System/360, som ble lansert i 1964 og var en av tidens mest innflytelsesrike datamaskinfamilier.",
    measurementSystem: "Digital dataenhet (databehandlingsstandard)",
    siEquivalent: "1 byte = 8 bit",
    commonUses: "Filstørrelse, minnekapasitet og dataoverføringsmåling",
  },
  {
    locale: "no",
    sourceSlug: "megabayt",
    slug: "megabyte",
    category: "veri",
    categoryName: "Datalagring",
    unit: "MB",
    name: "Megabyte",
    symbol: "MB",
    shortDescription: "Megabyte (MB) er en dataenhet lik 1 000 000 byte. Den brukes ofte til å uttrykke størrelsen på bilder, musikkfiler og korte dokumenter.",
    historySummary: "Megabyte ble en standard referanseenhet for å uttrykke fil- og diskstørrelser etter hvert som personlige datamaskiner ble utbredt.",
    measurementSystem: "Det internasjonale enhetssystemet (SI, multiplum)",
    siEquivalent: "1 MB = 1 000 000 byte",
    commonUses: "Bilder, musikkfiler, korte videoer og applikasjonsstørrelser",
  },
  {
    locale: "no",
    sourceSlug: "gigabayt",
    slug: "gigabyte",
    category: "veri",
    categoryName: "Datalagring",
    unit: "GB",
    name: "Gigabyte",
    symbol: "GB",
    shortDescription: "Gigabyte (GB) er en dataenhet lik 1 milliard byte. Den brukes til å uttrykke lagringsplass på smarttelefoner, videofiler og RAM-kapasitet.",
    historySummary: "Etter hvert som lagringsteknologien utviklet seg, ble gigabyte standard uttrykk for disk-, minne- og mobilenhetskapasitet; forskjellen mellom SI (1000-basert) og den tradisjonelle databehandlingsbruken (1024-basert) blir mest merkbar nettopp i denne enheten.",
    measurementSystem: "Det internasjonale enhetssystemet (SI, multiplum)",
    siEquivalent: "1 GB = 1 000 000 000 byte",
    commonUses: "Lagringsplass på smarttelefon og datamaskin, RAM-kapasitet, videofiler",
  },
  // Elektrisitet
  {
    locale: "no",
    sourceSlug: "volt",
    slug: "volt",
    category: "elektrik",
    categoryName: "Elektrisitet",
    unit: "V",
    name: "Volt",
    symbol: "V",
    shortDescription: "Volt er SIs avledede enhet for elektrisk spenning.",
    historySummary: "Enheten er oppkalt etter den italienske fysikeren Alessandro Volta -- Volta oppfant 'det voltaiske batteriet' i 1800, som resultat av sin diskusjon med kollegaen Luigi Galvani om 'animalsk elektrisitet'; ved å oppdage at sink og sølv var det mest effektive metallparet, skapte han verdens første apparat som produserte en kontinuerlig elektrisk strøm (forløperen til batteriet). Navnet 'volt' ble foreslått mye senere, i 1861, av Latimer Clark og Charles Bright. I 1873 definerte British Association for the Advancement of Science formelt enhetene volt, ohm og farad; i 1881 vedtok den internasjonale elektriske kongressen volt som den offisielle enheten for elektromotorisk kraft (spenning). Med SI-revisjonen i 2019 ble også definisjonen av volt oppdatert, ved å knytte den elementære elektriske ladningen til en fast verdi.",
    measurementSystem: "Det internasjonale enhetssystemet (SI)",
    siEquivalent: "SIs grunnleggende spenningsenhet",
    commonUses: "Elektroniske kretser, strømforsyninger og nettspenninger",
  },
  {
    locale: "no",
    sourceSlug: "amper",
    slug: "ampere",
    category: "elektrik",
    categoryName: "Elektrisitet",
    unit: "A",
    name: "Ampere",
    symbol: "A",
    shortDescription: "Ampere er standardenheten for en av SIs grunnleggende størrelser: elektrisk strøm.",
    historySummary: "Enheten er oppkalt etter den franske fysikeren og matematikeren Andre-Marie Ampere (1775-1836), som la grunnlaget for elektrodynamikken gjennom sitt arbeid med elektromagnetisme; Ampere bygde her videre på funnene til den danske fysikeren Hans Christian Ørsted. Ampere ble i 1881 erklært standardenheten for elektrisk strøm, gjennom en internasjonal konvensjon signert ved den internasjonale elektriske utstillingen; den første definisjonen var en tidel av den elektromagnetiske strømenheten i CGS-systemet. Frem til SI-revisjonen i 2019 var ampere definert som strømmen som skaper en magnetisk kraft på 2×10⁻⁷ newton per meter mellom to parallelle ledere med 1 meters avstand; fra 2019 defineres den direkte ut fra multipler av den elementære elektriske ladningen (fastsatt til 1,602176634×10⁻¹⁹ coulomb).",
    measurementSystem: "Det internasjonale enhetssystemet (SI)",
    siEquivalent: "SIs grunnleggende strømenhet",
    commonUses: "Strømmålinger, vernutstyr og apparatmerking",
  },
  {
    locale: "no",
    sourceSlug: "miliamper",
    slug: "milliampere",
    category: "elektrik",
    categoryName: "Elektrisitet",
    unit: "mA",
    name: "Milliampere",
    symbol: "mA",
    shortDescription: "Milliampere er en liten strømenhet lik en tusendel av en ampere.",
    historySummary: "Milliampere-visning ble utbredt for å gjøre det enklere å lese lave strømverdier i elektronikk og måleinstrumenter.",
    measurementSystem: "Det internasjonale enhetssystemet (SI, delenhet)",
    siEquivalent: "1 mÅ = 0,001 Å",
    commonUses: "Elektroniske kretser, sensorer og lavstrømtester",
  },
  // Gullkarat
  {
    locale: "no",
    sourceSlug: "24-ayar-altin",
    slug: "24-karat-gull",
    category: "altin_ayar",
    categoryName: "Gullkarat",
    unit: "24K",
    name: "24 karat gull",
    symbol: "24K",
    shortDescription: "24 karat gull er 99,9 % rent, nærmest helt rent gull. Fordi det er den mykeste karaten, brukes det oftest til barrer og investeringsprodukter.",
    historySummary: "Karatsystemet er en tradisjonell gullsmedstandard som uttrykker renhetsgraden i en gull-legering på en skala fra 24; 24 karat representerer ulegert, rent gull.",
    measurementSystem: "Gullsmedstandard for renhet (karat)",
    siEquivalent: "24 karat = 100 % rent gullinnhold",
    commonUses: "Gullbarrer, investeringsgull og bruk som renhetsreferanse",
  },
  {
    locale: "no",
    sourceSlug: "22-ayar-altin",
    slug: "22-karat-gull",
    category: "altin_ayar",
    categoryName: "Gullkarat",
    unit: "22K",
    name: "22 karat gull",
    symbol: "22K",
    shortDescription: "22 karat gull er en legering der 22/24 (om lag 91,6 %) av innholdet er rent gull. Den er vanlig for armbånd og tradisjonelle smykker i Tyrkia.",
    historySummary: "22 karat oppstår ved at en liten mengde sølv eller kobber legeres inn i rent gull for å redusere mykheten og øke holdbarheten, og har blitt den tradisjonelle smykkestandarden i Tyrkia og Midtøsten.",
    measurementSystem: "Gullsmedstandard for renhet (karat)",
    siEquivalent: "22 karat = 91,6 % rent gullinnhold (22/24)",
    commonUses: "Armbånd, tradisjonelle smykker og gullgaver",
  },
  {
    locale: "no",
    sourceSlug: "18-ayar-altin",
    slug: "18-karat-gull",
    category: "altin_ayar",
    categoryName: "Gullkarat",
    unit: "18K",
    name: "18 karat gull",
    symbol: "18K",
    shortDescription: "18 karat gull er en legering der 18/24 (75 %) av innholdet er rent gull. Takket være den høye holdbarheten foretrekkes den til dagligsmykker.",
    historySummary: "18 karat, som er hardere og mer ripebestandig enn rent gull, har blitt den internasjonale standarden særlig for ringer og dagligsmykker.",
    measurementSystem: "Gullsmedstandard for renhet (karat)",
    siEquivalent: "18 karat = 75 % rent gullinnhold (18/24)",
    commonUses: "Ringer, kjeder, dagligsmykker og diamantinnfatninger",
  },
  // Solvinnhold
  {
    locale: "no",
    sourceSlug: "999-ayar-gumus",
    slug: "silver-999",
    category: "gumus_ayar",
    categoryName: "Sølvinnhold",
    unit: "999",
    name: "Sølv 999 (fint)",
    symbol: "999",
    shortDescription: "Sølv 999 er 99,9 % rent, nærmest helt rent sølv, også kalt 'fint sølv'. Fordi det er svært mykt, brukes det hovedsakelig til barrer og investeringsprodukter fremfor smykker.",
    historySummary: "I motsetning til gull uttrykkes sølvets renhet direkte i tusendeler; 999 representerer ulegert, rent sølv og brukes som renhetsreferanse ved handel med edle metaller.",
    measurementSystem: "Gullsmedstandard for renhet (tusendeler)",
    siEquivalent: "999 = 99,9 % rent sølvinnhold",
    commonUses: "Sølvbarrer, investeringssølv og bruk som renhetsreferanse",
  },
  {
    locale: "no",
    sourceSlug: "925-ayar-gumus",
    slug: "sterlingsilver-925",
    category: "gumus_ayar",
    categoryName: "Sølvinnhold",
    unit: "925",
    name: "Sterlingsølv (925)",
    symbol: "925",
    shortDescription: "Sterlingsølv inneholder 92,5 % rent sølv, der resten som regel er kobber. Det er kjent verden over som 'sterling silver' og er den mest brukte sølvstandarden innen smykker.",
    historySummary: "Sterlingsølv-standarden oppsto i England for å motvirke det rene sølvets ekstreme mykhet, og har over tid blitt den faktiske globale standarden for sølvsmykker og bruksgjenstander.",
    measurementSystem: "Gullsmedstandard for renhet (tusendeler)",
    siEquivalent: "925 = 92,5 % rent sølvinnhold (sterlingsølv)",
    commonUses: "Sølvsmykker, ringer, kjeder og sølvbestikk",
  },
];

export function findNorwegianUnitPageBySourceSlug(sourceSlug: string) {
  return norwegianUnitPages.find((page) => page.sourceSlug === sourceSlug);
}

export function findNorwegianUnitPage(category: string, unit: string) {
  return norwegianUnitPages.find(
    (page) => page.category === category && page.unit === unit
  );
}
