// Danske enhedssider -- integreret i det nye i18n-system.
// Selvstaendig, ny fil (aendrer ingen eksisterende tr/en/de/ar/uz/bn/fr/es/pt/it/nl/sv/no-filer).
// Indholdet er oversat direkte fra den tyrkiske kilde
// (app/converter/unitPages.ts, unitDescriptions-tabellen), ikke fra et
// mellemsprog, for at bevare samme dybde og faktaindhold som flagskibet.
// Omfanget er bevidst begraenset til de 13 karnekategorier, som sammen med
// de 4 universelle vaerktojer (forsiden) udgor de 17 elementer, der
// definerer sidens identitet.

export type LocalizedDanishUnitPage = {
  locale: "da";
  sourceSlug: string;
  slug: string;
  category: string;
  categoryName: string;
  unit: string;
  name: string;
  symbol: string;
  shortDescription: string;
  historySummary: string;
  measurementSystem: string;
  siEquivalent: string;
  commonUses: string;
};

export const danishUnitPages: LocalizedDanishUnitPage[] = [
  // Laengde
  {
    locale: "da",
    sourceSlug: "metre",
    slug: "meter",
    category: "uzunluk",
    categoryName: "Laengde",
    unit: "m",
    name: "Meter",
    symbol: "m",
    shortDescription: "Meter er grundenheden for laengde i Det Internationale Enhedssystem. Den bruges til at male afstand og storrelse, fra dagligdagen til ingeniorfag.",
    historySummary: "Meteren opstod under den franske revolution, med mal om at erstatte de maleenheder, der frem til da varierede fra region til region, med en enkelt universel og naturbaseret standard. Man overvejede forst en definition baseret pa svingningstiden af en pendul, men denne idé blev forkastet, da man indsa, at en pendul pavirkes af lokal tyngdekraft. I stedet definerede den franske nationalforsamling i 1791 meteren som en titimillionte del af afstanden fra Nordpolen til ekvator langs meridianen gennem Paris -- en afstand beregnet gennem flerarige geodaetiske malinger udfort af Delambre og Méchain. I 1799 blev definitionen baseret pa en platinstav kaldet 'Mètre des Archives'; i 1889 blev denne stav erstattet af en ny standard i platin-iridiumlegering, med 29 kopier udplaceret over hele verden. I 1960 blev meteren ikke laengere defineret ud fra et fysisk objekt, men ud fra bolgelaengden af lyset udsendt af et krypton-86-atom. Siden 1983 er meteren defineret som den straekning, lyset tilbagelaegger i vakuum pa 1/299 792 458 sekund -- dette gor, at meteren kan reproduceres med ekstremt hoj praecision i et hvilket som helst laboratorium i verden, uden at have brug for en fysisk prototype.",
    measurementSystem: "Det Internationale Enhedssystem (SI)",
    siEquivalent: "SIs grundlaeggende laengdeenhed",
    commonUses: "Byggeri, videnskab, produktion, geometri og generel maling",
  },
  {
    locale: "da",
    sourceSlug: "kilometre",
    slug: "kilometer",
    category: "uzunluk",
    categoryName: "Laengde",
    unit: "km",
    name: "Kilometer",
    symbol: "km",
    shortDescription: "Kilometer er en laengdeenhed lig 1000 meter. Den bruges til at udtrykke afstande mellem byer og geografiske afstande.",
    historySummary: "Kilometeren etablerede sig som et multiplum af meteren inden for det metriske systems decimale struktur. Den blev en standardbetegnelse for veje og kortmalestoksforhold.",
    measurementSystem: "Det Internationale Enhedssystem (SI, multiplum)",
    siEquivalent: "1 km = 1000 m",
    commonUses: "Vejafstande, geografi, kartografi og infrastruktur",
  },
  {
    locale: "da",
    sourceSlug: "santimetre",
    slug: "centimeter",
    category: "uzunluk",
    categoryName: "Laengde",
    unit: "cm",
    name: "Centimeter",
    symbol: "cm",
    shortDescription: "Centimeter er en laengdeenhed lig en hundrededel af en meter. Den er almindelig til at udtrykke sma genstande og hverdagsmal.",
    historySummary: "Centimeteren udviklede sig som en decimal delenhed i det metriske system. Den fik bred anvendelse, fordi den gjorde malinger praktiske og hurtige at beregne.",
    measurementSystem: "Det Internationale Enhedssystem (SI, delenhed)",
    siEquivalent: "1 cm = 0,01 m",
    commonUses: "Mobler, tekstil, antropometri og hverdagsmalinger",
  },
  {
    locale: "da",
    sourceSlug: "milimetre",
    slug: "millimeter",
    category: "uzunluk",
    categoryName: "Laengde",
    unit: "mm",
    name: "Millimeter",
    symbol: "mm",
    shortDescription: "Millimeter er en laengdeenhed lig en tusindedel af en meter. Den bruges ofte i praecise tekniske malinger.",
    historySummary: "Millimeteren blev udbredt, efterhanden som industri og ingeniorfag fik behov for at male mindre tolerancer. Den blev en grundlaeggende delenhed, saerligt i produktions- og tegningsstandarder.",
    measurementSystem: "Det Internationale Enhedssystem (SI, delenhed)",
    siEquivalent: "1 mm = 0,001 m",
    commonUses: "Mekanisk produktion, tekniske tegninger, bearbejdningstolerancer",
  },
  {
    locale: "da",
    sourceSlug: "fit",
    slug: "fod",
    category: "uzunluk",
    categoryName: "Laengde",
    unit: "ft",
    name: "Fod",
    symbol: "ft",
    shortDescription: "Fod er en laengdeenhed brugt i det britiske og amerikanske malesystem. En international fod svarer noejagtigt til 0,3048 meter.",
    historySummary: "Fod (foot) var, som navnet antyder, historisk et omtrentligt mal baseret pa laengden af en menneskefod, og siden den romerske enhed 'pes' har snesevis af forskellige 'fod'-definitioner varieret mellem 250 og 335 mm afhaengigt af region og tidsperiode. Foden, der efterhanden blev stabil i England, blev endeligt fastsat til noejagtigt 0,3048 meter (altsa noejagtigt 12 tommer) gennem en international aftale i 1959 (samme ar som tomme og engelsk mil ogsa blev fastsat) mellem USA, Storbritannien og samveldelandene.",
    measurementSystem: "Britisk og amerikansk malesystem",
    siEquivalent: "1 ft = 0,3048 m",
    commonUses: "Arkitektur, bygningshojder, luftfart og feltmalinger",
  },
  {
    locale: "da",
    sourceSlug: "inc",
    slug: "tomme",
    category: "uzunluk",
    categoryName: "Laengde",
    unit: "in",
    name: "Tomme",
    symbol: "in",
    shortDescription: "Tomme er en kort laengdeenhed brugt i det britiske og amerikanske malesystem. En tomme svarer noejagtigt til 2,54 centimeter.",
    historySummary: "Ordet 'inch' stammer fra det latinske 'uncia', som betyder 'en tolvtedel'. Den aeldste definition blev givet i 1324 af kong Edward II af England, som 'tre byggekorn lagt ende mod ende', og denne definition blev brugt i arhundreder. Det fortaelles ogsa, at kong David I af Skotland (1100-tallet) definerede tommen som bredden ved neglebedet pa en mands tommelfinger. Et vendepunkt kom i 1896, da den svenske ingenior Carl Edvard Johansson, ved fremstilling af praecisionsmaleblokke, i praksis fastsatte tommen til noejagtigt 25,4 mm -- denne 'industrielle tomme' blev taget i brug af britiske standardorganer i 1930 og amerikanske i 1933. Den endelige internationale aftale tradte i kraft i 1959 (1. juli i USA), og siden da er tommen defineret som noejagtigt 25,4 millimeter.",
    measurementSystem: "Britisk og amerikansk malesystem",
    siEquivalent: "1 in = 25,4 mm = 2,54 cm",
    commonUses: "Skaermstorrelser, rorlaegning, fastgorelseselementer og tekniske kataloger",
  },
  {
    locale: "da",
    sourceSlug: "yarda",
    slug: "yard",
    category: "uzunluk",
    categoryName: "Laengde",
    unit: "yd",
    name: "Yard",
    symbol: "yd",
    shortDescription: "Yard er en laengdeenhed brugt i det britiske og amerikanske malesystem. En yard svarer noejagtigt til 0,9144 meter.",
    historySummary: "Oprindelsen af yarden er ikke helt klarlagt, men ifolge en udbredt fortaelling definerede kong Henrik I af England pa 1100-tallet yarden som afstanden fra hans egen naesetip til tommelfingeren pa den udstrakte arm. En mere veldokumenteret udvikling er, at officielle bronzeyardstaenger blev fremstillet som standardreference ved det britiske finansministerium pa 1500-tallet. Ligesom fod og tomme blev ogsa yarden endeligt fastsat til noejagtigt 0,9144 meter (3 fod) gennem den internationale aftale i 1959.",
    measurementSystem: "Britisk og amerikansk malesystem",
    siEquivalent: "1 yd = 0,9144 m",
    commonUses: "Idraetsbaner, tekstil, landskabsarbejde og feltplanlaegning",
  },
  {
    locale: "da",
    sourceSlug: "mil",
    slug: "engelsk-mil",
    category: "uzunluk",
    categoryName: "Laengde",
    unit: "mi",
    name: "Engelsk mil",
    symbol: "mi",
    shortDescription: "Engelsk mil er en laengdeenhed brugt saerligt i USA og Storbritannien. En international mil svarer til 1609,344 meter.",
    historySummary: "Ordet 'mile' kommer fra det latinske udtryk 'mille passus' (tusind skridt) -- et 'skridt' blev talt som afstanden mellem to nedtramp af samme fod. Den romerske mil blev indirekte fastsat, da Marcus Agrippa definerede en standard romersk fod i 29 f.Kr. (1 skridt = 5 romerske fod, 1 mil = 5000 romerske fod ≈ 1479 meter). I middelalderens England var den 'gamle engelske mil' et upraecist mal pa omkring 2,1 km, der varierede fra region til region. Det afgorende vendepunkt indtraf i 1593: en parlamentslov om vaegt og mal under dronning Elizabeth I bevarede den traditionelle milstruktur pa 8 furlong, men oegede antallet af fod, sa milen blev fastsat til noejagtigt 5280 fod (1760 yard) -- denne definition bredte sig gennem det britiske imperium og dannede grundlaget for nutidens internationale mil. Den moderne internationale mil blev endeligt fastsat til noejagtigt 1609,344 meter i 1959.",
    measurementSystem: "Britisk og amerikansk malesystem",
    siEquivalent: "1 mi = 1609,344 m",
    commonUses: "Vejafstande, navigation og feltmalestoksforhold",
  },
  // Areal
  {
    locale: "da",
    sourceSlug: "metrekare",
    slug: "kvadratmeter",
    category: "alan",
    categoryName: "Areal",
    unit: "m²",
    name: "Kvadratmeter",
    symbol: "m²",
    shortDescription: "Kvadratmeter er SIs afledte enhed for areal. Den bruges som grundlaeggende reference i beregning af gulv, tvaersnit og overflader.",
    historySummary: "Kvadratmeteren etablerede sig i det metriske system som den todimensionale udvidelse af meteren. Den blev et standardarealsprog i bygge-, grund- og ingeniortegninger.",
    measurementSystem: "Det Internationale Enhedssystem (SI)",
    siEquivalent: "SIs grundlaeggende arealenhed",
    commonUses: "Arkitektur, interior, panelflader og tvaersnitsareal",
  },
  {
    locale: "da",
    sourceSlug: "hektar",
    slug: "hektar",
    category: "alan",
    categoryName: "Areal",
    unit: "ha",
    name: "Hektar",
    symbol: "ha",
    shortDescription: "Hektar er en stor arealenhed brugt saerligt ved ejendomsmaling. 1 hektar svarer noejagtigt til 10 000 kvadratmeter.",
    historySummary: "Hektaren blev, som en del af det metriske system indfort af den franske revolution, i 1795 defineret som 100 gange enheden 'ar' (100 m²) og fik navn efter praefikset 'hekto-' (hundrede). Fordi den viste sig langt mere praktisk end ar til at udtrykke store landbrugs- og skovarealer, blev den efterhanden den globale standardenhed for arealmaling. Som en intuitiv sammenligning er en standard fodboldbane omkring 0,7 hektar stor -- hvilket gor hektaren let at forsta i dagligdagen.",
    measurementSystem: "Metrisk system, kompatibelt med SI",
    siEquivalent: "1 ha = 10 000 m²",
    commonUses: "Landbrugsarealer, lokalplaner og store grundregistre",
  },
  {
    locale: "da",
    sourceSlug: "akre",
    slug: "acre",
    category: "alan",
    categoryName: "Areal",
    unit: "ac",
    name: "Acre",
    symbol: "ac",
    shortDescription: "Acre er en stor arealenhed brugt saerligt i det britiske og amerikanske malesystem ved ejendomsmaling. Den svarer til 4046,8564224 kvadratmeter.",
    historySummary: "Acre har historisk udviklet sig fra en tilgang baseret pa storrelsen af den mark, et par okser kunne pluje pa en dag, og bruges stadig som standard arealenhed i det britiske malesystem.",
    measurementSystem: "Britisk og amerikansk malesystem",
    siEquivalent: "1 acre = 4046,8564224 m²",
    commonUses: "Kob og salg af ejendom og jord, maling af landbrugsareal og ejendomsannoncer",
  },
  // Rumfang
  {
    locale: "da",
    sourceSlug: "litre",
    slug: "liter",
    category: "hacim",
    categoryName: "Rumfang",
    unit: "L",
    name: "Liter",
    symbol: "L",
    shortDescription: "Liter er en meget udbredt rumfangsenhed til at udtrykke vaesker og kapaciteter. 1 liter svarer til 0,001 kubikmeter.",
    historySummary: "Liter blev i 1795 i Frankrig defineret som 'en kubikdecimeter', som en del af det nye malesystem indfort af den franske revolution. I 1901 definerede Generalkonferencen for Mal og Vaegt liter pa ny som 'rumfanget af 1 kg rent vand ved sin taethedsmaksimum-temperatur (3,98 °C) ved 1 atmosfaeres tryk' -- men denne definition gjorde liter en smule storre (omkring 1,000028 gange) end en kubikdecimeter, fordi den referencene platin-iridium-kilogramprototype viste sig at vaere 28 dele per million storre end forventet. Denne 63 ar lange afvigelse blev rettet i 1964, da Generalkonferencen igen definerede liter direkte knyttet til meteren, som noejagtigt 'en kubikdecimeter'.",
    measurementSystem: "Metrisk system, kompatibelt med SI",
    siEquivalent: "1 L = 0,001 m³",
    commonUses: "Vaesker, tankrumfang, laboratoriebeholdere og hverdagsmal",
  },
  {
    locale: "da",
    sourceSlug: "mililitre",
    slug: "milliliter",
    category: "hacim",
    categoryName: "Rumfang",
    unit: "mL",
    name: "Milliliter",
    symbol: "mL",
    shortDescription: "Milliliter er en lille rumfangsenhed lig en tusindedel af en liter. Den bruges til praecise vaeskemalinger.",
    historySummary: "Milliliter blev udbredt for palideligt at kunne udtrykke sma rumfang inden for medicin, laboratorium og koekkenmal.",
    measurementSystem: "Metrisk system, kompatibelt med SI",
    siEquivalent: "1 mL = 0,000001 m³",
    commonUses: "Medicindoser, laboratorieprover og sma vaeskerumfang",
  },
  {
    locale: "da",
    sourceSlug: "metrekup",
    slug: "kubikmeter",
    category: "hacim",
    categoryName: "Rumfang",
    unit: "m³",
    name: "Kubikmeter",
    symbol: "m³",
    shortDescription: "Kubikmeter er SIs afledte enhed for rumfang. Den er grundreferencen for store rumfang og tekniske kapaciteter.",
    historySummary: "Kubikmeteren defineres som det indre rumfang af en kube, hvor hver side er noejagtigt 1 meter, og fremkommer direkte ved at udvide meteren til tre dimensioner. Fordi den svarer til 1000 liter (1 m³ = 1000 L), bruges den verden over som standardenhed ved fakturering af naturgas- og vandforbrug -- ogsa i Danmark viser naturgas- og vandregninger forbruget i kubikmeter. Inden for byggebranchen udtrykkes ogsa betong- og jordmaengder, og i industrien tank- og lagerkapaciteter, ofte i denne enhed.",
    measurementSystem: "Det Internationale Enhedssystem (SI)",
    siEquivalent: "SIs grundlaeggende rumfangsenhed",
    commonUses: "Lagerrumfang, bygningsrumfang, procestanke og stromningsberegninger",
  },
  {
    locale: "da",
    sourceSlug: "galon",
    slug: "gallon",
    category: "hacim",
    categoryName: "Rumfang",
    unit: "gal",
    name: "Gallon",
    symbol: "gal",
    shortDescription: "Gallon er en enhed brugt saerligt i USA til at male vaeskerumfang. En amerikansk gallon svarer til 3,78541 liter.",
    historySummary: "Gallonen, der bruges i USA, bygger pa 'vingallon'-traditionen fra middelalderens engelske handel, og blev endeligt fastsat til noejagtigt 231 kubiktommer (3,785411784 L) under dronning Anne i 1706 -- USA tog officielt denne definition i brug i 1836. Storbritannien gik derimod en helt anden vej i 1824 og definerede pa ny sin egen 'britiske gallon' (imperial gallon) som 'rumfanget svarende til vaegten af 10 pund destilleret vand' (omkring 4,546 L), og ophaevede samtidig alle andre gallondefinitioner. Pa grund af disse forskellige oprindelsesvalg er den britiske gallon omkring 20 % storre end den amerikanske.",
    measurementSystem: "Amerikansk malesystem (US liquid gallon)",
    siEquivalent: "1 gallon (US) = 3,78541 L = 0,00378541 m³",
    commonUses: "Braendstofforbrug, amerikanske vaeskeproduktetiketter og koekkenmal",
  },
  // Masse
  {
    locale: "da",
    sourceSlug: "kilogram",
    slug: "kilogram",
    category: "kutle",
    categoryName: "Masse",
    unit: "kg",
    name: "Kilogram",
    symbol: "kg",
    shortDescription: "Kilogram er SI-grundenheden for masse. Den bruges meget inden for handel, laboratorium og ingeniorfag.",
    historySummary: "Oprindelsen af kilogrammet gar ogsa tilbage til den franske revolution: i 1795 blev gram defineret som massen af 1 kubikcentimeter vand ved isens smeltepunkt (0 °C) -- altsa svarede 1 kilogram til 1 liter vand under disse forhold. Men da man opdagede, at vandets taethed aendrer sig med temperaturen, blev der i 1799 lavet en platinprototype kaldet 'Kilogramme des Archives'; denne gang var referencen massen af 1 kubikdecimeter vand ved omkring 4 °C, hvor vandet er taettest. I 1889 blev denne prototype erstattet af en ny cylinder i platin-iridiumlegering kendt som 'Le Grand K', og denne blev opbevaret som verdens referencekilogram ved Det Internationale Byrå for Mal og Vaegt i Frankrig i 130 ar. Efterhanden blev det opdaget, at denne cylinder havde afveget omkring 50 mikrogram fra de kopier, der blev fremstillet pa samme tid -- en uundgaelig skrobelighed ved at basere sig pa et fysisk objekt. Den 16. november 2018 vedtog Generalkonferencen for Mal og Vaegt at indfore en ny definition af kilogrammet baseret pa Plancks konstant; denne nye definition tradte i kraft 20. maj 2019, og kilogrammet kan nu reproduceres i et hvilket som helst laboratorium i verden uden at have brug for en fysisk prototype.",
    measurementSystem: "Det Internationale Enhedssystem (SI)",
    siEquivalent: "SIs grundlaeggende masseenhed",
    commonUses: "Handel, transport, laboratorium og procesberegninger",
  },
  {
    locale: "da",
    sourceSlug: "gram",
    slug: "gram",
    category: "kutle",
    categoryName: "Masse",
    unit: "g",
    name: "Gram",
    symbol: "g",
    shortDescription: "Gram er en masseenhed lig en tusindedel af et kilogram. Den bruges til at udtrykke mad, laboratorie- og sma stofmaengder.",
    historySummary: "Gram var den oprindelige grundlaeggende masseenhed i den forste definition af det franske metriske system i 1795, og blev defineret som massen af 1 kubikcentimeter vand ved isens smeltepunkt. Men fordi det i praksis var svaert at omdanne en sa lille masse til en praecis og reproducerbar standardprototype, blev kilogrammet -- 1000 gange storre (massen af 1 kubikdecimeter vand) -- valgt som referenceprototype i 1799. Dette historiske valg forte til, at kilogram er den eneste af SIs syv grundenheder, der har et praefiks ('kilo-') i navnet -- mens gram, pa trods af at vaere hovedenheden, navnet er afledt af, i dag star som en sekundaer enhed defineret som en delenhed af kilogrammet.",
    measurementSystem: "Det Internationale Enhedssystem (SI, delenhed)",
    siEquivalent: "1 g = 0,001 kg",
    commonUses: "Mad, kemi, farmaci og praecisionsmaling",
  },
  {
    locale: "da",
    sourceSlug: "miligram",
    slug: "milligram",
    category: "kutle",
    categoryName: "Masse",
    unit: "mg",
    name: "Milligram",
    symbol: "mg",
    shortDescription: "Milligram er en meget lille masseenhed lig en tusindedel af et gram. Den har kritisk betydning i medicin- og laboratoriemalinger.",
    historySummary: "Milligrammet fik oeget betydning saerligt inden for sundhed og kemi, efterhanden som praecisionsvaegte og analytiske laboratorier blev udviklet.",
    measurementSystem: "Det Internationale Enhedssystem (SI, delenhed)",
    siEquivalent: "1 mg = 0,000001 kg",
    commonUses: "Medicindoser, analyser og praecise formuleringer",
  },
  {
    locale: "da",
    sourceSlug: "ton",
    slug: "ton",
    category: "kutle",
    categoryName: "Masse",
    unit: "t",
    name: "Ton",
    symbol: "t",
    shortDescription: "Metrisk ton er en stor masseenhed lig 1000 kilogram. Den bruges til at udtrykke tunge laster og industrielle maengder.",
    historySummary: "Ordet 'ton' stammer fra det middelalderengelske ord 'tun', som betyder en stor vintonde; fordi en fyldt tonde vejede omkring en 'long ton', begyndte ordet ogsa at blive brugt som masseenhed. I dag kan tre forskellige 'ton'-definitioner skabe forvirring: det metriske ton (noejagtigt 1000 kg, standard i verden og i Danmark), det amerikanske 'short ton' (2000 pund ≈ 907,18 kg), og det historisk britiske 'long ton' (2240 pund ≈ 1016,05 kg). Selvom forskellen mellem disse tre vaerdier kan virke lille, er det vigtigt tydeligt at angive, hvilken 'ton'-definition der bruges i internationale handels- og logistikaftaler.",
    measurementSystem: "Metrisk system, kompatibelt med SI",
    siEquivalent: "1 t = 1000 kg",
    commonUses: "Logistik, produktion, ravarehandel og tungindustri",
  },
  {
    locale: "da",
    sourceSlug: "pound",
    slug: "pund",
    category: "kutle",
    categoryName: "Masse",
    unit: "lb",
    name: "Pund",
    symbol: "lb",
    shortDescription: "Pund er en masseenhed brugt i det britiske og amerikanske malesystem. Et internationalt pund svarer noejagtigt til 0,45359237 kilogram.",
    historySummary: "Pund stammer fra den romerske enhed 'libra' (omkring 328,9 gram, delt i 12 'uncia') -- forkortelsen 'lb' kommer direkte herfra; selve ordet 'pound' kommer fra udtrykket 'libra pondo' (vaegt malt med libra). For den normanniske erobring (1066) brugte England det 'saksiske pund', defineret ud fra solv under kong Offa (757-796), hvor 1 pund solv gav 240 penny. Omkring 1300 blev 'avoirdupois-pundet', som blev udbredt i handel, oprindeligt fastsat til 6992 troy grain, men blev under dronning Elizabeth I fastsat til noejagtigt 7000 troy grain (delt i 16 ounce). Med vaegtloven af 1878 blev en platincylinder erklaeret officiel standardprototype. Den endelige internationale aftale blev underskrevet 1. juli 1959: pundet regnes nu for noejagtigt 0,45359237 kilogram; Storbritannien tog officielt denne definition i brug gennem loven af 1963.",
    measurementSystem: "Britisk og amerikansk malesystem",
    siEquivalent: "1 lb = 0,45359237 kg",
    commonUses: "Detailhandel, transport, ernaering og industrikataloger",
  },
  {
    locale: "da",
    sourceSlug: "ons",
    slug: "ounce",
    category: "kutle",
    categoryName: "Masse",
    unit: "oz",
    name: "Ounce",
    symbol: "oz",
    shortDescription: "Ounce er en lille masseenhed brugt i det britiske og amerikanske malesystem. En avoirdupois-ounce svarer til 28,349523125 gram.",
    historySummary: "Ordet 'ounce' stammer fra den romerske enhed 'uncia', som delte 'libra' (forlobere for pundet) i tolv lige dele. Ounce brugt i dagligdagen, avoirdupois-ounce (28,349523125 g), svarer til 1/16 af et pund; men troy-ounce, brugt i aedelmetalhandel, er anderledes og tungere (31,1034768 g) -- derfor svarer 'pris per ounce' angivet for guld/solv til en enhed, der er omkring 10 % tungere end den ounce, man moder i dagligvarehandelen. Troy-ounce har sit navn fra Troyes, en vigtig handelsby i middelalderens Frankrig.",
    measurementSystem: "Britisk og amerikansk malesystem",
    siEquivalent: "1 oz = 28,349523125 g",
    commonUses: "Emballage, mad og andre lette kommercielle mal end smykker",
  },
  // Temperatur
  {
    locale: "da",
    sourceSlug: "santigrat",
    slug: "celsius",
    category: "sicaklik",
    categoryName: "Temperatur",
    unit: "°C",
    name: "Celsius",
    symbol: "°C",
    shortDescription: "Celsius-skalaen er en af de mest brugte temperaturvisninger i dagligdagen og ingeniorfag.",
    historySummary: "Celsius-skalaen blev opfundet i 1742 af den svenske astronom Anders Celsius -- men interessant nok var hans oprindelige skala det modsatte af den nuvaerende: 0 grader repraesenterede vandets kogepunkt, og 100 grader frysepunktet. Skalaen blev vendt om i 1743 af den franske fysiker Jean-Pierre Christin (i udformningen af 'Lyon-termometeret') til den nuvaerende ordning med 0 °C for frysning og 100 °C for kogning; den svenske botaniker Carl Linnaeus lavede ogsa den samme ombytning uafhaengigt i 1744 til sit eget drivhustermometer. Skalaen blev laenge kaldt 'centigrade'; i 1948 aendrede Den Internationale Komité for Mal og Vaegt officielt navnet til 'grad Celsius', bade for at hylde Celsius og for at undga, at ordet 'centigrade' i visse sprog blev forvekslet med en hundrededel af en vinkelenhed.",
    measurementSystem: "Temperaturskala brugt sammen med SI",
    siEquivalent: "Ved temperaturforskel: 1 °C = 1 K",
    commonUses: "Vejr, HVAC, procesovervagning og daglige temperaturvaerdier",
  },
  {
    locale: "da",
    sourceSlug: "fahrenhayt",
    slug: "fahrenheit",
    category: "sicaklik",
    categoryName: "Temperatur",
    unit: "°F",
    name: "Fahrenheit",
    symbol: "°F",
    shortDescription: "Fahrenheit er en temperaturskala, der saerligt er udbredt i USA.",
    historySummary: "Fahrenheit-skalaen blev udviklet i 1724 af den polskfodte, hollandske fysiker Daniel Gabriel Fahrenheit. Han satte nulpunktet til den koldeste temperatur, hvor en blanding af is, vand og ammoniumklorid (eller havsalt) stabiliserede sig; 32 grader svarede til rent vands frysepunkt, og 96 grader (efter hans egen maling) menneskekroppens temperatur. Fahrenheit havde taget vaerdierne fra den tidligere Rømer-skala og ganget dem med 4 for at fa en finere, brokfri inddeling. I 1776-77 standardiserede et udvalg i Royal Society, ledet af Henry Cavendish, skalaen; vandets frysepunkt blev fastsat til noejagtigt 32 °F og kogepunktet til noejagtigt 212 °F -- denne korrektion forte ogsa til, at normal kropstemperatur endte pa den nuvaerende kendte 98,6 °F.",
    measurementSystem: "Britisk og amerikansk maletradition",
    siEquivalent: "Ved temperaturforskel: 1 °F = 5/9 K",
    commonUses: "Amerikanske vejrdata, indendorstemperaturer og enkelte tekniske kataloger",
  },
  {
    locale: "da",
    sourceSlug: "kelvin",
    slug: "kelvin",
    category: "sicaklik",
    categoryName: "Temperatur",
    unit: "K",
    name: "Kelvin",
    symbol: "K",
    shortDescription: "Kelvin er SI-grundenheden for temperatur og repraesenterer den absolutte temperaturskala.",
    historySummary: "Grundlaget for Kelvin-skalaen blev lagt i 1848 af den skotske fysiker William Thomson (senere Lord Kelvin); i artiklen 'On an Absolute Thermometric Scale' beregnede han, ved at bruge den termiske ekspansionskoefficient for ideelle gasser, at det absolutte nulpunkt lag pa omkring -273 °C -- overraskende taet pa den nuvaerende vaerdi pa -273,15 °C. I 1854 samarbejdede han med James Prescott Joule om at gore skalaen mere praktisk og kompatibel med lufttermometre. Enheden blev formaliseret i 1954 ved den 10. Generalkonference for Mal og Vaegt, da vandets trippelpunkt blev defineret til noejagtigt 273,16 K; i 1967/68 gav den 13. konference enheden navnet 'kelvin'. I 2019 blev definitionen aendret endnu mere fundamentalt: kelvin bygger nu ikke laengere pa vandets trippelpunkt, men direkte pa Boltzmann-konstanten (fastsat til 1,380649×10⁻²³ J/K).",
    measurementSystem: "Det Internationale Enhedssystem (SI)",
    siEquivalent: "SIs grundlaeggende temperaturenhed",
    commonUses: "Termodynamik, videnskabelige beregninger og analyser, der kraever absolut temperatur",
  },
  // Tid
  {
    locale: "da",
    sourceSlug: "saniye",
    slug: "sekund",
    category: "zaman",
    categoryName: "Tid",
    unit: "s",
    name: "Sekund",
    symbol: "s",
    shortDescription: "Sekund er SI-grundenheden for tid. Den ligger til grund for alle beregninger af varighed og hastighed.",
    historySummary: "Sekundet blev historisk defineret som 1/86 400 af en dag; men man indsa, at sma uregelmaessigheder i jordens rotationshastighed gjorde denne definition for ustabil. I 1967, pa det 13. mode i Generalkonferencen for Mal og Vaegt, blev sekundet fuldstaendigt omdefineret: det defineres nu som noejagtigt 9 192 631 770 perioder af den straling, der svarer til overgangen mellem to grundenerginiveauer i cesium-133-atomet. Denne definition gjorde det muligt for atomure at blive reproduceret med samme praecision (pa milliarddelsniveau) overalt i verden og knyttede sekundet til en universel reference uafhaengigt af himmellegemernes bevaegelse.",
    measurementSystem: "Det Internationale Enhedssystem (SI)",
    siEquivalent: "SIs grundlaeggende tidsenhed",
    commonUses: "Eksperimenttider, bevaegelsesanalyse, dataregistrering og tidtagning",
  },
  {
    locale: "da",
    sourceSlug: "dakika",
    slug: "minut",
    category: "zaman",
    categoryName: "Tid",
    unit: "min",
    name: "Minut",
    symbol: "min",
    shortDescription: "Minut er en praktisk tidsenhed lig 60 sekunder.",
    historySummary: "Minuttet er en mellemenhed, der historisk er blevet udbredt bade i daglig planlaegning og ikke-videnskabelig tidsfolgning.",
    measurementSystem: "Uden for SI, tidsenhed brugt sammen med SI",
    siEquivalent: "1 min = 60 s",
    commonUses: "Moder, korte tidsrum, traening og procescyklusser",
  },
  {
    locale: "da",
    sourceSlug: "saat",
    slug: "time",
    category: "zaman",
    categoryName: "Tid",
    unit: "t",
    name: "Time",
    symbol: "t",
    shortDescription: "Time er en udbredt tidsenhed lig 3600 sekunder.",
    historySummary: "Timeenheden er blevet overfort fra himmelske og mekaniske tidsmalingstraditioner til moderne kalender- og skiftesystemer.",
    measurementSystem: "Uden for SI, tidsenhed brugt sammen med SI",
    siEquivalent: "1 t = 3600 s",
    commonUses: "Arbejdstid, rejse, energiforbrug og daglig planlaegning",
  },
  {
    locale: "da",
    sourceSlug: "gun",
    slug: "dogn",
    category: "zaman",
    categoryName: "Tid",
    unit: "d",
    name: "Dogn",
    symbol: "d",
    shortDescription: "Dogn er en grundlaeggende tidsenhed lig 24 timer (86 400 sekunder), baseret pa en fuld omdrejning af jorden om sin egen akse (soldognet).",
    historySummary: "Begrebet dogn er menneskehedens aeldste og mest universelle tidsmal; det bygger pa cyklussen med solopgang og solnedgang. I den moderne definition er 1 dogn fastsat til noejagtigt 86 400 SI-sekunder (gennemsnitligt soldogn).",
    measurementSystem: "Det Internationale Enhedssystem (SI, skaleret enhed)",
    siEquivalent: "1 dogn = 86 400 s = 24 timer",
    commonUses: "Kalenderberegninger, varigheds-/aldersberegninger, rejse- og projektplanlaegning",
  },
  // Hastighed
  {
    locale: "da",
    sourceSlug: "metre-saniye",
    slug: "meter-per-sekund",
    category: "hiz",
    categoryName: "Hastighed",
    unit: "m/s",
    name: "Meter per sekund",
    symbol: "m/s",
    shortDescription: "Meter per sekund er SIs afledte enhed for hastighed. Den regnes for grundlaeggende reference i ingeniorfag og fysik.",
    historySummary: "Denne betegnelse, der fremkommer ved at kombinere meter og sekund, er det standardvidenskabelige sprog for moderne hastighedsmaling.",
    measurementSystem: "Det Internationale Enhedssystem (SI)",
    siEquivalent: "SIs grundlaeggende hastighedsenhed",
    commonUses: "Stromningslaere, mekanisk bevaegelse og videnskabelige malinger",
  },
  {
    locale: "da",
    sourceSlug: "kilometre-saat",
    slug: "kilometer-i-timen",
    category: "hiz",
    categoryName: "Hastighed",
    unit: "km/t",
    name: "Kilometer i timen",
    symbol: "km/t",
    shortDescription: "Kilometer i timen er en praktisk hastighedsenhed meget brugt i landtransport.",
    historySummary: "Efterhanden som vej- og transportsystemer blev udbredt, blev km/t standardbetegnelse for korsel og rejse.",
    measurementSystem: "Metrisk praktisk brug",
    siEquivalent: "1 km/t ≈ 0,277778 m/s",
    commonUses: "Koretojshastighed, faerdselsskilte og feltmalinger",
  },
  {
    locale: "da",
    sourceSlug: "mil-saat",
    slug: "engelsk-mil-i-timen",
    category: "hiz",
    categoryName: "Hastighed",
    unit: "mph",
    name: "Engelske mil i timen",
    symbol: "mph",
    shortDescription: "Engelske mil i timen er en hastighedsenhed brugt saerligt i USA og Storbritannien.",
    historySummary: "Kombinationen af mil og time har dannet det grundlaeggende hastighedssprog i den angloamerikanske maletradition for landtransport.",
    measurementSystem: "Britisk og amerikansk malesystem",
    siEquivalent: "1 mph = 1,609344 km/t",
    commonUses: "Vejhastigheder, bilindustri og feltrapporter",
  },
  {
    locale: "da",
    sourceSlug: "knot",
    slug: "knob",
    category: "hiz",
    categoryName: "Hastighed",
    unit: "knob",
    name: "Knob",
    symbol: "knob",
    shortDescription: "Knob (sominil i timen) er standard hastighedsenhed i sofart og luftfart, lig 1 sommil (1852 meter) per time.",
    historySummary: "Navnet knob stammer historisk fra en traeklods fastgjort til et knudet reb ('chip log'), der blev kastet ud i vandet for at male et fartojs hastighed; rebet, der var knudet med jaevne mellemrum, gav fartojets hastighed ved at taelle, hvor mange knuder der gik ud i lobet af en bestemt tid.",
    measurementSystem: "Uden for SI, standardenhed i sofart/luftfart",
    siEquivalent: "1 knob = 1852/3600 m/s ≈ 0,5144 m/s",
    commonUses: "Skibs- og flyhastighed, vindhastighed (i meteorologi), navigationsberegninger",
  },
  // Tryk
  {
    locale: "da",
    sourceSlug: "pascal",
    slug: "pascal",
    category: "basinc",
    categoryName: "Tryk",
    unit: "Pa",
    name: "Pascal",
    symbol: "Pa",
    shortDescription: "Pascal er SIs afledte enhed for tryk. Den defineres ved sammenhaengen 1 Pa = 1 N/m².",
    historySummary: "Enheden er opkaldt efter den franske videnskabsmand Blaise Pascal fra 1600-tallet -- Pascal er kendt for sit arbejde inden for hydrodynamik og hydrostatik, og for sine banebrydende trykforsog med barometeret. Pascals opdagelse af, at 'tryk pafort en lukket vaeske overfores lige i alle retninger' (Pascals lov), danner grundlaget for hydrauliske systemer. Enheden blev formelt vedtaget som SI-enhed pa det 14. mode i Generalkonferencen for Mal og Vaegt i 1971, og defineret som newton per kvadratmeter (N/m²).",
    measurementSystem: "Det Internationale Enhedssystem (SI)",
    siEquivalent: "SIs grundlaeggende trykenhed, 1 Pa = 1 N/m²",
    commonUses: "Videnskabelige beregninger, materialeanalyse og referenceomregninger",
  },
  {
    locale: "da",
    sourceSlug: "bar",
    slug: "bar",
    category: "basinc",
    categoryName: "Tryk",
    unit: "bar",
    name: "Bar",
    symbol: "bar",
    shortDescription: "Bar er en trykenhed lig 100 000 pascal. Den er en meget udbredt praktisk visning pa industri- og udstyrsmalere.",
    historySummary: "Bar-enheden blev lanceret af den norske meteorolog Vilhelm Bjerknes, en af pionererne inden for moderne vejrvarsling; navnet kommer fra det oldgraeske ord 'baros', som betyder 'vaegt' (interessant nok blev ordet 'bar' ogsa brugt mellem 1793 og 1795 i det tidlige metriske system om en masseenhed svarende til det nuvaerende ton). 1 bar svarer noejagtigt til 100 000 pascal og ligger meget taet pa det gennemsnitlige atmosfaeretryk ved havoverfladen (omkring 1,013 bar). Selvom bar ikke er en officiel SI-enhed, bruges den stadig meget af meteorologer og luftfartsbranchen i dag, fordi den talmaessigt svarer til millibar/hektopascal og er praktisk i brug.",
    measurementSystem: "Metrisk ingeniorenhed uden for SI",
    siEquivalent: "1 bar = 100 000 Pa",
    commonUses: "Kompressorer, hydraulik, pneumatik og servicemanometre",
  },
  {
    locale: "da",
    sourceSlug: "psi",
    slug: "psi",
    category: "basinc",
    categoryName: "Tryk",
    unit: "psi",
    name: "PSI",
    symbol: "psi",
    shortDescription: "PSI er forkortelsen for pound-force per square inch. Den er en udbredt trykenhed i angloamerikanske tekniske systemer.",
    historySummary: "PSI er, som navnet antyder, en sammensat enhed dannet ved at dividere en kraftenhed (pound-force) med en arealenhed (kvadrattomme), og blev udbredt i britisk ingeniortradition pa 1800-tallet til at angive keteltryk i dampmaskinernes tidsalder. Selvom det metriske system er blevet global standard, er PSI fortsat den de facto branchestandard inden for bilindustri (daektryk), hydrauliske systemer og amerikanskproducerede industrikataloger.",
    measurementSystem: "Britisk og amerikansk ingeniorbrug",
    siEquivalent: "1 psi = 6894,757293168 Pa",
    commonUses: "Daektryk, hydrauliske systemer og teknisk service",
  },
  {
    locale: "da",
    sourceSlug: "atmosfer",
    slug: "atmosfaere",
    category: "basinc",
    categoryName: "Tryk",
    unit: "atm",
    name: "Atmosfaere",
    symbol: "atm",
    shortDescription: "Atmosfaere er en trykenhed baseret pa en referencevaerdi taet pa det gennemsnitlige tryk i jordens atmosfaere ved havoverfladen. Ogsa kaldet standardatmosfaere.",
    historySummary: "Atmosfaere-enheden blev udbredt, efterhanden som barometriske malinger og havoverfladereferencetryk blev brugt som standard sammenligningspunkt i tekniske og videnskabelige arbejder. I 1954 definerede den 10. Generalkonference for Mal og Vaegt (CGPM) standardatmosfaeren til noejagtigt 101 325 Pa.",
    measurementSystem: "Uden for SI, referenceenhed i meteorologi og ingeniorfag",
    siEquivalent: "1 atm = 101 325 Pa (defineret vaerdi)",
    commonUses: "Referenceforhold, meteorologi, vakuum- og trykmalinger",
  },
  // Energi
  {
    locale: "da",
    sourceSlug: "joule",
    slug: "joule",
    category: "enerji",
    categoryName: "Energi",
    unit: "J",
    name: "Joule",
    symbol: "J",
    shortDescription: "Joule er SIs afledte enhed for energi. Den bruges til at udtrykke maengder af arbejde, varme og energi.",
    historySummary: "Enheden blev opkaldt efter den britiske fysiker James Prescott Joule (1818-1889), efter hans arbejde, der klarlagde sammenhaengen mellem mekanisk arbejde og varme. Navnet blev forst foreslaet 23. august 1882, i William Siemens' formandstale for British Association for the Advancement of Science; Siemens foreslog at kalde den 'joule', til aere for 'manden, der har bidraget sa meget til at udvikle den dynamiske varmeteori'. Enheden blev formelt vedtaget 31. august 1889, ved den anden internationale elektriske kongres, sammen med enheden watt -- ved et interessant sammentraef dode Joule senere samme ar (11. oktober 1889). Definitionen blev opdateret i 1946 inden for Giorgi-systemet, og blev nu udtrykt direkte og uafhaengigt af elektromagnetiske enheder, som 'det arbejde, en kraft udforer over en straekning pa en meter'.",
    measurementSystem: "Det Internationale Enhedssystem (SI)",
    siEquivalent: "SIs grundlaeggende energienhed",
    commonUses: "Termodynamik, energibalancer og videnskabelige beregninger",
  },
  {
    locale: "da",
    sourceSlug: "kilovatsaat",
    slug: "kilowattime",
    category: "enerji",
    categoryName: "Energi",
    unit: "kWh",
    name: "Kilowattime",
    symbol: "kWh",
    shortDescription: "Kilowattime er en energienhed meget brugt til at male elforbrug.",
    historySummary: "Pa grund af elmalere og faktureringssystemer er kilowattime blevet en af de mest kendte enheder for praktisk energiforbrug.",
    measurementSystem: "Teknisk og kommerciel energienhed",
    siEquivalent: "1 kWh = 3,6 MJ",
    commonUses: "Elregninger, batterikapacitet og forbrugssammenligninger",
  },
  {
    locale: "da",
    sourceSlug: "kalori",
    slug: "kalorie",
    category: "enerji",
    categoryName: "Energi",
    unit: "cal",
    name: "Kalorie",
    symbol: "cal",
    shortDescription: "Kalorie (cal) er en energienhed uden for SI, defineret som den energimaengde, der kraeves for at haeve temperaturen af et gram vand med 1 °C. Ifolge den termokemiske kaloriedefinition svarer 1 kalorie til 4,184 joule.",
    historySummary: "Kaloriebegrebet blev lanceret pa 1800-tallet af den franske kemiker Nicolas Clément til at male varmemaengde, og blev udbredt i termodynamikkens udviklingsperiode. Selvom SI-enheden joule i vid udstraekning forventes at erstatte den, bruges den stadig meget (som kilokalorie) i ernaeringsvidenskaben.",
    measurementSystem: "Uden for SI, traditionel energienhed",
    siEquivalent: "1 cal = 4,184 J (termokemisk definition)",
    commonUses: "Kemiske og termodynamiske beregninger, madenergi (via kilokalorie)",
  },
  {
    locale: "da",
    sourceSlug: "btu",
    slug: "btu",
    category: "enerji",
    categoryName: "Energi",
    unit: "Btu",
    name: "BTU",
    symbol: "Btu",
    shortDescription: "BTU (British Thermal Unit) er en energienhed brugt i det britiske/amerikanske malesystem, defineret som den energimaengde, der kraeves for at haeve temperaturen af et pund vand med 1 °F.",
    historySummary: "BTU blev udviklet i England i dampmaskinernes tidsalder til at male varmeenergi, og blev efterhanden standardenheden for opvarmnings-/koelebranchen i angloamerikanske lande, saerligt USA.",
    measurementSystem: "Britisk og amerikansk malesystem",
    siEquivalent: "1 Btu = 1055,056 J",
    commonUses: "Klima- og varmeapparatkapacitet (kole-/varmeeffekt), naturgasregninger (USA)",
  },
  // Datalagring
  {
    locale: "da",
    sourceSlug: "bayt",
    slug: "byte",
    category: "veri",
    categoryName: "Datalagring",
    unit: "B",
    name: "Byte",
    symbol: "B",
    shortDescription: "Byte er den grundlaeggende maleenhed for digital data. Den bestar af 8 bit og bruges til at repraesentere et tegn (bogstav, tal osv.).",
    historySummary: "Betegnelsen 'byte' blev bevidst afledt i 1956 af ingenioren Werner Buchholz hos IBM, som arbejdede med Stretch-computeren, ved at aendre skrivemaden af ordet 'bite' for at undga forveksling med ordet 'bit'. I de forste ar kunne en byte vaere af forskellig laengde -- fra 1 til 6 bit -- afhaengigt af den anvendte computerarkitektur; standarden pa 8-bits byte blev den de facto branchestandard med IBMs System/360, som blev lanceret i 1964 og var en af tidens mest indflydelsesrige computerfamilier.",
    measurementSystem: "Digital dataenhed (databehandlingsstandard)",
    siEquivalent: "1 byte = 8 bit",
    commonUses: "Filstorrelse, hukommelseskapacitet og dataoverforingsmaling",
  },
  {
    locale: "da",
    sourceSlug: "megabayt",
    slug: "megabyte",
    category: "veri",
    categoryName: "Datalagring",
    unit: "MB",
    name: "Megabyte",
    symbol: "MB",
    shortDescription: "Megabyte (MB) er en dataenhed lig 1 000 000 byte. Den bruges ofte til at udtrykke storrelsen af billeder, musikfiler og korte dokumenter.",
    historySummary: "Megabyte blev en standard referenceenhed til at udtrykke fil- og diskstorrelser, efterhanden som personlige computere blev udbredt.",
    measurementSystem: "Det Internationale Enhedssystem (SI, multiplum)",
    siEquivalent: "1 MB = 1 000 000 byte",
    commonUses: "Billeder, musikfiler, korte videoer og applikationsstorrelser",
  },
  {
    locale: "da",
    sourceSlug: "gigabayt",
    slug: "gigabyte",
    category: "veri",
    categoryName: "Datalagring",
    unit: "GB",
    name: "Gigabyte",
    symbol: "GB",
    shortDescription: "Gigabyte (GB) er en dataenhed lig 1 milliard byte. Den bruges til at udtrykke lagerplads pa smartphones, videofiler og RAM-kapacitet.",
    historySummary: "Efterhanden som lagringsteknologien udviklede sig, blev gigabyte standardudtryk for disk-, hukommelses- og mobilenhedskapacitet; forskellen mellem SI (1000-baseret) og den traditionelle databehandlingsbrug (1024-baseret) bliver mest maerkbar netop i denne enhed.",
    measurementSystem: "Det Internationale Enhedssystem (SI, multiplum)",
    siEquivalent: "1 GB = 1 000 000 000 byte",
    commonUses: "Lagerplads pa smartphone og computer, RAM-kapacitet, videofiler",
  },
  // Elektricitet
  {
    locale: "da",
    sourceSlug: "volt",
    slug: "volt",
    category: "elektrik",
    categoryName: "Elektricitet",
    unit: "V",
    name: "Volt",
    symbol: "V",
    shortDescription: "Volt er SIs afledte enhed for elektrisk spaending.",
    historySummary: "Enheden er opkaldt efter den italienske fysiker Alessandro Volta -- Volta opfandt 'det voltaiske batteri' i 1800, som resultat af sin diskussion med kollegaen Luigi Galvani om 'animalsk elektricitet'; ved at opdage, at zink og solv var det mest effektive metalpar, skabte han verdens forste apparat, der producerede en kontinuerlig elektrisk strom (forloberen til batteriet). Navnet 'volt' blev foreslaet meget senere, i 1861, af Latimer Clark og Charles Bright. I 1873 definerede British Association for the Advancement of Science formelt enhederne volt, ohm og farad; i 1881 vedtog den internationale elektriske kongres volt som den officielle enhed for elektromotorisk kraft (spaending). Med SI-revisionen i 2019 blev ogsa definitionen af volt opdateret, ved at knytte den elementaere elektriske ladning til en fast vaerdi.",
    measurementSystem: "Det Internationale Enhedssystem (SI)",
    siEquivalent: "SIs grundlaeggende spaendingsenhed",
    commonUses: "Elektroniske kredslob, stromforsyninger og netspaendinger",
  },
  {
    locale: "da",
    sourceSlug: "amper",
    slug: "ampere",
    category: "elektrik",
    categoryName: "Elektricitet",
    unit: "A",
    name: "Ampere",
    symbol: "A",
    shortDescription: "Ampere er standardenheden for en af SIs grundlaeggende storrelser: elektrisk strom.",
    historySummary: "Enheden er opkaldt efter den franske fysiker og matematiker André-Marie Ampère (1775-1836), som lagde grundlaget for elektrodynamikken gennem sit arbejde med elektromagnetisme; Ampère byggede her videre pa opdagelserne af den danske fysiker Hans Christian Ørsted. Ampere blev i 1881 erklaeret standardenheden for elektrisk strom, gennem en international konvention underskrevet ved den internationale elektriske udstilling; den forste definition var en tiendedel af den elektromagnetiske stromenhed i CGS-systemet. Frem til SI-revisionen i 2019 var ampere defineret som den strom, der skaber en magnetisk kraft pa 2×10⁻⁷ newton per meter mellem to parallelle ledere med 1 meters afstand; fra 2019 defineres den direkte ud fra multipla af den elementaere elektriske ladning (fastsat til 1,602176634×10⁻¹⁹ coulomb).",
    measurementSystem: "Det Internationale Enhedssystem (SI)",
    siEquivalent: "SIs grundlaeggende stromenhed",
    commonUses: "Stromalinger, beskyttelsesudstyr og apparatmaerkning",
  },
  {
    locale: "da",
    sourceSlug: "miliamper",
    slug: "milliampere",
    category: "elektrik",
    categoryName: "Elektricitet",
    unit: "mA",
    name: "Milliampere",
    symbol: "mA",
    shortDescription: "Milliampere er en lille stromenhed lig en tusindedel af en ampere.",
    historySummary: "Milliampere-visning blev udbredt for at gore det nemmere at aflaese lave stromvaerdier i elektronik og maleinstrumenter.",
    measurementSystem: "Det Internationale Enhedssystem (SI, delenhed)",
    siEquivalent: "1 mA = 0,001 A",
    commonUses: "Elektroniske kredslob, sensorer og lavstromtest",
  },
  // Guldkarat
  {
    locale: "da",
    sourceSlug: "24-ayar-altin",
    slug: "24-karat-guld",
    category: "altin_ayar",
    categoryName: "Guldkarat",
    unit: "24K",
    name: "24 karat guld",
    symbol: "24K",
    shortDescription: "24 karat guld er 99,9 % rent, naesten helt rent guld. Fordi det er den blodeste karat, bruges det oftest til barrer og investeringsprodukter.",
    historySummary: "Karatsystemet er en traditionel guldsmedstandard, der udtrykker renhedsgraden i en guldlegering pa en skala fra 24; 24 karat repraesenterer ulegeret, rent guld.",
    measurementSystem: "Guldsmedstandard for renhed (karat)",
    siEquivalent: "24 karat = 100 % rent guldindhold",
    commonUses: "Guldbarrer, investeringsguld og brug som renhedsreference",
  },
  {
    locale: "da",
    sourceSlug: "22-ayar-altin",
    slug: "22-karat-guld",
    category: "altin_ayar",
    categoryName: "Guldkarat",
    unit: "22K",
    name: "22 karat guld",
    symbol: "22K",
    shortDescription: "22 karat guld er en legering, hvor 22/24 (omkring 91,6 %) af indholdet er rent guld. Den er almindelig til armbaand og traditionelle smykker i Tyrkiet.",
    historySummary: "22 karat opstar ved, at en lille maengde solv eller kobber legeres ind i rent guld for at reducere blodheden og oege holdbarheden, og er blevet den traditionelle smykkestandard i Tyrkiet og Mellemosten.",
    measurementSystem: "Guldsmedstandard for renhed (karat)",
    siEquivalent: "22 karat = 91,6 % rent guldindhold (22/24)",
    commonUses: "Armbaand, traditionelle smykker og guldgaver",
  },
  {
    locale: "da",
    sourceSlug: "18-ayar-altin",
    slug: "18-karat-guld",
    category: "altin_ayar",
    categoryName: "Guldkarat",
    unit: "18K",
    name: "18 karat guld",
    symbol: "18K",
    shortDescription: "18 karat guld er en legering, hvor 18/24 (75 %) af indholdet er rent guld. Takket vaere den hoje holdbarhed foretraekkes den til dagligsmykker.",
    historySummary: "18 karat, som er hardere og mere ridsebestandigt end rent guld, er blevet den internationale standard saerligt for ringe og dagligsmykker.",
    measurementSystem: "Guldsmedstandard for renhed (karat)",
    siEquivalent: "18 karat = 75 % rent guldindhold (18/24)",
    commonUses: "Ringe, kaeder, dagligsmykker og diamantfatninger",
  },
  // Solvindhold
  {
    locale: "da",
    sourceSlug: "999-ayar-gumus",
    slug: "solv-999",
    category: "gumus_ayar",
    categoryName: "Solvindhold",
    unit: "999",
    name: "Solv 999 (fint)",
    symbol: "999",
    shortDescription: "Solv 999 er 99,9 % rent, naesten helt rent solv, ogsa kaldet 'fint solv'. Fordi det er meget blodt, bruges det hovedsageligt til barrer og investeringsprodukter frem for smykker.",
    historySummary: "I modsaetning til guld udtrykkes solvets renhed direkte i promille; 999 repraesenterer ulegeret, rent solv og bruges som renhedsreference ved handel med aedle metaller.",
    measurementSystem: "Guldsmedstandard for renhed (promille)",
    siEquivalent: "999 = 99,9 % rent solvindhold",
    commonUses: "Solvbarrer, investeringssolv og brug som renhedsreference",
  },
  {
    locale: "da",
    sourceSlug: "925-ayar-gumus",
    slug: "sterlingsolv-925",
    category: "gumus_ayar",
    categoryName: "Solvindhold",
    unit: "925",
    name: "Sterlingsolv (925)",
    symbol: "925",
    shortDescription: "Sterlingsolv indeholder 92,5 % rent solv, hvor resten som regel er kobber. Det er kendt verden over som 'sterling silver' og er den mest brugte solvstandard inden for smykker.",
    historySummary: "Sterlingsolv-standarden opstod i England for at modvirke det rene solvs ekstreme blodhed, og er over tid blevet den faktiske globale standard for solvsmykker og brugsgenstande.",
    measurementSystem: "Guldsmedstandard for renhed (promille)",
    siEquivalent: "925 = 92,5 % rent solvindhold (sterlingsolv)",
    commonUses: "Solvsmykker, ringe, kaeder og solvbestik",
  },
];

export function findDanishUnitPageBySourceSlug(sourceSlug: string) {
  return danishUnitPages.find((page) => page.sourceSlug === sourceSlug);
}

export function findDanishUnitPage(category: string, unit: string) {
  return danishUnitPages.find(
    (page) => page.category === category && page.unit === unit
  );
}
