// Paginas de unidad en espanol -- integradas en el nuevo sistema i18n
// Archivo independiente y nuevo (no modifica los archivos existentes de
// tr/en/de/ar/uz/bn/fr).
// Alcance limitado a las 13 categorias fundamentales que, junto con las
// 4 herramientas universales (pagina de inicio), forman los 17 elementos
// de la identidad del sitio.

export type LocalizedSpanishUnitPage = {
  locale: "es";
  sourceSlug: string;
  slug: string;
  category: string;
  categoryName: string;
  unit: string;
  name: string;
  symbol: string;
  shortDescription: string;
  historySummary: string;
  measurementSystem: string;
  siEquivalent: string;
  commonUses: string;
};

export const spanishUnitPages: LocalizedSpanishUnitPage[] = [
  // Longitud
  {
    locale: "es",
    sourceSlug: "metre",
    slug: "metro",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "m",
    name: "Metro",
    symbol: "m",
    shortDescription: "El metro es la unidad basica del SI para la longitud.",
    historySummary: "Desde 1983, el metro se define con precision a partir de la distancia recorrida por la luz en el vacio en 1/299 792 458 de segundo.",
    measurementSystem: "Sistema Internacional de Unidades (SI)",
    siEquivalent: "Unidad basica del SI para la longitud",
    commonUses: "Construccion, deporte, ciencia y medicion de distancias cotidianas",
  },
  {
    locale: "es",
    sourceSlug: "kilometre",
    slug: "kilometro",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "km",
    name: "Kilometro",
    symbol: "km",
    shortDescription: "El kilometro equivale a 1000 metros y se usa para expresar la distancia entre ciudades.",
    historySummary: "El kilometro se impuso como multiplo del metro dentro de la estructura decimal del sistema metrico, convirtiendose en la unidad estandar de carreteras y mapas.",
    measurementSystem: "Sistema Internacional (SI, multiplo)",
    siEquivalent: "1 km = 1000 m",
    commonUses: "Distancias por carretera, geografia, cartografia e infraestructura",
  },
  {
    locale: "es",
    sourceSlug: "santimetre",
    slug: "centimetro",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "cm",
    name: "Centimetro",
    symbol: "cm",
    shortDescription: "El centimetro equivale a la centesima parte de un metro y se usa para mediciones precisas cotidianas.",
    historySummary: "Introducido con el sistema metrico, el centimetro se convirtio en la unidad practica para medir objetos de tamano pequeno y mediano.",
    measurementSystem: "Sistema Internacional (SI, submultiplo)",
    siEquivalent: "1 cm = 0,01 m",
    commonUses: "Costura, medidas corporales, objetos cotidianos",
  },
  {
    locale: "es",
    sourceSlug: "milimetre",
    slug: "milimetro",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "mm",
    name: "Milimetro",
    symbol: "mm",
    shortDescription: "El milimetro equivale a la milesima parte de un metro, usado para mediciones de alta precision.",
    historySummary: "El milimetro es un submultiplo del sistema metrico adoptado para la ingenieria y la fabricacion de precision.",
    measurementSystem: "Sistema Internacional (SI, submultiplo)",
    siEquivalent: "1 mm = 0,001 m",
    commonUses: "Ingenieria mecanica, planos tecnicos, precision industrial",
  },
  {
    locale: "es",
    sourceSlug: "fit",
    slug: "pie",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "ft",
    name: "Pie",
    symbol: "ft",
    shortDescription: "El pie es una unidad de longitud del sistema imperial, todavia usada en Estados Unidos y el Reino Unido.",
    historySummary: "Historicamente basado en la longitud del pie humano, se estandarizo exactamente en 0,3048 metros en 1959 mediante un acuerdo internacional.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 ft = 0,3048 m",
    commonUses: "Inmobiliario, aviacion (altitud), construccion en Estados Unidos",
  },
  {
    locale: "es",
    sourceSlug: "inc",
    slug: "pulgada",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "in",
    name: "Pulgada",
    symbol: "in",
    shortDescription: "La pulgada es una pequena unidad de longitud imperial, muy usada para pantallas y tuberias.",
    historySummary: "La pulgada toma su nombre del ancho del pulgar humano y se fijo exactamente en 2,54 centimetros en 1959.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 in = 2,54 cm",
    commonUses: "Tamano de pantallas, diametro de tuberias, herramientas",
  },
  {
    locale: "es",
    sourceSlug: "yarda",
    slug: "yarda",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "yd",
    name: "Yarda",
    symbol: "yd",
    shortDescription: "La yarda equivale a 3 pies y se usa especialmente en futbol americano y golf.",
    historySummary: "De origen ingles, la yarda se estandarizo exactamente en 0,9144 metros en el acuerdo internacional de unidades de 1959.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 yd = 0,9144 m",
    commonUses: "Deporte (futbol americano, golf), textil",
  },
  {
    locale: "es",
    sourceSlug: "mil",
    slug: "milla",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "mi",
    name: "Milla",
    symbol: "mi",
    shortDescription: "La milla terrestre es la unidad de distancia vial en Estados Unidos y el Reino Unido.",
    historySummary: "Derivada de la milla romana, la milla moderna (milla terrestre) se fijo exactamente en 1609,344 metros.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 mi = 1609,344 m",
    commonUses: "Distancias por carretera en Estados Unidos y el Reino Unido",
  },

  // Superficie
  {
    locale: "es",
    sourceSlug: "metrekare",
    slug: "metro-cuadrado",
    category: "alan",
    categoryName: "Superficie",
    unit: "m²",
    name: "Metro cuadrado",
    symbol: "m²",
    shortDescription: "El metro cuadrado es la unidad basica del SI para la superficie, la de un cuadrado de un metro de lado.",
    historySummary: "Desde la introduccion del sistema metrico, el metro cuadrado es la unidad estandar en mediciones de construccion y terrenos.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidad basica del SI para la superficie",
    commonUses: "Superficie de edificios, extension de terrenos, planos de construccion",
  },
  {
    locale: "es",
    sourceSlug: "hektar",
    slug: "hectarea",
    category: "alan",
    categoryName: "Superficie",
    unit: "ha",
    name: "Hectarea",
    symbol: "ha",
    shortDescription: "La hectarea es una gran unidad de superficie igual a 10 000 metros cuadrados, usada sobre todo en tierras agricolas.",
    historySummary: "La hectarea se adopto ampliamente para expresar facilmente grandes superficies en agricultura y gestion de terrenos.",
    measurementSystem: "Sistema metrico (fuera del SI, unidad comun)",
    siEquivalent: "1 ha = 10 000 m²",
    commonUses: "Tierras agricolas, silvicultura, urbanismo",
  },
  {
    locale: "es",
    sourceSlug: "akre",
    slug: "acre",
    category: "alan",
    categoryName: "Superficie",
    unit: "ac",
    name: "Acre",
    symbol: "ac",
    shortDescription: "El acre es una unidad de superficie del sistema imperial, muy usada en el sector inmobiliario de Estados Unidos.",
    historySummary: "Historicamente, el acre representaba la superficie que una yunta de bueyes podia arar en un dia; hoy equivale exactamente a 4046,8564224 m².",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 ac ≈ 4046,86 m²",
    commonUses: "Terrenos inmobiliarios y agricolas en Estados Unidos y el Reino Unido",
  },

  // Volumen
  {
    locale: "es",
    sourceSlug: "litre",
    slug: "litro",
    category: "hacim",
    categoryName: "Volumen",
    unit: "L",
    name: "Litro",
    symbol: "L",
    shortDescription: "El litro es la unidad practica de volumen mas usada a diario, igual a 0,001 metros cubicos.",
    historySummary: "El litro se introdujo con el sistema metrico y sigue siendo la unidad estandar para liquidos en todo el mundo.",
    measurementSystem: "Sistema metrico (fuera del SI, unidad comun)",
    siEquivalent: "1 L = 0,001 m³",
    commonUses: "Bebidas, combustible, medidas de cocina",
  },
  {
    locale: "es",
    sourceSlug: "mililitre",
    slug: "mililitro",
    category: "hacim",
    categoryName: "Volumen",
    unit: "mL",
    name: "Mililitro",
    symbol: "mL",
    shortDescription: "El mililitro equivale a la milesima parte de un litro, usado para pequenas cantidades de liquido.",
    historySummary: "Submultiplo del litro, el mililitro se convirtio en la unidad estandar en medicina y cocina para las dosis pequenas.",
    measurementSystem: "Sistema metrico (fuera del SI, submultiplo)",
    siEquivalent: "1 mL = 0,001 L",
    commonUses: "Medicamentos, cosmeticos, medidas culinarias precisas",
  },
  {
    locale: "es",
    sourceSlug: "metrekup",
    slug: "metro-cubico",
    category: "hacim",
    categoryName: "Volumen",
    unit: "m³",
    name: "Metro cubico",
    symbol: "m³",
    shortDescription: "El metro cubico es la unidad de referencia del SI para el volumen.",
    historySummary: "El metro cubico se deriva directamente del metro, la unidad basica de longitud, elevada al cubo.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidad de referencia del SI para el volumen",
    commonUses: "Gas natural, hormigon, grandes volumenes industriales",
  },
  {
    locale: "es",
    sourceSlug: "galon",
    slug: "galon",
    category: "hacim",
    categoryName: "Volumen",
    unit: "gal",
    name: "Galon (US)",
    symbol: "gal",
    shortDescription: "El galon estadounidense es la unidad de volumen liquido usada en Estados Unidos, especialmente para la gasolina.",
    historySummary: "El galon estadounidense (liquido) deriva de antiguas medidas inglesas y difiere del galon imperial britanico.",
    measurementSystem: "Sistema estadounidense (US customary)",
    siEquivalent: "1 gal (US) ≈ 3,785 L",
    commonUses: "Combustible y bebidas en Estados Unidos",
  },

  // Masa
  {
    locale: "es",
    sourceSlug: "kilogram",
    slug: "kilogramo",
    category: "kutle",
    categoryName: "Masa",
    unit: "kg",
    name: "Kilogramo",
    symbol: "kg",
    shortDescription: "El kilogramo es la unidad basica del SI para la masa.",
    historySummary: "Desde 2019, el kilogramo se define a partir de la constante de Planck, reemplazando al antiguo prototipo metalico conservado en Paris.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidad basica del SI para la masa",
    commonUses: "Peso corporal, envios, cocina",
  },
  {
    locale: "es",
    sourceSlug: "gram",
    slug: "gramo",
    category: "kutle",
    categoryName: "Masa",
    unit: "g",
    name: "Gramo",
    symbol: "g",
    shortDescription: "El gramo equivale a la milesima parte de un kilogramo y se usa para pequenas cantidades de materia.",
    historySummary: "El gramo se definio originalmente como la masa de un centimetro cubico de agua a 4 °C.",
    measurementSystem: "Sistema Internacional (SI, submultiplo)",
    siEquivalent: "1 g = 0,001 kg",
    commonUses: "Cocina, joyeria, laboratorio",
  },
  {
    locale: "es",
    sourceSlug: "miligram",
    slug: "miligramo",
    category: "kutle",
    categoryName: "Masa",
    unit: "mg",
    name: "Miligramo",
    symbol: "mg",
    shortDescription: "El miligramo equivale a la milesima parte de un gramo, usado principalmente en farmacia y quimica.",
    historySummary: "Submultiplo del gramo, el miligramo se convirtio en esencial para la dosificacion precisa de medicamentos.",
    measurementSystem: "Sistema Internacional (SI, submultiplo)",
    siEquivalent: "1 mg = 0,001 g",
    commonUses: "Dosificacion de medicamentos, quimica analitica",
  },
  {
    locale: "es",
    sourceSlug: "ton",
    slug: "tonelada",
    category: "kutle",
    categoryName: "Masa",
    unit: "t",
    name: "Tonelada",
    symbol: "t",
    shortDescription: "La tonelada equivale a 1000 kilogramos y se usa para medir grandes masas.",
    historySummary: "La tonelada metrica se impuso para expresar facilmente grandes masas en la industria y el transporte.",
    measurementSystem: "Sistema metrico (fuera del SI, multiplo)",
    siEquivalent: "1 t = 1000 kg",
    commonUses: "Transporte maritimo, industria pesada, agricultura",
  },
  {
    locale: "es",
    sourceSlug: "pound",
    slug: "libra",
    category: "kutle",
    categoryName: "Masa",
    unit: "lb",
    name: "Libra",
    symbol: "lb",
    shortDescription: "La libra es la unidad de masa del sistema imperial, muy usada en Estados Unidos.",
    historySummary: "La libra avoirdupois moderna se fijo exactamente en 0,45359237 kilogramos en 1959.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 lb = 0,45359237 kg",
    commonUses: "Peso corporal y alimentacion en Estados Unidos",
  },
  {
    locale: "es",
    sourceSlug: "ons",
    slug: "onza",
    category: "kutle",
    categoryName: "Masa",
    unit: "oz",
    name: "Onza",
    symbol: "oz",
    shortDescription: "La onza equivale a un dieciseisavo de libra y se usa para masas pequenas en el sistema imperial.",
    historySummary: "La onza avoirdupois se ha usado durante siglos en Inglaterra para pequenas cantidades de mercancias.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 oz ≈ 28,3495 g",
    commonUses: "Alimentacion y cosmeticos en Estados Unidos",
  },

  // Temperatura
  {
    locale: "es",
    sourceSlug: "santigrat",
    slug: "celsius",
    category: "sicaklik",
    categoryName: "Temperatura",
    unit: "C",
    name: "Celsius",
    symbol: "°C",
    shortDescription: "La escala Celsius se usa en la mayor parte del mundo, con 0 °C como punto de congelacion y 100 °C como punto de ebullicion del agua.",
    historySummary: "Propuesta por el astronomo sueco Anders Celsius en 1742, la escala se invirtio despues para adoptar su forma actual.",
    measurementSystem: "Sistema metrico (escala comun)",
    siEquivalent: "K = °C + 273,15",
    commonUses: "Meteorologia, cocina, ciencia en la mayor parte del mundo",
  },
  {
    locale: "es",
    sourceSlug: "fahrenhayt",
    slug: "fahrenheit",
    category: "sicaklik",
    categoryName: "Temperatura",
    unit: "F",
    name: "Fahrenheit",
    symbol: "°F",
    shortDescription: "La escala Fahrenheit se usa principalmente en Estados Unidos para la temperatura cotidiana.",
    historySummary: "Propuesta en 1724 por el fisico aleman Daniel Gabriel Fahrenheit, basada inicialmente en una mezcla refrigerante.",
    measurementSystem: "Sistema estadounidense (escala comun)",
    siEquivalent: "°C = (°F − 32) × 5/9",
    commonUses: "Meteorologia y cocina en Estados Unidos",
  },
  {
    locale: "es",
    sourceSlug: "kelvin",
    slug: "kelvin",
    category: "sicaklik",
    categoryName: "Temperatura",
    unit: "K",
    name: "Kelvin",
    symbol: "K",
    shortDescription: "El kelvin es la unidad basica del SI para la temperatura, sin valores negativos.",
    historySummary: "Llamado asi en honor al fisico William Thomson (Lord Kelvin), el kelvin parte del cero absoluto, la temperatura mas baja posible.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidad basica del SI para la temperatura",
    commonUses: "Investigacion cientifica, fisica, astronomia",
  },

  // Tiempo
  {
    locale: "es",
    sourceSlug: "saniye",
    slug: "segundo",
    category: "zaman",
    categoryName: "Tiempo",
    unit: "s",
    name: "Segundo",
    symbol: "s",
    shortDescription: "El segundo es la unidad basica del SI para el tiempo.",
    historySummary: "Desde 1967, el segundo se define a partir de 9 192 631 770 periodos de radiacion del atomo de cesio-133.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidad basica del SI para el tiempo",
    commonUses: "Cronometraje deportivo, ciencia, informatica",
  },
  {
    locale: "es",
    sourceSlug: "dakika",
    slug: "minuto",
    category: "zaman",
    categoryName: "Tiempo",
    unit: "min",
    name: "Minuto",
    symbol: "min",
    shortDescription: "El minuto equivale a 60 segundos y es la unidad de tiempo mas usada a diario.",
    historySummary: "La division en 60 unidades proviene del sistema sexagesimal babilonico, todavia usado hoy.",
    measurementSystem: "Aceptado junto al SI",
    siEquivalent: "1 min = 60 s",
    commonUses: "Horarios, cocina, deporte",
  },
  {
    locale: "es",
    sourceSlug: "saat",
    slug: "hora",
    category: "zaman",
    categoryName: "Tiempo",
    unit: "h",
    name: "Hora",
    symbol: "h",
    shortDescription: "La hora equivale a 60 minutos y sirve para organizar el dia.",
    historySummary: "La division del dia en 24 horas se remonta al Antiguo Egipto.",
    measurementSystem: "Aceptado junto al SI",
    siEquivalent: "1 h = 3600 s",
    commonUses: "Tiempo de trabajo, tiempo de viaje, horarios",
  },
  {
    locale: "es",
    sourceSlug: "gun",
    slug: "dia",
    category: "zaman",
    categoryName: "Tiempo",
    unit: "day",
    name: "Dia",
    symbol: "d",
    shortDescription: "El dia corresponde a una rotacion completa de la Tierra sobre si misma, es decir, 24 horas.",
    historySummary: "La duracion del dia se basa en el ciclo dia-noche observado desde la antiguedad.",
    measurementSystem: "Aceptado junto al SI",
    siEquivalent: "1 dia = 86 400 s",
    commonUses: "Calendario, planificacion, calculo de duraciones",
  },

  // Velocidad
  {
    locale: "es",
    sourceSlug: "kilometre-saat",
    slug: "kilometro-hora",
    category: "hiz",
    categoryName: "Velocidad",
    unit: "km/h",
    name: "Kilometro por hora",
    symbol: "km/h",
    shortDescription: "El kilometro por hora es la unidad estandar de velocidad vial en la mayoria de los paises.",
    historySummary: "Adoptada con el sistema metrico, esta unidad se convirtio en la referencia de los limites de velocidad en todo el mundo.",
    measurementSystem: "Sistema metrico (unidad comun)",
    siEquivalent: "1 km/h ≈ 0,278 m/s",
    commonUses: "Velocidad de vehiculos, limites de velocidad",
  },
  {
    locale: "es",
    sourceSlug: "metre-saniye",
    slug: "metro-segundo",
    category: "hiz",
    categoryName: "Velocidad",
    unit: "m/s",
    name: "Metro por segundo",
    symbol: "m/s",
    shortDescription: "El metro por segundo es la unidad SI de velocidad, usada en fisica y meteorologia.",
    historySummary: "Unidad derivada directamente del metro y el segundo, estandar en calculos cientificos.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidad SI derivada de la velocidad",
    commonUses: "Velocidad del viento, calculos fisicos",
  },
  {
    locale: "es",
    sourceSlug: "mil-saat",
    slug: "milla-hora",
    category: "hiz",
    categoryName: "Velocidad",
    unit: "mph",
    name: "Milla por hora",
    symbol: "mph",
    shortDescription: "La milla por hora es la unidad de velocidad vial en Estados Unidos y el Reino Unido.",
    historySummary: "Derivada de la milla terrestre, esta unidad sigue siendo el estandar de las senales de trafico en ambos paises.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 mph ≈ 0,447 m/s",
    commonUses: "Velocidad de vehiculos en Estados Unidos y el Reino Unido",
  },
  {
    locale: "es",
    sourceSlug: "knot",
    slug: "nudo",
    category: "hiz",
    categoryName: "Velocidad",
    unit: "knot",
    name: "Nudo",
    symbol: "kn",
    shortDescription: "El nudo (milla nautica por hora) es la unidad estandar de velocidad en navegacion maritima y aerea.",
    historySummary: "El nombre proviene del metodo historico de contar los nudos de una cuerda arrojada al agua para medir la velocidad de un barco.",
    measurementSystem: "Navegacion maritima/aerea",
    siEquivalent: "1 kn ≈ 0,514 m/s",
    commonUses: "Velocidad de barcos y aviones",
  },

  // Presion
  {
    locale: "es",
    sourceSlug: "pascal",
    slug: "pascal",
    category: "basinc",
    categoryName: "Presion",
    unit: "Pa",
    name: "Pascal",
    symbol: "Pa",
    shortDescription: "El pascal es la unidad SI de presion, igual a un newton por metro cuadrado.",
    historySummary: "Nombrado en honor a Blaise Pascal, adoptado como unidad SI de presion en 1971.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "1 Pa = 1 N/m²",
    commonUses: "Calculos cientificos y de ingenieria",
  },
  {
    locale: "es",
    sourceSlug: "bar",
    slug: "bar",
    category: "basinc",
    categoryName: "Presion",
    unit: "bar",
    name: "Bar",
    symbol: "bar",
    shortDescription: "El bar es una unidad de presion practica cercana a la presion atmosferica media, muy usada en la industria.",
    historySummary: "Introducido a principios del siglo XX por el meteorologo Vilhelm Bjerknes, el bar sigue siendo ampliamente usado pese a la adopcion del pascal.",
    measurementSystem: "Sistema metrico (fuera del SI)",
    siEquivalent: "1 bar = 100 000 Pa",
    commonUses: "Sistemas industriales, compresores, meteorologia",
  },
  {
    locale: "es",
    sourceSlug: "psi",
    slug: "psi",
    category: "basinc",
    categoryName: "Presion",
    unit: "psi",
    name: "PSI",
    symbol: "psi",
    shortDescription: "El PSI (libra-fuerza por pulgada cuadrada) es la unidad de presion del sistema imperial, habitual para neumaticos.",
    historySummary: "El PSI se impuso con el sistema imperial estadounidense, especialmente para la presion de neumaticos y los sistemas hidraulicos.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 psi ≈ 6894,76 Pa",
    commonUses: "Presion de neumaticos, sistemas hidraulicos y neumaticos",
  },
  {
    locale: "es",
    sourceSlug: "atmosfer",
    slug: "atmosfera",
    category: "basinc",
    categoryName: "Presion",
    unit: "atm",
    name: "Atmosfera estandar",
    symbol: "atm",
    shortDescription: "La atmosfera estandar representa aproximadamente la presion atmosferica media al nivel del mar.",
    historySummary: "Definida a partir de las mediciones barometricas de Torricelli en el siglo XVII, sirve de referencia para las condiciones estandar.",
    measurementSystem: "Fuera del SI (unidad de referencia)",
    siEquivalent: "1 atm = 101 325 Pa",
    commonUses: "Condiciones atmosfericas y de referencia",
  },

  // Energia
  {
    locale: "es",
    sourceSlug: "joule",
    slug: "julio",
    category: "enerji",
    categoryName: "Energia",
    unit: "J",
    name: "Julio",
    symbol: "J",
    shortDescription: "El julio es la unidad SI de energia, igual al trabajo de una fuerza de un newton en una distancia de un metro.",
    historySummary: "Nombrado en honor al fisico ingles James Prescott Joule por sus trabajos sobre la energia y el calor.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "1 J = 1 N·m",
    commonUses: "Calculos cientificos y fisicos de energia",
  },
  {
    locale: "es",
    sourceSlug: "kilovatsaat",
    slug: "kilovatio-hora",
    category: "enerji",
    categoryName: "Energia",
    unit: "kWh",
    name: "Kilovatio-hora",
    symbol: "kWh",
    shortDescription: "El kilovatio-hora es la unidad estandar de facturacion del consumo electrico en el mundo.",
    historySummary: "Adoptado con la generalizacion de la electricidad domestica, el kilovatio-hora sigue siendo la unidad de referencia de los contadores electricos.",
    measurementSystem: "Sistema metrico (electricidad)",
    siEquivalent: "1 kWh = 3 600 000 J",
    commonUses: "Facturacion electrica",
  },
  {
    locale: "es",
    sourceSlug: "kalori",
    slug: "caloria",
    category: "enerji",
    categoryName: "Energia",
    unit: "cal",
    name: "Caloria",
    symbol: "cal",
    shortDescription: "La caloria es la energia necesaria para elevar en un grado Celsius la temperatura de un gramo de agua.",
    historySummary: "Definida en el siglo XIX para estudios termicos, la caloria hoy se asocia sobre todo a la nutricion.",
    measurementSystem: "Sistema metrico (tradicional)",
    siEquivalent: "1 cal = 4,184 J",
    commonUses: "Nutricion y quimica",
  },
  {
    locale: "es",
    sourceSlug: "btu",
    slug: "btu",
    category: "enerji",
    categoryName: "Energia",
    unit: "Btu",
    name: "BTU",
    symbol: "BTU",
    shortDescription: "El BTU (British Thermal Unit) expresa la capacidad de los sistemas de calefaccion y aire acondicionado.",
    historySummary: "De origen britanico, el BTU sigue siendo muy usado en Estados Unidos para aparatos termicos.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 Btu ≈ 1055,06 J",
    commonUses: "Climatizacion y calefaccion",
  },

  // Almacenamiento de datos
  {
    locale: "es",
    sourceSlug: "bayt",
    slug: "byte",
    category: "veri",
    categoryName: "Almacenamiento de datos",
    unit: "B",
    name: "Byte",
    symbol: "B",
    shortDescription: "El byte (8 bits) es la unidad basica para representar caracteres y datos digitales.",
    historySummary: "El byte se impuso con el desarrollo de los primeros ordenadores como unidad estandar de procesamiento de datos.",
    measurementSystem: "Informatica",
    siEquivalent: "1 B = 8 bits",
    commonUses: "Tamano de archivos, memoria, almacenamiento",
  },
  {
    locale: "es",
    sourceSlug: "megabayt",
    slug: "megabyte",
    category: "veri",
    categoryName: "Almacenamiento de datos",
    unit: "MB",
    name: "Megabyte",
    symbol: "MB",
    shortDescription: "El megabyte se usa para expresar el tamano de archivos medianos, como fotos o documentos.",
    historySummary: "Con el crecimiento de las capacidades de almacenamiento, el megabyte se convirtio en la unidad habitual para archivos digitales.",
    measurementSystem: "Informatica (base 1000 o 1024)",
    siEquivalent: "1 MB = 1 000 000 B (o 1024² B en base binaria)",
    commonUses: "Tamano de fotos, documentos y aplicaciones",
  },
  {
    locale: "es",
    sourceSlug: "gigabayt",
    slug: "gigabyte",
    category: "veri",
    categoryName: "Almacenamiento de datos",
    unit: "GB",
    name: "Gigabyte",
    symbol: "GB",
    shortDescription: "El gigabyte es la unidad estandar para expresar la capacidad de almacenamiento de moviles y ordenadores.",
    historySummary: "El gigabyte se impuso con el auge del almacenamiento digital masivo (discos duros, memorias USB, moviles).",
    measurementSystem: "Informatica (base 1000 o 1024)",
    siEquivalent: "1 GB = 1 000 000 000 B (o 1024³ B en base binaria)",
    commonUses: "Almacenamiento de moviles, ordenadores y tarifas de internet",
  },

  // Electricidad
  {
    locale: "es",
    sourceSlug: "volt",
    slug: "voltio",
    category: "elektrik",
    categoryName: "Electricidad",
    unit: "V",
    name: "Voltio",
    symbol: "V",
    shortDescription: "El voltio es la unidad SI de diferencia de potencial electrico.",
    historySummary: "Nombrado en honor al fisico italiano Alessandro Volta, inventor de la primera pila electrica.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidad SI de tension electrica",
    commonUses: "Pilas, tomas de corriente, circuitos electronicos",
  },
  {
    locale: "es",
    sourceSlug: "amper",
    slug: "amperio",
    category: "elektrik",
    categoryName: "Electricidad",
    unit: "A",
    name: "Amperio",
    symbol: "A",
    shortDescription: "El amperio es la unidad basica del SI para la corriente electrica.",
    historySummary: "Nombrado en honor al fisico frances Andre-Marie Ampere, pionero del electromagnetismo.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidad basica del SI para la corriente electrica",
    commonUses: "Circuitos electricos, interruptores automaticos, cargadores",
  },
  {
    locale: "es",
    sourceSlug: "miliamper",
    slug: "miliamperio",
    category: "elektrik",
    categoryName: "Electricidad",
    unit: "mA",
    name: "Miliamperio",
    symbol: "mA",
    shortDescription: "El miliamperio equivale a la milesima parte de un amperio y se usa para medir pequenas corrientes en electronica.",
    historySummary: "Submultiplo del amperio, el miliamperio se volvio esencial con el desarrollo de la electronica de precision.",
    measurementSystem: "Sistema Internacional (SI, submultiplo)",
    siEquivalent: "1 mA = 0,001 A",
    commonUses: "Baterias de moviles, sensores, circuitos electronicos",
  },

  // Quilate de oro
  {
    locale: "es",
    sourceSlug: "24-ayar-altin",
    slug: "oro-24-quilates",
    category: "altin_ayar",
    categoryName: "Quilate de oro",
    unit: "24K",
    name: "Oro de 24 quilates",
    symbol: "24K",
    shortDescription: "El oro de 24 quilates es oro puro al 99,9%, la referencia del sistema de quilates.",
    historySummary: "El oro de 24 quilates se usa tradicionalmente para lingotes de inversion debido a su maxima pureza.",
    measurementSystem: "Sistema de quilates",
    siEquivalent: "99,9% de oro puro",
    commonUses: "Lingotes e inversion en oro",
  },
  {
    locale: "es",
    sourceSlug: "22-ayar-altin",
    slug: "oro-22-quilates",
    category: "altin_ayar",
    categoryName: "Quilate de oro",
    unit: "22K",
    name: "Oro de 22 quilates",
    symbol: "22K",
    shortDescription: "El oro de 22 quilates contiene alrededor de un 91,6% de oro puro y es popular en la joyeria tradicional.",
    historySummary: "Muy usado en el sur de Asia y Oriente Medio, equilibra pureza y resistencia para la fabricacion de joyas.",
    measurementSystem: "Sistema de quilates",
    siEquivalent: "≈91,6% de oro puro",
    commonUses: "Joyeria tradicional",
  },
  {
    locale: "es",
    sourceSlug: "18-ayar-altin",
    slug: "oro-18-quilates",
    category: "altin_ayar",
    categoryName: "Quilate de oro",
    unit: "18K",
    name: "Oro de 18 quilates",
    symbol: "18K",
    shortDescription: "El oro de 18 quilates contiene un 75% de oro puro y es el estandar mas comun en la joyeria occidental.",
    historySummary: "Su buen equilibrio entre dureza y pureza lo convierte en la referencia de las joyerias en Europa y America.",
    measurementSystem: "Sistema de quilates",
    siEquivalent: "75% de oro puro",
    commonUses: "Joyeria occidental, anillos de boda",
  },

  // Ley de la plata
  {
    locale: "es",
    sourceSlug: "999-ayar-gumus",
    slug: "plata-999",
    category: "gumus_ayar",
    categoryName: "Ley de la plata",
    unit: "999",
    name: "Plata 999 (fina)",
    symbol: "999",
    shortDescription: "La plata 999 es plata pura al 99,9%, usada principalmente en lingotes de inversion.",
    historySummary: "Su maxima pureza la convierte en el estandar preferido para productos de inversion y lingotes de plata.",
    measurementSystem: "Sistema de milesimas",
    siEquivalent: "99,9% de plata pura",
    commonUses: "Lingotes y plata de inversion",
  },
  {
    locale: "es",
    sourceSlug: "925-ayar-gumus",
    slug: "plata-esterlina-925",
    category: "gumus_ayar",
    categoryName: "Ley de la plata",
    unit: "925",
    name: "Plata esterlina (925)",
    symbol: "925",
    shortDescription: "La plata esterlina contiene un 92,5% de plata pura y es el estandar mundial de la joyeria de plata.",
    historySummary: "El estandar de la plata esterlina se remonta a la Inglaterra del siglo XII y sigue siendo la norma mas reconocida del mundo.",
    measurementSystem: "Sistema de milesimas",
    siEquivalent: "92,5% de plata pura",
    commonUses: "Joyeria y cuberteria",
  },
];

export function findSpanishUnitPageBySourceSlug(sourceSlug: string) {
  return spanishUnitPages.find((page) => page.sourceSlug === sourceSlug);
}

export function findSpanishUnitPage(category: string, unit: string) {
  return spanishUnitPages.find(
    (page) => page.category === category && page.unit === unit
  );
}
