// Pagine di unità in italiano -- integrate nel nuovo sistema i18n.
// File indipendente e nuovo (non modifica i file esistenti di
// tr/en/de/ar/uz/bn/fr/es/pt).
// Ambito limitato alle 13 categorie fondamentali che, insieme ai 4
// strumenti universali (home page), formano i 17 elementi
// dell'identita del sito.

export type LocalizedItalianUnitPage = {
  locale: "it";
  sourceSlug: string;
  slug: string;
  category: string;
  categoryName: string;
  unit: string;
  name: string;
  symbol: string;
  shortDescription: string;
  historySummary: string;
  measurementSystem: string;
  siEquivalent: string;
  commonUses: string;
};

export const italianUnitPages: LocalizedItalianUnitPage[] = [
  // Lunghezza
  {
    locale: "it",
    sourceSlug: "metre",
    slug: "metro",
    category: "uzunluk",
    categoryName: "Lunghezza",
    unit: "m",
    name: "Metro",
    symbol: "m",
    shortDescription: "Il metro e l'unità di base del SI per la lunghezza.",
    historySummary: "Dal 1983, il metro e definito con precisione a partire dalla distanza percorsa dalla luce nel vuoto in 1/299.792.458 di secondo.",
    measurementSystem: "Sistema Internazionale di Unità (SI)",
    siEquivalent: "Unità di base del SI per la lunghezza",
    commonUses: "Edilizia, sport, scienza e misurazione di distanze quotidiane",
  },
  {
    locale: "it",
    sourceSlug: "kilometre",
    slug: "chilometro",
    category: "uzunluk",
    categoryName: "Lunghezza",
    unit: "km",
    name: "Chilometro",
    symbol: "km",
    shortDescription: "Il chilometro equivale a 1000 metri ed e usato per esprimere la distanza tra citta.",
    historySummary: "Il chilometro si e affermato come multiplo del metro all'interno della struttura decimale del sistema metrico, diventando l'unità standard di strade e mappe.",
    measurementSystem: "Sistema Internazionale (SI, multiplo)",
    siEquivalent: "1 km = 1000 m",
    commonUses: "Distanze stradali, geografia, cartografia e infrastrutture",
  },
  {
    locale: "it",
    sourceSlug: "santimetre",
    slug: "centimetro",
    category: "uzunluk",
    categoryName: "Lunghezza",
    unit: "cm",
    name: "Centimetro",
    symbol: "cm",
    shortDescription: "Il centimetro equivale alla centesima parte di un metro ed e usato per misurazioni precise quotidiane.",
    historySummary: "Introdotto con il sistema metrico, il centimetro e diventato l'unità pratica per misurare oggetti di piccole e medie dimensioni.",
    measurementSystem: "Sistema Internazionale (SI, sottomultiplo)",
    siEquivalent: "1 cm = 0,01 m",
    commonUses: "Sartoria, misure corporee, oggetti quotidiani",
  },
  {
    locale: "it",
    sourceSlug: "milimetre",
    slug: "millimetro",
    category: "uzunluk",
    categoryName: "Lunghezza",
    unit: "mm",
    name: "Millimetro",
    symbol: "mm",
    shortDescription: "Il millimetro equivale alla millesima parte di un metro, usato per misurazioni ad alta precisione.",
    historySummary: "Il millimetro e un sottomultiplo del sistema metrico adottato per l'ingegneria e la fabbricazione di precisione.",
    measurementSystem: "Sistema Internazionale (SI, sottomultiplo)",
    siEquivalent: "1 mm = 0,001 m",
    commonUses: "Ingegneria meccanica, disegni tecnici, precisione industriale",
  },
  {
    locale: "it",
    sourceSlug: "fit",
    slug: "piede",
    category: "uzunluk",
    categoryName: "Lunghezza",
    unit: "ft",
    name: "Piede",
    symbol: "ft",
    shortDescription: "Il piede e un'unità di lunghezza del sistema imperiale, ancora usata negli Stati Uniti e nel Regno Unito.",
    historySummary: "Storicamente basato sulla lunghezza del piede umano, fu standardizzato esattamente a 0,3048 metri nel 1959 tramite un accordo internazionale.",
    measurementSystem: "Sistema imperiale/statunitense",
    siEquivalent: "1 ft = 0,3048 m",
    commonUses: "Immobiliare, aviazione (altitudine), edilizia negli Stati Uniti",
  },
  {
    locale: "it",
    sourceSlug: "inc",
    slug: "pollice",
    category: "uzunluk",
    categoryName: "Lunghezza",
    unit: "in",
    name: "Pollice",
    symbol: "in",
    shortDescription: "Il pollice e una piccola unità di lunghezza imperiale, molto usata per schermi e tubazioni.",
    historySummary: "Il pollice prende il nome dalla larghezza del pollice umano e fu fissato esattamente a 2,54 centimetri nel 1959.",
    measurementSystem: "Sistema imperiale/statunitense",
    siEquivalent: "1 in = 2,54 cm",
    commonUses: "Dimensioni degli schermi, diametro delle tubazioni, utensili",
  },
  {
    locale: "it",
    sourceSlug: "yarda",
    slug: "iarda",
    category: "uzunluk",
    categoryName: "Lunghezza",
    unit: "yd",
    name: "Iarda",
    symbol: "yd",
    shortDescription: "La iarda equivale a 3 piedi ed e usata specialmente nel football americano e nel golf.",
    historySummary: "Di origine inglese, la iarda fu standardizzata esattamente a 0,9144 metri nell'accordo internazionale sulle unità del 1959.",
    measurementSystem: "Sistema imperiale/statunitense",
    siEquivalent: "1 yd = 0,9144 m",
    commonUses: "Sport (football americano, golf), tessile",
  },
  {
    locale: "it",
    sourceSlug: "mil",
    slug: "miglio",
    category: "uzunluk",
    categoryName: "Lunghezza",
    unit: "mi",
    name: "Miglio",
    symbol: "mi",
    shortDescription: "Il miglio terrestre e l'unità di distanza stradale negli Stati Uniti e nel Regno Unito.",
    historySummary: "Derivato dal miglio romano, il miglio moderno (miglio terrestre) fu fissato esattamente a 1609,344 metri.",
    measurementSystem: "Sistema imperiale/statunitense",
    siEquivalent: "1 mi = 1609,344 m",
    commonUses: "Distanze stradali negli Stati Uniti e nel Regno Unito",
  },

  // Area
  {
    locale: "it",
    sourceSlug: "metrekare",
    slug: "metro-quadrato",
    category: "alan",
    categoryName: "Area",
    unit: "m²",
    name: "Metro quadrato",
    symbol: "m²",
    shortDescription: "Il metro quadrato e l'unità di base del SI per l'area, quella di un quadrato con il lato di un metro.",
    historySummary: "Dall'introduzione del sistema metrico, il metro quadrato e l'unità standard nelle misurazioni edilizie e dei terreni.",
    measurementSystem: "Sistema Internazionale (SI)",
    siEquivalent: "Unità di base del SI per l'area",
    commonUses: "Area di edifici, estensione di terreni, planimetrie",
  },
  {
    locale: "it",
    sourceSlug: "hektar",
    slug: "ettaro",
    category: "alan",
    categoryName: "Area",
    unit: "ha",
    name: "Ettaro",
    symbol: "ha",
    shortDescription: "L'ettaro e una grande unità di area pari a 10.000 metri quadrati, usata soprattutto per i terreni agricoli.",
    historySummary: "L'ettaro fu ampiamente adottato per esprimere facilmente grandi aree in agricoltura e gestione dei terreni.",
    measurementSystem: "Sistema metrico (fuori dal SI, unità comune)",
    siEquivalent: "1 ha = 10.000 m²",
    commonUses: "Terreni agricoli, silvicoltura, urbanistica",
  },
  {
    locale: "it",
    sourceSlug: "akre",
    slug: "acro",
    category: "alan",
    categoryName: "Area",
    unit: "ac",
    name: "Acro",
    symbol: "ac",
    shortDescription: "L'acro e un'unità di area del sistema imperiale, molto usata nel settore immobiliare statunitense.",
    historySummary: "Storicamente, l'acro rappresentava l'area di terreno che un paio di buoi poteva arare in un giorno; oggi equivale esattamente a 4046,8564224 m².",
    measurementSystem: "Sistema imperiale/statunitense",
    siEquivalent: "1 ac ≈ 4046,86 m²",
    commonUses: "Terreni immobiliari e agricoli negli Stati Uniti e nel Regno Unito",
  },

  // Volume
  {
    locale: "it",
    sourceSlug: "litre",
    slug: "litro",
    category: "hacim",
    categoryName: "Volume",
    unit: "L",
    name: "Litro",
    symbol: "L",
    shortDescription: "Il litro e l'unità pratica di volume più usata nella vita quotidiana, pari a 0,001 metri cubi.",
    historySummary: "Il litro fu introdotto con il sistema metrico e rimane l'unità standard per i liquidi in tutto il mondo.",
    measurementSystem: "Sistema metrico (fuori dal SI, unità comune)",
    siEquivalent: "1 L = 0,001 m³",
    commonUses: "Bevande, carburante, misure da cucina",
  },
  {
    locale: "it",
    sourceSlug: "mililitre",
    slug: "millilitro",
    category: "hacim",
    categoryName: "Volume",
    unit: "mL",
    name: "Millilitro",
    symbol: "mL",
    shortDescription: "Il millilitro equivale alla millesima parte di un litro, usato per piccole quantità di liquido.",
    historySummary: "Sottomultiplo del litro, il millilitro e diventato l'unità standard in medicina e in cucina per le piccole dosi.",
    measurementSystem: "Sistema metrico (fuori dal SI, sottomultiplo)",
    siEquivalent: "1 mL = 0,001 L",
    commonUses: "Farmaci, cosmetici, misure culinarie precise",
  },
  {
    locale: "it",
    sourceSlug: "metrekup",
    slug: "metro-cubo",
    category: "hacim",
    categoryName: "Volume",
    unit: "m³",
    name: "Metro cubo",
    symbol: "m³",
    shortDescription: "Il metro cubo e l'unità di riferimento del SI per il volume.",
    historySummary: "Il metro cubo deriva direttamente dal metro, l'unità di base della lunghezza, elevato al cubo.",
    measurementSystem: "Sistema Internazionale (SI)",
    siEquivalent: "Unità di riferimento del SI per il volume",
    commonUses: "Gas naturale, calcestruzzo, grandi volumi industriali",
  },
  {
    locale: "it",
    sourceSlug: "galon",
    slug: "gallone",
    category: "hacim",
    categoryName: "Volume",
    unit: "gal",
    name: "Gallone (US)",
    symbol: "gal",
    shortDescription: "Il gallone statunitense e l'unità di volume liquido usata negli Stati Uniti, specialmente per la benzina.",
    historySummary: "Il gallone statunitense (liquido) deriva da antiche misure inglesi e differisce dal gallone imperiale britannico.",
    measurementSystem: "Sistema statunitense (US customary)",
    siEquivalent: "1 gal (US) ≈ 3,785 L",
    commonUses: "Carburante e bevande negli Stati Uniti",
  },

  // Massa
  {
    locale: "it",
    sourceSlug: "kilogram",
    slug: "chilogrammo",
    category: "kutle",
    categoryName: "Massa",
    unit: "kg",
    name: "Chilogrammo",
    symbol: "kg",
    shortDescription: "Il chilogrammo e l'unità di base del SI per la massa.",
    historySummary: "Dal 2019, il chilogrammo e definito a partire dalla costante di Planck, sostituendo l'antico prototipo metallico conservato a Parigi.",
    measurementSystem: "Sistema Internazionale (SI)",
    siEquivalent: "Unità di base del SI per la massa",
    commonUses: "Peso corporeo, spedizioni, cucina",
  },
  {
    locale: "it",
    sourceSlug: "gram",
    slug: "grammo",
    category: "kutle",
    categoryName: "Massa",
    unit: "g",
    name: "Grammo",
    symbol: "g",
    shortDescription: "Il grammo equivale alla millesima parte di un chilogrammo ed e usato per piccole quantità di materia.",
    historySummary: "Il grammo fu originariamente definito come la massa di un centimetro cubo d'acqua a 4 °C.",
    measurementSystem: "Sistema Internazionale (SI, sottomultiplo)",
    siEquivalent: "1 g = 0,001 kg",
    commonUses: "Cucina, gioielleria, laboratorio",
  },
  {
    locale: "it",
    sourceSlug: "miligram",
    slug: "milligrammo",
    category: "kutle",
    categoryName: "Massa",
    unit: "mg",
    name: "Milligrammo",
    symbol: "mg",
    shortDescription: "Il milligrammo equivale alla millesima parte di un grammo, usato principalmente in farmacia e chimica.",
    historySummary: "Sottomultiplo del grammo, il milligrammo e diventato essenziale per il dosaggio preciso dei farmaci.",
    measurementSystem: "Sistema Internazionale (SI, sottomultiplo)",
    siEquivalent: "1 mg = 0,001 g",
    commonUses: "Dosaggio di farmaci, chimica analitica",
  },
  {
    locale: "it",
    sourceSlug: "ton",
    slug: "tonnellata",
    category: "kutle",
    categoryName: "Massa",
    unit: "t",
    name: "Tonnellata",
    symbol: "t",
    shortDescription: "La tonnellata equivale a 1000 chilogrammi ed e usata per misurare grandi masse.",
    historySummary: "La tonnellata metrica si e affermata per esprimere facilmente grandi masse nell'industria e nel trasporto.",
    measurementSystem: "Sistema metrico (fuori dal SI, multiplo)",
    siEquivalent: "1 t = 1000 kg",
    commonUses: "Trasporto marittimo, industria pesante, agricoltura",
  },
  {
    locale: "it",
    sourceSlug: "pound",
    slug: "libbra",
    category: "kutle",
    categoryName: "Massa",
    unit: "lb",
    name: "Libbra",
    symbol: "lb",
    shortDescription: "La libbra e l'unità di massa del sistema imperiale, molto usata negli Stati Uniti.",
    historySummary: "La libbra avoirdupois moderna fu fissata esattamente a 0,45359237 chilogrammi nel 1959.",
    measurementSystem: "Sistema imperiale/statunitense",
    siEquivalent: "1 lb = 0,45359237 kg",
    commonUses: "Peso corporeo e alimentazione negli Stati Uniti",
  },
  {
    locale: "it",
    sourceSlug: "ons",
    slug: "oncia",
    category: "kutle",
    categoryName: "Massa",
    unit: "oz",
    name: "Oncia",
    symbol: "oz",
    shortDescription: "L'oncia equivale a un sedicesimo di libbra ed e usata per masse piccole nel sistema imperiale.",
    historySummary: "L'oncia avoirdupois e usata da secoli in Inghilterra per piccole quantità di merci.",
    measurementSystem: "Sistema imperiale/statunitense",
    siEquivalent: "1 oz ≈ 28,3495 g",
    commonUses: "Alimentazione e cosmetici negli Stati Uniti",
  },

  // Temperatura
  {
    locale: "it",
    sourceSlug: "santigrat",
    slug: "celsius",
    category: "sicaklik",
    categoryName: "Temperatura",
    unit: "C",
    name: "Celsius",
    symbol: "°C",
    shortDescription: "La scala Celsius e usata nella maggior parte del mondo, con 0 °C come punto di congelamento e 100 °C come punto di ebollizione dell'acqua.",
    historySummary: "Proposta dall'astronomo svedese Anders Celsius nel 1742, la scala fu poi invertita per assumere la sua forma attuale.",
    measurementSystem: "Sistema metrico (scala comune)",
    siEquivalent: "K = °C + 273,15",
    commonUses: "Meteorologia, vita quotidiana, scienza nella maggior parte del mondo",
  },
  {
    locale: "it",
    sourceSlug: "fahrenhayt",
    slug: "fahrenheit",
    category: "sicaklik",
    categoryName: "Temperatura",
    unit: "F",
    name: "Fahrenheit",
    symbol: "°F",
    shortDescription: "La scala Fahrenheit e usata principalmente negli Stati Uniti per la temperatura quotidiana.",
    historySummary: "Proposta nel 1724 dal fisico tedesco Daniel Gabriel Fahrenheit, inizialmente basata su una miscela refrigerante.",
    measurementSystem: "Sistema statunitense (scala comune)",
    siEquivalent: "°C = (°F − 32) × 5/9",
    commonUses: "Meteorologia e cucina negli Stati Uniti",
  },
  {
    locale: "it",
    sourceSlug: "kelvin",
    slug: "kelvin",
    category: "sicaklik",
    categoryName: "Temperatura",
    unit: "K",
    name: "Kelvin",
    symbol: "K",
    shortDescription: "Il kelvin e l'unità di base del SI per la temperatura, senza valori negativi.",
    historySummary: "Chiamato così in onore del fisico William Thomson (Lord Kelvin), il kelvin parte dallo zero assoluto, la temperatura più bassa possibile.",
    measurementSystem: "Sistema Internazionale (SI)",
    siEquivalent: "Unità di base del SI per la temperatura",
    commonUses: "Ricerca scientifica, fisica, astronomia",
  },

  // Tempo
  {
    locale: "it",
    sourceSlug: "saniye",
    slug: "secondo",
    category: "zaman",
    categoryName: "Tempo",
    unit: "s",
    name: "Secondo",
    symbol: "s",
    shortDescription: "Il secondo e l'unità di base del SI per il tempo.",
    historySummary: "Dal 1967, il secondo e definito a partire da 9.192.631.770 periodi di radiazione dell'atomo di cesio-133.",
    measurementSystem: "Sistema Internazionale (SI)",
    siEquivalent: "Unità di base del SI per il tempo",
    commonUses: "Cronometraggio sportivo, scienza, informatica",
  },
  {
    locale: "it",
    sourceSlug: "dakika",
    slug: "minuto",
    category: "zaman",
    categoryName: "Tempo",
    unit: "min",
    name: "Minuto",
    symbol: "min",
    shortDescription: "Il minuto equivale a 60 secondi ed e l'unità di tempo più usata nella vita quotidiana.",
    historySummary: "La divisione in 60 unità deriva dal sistema numerico sessagesimale babilonese, ancora usato oggi.",
    measurementSystem: "Accettato accanto al SI",
    siEquivalent: "1 min = 60 s",
    commonUses: "Orari, cucina, sport",
  },
  {
    locale: "it",
    sourceSlug: "saat",
    slug: "ora",
    category: "zaman",
    categoryName: "Tempo",
    unit: "h",
    name: "Ora",
    symbol: "h",
    shortDescription: "L'ora equivale a 60 minuti e serve a organizzare la giornata.",
    historySummary: "La divisione del giorno in 24 ore risale all'Antico Egitto.",
    measurementSystem: "Accettato accanto al SI",
    siEquivalent: "1 h = 3600 s",
    commonUses: "Tempo di lavoro, tempo di viaggio, orari",
  },
  {
    locale: "it",
    sourceSlug: "gun",
    slug: "giorno",
    category: "zaman",
    categoryName: "Tempo",
    unit: "day",
    name: "Giorno",
    symbol: "g",
    shortDescription: "Il giorno corrisponde a una rotazione completa della Terra su se stessa, ossia 24 ore.",
    historySummary: "La durata del giorno si basa sul ciclo giorno-notte osservato fin dall'antichita.",
    measurementSystem: "Accettato accanto al SI",
    siEquivalent: "1 giorno = 86.400 s",
    commonUses: "Calendario, pianificazione, calcolo delle durate",
  },

  // Velocità
  {
    locale: "it",
    sourceSlug: "kilometre-saat",
    slug: "chilometro-orario",
    category: "hiz",
    categoryName: "Velocità",
    unit: "km/h",
    name: "Chilometro orario",
    symbol: "km/h",
    shortDescription: "Il chilometro orario e l'unità standard di velocità stradale nella maggior parte dei paesi.",
    historySummary: "Adottata con il sistema metrico, questa unità e diventata il riferimento dei limiti di velocità in tutto il mondo.",
    measurementSystem: "Sistema metrico (unità comune)",
    siEquivalent: "1 km/h ≈ 0,278 m/s",
    commonUses: "Velocità dei veicoli, limiti di velocità",
  },
  {
    locale: "it",
    sourceSlug: "metre-saniye",
    slug: "metro-al-secondo",
    category: "hiz",
    categoryName: "Velocità",
    unit: "m/s",
    name: "Metro al secondo",
    symbol: "m/s",
    shortDescription: "Il metro al secondo e l'unità SI di velocità, usata in fisica e meteorologia.",
    historySummary: "Unità derivata direttamente dal metro e dal secondo, standard nei calcoli scientifici.",
    measurementSystem: "Sistema Internazionale (SI)",
    siEquivalent: "Unità SI derivata della velocità",
    commonUses: "Velocità del vento, calcoli fisici",
  },
  {
    locale: "it",
    sourceSlug: "mil-saat",
    slug: "miglio-orario",
    category: "hiz",
    categoryName: "Velocità",
    unit: "mph",
    name: "Miglio orario",
    symbol: "mph",
    shortDescription: "Il miglio orario e l'unità di velocità stradale negli Stati Uniti e nel Regno Unito.",
    historySummary: "Derivata dal miglio terrestre, questa unità rimane lo standard della segnaletica stradale in entrambi i paesi.",
    measurementSystem: "Sistema imperiale/statunitense",
    siEquivalent: "1 mph ≈ 0,447 m/s",
    commonUses: "Velocità dei veicoli negli USA e nel Regno Unito",
  },
  {
    locale: "it",
    sourceSlug: "knot",
    slug: "nodo",
    category: "hiz",
    categoryName: "Velocità",
    unit: "knot",
    name: "Nodo",
    symbol: "kn",
    shortDescription: "Il nodo (miglio nautico all'ora) e l'unità di velocità standard nella navigazione marittima e aerea.",
    historySummary: "Il nome deriva dal metodo storico usato per contare i nodi di una corda gettata in acqua per misurare la velocità di una nave.",
    measurementSystem: "Navigazione marittima/aerea",
    siEquivalent: "1 kn ≈ 0,514 m/s",
    commonUses: "Velocità di navi e aerei",
  },

  // Pressione
  {
    locale: "it",
    sourceSlug: "pascal",
    slug: "pascal",
    category: "basinc",
    categoryName: "Pressione",
    unit: "Pa",
    name: "Pascal",
    symbol: "Pa",
    shortDescription: "Il pascal e l'unità SI di pressione, pari a un newton per metro quadrato.",
    historySummary: "Chiamato così in onore di Blaise Pascal, adottato come unità SI di pressione nel 1971.",
    measurementSystem: "Sistema Internazionale (SI)",
    siEquivalent: "1 Pa = 1 N/m²",
    commonUses: "Calcoli scientifici e di ingegneria",
  },
  {
    locale: "it",
    sourceSlug: "bar",
    slug: "bar",
    category: "basinc",
    categoryName: "Pressione",
    unit: "bar",
    name: "Bar",
    symbol: "bar",
    shortDescription: "Il bar e un'unità di pressione pratica vicina alla pressione atmosferica media, molto usata nell'industria.",
    historySummary: "Introdotto all'inizio del XX secolo dal meteorologo Vilhelm Bjerknes, il bar rimane ampiamente usato nonostante l'adozione del pascal.",
    measurementSystem: "Sistema metrico (fuori dal SI)",
    siEquivalent: "1 bar = 100.000 Pa",
    commonUses: "Sistemi industriali, compressori, meteorologia",
  },
  {
    locale: "it",
    sourceSlug: "psi",
    slug: "psi",
    category: "basinc",
    categoryName: "Pressione",
    unit: "psi",
    name: "PSI",
    symbol: "psi",
    shortDescription: "Il PSI (libbra-forza per pollice quadrato) e l'unità di pressione del sistema imperiale, comune per gli pneumatici.",
    historySummary: "Il PSI si e affermato con il sistema imperiale statunitense, specialmente per la pressione degli pneumatici e i sistemi idraulici.",
    measurementSystem: "Sistema imperiale/statunitense",
    siEquivalent: "1 psi ≈ 6894,76 Pa",
    commonUses: "Pressione degli pneumatici, sistemi idraulici e pneumatici",
  },
  {
    locale: "it",
    sourceSlug: "atmosfer",
    slug: "atmosfera",
    category: "basinc",
    categoryName: "Pressione",
    unit: "atm",
    name: "Atmosfera standard",
    symbol: "atm",
    shortDescription: "L'atmosfera standard rappresenta approssimativamente la pressione atmosferica media al livello del mare.",
    historySummary: "Definita a partire dalle misurazioni barometriche di Torricelli nel XVII secolo, serve da riferimento per le condizioni standard.",
    measurementSystem: "Fuori dal SI (unità di riferimento)",
    siEquivalent: "1 atm = 101.325 Pa",
    commonUses: "Condizioni atmosferiche e di riferimento",
  },

  // Energia
  {
    locale: "it",
    sourceSlug: "joule",
    slug: "joule",
    category: "enerji",
    categoryName: "Energia",
    unit: "J",
    name: "Joule",
    symbol: "J",
    shortDescription: "Il joule e l'unità SI di energia, pari al lavoro di una forza di un newton su una distanza di un metro.",
    historySummary: "Chiamato così in onore del fisico inglese James Prescott Joule per i suoi lavori su energia e calore.",
    measurementSystem: "Sistema Internazionale (SI)",
    siEquivalent: "1 J = 1 N·m",
    commonUses: "Calcoli scientifici e fisici di energia",
  },
  {
    locale: "it",
    sourceSlug: "kilovatsaat",
    slug: "chilowattora",
    category: "enerji",
    categoryName: "Energia",
    unit: "kWh",
    name: "Chilowattora",
    symbol: "kWh",
    shortDescription: "Il chilowattora e l'unità standard di fatturazione del consumo elettrico nel mondo.",
    historySummary: "Adottato con la diffusione dell'elettricità domestica, il chilowattora rimane l'unità di riferimento dei contatori elettrici.",
    measurementSystem: "Sistema metrico (elettricità)",
    siEquivalent: "1 kWh = 3.600.000 J",
    commonUses: "Fatturazione elettrica",
  },
  {
    locale: "it",
    sourceSlug: "kalori",
    slug: "caloria",
    category: "enerji",
    categoryName: "Energia",
    unit: "cal",
    name: "Caloria",
    symbol: "cal",
    shortDescription: "La caloria e l'energia necessaria per elevare di un grado Celsius la temperatura di un grammo d'acqua.",
    historySummary: "Definita nel XIX secolo per studi termici, la caloria oggi e associata soprattutto alla nutrizione.",
    measurementSystem: "Sistema metrico (tradizionale)",
    siEquivalent: "1 cal = 4,184 J",
    commonUses: "Nutrizione e chimica",
  },
  {
    locale: "it",
    sourceSlug: "btu",
    slug: "btu",
    category: "enerji",
    categoryName: "Energia",
    unit: "Btu",
    name: "BTU",
    symbol: "BTU",
    shortDescription: "Il BTU (British Thermal Unit) esprime la capacita dei sistemi di riscaldamento e climatizzazione.",
    historySummary: "Di origine britannica, il BTU rimane molto usato negli Stati Uniti per gli apparecchi termici.",
    measurementSystem: "Sistema imperiale/statunitense",
    siEquivalent: "1 Btu ≈ 1055,06 J",
    commonUses: "Climatizzazione e riscaldamento",
  },

  // Archiviazione dati
  {
    locale: "it",
    sourceSlug: "bayt",
    slug: "byte",
    category: "veri",
    categoryName: "Archiviazione dati",
    unit: "B",
    name: "Byte",
    symbol: "B",
    shortDescription: "Il byte (8 bit) e l'unità di base per rappresentare caratteri e dati digitali.",
    historySummary: "Il byte si e affermato con lo sviluppo dei primi computer come unità standard di elaborazione dati.",
    measurementSystem: "Informatica",
    siEquivalent: "1 B = 8 bit",
    commonUses: "Dimensione dei file, memoria, archiviazione",
  },
  {
    locale: "it",
    sourceSlug: "megabayt",
    slug: "megabyte",
    category: "veri",
    categoryName: "Archiviazione dati",
    unit: "MB",
    name: "Megabyte",
    symbol: "MB",
    shortDescription: "Il megabyte e usato per esprimere la dimensione di file medi, come foto o documenti.",
    historySummary: "Con la crescita delle capacita di archiviazione, il megabyte e diventato l'unità abituale per i file digitali.",
    measurementSystem: "Informatica (base 1000 o 1024)",
    siEquivalent: "1 MB = 1.000.000 B (o 1024² B in base binaria)",
    commonUses: "Dimensione di foto, documenti e applicazioni",
  },
  {
    locale: "it",
    sourceSlug: "gigabayt",
    slug: "gigabyte",
    category: "veri",
    categoryName: "Archiviazione dati",
    unit: "GB",
    name: "Gigabyte",
    symbol: "GB",
    shortDescription: "Il gigabyte e l'unità standard per esprimere la capacita di archiviazione di cellulari e computer.",
    historySummary: "Il gigabyte si e affermato con la crescita dell'archiviazione digitale massiva (dischi rigidi, chiavette USB, cellulari).",
    measurementSystem: "Informatica (base 1000 o 1024)",
    siEquivalent: "1 GB = 1.000.000.000 B (o 1024³ B in base binaria)",
    commonUses: "Archiviazione di cellulari, computer e tariffe internet",
  },

  // Elettricità
  {
    locale: "it",
    sourceSlug: "volt",
    slug: "volt",
    category: "elektrik",
    categoryName: "Elettricità",
    unit: "V",
    name: "Volt",
    symbol: "V",
    shortDescription: "Il volt e l'unità SI di differenza di potenziale elettrico.",
    historySummary: "Chiamato così in onore del fisico italiano Alessandro Volta, inventore della prima pila elettrica.",
    measurementSystem: "Sistema Internazionale (SI)",
    siEquivalent: "Unità SI di tensione elettrica",
    commonUses: "Pile, prese di corrente, circuiti elettronici",
  },
  {
    locale: "it",
    sourceSlug: "amper",
    slug: "ampere",
    category: "elektrik",
    categoryName: "Elettricità",
    unit: "A",
    name: "Ampere",
    symbol: "A",
    shortDescription: "L'ampere e l'unità di base del SI per la corrente elettrica.",
    historySummary: "Chiamato così in onore del fisico francese Andre-Marie Ampere, pioniere dell'elettromagnetismo.",
    measurementSystem: "Sistema Internazionale (SI)",
    siEquivalent: "Unità di base del SI per la corrente elettrica",
    commonUses: "Circuiti elettrici, interruttori automatici, caricabatterie",
  },
  {
    locale: "it",
    sourceSlug: "miliamper",
    slug: "milliampere",
    category: "elektrik",
    categoryName: "Elettricità",
    unit: "mA",
    name: "Milliampere",
    symbol: "mA",
    shortDescription: "Il milliampere equivale alla millesima parte di un ampere ed e usato per misurare piccole correnti in elettronica.",
    historySummary: "Sottomultiplo dell'ampere, il milliampere e diventato essenziale con lo sviluppo dell'elettronica di precisione.",
    measurementSystem: "Sistema Internazionale (SI, sottomultiplo)",
    siEquivalent: "1 mA = 0,001 A",
    commonUses: "Batterie di cellulari, sensori, circuiti elettronici",
  },

  // Caratura oro
  {
    locale: "it",
    sourceSlug: "24-ayar-altin",
    slug: "oro-24-carati",
    category: "altin_ayar",
    categoryName: "Caratura oro",
    unit: "24K",
    name: "Oro a 24 carati",
    symbol: "24K",
    shortDescription: "L'oro a 24 carati e oro puro al 99,9%, il riferimento del sistema dei carati.",
    historySummary: "L'oro a 24 carati e tradizionalmente usato per lingotti di investimento grazie alla sua massima purezza.",
    measurementSystem: "Sistema dei carati",
    siEquivalent: "99,9% di oro puro",
    commonUses: "Lingotti e investimento in oro",
  },
  {
    locale: "it",
    sourceSlug: "22-ayar-altin",
    slug: "oro-22-carati",
    category: "altin_ayar",
    categoryName: "Caratura oro",
    unit: "22K",
    name: "Oro a 22 carati",
    symbol: "22K",
    shortDescription: "L'oro a 22 carati contiene circa il 91,6% di oro puro ed e diffuso nella gioielleria tradizionale.",
    historySummary: "Molto usato nel sud dell'Asia e in Medio Oriente, bilancia purezza e resistenza per la fabbricazione di gioielli.",
    measurementSystem: "Sistema dei carati",
    siEquivalent: "≈91,6% di oro puro",
    commonUses: "Gioielleria tradizionale",
  },
  {
    locale: "it",
    sourceSlug: "18-ayar-altin",
    slug: "oro-18-carati",
    category: "altin_ayar",
    categoryName: "Caratura oro",
    unit: "18K",
    name: "Oro a 18 carati",
    symbol: "18K",
    shortDescription: "L'oro a 18 carati contiene il 75% di oro puro ed e lo standard più comune nella gioielleria occidentale.",
    historySummary: "Il suo buon equilibrio tra durezza e purezza lo rende il riferimento delle gioiellerie in Europa e nelle Americhe.",
    measurementSystem: "Sistema dei carati",
    siEquivalent: "75% di oro puro",
    commonUses: "Gioielleria occidentale, fedi nuziali",
  },

  // Titolo argento
  {
    locale: "it",
    sourceSlug: "999-ayar-gumus",
    slug: "argento-999",
    category: "gumus_ayar",
    categoryName: "Titolo argento",
    unit: "999",
    name: "Argento 999 (fino)",
    symbol: "999",
    shortDescription: "L'argento 999 e argento puro al 99,9%, usato principalmente in lingotti di investimento.",
    historySummary: "La sua massima purezza lo rende lo standard preferito per prodotti di investimento e lingotti d'argento.",
    measurementSystem: "Sistema dei millesimi",
    siEquivalent: "99,9% di argento puro",
    commonUses: "Lingotti e argento da investimento",
  },
  {
    locale: "it",
    sourceSlug: "925-ayar-gumus",
    slug: "argento-sterling-925",
    category: "gumus_ayar",
    categoryName: "Titolo argento",
    unit: "925",
    name: "Argento sterling (925)",
    symbol: "925",
    shortDescription: "L'argento sterling contiene il 92,5% di argento puro ed e lo standard mondiale della gioielleria d'argento.",
    historySummary: "Lo standard dell'argento sterling risale all'Inghilterra del XII secolo e rimane la norma più riconosciuta al mondo.",
    measurementSystem: "Sistema dei millesimi",
    siEquivalent: "92,5% di argento puro",
    commonUses: "Gioielleria e posateria",
  },
];

export function findItalianUnitPageBySourceSlug(sourceSlug: string) {
  return italianUnitPages.find((page) => page.sourceSlug === sourceSlug);
}

export function findItalianUnitPage(category: string, unit: string) {
  return italianUnitPages.find(
    (page) => page.category === category && page.unit === unit
  );
}
