// Paginas de unidade em portugues (Brasil) -- integradas ao novo sistema
// i18n. Arquivo independente e novo (nao modifica os arquivos existentes
// de tr/en/de/ar/uz/bn/fr/es).
// Escopo limitado as 13 categorias fundamentais que, junto com as 4
// ferramentas universais (pagina inicial), formam os 17 elementos da
// identidade do site.

export type LocalizedPortugueseUnitPage = {
  locale: "pt";
  sourceSlug: string;
  slug: string;
  category: string;
  categoryName: string;
  unit: string;
  name: string;
  symbol: string;
  shortDescription: string;
  historySummary: string;
  measurementSystem: string;
  siEquivalent: string;
  commonUses: string;
};

export const portugueseUnitPages: LocalizedPortugueseUnitPage[] = [
  // Comprimento
  {
    locale: "pt",
    sourceSlug: "metre",
    slug: "metro",
    category: "uzunluk",
    categoryName: "Comprimento",
    unit: "m",
    name: "Metro",
    symbol: "m",
    shortDescription: "O metro é a unidade básica do SI para o comprimento.",
    historySummary: "Desde 1983, o metro é definido com precisão a partir da distância percorrida pela luz no vácuo em 1/299.792.458 de segundo.",
    measurementSystem: "Sistema Internacional de Unidades (SI)",
    siEquivalent: "Unidade básica do SI para o comprimento",
    commonUses: "Construção, esporte, ciência e medição de distâncias cotidianas",
  },
  {
    locale: "pt",
    sourceSlug: "kilometre",
    slug: "quilometro",
    category: "uzunluk",
    categoryName: "Comprimento",
    unit: "km",
    name: "Quilômetro",
    symbol: "km",
    shortDescription: "O quilômetro equivale a 1000 metros e é usado para expressar a distância entre cidades.",
    historySummary: "O quilômetro se consolidou como múltiplo do metro dentro da estrutura decimal do sistema métrico, tornando-se a unidade padrão de estradas e mapas.",
    measurementSystem: "Sistema Internacional (SI, múltiplo)",
    siEquivalent: "1 km = 1000 m",
    commonUses: "Distâncias rodoviárias, geografia, cartografia e infraestrutura",
  },
  {
    locale: "pt",
    sourceSlug: "santimetre",
    slug: "centimetro",
    category: "uzunluk",
    categoryName: "Comprimento",
    unit: "cm",
    name: "Centímetro",
    symbol: "cm",
    shortDescription: "O centímetro equivale à centésima parte de um metro e é usado para medições precisas cotidianas.",
    historySummary: "Introduzido com o sistema métrico, o centímetro se tornou a unidade prática para medir objetos de tamanho pequeno e médio.",
    measurementSystem: "Sistema Internacional (SI, submúltiplo)",
    siEquivalent: "1 cm = 0,01 m",
    commonUses: "Costura, medidas corporais, objetos cotidianos",
  },
  {
    locale: "pt",
    sourceSlug: "milimetre",
    slug: "milimetro",
    category: "uzunluk",
    categoryName: "Comprimento",
    unit: "mm",
    name: "Milímetro",
    symbol: "mm",
    shortDescription: "O milímetro equivale à milésima parte de um metro, usado para medições de alta precisão.",
    historySummary: "O milímetro é um submúltiplo do sistema métrico adotado para engenharia e fabricação de precisão.",
    measurementSystem: "Sistema Internacional (SI, submúltiplo)",
    siEquivalent: "1 mm = 0,001 m",
    commonUses: "Engenharia mecânica, desenhos técnicos, precisão industrial",
  },
  {
    locale: "pt",
    sourceSlug: "fit",
    slug: "pe",
    category: "uzunluk",
    categoryName: "Comprimento",
    unit: "ft",
    name: "Pé",
    symbol: "ft",
    shortDescription: "O pé é uma unidade de comprimento do sistema imperial, ainda usada nos Estados Unidos e no Reino Unido.",
    historySummary: "Historicamente baseado no comprimento do pé humano, foi padronizado exatamente em 0,3048 metro em 1959 por um acordo internacional.",
    measurementSystem: "Sistema imperial/norte-americano",
    siEquivalent: "1 ft = 0,3048 m",
    commonUses: "Imobiliário, aviação (altitude), construção nos Estados Unidos",
  },
  {
    locale: "pt",
    sourceSlug: "inc",
    slug: "polegada",
    category: "uzunluk",
    categoryName: "Comprimento",
    unit: "in",
    name: "Polegada",
    symbol: "in",
    shortDescription: "A polegada é uma pequena unidade de comprimento imperial, muito usada para telas e tubulações.",
    historySummary: "A polegada leva o nome da largura do polegar humano e foi fixada exatamente em 2,54 centímetros em 1959.",
    measurementSystem: "Sistema imperial/norte-americano",
    siEquivalent: "1 in = 2,54 cm",
    commonUses: "Tamanho de telas, diâmetro de tubulações, ferramentas",
  },
  {
    locale: "pt",
    sourceSlug: "yarda",
    slug: "jarda",
    category: "uzunluk",
    categoryName: "Comprimento",
    unit: "yd",
    name: "Jarda",
    symbol: "yd",
    shortDescription: "A jarda equivale a 3 pés e é usada especialmente no futebol americano e no golfe.",
    historySummary: "De origem inglesa, a jarda foi padronizada exatamente em 0,9144 metro no acordo internacional de unidades de 1959.",
    measurementSystem: "Sistema imperial/norte-americano",
    siEquivalent: "1 yd = 0,9144 m",
    commonUses: "Esporte (futebol americano, golfe), têxtil",
  },
  {
    locale: "pt",
    sourceSlug: "mil",
    slug: "milha",
    category: "uzunluk",
    categoryName: "Comprimento",
    unit: "mi",
    name: "Milha",
    symbol: "mi",
    shortDescription: "A milha terrestre é a unidade de distância rodoviária nos Estados Unidos e no Reino Unido.",
    historySummary: "Derivada da milha romana, a milha moderna (milha terrestre) foi fixada exatamente em 1609,344 metros.",
    measurementSystem: "Sistema imperial/norte-americano",
    siEquivalent: "1 mi = 1609,344 m",
    commonUses: "Distâncias rodoviárias nos Estados Unidos e no Reino Unido",
  },

  // Area
  {
    locale: "pt",
    sourceSlug: "metrekare",
    slug: "metro-quadrado",
    category: "alan",
    categoryName: "Área",
    unit: "m²",
    name: "Metro quadrado",
    symbol: "m²",
    shortDescription: "O metro quadrado é a unidade básica do SI para área, a de um quadrado de um metro de lado.",
    historySummary: "Desde a introdução do sistema métrico, o metro quadrado é a unidade padrão em medições de construção e terrenos.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidade básica do SI para a área",
    commonUses: "Área de edifícios, extensão de terrenos, plantas de construção",
  },
  {
    locale: "pt",
    sourceSlug: "hektar",
    slug: "hectare",
    category: "alan",
    categoryName: "Área",
    unit: "ha",
    name: "Hectare",
    symbol: "ha",
    shortDescription: "O hectare é uma grande unidade de área igual a 10.000 metros quadrados, usada sobretudo em terras agrícolas.",
    historySummary: "O hectare foi amplamente adotado para expressar facilmente grandes áreas na agricultura e na gestão de terrenos.",
    measurementSystem: "Sistema métrico (fora do SI, unidade comum)",
    siEquivalent: "1 ha = 10.000 m²",
    commonUses: "Terras agrícolas, silvicultura, planejamento urbano",
  },
  {
    locale: "pt",
    sourceSlug: "akre",
    slug: "acre",
    category: "alan",
    categoryName: "Área",
    unit: "ac",
    name: "Acre",
    symbol: "ac",
    shortDescription: "O acre é uma unidade de área do sistema imperial, muito usada no mercado imobiliário dos Estados Unidos.",
    historySummary: "Historicamente, o acre representava a área que uma junta de bois conseguia arar em um dia; hoje equivale exatamente a 4046,8564224 m².",
    measurementSystem: "Sistema imperial/norte-americano",
    siEquivalent: "1 ac ≈ 4046,86 m²",
    commonUses: "Terrenos imobiliários e agrícolas nos Estados Unidos e no Reino Unido",
  },

  // Volume
  {
    locale: "pt",
    sourceSlug: "litre",
    slug: "litro",
    category: "hacim",
    categoryName: "Volume",
    unit: "L",
    name: "Litro",
    symbol: "L",
    shortDescription: "O litro é a unidade prática de volume mais usada no dia a dia, igual a 0,001 metro cúbico.",
    historySummary: "O litro foi introduzido com o sistema métrico e continua sendo a unidade padrão para líquidos no mundo todo.",
    measurementSystem: "Sistema métrico (fora do SI, unidade comum)",
    siEquivalent: "1 L = 0,001 m³",
    commonUses: "Bebidas, combustível, medidas de cozinha",
  },
  {
    locale: "pt",
    sourceSlug: "mililitre",
    slug: "mililitro",
    category: "hacim",
    categoryName: "Volume",
    unit: "mL",
    name: "Mililitro",
    symbol: "mL",
    shortDescription: "O mililitro equivale à milésima parte de um litro, usado para pequenas quantidades de líquido.",
    historySummary: "Submúltiplo do litro, o mililitro se tornou a unidade padrão em medicina e culinária para pequenas doses.",
    measurementSystem: "Sistema métrico (fora do SI, submúltiplo)",
    siEquivalent: "1 mL = 0,001 L",
    commonUses: "Medicamentos, cosméticos, medidas culinárias precisas",
  },
  {
    locale: "pt",
    sourceSlug: "metrekup",
    slug: "metro-cubico",
    category: "hacim",
    categoryName: "Volume",
    unit: "m³",
    name: "Metro cúbico",
    symbol: "m³",
    shortDescription: "O metro cúbico é a unidade de referência do SI para o volume.",
    historySummary: "O metro cúbico deriva diretamente do metro, a unidade básica de comprimento, elevada ao cubo.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidade de referência do SI para o volume",
    commonUses: "Gás natural, concreto, grandes volumes industriais",
  },
  {
    locale: "pt",
    sourceSlug: "galon",
    slug: "galao",
    category: "hacim",
    categoryName: "Volume",
    unit: "gal",
    name: "Galão (US)",
    symbol: "gal",
    shortDescription: "O galão norte-americano é a unidade de volume líquido usada nos Estados Unidos, especialmente para gasolina.",
    historySummary: "O galão norte-americano (líquido) deriva de antigas medidas inglesas e difere do galão imperial britânico.",
    measurementSystem: "Sistema norte-americano (US customary)",
    siEquivalent: "1 gal (US) ≈ 3,785 L",
    commonUses: "Combustível e bebidas nos Estados Unidos",
  },

  // Massa
  {
    locale: "pt",
    sourceSlug: "kilogram",
    slug: "quilograma",
    category: "kutle",
    categoryName: "Massa",
    unit: "kg",
    name: "Quilograma",
    symbol: "kg",
    shortDescription: "O quilograma é a unidade básica do SI para a massa.",
    historySummary: "Desde 2019, o quilograma é definido a partir da constante de Planck, substituindo o antigo protótipo metálico guardado em Paris.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidade básica do SI para a massa",
    commonUses: "Peso corporal, encomendas, culinária",
  },
  {
    locale: "pt",
    sourceSlug: "arroba",
    slug: "arroba",
    category: "kutle",
    categoryName: "Massa",
    unit: "@",
    name: "Arroba",
    symbol: "@",
    shortDescription: "No Brasil, a arroba equivale a 15 quilogramas e é a unidade de referência na pecuária: o preço do boi gordo é cotado em reais por arroba.",
    historySummary: "A arroba é uma antiga unidade de peso de origem ibérica. No Brasil, foi fixada em 15 kg e continua em uso no comércio de gado e em cotações agropecuárias, mesmo após a adoção do sistema métrico.",
    measurementSystem: "Unidade tradicional brasileira, fora do SI",
    siEquivalent: "1 @ = 15 kg",
    commonUses: "Pecuária (boi gordo), comércio de gado e cotações agropecuárias",
  },
  {
    locale: "pt",
    sourceSlug: "gram",
    slug: "grama",
    category: "kutle",
    categoryName: "Massa",
    unit: "g",
    name: "Grama",
    symbol: "g",
    shortDescription: "O grama equivale à milésima parte de um quilograma e é usado para pequenas quantidades de matéria.",
    historySummary: "O grama foi originalmente definido como a massa de um centímetro cúbico de água a 4 °C.",
    measurementSystem: "Sistema Internacional (SI, submúltiplo)",
    siEquivalent: "1 g = 0,001 kg",
    commonUses: "Culinária, joalheria, laboratório",
  },
  {
    locale: "pt",
    sourceSlug: "miligram",
    slug: "miligrama",
    category: "kutle",
    categoryName: "Massa",
    unit: "mg",
    name: "Miligrama",
    symbol: "mg",
    shortDescription: "O miligrama equivale à milésima parte de um grama, usado principalmente em farmácia e química.",
    historySummary: "Submúltiplo do grama, o miligrama se tornou essencial para a dosagem precisa de medicamentos.",
    measurementSystem: "Sistema Internacional (SI, submúltiplo)",
    siEquivalent: "1 mg = 0,001 g",
    commonUses: "Dosagem de medicamentos, química analítica",
  },
  {
    locale: "pt",
    sourceSlug: "ton",
    slug: "tonelada",
    category: "kutle",
    categoryName: "Massa",
    unit: "t",
    name: "Tonelada",
    symbol: "t",
    shortDescription: "A tonelada equivale a 1000 quilogramas e é usada para medir grandes massas.",
    historySummary: "A tonelada métrica se consolidou para expressar facilmente grandes massas na indústria e no transporte.",
    measurementSystem: "Sistema métrico (fora do SI, múltiplo)",
    siEquivalent: "1 t = 1000 kg",
    commonUses: "Transporte marítimo, indústria pesada, agricultura",
  },
  {
    locale: "pt",
    sourceSlug: "pound",
    slug: "libra",
    category: "kutle",
    categoryName: "Massa",
    unit: "lb",
    name: "Libra",
    symbol: "lb",
    shortDescription: "A libra é a unidade de massa do sistema imperial, muito usada nos Estados Unidos.",
    historySummary: "A libra avoirdupois moderna foi fixada exatamente em 0,45359237 quilograma em 1959.",
    measurementSystem: "Sistema imperial/norte-americano",
    siEquivalent: "1 lb = 0,45359237 kg",
    commonUses: "Peso corporal e alimentação nos Estados Unidos",
  },
  {
    locale: "pt",
    sourceSlug: "ons",
    slug: "onca",
    category: "kutle",
    categoryName: "Massa",
    unit: "oz",
    name: "Onça",
    symbol: "oz",
    shortDescription: "A onça equivale a um dezesseis avos de libra e é usada para massas pequenas no sistema imperial.",
    historySummary: "A onça avoirdupois é usada há séculos na Inglaterra para pequenas quantidades de mercadorias.",
    measurementSystem: "Sistema imperial/norte-americano",
    siEquivalent: "1 oz ≈ 28,3495 g",
    commonUses: "Alimentação e cosméticos nos Estados Unidos",
  },

  // Temperatura
  {
    locale: "pt",
    sourceSlug: "santigrat",
    slug: "celsius",
    category: "sicaklik",
    categoryName: "Temperatura",
    unit: "C",
    name: "Celsius",
    symbol: "°C",
    shortDescription: "A escala Celsius é usada na maior parte do mundo, com 0 °C como ponto de congelamento e 100 °C como ponto de ebulição da água.",
    historySummary: "Proposta pelo astrônomo sueco Anders Celsius em 1742, a escala foi invertida depois para adotar sua forma atual.",
    measurementSystem: "Sistema métrico (escala comum)",
    siEquivalent: "K = °C + 273,15",
    commonUses: "Meteorologia, culinária, ciência na maior parte do mundo",
  },
  {
    locale: "pt",
    sourceSlug: "fahrenhayt",
    slug: "fahrenheit",
    category: "sicaklik",
    categoryName: "Temperatura",
    unit: "F",
    name: "Fahrenheit",
    symbol: "°F",
    shortDescription: "A escala Fahrenheit é usada principalmente nos Estados Unidos para a temperatura cotidiana.",
    historySummary: "Proposta em 1724 pelo físico alemão Daniel Gabriel Fahrenheit, baseada inicialmente em uma mistura refrigerante.",
    measurementSystem: "Sistema norte-americano (escala comum)",
    siEquivalent: "°C = (°F − 32) × 5/9",
    commonUses: "Meteorologia e culinária nos Estados Unidos",
  },
  {
    locale: "pt",
    sourceSlug: "kelvin",
    slug: "kelvin",
    category: "sicaklik",
    categoryName: "Temperatura",
    unit: "K",
    name: "Kelvin",
    symbol: "K",
    shortDescription: "O kelvin é a unidade básica do SI para temperatura, sem valores negativos.",
    historySummary: "Recebeu esse nome em homenagem ao físico William Thomson (Lord Kelvin), o kelvin parte do zero absoluto, a temperatura mais baixa possível.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidade básica do SI para a temperatura",
    commonUses: "Pesquisa científica, física, astronomia",
  },

  // Tempo
  {
    locale: "pt",
    sourceSlug: "saniye",
    slug: "segundo",
    category: "zaman",
    categoryName: "Tempo",
    unit: "s",
    name: "Segundo",
    symbol: "s",
    shortDescription: "O segundo é a unidade básica do SI para o tempo.",
    historySummary: "Desde 1967, o segundo é definido a partir de 9.192.631.770 períodos de radiação do átomo de césio-133.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidade básica do SI para o tempo",
    commonUses: "Cronometragem esportiva, ciência, computação",
  },
  {
    locale: "pt",
    sourceSlug: "dakika",
    slug: "minuto",
    category: "zaman",
    categoryName: "Tempo",
    unit: "min",
    name: "Minuto",
    symbol: "min",
    shortDescription: "O minuto equivale a 60 segundos e é a unidade de tempo mais usada no dia a dia.",
    historySummary: "A divisão em 60 unidades vem do sistema sexagesimal babilônico, ainda usado hoje.",
    measurementSystem: "Aceito junto ao SI",
    siEquivalent: "1 min = 60 s",
    commonUses: "Horários, culinária, esporte",
  },
  {
    locale: "pt",
    sourceSlug: "saat",
    slug: "hora",
    category: "zaman",
    categoryName: "Tempo",
    unit: "h",
    name: "Hora",
    symbol: "h",
    shortDescription: "A hora equivale a 60 minutos e serve para organizar o dia.",
    historySummary: "A divisão do dia em 24 horas remonta ao Antigo Egito.",
    measurementSystem: "Aceito junto ao SI",
    siEquivalent: "1 h = 3600 s",
    commonUses: "Tempo de trabalho, tempo de viagem, horários",
  },
  {
    locale: "pt",
    sourceSlug: "gun",
    slug: "dia",
    category: "zaman",
    categoryName: "Tempo",
    unit: "day",
    name: "Dia",
    symbol: "d",
    shortDescription: "O dia corresponde a uma rotação completa da Terra em torno de si mesma, ou seja, 24 horas.",
    historySummary: "A duração do dia se baseia no ciclo dia-noite observado desde a antiguidade.",
    measurementSystem: "Aceito junto ao SI",
    siEquivalent: "1 dia = 86.400 s",
    commonUses: "Calendário, planejamento, cálculo de durações",
  },

  // Velocidade
  {
    locale: "pt",
    sourceSlug: "kilometre-saat",
    slug: "quilometro-hora",
    category: "hiz",
    categoryName: "Velocidade",
    unit: "km/h",
    name: "Quilômetro por hora",
    symbol: "km/h",
    shortDescription: "O quilômetro por hora é a unidade padrão de velocidade rodoviária na maioria dos países.",
    historySummary: "Adotada com o sistema métrico, essa unidade se tornou a referência dos limites de velocidade no mundo todo.",
    measurementSystem: "Sistema métrico (unidade comum)",
    siEquivalent: "1 km/h ≈ 0,278 m/s",
    commonUses: "Velocidade de veículos, limites de velocidade",
  },
  {
    locale: "pt",
    sourceSlug: "metre-saniye",
    slug: "metro-segundo",
    category: "hiz",
    categoryName: "Velocidade",
    unit: "m/s",
    name: "Metro por segundo",
    symbol: "m/s",
    shortDescription: "O metro por segundo é a unidade SI de velocidade, usada em física e meteorologia.",
    historySummary: "Unidade derivada diretamente do metro e do segundo, padrão em cálculos científicos.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidade SI derivada da velocidade",
    commonUses: "Velocidade do vento, cálculos físicos",
  },
  {
    locale: "pt",
    sourceSlug: "mil-saat",
    slug: "milha-hora",
    category: "hiz",
    categoryName: "Velocidade",
    unit: "mph",
    name: "Milha por hora",
    symbol: "mph",
    shortDescription: "A milha por hora é a unidade de velocidade rodoviária nos Estados Unidos e no Reino Unido.",
    historySummary: "Derivada da milha terrestre, essa unidade continua sendo o padrão das placas de trânsito em ambos os países.",
    measurementSystem: "Sistema imperial/norte-americano",
    siEquivalent: "1 mph ≈ 0,447 m/s",
    commonUses: "Velocidade de veículos nos Estados Unidos e no Reino Unido",
  },
  {
    locale: "pt",
    sourceSlug: "knot",
    slug: "no",
    category: "hiz",
    categoryName: "Velocidade",
    unit: "knot",
    name: "No",
    symbol: "kn",
    shortDescription: "O nó (milha náutica por hora) é a unidade padrão de velocidade na navegação marítima e aérea.",
    historySummary: "O nome vem do método histórico de contar os nós de uma corda jogada na água para medir a velocidade de um navio.",
    measurementSystem: "Navegação marítima/aérea",
    siEquivalent: "1 kn ≈ 0,514 m/s",
    commonUses: "Velocidade de navios e aviões",
  },

  // Pressao
  {
    locale: "pt",
    sourceSlug: "pascal",
    slug: "pascal",
    category: "basinc",
    categoryName: "Pressão",
    unit: "Pa",
    name: "Pascal",
    symbol: "Pa",
    shortDescription: "O pascal é a unidade SI de pressão, igual a um newton por metro quadrado.",
    historySummary: "Recebeu esse nome em homenagem a Blaise Pascal, adotado como unidade SI de pressão em 1971.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "1 Pa = 1 N/m²",
    commonUses: "Cálculos científicos e de engenharia",
  },
  {
    locale: "pt",
    sourceSlug: "bar",
    slug: "bar",
    category: "basinc",
    categoryName: "Pressão",
    unit: "bar",
    name: "Bar",
    symbol: "bar",
    shortDescription: "O bar é uma unidade de pressão prática próxima da pressão atmosférica média, muito usada na indústria.",
    historySummary: "Introduzido no início do século XX pelo meteorologista Vilhelm Bjerknes, o bar continua amplamente usado apesar da adoção do pascal.",
    measurementSystem: "Sistema métrico (fora do SI)",
    siEquivalent: "1 bar = 100.000 Pa",
    commonUses: "Sistemas industriais, compressores, meteorologia",
  },
  {
    locale: "pt",
    sourceSlug: "psi",
    slug: "psi",
    category: "basinc",
    categoryName: "Pressão",
    unit: "psi",
    name: "PSI",
    symbol: "psi",
    shortDescription: "O PSI (libra-força por polegada quadrada) é a unidade de pressão do sistema imperial, comum em pneus.",
    historySummary: "O PSI se consolidou com o sistema imperial norte-americano, especialmente para pressão de pneus e sistemas hidráulicos.",
    measurementSystem: "Sistema imperial/norte-americano",
    siEquivalent: "1 psi ≈ 6894,76 Pa",
    commonUses: "Pressão de pneus, sistemas hidráulicos e pneumáticos",
  },
  {
    locale: "pt",
    sourceSlug: "atmosfer",
    slug: "atmosfera",
    category: "basinc",
    categoryName: "Pressão",
    unit: "atm",
    name: "Atmosfera padrão",
    symbol: "atm",
    shortDescription: "A atmosfera padrão representa aproximadamente a pressão atmosférica média ao nível do mar.",
    historySummary: "Definida a partir das medições barométricas de Torricelli no século XVII, serve de referência para as condições padrão.",
    measurementSystem: "Fora do SI (unidade de referência)",
    siEquivalent: "1 atm = 101.325 Pa",
    commonUses: "Condições atmosféricas e de referência",
  },

  // Energia
  {
    locale: "pt",
    sourceSlug: "joule",
    slug: "joule",
    category: "enerji",
    categoryName: "Energia",
    unit: "J",
    name: "Joule",
    symbol: "J",
    shortDescription: "O joule é a unidade SI de energia, igual ao trabalho de uma força de um newton ao longo de um metro.",
    historySummary: "Recebeu esse nome em homenagem ao físico inglês James Prescott Joule por seus trabalhos sobre energia e calor.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "1 J = 1 N·m",
    commonUses: "Cálculos científicos e físicos de energia",
  },
  {
    locale: "pt",
    sourceSlug: "kilovatsaat",
    slug: "quilowatt-hora",
    category: "enerji",
    categoryName: "Energia",
    unit: "kWh",
    name: "Quilowatt-hora",
    symbol: "kWh",
    shortDescription: "O quilowatt-hora é a unidade padrão de cobrança do consumo elétrico no mundo.",
    historySummary: "Adotado com a generalização da eletricidade doméstica, o quilowatt-hora continua sendo a unidade de referência dos medidores elétricos.",
    measurementSystem: "Sistema métrico (eletricidade)",
    siEquivalent: "1 kWh = 3.600.000 J",
    commonUses: "Cobrança de energia elétrica",
  },
  {
    locale: "pt",
    sourceSlug: "kalori",
    slug: "caloria",
    category: "enerji",
    categoryName: "Energia",
    unit: "cal",
    name: "Caloria",
    symbol: "cal",
    shortDescription: "A caloria é a energia necessária para elevar em um grau Celsius a temperatura de um grama de água.",
    historySummary: "Definida no século XIX para estudos térmicos, a caloria hoje está associada sobretudo à nutrição.",
    measurementSystem: "Sistema métrico (tradicional)",
    siEquivalent: "1 cal = 4,184 J",
    commonUses: "Nutrição e química",
  },
  {
    locale: "pt",
    sourceSlug: "btu",
    slug: "btu",
    category: "enerji",
    categoryName: "Energia",
    unit: "Btu",
    name: "BTU",
    symbol: "BTU",
    shortDescription: "O BTU (British Thermal Unit) expressa a capacidade de sistemas de aquecimento e ar-condicionado.",
    historySummary: "De origem britânica, o BTU continua sendo muito usado nos Estados Unidos para aparelhos térmicos.",
    measurementSystem: "Sistema imperial/norte-americano",
    siEquivalent: "1 Btu ≈ 1055,06 J",
    commonUses: "Climatização e aquecimento",
  },

  // Armazenamento de dados
  {
    locale: "pt",
    sourceSlug: "bayt",
    slug: "byte",
    category: "veri",
    categoryName: "Armazenamento de dados",
    unit: "B",
    name: "Byte",
    symbol: "B",
    shortDescription: "O byte (8 bits) é a unidade básica para representar caracteres e dados digitais.",
    historySummary: "O byte se consolidou com o desenvolvimento dos primeiros computadores como unidade padrão de processamento de dados.",
    measurementSystem: "Computação",
    siEquivalent: "1 B = 8 bits",
    commonUses: "Tamanho de arquivos, memoria, armazenamento",
  },
  {
    locale: "pt",
    sourceSlug: "megabayt",
    slug: "megabyte",
    category: "veri",
    categoryName: "Armazenamento de dados",
    unit: "MB",
    name: "Megabyte",
    symbol: "MB",
    shortDescription: "O megabyte é usado para expressar o tamanho de arquivos médios, como fotos ou documentos.",
    historySummary: "Com o crescimento das capacidades de armazenamento, o megabyte se tornou a unidade habitual para arquivos digitais.",
    measurementSystem: "Computação (base 1000 ou 1024)",
    siEquivalent: "1 MB = 1.000.000 B (ou 1024² B em base binaria)",
    commonUses: "Tamanho de fotos, documentos e aplicativos",
  },
  {
    locale: "pt",
    sourceSlug: "gigabayt",
    slug: "gigabyte",
    category: "veri",
    categoryName: "Armazenamento de dados",
    unit: "GB",
    name: "Gigabyte",
    symbol: "GB",
    shortDescription: "O gigabyte é a unidade padrão para expressar a capacidade de armazenamento de celulares e computadores.",
    historySummary: "O gigabyte se consolidou com o crescimento do armazenamento digital massivo (discos rígidos, pendrives, celulares).",
    measurementSystem: "Computação (base 1000 ou 1024)",
    siEquivalent: "1 GB = 1.000.000.000 B (ou 1024³ B em base binaria)",
    commonUses: "Armazenamento de celulares, computadores e planos de internet",
  },

  // Eletricidade
  {
    locale: "pt",
    sourceSlug: "volt",
    slug: "volt",
    category: "elektrik",
    categoryName: "Eletricidade",
    unit: "V",
    name: "Volt",
    symbol: "V",
    shortDescription: "O volt é a unidade SI de diferença de potencial elétrico.",
    historySummary: "Recebeu esse nome em homenagem ao físico italiano Alessandro Volta, inventor da primeira pilha elétrica.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidade SI de tensão elétrica",
    commonUses: "Pilhas, tomadas, circuitos eletrônicos",
  },
  {
    locale: "pt",
    sourceSlug: "amper",
    slug: "ampere",
    category: "elektrik",
    categoryName: "Eletricidade",
    unit: "A",
    name: "Ampere",
    symbol: "A",
    shortDescription: "O ampere é a unidade básica do SI para a corrente elétrica.",
    historySummary: "Recebeu esse nome em homenagem ao físico francês Andre-Marie Ampere, pioneiro do eletromagnetismo.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidade básica do SI para a corrente elétrica",
    commonUses: "Circuitos elétricos, disjuntores, carregadores",
  },
  {
    locale: "pt",
    sourceSlug: "miliamper",
    slug: "miliampere",
    category: "elektrik",
    categoryName: "Eletricidade",
    unit: "mA",
    name: "Miliampere",
    symbol: "mA",
    shortDescription: "O miliampere equivale à milésima parte de um ampere e é usado para medir pequenas correntes em eletrônica.",
    historySummary: "Submúltiplo do ampere, o miliampere se tornou essencial com o desenvolvimento da eletrônica de precisão.",
    measurementSystem: "Sistema Internacional (SI, submúltiplo)",
    siEquivalent: "1 mA = 0,001 A",
    commonUses: "Baterias de celular, sensores, circuitos eletrônicos",
  },

  // Quilate de ouro
  {
    locale: "pt",
    sourceSlug: "24-ayar-altin",
    slug: "ouro-24-quilates",
    category: "altin_ayar",
    categoryName: "Quilate de ouro",
    unit: "24K",
    name: "Ouro de 24 quilates",
    symbol: "24K",
    shortDescription: "O ouro de 24 quilates é ouro puro a 99,9%, a referência do sistema de quilates.",
    historySummary: "O ouro de 24 quilates é tradicionalmente usado em lingotes de investimento devido à sua máxima pureza.",
    measurementSystem: "Sistema de quilates",
    siEquivalent: "99,9% de ouro puro",
    commonUses: "Lingotes e investimento em ouro",
  },
  {
    locale: "pt",
    sourceSlug: "22-ayar-altin",
    slug: "ouro-22-quilates",
    category: "altin_ayar",
    categoryName: "Quilate de ouro",
    unit: "22K",
    name: "Ouro de 22 quilates",
    symbol: "22K",
    shortDescription: "O ouro de 22 quilates contém cerca de 91,6% de ouro puro e é popular na joalheria tradicional.",
    historySummary: "Muito usado no sul da Ásia e no Oriente Médio, equilibra pureza e resistência para a fabricação de joias.",
    measurementSystem: "Sistema de quilates",
    siEquivalent: "≈91,6% de ouro puro",
    commonUses: "Joalheria tradicional",
  },
  {
    locale: "pt",
    sourceSlug: "18-ayar-altin",
    slug: "ouro-18-quilates",
    category: "altin_ayar",
    categoryName: "Quilate de ouro",
    unit: "18K",
    name: "Ouro de 18 quilates",
    symbol: "18K",
    shortDescription: "O ouro de 18 quilates contém 75% de ouro puro e é o padrão mais comum na joalheria ocidental.",
    historySummary: "Seu bom equilíbrio entre dureza e pureza o torna a referência das joalherias na Europa e nas Américas.",
    measurementSystem: "Sistema de quilates",
    siEquivalent: "75% de ouro puro",
    commonUses: "Joalheria ocidental, alianças de casamento",
  },

  // Teor de prata
  {
    locale: "pt",
    sourceSlug: "999-ayar-gumus",
    slug: "prata-999",
    category: "gumus_ayar",
    categoryName: "Teor de prata",
    unit: "999",
    name: "Prata 999 (fina)",
    symbol: "999",
    shortDescription: "A prata 999 e prata pura a 99,9%, usada principalmente em lingotes de investimento.",
    historySummary: "Sua máxima pureza a torna o padrão preferido para produtos de investimento e lingotes de prata.",
    measurementSystem: "Sistema de milésimos",
    siEquivalent: "99,9% de prata pura",
    commonUses: "Lingotes e prata de investimento",
  },
  {
    locale: "pt",
    sourceSlug: "925-ayar-gumus",
    slug: "prata-esterlina-925",
    category: "gumus_ayar",
    categoryName: "Teor de prata",
    unit: "925",
    name: "Prata esterlina (925)",
    symbol: "925",
    shortDescription: "A prata esterlina contém 92,5% de prata pura e é o padrão mundial da joalheria de prata.",
    historySummary: "O padrão da prata esterlina remonta à Inglaterra do século XII e continua sendo a norma mais reconhecida do mundo.",
    measurementSystem: "Sistema de milésimos",
    siEquivalent: "92,5% de prata pura",
    commonUses: "Joalheria e talheres",
  },
];

export function findPortugueseUnitPageBySourceSlug(sourceSlug: string) {
  return portugueseUnitPages.find((page) => page.sourceSlug === sourceSlug);
}

export function findPortugueseUnitPage(category: string, unit: string) {
  return portugueseUnitPages.find(
    (page) => page.category === category && page.unit === unit
  );
}
