// Páginas de unidad en español latinoamericano — integradas en el sistema i18n.
// Archivo independiente (no modifica los archivos existentes de
// tr/en/de/ar/uz/bn/fr).
// Alcance limitado a las 13 categorías fundamentales que, junto con las
// 4 herramientas universales (página de inicio), forman los 17 elementos
// de la identidad del sitio.

import { buildSpanishExtraUnitPages } from "./localizedSpanishExtraUnitPages";

export type LocalizedSpanishUnitPage = {
  locale: "es";
  sourceSlug: string;
  slug: string;
  category: string;
  categoryName: string;
  unit: string;
  name: string;
  symbol: string;
  shortDescription: string;
  historySummary: string;
  measurementSystem: string;
  siEquivalent: string;
  commonUses: string;
};

export const es419UnitPages: LocalizedSpanishUnitPage[] = [
  // Longitud
  {
    locale: "es",
    sourceSlug: "metre",
    slug: "metro",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "m",
    name: "Metro",
    symbol: "m",
    shortDescription: "El metro es la unidad básica del SI para medir longitud.",
    historySummary: "Desde 1983, el metro se define exactamente como la distancia que recorre la luz en el vacío durante 1/299.792.458 de segundo.",
    measurementSystem: "Sistema Internacional de Unidades (SI)",
    siEquivalent: "Unidad básica del SI para longitud",
    commonUses: "Construcción, deporte, ciencia y distancias cotidianas",
  },
  {
    locale: "es",
    sourceSlug: "kilometre",
    slug: "kilometro",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "km",
    name: "Kilómetro",
    symbol: "km",
    shortDescription: "El kilómetro equivale a 1.000 metros y se usa para distancias entre lugares.",
    historySummary: "Como múltiplo decimal del metro, el kilómetro se convirtió en una referencia habitual en carreteras, mapas y geografía.",
    measurementSystem: "Sistema Internacional (múltiplo del SI)",
    siEquivalent: "1 km = 1.000 m",
    commonUses: "Carreteras, geografía, cartografía e infraestructura",
  },
  {
    locale: "es",
    sourceSlug: "santimetre",
    slug: "centimetro",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "cm",
    name: "Centímetro",
    symbol: "cm",
    shortDescription: "El centímetro es la centésima parte de un metro y sirve para medidas cotidianas precisas.",
    historySummary: "Introducido con el sistema métrico, el centímetro es práctico para objetos pequeños y medianos.",
    measurementSystem: "Sistema Internacional (submúltiplo del SI)",
    siEquivalent: "1 cm = 0,01 m",
    commonUses: "Costura, medidas corporales y objetos cotidianos",
  },
  {
    locale: "es",
    sourceSlug: "milimetre",
    slug: "milimetro",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "mm",
    name: "Milímetro",
    symbol: "mm",
    shortDescription: "El milímetro es la milésima parte de un metro y se usa en mediciones de alta precisión.",
    historySummary: "El milímetro es un submúltiplo métrico común en ingeniería y fabricación de precisión.",
    measurementSystem: "Sistema Internacional (submúltiplo del SI)",
    siEquivalent: "1 mm = 0,001 m",
    commonUses: "Ingeniería mecánica, planos técnicos y precisión industrial",
  },
  {
    locale: "es",
    sourceSlug: "fit",
    slug: "pie",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "ft",
    name: "Pie",
    symbol: "ft",
    shortDescription: "El pie es una unidad anglosajona de longitud, usada principalmente en Estados Unidos y Reino Unido.",
    historySummary: "Históricamente se relacionó con el pie humano y en 1959 se fijó exactamente en 0,3048 metros por acuerdo internacional.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 ft = 0,3048 m",
    commonUses: "Inmuebles, aviación y construcción en Estados Unidos",
  },
  {
    locale: "es",
    sourceSlug: "inc",
    slug: "pulgada",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "in",
    name: "Pulgada",
    symbol: "in",
    shortDescription: "La pulgada es una unidad anglosajona pequeña, usada en pantallas, tuberías y herramientas.",
    historySummary: "Su nombre se asocia con el ancho del pulgar humano; desde 1959 equivale exactamente a 2,54 centímetros.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 in = 2,54 cm",
    commonUses: "Tamaño de pantallas, diámetro de tuberías y herramientas",
  },
  {
    locale: "es",
    sourceSlug: "yarda",
    slug: "yarda",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "yd",
    name: "Yarda",
    symbol: "yd",
    shortDescription: "La yarda equivale a tres pies y se usa en deportes, textiles y algunos contextos anglosajones.",
    historySummary: "De origen inglés, la yarda se fijó exactamente en 0,9144 metros en el acuerdo internacional de 1959.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 yd = 0,9144 m",
    commonUses: "Deportes, textiles y mediciones anglosajonas",
  },
  {
    locale: "es",
    sourceSlug: "mil",
    slug: "milla",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "mi",
    name: "Milla",
    symbol: "mi",
    shortDescription: "La milla terrestre es una unidad vial usada principalmente en Estados Unidos y Reino Unido.",
    historySummary: "Derivada de la milla romana, la milla terrestre internacional equivale exactamente a 1.609,344 metros.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 mi = 1.609,344 m",
    commonUses: "Distancias por carretera en Estados Unidos y el Reino Unido",
  },

  // Superficie
  {
    locale: "es",
    sourceSlug: "metrekare",
    slug: "metro-cuadrado",
    category: "alan",
    categoryName: "Superficie",
    unit: "m²",
    name: "Metro cuadrado",
    symbol: "m²",
    shortDescription: "El metro cuadrado es la unidad derivada del SI para superficie: un cuadrado de un metro por lado.",
    historySummary: "Derivado del metro, el metro cuadrado es la referencia habitual en construcción, viviendas y terrenos.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "1 m² = 1 m × 1 m",
    commonUses: "Edificios, terrenos y planos de construcción",
  },
  {
    locale: "es",
    sourceSlug: "hektar",
    slug: "hectarea",
    category: "alan",
    categoryName: "Superficie",
    unit: "ha",
    name: "Hectárea",
    symbol: "ha",
    shortDescription: "La hectárea equivale a 10.000 metros cuadrados y se usa sobre todo para grandes extensiones de tierra.",
    historySummary: "La hectárea facilita expresar superficies agrícolas, forestales y territoriales de gran tamaño.",
    measurementSystem: "Sistema métrico (aceptada para uso con el SI)",
    siEquivalent: "1 ha = 10.000 m²",
    commonUses: "Tierras agrícolas, silvicultura y urbanismo",
  },
  {
    locale: "es",
    sourceSlug: "akre",
    slug: "acre",
    category: "alan",
    categoryName: "Superficie",
    unit: "ac",
    name: "Acre",
    symbol: "ac",
    shortDescription: "El acre es una unidad anglosajona de superficie, frecuente en terrenos de Estados Unidos y otros mercados.",
    historySummary: "Históricamente se asoció a la superficie arable en una jornada; hoy equivale exactamente a 4.046,8564224 m².",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 ac = 4.046,8564224 m²",
    commonUses: "Terrenos inmobiliarios y agrícolas en Estados Unidos y Reino Unido",
  },

  // Volumen
  {
    locale: "es",
    sourceSlug: "litre",
    slug: "litro",
    category: "hacim",
    categoryName: "Volumen",
    unit: "L",
    name: "Litro",
    symbol: "L",
    shortDescription: "El litro es una unidad práctica de volumen muy usada y equivale a 0,001 metros cúbicos.",
    historySummary: "El litro se introdujo con el sistema métrico y se usa de forma generalizada para líquidos y recipientes.",
    measurementSystem: "Sistema métrico (aceptada para uso con el SI)",
    siEquivalent: "1 L = 0,001 m³",
    commonUses: "Bebidas, combustible y medidas de cocina",
  },
  {
    locale: "es",
    sourceSlug: "mililitre",
    slug: "mililitro",
    category: "hacim",
    categoryName: "Volumen",
    unit: "mL",
    name: "Mililitro",
    symbol: "mL",
    shortDescription: "El mililitro es la milésima parte de un litro y se usa para pequeñas cantidades de líquido.",
    historySummary: "Como submúltiplo del litro, el mililitro es habitual en medicina, laboratorio y cocina.",
    measurementSystem: "Sistema métrico (submúltiplo del litro)",
    siEquivalent: "1 mL = 0,001 L",
    commonUses: "Medicamentos, cosméticos y medidas culinarias precisas",
  },
  {
    locale: "es",
    sourceSlug: "metrekup",
    slug: "metro-cubico",
    category: "hacim",
    categoryName: "Volumen",
    unit: "m³",
    name: "Metro cúbico",
    symbol: "m³",
    shortDescription: "El metro cúbico es la unidad derivada del SI para volumen.",
    historySummary: "Se obtiene al elevar al cubo el metro, la unidad básica de longitud.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "1 m³ = 1.000 L",
    commonUses: "Gas natural, concreto y grandes volúmenes industriales",
  },
  {
    locale: "es",
    sourceSlug: "galon",
    slug: "galon",
    category: "hacim",
    categoryName: "Volumen",
    unit: "gal",
    name: "Galón (US)",
    symbol: "gal",
    shortDescription: "El galón estadounidense es una unidad de volumen líquido usada en Estados Unidos, especialmente para combustible.",
    historySummary: "El galón líquido estadounidense procede de medidas históricas inglesas y difiere del galón imperial británico.",
    measurementSystem: "Sistema estadounidense (US customary)",
    siEquivalent: "1 gal (US) = 3,785411784 L",
    commonUses: "Combustible y bebidas en Estados Unidos",
  },

  // Masa
  {
    locale: "es",
    sourceSlug: "kilogram",
    slug: "kilogramo",
    category: "kutle",
    categoryName: "Masa",
    unit: "kg",
    name: "Kilogramo",
    symbol: "kg",
    shortDescription: "El kilogramo es la unidad básica del SI para la masa.",
    historySummary: "Desde 2019, el kilogramo se define fijando el valor de la constante de Planck, sin depender de un prototipo físico.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidad básica del SI para masa",
    commonUses: "Masa corporal, envíos y cocina",
  },
  {
    locale: "es",
    sourceSlug: "gram",
    slug: "gramo",
    category: "kutle",
    categoryName: "Masa",
    unit: "g",
    name: "Gramo",
    symbol: "g",
    shortDescription: "El gramo equivale a la milésima parte de un kilogramo y se usa para pequeñas masas.",
    historySummary: "El gramo tuvo un papel central en el desarrollo histórico del sistema métrico y hoy se define como 0,001 kg.",
    measurementSystem: "Sistema Internacional (submúltiplo del SI)",
    siEquivalent: "1 g = 0,001 kg",
    commonUses: "Cocina, joyería y laboratorio",
  },
  {
    locale: "es",
    sourceSlug: "miligram",
    slug: "miligramo",
    category: "kutle",
    categoryName: "Masa",
    unit: "mg",
    name: "Miligramo",
    symbol: "mg",
    shortDescription: "El miligramo equivale a la milésima parte de un gramo y se usa en farmacia y química.",
    historySummary: "Como submúltiplo del gramo, permite expresar cantidades pequeñas con precisión en laboratorio y formulación.",
    measurementSystem: "Sistema Internacional (submúltiplo del SI)",
    siEquivalent: "1 mg = 0,001 g",
    commonUses: "Dosificación de medicamentos y química analítica",
  },
  {
    locale: "es",
    sourceSlug: "ton",
    slug: "tonelada",
    category: "kutle",
    categoryName: "Masa",
    unit: "t",
    name: "Tonelada",
    symbol: "t",
    shortDescription: "La tonelada métrica equivale a 1.000 kilogramos y se usa para grandes masas.",
    historySummary: "La tonelada métrica facilita expresar cargas grandes en industria, transporte y agricultura.",
    measurementSystem: "Sistema métrico (aceptada para uso con el SI)",
    siEquivalent: "1 t = 1.000 kg",
    commonUses: "Transporte marítimo, industria pesada y agricultura",
  },
  {
    locale: "es",
    sourceSlug: "pound",
    slug: "libra",
    category: "kutle",
    categoryName: "Masa",
    unit: "lb",
    name: "Libra",
    symbol: "lb",
    shortDescription: "La libra avoirdupois es una unidad de masa usada principalmente en Estados Unidos.",
    historySummary: "La libra avoirdupois internacional se fijó exactamente en 0,45359237 kg en 1959.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 lb = 0,45359237 kg",
    commonUses: "Masa corporal y alimentos en Estados Unidos",
  },
  {
    locale: "es",
    sourceSlug: "ons",
    slug: "onza",
    category: "kutle",
    categoryName: "Masa",
    unit: "oz",
    name: "Onza",
    symbol: "oz",
    shortDescription: "La onza avoirdupois equivale a un dieciseisavo de libra y se usa para masas pequeñas.",
    historySummary: "La onza avoirdupois se ha usado históricamente en mercados anglosajones para cantidades pequeñas de mercancías.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 oz ≈ 28,3495 g",
    commonUses: "Alimentos y cosméticos en Estados Unidos",
  },

  // Temperatura
  {
    locale: "es",
    sourceSlug: "santigrat",
    slug: "celsius",
    category: "sicaklik",
    categoryName: "Temperatura",
    unit: "C",
    name: "Celsius",
    symbol: "°C",
    shortDescription: "Celsius es una escala muy usada; a presión atmosférica estándar, el agua congela a 0 °C y hierve a 100 °C.",
    historySummary: "Anders Celsius propuso una escala en 1742; posteriormente se adoptó la orientación actual de sus puntos de referencia.",
    measurementSystem: "Escala métrica de uso común",
    siEquivalent: "K = °C + 273,15",
    commonUses: "Meteorología, cocina y ciencia",
  },
  {
    locale: "es",
    sourceSlug: "fahrenhayt",
    slug: "fahrenheit",
    category: "sicaklik",
    categoryName: "Temperatura",
    unit: "F",
    name: "Fahrenheit",
    symbol: "°F",
    shortDescription: "La escala Fahrenheit se usa principalmente en Estados Unidos para la temperatura cotidiana.",
    historySummary: "Daniel Gabriel Fahrenheit propuso la escala en 1724; sus puntos de referencia históricos dieron lugar a la escala actual.",
    measurementSystem: "Escala de uso común en Estados Unidos",
    siEquivalent: "°C = (°F − 32) × 5/9",
    commonUses: "Meteorología y cocina en Estados Unidos",
  },
  {
    locale: "es",
    sourceSlug: "kelvin",
    slug: "kelvin",
    category: "sicaklik",
    categoryName: "Temperatura",
    unit: "K",
    name: "Kelvin",
    symbol: "K",
    shortDescription: "El kelvin es la unidad básica del SI para temperatura termodinámica; se escribe K, sin signo de grado.",
    historySummary: "Nombrado por William Thomson, Lord Kelvin, parte del cero absoluto: 0 K.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidad básica del SI para temperatura termodinámica",
    commonUses: "Investigación científica, física y astronomía",
  },

  // Tiempo
  {
    locale: "es",
    sourceSlug: "saniye",
    slug: "segundo",
    category: "zaman",
    categoryName: "Tiempo",
    unit: "s",
    name: "Segundo",
    symbol: "s",
    shortDescription: "El segundo es la unidad básica del SI para el tiempo.",
    historySummary: "Desde 1967, el segundo se define mediante 9.192.631.770 períodos de una radiación asociada al átomo de cesio-133.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidad básica del SI para tiempo",
    commonUses: "Cronometraje deportivo, ciencia y computación",
  },
  {
    locale: "es",
    sourceSlug: "dakika",
    slug: "minuto",
    category: "zaman",
    categoryName: "Tiempo",
    unit: "min",
    name: "Minuto",
    symbol: "min",
    shortDescription: "El minuto equivale a 60 segundos y es una unidad cotidiana de tiempo.",
    historySummary: "La división en 60 unidades procede del sistema sexagesimal de la antigua Babilonia y sigue en uso.",
    measurementSystem: "Aceptada para uso con el SI",
    siEquivalent: "1 min = 60 s",
    commonUses: "Horarios, cocina, deporte",
  },
  {
    locale: "es",
    sourceSlug: "saat",
    slug: "hora",
    category: "zaman",
    categoryName: "Tiempo",
    unit: "h",
    name: "Hora",
    symbol: "h",
    shortDescription: "La hora equivale a 60 minutos y sirve para organizar el día.",
    historySummary: "La división del día en 24 horas se asocia con sistemas de medición del tiempo del Antiguo Egipto.",
    measurementSystem: "Aceptada para uso con el SI",
    siEquivalent: "1 h = 3.600 s",
    commonUses: "Trabajo, viajes y horarios",
  },
  {
    locale: "es",
    sourceSlug: "gun",
    slug: "dia",
    category: "zaman",
    categoryName: "Tiempo",
    unit: "day",
    name: "Día",
    symbol: "d",
    shortDescription: "El día convencional equivale a 24 horas, o 86.400 segundos.",
    historySummary: "Su uso se relaciona con el ciclo día-noche; la duración de la rotación terrestre no es perfectamente constante.",
    measurementSystem: "Aceptada para uso con el SI",
    siEquivalent: "1 d = 86.400 s",
    commonUses: "Calendario, planificación y duraciones",
  },

  // Velocidad
  {
    locale: "es",
    sourceSlug: "kilometre-saat",
    slug: "kilometro-hora",
    category: "hiz",
    categoryName: "Velocidad",
    unit: "km/h",
    name: "Kilómetro por hora",
    symbol: "km/h",
    shortDescription: "El kilómetro por hora es la unidad habitual de velocidad vial en países que usan el sistema métrico.",
    historySummary: "Como combinación del kilómetro y la hora, se convirtió en una referencia común para tránsito y transporte.",
    measurementSystem: "Sistema métrico (uso común)",
    siEquivalent: "1 km/h ≈ 0,278 m/s",
    commonUses: "Velocidad de vehículos y límites viales",
  },
  {
    locale: "es",
    sourceSlug: "metre-saniye",
    slug: "metro-segundo",
    category: "hiz",
    categoryName: "Velocidad",
    unit: "m/s",
    name: "Metro por segundo",
    symbol: "m/s",
    shortDescription: "El metro por segundo es la unidad derivada del SI para velocidad, usada en física y meteorología.",
    historySummary: "Se obtiene directamente del metro y el segundo, y es la referencia para cálculos científicos.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "1 m/s",
    commonUses: "Velocidad del viento y cálculos físicos",
  },
  {
    locale: "es",
    sourceSlug: "mil-saat",
    slug: "milla-hora",
    category: "hiz",
    categoryName: "Velocidad",
    unit: "mph",
    name: "Milla por hora",
    symbol: "mph",
    shortDescription: "La milla por hora es la unidad de velocidad vial en Estados Unidos y el Reino Unido.",
    historySummary: "Derivada de la milla terrestre, esta unidad sigue siendo común en señales de tránsito de ambos países.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 mph ≈ 0,447 m/s",
    commonUses: "Velocidad de vehículos en Estados Unidos y Reino Unido",
  },
  {
    locale: "es",
    sourceSlug: "knot",
    slug: "nudo",
    category: "hiz",
    categoryName: "Velocidad",
    unit: "knot",
    name: "Nudo",
    symbol: "kn",
    shortDescription: "El nudo equivale a una milla náutica por hora y se usa en navegación marítima y aérea.",
    historySummary: "El nombre proviene del método histórico de contar nudos en una cuerda arrojada al agua desde un barco.",
    measurementSystem: "Navegación marítima y aérea",
    siEquivalent: "1 kn = 0,514444… m/s",
    commonUses: "Velocidad de barcos y aviones",
  },

  // Presion
  {
    locale: "es",
    sourceSlug: "pascal",
    slug: "pascal",
    category: "basinc",
    categoryName: "Presión",
    unit: "Pa",
    name: "Pascal",
    symbol: "Pa",
    shortDescription: "El pascal es la unidad derivada del SI para presión: un newton por metro cuadrado.",
    historySummary: "Recibe su nombre de Blaise Pascal y se adoptó como unidad del SI para presión en 1971.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "1 Pa = 1 N/m²",
    commonUses: "Cálculos científicos y de ingeniería",
  },
  {
    locale: "es",
    sourceSlug: "bar",
    slug: "bar",
    category: "basinc",
    categoryName: "Presión",
    unit: "bar",
    name: "Bar",
    symbol: "bar",
    shortDescription: "El bar es una unidad práctica de presión, cercana a la presión atmosférica estándar y común en industria.",
    historySummary: "El bar se extendió en meteorología e ingeniería antes de la adopción general del pascal y continúa en uso técnico.",
    measurementSystem: "Sistema métrico (fuera del SI)",
    siEquivalent: "1 bar = 100.000 Pa",
    commonUses: "Sistemas industriales, compresores y meteorología",
  },
  {
    locale: "es",
    sourceSlug: "psi",
    slug: "psi",
    category: "basinc",
    categoryName: "Presión",
    unit: "psi",
    name: "Psi",
    symbol: "psi",
    shortDescription: "Psi significa libra-fuerza por pulgada cuadrada y se usa en equipos anglosajones, incluidos neumáticos.",
    historySummary: "La unidad se consolidó con el sistema estadounidense en neumática, hidráulica y medición de neumáticos.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 psi = 6.894,757293… Pa",
    commonUses: "Presión de neumáticos y sistemas hidráulicos o neumáticos",
  },
  {
    locale: "es",
    sourceSlug: "atmosfer",
    slug: "atmosfera",
    category: "basinc",
    categoryName: "Presión",
    unit: "atm",
    name: "Atmósfera estándar",
    symbol: "atm",
    shortDescription: "La atmósfera estándar es una unidad de referencia definida como 101.325 Pa; no describe la presión real de un lugar.",
    historySummary: "La presión atmosférica se estudió con barómetros desde el siglo XVII; la atmósfera estándar se usa hoy como referencia convencional.",
    measurementSystem: "Fuera del SI (unidad de referencia)",
    siEquivalent: "1 atm = 101.325 Pa",
    commonUses: "Condiciones atmosféricas de referencia",
  },

  // Energía
  {
    locale: "es",
    sourceSlug: "joule",
    slug: "julio",
    category: "enerji",
    categoryName: "Energía",
    unit: "J",
    name: "Julio",
    symbol: "J",
    shortDescription: "El julio es la unidad derivada del SI para energía: un newton por metro.",
    historySummary: "Recibe su nombre de James Prescott Joule por sus investigaciones sobre energía y calor.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "1 J = 1 N·m",
    commonUses: "Cálculos científicos y físicos de energía",
  },
  {
    locale: "es",
    sourceSlug: "kilovatsaat",
    slug: "kilovatio-hora",
    category: "enerji",
    categoryName: "Energía",
    unit: "kWh",
    name: "Kilovatio-hora",
    symbol: "kWh",
    shortDescription: "El kilovatio-hora mide energía: la consumida por una potencia de un kilovatio durante una hora.",
    historySummary: "Se generalizó con los sistemas eléctricos y sigue siendo una referencia habitual para registrar y facturar consumo energético.",
    measurementSystem: "Electricidad (uso común)",
    siEquivalent: "1 kWh = 3.600.000 J",
    commonUses: "Facturación eléctrica y consumo energético",
  },
  {
    locale: "es",
    sourceSlug: "kalori",
    slug: "caloria",
    category: "enerji",
    categoryName: "Energía",
    unit: "cal",
    name: "Caloría",
    symbol: "cal",
    shortDescription: "La caloría es una unidad tradicional de energía; para esta conversión, 1 cal equivale a 4,184 J.",
    historySummary: "Se usó en estudios térmicos y hoy se asocia sobre todo con nutrición, donde “caloría” suele significar kilocaloría.",
    measurementSystem: "Unidad métrica tradicional",
    siEquivalent: "1 cal = 4,184 J",
    commonUses: "Nutrición y química",
  },
  {
    locale: "es",
    sourceSlug: "btu",
    slug: "btu",
    category: "enerji",
    categoryName: "Energía",
    unit: "Btu",
    name: "BTU",
    symbol: "BTU",
    shortDescription: "El Btu es una unidad tradicional de energía usada en calefacción y aire acondicionado.",
    historySummary: "De origen anglosajón, sigue siendo frecuente en especificaciones de equipos térmicos en Estados Unidos.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 Btu ≈ 1.055,06 J",
    commonUses: "Climatización y calefacción",
  },

  // Almacenamiento de datos
  {
    locale: "es",
    sourceSlug: "bayt",
    slug: "byte",
    category: "veri",
    categoryName: "Almacenamiento de datos",
    unit: "B",
    name: "Byte",
    symbol: "B",
    shortDescription: "El byte equivale a ocho bits y es una unidad básica para datos digitales.",
    historySummary: "Se consolidó con las primeras computadoras como una unidad práctica para organizar y procesar datos.",
    measurementSystem: "Informática",
    siEquivalent: "1 B = 8 bits",
    commonUses: "Tamaño de archivos, memoria y almacenamiento",
  },
  {
    locale: "es",
    sourceSlug: "megabayt",
    slug: "megabyte",
    category: "veri",
    categoryName: "Almacenamiento de datos",
    unit: "MB",
    name: "Megabyte",
    symbol: "MB",
    shortDescription: "El megabyte decimal equivale a un millón de bytes y se usa para archivos como fotos y documentos.",
    historySummary: "Se volvió común con el crecimiento de archivos y capacidades de almacenamiento digital.",
    measurementSystem: "Informática decimal",
    siEquivalent: "1 MB = 1.000.000 B; 1 MiB = 1.048.576 B",
    commonUses: "Tamaño de fotos, documentos y aplicaciones",
  },
  {
    locale: "es",
    sourceSlug: "gigabayt",
    slug: "gigabyte",
    category: "veri",
    categoryName: "Almacenamiento de datos",
    unit: "GB",
    name: "Gigabyte",
    symbol: "GB",
    shortDescription: "El gigabyte decimal equivale a mil millones de bytes y se usa para capacidades de almacenamiento y transferencia.",
    historySummary: "Se hizo habitual con el almacenamiento digital masivo en discos, memorias y dispositivos personales.",
    measurementSystem: "Informática decimal",
    siEquivalent: "1 GB = 1.000.000.000 B; 1 GiB = 1.073.741.824 B",
    commonUses: "Almacenamiento de celulares, computadoras y tarifas de datos",
  },

  // Electricidad
  {
    locale: "es",
    sourceSlug: "volt",
    slug: "voltio",
    category: "elektrik",
    categoryName: "Electricidad",
    unit: "V",
    name: "Voltio",
    symbol: "V",
    shortDescription: "El voltio es la unidad derivada del SI para diferencia de potencial eléctrico.",
    historySummary: "Recibe su nombre de Alessandro Volta, pionero en el desarrollo de la pila eléctrica.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "1 V = 1 J/C",
    commonUses: "Pilas, fuentes de alimentación y circuitos electrónicos",
  },
  {
    locale: "es",
    sourceSlug: "amper",
    slug: "amperio",
    category: "elektrik",
    categoryName: "Electricidad",
    unit: "A",
    name: "Amperio",
    symbol: "A",
    shortDescription: "El amperio es la unidad básica del SI para corriente eléctrica.",
    historySummary: "Recibe su nombre de André-Marie Ampère, pionero del electromagnetismo.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "1 A = 1 C/s",
    commonUses: "Circuitos eléctricos, interruptores y cargadores",
  },
  {
    locale: "es",
    sourceSlug: "miliamper",
    slug: "miliamperio",
    category: "elektrik",
    categoryName: "Electricidad",
    unit: "mA",
    name: "Miliamperio",
    symbol: "mA",
    shortDescription: "El miliamperio es la milésima parte de un amperio y mide corrientes pequeñas en electrónica.",
    historySummary: "Como submúltiplo del amperio, permite expresar corrientes pequeñas en sensores y dispositivos electrónicos.",
    measurementSystem: "Sistema Internacional (submúltiplo del SI)",
    siEquivalent: "1 mA = 0,001 A",
    commonUses: "Baterías de celulares, sensores y circuitos electrónicos",
  },

  // Quilataje del oro
  {
    locale: "es",
    sourceSlug: "24-ayar-altin",
    slug: "oro-24-quilates",
    category: "altin_ayar",
    categoryName: "Quilataje del oro",
    unit: "24K",
    name: "Oro de 24 quilates",
    symbol: "24K",
    shortDescription: "El oro de 24 quilates representa 24 partes nominales de oro fino por cada 24 partes de aleación.",
    historySummary: "Las aleaciones cercanas a 24 K se usan con frecuencia en lingotes y productos de inversión; el sello indica la finura declarada.",
    measurementSystem: "Sistema de quilates",
    siEquivalent: "24/24 de oro fino nominal",
    commonUses: "Lingotes y productos de inversión",
  },
  {
    locale: "es",
    sourceSlug: "22-ayar-altin",
    slug: "oro-22-quilates",
    category: "altin_ayar",
    categoryName: "Quilataje del oro",
    unit: "22K",
    name: "Oro de 22 quilates",
    symbol: "22K",
    shortDescription: "El oro de 22 quilates contiene 22/24, o 91,7 % nominal, de oro fino.",
    historySummary: "Esta aleación combina una proporción alta de oro fino con mayor resistencia que una aleación de 24 K.",
    measurementSystem: "Sistema de quilates",
    siEquivalent: "91,7 % de oro fino nominal",
    commonUses: "Joyería y piezas tradicionales",
  },
  {
    locale: "es",
    sourceSlug: "18-ayar-altin",
    slug: "oro-18-quilates",
    category: "altin_ayar",
    categoryName: "Quilataje del oro",
    unit: "18K",
    name: "Oro de 18 quilates",
    symbol: "18K",
    shortDescription: "El oro de 18 quilates contiene 18/24, o 75 %, de oro fino nominal.",
    historySummary: "Su equilibrio entre contenido de oro y resistencia lo hace habitual en joyería de uso diario.",
    measurementSystem: "Sistema de quilates",
    siEquivalent: "75 % de oro fino nominal",
    commonUses: "Anillos, collares y joyería diaria",
  },

  // Ley de plata
  {
    locale: "es",
    sourceSlug: "999-ayar-gumus",
    slug: "plata-999",
    category: "gumus_ayar",
    categoryName: "Ley de plata",
    unit: "999",
    name: "Plata 999 (fina)",
    symbol: "999",
    shortDescription: "La plata 999 contiene 999 milésimas, o 99,9 % nominal, de plata fina.",
    historySummary: "La ley 999 es habitual en lingotes y productos donde interesa una proporción alta de plata fina.",
    measurementSystem: "Sistema de milésimas",
    siEquivalent: "99,9 % de plata fina nominal",
    commonUses: "Lingotes y productos de inversión",
  },
  {
    locale: "es",
    sourceSlug: "925-ayar-gumus",
    slug: "plata-esterlina-925",
    category: "gumus_ayar",
    categoryName: "Ley de plata",
    unit: "925",
    name: "Plata esterlina (925)",
    symbol: "925",
    shortDescription: "La plata esterlina 925 contiene 925 milésimas, o 92,5 % nominal, de plata fina.",
    historySummary: "Esta ley se desarrolló históricamente en Inglaterra y es una referencia ampliamente reconocida para joyería y objetos de plata.",
    measurementSystem: "Sistema de milésimas",
    siEquivalent: "92,5 % de plata fina nominal",
    commonUses: "Joyería y cubertería",
  },
  ...buildSpanishExtraUnitPages("es-419"),
];

export function findEs419UnitPageBySourceSlug(sourceSlug: string) {
  return es419UnitPages.find((page) => page.sourceSlug === sourceSlug);
}

export function findEs419UnitPage(category: string, unit: string) {
  return es419UnitPages.find(
    (page) => page.category === category && page.unit === unit
  );
}
