// O'zbekcha birlik sahifalari -- yangi i18n tizimiga ulanish uchun
// mustaqil, yangi fayl. Har kategoriyadan eng asosiy 1-2 birlik bilan
// boshlanadi (to'liq 140+ birlik emas -- kengaytirish keyingi bosqich).

export type LocalizedUzbekUnitPage = {
  locale: "uz";
  sourceSlug: string;
  slug: string;
  category: string;
  categoryName: string;
  unit: string;
  name: string;
  symbol: string;
  shortDescription: string;
  historySummary: string;
  measurementSystem: string;
  siEquivalent: string;
  commonUses: string;
};

export const uzbekUnitPages: LocalizedUzbekUnitPage[] = [
  {
    locale: "uz",
    sourceSlug: "metre",
    slug: "metr",
    category: "uzunluk",
    categoryName: "Uzunlik",
    unit: "m",
    name: "Metr",
    symbol: "m",
    shortDescription:
      "Metr -- uzunlikning xalqaro SI asosiy birligi.",
    historySummary:
      "1983-yildan beri metr yorug'likning vakuumda 1/299 792 458 soniyada bosib o'tgan masofasi sifatida aniq belgilangan.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI)",
    siEquivalent: "Asosiy SI uzunlik birligi",
    commonUses: "Qurilish, sport, fan va kundalik masofa o'lchovlari",
  },
  {
    locale: "uz",
    sourceSlug: "kilometre",
    slug: "kilometr",
    category: "uzunluk",
    categoryName: "Uzunlik",
    unit: "km",
    name: "Kilometr",
    symbol: "km",
    shortDescription: "Kilometr -- 1000 metrga teng uzunlik birligi, uzoq masofalarni ifodalash uchun ishlatiladi.",
    historySummary: "Metr tizimining bir qismi sifatida, uzoq masofalarni qulay ifodalash uchun keng qo'llaniladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, ko'paytma birlik)",
    siEquivalent: "1 km = 1000 m",
    commonUses: "Yo'l masofalari, geografiya, sayohat",
  },
  {
    locale: "uz",
    sourceSlug: "metrekare",
    slug: "kvadrat-metr",
    category: "alan",
    categoryName: "Yuza",
    unit: "m²",
    name: "Kvadrat metr",
    symbol: "m²",
    shortDescription: "Kvadrat metr -- yuzaning SI asosidagi birligi.",
    historySummary: "Metr birligidan to'g'ridan-to'g'ri hosil qilingan, bino va yer o'lchamlarini ifodalashning standart usuli.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI)",
    siEquivalent: "Asosiy SI yuza birligi",
    commonUses: "Xona, uy va yer uchastkasi o'lchamlari",
  },
  {
    locale: "uz",
    sourceSlug: "hektar",
    slug: "gektar",
    category: "alan",
    categoryName: "Yuza",
    unit: "ha",
    name: "Gektar",
    symbol: "ha",
    shortDescription: "Gektar -- 10 000 kvadrat metrga teng, yer va qishloq xo'jaligi maydonlarini o'lchash uchun ishlatiladigan katta yuza birligi.",
    historySummary: "Metrik tizimda yer maydonlarini qulay ifodalash uchun kiritilgan.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, ko'paytma birlik)",
    siEquivalent: "1 ha = 10 000 m²",
    commonUses: "Qishloq xo'jaligi, yer boshqaruvi, o'rmon xo'jaligi",
  },
  {
    locale: "uz",
    sourceSlug: "litre",
    slug: "litr",
    category: "hacim",
    categoryName: "Hajm",
    unit: "L",
    name: "Litr",
    symbol: "L",
    shortDescription: "Litr -- kundalik hayotda eng ko'p ishlatiladigan hajm birligi.",
    historySummary: "1 kub detsimetr sifatida ta'riflangan, suyuqliklarni o'lchashda dunyo bo'ylab keng qo'llaniladi.",
    measurementSystem: "Metrik tizim (SI bilan mos)",
    siEquivalent: "1 L = 0,001 m³",
    commonUses: "Suyuqliklar, oshxona, yoqilg'i sig'imi",
  },
  {
    locale: "uz",
    sourceSlug: "metrekup",
    slug: "kub-metr",
    category: "hacim",
    categoryName: "Hajm",
    unit: "m³",
    name: "Kub metr",
    symbol: "m³",
    shortDescription: "Kub metr -- hajmning SI asosidagi birligi.",
    historySummary: "Uzunlik birligidan to'g'ridan-to'g'ri hosil qilingan, sanoat va muhandislik hajm hisoblarida qo'llaniladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI)",
    siEquivalent: "Asosiy SI hajm birligi",
    commonUses: "Sanoat jarayonlari, qurilish, saqlash sig'imi",
  },
  {
    locale: "uz",
    sourceSlug: "kilogram",
    slug: "kilogramm",
    category: "kutle",
    categoryName: "Massa",
    unit: "kg",
    name: "Kilogramm",
    symbol: "kg",
    shortDescription: "Kilogramm -- massaning SI asosiy birligi.",
    historySummary: "Hozirda Plank doimiysi orqali aniq belgilangan yagona SI asosiy birligi -- avvallari jismoniy platina-iridiy etalon orqali ta'riflangan edi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI)",
    siEquivalent: "Asosiy SI massa birligi",
    commonUses: "Oshxona, tibbiyot, savdo, sport",
  },
  {
    locale: "uz",
    sourceSlug: "gram",
    slug: "gramm",
    category: "kutle",
    categoryName: "Massa",
    unit: "g",
    name: "Gramm",
    symbol: "g",
    shortDescription: "Gramm -- kilogrammning mingdan bir qismi, kichik massalarni o'lchash uchun ishlatiladi.",
    historySummary: "Dastlab 1795-yilda 1 kub santimetr suvning massasi sifatida ta'riflangan.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, quyi birlik)",
    siEquivalent: "1 g = 0,001 kg",
    commonUses: "Oshxona retseptlari, zargarlik, kimyo",
  },
  {
    locale: "uz",
    sourceSlug: "santigrat",
    slug: "selsiy",
    category: "sicaklik",
    categoryName: "Harorat",
    unit: "C",
    name: "Selsiy",
    symbol: "°C",
    shortDescription: "Selsiy -- suvning muzlash nuqtasini 0°, qaynash nuqtasini 100° deb belgilaydigan keng tarqalgan harorat shkalasi.",
    historySummary: "1742-yilda shved astronomi Anders Selsiy tomonidan taklif qilingan.",
    measurementSystem: "Metrik tizim (SI bilan mos)",
    siEquivalent: "K = °C + 273,15",
    commonUses: "Ob-havo, oshpazlik, tibbiyot, kundalik hayot",
  },
  {
    locale: "uz",
    sourceSlug: "kelvin",
    slug: "kelvin",
    category: "sicaklik",
    categoryName: "Harorat",
    unit: "K",
    name: "Kelvin",
    symbol: "K",
    shortDescription: "Kelvin -- haroratning SI asosiy birligi, mutlaq nol nuqtasidan boshlanadi.",
    historySummary: "Ingliz fizigi Lord Kelvin nomi bilan atalgan, ilmiy va muhandislik hisob-kitoblarida standart birlik.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI)",
    siEquivalent: "0 K = -273,15°C (mutlaq nol)",
    commonUses: "Fizika, astronomiya, muhandislik hisob-kitoblari",
  },
  {
    locale: "uz",
    sourceSlug: "saniye",
    slug: "soniya",
    category: "zaman",
    categoryName: "Vaqt",
    unit: "s",
    name: "Soniya",
    symbol: "s",
    shortDescription: "Soniya -- vaqtning SI asosiy birligi.",
    historySummary: "Hozirda seziy atomining nurlanish chastotasi orqali aniq belgilangan.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI)",
    siEquivalent: "Asosiy SI vaqt birligi",
    commonUses: "Fan, sport, kundalik vaqt o'lchovlari",
  },
  {
    locale: "uz",
    sourceSlug: "saat",
    slug: "soat",
    category: "zaman",
    categoryName: "Vaqt",
    unit: "h",
    name: "Soat",
    symbol: "soat",
    shortDescription: "Soat -- 60 daqiqaga teng, kundalik hayotda eng ko'p ishlatiladigan vaqt birligi.",
    historySummary: "Kunni 24 qismga bo'lish an'anasi qadimgi Misr va Bobil tsivilizatsiyalariga borib taqaladi.",
    measurementSystem: "SI bilan mos, kundalik birlik",
    siEquivalent: "1 soat = 3600 soniya",
    commonUses: "Ish jadvali, sayohat, kundalik reja",
  },
  {
    locale: "uz",
    sourceSlug: "kilometre-saat",
    slug: "km-soat",
    category: "hiz",
    categoryName: "Tezlik",
    unit: "km/h",
    name: "Kilometr/soat",
    symbol: "km/soat",
    shortDescription: "Km/soat -- avtomobil tezligini ifodalashda dunyo bo'ylab eng ko'p ishlatiladigan tezlik birligi.",
    historySummary: "Metrik tizimning tabiiy natijasi sifatida transport va yo'l harakatida standart birlikka aylangan.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI bilan mos)",
    siEquivalent: "1 km/soat = 0,2778 m/s",
    commonUses: "Avtomobil tezligi, yo'l belgilari, sport",
  },
  {
    locale: "uz",
    sourceSlug: "pascal",
    slug: "paskal",
    category: "basinc",
    categoryName: "Bosim",
    unit: "Pa",
    name: "Paskal",
    symbol: "Pa",
    shortDescription: "Paskal -- bosimning SI asosiy birligi.",
    historySummary: "Frantsuz olimi Blez Paskal nomi bilan atalgan.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI)",
    siEquivalent: "1 Pa = 1 N/m²",
    commonUses: "Muhandislik, meteorologiya, fizika",
  },
  {
    locale: "uz",
    sourceSlug: "joule",
    slug: "joul",
    category: "enerji",
    categoryName: "Energiya",
    unit: "J",
    name: "Joul",
    symbol: "J",
    shortDescription: "Joul -- energiyaning SI asosiy birligi.",
    historySummary: "Ingliz fizigi Jeyms Prescott Joul nomi bilan atalgan.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI)",
    siEquivalent: "Asosiy SI energiya birligi",
    commonUses: "Fizika, muhandislik, ozuqa energiyasi hisoblari",
  },
  {
    locale: "uz",
    sourceSlug: "bayt",
    slug: "bayt",
    category: "veri",
    categoryName: "Ma'lumot hajmi",
    unit: "B",
    name: "Bayt",
    symbol: "B",
    shortDescription: "Bayt -- raqamli ma'lumot hajmining asosiy birligi, 8 bitdan iborat.",
    historySummary: "Kompyuter texnologiyasi rivojlanishi bilan ma'lumot hajmini o'lchashning standart asosiy birligiga aylangan.",
    measurementSystem: "Raqamli ma'lumot birligi",
    siEquivalent: "1 bayt = 8 bit",
    commonUses: "Fayl hajmi, xotira sig'imi, internet trafigi",
  },
  {
    locale: "uz",
    sourceSlug: "volt",
    slug: "volt",
    category: "elektrik",
    categoryName: "Elektr",
    unit: "V",
    name: "Volt",
    symbol: "V",
    shortDescription: "Volt -- elektr kuchlanishining SI asosiy birligi.",
    historySummary: "Italyan fizigi Alessandro Volta nomi bilan atalgan.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI)",
    siEquivalent: "Asosiy SI kuchlanish birligi",
    commonUses: "Elektronika, quvvat manbalari, tarmoq kuchlanishi",
  },
  {
    locale: "uz",
    sourceSlug: "amper",
    slug: "amper",
    category: "elektrik",
    categoryName: "Elektr",
    unit: "A",
    name: "Amper",
    symbol: "A",
    shortDescription: "Amper -- elektr tokining SI asosiy birligi.",
    historySummary: "Frantsuz fizigi Andre-Mari Amper nomi bilan atalgan.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI)",
    siEquivalent: "Asosiy SI tok birligi",
    commonUses: "Tok o'lchash, himoya qurilmalari, uskuna quvvati",
  },
  {
    locale: "uz",
    sourceSlug: "24-ayar-altin",
    slug: "24-karat",
    category: "altin_ayar",
    categoryName: "Oltin karati",
    unit: "24K",
    name: "24 Karat Oltin",
    symbol: "24K",
    shortDescription: "24 karat -- 100% sof oltinni bildiradi, eng yuqori tozalik darajasi.",
    historySummary: "Karat tizimi 24 qismli bo'linishga asoslanadi, bu tizim asrlar davomida zargarlikda qo'llanilib kelinadi.",
    measurementSystem: "Karat tizimi (SI dan tashqari)",
    siEquivalent: "999/1000 sof oltin",
    commonUses: "Investitsiya quyma oltin, yuqori sifatli zargarlik",
  },
  {
    locale: "uz",
    sourceSlug: "santimetre",
    slug: "santimetr",
    category: "uzunluk",
    categoryName: "Uzunlik",
    unit: "cm",
    name: "Santimetr",
    symbol: "cm",
    shortDescription: "Santimetr metrning yuzdan bir qismiga teng uzunlik birligi.",
    historySummary: "Kundalik o'lchovlarda va kichik narsalarni o'lchashda keng qo'llaniladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, quyi birlik)",
    siEquivalent: "1 sm = 0,01 m",
    commonUses: "Mebel, kiyim, kundalik o'lchovlar",
  },
  {
    locale: "uz",
    sourceSlug: "milimetre",
    slug: "millimetr",
    category: "uzunluk",
    categoryName: "Uzunlik",
    unit: "mm",
    name: "Millimetr",
    symbol: "mm",
    shortDescription: "Millimetr metrning mingdan bir qismiga teng uzunlik birligi, texnik o'lchovlarda ishlatiladi.",
    historySummary: "Sanoat va muhandislikda kichik toleranslarni o'lchash ehtiyoji bilan keng tarqaldi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, quyi birlik)",
    siEquivalent: "1 mm = 0,001 m",
    commonUses: "Ishlab chiqarish, chizmachilik standartlari",
  },
  {
    locale: "uz",
    sourceSlug: "mikrometre",
    slug: "mikrometr",
    category: "uzunluk",
    categoryName: "Uzunlik",
    unit: "µm",
    name: "Mikrometr",
    symbol: "µm",
    shortDescription: "Mikrometr metrning milliondan bir qismiga teng, juda kichik o'lchovlar uchun ishlatiladi.",
    historySummary: "Materialshunoslik va yarim o'tkazgichlar texnologiyasida asosiy birlik hisoblanadi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, quyi birlik)",
    siEquivalent: "1 µm = 0,000001 m",
    commonUses: "Materialshunoslik, yarim o'tkazgichlar",
  },
  {
    locale: "uz",
    sourceSlug: "nanometre",
    slug: "nanometr",
    category: "uzunluk",
    categoryName: "Uzunlik",
    unit: "nm",
    name: "Nanometr",
    symbol: "nm",
    shortDescription: "Nanometr metrning milliarddan bir qismiga teng, atom va molekulalarni o'lchashda ishlatiladi.",
    historySummary: "Fizika, kimyo va zamonaviy nanotexnologiyada asosiy o'lchov birligi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, quyi birlik)",
    siEquivalent: "1 nm = 0,000000001 m",
    commonUses: "Nanotexnologiya, yorug'lik to'lqin uzunligi",
  },
  {
    locale: "uz",
    sourceSlug: "fit",
    slug: "fut",
    category: "uzunluk",
    categoryName: "Uzunlik",
    unit: "ft",
    name: "Fut",
    symbol: "ft",
    shortDescription: "Fut AQSH va Buyuk Britaniyada keng qo'llaniladigan an'anaviy uzunlik birligi.",
    historySummary: "Qadimgi Rim va ingliz o'lchov tizimlaridan kelib chiqqan, hozir ham qurilishda ishlatiladi.",
    measurementSystem: "Angliya-Amerika o'lchov tizimi (SI dan tashqari)",
    siEquivalent: "1 fut ≈ 0,3048 m",
    commonUses: "Qurilish, bino balandligi, AQSH o'lchovlari",
  },
  {
    locale: "uz",
    sourceSlug: "inc",
    slug: "dyum",
    category: "uzunluk",
    categoryName: "Uzunlik",
    unit: "in",
    name: "Dyum",
    symbol: "in",
    shortDescription: "Dyum kichik uzunlik birligi bo'lib, ekran o'lchamlarini ifodalashda keng qo'llaniladi.",
    historySummary: "Tarixan bosh barmoq kengligiga asoslangan, hozir aniq metrik qiymatga ega.",
    measurementSystem: "Angliya-Amerika o'lchov tizimi (SI dan tashqari)",
    siEquivalent: "1 dyum = 2,54 sm",
    commonUses: "Ekran o'lchamlari, elektronika, AQSH sanoati",
  },
  {
    locale: "uz",
    sourceSlug: "yarda",
    slug: "yard",
    category: "uzunluk",
    categoryName: "Uzunlik",
    unit: "yd",
    name: "Yard",
    symbol: "yd",
    shortDescription: "Yard AQSH va Buyuk Britaniyada matolar va sport maydonlarini o'lchashda ishlatiladi.",
    historySummary: "Tarixan qadam uzunligiga asoslangan, hozir amerika futboli maydonlarida standart o'lchov.",
    measurementSystem: "Angliya-Amerika o'lchov tizimi (SI dan tashqari)",
    siEquivalent: "1 yard ≈ 0,9144 m",
    commonUses: "Sport maydonlari, mato o'lchovlari",
  },
  {
    locale: "uz",
    sourceSlug: "mil",
    slug: "milya",
    category: "uzunluk",
    categoryName: "Uzunlik",
    unit: "mi",
    name: "Milya",
    symbol: "mi",
    shortDescription: "Milya AQSH va Buyuk Britaniyada yo'l masofalarini o'lchashda keng qo'llaniladigan uzunlik birligi.",
    historySummary: "Rim legioner qadamlaridan kelib chiqqan, hozir ingliz o'lchov tizimida standartlashtirilgan.",
    measurementSystem: "Angliya-Amerika o'lchov tizimi (SI dan tashqari)",
    siEquivalent: "1 milya ≈ 1,609 km",
    commonUses: "Yo'l masofalari, AQSH va Buyuk Britaniya navigatsiyasi",
  },
  {
    locale: "uz",
    sourceSlug: "deniz-mili",
    slug: "dengiz-milyasi",
    category: "uzunluk",
    categoryName: "Uzunlik",
    unit: "nmi",
    name: "Dengiz Milyasi",
    symbol: "nmi",
    shortDescription: "Dengiz milyasi dengiz va havo navigatsiyasida ishlatiladigan, yer aylanasiga asoslangan uzunlik birligi.",
    historySummary: "Yer katta doirasidagi bir yoy daqiqasiga teng bo'lib, xalqaro navigatsiya birligi hisoblanadi.",
    measurementSystem: "SI dan tashqari, xalqaro navigatsiya birligi",
    siEquivalent: "1 dengiz milyasi = 1852 m",
    commonUses: "Dengiz va havo navigatsiyasi",
  },
  {
    locale: "uz",
    sourceSlug: "arsin",
    slug: "arshin",
    category: "uzunluk",
    categoryName: "Uzunlik",
    unit: "arşın",
    name: "Arshin",
    symbol: "arshin",
    shortDescription: "Arshin Usmonli davrida kundalik hayotda va savdoda ishlatilgan an'anaviy uzunlik birligi.",
    historySummary: "20-asrda metrik tizim joriy etilgunga qadar Usmonli imperiyasida standart o'lchov birligi bo'lgan.",
    measurementSystem: "SI dan tashqari, tarixiy Usmonli birligi",
    siEquivalent: "1 arshin ≈ 0,68 m",
    commonUses: "Tarixiy hujjatlar va Usmonli davri tadqiqotlari",
  },
  {
    locale: "uz",
    sourceSlug: "endaze",
    slug: "endaze",
    category: "uzunluk",
    categoryName: "Uzunlik",
    unit: "endaze",
    name: "Endaze",
    symbol: "endaze",
    shortDescription: "Endaze Usmonli davrida asosan mato savdosida ishlatilgan uzunlik birligi.",
    historySummary: "Arshinga qaraganda biroz qisqaroq bo'lib, mato o'lchashda qo'llanilgan.",
    measurementSystem: "SI dan tashqari, tarixiy Usmonli birligi",
    siEquivalent: "1 endaze ≈ 0,65 m",
    commonUses: "Tarixiy mato savdosi va tadqiqotlar",
  },
  {
    locale: "uz",
    sourceSlug: "bizans-ayagi",
    slug: "vizantiya-futi",
    category: "uzunluk",
    categoryName: "Uzunlik",
    unit: "pus",
    name: "Vizantiya Futi",
    symbol: "pus",
    shortDescription: "Vizantiya futi Vizantiya imperiyasida bino va yer o'lchovlarida ishlatilgan uzunlik birligi.",
    historySummary: "Zamonaviy o'lchov tizimlari joriy etilgunga qadar Vizantiya arxitekturasida qo'llanilgan.",
    measurementSystem: "SI dan tashqari, Vizantiya tarixiy birligi",
    siEquivalent: "1 pus ≈ 0,3148 m",
    commonUses: "Vizantiya arxitekturasi va tarixiy tadqiqotlar",
  },
  {
    locale: "uz",
    sourceSlug: "bizans-kulaci",
    slug: "vizantiya-kulochi",
    category: "uzunluk",
    categoryName: "Uzunlik",
    unit: "orgyia",
    name: "Vizantiya Kulochi",
    symbol: "orgyia",
    shortDescription: "Vizantiya kulochi inson qo'l uzunligiga taxminan teng bo'lgan kattaroq uzunlik birligi.",
    historySummary: "Vizantiya imperiyasida katta masofalar va yer uchastkalarini o'lchashda ishlatilgan.",
    measurementSystem: "SI dan tashqari, Vizantiya tarixiy birligi",
    siEquivalent: "1 orgyia ≈ 1,8888 m",
    commonUses: "Vizantiya yer o'lchovlari va tarixiy hujjatlar",
  },
  {
    locale: "uz",
    sourceSlug: "cig",
    slug: "chig",
    category: "uzunluk",
    categoryName: "Uzunlik",
    unit: "çığ",
    name: "Chig",
    symbol: "chig",
    shortDescription: "Chig qadimgi turkiy manbalarda uchraydigan uzunlik birligi.",
    historySummary: "Qiymati Qashqarli Mahmudning Devonu Lug'otit-Turk asari asosida taxminan 33,3 santimetr deb aniqlangan.",
    measurementSystem: "SI dan tashqari, qadimgi turkiy tarixiy birlik",
    siEquivalent: "1 chig ≈ 0,333 m",
    commonUses: "Qadimgi turkiy o'lchov birliklari tadqiqoti",
  },
  {
    locale: "uz",
    sourceSlug: "santimetrekare",
    slug: "kvadrat-santimetr",
    category: "alan",
    categoryName: "Yuza",
    unit: "cm²",
    name: "Kvadrat Santimetr",
    symbol: "cm²",
    shortDescription: "Kvadrat santimetr kichik yuzalarni o'lchashda ishlatiladigan birlik.",
    historySummary: "Texnik chizmalarda va kichik buyumlar yuzasini ifodalashda keng qo'llaniladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, quyi birlik)",
    siEquivalent: "1 sm² = 0,0001 m²",
    commonUses: "Texnik chizmalar, mato va kichik yuzalar",
  },
  {
    locale: "uz",
    sourceSlug: "milimetrekare",
    slug: "kvadrat-millimetr",
    category: "alan",
    categoryName: "Yuza",
    unit: "mm²",
    name: "Kvadrat Millimetr",
    symbol: "mm²",
    shortDescription: "Kvadrat millimetr juda kichik yuzalarni aniq o'lchash uchun ishlatiladi.",
    historySummary: "Elektronika va aniqlik ishlab chiqarishda kesim yuzasini ifodalashda qo'llaniladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, quyi birlik)",
    siEquivalent: "1 mm² = 0,000001 m²",
    commonUses: "Elektronika, aniqlik ishlab chiqarish",
  },
  {
    locale: "uz",
    sourceSlug: "kilometrekare",
    slug: "kvadrat-kilometr",
    category: "alan",
    categoryName: "Yuza",
    unit: "km²",
    name: "Kvadrat Kilometr",
    symbol: "km²",
    shortDescription: "Kvadrat kilometr davlat, shahar va katta hududlarning yuzasini o'lchashda ishlatiladi.",
    historySummary: "Geografiya va statistikada katta yer maydonlarini ifodalash uchun qo'llaniladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, ko'paytma)",
    siEquivalent: "1 km² = 1 000 000 m²",
    commonUses: "Geografiya, kartografiya, hudud statistikasi",
  },
  {
    locale: "uz",
    sourceSlug: "fitkare",
    slug: "kvadrat-fut",
    category: "alan",
    categoryName: "Yuza",
    unit: "ft²",
    name: "Kvadrat Fut",
    symbol: "ft²",
    shortDescription: "Kvadrat fut AQSHda uy-joy va qurilish yuzasini o'lchashda keng qo'llaniladi.",
    historySummary: "Amerika ko'chmas mulk va qurilish sanoatida standart yuza birligi hisoblanadi.",
    measurementSystem: "Angliya-Amerika o'lchov tizimi (SI dan tashqari)",
    siEquivalent: "1 ft² ≈ 0,0929 m²",
    commonUses: "AQSH ko'chmas mulk va qurilish hisoblari",
  },
  {
    locale: "uz",
    sourceSlug: "incare",
    slug: "kvadrat-dyum",
    category: "alan",
    categoryName: "Yuza",
    unit: "in²",
    name: "Kvadrat Dyum",
    symbol: "in²",
    shortDescription: "Kvadrat dyum kichik yuzalarni o'lchashda ishlatiladigan an'anaviy birlik.",
    historySummary: "AQSH sanoat va elektronika spetsifikatsiyalarida keng uchraydi.",
    measurementSystem: "Angliya-Amerika o'lchov tizimi (SI dan tashqari)",
    siEquivalent: "1 in² ≈ 6,4516 sm²",
    commonUses: "AQSH sanoat spetsifikatsiyalari, kichik ekranlar",
  },
  {
    locale: "uz",
    sourceSlug: "akre",
    slug: "akr",
    category: "alan",
    categoryName: "Yuza",
    unit: "ac",
    name: "Akr",
    symbol: "ac",
    shortDescription: "Akr AQSH va Buyuk Britaniyada qishloq xo'jaligi yerlarini o'lchashda ishlatiladigan katta yuza birligi.",
    historySummary: "O'rta asrlardan kelib chiqqan bo'lib, dastlab bir juft ho'kiz bir kunda haydaydigan yer maydoniga teng bo'lgan.",
    measurementSystem: "Angliya-Amerika o'lchov tizimi (SI dan tashqari)",
    siEquivalent: "1 akr ≈ 4046,86 m²",
    commonUses: "AQSH va Buyuk Britaniyada ko'chmas mulk va qishloq xo'jaligi",
  },
  {
    locale: "uz",
    sourceSlug: "donum",
    slug: "donum",
    category: "alan",
    categoryName: "Yuza",
    unit: "dönüm",
    name: "Donum",
    symbol: "donum",
    shortDescription: "Donum Turkiya va Yaqin Sharqda qishloq xo'jaligi yerlarini o'lchashda ishlatiladigan mintaqaviy birlik.",
    historySummary: "Usmonli davridan qolgan bo'lib, hozir ham Turkiyaning qishloq hududlarida amaliy yuza birligi sifatida qo'llaniladi.",
    measurementSystem: "SI dan tashqari, mintaqaviy birlik",
    siEquivalent: "1 donum = 1000 m²",
    commonUses: "Turkiya va Yaqin Sharqda qishloq xo'jaligi yerlari",
  },
  {
    locale: "uz",
    sourceSlug: "dekar",
    slug: "dekar",
    category: "alan",
    categoryName: "Yuza",
    unit: "dekar",
    name: "Dekar",
    symbol: "dekar",
    shortDescription: "Dekar 1000 kvadrat metrga teng mintaqaviy yuza birligi, Bolqon va Sharqiy O'rta yer dengizi hududlarida keng tarqalgan.",
    historySummary: "Metrik tizimdan kelib chiqqan bo'lib, ba'zi qo'shni hududlarda donumga muqobil mahalliy birlik sifatida ishlatiladi.",
    measurementSystem: "SI dan tashqari, mintaqaviy birlik",
    siEquivalent: "1 dekar = 1000 m²",
    commonUses: "Bolqon hududida qishloq xo'jaligi yerlari",
  },
  {
    locale: "uz",
    sourceSlug: "mililitre",
    slug: "millilitr",
    category: "hacim",
    categoryName: "Hajm",
    unit: "mL",
    name: "Millilitr",
    symbol: "mL",
    shortDescription: "Millilitr litrning mingdan bir qismiga teng kichik hajm birligi.",
    historySummary: "Tibbiyot dozalari va laboratoriya o'lchovlarida keng qo'llaniladi.",
    measurementSystem: "Metrik tizim (SI dan tashqari, quyi birlik)",
    siEquivalent: "1 mL = 0,000001 m³",
    commonUses: "Tibbiy dozalar, laboratoriya, oshxona o'lchovlari",
  },
  {
    locale: "uz",
    sourceSlug: "santimetrekup",
    slug: "kub-santimetr",
    category: "hacim",
    categoryName: "Hajm",
    unit: "cm³",
    name: "Kub Santimetr",
    symbol: "cm³",
    shortDescription: "Kub santimetr millilitrga to'liq teng bo'lgan kichik hajm birligi.",
    historySummary: "Tibbiyot, kimyo va avtomobil dvigateli hajmini ifodalashda keng qo'llaniladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, quyi birlik)",
    siEquivalent: "1 sm³ = 1 mL = 0,000001 m³",
    commonUses: "Avtomobil dvigateli hajmi, tibbiy dozalar",
  },
  {
    locale: "uz",
    sourceSlug: "fitkup",
    slug: "kub-fut",
    category: "hacim",
    categoryName: "Hajm",
    unit: "ft³",
    name: "Kub Fut",
    symbol: "ft³",
    shortDescription: "Kub fut AQSH qurilish va konditsioner texnikasida ishlatiladigan an'anaviy hajm birligi.",
    historySummary: "AQSH klimat texnikasi spetsifikatsiyalarida standart hisoblanadi.",
    measurementSystem: "Angliya-Amerika o'lchov tizimi (SI dan tashqari)",
    siEquivalent: "1 ft³ ≈ 0,0283 m³",
    commonUses: "AQSH klimat texnikasi va qurilish hisoblari",
  },
  {
    locale: "uz",
    sourceSlug: "inckup",
    slug: "kub-dyum",
    category: "hacim",
    categoryName: "Hajm",
    unit: "in³",
    name: "Kub Dyum",
    symbol: "in³",
    shortDescription: "Kub dyum eski AQSH avtomobil dvigatellari hajmini ifodalashda ishlatiladigan kichik hajm birligi.",
    historySummary: "Klassik amerika avtomobillari dvigatellarini tasniflashda tarixiy standart bo'lgan.",
    measurementSystem: "Angliya-Amerika o'lchov tizimi (SI dan tashqari)",
    siEquivalent: "1 in³ ≈ 16,39 sm³",
    commonUses: "Klassik AQSH avtomobil dvigatellari tasnifi",
  },
  {
    locale: "uz",
    sourceSlug: "galon",
    slug: "gallon",
    category: "hacim",
    categoryName: "Hajm",
    unit: "gal",
    name: "Gallon",
    symbol: "gal",
    shortDescription: "Gallon AQSH va Buyuk Britaniyada suyuqliklarni o'lchashda keng qo'llaniladigan an'anaviy hajm birligi.",
    historySummary: "AQSH gallon va imperial gallon qiymati bo'yicha farqlanadi, ikkalasi ham tarixiy ingliz o'lchov tizimidan kelib chiqqan.",
    measurementSystem: "Angliya-Amerika o'lchov tizimi (SI dan tashqari)",
    siEquivalent: "1 AQSH galloni ≈ 3,785 litr",
    commonUses: "Yoqilg'i va suyuqlik miqdorlari AQSH va Buyuk Britaniyada",
  },
  {
    locale: "uz",
    sourceSlug: "varil",
    slug: "barrel",
    category: "hacim",
    categoryName: "Hajm",
    unit: "bbl",
    name: "Barrel",
    symbol: "bbl",
    shortDescription: "Barrel xalqaro neft savdosida ishlatiladigan standartlashtirilgan hajm birligi.",
    historySummary: "AQSH neft sanoatining dastlabki davrlaridan beri xom neft savdosining jahon standarti bo'lib qolgan.",
    measurementSystem: "SI dan tashqari, xalqaro savdo birligi",
    siEquivalent: "1 barrel ≈ 158,987 litr",
    commonUses: "Xom neft xalqaro savdosi va energiya bozorlari",
  },
  {
    locale: "uz",
    sourceSlug: "miligram",
    slug: "milligram",
    category: "kutle",
    categoryName: "Massa",
    unit: "mg",
    name: "Milligram",
    symbol: "mg",
    shortDescription: "Milligram gramning mingdan bir qismiga teng juda kichik massa birligi.",
    historySummary: "Dorivor moddalar va aniq laboratoriya o'lchovlarida keng qo'llaniladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, quyi birlik)",
    siEquivalent: "1 mg = 0,000001 kg",
    commonUses: "Dori dozalari, laboratoriya o'lchovlari",
  },
  {
    locale: "uz",
    sourceSlug: "ton",
    slug: "tonna",
    category: "kutle",
    categoryName: "Massa",
    unit: "ton",
    name: "Tonna",
    symbol: "t",
    shortDescription: "Tonna 1000 kilogrammga teng katta massa birligi, yuk va sanoatda ishlatiladi.",
    historySummary: "Yuk tashish va sanoat ishlab chiqarishida katta massalarni ifodalash uchun keng qo'llaniladi.",
    measurementSystem: "Metrik tizim (SI dan tashqari, ko'paytma)",
    siEquivalent: "1 t = 1000 kg",
    commonUses: "Yuk tashish, sanoat ishlab chiqarish",
  },
  {
    locale: "uz",
    sourceSlug: "pound",
    slug: "funt",
    category: "kutle",
    categoryName: "Massa",
    unit: "lb",
    name: "Funt",
    symbol: "lb",
    shortDescription: "Funt AQSH va Buyuk Britaniyada kundalik og'irlik o'lchovida keng qo'llaniladigan massa birligi.",
    historySummary: "Rim libra birligidan kelib chiqqan, hozir angliya-amerika tizimida standartlashtirilgan.",
    measurementSystem: "Angliya-Amerika o'lchov tizimi (SI dan tashqari)",
    siEquivalent: "1 funt ≈ 0,4536 kg",
    commonUses: "AQSH va Buyuk Britaniyada kundalik og'irlik o'lchovlari",
  },
  {
    locale: "uz",
    sourceSlug: "ons",
    slug: "untsiya",
    category: "kutle",
    categoryName: "Massa",
    unit: "oz",
    name: "Untsiya",
    symbol: "oz",
    shortDescription: "Untsiya kichik massalarni, ayniqsa oziq-ovqat va qimmatbaho metallarni o'lchashda ishlatiladi.",
    historySummary: "Rim uncia birligidan kelib chiqqan, hozir ham AQSHda oshxona va zargarlik o'lchovlarida qo'llaniladi.",
    measurementSystem: "Angliya-Amerika o'lchov tizimi (SI dan tashqari)",
    siEquivalent: "1 untsiya ≈ 28,35 g",
    commonUses: "Oziq-ovqat retseptlari, qimmatbaho metallar",
  },
  {
    locale: "uz",
    sourceSlug: "okka",
    slug: "okka",
    category: "kutle",
    categoryName: "Massa",
    unit: "okka",
    name: "Okka",
    symbol: "okka",
    shortDescription: "Okka Usmonli davrida kundalik hayotda va savdoda keng ishlatilgan massa birligi.",
    historySummary: "20-asrda metrik tizim joriy etilgunga qadar Usmonli imperiyasida og'irlik uchun standart birlik bo'lgan.",
    measurementSystem: "SI dan tashqari, tarixiy Usmonli birligi",
    siEquivalent: "1 okka ≈ 1,283 kg",
    commonUses: "Tarixiy savdo va Usmonli davri tadqiqotlari",
  },
  {
    locale: "uz",
    sourceSlug: "dirhem",
    slug: "dirham",
    category: "kutle",
    categoryName: "Massa",
    unit: "dirhem",
    name: "Dirham",
    symbol: "dirham",
    shortDescription: "Dirham Usmonli davrida asosan qimmatbaho metallar va ziravorlar uchun ishlatilgan kichikroq massa birligi.",
    historySummary: "Okkaning quyi birligi bo'lib, Usmonli savdosida kichik og'irliklarni aniq ifodalash uchun qo'llanilgan.",
    measurementSystem: "SI dan tashqari, tarixiy Usmonli birligi",
    siEquivalent: "1 dirham ≈ 3,207 g",
    commonUses: "Tarixiy qimmatbaho metall va ziravor savdosi",
  },
  {
    locale: "uz",
    sourceSlug: "bizans-litrasi",
    slug: "vizantiya-litrasi",
    category: "kutle",
    categoryName: "Massa",
    unit: "litra",
    name: "Vizantiya Litrasi",
    symbol: "litra",
    shortDescription: "Vizantiya litrasi Vizantiya imperiyasida ishlatilgan, Rim funtiga o'xshash massa birligi.",
    historySummary: "Usmonli bosqinigacha Vizantiya savdosi va zargarligida qo'llanilgan.",
    measurementSystem: "SI dan tashqari, Vizantiya tarixiy birligi",
    siEquivalent: "1 litra ≈ 0,324 kg",
    commonUses: "Vizantiya savdosi va tarixiy tadqiqotlar",
  },
  {
    locale: "uz",
    sourceSlug: "bizans-onsu",
    slug: "vizantiya-unsiyasi",
    category: "kutle",
    categoryName: "Massa",
    unit: "ounkia",
    name: "Vizantiya Unsiyasi",
    symbol: "ounkia",
    shortDescription: "Ounkia Vizantiya litrasining o'n ikkidan bir qismiga teng kichik massa birligi.",
    historySummary: "Vizantiya kundalik savdosida kichik miqdorlarni tortishda ishlatilgan.",
    measurementSystem: "SI dan tashqari, Vizantiya tarixiy birligi",
    siEquivalent: "1 ounkia ≈ 27 g",
    commonUses: "Vizantiya kundalik savdosi va tarixiy tadqiqotlar",
  },
  {
    locale: "uz",
    sourceSlug: "kilogram-metrekup",
    slug: "kilogram-kub-metr",
    category: "yogunluk",
    categoryName: "Zichlik",
    unit: "kg/m³",
    name: "Kilogram/Kub Metr",
    symbol: "kg/m³",
    shortDescription: "Kilogram/kub metr zichlikning SI asosiy birligi, massa va hajm nisbatini bildiradi.",
    historySummary: "Fan va texnikada zichlik ko'rsatishning xalqaro standartlashtirilgan asosiy birligi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, asosiy birlik)",
    siEquivalent: "Zichlikning asosiy SI birligi",
    commonUses: "Materialshunoslik, fizika, texnik hisoblar",
  },
  {
    locale: "uz",
    sourceSlug: "gram-santimetrekup",
    slug: "gram-kub-santimetr",
    category: "yogunluk",
    categoryName: "Zichlik",
    unit: "g/cm³",
    name: "Gram/Kub Santimetr",
    symbol: "g/cm³",
    shortDescription: "Gram/kub santimetr kimyo va laboratoriya amaliyotida keng qo'llaniladigan amaliy zichlik birligi.",
    historySummary: "Suv va boshqa keng tarqalgan materiallarning zichligini qulay raqamlar bilan ifodalash uchun ishlatiladi.",
    measurementSystem: "Metrik tizim (SI quyi birliklari)",
    siEquivalent: "1 g/sm³ = 1000 kg/m³",
    commonUses: "Kimyo, materialshunoslik, laboratoriya ishlari",
  },
  {
    locale: "uz",
    sourceSlug: "metre-saniye",
    slug: "metr-soniyaga",
    category: "hiz",
    categoryName: "Tezlik",
    unit: "m/s",
    name: "Metr/Soniya",
    symbol: "m/s",
    shortDescription: "Metr/soniya tezlikning SI asosiy birligi, fan va texnikada ishlatiladi.",
    historySummary: "Fizik hisoblarda tezlik ko'rsatishning xalqaro standartlashtirilgan birligi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, asosiy birlik)",
    siEquivalent: "Tezlikning asosiy SI birligi",
    commonUses: "Fizika, texnika, ilmiy hisoblar",
  },
  {
    locale: "uz",
    sourceSlug: "mil-saat",
    slug: "milya-soatiga",
    category: "hiz",
    categoryName: "Tezlik",
    unit: "mph",
    name: "Milya/Soat",
    symbol: "mph",
    shortDescription: "Milya/soat AQSH va Buyuk Britaniya yo'l harakatida ishlatiladigan tezlik birligi.",
    historySummary: "AQSH va Buyuk Britaniya spidometrlari va yo'l belgilarida standart hisoblanadi.",
    measurementSystem: "Angliya-Amerika o'lchov tizimi (SI dan tashqari)",
    siEquivalent: "1 mph ≈ 1,609 km/soat",
    commonUses: "AQSH va Buyuk Britaniya yo'l harakati",
  },
  {
    locale: "uz",
    sourceSlug: "knot",
    slug: "uzel",
    category: "hiz",
    categoryName: "Tezlik",
    unit: "knot",
    name: "Uzel",
    symbol: "uzel",
    shortDescription: "Uzel dengiz va havo navigatsiyasida ishlatiladigan, bir dengiz milyasi/soatga teng tezlik birligi.",
    historySummary: "Nomi kemaning tezligini tugunlangan arqon yordamida o'lchash tarixiy usulidan kelib chiqqan.",
    measurementSystem: "SI dan tashqari, xalqaro navigatsiya birligi",
    siEquivalent: "1 uzel ≈ 0,5144 m/s",
    commonUses: "Dengiz va havo navigatsiyasi, shamol tezligi",
  },
  {
    locale: "uz",
    sourceSlug: "isik-hizi",
    slug: "yorugliktezligi",
    category: "hiz",
    categoryName: "Tezlik",
    unit: "c",
    name: "Yorug'lik Tezligi",
    symbol: "c",
    shortDescription: "Yorug'lik tezligi vakuumda yorug'lik tarqalish tezligi bo'lib, fundamental fizik konstanta hisoblanadi.",
    historySummary: "Hozir aniq belgilangan bo'lib, zamonaviy metr ta'rifining asosini tashkil qiladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, tabiat konstantasi)",
    siEquivalent: "Fizika va astronomiyaning asosiy konstantasi",
    commonUses: "Fizika, astronomiya, metr ta'rifi",
  },
  {
    locale: "uz",
    sourceSlug: "metre-saniyekare",
    slug: "metr-soniya-kvadratga",
    category: "ivme",
    categoryName: "Tezlanish",
    unit: "m/s²",
    name: "Metr/Soniya Kvadrat",
    symbol: "m/s²",
    shortDescription: "Metr/soniya kvadrat tezlanishning SI asosiy birligi.",
    historySummary: "Fizika va texnikada tezlanish ko'rsatishning xalqaro standartlashtirilgan birligi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, asosiy birlik)",
    siEquivalent: "Tezlanishning asosiy SI birligi",
    commonUses: "Fizika, avtomobil texnikasi, ilmiy hisoblar",
  },
  {
    locale: "uz",
    sourceSlug: "fit-saniyekare",
    slug: "fut-soniya-kvadratga",
    category: "ivme",
    categoryName: "Tezlanish",
    unit: "ft/s²",
    name: "Fut/Soniya Kvadrat",
    symbol: "ft/s²",
    shortDescription: "Fut/soniya kvadrat AQSHda ishlatiladigan angliya-amerika tezlanish birligi.",
    historySummary: "AQSH texnika va aviatsiyasida metrik birlik o'rniga qo'llaniladi.",
    measurementSystem: "Angliya-Amerika o'lchov tizimi (SI dan tashqari)",
    siEquivalent: "1 ft/s² ≈ 0,3048 m/s²",
    commonUses: "AQSH texnikasi va aviatsiya hisoblari",
  },
  {
    locale: "uz",
    sourceSlug: "yercekimi-ivmesi",
    slug: "yer-tortishish-tezlanishi",
    category: "ivme",
    categoryName: "Tezlanish",
    unit: "g0",
    name: "Yer Tortishish Tezlanishi (g)",
    symbol: "g",
    shortDescription: "Yer tortishish tezlanishi yer yuzasiga yaqin erkin tushayotgan jismning standart tezlanishi.",
    historySummary: "9,80665 m/s² standart qiymati xalqaro miqyosda belgilangan va amaliy taqqoslash birligi sifatida ishlatiladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, standart konstanta)",
    siEquivalent: "Fizika va kosmonavtikaning standart konstantasi",
    commonUses: "Fizika, kosmonavtika, tezlanish taqqoslash",
  },
  {
    locale: "uz",
    sourceSlug: "dakika",
    slug: "daqiqa",
    category: "zaman",
    categoryName: "Vaqt",
    unit: "min",
    name: "Daqiqa",
    symbol: "min",
    shortDescription: "Daqiqa 60 soniyaga teng, kundalik vaqt hisobida keng qo'llaniladigan vaqt birligi.",
    historySummary: "Qadimgi bobil oltmish asosli sanoq tizimidan kelib chiqqan bo'lib, bugun ham dunyo miqyosida qo'llaniladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI dan tashqari, keng tarqalgan)",
    siEquivalent: "1 daqiqa = 60 s",
    commonUses: "Kundalik jadval, sport, fan",
  },
  {
    locale: "uz",
    sourceSlug: "gun",
    slug: "kun",
    category: "zaman",
    categoryName: "Vaqt",
    unit: "day",
    name: "Kun",
    symbol: "kun",
    shortDescription: "Kun bir marta to'liq yer aylanishiga teng vaqt birligi.",
    historySummary: "Insoniyat tomonidan ishlatilgan eng qadimgi vaqt birliklaridan biri bo'lib, kalendarlarning asosi hisoblanadi.",
    measurementSystem: "SI dan tashqari, keng tarqalgan vaqt birligi",
    siEquivalent: "1 kun = 86 400 s",
    commonUses: "Kalendar, kundalik reja, vaqt hisobi",
  },
  {
    locale: "uz",
    sourceSlug: "radyan-saniye",
    slug: "radian-soniyaga",
    category: "acisal_hiz",
    categoryName: "Burchak tezligi",
    unit: "rad/s",
    name: "Radian/Soniya",
    symbol: "rad/s",
    shortDescription: "Radian/soniya burchak tezligining SI asosiy birligi.",
    historySummary: "Fizika va mashinasozlikda aylanish harakatini aniq tavsiflashda ishlatiladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, asosiy birlik)",
    siEquivalent: "Burchak tezligining asosiy SI birligi",
    commonUses: "Mashinasozlik, robototexnika, aylanish fizikasi",
  },
  {
    locale: "uz",
    sourceSlug: "devir-dakika",
    slug: "aylanish-daqiqaga",
    category: "acisal_hiz",
    categoryName: "Burchak tezligi",
    unit: "rpm",
    name: "Aylanish/Daqiqa (RPM)",
    symbol: "rpm",
    shortDescription: "RPM motor va aylanuvchi mashinalar tezligini ifodalashda keng qo'llaniladigan birlik.",
    historySummary: "Motor va disklarning aylanish tezligini ko'rsatuvchi standart amaliy birlik.",
    measurementSystem: "SI dan tashqari, keng tarqalgan texnik birlik",
    siEquivalent: "SI dan tashqari, texnik amaliy birlik",
    commonUses: "Motor tezligi, mashinasozlik, disk tezligi",
  },
  {
    locale: "uz",
    sourceSlug: "derece-saniye",
    slug: "daraja-soniyaga",
    category: "acisal_hiz",
    categoryName: "Burchak tezligi",
    unit: "°/s",
    name: "Daraja/Soniya",
    symbol: "°/s",
    shortDescription: "Daraja/soniya burchak asosidagi tushunarli tezlik birligi.",
    historySummary: "Robototexnika va sensor texnologiyasida daraja qiymatlari radiandan ko'ra tushunarliroq bo'lgani uchun ishlatiladi.",
    measurementSystem: "SI dan tashqari, keng tarqalgan birlik",
    siEquivalent: "1 °/s = π/180 rad/s",
    commonUses: "Robototexnika, sensor texnologiyasi",
  },
  {
    locale: "uz",
    sourceSlug: "radyan",
    slug: "radian",
    category: "aci",
    categoryName: "Burchak",
    unit: "rad",
    name: "Radian",
    symbol: "rad",
    shortDescription: "Radian tekis burchaklar uchun SI birligi bo'lib, yoy uzunligi va radius nisbatiga asoslanadi.",
    historySummary: "Matematika va fizikada daraja o'rniga afzal ko'riladigan burchak birligi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, hosila birlik)",
    siEquivalent: "1 to'liq aylana = 2π radian",
    commonUses: "Matematika, fizika, texnik hisoblar",
  },
  {
    locale: "uz",
    sourceSlug: "derece",
    slug: "daraja",
    category: "aci",
    categoryName: "Burchak",
    unit: "°",
    name: "Daraja",
    symbol: "°",
    shortDescription: "Daraja kundalik hayotda eng ko'p ishlatiladigan burchak birligi, to'liq aylana 360 darajaga teng.",
    historySummary: "360 ga bo'linish bobil astronomiyasidan kelib chiqqan va hozir ham dunyo miqyosida qo'llaniladi.",
    measurementSystem: "SI dan tashqari, dunyo miqyosida keng tarqalgan birlik",
    siEquivalent: "1 to'liq aylana = 360°",
    commonUses: "Geometriya, navigatsiya, kundalik burchak ko'rsatkichlari",
  },
  {
    locale: "uz",
    sourceSlug: "gradyan",
    slug: "grad",
    category: "aci",
    categoryName: "Burchak",
    unit: "gon",
    name: "Grad",
    symbol: "gon",
    shortDescription: "Grad to'liq aylanani 400 qismga bo'lib, asosan geodeziyada ishlatiladi.",
    historySummary: "Metrik tizim joriy etilishi bilan burchaklarni o'nlik tizimda bo'lish uchun ishlab chiqilgan.",
    measurementSystem: "SI dan tashqari, geodezik birlik",
    siEquivalent: "1 to'liq aylana = 400 gon",
    commonUses: "Geodeziya, yer o'lchash ishlari",
  },
  {
    locale: "uz",
    sourceSlug: "tam-tur",
    slug: "toliq-aylanish",
    category: "aci",
    categoryName: "Burchak",
    unit: "tur",
    name: "To'liq Aylanish",
    symbol: "aylanish",
    shortDescription: "To'liq aylanish bir nuqta atrofida to'liq aylanishga, ya'ni 360 darajaga teng.",
    historySummary: "O'q atrofida bir yoki bir necha to'liq aylanishni tavsiflashda ishlatiladigan tushunarli burchak birligi.",
    measurementSystem: "SI dan tashqari, amaliy birlik",
    siEquivalent: "1 aylanish = 360° = 2π radian",
    commonUses: "Mexanik aylanish harakatlarini tavsiflash",
  },
  {
    locale: "uz",
    sourceSlug: "hertz",
    slug: "gerts",
    category: "frekans",
    categoryName: "Chastota",
    unit: "Hz",
    name: "Gerts",
    symbol: "Hz",
    shortDescription: "Gerts chastotaning SI birligi bo'lib, soniyadagi tebranishlar sonini bildiradi.",
    historySummary: "Geynrix Gerts nomi bilan atalgan bo'lib, elektrotexnika va akustikada asosiy chastota birligi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, asosiy birlik)",
    siEquivalent: "Chastotaning asosiy SI birligi",
    commonUses: "Elektrotexnika, akustika, signal ishlov berish",
  },
  {
    locale: "uz",
    sourceSlug: "kilohertz",
    slug: "kilogerts",
    category: "frekans",
    categoryName: "Chastota",
    unit: "kHz",
    name: "Kilogerts",
    symbol: "kHz",
    shortDescription: "Kilogerts 1000 gertsga teng bo'lib, o'rta chastotali audio signallar uchun ishlatiladi.",
    historySummary: "Radio chastotalari va audio namunalash tezligini ko'rsatishda keng qo'llaniladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, ko'paytma)",
    siEquivalent: "1 kGts = 1000 Gts",
    commonUses: "Radio chastotalari, audio texnika",
  },
  {
    locale: "uz",
    sourceSlug: "megahertz",
    slug: "megagerts",
    category: "frekans",
    categoryName: "Chastota",
    unit: "MHz",
    name: "Megagerts",
    symbol: "MHz",
    shortDescription: "Megagerts bir million gertsga teng bo'lib, radioto'lqin va protsessor chastotalari uchun ishlatiladi.",
    historySummary: "Radioeshittirish chastotalari va eski kompyuter protsessor tezligini ko'rsatishda standart hisoblanadi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, ko'paytma)",
    siEquivalent: "1 MGts = 1 000 000 Gts",
    commonUses: "Radioeshittirish chastotalari, protsessor texnikasi",
  },
  {
    locale: "uz",
    sourceSlug: "gigahertz",
    slug: "gigagerts",
    category: "frekans",
    categoryName: "Chastota",
    unit: "GHz",
    name: "Gigagerts",
    symbol: "GHz",
    shortDescription: "Gigagerts bir milliard gertsga teng bo'lib, zamonaviy protsessor chastotalari uchun ishlatiladigan birlik.",
    historySummary: "Zamonaviy kompyuter protsessorlari va simsiz aloqa tizimlari chastotasini ko'rsatishda standart.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, ko'paytma)",
    siEquivalent: "1 GGts = 1 000 000 000 Gts",
    commonUses: "Protsessor texnikasi, simsiz aloqa",
  },
  {
    locale: "uz",
    sourceSlug: "newton",
    slug: "nyuton",
    category: "kuvvet",
    categoryName: "Kuch",
    unit: "N",
    name: "Nyuton",
    symbol: "N",
    shortDescription: "Nyuton kuchning SI birligi bo'lib, Isaak Nyuton nomi bilan atalgan.",
    historySummary: "Fizika va texnikada kuch ko'rsatishning dunyo miqyosidagi asosiy birligi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, hosila birlik)",
    siEquivalent: "Kuchning asosiy SI birligi",
    commonUses: "Fizika, mashinasozlik, texnik hisoblar",
  },
  {
    locale: "uz",
    sourceSlug: "kilogram-kuvvet",
    slug: "kilogram-kuch",
    category: "kuvvet",
    categoryName: "Kuch",
    unit: "kgf",
    name: "Kilogram-Kuch",
    symbol: "kgf",
    shortDescription: "Kilogram-kuch bir kilogramm massaning standart tortishish kuchi ostidagi og'irlik kuchiga teng an'anaviy birlik.",
    historySummary: "SI tizimi to'liq standartlashtirilishidan oldin ishlatilgan bo'lib, hozir ham eski texnik hujjatlarda uchraydi.",
    measurementSystem: "SI dan tashqari, an'anaviy birlik",
    siEquivalent: "1 kgf ≈ 9,80665 N",
    commonUses: "Eski texnik spetsifikatsiyalar va muhandislik",
  },
  {
    locale: "uz",
    sourceSlug: "newton-metre",
    slug: "nyuton-metr",
    category: "tork",
    categoryName: "Tork",
    unit: "N·m",
    name: "Nyuton-Metr",
    symbol: "N·m",
    shortDescription: "Nyuton-metr torkning SI birligi bo'lib, murvat ulanishlari va motorlarda ishlatiladi.",
    historySummary: "Texnika va avtomobil sanoatida tork ko'rsatishning xalqaro standarti.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, hosila birlik)",
    siEquivalent: "Torkning asosiy SI birligi",
    commonUses: "Avtomobil texnikasi, murvat ulanishlari, mashinasozlik",
  },
  {
    locale: "uz",
    sourceSlug: "kilogram-kuvvet-metre",
    slug: "kilogram-kuch-metr",
    category: "tork",
    categoryName: "Tork",
    unit: "kgf·m",
    name: "Kilogram-Kuch-Metr",
    symbol: "kgf·m",
    shortDescription: "Kilogram-kuch-metr eski texnik qo'llanmalarda hali ham uchraydigan an'anaviy tork birligi.",
    historySummary: "Ko'p mamlakatlarda nyuton-metrga to'liq o'tishdan oldin ishlatilgan.",
    measurementSystem: "SI dan tashqari, an'anaviy birlik",
    siEquivalent: "1 kgf·m ≈ 9,80665 N·m",
    commonUses: "Eski texnik qo'llanmalar va muhandislik",
  },
  {
    locale: "uz",
    sourceSlug: "pound-fit",
    slug: "funt-fut",
    category: "tork",
    categoryName: "Tork",
    unit: "lb·ft",
    name: "Funt-Fut",
    symbol: "lb·ft",
    shortDescription: "Funt-fut AQSHda motor va asboblar uchun ishlatiladigan angliya-amerika tork birligi.",
    historySummary: "AQSH avtomobil va asbob spetsifikatsiyalarida tork ko'rsatishning standarti.",
    measurementSystem: "Angliya-Amerika o'lchov tizimi (SI dan tashqari)",
    siEquivalent: "1 lb·ft ≈ 1,3558 N·m",
    commonUses: "AQSH avtomobil texnikasi va asboblar",
  },
  {
    locale: "uz",
    sourceSlug: "kilogram-metre-saniye",
    slug: "kilogram-metr-soniyaga",
    category: "momentum",
    categoryName: "Impuls",
    unit: "kg·m/s",
    name: "Kilogram-Metr/Soniya",
    symbol: "kg·m/s",
    shortDescription: "Kilogram-metr/soniya klassik mexanikada impulsning SI birligi.",
    historySummary: "Harakat miqdorini tavsiflashda fizik hisoblarda ishlatiladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, hosila birlik)",
    siEquivalent: "Impulsning asosiy SI birligi",
    commonUses: "Fizika va mexanika hisoblari",
  },
  {
    locale: "uz",
    sourceSlug: "newton-saniye",
    slug: "nyuton-soniya",
    category: "momentum",
    categoryName: "Impuls",
    unit: "N·s",
    name: "Nyuton-Soniya",
    symbol: "N·s",
    shortDescription: "Nyuton-soniya kilogram-metr/soniyaga teng, impulsning muqobil birligi.",
    historySummary: "Kuch, vaqt va impuls o'zgarishi orasidagi bog'liqlikni ifodalash uchun ishlatiladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, hosila birlik)",
    siEquivalent: "1 N·s = 1 kg·m/s",
    commonUses: "Fizika, zarba va to'qnashuv hisoblari",
  },
  {
    locale: "uz",
    sourceSlug: "kilopascal",
    slug: "kilopaskal",
    category: "basinc",
    categoryName: "Bosim",
    unit: "kPa",
    name: "Kilopaskal",
    symbol: "kPa",
    shortDescription: "Kilopaskal 1000 paskalga teng, amaliy bosim o'lchovlarida keng qo'llaniladi.",
    historySummary: "Muhandislik va meteorologiyada qulay raqamli qiymatlar berish uchun ishlatiladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, ko'paytma)",
    siEquivalent: "1 kPa = 1000 Pa",
    commonUses: "Muhandislik, meteorologiya, shina bosimi",
  },
  {
    locale: "uz",
    sourceSlug: "bar",
    slug: "bar",
    category: "basinc",
    categoryName: "Bosim",
    unit: "bar",
    name: "Bar",
    symbol: "bar",
    shortDescription: "Bar taxminan atmosfera bosimiga teng amaliy bosim birligi.",
    historySummary: "Meteorologiya va sanoatda keng qo'llaniladigan qulay bosim birligi sifatida ishlab chiqilgan.",
    measurementSystem: "SI dan tashqari, keng tarqalgan amaliy birlik",
    siEquivalent: "1 bar = 100 000 Pa",
    commonUses: "Meteorologiya, sanoat bosim ko'rsatkichlari",
  },
  {
    locale: "uz",
    sourceSlug: "milibar",
    slug: "millibar",
    category: "basinc",
    categoryName: "Bosim",
    unit: "mbar",
    name: "Millibar",
    symbol: "mbar",
    shortDescription: "Millibar meteorologiyada havo bosimini ko'rsatishda keng qo'llaniladigan bosim birligi.",
    historySummary: "Dunyo miqyosidagi ob-havo hisobotlarida havo bosimi tizimlarini tavsiflashning standarti bo'lgan.",
    measurementSystem: "SI dan tashqari, keng tarqalgan meteorologik birlik",
    siEquivalent: "1 mbar = 100 Pa",
    commonUses: "Ob-havo hisobotlari va xaritalari",
  },
  {
    locale: "uz",
    sourceSlug: "atmosfer",
    slug: "atmosfera",
    category: "basinc",
    categoryName: "Bosim",
    unit: "atm",
    name: "Atmosfera",
    symbol: "atm",
    shortDescription: "Atmosfera dengiz sathidagi o'rtacha havo bosimiga taxminan teng bosim birligi.",
    historySummary: "Fan va texnikada bosim ko'rsatish uchun amaliy taqqoslash qiymati sifatida belgilangan.",
    measurementSystem: "SI dan tashqari, keng tarqalgan taqqoslash birligi",
    siEquivalent: "1 atm ≈ 101 325 Pa",
    commonUses: "Meteorologiya, kimyo, texnik bosim ko'rsatkichlari",
  },
  {
    locale: "uz",
    sourceSlug: "psi",
    slug: "psi",
    category: "basinc",
    categoryName: "Bosim",
    unit: "psi",
    name: "PSI",
    symbol: "psi",
    shortDescription: "PSI (funt/kvadrat dyum) AQSHda shina bosimi va sanoat spetsifikatsiyalarida ishlatiladi.",
    historySummary: "AQSH shina bosimi va sanoat asbob-uskunalarida standart bosim birligi.",
    measurementSystem: "Angliya-Amerika o'lchov tizimi (SI dan tashqari)",
    siEquivalent: "1 psi ≈ 6894,76 Pa",
    commonUses: "AQSH shina bosimi va sanoat spetsifikatsiyalari",
  },
  {
    locale: "uz",
    sourceSlug: "milimetre-civa",
    slug: "simob-ustuni-millimetri",
    category: "basinc",
    categoryName: "Bosim",
    unit: "mmHg",
    name: "Simob Ustuni Millimetri",
    symbol: "mmHg",
    shortDescription: "Simob ustuni millimetri tibbiyotda qon bosimini o'lchashda hali ham ishlatiladigan an'anaviy bosim birligi.",
    historySummary: "Tarixiy simobli bosim o'lchagichlardan kelib chiqqan bo'lib, bugungacha tibbiy dunyo standarti hisoblanadi.",
    measurementSystem: "SI dan tashqari, keng tarqalgan tibbiy birlik",
    siEquivalent: "1 mmHg ≈ 133,322 Pa",
    commonUses: "Qon bosimini o'lchash, tibbiy o'lchovlar",
  },
  {
    locale: "uz",
    sourceSlug: "kilogram-kuvvet-santimetrekare",
    slug: "kilogram-kuch-kvadrat-santimetrga",
    category: "basinc",
    categoryName: "Bosim",
    unit: "kgf/cm²",
    name: "Kilogram-Kuch/Kvadrat Santimetr",
    symbol: "kgf/cm²",
    shortDescription: "Kilogram-kuch/kvadrat santimetr eski shina bosimi va asbob ko'rsatkichlarida uchraydigan an'anaviy bosim birligi.",
    historySummary: "SI tizimi to'liq standartlashtirilishidan oldin ishlatilgan, hozir ham ba'zi eski o'lchagichlarda uchraydi.",
    measurementSystem: "SI dan tashqari, an'anaviy birlik",
    siEquivalent: "1 kgf/sm² ≈ 98 066,5 Pa",
    commonUses: "Eski shina bosimi o'lchagichlari va sanoat uskunalari",
  },
  {
    locale: "uz",
    sourceSlug: "pascal-saniye",
    slug: "paskal-soniya",
    category: "viskozite_dinamik",
    categoryName: "Dinamik qovushqoqlik",
    unit: "Pa·s",
    name: "Paskal-Soniya",
    symbol: "Pa·s",
    shortDescription: "Paskal-soniya dinamik qovushqoqlikning SI birligi bo'lib, suyuqlik oqim qarshiligini bildiradi.",
    historySummary: "Kimyo va muhandislikda suyuqliklarni aniq tavsiflashda ishlatiladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, hosila birlik)",
    siEquivalent: "Dinamik qovushqoqlikning asosiy SI birligi",
    commonUses: "Materialshunoslik, kimyo, suyuqlik tahlili",
  },
  {
    locale: "uz",
    sourceSlug: "santipoise",
    slug: "santipoiz",
    category: "viskozite_dinamik",
    categoryName: "Dinamik qovushqoqlik",
    unit: "cP",
    name: "Santipoiz",
    symbol: "cP",
    shortDescription: "Santipoiz sanoatda eng ko'p ishlatiladigan amaliy dinamik qovushqoqlik birligi.",
    historySummary: "Taxminan 20°C dagi suvning qovushqoqligiga teng bo'lib, amaliy taqqoslash qiymati hisoblanadi.",
    measurementSystem: "CGS tizimi (SI dan tashqari, quyi birlik)",
    siEquivalent: "1 sP = 0,001 Pa·s",
    commonUses: "Motor moyi tasnifi, sanoat suyuqliklari",
  },
  {
    locale: "uz",
    sourceSlug: "metrekare-saniye",
    slug: "kvadrat-metr-soniyaga",
    category: "viskozite_kinematik",
    categoryName: "Kinematik qovushqoqlik",
    unit: "m²/s",
    name: "Kvadrat Metr/Soniya",
    symbol: "m²/s",
    shortDescription: "Kvadrat metr/soniya kinematik qovushqoqlikning SI asosiy birligi.",
    historySummary: "Ilmiy hisoblarda suyuqliklarning oqim xususiyatlarini tavsiflashda ishlatiladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, asosiy birlik)",
    siEquivalent: "Kinematik qovushqoqlikning asosiy SI birligi",
    commonUses: "Suyuqlik mexanikasi va ilmiy hisoblar",
  },
  {
    locale: "uz",
    sourceSlug: "santistok",
    slug: "santistoks",
    category: "viskozite_kinematik",
    categoryName: "Kinematik qovushqoqlik",
    unit: "cSt",
    name: "Santistoks",
    symbol: "cSt",
    shortDescription: "Santistoks sanoatda eng ko'p ishlatiladigan amaliy kinematik qovushqoqlik birligi.",
    historySummary: "1 mm²/s ga teng bo'lib, motor moylarini tasniflashning sanoat standarti bo'lgan.",
    measurementSystem: "CGS tizimi (SI dan tashqari, quyi birlik)",
    siEquivalent: "1 sSt = 1 mm²/s = 0,000001 m²/s",
    commonUses: "Motor moyi tasnifi, yoqilg'i xususiyatlari",
  },
  {
    locale: "uz",
    sourceSlug: "metrekup-saniye",
    slug: "kub-metr-soniyaga",
    category: "debi_hacimsel",
    categoryName: "Hajmiy sarf",
    unit: "m³/s",
    name: "Kub Metr/Soniya",
    symbol: "m³/s",
    shortDescription: "Kub metr/soniya hajmiy sarfning SI asosiy birligi.",
    historySummary: "Katta oqim miqdorlarini, masalan daryolar yoki sanoat qurilmalarini tavsiflashda ishlatiladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, asosiy birlik)",
    siEquivalent: "Hajmiy sarfning asosiy SI birligi",
    commonUses: "Suv xo'jaligi, quvur texnikasi",
  },
  {
    locale: "uz",
    sourceSlug: "fitkup-dakika",
    slug: "kub-fut-daqiqaga",
    category: "debi_hacimsel",
    categoryName: "Hajmiy sarf",
    unit: "cfm",
    name: "Kub Fut/Daqiqa (CFM)",
    symbol: "cfm",
    shortDescription: "CFM AQSHda konditsioner va shamollatish tizimlarining havo o'tkazish miqdorini ko'rsatishda ishlatiladi.",
    historySummary: "Amerika ventilyator va klimat texnikasi spetsifikatsiyalarida standart hisoblanadi.",
    measurementSystem: "Angliya-Amerika o'lchov tizimi (SI dan tashqari)",
    siEquivalent: "1 CFM ≈ 0,000472 m³/s",
    commonUses: "AQSH shamollatish va klimat texnikasi",
  },
  {
    locale: "uz",
    sourceSlug: "galon-dakika",
    slug: "gallon-daqiqaga",
    category: "debi_hacimsel",
    categoryName: "Hajmiy sarf",
    unit: "gpm",
    name: "Gallon/Daqiqa (GPM)",
    symbol: "gpm",
    shortDescription: "GPM AQSHda nasos va suv quvurlarining sarfini ko'rsatishda ishlatiladi.",
    historySummary: "Amerika nasos, sug'orish va santexnika texnikasi spetsifikatsiyalarida standart.",
    measurementSystem: "Angliya-Amerika o'lchov tizimi (SI dan tashqari)",
    siEquivalent: "1 GPM ≈ 0,0000631 m³/s",
    commonUses: "AQSH nasos, sug'orish va santexnika texnikasi",
  },
  {
    locale: "uz",
    sourceSlug: "kilogram-saniye",
    slug: "kilogram-soniyaga",
    category: "debi_kutlesel",
    categoryName: "Massaviy sarf",
    unit: "kg/s",
    name: "Kilogram/Soniya",
    symbol: "kg/s",
    shortDescription: "Kilogram/soniya massaviy sarfning SI asosiy birligi.",
    historySummary: "Jarayonlardagi massa oqimini tavsiflashda kimyoviy texnologiyada ishlatiladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, asosiy birlik)",
    siEquivalent: "Massaviy sarfning asosiy SI birligi",
    commonUses: "Kimyoviy texnologiya, sanoat jarayoni hisoblari",
  },
  {
    locale: "uz",
    sourceSlug: "kilogram-saat",
    slug: "kilogram-soatiga",
    category: "debi_kutlesel",
    categoryName: "Massaviy sarf",
    unit: "kg/h",
    name: "Kilogram/Soat",
    symbol: "kg/h",
    shortDescription: "Kilogram/soat sanoat qo'llanmalari uchun amaliy massaviy sarf birligi.",
    historySummary: "Soatlik ishlab chiqarish tezliklari muhim bo'lgan ishlab chiqarish jarayonlarida ko'p ishlatiladi.",
    measurementSystem: "Metrik tizim (SI hosila amaliy birligi)",
    siEquivalent: "1 kg/soat = 0,0002778 kg/s",
    commonUses: "Ishlab chiqarish jarayonlari va sanoat ko'rsatkichlari",
  },
  {
    locale: "uz",
    sourceSlug: "kilojoule",
    slug: "kilojoul",
    category: "enerji",
    categoryName: "Energiya",
    unit: "kJ",
    name: "Kilojoul",
    symbol: "kJ",
    shortDescription: "Kilojoul 1000 joulga teng bo'lib, oziq-ovqat energiya qiymatini ko'rsatishda keng ishlatiladi.",
    historySummary: "Ko'p mamlakatlarda oziq-ovqat yorliqlarida kaloriya o'rniga rasmiy birlik hisoblanadi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, ko'paytma)",
    siEquivalent: "1 kJ = 1000 J",
    commonUses: "Oziq-ovqat yorliqlari, energiya hisoblari",
  },
  {
    locale: "uz",
    sourceSlug: "watt-saat",
    slug: "vatt-soat",
    category: "enerji",
    categoryName: "Energiya",
    unit: "Wh",
    name: "Vatt-Soat",
    symbol: "Wh",
    shortDescription: "Vatt-soat amaliy energiya birligi bo'lib, bir vatt quvvatda bir soat davomida sarflangan energiyani bildiradi.",
    historySummary: "Elektr hisob-kitoblarida ishlatiladigan kattaroq kilovat-soat birligining asosini tashkil qiladi.",
    measurementSystem: "SI dan tashqari, keng tarqalgan savdo birligi",
    siEquivalent: "1 Vt·soat = 3600 J",
    commonUses: "Kichik batareya sig'imlari, mobil elektronika",
  },
  {
    locale: "uz",
    sourceSlug: "kilovatsaat",
    slug: "kilovatt-soat",
    category: "enerji",
    categoryName: "Energiya",
    unit: "kWh",
    name: "Kilovatt-Soat",
    symbol: "kWh",
    shortDescription: "Kilovatt-soat elektr energiyasi hisoblarida keng qo'llaniladigan amaliy energiya birligi.",
    historySummary: "Dunyo miqyosida elektr energiyasi to'lovlarini hisoblash uchun standart birlik hisoblanadi.",
    measurementSystem: "SI dan tashqari, keng tarqalgan savdo birligi",
    siEquivalent: "1 kVt·soat = 3 600 000 J",
    commonUses: "Elektr energiyasi hisob-kitoblari va to'lovlar",
  },
  {
    locale: "uz",
    sourceSlug: "kalori",
    slug: "kaloriya",
    category: "enerji",
    categoryName: "Energiya",
    unit: "cal",
    name: "Kaloriya",
    symbol: "cal",
    shortDescription: "Kaloriya dastlab issiqlik miqdorini ko'rsatish uchun ishlatilgan an'anaviy energiya birligi.",
    historySummary: "Bugungacha ko'p mamlakatlarda ovqatlanish fanida keng qo'llaniladi.",
    measurementSystem: "SI dan tashqari, keng tarqalgan birlik",
    siEquivalent: "1 kaloriya ≈ 4,184 J",
    commonUses: "Ovqatlanish fani, oziq-ovqat energiya qiymati",
  },
  {
    locale: "uz",
    sourceSlug: "kilokalori",
    slug: "kilokaloriya",
    category: "enerji",
    categoryName: "Energiya",
    unit: "kcal",
    name: "Kilokaloriya",
    symbol: "kcal",
    shortDescription: "Kilokaloriya 1000 kaloriyaga teng bo'lib, oziq-ovqat qadoqlarida ishlatiladigan energiya birligi.",
    historySummary: "Ko'pincha oddiygina kaloriya deb ataladi va ovqatlanish yorliqlarida standart hisoblanadi.",
    measurementSystem: "SI dan tashqari, keng tarqalgan birlik",
    siEquivalent: "1 kkal = 4184 J",
    commonUses: "Ovqatlanish yorliqlari va reja tuzish",
  },
  {
    locale: "uz",
    sourceSlug: "btu",
    slug: "btu",
    category: "enerji",
    categoryName: "Energiya",
    unit: "Btu",
    name: "BTU",
    symbol: "Btu",
    shortDescription: "BTU (Britaniya issiqlik birligi) AQSHda isitish va sovutish qurilmalarida ishlatiladigan an'anaviy energiya birligi.",
    historySummary: "AQSH klimat texnikasi va isitish tizimlari spetsifikatsiyalarida standart hisoblanadi.",
    measurementSystem: "Angliya-Amerika o'lchov tizimi (SI dan tashqari)",
    siEquivalent: "1 Btu ≈ 1055,06 J",
    commonUses: "AQSH klimat va isitish tizimlari spetsifikatsiyalari",
  },
  {
    locale: "uz",
    sourceSlug: "watt",
    slug: "vatt",
    category: "guc",
    categoryName: "Quvvat",
    unit: "W",
    name: "Vatt",
    symbol: "W",
    shortDescription: "Vatt quvvatning SI birligi bo'lib, James Vatt nomi bilan atalgan.",
    historySummary: "Elektr qurilmalari va motorlarning quvvatini ko'rsatishning xalqaro standarti.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, hosila birlik)",
    siEquivalent: "Quvvatning asosiy SI birligi",
    commonUses: "Elektr qurilmalari, motorlar",
  },
  {
    locale: "uz",
    sourceSlug: "kilowatt",
    slug: "kilovatt",
    category: "guc",
    categoryName: "Quvvat",
    unit: "kW",
    name: "Kilovatt",
    symbol: "kW",
    shortDescription: "Kilovatt 1000 vattga teng, motor va uskunalar quvvatini ko'rsatishda keng qo'llaniladi.",
    historySummary: "Sanoat va uy-ro'zg'or elektr uskunalari spetsifikatsiyalarida standart hisoblanadi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, ko'paytma)",
    siEquivalent: "1 kVt = 1000 Vt",
    commonUses: "Motor va elektr uskunalar spetsifikatsiyalari",
  },
  {
    locale: "uz",
    sourceSlug: "megawatt",
    slug: "megavatt",
    category: "guc",
    categoryName: "Quvvat",
    unit: "MW",
    name: "Megavatt",
    symbol: "MW",
    shortDescription: "Megavatt bir million vattga teng, elektr stansiyalari va yirik sanoat quvvatini ko'rsatishda ishlatiladi.",
    historySummary: "Elektr ishlab chiqarish stansiyalari va yirik sanoat qurilmalari uchun standart quvvat birligi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, ko'paytma)",
    siEquivalent: "1 MVt = 1 000 000 Vt",
    commonUses: "Elektr stansiyalari, yirik sanoat quvvati",
  },
  {
    locale: "uz",
    sourceSlug: "beygirgucu",
    slug: "ot-kuchi",
    category: "guc",
    categoryName: "Quvvat",
    unit: "hp",
    name: "Ot Kuchi",
    symbol: "ot kuchi",
    shortDescription: "Ot kuchi Yevropa avtomobil texnikasida keng qo'llaniladigan an'anaviy quvvat birligi.",
    historySummary: "Dastlab bug' mashinalari quvvatini otlar bilan taqqoslash uchun ishlab chiqilgan.",
    measurementSystem: "Metrik tizim (SI dan tashqari)",
    siEquivalent: "1 ot kuchi ≈ 735,5 Vt",
    commonUses: "Yevropa avtomobil va motor spetsifikatsiyalari",
  },
  {
    locale: "uz",
    sourceSlug: "beygirgucu-mekanik",
    slug: "mexanik-ot-kuchi",
    category: "guc",
    categoryName: "Quvvat",
    unit: "HP",
    name: "Mexanik Ot Kuchi",
    symbol: "HP",
    shortDescription: "Mexanik ot kuchi metrik ot kuchidan biroz farq qiladigan britaniya-amerika quvvat birligi.",
    historySummary: "Dastlab Jeyms Vatt tomonidan aniqlangan, hozir ham AQSH va Buyuk Britaniya avtomobil texnikasida ishlatiladi.",
    measurementSystem: "Angliya-Amerika o'lchov tizimi (SI dan tashqari)",
    siEquivalent: "1 HP (mexanik) = 745,7 Vt",
    commonUses: "AQSH va Buyuk Britaniya avtomobil spetsifikatsiyalari",
  },
  {
    locale: "uz",
    sourceSlug: "fahrenhayt",
    slug: "farengeyt",
    category: "sicaklik",
    categoryName: "Harorat",
    unit: "F",
    name: "Farengeyt",
    symbol: "°F",
    shortDescription: "Farengeyt AQSHda kundalik harorat o'lchovida keng qo'llaniladigan harorat shkalasi.",
    historySummary: "Daniyel Gabriel Farengeyt tomonidan 18-asrda ishlab chiqilgan, hozir asosan AQSHda qo'llaniladi.",
    measurementSystem: "SI dan tashqari, keng tarqalgan birlik",
    siEquivalent: "K = (°F − 32) × 5/9 + 273,15",
    commonUses: "AQSHda kundalik harorat o'lchovlari",
  },
  {
    locale: "uz",
    sourceSlug: "watt-metre-kelvin",
    slug: "vatt-metr-kelvinga",
    category: "isil_iletkenlik",
    categoryName: "Issiqlik o'tkazuvchanligi",
    unit: "W/m·K",
    name: "Vatt/Metr-Kelvin",
    symbol: "W/(m·K)",
    shortDescription: "Vatt/metr-Kelvin issiqlik o'tkazuvchanligining SI birligi.",
    historySummary: "Qurilish fizikasi va materialshunoslikda materiallarning issiqlik izolyatsiya xususiyatlarini baholashda ishlatiladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, hosila birlik)",
    siEquivalent: "Issiqlik o'tkazuvchanligining asosiy SI birligi",
    commonUses: "Qurilish fizikasi, izolyatsiya materiallari",
  },
  {
    locale: "uz",
    sourceSlug: "btu-saat-fit-f",
    slug: "btu-soat-fut-f",
    category: "isil_iletkenlik",
    categoryName: "Issiqlik o'tkazuvchanligi",
    unit: "Btu/h·ft·°F",
    name: "BTU/Soat-Fut-°F",
    symbol: "Btu/(h·ft·°F)",
    shortDescription: "BTU/soat-fut-°F AQSHda ishlatiladigan issiqlik o'tkazuvchanligi birligi.",
    historySummary: "AQSH qurilish normalarida metrik birlik o'rniga qo'llaniladi.",
    measurementSystem: "Angliya-Amerika o'lchov tizimi (SI dan tashqari)",
    siEquivalent: "1 Btu/(soat·fut·°F) ≈ 1,731 W/(m·K)",
    commonUses: "AQSH qurilish normalari va izolyatsiya spetsifikatsiyalari",
  },
  {
    locale: "uz",
    sourceSlug: "watt-metrekare",
    slug: "vatt-kvadrat-metrga",
    category: "isi_akisi",
    categoryName: "Issiqlik oqimi zichligi",
    unit: "W/m²",
    name: "Vatt/Kvadrat Metr",
    symbol: "W/m²",
    shortDescription: "Vatt/kvadrat metr issiqlik oqimi zichligining SI birligi.",
    historySummary: "Qurilish fizikasi va quyosh energetikasida yuzalardagi energiya oqimini tavsiflashda ishlatiladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, hosila birlik)",
    siEquivalent: "Issiqlik oqimi zichligining asosiy SI birligi",
    commonUses: "Qurilish fizikasi, quyosh energetikasi",
  },
  {
    locale: "uz",
    sourceSlug: "kilowatt-metrekare",
    slug: "kilovatt-kvadrat-metrga",
    category: "isi_akisi",
    categoryName: "Issiqlik oqimi zichligi",
    unit: "kW/m²",
    name: "Kilovatt/Kvadrat Metr",
    symbol: "kW/m²",
    shortDescription: "Kilovatt/kvadrat metr kattaroq issiqlik oqimi zichligi qiymatlari uchun ishlatiladigan birlik.",
    historySummary: "Yuza birligiga yuqori issiqlik quvvati to'g'ri keladigan sanoat qo'llanmalarida ishlatiladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, ko'paytma)",
    siEquivalent: "1 kVt/m² = 1000 Vt/m²",
    commonUses: "Sanoat issiqlik texnikasi, quyosh qurilmalari",
  },
  {
    locale: "uz",
    sourceSlug: "joule-kilogram-kelvin",
    slug: "joul-kilogram-kelvinga",
    category: "ozgul_isi",
    categoryName: "Solishtirma issiqlik sig'imi",
    unit: "J/kg·K",
    name: "Joul/Kilogram-Kelvin",
    symbol: "J/(kg·K)",
    shortDescription: "Joul/kilogram-Kelvin materiallarning solishtirma issiqlik sig'imining SI birligi.",
    historySummary: "Bir kilogramm moddani bir Kelvinga isitish uchun kerakli energiyani bildiradi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, hosila birlik)",
    siEquivalent: "Solishtirma issiqlik sig'imining asosiy SI birligi",
    commonUses: "Materialshunoslik va termodinamika hisoblari",
  },
  {
    locale: "uz",
    sourceSlug: "kalori-gram-kelvin",
    slug: "kaloriya-gram-kelvinga",
    category: "ozgul_isi",
    categoryName: "Solishtirma issiqlik sig'imi",
    unit: "cal/g·K",
    name: "Kaloriya/Gram-Kelvin",
    symbol: "cal/(g·K)",
    shortDescription: "Kaloriya/gram-Kelvin solishtirma issiqlik sig'imining an'anaviy birligi.",
    historySummary: "SI tizimiga to'liq o'tishdan oldin kimyo va fizikada ishlatilgan.",
    measurementSystem: "SI dan tashqari, an'anaviy birlik",
    siEquivalent: "1 kal/(g·K) = 4184 J/(kg·K)",
    commonUses: "Kimyo va eski termodinamika hisoblari",
  },
  {
    locale: "uz",
    sourceSlug: "metrekup-saat",
    slug: "kub-metr-soatiga",
    category: "debi",
    categoryName: "Sarf",
    unit: "m³/h",
    name: "Kub Metr/Soat",
    symbol: "m³/h",
    shortDescription: "Kub metr/soat suv va gaz quvurlari sarfini ko'rsatishda keng qo'llaniladigan birlik.",
    historySummary: "Uy-ro'zg'or texnikasi va suv xo'jaligida sarf tezligini ko'rsatishda ishlatiladi.",
    measurementSystem: "Metrik tizim (SI hosila amaliy birligi)",
    siEquivalent: "1 m³/soat ≈ 0,000278 m³/s",
    commonUses: "Uy-ro'zg'or texnikasi, suv xo'jaligi, gaz quvurlari",
  },
  {
    locale: "uz",
    sourceSlug: "litre-dakika",
    slug: "litr-daqiqaga",
    category: "debi",
    categoryName: "Sarf",
    unit: "L/min",
    name: "Litr/Daqiqa",
    symbol: "L/min",
    shortDescription: "Litr/daqiqa kran yoki nasoslardagi kichikroq sarf miqdorlari uchun amaliy birlik.",
    historySummary: "Kundalik hayotda va uy-ro'zg'or texnikasida qulay sarf qiymatlarini ko'rsatish uchun keng tarqalgan.",
    measurementSystem: "Metrik tizim (SI hosila amaliy birligi)",
    siEquivalent: "1 L/daqiqa ≈ 0,0000167 m³/s",
    commonUses: "Uy-ro'zg'or texnikasi, nasoslar",
  },
  {
    locale: "uz",
    sourceSlug: "kilovolt",
    slug: "kilovolt",
    category: "elektrik",
    categoryName: "Elektr",
    unit: "kV",
    name: "Kilovolt",
    symbol: "kV",
    shortDescription: "Kilovolt 1000 voltga teng, yuqori kuchlanish tizimlarida ishlatiladigan birlik.",
    historySummary: "Elektr uzatish tarmoqlarida yuqori kuchlanishlarni ko'rsatish uchun ishlatiladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, ko'paytma)",
    siEquivalent: "1 kV = 1000 V",
    commonUses: "Elektr uzatish tarmoqlari, yuqori kuchlanish uskunalari",
  },
  {
    locale: "uz",
    sourceSlug: "miliamper",
    slug: "milliamper",
    category: "elektrik",
    categoryName: "Elektr",
    unit: "mA",
    name: "Milliamper",
    symbol: "mA",
    shortDescription: "Milliamper amperning mingdan bir qismiga teng, kichik tok kuchlarini o'lchashda ishlatiladi.",
    historySummary: "Elektronika, sensorika va aniqlik asboblari rivojlanishi bilan muhim ahamiyat kasb etdi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, quyi birlik)",
    siEquivalent: "1 mA = 0,001 A",
    commonUses: "Elektronika, sensorlar, kichik tok o'lchovlari",
  },
  {
    locale: "uz",
    sourceSlug: "milivolt",
    slug: "millivolt",
    category: "elektrik",
    categoryName: "Elektr",
    unit: "mV",
    name: "Millivolt",
    symbol: "mV",
    shortDescription: "Millivolt voltning mingdan bir qismiga teng, kichik kuchlanish qiymatlari uchun ishlatiladi.",
    historySummary: "Elektronika va aniqlik asboblari rivojlanishi bilan muhim ahamiyat kasb etdi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, quyi birlik)",
    siEquivalent: "1 mV = 0,001 V",
    commonUses: "Elektronika, sensorlar, past kuchlanish o'lchovlari",
  },
  {
    locale: "uz",
    sourceSlug: "kiloamper",
    slug: "kiloamper",
    category: "elektrik",
    categoryName: "Elektr",
    unit: "kA",
    name: "Kiloamper",
    symbol: "kA",
    shortDescription: "Kiloamper 1000 amperga teng, qisqa tutashuv va chaqmoq oqimlari kabi katta toklarni o'lchashda ishlatiladi.",
    historySummary: "Energiya taqsimoti tizimlari va yirik sanoat elektr qurilmalarida amaliy standart bo'lgan.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, ko'paytma)",
    siEquivalent: "1 kA = 1000 A",
    commonUses: "Qisqa tutashuv hisoblari, energiya taqsimoti uskunalari",
  },
  {
    locale: "uz",
    sourceSlug: "ohm",
    slug: "om",
    category: "elektrik_direnc",
    categoryName: "Qarshilik",
    unit: "Ω",
    name: "Om",
    symbol: "Ω",
    shortDescription: "Om elektr qarshiligining SI birligi bo'lib, Georg Simon Om nomi bilan atalgan.",
    historySummary: "Dunyo bo'ylab elektrotexnikada qarshilik ko'rsatishning asosiy birligi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, hosila birlik)",
    siEquivalent: "Elektr qarshiligining asosiy SI birligi",
    commonUses: "Elektrotexnika, sxema loyihalash",
  },
  {
    locale: "uz",
    sourceSlug: "kiloohm",
    slug: "kiloom",
    category: "elektrik_direnc",
    categoryName: "Qarshilik",
    unit: "kΩ",
    name: "Kiloom",
    symbol: "kΩ",
    shortDescription: "Kiloom 1000 omga teng, elektronikada o'rta qarshilik qiymatlari uchun ishlatiladi.",
    historySummary: "Odatiy sxemalardagi rezistorlar uchun keng tarqalgan birlik hisoblanadi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, ko'paytma)",
    siEquivalent: "1 kΩ = 1000 Ω",
    commonUses: "Elektronika va sxema loyihalash",
  },
  {
    locale: "uz",
    sourceSlug: "megaohm",
    slug: "megaom",
    category: "elektrik_direnc",
    categoryName: "Qarshilik",
    unit: "MΩ",
    name: "Megaom",
    symbol: "MΩ",
    shortDescription: "Megaom bir million omga teng, juda yuqori qarshilik qiymatlari uchun ishlatiladi.",
    historySummary: "Izolyatsiya qarshiligini o'lchash va yuqori aniqlikdagi sxemalarda ishlatiladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, ko'paytma)",
    siEquivalent: "1 MΩ = 1 000 000 Ω",
    commonUses: "Izolyatsiya o'lchovlari, yuqori aniqlik elektronikasi",
  },
  {
    locale: "uz",
    sourceSlug: "farad",
    slug: "farad",
    category: "kapasitans",
    categoryName: "Sig'im",
    unit: "F",
    name: "Farad",
    symbol: "F",
    shortDescription: "Farad elektr sig'imining SI birligi bo'lib, Maykl Faradey nomi bilan atalgan.",
    historySummary: "Kondensator sig'imini ifodalashning elektrotexnikadagi asosiy birligi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, hosila birlik)",
    siEquivalent: "Sig'imning asosiy SI birligi",
    commonUses: "Kondensator loyihalash, sxema texnikasi",
  },
  {
    locale: "uz",
    sourceSlug: "milifarad",
    slug: "millifarad",
    category: "kapasitans",
    categoryName: "Sig'im",
    unit: "mF",
    name: "Millifarad",
    symbol: "mF",
    shortDescription: "Millifarad faradning mingdan bir qismiga teng, katta energiya kondensatorlarida ishlatiladi.",
    historySummary: "Quvvat elektronikasi va katta energiya saqlash kondensatorlarida qo'llaniladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, quyi birlik)",
    siEquivalent: "1 mF = 0,001 F",
    commonUses: "Quvvat elektronikasi, energiya saqlash",
  },
  {
    locale: "uz",
    sourceSlug: "mikrofarad",
    slug: "mikrofarad",
    category: "kapasitans",
    categoryName: "Sig'im",
    unit: "µF",
    name: "Mikrofarad",
    symbol: "µF",
    shortDescription: "Mikrofarad faradning milliondan bir qismiga teng, kundalik elektron kondensatorlarda eng ko'p ishlatiladigan birlik.",
    historySummary: "Elektron qurilmalardagi ko'pchilik savdo kondensatorlari mikrofaradda ko'rsatiladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, quyi birlik)",
    siEquivalent: "1 µF = 0,000001 F",
    commonUses: "Elektron qurilmalar, sxema loyihalash",
  },
  {
    locale: "uz",
    sourceSlug: "nanofarad",
    slug: "nanofarad",
    category: "kapasitans",
    categoryName: "Sig'im",
    unit: "nF",
    name: "Nanofarad",
    symbol: "nF",
    shortDescription: "Nanofarad faradning milliarddan bir qismiga teng, yuqori chastotali sxemalarda kichik kondensatorlar uchun ishlatiladi.",
    historySummary: "Filtr va yuqori chastotali aloqa sxemalarini loyihalashda muhim.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, quyi birlik)",
    siEquivalent: "1 nF = 0,000000001 F",
    commonUses: "Filtr sxemalari, yuqori chastotali aloqa",
  },
  {
    locale: "uz",
    sourceSlug: "pikofarad",
    slug: "pikofarad",
    category: "kapasitans",
    categoryName: "Sig'im",
    unit: "pF",
    name: "Pikofarad",
    symbol: "pF",
    shortDescription: "Pikofarad faradning trilliondan bir qismiga teng, aniqlik sxemalaridagi eng kichik kondensator qiymatlari uchun.",
    historySummary: "Radio va simsiz aloqa kabi aniq yuqori chastotali sxemalarni loyihalashda muhim.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, quyi birlik)",
    siEquivalent: "1 pF = 0,000000000001 F",
    commonUses: "Radio sxemalari, simsiz aloqa",
  },
  {
    locale: "uz",
    sourceSlug: "henry",
    slug: "genri",
    category: "enduktans",
    categoryName: "Induktivlik",
    unit: "H",
    name: "Genri",
    symbol: "H",
    shortDescription: "Genri induktivlikning SI birligi bo'lib, Jozef Genri nomi bilan atalgan.",
    historySummary: "G'altak induktivligini ifodalashning elektrotexnikadagi asosiy birligi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, hosila birlik)",
    siEquivalent: "Induktivlikning asosiy SI birligi",
    commonUses: "G'altak loyihalash, sxema texnikasi",
  },
  {
    locale: "uz",
    sourceSlug: "milihenry",
    slug: "milligenri",
    category: "enduktans",
    categoryName: "Induktivlik",
    unit: "mH",
    name: "Milligenri",
    symbol: "mH",
    shortDescription: "Milligenri genrining mingdan bir qismiga teng, o'rta induktivlik qiymatlari uchun ishlatiladi.",
    historySummary: "Quvvat elektronikasi va tarmoq drossellarida keng qo'llaniladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, quyi birlik)",
    siEquivalent: "1 mH = 0,001 H",
    commonUses: "Quvvat elektronikasi, tarmoq bloklari",
  },
  {
    locale: "uz",
    sourceSlug: "mikrohenry",
    slug: "mikrogenri",
    category: "enduktans",
    categoryName: "Induktivlik",
    unit: "µH",
    name: "Mikrogenri",
    symbol: "µH",
    shortDescription: "Mikrogenri genrining milliondan bir qismiga teng, yuqori chastotali sxemalardagi kichik g'altaklar uchun.",
    historySummary: "Radio va yuqori chastotali sxemalarni loyihalashda muhim ahamiyatga ega.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, quyi birlik)",
    siEquivalent: "1 µH = 0,000001 H",
    commonUses: "Radio sxemalari, yuqori chastotali texnika",
  },
  {
    locale: "uz",
    sourceSlug: "coulomb",
    slug: "kulon",
    category: "elektrik_yuk",
    categoryName: "Elektr zaryadi",
    unit: "C",
    name: "Kulon",
    symbol: "C",
    shortDescription: "Kulon elektr zaryadining SI birligi bo'lib, Sharl Ogusten de Kulon nomi bilan atalgan.",
    historySummary: "Elektrotexnika va fizikada zaryad ko'rsatishning asosiy birligi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, hosila birlik)",
    siEquivalent: "Elektr zaryadining asosiy SI birligi",
    commonUses: "Elektrotexnika va fizik zaryad hisoblari",
  },
  {
    locale: "uz",
    sourceSlug: "milicoulomb",
    slug: "millikulon",
    category: "elektrik_yuk",
    categoryName: "Elektr zaryadi",
    unit: "mC",
    name: "Millikulon",
    symbol: "mC",
    shortDescription: "Millikulon kulonning mingdan bir qismiga teng, o'rta zaryad qiymatlari uchun ishlatiladi.",
    historySummary: "Batareya texnikasi va kondensator zaryad hisoblarida qo'llaniladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, quyi birlik)",
    siEquivalent: "1 mC = 0,001 C",
    commonUses: "Batareya texnikasi, kondensator hisoblari",
  },
  {
    locale: "uz",
    sourceSlug: "mikrocoulomb",
    slug: "mikrokulon",
    category: "elektrik_yuk",
    categoryName: "Elektr zaryadi",
    unit: "µC",
    name: "Mikrokulon",
    symbol: "µC",
    shortDescription: "Mikrokulon kulonning milliondan bir qismiga teng, elektronikadagi kichikroq zaryad qiymatlari uchun ishlatiladi.",
    historySummary: "Aniqlik elektronikasi va elektrostatik hisoblarda keng qo'llaniladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, quyi birlik)",
    siEquivalent: "1 µC = 0,000001 C",
    commonUses: "Aniqlik elektronikasi, elektrostatik hisoblar",
  },
  {
    locale: "uz",
    sourceSlug: "nanocoulomb",
    slug: "nanokulon",
    category: "elektrik_yuk",
    categoryName: "Elektr zaryadi",
    unit: "nC",
    name: "Nanokulon",
    symbol: "nC",
    shortDescription: "Nanokulon kulonning milliarddan bir qismiga teng, juda kichik zaryad qiymatlari uchun ishlatiladi.",
    historySummary: "Aniq fizika tajribalari va kichik elektrostatik zaryadlarni tahlil qilishda qo'llaniladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, quyi birlik)",
    siEquivalent: "1 nC = 0,000000001 C",
    commonUses: "Aniqlik fizikasi, elektrostatik zaryad tahlili",
  },
  {
    locale: "uz",
    sourceSlug: "amper-metre",
    slug: "amper-metrga",
    category: "manyetik_alan",
    categoryName: "Magnit maydoni",
    unit: "A/m",
    name: "Amper/Metr",
    symbol: "A/m",
    shortDescription: "Amper/metr magnit maydoni kuchining SI birligi.",
    historySummary: "Elektrotexnikada magnit maydonlarini aniq tavsiflashda ishlatiladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, hosila birlik)",
    siEquivalent: "Magnit maydoni kuchining asosiy SI birligi",
    commonUses: "Elektrotexnika, magnit maydoni hisoblari",
  },
  {
    locale: "uz",
    sourceSlug: "oersted",
    slug: "ersted",
    category: "manyetik_alan",
    categoryName: "Magnit maydoni",
    unit: "Oe",
    name: "Ersted",
    symbol: "Oe",
    shortDescription: "Ersted CGS tizimidan qolgan an'anaviy magnit maydoni kuchi birligi.",
    historySummary: "Hans Kristian Yorsted nomi bilan atalgan, eski magnetizm hujjatlarida va AQSHda ishlatiladi.",
    measurementSystem: "CGS tizimi (SI dan tashqari)",
    siEquivalent: "1 Oe ≈ 79,58 A/m",
    commonUses: "Eski magnetizm hujjatlari va AQSH adabiyoti",
  },
  {
    locale: "uz",
    sourceSlug: "weber",
    slug: "veber",
    category: "manyetik_aki",
    categoryName: "Magnit oqimi",
    unit: "Wb",
    name: "Veber",
    symbol: "Wb",
    shortDescription: "Veber magnit oqimining SI birligi bo'lib, Vilgelm Eduard Veber nomi bilan atalgan.",
    historySummary: "Elektrotexnikada magnit oqimini ifodalashning asosiy birligi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, hosila birlik)",
    siEquivalent: "Magnit oqimining asosiy SI birligi",
    commonUses: "Elektrotexnika, transformator loyihalash",
  },
  {
    locale: "uz",
    sourceSlug: "miliweber",
    slug: "milliveber",
    category: "manyetik_aki",
    categoryName: "Magnit oqimi",
    unit: "mWb",
    name: "Milliveber",
    symbol: "mWb",
    shortDescription: "Milliveber vebering mingdan bir qismiga teng, kichikroq magnit oqimi qiymatlari uchun ishlatiladi.",
    historySummary: "Elektromotor va transformator hisoblarida amaliy qiymatlar berish uchun ishlatiladi.",
    measurementSystem: "Xalqaro Birliklar Tizimi (SI, quyi birlik)",
    siEquivalent: "1 mWb = 0,001 Wb",
    commonUses: "Elektromotor va transformator hisoblari",
  },
  {
    locale: "uz",
    sourceSlug: "bit",
    slug: "bit",
    category: "veri",
    categoryName: "Ma'lumot hajmi",
    unit: "bit",
    name: "Bit",
    symbol: "bit",
    shortDescription: "Bit raqamli ma'lumot qayta ishlashning eng kichik birligi bo'lib, 0 yoki 1 qiymatini oladi.",
    historySummary: "Zamonaviy kompyuter texnikasi va ma'lumot uzatishning butun asosini tashkil qiladi.",
    measurementSystem: "Raqamli ma'lumot birligi (asosiy birlik)",
    siEquivalent: "Ma'lumot uzatish tezligining asosiy birligi",
    commonUses: "Ma'lumot uzatish tezligi, raqamli axborot qayta ishlash",
  },
  {
    locale: "uz",
    sourceSlug: "kilobayt",
    slug: "kilobayt",
    category: "veri",
    categoryName: "Ma'lumot hajmi",
    unit: "KB",
    name: "Kilobayt",
    symbol: "KB",
    shortDescription: "Kilobayt taxminan 1000 baytga teng, kichik fayllar va dastlabki xotira qurilmalari uchun ishlatilgan.",
    historySummary: "Kompyuter texnikasining dastlabki davrlarida matn fayllari va dasturlar uchun keng qo'llanilgan.",
    measurementSystem: "Raqamli ma'lumot birligi (ko'paytma)",
    siEquivalent: "1 KB ≈ 1000 bayt",
    commonUses: "Kichik fayllar, dastlabki kompyuter texnikasi",
  },
  {
    locale: "uz",
    sourceSlug: "megabayt",
    slug: "megabayt",
    category: "veri",
    categoryName: "Ma'lumot hajmi",
    unit: "MB",
    name: "Megabayt",
    symbol: "MB",
    shortDescription: "Megabayt taxminan bir million baytga teng, o'rtacha fayllar, masalan rasm yoki hujjatlar uchun ishlatiladi.",
    historySummary: "Multimedia fayllari va kattaroq dasturlarning paydo bo'lishi bilan keng tarqalgan xotira birligiga aylandi.",
    measurementSystem: "Raqamli ma'lumot birligi (ko'paytma)",
    siEquivalent: "1 MB ≈ 1 000 000 bayt",
    commonUses: "Rasmlar, hujjatlar, o'rtacha dasturiy fayllar",
  },
  {
    locale: "uz",
    sourceSlug: "gigabayt",
    slug: "gigabayt",
    category: "veri",
    categoryName: "Ma'lumot hajmi",
    unit: "GB",
    name: "Gigabayt",
    symbol: "GB",
    shortDescription: "Gigabayt taxminan bir milliard baytga teng, zamonaviy xotira qurilmalari va ma'lumot hajmini ko'rsatishda ishlatiladi.",
    historySummary: "Bugungi kunda operativ xotira, qattiq disk va mobil ma'lumot hajmini ko'rsatishning standart birligi.",
    measurementSystem: "Raqamli ma'lumot birligi (ko'paytma)",
    siEquivalent: "1 GB ≈ 1 000 000 000 bayt",
    commonUses: "Operativ xotira, qattiq disklar, mobil ma'lumot hajmi",
  },
  {
    locale: "uz",
    sourceSlug: "terabayt",
    slug: "terabayt",
    category: "veri",
    categoryName: "Ma'lumot hajmi",
    unit: "TB",
    name: "Terabayt",
    symbol: "TB",
    shortDescription: "Terabayt taxminan bir trillion baytga teng, katta xotira qurilmalari uchun ishlatiladigan birlik.",
    historySummary: "Video kontent va bulutli saqlashning o'sishi bilan katta ma'lumot hajmlari uchun standart birlikka aylandi.",
    measurementSystem: "Raqamli ma'lumot birligi (ko'paytma)",
    siEquivalent: "1 TB ≈ 1 000 000 000 000 bayt",
    commonUses: "Katta qattiq disklar, video kontent, bulutli saqlash",
  },
  {
    locale: "uz",
    sourceSlug: "petabayt",
    slug: "petabayt",
    category: "veri",
    categoryName: "Ma'lumot hajmi",
    unit: "PB",
    name: "Petabayt",
    symbol: "PB",
    shortDescription: "Petabayt taxminan 1000 terabaytga teng, ma'lumot markazlaridagi juda katta xotira sig'imlari uchun ishlatiladi.",
    historySummary: "Yirik ma'lumot markazlari va bulutli hisoblash xizmatlarining o'sishi bilan keng tarqaldi.",
    measurementSystem: "Raqamli ma'lumot birligi (ko'paytma)",
    siEquivalent: "1 PB ≈ 1000 TB",
    commonUses: "Yirik ma'lumot markazlari, bulutli hisoblash",
  },
  {
    locale: "uz",
    sourceSlug: "kibibayt",
    slug: "kibibayt",
    category: "veri",
    categoryName: "Ma'lumot hajmi",
    unit: "KiB",
    name: "Kibibayt",
    symbol: "KiB",
    shortDescription: "Kibibayt aynan 1024 baytga teng aniq binar birlik bo'lib, o'nlik kilobayt bilan chalkashishning oldini oladi.",
    historySummary: "IEC tomonidan 1000 va 1024 asoslari orasidagi noaniqlikni bartaraf etish uchun qabul qilingan.",
    measurementSystem: "Aniq binar ma'lumot birligi (IEC standarti)",
    siEquivalent: "1 KiB = 1024 bayt aniq",
    commonUses: "Operatsion tizim va xotira uchun aniq texnik hujjatlar",
  },
  {
    locale: "uz",
    sourceSlug: "mebibayt",
    slug: "mebibayt",
    category: "veri",
    categoryName: "Ma'lumot hajmi",
    unit: "MiB",
    name: "Mebibayt",
    symbol: "MiB",
    shortDescription: "Mebibayt aynan 1024 kibibaytga teng aniq binar birlik.",
    historySummary: "O'nlik va binar xotira ko'rsatkichlari orasidagi chalkashlikni oldini olish uchun aniq texnik hujjatlarda ishlatiladi.",
    measurementSystem: "Aniq binar ma'lumot birligi (IEC standarti)",
    siEquivalent: "1 MiB = 1024 KiB aniq",
    commonUses: "Operativ xotira sig'imining aniq hujjatlashtirilishi",
  },
  {
    locale: "uz",
    sourceSlug: "gibibayt",
    slug: "gibibayt",
    category: "veri",
    categoryName: "Ma'lumot hajmi",
    unit: "GiB",
    name: "Gibibayt",
    symbol: "GiB",
    shortDescription: "Gibibayt aynan 1024 mebibaytga teng aniq binar birlik.",
    historySummary: "Xotira sig'imining aniq IEC standarti bo'lib, savdo maqsadidagi o'nlik gigabaytdan farqlash uchun ishlatiladi.",
    measurementSystem: "Aniq binar ma'lumot birligi (IEC standarti)",
    siEquivalent: "1 GiB = 1024 MiB aniq",
    commonUses: "Xotira va saqlash sig'imining aniq hujjatlashtirilishi",
  },
  {
    locale: "uz",
    sourceSlug: "tebibayt",
    slug: "tebibayt",
    category: "veri",
    categoryName: "Ma'lumot hajmi",
    unit: "TiB",
    name: "Tebibayt",
    symbol: "TiB",
    shortDescription: "Tebibayt aynan 1024 gibibaytga teng aniq binar birlik.",
    historySummary: "Katta saqlash tizimlarining sig'imini aniq texnik tarzda belgilashda ishlatiladi.",
    measurementSystem: "Aniq binar ma'lumot birligi (IEC standarti)",
    siEquivalent: "1 TiB = 1024 GiB aniq",
    commonUses: "Katta saqlash tizimlari va aniq ma'lumot markazi hujjatlari",
  },
  {
    locale: "uz",
    sourceSlug: "22-ayar-altin",
    slug: "22-karat",
    category: "altin_ayar",
    categoryName: "Oltin karati",
    unit: "22K",
    name: "22 Karat Oltin",
    symbol: "22K",
    shortDescription: "22 karat 91,7% sof oltindan iborat qotishma bo'lib, tozalik va qattiqlik o'rtasida yaxshi muvozanat hisoblanadi.",
    historySummary: "Ko'p Osiyo va Yaqin Sharq mamlakatlarida an'anaviy zargarlik buyumlari uchun afzal ko'riladigan karat darajasi.",
    measurementSystem: "Karat tizimi (SI dan tashqari)",
    siEquivalent: "917/1000 sof oltin",
    commonUses: "Osiyo va Yaqin Sharqda an'anaviy zargarlik",
  },
  {
    locale: "uz",
    sourceSlug: "18-ayar-altin",
    slug: "18-karat",
    category: "altin_ayar",
    categoryName: "Oltin karati",
    unit: "18K",
    name: "18 Karat Oltin",
    symbol: "18K",
    shortDescription: "18 karat 75% sof oltindan iborat qotishma bo'lib, qattiqlik va qiymat o'rtasida yaxshi muvozanatni ta'minlaydi.",
    historySummary: "Chidamliligi va rang xilma-xilligi tufayli g'arb zargarlik sanoatida ayniqsa mashhur.",
    measurementSystem: "Karat tizimi (SI dan tashqari)",
    siEquivalent: "750/1000 sof oltin",
    commonUses: "G'arb zargarlik buyumlari va nikoh uzuklari",
  },
  {
    locale: "uz",
    sourceSlug: "14-ayar-altin",
    slug: "14-karat",
    category: "altin_ayar",
    categoryName: "Oltin karati",
    unit: "14K",
    name: "14 Karat Oltin",
    symbol: "14K",
    shortDescription: "14 karat 58,3% sof oltindan iborat qotishma bo'lib, yuqori karatlarga qaraganda ancha chidamli va arzon.",
    historySummary: "G'arb bozorlarida yuqori chidamliligi va nisbatan arzon narxi tufayli kundalik zargarlik buyumlarida keng tarqalgan.",
    measurementSystem: "Karat tizimi (SI dan tashqari)",
    siEquivalent: "583/1000 sof oltin",
    commonUses: "G'arb bozorlarida chidamli kundalik zargarlik",
  },
];

export function findUzbekUnitPageBySourceSlug(sourceSlug: string) {
  return uzbekUnitPages.find((page) => page.sourceSlug === sourceSlug);
}

export function findUzbekUnitPage(category: string, unit: string) {
  return uzbekUnitPages.find(
    (page) => page.category === category && page.unit === unit
  );
}
