// Svenska enhetssidor -- integrerade i det nya i18n-systemet.
// Fristaende, nytt fil (andrar inga befintliga tr/en/de/ar/uz/bn/fr/es/pt/it/nl-filer).
// Innehallet ar oversatt direkt fran den turkiska kallan
// (app/converter/unitPages.ts, unitDescriptions-tabellen), inte fran ett
// mellansprak, for att bevara samma djup och faktainnehall som flaggskeppet.
// Bereik begransat till de 13 karnkategorierna som, tillsammans med de 4
// universella verktygen (startsidan), utgor de 17 element som definierar
// sidans identitet.

export type LocalizedSwedishUnitPage = {
  locale: "sv";
  sourceSlug: string;
  slug: string;
  category: string;
  categoryName: string;
  unit: string;
  name: string;
  symbol: string;
  shortDescription: string;
  historySummary: string;
  measurementSystem: string;
  siEquivalent: string;
  commonUses: string;
};

export const swedishUnitPages: LocalizedSwedishUnitPage[] = [
  // Langd
  {
    locale: "sv",
    sourceSlug: "metre",
    slug: "meter",
    category: "uzunluk",
    categoryName: "Langd",
    unit: "m",
    name: "Meter",
    symbol: "m",
    shortDescription: "Metern ar den grundlaggande langdenheten i Internationella Enhetssystemet. Den anvands for att mata avstand och storlek, fran vardagslivet till teknik.",
    historySummary: "Metern uppstod under franska revolutionen, i syfte att ersatta de matenheter som dittills varierat fran region till region med en enda universell och naturbaserad standard. Man overvagde forst en definition baserad pa en pendels svangningstid, men den overgavs eftersom en pendel paverkas av den lokala tyngdkraften. Istallet definierade franska nationalforsamlingen 1791 metern som en tiomiljondel av avstandet fran Nordpolen till ekvatorn langs meridianen genom Paris -- ett avstand som berakandes genom Delambres och Mechains ariga geodetiska matningar. Ar 1799 baserades definitionen pa en platinastav kallad 'Metre des Archives'; 1889 ersattes staven av en ny standard i platina-iridiumlegering, med 29 kopior utplacerade over hela varlden. Ar 1960 definierades metern inte langre utifran ett fysiskt foremal, utan utifran vaglangden hos ljuset som en krypton-86-atom sander ut. Sedan 1983 definieras metern som den strackan ljus tillryggalagger i vakuum pa 1/299 792 458 sekund -- detta gor att metern kan reproduceras med extremt hog precision i vilket laboratorium som helst i varlden, utan att behova en fysisk prototyp.",
    measurementSystem: "Internationella Enhetssystemet (SI)",
    siEquivalent: "SI:s grundlaggande langdenhet",
    commonUses: "Byggnation, vetenskap, tillverkning, geometri och allman matning",
  },
  {
    locale: "sv",
    sourceSlug: "kilometre",
    slug: "kilometer",
    category: "uzunluk",
    categoryName: "Langd",
    unit: "km",
    name: "Kilometer",
    symbol: "km",
    shortDescription: "Kilometer ar en langdenhet lika med 1000 meter. Den anvands for att uttrycka avstand mellan stader och geografiska avstand.",
    historySummary: "Kilometern etablerade sig som ett veulve av metern inom det metriska systemets decimala struktur. Den blev en standardbeteckning for vagar och kartskalor.",
    measurementSystem: "Internationella Enhetssystemet (SI, multipel)",
    siEquivalent: "1 km = 1000 m",
    commonUses: "Vagavstand, geografi, kartografi och infrastruktur",
  },
  {
    locale: "sv",
    sourceSlug: "santimetre",
    slug: "centimeter",
    category: "uzunluk",
    categoryName: "Langd",
    unit: "cm",
    name: "Centimeter",
    symbol: "cm",
    shortDescription: "Centimeter ar en langdenhet lika med en hundradel av en meter. Den ar vanlig for att uttrycka sma foremal och vardagliga matt.",
    historySummary: "Centimetern utvecklades som en decimal underenhet i det metriska systemet. Den fick brett genomslag eftersom den gjorde matningar praktiska och latta att berakna snabbt.",
    measurementSystem: "Internationella Enhetssystemet (SI, underenhet)",
    siEquivalent: "1 cm = 0,01 m",
    commonUses: "Mobler, textil, antropometri och vardagliga matningar",
  },
  {
    locale: "sv",
    sourceSlug: "milimetre",
    slug: "millimeter",
    category: "uzunluk",
    categoryName: "Langd",
    unit: "mm",
    name: "Millimeter",
    symbol: "mm",
    shortDescription: "Millimeter ar en langdenhet lika med en tusendel av en meter. Den anvands ofta vid precisa tekniska matningar.",
    historySummary: "Millimetern fick spridning i takt med industrins och teknikens behov av att mata mindre toleranser. Den blev en grundlaggande underenhet inom tillverknings- och ritningsstandarder.",
    measurementSystem: "Internationella Enhetssystemet (SI, underenhet)",
    siEquivalent: "1 mm = 0,001 m",
    commonUses: "Mekanisk tillverkning, tekniska ritningar, bearbetningstoleranser",
  },
  {
    locale: "sv",
    sourceSlug: "fit",
    slug: "fot",
    category: "uzunluk",
    categoryName: "Langd",
    unit: "ft",
    name: "Fot",
    symbol: "ft",
    shortDescription: "Fot ar en langdenhet som anvands i det brittiska och amerikanska matsystemet. En internationell fot motsvarar exakt 0,3048 meter.",
    historySummary: "Fot (foot) var historiskt, som namnet antyder, ett ungefarligt matt baserat pa den mansliga fotens langd, och sedan den romerska enheten 'pes' har tiotals olika 'fot'-definitioner mellan 250 och 335 mm anvants i olika regioner och epoker. Den fot som sa smaningom etablerades i England fastslogs 1959 (samma ar som tum och engelsk mil ocksa fastslogs) genom en internationell overenskommelse mellan USA, Storbritannien och Samvaldslanderna till exakt 0,3048 meter (det vill saga exakt 12 tum).",
    measurementSystem: "Brittiskt och amerikanskt matsystem",
    siEquivalent: "1 ft = 0,3048 m",
    commonUses: "Arkitektur, byggnadshojder, luftfart och faltmatningar",
  },
  {
    locale: "sv",
    sourceSlug: "inc",
    slug: "tum",
    category: "uzunluk",
    categoryName: "Langd",
    unit: "in",
    name: "Tum",
    symbol: "in",
    shortDescription: "Tum ar en kort langdenhet som anvands i det brittiska och amerikanska matsystemet. En tum motsvarar exakt 2,54 centimeter.",
    historySummary: "Ordet tum (inch) harstammar fran latinets 'uncia', som betyder 'en tolftedel'. Den aldsta definitionen gjordes 1324 av kung Edward II av England som 'tre korn korn lagda ande mot ande', och denna definition anvandes i arhundraden. Enligt en annan tradition definierade kung David I av Skottland (1100-talet) tummen som bredden vid nageln pa en mans tumme. Ett avgorande genombrott kom 1896 nar den svenske ingenjoren Carl Edvard Johansson, vid tillverkningen av sina precisionsmatblock, i praktiken fastslog tummen till exakt 25,4 mm -- denna 'industriella tum' antogs av brittiska standardiseringsorgan 1930 och amerikanska 1933. Den slutliga internationella overenskommelsen tradde i kraft 1959 (i USA den 1 juli), och sedan dess ar en tum exakt definierad som 25,4 millimeter.",
    measurementSystem: "Brittiskt och amerikanskt matsystem",
    siEquivalent: "1 in = 25,4 mm = 2,54 cm",
    commonUses: "Skarmstorlekar, rorledningar, fastelement och tekniska kataloger",
  },
  {
    locale: "sv",
    sourceSlug: "yarda",
    slug: "yard",
    category: "uzunluk",
    categoryName: "Langd",
    unit: "yd",
    name: "Yard",
    symbol: "yd",
    shortDescription: "Yard ar en langdenhet som anvands i det brittiska och amerikanska matsystemet. En yard motsvarar exakt 0,9144 meter.",
    historySummary: "Yardens ursprung ar inte helt klarlagt, men enligt en vanlig tradition definierade kung Henry I av England pa 1100-talet yarden som avstandet fran hans nastipp till tummen pa hans utstrackta arm. En mer val dokumenterad utveckling var att officiella bronsstavar, 'yard-stavar', tillverkades som standardreferens i den engelska skattkammaren pa 1500-talet. Liksom fot och tum fastslogs aven yarden genom den internationella overenskommelsen 1959 till exakt 0,9144 meter (3 fot).",
    measurementSystem: "Brittiskt och amerikanskt matsystem",
    siEquivalent: "1 yd = 0,9144 m",
    commonUses: "Idrottsplaner, textil, tradgardsdesign och faltplanering",
  },
  {
    locale: "sv",
    sourceSlug: "mil",
    slug: "engelsk-mil",
    category: "uzunluk",
    categoryName: "Langd",
    unit: "mi",
    name: "Engelsk mil",
    symbol: "mi",
    shortDescription: "Engelsk mil ar en langdenhet som anvands sarskilt i USA och Storbritannien. En internationell mil motsvarar 1609,344 meter.",
    historySummary: "Ordet 'mil' kommer fran det latinska uttrycket 'mille passus' (tusen steg) -- ett 'steg' rakandes som avstandet mellan tva nedslag av samma fot. Den romerska milen fastslogs indirekt nar Marcus Agrippa ar 29 f.Kr. faststallde en standard romersk fot (1 steg = 5 romerska fot, 1 mil = 5000 romerska fot ≈ 1479 meter). I det medeltida England var den 'gamla engelska milen' ett oklart matt pa cirka 2,1 km som varierade fran region till region. Den avgorande vandpunkten kom 1593: en parlamentslag om matt och vikt under drottning Elizabeth I:s regeringstid behöll den traditionella milstrukturen pa 8 furlongs men okade antalet fot, och faststallde milen till exakt 5280 fot (1760 yard) -- denna definition spreds via det brittiska imperiet och utgor grunden for dagens internationella mil. Den moderna internationella milen fastslogs 1959 till exakt 1609,344 meter.",
    measurementSystem: "Brittiskt och amerikanskt matsystem",
    siEquivalent: "1 mi = 1609,344 m",
    commonUses: "Vagavstand, navigation och faltskalor",
  },

  // Area
  {
    locale: "sv",
    sourceSlug: "metrekare",
    slug: "kvadratmeter",
    category: "alan",
    categoryName: "Area",
    unit: "m²",
    name: "Kvadratmeter",
    symbol: "m²",
    shortDescription: "Kvadratmeter ar SI:s harledda enhet for area. Den anvands som grundreferens vid berakningar av golvyta, tvarsnitt och ytor.",
    historySummary: "Kvadratmetern etablerade sig inom det metriska systemet som en tvadimensionell forlangning av metern. Den blev standardspraket for area i bygg-, mark- och tekniska ritningar.",
    measurementSystem: "Internationella Enhetssystemet (SI)",
    siEquivalent: "SI:s grundlaggande areaenhet",
    commonUses: "Arkitektur, inredning, panelytor och tvarsnittsareor",
  },
  {
    locale: "sv",
    sourceSlug: "hektar",
    slug: "hektar",
    category: "alan",
    categoryName: "Area",
    unit: "ha",
    name: "Hektar",
    symbol: "ha",
    shortDescription: "Hektar ar en stor areaenhet som sarskilt anvands vid markmatning. 1 hektar motsvarar exakt 10 000 kvadratmeter.",
    historySummary: "Hektar definierades 1795, som en del av det metriska system som franska revolutionen forde med sig, som 100 ganger enheten 'ar' (100 m²) och fick namnet med forledet 'hekto-' (hundra). Eftersom den ansags mycket mer praktisk an ar for att uttrycka stora jordbruks- och skogsarealer, blev den med tiden den globala standardenheten for mark. Som en intuitiv jamforelse ar en standardfotbollsplan ungefar 0,7 hektar stor -- vilket gor hektar latt att greppa i vardagslivet.",
    measurementSystem: "Metriskt system, forenligt med SI",
    siEquivalent: "1 ha = 10 000 m²",
    commonUses: "Jordbruksmark, detaljplaner och stora fastighetsregister",
  },
  {
    locale: "sv",
    sourceSlug: "akre",
    slug: "acre",
    category: "alan",
    categoryName: "Area",
    unit: "ac",
    name: "Acre",
    symbol: "ac",
    shortDescription: "Acre ar en stor areaenhet som sarskilt anvands for markmatning i det brittiska och amerikanska matsystemet. Den motsvarar 4046,8564224 kvadratmeter.",
    historySummary: "Acre utvecklades historiskt fran ett synsatt baserat pa den markyta ett par oxar kunde plojja pa en dag, och anvands fortfarande som standard markenhet i det brittiska matsystemet.",
    measurementSystem: "Brittiskt och amerikanskt matsystem",
    siEquivalent: "1 acre = 4046,8564224 m²",
    commonUses: "Fastighets- och markforsaljning, jordbruksmarksmatning och fastighetsannonser",
  },

  // Volym
  {
    locale: "sv",
    sourceSlug: "litre",
    slug: "liter",
    category: "hacim",
    categoryName: "Volym",
    unit: "L",
    name: "Liter",
    symbol: "L",
    shortDescription: "Liter ar en mycket vanlig volymenhet for att uttrycka vatskor och kapaciteter. 1 liter motsvarar 0,001 kubikmeter.",
    historySummary: "Litern definierades 1795 i Frankrike, som en del av det nya matsystem som franska revolutionen forde med sig, som 'en kubisk decimeter'. Ar 1901 definierade Generalkonferensen for matt och vikt om litern som 'volymen som upptas av 1 kg rent vatten vid dess maximala densitet (3,98 °C) vid ett tryck av en atmosfar' -- men denna definition gjorde litern nagot storre (cirka 1,000028 ganger) an en kubikdecimeter, eftersom referensens platina-iridium-kilogramprototyp visade sig vara 28 miljondelar storre an vantat. Denna avvikelse, som bestod i 63 ar, korrigerades 1964 nar Generalkonferensen ater definierade litern som exakt 'en kubikdecimeter', direkt kopplad till metern.",
    measurementSystem: "Metriskt system, forenligt med SI",
    siEquivalent: "1 L = 0,001 m³",
    commonUses: "Vatskor, tankvolymer, laboratoriekarl och vardagliga matt",
  },
  {
    locale: "sv",
    sourceSlug: "mililitre",
    slug: "milliliter",
    category: "hacim",
    categoryName: "Volym",
    unit: "mL",
    name: "Milliliter",
    symbol: "mL",
    shortDescription: "Milliliter ar en liten volymenhet lika med en tusendel av en liter. Den anvands for precisa vatskematningar.",
    historySummary: "Millilitern fick spridning for att pa ett tillforlitligt satt kunna uttrycka sma volymer inom lakemedel, laboratoriearbete och matlagning.",
    measurementSystem: "Metriskt system, forenligt med SI",
    siEquivalent: "1 mL = 0,000001 m³",
    commonUses: "Lakemedelsdoser, laboratorieprover och sma vatskevolymer",
  },
  {
    locale: "sv",
    sourceSlug: "metrekup",
    slug: "kubikmeter",
    category: "hacim",
    categoryName: "Volym",
    unit: "m³",
    name: "Kubikmeter",
    symbol: "m³",
    shortDescription: "Kubikmeter ar SI:s harledda enhet for volym. Den ar grundreferensen for stora volymer och tekniska kapaciteter.",
    historySummary: "Kubikmeter definieras som den inre volymen hos en kub vars varje sida ar exakt 1 meter, och harleds direkt genom att utvidga metern till tre dimensioner. Eftersom den motsvarar 1000 liter (1 m³ = 1000 L) anvands den som global standardenhet vid fakturering av naturgas- och vattenforbrukning -- aven i Turkiet visar naturgas- och vattenrakningar forbrukningen i kubikmeter. Inom byggbranschen uttrycks aven betong- och schaktmangder, och inom industrin tank- och forradskapaciteter, ofta i denna enhet.",
    measurementSystem: "Internationella Enhetssystemet (SI)",
    siEquivalent: "SI:s grundlaggande volymenhet",
    commonUses: "Lagringsvolym, byggnaders innervolym, processtankar och flodesberakningar",
  },
  {
    locale: "sv",
    sourceSlug: "galon",
    slug: "gallon",
    category: "hacim",
    categoryName: "Volym",
    unit: "gal",
    name: "Gallon (USA)",
    symbol: "gal",
    shortDescription: "Gallon ar en enhet som sarskilt anvands i USA for att mata vatskevolym. En amerikansk gallon motsvarar 3,78541 liter.",
    historySummary: "Den amerikanska gallonen bygger pa den medeltida engelska handelstraditionen med 'vingallonen', och faststalldes 1706 under drottning Annes regeringstid till exakt 231 kubiktum (3,785411784 L) -- USA antog officiellt denna definition 1836. Storbritannien gick 1824 en helt annan vag och definierade om sin egen 'imperial gallon' som 'volymen som motsvarar vikten av 10 pund destillerat vatten' (cirka 4,546 L) och avskaffade alla andra galllondefinitioner. Pa grund av dessa olika ursprung ar den brittiska gallonen cirka 20 % storre an den amerikanska.",
    measurementSystem: "Amerikanskt matsystem (US liquid gallon)",
    siEquivalent: "1 gallon (USA) = 3,78541 L = 0,00378541 m³",
    commonUses: "Branslefoerbrukning, amerikanska vatskeprodukters etiketter och koksmatt",
  },

  // Massa
  {
    locale: "sv",
    sourceSlug: "kilogram",
    slug: "kilogram",
    category: "kutle",
    categoryName: "Massa",
    unit: "kg",
    name: "Kilogram",
    symbol: "kg",
    shortDescription: "Kilogram ar SI:s grundenhet for massa. Den anvands i stor utstrackning inom handel, laboratoriearbete och teknik.",
    historySummary: "Ocksa kilogrammets ursprung gar tillbaka till franska revolutionen: 1795 definierades gram som massan hos 1 kubikcentimeter vatten vid dess smaltpunkt (0 °C) -- det vill saga 1 kilogram motsvarade massan hos 1 liter vatten under dessa forhallanden. Men nar man insag att vattnets densitet varierar med temperaturen, tillverkades 1799 en platinaprototyp kallad 'Kilogramme des Archives'; denna gang var referensen massan hos 1 kubikdecimeter vatten vid ~4 °C, dar vattnet ar som tatast. Ar 1889 ersattes denna prototyp av en ny cylinder i platina-iridiumlegering, kand som 'Le Grand K', som under 130 ar bevarades som varldens referenskilogram vid Internationella byran for matt och vikt i Frankrike. Med tiden upptacktes att denna cylinder avvek cirka 50 mikrogram fran sina samtida kopior -- en ofrankomlig svaghet i att basera en definition pa ett fysiskt foremal. Den 16 november 2018 beslutade Generalkonferensen for matt och vikt att ge kilogrammet en ny definition baserad pa Plancks konstant; denna nya definition tradde i kraft den 20 maj 2019, och kilogrammet kan nu reproduceras i vilket laboratorium som helst i varlden utan behov av ett fysiskt referensforemal.",
    measurementSystem: "Internationella Enhetssystemet (SI)",
    siEquivalent: "SI:s grundlaggande massaenhet",
    commonUses: "Handel, transport, laboratorie- och processberakningar",
  },
  {
    locale: "sv",
    sourceSlug: "gram",
    slug: "gram",
    category: "kutle",
    categoryName: "Massa",
    unit: "g",
    name: "Gram",
    symbol: "g",
    shortDescription: "Gram ar en massaenhet lika med en tusendel av ett kilogram. Den anvands for att uttrycka livsmedel, laboratorie- och sma materiemangder.",
    historySummary: "Gram var den egentliga grundlaggande massaenheten i den forsta definitionen av det franska metriska systemet 1795, och definierades som massan hos 1 kubikcentimeter vatten vid dess smaltpunkt. Men eftersom det i praktiken var svart att omvandla en sa liten massa till en precis och reproducerbar standardprototyp, valdes 1799 istallet kilogrammet -- 1000 ganger storre (massan hos en kubikdecimeter vatten) -- som referensprototyp. Detta historiska val ledde till att kilogrammet blev det enda undantaget bland SI:s sju grundenheter vars namn innehaller ett prefix ('kilo-') -- gram, som ju ger namnet at enheten, ar idag i stallet en sekundar enhet definierad som en underenhet av kilogrammet.",
    measurementSystem: "Internationella Enhetssystemet (SI, underenhet)",
    siEquivalent: "1 g = 0,001 kg",
    commonUses: "Livsmedel, kemi, farmaci och precisionsmatning",
  },
  {
    locale: "sv",
    sourceSlug: "miligram",
    slug: "milligram",
    category: "kutle",
    categoryName: "Massa",
    unit: "mg",
    name: "Milligram",
    symbol: "mg",
    shortDescription: "Milligram ar en mycket liten massaenhet lika med en tusendel av ett gram. Den har avgorande betydelse vid lakemedels- och laboratoriematningar.",
    historySummary: "Milligrammet fick storre betydelse i takt med att precisionsvagar och analytiska laboratorier utvecklades, sarskilt inom halso- och kemiomradet.",
    measurementSystem: "Internationella Enhetssystemet (SI, underenhet)",
    siEquivalent: "1 mg = 0,000001 kg",
    commonUses: "Lakemedelsdoser, analyser och precisionsformuleringar",
  },
  {
    locale: "sv",
    sourceSlug: "ton",
    slug: "ton",
    category: "kutle",
    categoryName: "Massa",
    unit: "t",
    name: "Ton",
    symbol: "t",
    shortDescription: "Metriskt ton ar en stor massaenhet lika med 1000 kilogram. Den anvands for att uttrycka tunga laster och industriella mangder.",
    historySummary: "Ordet 'ton' harstammar fran det medeltida engelska ordet 'tun', som betyder en stor vintunna; eftersom en fylld tunna vagde ungefar ett 'long ton', borjade ordet ocksa anvandas som massaenhet. Idag kan tre olika 'ton'-definitioner skapa forvirring: det metriska tonet (exakt 1000 kg, standard i varlden och i Turkiet), det i USA vanliga 'short ton' (2000 pund ≈ 907,18 kg), och det i Storbritannien historiskt anvanda 'long ton' (2240 pund ≈ 1016,05 kg). Aven om skillnaden mellan dessa tre varden kan verka liten ar det viktigt att tydligt ange vilken 'ton'-definition som anvands i internationella handels- och logistikavtal.",
    measurementSystem: "Metriskt system, forenligt med SI",
    siEquivalent: "1 t = 1000 kg",
    commonUses: "Logistik, tillverkning, ravaruhandel och tung industri",
  },
  {
    locale: "sv",
    sourceSlug: "pound",
    slug: "pund",
    category: "kutle",
    categoryName: "Massa",
    unit: "lb",
    name: "Pund",
    symbol: "lb",
    shortDescription: "Pund ar en massaenhet som anvands i det brittiska och amerikanska matsystemet. Ett internationellt pund motsvarar exakt 0,45359237 kilogram.",
    historySummary: "Pund harstammar fran den romerska enheten 'libra' (cirka 328,9 gram, indelad i 12 'uncia') -- forkortningen 'lb' kommer direkt harifran; sjalva ordet 'pound' kommer fran uttrycket 'libra pondo' (en vikt matt med libra). Fore normandernas erovring (1066) anvandes i England det 'saxiska pundet', definierat i silver under kung Offas tid (757-796), dar 1 pund silver gav 240 pence. Det 'avoirdupois-pund' som blev vanligt i handeln omkring 1300 var till en borjan 6992 troy grain, men fastslogs under drottning Elizabeth I:s regeringstid till exakt 7000 troy grain (indelat i 16 uns). Genom 1878 ars lag om matt och vikt utsags en platinacylinder till officiell standardprototyp. Den slutliga internationella overenskommelsen undertecknades den 1 juli 1959: pundet ar sedan dess exakt 0,45359237 kilogram; Storbritannien antog formellt denna definition genom 1963 ars lag.",
    measurementSystem: "Brittiskt och amerikanskt matsystem",
    siEquivalent: "1 lb = 0,45359237 kg",
    commonUses: "Detaljhandel, transport, naring och industriella kataloger",
  },
  {
    locale: "sv",
    sourceSlug: "ons",
    slug: "uns",
    category: "kutle",
    categoryName: "Massa",
    unit: "oz",
    name: "Uns",
    symbol: "oz",
    shortDescription: "Uns ar en liten massaenhet som anvands i det brittiska och amerikanska matsystemet. Ett avoirdupois-uns motsvarar 28,349523125 gram.",
    historySummary: "Ordet 'uns' harstammar fran den romerska enheten 'uncia', som delade upp 'libra' (pundets foregangare) i tolv lika delar. Det avoirdupois-uns som anvands i vardagslivet (28,349523125 g) motsvarar 1/16 av ett pund; men det troy-uns som anvands i handeln med adla metaller ar annorlunda och tyngre (31,1034768 g) -- darfor motsvarar det 'pris per uns' som anges for guld/silver cirka 10 % mer an det uns som anvands vid vanliga inkop. Troy-unset har fatt sitt namn fran Troyes, en viktig medeltida handelsmassestad i Frankrike.",
    measurementSystem: "Brittiskt och amerikanskt matsystem",
    siEquivalent: "1 oz = 28,349523125 g",
    commonUses: "Forpackning, livsmedel och lattare kommersiella matt utanfor smycken",
  },

  // Temperatur
  {
    locale: "sv",
    sourceSlug: "santigrat",
    slug: "celsius",
    category: "sicaklik",
    categoryName: "Temperatur",
    unit: "C",
    name: "Celsius",
    symbol: "°C",
    shortDescription: "Celsiusskalan ar en av de vanligaste temperaturangivelserna i vardagslivet och tekniken.",
    historySummary: "Celsiusskalan uppfanns 1742 av den svenske astronomen Anders Celsius -- men intressant nog var hans ursprungliga skala tvartom mot dagens: 0 grader angav vattnets kokpunkt, och 100 grader dess fryspunkt. Skalan vandes 1743 av den franske fysikern Jean-Pierre Christin (i konstruktionen av 'Lyontermometern') till dagens ordning med 0 °C som fryspunkt och 100 °C som kokpunkt; den svenske botanikern Carl Linne gjorde samma vandning oberoende 1744 for sin egen vaxthustermometer. Skalan kallades lange 'centigrad'; 1948 andrade Internationella kommittén for matt och vikt officiellt namnet till 'Celsiusgrad', dels for att hedra Celsius minne, dels for att undvika sammanblandning med 'centigrad' som i vissa sprak ocksa betyder en hundradels vinkelgrad.",
    measurementSystem: "Temperaturskala som anvands tillsammans med SI",
    siEquivalent: "For temperaturskillnad: 1 °C = 1 K",
    commonUses: "Vaderrapportering, HVAC, processovervakning och vardagliga temperaturvarden",
  },
  {
    locale: "sv",
    sourceSlug: "fahrenhayt",
    slug: "fahrenheit",
    category: "sicaklik",
    categoryName: "Temperatur",
    unit: "F",
    name: "Fahrenheit",
    symbol: "°F",
    shortDescription: "Fahrenheit ar en temperaturskala som sarskilt ar vanlig i USA.",
    historySummary: "Fahrenheitskalan utvecklades 1724 av den i Polen fodda, nederlandska fysikern Daniel Gabriel Fahrenheit. Han satte nollpunkten till den kallaste temperatur dar en blandning av is, vatten och ammoniumklorid (eller havssalt) stabiliserades; 32 grader motsvarade rent vattens fryspunkt, och 96 grader (enligt hans egen matning) mansklig kroppstemperatur. Fahrenheit hade fatt en finare, brakdelsfri indelning genom att multiplicera den tidigare Romer-skalans varden med 4. Aren 1776-77 standardiserade en kommitte inom Royal Society, under ledning av Henry Cavendish, skalan och faststallde vattnets fryspunkt till exakt 32 °F och kokpunkt till exakt 212 °F -- denna korrigering ledde till att normal kroppstemperatur hamnade pa det varde vi kanner idag, 98,6 °F.",
    measurementSystem: "Brittisk och amerikansk mattradition",
    siEquivalent: "For temperaturskillnad: 1 °F = 5/9 K",
    commonUses: "Amerikanska vaderdata, inomhustemperaturer och vissa tekniska kataloger",
  },
  {
    locale: "sv",
    sourceSlug: "kelvin",
    slug: "kelvin",
    category: "sicaklik",
    categoryName: "Temperatur",
    unit: "K",
    name: "Kelvin",
    symbol: "K",
    shortDescription: "Kelvin ar SI:s grundenhet for temperatur och representerar den absoluta temperaturskalan.",
    historySummary: "Grunden till Kelvinskalan lades 1848 av den skotske fysikern William Thomson (som senare fick titeln Lord Kelvin); i sin uppsats 'On an Absolute Thermometric Scale' beraknade han, med hjalp av ideala gasers varmeutvidgningskoefficient, att den absoluta nollpunkten lag vid cirka -273 °C -- forbluffande nara dagens varde -273,15 °C. Ar 1854 arbetade han tillsammans med James Prescott Joule for att gora skalan mer praktisk och forenlig med luftermometrar. Enheten formaliserades 1954 vid den 10:e Generalkonferensen for matt och vikt, genom att vattnets trippelpunkt definierades till exakt 273,16 K; 1967/68 gav den 13:e konferensen enheten namnet 'kelvin'. Ar 2019 andrades definitionen annu mer grundlaggande: kelvin bygger nu inte pa vattnets trippelpunkt, utan direkt pa Boltzmanns konstant (fastslagen till 1,380649 × 10⁻²³ J/K).",
    measurementSystem: "Internationella Enhetssystemet (SI)",
    siEquivalent: "SI:s grundlaggande temperaturenhet",
    commonUses: "Termodynamik, vetenskapliga berakningar och analyser som kraver absolut temperatur",
  },

  // Tid
  {
    locale: "sv",
    sourceSlug: "saniye",
    slug: "sekund",
    category: "zaman",
    categoryName: "Tid",
    unit: "s",
    name: "Sekund",
    symbol: "s",
    shortDescription: "Sekund ar SI:s grundenhet for tid. Alla berakningar av varaktighet och hastighet bygger pa den.",
    historySummary: "Historiskt definierades sekunden som 1/86 400 av ett dygn; men man insag att smarre oregelbundenheter i jordens rotationshastighet gjorde denna definition otillrackligt stabil. Vid Generalkonferensen for matt och vikts 13:e mote 1967 definierades sekunden om i grunden: den definieras nu som exakt 9 192 631 770 perioder av den stralning som motsvarar overgangen mellan tva grundlaggande energiniva hos cesium-133-atomen. Denna definition gjorde det mojligt for atomklockor att reproduceras med samma precision (i storleksordningen en miljarddel) overallt i varlden, och kopplade sekunden till en universell referens oberoende av himlakropparnas rorelse.",
    measurementSystem: "Internationella Enhetssystemet (SI)",
    siEquivalent: "SI:s grundlaggande tidsenhet",
    commonUses: "Experimenttider, rorelseanalys, dataloggning och tidtagning",
  },
  {
    locale: "sv",
    sourceSlug: "dakika",
    slug: "minut",
    category: "zaman",
    categoryName: "Tid",
    unit: "min",
    name: "Minut",
    symbol: "min",
    shortDescription: "Minut ar en praktisk tidsenhet lika med 60 sekunder.",
    historySummary: "Minuten ar en historiskt utbredd mellanenhet inom bade daglig planering och icke-vetenskaplig tidsuppfoljning.",
    measurementSystem: "Utanfor SI, men tillaten tillsammans med SI",
    siEquivalent: "1 min = 60 s",
    commonUses: "Moten, korta tidsintervall, traning och processcykler",
  },
  {
    locale: "sv",
    sourceSlug: "saat",
    slug: "timme",
    category: "zaman",
    categoryName: "Tid",
    unit: "h",
    name: "Timme",
    symbol: "h",
    shortDescription: "Timme ar en vanlig tidsenhet lika med 3600 sekunder.",
    historySummary: "Timmen har forts vidare fran himmelska och mekaniska tidmatningstraditioner till moderna kalender- och skiftsystem.",
    measurementSystem: "Utanfor SI, men tillaten tillsammans med SI",
    siEquivalent: "1 h = 3600 s",
    commonUses: "Arbetstider, resor, energiforbrukning och daglig planering",
  },
  {
    locale: "sv",
    sourceSlug: "gun",
    slug: "dygn",
    category: "zaman",
    categoryName: "Tid",
    unit: "day",
    name: "Dygn",
    symbol: "d",
    shortDescription: "Dygn ar en grundlaggande tidsenhet baserad pa jordens en fullstandiga rotation kring sin egen axel (soldygnet), lika med 24 timmar (86 400 sekunder).",
    historySummary: "Begreppet dygn ar mansklighetens aldsta och mest universella tidsmatt, baserat pa solens upp- och nedgang. I den moderna definitionen ar 1 dygn fastslaget till exakt 86 400 SI-sekunder (medelvardet av soldygnet).",
    measurementSystem: "Utanfor SI, men tillaten tillsammans med SI",
    siEquivalent: "1 dygn = 86 400 s = 24 timmar",
    commonUses: "Kalenderberakningar, varaktighets-/aldersberakningar, resor och projektplanering",
  },

  // Hastighet
  {
    locale: "sv",
    sourceSlug: "kilometre-saat",
    slug: "kilometer-i-timmen",
    category: "hiz",
    categoryName: "Hastighet",
    unit: "km/h",
    name: "Kilometer i timmen",
    symbol: "km/h",
    shortDescription: "Kilometer i timmen ar en praktisk hastighetsenhet som ar vanlig inom vagtransport.",
    historySummary: "I takt med att vag- och transportsystem blev vanligare standardiserades kilometer i timmen som mattet for korning och resor.",
    measurementSystem: "Metrisk praktisk anvandning",
    siEquivalent: "1 km/h ≈ 0,277778 m/s",
    commonUses: "Fordonshastigheter, trafikskyltar och faltmatningar",
  },
  {
    locale: "sv",
    sourceSlug: "metre-saniye",
    slug: "meter-per-sekund",
    category: "hiz",
    categoryName: "Hastighet",
    unit: "m/s",
    name: "Meter per sekund",
    symbol: "m/s",
    shortDescription: "Meter per sekund ar SI:s harledda enhet for hastighet. Den anvands som grundreferens inom teknik och fysik.",
    historySummary: "Denna beteckning, som uppstar ur kombinationen av meter och sekund, ar det moderna vetenskapliga sprak som anvands som standard for hastighetsmatning.",
    measurementSystem: "Internationella Enhetssystemet (SI)",
    siEquivalent: "SI:s grundlaggande hastighetsenhet",
    commonUses: "Vatskor, mekanisk rorelse och vetenskapliga matningar",
  },
  {
    locale: "sv",
    sourceSlug: "mil-saat",
    slug: "engelsk-mil-i-timmen",
    category: "hiz",
    categoryName: "Hastighet",
    unit: "mph",
    name: "Engelsk mil i timmen",
    symbol: "mph",
    shortDescription: "Engelsk mil i timmen ar en hastighetsenhet som sarskilt anvands i USA och Storbritannien.",
    historySummary: "Kombinationen av engelsk mil och timme utgor den grundlaggande hastighetsterminologin i den anglo-amerikanska mattraditionen for vagtransport.",
    measurementSystem: "Brittiskt och amerikanskt matsystem",
    siEquivalent: "1 mph = 1,609344 km/h",
    commonUses: "Vaghastigheter, fordonsindustri och faltrapporter",
  },
  {
    locale: "sv",
    sourceSlug: "knot",
    slug: "knop",
    category: "hiz",
    categoryName: "Hastighet",
    unit: "knot",
    name: "Knop",
    symbol: "kn",
    shortDescription: "Knop (nautisk mil per timme) ar standardhastighetsenheten inom sjofart och luftfart, lika med en fart av 1 nautisk mil (1852 meter) i timmen.",
    historySummary: "Namnet knop kommer historiskt fran en trabit fastbunden vid ett knutat rep ('chip log') som kastades i vattnet for att mata fartygs hastighet; genom att rakna hur manga knutar som lopte ut pa en bestamd tid fick man fartygets fart.",
    measurementSystem: "Utanfor SI, standardenhet inom sjofart/luftfart",
    siEquivalent: "1 knop = 1852/3600 m/s ≈ 0,5144 m/s",
    commonUses: "Fartygs- och flygplanshastighet, vindhastighet (meteorologi), navigationsberakningar till sjoss",
  },

  // Tryck
  {
    locale: "sv",
    sourceSlug: "pascal",
    slug: "pascal",
    category: "basinc",
    categoryName: "Tryck",
    unit: "Pa",
    name: "Pascal",
    symbol: "Pa",
    shortDescription: "Pascal ar den harledda SI-enheten for tryck. Den definieras genom sambandet 1 Pa = 1 N/m².",
    historySummary: "Enheten ar uppkallad efter den franske 1600-talsvetenskapsmannen Blaise Pascal -- Pascal ar kand for sitt arbete inom hydrodynamik och hydrostatik samt sina banbrytande tryckexperiment med barometern. Pascals upptackt att 'tryck som appliceras pa en instangd vatska fortplantar sig lika i alla riktningar' (Pascals lag) utgor grunden for hydrauliska system. Enheten antogs formellt som SI-enhet vid Generalkonferensen for matt och vikts 14:e mote 1971 och definierades som newton per kvadratmeter (N/m²).",
    measurementSystem: "Internationella Enhetssystemet (SI)",
    siEquivalent: "SI:s grundlaggande tryckenhet, 1 Pa = 1 N/m²",
    commonUses: "Vetenskapliga berakningar, materialanalys och referensomvandlingar",
  },
  {
    locale: "sv",
    sourceSlug: "bar",
    slug: "bar",
    category: "basinc",
    categoryName: "Tryck",
    unit: "bar",
    name: "Bar",
    symbol: "bar",
    shortDescription: "Bar ar en tryckenhet lika med 100 000 pascal. Den ar en mycket vanlig praktisk beteckning inom industri- och utrustningsvisning.",
    historySummary: "Enheten bar introducerades av den norske meteorologen Vilhelm Bjerknes, en av moderna vaderleksprognosens pionjarer; namnet kommer fran det grekiska ordet 'baros', som betyder 'vikt' (intressant nog anvandes ordet 'bar' mellan 1793 och 1795 aven for en massaenhet motsvarande dagens ton, i det tidiga metriska systemet). 1 bar motsvarar exakt 100 000 pascal och ligger mycket nara medelatmosfartrycket vid havsniva (cirka 1,013 bar). Aven om bar inte ar en officiell SI-enhet anvands den fortfarande i stor utstrackning av meteorologer och flygbranschen, tack vare att den numeriskt sammanfaller med millibar/hektopascal och ar praktisk att anvanda.",
    measurementSystem: "Metrisk teknisk enhet utanfor SI",
    siEquivalent: "1 bar = 100 000 Pa",
    commonUses: "Kompressorer, hydraulik, pneumatik och servicemanometrar",
  },
  {
    locale: "sv",
    sourceSlug: "psi",
    slug: "psi",
    category: "basinc",
    categoryName: "Tryck",
    unit: "psi",
    name: "PSI",
    symbol: "psi",
    shortDescription: "PSI ar forkortningen for 'pound-force per square inch'. Det ar en vanlig tryckenhet inom anglo-amerikanska tekniska system.",
    historySummary: "PSI ar, som namnet antyder, en sammansatt enhet som bildas genom att dela en kraftenhet (pound-force) med en areaenhet (kvadrattum), och blev vanlig inom brittisk ingenjorstradition pa 1800-talet for att uttrycka pannans tryck under angmaskinernas tidsalder. Aven om det metriska systemet har blivit global standard fortsatter PSI att fungera som faktisk branschstandard inom fordonsindustrin (dacktryck), hydrauliska system och amerikansk industriutrustning.",
    measurementSystem: "Brittisk och amerikansk teknisk anvandning",
    siEquivalent: "1 psi = 6894,757293168 Pa",
    commonUses: "Dacktryck, hydrauliska system och teknisk service",
  },
  {
    locale: "sv",
    sourceSlug: "atmosfer",
    slug: "atmosfar",
    category: "basinc",
    categoryName: "Tryck",
    unit: "atm",
    name: "Standardatmosfar",
    symbol: "atm",
    shortDescription: "Atmosfar ar en tryckenhet baserad pa ett referensvarde nara jordatmosfarens genomsnittliga tryck vid havsniva. Den kallas aven standardatmosfar.",
    historySummary: "Atmosfarsenheten fick spridning genom att barometriska matningar och havsnivans referenstryck anvandes som standard jamforelsepunkt i tekniska och vetenskapliga sammanhang. Ar 1954 definierade den 10:e Generalkonferensen for matt och vikt (CGPM) standardatmosfaren till exakt 101 325 Pa.",
    measurementSystem: "Utanfor SI, referensenhet inom meteorologi och teknik",
    siEquivalent: "1 atm = 101 325 Pa (definierat varde)",
    commonUses: "Referensforhallanden, meteorologi, vakuum och tryckmatningar",
  },

  // Energi
  {
    locale: "sv",
    sourceSlug: "joule",
    slug: "joule",
    category: "enerji",
    categoryName: "Energi",
    unit: "J",
    name: "Joule",
    symbol: "J",
    shortDescription: "Joule ar SI:s harledda enhet for energi. Den anvands for att uttrycka arbete, varme och energimangder.",
    historySummary: "Enheten ar uppkallad efter den engelske fysikern James Prescott Joule (1818-1889), for hans arbete som visade sambandet mellan mekaniskt arbete och varme. Namnet foreslogs forsta gangen den 23 augusti 1882, i William Siemens ordforandetal vid British Association for the Advancement of Science; Siemens foreslog att kalla enheten 'joule' till minne av 'mannen som bidragit sa mycket till att utveckla den dynamiska varmeteorin'. Enheten antogs officiellt den 31 augusti 1889, vid den andra internationella elektrikerkongressen, tillsammans med enheten watt -- av en tillfallighet gick Joule bort samma ar (den 11 oktober 1889). Definitionen uppdaterades 1946 inom ramen for Giorgi-systemet och uttrycktes da direkt, oberoende av elektromagnetiska enheter, som 'det arbete en kraft utfor over en strackan pa en meter'.",
    measurementSystem: "Internationella Enhetssystemet (SI)",
    siEquivalent: "SI:s grundlaggande energienhet",
    commonUses: "Termodynamik, energibalanser och vetenskapliga berakningar",
  },
  {
    locale: "sv",
    sourceSlug: "kilovatsaat",
    slug: "kilowattimme",
    category: "enerji",
    categoryName: "Energi",
    unit: "kWh",
    name: "Kilowattimme",
    symbol: "kWh",
    shortDescription: "Kilowattimme ar en vanlig energienhet vid elforbrukning.",
    historySummary: "Genom elmatare och faktureringssystem har kilowattimme blivit en av de mest kanda enheterna for praktisk energianvandning.",
    measurementSystem: "Teknisk och kommersiell energienhet",
    siEquivalent: "1 kWh = 3,6 MJ",
    commonUses: "Elrakningar, batterikapacitet och forbrukningsjamforelser",
  },
  {
    locale: "sv",
    sourceSlug: "kalori",
    slug: "kalori",
    category: "enerji",
    categoryName: "Energi",
    unit: "cal",
    name: "Kalori",
    symbol: "cal",
    shortDescription: "Kalori (cal) definieras som den energimangd som kravs for att hoja temperaturen hos ett gram vatten med 1 °C, och ar en energienhet utanfor SI. Enligt den termokemiska definitionen motsvarar 1 kalori 4,184 joule.",
    historySummary: "Begreppet kalori infordes pa 1800-talet av den franske kemisten Nicolas Clement for att mata varmemangd, och fick spridning under termodynamikens utvecklingsperiod. Aven om SI-enheten joule i stor utstrackning forvantas ersatta den, anvands den fortfarande i stor utstrackning (som kilokalori) inom naringslara.",
    measurementSystem: "Utanfor SI, traditionell energienhet",
    siEquivalent: "1 cal = 4,184 J (termokemisk definition)",
    commonUses: "Kemiska och termodynamiska berakningar, livsmedelsenergi (via kilokalori)",
  },
  {
    locale: "sv",
    sourceSlug: "btu",
    slug: "btu",
    category: "enerji",
    categoryName: "Energi",
    unit: "Btu",
    name: "BTU",
    symbol: "BTU",
    shortDescription: "BTU (British Thermal Unit) definieras som den energimangd som kravs for att hoja temperaturen hos ett pund vatten med 1 °F, och ar en energienhet som anvands i det brittiska/amerikanska matsystemet.",
    historySummary: "BTU utvecklades i England under angmaskinernas tidsalder for att mata varmeenergi, och blev med tiden standardenheten inom varme-/kylbranschen i anglosaxiska lander, framst USA.",
    measurementSystem: "Brittiskt och amerikanskt matsystem",
    siEquivalent: "1 Btu = 1055,056 J",
    commonUses: "Kapacitet for luftkonditionering och varmare (kyl-/varmeeffekt), naturgasrakningar (USA)",
  },

  // Data-opslag / Datalagring
  {
    locale: "sv",
    sourceSlug: "bayt",
    slug: "byte",
    category: "veri",
    categoryName: "Datalagring",
    unit: "B",
    name: "Byte",
    symbol: "B",
    shortDescription: "Byte ar den grundlaggande matenheten for digital data. Den bestar av 8 bitar och anvands for att representera ett tecken (bokstav, siffra osv.).",
    historySummary: "Termen 'byte' myntades 1956 av ingenjoren Werner Buchholz, som arbetade med IBM:s Stretch-dator, genom att avsiktligt andra stavningen av ordet 'bite' for att undvika forvaxling med ordet 'bit'. Under de forsta aren kunde en byte ha olika langd, fran 1 till 6 bitar, beroende pa vilken datorarkitektur som anvandes; standarden pa 8-bitars byte blev i praktiken branschstandard med IBM:s System/360, som lanserades 1964 och var en av tidens mest inflytelserika datorfamiljer.",
    measurementSystem: "Digital dataenhet (databehandlingsstandard)",
    siEquivalent: "1 byte = 8 bit",
    commonUses: "Filstorlek, minneskapacitet och matning av dataoverforing",
  },
  {
    locale: "sv",
    sourceSlug: "megabayt",
    slug: "megabyte",
    category: "veri",
    categoryName: "Datalagring",
    unit: "MB",
    name: "Megabyte",
    symbol: "MB",
    shortDescription: "Megabyte (MB) ar en dataenhet lika med 1 000 000 byte. Den anvands i stor utstrackning for att uttrycka storleken pa foton, musikfiler och korta dokument.",
    historySummary: "I takt med att persondatorer blev vanligare blev megabyte en standardreferensenhet for att uttrycka fil- och diskstorlekar.",
    measurementSystem: "Internationella Enhetssystemet (SI, multipel)",
    siEquivalent: "1 MB = 1 000 000 byte",
    commonUses: "Foton, musikfiler, korta videor och applikationsstorlekar",
  },
  {
    locale: "sv",
    sourceSlug: "gigabayt",
    slug: "gigabyte",
    category: "veri",
    categoryName: "Datalagring",
    unit: "GB",
    name: "Gigabyte",
    symbol: "GB",
    shortDescription: "Gigabyte (GB) ar en dataenhet lika med 1 miljard byte. Den anvands for att uttrycka lagringsutrymme pa smartphones, videofiler och RAM-kapacitet.",
    historySummary: "I takt med lagringsteknikens utveckling blev gigabyte standardenheten for att uttrycka disk-, minnes- och mobilenheters kapacitet; skillnaden mellan SI:s (bastal 1000) och datorvarldens traditionella (bastal 1024) anvandning blir tydligast markbar just vid denna enhet.",
    measurementSystem: "Internationella Enhetssystemet (SI, multipel)",
    siEquivalent: "1 GB = 1 000 000 000 byte",
    commonUses: "Lagringsutrymme pa smartphones och datorer, RAM-kapacitet, videofiler",
  },

  // Elektricitet
  {
    locale: "sv",
    sourceSlug: "volt",
    slug: "volt",
    category: "elektrik",
    categoryName: "Elektricitet",
    unit: "V",
    name: "Volt",
    symbol: "V",
    shortDescription: "Volt ar den harledda SI-enheten for elektrisk spanning.",
    historySummary: "Enheten ar uppkallad efter den italienske fysikern Alessandro Volta -- Volta uppfann 1800, efter diskussioner med sin kollega Luigi Galvani om 'animal elektricitet', det 'voltaiska batteriet'; genom att upptacka att zink och silver var det mest effektiva metallparet skapade han varldens forsta apparat som producerade en kontinuerlig elektrisk strom (foregangaren till batteriet). Namnet 'volt' foreslogs mycket senare, 1861, av Latimer Clark och Charles Bright. Ar 1873 definierade British Association for the Advancement of Science formellt enheterna volt, ohm och farad; 1881 antog den internationella elektrikerkongressen volt som officiell enhet for elektromotorisk kraft (spanning). Vid SI-revideringen 2019 uppdaterades aven volts definition, i och med att den elementara elektriska laddningen fastslogs till ett bestamt varde.",
    measurementSystem: "Internationella Enhetssystemet (SI)",
    siEquivalent: "SI:s grundlaggande spanningsenhet",
    commonUses: "Elektroniska kretsar, stromforsorjningar och natspanningar",
  },
  {
    locale: "sv",
    sourceSlug: "amper",
    slug: "ampere",
    category: "elektrik",
    categoryName: "Elektricitet",
    unit: "A",
    name: "Ampere",
    symbol: "A",
    shortDescription: "Ampere ar SI:s grundenhet for elektrisk strom.",
    historySummary: "Enheten ar uppkallad efter den franske fysikern och matematikern André-Marie Ampère (1775-1836), som lade grunden for elektrodynamiken genom sina studier av elektromagnetism; Ampère byggde vidare pa den danske fysikern Hans Christian Orsteds upptackter inom omradet. Ampere utsags till standardenhet for elektrisk strom genom en internationell overenskommelse som undertecknades vid den internationella elektricitetsutstallningen 1881; dess forsta definition var en tiondel av CGS-systemets elektromagnetiska stromenhet. Fram till SI-revideringen 2019 definierades ampere som den strom som mellan tva parallella ledare pa 1 meters avstand fran varandra ger upphov till en magnetisk kraft pa 2×10⁻⁷ newton per meter; sedan 2019 definieras den istallet direkt via multiplar av den elementara elektriska laddningen (fastslagen till 1,602176634×10⁻¹⁹ coulomb).",
    measurementSystem: "Internationella Enhetssystemet (SI)",
    siEquivalent: "SI:s grundlaggande stromenhet",
    commonUses: "Strommatningar, skyddskomponenter och apparatetiketter",
  },
  {
    locale: "sv",
    sourceSlug: "miliamper",
    slug: "milliampere",
    category: "elektrik",
    categoryName: "Elektricitet",
    unit: "mA",
    name: "Milliampere",
    symbol: "mA",
    shortDescription: "Milliampere ar en liten stromenhet lika med en tusendel av en ampere.",
    historySummary: "For att laga strommar ska kunna avlasas bekvamt i elektronik och matinstrument har beteckningen milliampere fatt stor spridning.",
    measurementSystem: "Internationella Enhetssystemet (SI, underenhet)",
    siEquivalent: "1 mA = 0,001 A",
    commonUses: "Elektroniska kretsar, sensorer och lagstromstester",
  },

  // Guldkarat
  {
    locale: "sv",
    sourceSlug: "24-ayar-altin",
    slug: "24-karat-guld",
    category: "altin_ayar",
    categoryName: "Guldkaraat",
    unit: "24K",
    name: "24 karat guld",
    symbol: "24K",
    shortDescription: "24 karat guld ar till 99,9 % rent, nastan helt rent guld. Eftersom det ar den mjukaste karaten anvands det oftast i tackor och investeringsprodukter.",
    historySummary: "Karatsystemet ar en traditionell juvelerarstandard som uttrycker renhetsgraden i en guldlegering pa en skala fran 24; 24 karat representerar olegerat, rent guld.",
    measurementSystem: "Juvelerarnas renhetsstandard (karat)",
    siEquivalent: "24 karat = 100 % rent guldinnehall",
    commonUses: "Guldtackor, investeringsguld och anvandning som renhetsreferens",
  },
  {
    locale: "sv",
    sourceSlug: "22-ayar-altin",
    slug: "22-karat-guld",
    category: "altin_ayar",
    categoryName: "Guldkaraat",
    unit: "22K",
    name: "22 karat guld",
    symbol: "22K",
    shortDescription: "22 karat guld ar en legering dar 22/24 (cirka 91,6 %) av innehallet ar rent guld. Den ar vanlig for armband och traditionella smycken i Turkiet.",
    historySummary: "22 karat har uppstatt genom att en liten mangd silver eller koppar legeras in i rent guld for att minska mjukheten och oka hallbarheten, och har blivit den traditionella smyckesstandarden i Turkiet och Mellanostern.",
    measurementSystem: "Juvelerarnas renhetsstandard (karat)",
    siEquivalent: "22 karat = 91,6 % rent guldinnehall (22/24)",
    commonUses: "Armband, traditionella smycken och guldgavor",
  },
  {
    locale: "sv",
    sourceSlug: "18-ayar-altin",
    slug: "18-karat-guld",
    category: "altin_ayar",
    categoryName: "Guldkaraat",
    unit: "18K",
    name: "18 karat guld",
    symbol: "18K",
    shortDescription: "18 karat guld ar en legering dar 18/24 (75 %) av innehallet ar rent guld. Tack vare den hoga hallbarheten foredras den for vardagssmycken.",
    historySummary: "18 karat, som ar hardare och mer repbestandigt an rent guld, har blivit den internationella standarden sarskilt for ringar och vardagssmycken.",
    measurementSystem: "Juvelerarnas renhetsstandard (karat)",
    siEquivalent: "18 karat = 75 % rent guldinnehall (18/24)",
    commonUses: "Ringar, halsband, vardagssmycken och diamantinfattningar",
  },

  // Zilvergehalte / Silverhalt
  {
    locale: "sv",
    sourceSlug: "999-ayar-gumus",
    slug: "silver-999",
    category: "gumus_ayar",
    categoryName: "Silverhalt",
    unit: "999",
    name: "Silver 999 (fint)",
    symbol: "999",
    shortDescription: "Silver 999 ar till 99,9 % rent, nastan helt rent silver, ocksa kallat 'fint silver'. Eftersom det ar mycket mjukt anvands det framst i tackor och investeringsprodukter snarare an smycken.",
    historySummary: "Till skillnad fran guld uttrycks silvrets renhet direkt i promille; 999 representerar olegerat, rent silver och anvands som renhetsreferens vid handel med adla metaller.",
    measurementSystem: "Juvelerarnas renhetsstandard (promille)",
    siEquivalent: "999 = 99,9 % rent silverinnehall",
    commonUses: "Silvertackor, investeringssilver och anvandning som renhetsreferens",
  },
  {
    locale: "sv",
    sourceSlug: "925-ayar-gumus",
    slug: "sterlingsilver-925",
    category: "gumus_ayar",
    categoryName: "Silverhalt",
    unit: "925",
    name: "Sterlingsilver (925)",
    symbol: "925",
    shortDescription: "Sterlingsilver innehaller 92,5 % rent silver, dar resten oftast ar koppar. Det ar kant varlden over som 'sterling silver' och ar den mest anvanda silverstandarden inom smycken.",
    historySummary: "Sterlingsilverstandarden uppstod i England for att motverka rent silvers extrema mjukhet, och har med tiden blivit den faktiska globala standarden for silversmycken och husgerad.",
    measurementSystem: "Juvelerarnas renhetsstandard (promille)",
    siEquivalent: "925 = 92,5 % rent silverinnehall (sterlingsilver)",
    commonUses: "Silversmycken, ringar, halsband och silverbestick",
  },
];

export function findSwedishUnitPageBySourceSlug(sourceSlug: string) {
  return swedishUnitPages.find((page) => page.sourceSlug === sourceSlug);
}

export function findSwedishUnitPage(category: string, unit: string) {
  return swedishUnitPages.find(
    (page) => page.category === category && page.unit === unit
  );
}
