// Unidades en espanol para las categorias tecnicas y cientificas
// (potencia, fuerza, densidad, angulo, frecuencia, caudal, electricidad...).
// Mismo formato que localizedSpanishExtraUnitPages.ts; se combinan alli.
import type { SpanishExtraUnit } from "./localizedSpanishExtraUnitPages";

const SI_DERIVED = "Unidad derivada del SI";
const US = "Sistema consuetudinario de EE. UU.";
const CGS = "Sistema CGS";
const TECHNICAL = "Sistema técnico de unidades";

export const spanishScienceUnits: SpanishExtraUnit[] = [
  // Potencia
  {
    sourceSlug: "watt", slug: "vatio", name: "Vatio",
    shortDescription: "El vatio es la unidad de potencia del SI: un julio de energía por segundo.",
    historySummary: "Recibe su nombre de James Watt, cuyas mejoras de la máquina de vapor impulsaron la Revolución Industrial.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 W = 1 J/s",
    commonUses: "Bombillas, electrodomésticos, cargadores y paneles solares",
  },
  {
    sourceSlug: "kilowatt", slug: "kilovatio", name: "Kilovatio",
    shortDescription: "El kilovatio equivale a 1.000 vatios y es la unidad habitual de potencia de motores y aparatos grandes.",
    historySummary: "En la mayoría de los países la potencia oficial de los coches se indica en kW, aunque se siga hablando de caballos.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 kW = 1.000 W",
    commonUses: "Potencia de coches, calderas, bombas de calor y la potencia contratada de la luz",
  },
  {
    sourceSlug: "megawatt", slug: "megavatio", name: "Megavatio",
    shortDescription: "El megavatio equivale a un millón de vatios.",
    historySummary: "Es la escala de las centrales eléctricas: un aerogenerador moderno ronda los 3 a 15 MW.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 MW = 1.000.000 W",
    commonUses: "Centrales eléctricas, parques eólicos y solares, industria pesada",
  },
  {
    sourceSlug: "beygirgucu", slug: "caballo-de-vapor", name: "Caballo de vapor (CV)", displaySymbol: "CV",
    shortDescription: "El caballo de vapor métrico (CV) equivale a unos 735,5 vatios.",
    historySummary: "Se define como la potencia necesaria para levantar 75 kg a un metro de altura en un segundo. Es el «caballo» de las fichas de coches en España y Latinoamérica.",
    measurementSystem: "Unidad métrica tradicional", siEquivalent: "1 CV = 735,49875 W",
    commonUses: "Potencia de coches, motos y motores",
  },
  {
    sourceSlug: "beygirgucu-mekanik", slug: "caballo-de-fuerza", name: "Caballo de fuerza (hp)", displaySymbol: "hp",
    shortDescription: "El caballo de fuerza mecánico (hp) equivale a unos 745,7 vatios, algo más que el CV.",
    historySummary: "James Watt lo definió en el siglo XVIII comparando sus máquinas con el trabajo de los caballos. Se usa sobre todo en EE. UU. y el Reino Unido.",
    measurementSystem: US, siEquivalent: "1 hp ≈ 745,6999 W",
    commonUses: "Motores de coches estadounidenses, motores eléctricos y maquinaria",
  },
  {
    sourceSlug: "btu-saat", slug: "btu-por-hora", name: "BTU por hora",
    shortDescription: "La BTU por hora (BTU/h) es la unidad de potencia térmica de los aparatos de aire acondicionado.",
    historySummary: "Un equipo de «12.000 BTU» tiene una capacidad de enfriamiento de 12.000 BTU/h, unos 3,5 kW.",
    measurementSystem: US, siEquivalent: "1 BTU/h ≈ 0,29307 W",
    commonUses: "Aire acondicionado, calefacción y climatización",
  },
  {
    sourceSlug: "sogutma-tonu", slug: "tonelada-de-refrigeracion", name: "Tonelada de refrigeración",
    shortDescription: "La tonelada de refrigeración (TR) equivale a 12.000 BTU/h, unos 3,517 kW de frío.",
    historySummary: "Procede de la potencia necesaria para fundir una tonelada corta de hielo en 24 horas.",
    measurementSystem: US, siEquivalent: "1 TR ≈ 3.516,85 W",
    commonUses: "Capacidad de enfriadoras, climatización industrial y equipos de aire",
  },

  // Fuerza
  {
    sourceSlug: "newton", slug: "newton", name: "Newton",
    shortDescription: "El newton es la unidad de fuerza del SI: la fuerza que acelera 1 kg a 1 m/s².",
    historySummary: "Lleva el nombre de Isaac Newton, que formuló las leyes del movimiento en 1687.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 N = 1 kg·m/s²",
    commonUses: "Física, ingeniería y cálculo de estructuras",
  },
  {
    sourceSlug: "kilonewton", slug: "kilonewton", name: "Kilonewton",
    shortDescription: "El kilonewton equivale a 1.000 newtons, aproximadamente el peso de 102 kg.",
    historySummary: "Es la unidad habitual para cargas en ingeniería civil, anclajes y equipos de escalada.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 kN = 1.000 N",
    commonUses: "Cargas estructurales, anclajes, mosquetones y grúas",
  },
  {
    sourceSlug: "kilogram-kuvvet", slug: "kilogramo-fuerza", name: "Kilogramo-fuerza",
    shortDescription: "El kilogramo-fuerza (kgf) es el peso de una masa de 1 kg en la gravedad estándar.",
    historySummary: "Muy usado antes del SI en la industria; en el lenguaje común, «pesa 10 kilos» se refiere a esta idea.",
    measurementSystem: TECHNICAL, siEquivalent: "1 kgf = 9,80665 N",
    commonUses: "Básculas de fuerza, ingeniería antigua y fichas técnicas",
  },
  {
    sourceSlug: "pound-kuvvet", slug: "libra-fuerza", name: "Libra-fuerza",
    shortDescription: "La libra-fuerza (lbf) es el peso de una libra de masa en la gravedad estándar.",
    historySummary: "Es la unidad de fuerza del sistema anglosajón; el empuje de los motores de avión se suele dar en lbf.",
    measurementSystem: US, siEquivalent: "1 lbf ≈ 4,44822 N",
    commonUses: "Empuje de motores, ingeniería en EE. UU. y arco",
  },
  {
    sourceSlug: "dyn", slug: "dina", name: "Dina",
    shortDescription: "La dina es la unidad de fuerza del sistema CGS: 10⁻⁵ newtons.",
    historySummary: "Se usó en física hasta mediados del siglo XX y aparece aún en la tensión superficial (dyn/cm).",
    measurementSystem: CGS, siEquivalent: "1 dyn = 0,00001 N",
    commonUses: "Tensión superficial y textos científicos antiguos",
  },

  // Densidad
  {
    sourceSlug: "kilogram-metrekup", slug: "kilogramo-por-metro-cubico", name: "Kilogramo por metro cúbico",
    shortDescription: "El kg/m³ es la unidad de densidad del SI. El agua tiene unos 1.000 kg/m³.",
    historySummary: "Es la unidad de referencia en ingeniería para materiales, fluidos y gases.",
    measurementSystem: SI_DERIVED, siEquivalent: "Unidad de densidad del SI",
    commonUses: "Materiales de construcción, fluidos y cálculo de pesos",
  },
  {
    sourceSlug: "gram-santimetrekup", slug: "gramo-por-centimetro-cubico", name: "Gramo por centímetro cúbico",
    shortDescription: "El g/cm³ es una unidad de densidad cómoda para sólidos y líquidos: el agua tiene 1 g/cm³.",
    historySummary: "Procede del sistema CGS y sigue siendo habitual en química y mineralogía.",
    measurementSystem: CGS, siEquivalent: "1 g/cm³ = 1.000 kg/m³",
    commonUses: "Química, metales, minerales y plásticos",
  },
  {
    sourceSlug: "gram-mililitre", slug: "gramo-por-mililitro", name: "Gramo por mililitro",
    shortDescription: "El g/mL es numéricamente igual al g/cm³ y se usa para líquidos.",
    historySummary: "Es la forma habitual de indicar la densidad de soluciones en el laboratorio.",
    measurementSystem: "Unidad métrica", siEquivalent: "1 g/mL = 1.000 kg/m³",
    commonUses: "Laboratorio, farmacia y líquidos",
  },
  {
    sourceSlug: "kilogram-litre", slug: "kilogramo-por-litro", name: "Kilogramo por litro",
    shortDescription: "El kg/L indica cuántos kilos pesa un litro de sustancia; el agua pesa 1 kg/L.",
    historySummary: "Es práctico para aceites, combustibles y productos a granel.",
    measurementSystem: "Unidad métrica", siEquivalent: "1 kg/L = 1.000 kg/m³",
    commonUses: "Aceites, combustibles, pinturas y alimentos líquidos",
  },
  {
    sourceSlug: "gram-litre", slug: "gramo-por-litro", name: "Gramo por litro",
    shortDescription: "El g/L expresa la concentración o densidad de una sustancia en un litro.",
    historySummary: "Numéricamente coincide con el kg/m³; se usa mucho para concentraciones de soluciones.",
    measurementSystem: "Unidad métrica", siEquivalent: "1 g/L = 1 kg/m³",
    commonUses: "Concentración de soluciones, salinidad y análisis de agua",
  },
  {
    sourceSlug: "miligram-litre", slug: "miligramo-por-litro", name: "Miligramo por litro",
    shortDescription: "El mg/L mide concentraciones pequeñas; en agua equivale aproximadamente a partes por millón.",
    historySummary: "Es la unidad de los análisis de agua potable y de muchos límites ambientales.",
    measurementSystem: "Unidad métrica", siEquivalent: "1 mg/L = 0,001 kg/m³",
    commonUses: "Calidad del agua, nitratos, cloro y análisis ambientales",
  },
  {
    sourceSlug: "pound-fitkup", slug: "libra-por-pie-cubico", name: "Libra por pie cúbico",
    shortDescription: "La lb/ft³ es la unidad de densidad más usada en EE. UU.",
    historySummary: "El agua tiene unas 62,4 lb/ft³; se usa para materiales de construcción y áridos.",
    measurementSystem: US, siEquivalent: "1 lb/ft³ ≈ 16,0185 kg/m³",
    commonUses: "Hormigón, madera y materiales en EE. UU.",
  },
  {
    sourceSlug: "pound-inckup", slug: "libra-por-pulgada-cubica", name: "Libra por pulgada cúbica",
    shortDescription: "La lb/in³ se usa para densidades de metales en fichas técnicas estadounidenses.",
    historySummary: "El acero tiene unas 0,284 lb/in³ y el aluminio unas 0,098 lb/in³.",
    measurementSystem: US, siEquivalent: "1 lb/in³ ≈ 27.679,9 kg/m³",
    commonUses: "Metales y mecanizado en EE. UU.",
  },
  {
    sourceSlug: "pound-galon", slug: "libra-por-galon", name: "Libra por galón (US)",
    shortDescription: "La lb/gal indica cuántas libras pesa un galón estadounidense de líquido.",
    historySummary: "El agua pesa unas 8,34 lb/gal; es habitual en lodos de perforación y químicos.",
    measurementSystem: US, siEquivalent: "1 lb/gal ≈ 119,826 kg/m³",
    commonUses: "Lodos de perforación, pinturas y productos químicos",
  },
  {
    sourceSlug: "slug-fitkup", slug: "slug-por-pie-cubico", name: "Slug por pie cúbico",
    shortDescription: "El slug/ft³ es la unidad de densidad del sistema técnico inglés.",
    historySummary: "El slug es la masa que se acelera 1 ft/s² con una libra-fuerza; se usa en aerodinámica.",
    measurementSystem: US, siEquivalent: "1 slug/ft³ ≈ 515,379 kg/m³",
    commonUses: "Aerodinámica y mecánica de fluidos en EE. UU.",
  },

  // Aceleracion
  {
    sourceSlug: "metre-saniyekare", slug: "metro-por-segundo-cuadrado", name: "Metro por segundo al cuadrado",
    shortDescription: "El m/s² es la unidad de aceleración del SI.",
    historySummary: "Un objeto en caída libre cerca de la superficie terrestre acelera unos 9,81 m/s².",
    measurementSystem: SI_DERIVED, siEquivalent: "Unidad de aceleración del SI",
    commonUses: "Física, vehículos y sensores de movimiento",
  },
  {
    sourceSlug: "yercekimi-ivmesi", slug: "gravedad-estandar", name: "Gravedad estándar (g)",
    shortDescription: "La g expresa aceleraciones como múltiplos de la gravedad terrestre estándar.",
    historySummary: "Su valor, 9,80665 m/s², se fijó en 1901. Pilotos y montañas rusas se describen con «fuerzas g».",
    measurementSystem: "Unidad convencional", siEquivalent: "1 g = 9,80665 m/s²",
    commonUses: "Aviación, automovilismo, montañas rusas y acelerómetros",
  },
  {
    sourceSlug: "fit-saniyekare", slug: "pie-por-segundo-cuadrado", name: "Pie por segundo al cuadrado",
    shortDescription: "El ft/s² es la unidad de aceleración del sistema anglosajón.",
    historySummary: "La gravedad estándar equivale a unos 32,174 ft/s².",
    measurementSystem: US, siEquivalent: "1 ft/s² = 0,3048 m/s²",
    commonUses: "Ingeniería y balística en EE. UU.",
  },
  {
    sourceSlug: "santimetre-saniyekare", slug: "centimetro-por-segundo-cuadrado", name: "Centímetro por segundo al cuadrado",
    shortDescription: "El cm/s² es la unidad de aceleración del sistema CGS, igual al gal.",
    historySummary: "Se usa en geofísica y sismología para aceleraciones pequeñas.",
    measurementSystem: CGS, siEquivalent: "1 cm/s² = 0,01 m/s²",
    commonUses: "Geofísica y sismología",
  },
  {
    sourceSlug: "milimetre-saniyekare", slug: "milimetro-por-segundo-cuadrado", name: "Milímetro por segundo al cuadrado",
    shortDescription: "El mm/s² mide aceleraciones muy pequeñas.",
    historySummary: "Aparece en vibraciones de maquinaria y en instrumentación de precisión.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 mm/s² = 0,001 m/s²",
    commonUses: "Vibraciones y sensores de precisión",
  },
  {
    sourceSlug: "kilometre-saniyekare", slug: "kilometro-por-segundo-cuadrado", name: "Kilómetro por segundo al cuadrado",
    shortDescription: "El km/s² expresa aceleraciones enormes, propias de la astrofísica.",
    historySummary: "Es útil para describir aceleraciones de partículas o cuerpos en campos gravitatorios intensos.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 km/s² = 1.000 m/s²",
    commonUses: "Astrofísica y física de partículas",
  },
  {
    sourceSlug: "inc-saniyekare", slug: "pulgada-por-segundo-cuadrado", name: "Pulgada por segundo al cuadrado",
    shortDescription: "La in/s² es una unidad anglosajona de aceleración pequeña.",
    historySummary: "Se usa en ensayos de vibración y en especificaciones de máquinas estadounidenses.",
    measurementSystem: US, siEquivalent: "1 in/s² = 0,0254 m/s²",
    commonUses: "Vibraciones y maquinaria en EE. UU.",
  },
  {
    sourceSlug: "metre-dakikakare", slug: "metro-por-minuto-cuadrado", name: "Metro por minuto al cuadrado",
    shortDescription: "El m/min² expresa aceleraciones lentas, como las de cintas o ascensores.",
    historySummary: "Es cómodo cuando la velocidad se da en metros por minuto.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 m/min² ≈ 0,000278 m/s²",
    commonUses: "Cintas transportadoras, ascensores y ejes de máquinas",
  },
  {
    sourceSlug: "fit-dakikakare", slug: "pie-por-minuto-cuadrado", name: "Pie por minuto al cuadrado",
    shortDescription: "El ft/min² es una unidad anglosajona para aceleraciones lentas.",
    historySummary: "Aparece en sistemas de transporte y máquinas con velocidades en pies por minuto.",
    measurementSystem: US, siEquivalent: "1 ft/min² ≈ 0,0000847 m/s²",
    commonUses: "Transporte industrial en EE. UU.",
  },
  {
    sourceSlug: "gal-ivme", slug: "gal", name: "Gal",
    shortDescription: "El gal (o galileo) equivale a 1 cm/s².",
    historySummary: "Honra a Galileo Galilei. Los geofísicos usan el miligal para medir variaciones de la gravedad.",
    measurementSystem: CGS, siEquivalent: "1 Gal = 0,01 m/s²",
    commonUses: "Gravimetría, geodesia y sismología",
  },

  // Velocidad angular
  {
    sourceSlug: "devir-dakika", slug: "revoluciones-por-minuto", name: "Revoluciones por minuto",
    shortDescription: "Las revoluciones por minuto (rpm) indican cuántas vueltas completas da un eje en un minuto.",
    historySummary: "Es la unidad del cuentarrevoluciones de los coches y de la velocidad de discos, taladros y ventiladores.",
    measurementSystem: "Unidad práctica", siEquivalent: "1 rpm ≈ 0,10472 rad/s",
    commonUses: "Motores, lavadoras, taladros, discos y ventiladores",
  },
  {
    sourceSlug: "devir-saniye-acisal", slug: "revoluciones-por-segundo", name: "Revoluciones por segundo", displaySymbol: "rps",
    shortDescription: "Las revoluciones por segundo indican vueltas completas por segundo; 1 rps equivale a 60 rpm.",
    historySummary: "Numéricamente coincide con la frecuencia de giro en hercios.",
    measurementSystem: "Unidad práctica", siEquivalent: "1 rps = 2π rad/s",
    commonUses: "Turbinas, centrifugadoras y motores rápidos",
  },
  {
    sourceSlug: "radyan-saniye", slug: "radian-por-segundo", name: "Radián por segundo",
    shortDescription: "El rad/s es la unidad de velocidad angular del SI.",
    historySummary: "Se usa en física porque simplifica las fórmulas de rotación y oscilación.",
    measurementSystem: SI_DERIVED, siEquivalent: "Unidad de velocidad angular del SI",
    commonUses: "Física, control de motores y robótica",
  },
  {
    sourceSlug: "radyan-dakika", slug: "radian-por-minuto", name: "Radián por minuto",
    shortDescription: "El rad/min expresa giros lentos en radianes.",
    historySummary: "Es poco habitual; aparece en cálculos de mecanismos lentos.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 rad/min ≈ 0,016667 rad/s",
    commonUses: "Mecanismos lentos y cálculos técnicos",
  },
  {
    sourceSlug: "radyan-saat", slug: "radian-por-hora", name: "Radián por hora",
    shortDescription: "El rad/h expresa rotaciones muy lentas.",
    historySummary: "Sirve para movimientos como el giro de antenas o de seguidores solares.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 rad/h ≈ 0,000278 rad/s",
    commonUses: "Seguidores solares y movimientos astronómicos",
  },
  {
    sourceSlug: "derece-saniye", slug: "grado-por-segundo", name: "Grado por segundo",
    shortDescription: "El °/s indica cuántos grados gira un objeto en un segundo.",
    historySummary: "Es la unidad de los giroscopios de móviles, drones y consolas.",
    measurementSystem: "Unidad práctica", siEquivalent: "1 °/s ≈ 0,017453 rad/s",
    commonUses: "Giroscopios, drones, cámaras y robótica",
  },
  {
    sourceSlug: "derece-dakika", slug: "grado-por-minuto", name: "Grado por minuto",
    shortDescription: "El °/min expresa giros lentos en grados.",
    historySummary: "Se usa en navegación para la velocidad de giro de barcos.",
    measurementSystem: "Unidad práctica", siEquivalent: "1 °/min ≈ 0,000291 rad/s",
    commonUses: "Navegación marítima y maquinaria lenta",
  },
  {
    sourceSlug: "derece-saat", slug: "grado-por-hora", name: "Grado por hora",
    shortDescription: "El °/h mide rotaciones muy lentas; la Tierra gira unos 15 °/h.",
    historySummary: "Es la unidad de la deriva de los giroscopios de navegación inercial.",
    measurementSystem: "Unidad práctica", siEquivalent: "1 °/h ≈ 0,00000485 rad/s",
    commonUses: "Navegación inercial y astronomía",
  },

  // Angulo
  {
    sourceSlug: "derece", slug: "grado", name: "Grado",
    shortDescription: "El grado es la unidad de ángulo más común: una vuelta completa tiene 360 grados.",
    historySummary: "La división en 360 partes procede de la astronomía babilónica.",
    measurementSystem: "Unidad aceptada con el SI", siEquivalent: "1° = π/180 rad",
    commonUses: "Geometría, mapas, navegación y construcción",
  },
  {
    sourceSlug: "radyan", slug: "radian", name: "Radián",
    shortDescription: "El radián es la unidad de ángulo del SI: el arco igual al radio del círculo.",
    historySummary: "Una vuelta completa mide 2π radianes. Las calculadoras científicas permiten elegir entre grados y radianes.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 rad ≈ 57,2958°",
    commonUses: "Matemáticas, física y programación",
  },
  {
    sourceSlug: "gradyan", slug: "gradian", name: "Gradián (gon)",
    shortDescription: "El gradián divide la vuelta completa en 400 partes; un ángulo recto mide 100 gon.",
    historySummary: "Surgió con el sistema métrico en Francia y se mantiene en topografía.",
    measurementSystem: "Unidad métrica de ángulo", siEquivalent: "1 gon = 0,9°",
    commonUses: "Topografía y teodolitos",
  },
  {
    sourceSlug: "tam-tur", slug: "vuelta", name: "Vuelta completa",
    shortDescription: "Una vuelta completa equivale a 360 grados o 2π radianes.",
    historySummary: "Es la unidad natural para contar giros de ruedas, ejes y engranajes.",
    measurementSystem: "Unidad práctica", siEquivalent: "1 vuelta = 2π rad = 360°",
    commonUses: "Mecánica, engranajes y rotaciones",
  },

  // Frecuencia
  {
    sourceSlug: "hertz", slug: "hercio", name: "Hercio",
    shortDescription: "El hercio (Hz) es la unidad de frecuencia del SI: un ciclo por segundo.",
    historySummary: "Recibe su nombre de Heinrich Hertz, que demostró la existencia de las ondas electromagnéticas.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 Hz = 1 s⁻¹",
    commonUses: "Red eléctrica (50 o 60 Hz), sonido y señales",
  },
  {
    sourceSlug: "kilohertz", slug: "kilohercio", name: "Kilohercio",
    shortDescription: "El kilohercio equivale a 1.000 hercios.",
    historySummary: "Las emisoras de radio AM se sintonizan en kHz.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 kHz = 1.000 Hz",
    commonUses: "Radio AM, audio y ultrasonidos",
  },
  {
    sourceSlug: "megahertz", slug: "megahercio", name: "Megahercio",
    shortDescription: "El megahercio equivale a un millón de hercios.",
    historySummary: "Las emisoras de FM se sintonizan en MHz, por ejemplo 98,5 MHz.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 MHz = 1.000.000 Hz",
    commonUses: "Radio FM, electrónica y memorias",
  },
  {
    sourceSlug: "gigahertz", slug: "gigahercio", name: "Gigahercio",
    shortDescription: "El gigahercio equivale a mil millones de hercios.",
    historySummary: "Es la unidad de la velocidad de los procesadores y de las bandas wifi de 2,4 y 5 GHz.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 GHz = 10⁹ Hz",
    commonUses: "Procesadores, wifi, 5G y radar",
  },

  // Par de torsion
  {
    sourceSlug: "newton-metre", slug: "newton-metro", name: "Newton metro",
    shortDescription: "El newton metro (N·m) es la unidad de par o momento de fuerza del SI.",
    historySummary: "El par de los motores y el apriete de tornillos y ruedas se indica en N·m.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 N·m = 1 kg·m²/s²",
    commonUses: "Par de motores, llaves dinamométricas y apriete de tornillos",
  },
  {
    sourceSlug: "kilonewton-metre", slug: "kilonewton-metro", name: "Kilonewton metro",
    shortDescription: "El kilonewton metro equivale a 1.000 N·m.",
    historySummary: "Se usa para momentos grandes en estructuras, grúas y ejes industriales.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 kN·m = 1.000 N·m",
    commonUses: "Cálculo de estructuras, vigas y maquinaria pesada",
  },
  {
    sourceSlug: "kilogram-kuvvet-metre", slug: "kilogramo-fuerza-metro", name: "Kilogramo-fuerza metro",
    shortDescription: "El kgf·m es una unidad técnica de par, unas 9,81 veces el N·m.",
    historySummary: "Aparece en fichas de coches antiguos y en manuales de taller.",
    measurementSystem: TECHNICAL, siEquivalent: "1 kgf·m = 9,80665 N·m",
    commonUses: "Fichas técnicas antiguas y manuales de taller",
  },
  {
    sourceSlug: "pound-fit", slug: "libra-pie", name: "Libra pie",
    shortDescription: "La libra pie (lb·ft) es la unidad de par del sistema anglosajón.",
    historySummary: "Es la forma habitual de indicar el par de los motores en EE. UU.",
    measurementSystem: US, siEquivalent: "1 lb·ft ≈ 1,35582 N·m",
    commonUses: "Par de motores y llaves dinamométricas en EE. UU.",
  },

  // Momento lineal
  {
    sourceSlug: "kilogram-metre-saniye", slug: "kilogramo-metro-por-segundo", name: "Kilogramo metro por segundo",
    shortDescription: "El kg·m/s es la unidad de momento lineal (cantidad de movimiento) del SI.",
    historySummary: "El momento lineal es el producto de la masa por la velocidad y se conserva en los choques.",
    measurementSystem: SI_DERIVED, siEquivalent: "Unidad de momento lineal del SI",
    commonUses: "Física de choques, balística y mecánica",
  },
  {
    sourceSlug: "newton-saniye", slug: "newton-segundo", name: "Newton segundo",
    shortDescription: "El newton segundo (N·s) mide el impulso, y equivale exactamente al kg·m/s.",
    historySummary: "Se usa para el impulso de motores de cohetes y de impactos.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 N·s = 1 kg·m/s",
    commonUses: "Impulso de cohetes, impactos y deportes",
  },
  {
    sourceSlug: "pound-fit-saniye", slug: "libra-pie-por-segundo", name: "Libra pie por segundo",
    shortDescription: "La lb·ft/s es la unidad anglosajona de momento lineal.",
    historySummary: "Aparece en textos de física e ingeniería estadounidenses.",
    measurementSystem: US, siEquivalent: "1 lb·ft/s ≈ 0,138255 kg·m/s",
    commonUses: "Ingeniería en EE. UU.",
  },

  // Viscosidad dinamica
  {
    sourceSlug: "pascal-saniye", slug: "pascal-segundo", name: "Pascal segundo",
    shortDescription: "El pascal segundo (Pa·s) es la unidad de viscosidad dinámica del SI.",
    historySummary: "El agua a 20 °C tiene unos 0,001 Pa·s; la miel, entre 2 y 10 Pa·s.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 Pa·s = 1 kg/(m·s)",
    commonUses: "Ingeniería de fluidos, polímeros y alimentos",
  },
  {
    sourceSlug: "milipaskal-saniye", slug: "milipascal-segundo", name: "Milipascal segundo",
    shortDescription: "El mPa·s es igual al centipoise; el agua tiene alrededor de 1 mPa·s.",
    historySummary: "Es la unidad más habitual en fichas técnicas de pinturas, aceites y adhesivos.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 mPa·s = 0,001 Pa·s",
    commonUses: "Pinturas, aceites, adhesivos y cosméticos",
  },
  {
    sourceSlug: "poise", slug: "poise", name: "Poise",
    shortDescription: "El poise es la unidad de viscosidad dinámica del sistema CGS.",
    historySummary: "Honra al médico francés Jean Poiseuille, que estudió el flujo de la sangre.",
    measurementSystem: CGS, siEquivalent: "1 P = 0,1 Pa·s",
    commonUses: "Laboratorio y textos científicos",
  },
  {
    sourceSlug: "santipoise", slug: "centipoise", name: "Centipoise",
    shortDescription: "El centipoise (cP) es la centésima parte del poise y equivale a 1 mPa·s.",
    historySummary: "Su popularidad se debe a que el agua a 20 °C tiene casi exactamente 1 cP.",
    measurementSystem: CGS, siEquivalent: "1 cP = 0,001 Pa·s",
    commonUses: "Aceites, pinturas, alimentos y laboratorio",
  },

  // Viscosidad cinematica
  {
    sourceSlug: "metrekare-saniye", slug: "metro-cuadrado-por-segundo", name: "Metro cuadrado por segundo",
    shortDescription: "El m²/s es la unidad de viscosidad cinemática del SI.",
    historySummary: "La viscosidad cinemática es la dinámica dividida por la densidad del fluido.",
    measurementSystem: SI_DERIVED, siEquivalent: "Unidad de viscosidad cinemática del SI",
    commonUses: "Mecánica de fluidos y número de Reynolds",
  },
  {
    sourceSlug: "milimetrekare-saniye", slug: "milimetro-cuadrado-por-segundo", name: "Milímetro cuadrado por segundo",
    shortDescription: "El mm²/s es igual al centistokes y es la unidad de viscosidad de los aceites.",
    historySummary: "Los grados de viscosidad ISO VG se definen en mm²/s a 40 °C.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 mm²/s = 10⁻⁶ m²/s",
    commonUses: "Aceites lubricantes e hidráulicos, combustibles",
  },
  {
    sourceSlug: "santistok", slug: "centistokes", name: "Centistokes",
    shortDescription: "El centistokes (cSt) es la centésima parte del stokes y equivale a 1 mm²/s.",
    historySummary: "Lleva el nombre de George Stokes; el agua a 20 °C tiene aproximadamente 1 cSt.",
    measurementSystem: CGS, siEquivalent: "1 cSt = 10⁻⁶ m²/s",
    commonUses: "Aceites de motor, siliconas y combustibles",
  },

  // Caudal
  {
    sourceSlug: "metrekup-saat", slug: "metro-cubico-por-hora", name: "Metro cúbico por hora",
    shortDescription: "El m³/h indica cuántos metros cúbicos de fluido pasan en una hora.",
    historySummary: "Es la unidad habitual de bombas, ventiladores y contadores de agua.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 m³/h ≈ 0,27778 L/s",
    commonUses: "Bombas de agua, ventilación y piscinas",
  },
  {
    sourceSlug: "litre-dakika", slug: "litro-por-minuto", name: "Litro por minuto",
    shortDescription: "El L/min indica cuántos litros fluyen en un minuto.",
    historySummary: "Se usa para grifos, duchas, bombas pequeñas y oxígeno medicinal.",
    measurementSystem: "Unidad métrica", siEquivalent: "1 L/min ≈ 0,016667 L/s",
    commonUses: "Grifos, duchas, bombas y oxigenoterapia",
  },
  {
    sourceSlug: "metrekup-saniye", slug: "metro-cubico-por-segundo", name: "Metro cúbico por segundo",
    shortDescription: "El m³/s es la unidad de caudal volumétrico del SI.",
    historySummary: "El caudal de los ríos y presas se expresa en m³/s; el Amazonas supera los 200.000 m³/s.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 m³/s = 1.000 L/s",
    commonUses: "Ríos, presas, hidráulica e ingeniería",
  },
  {
    sourceSlug: "litre-saniye", slug: "litro-por-segundo", name: "Litro por segundo",
    shortDescription: "El L/s indica cuántos litros fluyen en un segundo.",
    historySummary: "Es habitual en redes de abastecimiento, saneamiento y riego.",
    measurementSystem: "Unidad métrica", siEquivalent: "1 L/s = 0,001 m³/s",
    commonUses: "Abastecimiento de agua, riego y alcantarillado",
  },
  {
    sourceSlug: "metrekup-saat-hacimsel", slug: "metro-cubico-por-hora-volumetrico", name: "Metro cúbico por hora (caudal volumétrico)",
    shortDescription: "El m³/h expresa caudales de agua, aire o gas en instalaciones.",
    historySummary: "Es la unidad de las curvas de bombas y del caudal de aire en climatización.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 m³/h ≈ 0,000278 m³/s",
    commonUses: "Bombas, climatización y gas",
  },
  {
    sourceSlug: "litre-dakika-hacimsel", slug: "litro-por-minuto-volumetrico", name: "Litro por minuto (caudal volumétrico)",
    shortDescription: "El L/min expresa caudales moderados de líquidos o gases.",
    historySummary: "Es habitual en hidráulica, neumática y equipos médicos.",
    measurementSystem: "Unidad métrica", siEquivalent: "1 L/min ≈ 0,0000167 m³/s",
    commonUses: "Hidráulica, neumática y equipos médicos",
  },
  {
    sourceSlug: "fitkup-dakika", slug: "pie-cubico-por-minuto", name: "Pie cúbico por minuto (CFM)",
    shortDescription: "El CFM indica cuántos pies cúbicos de aire mueve un equipo por minuto.",
    historySummary: "Es la unidad estándar de ventiladores, compresores y extractores en EE. UU.",
    measurementSystem: US, siEquivalent: "1 CFM ≈ 1,699 m³/h",
    commonUses: "Ventiladores, compresores, campanas y ventilación",
  },
  {
    sourceSlug: "galon-dakika", slug: "galon-por-minuto", name: "Galón por minuto (GPM)",
    shortDescription: "El GPM indica cuántos galones estadounidenses fluyen por minuto.",
    historySummary: "Se usa para bombas, piscinas y sistemas de riego en EE. UU.",
    measurementSystem: US, siEquivalent: "1 GPM ≈ 3,785 L/min",
    commonUses: "Bombas, piscinas, riego y fontanería",
  },
  {
    sourceSlug: "kilogram-saniye", slug: "kilogramo-por-segundo", name: "Kilogramo por segundo",
    shortDescription: "El kg/s es la unidad de caudal másico del SI.",
    historySummary: "El caudal másico no depende de la temperatura ni de la presión, por eso se prefiere en procesos.",
    measurementSystem: SI_DERIVED, siEquivalent: "Unidad de caudal másico del SI",
    commonUses: "Procesos industriales, turbinas y motores",
  },
  {
    sourceSlug: "kilogram-saat", slug: "kilogramo-por-hora", name: "Kilogramo por hora",
    shortDescription: "El kg/h indica cuántos kilos de materia pasan en una hora.",
    historySummary: "Es la unidad de dosificadores, quemadores y líneas de producción.",
    measurementSystem: "Unidad métrica", siEquivalent: "1 kg/h ≈ 0,000278 kg/s",
    commonUses: "Líneas de producción, quemadores y calderas",
  },
  {
    sourceSlug: "gram-saniye", slug: "gramo-por-segundo", name: "Gramo por segundo",
    shortDescription: "El g/s mide caudales másicos pequeños.",
    historySummary: "El sensor de flujo de aire (MAF) de los coches mide la entrada de aire en g/s.",
    measurementSystem: "Unidad métrica", siEquivalent: "1 g/s = 0,001 kg/s",
    commonUses: "Sensores MAF de motores y laboratorio",
  },
  {
    sourceSlug: "gram-saat", slug: "gramo-por-hora", name: "Gramo por hora",
    shortDescription: "El g/h mide caudales másicos muy pequeños.",
    historySummary: "Se usa en dosificación química y en emisiones de pequeños equipos.",
    measurementSystem: "Unidad métrica", siEquivalent: "1 g/h ≈ 2,78 × 10⁻⁷ kg/s",
    commonUses: "Dosificación química y emisiones",
  },

  // Resistencia, capacitancia, inductancia y carga
  {
    sourceSlug: "ohm", slug: "ohmio", name: "Ohmio",
    shortDescription: "El ohmio (Ω) es la unidad de resistencia eléctrica del SI.",
    historySummary: "Lleva el nombre de Georg Ohm, que formuló la ley V = I × R en 1827.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 Ω = 1 V/A",
    commonUses: "Resistencias, electrónica y medidas con polímetro",
  },
  {
    sourceSlug: "kiloohm", slug: "kiloohmio", name: "Kiloohmio",
    shortDescription: "El kiloohmio equivale a 1.000 ohmios.",
    historySummary: "Es el rango típico de las resistencias de los circuitos electrónicos.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 kΩ = 1.000 Ω",
    commonUses: "Electrónica y circuitos",
  },
  {
    sourceSlug: "megaohm", slug: "megaohmio", name: "Megaohmio",
    shortDescription: "El megaohmio equivale a un millón de ohmios.",
    historySummary: "Se usa para medir el aislamiento de cables e instalaciones eléctricas.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 MΩ = 1.000.000 Ω",
    commonUses: "Pruebas de aislamiento y electrónica",
  },
  {
    sourceSlug: "farad", slug: "faradio", name: "Faradio",
    shortDescription: "El faradio es la unidad de capacidad eléctrica del SI.",
    historySummary: "Honra a Michael Faraday. Un faradio es una capacidad muy grande; los supercondensadores la alcanzan.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 F = 1 C/V",
    commonUses: "Supercondensadores y física",
  },
  {
    sourceSlug: "milifarad", slug: "milifaradio", name: "Milifaradio",
    shortDescription: "El milifaradio es la milésima parte de un faradio.",
    historySummary: "Aparece en condensadores de gran capacidad de fuentes de alimentación.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 mF = 0,001 F",
    commonUses: "Fuentes de alimentación y audio",
  },
  {
    sourceSlug: "mikrofarad", slug: "microfaradio", name: "Microfaradio",
    shortDescription: "El microfaradio (µF) es la millonésima parte de un faradio.",
    historySummary: "Es la unidad de los condensadores de arranque de motores y de aires acondicionados.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 µF = 10⁻⁶ F",
    commonUses: "Condensadores de motores, aire acondicionado y electrónica",
  },
  {
    sourceSlug: "nanofarad", slug: "nanofaradio", name: "Nanofaradio",
    shortDescription: "El nanofaradio equivale a 10⁻⁹ faradios.",
    historySummary: "Es habitual en condensadores cerámicos y de filtrado.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 nF = 10⁻⁹ F",
    commonUses: "Electrónica, filtros y temporizadores",
  },
  {
    sourceSlug: "pikofarad", slug: "picofaradio", name: "Picofaradio",
    shortDescription: "El picofaradio equivale a 10⁻¹² faradios.",
    historySummary: "Se usa en circuitos de radiofrecuencia y osciladores.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 pF = 10⁻¹² F",
    commonUses: "Radiofrecuencia, osciladores y antenas",
  },
  {
    sourceSlug: "henry", slug: "henrio", name: "Henrio",
    shortDescription: "El henrio (H) es la unidad de inductancia del SI.",
    historySummary: "Honra al físico estadounidense Joseph Henry, pionero del electromagnetismo.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 H = 1 V·s/A",
    commonUses: "Bobinas, transformadores y filtros",
  },
  {
    sourceSlug: "milihenry", slug: "milihenrio", name: "Milihenrio",
    shortDescription: "El milihenrio es la milésima parte de un henrio.",
    historySummary: "Es el rango habitual de bobinas de filtros de audio y fuentes.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 mH = 0,001 H",
    commonUses: "Filtros de audio, fuentes y motores",
  },
  {
    sourceSlug: "mikrohenry", slug: "microhenrio", name: "Microhenrio",
    shortDescription: "El microhenrio es la millonésima parte de un henrio.",
    historySummary: "Se usa en bobinas de radiofrecuencia y convertidores de potencia.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 µH = 10⁻⁶ H",
    commonUses: "Radiofrecuencia y convertidores DC-DC",
  },
  {
    sourceSlug: "coulomb", slug: "culombio", name: "Culombio",
    shortDescription: "El culombio (C) es la unidad de carga eléctrica del SI: la carga que transporta 1 A en 1 s.",
    historySummary: "Honra a Charles-Augustin de Coulomb, que estudió la fuerza entre cargas eléctricas.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 C = 1 A·s",
    commonUses: "Física, electroquímica y baterías",
  },
  {
    sourceSlug: "milicoulomb", slug: "miliculombio", name: "Miliculombio",
    shortDescription: "El miliculombio es la milésima parte de un culombio.",
    historySummary: "Aparece en electroquímica y en la carga de condensadores.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 mC = 0,001 C",
    commonUses: "Condensadores y electroquímica",
  },
  {
    sourceSlug: "mikrocoulomb", slug: "microculombio", name: "Microculombio",
    shortDescription: "El microculombio es la millonésima parte de un culombio.",
    historySummary: "Es la escala de las cargas en problemas de electrostática.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 µC = 10⁻⁶ C",
    commonUses: "Electrostática y sensores",
  },
  {
    sourceSlug: "nanocoulomb", slug: "nanoculombio", name: "Nanoculombio",
    shortDescription: "El nanoculombio equivale a 10⁻⁹ culombios.",
    historySummary: "Se usa para cargas muy pequeñas, como las de descargas electrostáticas.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 nC = 10⁻⁹ C",
    commonUses: "Descargas electrostáticas y física",
  },

  // Magnetismo
  {
    sourceSlug: "amper-metre", slug: "amperio-por-metro", name: "Amperio por metro",
    shortDescription: "El A/m es la unidad de intensidad de campo magnético (H) del SI.",
    historySummary: "Describe el campo creado por corrientes eléctricas, independiente del material.",
    measurementSystem: SI_DERIVED, siEquivalent: "Unidad de campo magnético H del SI",
    commonUses: "Electromagnetismo, bobinas e imanes",
  },
  {
    sourceSlug: "kiloamper-metre", slug: "kiloamperio-por-metro", name: "Kiloamperio por metro",
    shortDescription: "El kA/m equivale a 1.000 A/m.",
    historySummary: "Se usa para campos intensos, como la coercitividad de imanes permanentes.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 kA/m = 1.000 A/m",
    commonUses: "Imanes permanentes y materiales magnéticos",
  },
  {
    sourceSlug: "oersted", slug: "oersted", name: "Oersted",
    shortDescription: "El oersted (Oe) es la unidad CGS de intensidad de campo magnético.",
    historySummary: "Honra a Hans Christian Ørsted, que descubrió en 1820 que la corriente eléctrica desvía una brújula.",
    measurementSystem: CGS, siEquivalent: "1 Oe ≈ 79,5775 A/m",
    commonUses: "Materiales magnéticos y grabación magnética",
  },
  {
    sourceSlug: "weber", slug: "weber", name: "Weber",
    shortDescription: "El weber (Wb) es la unidad de flujo magnético del SI.",
    historySummary: "Honra a Wilhelm Weber. Un tesla equivale a un weber por metro cuadrado.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 Wb = 1 V·s",
    commonUses: "Transformadores, motores y electromagnetismo",
  },
  {
    sourceSlug: "miliweber", slug: "miliweber", name: "Miliweber",
    shortDescription: "El miliweber es la milésima parte de un weber.",
    historySummary: "Es la escala del flujo en núcleos de transformadores pequeños.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 mWb = 0,001 Wb",
    commonUses: "Transformadores y motores",
  },
  {
    sourceSlug: "mikroweber", slug: "microweber", name: "Microweber",
    shortDescription: "El microweber es la millonésima parte de un weber.",
    historySummary: "Se usa en sensores magnéticos y bobinas pequeñas.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 µWb = 10⁻⁶ Wb",
    commonUses: "Sensores y bobinas",
  },
  {
    sourceSlug: "nanoweber", slug: "nanoweber", name: "Nanoweber",
    shortDescription: "El nanoweber equivale a 10⁻⁹ weber.",
    historySummary: "Aparece en medidas de laboratorio y en magnetometría.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 nWb = 10⁻⁹ Wb",
    commonUses: "Magnetometría y laboratorio",
  },

  // Transferencia de calor
  {
    sourceSlug: "watt-metre-kelvin", slug: "vatio-por-metro-kelvin", name: "Vatio por metro kelvin",
    shortDescription: "El W/(m·K) es la unidad de conductividad térmica del SI.",
    historySummary: "Un buen aislante tiene menos de 0,04 W/(m·K); el cobre, cerca de 400.",
    measurementSystem: SI_DERIVED, siEquivalent: "Unidad de conductividad térmica del SI",
    commonUses: "Aislamiento de edificios, disipadores y materiales",
  },
  {
    sourceSlug: "kilowatt-metre-kelvin", slug: "kilovatio-por-metro-kelvin", name: "Kilovatio por metro kelvin",
    shortDescription: "El kW/(m·K) equivale a 1.000 W/(m·K).",
    historySummary: "Solo materiales excepcionales como el diamante o el grafeno alcanzan estos valores.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 kW/(m·K) = 1.000 W/(m·K)",
    commonUses: "Materiales avanzados",
  },
  {
    sourceSlug: "watt-santimetre-kelvin", slug: "vatio-por-centimetro-kelvin", name: "Vatio por centímetro kelvin",
    shortDescription: "El W/(cm·K) equivale a 100 W/(m·K).",
    historySummary: "Aparece en la literatura de semiconductores y materiales.",
    measurementSystem: "Unidad métrica", siEquivalent: "1 W/(cm·K) = 100 W/(m·K)",
    commonUses: "Semiconductores y ciencia de materiales",
  },
  {
    sourceSlug: "btu-saat-fit-f", slug: "btu-por-hora-pie-fahrenheit", name: "BTU por hora pie °F",
    shortDescription: "La BTU/(h·ft·°F) es la unidad anglosajona de conductividad térmica.",
    historySummary: "Se usa en fichas de aislamiento y climatización de EE. UU.",
    measurementSystem: US, siEquivalent: "1 BTU/(h·ft·°F) ≈ 1,7307 W/(m·K)",
    commonUses: "Aislamiento y climatización en EE. UU.",
  },
  {
    sourceSlug: "watt-metrekare", slug: "vatio-por-metro-cuadrado", name: "Vatio por metro cuadrado",
    shortDescription: "El W/m² mide densidad de flujo de calor o de radiación.",
    historySummary: "La radiación solar en un día despejado ronda los 1.000 W/m² a nivel del suelo.",
    measurementSystem: SI_DERIVED, siEquivalent: "Unidad de flujo de calor del SI",
    commonUses: "Energía solar, pérdidas de calor y radiación",
  },
  {
    sourceSlug: "kilowatt-metrekare", slug: "kilovatio-por-metro-cuadrado", name: "Kilovatio por metro cuadrado",
    shortDescription: "El kW/m² equivale a 1.000 W/m².",
    historySummary: "Se usa en ensayos de fuego y en la irradiancia solar concentrada.",
    measurementSystem: SI_DERIVED, siEquivalent: "1 kW/m² = 1.000 W/m²",
    commonUses: "Ensayos de incendio y energía solar",
  },
  {
    sourceSlug: "kalori-santimetrekare-saniye", slug: "caloria-por-centimetro-cuadrado-segundo", name: "Caloría por cm² y segundo",
    shortDescription: "La cal/(cm²·s) es una unidad antigua de flujo de calor.",
    historySummary: "Aparece en textos antiguos de meteorología y transferencia de calor.",
    measurementSystem: CGS, siEquivalent: "1 cal/(cm²·s) = 41.840 W/m²",
    commonUses: "Textos científicos antiguos",
  },
  {
    sourceSlug: "joule-kilogram-kelvin", slug: "julio-por-kilogramo-kelvin", name: "Julio por kilogramo kelvin",
    shortDescription: "El J/(kg·K) es la unidad de calor específico del SI.",
    historySummary: "El agua tiene uno de los calores específicos más altos: unos 4.186 J/(kg·K).",
    measurementSystem: SI_DERIVED, siEquivalent: "Unidad de calor específico del SI",
    commonUses: "Termodinámica, calefacción y materiales",
  },
  {
    sourceSlug: "kilojoule-kilogram-kelvin", slug: "kilojulio-por-kilogramo-kelvin", name: "Kilojulio por kilogramo kelvin",
    shortDescription: "El kJ/(kg·K) equivale a 1.000 J/(kg·K).",
    historySummary: "Es la forma habitual en tablas de ingeniería: el agua tiene unos 4,19 kJ/(kg·K).",
    measurementSystem: SI_DERIVED, siEquivalent: "1 kJ/(kg·K) = 1.000 J/(kg·K)",
    commonUses: "Tablas de ingeniería y climatización",
  },
  {
    sourceSlug: "kalori-gram-kelvin", slug: "caloria-por-gramo-kelvin", name: "Caloría por gramo kelvin",
    shortDescription: "La cal/(g·K) es una unidad clásica de calor específico; el agua tiene 1 cal/(g·K).",
    historySummary: "La caloría se definió precisamente a partir del calentamiento del agua.",
    measurementSystem: CGS, siEquivalent: "1 cal/(g·K) = 4.184 J/(kg·K)",
    commonUses: "Química y enseñanza",
  },
  {
    sourceSlug: "btu-pound-fahrenhayt", slug: "btu-por-libra-fahrenheit", name: "BTU por libra °F",
    shortDescription: "La BTU/(lb·°F) es la unidad anglosajona de calor específico; el agua tiene 1 BTU/(lb·°F).",
    historySummary: "Numéricamente coincide con la cal/(g·K) porque ambas se basan en el agua.",
    measurementSystem: US, siEquivalent: "1 BTU/(lb·°F) = 4.186,8 J/(kg·K)",
    commonUses: "Ingeniería térmica en EE. UU.",
  },

  // Salud
  {
    sourceSlug: "miligram-desilitre", slug: "miligramo-por-decilitro", name: "Miligramo por decilitro",
    shortDescription: "El mg/dL es la unidad de glucosa en sangre usada en España, Latinoamérica y EE. UU.",
    historySummary: "Una glucemia en ayunas normal suele estar entre 70 y 100 mg/dL. Consulta siempre a tu médico.",
    measurementSystem: "Unidad clínica", siEquivalent: "1 mg/dL ≈ 0,0555 mmol/L (glucosa)",
    commonUses: "Glucómetros, análisis de sangre y diabetes",
  },
  {
    sourceSlug: "milimol-litre", slug: "milimol-por-litro", name: "Milimol por litro",
    shortDescription: "El mmol/L es la unidad de glucosa en sangre del Reino Unido, Canadá y muchos países europeos.",
    historySummary: "Para convertir glucosa de mmol/L a mg/dL se multiplica por unos 18.",
    measurementSystem: "Unidad clínica del SI", siEquivalent: "1 mmol/L ≈ 18,016 mg/dL (glucosa)",
    commonUses: "Glucómetros y análisis clínicos",
  },
  {
    sourceSlug: "nanogram-mililitre", slug: "nanogramo-por-mililitro", name: "Nanogramo por mililitro",
    shortDescription: "El ng/mL es la unidad más usada para la vitamina D (25-OH) en los análisis de sangre.",
    historySummary: "Muchos laboratorios consideran suficientes valores de 30 ng/mL o más; tu médico interpretará el resultado.",
    measurementSystem: "Unidad clínica", siEquivalent: "1 ng/mL ≈ 2,496 nmol/L (vitamina D)",
    commonUses: "Análisis de vitamina D",
  },
  {
    sourceSlug: "nanomol-litre", slug: "nanomol-por-litro", name: "Nanomol por litro",
    shortDescription: "El nmol/L es la unidad del SI para la vitamina D en sangre.",
    historySummary: "Se usa en el Reino Unido, Australia y parte de Europa; 75 nmol/L equivalen a unos 30 ng/mL.",
    measurementSystem: "Unidad clínica del SI", siEquivalent: "1 nmol/L ≈ 0,4006 ng/mL (vitamina D)",
    commonUses: "Análisis de vitamina D",
  },
];
