// বাংলা একক পৃষ্ঠা -- নতুন i18n সিস্টেমের সাথে সংযুক্ত করার জন্য
// স্বাধীন, নতুন ফাইল। প্রতিটি বিভাগ থেকে সবচেয়ে গুরুত্বপূর্ণ ১-২টি একক
// দিয়ে শুরু করা হয়েছে (সম্পূর্ণ ১৫০+ একক নয় -- সম্প্রসারণ পরবর্তী ধাপ)।

export type LocalizedBengaliUnitPage = {
  locale: "bn";
  sourceSlug: string;
  slug: string;
  category: string;
  categoryName: string;
  unit: string;
  name: string;
  symbol: string;
  shortDescription: string;
  historySummary: string;
  measurementSystem: string;
  siEquivalent: string;
  commonUses: string;
};

export const bengaliUnitPages: LocalizedBengaliUnitPage[] = [
  {
    locale: "bn",
    sourceSlug: "metre",
    slug: "meter",
    category: "uzunluk",
    categoryName: "দৈর্ঘ্য",
    unit: "m",
    name: "মিটার",
    symbol: "m",
    shortDescription: "মিটার হলো দৈর্ঘ্যের আন্তর্জাতিক SI মৌলিক একক।",
    historySummary:
      "১৯৮৩ সাল থেকে মিটারকে আলো শূন্যস্থানে ১/২৯৯৭৯২৪৫৮ সেকেন্ডে যে দূরত্ব অতিক্রম করে তার ভিত্তিতে সুনির্দিষ্টভাবে সংজ্ঞায়িত করা হয়েছে।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI)",
    siEquivalent: "দৈর্ঘ্যের মৌলিক SI একক",
    commonUses: "নির্মাণ, খেলাধুলা, বিজ্ঞান এবং দৈনন্দিন দূরত্ব পরিমাপ",
  },
  {
    locale: "bn",
    sourceSlug: "kilometre",
    slug: "kilometer",
    category: "uzunluk",
    categoryName: "দৈর্ঘ্য",
    unit: "km",
    name: "কিলোমিটার",
    symbol: "km",
    shortDescription: "কিলোমিটার সমান ১০০০ মিটার এবং শহরের মধ্যবর্তী দূরত্ব প্রকাশে ব্যবহৃত হয়।",
    historySummary:
      "মেট্রিক পদ্ধতির দশমিক কাঠামোর মধ্যে কিলোমিটার মিটারের গুণিতক হিসেবে প্রতিষ্ঠিত হয়েছে এবং সড়ক ও মানচিত্রে মানক একক হয়ে উঠেছে।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, গুণিতক একক)",
    siEquivalent: "১ km = ১০০০ m",
    commonUses: "সড়ক দূরত্ব, ভূগোল, মানচিত্রায়ন এবং অবকাঠামো",
  },
  {
    locale: "bn",
    sourceSlug: "metrekare",
    slug: "borgomiter",
    category: "alan",
    categoryName: "ক্ষেত্রফল",
    unit: "m²",
    name: "বর্গমিটার",
    symbol: "m²",
    shortDescription: "বর্গমিটার হলো ক্ষেত্রফলের SI মৌলিক একক, প্রতিটি বাহু এক মিটার দৈর্ঘ্যের বর্গক্ষেত্রের ক্ষেত্রফলের সমান।",
    historySummary: "মেট্রিক পদ্ধতির প্রবর্তনের পর থেকেই বর্গমিটার নির্মাণ ও ভূমি পরিমাপের মানক একক হয়ে দাঁড়িয়েছে।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI)",
    siEquivalent: "ক্ষেত্রফলের মৌলিক SI একক",
    commonUses: "ভবনের আয়তন, জমির ক্ষেত্রফল এবং নির্মাণ পরিকল্পনা",
  },
  {
    locale: "bn",
    sourceSlug: "hektar",
    slug: "hector",
    category: "alan",
    categoryName: "ক্ষেত্রফল",
    unit: "ha",
    name: "হেক্টর",
    symbol: "ha",
    shortDescription: "হেক্টর একটি বৃহৎ ক্ষেত্রফল একক, ১০,০০০ বর্গমিটারের সমান, মূলত কৃষি জমি পরিমাপে ব্যবহৃত হয়।",
    historySummary: "কৃষি ও ভূমি ব্যবস্থাপনায় বড় জমির ক্ষেত্রফল সহজে প্রকাশের জন্য হেক্টর ব্যাপকভাবে গৃহীত হয়েছে।",
    measurementSystem: "মেট্রিক পদ্ধতি (SI-এর বাইরে, প্রচলিত একক)",
    siEquivalent: "১ ha = ১০,০০০ m²",
    commonUses: "কৃষি জমি, বনভূমি এবং ভূমি নিবন্ধন",
  },
  {
    locale: "bn",
    sourceSlug: "litre",
    slug: "liter",
    category: "hacim",
    categoryName: "আয়তন",
    unit: "L",
    name: "লিটার",
    symbol: "L",
    shortDescription: "লিটার হলো তরল পরিমাপের সবচেয়ে প্রচলিত একক, এক ঘন ডেসিমিটারের সমান।",
    historySummary: "মেট্রিক পদ্ধতির প্রবর্তনের পর থেকে লিটার দৈনন্দিন জীবনে তরল পরিমাপের মানক একক হয়ে উঠেছে।",
    measurementSystem: "মেট্রিক পদ্ধতি (SI-এর বাইরে, প্রচলিত একক)",
    siEquivalent: "১ L = ০.০০১ m³",
    commonUses: "পানীয়, রান্না এবং জ্বালানি পরিমাপ",
  },
  {
    locale: "bn",
    sourceSlug: "metrekup",
    slug: "ghonomiter",
    category: "hacim",
    categoryName: "আয়তন",
    unit: "m³",
    name: "ঘনমিটার",
    symbol: "m³",
    shortDescription: "ঘনমিটার হলো আয়তনের SI মৌলিক একক, প্রতিটি বাহু এক মিটার দৈর্ঘ্যের ঘনকের আয়তনের সমান।",
    historySummary: "বৃহৎ আয়তনের হিসাবে, যেমন পানি সরবরাহ ও নির্মাণে, ঘনমিটার মানক একক হিসেবে প্রতিষ্ঠিত।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI)",
    siEquivalent: "আয়তনের মৌলিক SI একক",
    commonUses: "পানি সরবরাহ, নির্মাণ এবং শিল্প পরিমাপ",
  },
  {
    locale: "bn",
    sourceSlug: "kilogram",
    slug: "kilogram",
    category: "kutle",
    categoryName: "ভর",
    unit: "kg",
    name: "কিলোগ্রাম",
    symbol: "kg",
    shortDescription: "কিলোগ্রাম হলো ভরের SI মৌলিক একক এবং দৈনন্দিন জীবনে সবচেয়ে বেশি ব্যবহৃত ওজন একক।",
    historySummary: "২০১৯ সাল থেকে কিলোগ্রামকে প্ল্যাংক ধ্রুবকের ভিত্তিতে সুনির্দিষ্টভাবে সংজ্ঞায়িত করা হয়েছে, পূর্বে এটি একটি ভৌত মানদণ্ডের উপর নির্ভরশীল ছিল।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI)",
    siEquivalent: "ভরের মৌলিক SI একক",
    commonUses: "খাদ্য, শিপিং, চিকিৎসা এবং দৈনন্দিন ওজন পরিমাপ",
  },
  {
    locale: "bn",
    sourceSlug: "gram",
    slug: "gram",
    category: "kutle",
    categoryName: "ভর",
    unit: "g",
    name: "গ্রাম",
    symbol: "g",
    shortDescription: "গ্রাম কিলোগ্রামের হাজার ভাগের এক ভাগ এবং ছোট পরিমাণের ভর প্রকাশে ব্যবহৃত হয়।",
    historySummary: "রান্না, ওষুধ এবং স্বর্ণ ব্যবসায় ছোট ও নির্ভুল পরিমাপের জন্য গ্রাম ব্যাপকভাবে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, উপ-একক)",
    siEquivalent: "১ g = ০.০০১ kg",
    commonUses: "রান্নার উপকরণ, ওষুধের ডোজ এবং স্বর্ণের ওজন",
  },
  {
    locale: "bn",
    sourceSlug: "santigrat",
    slug: "celsius",
    category: "sicaklik",
    categoryName: "তাপমাত্রা",
    unit: "°C",
    name: "সেলসিয়াস",
    symbol: "°C",
    shortDescription: "সেলসিয়াস স্কেলে পানি ০ ডিগ্রিতে জমে এবং ১০০ ডিগ্রিতে ফুটে; এটি বিশ্বব্যাপী সবচেয়ে প্রচলিত তাপমাত্রা একক।",
    historySummary: "১৭৪২ সালে অ্যান্ডার্স সেলসিয়াস এই স্কেল প্রবর্তন করেন, যা পরে বিশ্বজুড়ে দৈনন্দিন ও বৈজ্ঞানিক ব্যবহারে গৃহীত হয়।",
    measurementSystem: "মেট্রিক পদ্ধতি (SI-স্বীকৃত)",
    siEquivalent: "K = °C + ২৭৩.১৫",
    commonUses: "আবহাওয়া, রান্না এবং দৈনন্দিন তাপমাত্রা পরিমাপ",
  },
  {
    locale: "bn",
    sourceSlug: "kelvin",
    slug: "kelvin",
    category: "sicaklik",
    categoryName: "তাপমাত্রা",
    unit: "K",
    name: "কেলভিন",
    symbol: "K",
    shortDescription: "কেলভিন হলো তাপমাত্রার SI মৌলিক একক, যেখানে শূন্য কেলভিন পরম শূন্য তাপমাত্রা নির্দেশ করে।",
    historySummary: "কেলভিন স্কেলে কোনো ঋণাত্মক মান নেই বলে এটি বৈজ্ঞানিক গবেষণা ও তাপগতিবিদ্যায় ব্যাপকভাবে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI)",
    siEquivalent: "তাপমাত্রার মৌলিক SI একক",
    commonUses: "বৈজ্ঞানিক গবেষণা, পদার্থবিজ্ঞান এবং তাপগতিবিদ্যা",
  },
  {
    locale: "bn",
    sourceSlug: "saniye",
    slug: "second",
    category: "zaman",
    categoryName: "সময়",
    unit: "s",
    name: "সেকেন্ড",
    symbol: "s",
    shortDescription: "সেকেন্ড হলো সময়ের SI মৌলিক একক এবং সমস্ত সময়ভিত্তিক পরিমাপের ভিত্তি।",
    historySummary: "সেকেন্ড বর্তমানে সিজিয়াম-১৩৩ পরমাণুর নির্দিষ্ট সংখ্যক কম্পনের ভিত্তিতে অত্যন্ত সুনির্দিষ্টভাবে সংজ্ঞায়িত।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI)",
    siEquivalent: "সময়ের মৌলিক SI একক",
    commonUses: "বৈজ্ঞানিক পরিমাপ, খেলাধুলা এবং দৈনন্দিন সময়সূচি",
  },
  {
    locale: "bn",
    sourceSlug: "saat",
    slug: "ghonta",
    category: "zaman",
    categoryName: "সময়",
    unit: "h",
    name: "ঘণ্টা",
    symbol: "h",
    shortDescription: "ঘণ্টা সমান ৬০ মিনিট এবং দৈনন্দিন সময়সূচি ও পরিকল্পনায় সবচেয়ে বেশি ব্যবহৃত সময় একক।",
    historySummary: "প্রাচীন ব্যাবিলনীয় ষাটভিত্তিক সংখ্যাপদ্ধতি থেকে ঘণ্টার ধারণা এসেছে এবং আজও বিশ্বজুড়ে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI-স্বীকৃত, প্রচলিত একক)",
    siEquivalent: "১ h = ৩৬০০ s",
    commonUses: "কর্মঘণ্টা, ভ্রমণ পরিকল্পনা এবং দৈনন্দিন সময়সূচি",
  },
  {
    locale: "bn",
    sourceSlug: "kilometre-saat",
    slug: "kilometer-protiy-ghonta",
    category: "hiz",
    categoryName: "গতি",
    unit: "km/h",
    name: "কিলোমিটার প্রতি ঘণ্টা",
    symbol: "km/h",
    shortDescription: "কিলোমিটার প্রতি ঘণ্টা হলো সড়ক পরিবহনে সবচেয়ে প্রচলিত গতি একক।",
    historySummary: "মেট্রিক পদ্ধতিতে সড়ক পরিবহনের সম্প্রসারণের সাথে সাথে কিমি/ঘণ্টা বিশ্বের অধিকাংশ দেশে গতিসীমার মানক একক হয়ে উঠেছে।",
    measurementSystem: "মেট্রিক পদ্ধতি (প্রচলিত একক)",
    siEquivalent: "১ km/h ≈ ০.২৭৮ m/s",
    commonUses: "গাড়ির গতিসীমা, ট্র্যাফিক এবং সড়ক পরিবহন",
  },
  {
    locale: "bn",
    sourceSlug: "pascal",
    slug: "pascal",
    category: "basinc",
    categoryName: "চাপ",
    unit: "Pa",
    name: "প্যাসকেল",
    symbol: "Pa",
    shortDescription: "প্যাসকেল হলো চাপের SI মৌলিক একক, প্রতি বর্গমিটারে এক নিউটন বলের সমান।",
    historySummary: "ব্লেইজ প্যাসকেলের নামে নামকরণ করা এই একক তরল যন্ত্রবিজ্ঞান ও আবহাওয়াবিদ্যায় ব্যাপকভাবে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI)",
    siEquivalent: "চাপের মৌলিক SI একক",
    commonUses: "আবহাওয়াবিদ্যা, প্রকৌশল এবং তরল যন্ত্রবিজ্ঞান",
  },
  {
    locale: "bn",
    sourceSlug: "joule",
    slug: "joule",
    category: "enerji",
    categoryName: "শক্তি",
    unit: "J",
    name: "জুল",
    symbol: "J",
    shortDescription: "জুল হলো শক্তির SI মৌলিক একক এবং কাজ, তাপ ও শক্তির পরিমাপে ব্যবহৃত হয়।",
    historySummary: "জেমস প্রেসকট জুলের নামে নামকরণ করা এই একক শক্তি বিজ্ঞানে এক গুরুত্বপূর্ণ ভিত্তি স্থাপন করেছে।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI)",
    siEquivalent: "শক্তির মৌলিক SI একক",
    commonUses: "পদার্থবিজ্ঞান, প্রকৌশল এবং শক্তি হিসাব",
  },
  {
    locale: "bn",
    sourceSlug: "bayt",
    slug: "byte",
    category: "veri",
    categoryName: "ডেটা স্টোরেজ",
    unit: "B",
    name: "বাইট",
    symbol: "B",
    shortDescription: "বাইট ৮ বিট নিয়ে গঠিত এবং কম্পিউটার প্রযুক্তিতে স্টোরেজ ক্ষমতার মৌলিক একক।",
    historySummary: "কম্পিউটার সিস্টেমে অক্ষর ও ডেটা প্রকাশের মানক একক হিসেবে বাইট প্রতিষ্ঠিত হয়েছে।",
    measurementSystem: "ডিজিটাল ডেটা একক (মৌলিক একক)",
    siEquivalent: "১ বাইট = ৮ বিট",
    commonUses: "ফাইলের আকার এবং স্টোরেজ ক্ষমতা প্রকাশ",
  },
  {
    locale: "bn",
    sourceSlug: "volt",
    slug: "volt",
    category: "elektrik",
    categoryName: "বিদ্যুৎ",
    unit: "V",
    name: "ভোল্ট",
    symbol: "V",
    shortDescription: "ভোল্ট হলো বৈদ্যুতিক বিভব পার্থক্যের SI মৌলিক একক।",
    historySummary: "আলেসান্দ্রো ভোল্টার নামে নামকরণ করা এই একক আধুনিক বিদ্যুৎ প্রকৌশলের ভিত্তি স্থাপন করেছে।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI)",
    siEquivalent: "বৈদ্যুতিক বিভবের মৌলিক SI একক",
    commonUses: "গৃহস্থালি বিদ্যুৎ, ইলেকট্রনিক্স এবং ব্যাটারি স্পেসিফিকেশন",
  },
  {
    locale: "bn",
    sourceSlug: "amper",
    slug: "ampere",
    category: "elektrik",
    categoryName: "বিদ্যুৎ",
    unit: "A",
    name: "অ্যাম্পিয়ার",
    symbol: "A",
    shortDescription: "অ্যাম্পিয়ার হলো তড়িৎ প্রবাহের SI মৌলিক একক।",
    historySummary: "আঁদ্রে-মারি আম্পেয়ারের নামে নামকরণ করা এই একক তড়িৎ প্রকৌশলের একটি মৌলিক ভিত্তি।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI)",
    siEquivalent: "তড়িৎ প্রবাহের মৌলিক SI একক",
    commonUses: "বৈদ্যুতিক বর্তনী, ফিউজ রেটিং এবং ইলেকট্রনিক্স",
  },
  {
    locale: "bn",
    sourceSlug: "24-ayar-altin",
    slug: "24-carat-gold",
    category: "altin_ayar",
    categoryName: "স্বর্ণের ক্যারেট",
    unit: "24K",
    name: "২৪ ক্যারেট স্বর্ণ",
    symbol: "24K",
    shortDescription: "২৪ ক্যারেট বলতে বিশুদ্ধ স্বর্ণ বোঝায়, যাতে অন্য কোনো ধাতু মেশানো থাকে না, অর্থাৎ ৯৯.৯% বিশুদ্ধতা।",
    historySummary: "সবচেয়ে বিশুদ্ধ প্রচলিত স্বর্ণের রূপ হিসেবে এটি মূলত বার ও বিনিয়োগ মুদ্রায় ব্যবহৃত হয়।",
    measurementSystem: "ক্যারেট পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "৯৯৯/১০০০ বিশুদ্ধ স্বর্ণ",
    commonUses: "স্বর্ণের বার, বিনিয়োগ মুদ্রা এবং মূল্য সংরক্ষণ",
  },
  {
    locale: "bn",
    sourceSlug: "santimetre",
    slug: "centimeter",
    category: "uzunluk",
    categoryName: "দৈর্ঘ্য",
    unit: "cm",
    name: "সেন্টিমিটার",
    symbol: "cm",
    shortDescription: "সেন্টিমিটার মিটারের একশ ভাগের এক ভাগের সমান দৈর্ঘ্যের একক।",
    historySummary: "দৈনন্দিন পরিমাপ ও ছোট বস্তুর জন্য ব্যাপকভাবে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, উপ-একক)",
    siEquivalent: "১ cm = ০.০১ m",
    commonUses: "আসবাবপত্র, পোশাক, দৈনন্দিন পরিমাপ",
  },
  {
    locale: "bn",
    sourceSlug: "milimetre",
    slug: "millimeter",
    category: "uzunluk",
    categoryName: "দৈর্ঘ্য",
    unit: "mm",
    name: "মিলিমিটার",
    symbol: "mm",
    shortDescription: "মিলিমিটার মিটারের হাজার ভাগের এক ভাগের সমান, প্রযুক্তিগত পরিমাপে ব্যবহৃত হয়।",
    historySummary: "শিল্প ও প্রকৌশলে ছোট সহনশীলতা পরিমাপের প্রয়োজনে ব্যাপকভাবে প্রচলিত হয়েছে।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, উপ-একক)",
    siEquivalent: "১ mm = ০.০০১ m",
    commonUses: "উৎপাদন, নকশা মানদণ্ড",
  },
  {
    locale: "bn",
    sourceSlug: "mikrometre",
    slug: "micrometer",
    category: "uzunluk",
    categoryName: "দৈর্ঘ্য",
    unit: "µm",
    name: "মাইক্রোমিটার",
    symbol: "µm",
    shortDescription: "মাইক্রোমিটার মিটারের দশ লক্ষ ভাগের এক ভাগের সমান, অতি ক্ষুদ্র পরিমাপে ব্যবহৃত হয়।",
    historySummary: "উপাদান বিজ্ঞান ও সেমিকন্ডাক্টর প্রযুক্তিতে মূল একক হিসেবে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, উপ-একক)",
    siEquivalent: "১ µm = ০.০০০০০১ m",
    commonUses: "উপাদান বিজ্ঞান, সেমিকন্ডাক্টর প্রযুক্তি",
  },
  {
    locale: "bn",
    sourceSlug: "nanometre",
    slug: "nanometer",
    category: "uzunluk",
    categoryName: "দৈর্ঘ্য",
    unit: "nm",
    name: "ন্যানোমিটার",
    symbol: "nm",
    shortDescription: "ন্যানোমিটার মিটারের একশ কোটি ভাগের এক ভাগের সমান, পরমাণু ও অণু পরিমাপে ব্যবহৃত হয়।",
    historySummary: "পদার্থবিজ্ঞান, রসায়ন এবং আধুনিক ন্যানো প্রযুক্তিতে মৌলিক একক।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, উপ-একক)",
    siEquivalent: "১ nm = ০.০০০০০০০০১ m",
    commonUses: "ন্যানো প্রযুক্তি, আলোর তরঙ্গদৈর্ঘ্য",
  },
  {
    locale: "bn",
    sourceSlug: "fit",
    slug: "foot",
    category: "uzunluk",
    categoryName: "দৈর্ঘ্য",
    unit: "ft",
    name: "ফুট",
    symbol: "ft",
    shortDescription: "ফুট যুক্তরাষ্ট্র ও যুক্তরাজ্যে ব্যাপকভাবে ব্যবহৃত ঐতিহ্যবাহী দৈর্ঘ্যের একক।",
    historySummary: "প্রাচীন রোমান ও ইংরেজি পরিমাপ পদ্ধতি থেকে উদ্ভূত, আজও নির্মাণে ব্যবহৃত হয়।",
    measurementSystem: "ইম্পেরিয়াল/মার্কিন পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "১ ফুট ≈ ০.৩০৪৮ m",
    commonUses: "নির্মাণ, ভবনের উচ্চতা, মার্কিন পরিমাপ",
  },
  {
    locale: "bn",
    sourceSlug: "inc",
    slug: "inch",
    category: "uzunluk",
    categoryName: "দৈর্ঘ্য",
    unit: "in",
    name: "ইঞ্চি",
    symbol: "in",
    shortDescription: "ইঞ্চি স্ক্রিনের আকার প্রকাশে ব্যাপকভাবে ব্যবহৃত ছোট দৈর্ঘ্যের একক।",
    historySummary: "ঐতিহাসিকভাবে বুড়ো আঙুলের প্রস্থের উপর ভিত্তি করে তৈরি, এখন সুনির্দিষ্ট মেট্রিক মান রয়েছে।",
    measurementSystem: "ইম্পেরিয়াল/মার্কিন পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "১ ইঞ্চি = ২.৫৪ cm",
    commonUses: "স্ক্রিনের আকার, ইলেকট্রনিক্স, মার্কিন শিল্প",
  },
  {
    locale: "bn",
    sourceSlug: "yarda",
    slug: "yard",
    category: "uzunluk",
    categoryName: "দৈর্ঘ্য",
    unit: "yd",
    name: "গজ",
    symbol: "yd",
    shortDescription: "গজ যুক্তরাষ্ট্র ও যুক্তরাজ্যে কাপড় ও খেলার মাঠ পরিমাপে ব্যবহৃত হয়।",
    historySummary: "ঐতিহাসিকভাবে পদক্ষেপের দৈর্ঘ্যের উপর ভিত্তি করে, এখন আমেরিকান ফুটবল মাঠে মানক পরিমাপ।",
    measurementSystem: "ইম্পেরিয়াল/মার্কিন পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "১ গজ ≈ ০.৯১৪৪ m",
    commonUses: "খেলার মাঠ, কাপড়ের পরিমাপ",
  },
  {
    locale: "bn",
    sourceSlug: "mil",
    slug: "mile",
    category: "uzunluk",
    categoryName: "দৈর্ঘ্য",
    unit: "mi",
    name: "মাইল",
    symbol: "mi",
    shortDescription: "মাইল যুক্তরাষ্ট্র ও যুক্তরাজ্যে সড়ক দূরত্ব পরিমাপে ব্যাপকভাবে ব্যবহৃত দৈর্ঘ্যের একক।",
    historySummary: "রোমান সৈনিকদের পদক্ষেপ থেকে উদ্ভূত, এখন ইংরেজি পরিমাপ পদ্ধতিতে প্রমিত।",
    measurementSystem: "ইম্পেরিয়াল/মার্কিন পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "১ মাইল ≈ ১.৬০৯ km",
    commonUses: "সড়ক দূরত্ব, যুক্তরাষ্ট্র ও যুক্তরাজ্য নেভিগেশন",
  },
  {
    locale: "bn",
    sourceSlug: "deniz-mili",
    slug: "nautical-mile",
    category: "uzunluk",
    categoryName: "দৈর্ঘ্য",
    unit: "nmi",
    name: "নটিক্যাল মাইল",
    symbol: "nmi",
    shortDescription: "নটিক্যাল মাইল সমুদ্র ও বিমান নেভিগেশনে ব্যবহৃত, পৃথিবীর পরিধির উপর ভিত্তি করে দৈর্ঘ্যের একক।",
    historySummary: "পৃথিবীর বৃহৎ বৃত্তে এক আর্কমিনিটের সমান, আন্তর্জাতিক নেভিগেশন একক।",
    measurementSystem: "SI-এর বাইরে, আন্তর্জাতিক নেভিগেশন একক",
    siEquivalent: "১ নটিক্যাল মাইল = ১৮৫২ m",
    commonUses: "সমুদ্র ও বিমান নেভিগেশন",
  },
  {
    locale: "bn",
    sourceSlug: "arsin",
    slug: "arshin",
    category: "uzunluk",
    categoryName: "দৈর্ঘ্য",
    unit: "arşın",
    name: "আরশিন",
    symbol: "আরশিন",
    shortDescription: "আরশিন উসমানীয় যুগে দৈনন্দিন জীবনে ও বাণিজ্যে ব্যবহৃত ঐতিহ্যবাহী দৈর্ঘ্যের একক।",
    historySummary: "২০ শতকে মেট্রিক পদ্ধতি চালু হওয়ার আগ পর্যন্ত উসমানীয় সাম্রাজ্যে মানক পরিমাপ একক ছিল।",
    measurementSystem: "SI-এর বাইরে, ঐতিহাসিক উসমানীয় একক",
    siEquivalent: "১ আরশিন ≈ ০.৬৮ m",
    commonUses: "ঐতিহাসিক নথি ও উসমানীয় যুগের গবেষণা",
  },
  {
    locale: "bn",
    sourceSlug: "endaze",
    slug: "endaze",
    category: "uzunluk",
    categoryName: "দৈর্ঘ্য",
    unit: "endaze",
    name: "এন্দাজে",
    symbol: "এন্দাজে",
    shortDescription: "এন্দাজে উসমানীয় যুগে প্রধানত কাপড় ব্যবসায় ব্যবহৃত দৈর্ঘ্যের একক।",
    historySummary: "আরশিনের চেয়ে কিছুটা ছোট ছিল এবং কাপড় পরিমাপে ব্যবহৃত হতো।",
    measurementSystem: "SI-এর বাইরে, ঐতিহাসিক উসমানীয় একক",
    siEquivalent: "১ এন্দাজে ≈ ০.৬৫ m",
    commonUses: "ঐতিহাসিক কাপড় ব্যবসা ও গবেষণা",
  },
  {
    locale: "bn",
    sourceSlug: "bizans-ayagi",
    slug: "byzantine-foot",
    category: "uzunluk",
    categoryName: "দৈর্ঘ্য",
    unit: "pus",
    name: "বাইজেন্টাইন ফুট",
    symbol: "pus",
    shortDescription: "বাইজেন্টাইন ফুট বাইজেন্টাইন সাম্রাজ্যে ভবন ও জমি পরিমাপে ব্যবহৃত দৈর্ঘ্যের একক।",
    historySummary: "আধুনিক পরিমাপ পদ্ধতি চালু হওয়ার আগে বাইজেন্টাইন স্থাপত্যে ব্যবহৃত হতো।",
    measurementSystem: "SI-এর বাইরে, বাইজেন্টাইন ঐতিহাসিক একক",
    siEquivalent: "১ pus ≈ ০.৩১৪৮ m",
    commonUses: "বাইজেন্টাইন স্থাপত্য ও ঐতিহাসিক গবেষণা",
  },
  {
    locale: "bn",
    sourceSlug: "bizans-kulaci",
    slug: "byzantine-fathom",
    category: "uzunluk",
    categoryName: "দৈর্ঘ্য",
    unit: "orgyia",
    name: "বাইজেন্টাইন ফ্যাদম",
    symbol: "orgyia",
    shortDescription: "বাইজেন্টাইন ফ্যাদম মানুষের হাত বিস্তৃতির প্রায় সমান বড় দৈর্ঘ্যের একক।",
    historySummary: "বাইজেন্টাইন সাম্রাজ্যে বড় দূরত্ব ও জমি পরিমাপে ব্যবহৃত হতো।",
    measurementSystem: "SI-এর বাইরে, বাইজেন্টাইন ঐতিহাসিক একক",
    siEquivalent: "১ orgyia ≈ ১.৮৮৮৮ m",
    commonUses: "বাইজেন্টাইন জমি জরিপ ও ঐতিহাসিক নথি",
  },
  {
    locale: "bn",
    sourceSlug: "cig",
    slug: "cig",
    category: "uzunluk",
    categoryName: "দৈর্ঘ্য",
    unit: "çığ",
    name: "চিগ",
    symbol: "চিগ",
    shortDescription: "চিগ প্রাচীন তুর্কি উৎসে পাওয়া একটি দৈর্ঘ্যের একক।",
    historySummary: "কাশগরি মাহমুদের দিভানু লুগাতিত-তুর্ক গ্রন্থের ভিত্তিতে এর মান প্রায় ৩৩.৩ সেন্টিমিটার নির্ধারণ করা হয়েছে।",
    measurementSystem: "SI-এর বাইরে, প্রাচীন তুর্কি ঐতিহাসিক একক",
    siEquivalent: "১ চিগ ≈ ০.৩৩৩ m",
    commonUses: "প্রাচীন তুর্কি পরিমাপ একক গবেষণা",
  },
  {
    locale: "bn",
    sourceSlug: "santimetrekare",
    slug: "square-centimeter",
    category: "alan",
    categoryName: "ক্ষেত্রফল",
    unit: "cm²",
    name: "বর্গ সেন্টিমিটার",
    symbol: "cm²",
    shortDescription: "বর্গ সেন্টিমিটার ছোট ক্ষেত্রফল পরিমাপে ব্যবহৃত একক।",
    historySummary: "প্রযুক্তিগত অঙ্কন ও ছোট বস্তুর ক্ষেত্রফল প্রকাশে ব্যাপকভাবে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, উপ-একক)",
    siEquivalent: "১ cm² = ০.০০০১ m²",
    commonUses: "প্রযুক্তিগত অঙ্কন, কাপড় ও ছোট ক্ষেত্রফল",
  },
  {
    locale: "bn",
    sourceSlug: "milimetrekare",
    slug: "square-millimeter",
    category: "alan",
    categoryName: "ক্ষেত্রফল",
    unit: "mm²",
    name: "বর্গ মিলিমিটার",
    symbol: "mm²",
    shortDescription: "বর্গ মিলিমিটার অত্যন্ত ছোট ক্ষেত্রফল নির্ভুলভাবে পরিমাপে ব্যবহৃত হয়।",
    historySummary: "ইলেকট্রনিক্স ও নির্ভুল উৎপাদনে ক্রস-সেকশন প্রকাশে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, উপ-একক)",
    siEquivalent: "১ mm² = ০.০০০০০১ m²",
    commonUses: "ইলেকট্রনিক্স প্রযুক্তি, নির্ভুল উৎপাদন",
  },
  {
    locale: "bn",
    sourceSlug: "kilometrekare",
    slug: "square-kilometer",
    category: "alan",
    categoryName: "ক্ষেত্রফল",
    unit: "km²",
    name: "বর্গ কিলোমিটার",
    symbol: "km²",
    shortDescription: "বর্গ কিলোমিটার দেশ, শহর ও বড় ভৌগোলিক এলাকার ক্ষেত্রফল পরিমাপে ব্যবহৃত হয়।",
    historySummary: "ভূগোল ও পরিসংখ্যানে বড় ভূমি এলাকা প্রকাশে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, গুণিতক)",
    siEquivalent: "১ km² = ১০,০০,০০০ m²",
    commonUses: "ভূগোল, মানচিত্রায়ন, এলাকা পরিসংখ্যান",
  },
  {
    locale: "bn",
    sourceSlug: "fitkare",
    slug: "square-foot",
    category: "alan",
    categoryName: "ক্ষেত্রফল",
    unit: "ft²",
    name: "বর্গ ফুট",
    symbol: "ft²",
    shortDescription: "বর্গ ফুট যুক্তরাষ্ট্রে বাড়ি ও নির্মাণ ক্ষেত্রফল পরিমাপে ব্যাপকভাবে ব্যবহৃত হয়।",
    historySummary: "মার্কিন রিয়েল এস্টেট ও নির্মাণ শিল্পে মানক ক্ষেত্রফল একক।",
    measurementSystem: "ইম্পেরিয়াল/মার্কিন পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "১ ft² ≈ ০.০৯২৯ m²",
    commonUses: "মার্কিন রিয়েল এস্টেট ও নির্মাণ হিসাব",
  },
  {
    locale: "bn",
    sourceSlug: "incare",
    slug: "square-inch",
    category: "alan",
    categoryName: "ক্ষেত্রফল",
    unit: "in²",
    name: "বর্গ ইঞ্চি",
    symbol: "in²",
    shortDescription: "বর্গ ইঞ্চি ছোট ক্ষেত্রফল পরিমাপে ব্যবহৃত একটি ঐতিহ্যবাহী একক।",
    historySummary: "মার্কিন শিল্প ও ইলেকট্রনিক্স স্পেসিফিকেশনে প্রায়শই দেখা যায়।",
    measurementSystem: "ইম্পেরিয়াল/মার্কিন পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "১ in² ≈ ৬.৪৫১৬ cm²",
    commonUses: "মার্কিন শিল্প স্পেসিফিকেশন, ছোট স্ক্রিন",
  },
  {
    locale: "bn",
    sourceSlug: "akre",
    slug: "acre",
    category: "alan",
    categoryName: "ক্ষেত্রফল",
    unit: "ac",
    name: "একর",
    symbol: "ac",
    shortDescription: "একর যুক্তরাষ্ট্র ও যুক্তরাজ্যে কৃষি জমি ও সম্পত্তি পরিমাপে ব্যবহৃত বড় ক্ষেত্রফল একক।",
    historySummary: "মধ্যযুগ থেকে উদ্ভূত, মূলত একজোড়া বলদ একদিনে যে জমি চাষ করতে পারত তার সমান ছিল।",
    measurementSystem: "ইম্পেরিয়াল/মার্কিন পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "১ একর ≈ ৪০৪৬.৮৬ m²",
    commonUses: "যুক্তরাষ্ট্র ও যুক্তরাজ্যে সম্পত্তি ও কৃষি জমি",
  },
  {
    locale: "bn",
    sourceSlug: "donum",
    slug: "donum",
    category: "alan",
    categoryName: "ক্ষেত্রফল",
    unit: "dönüm",
    name: "দোনুম",
    symbol: "দোনুম",
    shortDescription: "দোনুম তুরস্ক ও মধ্যপ্রাচ্যে কৃষি জমি পরিমাপে ব্যবহৃত আঞ্চলিক ক্ষেত্রফল একক।",
    historySummary: "উসমানীয় যুগ থেকে চলে আসছে এবং আজও তুরস্কের গ্রামীণ এলাকায় ব্যবহারিক ক্ষেত্রফল একক হিসেবে ব্যবহৃত হয়।",
    measurementSystem: "SI-এর বাইরে, আঞ্চলিক একক",
    siEquivalent: "১ দোনুম = ১০০০ m²",
    commonUses: "তুরস্ক ও মধ্যপ্রাচ্যে কৃষি জমি",
  },
  {
    locale: "bn",
    sourceSlug: "dekar",
    slug: "decare",
    category: "alan",
    categoryName: "ক্ষেত্রফল",
    unit: "dekar",
    name: "ডেকার",
    symbol: "ডেকার",
    shortDescription: "ডেকার ১০০০ বর্গমিটারের সমান, বলকান ও পূর্ব ভূমধ্যসাগরীয় অঞ্চলে ব্যাপক প্রচলিত আঞ্চলিক একক।",
    historySummary: "মেট্রিক পদ্ধতি থেকে উদ্ভূত, কিছু প্রতিবেশী অঞ্চলে দোনুমের বিকল্প স্থানীয় একক হিসেবে ব্যবহৃত হয়।",
    measurementSystem: "SI-এর বাইরে, আঞ্চলিক একক",
    siEquivalent: "১ ডেকার = ১০০০ m²",
    commonUses: "বলকান অঞ্চলে কৃষি জমি",
  },
  {
    locale: "bn",
    sourceSlug: "mililitre",
    slug: "milliliter",
    category: "hacim",
    categoryName: "আয়তন",
    unit: "mL",
    name: "মিলিলিটার",
    symbol: "mL",
    shortDescription: "মিলিলিটার লিটারের হাজার ভাগের এক ভাগের সমান ছোট আয়তন একক।",
    historySummary: "চিকিৎসা ডোজ ও ল্যাবরেটরি পরিমাপে ব্যাপকভাবে ব্যবহৃত হয়।",
    measurementSystem: "মেট্রিক পদ্ধতি (SI-এর বাইরে, উপ-একক)",
    siEquivalent: "১ mL = ০.০০০০০১ m³",
    commonUses: "চিকিৎসা ডোজ, ল্যাবরেটরি, রান্নার পরিমাপ",
  },
  {
    locale: "bn",
    sourceSlug: "santimetrekup",
    slug: "cubic-centimeter",
    category: "hacim",
    categoryName: "আয়তন",
    unit: "cm³",
    name: "ঘন সেন্টিমিটার",
    symbol: "cm³",
    shortDescription: "ঘন সেন্টিমিটার মিলিলিটারের সাথে সম্পূর্ণ সমান একটি ছোট আয়তন একক।",
    historySummary: "চিকিৎসা, রসায়ন ও গাড়ির ইঞ্জিন আয়তন প্রকাশে ব্যাপকভাবে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, উপ-একক)",
    siEquivalent: "১ cm³ = ১ mL = ০.০০০০০১ m³",
    commonUses: "গাড়ির ইঞ্জিন আয়তন, চিকিৎসা ডোজ",
  },
  {
    locale: "bn",
    sourceSlug: "fitkup",
    slug: "cubic-foot",
    category: "hacim",
    categoryName: "আয়তন",
    unit: "ft³",
    name: "ঘন ফুট",
    symbol: "ft³",
    shortDescription: "ঘন ফুট মার্কিন নির্মাণ ও শীতাতপ প্রযুক্তিতে ব্যবহৃত ঐতিহ্যবাহী আয়তন একক।",
    historySummary: "মার্কিন শীতাতপ ও বায়ুচলাচল সরঞ্জাম স্পেসিফিকেশনে মানক হিসেবে গণ্য।",
    measurementSystem: "ইম্পেরিয়াল/মার্কিন পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "১ ft³ ≈ ০.০২৮৩ m³",
    commonUses: "মার্কিন শীতাতপ প্রযুক্তি ও নির্মাণ হিসাব",
  },
  {
    locale: "bn",
    sourceSlug: "inckup",
    slug: "cubic-inch",
    category: "hacim",
    categoryName: "আয়তন",
    unit: "in³",
    name: "ঘন ইঞ্চি",
    symbol: "in³",
    shortDescription: "ঘন ইঞ্চি পুরনো মার্কিন গাড়ির ইঞ্জিন আয়তন প্রকাশে ব্যবহৃত ছোট আয়তন একক।",
    historySummary: "ক্লাসিক আমেরিকান মাসল কার ইঞ্জিন শ্রেণীবিভাগে ঐতিহাসিক মানদণ্ড ছিল।",
    measurementSystem: "ইম্পেরিয়াল/মার্কিন পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "১ in³ ≈ ১৬.৩৯ cm³",
    commonUses: "ক্লাসিক মার্কিন গাড়ির ইঞ্জিন শ্রেণীবিভাগ",
  },
  {
    locale: "bn",
    sourceSlug: "galon",
    slug: "gallon",
    category: "hacim",
    categoryName: "আয়তন",
    unit: "gal",
    name: "গ্যালন",
    symbol: "gal",
    shortDescription: "গ্যালন যুক্তরাষ্ট্র ও যুক্তরাজ্যে তরল পরিমাপে ব্যাপকভাবে ব্যবহৃত ঐতিহ্যবাহী আয়তন একক।",
    historySummary: "মার্কিন গ্যালন ও ইম্পেরিয়াল গ্যালনের মান ভিন্ন, উভয়ই ঐতিহাসিক ইংরেজি পরিমাপ পদ্ধতি থেকে উদ্ভূত।",
    measurementSystem: "ইম্পেরিয়াল/মার্কিন পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "১ মার্কিন গ্যালন ≈ ৩.৭৮৫ লিটার",
    commonUses: "জ্বালানি ও তরল পরিমাণ যুক্তরাষ্ট্র ও যুক্তরাজ্যে",
  },
  {
    locale: "bn",
    sourceSlug: "varil",
    slug: "barrel",
    category: "hacim",
    categoryName: "আয়তন",
    unit: "bbl",
    name: "ব্যারেল",
    symbol: "bbl",
    shortDescription: "ব্যারেল আন্তর্জাতিক তেল বাণিজ্যে ব্যবহৃত মানসম্মত আয়তন একক।",
    historySummary: "মার্কিন তেল শিল্পের প্রথম দিক থেকে অপরিশোধিত তেল বাণিজ্যের বিশ্ব মানদণ্ড হয়ে উঠেছে।",
    measurementSystem: "SI-এর বাইরে, আন্তর্জাতিক বাণিজ্য একক",
    siEquivalent: "১ ব্যারেল ≈ ১৫৮.৯৮৭ লিটার",
    commonUses: "বিশ্বব্যাপী অপরিশোধিত তেল বাণিজ্য",
  },
  {
    locale: "bn",
    sourceSlug: "miligram",
    slug: "milligram",
    category: "kutle",
    categoryName: "ভর",
    unit: "mg",
    name: "মিলিগ্রাম",
    symbol: "mg",
    shortDescription: "মিলিগ্রাম গ্রামের হাজার ভাগের এক ভাগের সমান অত্যন্ত ছোট ভর একক।",
    historySummary: "ওষুধ ও নির্ভুল ল্যাবরেটরি পরিমাপে ব্যাপকভাবে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, উপ-একক)",
    siEquivalent: "১ mg = ০.০০০০০১ kg",
    commonUses: "ওষুধের ডোজ, ল্যাবরেটরি পরিমাপ",
  },
  {
    locale: "bn",
    sourceSlug: "ton",
    slug: "tonne",
    category: "kutle",
    categoryName: "ভর",
    unit: "t",
    name: "টন",
    symbol: "t",
    shortDescription: "টন ১০০০ কিলোগ্রামের সমান বড় ভর একক, শিপিং ও শিল্পে ব্যবহৃত হয়।",
    historySummary: "শিপিং ও শিল্প উৎপাদনে বড় ভর প্রকাশে ব্যাপকভাবে ব্যবহৃত হয়।",
    measurementSystem: "মেট্রিক পদ্ধতি (SI-এর বাইরে, গুণিতক)",
    siEquivalent: "১ t = ১০০০ kg",
    commonUses: "শিপিং, শিল্প উৎপাদন",
  },
  {
    locale: "bn",
    sourceSlug: "pound",
    slug: "pound",
    category: "kutle",
    categoryName: "ভর",
    unit: "lb",
    name: "পাউন্ড",
    symbol: "lb",
    shortDescription: "পাউন্ড যুক্তরাষ্ট্র ও যুক্তরাজ্যে দৈনন্দিন ওজন পরিমাপে ব্যাপকভাবে ব্যবহৃত ভর একক।",
    historySummary: "রোমান লিব্রা একক থেকে উদ্ভূত, এখন ইংরেজি-মার্কিন পদ্ধতিতে প্রমিত।",
    measurementSystem: "ইম্পেরিয়াল/মার্কিন পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "১ পাউন্ড ≈ ০.৪৫৩৬ kg",
    commonUses: "যুক্তরাষ্ট্র ও যুক্তরাজ্যে দৈনন্দিন ওজন পরিমাপ",
  },
  {
    locale: "bn",
    sourceSlug: "ons",
    slug: "ounce",
    category: "kutle",
    categoryName: "ভর",
    unit: "oz",
    name: "আউন্স",
    symbol: "oz",
    shortDescription: "আউন্স ছোট ভর, বিশেষত খাদ্য ও মূল্যবান ধাতু পরিমাপে ব্যবহৃত হয়।",
    historySummary: "রোমান আনসিয়া একক থেকে উদ্ভূত, এখনও যুক্তরাষ্ট্রে রান্না ও গহনা পরিমাপে ব্যবহৃত হয়।",
    measurementSystem: "ইম্পেরিয়াল/মার্কিন পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "১ আউন্স ≈ ২৮.৩৫ g",
    commonUses: "রান্নার রেসিপি, মূল্যবান ধাতু",
  },
  {
    locale: "bn",
    sourceSlug: "okka",
    slug: "okka",
    category: "kutle",
    categoryName: "ভর",
    unit: "okka",
    name: "ওক্কা",
    symbol: "ওক্কা",
    shortDescription: "ওক্কা উসমানীয় যুগে দৈনন্দিন জীবনে ও বাণিজ্যে ব্যাপকভাবে ব্যবহৃত ভর একক।",
    historySummary: "২০ শতকে মেট্রিক পদ্ধতি চালু হওয়ার আগ পর্যন্ত উসমানীয় সাম্রাজ্যে ওজনের মানক একক ছিল।",
    measurementSystem: "SI-এর বাইরে, ঐতিহাসিক উসমানীয় একক",
    siEquivalent: "১ ওক্কা ≈ ১.২৮৩ kg",
    commonUses: "ঐতিহাসিক বাণিজ্য ও উসমানীয় যুগের গবেষণা",
  },
  {
    locale: "bn",
    sourceSlug: "dirhem",
    slug: "dirham",
    category: "kutle",
    categoryName: "ভর",
    unit: "dirhem",
    name: "দিরহাম",
    symbol: "দিরহাম",
    shortDescription: "দিরহাম উসমানীয় যুগে প্রধানত মূল্যবান ধাতু ও মসলার জন্য ব্যবহৃত ছোট ভর একক।",
    historySummary: "ওক্কার উপ-একক ছিল, উসমানীয় বাণিজ্যে ছোট ওজন সঠিকভাবে প্রকাশ করতে ব্যবহৃত হতো।",
    measurementSystem: "SI-এর বাইরে, ঐতিহাসিক উসমানীয় একক",
    siEquivalent: "১ দিরহাম ≈ ৩.২০৭ g",
    commonUses: "ঐতিহাসিক মূল্যবান ধাতু ও মসলা বাণিজ্য",
  },
  {
    locale: "bn",
    sourceSlug: "bizans-litrasi",
    slug: "byzantine-litra",
    category: "kutle",
    categoryName: "ভর",
    unit: "litra",
    name: "বাইজেন্টাইন লিত্রা",
    symbol: "litra",
    shortDescription: "বাইজেন্টাইন লিত্রা বাইজেন্টাইন সাম্রাজ্যে ব্যবহৃত, রোমান পাউন্ডের অনুরূপ ভর একক।",
    historySummary: "উসমানীয় বিজয়ের আগে বাইজেন্টাইন বাণিজ্য ও স্বর্ণশিল্পে ব্যবহৃত হতো।",
    measurementSystem: "SI-এর বাইরে, বাইজেন্টাইন ঐতিহাসিক একক",
    siEquivalent: "১ litra ≈ ০.৩২৪ kg",
    commonUses: "বাইজেন্টাইন বাণিজ্য ও ঐতিহাসিক গবেষণা",
  },
  {
    locale: "bn",
    sourceSlug: "bizans-onsu",
    slug: "byzantine-ounce",
    category: "kutle",
    categoryName: "ভর",
    unit: "ounkia",
    name: "বাইজেন্টাইন আউন্স",
    symbol: "ounkia",
    shortDescription: "আউন্কিয়া বাইজেন্টাইন লিত্রার বারো ভাগের এক ভাগের সমান ছোট ভর একক।",
    historySummary: "বাইজেন্টাইন দৈনন্দিন বাণিজ্যে ছোট পরিমাণ ওজন করতে ব্যবহৃত হতো।",
    measurementSystem: "SI-এর বাইরে, বাইজেন্টাইন ঐতিহাসিক একক",
    siEquivalent: "১ ounkia ≈ ২৭ g",
    commonUses: "বাইজেন্টাইন দৈনন্দিন বাণিজ্য ও ঐতিহাসিক গবেষণা",
  },
  {
    locale: "bn",
    sourceSlug: "kilogram-metrekup",
    slug: "kilogram-per-cubic-meter",
    category: "yogunluk",
    categoryName: "ঘনত্ব",
    unit: "kg/m³",
    name: "কিলোগ্রাম/ঘনমিটার",
    symbol: "kg/m³",
    shortDescription: "কিলোগ্রাম/ঘনমিটার ঘনত্বের SI মৌলিক একক, ভর ও আয়তনের অনুপাত প্রকাশ করে।",
    historySummary: "বিজ্ঞান ও প্রকৌশলে ঘনত্ব প্রকাশের আন্তর্জাতিক প্রমিত মৌলিক একক।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, মৌলিক একক)",
    siEquivalent: "ঘনত্বের মৌলিক SI একক",
    commonUses: "উপাদান বিজ্ঞান, পদার্থবিজ্ঞান, প্রযুক্তিগত হিসাব",
  },
  {
    locale: "bn",
    sourceSlug: "gram-santimetrekup",
    slug: "gram-per-cubic-centimeter",
    category: "yogunluk",
    categoryName: "ঘনত্ব",
    unit: "g/cm³",
    name: "গ্রাম/ঘনসেন্টিমিটার",
    symbol: "g/cm³",
    shortDescription: "গ্রাম/ঘনসেন্টিমিটার রসায়ন ও ল্যাবরেটরি চর্চায় ব্যাপকভাবে ব্যবহৃত ব্যবহারিক ঘনত্ব একক।",
    historySummary: "পানি ও অন্যান্য সাধারণ পদার্থের ঘনত্ব সুবিধাজনক সংখ্যায় প্রকাশ করার জন্য ব্যবহৃত হয়।",
    measurementSystem: "মেট্রিক পদ্ধতি (SI উপ-একক)",
    siEquivalent: "১ g/cm³ = ১০০০ kg/m³",
    commonUses: "রসায়ন, উপাদান বিজ্ঞান, ল্যাবরেটরি কাজ",
  },
  {
    locale: "bn",
    sourceSlug: "metre-saniye",
    slug: "meter-per-second",
    category: "hiz",
    categoryName: "গতি",
    unit: "m/s",
    name: "মিটার/সেকেন্ড",
    symbol: "m/s",
    shortDescription: "মিটার/সেকেন্ড গতির SI মৌলিক একক, বিজ্ঞান ও প্রযুক্তিতে ব্যবহৃত হয়।",
    historySummary: "পদার্থবিজ্ঞান হিসাবে গতি প্রকাশের আন্তর্জাতিক প্রমিত একক।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, মৌলিক একক)",
    siEquivalent: "গতির মৌলিক SI একক",
    commonUses: "পদার্থবিজ্ঞান, প্রযুক্তি, বৈজ্ঞানিক হিসাব",
  },
  {
    locale: "bn",
    sourceSlug: "mil-saat",
    slug: "mile-per-hour",
    category: "hiz",
    categoryName: "গতি",
    unit: "mph",
    name: "মাইল/ঘণ্টা",
    symbol: "mph",
    shortDescription: "মাইল/ঘণ্টা যুক্তরাষ্ট্র ও যুক্তরাজ্যে সড়ক পরিবহনে ব্যবহৃত গতি একক।",
    historySummary: "মার্কিন ও ব্রিটিশ স্পিডোমিটার ও রাস্তার চিহ্নে মানক।",
    measurementSystem: "ইম্পেরিয়াল/মার্কিন পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "১ mph ≈ ১.৬০৯ km/ঘণ্টা",
    commonUses: "যুক্তরাষ্ট্র ও যুক্তরাজ্যে সড়ক পরিবহন",
  },
  {
    locale: "bn",
    sourceSlug: "knot",
    slug: "knot",
    category: "hiz",
    categoryName: "গতি",
    unit: "knot",
    name: "নট",
    symbol: "নট",
    shortDescription: "নট সমুদ্র ও বিমান নেভিগেশনে ব্যবহৃত, এক নটিক্যাল মাইল/ঘণ্টার সমান গতি একক।",
    historySummary: "গিঁট বাঁধা দড়ি দিয়ে জাহাজের গতি পরিমাপের ঐতিহাসিক পদ্ধতি থেকে নামটি এসেছে।",
    measurementSystem: "SI-এর বাইরে, আন্তর্জাতিক নেভিগেশন একক",
    siEquivalent: "১ নট ≈ ০.৫১৪৪ m/s",
    commonUses: "সমুদ্র ও বিমান নেভিগেশন, বাতাসের গতি",
  },
  {
    locale: "bn",
    sourceSlug: "isik-hizi",
    slug: "speed-of-light",
    category: "hiz",
    categoryName: "গতি",
    unit: "c",
    name: "আলোর গতি",
    symbol: "c",
    shortDescription: "আলোর গতি শূন্যস্থানে আলো যে গতিতে ভ্রমণ করে তা প্রকাশ করে, একটি মৌলিক প্রাকৃতিক ধ্রুবক।",
    historySummary: "এখন সুনির্দিষ্টভাবে সংজ্ঞায়িত এবং মিটারের আধুনিক সংজ্ঞার ভিত্তি তৈরি করে।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, প্রাকৃতিক ধ্রুবক)",
    siEquivalent: "পদার্থবিজ্ঞান ও জ্যোতির্বিজ্ঞানের মৌলিক ধ্রুবক",
    commonUses: "পদার্থবিজ্ঞান, জ্যোতির্বিজ্ঞান, মিটারের সংজ্ঞা",
  },
  {
    locale: "bn",
    sourceSlug: "metre-saniyekare",
    slug: "meter-per-second-squared",
    category: "ivme",
    categoryName: "ত্বরণ",
    unit: "m/s²",
    name: "মিটার/সেকেন্ড²",
    symbol: "m/s²",
    shortDescription: "মিটার/সেকেন্ড² ত্বরণের SI মৌলিক একক।",
    historySummary: "পদার্থবিজ্ঞান ও প্রযুক্তিতে ত্বরণ প্রকাশের আন্তর্জাতিক প্রমিত একক।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, মৌলিক একক)",
    siEquivalent: "ত্বরণের মৌলিক SI একক",
    commonUses: "পদার্থবিজ্ঞান, যানবাহন প্রযুক্তি, বৈজ্ঞানিক হিসাব",
  },
  {
    locale: "bn",
    sourceSlug: "fit-saniyekare",
    slug: "foot-per-second-squared",
    category: "ivme",
    categoryName: "ত্বরণ",
    unit: "ft/s²",
    name: "ফুট/সেকেন্ড²",
    symbol: "ft/s²",
    shortDescription: "ফুট/সেকেন্ড² যুক্তরাষ্ট্রে ব্যবহৃত ইংরেজি-আমেরিকান ত্বরণ একক।",
    historySummary: "মার্কিন প্রযুক্তি ও বিমান শিল্পে মেট্রিক এককের পরিবর্তে ব্যবহৃত হয়।",
    measurementSystem: "ইম্পেরিয়াল/মার্কিন পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "১ ft/s² ≈ ০.৩০৪৮ m/s²",
    commonUses: "মার্কিন প্রযুক্তি ও বিমান হিসাব",
  },
  {
    locale: "bn",
    sourceSlug: "yercekimi-ivmesi",
    slug: "gravitational-acceleration",
    category: "ivme",
    categoryName: "ত্বরণ",
    unit: "g0",
    name: "অভিকর্ষজ ত্বরণ (g)",
    symbol: "g",
    shortDescription: "অভিকর্ষজ ত্বরণ পৃথিবীর পৃষ্ঠের কাছে মুক্তভাবে পড়া বস্তুর প্রমিত ত্বরণ।",
    historySummary: "৯.৮০৬৬৫ m/s² প্রমিত মান আন্তর্জাতিকভাবে নির্ধারিত এবং ব্যবহারিক তুলনামূলক একক হিসেবে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, প্রমিত ধ্রুবক)",
    siEquivalent: "পদার্থবিজ্ঞান ও মহাকাশ গবেষণার প্রমিত ধ্রুবক",
    commonUses: "পদার্থবিজ্ঞান, মহাকাশ গবেষণা, ত্বরণ তুলনা",
  },
  {
    locale: "bn",
    sourceSlug: "dakika",
    slug: "minute",
    category: "zaman",
    categoryName: "সময়",
    unit: "min",
    name: "মিনিট",
    symbol: "min",
    shortDescription: "মিনিট ৬০ সেকেন্ডের সমান, দৈনন্দিন সময় হিসাবে ব্যাপকভাবে ব্যবহৃত সময়ের একক।",
    historySummary: "প্রাচীন ব্যাবিলনীয় ষাটভিত্তিক সংখ্যাপদ্ধতি থেকে উদ্ভূত, আজও বিশ্বব্যাপী ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI-এর বাইরে, প্রচলিত)",
    siEquivalent: "১ মিনিট = ৬০ s",
    commonUses: "দৈনন্দিন সময়সূচি, খেলাধুলা, বিজ্ঞান",
  },
  {
    locale: "bn",
    sourceSlug: "gun",
    slug: "day",
    category: "zaman",
    categoryName: "সময়",
    unit: "day",
    name: "দিন",
    symbol: "দিন",
    shortDescription: "দিন একটি সম্পূর্ণ পৃথিবীর আবর্তনের সময়ের সমান সময়ের একক।",
    historySummary: "মানুষের ব্যবহৃত প্রাচীনতম সময়ের এককগুলোর একটি, যা বিশ্বব্যাপী ক্যালেন্ডারের ভিত্তি তৈরি করে।",
    measurementSystem: "SI-এর বাইরে, প্রচলিত সময় একক",
    siEquivalent: "১ দিন = ৮৬,৪০০ s",
    commonUses: "ক্যালেন্ডার, দৈনন্দিন পরিকল্পনা, সময় হিসাব",
  },
  {
    locale: "bn",
    sourceSlug: "radyan-saniye",
    slug: "radian-per-second",
    category: "acisal_hiz",
    categoryName: "কৌণিক বেগ",
    unit: "rad/s",
    name: "রেডিয়ান/সেকেন্ড",
    symbol: "rad/s",
    shortDescription: "রেডিয়ান/সেকেন্ড কৌণিক বেগের SI মৌলিক একক।",
    historySummary: "পদার্থবিজ্ঞান ও যন্ত্রপ্রকৌশলে ঘূর্ণন গতি নির্ভুলভাবে প্রকাশে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, মৌলিক একক)",
    siEquivalent: "কৌণিক বেগের মৌলিক SI একক",
    commonUses: "যন্ত্রপ্রকৌশল, রোবোটিক্স, ঘূর্ণন পদার্থবিজ্ঞান",
  },
  {
    locale: "bn",
    sourceSlug: "devir-dakika",
    slug: "revolutions-per-minute",
    category: "acisal_hiz",
    categoryName: "কৌণিক বেগ",
    unit: "rpm",
    name: "আবর্তন/মিনিট (RPM)",
    symbol: "rpm",
    shortDescription: "RPM মোটর ও ঘূর্ণায়মান যন্ত্রের গতি প্রকাশে ব্যাপকভাবে ব্যবহৃত একক।",
    historySummary: "মোটর ও ডিস্কের ঘূর্ণন গতি প্রদর্শনে মানক ব্যবহারিক একক।",
    measurementSystem: "SI-এর বাইরে, প্রচলিত প্রযুক্তিগত একক",
    siEquivalent: "SI-এর বাইরে, প্রযুক্তিগত ব্যবহারিক একক",
    commonUses: "মোটরের গতি, যন্ত্রপ্রকৌশল, ডিস্ক গতি",
  },
  {
    locale: "bn",
    sourceSlug: "derece-saniye",
    slug: "degree-per-second",
    category: "acisal_hiz",
    categoryName: "কৌণিক বেগ",
    unit: "°/s",
    name: "ডিগ্রি/সেকেন্ড",
    symbol: "°/s",
    shortDescription: "ডিগ্রি/সেকেন্ড কোণ-ভিত্তিক সহজবোধ্য গতি একক।",
    historySummary: "রোবোটিক্স ও সেন্সর প্রযুক্তিতে ডিগ্রি মান রেডিয়ানের চেয়ে বেশি সহজবোধ্য বলে ব্যবহৃত হয়।",
    measurementSystem: "SI-এর বাইরে, প্রচলিত একক",
    siEquivalent: "১ °/s = π/১৮০ rad/s",
    commonUses: "রোবোটিক্স, সেন্সর প্রযুক্তি",
  },
  {
    locale: "bn",
    sourceSlug: "radyan",
    slug: "radian",
    category: "aci",
    categoryName: "কোণ",
    unit: "rad",
    name: "রেডিয়ান",
    symbol: "rad",
    shortDescription: "রেডিয়ান সমতল কোণের SI একক, চাপের দৈর্ঘ্য ও ব্যাসার্ধের অনুপাতের উপর ভিত্তি করে।",
    historySummary: "গণিত ও পদার্থবিজ্ঞানে ডিগ্রির চেয়ে বেশি পছন্দনীয় কোণ একক।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, ডেরাইভড একক)",
    siEquivalent: "১ সম্পূর্ণ বৃত্ত = ২π রেডিয়ান",
    commonUses: "গণিত, পদার্থবিজ্ঞান, প্রযুক্তিগত হিসাব",
  },
  {
    locale: "bn",
    sourceSlug: "derece",
    slug: "degree",
    category: "aci",
    categoryName: "কোণ",
    unit: "°",
    name: "ডিগ্রি",
    symbol: "°",
    shortDescription: "ডিগ্রি দৈনন্দিন জীবনে সবচেয়ে বেশি ব্যবহৃত কোণ একক, একটি সম্পূর্ণ বৃত্ত ৩৬০ ডিগ্রির সমান।",
    historySummary: "৩৬০ ভাগে বিভাজন ব্যাবিলনীয় জ্যোতির্বিজ্ঞান থেকে এসেছে এবং আজও বিশ্বব্যাপী ব্যবহৃত হয়।",
    measurementSystem: "SI-এর বাইরে, বিশ্বব্যাপী প্রচলিত একক",
    siEquivalent: "১ সম্পূর্ণ বৃত্ত = ৩৬০°",
    commonUses: "জ্যামিতি, নেভিগেশন, দৈনন্দিন কোণ প্রকাশ",
  },
  {
    locale: "bn",
    sourceSlug: "gradyan",
    slug: "gradian",
    category: "aci",
    categoryName: "কোণ",
    unit: "gon",
    name: "গ্রেড",
    symbol: "gon",
    shortDescription: "গ্রেড একটি সম্পূর্ণ বৃত্তকে ৪০০ ভাগে ভাগ করে, প্রধানত জিওডেসিতে ব্যবহৃত হয়।",
    historySummary: "মেট্রিক পদ্ধতি প্রবর্তনের সময় কোণকে দশমিকভাবে ভাগ করার জন্য তৈরি করা হয়েছিল।",
    measurementSystem: "SI-এর বাইরে, জিওডেটিক একক",
    siEquivalent: "১ সম্পূর্ণ বৃত্ত = ৪০০ gon",
    commonUses: "ভূমি জরিপ ও জিওডেটিক হিসাব",
  },
  {
    locale: "bn",
    sourceSlug: "tam-tur",
    slug: "full-turn",
    category: "aci",
    categoryName: "কোণ",
    unit: "tur",
    name: "সম্পূর্ণ আবর্তন",
    symbol: "আবর্তন",
    shortDescription: "সম্পূর্ণ আবর্তন একটি বিন্দুর চারপাশে একটি সম্পূর্ণ ঘূর্ণনের সমান, অর্থাৎ পূর্ণ ৩৬০ ডিগ্রি।",
    historySummary: "একটি অক্ষের চারপাশে এক বা একাধিক সম্পূর্ণ ঘূর্ণন বর্ণনা করতে ব্যবহৃত একটি সহজবোধ্য কোণ একক।",
    measurementSystem: "SI-এর বাইরে, ব্যবহারিক একক",
    siEquivalent: "১ আবর্তন = ৩৬০° = ২π রেডিয়ান",
    commonUses: "যান্ত্রিক ঘূর্ণন গতি বর্ণনা",
  },
  {
    locale: "bn",
    sourceSlug: "hertz",
    slug: "hertz",
    category: "frekans",
    categoryName: "কম্পাঙ্ক",
    unit: "Hz",
    name: "হার্জ",
    symbol: "Hz",
    shortDescription: "হার্জ কম্পাঙ্কের SI একক, সেকেন্ডে কম্পনের সংখ্যা প্রকাশ করে।",
    historySummary: "হাইনরিখ হার্জের নামে নামকরণ, তড়িৎ প্রকৌশল ও শব্দবিজ্ঞানে মৌলিক কম্পাঙ্ক একক।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, মৌলিক একক)",
    siEquivalent: "কম্পাঙ্কের মৌলিক SI একক",
    commonUses: "তড়িৎ প্রকৌশল, শব্দবিজ্ঞান, সংকেত প্রক্রিয়াকরণ",
  },
  {
    locale: "bn",
    sourceSlug: "kilohertz",
    slug: "kilohertz",
    category: "frekans",
    categoryName: "কম্পাঙ্ক",
    unit: "kHz",
    name: "কিলোহার্জ",
    symbol: "kHz",
    shortDescription: "কিলোহার্জ ১০০০ হার্জের সমান, মধ্যম কম্পাঙ্কের অডিও সংকেতে ব্যবহৃত হয়।",
    historySummary: "রেডিও কম্পাঙ্ক ও অডিও স্যাম্পলিং হার প্রকাশে ব্যাপকভাবে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, গুণিতক)",
    siEquivalent: "১ kHz = ১০০০ Hz",
    commonUses: "রেডিও কম্পাঙ্ক, অডিও প্রযুক্তি",
  },
  {
    locale: "bn",
    sourceSlug: "megahertz",
    slug: "megahertz",
    category: "frekans",
    categoryName: "কম্পাঙ্ক",
    unit: "MHz",
    name: "মেগাহার্জ",
    symbol: "MHz",
    shortDescription: "মেগাহার্জ দশ লক্ষ হার্জের সমান, বেতার তরঙ্গ ও প্রসেসর কম্পাঙ্কে ব্যবহৃত হয়।",
    historySummary: "সম্প্রচার কম্পাঙ্ক ও পুরনো কম্পিউটার প্রসেসরের গতি প্রকাশে মানক।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, গুণিতক)",
    siEquivalent: "১ MHz = ১০,০০,০০০ Hz",
    commonUses: "সম্প্রচার কম্পাঙ্ক, প্রসেসর প্রযুক্তি",
  },
  {
    locale: "bn",
    sourceSlug: "gigahertz",
    slug: "gigahertz",
    category: "frekans",
    categoryName: "কম্পাঙ্ক",
    unit: "GHz",
    name: "গিগাহার্জ",
    symbol: "GHz",
    shortDescription: "গিগাহার্জ একশ কোটি হার্জের সমান, আধুনিক প্রসেসর কম্পাঙ্কে ব্যবহৃত একক।",
    historySummary: "আধুনিক কম্পিউটার প্রসেসর ও বেতার যোগাযোগ ব্যবস্থার কম্পাঙ্ক প্রকাশে মানক।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, গুণিতক)",
    siEquivalent: "১ GHz = ১০০,০০,০০,০০০ Hz",
    commonUses: "প্রসেসর প্রযুক্তি, বেতার যোগাযোগ",
  },
  {
    locale: "bn",
    sourceSlug: "newton",
    slug: "newton",
    category: "kuvvet",
    categoryName: "বল",
    unit: "N",
    name: "নিউটন",
    symbol: "N",
    shortDescription: "নিউটন বলের SI একক, আইজ্যাক নিউটনের নামে নামকরণ করা হয়েছে।",
    historySummary: "পদার্থবিজ্ঞান ও প্রযুক্তিতে বল প্রকাশের বিশ্বব্যাপী মৌলিক একক।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, ডেরাইভড একক)",
    siEquivalent: "বলের মৌলিক SI একক",
    commonUses: "পদার্থবিজ্ঞান, যন্ত্রপ্রকৌশল, প্রযুক্তিগত হিসাব",
  },
  {
    locale: "bn",
    sourceSlug: "kilogram-kuvvet",
    slug: "kilogram-force",
    category: "kuvvet",
    categoryName: "বল",
    unit: "kgf",
    name: "কিলোগ্রাম-বল",
    symbol: "kgf",
    shortDescription: "কিলোগ্রাম-বল এক কিলোগ্রাম ভরের প্রমিত অভিকর্ষজ বলের সমান ঐতিহ্যবাহী একক।",
    historySummary: "SI পদ্ধতি সম্পূর্ণ প্রমিতকরণের আগে ব্যবহৃত হতো, এখনও পুরনো প্রযুক্তিগত নথিতে দেখা যায়।",
    measurementSystem: "SI-এর বাইরে, ঐতিহ্যবাহী একক",
    siEquivalent: "১ kgf ≈ ৯.৮০৬৬৫ N",
    commonUses: "পুরনো প্রযুক্তিগত স্পেসিফিকেশন ও প্রকৌশল",
  },
  {
    locale: "bn",
    sourceSlug: "newton-metre",
    slug: "newton-meter",
    category: "tork",
    categoryName: "টর্ক",
    unit: "N·m",
    name: "নিউটন-মিটার",
    symbol: "N·m",
    shortDescription: "নিউটন-মিটার টর্কের SI একক, বোল্ট সংযোগ ও মোটরে ব্যবহৃত হয়।",
    historySummary: "যানবাহন প্রযুক্তি ও প্রকৌশলে টর্ক প্রকাশের আন্তর্জাতিক মানদণ্ড।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, ডেরাইভড একক)",
    siEquivalent: "টর্কের মৌলিক SI একক",
    commonUses: "যানবাহন প্রযুক্তি, বোল্ট সংযোগ, যন্ত্রপ্রকৌশল",
  },
  {
    locale: "bn",
    sourceSlug: "kilogram-kuvvet-metre",
    slug: "kilogram-force-meter",
    category: "tork",
    categoryName: "টর্ক",
    unit: "kgf·m",
    name: "কিলোগ্রাম-বল-মিটার",
    symbol: "kgf·m",
    shortDescription: "কিলোগ্রাম-বল-মিটার পুরনো প্রযুক্তিগত ম্যানুয়ালে এখনও পাওয়া যায় এমন ঐতিহ্যবাহী টর্ক একক।",
    historySummary: "নিউটন-মিটারে সম্পূর্ণ রূপান্তরের আগে অনেক দেশে ব্যবহৃত হতো।",
    measurementSystem: "SI-এর বাইরে, ঐতিহ্যবাহী একক",
    siEquivalent: "১ kgf·m ≈ ৯.৮০৬৬৫ N·m",
    commonUses: "পুরনো প্রযুক্তিগত ম্যানুয়াল ও প্রকৌশল",
  },
  {
    locale: "bn",
    sourceSlug: "pound-fit",
    slug: "pound-foot",
    category: "tork",
    categoryName: "টর্ক",
    unit: "lb·ft",
    name: "পাউন্ড-ফুট",
    symbol: "lb·ft",
    shortDescription: "পাউন্ড-ফুট যুক্তরাষ্ট্রে মোটর ও যন্ত্রপাতির জন্য ব্যবহৃত ইংরেজি-আমেরিকান টর্ক একক।",
    historySummary: "মার্কিন যানবাহন ও যন্ত্রপাতি স্পেসিফিকেশনে টর্ক প্রকাশের মানদণ্ড।",
    measurementSystem: "ইম্পেরিয়াল/মার্কিন পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "১ lb·ft ≈ ১.৩৫৫৮ N·m",
    commonUses: "মার্কিন যানবাহন প্রযুক্তি ও যন্ত্রপাতি",
  },
  {
    locale: "bn",
    sourceSlug: "kilogram-metre-saniye",
    slug: "kilogram-meter-per-second",
    category: "momentum",
    categoryName: "ভরবেগ",
    unit: "kg·m/s",
    name: "কিলোগ্রাম-মিটার/সেকেন্ড",
    symbol: "kg·m/s",
    shortDescription: "কিলোগ্রাম-মিটার/সেকেন্ড ধ্রুপদী বলবিজ্ঞানে ভরবেগের SI একক।",
    historySummary: "গতির পরিমাণ বর্ণনা করতে পদার্থবিজ্ঞান হিসাবে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, ডেরাইভড একক)",
    siEquivalent: "ভরবেগের মৌলিক SI একক",
    commonUses: "পদার্থবিজ্ঞান ও বলবিজ্ঞান হিসাব",
  },
  {
    locale: "bn",
    sourceSlug: "newton-saniye",
    slug: "newton-second",
    category: "momentum",
    categoryName: "ভরবেগ",
    unit: "N·s",
    name: "নিউটন-সেকেন্ড",
    symbol: "N·s",
    shortDescription: "নিউটন-সেকেন্ড কিলোগ্রাম-মিটার/সেকেন্ডের সমান, ভরবেগের বিকল্প একক।",
    historySummary: "বল, সময় ও ভরবেগের পরিবর্তনের মধ্যে সম্পর্ক প্রকাশে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, ডেরাইভড একক)",
    siEquivalent: "১ N·s = ১ kg·m/s",
    commonUses: "পদার্থবিজ্ঞান, সংঘর্ষ ও আঘাত হিসাব",
  },
  {
    locale: "bn",
    sourceSlug: "kilopascal",
    slug: "kilopascal",
    category: "basinc",
    categoryName: "চাপ",
    unit: "kPa",
    name: "কিলোপ্যাসকেল",
    symbol: "kPa",
    shortDescription: "কিলোপ্যাসকেল ১০০০ প্যাসকেলের সমান, ব্যবহারিক চাপ পরিমাপে ব্যাপকভাবে ব্যবহৃত হয়।",
    historySummary: "প্রকৌশল ও আবহাওয়াবিদ্যায় সুবিধাজনক সংখ্যাসূচক মান প্রদানে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, গুণিতক)",
    siEquivalent: "১ kPa = ১০০০ Pa",
    commonUses: "প্রকৌশল, আবহাওয়াবিদ্যা, টায়ার চাপ",
  },
  {
    locale: "bn",
    sourceSlug: "bar",
    slug: "bar",
    category: "basinc",
    categoryName: "চাপ",
    unit: "bar",
    name: "বার",
    symbol: "bar",
    shortDescription: "বার আনুমানিক বায়ুমণ্ডলীয় চাপের সমান একটি ব্যবহারিক চাপ একক।",
    historySummary: "আবহাওয়াবিদ্যা ও শিল্পে ব্যাপকভাবে ব্যবহৃত সুবিধাজনক চাপ একক হিসেবে তৈরি করা হয়েছে।",
    measurementSystem: "SI-এর বাইরে, ব্যাপক প্রচলিত ব্যবহারিক একক",
    siEquivalent: "১ bar = ১,০০,০০০ Pa",
    commonUses: "আবহাওয়াবিদ্যা, শিল্প চাপ নির্দেশক",
  },
  {
    locale: "bn",
    sourceSlug: "milibar",
    slug: "millibar",
    category: "basinc",
    categoryName: "চাপ",
    unit: "mbar",
    name: "মিলিবার",
    symbol: "mbar",
    shortDescription: "মিলিবার আবহাওয়াবিদ্যায় বায়ুচাপ প্রকাশে ব্যাপকভাবে ব্যবহৃত চাপ একক।",
    historySummary: "বিশ্বব্যাপী আবহাওয়া প্রতিবেদনে বায়ুচাপ ব্যবস্থা বর্ণনার মানদণ্ড হয়ে উঠেছে।",
    measurementSystem: "SI-এর বাইরে, প্রচলিত আবহাওয়াবিদ্যা একক",
    siEquivalent: "১ mbar = ১০০ Pa",
    commonUses: "আবহাওয়া প্রতিবেদন ও মানচিত্র",
  },
  {
    locale: "bn",
    sourceSlug: "atmosfer",
    slug: "atmosphere",
    category: "basinc",
    categoryName: "চাপ",
    unit: "atm",
    name: "বায়ুমণ্ডল",
    symbol: "atm",
    shortDescription: "বায়ুমণ্ডল সমুদ্রপৃষ্ঠে গড় বায়ুচাপের প্রায় সমান চাপ একক।",
    historySummary: "বিজ্ঞান ও প্রযুক্তিতে চাপ প্রকাশের ব্যবহারিক তুলনামূলক মান হিসেবে নির্ধারিত।",
    measurementSystem: "SI-এর বাইরে, প্রচলিত তুলনামূলক একক",
    siEquivalent: "১ atm ≈ ১,০১,৩২৫ Pa",
    commonUses: "আবহাওয়াবিদ্যা, রসায়ন, প্রযুক্তিগত চাপ নির্দেশক",
  },
  {
    locale: "bn",
    sourceSlug: "psi",
    slug: "psi",
    category: "basinc",
    categoryName: "চাপ",
    unit: "psi",
    name: "PSI",
    symbol: "psi",
    shortDescription: "PSI (পাউন্ড/বর্গ ইঞ্চি) যুক্তরাষ্ট্রে টায়ার চাপ ও শিল্প স্পেসিফিকেশনে ব্যবহৃত হয়।",
    historySummary: "মার্কিন টায়ার চাপ ও শিল্প যন্ত্রপাতিতে মানক চাপ একক।",
    measurementSystem: "ইম্পেরিয়াল/মার্কিন পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "১ psi ≈ ৬৮৯৪.৭৬ Pa",
    commonUses: "মার্কিন টায়ার চাপ ও শিল্প স্পেসিফিকেশন",
  },
  {
    locale: "bn",
    sourceSlug: "milimetre-civa",
    slug: "millimeter-of-mercury",
    category: "basinc",
    categoryName: "চাপ",
    unit: "mmHg",
    name: "মিলিমিটার পারদ স্তম্ভ",
    symbol: "mmHg",
    shortDescription: "মিলিমিটার পারদ স্তম্ভ চিকিৎসায় রক্তচাপ পরিমাপে এখনও ব্যবহৃত ঐতিহ্যবাহী চাপ একক।",
    historySummary: "ঐতিহাসিক পারদ চাপ মাপক থেকে উদ্ভূত, আজও চিকিৎসা বিশ্ব মানদণ্ড।",
    measurementSystem: "SI-এর বাইরে, প্রচলিত চিকিৎসা একক",
    siEquivalent: "১ mmHg ≈ ১৩৩.৩২২ Pa",
    commonUses: "রক্তচাপ পরিমাপ, চিকিৎসা পরিমাপ",
  },
  {
    locale: "bn",
    sourceSlug: "kilogram-kuvvet-santimetrekare",
    slug: "kilogram-force-per-square-centimeter",
    category: "basinc",
    categoryName: "চাপ",
    unit: "kgf/cm²",
    name: "কিলোগ্রাম-বল/বর্গ সেন্টিমিটার",
    symbol: "kgf/cm²",
    shortDescription: "কিলোগ্রাম-বল/বর্গ সেন্টিমিটার পুরনো টায়ার চাপ ও যন্ত্রপাতির নির্দেশকে পাওয়া যায় এমন ঐতিহ্যবাহী চাপ একক।",
    historySummary: "SI পদ্ধতি সম্পূর্ণ প্রমিতকরণের আগে ব্যবহৃত হতো, এখনও কিছু পুরনো মাপকে দেখা যায়।",
    measurementSystem: "SI-এর বাইরে, ঐতিহ্যবাহী একক",
    siEquivalent: "১ kgf/cm² ≈ ৯৮,০৬৬.৫ Pa",
    commonUses: "পুরনো টায়ার চাপ মাপক ও শিল্প যন্ত্রপাতি",
  },
  {
    locale: "bn",
    sourceSlug: "pascal-saniye",
    slug: "pascal-second",
    category: "viskozite_dinamik",
    categoryName: "গতিশীল সান্দ্রতা",
    unit: "Pa·s",
    name: "প্যাসকেল-সেকেন্ড",
    symbol: "Pa·s",
    shortDescription: "প্যাসকেল-সেকেন্ড গতিশীল সান্দ্রতার SI একক, তরলের প্রবাহ প্রতিরোধ প্রকাশ করে।",
    historySummary: "রসায়ন ও প্রকৌশলে তরল নির্ভুলভাবে বর্ণনা করতে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, ডেরাইভড একক)",
    siEquivalent: "গতিশীল সান্দ্রতার মৌলিক SI একক",
    commonUses: "উপাদান বিজ্ঞান, রসায়ন, তরল বিশ্লেষণ",
  },
  {
    locale: "bn",
    sourceSlug: "santipoise",
    slug: "centipoise",
    category: "viskozite_dinamik",
    categoryName: "গতিশীল সান্দ্রতা",
    unit: "cP",
    name: "সেন্টিপয়েজ",
    symbol: "cP",
    shortDescription: "সেন্টিপয়েজ শিল্পে সবচেয়ে বেশি ব্যবহৃত ব্যবহারিক গতিশীল সান্দ্রতা একক।",
    historySummary: "প্রায় ২০°C তাপমাত্রায় পানির সান্দ্রতার সমান, তাই একটি সহজবোধ্য তুলনামূলক মান।",
    measurementSystem: "CGS পদ্ধতি (SI-এর বাইরে, উপ-একক)",
    siEquivalent: "১ cP = ০.০০১ Pa·s",
    commonUses: "মোটর তেল শ্রেণীবিভাগ, শিল্প তরল",
  },
  {
    locale: "bn",
    sourceSlug: "metrekare-saniye",
    slug: "square-meter-per-second",
    category: "viskozite_kinematik",
    categoryName: "গতীয় সান্দ্রতা",
    unit: "m²/s",
    name: "বর্গমিটার/সেকেন্ড",
    symbol: "m²/s",
    shortDescription: "বর্গমিটার/সেকেন্ড গতীয় সান্দ্রতার SI মৌলিক একক।",
    historySummary: "বৈজ্ঞানিক হিসাবে তরলের প্রবাহ বৈশিষ্ট্য বর্ণনা করতে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, মৌলিক একক)",
    siEquivalent: "গতীয় সান্দ্রতার মৌলিক SI একক",
    commonUses: "তরল বলবিজ্ঞান ও বৈজ্ঞানিক হিসাব",
  },
  {
    locale: "bn",
    sourceSlug: "santistok",
    slug: "centistoke",
    category: "viskozite_kinematik",
    categoryName: "গতীয় সান্দ্রতা",
    unit: "cSt",
    name: "সেন্টিস্টোক",
    symbol: "cSt",
    shortDescription: "সেন্টিস্টোক শিল্পে সবচেয়ে বেশি ব্যবহৃত ব্যবহারিক গতীয় সান্দ্রতা একক।",
    historySummary: "১ mm²/s এর সমান, মোটর তেল শ্রেণীবিভাগের শিল্প মানদণ্ড হয়ে উঠেছে।",
    measurementSystem: "CGS পদ্ধতি (SI-এর বাইরে, উপ-একক)",
    siEquivalent: "১ cSt = ১ mm²/s = ০.০০০০০১ m²/s",
    commonUses: "মোটর তেল শ্রেণীবিভাগ, জ্বালানি বৈশিষ্ট্য",
  },
  {
    locale: "bn",
    sourceSlug: "metrekup-saniye",
    slug: "cubic-meter-per-second",
    category: "debi_hacimsel",
    categoryName: "আয়তনিক প্রবাহ হার",
    unit: "m³/s",
    name: "ঘনমিটার/সেকেন্ড",
    symbol: "m³/s",
    shortDescription: "ঘনমিটার/সেকেন্ড আয়তনিক প্রবাহ হারের SI মৌলিক একক।",
    historySummary: "নদী বা শিল্প স্থাপনার মতো বড় প্রবাহের পরিমাণ বর্ণনায় ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, মৌলিক একক)",
    siEquivalent: "আয়তনিক প্রবাহ হারের মৌলিক SI একক",
    commonUses: "জল ব্যবস্থাপনা, পাইপলাইন প্রযুক্তি",
  },
  {
    locale: "bn",
    sourceSlug: "fitkup-dakika",
    slug: "cubic-foot-per-minute",
    category: "debi_hacimsel",
    categoryName: "আয়তনিক প্রবাহ হার",
    unit: "cfm",
    name: "ঘনফুট/মিনিট (CFM)",
    symbol: "cfm",
    shortDescription: "CFM যুক্তরাষ্ট্রে শীতাতপ ও বায়ুচলাচল ব্যবস্থার বায়ু প্রবাহ প্রকাশে ব্যবহৃত হয়।",
    historySummary: "মার্কিন পাখা ও জলবায়ু প্রযুক্তি স্পেসিফিকেশনে মানদণ্ড।",
    measurementSystem: "ইম্পেরিয়াল/মার্কিন পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "১ CFM ≈ ০.০০০৪৭২ m³/s",
    commonUses: "মার্কিন বায়ুচলাচল ও জলবায়ু প্রযুক্তি",
  },
  {
    locale: "bn",
    sourceSlug: "galon-dakika",
    slug: "gallons-per-minute",
    category: "debi_hacimsel",
    categoryName: "আয়তনিক প্রবাহ হার",
    unit: "gpm",
    name: "গ্যালন/মিনিট (GPM)",
    symbol: "gpm",
    shortDescription: "GPM যুক্তরাষ্ট্রে পাম্প ও জলের পাইপের প্রবাহ প্রকাশে ব্যবহৃত হয়।",
    historySummary: "মার্কিন পাম্প, সেচ ও স্যানিটারি প্রযুক্তি স্পেসিফিকেশনে মানদণ্ড।",
    measurementSystem: "ইম্পেরিয়াল/মার্কিন পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "১ GPM ≈ ০.০০০০৬৩১ m³/s",
    commonUses: "মার্কিন পাম্প, সেচ ও স্যানিটারি প্রযুক্তি",
  },
  {
    locale: "bn",
    sourceSlug: "kilogram-saniye",
    slug: "kilogram-per-second",
    category: "debi_kutlesel",
    categoryName: "ভরের প্রবাহ হার",
    unit: "kg/s",
    name: "কিলোগ্রাম/সেকেন্ড",
    symbol: "kg/s",
    shortDescription: "কিলোগ্রাম/সেকেন্ড ভরের প্রবাহ হারের SI মৌলিক একক।",
    historySummary: "রাসায়নিক প্রযুক্তিতে প্রক্রিয়ায় ভরের প্রবাহ বর্ণনায় ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, মৌলিক একক)",
    siEquivalent: "ভরের প্রবাহ হারের মৌলিক SI একক",
    commonUses: "রাসায়নিক প্রযুক্তি, শিল্প প্রক্রিয়া হিসাব",
  },
  {
    locale: "bn",
    sourceSlug: "kilogram-saat",
    slug: "kilogram-per-hour",
    category: "debi_kutlesel",
    categoryName: "ভরের প্রবাহ হার",
    unit: "kg/h",
    name: "কিলোগ্রাম/ঘণ্টা",
    symbol: "kg/h",
    shortDescription: "কিলোগ্রাম/ঘণ্টা শিল্প প্রয়োগের জন্য একটি ব্যবহারিক ভরের প্রবাহ হার একক।",
    historySummary: "ঘণ্টাভিত্তিক উৎপাদন হার গুরুত্বপূর্ণ এমন উৎপাদন প্রক্রিয়ায় বেশি ব্যবহৃত হয়।",
    measurementSystem: "মেট্রিক পদ্ধতি (SI ডেরাইভড ব্যবহারিক একক)",
    siEquivalent: "১ kg/ঘণ্টা = ০.০০০২৭৭৮ kg/s",
    commonUses: "উৎপাদন প্রক্রিয়া ও শিল্প নির্দেশক",
  },
  {
    locale: "bn",
    sourceSlug: "kilojoule",
    slug: "kilojoule",
    category: "enerji",
    categoryName: "শক্তি",
    unit: "kJ",
    name: "কিলোজুল",
    symbol: "kJ",
    shortDescription: "কিলোজুল ১০০০ জুলের সমান, খাদ্যের শক্তির মান প্রকাশে ব্যাপকভাবে ব্যবহৃত হয়।",
    historySummary: "অনেক দেশে খাদ্য লেবেলে ক্যালোরির পরিবর্তে সরকারি একক হিসেবে গণ্য।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, গুণিতক)",
    siEquivalent: "১ kJ = ১০০০ J",
    commonUses: "খাদ্য লেবেল, শক্তি হিসাব",
  },
  {
    locale: "bn",
    sourceSlug: "watt-saat",
    slug: "watt-hour",
    category: "enerji",
    categoryName: "শক্তি",
    unit: "Wh",
    name: "ওয়াট-ঘণ্টা",
    symbol: "Wh",
    shortDescription: "ওয়াট-ঘণ্টা একটি ব্যবহারিক শক্তি একক, এক ওয়াট ক্ষমতায় এক ঘণ্টায় ব্যয়িত শক্তি প্রকাশ করে।",
    historySummary: "বিদ্যুৎ বিলে ব্যবহৃত বড় কিলোওয়াট-ঘণ্টা একক এর ভিত্তি তৈরি করে।",
    measurementSystem: "SI-এর বাইরে, প্রচলিত বাণিজ্যিক একক",
    siEquivalent: "১ Wh = ৩৬০০ J",
    commonUses: "ছোট ব্যাটারি ক্ষমতা, বহনযোগ্য ইলেকট্রনিক্স",
  },
  {
    locale: "bn",
    sourceSlug: "kilovatsaat",
    slug: "kilowatt-hour",
    category: "enerji",
    categoryName: "শক্তি",
    unit: "kWh",
    name: "কিলোওয়াট-ঘণ্টা",
    symbol: "kWh",
    shortDescription: "কিলোওয়াট-ঘণ্টা বিদ্যুৎ শক্তি হিসাবে ব্যাপকভাবে ব্যবহৃত ব্যবহারিক শক্তি একক।",
    historySummary: "বিশ্বব্যাপী বিদ্যুৎ বিল হিসাব করার জন্য মানক একক হিসেবে গণ্য।",
    measurementSystem: "SI-এর বাইরে, প্রচলিত বাণিজ্যিক একক",
    siEquivalent: "১ kWh = ৩৬,০০,০০০ J",
    commonUses: "বিদ্যুৎ শক্তি হিসাব ও বিল",
  },
  {
    locale: "bn",
    sourceSlug: "kalori",
    slug: "calorie",
    category: "enerji",
    categoryName: "শক্তি",
    unit: "cal",
    name: "ক্যালোরি",
    symbol: "cal",
    shortDescription: "ক্যালোরি মূলত তাপের পরিমাণ প্রকাশ করতে ব্যবহৃত একটি ঐতিহ্যবাহী শক্তি একক।",
    historySummary: "আজও অনেক দেশে পুষ্টিবিজ্ঞানে ব্যাপকভাবে ব্যবহৃত হয়।",
    measurementSystem: "SI-এর বাইরে, প্রচলিত একক",
    siEquivalent: "১ ক্যালোরি ≈ ৪.১৮৪ J",
    commonUses: "পুষ্টিবিজ্ঞান, খাদ্যের শক্তির মান",
  },
  {
    locale: "bn",
    sourceSlug: "kilokalori",
    slug: "kilocalorie",
    category: "enerji",
    categoryName: "শক্তি",
    unit: "kcal",
    name: "কিলোক্যালোরি",
    symbol: "kcal",
    shortDescription: "কিলোক্যালোরি ১০০০ ক্যালোরির সমান, খাদ্যের প্যাকেটে ব্যবহৃত শক্তি একক।",
    historySummary: "প্রায়ই সহজভাবে ক্যালোরি বলা হয়, পুষ্টি লেবেলে মানদণ্ড হিসেবে গণ্য।",
    measurementSystem: "SI-এর বাইরে, প্রচলিত একক",
    siEquivalent: "১ kcal = ৪১৮৪ J",
    commonUses: "পুষ্টি লেবেল ও খাদ্য পরিকল্পনা",
  },
  {
    locale: "bn",
    sourceSlug: "btu",
    slug: "btu",
    category: "enerji",
    categoryName: "শক্তি",
    unit: "Btu",
    name: "BTU",
    symbol: "Btu",
    shortDescription: "BTU (ব্রিটিশ থার্মাল ইউনিট) যুক্তরাষ্ট্রে গরম ও ঠান্ডা করার যন্ত্রে ব্যবহৃত ঐতিহ্যবাহী শক্তি একক।",
    historySummary: "মার্কিন জলবায়ু ও গরম ব্যবস্থা স্পেসিফিকেশনে মানদণ্ড হিসেবে গণ্য।",
    measurementSystem: "ইম্পেরিয়াল/মার্কিন পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "১ Btu ≈ ১০৫৫.০৬ J",
    commonUses: "মার্কিন জলবায়ু ও গরম ব্যবস্থা স্পেসিফিকেশন",
  },
  {
    locale: "bn",
    sourceSlug: "watt",
    slug: "watt",
    category: "guc",
    categoryName: "ক্ষমতা",
    unit: "W",
    name: "ওয়াট",
    symbol: "W",
    shortDescription: "ওয়াট ক্ষমতার SI একক, জেমস ওয়াটের নামে নামকরণ করা হয়েছে।",
    historySummary: "বৈদ্যুতিক যন্ত্রপাতি ও মোটরের ক্ষমতা প্রকাশের বিশ্বব্যাপী মানদণ্ড।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, ডেরাইভড একক)",
    siEquivalent: "ক্ষমতার মৌলিক SI একক",
    commonUses: "বৈদ্যুতিক যন্ত্রপাতি, মোটর",
  },
  {
    locale: "bn",
    sourceSlug: "kilowatt",
    slug: "kilowatt",
    category: "guc",
    categoryName: "ক্ষমতা",
    unit: "kW",
    name: "কিলোওয়াট",
    symbol: "kW",
    shortDescription: "কিলোওয়াট ১০০০ ওয়াটের সমান, মোটর ও যন্ত্রপাতির ক্ষমতা প্রকাশে ব্যাপকভাবে ব্যবহৃত হয়।",
    historySummary: "শিল্প ও গৃহস্থালি বৈদ্যুতিক যন্ত্রপাতি স্পেসিফিকেশনে মানদণ্ড হিসেবে গণ্য।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, গুণিতক)",
    siEquivalent: "১ kW = ১০০০ W",
    commonUses: "মোটর ও বৈদ্যুতিক যন্ত্রপাতি স্পেসিফিকেশন",
  },
  {
    locale: "bn",
    sourceSlug: "megawatt",
    slug: "megawatt",
    category: "guc",
    categoryName: "ক্ষমতা",
    unit: "MW",
    name: "মেগাওয়াট",
    symbol: "MW",
    shortDescription: "মেগাওয়াট দশ লক্ষ ওয়াটের সমান, বিদ্যুৎ কেন্দ্র ও বড় শিল্প ক্ষমতা প্রকাশে ব্যবহৃত হয়।",
    historySummary: "বিদ্যুৎ উৎপাদন কেন্দ্র ও বড় শিল্প স্থাপনার জন্য মানদণ্ড ক্ষমতা একক।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, গুণিতক)",
    siEquivalent: "১ MW = ১০,০০,০০০ W",
    commonUses: "বিদ্যুৎ কেন্দ্র, বড় শিল্প ক্ষমতা",
  },
  {
    locale: "bn",
    sourceSlug: "beygirgucu",
    slug: "horsepower",
    category: "guc",
    categoryName: "ক্ষমতা",
    unit: "hp",
    name: "অশ্বশক্তি",
    symbol: "hp",
    shortDescription: "অশ্বশক্তি ইউরোপীয় যানবাহন প্রযুক্তিতে ব্যাপকভাবে ব্যবহৃত ঐতিহ্যবাহী ক্ষমতা একক।",
    historySummary: "মূলত বাষ্প ইঞ্জিনের ক্ষমতা ঘোড়ার সাথে তুলনা করার জন্য তৈরি করা হয়েছিল।",
    measurementSystem: "মেট্রিক পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "১ অশ্বশক্তি ≈ ৭৩৫.৫ W",
    commonUses: "ইউরোপীয় যানবাহন ও মোটর স্পেসিফিকেশন",
  },
  {
    locale: "bn",
    sourceSlug: "beygirgucu-mekanik",
    slug: "mechanical-horsepower",
    category: "guc",
    categoryName: "ক্ষমতা",
    unit: "HP",
    name: "যান্ত্রিক অশ্বশক্তি",
    symbol: "HP",
    shortDescription: "যান্ত্রিক অশ্বশক্তি মেট্রিক অশ্বশক্তির চেয়ে কিছুটা ভিন্ন ব্রিটিশ-আমেরিকান ক্ষমতা একক।",
    historySummary: "মূলত জেমস ওয়াট দ্বারা সংজ্ঞায়িত, এখনও যুক্তরাষ্ট্র ও যুক্তরাজ্যের যানবাহন প্রযুক্তিতে ব্যবহৃত হয়।",
    measurementSystem: "ইম্পেরিয়াল/মার্কিন পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "১ HP (যান্ত্রিক) = ৭৪৫.৭ W",
    commonUses: "যুক্তরাষ্ট্র ও যুক্তরাজ্যের যানবাহন স্পেসিফিকেশন",
  },
  {
    locale: "bn",
    sourceSlug: "fahrenhayt",
    slug: "fahrenheit",
    category: "sicaklik",
    categoryName: "তাপমাত্রা",
    unit: "F",
    name: "ফারেনহাইট",
    symbol: "°F",
    shortDescription: "ফারেনহাইট যুক্তরাষ্ট্রে দৈনন্দিন তাপমাত্রা পরিমাপে ব্যাপকভাবে ব্যবহৃত তাপমাত্রা স্কেল।",
    historySummary: "১৮ শতকে ড্যানিয়েল গ্যাব্রিয়েল ফারেনহাইট তৈরি করেন, এখন প্রধানত যুক্তরাষ্ট্রে ব্যবহৃত হয়।",
    measurementSystem: "SI-এর বাইরে, প্রচলিত একক",
    siEquivalent: "K = (°F − ৩২) × ৫/৯ + ২৭৩.১৫",
    commonUses: "যুক্তরাষ্ট্রে দৈনন্দিন তাপমাত্রা পরিমাপ",
  },
  {
    locale: "bn",
    sourceSlug: "watt-metre-kelvin",
    slug: "watt-per-meter-kelvin",
    category: "isil_iletkenlik",
    categoryName: "তাপ পরিবাহিতা",
    unit: "W/m·K",
    name: "ওয়াট/মিটার-কেলভিন",
    symbol: "W/(m·K)",
    shortDescription: "ওয়াট/মিটার-কেলভিন তাপ পরিবাহিতার SI একক।",
    historySummary: "নির্মাণ পদার্থবিজ্ঞান ও উপাদান বিজ্ঞানে উপকরণের নিরোধক বৈশিষ্ট্য মূল্যায়নে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, ডেরাইভড একক)",
    siEquivalent: "তাপ পরিবাহিতার মৌলিক SI একক",
    commonUses: "নির্মাণ পদার্থবিজ্ঞান, নিরোধক উপকরণ",
  },
  {
    locale: "bn",
    sourceSlug: "btu-saat-fit-f",
    slug: "btu-per-hour-foot-fahrenheit",
    category: "isil_iletkenlik",
    categoryName: "তাপ পরিবাহিতা",
    unit: "Btu/h·ft·°F",
    name: "BTU/ঘণ্টা-ফুট-°F",
    symbol: "Btu/(h·ft·°F)",
    shortDescription: "BTU/ঘণ্টা-ফুট-°F যুক্তরাষ্ট্রে ব্যবহৃত তাপ পরিবাহিতা একক।",
    historySummary: "মার্কিন নির্মাণ নিয়মে মেট্রিক এককের পরিবর্তে ব্যবহৃত হয়।",
    measurementSystem: "ইম্পেরিয়াল/মার্কিন পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "১ Btu/(ঘণ্টা·ফুট·°F) ≈ ১.৭৩১ W/(m·K)",
    commonUses: "মার্কিন নির্মাণ নিয়ম ও নিরোধক স্পেসিফিকেশন",
  },
  {
    locale: "bn",
    sourceSlug: "watt-metrekare",
    slug: "watt-per-square-meter",
    category: "isi_akisi",
    categoryName: "তাপ প্রবাহ ঘনত্ব",
    unit: "W/m²",
    name: "ওয়াট/বর্গমিটার",
    symbol: "W/m²",
    shortDescription: "ওয়াট/বর্গমিটার তাপ প্রবাহ ঘনত্বের SI একক।",
    historySummary: "নির্মাণ পদার্থবিজ্ঞান ও সৌর শক্তিতে পৃষ্ঠের শক্তি প্রবাহ বর্ণনায় ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, ডেরাইভড একক)",
    siEquivalent: "তাপ প্রবাহ ঘনত্বের মৌলিক SI একক",
    commonUses: "নির্মাণ পদার্থবিজ্ঞান, সৌর শক্তি",
  },
  {
    locale: "bn",
    sourceSlug: "kilowatt-metrekare",
    slug: "kilowatt-per-square-meter",
    category: "isi_akisi",
    categoryName: "তাপ প্রবাহ ঘনত্ব",
    unit: "kW/m²",
    name: "কিলোওয়াট/বর্গমিটার",
    symbol: "kW/m²",
    shortDescription: "কিলোওয়াট/বর্গমিটার বৃহত্তর তাপ প্রবাহ ঘনত্ব মানের জন্য ব্যবহৃত একক।",
    historySummary: "একক ক্ষেত্রফলে উচ্চ তাপ ক্ষমতা প্রয়োজন এমন শিল্প প্রয়োগে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, গুণিতক)",
    siEquivalent: "১ kW/m² = ১০০০ W/m²",
    commonUses: "শিল্প তাপ প্রযুক্তি, সৌর যন্ত্রপাতি",
  },
  {
    locale: "bn",
    sourceSlug: "joule-kilogram-kelvin",
    slug: "joule-per-kilogram-kelvin",
    category: "ozgul_isi",
    categoryName: "আপেক্ষিক তাপ ধারণক্ষমতা",
    unit: "J/kg·K",
    name: "জুল/কিলোগ্রাম-কেলভিন",
    symbol: "J/(kg·K)",
    shortDescription: "জুল/কিলোগ্রাম-কেলভিন উপাদানের আপেক্ষিক তাপ ধারণক্ষমতার SI একক।",
    historySummary: "এক কিলোগ্রাম পদার্থকে এক কেলভিন গরম করতে প্রয়োজনীয় শক্তি প্রকাশ করে।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, ডেরাইভড একক)",
    siEquivalent: "আপেক্ষিক তাপ ধারণক্ষমতার মৌলিক SI একক",
    commonUses: "উপাদান বিজ্ঞান ও তাপগতিবিদ্যা হিসাব",
  },
  {
    locale: "bn",
    sourceSlug: "kalori-gram-kelvin",
    slug: "calorie-per-gram-kelvin",
    category: "ozgul_isi",
    categoryName: "আপেক্ষিক তাপ ধারণক্ষমতা",
    unit: "cal/g·K",
    name: "ক্যালোরি/গ্রাম-কেলভিন",
    symbol: "cal/(g·K)",
    shortDescription: "ক্যালোরি/গ্রাম-কেলভিন আপেক্ষিক তাপ ধারণক্ষমতার ঐতিহ্যবাহী একক।",
    historySummary: "SI পদ্ধতিতে সম্পূর্ণ রূপান্তরের আগে রসায়ন ও পদার্থবিজ্ঞানে ব্যবহৃত হতো।",
    measurementSystem: "SI-এর বাইরে, ঐতিহ্যবাহী একক",
    siEquivalent: "১ cal/(g·K) = ৪১৮৪ J/(kg·K)",
    commonUses: "রসায়ন ও পুরনো তাপগতিবিদ্যা হিসাব",
  },
  {
    locale: "bn",
    sourceSlug: "metrekup-saat",
    slug: "cubic-meter-per-hour",
    category: "debi",
    categoryName: "প্রবাহ হার",
    unit: "m³/h",
    name: "ঘনমিটার/ঘণ্টা",
    symbol: "m³/h",
    shortDescription: "ঘনমিটার/ঘণ্টা পানি ও গ্যাস পাইপলাইনের প্রবাহ প্রকাশে ব্যাপকভাবে ব্যবহৃত হয়।",
    historySummary: "গৃহস্থালি প্রযুক্তি ও জল ব্যবস্থাপনায় প্রবাহ হার প্রকাশে ব্যবহৃত হয়।",
    measurementSystem: "মেট্রিক পদ্ধতি (SI ডেরাইভড ব্যবহারিক একক)",
    siEquivalent: "১ m³/ঘণ্টা ≈ ০.০০০২৭৮ m³/s",
    commonUses: "গৃহস্থালি প্রযুক্তি, জল ব্যবস্থাপনা, গ্যাস পাইপলাইন",
  },
  {
    locale: "bn",
    sourceSlug: "litre-dakika",
    slug: "liter-per-minute",
    category: "debi",
    categoryName: "প্রবাহ হার",
    unit: "L/min",
    name: "লিটার/মিনিট",
    symbol: "L/min",
    shortDescription: "লিটার/মিনিট কল বা পাম্পের ছোট প্রবাহ পরিমাণের জন্য একটি ব্যবহারিক একক।",
    historySummary: "দৈনন্দিন জীবন ও গৃহস্থালি প্রযুক্তিতে সুবিধাজনক প্রবাহ মান প্রকাশে ব্যাপকভাবে প্রচলিত।",
    measurementSystem: "মেট্রিক পদ্ধতি (SI ডেরাইভড ব্যবহারিক একক)",
    siEquivalent: "১ L/মিনিট ≈ ০.০০০০১৬৭ m³/s",
    commonUses: "গৃহস্থালি প্রযুক্তি, পাম্প",
  },
  {
    locale: "bn",
    sourceSlug: "kilovolt",
    slug: "kilovolt",
    category: "elektrik",
    categoryName: "বিদ্যুৎ",
    unit: "kV",
    name: "কিলোভোল্ট",
    symbol: "kV",
    shortDescription: "কিলোভোল্ট ১০০০ ভোল্টের সমান, উচ্চ বিভব ব্যবস্থায় ব্যবহৃত হয়।",
    historySummary: "বিদ্যুৎ সঞ্চালন গ্রিডে উচ্চ বিভব প্রকাশে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, গুণিতক)",
    siEquivalent: "১ kV = ১০০০ V",
    commonUses: "বিদ্যুৎ সঞ্চালন গ্রিড, উচ্চ বিভব যন্ত্রপাতি",
  },
  {
    locale: "bn",
    sourceSlug: "miliamper",
    slug: "milliampere",
    category: "elektrik",
    categoryName: "বিদ্যুৎ",
    unit: "mA",
    name: "মিলিঅ্যাম্পিয়ার",
    symbol: "mA",
    shortDescription: "মিলিঅ্যাম্পিয়ার অ্যাম্পিয়ারের হাজার ভাগের এক ভাগের সমান, ছোট প্রবাহ পরিমাপে ব্যবহৃত হয়।",
    historySummary: "ইলেকট্রনিক্স, সেন্সর ও নির্ভুল যন্ত্রপাতির বিকাশের সাথে গুরুত্বপূর্ণ হয়ে উঠেছে।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, উপ-একক)",
    siEquivalent: "১ mA = ০.০০১ A",
    commonUses: "ইলেকট্রনিক্স, সেন্সর, ছোট প্রবাহ পরিমাপ",
  },
  {
    locale: "bn",
    sourceSlug: "milivolt",
    slug: "millivolt",
    category: "elektrik",
    categoryName: "বিদ্যুৎ",
    unit: "mV",
    name: "মিলিভোল্ট",
    symbol: "mV",
    shortDescription: "মিলিভোল্ট ভোল্টের হাজার ভাগের এক ভাগের সমান, ছোট বিভব মান প্রকাশে ব্যবহৃত হয়।",
    historySummary: "ইলেকট্রনিক্স ও নির্ভুল যন্ত্রপাতির বিকাশের সাথে গুরুত্বপূর্ণ হয়ে উঠেছে।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, উপ-একক)",
    siEquivalent: "১ mV = ০.০০১ V",
    commonUses: "ইলেকট্রনিক্স, সেন্সর, নিম্ন বিভব পরিমাপ",
  },
  {
    locale: "bn",
    sourceSlug: "kiloamper",
    slug: "kiloampere",
    category: "elektrik",
    categoryName: "বিদ্যুৎ",
    unit: "kA",
    name: "কিলোঅ্যাম্পিয়ার",
    symbol: "kA",
    shortDescription: "কিলোঅ্যাম্পিয়ার ১০০০ অ্যাম্পিয়ারের সমান, শর্ট সার্কিট ও বজ্রপাতের মতো বড় প্রবাহ পরিমাপে ব্যবহৃত হয়।",
    historySummary: "বিদ্যুৎ বিতরণ ব্যবস্থা ও বড় শিল্প বৈদ্যুতিক স্থাপনায় ব্যবহারিক মানদণ্ড হয়ে উঠেছে।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, গুণিতক)",
    siEquivalent: "১ kA = ১০০০ A",
    commonUses: "শর্ট সার্কিট হিসাব, বিদ্যুৎ বিতরণ যন্ত্রপাতি",
  },
  {
    locale: "bn",
    sourceSlug: "ohm",
    slug: "ohm",
    category: "elektrik_direnc",
    categoryName: "রোধ",
    unit: "Ω",
    name: "ওহম",
    symbol: "Ω",
    shortDescription: "ওহম তড়িৎ রোধের SI একক, জর্জ সাইমন ওহমের নামে নামকরণ করা হয়েছে।",
    historySummary: "বিশ্বব্যাপী তড়িৎ প্রকৌশলে রোধ প্রকাশের মৌলিক একক।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, ডেরাইভড একক)",
    siEquivalent: "তড়িৎ রোধের মৌলিক SI একক",
    commonUses: "তড়িৎ প্রকৌশল, বর্তনী ডিজাইন",
  },
  {
    locale: "bn",
    sourceSlug: "kiloohm",
    slug: "kiloohm",
    category: "elektrik_direnc",
    categoryName: "রোধ",
    unit: "kΩ",
    name: "কিলোওহম",
    symbol: "kΩ",
    shortDescription: "কিলোওহম ১০০০ ওহমের সমান, ইলেকট্রনিক্সে মাঝারি রোধ মানের জন্য ব্যবহৃত হয়।",
    historySummary: "সাধারণ বর্তনীর রেজিস্টরের জন্য ব্যাপকভাবে ব্যবহৃত একক।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, গুণিতক)",
    siEquivalent: "১ kΩ = ১০০০ Ω",
    commonUses: "ইলেকট্রনিক্স ও বর্তনী ডিজাইন",
  },
  {
    locale: "bn",
    sourceSlug: "megaohm",
    slug: "megaohm",
    category: "elektrik_direnc",
    categoryName: "রোধ",
    unit: "MΩ",
    name: "মেগাওহম",
    symbol: "MΩ",
    shortDescription: "মেগাওহম দশ লক্ষ ওহমের সমান, অত্যন্ত উচ্চ রোধ মানের জন্য ব্যবহৃত হয়।",
    historySummary: "ইনসুলেশন রোধ পরিমাপ ও উচ্চ নির্ভুলতার বর্তনীতে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, গুণিতক)",
    siEquivalent: "১ MΩ = ১০,০০,০০০ Ω",
    commonUses: "ইনসুলেশন পরিমাপ, উচ্চ নির্ভুলতা ইলেকট্রনিক্স",
  },
  {
    locale: "bn",
    sourceSlug: "farad",
    slug: "farad",
    category: "kapasitans",
    categoryName: "ধারকত্ব",
    unit: "F",
    name: "ফ্যারাড",
    symbol: "F",
    shortDescription: "ফ্যারাড তড়িৎ ধারকত্বের SI একক, মাইকেল ফ্যারাডের নামে নামকরণ করা হয়েছে।",
    historySummary: "তড়িৎ প্রকৌশলে ক্যাপাসিটরের ধারকত্ব প্রকাশের মৌলিক একক।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, ডেরাইভড একক)",
    siEquivalent: "ধারকত্বের মৌলিক SI একক",
    commonUses: "ক্যাপাসিটর ডিজাইন, বর্তনী প্রযুক্তি",
  },
  {
    locale: "bn",
    sourceSlug: "milifarad",
    slug: "millifarad",
    category: "kapasitans",
    categoryName: "ধারকত্ব",
    unit: "mF",
    name: "মিলিফ্যারাড",
    symbol: "mF",
    shortDescription: "মিলিফ্যারাড ফ্যারাডের হাজার ভাগের এক ভাগের সমান, বড় শক্তির ক্যাপাসিটরে ব্যবহৃত হয়।",
    historySummary: "পাওয়ার ইলেকট্রনিক্স ও বড় শক্তি সংরক্ষণ ক্যাপাসিটরে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, উপ-একক)",
    siEquivalent: "১ mF = ০.০০১ F",
    commonUses: "পাওয়ার ইলেকট্রনিক্স, শক্তি সংরক্ষণ",
  },
  {
    locale: "bn",
    sourceSlug: "mikrofarad",
    slug: "microfarad",
    category: "kapasitans",
    categoryName: "ধারকত্ব",
    unit: "µF",
    name: "মাইক্রোফ্যারাড",
    symbol: "µF",
    shortDescription: "মাইক্রোফ্যারাড ফ্যারাডের দশ লক্ষ ভাগের এক ভাগের সমান, দৈনন্দিন ইলেকট্রনিক ক্যাপাসিটরে সবচেয়ে বেশি ব্যবহৃত হয়।",
    historySummary: "ইলেকট্রনিক যন্ত্রপাতির বেশিরভাগ বাণিজ্যিক ক্যাপাসিটর মাইক্রোফ্যারাডে প্রকাশিত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, উপ-একক)",
    siEquivalent: "১ µF = ০.০০০০০১ F",
    commonUses: "ইলেকট্রনিক যন্ত্রপাতি, বর্তনী ডিজাইন",
  },
  {
    locale: "bn",
    sourceSlug: "nanofarad",
    slug: "nanofarad",
    category: "kapasitans",
    categoryName: "ধারকত্ব",
    unit: "nF",
    name: "ন্যানোফ্যারাড",
    symbol: "nF",
    shortDescription: "ন্যানোফ্যারাড ফ্যারাডের একশ কোটি ভাগের এক ভাগের সমান, উচ্চ কম্পাঙ্কের বর্তনীতে ছোট ক্যাপাসিটরের জন্য ব্যবহৃত হয়।",
    historySummary: "ফিল্টার ও উচ্চ কম্পাঙ্কের যোগাযোগ বর্তনী ডিজাইনে গুরুত্বপূর্ণ।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, উপ-একক)",
    siEquivalent: "১ nF = ০.০০০০০০০০১ F",
    commonUses: "ফিল্টার বর্তনী, উচ্চ কম্পাঙ্কের যোগাযোগ",
  },
  {
    locale: "bn",
    sourceSlug: "pikofarad",
    slug: "picofarad",
    category: "kapasitans",
    categoryName: "ধারকত্ব",
    unit: "pF",
    name: "পিকোফ্যারাড",
    symbol: "pF",
    shortDescription: "পিকোফ্যারাড ফ্যারাডের এক লক্ষ কোটি ভাগের এক ভাগের সমান, নির্ভুল বর্তনীর ক্ষুদ্রতম ক্যাপাসিটর মানের জন্য।",
    historySummary: "রেডিও ও বেতার যোগাযোগের মতো নির্ভুল উচ্চ কম্পাঙ্কের বর্তনী ডিজাইনে গুরুত্বপূর্ণ।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, উপ-একক)",
    siEquivalent: "১ pF = ০.০০০০০০০০০০০১ F",
    commonUses: "রেডিও বর্তনী, বেতার যোগাযোগ",
  },
  {
    locale: "bn",
    sourceSlug: "henry",
    slug: "henry",
    category: "enduktans",
    categoryName: "আবেশ",
    unit: "H",
    name: "হেনরি",
    symbol: "H",
    shortDescription: "হেনরি আবেশের SI একক, জোসেফ হেনরির নামে নামকরণ করা হয়েছে।",
    historySummary: "তড়িৎ প্রকৌশলে কয়েলের আবেশ প্রকাশের মৌলিক একক।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, ডেরাইভড একক)",
    siEquivalent: "আবেশের মৌলিক SI একক",
    commonUses: "কয়েল ডিজাইন, বর্তনী প্রযুক্তি",
  },
  {
    locale: "bn",
    sourceSlug: "milihenry",
    slug: "millihenry",
    category: "enduktans",
    categoryName: "আবেশ",
    unit: "mH",
    name: "মিলিহেনরি",
    symbol: "mH",
    shortDescription: "মিলিহেনরি হেনরির হাজার ভাগের এক ভাগের সমান, মাঝারি আবেশ মানের জন্য ব্যবহৃত হয়।",
    historySummary: "পাওয়ার ইলেকট্রনিক্স ও নেটওয়ার্ক চোক-এ ব্যাপকভাবে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, উপ-একক)",
    siEquivalent: "১ mH = ০.০০১ H",
    commonUses: "পাওয়ার ইলেকট্রনিক্স, নেটওয়ার্ক ব্লক",
  },
  {
    locale: "bn",
    sourceSlug: "mikrohenry",
    slug: "microhenry",
    category: "enduktans",
    categoryName: "আবেশ",
    unit: "µH",
    name: "মাইক্রোহেনরি",
    symbol: "µH",
    shortDescription: "মাইক্রোহেনরি হেনরির দশ লক্ষ ভাগের এক ভাগের সমান, উচ্চ কম্পাঙ্কের বর্তনীর ছোট কয়েলের জন্য।",
    historySummary: "রেডিও ও উচ্চ কম্পাঙ্কের বর্তনী ডিজাইনে গুরুত্বপূর্ণ ভূমিকা পালন করে।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, উপ-একক)",
    siEquivalent: "১ µH = ০.০০০০০১ H",
    commonUses: "রেডিও বর্তনী, উচ্চ কম্পাঙ্কের প্রযুক্তি",
  },
  {
    locale: "bn",
    sourceSlug: "coulomb",
    slug: "coulomb",
    category: "elektrik_yuk",
    categoryName: "তড়িৎ আধান",
    unit: "C",
    name: "কুলম্ব",
    symbol: "C",
    shortDescription: "কুলম্ব তড়িৎ আধানের SI একক, শার্ল অগুস্তাঁ দ্য কুলম্বের নামে নামকরণ করা হয়েছে।",
    historySummary: "তড়িৎ প্রকৌশল ও পদার্থবিজ্ঞানে আধান প্রকাশের মৌলিক একক।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, ডেরাইভড একক)",
    siEquivalent: "তড়িৎ আধানের মৌলিক SI একক",
    commonUses: "তড়িৎ প্রকৌশল ও পদার্থবিজ্ঞান আধান হিসাব",
  },
  {
    locale: "bn",
    sourceSlug: "milicoulomb",
    slug: "millicoulomb",
    category: "elektrik_yuk",
    categoryName: "তড়িৎ আধান",
    unit: "mC",
    name: "মিলিকুলম্ব",
    symbol: "mC",
    shortDescription: "মিলিকুলম্ব কুলম্বের হাজার ভাগের এক ভাগের সমান, মাঝারি আধান মানের জন্য ব্যবহৃত হয়।",
    historySummary: "ব্যাটারি প্রযুক্তি ও ক্যাপাসিটর আধান হিসাবে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, উপ-একক)",
    siEquivalent: "১ mC = ০.০০১ C",
    commonUses: "ব্যাটারি প্রযুক্তি, ক্যাপাসিটর হিসাব",
  },
  {
    locale: "bn",
    sourceSlug: "mikrocoulomb",
    slug: "microcoulomb",
    category: "elektrik_yuk",
    categoryName: "তড়িৎ আধান",
    unit: "µC",
    name: "মাইক্রোকুলম্ব",
    symbol: "µC",
    shortDescription: "মাইক্রোকুলম্ব কুলম্বের দশ লক্ষ ভাগের এক ভাগের সমান, ইলেকট্রনিক্সে ছোট আধান মানের জন্য ব্যবহৃত হয়।",
    historySummary: "নির্ভুল ইলেকট্রনিক্স ও স্থিতিবিদ্যুৎ হিসাবে ব্যাপকভাবে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, উপ-একক)",
    siEquivalent: "১ µC = ০.০০০০০১ C",
    commonUses: "নির্ভুল ইলেকট্রনিক্স, স্থিতিবিদ্যুৎ হিসাব",
  },
  {
    locale: "bn",
    sourceSlug: "nanocoulomb",
    slug: "nanocoulomb",
    category: "elektrik_yuk",
    categoryName: "তড়িৎ আধান",
    unit: "nC",
    name: "ন্যানোকুলম্ব",
    symbol: "nC",
    shortDescription: "ন্যানোকুলম্ব কুলম্বের একশ কোটি ভাগের এক ভাগের সমান, অত্যন্ত ছোট আধান মানের জন্য ব্যবহৃত হয়।",
    historySummary: "নির্ভুল পদার্থবিজ্ঞান পরীক্ষা ও ছোট স্থিতিবিদ্যুৎ আধান বিশ্লেষণে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, উপ-একক)",
    siEquivalent: "১ nC = ০.০০০০০০০০১ C",
    commonUses: "নির্ভুল পদার্থবিজ্ঞান, স্থিতিবিদ্যুৎ আধান বিশ্লেষণ",
  },
  {
    locale: "bn",
    sourceSlug: "amper-metre",
    slug: "ampere-per-meter",
    category: "manyetik_alan",
    categoryName: "চৌম্বক ক্ষেত্র প্রাবল্য",
    unit: "A/m",
    name: "অ্যাম্পিয়ার/মিটার",
    symbol: "A/m",
    shortDescription: "অ্যাম্পিয়ার/মিটার চৌম্বক ক্ষেত্র প্রাবল্যের SI একক।",
    historySummary: "তড়িৎ প্রকৌশলে চৌম্বক ক্ষেত্র নির্ভুলভাবে বর্ণনায় ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, ডেরাইভড একক)",
    siEquivalent: "চৌম্বক ক্ষেত্র প্রাবল্যের মৌলিক SI একক",
    commonUses: "তড়িৎ প্রকৌশল, চৌম্বক ক্ষেত্র হিসাব",
  },
  {
    locale: "bn",
    sourceSlug: "oersted",
    slug: "oersted",
    category: "manyetik_alan",
    categoryName: "চৌম্বক ক্ষেত্র প্রাবল্য",
    unit: "Oe",
    name: "অরস্টেড",
    symbol: "Oe",
    shortDescription: "অরস্টেড CGS পদ্ধতি থেকে আসা ঐতিহ্যবাহী চৌম্বক ক্ষেত্র প্রাবল্য একক।",
    historySummary: "হান্স ক্রিশ্চিয়ান অরস্টেডের নামে নামকরণ, পুরনো চুম্বকত্ব নথি ও যুক্তরাষ্ট্রে ব্যবহৃত হয়।",
    measurementSystem: "CGS পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "১ Oe ≈ ৭৯.৫৮ A/m",
    commonUses: "পুরনো চুম্বকত্ব নথি ও মার্কিন সাহিত্য",
  },
  {
    locale: "bn",
    sourceSlug: "weber",
    slug: "weber",
    category: "manyetik_aki",
    categoryName: "চৌম্বক ফ্লাক্স",
    unit: "Wb",
    name: "ওয়েবার",
    symbol: "Wb",
    shortDescription: "ওয়েবার চৌম্বক ফ্লাক্সের SI একক, ভিলহেল্ম এডুয়ার্ড ওয়েবারের নামে নামকরণ করা হয়েছে।",
    historySummary: "তড়িৎ প্রকৌশলে চৌম্বক ফ্লাক্স প্রকাশের মৌলিক একক।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, ডেরাইভড একক)",
    siEquivalent: "চৌম্বক ফ্লাক্সের মৌলিক SI একক",
    commonUses: "তড়িৎ প্রকৌশল, ট্রান্সফরমার ডিজাইন",
  },
  {
    locale: "bn",
    sourceSlug: "miliweber",
    slug: "milliweber",
    category: "manyetik_aki",
    categoryName: "চৌম্বক ফ্লাক্স",
    unit: "mWb",
    name: "মিলিওয়েবার",
    symbol: "mWb",
    shortDescription: "মিলিওয়েবার ওয়েবারের হাজার ভাগের এক ভাগের সমান, ছোট চৌম্বক ফ্লাক্স মানের জন্য ব্যবহৃত হয়।",
    historySummary: "ইলেকট্রোমোটর ও ট্রান্সফরমার হিসাবে ব্যবহারিক মান দিতে ব্যবহৃত হয়।",
    measurementSystem: "আন্তর্জাতিক একক পদ্ধতি (SI, উপ-একক)",
    siEquivalent: "১ mWb = ০.০০১ Wb",
    commonUses: "ইলেকট্রোমোটর ও ট্রান্সফরমার হিসাব",
  },
  {
    locale: "bn",
    sourceSlug: "bit",
    slug: "bit",
    category: "veri",
    categoryName: "ডেটা স্টোরেজ",
    unit: "bit",
    name: "বিট",
    symbol: "bit",
    shortDescription: "বিট ডিজিটাল তথ্য প্রক্রিয়াকরণের ক্ষুদ্রতম একক, ০ বা ১ মান নিতে পারে।",
    historySummary: "আধুনিক কম্পিউটার প্রযুক্তি ও তথ্য স্থানান্তরের সম্পূর্ণ ভিত্তি তৈরি করে।",
    measurementSystem: "ডিজিটাল ডেটা একক (মৌলিক একক)",
    siEquivalent: "তথ্য স্থানান্তর হারের মৌলিক একক",
    commonUses: "তথ্য স্থানান্তর হার, ডিজিটাল তথ্য প্রক্রিয়াকরণ",
  },
  {
    locale: "bn",
    sourceSlug: "kilobayt",
    slug: "kilobyte",
    category: "veri",
    categoryName: "ডেটা স্টোরেজ",
    unit: "KB",
    name: "কিলোবাইট",
    symbol: "KB",
    shortDescription: "কিলোবাইট আনুমানিক ১০০০ বাইটের সমান, ছোট ফাইল ও প্রাথমিক স্টোরেজ ডিভাইসে ব্যবহৃত হয়েছে।",
    historySummary: "কম্পিউটার প্রযুক্তির প্রথম দিকে টেক্সট ফাইল ও প্রোগ্রামের জন্য ব্যাপকভাবে ব্যবহৃত হতো।",
    measurementSystem: "ডিজিটাল ডেটা একক (গুণিতক)",
    siEquivalent: "১ KB ≈ ১০০০ বাইট",
    commonUses: "ছোট ফাইল, প্রাথমিক কম্পিউটার প্রযুক্তি",
  },
  {
    locale: "bn",
    sourceSlug: "megabayt",
    slug: "megabyte",
    category: "veri",
    categoryName: "ডেটা স্টোরেজ",
    unit: "MB",
    name: "মেগাবাইট",
    symbol: "MB",
    shortDescription: "মেগাবাইট আনুমানিক দশ লক্ষ বাইটের সমান, ছবি বা নথির মতো মাঝারি ফাইলের জন্য ব্যবহৃত হয়।",
    historySummary: "মাল্টিমিডিয়া ফাইল ও বড় প্রোগ্রামের আবির্ভাবের সাথে সাধারণ স্টোরেজ একক হয়ে উঠেছে।",
    measurementSystem: "ডিজিটাল ডেটা একক (গুণিতক)",
    siEquivalent: "১ MB ≈ ১০,০০,০০০ বাইট",
    commonUses: "ছবি, নথি, মাঝারি সফটওয়্যার ফাইল",
  },
  {
    locale: "bn",
    sourceSlug: "gigabayt",
    slug: "gigabyte",
    category: "veri",
    categoryName: "ডেটা স্টোরেজ",
    unit: "GB",
    name: "গিগাবাইট",
    symbol: "GB",
    shortDescription: "গিগাবাইট আনুমানিক একশ কোটি বাইটের সমান, আধুনিক স্টোরেজ ডিভাইস ও ডেটা পরিমাণ প্রকাশে ব্যবহৃত হয়।",
    historySummary: "আজকের দিনে RAM, হার্ড ডিস্ক ও মোবাইল ডেটা পরিমাণ প্রকাশের মানক একক।",
    measurementSystem: "ডিজিটাল ডেটা একক (গুণিতক)",
    siEquivalent: "১ GB ≈ ১০০,০০,০০,০০০ বাইট",
    commonUses: "RAM, হার্ড ডিস্ক, মোবাইল ডেটা পরিমাণ",
  },
  {
    locale: "bn",
    sourceSlug: "terabayt",
    slug: "terabyte",
    category: "veri",
    categoryName: "ডেটা স্টোরেজ",
    unit: "TB",
    name: "টেরাবাইট",
    symbol: "TB",
    shortDescription: "টেরাবাইট আনুমানিক এক লক্ষ কোটি বাইটের সমান, বড় স্টোরেজ ডিভাইসের জন্য ব্যবহৃত একক।",
    historySummary: "ভিডিও কনটেন্ট ও ক্লাউড স্টোরেজের বৃদ্ধির সাথে বড় ডেটা পরিমাণের মানক একক হয়ে উঠেছে।",
    measurementSystem: "ডিজিটাল ডেটা একক (গুণিতক)",
    siEquivalent: "১ TB ≈ ১০,০০,০০,০০,০০,০০০ বাইট",
    commonUses: "বড় হার্ড ডিস্ক, ভিডিও কনটেন্ট, ক্লাউড স্টোরেজ",
  },
  {
    locale: "bn",
    sourceSlug: "petabayt",
    slug: "petabyte",
    category: "veri",
    categoryName: "ডেটা স্টোরেজ",
    unit: "PB",
    name: "পেটাবাইট",
    symbol: "PB",
    shortDescription: "পেটাবাইট আনুমানিক ১০০০ টেরাবাইটের সমান, ডেটা সেন্টারের অত্যন্ত বড় স্টোরেজ ক্ষমতার জন্য ব্যবহৃত হয়।",
    historySummary: "বৃহৎ ডেটা সেন্টার ও ক্লাউড কম্পিউটিং সেবার বৃদ্ধির সাথে ব্যাপকভাবে প্রচলিত হয়েছে।",
    measurementSystem: "ডিজিটাল ডেটা একক (গুণিতক)",
    siEquivalent: "১ PB ≈ ১০০০ TB",
    commonUses: "বৃহৎ ডেটা সেন্টার, ক্লাউড কম্পিউটিং",
  },
  {
    locale: "bn",
    sourceSlug: "kibibayt",
    slug: "kibibyte",
    category: "veri",
    categoryName: "ডেটা স্টোরেজ",
    unit: "KiB",
    name: "কিবিবাইট",
    symbol: "KiB",
    shortDescription: "কিবিবাইট ঠিক ১০২৪ বাইটের সমান একটি সুনির্দিষ্ট বাইনারি একক, দশমিক কিলোবাইটের সাথে বিভ্রান্তি এড়ায়।",
    historySummary: "১০০০ ও ১০২৪ ভিত্তির মধ্যে অস্পষ্টতা দূর করতে IEC কর্তৃক গৃহীত হয়েছে।",
    measurementSystem: "সুনির্দিষ্ট বাইনারি ডেটা একক (IEC মানদণ্ড)",
    siEquivalent: "১ KiB = ঠিক ১০২৪ বাইট",
    commonUses: "অপারেটিং সিস্টেম ও মেমরির সুনির্দিষ্ট প্রযুক্তিগত নথি",
  },
  {
    locale: "bn",
    sourceSlug: "mebibayt",
    slug: "mebibyte",
    category: "veri",
    categoryName: "ডেটা স্টোরেজ",
    unit: "MiB",
    name: "মেবিবাইট",
    symbol: "MiB",
    shortDescription: "মেবিবাইট ঠিক ১০২৪ কিবিবাইটের সমান একটি সুনির্দিষ্ট বাইনারি একক।",
    historySummary: "দশমিক ও বাইনারি স্টোরেজ নির্দেশকের মধ্যে বিভ্রান্তি এড়াতে সুনির্দিষ্ট প্রযুক্তিগত নথিতে ব্যবহৃত হয়।",
    measurementSystem: "সুনির্দিষ্ট বাইনারি ডেটা একক (IEC মানদণ্ড)",
    siEquivalent: "১ MiB = ঠিক ১০২৪ KiB",
    commonUses: "র‍্যাম মেমরি ক্ষমতার সুনির্দিষ্ট নথি",
  },
  {
    locale: "bn",
    sourceSlug: "gibibayt",
    slug: "gibibyte",
    category: "veri",
    categoryName: "ডেটা স্টোরেজ",
    unit: "GiB",
    name: "গিবিবাইট",
    symbol: "GiB",
    shortDescription: "গিবিবাইট ঠিক ১০২৪ মেবিবাইটের সমান একটি সুনির্দিষ্ট বাইনারি একক।",
    historySummary: "বাণিজ্যিক দশমিক গিগাবাইট থেকে আলাদা করতে ব্যবহৃত মেমরি ক্ষমতার সুনির্দিষ্ট IEC মানদণ্ড।",
    measurementSystem: "সুনির্দিষ্ট বাইনারি ডেটা একক (IEC মানদণ্ড)",
    siEquivalent: "১ GiB = ঠিক ১০২৪ MiB",
    commonUses: "মেমরি ও স্টোরেজ ক্ষমতার সুনির্দিষ্ট নথি",
  },
  {
    locale: "bn",
    sourceSlug: "tebibayt",
    slug: "tebibyte",
    category: "veri",
    categoryName: "ডেটা স্টোরেজ",
    unit: "TiB",
    name: "টেবিবাইট",
    symbol: "TiB",
    shortDescription: "টেবিবাইট ঠিক ১০২৪ গিবিবাইটের সমান একটি সুনির্দিষ্ট বাইনারি একক।",
    historySummary: "বড় স্টোরেজ সিস্টেমের ক্ষমতা সুনির্দিষ্টভাবে নির্ধারণে ব্যবহৃত হয়।",
    measurementSystem: "সুনির্দিষ্ট বাইনারি ডেটা একক (IEC মানদণ্ড)",
    siEquivalent: "১ TiB = ঠিক ১০২৪ GiB",
    commonUses: "বড় স্টোরেজ সিস্টেম ও সুনির্দিষ্ট ডেটা সেন্টার নথি",
  },
  {
    locale: "bn",
    sourceSlug: "22-ayar-altin",
    slug: "22-carat-gold",
    category: "altin_ayar",
    categoryName: "স্বর্ণের ক্যারেট",
    unit: "22K",
    name: "২২ ক্যারেট স্বর্ণ",
    symbol: "22K",
    shortDescription: "২২ ক্যারেট বলতে ৯১.৭% বিশুদ্ধ স্বর্ণের সংকর ধাতু বোঝায়, বিশুদ্ধতা ও কাঠিন্যের মধ্যে ভালো ভারসাম্য।",
    historySummary: "এশিয়া ও মধ্যপ্রাচ্যের অনেক দেশে ঐতিহ্যবাহী গহনার জন্য পছন্দের ক্যারেট মাত্রা।",
    measurementSystem: "ক্যারেট পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "৯১৭/১০০০ বিশুদ্ধ স্বর্ণ",
    commonUses: "এশিয়া ও মধ্যপ্রাচ্যে ঐতিহ্যবাহী গহনা",
  },
  {
    locale: "bn",
    sourceSlug: "18-ayar-altin",
    slug: "18-carat-gold",
    category: "altin_ayar",
    categoryName: "স্বর্ণের ক্যারেট",
    unit: "18K",
    name: "১৮ ক্যারেট স্বর্ণ",
    symbol: "18K",
    shortDescription: "১৮ ক্যারেট বলতে ৭৫% বিশুদ্ধ স্বর্ণের সংকর ধাতু বোঝায়, কাঠিন্য ও মূল্যের মধ্যে ভালো ভারসাম্য দেয়।",
    historySummary: "টেকসই ও রঙের বৈচিত্র্যের কারণে পশ্চিমা গহনা শিল্পে বিশেষভাবে জনপ্রিয়।",
    measurementSystem: "ক্যারেট পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "৭৫০/১০০০ বিশুদ্ধ স্বর্ণ",
    commonUses: "পশ্চিমা গহনা ও বাগদান আংটি",
  },
  {
    locale: "bn",
    sourceSlug: "14-ayar-altin",
    slug: "14-carat-gold",
    category: "altin_ayar",
    categoryName: "স্বর্ণের ক্যারেট",
    unit: "14K",
    name: "১৪ ক্যারেট স্বর্ণ",
    symbol: "14K",
    shortDescription: "১৪ ক্যারেট বলতে ৫৮.৩% বিশুদ্ধ স্বর্ণের সংকর ধাতু বোঝায়, উচ্চতর ক্যারেটের চেয়ে অনেক বেশি টেকসই ও সাশ্রয়ী।",
    historySummary: "উচ্চ টেকসইতা ও তুলনামূলক কম দামের কারণে পশ্চিমা বাজারে দৈনন্দিন গহনায় ব্যাপকভাবে প্রচলিত।",
    measurementSystem: "ক্যারেট পদ্ধতি (SI-এর বাইরে)",
    siEquivalent: "৫৮৩/১০০০ বিশুদ্ধ স্বর্ণ",
    commonUses: "পশ্চিমা বাজারে টেকসই দৈনন্দিন গহনা",
  },
];

export function findBengaliUnitPageBySourceSlug(sourceSlug: string) {
  return bengaliUnitPages.find((page) => page.sourceSlug === sourceSlug);
}

export function findBengaliUnitPage(category: string, unit: string) {
  return bengaliUnitPages.find(
    (page) => page.category === category && page.unit === unit
  );
}
