// صفحات الوحدات باللغة العربية -- محتوى حقيقي لكل وحدة على حدة،
// يبدأ بالوحدات الأساسية لكل فئة من الفئات الاثنتي عشرة الأساسية
// (وليس شرحًا موسعًا لجميع 100+ وحدة بعد -- توسيع لاحق).

export type LocalizedArabicUnitPage = {
  locale: "ar";
  sourceSlug: string;
  slug: string;
  category: string;
  categoryName: string;
  unit: string;
  name: string;
  symbol: string;
  shortDescription: string;
  historySummary: string;
  measurementSystem: string;
  siEquivalent: string;
  commonUses: string;
};

export const arabicUnitPages: LocalizedArabicUnitPage[] = [
  {
    locale: "ar",
    sourceSlug: "metre",
    slug: "meter",
    category: "uzunluk",
    categoryName: "الطول",
    unit: "m",
    name: "متر",
    symbol: "م",
    shortDescription: "المتر هو الوحدة الأساسية للطول في النظام الدولي.",
    historySummary: "منذ عام 1983، يُعرَّف المتر بدقة بأنه المسافة التي يقطعها الضوء في الفراغ خلال 1/299,792,458 من الثانية.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية للطول في النظام الدولي",
    commonUses: "البناء والرياضة والعلوم وقياسات المسافة اليومية",
  },
  {
    locale: "ar",
    sourceSlug: "kilometre",
    slug: "kilometer",
    category: "uzunluk",
    categoryName: "الطول",
    unit: "km",
    name: "كيلومتر",
    symbol: "كم",
    shortDescription: "الكيلومتر يساوي 1000 متر، ويُستخدم للتعبير عن المسافات الطويلة.",
    historySummary: "كجزء من النظام المتري، أصبح الكيلومتر الطريقة العملية للتعبير عن المسافات الطويلة.",
    measurementSystem: "النظام الدولي للوحدات (وحدة مضاعفة)",
    siEquivalent: "1 كم = 1000 م",
    commonUses: "مسافات الطرق والجغرافيا والسفر",
  },
  {
    locale: "ar",
    sourceSlug: "metrekare",
    slug: "square-meter",
    category: "alan",
    categoryName: "المساحة",
    unit: "m²",
    name: "متر مربع",
    symbol: "م²",
    shortDescription: "المتر المربع هو وحدة المساحة الأساسية في النظام الدولي.",
    historySummary: "مشتق مباشرة من وحدة المتر، وهو الطريقة القياسية للتعبير عن مساحات المباني والأراضي.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية للمساحة في النظام الدولي",
    commonUses: "مساحات الغرف والمنازل وقطع الأراضي",
  },
  {
    locale: "ar",
    sourceSlug: "hektar",
    slug: "hectare",
    category: "alan",
    categoryName: "المساحة",
    unit: "ha",
    name: "هكتار",
    symbol: "هك",
    shortDescription: "الهكتار يساوي 10,000 متر مربع، وهو وحدة مساحة كبيرة تُستخدم في قياس الأراضي والزراعة.",
    historySummary: "أُدخل ضمن النظام المتري للتعبير العملي عن مساحات الأراضي.",
    measurementSystem: "النظام الدولي للوحدات (وحدة مضاعفة)",
    siEquivalent: "1 هكتار = 10,000 م²",
    commonUses: "الزراعة وإدارة الأراضي والحراجة",
  },
  {
    locale: "ar",
    sourceSlug: "litre",
    slug: "liter",
    category: "hacim",
    categoryName: "الحجم",
    unit: "L",
    name: "لتر",
    symbol: "ل",
    shortDescription: "اللتر هو وحدة الحجم الأكثر استخدامًا في الحياة اليومية.",
    historySummary: "يُعرَّف بأنه ديسيمتر مكعب واحد، ويُستخدم على نطاق واسع في قياس السوائل حول العالم.",
    measurementSystem: "النظام المتري (متوافق مع النظام الدولي)",
    siEquivalent: "1 لتر = 0.001 م³",
    commonUses: "السوائل والمطبخ وسعة الوقود",
  },
  {
    locale: "ar",
    sourceSlug: "metrekup",
    slug: "cubic-meter",
    category: "hacim",
    categoryName: "الحجم",
    unit: "m³",
    name: "متر مكعب",
    symbol: "م³",
    shortDescription: "المتر المكعب هو وحدة الحجم الأساسية في النظام الدولي.",
    historySummary: "مشتق مباشرة من وحدة الطول، ويُستخدم في الحسابات الصناعية والهندسية للحجم.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية للحجم في النظام الدولي",
    commonUses: "العمليات الصناعية والبناء وسعة التخزين",
  },
  {
    locale: "ar",
    sourceSlug: "kilogram",
    slug: "kilogram",
    category: "kutle",
    categoryName: "الكتلة",
    unit: "kg",
    name: "كيلوغرام",
    symbol: "كغ",
    shortDescription: "الكيلوغرام هو الوحدة الأساسية للكتلة في النظام الدولي.",
    historySummary: "الوحدة الأساسية الوحيدة في النظام الدولي المعرّفة حاليًا عبر ثابت فيزيائي (ثابت بلانك) -- سابقًا كانت تُعرَّف بمرجع مادي من البلاتين والإيريديوم.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية للكتلة في النظام الدولي",
    commonUses: "المطبخ والطب والتجارة والرياضة",
  },
  {
    locale: "ar",
    sourceSlug: "gram",
    slug: "gram",
    category: "kutle",
    categoryName: "الكتلة",
    unit: "g",
    name: "غرام",
    symbol: "غ",
    shortDescription: "الغرام يساوي جزءًا من ألف من الكيلوغرام، ويُستخدم لقياس الكتل الصغيرة.",
    historySummary: "عُرِّف في الأصل عام 1795 بأنه كتلة سنتيمتر مكعب واحد من الماء.",
    measurementSystem: "النظام الدولي للوحدات (وحدة فرعية)",
    siEquivalent: "1 غ = 0.001 كغ",
    commonUses: "وصفات الطهي والمجوهرات والكيمياء",
  },
  {
    locale: "ar",
    sourceSlug: "santigrat",
    slug: "celsius",
    category: "sicaklik",
    categoryName: "درجة الحرارة",
    unit: "C",
    name: "مئوية",
    symbol: "°م",
    shortDescription: "المئوية مقياس حراري شائع يحدد نقطة تجمد الماء عند 0 درجة ونقطة غليانه عند 100 درجة.",
    historySummary: "اقترحه عام 1742 عالم الفلك السويدي أندرس سيلسيوس.",
    measurementSystem: "النظام المتري (متوافق مع النظام الدولي)",
    siEquivalent: "ك = °م + 273.15",
    commonUses: "الطقس والطهي والطب والحياة اليومية",
  },
  {
    locale: "ar",
    sourceSlug: "kelvin",
    slug: "kelvin",
    category: "sicaklik",
    categoryName: "درجة الحرارة",
    unit: "K",
    name: "كلفن",
    symbol: "ك",
    shortDescription: "الكلفن هو الوحدة الأساسية لدرجة الحرارة في النظام الدولي، ويبدأ من الصفر المطلق.",
    historySummary: "سُمّي تيمنًا بالفيزيائي الإنجليزي اللورد كلفن، وهو الوحدة القياسية في الحسابات العلمية والهندسية.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "0 ك = -273.15°م (الصفر المطلق)",
    commonUses: "الفيزياء والفلك والحسابات الهندسية",
  },
  {
    locale: "ar",
    sourceSlug: "saniye",
    slug: "second",
    category: "zaman",
    categoryName: "الزمن",
    unit: "s",
    name: "ثانية",
    symbol: "ث",
    shortDescription: "الثانية هي الوحدة الأساسية للزمن في النظام الدولي.",
    historySummary: "تُعرَّف حاليًا بدقة عبر تردد إشعاع ذرة السيزيوم.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية للزمن في النظام الدولي",
    commonUses: "العلوم والرياضة وقياسات الزمن اليومية",
  },
  {
    locale: "ar",
    sourceSlug: "saat",
    slug: "hour",
    category: "zaman",
    categoryName: "الزمن",
    unit: "h",
    name: "ساعة",
    symbol: "ساعة",
    shortDescription: "الساعة تساوي 60 دقيقة، وهي وحدة الزمن الأكثر استخدامًا في الحياة اليومية.",
    historySummary: "يعود تقسيم اليوم إلى 24 ساعة إلى الحضارتين المصرية والبابلية القديمتين.",
    measurementSystem: "متوافقة مع النظام الدولي، وحدة يومية",
    siEquivalent: "1 ساعة = 3600 ثانية",
    commonUses: "جداول العمل والسفر والتخطيط اليومي",
  },
  {
    locale: "ar",
    sourceSlug: "kilometre-saat",
    slug: "km-per-hour",
    category: "hiz",
    categoryName: "السرعة",
    unit: "km/h",
    name: "كيلومتر في الساعة",
    symbol: "كم/س",
    shortDescription: "كيلومتر في الساعة هي وحدة السرعة الأكثر استخدامًا عالميًا للتعبير عن سرعة السيارات.",
    historySummary: "نتيجة طبيعية للنظام المتري، أصبحت الوحدة القياسية في النقل وحركة المرور.",
    measurementSystem: "النظام الدولي للوحدات (متوافقة)",
    siEquivalent: "1 كم/س = 0.2778 م/ث",
    commonUses: "سرعة السيارات وإشارات الطرق والرياضة",
  },
  {
    locale: "ar",
    sourceSlug: "pascal",
    slug: "pascal",
    category: "basinc",
    categoryName: "الضغط",
    unit: "Pa",
    name: "باسكال",
    symbol: "با",
    shortDescription: "الباسكال هو الوحدة الأساسية للضغط في النظام الدولي.",
    historySummary: "سُمّي تيمنًا بالعالم الفرنسي بليز باسكال.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "1 با = 1 نيوتن/م²",
    commonUses: "الهندسة والأرصاد الجوية والفيزياء",
  },
  {
    locale: "ar",
    sourceSlug: "joule",
    slug: "joule",
    category: "enerji",
    categoryName: "الطاقة",
    unit: "J",
    name: "جول",
    symbol: "ج",
    shortDescription: "الجول هو الوحدة الأساسية للطاقة في النظام الدولي.",
    historySummary: "سُمّي تيمنًا بالفيزيائي الإنجليزي جيمس بريسكوت جول.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية للطاقة في النظام الدولي",
    commonUses: "الفيزياء والهندسة وحسابات الطاقة الغذائية",
  },
  {
    locale: "ar",
    sourceSlug: "bayt",
    slug: "byte",
    category: "veri",
    categoryName: "تخزين البيانات",
    unit: "B",
    name: "بايت",
    symbol: "بايت",
    shortDescription: "البايت هو الوحدة الأساسية لحجم البيانات الرقمية، ويتكون من 8 بت.",
    historySummary: "أصبح الوحدة الأساسية القياسية لقياس حجم البيانات مع تطور تقنية الحاسوب.",
    measurementSystem: "وحدة بيانات رقمية",
    siEquivalent: "1 بايت = 8 بت",
    commonUses: "حجم الملفات وسعة الذاكرة وحركة بيانات الإنترنت",
  },
  {
    locale: "ar",
    sourceSlug: "volt",
    slug: "volt",
    category: "elektrik",
    categoryName: "الكهرباء",
    unit: "V",
    name: "فولت",
    symbol: "ف",
    shortDescription: "الفولت هو الوحدة الأساسية للجهد الكهربائي في النظام الدولي.",
    historySummary: "سُمّي تيمنًا بالفيزيائي الإيطالي أليساندرو فولتا.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية للجهد في النظام الدولي",
    commonUses: "الإلكترونيات ومصادر الطاقة وجهد الشبكة الكهربائية",
  },
  {
    locale: "ar",
    sourceSlug: "amper",
    slug: "ampere",
    category: "elektrik",
    categoryName: "الكهرباء",
    unit: "A",
    name: "أمبير",
    symbol: "أ",
    shortDescription: "الأمبير هو الوحدة الأساسية للتيار الكهربائي في النظام الدولي.",
    historySummary: "سُمّي تيمنًا بالفيزيائي الفرنسي أندريه ماري أمبير.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية للتيار في النظام الدولي",
    commonUses: "قياس التيار وأجهزة الحماية وقدرة المعدات",
  },
  {
    locale: "ar",
    sourceSlug: "24-ayar-altin",
    slug: "24k-gold",
    category: "altin_ayar",
    categoryName: "عيار الذهب",
    unit: "24K",
    name: "ذهب عيار 24",
    symbol: "24K",
    shortDescription: "عيار 24 يعني ذهبًا خالصًا بنسبة 100%، وهو أعلى درجة نقاء.",
    historySummary: "نظام العيار المبني على تقسيم 24 جزءًا مستخدم في صناعة المجوهرات منذ قرون.",
    measurementSystem: "نظام العيار (خارج النظام الدولي)",
    siEquivalent: "999/1000 ذهب خالص",
    commonUses: "سبائك الاستثمار والمجوهرات عالية الجودة",
  },
  {
    locale: "ar",
    sourceSlug: "metrekup-saat",
    slug: "cubic-meter-per-hour",
    category: "debi",
    categoryName: "معدل التدفق",
    unit: "m³/h",
    name: "متر مكعب/ساعة",
    symbol: "م³/س",
    shortDescription: "متر مكعب في الساعة هي وحدة شائعة لقياس معدل تدفق السوائل والغازات.",
    historySummary: "مشتقة من الوحدات الأساسية للحجم والزمن في النظام الدولي.",
    measurementSystem: "النظام الدولي للوحدات (متوافقة)",
    siEquivalent: "1 م³/س = 1/3600 م³/ث",
    commonUses: "أنظمة المياه والتهوية والعمليات الصناعية",
  },
  {
    locale: "ar",
    sourceSlug: "kilogram-metrekup",
    slug: "kg-per-cubic-meter",
    category: "yogunluk",
    categoryName: "الكثافة",
    unit: "kg/m³",
    name: "كيلوغرام/متر مكعب",
    symbol: "كغ/م³",
    shortDescription: "كيلوغرام لكل متر مكعب هي الوحدة الأساسية للكثافة في النظام الدولي.",
    historySummary: "مشتقة مباشرة من الوحدتين الأساسيتين للكتلة والحجم.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية للكثافة في النظام الدولي",
    commonUses: "علوم المواد والهندسة والفيزياء",
  },
  {
    locale: "ar",
    sourceSlug: "newton",
    slug: "newton",
    category: "kuvvet",
    categoryName: "القوة",
    unit: "N",
    name: "نيوتن",
    symbol: "ن",
    shortDescription: "النيوتن هو الوحدة الأساسية للقوة في النظام الدولي.",
    historySummary: "سُمّي تيمنًا بإسحاق نيوتن، ويُعرَّف بأنه القوة اللازمة لإكساب كتلة قدرها كيلوغرام واحد تسارعًا قدره متر واحد لكل ثانية مربعة.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "1 ن = 1 كغ·م/ث²",
    commonUses: "الهندسة والفيزياء وتحليل الهياكل",
  },
  {
    locale: "ar",
    sourceSlug: "newton-metre",
    slug: "newton-meter",
    category: "tork",
    categoryName: "عزم الدوران",
    unit: "N·m",
    name: "نيوتن متر",
    symbol: "ن·م",
    shortDescription: "نيوتن متر هي الوحدة الأساسية لعزم الدوران في النظام الدولي.",
    historySummary: "مشتقة مباشرة من وحدتي القوة والطول في النظام الدولي.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية لعزم الدوران في النظام الدولي",
    commonUses: "عزم المحركات ومفاتيح العزم والتصميم الميكانيكي",
  },
  {
    locale: "ar",
    sourceSlug: "derece",
    slug: "degree",
    category: "aci",
    categoryName: "الزاوية",
    unit: "°",
    name: "درجة",
    symbol: "°",
    shortDescription: "الدرجة هي الوحدة العملية الأكثر شيوعًا للزاوية، وتقسم الدائرة الكاملة إلى 360 جزءًا متساويًا.",
    historySummary: "يعود أصلها إلى الرياضيات البابلية القديمة المبنية على الأساس الستيني.",
    measurementSystem: "خارج النظام الدولي، وحدة شائعة الاستخدام",
    siEquivalent: "1° = π/180 راديان",
    commonUses: "الملاحة والجغرافيا والرسم الهندسي",
  },
  {
    locale: "ar",
    sourceSlug: "hertz",
    slug: "hertz",
    category: "frekans",
    categoryName: "التردد",
    unit: "Hz",
    name: "هرتز",
    symbol: "هرتز",
    shortDescription: "الهرتز هو الوحدة الأساسية للتردد في النظام الدولي.",
    historySummary: "سُمّي تيمنًا بالفيزيائي الألماني هاينريش هرتز.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "1 هرتز = دورة واحدة في الثانية",
    commonUses: "موجات الصوت وتردد التيار الكهربائي وسرعة المعالجات",
  },
  {
    locale: "ar",
    sourceSlug: "metrekup-saniye",
    slug: "cubic-meter-per-second",
    category: "debi_hacimsel",
    categoryName: "معدل التدفق الحجمي",
    unit: "m³/s",
    name: "متر مكعب/ثانية",
    symbol: "م³/ث",
    shortDescription: "متر مكعب في الثانية هي الوحدة الأساسية لمعدل التدفق الحجمي في النظام الدولي.",
    historySummary: "مشتقة مباشرة من وحدتي الحجم والزمن الأساسيتين.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية لمعدل التدفق الحجمي",
    commonUses: "سعة المضخات والتوربينات الكبيرة والعمليات الصناعية",
  },
  {
    locale: "ar",
    sourceSlug: "kilogram-saniye",
    slug: "kilogram-per-second",
    category: "debi_kutlesel",
    categoryName: "معدل التدفق الكتلي",
    unit: "kg/s",
    name: "كيلوغرام/ثانية",
    symbol: "كغ/ث",
    shortDescription: "كيلوغرام في الثانية هي الوحدة الأساسية لمعدل التدفق الكتلي في النظام الدولي.",
    historySummary: "مشتقة مباشرة من وحدتي الكتلة والزمن الأساسيتين.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية لمعدل التدفق الكتلي",
    commonUses: "تصميم العمليات الصناعية وحسابات توازن الكتلة",
  },
  {
    locale: "ar",
    sourceSlug: "amper-metre",
    slug: "ampere-per-meter",
    category: "manyetik_alan",
    categoryName: "المجال المغناطيسي",
    unit: "A/m",
    name: "أمبير/متر",
    symbol: "أ/م",
    shortDescription: "أمبير في المتر هي الوحدة الأساسية لشدة المجال المغناطيسي في النظام الدولي.",
    historySummary: "مشتقة من وحدتي التيار والطول الأساسيتين في النظام الدولي.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية لشدة المجال المغناطيسي",
    commonUses: "تصميم الملفات والمغناطيسات الكهربائية واختبار المواد المغناطيسية",
  },
  {
    locale: "ar",
    sourceSlug: "weber",
    slug: "weber",
    category: "manyetik_aki",
    categoryName: "التدفق المغناطيسي",
    unit: "Wb",
    name: "ويبر",
    symbol: "وب",
    shortDescription: "الويبر هو الوحدة الأساسية للتدفق المغناطيسي في النظام الدولي.",
    historySummary: "سُمّي تيمنًا بالفيزيائي الألماني فيلهلم إدوارد ويبر.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "1 وب = 1 فولت·ثانية",
    commonUses: "تصميم المحولات وحسابات الحث الكهرومغناطيسي",
  },
  {
    locale: "ar",
    sourceSlug: "metrekare-saniye",
    slug: "square-meter-per-second",
    category: "viskozite_kinematik",
    categoryName: "اللزوجة الحركية",
    unit: "m²/s",
    name: "متر مربع/ثانية",
    symbol: "م²/ث",
    shortDescription: "متر مربع في الثانية هي الوحدة الأساسية للزوجة الحركية في النظام الدولي.",
    historySummary: "مشتقة من نسبة اللزوجة الديناميكية إلى الكثافة.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية للزوجة الحركية",
    commonUses: "حسابات ميكانيكا الموائع وعدد رينولدز",
  },
  {
    locale: "ar",
    sourceSlug: "watt-metre-kelvin",
    slug: "watt-per-meter-kelvin",
    category: "isil_iletkenlik",
    categoryName: "الموصلية الحرارية",
    unit: "W/m·K",
    name: "واط/متر كلفن",
    symbol: "و/م·ك",
    shortDescription: "واط لكل متر-كلفن هي الوحدة الأساسية للموصلية الحرارية في النظام الدولي.",
    historySummary: "مشتقة مباشرة من قانون فورييه لانتقال الحرارة بالتوصيل.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية للموصلية الحرارية",
    commonUses: "اختيار مواد العزل الحراري وأداء طاقة المباني",
  },
  {
    locale: "ar",
    sourceSlug: "watt-metrekare",
    slug: "watt-per-square-meter",
    category: "isi_akisi",
    categoryName: "التدفق الحراري",
    unit: "W/m²",
    name: "واط/متر مربع",
    symbol: "و/م²",
    shortDescription: "واط لكل متر مربع هي الوحدة الأساسية للتدفق الحراري في النظام الدولي.",
    historySummary: "مشتقة من الوحدات الأساسية لهندسة انتقال الحرارة.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية للتدفق الحراري",
    commonUses: "حسابات فقدان الحرارة من المباني وتحليل الإشعاع الشمسي",
  },
  {
    locale: "ar",
    sourceSlug: "joule-kilogram-kelvin",
    slug: "joule-per-kilogram-kelvin",
    category: "ozgul_isi",
    categoryName: "الحرارة النوعية",
    unit: "J/kg·K",
    name: "جول/كيلوغرام كلفن",
    symbol: "ج/كغ·ك",
    shortDescription: "جول لكل كيلوغرام-كلفن هي الوحدة الأساسية للحرارة النوعية في النظام الدولي.",
    historySummary: "اعتُمدت مع تطور علم قياس الحرارة، وتوفر طريقة موحدة لمقارنة سعة تسخين المواد.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية للحرارة النوعية",
    commonUses: "علوم المواد والحسابات الديناميكية الحرارية",
  },
  {
    locale: "ar",
    sourceSlug: "metre-saniyekare",
    slug: "meter-per-second-squared",
    category: "ivme",
    categoryName: "التسارع",
    unit: "m/s²",
    name: "متر/ثانية مربعة",
    symbol: "م/ث²",
    shortDescription: "متر في الثانية المربعة هي الوحدة الأساسية للتسارع في النظام الدولي.",
    historySummary: "نتيجة طبيعية لقوانين نيوتن للحركة، مشتقة من وحدتي الطول والزمن.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية للتسارع",
    commonUses: "اختبارات أداء المركبات والحسابات الفيزيائية",
  },
  {
    locale: "ar",
    sourceSlug: "devir-dakika",
    slug: "rpm",
    category: "acisal_hiz",
    categoryName: "السرعة الزاوية",
    unit: "rpm",
    name: "دورة في الدقيقة",
    symbol: "دورة/دقيقة",
    shortDescription: "دورة في الدقيقة (RPM) تعبّر عن عدد الدورات الكاملة التي يقوم بها محرك أو جزء دوّار خلال دقيقة واحدة.",
    historySummary: "أصبحت الوحدة العملية القياسية مع تطور المحركات الاحتراقية والكهربائية.",
    measurementSystem: "خارج النظام الدولي، وحدة هندسية عملية",
    siEquivalent: "1 دورة/دقيقة ≈ 0.10472 راديان/ثانية",
    commonUses: "سرعة المحركات والأقراص الصلبة والمراوح وأجهزة الطرد المركزي",
  },
  {
    locale: "ar",
    sourceSlug: "watt",
    slug: "watt",
    category: "guc",
    categoryName: "القدرة",
    unit: "W",
    name: "واط",
    symbol: "و",
    shortDescription: "الواط هو الوحدة الأساسية للقدرة في النظام الدولي.",
    historySummary: "أصبح الواط اللغة القياسية للتعبير عن القدرة في الهندسة الكهربائية والميكانيكية.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية للقدرة في النظام الدولي",
    commonUses: "تصنيف الأجهزة والأحمال الكهربائية وقدرة المحركات",
  },
  {
    locale: "ar",
    sourceSlug: "kilogram-metre-saniye",
    slug: "kilogram-meter-per-second",
    category: "momentum",
    categoryName: "الزخم",
    unit: "kg·m/s",
    name: "كيلوغرام متر/ثانية",
    symbol: "كغ·م/ث",
    shortDescription: "كيلوغرام متر في الثانية هي الوحدة الأساسية للزخم في النظام الدولي.",
    historySummary: "مشتقة مباشرة من حاصل ضرب الكتلة في السرعة.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية للزخم",
    commonUses: "تحليل التصادمات وحسابات الدفع في الفيزياء",
  },
  {
    locale: "ar",
    sourceSlug: "pascal-saniye",
    slug: "pascal-second",
    category: "viskozite_dinamik",
    categoryName: "اللزوجة الديناميكية",
    unit: "Pa·s",
    name: "باسكال ثانية",
    symbol: "با·ث",
    shortDescription: "باسكال ثانية هي الوحدة الأساسية للزوجة الديناميكية في النظام الدولي.",
    historySummary: "مشتقة من وحدتي الضغط والزمن الأساسيتين.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية للزوجة الديناميكية",
    commonUses: "ميكانيكا الموائع وحساب عدد رينولدز",
  },
  {
    locale: "ar",
    sourceSlug: "ohm",
    slug: "ohm",
    category: "elektrik_direnc",
    categoryName: "المقاومة الكهربائية",
    unit: "Ω",
    name: "أوم",
    symbol: "أوم",
    shortDescription: "الأوم هو الوحدة الأساسية للمقاومة الكهربائية في النظام الدولي.",
    historySummary: "سُمّي تيمنًا بالفيزيائي الألماني جورج سيمون أوم.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "1 أوم = 1 فولت/أمبير",
    commonUses: "تصميم الدوائر الكهربائية وقانون أوم",
  },
  {
    locale: "ar",
    sourceSlug: "farad",
    slug: "farad",
    category: "kapasitans",
    categoryName: "السعة الكهربائية",
    unit: "F",
    name: "فاراد",
    symbol: "ف",
    shortDescription: "الفاراد هو الوحدة الأساسية للسعة الكهربائية في النظام الدولي.",
    historySummary: "سُمّي تيمنًا بالعالم الإنجليزي مايكل فاراداي.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية للسعة في النظام الدولي",
    commonUses: "تصميم المكثفات والدوائر الإلكترونية",
  },
  {
    locale: "ar",
    sourceSlug: "henry",
    slug: "henry",
    category: "enduktans",
    categoryName: "الحث الكهربائي",
    unit: "H",
    name: "هنري",
    symbol: "هنري",
    shortDescription: "الهنري هو الوحدة الأساسية للحث الكهربائي في النظام الدولي.",
    historySummary: "سُمّي تيمنًا بالعالم الأمريكي جوزيف هنري.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية للحث في النظام الدولي",
    commonUses: "تصميم الملفات والمحولات",
  },
  {
    locale: "ar",
    sourceSlug: "metre-saniye",
    slug: "meter-per-second",
    category: "hiz",
    categoryName: "السرعة",
    unit: "m/s",
    name: "متر/ثانية",
    symbol: "م/ث",
    shortDescription: "متر في الثانية هي الوحدة الأساسية للسرعة في النظام الدولي.",
    historySummary: "مشتقة مباشرة من وحدتي الطول والزمن الأساسيتين.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية للسرعة في النظام الدولي",
    commonUses: "الفيزياء والهندسة والحسابات العلمية",
  },
  {
    locale: "ar",
    sourceSlug: "bar",
    slug: "bar",
    category: "basinc",
    categoryName: "الضغط",
    unit: "bar",
    name: "بار",
    symbol: "بار",
    shortDescription: "البار وحدة ضغط شائعة تقارب الضغط الجوي عند مستوى سطح البحر تقريبًا.",
    historySummary: "اعتُمد لتسهيل التعبير عن قيم الضغط الجوي والصناعي بأرقام عملية.",
    measurementSystem: "خارج النظام الدولي، وحدة شائعة",
    siEquivalent: "1 بار = 100,000 باسكال",
    commonUses: "الأرصاد الجوية وأنظمة الضغط الصناعية وإطارات السيارات",
  },
  {
    locale: "ar",
    sourceSlug: "kilovatsaat",
    slug: "kilowatt-hour",
    category: "enerji",
    categoryName: "الطاقة",
    unit: "kWh",
    name: "كيلوواط ساعة",
    symbol: "ك.و.س",
    shortDescription: "كيلوواط ساعة هي وحدة الطاقة الأكثر استخدامًا في فواتير الكهرباء.",
    historySummary: "أصبحت الوحدة العملية القياسية لقياس استهلاك الطاقة الكهربائية المنزلية والصناعية.",
    measurementSystem: "خارج النظام الدولي، وحدة تجارية شائعة",
    siEquivalent: "1 ك.و.س = 3,600,000 جول",
    commonUses: "فواتير الكهرباء وسعة البطاريات ومقارنات استهلاك الطاقة",
  },
  {
    locale: "ar",
    sourceSlug: "kilobayt",
    slug: "kilobyte",
    category: "veri",
    categoryName: "تخزين البيانات",
    unit: "KB",
    name: "كيلوبايت",
    symbol: "ك.ب",
    shortDescription: "الكيلوبايت تساوي 1000 بايت (أو 1024 حسب النظام المستخدم)، وتُستخدم لقياس أحجام الملفات الصغيرة.",
    historySummary: "أصبحت الوحدة العملية الأولى للتعبير عن أحجام البيانات مع تطور الحواسيب المبكرة.",
    measurementSystem: "وحدة بيانات رقمية",
    siEquivalent: "1 ك.ب = 1000 بايت (أو 1024 بايت في النظام الثنائي)",
    commonUses: "أحجام الملفات النصية والصور الصغيرة",
  },
  {
    locale: "ar",
    sourceSlug: "18-ayar-altin",
    slug: "18k-gold",
    category: "altin_ayar",
    categoryName: "عيار الذهب",
    unit: "18K",
    name: "ذهب عيار 18",
    symbol: "18K",
    shortDescription: "عيار 18 يعني سبيكة من 75% ذهب خالص و25% معادن أخرى، وهو شائع جدًا في المجوهرات اليومية.",
    historySummary: "يوازن بين نقاء الذهب ومتانة السبيكة، مما يجعله خيارًا شائعًا لقطع المجوهرات القابلة للاستخدام اليومي.",
    measurementSystem: "نظام العيار (خارج النظام الدولي)",
    siEquivalent: "750/1000 ذهب خالص",
    commonUses: "المجوهرات اليومية والخواتم والأساور",
  },
  {
    locale: "ar",
    sourceSlug: "kilowatt",
    slug: "kilowatt",
    category: "guc",
    categoryName: "القدرة",
    unit: "kW",
    name: "كيلوواط",
    symbol: "ك.و",
    shortDescription: "الكيلوواط يساوي 1000 واط، ويُستخدم للتعبير عن قدرات أكبر بشكل عملي.",
    historySummary: "أصبح شائعًا لأن كثيرًا من قدرات الآلات والمعدات العملية تقع في نطاق الآلاف من الواط.",
    measurementSystem: "النظام الدولي للوحدات (وحدة مضاعفة)",
    siEquivalent: "1 ك.و = 1000 و",
    commonUses: "أنظمة التكييف والمولدات وقدرة الآلات",
  },
  {
    locale: "ar",
    sourceSlug: "kilohertz",
    slug: "kilohertz",
    category: "frekans",
    categoryName: "التردد",
    unit: "kHz",
    name: "كيلوهرتز",
    symbol: "ك.هرتز",
    shortDescription: "الكيلوهرتز يساوي 1000 هرتز، ويُستخدم للترددات الصوتية والراديوية المتوسطة.",
    historySummary: "أصبح الطريقة القياسية للتعبير عن ترددات إذاعة AM مع تطور البث الإذاعي.",
    measurementSystem: "النظام الدولي للوحدات (وحدة مضاعفة)",
    siEquivalent: "1 ك.هرتز = 1000 هرتز",
    commonUses: "ترددات إذاعة AM ومعالجة الصوت والأجهزة فوق الصوتية",
  },
  {
    locale: "ar",
    sourceSlug: "radyan",
    slug: "radian",
    category: "aci",
    categoryName: "الزاوية",
    unit: "rad",
    name: "راديان",
    symbol: "راد",
    shortDescription: "الراديان هو الوحدة الأساسية للزاوية في النظام الدولي.",
    historySummary: "اقترحه عام 1873 الفيزيائي الاسكتلندي جيمس طومسون، واعتُمد لملاءمته الطبيعية للحسابات الرياضية.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية للزاوية (2π راد = 360°)",
    commonUses: "المثلثات والحسابات الهندسية وصيغ السرعة الزاوية",
  },
  {
    locale: "ar",
    sourceSlug: "coulomb",
    slug: "coulomb",
    category: "elektrik_yuk",
    categoryName: "الشحنة الكهربائية",
    unit: "C",
    name: "كولوم",
    symbol: "ك",
    shortDescription: "الكولوم هو الوحدة الأساسية للشحنة الكهربائية في النظام الدولي.",
    historySummary: "سُمّي تيمنًا بالفيزيائي الفرنسي شارل أوغستان دي كولوم.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية للشحنة في النظام الدولي",
    commonUses: "سعة البطاريات وتحليل الكهرباء الساكنة",
  },
  {
    locale: "ar",
    sourceSlug: "litre-dakika",
    slug: "liter-per-minute",
    category: "debi",
    categoryName: "معدل التدفق",
    unit: "L/min",
    name: "لتر/دقيقة",
    symbol: "ل/د",
    shortDescription: "لتر في الدقيقة وحدة عملية شائعة لقياس معدل تدفق السوائل الصغيرة والمتوسطة.",
    historySummary: "شائعة في أنظمة المياه والمضخات الصغيرة نظرًا لسهولة قراءتها بأرقام عملية.",
    measurementSystem: "النظام المتري (متوافق مع النظام الدولي)",
    siEquivalent: "1 ل/د = 0.001/60 م³/ث",
    commonUses: "أنظمة الري والمضخات المنزلية وأجهزة الترشيح",
  },
  {
    locale: "ar",
    sourceSlug: "gram-santimetrekup",
    slug: "gram-per-cubic-centimeter",
    category: "yogunluk",
    categoryName: "الكثافة",
    unit: "g/cm³",
    name: "غرام/سنتيمتر مكعب",
    symbol: "غ/سم³",
    shortDescription: "غرام لكل سنتيمتر مكعب وحدة كثافة عملية شائعة في الكيمياء وعلوم المواد.",
    historySummary: "توفر أرقامًا عملية عند التعامل مع كثافات المواد الصلبة والسوائل المخبرية.",
    measurementSystem: "النظام المتري (متوافق مع النظام الدولي)",
    siEquivalent: "1 غ/سم³ = 1000 كغ/م³",
    commonUses: "الكيمياء وعلوم المواد وتحديد نقاء المعادن",
  },
  {
    locale: "ar",
    sourceSlug: "kilogram-kuvvet",
    slug: "kilogram-force",
    category: "kuvvet",
    categoryName: "القوة",
    unit: "kgf",
    name: "كيلوغرام قوة",
    symbol: "كغف",
    shortDescription: "كيلوغرام القوة وحدة قوة تقليدية خارج النظام الدولي، لا تزال شائعة في بعض الوثائق الهندسية القديمة.",
    historySummary: "استُخدمت قبل التوحيد الكامل للنظام الدولي، وتساوي وزن كيلوغرام واحد تحت الجاذبية الأرضية القياسية.",
    measurementSystem: "خارج النظام الدولي، وحدة تقليدية",
    siEquivalent: "1 كغف = 9.80665 نيوتن",
    commonUses: "الوثائق الهندسية القديمة ومفاتيح العزم واختبارات الشد",
  },
  {
    locale: "ar",
    sourceSlug: "pound-fit",
    slug: "pound-foot",
    category: "tork",
    categoryName: "عزم الدوران",
    unit: "lb·ft",
    name: "باوند قدم",
    symbol: "باوند·قدم",
    shortDescription: "باوند قدم وحدة عزم دوران شائعة في الولايات المتحدة والمملكة المتحدة.",
    historySummary: "مشتقة من النظام الإمبراطوري البريطاني، لا تزال معيارًا في مواصفات محركات السيارات الأمريكية.",
    measurementSystem: "النظام الإمبراطوري/الأمريكي (خارج النظام الدولي)",
    siEquivalent: "1 باوند·قدم ≈ 1.356 نيوتن·متر",
    commonUses: "مواصفات محركات السيارات الأمريكية ومفاتيح العزم",
  },
  {
    locale: "ar",
    sourceSlug: "galon-dakika",
    slug: "gallons-per-minute",
    category: "debi_hacimsel",
    categoryName: "معدل التدفق الحجمي",
    unit: "gpm",
    name: "غالون/دقيقة",
    symbol: "GPM",
    shortDescription: "غالون في الدقيقة وحدة أمريكية شائعة للتعبير عن سعة المضخات وأنظمة المياه.",
    historySummary: "مبنية على الغالون الأمريكي، وأصبحت المعيار العملي في صناعة المضخات وأنظمة الري بأمريكا الشمالية.",
    measurementSystem: "النظام الإمبراطوري/الأمريكي (خارج النظام الدولي)",
    siEquivalent: "1 GPM ≈ 0.0000631 م³/ث",
    commonUses: "سعة مضخات المياه وأنظمة الري والنقل الصناعي للسوائل",
  },
  {
    locale: "ar",
    sourceSlug: "kilogram-saat",
    slug: "kilogram-per-hour",
    category: "debi_kutlesel",
    categoryName: "معدل التدفق الكتلي",
    unit: "kg/h",
    name: "كيلوغرام/ساعة",
    symbol: "كغ/س",
    shortDescription: "كيلوغرام في الساعة وحدة عملية للتعبير عن معدلات التدفق الكتلي الصغيرة نسبيًا.",
    historySummary: "أصبحت شائعة للتعبير بشكل عملي عن التدفقات الصناعية والمخبرية الصغيرة نسبيًا.",
    measurementSystem: "النظام الدولي للوحدات (وحدة مشتقة)",
    siEquivalent: "1 كغ/س = 1/3600 كغ/ث ≈ 0.000278 كغ/ث",
    commonUses: "خطوط إنتاج الصناعات الغذائية والكيميائية وأنظمة الجرعات المخبرية",
  },
  {
    locale: "ar",
    sourceSlug: "oersted",
    slug: "oersted",
    category: "manyetik_alan",
    categoryName: "المجال المغناطيسي",
    unit: "Oe",
    name: "أورستد",
    symbol: "أورستد",
    shortDescription: "الأورستد وحدة شدة المجال المغناطيسي في نظام CGS، لا تزال مستخدمة في صناعة المواد المغناطيسية.",
    historySummary: "سُمّيت تيمنًا بالفيزيائي الدنماركي هانس كريستيان أورستد مكتشف الكهرومغناطيسية.",
    measurementSystem: "نظام CGS (خارج النظام الدولي)",
    siEquivalent: "1 أورستد ≈ 79.5775 أمبير/متر",
    commonUses: "صناعة المغناطيس والمواد المغناطيسية وخصائص وسائط التسجيل المغناطيسي",
  },
  {
    locale: "ar",
    sourceSlug: "miliweber",
    slug: "milliweber",
    category: "manyetik_aki",
    categoryName: "التدفق المغناطيسي",
    unit: "mWb",
    name: "ميلي ويبر",
    symbol: "م.وب",
    shortDescription: "ميلي ويبر يساوي جزءًا من ألف من الويبر، ويُستخدم لقيم التدفق المغناطيسي الأصغر.",
    historySummary: "أصبحت شائعة للتعبير العملي عن قيم التدفق المغناطيسي في تصميم الملفات والمستشعرات الصغيرة.",
    measurementSystem: "النظام الدولي للوحدات (وحدة فرعية)",
    siEquivalent: "1 م.وب = 0.001 وب",
    commonUses: "تصميم الملفات والمستشعرات الصغيرة والدوائر الإلكترونية",
  },
  {
    locale: "ar",
    sourceSlug: "santipoise",
    slug: "centipoise",
    category: "viskozite_dinamik",
    categoryName: "اللزوجة الديناميكية",
    unit: "cP",
    name: "سنتيبواز",
    symbol: "سنتيبواز",
    shortDescription: "السنتيبواز وحدة عملية شائعة للزوجة الديناميكية، ولزوجة الماء عند درجة حرارة الغرفة تقارب 1 سنتيبواز.",
    historySummary: "مشتقة من وحدة البواز في نظام CGS، ولا تزال معيارًا صناعيًا شائعًا لوصف لزوجة السوائل.",
    measurementSystem: "نظام CGS (خارج النظام الدولي)",
    siEquivalent: "1 سنتيبواز = 0.001 باسكال ثانية",
    commonUses: "صناعة الزيوت والمواد الغذائية السائلة ومستحضرات التجميل",
  },
  {
    locale: "ar",
    sourceSlug: "btu-saat-fit-f",
    slug: "btu-per-hour-foot-f",
    category: "isil_iletkenlik",
    categoryName: "الموصلية الحرارية",
    unit: "Btu/h·ft·°F",
    name: "وحدة حرارية بريطانية/ساعة قدم فهرنهايت",
    symbol: "Btu/h·ft·°F",
    shortDescription: "وحدة تقليدية للموصلية الحرارية تُستخدم في النظام الأمريكي.",
    historySummary: "أصبحت جزءًا من الوثائق الفنية الأمريكية في مجالي العزل الحراري وتكييف الهواء.",
    measurementSystem: "النظام الإمبراطوري/الأمريكي (خارج النظام الدولي)",
    siEquivalent: "1 Btu/(h·ft·°F) ≈ 1.730735 واط/(م·ك)",
    commonUses: "وثائق العزل الحراري وأنظمة التكييف الأمريكية",
  },
  {
    locale: "ar",
    sourceSlug: "kilowatt-metrekare",
    slug: "kilowatt-per-square-meter",
    category: "isi_akisi",
    categoryName: "التدفق الحراري",
    unit: "kW/m²",
    name: "كيلوواط/متر مربع",
    symbol: "ك.و/م²",
    shortDescription: "كيلوواط لكل متر مربع وحدة عملية للتعبير عن قيم التدفق الحراري الكبيرة.",
    historySummary: "أصبحت شائعة للتعبير عن قيم التدفق الحراري الكبيرة بشكل عملي وقابل للقراءة.",
    measurementSystem: "النظام الدولي للوحدات (وحدة مضاعفة)",
    siEquivalent: "1 ك.و/م² = 1000 واط/م²",
    commonUses: "حسابات التدفق الحراري للأفران الصناعية والمراجل والإشعاع الشمسي المكثف",
  },
  {
    locale: "ar",
    sourceSlug: "kalori-gram-kelvin",
    slug: "calorie-per-gram-kelvin",
    category: "ozgul_isi",
    categoryName: "الحرارة النوعية",
    unit: "cal/g·K",
    name: "سعرة حرارية/غرام كلفن",
    symbol: "سعرة/غ·ك",
    shortDescription: "تُعبّر عن الحرارة النوعية بوحدة السعرة الحرارية التقليدية؛ حُددت الحرارة النوعية للماء بأنها تساوي بالضبط 1 سعرة/غ·ك.",
    historySummary: "يعود تعريف السعرة الحرارية تاريخيًا إلى سعة تسخين الماء، ولا تزال هذه الوحدة شائعة في الكيمياء وعلم التغذية.",
    measurementSystem: "خارج النظام الدولي، وحدة تقليدية",
    siEquivalent: "1 سعرة/غ·ك = 4.184 جول/كغ·ك",
    commonUses: "حسابات المختبرات الكيميائية وعلم التغذية والكتب الدراسية في الديناميكا الحرارية",
  },
  {
    locale: "ar",
    sourceSlug: "yercekimi-ivmesi",
    slug: "standard-gravity",
    category: "ivme",
    categoryName: "التسارع",
    unit: "g0",
    name: "تسارع الجاذبية القياسي",
    symbol: "g",
    shortDescription: "تسارع الجاذبية القياسي هو ثابت مرجعي يساوي 9.80665 م/ث²، يُستخدم للتعبير عن التسارع بالنسبة لجاذبية الأرض.",
    historySummary: "حُدد عام 1901 من قبل اللجنة الدولية للأوزان والمقاييس كقيمة مرجعية ثابتة، مستقلة عن اختلافات الجاذبية المحلية.",
    measurementSystem: "ثابت مرجعي دولي (خارج النظام الدولي، قيمة مُعرَّفة)",
    siEquivalent: "1 g = 9.80665 م/ث²",
    commonUses: "تسارع الصواريخ والطائرات، اختبارات تصادم المركبات، تدريب رواد الفضاء",
  },
  {
    locale: "ar",
    sourceSlug: "radyan-saniye",
    slug: "radian-per-second",
    category: "acisal_hiz",
    categoryName: "السرعة الزاوية",
    unit: "rad/s",
    name: "راديان/ثانية",
    symbol: "راد/ث",
    shortDescription: "راديان في الثانية هي الوحدة الأساسية للسرعة الزاوية في النظام الدولي.",
    historySummary: "أصبحت الوحدة الطبيعية لحسابات السرعة الزاوية والتسارع الزاوي بعد اعتماد الراديان كوحدة زاوية في النظام الدولي.",
    measurementSystem: "النظام الدولي للوحدات",
    siEquivalent: "الوحدة الأساسية للسرعة الزاوية",
    commonUses: "هندسة الديناميكا الدورانية وتحليل المحركات والتوربينات والروبوتات",
  },
  {
    locale: "ar",
    sourceSlug: "newton-saniye",
    slug: "newton-second",
    category: "momentum",
    categoryName: "الزخم",
    unit: "N·s",
    name: "نيوتن ثانية",
    symbol: "ن·ث",
    shortDescription: "نيوتن ثانية وحدة الدفع (Impulse)، وهي مكافئة أبعاديًا للزخم.",
    historySummary: "تنشأ بشكل طبيعي من نظرية الدفع والزخم؛ حاصل ضرب القوة المؤثرة على جسم في الزمن يساوي التغير في زخمه.",
    measurementSystem: "النظام الدولي للوحدات (وحدة مشتقة)",
    siEquivalent: "1 ن·ث = 1 كغ·م/ث",
    commonUses: "تحليل التصادمات والصدمات ودفع الصواريخ والميكانيكا الحيوية الرياضية",
  },
  {
    locale: "ar",
    sourceSlug: "kiloohm",
    slug: "kiloohm",
    category: "elektrik_direnc",
    categoryName: "المقاومة الكهربائية",
    unit: "kΩ",
    name: "كيلوأوم",
    symbol: "ك.أوم",
    shortDescription: "الكيلوأوم يساوي 1000 أوم، ويُستخدم للتعبير عن قيم المقاومة الأكبر بشكل عملي.",
    historySummary: "أصبح شائعًا في الإلكترونيات لأن قيم المقاومات العملية غالبًا ما تقع في نطاق الآلاف من الأومات.",
    measurementSystem: "النظام الدولي للوحدات (وحدة مضاعفة)",
    siEquivalent: "1 ك.أوم = 1000 أوم",
    commonUses: "تصميم الدوائر الإلكترونية وحسابات قانون أوم",
  },
  {
    locale: "ar",
    sourceSlug: "mikrofarad",
    slug: "microfarad",
    category: "kapasitans",
    categoryName: "السعة الكهربائية",
    unit: "µF",
    name: "ميكروفاراد",
    symbol: "µF",
    shortDescription: "الميكروفاراد يساوي جزءًا من مليون من الفاراد، وهي القيمة العملية الأكثر شيوعًا للمكثفات.",
    historySummary: "بما أن الفاراد وحدة كبيرة جدًا عمليًا، أصبح الميكروفاراد الوحدة القياسية المستخدمة في وسم المكثفات التجارية.",
    measurementSystem: "النظام الدولي للوحدات (وحدة فرعية)",
    siEquivalent: "1 µF = 0.000001 فاراد",
    commonUses: "وسم المكثفات التجارية وتصميم دوائر التغذية الكهربائية",
  },
  {
    locale: "ar",
    sourceSlug: "milihenry",
    slug: "millihenry",
    category: "enduktans",
    categoryName: "الحث الكهربائي",
    unit: "mH",
    name: "ميلي هنري",
    symbol: "م.هنري",
    shortDescription: "ميلي هنري يساوي جزءًا من ألف من الهنري، وهي قيمة عملية شائعة لملفات الدوائر الإلكترونية.",
    historySummary: "أصبحت الوحدة العملية الشائعة لوسم الملفات الصغيرة والمتوسطة في الدوائر الإلكترونية.",
    measurementSystem: "النظام الدولي للوحدات (وحدة فرعية)",
    siEquivalent: "1 م.هنري = 0.001 هنري",
    commonUses: "تصميم الملفات الصغيرة ومرشحات الدوائر الإلكترونية",
  },
  {
    locale: "ar",
    sourceSlug: "milicoulomb",
    slug: "millicoulomb",
    category: "elektrik_yuk",
    categoryName: "الشحنة الكهربائية",
    unit: "mC",
    name: "ميلي كولوم",
    symbol: "م.ك",
    shortDescription: "ميلي كولوم يساوي جزءًا من ألف من الكولوم، ويُستخدم للتعبير عن كميات الشحنة العملية الأصغر.",
    historySummary: "أصبحت وحدة عملية شائعة في حسابات سعة البطاريات الصغيرة والكهرباء الساكنة.",
    measurementSystem: "النظام الدولي للوحدات (وحدة فرعية)",
    siEquivalent: "1 م.ك = 0.001 كولوم",
    commonUses: "حسابات سعة البطاريات الصغيرة وتحليل الكهرباء الساكنة",
  },
  {
    locale: "ar", sourceSlug: "santimetre", slug: "centimeter", category: "uzunluk", categoryName: "الطول",
    unit: "cm", name: "سنتيمتر", symbol: "سم",
    shortDescription: "السنتيمتر يساوي جزءًا من مئة من المتر، ويُستخدم لقياس الأطوال الصغيرة والمتوسطة.",
    historySummary: "جزء من النظام المتري، شائع الاستخدام في القياسات اليومية والملابس.",
    measurementSystem: "النظام الدولي للوحدات (وحدة فرعية)", siEquivalent: "1 سم = 0.01 م",
    commonUses: "قياسات الجسم والملابس والأدوات المكتبية",
  },
  {
    locale: "ar", sourceSlug: "milimetre", slug: "millimeter", category: "uzunluk", categoryName: "الطول",
    unit: "mm", name: "مليمتر", symbol: "مم",
    shortDescription: "المليمتر يساوي جزءًا من ألف من المتر، ويُستخدم للقياسات الدقيقة.",
    historySummary: "جزء من النظام المتري، ضروري في الهندسة الدقيقة والتصنيع.",
    measurementSystem: "النظام الدولي للوحدات (وحدة فرعية)", siEquivalent: "1 مم = 0.001 م",
    commonUses: "الهندسة الميكانيكية والتصنيع الدقيق والطباعة",
  },
  {
    locale: "ar", sourceSlug: "fit", slug: "foot", category: "uzunluk", categoryName: "الطول",
    unit: "ft", name: "قدم", symbol: "قدم",
    shortDescription: "القدم وحدة طول تقليدية شائعة في الولايات المتحدة والمملكة المتحدة.",
    historySummary: "من أقدم وحدات القياس البشرية، مبنية تاريخيًا على طول القدم البشرية.",
    measurementSystem: "النظام الإمبراطوري/الأمريكي (خارج النظام الدولي)", siEquivalent: "1 قدم = 0.3048 م",
    commonUses: "البناء والطيران والقياسات اليومية الأمريكية والبريطانية",
  },
  {
    locale: "ar", sourceSlug: "inc", slug: "inch", category: "uzunluk", categoryName: "الطول",
    unit: "in", name: "إنش", symbol: "إنش",
    shortDescription: "الإنش وحدة طول تقليدية تُستخدم للقياسات الصغيرة في الولايات المتحدة والمملكة المتحدة.",
    historySummary: "استُخدم تاريخيًا بناءً على عرض الإبهام البشري.",
    measurementSystem: "النظام الإمبراطوري/الأمريكي (خارج النظام الدولي)", siEquivalent: "1 إنش = 2.54 سم",
    commonUses: "أحجام الشاشات والأدوات وقياسات الأجهزة الإلكترونية",
  },
  {
    locale: "ar", sourceSlug: "yarda", slug: "yard", category: "uzunluk", categoryName: "الطول",
    unit: "yd", name: "ياردة", symbol: "يارد",
    shortDescription: "الياردة وحدة طول تقليدية شائعة في الرياضة والقياسات الأمريكية والبريطانية.",
    historySummary: "استُخدمت تاريخيًا في القياسات البريطانية، وتُستخدم اليوم كثيرًا في كرة القدم الأمريكية والغولف.",
    measurementSystem: "النظام الإمبراطوري/الأمريكي (خارج النظام الدولي)", siEquivalent: "1 يارد = 0.9144 م",
    commonUses: "الرياضة الأمريكية والقياسات العقارية",
  },
  {
    locale: "ar", sourceSlug: "mil", slug: "mile", category: "uzunluk", categoryName: "الطول",
    unit: "mi", name: "ميل", symbol: "ميل",
    shortDescription: "الميل وحدة مسافة طويلة تُستخدم في الولايات المتحدة والمملكة المتحدة.",
    historySummary: "يعود أصله إلى الميل الروماني القديم (mille passus أي ألف خطوة).",
    measurementSystem: "النظام الإمبراطوري/الأمريكي (خارج النظام الدولي)", siEquivalent: "1 ميل = 1609.344 م",
    commonUses: "مسافات الطرق والسفر في أمريكا الشمالية والمملكة المتحدة",
  },
  {
    locale: "ar", sourceSlug: "miligram", slug: "milligram", category: "kutle", categoryName: "الكتلة",
    unit: "mg", name: "مليغرام", symbol: "ملغ",
    shortDescription: "المليغرام يساوي جزءًا من ألف من الغرام، ويُستخدم لقياس الكتل الصغيرة جدًا.",
    historySummary: "أساسي في الطب والصيدلة لدقة الجرعات الدوائية.",
    measurementSystem: "النظام الدولي للوحدات (وحدة فرعية)", siEquivalent: "1 ملغ = 0.001 غ",
    commonUses: "الجرعات الدوائية والمكملات الغذائية والكيمياء التحليلية",
  },
  {
    locale: "ar", sourceSlug: "ton", slug: "tonne", category: "kutle", categoryName: "الكتلة",
    unit: "ton", name: "طن", symbol: "طن",
    shortDescription: "الطن المتري يساوي 1000 كيلوغرام، ويُستخدم للكتل الكبيرة جدًا.",
    historySummary: "اعتُمد كوحدة عملية للتعبير عن الكتل الصناعية والتجارية الضخمة.",
    measurementSystem: "النظام الدولي للوحدات (وحدة مضاعفة)", siEquivalent: "1 طن = 1000 كغ",
    commonUses: "الشحن والصناعة والزراعة على نطاق واسع",
  },
  {
    locale: "ar", sourceSlug: "pound", slug: "pound", category: "kutle", categoryName: "الكتلة",
    unit: "lb", name: "باوند", symbol: "رطل",
    shortDescription: "الباوند (الرطل) وحدة كتلة تقليدية شائعة في الولايات المتحدة والمملكة المتحدة.",
    historySummary: "مشتق من الرطل الروماني القديم (libra)، ولا يزال شائعًا في القياسات اليومية الأمريكية.",
    measurementSystem: "النظام الإمبراطوري/الأمريكي (خارج النظام الدولي)", siEquivalent: "1 رطل = 0.453592 كغ",
    commonUses: "وزن الجسم والطعام والشحن في أمريكا الشمالية",
  },
  {
    locale: "ar", sourceSlug: "ons", slug: "ounce", category: "kutle", categoryName: "الكتلة",
    unit: "oz", name: "أونصة", symbol: "أونصة",
    shortDescription: "الأونصة وحدة كتلة صغيرة تقليدية، تساوي جزءًا من ستة عشر من الرطل.",
    historySummary: "استُخدمت تاريخيًا في التجارة والصياغة قبل اعتماد النظام المتري.",
    measurementSystem: "النظام الإمبراطوري/الأمريكي (خارج النظام الدولي)", siEquivalent: "1 أونصة ≈ 28.35 غ",
    commonUses: "وصفات الطهي الأمريكية وقياس الذهب والفضة",
  },
  {
    locale: "ar", sourceSlug: "santimetrekare", slug: "square-centimeter", category: "alan", categoryName: "المساحة",
    unit: "cm²", name: "سنتيمتر مربع", symbol: "سم²",
    shortDescription: "سنتيمتر مربع وحدة مساحة صغيرة تُستخدم للقياسات الدقيقة والحرفية.",
    historySummary: "مشتقة من وحدة السنتيمتر، وتُستخدم عند التعامل مع مساحات صغيرة نسبيًا.",
    measurementSystem: "النظام الدولي للوحدات (وحدة فرعية)", siEquivalent: "1 سم² = 0.0001 م²",
    commonUses: "الحرف اليدوية والتصميم الدقيق والمختبرات",
  },
  {
    locale: "ar", sourceSlug: "kilometrekare", slug: "square-kilometer", category: "alan", categoryName: "المساحة",
    unit: "km²", name: "كيلومتر مربع", symbol: "كم²",
    shortDescription: "كيلومتر مربع وحدة مساحة كبيرة جدًا تُستخدم للمدن والمناطق الجغرافية.",
    historySummary: "شائعة في الجغرافيا والتخطيط العمراني للتعبير عن مساحات واسعة.",
    measurementSystem: "النظام الدولي للوحدات (وحدة مضاعفة)", siEquivalent: "1 كم² = 1,000,000 م²",
    commonUses: "مساحات المدن والدول والدراسات الجغرافية",
  },
  {
    locale: "ar", sourceSlug: "fitkare", slug: "square-foot", category: "alan", categoryName: "المساحة",
    unit: "ft²", name: "قدم مربع", symbol: "قدم²",
    shortDescription: "قدم مربع وحدة مساحة تقليدية شائعة في العقارات الأمريكية.",
    historySummary: "معيار شائع في وثائق العقارات والبناء الأمريكية والبريطانية.",
    measurementSystem: "النظام الإمبراطوري/الأمريكي (خارج النظام الدولي)", siEquivalent: "1 قدم² ≈ 0.0929 م²",
    commonUses: "مساحات المنازل والمكاتب في الإعلانات العقارية الأمريكية",
  },
  {
    locale: "ar", sourceSlug: "donum", slug: "donum", category: "alan", categoryName: "المساحة",
    unit: "dönüm", name: "دونم", symbol: "دونم",
    shortDescription: "الدونم وحدة مساحة تقليدية شائعة في تركيا والشرق الأوسط، تساوي 1000 متر مربع.",
    historySummary: "يعود أصله إلى العصر العثماني، ولا يزال مستخدمًا رسميًا في قياس الأراضي الزراعية.",
    measurementSystem: "خارج النظام الدولي، وحدة إقليمية تقليدية", siEquivalent: "1 دونم = 1000 م²",
    commonUses: "قياس الأراضي الزراعية والعقارات في تركيا والمنطقة",
  },
  {
    locale: "ar", sourceSlug: "mililitre", slug: "milliliter", category: "hacim", categoryName: "الحجم",
    unit: "mL", name: "مليلتر", symbol: "مل",
    shortDescription: "المليلتر يساوي جزءًا من ألف من اللتر، ويُستخدم للسوائل بكميات صغيرة.",
    historySummary: "وحدة عملية أساسية في الطهي والطب والمختبرات.",
    measurementSystem: "النظام المتري (متوافق مع النظام الدولي)", siEquivalent: "1 مل = 0.001 لتر",
    commonUses: "الوصفات الطبية والطهي والمختبرات الكيميائية",
  },
  {
    locale: "ar", sourceSlug: "galon", slug: "gallon", category: "hacim", categoryName: "الحجم",
    unit: "gal", name: "غالون", symbol: "غالون",
    shortDescription: "الغالون وحدة حجم تقليدية شائعة في الولايات المتحدة لقياس السوائل والوقود.",
    historySummary: "له عدة تعريفات تاريخية مختلفة، والغالون الأمريكي هو الأكثر استخدامًا اليوم.",
    measurementSystem: "النظام الإمبراطوري/الأمريكي (خارج النظام الدولي)", siEquivalent: "1 غالون (أمريكي) ≈ 3.785 لتر",
    commonUses: "استهلاك الوقود والسوائل الكبيرة في أمريكا الشمالية",
  },
  {
    locale: "ar", sourceSlug: "kilopascal", slug: "kilopascal", category: "basinc", categoryName: "الضغط",
    unit: "kPa", name: "كيلوباسكال", symbol: "ك.با",
    shortDescription: "الكيلوباسكال يساوي 1000 باسكال، ويُستخدم للتعبير عن قيم ضغط أكبر بشكل عملي.",
    historySummary: "شائع في الأرصاد الجوية والهندسة لأن قيم الضغط الجوي الفعلية كبيرة بالباسكال المفرد.",
    measurementSystem: "النظام الدولي للوحدات (وحدة مضاعفة)", siEquivalent: "1 ك.با = 1000 با",
    commonUses: "الأرصاد الجوية وأنظمة الضغط الهندسية",
  },
  {
    locale: "ar", sourceSlug: "atmosfer", slug: "atmosphere", category: "basinc", categoryName: "الضغط",
    unit: "atm", name: "ضغط جوي", symbol: "atm",
    shortDescription: "الضغط الجوي القياسي يمثل متوسط الضغط الجوي عند مستوى سطح البحر.",
    historySummary: "اعتُمد كمرجع قياسي لمقارنة قيم الضغط في الأرصاد الجوية والطيران والغوص.",
    measurementSystem: "خارج النظام الدولي، ثابت مرجعي", siEquivalent: "1 atm = 101,325 باسكال",
    commonUses: "الطيران والغوص وقياسات الأرصاد الجوية",
  },
  {
    locale: "ar", sourceSlug: "psi", slug: "psi", category: "basinc", categoryName: "الضغط",
    unit: "psi", name: "رطل لكل إنش مربع", symbol: "PSI",
    shortDescription: "PSI وحدة ضغط أمريكية شائعة، تُستخدم كثيرًا في ضغط إطارات السيارات.",
    historySummary: "معيار شائع في الصناعة والسيارات في الولايات المتحدة.",
    measurementSystem: "النظام الإمبراطوري/الأمريكي (خارج النظام الدولي)", siEquivalent: "1 PSI ≈ 6894.76 باسكال",
    commonUses: "ضغط إطارات السيارات وأنظمة الضغط الصناعية الأمريكية",
  },
  {
    locale: "ar", sourceSlug: "kilojoule", slug: "kilojoule", category: "enerji", categoryName: "الطاقة",
    unit: "kJ", name: "كيلوجول", symbol: "ك.ج",
    shortDescription: "الكيلوجول يساوي 1000 جول، ويُستخدم للتعبير عن قيم طاقة أكبر بشكل عملي.",
    historySummary: "شائع في علم التغذية للتعبير عن القيمة الطاقية للأطعمة كبديل للسعرات الحرارية.",
    measurementSystem: "النظام الدولي للوحدات (وحدة مضاعفة)", siEquivalent: "1 ك.ج = 1000 ج",
    commonUses: "الملصقات الغذائية والهندسة والفيزياء",
  },
  {
    locale: "ar", sourceSlug: "kalori", slug: "calorie", category: "enerji", categoryName: "الطاقة",
    unit: "cal", name: "سعرة حرارية", symbol: "سعرة",
    shortDescription: "السعرة الحرارية وحدة طاقة تقليدية، عُرِّفت أصلًا بناءً على تسخين الماء.",
    historySummary: "شائعة تاريخيًا في الكيمياء وعلم التغذية.",
    measurementSystem: "خارج النظام الدولي، وحدة تقليدية", siEquivalent: "1 سعرة = 4.184 جول",
    commonUses: "علم التغذية والكيمياء",
  },
  {
    locale: "ar", sourceSlug: "kilokalori", slug: "kilocalorie", category: "enerji", categoryName: "الطاقة",
    unit: "kcal", name: "كيلو سعرة حرارية", symbol: "ك.سعرة",
    shortDescription: "الكيلو سعرة الحرارية (السعرة الغذائية) هي الوحدة الفعلية المستخدمة في ملصقات القيمة الغذائية للأطعمة.",
    historySummary: "ما يُسمى \"سعرة\" في ملصقات الأطعمة هو في الواقع كيلو سعرة حرارية.",
    measurementSystem: "خارج النظام الدولي، وحدة تجارية شائعة", siEquivalent: "1 ك.سعرة = 1000 سعرة = 4184 جول",
    commonUses: "ملصقات القيمة الغذائية وحساب استهلاك الطاقة اليومي",
  },
  {
    locale: "ar", sourceSlug: "btu", slug: "btu", category: "enerji", categoryName: "الطاقة",
    unit: "Btu", name: "وحدة حرارية بريطانية", symbol: "Btu",
    shortDescription: "الوحدة الحرارية البريطانية وحدة طاقة تقليدية تُستخدم في أنظمة التدفئة والتبريد الأمريكية.",
    historySummary: "معيار صناعي أمريكي، لا يزال يُستخدم في تصنيف أجهزة التكييف.",
    measurementSystem: "النظام الإمبراطوري/الأمريكي (خارج النظام الدولي)", siEquivalent: "1 Btu ≈ 1055.06 جول",
    commonUses: "تصنيف أجهزة التكييف والتدفئة الأمريكية",
  },
  {
    locale: "ar", sourceSlug: "megawatt", slug: "megawatt", category: "guc", categoryName: "القدرة",
    unit: "MW", name: "ميغاواط", symbol: "م.و",
    shortDescription: "الميغاواط يساوي مليون واط، ويُستخدم للتعبير عن قدرات محطات الطاقة الكبيرة.",
    historySummary: "أصبح الوحدة العملية القياسية لقدرة محطات توليد الكهرباء.",
    measurementSystem: "النظام الدولي للوحدات (وحدة مضاعفة)", siEquivalent: "1 م.و = 1,000,000 و",
    commonUses: "سعة محطات الطاقة ومزارع الرياح والطاقة الشمسية",
  },
  {
    locale: "ar", sourceSlug: "kilovolt", slug: "kilovolt", category: "elektrik", categoryName: "الكهرباء",
    unit: "kV", name: "كيلوفولت", symbol: "ك.ف",
    shortDescription: "الكيلوفولت يساوي 1000 فولت، ويُستخدم في أنظمة الجهد العالي والمتوسط.",
    historySummary: "أصبح ضروريًا مع تطور شبكات نقل الكهرباء عالية الجهد.",
    measurementSystem: "النظام الدولي للوحدات (وحدة مضاعفة)", siEquivalent: "1 ك.ف = 1000 ف",
    commonUses: "شبكات الكهرباء والمحولات والمعدات عالية الجهد",
  },
  {
    locale: "ar", sourceSlug: "miliamper", slug: "milliampere", category: "elektrik", categoryName: "الكهرباء",
    unit: "mA", name: "مليأمبير", symbol: "م.أ",
    shortDescription: "مليأمبير يساوي جزءًا من ألف من الأمبير، ويُستخدم لقياس تيارات صغيرة جدًا.",
    historySummary: "أساسي في الإلكترونيات لأن كثيرًا من التيارات العملية أصغر بكثير من الأمبير الواحد.",
    measurementSystem: "النظام الدولي للوحدات (وحدة فرعية)", siEquivalent: "1 م.أ = 0.001 أ",
    commonUses: "الإلكترونيات والمستشعرات واختبارات التيار المنخفض",
  },
  {
    locale: "ar", sourceSlug: "megabayt", slug: "megabyte", category: "veri", categoryName: "تخزين البيانات",
    unit: "MB", name: "ميغابايت", symbol: "م.ب",
    shortDescription: "الميغابايت يساوي حوالي مليون بايت، وهي الوحدة الشائعة لقياس أحجام الملفات المتوسطة.",
    historySummary: "أصبحت الوحدة اليومية الشائعة مع انتشار الصور والمستندات الرقمية.",
    measurementSystem: "وحدة بيانات رقمية (وحدة مضاعفة)", siEquivalent: "1 م.ب = 1000 ك.ب (أو 1024 حسب النظام)",
    commonUses: "أحجام الصور والمستندات والتطبيقات",
  },
  {
    locale: "ar", sourceSlug: "gigabayt", slug: "gigabyte", category: "veri", categoryName: "تخزين البيانات",
    unit: "GB", name: "غيغابايت", symbol: "غ.ب",
    shortDescription: "الغيغابايت يساوي حوالي مليار بايت، وهي الوحدة الشائعة لسعة الذاكرة والتخزين الحديثة.",
    historySummary: "أصبحت المعيار الشائع لوصف سعة الهواتف الذكية وبطاقات الذاكرة.",
    measurementSystem: "وحدة بيانات رقمية (وحدة مضاعفة)", siEquivalent: "1 غ.ب = 1000 م.ب (أو 1024 حسب النظام)",
    commonUses: "سعة تخزين الهواتف والحواسيب وباقات الإنترنت",
  },
  {
    locale: "ar", sourceSlug: "terabayt", slug: "terabyte", category: "veri", categoryName: "تخزين البيانات",
    unit: "TB", name: "تيرابايت", symbol: "ت.ب",
    shortDescription: "التيرابايت يساوي حوالي تريليون بايت، ويُستخدم لسعات التخزين الكبيرة جدًا.",
    historySummary: "أصبحت شائعة مع تطور محركات الأقراص الصلبة وخدمات التخزين السحابي.",
    measurementSystem: "وحدة بيانات رقمية (وحدة مضاعفة)", siEquivalent: "1 ت.ب = 1000 غ.ب (أو 1024 حسب النظام)",
    commonUses: "محركات الأقراص الصلبة والتخزين السحابي ومراكز البيانات",
  },
  {
    locale: "ar", sourceSlug: "dakika", slug: "minute", category: "zaman", categoryName: "الزمن",
    unit: "min", name: "دقيقة", symbol: "د",
    shortDescription: "الدقيقة تساوي 60 ثانية، وهي وحدة زمن أساسية في الحياة اليومية.",
    historySummary: "يعود تقسيم الساعة إلى 60 دقيقة إلى النظام الستيني البابلي القديم.",
    measurementSystem: "متوافقة مع النظام الدولي، وحدة يومية", siEquivalent: "1 دقيقة = 60 ثانية",
    commonUses: "الجداول الزمنية والطهي والرياضة",
  },
  {
    locale: "ar", sourceSlug: "gun", slug: "day", category: "zaman", categoryName: "الزمن",
    unit: "day", name: "يوم", symbol: "يوم",
    shortDescription: "اليوم يساوي 24 ساعة، ويستند إلى دورة دوران الأرض حول نفسها.",
    historySummary: "من أقدم وحدات الزمن المستخدمة في تاريخ البشرية، مرتبط مباشرة بدورة الليل والنهار.",
    measurementSystem: "متوافق مع النظام الدولي، وحدة طبيعية", siEquivalent: "1 يوم = 86,400 ثانية = 24 ساعة",
    commonUses: "التقويم وحساب الأعمار والتخطيط",
  },
  {
    locale: "ar", sourceSlug: "fahrenhayt", slug: "fahrenheit", category: "sicaklik", categoryName: "درجة الحرارة",
    unit: "F", name: "فهرنهايت", symbol: "°ف",
    shortDescription: "الفهرنهايت مقياس حراري تقليدي لا يزال مستخدمًا في الولايات المتحدة.",
    historySummary: "اقترحه عام 1724 الفيزيائي الألماني دانيال غابرييل فهرنهايت.",
    measurementSystem: "خارج النظام الدولي، وحدة إقليمية", siEquivalent: "°ف = °م × 9/5 + 32",
    commonUses: "توقعات الطقس اليومية في الولايات المتحدة",
  },
  {
    locale: "ar", sourceSlug: "beygirgucu", slug: "horsepower", category: "guc", categoryName: "القدرة",
    unit: "hp", name: "حصان", symbol: "حصان",
    shortDescription: "الحصان (القدرة الحصانية) وحدة قدرة تقليدية تُستخدم خصوصًا في محركات المركبات.",
    historySummary: "اقترحها في القرن الثامن عشر جيمس واط لمقارنة قدرة محركات البخار بقوة الخيول.",
    measurementSystem: "عائلة الحصان المتري (PS/CV، خارج النظام الدولي)", siEquivalent: "1 حصان (متري) = 735.49875 واط",
    commonUses: "قدرة محركات السيارات والدراجات النارية والمواصفات الفنية",
  },
  {
    locale: "ar", sourceSlug: "megahertz", slug: "megahertz", category: "frekans", categoryName: "التردد",
    unit: "MHz", name: "ميغاهرتز", symbol: "م.هرتز",
    shortDescription: "الميغاهرتز يساوي مليون هرتز، ويُستخدم في الراديو والواي فاي والمعالجات القديمة.",
    historySummary: "أصبحت الوحدة العملية القياسية للترددات العالية مع تطور تقنيات الراديو والاتصالات.",
    measurementSystem: "النظام الدولي للوحدات (وحدة مضاعفة)", siEquivalent: "1 م.هرتز = 1,000,000 هرتز",
    commonUses: "ترددات إذاعة FM ونطاق الواي فاي والبلوتوث",
  },
  {
    locale: "ar", sourceSlug: "gigahertz", slug: "gigahertz", category: "frekans", categoryName: "التردد",
    unit: "GHz", name: "غيغاهرتز", symbol: "غ.هرتز",
    shortDescription: "الغيغاهرتز يساوي مليار هرتز، ويُعبّر عن سرعات معالجات الحواسيب الحديثة والاتصالات عالية التردد.",
    historySummary: "أصبحت الوحدة القياسية مع تسارع تقنية المعالجات وأنظمة الجيل الخامس.",
    measurementSystem: "النظام الدولي للوحدات (وحدة مضاعفة)", siEquivalent: "1 غ.هرتز = 1,000,000,000 هرتز",
    commonUses: "سرعات معالجات الحواسيب والهواتف ونطاقات الجيل الخامس",
  },
  {
    locale: "ar", sourceSlug: "gradyan", slug: "gradian", category: "aci", categoryName: "الزاوية",
    unit: "gon", name: "غراد", symbol: "غراد",
    shortDescription: "الغراد وحدة زاوية عشرية تقسم الدائرة الكاملة إلى 400 جزء متساوٍ.",
    historySummary: "اقتُرحت بعد الثورة الفرنسية كجزء من حركة النظام العشري، ولا تزال تُستخدم في مساحة الأراضي.",
    measurementSystem: "خارج النظام الدولي، وحدة عشرية", siEquivalent: "1 غراد = π/200 راديان = 0.9°",
    commonUses: "المساحة الجيوديسية وبعض التطبيقات الهندسية الأوروبية",
  },
  {
    locale: "ar", sourceSlug: "mil-saat", slug: "mile-per-hour", category: "hiz", categoryName: "السرعة",
    unit: "mph", name: "ميل/ساعة", symbol: "ميل/س",
    shortDescription: "ميل في الساعة وحدة سرعة تقليدية شائعة في الولايات المتحدة والمملكة المتحدة.",
    historySummary: "معيار شائع لسرعة المركبات وحدود السرعة في أمريكا الشمالية والمملكة المتحدة.",
    measurementSystem: "النظام الإمبراطوري/الأمريكي (خارج النظام الدولي)", siEquivalent: "1 ميل/س ≈ 0.44704 م/ث",
    commonUses: "سرعة السيارات وإشارات الطرق الأمريكية والبريطانية",
  },
  {
    locale: "ar", sourceSlug: "kilogram-kuvvet-metre", slug: "kilogram-force-meter", category: "tork", categoryName: "عزم الدوران",
    unit: "kgf·m", name: "كيلوغرام قوة متر", symbol: "كغف·م",
    shortDescription: "كيلوغرام قوة متر وحدة عزم دوران تقليدية تظهر في وثائق المحركات القديمة.",
    historySummary: "استُخدمت قبل التوحيد الكامل للنظام الدولي، ولا تزال تظهر في بعض مفاتيح العزم القديمة.",
    measurementSystem: "خارج النظام الدولي، وحدة تقليدية", siEquivalent: "1 كغف·م ≈ 9.80665 نيوتن·متر",
    commonUses: "وثائق محركات السيارات القديمة ومفاتيح العزم",
  },
  {
    locale: "ar", sourceSlug: "milifarad", slug: "millifarad", category: "kapasitans", categoryName: "السعة الكهربائية",
    unit: "mF", name: "ميلي فاراد", symbol: "م.ف",
    shortDescription: "ميلي فاراد يساوي جزءًا من ألف من الفاراد، ويُستخدم للمكثفات ذات السعة الأكبر نسبيًا.",
    historySummary: "شائعة في تطبيقات تخزين الطاقة الكهربائية متوسطة الحجم.",
    measurementSystem: "النظام الدولي للوحدات (وحدة فرعية)", siEquivalent: "1 م.ف = 0.001 فاراد",
    commonUses: "أنظمة تخزين الطاقة ومرشحات الطاقة الكهربائية",
  },
  {
    locale: "ar", sourceSlug: "megaohm", slug: "megaohm", category: "elektrik_direnc", categoryName: "المقاومة الكهربائية",
    unit: "MΩ", name: "ميغاأوم", symbol: "م.أوم",
    shortDescription: "الميغاأوم يساوي مليون أوم، ويُستخدم لقياس مقاومات عالية جدًا.",
    historySummary: "أساسي في اختبار العزل الكهربائي وقياس المقاومات العالية في الدوائر الحساسة.",
    measurementSystem: "النظام الدولي للوحدات (وحدة مضاعفة)", siEquivalent: "1 م.أوم = 1,000,000 أوم",
    commonUses: "اختبار العزل الكهربائي والدوائر عالية المقاومة",
  },
  {
    locale: "ar", sourceSlug: "mikrocoulomb", slug: "microcoulomb", category: "elektrik_yuk", categoryName: "الشحنة الكهربائية",
    unit: "µC", name: "ميكروكولوم", symbol: "µC",
    shortDescription: "الميكروكولوم يساوي جزءًا من مليون من الكولوم، ويُستخدم لقيم الشحنة الصغيرة جدًا.",
    historySummary: "شائع في تحليل الكهرباء الساكنة وتجارب الفيزياء الكهربائية الدقيقة.",
    measurementSystem: "النظام الدولي للوحدات (وحدة فرعية)", siEquivalent: "1 µC = 0.000001 كولوم",
    commonUses: "تجارب الكهرباء الساكنة والفيزياء الدقيقة",
  },
  {
    locale: "ar", sourceSlug: "mikrohenry", slug: "microhenry", category: "enduktans", categoryName: "الحث الكهربائي",
    unit: "µH", name: "ميكروهنري", symbol: "µH",
    shortDescription: "الميكروهنري يساوي جزءًا من مليون من الهنري، ويُستخدم للملفات الصغيرة جدًا في الدوائر عالية التردد.",
    historySummary: "أساسي في تصميم دوائر الراديو والاتصالات عالية التردد.",
    measurementSystem: "النظام الدولي للوحدات (وحدة فرعية)", siEquivalent: "1 µH = 0.000001 هنري",
    commonUses: "دوائر الراديو والاتصالات عالية التردد",
  },
  {
    locale: "ar", sourceSlug: "milivolt", slug: "millivolt", category: "elektrik_gerilim", categoryName: "الجهد الكهربائي",
    unit: "mV", name: "مليفولت", symbol: "م.ف",
    shortDescription: "المليفولت يساوي جزءًا من ألف من الفولت، ويُستخدم للإشارات الكهربائية الصغيرة جدًا.",
    historySummary: "أساسي في الإلكترونيات والأجهزة الطبية لقياس الإشارات الحيوية الدقيقة.",
    measurementSystem: "النظام الدولي للوحدات (وحدة فرعية)", siEquivalent: "1 م.ف = 0.001 ف",
    commonUses: "الإشارات الطبية (تخطيط القلب والدماغ) والدوائر الإلكترونية الدقيقة",
  },
  {
    locale: "ar", sourceSlug: "22-ayar-altin", slug: "22k-gold", category: "altin_ayar", categoryName: "عيار الذهب",
    unit: "22K", name: "ذهب عيار 22", symbol: "22K",
    shortDescription: "عيار 22 يعني سبيكة من 91.6% ذهب خالص، وهو شائع جدًا في المجوهرات التقليدية.",
    historySummary: "يوفر توازنًا بين النقاء العالي ومتانة أكبر قليلًا من عيار 24 الخالص.",
    measurementSystem: "نظام العيار (خارج النظام الدولي)", siEquivalent: "916/1000 ذهب خالص",
    commonUses: "المجوهرات التقليدية والسبائك الاستثمارية عالية النقاء",
  },
  {
    locale: "ar", sourceSlug: "fit-saniyekare", slug: "foot-per-second-squared", category: "ivme", categoryName: "التسارع",
    unit: "ft/s²", name: "قدم/ثانية مربعة", symbol: "قدم/ث²",
    shortDescription: "قدم في الثانية المربعة وحدة تسارع تقليدية تُستخدم في النظامين الأمريكي والبريطاني.",
    historySummary: "مشتقة مباشرة من وحدة القدم، وتظهر في الوثائق الهندسية والفضائية الأمريكية.",
    measurementSystem: "النظام الإمبراطوري/الأمريكي (خارج النظام الدولي)", siEquivalent: "1 قدم/ث² = 0.3048 م/ث²",
    commonUses: "الوثائق الهندسية الأمريكية وحسابات الطيران والفضاء",
  },
  {
    locale: "ar", sourceSlug: "fitkup-dakika", slug: "cubic-feet-per-minute", category: "debi_hacimsel", categoryName: "معدل التدفق الحجمي",
    unit: "cfm", name: "قدم مكعب/دقيقة", symbol: "CFM",
    shortDescription: "CFM وحدة أمريكية شائعة للتعبير عن معدل تدفق الهواء، خصوصًا في أنظمة التهوية.",
    historySummary: "أصبحت المعيار القياسي في صناعة التكييف والتهوية الأمريكية.",
    measurementSystem: "النظام الإمبراطوري/الأمريكي (خارج النظام الدولي)", siEquivalent: "1 CFM ≈ 0.000472 م³/ث",
    commonUses: "أنظمة التهوية والتكييف وفلاتر الهواء",
  },
  {
    locale: "ar", sourceSlug: "derece-saniye", slug: "degree-per-second", category: "acisal_hiz", categoryName: "السرعة الزاوية",
    unit: "°/s", name: "درجة/ثانية", symbol: "°/ث",
    shortDescription: "درجة في الثانية تعبّر عن السرعة الزاوية بالدرجات، وهي أكثر سهولة للفهم اليومي من الراديان.",
    historySummary: "نشأت من الاستخدام الشائع للدرجة في قياس الزوايا، كبديل عملي للراديان.",
    measurementSystem: "خارج النظام الدولي، وحدة عملية", siEquivalent: "1 °/ث = π/180 راد/ث ≈ 0.01745 راد/ث",
    commonUses: "أنظمة تدوير الكاميرات والهوائيات وسرعات المفاصل الروبوتية",
  },
  {
    locale: "ar", sourceSlug: "okka", slug: "okka", category: "kutle", categoryName: "الكتلة",
    unit: "okka", name: "أوقية عثمانية", symbol: "أوقية",
    shortDescription: "الأوقية (أوكا) وحدة كتلة تقليدية استُخدمت في الإمبراطورية العثمانية، لا تزال معروفة في تركيا والمنطقة.",
    historySummary: "كانت وحدة الكتلة الرسمية في الدولة العثمانية لقرون، وتُستخدم أحيانًا في الأسواق التقليدية حتى اليوم.",
    measurementSystem: "خارج النظام الدولي، وحدة تاريخية عثمانية", siEquivalent: "1 أوقية ≈ 1.283 كغ",
    commonUses: "الأسواق التقليدية والوثائق التاريخية العثمانية",
  },
  {
    locale: "ar", sourceSlug: "dirhem", slug: "dirham", category: "kutle", categoryName: "الكتلة",
    unit: "dirhem", name: "درهم عثماني", symbol: "درهم",
    shortDescription: "الدرهم وحدة كتلة عثمانية صغيرة، تساوي جزءًا من أربعمائة من الأوقية.",
    historySummary: "استُخدم تقليديًا لوزن التوابل والمعادن الثمينة والذهب في الأسواق العثمانية.",
    measurementSystem: "خارج النظام الدولي، وحدة تاريخية عثمانية", siEquivalent: "1 درهم ≈ 3.207 غ",
    commonUses: "وزن الذهب والتوابل في الأسواق التقليدية",
  },
  {
    locale: "ar", sourceSlug: "bizans-litrasi", slug: "byzantine-litra", category: "kutle", categoryName: "الكتلة",
    unit: "litra", name: "ليترا بيزنطية", symbol: "ليترا",
    shortDescription: "الليترا وحدة كتلة تقليدية استُخدمت في الإمبراطورية البيزنطية.",
    historySummary: "استُخدمت في التجارة والصياغة خلال العصر البيزنطي قبل الفتح العثماني.",
    measurementSystem: "خارج النظام الدولي، وحدة تاريخية بيزنطية", siEquivalent: "1 ليترا ≈ 0.324 كغ",
    commonUses: "الوثائق والدراسات التاريخية البيزنطية",
  },
  {
    locale: "ar", sourceSlug: "bizans-onsu", slug: "byzantine-ounce", category: "kutle", categoryName: "الكتلة",
    unit: "ounkia", name: "أونصة بيزنطية", symbol: "ounkia",
    shortDescription: "الأونكيا وحدة كتلة بيزنطية صغيرة، جزء من اثني عشر من الليترا البيزنطية.",
    historySummary: "استُخدمت في التجارة البيزنطية اليومية لوزن الكميات الصغيرة.",
    measurementSystem: "خارج النظام الدولي، وحدة تاريخية بيزنطية", siEquivalent: "1 ounkia ≈ 27 غ",
    commonUses: "الدراسات التاريخية والوثائق البيزنطية",
  },
  {
    locale: "ar", sourceSlug: "arsin", slug: "arshin", category: "uzunluk", categoryName: "الطول",
    unit: "arşın", name: "أرشين عثماني", symbol: "أرشين",
    shortDescription: "الأرشين وحدة طول تقليدية عثمانية، استُخدمت على نطاق واسع في قياس الأقمشة والأراضي.",
    historySummary: "كانت وحدة الطول القياسية في الدولة العثمانية قبل اعتماد النظام المتري.",
    measurementSystem: "خارج النظام الدولي، وحدة تاريخية عثمانية", siEquivalent: "1 أرشين ≈ 0.68 م",
    commonUses: "الوثائق التاريخية العثمانية وقياس الأقمشة التقليدية",
  },
  {
    locale: "ar", sourceSlug: "endaze", slug: "endaze", category: "uzunluk", categoryName: "الطول",
    unit: "endaze", name: "إنداز عثماني", symbol: "إنداز",
    shortDescription: "الإنداز وحدة طول عثمانية تقليدية، استُخدمت خصوصًا في تجارة الأقمشة والمنسوجات.",
    historySummary: "كانت شائعة بين تجار الأقمشة في الأسواق العثمانية لقياس القماش المباع بالطول.",
    measurementSystem: "خارج النظام الدولي، وحدة تاريخية عثمانية", siEquivalent: "1 إنداز ≈ 0.65 م",
    commonUses: "تجارة الأقمشة التقليدية والوثائق التاريخية",
  },
  {
    locale: "ar", sourceSlug: "bizans-ayagi", slug: "byzantine-foot", category: "uzunluk", categoryName: "الطول",
    unit: "pous", name: "قدم بيزنطية", symbol: "pous",
    shortDescription: "القدم البيزنطية وحدة طول تقليدية استُخدمت في العمارة والقياسات البيزنطية.",
    historySummary: "استُخدمت في تصميم المباني والكنائس خلال العصر البيزنطي.",
    measurementSystem: "خارج النظام الدولي، وحدة تاريخية بيزنطية", siEquivalent: "1 pous ≈ 0.3148 م",
    commonUses: "الدراسات المعمارية والتاريخية البيزنطية",
  },
  {
    locale: "ar", sourceSlug: "bizans-kulaci", slug: "byzantine-fathom", category: "uzunluk", categoryName: "الطول",
    unit: "orgyia", name: "قامة بيزنطية", symbol: "orgyia",
    shortDescription: "القامة البيزنطية (أورغيا) وحدة طول تقليدية أكبر، استُخدمت لقياس المسافات البحرية والأراضي.",
    historySummary: "كانت تعادل تقريبًا امتداد ذراعي الإنسان، واستُخدمت في الملاحة والمساحة البيزنطية.",
    measurementSystem: "خارج النظام الدولي، وحدة تاريخية بيزنطية", siEquivalent: "1 orgyia ≈ 1.889 م",
    commonUses: "الملاحة البحرية ومساحة الأراضي في العصر البيزنطي",
  },
  {
    locale: "ar", sourceSlug: "cig", slug: "cig", category: "uzunluk", categoryName: "الطول",
    unit: "çığ", name: "جيغ (تركي قديم)", symbol: "çığ",
    shortDescription: "الجيغ وحدة طول من عصر الأتراك القدامى، وردت في القاموس التاريخي \"ديوان لغات الترك\" لكاشغري محمود.",
    historySummary: "تُعرَف من مصادر أكاديمية حديثة حددتها بدقة استنادًا إلى دراسة نصوص كاشغري محمود التاريخية.",
    measurementSystem: "خارج النظام الدولي، وحدة تاريخية تركية قديمة", siEquivalent: "1 çığ ≈ 0.333 م",
    commonUses: "الدراسات اللغوية والتاريخية للأتراك القدامى",
  },
  {
    locale: "ar", sourceSlug: "isik-hizi", slug: "speed-of-light", category: "hiz", categoryName: "السرعة",
    unit: "c", name: "سرعة الضوء", symbol: "c",
    shortDescription: "سرعة الضوء ثابت فيزيائي أساسي، يمثل سرعة انتشار الضوء والموجات الكهرومغناطيسية في الفراغ.",
    historySummary: "منذ عام 1983، أصبح تعريف المتر نفسه مبنيًا على سرعة الضوء، مما يجعل قيمتها ثابتة تمامًا وليست مقيسة.",
    measurementSystem: "ثابت فيزيائي أساسي في النظام الدولي", siEquivalent: "c = 299,792,458 م/ث (بالضبط، حسب التعريف)",
    commonUses: "الفيزياء والفلك ونظرية النسبية وأنظمة تحديد المواقع",
  },
  {
    locale: "ar", sourceSlug: "bit", slug: "bit", category: "veri", categoryName: "تخزين البيانات",
    unit: "bit", name: "بت", symbol: "بت",
    shortDescription: "البت هو أصغر وحدة أساسية للمعلومات الرقمية، ويمثل قيمة ثنائية واحدة (0 أو 1).",
    historySummary: "الأساس الرياضي لكل الحوسبة الرقمية الحديثة، مأخوذ من نظرية المعلومات لكلود شانون.",
    measurementSystem: "وحدة معلومات رقمية أساسية", siEquivalent: "1 بايت = 8 بت",
    commonUses: "سرعات الاتصال بالإنترنت ونظرية المعلومات والحوسبة",
  },
  {
    locale: "ar", sourceSlug: "tam-tur", slug: "full-turn", category: "aci", categoryName: "الزاوية",
    unit: "تور", name: "دورة كاملة", symbol: "دورة",
    shortDescription: "الدورة الكاملة تمثل زاوية دوران كاملة حول نقطة، أي 360 درجة بالكامل.",
    historySummary: "وحدة زاوية بديهية تُستخدم لوصف دوران كامل واحد أو أكثر حول محور معين.",
    measurementSystem: "خارج النظام الدولي، وحدة عملية", siEquivalent: "1 دورة = 360° = 2π راديان",
    commonUses: "وصف الدورات الميكانيكية الكاملة والحركة الدورانية",
  },
  {
    locale: "ar", sourceSlug: "mikrometre", slug: "micrometer", category: "uzunluk", categoryName: "الطول",
    unit: "µm", name: "ميكرومتر", symbol: "µm",
    shortDescription: "الميكرومتر يساوي جزءًا من مليون من المتر، ويُستخدم للقياسات المجهرية الدقيقة جدًا.",
    historySummary: "أساسي في علوم المواد وتكنولوجيا أشباه الموصلات لقياس الأبعاد شديدة الصغر.",
    measurementSystem: "النظام الدولي للوحدات (وحدة فرعية)", siEquivalent: "1 µm = 0.000001 م",
    commonUses: "علوم المواد وتكنولوجيا أشباه الموصلات والبيولوجيا المجهرية",
  },
  {
    locale: "ar", sourceSlug: "nanometre", slug: "nanometer", category: "uzunluk", categoryName: "الطول",
    unit: "nm", name: "نانومتر", symbol: "nm",
    shortDescription: "النانومتر يساوي جزءًا من مليار من المتر، ويُستخدم في مقاييس الذرات والجزيئات.",
    historySummary: "أساسي في الفيزياء والكيمياء وتكنولوجيا النانو الحديثة.",
    measurementSystem: "النظام الدولي للوحدات (وحدة فرعية)", siEquivalent: "1 nm = 0.000000001 م",
    commonUses: "تكنولوجيا النانو وأطوال موجات الضوء وعلوم أشباه الموصلات",
  },
  {
    locale: "ar", sourceSlug: "deniz-mili", slug: "nautical-mile", category: "uzunluk", categoryName: "الطول",
    unit: "nmi", name: "ميل بحري", symbol: "ميل بحري",
    shortDescription: "الميل البحري وحدة مسافة تُستخدم في الملاحة البحرية والجوية، مبنية على قياس خط العرض الأرضي.",
    historySummary: "يُعرَّف بدقة الدقيقة الواحدة من القوس على دائرة عرض الأرض الكبرى.",
    measurementSystem: "خارج النظام الدولي، وحدة ملاحية دولية", siEquivalent: "1 ميل بحري = 1852 م",
    commonUses: "الملاحة البحرية والجوية وأنظمة تحديد المواقع",
  },
  {
    locale: "ar", sourceSlug: "milimetrekare", slug: "square-millimeter", category: "alan", categoryName: "المساحة",
    unit: "mm²", name: "مليمتر مربع", symbol: "مم²",
    shortDescription: "مليمتر مربع وحدة مساحة صغيرة جدًا تُستخدم في الهندسة الدقيقة.",
    historySummary: "أساسية في تصميم المكونات الإلكترونية الدقيقة والقياسات الهندسية الصغيرة.",
    measurementSystem: "النظام الدولي للوحدات (وحدة فرعية)", siEquivalent: "1 مم² = 0.000001 م²",
    commonUses: "الهندسة الدقيقة وتصميم المكونات الإلكترونية",
  },
  {
    locale: "ar", sourceSlug: "incare", slug: "square-inch", category: "alan", categoryName: "المساحة",
    unit: "in²", name: "إنش مربع", symbol: "إنش²",
    shortDescription: "إنش مربع وحدة مساحة تقليدية صغيرة تُستخدم في الولايات المتحدة.",
    historySummary: "شائعة في مواصفات المكونات الصناعية والإلكترونية الأمريكية.",
    measurementSystem: "النظام الإمبراطوري/الأمريكي (خارج النظام الدولي)", siEquivalent: "1 إنش² ≈ 6.4516 سم²",
    commonUses: "المواصفات الصناعية الأمريكية والشاشات الصغيرة",
  },
  {
    locale: "ar", sourceSlug: "akre", slug: "acre", category: "alan", categoryName: "المساحة",
    unit: "ac", name: "أكر", symbol: "أكر",
    shortDescription: "الأكر وحدة مساحة تقليدية كبيرة تُستخدم لقياس الأراضي الزراعية والعقارات في أمريكا وبريطانيا.",
    historySummary: "يعود أصله إلى العصور الوسطى، كان يمثل تقريبًا مساحة الأرض التي يحرثها ثور في يوم واحد.",
    measurementSystem: "النظام الإمبراطوري/الأمريكي (خارج النظام الدولي)", siEquivalent: "1 أكر ≈ 4046.86 م²",
    commonUses: "العقارات والأراضي الزراعية في أمريكا وبريطانيا",
  },
  {
    locale: "ar", sourceSlug: "dekar", slug: "decare", category: "alan", categoryName: "المساحة",
    unit: "dekar", name: "ديكار", symbol: "ديكار",
    shortDescription: "الديكار وحدة مساحة إقليمية تساوي 1000 متر مربع، شائعة في منطقة البلقان وشرق المتوسط.",
    historySummary: "مشتقة من النظام المتري، تُستخدم بديلًا محليًا للدونم في بعض مناطق الشرق الأوسط والبلقان.",
    measurementSystem: "خارج النظام الدولي، وحدة إقليمية", siEquivalent: "1 ديكار = 1000 م²",
    commonUses: "قياس الأراضي الزراعية في منطقة البلقان وشرق المتوسط",
  },
  {
    locale: "ar", sourceSlug: "santimetrekup", slug: "cubic-centimeter", category: "hacim", categoryName: "الحجم",
    unit: "cm³", name: "سنتيمتر مكعب", symbol: "سم³",
    shortDescription: "سنتيمتر مكعب وحدة حجم صغيرة، تكافئ المليلتر تمامًا.",
    historySummary: "شائعة في الطب والكيمياء وقياس حجم محركات السيارات.",
    measurementSystem: "النظام الدولي للوحدات (وحدة فرعية)", siEquivalent: "1 سم³ = 1 مل = 0.000001 م³",
    commonUses: "حجم محركات السيارات والجرعات الطبية والمختبرات",
  },
  {
    locale: "ar", sourceSlug: "fitkup", slug: "cubic-foot", category: "hacim", categoryName: "الحجم",
    unit: "ft³", name: "قدم مكعب", symbol: "قدم³",
    shortDescription: "قدم مكعب وحدة حجم تقليدية شائعة في البناء والتكييف الأمريكي.",
    historySummary: "معيار شائع في مواصفات معدات التكييف والتهوية الأمريكية.",
    measurementSystem: "النظام الإمبراطوري/الأمريكي (خارج النظام الدولي)", siEquivalent: "1 قدم³ ≈ 0.0283 م³",
    commonUses: "معدات التكييف الأمريكية وحسابات البناء",
  },
  {
    locale: "ar", sourceSlug: "inckup", slug: "cubic-inch", category: "hacim", categoryName: "الحجم",
    unit: "in³", name: "إنش مكعب", symbol: "إنش³",
    shortDescription: "إنش مكعب وحدة حجم تقليدية صغيرة تُستخدم لقياس حجم محركات السيارات الأمريكية القديمة.",
    historySummary: "معيار تاريخي شائع لتصنيف محركات السيارات الأمريكية العضلية.",
    measurementSystem: "النظام الإمبراطوري/الأمريكي (خارج النظام الدولي)", siEquivalent: "1 إنش³ ≈ 16.39 سم³",
    commonUses: "تصنيف محركات السيارات الأمريكية الكلاسيكية",
  },
  {
    locale: "ar", sourceSlug: "varil", slug: "barrel", category: "hacim", categoryName: "الحجم",
    unit: "bbl", name: "برميل نفط", symbol: "برميل",
    shortDescription: "البرميل وحدة حجم تجارية عالمية معيارية لقياس النفط الخام.",
    historySummary: "أصبح المعيار العالمي لتجارة النفط الخام منذ بدايات صناعة النفط الأمريكية.",
    measurementSystem: "خارج النظام الدولي، وحدة تجارية عالمية", siEquivalent: "1 برميل نفط ≈ 158.987 لتر",
    commonUses: "تجارة النفط الخام العالمية وأسواق الطاقة",
  },
  {
    locale: "ar", sourceSlug: "knot", slug: "knot", category: "hiz", categoryName: "السرعة",
    unit: "knot", name: "عقدة", symbol: "عقدة",
    shortDescription: "العقدة وحدة سرعة تُستخدم في الملاحة البحرية والجوية، تساوي ميلًا بحريًا واحدًا في الساعة.",
    historySummary: "اسمها يعود إلى طريقة تاريخية لقياس سرعة السفن باستخدام حبل معقود يُرمى خلف السفينة.",
    measurementSystem: "خارج النظام الدولي، وحدة ملاحية دولية", siEquivalent: "1 عقدة ≈ 0.5144 م/ث",
    commonUses: "الملاحة البحرية والجوية وتوقعات سرعة الرياح",
  },
  {
    locale: "ar", sourceSlug: "milibar", slug: "millibar", category: "basinc", categoryName: "الضغط",
    unit: "mbar", name: "ميلي بار", symbol: "ميلي بار",
    shortDescription: "الميلي بار وحدة ضغط شائعة في الأرصاد الجوية لوصف الضغط الجوي.",
    historySummary: "أصبحت الوحدة القياسية في تقارير الأرصاد الجوية العالمية لوصف أنظمة الضغط الجوي.",
    measurementSystem: "خارج النظام الدولي، وحدة أرصاد جوية شائعة", siEquivalent: "1 ميلي بار = 100 باسكال",
    commonUses: "تقارير الأرصاد الجوية وخرائط الطقس",
  },
  {
    locale: "ar", sourceSlug: "milimetre-civa", slug: "millimeter-of-mercury", category: "basinc", categoryName: "الضغط",
    unit: "mmHg", name: "مليمتر زئبق", symbol: "مم زئبق",
    shortDescription: "مليمتر الزئبق وحدة ضغط تقليدية لا تزال تُستخدم في الطب لقياس ضغط الدم.",
    historySummary: "مشتقة من مقاييس الضغط الزئبقية التاريخية، لا تزال معيارًا طبيًا عالميًا.",
    measurementSystem: "خارج النظام الدولي، وحدة طبية شائعة", siEquivalent: "1 مم زئبق ≈ 133.322 باسكال",
    commonUses: "قياس ضغط الدم والقياسات الطبية",
  },
  {
    locale: "ar", sourceSlug: "kilogram-kuvvet-santimetrekare", slug: "kilogram-force-per-square-centimeter", category: "basinc", categoryName: "الضغط",
    unit: "kgf/cm²", name: "كيلوغرام قوة/سنتيمتر مربع", symbol: "كغف/سم²",
    shortDescription: "كيلوغرام قوة لكل سنتيمتر مربع وحدة ضغط تقليدية تظهر في وثائق ضغط الإطارات والمعدات القديمة.",
    historySummary: "استُخدمت قبل التوحيد الكامل للنظام الدولي، لا تزال تظهر في بعض عدادات الضغط القديمة.",
    measurementSystem: "خارج النظام الدولي، وحدة تقليدية", siEquivalent: "1 كغف/سم² ≈ 98,066.5 باسكال",
    commonUses: "عدادات ضغط الإطارات والمعدات الصناعية القديمة",
  },
  {
    locale: "ar", sourceSlug: "santistok", slug: "centistoke", category: "viskozite_kinematik", categoryName: "اللزوجة الحركية",
    unit: "cSt", name: "سنتيستوك", symbol: "سنتيستوك",
    shortDescription: "السنتيستوك هو الوحدة العملية الأكثر استخدامًا للزوجة الحركية في الصناعة.",
    historySummary: "تعادل 1 مم²/ث، وأصبحت المعيار القياسي لتصنيف زيوت المحركات في الصناعة.",
    measurementSystem: "نظام CGS (خارج النظام الدولي، وحدة فرعية)", siEquivalent: "1 سنتيستوك = 1 مم²/ث = 0.000001 م²/ث",
    commonUses: "تصنيف زيوت المحركات وخصائص الوقود والسوائل الصناعية",
  },
  {
    locale: "ar", sourceSlug: "watt-saat", slug: "watt-hour", category: "enerji", categoryName: "الطاقة",
    unit: "Wh", name: "واط ساعة", symbol: "و.س",
    shortDescription: "واط ساعة وحدة طاقة عملية، تعبّر عن الطاقة المستهلكة بمعدل واط واحد لمدة ساعة.",
    historySummary: "أساس وحدة كيلوواط الساعة الأكبر المستخدمة في فواتير الكهرباء.",
    measurementSystem: "خارج النظام الدولي، وحدة تجارية شائعة", siEquivalent: "1 و.س = 3600 جول",
    commonUses: "سعة البطاريات الصغيرة والأجهزة الإلكترونية المحمولة",
  },
  {
    locale: "ar", sourceSlug: "beygirgucu-mekanik", slug: "horsepower-mechanical", category: "guc", categoryName: "القدرة",
    unit: "HP", name: "حصان ميكانيكي", symbol: "حصان",
    shortDescription: "الحصان الميكانيكي وحدة قدرة تقليدية بريطانية/أمريكية، تختلف قليلًا عن الحصان المتري (PS/CV).",
    historySummary: "الحصان الإمبراطوري الذي عرّفه جيمس واط في الأصل، لا يزال مستخدمًا في صناعة السيارات الأمريكية والبريطانية بدلًا من PS/CV المتري.",
    measurementSystem: "النظام الإمبراطوري/الأمريكي (خارج النظام الدولي)", siEquivalent: "1 حصان (ميكانيكي) = 745.7 واط",
    commonUses: "مواصفات المركبات والمحركات الأمريكية والبريطانية",
  },
  {
    locale: "ar", sourceSlug: "kiloamper", slug: "kiloampere", category: "elektrik", categoryName: "الكهرباء",
    unit: "kA", name: "كيلوأمبير", symbol: "ك.أ",
    shortDescription: "الكيلوأمبير يساوي 1000 أمبير، ويُستخدم لقياس تيارات كهربائية كبيرة جدًا مثل تيارات القصر والبرق.",
    historySummary: "أصبح المعيار العملي في أنظمة توزيع الطاقة والمنشآت الكهربائية الصناعية الكبيرة.",
    measurementSystem: "النظام الدولي للوحدات (وحدة مضاعفة)", siEquivalent: "1 ك.أ = 1000 أ",
    commonUses: "حسابات تيار القصر ومعدات التوزيع الكهربائي وتحليل تيار البرق",
  },
  {
    locale: "ar", sourceSlug: "nanofarad", slug: "nanofarad", category: "kapasitans", categoryName: "السعة الكهربائية",
    unit: "nF", name: "نانوفاراد", symbol: "nF",
    shortDescription: "النانوفاراد يساوي جزءًا من مليار من الفاراد، ويُستخدم للمكثفات الصغيرة في الدوائر عالية التردد.",
    historySummary: "أساسي في تصميم دوائر الترشيح والاتصالات عالية التردد.",
    measurementSystem: "النظام الدولي للوحدات (وحدة فرعية)", siEquivalent: "1 nF = 0.000000001 فاراد",
    commonUses: "دوائر الترشيح والاتصالات عالية التردد",
  },
  {
    locale: "ar", sourceSlug: "pikofarad", slug: "picofarad", category: "kapasitans", categoryName: "السعة الكهربائية",
    unit: "pF", name: "بيكوفاراد", symbol: "pF",
    shortDescription: "البيكوفاراد يساوي جزءًا من تريليون من الفاراد، ويُستخدم لأصغر قيم المكثفات في الدوائر الدقيقة.",
    historySummary: "أساسي في تصميم الدوائر الدقيقة عالية التردد مثل دوائر الراديو والاتصالات اللاسلكية.",
    measurementSystem: "النظام الدولي للوحدات (وحدة فرعية)", siEquivalent: "1 pF = 0.000000000001 فاراد",
    commonUses: "دوائر الراديو والاتصالات اللاسلكية الدقيقة",
  },
  {
    locale: "ar", sourceSlug: "nanocoulomb", slug: "nanocoulomb", category: "elektrik_yuk", categoryName: "الشحنة الكهربائية",
    unit: "nC", name: "نانوكولوم", symbol: "nC",
    shortDescription: "النانوكولوم يساوي جزءًا من مليار من الكولوم، ويُستخدم لقيم الشحنة الكهربائية الدقيقة جدًا.",
    historySummary: "شائع في تجارب الفيزياء الدقيقة وتحليل الشحنات الساكنة الصغيرة جدًا.",
    measurementSystem: "النظام الدولي للوحدات (وحدة فرعية)", siEquivalent: "1 nC = 0.000000001 كولوم",
    commonUses: "تجارب الفيزياء الدقيقة وتحليل الشحنات الساكنة",
  },
  {
    locale: "ar", sourceSlug: "petabayt", slug: "petabyte", category: "veri", categoryName: "تخزين البيانات",
    unit: "PB", name: "بيتابايت", symbol: "ب.ب",
    shortDescription: "البيتابايت يساوي حوالي ألف تيرابايت، ويُستخدم لسعات التخزين الضخمة جدًا في مراكز البيانات.",
    historySummary: "أصبحت شائعة مع نمو مراكز البيانات الضخمة وخدمات الحوسبة السحابية العملاقة.",
    measurementSystem: "وحدة بيانات رقمية (وحدة مضاعفة)", siEquivalent: "1 ب.ب = 1000 ت.ب (أو 1024 حسب النظام)",
    commonUses: "مراكز البيانات الضخمة والحوسبة السحابية العملاقة",
  },
  {
    locale: "ar", sourceSlug: "kibibayt", slug: "kibibyte", category: "veri", categoryName: "تخزين البيانات",
    unit: "KiB", name: "كيبيبايت", symbol: "ك.ي.ب",
    shortDescription: "الكيبيبايت وحدة ثنائية بالضبط تساوي 1024 بايت، تُستخدم لتفادي الالتباس مع الكيلوبايت العشري.",
    historySummary: "اعتمدتها المنظمة الدولية للمقاييس الكهروتقنية (IEC) لإزالة الغموض بين الأساس 1000 والأساس 1024.",
    measurementSystem: "وحدة بيانات ثنائية دقيقة (IEC)", siEquivalent: "1 ك.ي.ب = 1024 بايت بالضبط",
    commonUses: "التوثيق التقني الدقيق لأنظمة التشغيل والذاكرة",
  },
  {
    locale: "ar", sourceSlug: "mebibayt", slug: "mebibyte", category: "veri", categoryName: "تخزين البيانات",
    unit: "MiB", name: "ميبيبايت", symbol: "م.ي.ب",
    shortDescription: "الميبيبايت وحدة ثنائية دقيقة تساوي 1024 كيبيبايت بالضبط.",
    historySummary: "تُستخدم في التوثيق التقني الدقيق لتفادي الالتباس بين المعايير العشرية والثنائية لسعة الذاكرة.",
    measurementSystem: "وحدة بيانات ثنائية دقيقة (IEC)", siEquivalent: "1 م.ي.ب = 1024 ك.ي.ب بالضبط",
    commonUses: "توثيق سعة ذاكرة الوصول العشوائي (RAM) بدقة",
  },
  {
    locale: "ar", sourceSlug: "gibibayt", slug: "gibibyte", category: "veri", categoryName: "تخزين البيانات",
    unit: "GiB", name: "غيبيبايت", symbol: "غ.ي.ب",
    shortDescription: "الغيبيبايت وحدة ثنائية دقيقة تساوي 1024 ميبيبايت بالضبط.",
    historySummary: "معيار IEC الدقيق لسعة الذاكرة، يُستخدم لتمييزها عن الغيغابايت العشري التجاري.",
    measurementSystem: "وحدة بيانات ثنائية دقيقة (IEC)", siEquivalent: "1 غ.ي.ب = 1024 م.ي.ب بالضبط",
    commonUses: "توثيق سعة الذاكرة والتخزين بدقة تقنية",
  },
  {
    locale: "ar", sourceSlug: "tebibayt", slug: "tebibyte", category: "veri", categoryName: "تخزين البيانات",
    unit: "TiB", name: "تيبيبايت", symbol: "ت.ي.ب",
    shortDescription: "التيبيبايت وحدة ثنائية دقيقة تساوي 1024 غيبيبايت بالضبط.",
    historySummary: "تُستخدم في تحديد سعة أنظمة التخزين الكبيرة بدقة تقنية صارمة.",
    measurementSystem: "وحدة بيانات ثنائية دقيقة (IEC)", siEquivalent: "1 ت.ي.ب = 1024 غ.ي.ب بالضبط",
    commonUses: "أنظمة التخزين الكبيرة ومراكز البيانات الدقيقة",
  },
  {
    locale: "ar", sourceSlug: "14-ayar-altin", slug: "14k-gold", category: "altin_ayar", categoryName: "عيار الذهب",
    unit: "14K", name: "ذهب عيار 14", symbol: "14K",
    shortDescription: "عيار 14 يعني سبيكة من 58.3% ذهب خالص، وهو أكثر متانة وأقل تكلفة من العيارات الأعلى.",
    historySummary: "شائع في الأسواق الغربية للمجوهرات اليومية بسبب متانته العالية وسعره المعقول نسبيًا.",
    measurementSystem: "نظام العيار (خارج النظام الدولي)", siEquivalent: "583/1000 ذهب خالص",
    commonUses: "المجوهرات اليومية المتينة في الأسواق الغربية",
  },
];

export function findArabicUnitPageBySourceSlug(sourceSlug: string) {
  return arabicUnitPages.find((page) => page.sourceSlug === sourceSlug);
}

export function findArabicUnitPageBySlug(slug: string) {
  return arabicUnitPages.find((page) => page.slug === slug);
}
