// Paginas de unidad en espanol -- integradas en el nuevo sistema i18n
// Archivo independiente y nuevo (no modifica los archivos existentes de
// tr/en/de/ar/uz/bn/fr).
// Alcance limitado a las 13 categorias fundamentales que, junto con las
// 4 herramientas universales (pagina de inicio), forman los 17 elementos
// de la identidad del sitio.

export type LocalizedSpanishUnitPage = {
  locale: "es";
  sourceSlug: string;
  slug: string;
  category: string;
  categoryName: string;
  unit: string;
  name: string;
  symbol: string;
  shortDescription: string;
  historySummary: string;
  measurementSystem: string;
  siEquivalent: string;
  commonUses: string;
};

export const spanishUnitPages: LocalizedSpanishUnitPage[] = [
  // Longitud
  {
    locale: "es",
    sourceSlug: "metre",
    slug: "metro",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "m",
    name: "Metro",
    symbol: "m",
    shortDescription: "El metro es la unidad básica del SI para medir longitud.",
    historySummary: "Desde 1983, el metro se define por la distancia que recorre la luz en el vacío durante 1/299.792.458 de segundo.",
    measurementSystem: "Sistema Internacional de Unidades (SI)",
    siEquivalent: "Unidad basica del SI para la longitud",
    commonUses: "Construcción, deporte, ciencia y distancias cotidianas",
  },
  {
    locale: "es",
    sourceSlug: "kilometre",
    slug: "kilometro",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "km",
    name: "Kilómetro",
    symbol: "km",
    shortDescription: "El kilómetro equivale a 1.000 metros y se usa para distancias largas.",
    historySummary: "El kilómetro es un múltiplo decimal del metro y se consolidó como unidad habitual de carreteras, mapas y geografía.",
    measurementSystem: "Sistema Internacional (múltiplo del SI)",
    siEquivalent: "1 km = 1.000 m",
    commonUses: "Carreteras, geografía, cartografía e infraestructura",
  },
  {
    locale: "es",
    sourceSlug: "santimetre",
    slug: "centimetro",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "cm",
    name: "Centímetro",
    symbol: "cm",
    shortDescription: "El centímetro equivale a una centésima parte de un metro y se usa en mediciones cotidianas precisas.",
    historySummary: "Introducido con el sistema métrico, el centímetro resulta práctico para objetos pequeños y medianos.",
    measurementSystem: "Sistema Internacional (submúltiplo del SI)",
    siEquivalent: "1 cm = 0,01 m",
    commonUses: "Costura, medidas corporales y objetos cotidianos",
  },
  {
    locale: "es",
    sourceSlug: "milimetre",
    slug: "milimetro",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "mm",
    name: "Milímetro",
    symbol: "mm",
    shortDescription: "El milímetro equivale a una milésima parte de un metro y se usa en mediciones de alta precisión.",
    historySummary: "El milímetro es un submúltiplo métrico habitual en ingeniería y fabricación de precisión.",
    measurementSystem: "Sistema Internacional (submúltiplo del SI)",
    siEquivalent: "1 mm = 0,001 m",
    commonUses: "Ingeniería mecánica, planos técnicos y precisión industrial",
  },
  {
    locale: "es",
    sourceSlug: "fit",
    slug: "pie",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "ft",
    name: "Pie",
    symbol: "ft",
    shortDescription: "El pie es una unidad de longitud anglosajona, usada sobre todo en Estados Unidos y en ciertos contextos del Reino Unido.",
    historySummary: "Basado históricamente en el pie humano, se fijó exactamente en 0,3048 metros mediante un acuerdo internacional de 1959.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 ft = 0,3048 m",
    commonUses: "Inmobiliario, aviación y construcción en Estados Unidos",
  },
  {
    locale: "es",
    sourceSlug: "inc",
    slug: "pulgada",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "in",
    name: "Pulgada",
    symbol: "in",
    shortDescription: "La pulgada es una unidad anglosajona pequeña, muy usada para pantallas y tuberías.",
    historySummary: "Su nombre procede del pulgar y se fijó exactamente en 2,54 centímetros en 1959.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 in = 2,54 cm",
    commonUses: "Tamaño de pantallas, diámetro de tuberías y herramientas",
  },
  {
    locale: "es",
    sourceSlug: "yarda",
    slug: "yarda",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "yd",
    name: "Yarda",
    symbol: "yd",
    shortDescription: "La yarda equivale a 3 pies y se usa especialmente en fútbol americano y golf.",
    historySummary: "De origen inglés, la yarda se fijó exactamente en 0,9144 metros en el acuerdo internacional de 1959.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 yd = 0,9144 m",
    commonUses: "Deporte (fútbol americano y golf) y textil",
  },
  {
    locale: "es",
    sourceSlug: "mil",
    slug: "milla",
    category: "uzunluk",
    categoryName: "Longitud",
    unit: "mi",
    name: "Milla",
    symbol: "mi",
    shortDescription: "La milla terrestre se usa para distancias por carretera en Estados Unidos y el Reino Unido.",
    historySummary: "Derivada de la milla romana, la milla terrestre internacional equivale exactamente a 1.609,344 metros.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 mi = 1.609,344 m",
    commonUses: "Distancias por carretera en Estados Unidos y el Reino Unido",
  },

  // Superficie
  {
    locale: "es",
    sourceSlug: "metrekare",
    slug: "metro-cuadrado",
    category: "alan",
    categoryName: "Superficie",
    unit: "m²",
    name: "Metro cuadrado",
    symbol: "m²",
    shortDescription: "El metro cuadrado es la unidad derivada del SI para superficie: la de un cuadrado de un metro de lado.",
    historySummary: "Desde la introducción del sistema métrico, el metro cuadrado es la referencia para construcción, vivienda y terrenos.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidad basica del SI para la superficie",
    commonUses: "Superficie de edificios, extensión de terrenos y planos de construcción",
  },
  {
    locale: "es",
    sourceSlug: "hektar",
    slug: "hectarea",
    category: "alan",
    categoryName: "Superficie",
    unit: "ha",
    name: "Hectárea",
    symbol: "ha",
    shortDescription: "La hectárea equivale a 10.000 metros cuadrados y se usa sobre todo en terrenos agrícolas.",
    historySummary: "La hectárea se adoptó para expresar grandes superficies de forma práctica en agricultura y gestión del suelo.",
    measurementSystem: "Sistema métrico (aceptada para su uso con el SI)",
    siEquivalent: "1 ha = 10.000 m²",
    commonUses: "Tierras agrícolas, silvicultura y urbanismo",
  },
  {
    locale: "es",
    sourceSlug: "akre",
    slug: "acre",
    category: "alan",
    categoryName: "Superficie",
    unit: "ac",
    name: "Acre",
    symbol: "ac",
    shortDescription: "El acre es una unidad de superficie del sistema imperial, muy usada en el sector inmobiliario de Estados Unidos.",
    historySummary: "Históricamente, el acre se asociaba a la superficie arada por una yunta en un día; hoy equivale exactamente a 4.046,8564224 m².",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 ac ≈ 4.046,86 m²",
    commonUses: "Terrenos inmobiliarios y agrícolas en Estados Unidos y el Reino Unido",
  },

  // Volumen
  {
    locale: "es",
    sourceSlug: "litre",
    slug: "litro",
    category: "hacim",
    categoryName: "Volumen",
    unit: "L",
    name: "Litro",
    symbol: "L",
    shortDescription: "El litro es la unidad de volumen más usada en la vida diaria y equivale a 0,001 metros cúbicos.",
    historySummary: "El litro se introdujo con el sistema métrico y se acepta para su uso con el SI en líquidos, recipientes y alimentos.",
    measurementSystem: "Sistema métrico (aceptada para su uso con el SI)",
    siEquivalent: "1 L = 0,001 m³",
    commonUses: "Bebidas, combustible y medidas de cocina",
  },
  {
    locale: "es",
    sourceSlug: "mililitre",
    slug: "mililitro",
    category: "hacim",
    categoryName: "Volumen",
    unit: "mL",
    name: "Mililitro",
    symbol: "mL",
    shortDescription: "El mililitro equivale a una milésima parte de un litro y se usa para pequeñas cantidades de líquido.",
    historySummary: "Como submúltiplo del litro, el mililitro es habitual en medicina, laboratorio y cocina.",
    measurementSystem: "Sistema métrico (submúltiplo del litro)",
    siEquivalent: "1 mL = 0,001 L",
    commonUses: "Medicamentos, cosméticos y medidas culinarias precisas",
  },
  {
    locale: "es",
    sourceSlug: "metrekup",
    slug: "metro-cubico",
    category: "hacim",
    categoryName: "Volumen",
    unit: "m³",
    name: "Metro cúbico",
    symbol: "m³",
    shortDescription: "El metro cúbico es la unidad derivada del SI para volumen.",
    historySummary: "Se deriva directamente del metro: corresponde al volumen de un cubo de un metro de lado.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidad de referencia del SI para el volumen",
    commonUses: "Gas natural, hormigón y grandes volúmenes industriales",
  },
  {
    locale: "es",
    sourceSlug: "galon",
    slug: "galon",
    category: "hacim",
    categoryName: "Volumen",
    unit: "gal",
    name: "Galón estadounidense",
    symbol: "gal",
    shortDescription: "El galón estadounidense es una unidad de volumen líquido usada en Estados Unidos, especialmente para combustible.",
    historySummary: "El galón líquido estadounidense deriva de medidas inglesas históricas y no equivale al galón imperial británico.",
    measurementSystem: "Sistema estadounidense (US customary)",
    siEquivalent: "1 gal (US) ≈ 3,785 L",
    commonUses: "Combustible y bebidas en Estados Unidos",
  },

  // Masa
  {
    locale: "es",
    sourceSlug: "kilogram",
    slug: "kilogramo",
    category: "kutle",
    categoryName: "Masa",
    unit: "kg",
    name: "Kilogramo",
    symbol: "kg",
    shortDescription: "El kilogramo es la unidad básica del SI para la masa.",
    historySummary: "Desde 2019, el kilogramo se define mediante un valor fijo de la constante de Planck, en lugar de un prototipo físico.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidad basica del SI para la masa",
    commonUses: "Masa corporal, envíos y cocina",
  },
  {
    locale: "es",
    sourceSlug: "gram",
    slug: "gramo",
    category: "kutle",
    categoryName: "Masa",
    unit: "g",
    name: "Gramo",
    symbol: "g",
    shortDescription: "El gramo equivale a una milésima parte de un kilogramo y se usa para masas pequeñas.",
    historySummary: "El gramo tuvo un papel central en las primeras definiciones del sistema métrico; hoy se deriva del kilogramo.",
    measurementSystem: "Sistema Internacional (submúltiplo del SI)",
    siEquivalent: "1 g = 0,001 kg",
    commonUses: "Cocina, joyería y laboratorio",
  },
  {
    locale: "es",
    sourceSlug: "miligram",
    slug: "miligramo",
    category: "kutle",
    categoryName: "Masa",
    unit: "mg",
    name: "Miligramo",
    symbol: "mg",
    shortDescription: "El miligramo equivale a una milésima parte de un gramo y se usa en farmacia y química.",
    historySummary: "Como submúltiplo del gramo, el miligramo permite expresar cantidades muy pequeñas con precisión.",
    measurementSystem: "Sistema Internacional (submúltiplo del SI)",
    siEquivalent: "1 mg = 0,001 g",
    commonUses: "Dosificación de medicamentos y química analítica",
  },
  {
    locale: "es",
    sourceSlug: "ton",
    slug: "tonelada",
    category: "kutle",
    categoryName: "Masa",
    unit: "t",
    name: "Tonelada",
    symbol: "t",
    shortDescription: "La tonelada métrica equivale a 1.000 kilogramos y se usa para grandes masas.",
    historySummary: "La tonelada métrica permite expresar de forma práctica grandes cargas en industria y transporte.",
    measurementSystem: "Sistema métrico (aceptada para su uso con el SI)",
    siEquivalent: "1 t = 1.000 kg",
    commonUses: "Transporte marítimo, industria pesada y agricultura",
  },
  {
    locale: "es",
    sourceSlug: "pound",
    slug: "libra",
    category: "kutle",
    categoryName: "Masa",
    unit: "lb",
    name: "Libra",
    symbol: "lb",
    shortDescription: "La libra avoirdupois es una unidad de masa usada principalmente en Estados Unidos.",
    historySummary: "La libra avoirdupois internacional se fijó exactamente en 0,45359237 kilogramos en 1959.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 lb = 0,45359237 kg",
    commonUses: "Masa corporal y alimentación en Estados Unidos",
  },
  {
    locale: "es",
    sourceSlug: "ons",
    slug: "onza",
    category: "kutle",
    categoryName: "Masa",
    unit: "oz",
    name: "Onza",
    symbol: "oz",
    shortDescription: "La onza avoirdupois equivale a una dieciseisava parte de una libra y se usa para masas pequeñas.",
    historySummary: "La onza avoirdupois se ha usado durante siglos en el comercio anglosajón para cantidades pequeñas.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 oz ≈ 28,3495 g",
    commonUses: "Alimentación y cosméticos en Estados Unidos",
  },

  // Temperatura
  {
    locale: "es",
    sourceSlug: "santigrat",
    slug: "celsius",
    category: "sicaklik",
    categoryName: "Temperatura",
    unit: "C",
    name: "Celsius",
    symbol: "°C",
    shortDescription: "La escala Celsius se usa en gran parte del mundo; a presión estándar, el agua se congela a 0 °C y hierve a 100 °C.",
    historySummary: "Anders Celsius propuso la escala en 1742; posteriormente se adoptó la orientación actual de sus puntos de referencia.",
    measurementSystem: "Escala de uso métrico habitual",
    siEquivalent: "K = °C + 273,15",
    commonUses: "Meteorología, cocina y ciencia en gran parte del mundo",
  },
  {
    locale: "es",
    sourceSlug: "fahrenhayt",
    slug: "fahrenheit",
    category: "sicaklik",
    categoryName: "Temperatura",
    unit: "F",
    name: "Fahrenheit",
    symbol: "°F",
    shortDescription: "La escala Fahrenheit se usa principalmente en Estados Unidos para la temperatura cotidiana.",
    historySummary: "Daniel Gabriel Fahrenheit propuso la escala en 1724; el agua se congela a 32 °F y hierve a 212 °F a presión estándar.",
    measurementSystem: "Sistema estadounidense (escala comun)",
    siEquivalent: "°C = (°F − 32) × 5/9",
    commonUses: "Meteorología y cocina en Estados Unidos",
  },
  {
    locale: "es",
    sourceSlug: "kelvin",
    slug: "kelvin",
    category: "sicaklik",
    categoryName: "Temperatura",
    unit: "K",
    name: "Kelvin",
    symbol: "K",
    shortDescription: "El kelvin es la unidad básica del SI para temperatura termodinámica y parte del cero absoluto.",
    historySummary: "La unidad recibe su nombre de William Thomson, Lord Kelvin. Su escala comienza en 0 K; el símbolo K no lleva signo de grado.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidad basica del SI para la temperatura",
    commonUses: "Investigación científica, física y astronomía",
  },

  // Tiempo
  {
    locale: "es",
    sourceSlug: "saniye",
    slug: "segundo",
    category: "zaman",
    categoryName: "Tiempo",
    unit: "s",
    name: "Segundo",
    symbol: "s",
    shortDescription: "El segundo es la unidad básica del SI para el tiempo.",
    historySummary: "Desde 1967, se define por 9.192.631.770 períodos de radiación asociados al átomo de cesio-133.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidad basica del SI para el tiempo",
    commonUses: "Cronometraje deportivo, ciencia e informática",
  },
  {
    locale: "es",
    sourceSlug: "dakika",
    slug: "minuto",
    category: "zaman",
    categoryName: "Tiempo",
    unit: "min",
    name: "Minuto",
    symbol: "min",
    shortDescription: "El minuto equivale a 60 segundos y es una unidad cotidiana de tiempo.",
    historySummary: "La división en 60 unidades procede del sistema sexagesimal de la antigua Mesopotamia.",
    measurementSystem: "Aceptado junto al SI",
    siEquivalent: "1 min = 60 s",
    commonUses: "Horarios, cocina, deporte",
  },
  {
    locale: "es",
    sourceSlug: "saat",
    slug: "hora",
    category: "zaman",
    categoryName: "Tiempo",
    unit: "h",
    name: "Hora",
    symbol: "h",
    shortDescription: "La hora equivale a 60 minutos y se usa para organizar el día.",
    historySummary: "La división del día en 24 horas se remonta a prácticas de medición del tiempo del Antiguo Egipto.",
    measurementSystem: "Aceptado junto al SI",
    siEquivalent: "1 h = 3.600 s",
    commonUses: "Tiempo de trabajo, viajes y horarios",
  },
  {
    locale: "es",
    sourceSlug: "gun",
    slug: "dia",
    category: "zaman",
    categoryName: "Tiempo",
    unit: "day",
    name: "Día",
    symbol: "d",
    shortDescription: "El día civil equivale a 24 horas, es decir, 86.400 segundos.",
    historySummary: "Su uso parte del ciclo de luz y oscuridad observado desde la antigüedad; la rotación terrestre real no dura exactamente 24 horas.",
    measurementSystem: "Aceptado junto al SI",
    siEquivalent: "1 d = 86.400 s",
    commonUses: "Calendario, planificación y cálculo de duraciones",
  },

  // Velocidad
  {
    locale: "es",
    sourceSlug: "kilometre-saat",
    slug: "kilometro-hora",
    category: "hiz",
    categoryName: "Velocidad",
    unit: "km/h",
    name: "Kilómetro por hora",
    symbol: "km/h",
    shortDescription: "El kilómetro por hora es la unidad habitual de velocidad vial en gran parte del mundo.",
    historySummary: "Al combinar kilómetro y hora, se consolidó como referencia práctica de tráfico y transporte en países métricos.",
    measurementSystem: "Sistema métrico (unidad de uso común)",
    siEquivalent: "1 km/h ≈ 0,278 m/s",
    commonUses: "Velocidad de vehículos y límites de velocidad",
  },
  {
    locale: "es",
    sourceSlug: "metre-saniye",
    slug: "metro-segundo",
    category: "hiz",
    categoryName: "Velocidad",
    unit: "m/s",
    name: "Metro por segundo",
    symbol: "m/s",
    shortDescription: "El metro por segundo es la unidad derivada del SI para velocidad, habitual en física y meteorología.",
    historySummary: "Se deriva directamente del metro y del segundo, por lo que es la referencia de los cálculos científicos.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "Unidad SI derivada de la velocidad",
    commonUses: "Velocidad del viento y cálculos físicos",
  },
  {
    locale: "es",
    sourceSlug: "mil-saat",
    slug: "milla-hora",
    category: "hiz",
    categoryName: "Velocidad",
    unit: "mph",
    name: "Milla por hora",
    symbol: "mph",
    shortDescription: "La milla por hora es la unidad de velocidad vial en Estados Unidos y el Reino Unido.",
    historySummary: "Derivada de la milla terrestre, esta unidad sigue siendo la referencia de tráfico en Estados Unidos y el Reino Unido.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 mph ≈ 0,447 m/s",
    commonUses: "Velocidad de vehículos en Estados Unidos y el Reino Unido",
  },
  {
    locale: "es",
    sourceSlug: "knot",
    slug: "nudo",
    category: "hiz",
    categoryName: "Velocidad",
    unit: "knot",
    name: "Nudo",
    symbol: "kn",
    shortDescription: "El nudo equivale a una milla náutica por hora y es la unidad estándar de navegación marítima y aérea.",
    historySummary: "Su nombre procede del método histórico de contar los nudos de una cuerda lanzada al agua para estimar la velocidad de un barco.",
    measurementSystem: "Navegación marítima y aérea",
    siEquivalent: "1 kn ≈ 0,514 m/s",
    commonUses: "Velocidad de barcos y aviones",
  },

  // Presion
  {
    locale: "es",
    sourceSlug: "pascal",
    slug: "pascal",
    category: "basinc",
    categoryName: "Presión",
    unit: "Pa",
    name: "Pascal",
    symbol: "Pa",
    shortDescription: "El pascal es la unidad derivada del SI para presión y equivale a un newton por metro cuadrado.",
    historySummary: "Recibe su nombre de Blaise Pascal y fue adoptado como unidad del SI para presión en 1971.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "1 Pa = 1 N/m²",
    commonUses: "Cálculos científicos y de ingeniería",
  },
  {
    locale: "es",
    sourceSlug: "bar",
    slug: "bar",
    category: "basinc",
    categoryName: "Presión",
    unit: "bar",
    name: "Bar",
    symbol: "bar",
    shortDescription: "El bar es una unidad práctica de presión, cercana a una atmósfera estándar y muy usada en industria.",
    historySummary: "El bar se introdujo a comienzos del siglo XX y sigue utilizándose junto al pascal en muchos ámbitos técnicos.",
    measurementSystem: "Fuera del SI",
    siEquivalent: "1 bar = 100.000 Pa",
    commonUses: "Sistemas industriales, compresores y meteorología",
  },
  {
    locale: "es",
    sourceSlug: "psi",
    slug: "psi",
    category: "basinc",
    categoryName: "Presión",
    unit: "psi",
    name: "PSI",
    symbol: "psi",
    shortDescription: "El psi, o libra-fuerza por pulgada cuadrada, es una unidad anglosajona habitual para neumáticos.",
    historySummary: "El psi se consolidó en Estados Unidos para la presión de neumáticos y sistemas hidráulicos y neumáticos.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 psi ≈ 6894,76 Pa",
    commonUses: "Presión de neumáticos y sistemas hidráulicos o neumáticos",
  },
  {
    locale: "es",
    sourceSlug: "atmosfer",
    slug: "atmosfera",
    category: "basinc",
    categoryName: "Presión",
    unit: "atm",
    name: "Atmósfera estándar",
    symbol: "atm",
    shortDescription: "La atmósfera estándar es una presión de referencia definida, cercana a la presión media al nivel del mar.",
    historySummary: "La unidad se relaciona con la historia de la barometría y se usa como referencia en condiciones estándar, no como valor meteorológico fijo.",
    measurementSystem: "Fuera del SI (unidad de referencia)",
    siEquivalent: "1 atm = 101.325 Pa",
    commonUses: "Condiciones atmosféricas y de referencia",
  },

  // Energía
  {
    locale: "es",
    sourceSlug: "joule",
    slug: "julio",
    category: "enerji",
    categoryName: "Energía",
    unit: "J",
    name: "Julio",
    symbol: "J",
    shortDescription: "El julio es la unidad derivada del SI para energía y equivale a un newton-metro.",
    historySummary: "Recibe su nombre de James Prescott Joule por sus trabajos sobre energía y calor.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "1 J = 1 N·m",
    commonUses: "Cálculos científicos y físicos de energía",
  },
  {
    locale: "es",
    sourceSlug: "kilovatsaat",
    slug: "kilovatio-hora",
    category: "enerji",
    categoryName: "Energía",
    unit: "kWh",
    name: "Kilovatio-hora",
    symbol: "kWh",
    shortDescription: "El kilovatio-hora mide energía consumida y es la unidad habitual de facturación eléctrica.",
    historySummary: "Se generalizó con la electrificación doméstica y continúa como referencia de los contadores eléctricos.",
    measurementSystem: "Electricidad",
    siEquivalent: "1 kWh = 3.600.000 J",
    commonUses: "Facturación eléctrica",
  },
  {
    locale: "es",
    sourceSlug: "kalori",
    slug: "caloria",
    category: "enerji",
    categoryName: "Energía",
    unit: "cal",
    name: "Caloría",
    symbol: "cal",
    shortDescription: "La caloría termoquímica equivale exactamente a 4,184 J y se usa sobre todo en nutrición.",
    historySummary: "Definida en el siglo XIX para estudios térmicos, hoy se utiliza principalmente como kilocaloría en etiquetas nutricionales.",
    measurementSystem: "Unidad tradicional",
    siEquivalent: "1 cal = 4,184 J",
    commonUses: "Nutrición y química",
  },
  {
    locale: "es",
    sourceSlug: "btu",
    slug: "btu",
    category: "enerji",
    categoryName: "Energía",
    unit: "Btu",
    name: "BTU",
    symbol: "BTU",
    shortDescription: "El BTU es una unidad de energía usada sobre todo para capacidad de calefacción y aire acondicionado.",
    historySummary: "De origen anglosajón, el BTU sigue siendo habitual en Estados Unidos para equipos térmicos.",
    measurementSystem: "Sistema imperial/estadounidense",
    siEquivalent: "1 Btu ≈ 1055,06 J",
    commonUses: "Climatización y calefacción",
  },

  // Almacenamiento de datos
  {
    locale: "es",
    sourceSlug: "bayt",
    slug: "byte",
    category: "veri",
    categoryName: "Almacenamiento de datos",
    unit: "B",
    name: "Byte",
    symbol: "B",
    shortDescription: "El byte equivale a 8 bits y es una unidad básica para datos digitales.",
    historySummary: "El byte se consolidó con los primeros ordenadores como unidad habitual de procesamiento y almacenamiento.",
    measurementSystem: "Informática",
    siEquivalent: "1 B = 8 bits",
    commonUses: "Tamaño de archivos, memoria y almacenamiento",
  },
  {
    locale: "es",
    sourceSlug: "megabayt",
    slug: "megabyte",
    category: "veri",
    categoryName: "Almacenamiento de datos",
    unit: "MB",
    name: "Megabyte",
    symbol: "MB",
    shortDescription: "El megabyte equivale a 1.000.000 bytes y se usa para archivos medianos, como fotos o documentos.",
    historySummary: "Creció como unidad habitual de archivos digitales con el aumento de la capacidad de almacenamiento.",
    measurementSystem: "Informática decimal",
    siEquivalent: "1 MB = 1.000.000 B",
    commonUses: "Tamaño de fotos, documentos y aplicaciones",
  },
  {
    locale: "es",
    sourceSlug: "gigabayt",
    slug: "gigabyte",
    category: "veri",
    categoryName: "Almacenamiento de datos",
    unit: "GB",
    name: "Gigabyte",
    symbol: "GB",
    shortDescription: "El gigabyte equivale a 1.000.000.000 bytes y se usa para capacidad de almacenamiento y datos.",
    historySummary: "Se consolidó con el almacenamiento digital masivo en discos, memorias USB y dispositivos móviles.",
    measurementSystem: "Informática decimal",
    siEquivalent: "1 GB = 1.000.000.000 B",
    commonUses: "Almacenamiento de móviles, ordenadores y tarifas de internet",
  },

  // Electricidad
  {
    locale: "es",
    sourceSlug: "volt",
    slug: "voltio",
    category: "elektrik",
    categoryName: "Electricidad",
    unit: "V",
    name: "Voltio",
    symbol: "V",
    shortDescription: "El voltio es la unidad derivada del SI para diferencia de potencial eléctrico.",
    historySummary: "Recibe su nombre de Alessandro Volta, pionero de la pila eléctrica.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "1 V = 1 J/C",
    commonUses: "Pilas, red eléctrica y circuitos electrónicos",
  },
  {
    locale: "es",
    sourceSlug: "amper",
    slug: "amperio",
    category: "elektrik",
    categoryName: "Electricidad",
    unit: "A",
    name: "Amperio",
    symbol: "A",
    shortDescription: "El amperio es la unidad básica del SI para corriente eléctrica.",
    historySummary: "Recibe su nombre de André-Marie Ampère, pionero del electromagnetismo.",
    measurementSystem: "Sistema Internacional (SI)",
    siEquivalent: "1 A = 1 C/s",
    commonUses: "Circuitos eléctricos, interruptores y cargadores",
  },
  {
    locale: "es",
    sourceSlug: "miliamper",
    slug: "miliamperio",
    category: "elektrik",
    categoryName: "Electricidad",
    unit: "mA",
    name: "Miliamperio",
    symbol: "mA",
    shortDescription: "El miliamperio equivale a una milésima parte de un amperio y se usa para corrientes pequeñas.",
    historySummary: "Como submúltiplo del amperio, el miliamperio resulta práctico en electrónica y sensores.",
    measurementSystem: "Sistema Internacional (submúltiplo del SI)",
    siEquivalent: "1 mA = 0,001 A",
    commonUses: "Baterías de móviles, sensores y circuitos electrónicos",
  },

  // Quilate de oro
  {
    locale: "es",
    sourceSlug: "24-ayar-altin",
    slug: "oro-24-quilates",
    category: "altin_ayar",
    categoryName: "Quilate de oro",
    unit: "24K",
    name: "Oro de 24 quilates",
    symbol: "24K",
    shortDescription: "El oro de 24 quilates representa la referencia máxima de la escala de pureza en quilates.",
    historySummary: "El 24K se utiliza principalmente en lingotes y productos de inversión por su alto contenido de oro fino.",
    measurementSystem: "Sistema de quilates",
    siEquivalent: "24/24 de oro fino",
    commonUses: "Lingotes e inversión en oro",
  },
  {
    locale: "es",
    sourceSlug: "22-ayar-altin",
    slug: "oro-22-quilates",
    category: "altin_ayar",
    categoryName: "Quilate de oro",
    unit: "22K",
    name: "Oro de 22 quilates",
    symbol: "22K",
    shortDescription: "El oro de 22 quilates contiene 22/24 de oro fino, aproximadamente un 91,7 %.",
    historySummary: "Muy usado en Asia meridional y Oriente Medio, equilibra alto contenido de oro y resistencia para joyería.",
    measurementSystem: "Sistema de quilates",
    siEquivalent: "91,7 % de oro fino",
    commonUses: "Joyería tradicional",
  },
  {
    locale: "es",
    sourceSlug: "18-ayar-altin",
    slug: "oro-18-quilates",
    category: "altin_ayar",
    categoryName: "Quilate de oro",
    unit: "18K",
    name: "Oro de 18 quilates",
    symbol: "18K",
    shortDescription: "El oro de 18 quilates contiene 18/24 de oro fino, es decir, un 75 %.",
    historySummary: "Su equilibrio entre pureza y resistencia lo hace frecuente en joyería de Europa y América.",
    measurementSystem: "Sistema de quilates",
    siEquivalent: "75 % de oro fino",
    commonUses: "Joyería y anillos de boda",
  },

  // Ley de la plata
  {
    locale: "es",
    sourceSlug: "999-ayar-gumus",
    slug: "plata-999",
    category: "gumus_ayar",
    categoryName: "Ley de la plata",
    unit: "999",
    name: "Plata 999 (fina)",
    symbol: "999",
    shortDescription: "La plata 999 contiene un 99,9 % de plata fina y se usa principalmente en lingotes.",
    historySummary: "Su alta pureza la hace habitual en productos de inversión y lingotes de plata.",
    measurementSystem: "Sistema de milesimas",
    siEquivalent: "99,9 % de plata fina",
    commonUses: "Lingotes e inversión en plata",
  },
  {
    locale: "es",
    sourceSlug: "925-ayar-gumus",
    slug: "plata-esterlina-925",
    category: "gumus_ayar",
    categoryName: "Ley de la plata",
    unit: "925",
    name: "Plata esterlina (925)",
    symbol: "925",
    shortDescription: "La plata esterlina 925 contiene un 92,5 % de plata fina y se usa ampliamente en joyería.",
    historySummary: "La plata esterlina se consolidó históricamente en Inglaterra y sigue siendo una ley muy reconocida para joyería y cubertería.",
    measurementSystem: "Sistema de milesimas",
    siEquivalent: "92,5 % de plata fina",
    commonUses: "Joyería y cubertería",
  },
];

export function findSpanishUnitPageBySourceSlug(sourceSlug: string) {
  return spanishUnitPages.find((page) => page.sourceSlug === sourceSlug);
}

export function findSpanishUnitPage(category: string, unit: string) {
  return spanishUnitPages.find(
    (page) => page.category === category && page.unit === unit
  );
}
