// Nederlandstalige eenheidspagina's -- geintegreerd in het nieuwe i18n-systeem.
// Onafhankelijk, nieuw bestand (wijzigt geen bestaande tr/en/de/ar/uz/bn/fr/es/pt/it-bestanden).
// Bereik beperkt tot de 13 kerncategorieen die, samen met de 4
// universele tools (homepage), de 17 elementen vormen die de identiteit
// van de site bepalen.

export type LocalizedNederlandsUnitPage = {
  locale: "nl";
  sourceSlug: string;
  slug: string;
  category: string;
  categoryName: string;
  unit: string;
  name: string;
  symbol: string;
  shortDescription: string;
  historySummary: string;
  measurementSystem: string;
  siEquivalent: string;
  commonUses: string;
};

export const nederlandsUnitPages: LocalizedNederlandsUnitPage[] = [
  // Lengte
  {
    locale: "nl",
    sourceSlug: "metre",
    slug: "meter",
    category: "uzunluk",
    categoryName: "Lengte",
    unit: "m",
    name: "Meter",
    symbol: "m",
    shortDescription: "De meter is de SI-basiseenheid voor lengte.",
    historySummary: "Sinds 1983 wordt de meter nauwkeurig gedefinieerd op basis van de afstand die licht in vacuum aflegt in 1/299.792.458 seconde.",
    measurementSystem: "Internationaal Eenhedenstelsel (SI)",
    siEquivalent: "SI-basiseenheid voor lengte",
    commonUses: "Bouw, sport, wetenschap en dagelijkse afstandsmeting",
  },
  {
    locale: "nl",
    sourceSlug: "kilometre",
    slug: "kilometer",
    category: "uzunluk",
    categoryName: "Lengte",
    unit: "km",
    name: "Kilometer",
    symbol: "km",
    shortDescription: "De kilometer komt overeen met 1000 meter en wordt gebruikt om de afstand tussen steden uit te drukken.",
    historySummary: "De kilometer heeft zich gevestigd als veelvoud van de meter binnen de decimale structuur van het metrieke stelsel en werd de standaardeenheid voor wegen en kaarten.",
    measurementSystem: "Internationaal stelsel (SI, veelvoud)",
    siEquivalent: "1 km = 1000 m",
    commonUses: "Wegafstanden, geografie, cartografie en infrastructuur",
  },
  {
    locale: "nl",
    sourceSlug: "santimetre",
    slug: "centimeter",
    category: "uzunluk",
    categoryName: "Lengte",
    unit: "cm",
    name: "Centimeter",
    symbol: "cm",
    shortDescription: "De centimeter komt overeen met een honderdste van een meter en wordt gebruikt voor nauwkeurige dagelijkse metingen.",
    historySummary: "Geintroduceerd met het metrieke stelsel, werd de centimeter de praktische eenheid voor het meten van kleine en middelgrote objecten.",
    measurementSystem: "Internationaal stelsel (SI, onderdeel)",
    siEquivalent: "1 cm = 0,01 m",
    commonUses: "Kleding, lichaamsmaten, alledaagse objecten",
  },
  {
    locale: "nl",
    sourceSlug: "milimetre",
    slug: "millimeter",
    category: "uzunluk",
    categoryName: "Lengte",
    unit: "mm",
    name: "Millimeter",
    symbol: "mm",
    shortDescription: "De millimeter komt overeen met een duizendste van een meter en wordt gebruikt voor zeer nauwkeurige metingen.",
    historySummary: "De millimeter is een onderdeel van het metrieke stelsel dat is aangenomen voor precisietechniek en -fabricage.",
    measurementSystem: "Internationaal stelsel (SI, onderdeel)",
    siEquivalent: "1 mm = 0,001 m",
    commonUses: "Werktuigbouwkunde, technische tekeningen, industriele precisie",
  },
  {
    locale: "nl",
    sourceSlug: "fit",
    slug: "voet",
    category: "uzunluk",
    categoryName: "Lengte",
    unit: "ft",
    name: "Voet",
    symbol: "ft",
    shortDescription: "De voet is een lengte-eenheid uit het imperiale stelsel, nog steeds gebruikt in de Verenigde Staten en het Verenigd Koninkrijk.",
    historySummary: "Historisch gebaseerd op de lengte van de menselijke voet, werd deze in 1959 via een internationale overeenkomst exact gestandaardiseerd op 0,3048 meter.",
    measurementSystem: "Imperiaal/Amerikaans stelsel",
    siEquivalent: "1 ft = 0,3048 m",
    commonUses: "Vastgoed, luchtvaart (hoogte), bouw in de VS",
  },
  {
    locale: "nl",
    sourceSlug: "inc",
    slug: "inch",
    category: "uzunluk",
    categoryName: "Lengte",
    unit: "in",
    name: "Inch",
    symbol: "in",
    shortDescription: "De inch is een kleine imperiale lengte-eenheid, veel gebruikt voor schermen en leidingen.",
    historySummary: "De inch is genoemd naar de breedte van de menselijke duim en werd in 1959 exact vastgesteld op 2,54 centimeter.",
    measurementSystem: "Imperiaal/Amerikaans stelsel",
    siEquivalent: "1 in = 2,54 cm",
    commonUses: "Schermformaten, leidingdiameter, gereedschap",
  },
  {
    locale: "nl",
    sourceSlug: "yarda",
    slug: "yard",
    category: "uzunluk",
    categoryName: "Lengte",
    unit: "yd",
    name: "Yard",
    symbol: "yd",
    shortDescription: "De yard komt overeen met 3 voet en wordt vooral gebruikt in American football en golf.",
    historySummary: "Van Engelse oorsprong, werd de yard in de internationale eenhedenovereenkomst van 1959 exact gestandaardiseerd op 0,9144 meter.",
    measurementSystem: "Imperiaal/Amerikaans stelsel",
    siEquivalent: "1 yd = 0,9144 m",
    commonUses: "Sport (American football, golf), textiel",
  },
  {
    locale: "nl",
    sourceSlug: "mil",
    slug: "mijl",
    category: "uzunluk",
    categoryName: "Lengte",
    unit: "mi",
    name: "Mijl",
    symbol: "mi",
    shortDescription: "De landmijl is de wegafstandseenheid in de Verenigde Staten en het Verenigd Koninkrijk.",
    historySummary: "Afgeleid van de Romeinse mijl, werd de moderne mijl (landmijl) exact vastgesteld op 1609,344 meter.",
    measurementSystem: "Imperiaal/Amerikaans stelsel",
    siEquivalent: "1 mi = 1609,344 m",
    commonUses: "Wegafstanden in de VS en het VK",
  },

  // Oppervlakte
  {
    locale: "nl",
    sourceSlug: "metrekare",
    slug: "vierkante-meter",
    category: "alan",
    categoryName: "Oppervlakte",
    unit: "m²",
    name: "Vierkante meter",
    symbol: "m²",
    shortDescription: "De vierkante meter is de SI-basiseenheid voor oppervlakte, die van een vierkant met een zijde van een meter.",
    historySummary: "Sinds de invoering van het metrieke stelsel is de vierkante meter de standaardeenheid bij bouw- en grondmetingen.",
    measurementSystem: "Internationaal stelsel (SI)",
    siEquivalent: "SI-basiseenheid voor oppervlakte",
    commonUses: "Oppervlakte van gebouwen, grondomvang, plattegronden",
  },
  {
    locale: "nl",
    sourceSlug: "hektar",
    slug: "hectare",
    category: "alan",
    categoryName: "Oppervlakte",
    unit: "ha",
    name: "Hectare",
    symbol: "ha",
    shortDescription: "De hectare is een grote oppervlakte-eenheid gelijk aan 10.000 vierkante meter, vooral gebruikt voor landbouwgrond.",
    historySummary: "De hectare werd algemeen aangenomen om grote oppervlaktes in de landbouw en het grondbeheer eenvoudig uit te drukken.",
    measurementSystem: "Metriek stelsel (buiten het SI, gangbare eenheid)",
    siEquivalent: "1 ha = 10.000 m²",
    commonUses: "Landbouwgrond, bosbouw, stedenbouw",
  },
  {
    locale: "nl",
    sourceSlug: "akre",
    slug: "acre",
    category: "alan",
    categoryName: "Oppervlakte",
    unit: "ac",
    name: "Acre",
    symbol: "ac",
    shortDescription: "De acre is een oppervlakte-eenheid uit het imperiale stelsel, veel gebruikt in de Amerikaanse vastgoedsector.",
    historySummary: "Historisch stelde de acre de oppervlakte grond voor die een span ossen in een dag kon ploegen; tegenwoordig komt het exact overeen met 4046,8564224 m².",
    measurementSystem: "Imperiaal/Amerikaans stelsel",
    siEquivalent: "1 ac ≈ 4046,86 m²",
    commonUses: "Vastgoed- en landbouwgrond in de VS en het VK",
  },

  // Volume
  {
    locale: "nl",
    sourceSlug: "litre",
    slug: "liter",
    category: "hacim",
    categoryName: "Volume",
    unit: "L",
    name: "Liter",
    symbol: "L",
    shortDescription: "De liter is de meest gebruikte praktische volume-eenheid in het dagelijks leven, gelijk aan 0,001 kubieke meter.",
    historySummary: "De liter werd geintroduceerd met het metrieke stelsel en blijft wereldwijd de standaardeenheid voor vloeistoffen.",
    measurementSystem: "Metriek stelsel (buiten het SI, gangbare eenheid)",
    siEquivalent: "1 L = 0,001 m³",
    commonUses: "Dranken, brandstof, keukenmaten",
  },
  {
    locale: "nl",
    sourceSlug: "mililitre",
    slug: "milliliter",
    category: "hacim",
    categoryName: "Volume",
    unit: "mL",
    name: "Milliliter",
    symbol: "mL",
    shortDescription: "De milliliter komt overeen met een duizendste van een liter, gebruikt voor kleine hoeveelheden vloeistof.",
    historySummary: "Als onderdeel van de liter is de milliliter de standaardeenheid geworden in de geneeskunde en de keuken voor kleine doseringen.",
    measurementSystem: "Metriek stelsel (buiten het SI, onderdeel)",
    siEquivalent: "1 mL = 0,001 L",
    commonUses: "Medicijnen, cosmetica, nauwkeurige keukenmaten",
  },
  {
    locale: "nl",
    sourceSlug: "metrekup",
    slug: "kubieke-meter",
    category: "hacim",
    categoryName: "Volume",
    unit: "m³",
    name: "Kubieke meter",
    symbol: "m³",
    shortDescription: "De kubieke meter is de SI-referentie-eenheid voor volume.",
    historySummary: "De kubieke meter is rechtstreeks afgeleid van de meter, de basiseenheid van lengte, tot de derde macht verheven.",
    measurementSystem: "Internationaal stelsel (SI)",
    siEquivalent: "SI-referentie-eenheid voor volume",
    commonUses: "Aardgas, beton, grote industriele volumes",
  },
  {
    locale: "nl",
    sourceSlug: "galon",
    slug: "gallon",
    category: "hacim",
    categoryName: "Volume",
    unit: "gal",
    name: "Gallon (VS)",
    symbol: "gal",
    shortDescription: "De Amerikaanse gallon is de vloeistofvolume-eenheid die in de Verenigde Staten wordt gebruikt, vooral voor benzine.",
    historySummary: "De Amerikaanse (vloeistof)gallon is afgeleid van oude Engelse maten en verschilt van de Britse imperial gallon.",
    measurementSystem: "Amerikaans gebruikelijk stelsel",
    siEquivalent: "1 gal (VS) ≈ 3,785 L",
    commonUses: "Brandstof en dranken in de Verenigde Staten",
  },

  // Massa
  {
    locale: "nl",
    sourceSlug: "kilogram",
    slug: "kilogram",
    category: "kutle",
    categoryName: "Massa",
    unit: "kg",
    name: "Kilogram",
    symbol: "kg",
    shortDescription: "Het kilogram is de SI-basiseenheid voor massa.",
    historySummary: "Sinds 2019 wordt het kilogram gedefinieerd op basis van de constante van Planck, ter vervanging van het oude metalen prototype dat in Parijs werd bewaard.",
    measurementSystem: "Internationaal stelsel (SI)",
    siEquivalent: "SI-basiseenheid voor massa",
    commonUses: "Lichaamsgewicht, verzendingen, koken",
  },
  {
    locale: "nl",
    sourceSlug: "gram",
    slug: "gram",
    category: "kutle",
    categoryName: "Massa",
    unit: "g",
    name: "Gram",
    symbol: "g",
    shortDescription: "Het gram komt overeen met een duizendste van een kilogram en wordt gebruikt voor kleine hoeveelheden materie.",
    historySummary: "Het gram werd oorspronkelijk gedefinieerd als de massa van een kubieke centimeter water bij 4 °C.",
    measurementSystem: "Internationaal stelsel (SI, onderdeel)",
    siEquivalent: "1 g = 0,001 kg",
    commonUses: "Koken, sieraden, laboratorium",
  },
  {
    locale: "nl",
    sourceSlug: "miligram",
    slug: "milligram",
    category: "kutle",
    categoryName: "Massa",
    unit: "mg",
    name: "Milligram",
    symbol: "mg",
    shortDescription: "Het milligram komt overeen met een duizendste van een gram en wordt vooral gebruikt in de farmacie en scheikunde.",
    historySummary: "Als onderdeel van het gram is het milligram essentieel geworden voor nauwkeurige medicijndosering.",
    measurementSystem: "Internationaal stelsel (SI, onderdeel)",
    siEquivalent: "1 mg = 0,001 g",
    commonUses: "Medicijndosering, analytische scheikunde",
  },
  {
    locale: "nl",
    sourceSlug: "ton",
    slug: "ton",
    category: "kutle",
    categoryName: "Massa",
    unit: "t",
    name: "Ton",
    symbol: "t",
    shortDescription: "De ton komt overeen met 1000 kilogram en wordt gebruikt voor het meten van grote massa's.",
    historySummary: "De metrische ton heeft zich gevestigd om grote massa's in de industrie en het transport eenvoudig uit te drukken.",
    measurementSystem: "Metriek stelsel (buiten het SI, veelvoud)",
    siEquivalent: "1 t = 1000 kg",
    commonUses: "Zeevervoer, zware industrie, landbouw",
  },
  {
    locale: "nl",
    sourceSlug: "pound",
    slug: "pond",
    category: "kutle",
    categoryName: "Massa",
    unit: "lb",
    name: "Pond",
    symbol: "lb",
    shortDescription: "Het pond is de massa-eenheid uit het imperiale stelsel, veel gebruikt in de Verenigde Staten.",
    historySummary: "Het moderne avoirdupois-pond werd in 1959 exact vastgesteld op 0,45359237 kilogram.",
    measurementSystem: "Imperiaal/Amerikaans stelsel",
    siEquivalent: "1 lb = 0,45359237 kg",
    commonUses: "Lichaamsgewicht en voeding in de Verenigde Staten",
  },
  {
    locale: "nl",
    sourceSlug: "ons",
    slug: "ounce",
    category: "kutle",
    categoryName: "Massa",
    unit: "oz",
    name: "Ounce",
    symbol: "oz",
    shortDescription: "De ounce komt overeen met een zestiende van een pond en wordt gebruikt voor kleine massa's in het imperiale stelsel.",
    historySummary: "De avoirdupois-ounce wordt al eeuwenlang in Engeland gebruikt voor kleine hoeveelheden goederen.",
    measurementSystem: "Imperiaal/Amerikaans stelsel",
    siEquivalent: "1 oz ≈ 28,3495 g",
    commonUses: "Voeding en cosmetica in de Verenigde Staten",
  },

  // Temperatuur
  {
    locale: "nl",
    sourceSlug: "santigrat",
    slug: "celsius",
    category: "sicaklik",
    categoryName: "Temperatuur",
    unit: "C",
    name: "Celsius",
    symbol: "°C",
    shortDescription: "De Celsiusschaal wordt in het grootste deel van de wereld gebruikt, met 0 °C als vriespunt en 100 °C als kookpunt van water.",
    historySummary: "Voorgesteld door de Zweedse astronoom Anders Celsius in 1742, werd de schaal later omgekeerd naar de huidige vorm.",
    measurementSystem: "Metriek stelsel (gangbare schaal)",
    siEquivalent: "K = °C + 273,15",
    commonUses: "Weerkunde, dagelijks leven, wetenschap in het grootste deel van de wereld",
  },
  {
    locale: "nl",
    sourceSlug: "fahrenhayt",
    slug: "fahrenheit",
    category: "sicaklik",
    categoryName: "Temperatuur",
    unit: "F",
    name: "Fahrenheit",
    symbol: "°F",
    shortDescription: "De Fahrenheitschaal wordt vooral in de Verenigde Staten gebruikt voor de dagelijkse temperatuur.",
    historySummary: "Voorgesteld in 1724 door de Duitse natuurkundige Daniel Gabriel Fahrenheit, aanvankelijk gebaseerd op een koelmengsel.",
    measurementSystem: "Amerikaans stelsel (gangbare schaal)",
    siEquivalent: "°C = (°F − 32) × 5/9",
    commonUses: "Weerkunde en koken in de Verenigde Staten",
  },
  {
    locale: "nl",
    sourceSlug: "kelvin",
    slug: "kelvin",
    category: "sicaklik",
    categoryName: "Temperatuur",
    unit: "K",
    name: "Kelvin",
    symbol: "K",
    shortDescription: "De kelvin is de SI-basiseenheid voor temperatuur, zonder negatieve waarden.",
    historySummary: "Genoemd naar de natuurkundige William Thomson (Lord Kelvin), begint de kelvinschaal bij het absolute nulpunt, de laagst mogelijke temperatuur.",
    measurementSystem: "Internationaal stelsel (SI)",
    siEquivalent: "SI-basiseenheid voor temperatuur",
    commonUses: "Wetenschappelijk onderzoek, natuurkunde, astronomie",
  },

  // Tijd
  {
    locale: "nl",
    sourceSlug: "saniye",
    slug: "seconde",
    category: "zaman",
    categoryName: "Tijd",
    unit: "s",
    name: "Seconde",
    symbol: "s",
    shortDescription: "De seconde is de SI-basiseenheid voor tijd.",
    historySummary: "Sinds 1967 wordt de seconde gedefinieerd op basis van 9.192.631.770 stralingsperioden van het cesium-133-atoom.",
    measurementSystem: "Internationaal stelsel (SI)",
    siEquivalent: "SI-basiseenheid voor tijd",
    commonUses: "Sporttijdwaarneming, wetenschap, informatica",
  },
  {
    locale: "nl",
    sourceSlug: "dakika",
    slug: "minuut",
    category: "zaman",
    categoryName: "Tijd",
    unit: "min",
    name: "Minuut",
    symbol: "min",
    shortDescription: "De minuut komt overeen met 60 seconden en is de meest gebruikte tijdseenheid in het dagelijks leven.",
    historySummary: "De verdeling in 60 eenheden is afkomstig van het Babylonische sexagesimale getalsysteem, dat vandaag de dag nog steeds wordt gebruikt.",
    measurementSystem: "Naast het SI toegestaan",
    siEquivalent: "1 min = 60 s",
    commonUses: "Roosters, koken, sport",
  },
  {
    locale: "nl",
    sourceSlug: "saat",
    slug: "uur",
    category: "zaman",
    categoryName: "Tijd",
    unit: "h",
    name: "Uur",
    symbol: "h",
    shortDescription: "Het uur komt overeen met 60 minuten en dient om de dag te structureren.",
    historySummary: "De verdeling van de dag in 24 uur gaat terug op het Oude Egypte.",
    measurementSystem: "Naast het SI toegestaan",
    siEquivalent: "1 h = 3600 s",
    commonUses: "Werktijd, reistijd, roosters",
  },
  {
    locale: "nl",
    sourceSlug: "gun",
    slug: "dag",
    category: "zaman",
    categoryName: "Tijd",
    unit: "day",
    name: "Dag",
    symbol: "d",
    shortDescription: "De dag komt overeen met een volledige rotatie van de aarde om haar eigen as, oftewel 24 uur.",
    historySummary: "De duur van de dag is gebaseerd op de dag-nachtcyclus die al sinds de oudheid wordt waargenomen.",
    measurementSystem: "Naast het SI toegestaan",
    siEquivalent: "1 dag = 86.400 s",
    commonUses: "Kalender, planning, duurberekening",
  },

  // Snelheid
  {
    locale: "nl",
    sourceSlug: "kilometre-saat",
    slug: "kilometer-per-uur",
    category: "hiz",
    categoryName: "Snelheid",
    unit: "km/h",
    name: "Kilometer per uur",
    symbol: "km/u",
    shortDescription: "Kilometer per uur is de standaard wegvoertuigsnelheidseenheid in de meeste landen.",
    historySummary: "Aangenomen met het metrieke stelsel, werd deze eenheid wereldwijd de referentie voor snelheidslimieten.",
    measurementSystem: "Metriek stelsel (gangbare eenheid)",
    siEquivalent: "1 km/u ≈ 0,278 m/s",
    commonUses: "Voertuigsnelheid, snelheidslimieten",
  },
  {
    locale: "nl",
    sourceSlug: "metre-saniye",
    slug: "meter-per-seconde",
    category: "hiz",
    categoryName: "Snelheid",
    unit: "m/s",
    name: "Meter per seconde",
    symbol: "m/s",
    shortDescription: "Meter per seconde is de SI-eenheid van snelheid, gebruikt in natuurkunde en meteorologie.",
    historySummary: "Rechtstreeks afgeleid van de meter en de seconde, is dit de standaardeenheid in wetenschappelijke berekeningen.",
    measurementSystem: "Internationaal stelsel (SI)",
    siEquivalent: "Afgeleide SI-eenheid van snelheid",
    commonUses: "Windsnelheid, natuurkundige berekeningen",
  },
  {
    locale: "nl",
    sourceSlug: "mil-saat",
    slug: "mijl-per-uur",
    category: "hiz",
    categoryName: "Snelheid",
    unit: "mph",
    name: "Mijl per uur",
    symbol: "mph",
    shortDescription: "Mijl per uur is de wegvoertuigsnelheidseenheid in de Verenigde Staten en het Verenigd Koninkrijk.",
    historySummary: "Afgeleid van de landmijl, blijft deze eenheid de standaard voor wegbebording in beide landen.",
    measurementSystem: "Imperiaal/Amerikaans stelsel",
    siEquivalent: "1 mph ≈ 0,447 m/s",
    commonUses: "Voertuigsnelheid in de VS en het VK",
  },
  {
    locale: "nl",
    sourceSlug: "knot",
    slug: "knoop",
    category: "hiz",
    categoryName: "Snelheid",
    unit: "knot",
    name: "Knoop",
    symbol: "kn",
    shortDescription: "De knoop (zeemijl per uur) is de standaardsnelheidseenheid in de scheepvaart en luchtvaart.",
    historySummary: "De naam is afgeleid van de historische methode waarbij de knopen van een touw in het water werden geteld om de snelheid van een schip te meten.",
    measurementSystem: "Scheepvaart/luchtvaart",
    siEquivalent: "1 kn ≈ 0,514 m/s",
    commonUses: "Snelheid van schepen en vliegtuigen",
  },

  // Druk
  {
    locale: "nl",
    sourceSlug: "pascal",
    slug: "pascal",
    category: "basinc",
    categoryName: "Druk",
    unit: "Pa",
    name: "Pascal",
    symbol: "Pa",
    shortDescription: "De pascal is de SI-eenheid van druk, gelijk aan een newton per vierkante meter.",
    historySummary: "Genoemd naar Blaise Pascal, in 1971 aangenomen als de SI-eenheid van druk.",
    measurementSystem: "Internationaal stelsel (SI)",
    siEquivalent: "1 Pa = 1 N/m²",
    commonUses: "Wetenschappelijke en technische berekeningen",
  },
  {
    locale: "nl",
    sourceSlug: "bar",
    slug: "bar",
    category: "basinc",
    categoryName: "Druk",
    unit: "bar",
    name: "Bar",
    symbol: "bar",
    shortDescription: "De bar is een praktische drukeenheid dicht bij de gemiddelde atmosferische druk, veel gebruikt in de industrie.",
    historySummary: "In het begin van de 20e eeuw geintroduceerd door meteoroloog Vilhelm Bjerknes, blijft de bar veel gebruikt ondanks de invoering van de pascal.",
    measurementSystem: "Metriek stelsel (buiten het SI)",
    siEquivalent: "1 bar = 100.000 Pa",
    commonUses: "Industriele systemen, compressoren, meteorologie",
  },
  {
    locale: "nl",
    sourceSlug: "psi",
    slug: "psi",
    category: "basinc",
    categoryName: "Druk",
    unit: "psi",
    name: "PSI",
    symbol: "psi",
    shortDescription: "PSI (pound-force per vierkante inch) is de drukeenheid uit het imperiale stelsel, gangbaar voor banden.",
    historySummary: "PSI heeft zich gevestigd met het Amerikaanse imperiale stelsel, vooral voor bandenspanning en hydraulische systemen.",
    measurementSystem: "Imperiaal/Amerikaans stelsel",
    siEquivalent: "1 psi ≈ 6894,76 Pa",
    commonUses: "Bandenspanning, hydraulische en pneumatische systemen",
  },
  {
    locale: "nl",
    sourceSlug: "atmosfer",
    slug: "atmosfeer",
    category: "basinc",
    categoryName: "Druk",
    unit: "atm",
    name: "Standaardatmosfeer",
    symbol: "atm",
    shortDescription: "De standaardatmosfeer stelt bij benadering de gemiddelde atmosferische druk op zeeniveau voor.",
    historySummary: "Gedefinieerd op basis van de barometrische metingen van Torricelli in de 17e eeuw, dient als referentie voor standaardomstandigheden.",
    measurementSystem: "Buiten het SI (referentie-eenheid)",
    siEquivalent: "1 atm = 101.325 Pa",
    commonUses: "Atmosferische en referentieomstandigheden",
  },

  // Energie
  {
    locale: "nl",
    sourceSlug: "joule",
    slug: "joule",
    category: "enerji",
    categoryName: "Energie",
    unit: "J",
    name: "Joule",
    symbol: "J",
    shortDescription: "De joule is de SI-eenheid van energie, gelijk aan de arbeid van een kracht van een newton over een afstand van een meter.",
    historySummary: "Genoemd naar de Engelse natuurkundige James Prescott Joule voor zijn werk aan energie en warmte.",
    measurementSystem: "Internationaal stelsel (SI)",
    siEquivalent: "1 J = 1 N·m",
    commonUses: "Wetenschappelijke en natuurkundige energieberekeningen",
  },
  {
    locale: "nl",
    sourceSlug: "kilovatsaat",
    slug: "kilowattuur",
    category: "enerji",
    categoryName: "Energie",
    unit: "kWh",
    name: "Kilowattuur",
    symbol: "kWh",
    shortDescription: "De kilowattuur is de wereldwijde standaardeenheid voor het factureren van elektriciteitsverbruik.",
    historySummary: "Aangenomen met de verspreiding van elektriciteit in huishoudens, blijft de kilowattuur de referentie-eenheid van elektriciteitsmeters.",
    measurementSystem: "Metriek stelsel (elektriciteit)",
    siEquivalent: "1 kWh = 3.600.000 J",
    commonUses: "Elektriciteitsfacturering",
  },
  {
    locale: "nl",
    sourceSlug: "kalori",
    slug: "calorie",
    category: "enerji",
    categoryName: "Energie",
    unit: "cal",
    name: "Calorie",
    symbol: "cal",
    shortDescription: "De calorie is de energie die nodig is om de temperatuur van een gram water met een graad Celsius te verhogen.",
    historySummary: "In de 19e eeuw gedefinieerd voor thermisch onderzoek, wordt de calorie tegenwoordig vooral geassocieerd met voeding.",
    measurementSystem: "Metriek stelsel (traditioneel)",
    siEquivalent: "1 cal = 4,184 J",
    commonUses: "Voeding en scheikunde",
  },
  {
    locale: "nl",
    sourceSlug: "btu",
    slug: "btu",
    category: "enerji",
    categoryName: "Energie",
    unit: "Btu",
    name: "BTU",
    symbol: "BTU",
    shortDescription: "De BTU (British Thermal Unit) drukt de capaciteit van verwarmings- en klimaatregelingssystemen uit.",
    historySummary: "Van Britse oorsprong, blijft de BTU veel gebruikt in de Verenigde Staten voor thermische apparaten.",
    measurementSystem: "Imperiaal/Amerikaans stelsel",
    siEquivalent: "1 Btu ≈ 1055,06 J",
    commonUses: "Klimaatregeling en verwarming",
  },

  // Data-opslag
  {
    locale: "nl",
    sourceSlug: "bayt",
    slug: "byte",
    category: "veri",
    categoryName: "Data-opslag",
    unit: "B",
    name: "Byte",
    symbol: "B",
    shortDescription: "De byte (8 bit) is de basiseenheid om tekens en digitale gegevens weer te geven.",
    historySummary: "De byte heeft zich gevestigd met de ontwikkeling van de eerste computers als standaardeenheid voor gegevensverwerking.",
    measurementSystem: "Informatica",
    siEquivalent: "1 B = 8 bit",
    commonUses: "Bestandsgrootte, geheugen, opslag",
  },
  {
    locale: "nl",
    sourceSlug: "megabayt",
    slug: "megabyte",
    category: "veri",
    categoryName: "Data-opslag",
    unit: "MB",
    name: "Megabyte",
    symbol: "MB",
    shortDescription: "De megabyte wordt gebruikt om de grootte van middelgrote bestanden, zoals foto's of documenten, uit te drukken.",
    historySummary: "Met de groei van opslagcapaciteit werd de megabyte de gangbare eenheid voor digitale bestanden.",
    measurementSystem: "Informatica (grondtal 1000 of 1024)",
    siEquivalent: "1 MB = 1.000.000 B (of 1024² B op binaire basis)",
    commonUses: "Grootte van foto's, documenten en applicaties",
  },
  {
    locale: "nl",
    sourceSlug: "gigabayt",
    slug: "gigabyte",
    category: "veri",
    categoryName: "Data-opslag",
    unit: "GB",
    name: "Gigabyte",
    symbol: "GB",
    shortDescription: "De gigabyte is de standaardeenheid om de opslagcapaciteit van telefoons en computers uit te drukken.",
    historySummary: "De gigabyte heeft zich gevestigd met de groei van grootschalige digitale opslag (harde schijven, USB-sticks, telefoons).",
    measurementSystem: "Informatica (grondtal 1000 of 1024)",
    siEquivalent: "1 GB = 1.000.000.000 B (of 1024³ B op binaire basis)",
    commonUses: "Opslag van telefoons, computers en internetabonnementen",
  },

  // Elektriciteit
  {
    locale: "nl",
    sourceSlug: "volt",
    slug: "volt",
    category: "elektrik",
    categoryName: "Elektriciteit",
    unit: "V",
    name: "Volt",
    symbol: "V",
    shortDescription: "De volt is de SI-eenheid van elektrisch potentiaalverschil.",
    historySummary: "Genoemd naar de Italiaanse natuurkundige Alessandro Volta, uitvinder van de eerste elektrische batterij.",
    measurementSystem: "Internationaal stelsel (SI)",
    siEquivalent: "SI-eenheid van elektrische spanning",
    commonUses: "Batterijen, stopcontacten, elektronische circuits",
  },
  {
    locale: "nl",
    sourceSlug: "amper",
    slug: "ampere",
    category: "elektrik",
    categoryName: "Elektriciteit",
    unit: "A",
    name: "Ampere",
    symbol: "A",
    shortDescription: "De ampere is de SI-basiseenheid voor elektrische stroom.",
    historySummary: "Genoemd naar de Franse natuurkundige Andre-Marie Ampere, een pionier van het elektromagnetisme.",
    measurementSystem: "Internationaal stelsel (SI)",
    siEquivalent: "SI-basiseenheid voor elektrische stroom",
    commonUses: "Elektrische circuits, stroomonderbrekers, opladers",
  },
  {
    locale: "nl",
    sourceSlug: "miliamper",
    slug: "milliampere",
    category: "elektrik",
    categoryName: "Elektriciteit",
    unit: "mA",
    name: "Milliampere",
    symbol: "mA",
    shortDescription: "De milliampere komt overeen met een duizendste van een ampere en wordt gebruikt om kleine stromen in de elektronica te meten.",
    historySummary: "Als onderdeel van de ampere is de milliampere essentieel geworden met de ontwikkeling van precisie-elektronica.",
    measurementSystem: "Internationaal stelsel (SI, onderdeel)",
    siEquivalent: "1 mA = 0,001 A",
    commonUses: "Telefoonbatterijen, sensoren, elektronische circuits",
  },

  // Goudkaraat
  {
    locale: "nl",
    sourceSlug: "24-ayar-altin",
    slug: "24-karaat-goud",
    category: "altin_ayar",
    categoryName: "Goudkaraat",
    unit: "24K",
    name: "24 karaat goud",
    symbol: "24K",
    shortDescription: "24 karaat goud is 99,9% zuiver goud, de referentie van het karaatsysteem.",
    historySummary: "24 karaat goud wordt traditioneel gebruikt voor beleggingsbaren vanwege de maximale zuiverheid.",
    measurementSystem: "Karaatsysteem",
    siEquivalent: "99,9% zuiver goud",
    commonUses: "Baren en beleggingsgoud",
  },
  {
    locale: "nl",
    sourceSlug: "22-ayar-altin",
    slug: "22-karaat-goud",
    category: "altin_ayar",
    categoryName: "Goudkaraat",
    unit: "22K",
    name: "22 karaat goud",
    symbol: "22K",
    shortDescription: "22 karaat goud bevat ongeveer 91,6% zuiver goud en is gangbaar in traditionele sieraden.",
    historySummary: "Veel gebruikt in Zuid-Azie en het Midden-Oosten, balanceert het zuiverheid en sterkte voor sieradenfabricage.",
    measurementSystem: "Karaatsysteem",
    siEquivalent: "≈91,6% zuiver goud",
    commonUses: "Traditionele sieraden",
  },
  {
    locale: "nl",
    sourceSlug: "18-ayar-altin",
    slug: "18-karaat-goud",
    category: "altin_ayar",
    categoryName: "Goudkaraat",
    unit: "18K",
    name: "18 karaat goud",
    symbol: "18K",
    shortDescription: "18 karaat goud bevat 75% zuiver goud en is de meest gangbare standaard in westerse sieraden.",
    historySummary: "De goede balans tussen hardheid en zuiverheid maakt het de referentie van juweliers in Europa en Amerika.",
    measurementSystem: "Karaatsysteem",
    siEquivalent: "75% zuiver goud",
    commonUses: "Westerse sieraden, trouwringen",
  },

  // Zilvergehalte
  {
    locale: "nl",
    sourceSlug: "999-ayar-gumus",
    slug: "zilver-999",
    category: "gumus_ayar",
    categoryName: "Zilvergehalte",
    unit: "999",
    name: "Zilver 999 (fijn)",
    symbol: "999",
    shortDescription: "Zilver 999 is 99,9% zuiver zilver, vooral gebruikt in beleggingsbaren.",
    historySummary: "Door de maximale zuiverheid ervan is dit de voorkeursstandaard voor beleggingsproducten en zilverbaren.",
    measurementSystem: "Promillesysteem",
    siEquivalent: "99,9% zuiver zilver",
    commonUses: "Baren en beleggingszilver",
  },
  {
    locale: "nl",
    sourceSlug: "925-ayar-gumus",
    slug: "sterlingzilver-925",
    category: "gumus_ayar",
    categoryName: "Zilvergehalte",
    unit: "925",
    name: "Sterlingzilver (925)",
    symbol: "925",
    shortDescription: "Sterlingzilver bevat 92,5% zuiver zilver en is de wereldstandaard voor zilveren sieraden.",
    historySummary: "De sterlingzilverstandaard gaat terug op het 12e-eeuwse Engeland en blijft de meest erkende norm ter wereld.",
    measurementSystem: "Promillesysteem",
    siEquivalent: "92,5% zuiver zilver",
    commonUses: "Sieraden en bestek",
  },
];

export function findNederlandsUnitPageBySourceSlug(sourceSlug: string) {
  return nederlandsUnitPages.find((page) => page.sourceSlug === sourceSlug);
}

export function findNederlandsUnitPage(category: string, unit: string) {
  return nederlandsUnitPages.find(
    (page) => page.category === category && page.unit === unit
  );
}
