// Pages d'unite francaises -- integrees au nouveau systeme i18n
// Fichier independant et nouveau (ne touche pas aux fichiers tr/en/de/ar/uz/bn existants).
// Portee volontairement limitee aux 13 categories fondamentales qui, avec
// les 4 outils universels (page d'accueil), forment les 17 elements de
// l'identite du site -- pas de categories techniques/medicales annexes
// (tork, kan sekeri, etc.) a ce stade.

export type LocalizedFrenchUnitPage = {
  locale: "fr";
  sourceSlug: string;
  slug: string;
  category: string;
  categoryName: string;
  unit: string;
  name: string;
  symbol: string;
  shortDescription: string;
  historySummary: string;
  measurementSystem: string;
  siEquivalent: string;
  commonUses: string;
};

export const frenchUnitPages: LocalizedFrenchUnitPage[] = [
  // Longueur
  {
    locale: "fr",
    sourceSlug: "metre",
    slug: "metre",
    category: "uzunluk",
    categoryName: "Longueur",
    unit: "m",
    name: "Metre",
    symbol: "m",
    shortDescription: "Le metre est l'unite SI de base de la longueur.",
    historySummary:
      "Depuis 1983, le metre est defini avec precision a partir de la distance parcourue par la lumiere dans le vide en 1/299 792 458 de seconde.",
    measurementSystem: "Systeme international d'unites (SI)",
    siEquivalent: "Unite SI de base de la longueur",
    commonUses: "Construction, sport, sciences et mesure de distance au quotidien",
  },
  {
    locale: "fr",
    sourceSlug: "kilometre",
    slug: "kilometre",
    category: "uzunluk",
    categoryName: "Longueur",
    unit: "km",
    name: "Kilometre",
    symbol: "km",
    shortDescription: "Le kilometre vaut 1000 metres et sert a exprimer la distance entre les villes.",
    historySummary:
      "Le kilometre s'est impose comme multiple du metre dans la structure decimale du systeme metrique, devenant l'unite standard des routes et des cartes.",
    measurementSystem: "Systeme international (SI, multiple)",
    siEquivalent: "1 km = 1000 m",
    commonUses: "Distance routiere, geographie, cartographie et infrastructure",
  },
  {
    locale: "fr",
    sourceSlug: "santimetre",
    slug: "centimetre",
    category: "uzunluk",
    categoryName: "Longueur",
    unit: "cm",
    name: "Centimetre",
    symbol: "cm",
    shortDescription: "Le centimetre vaut un centieme de metre et sert aux mesures precises du quotidien.",
    historySummary:
      "Introduit avec le systeme metrique, le centimetre est devenu l'unite pratique pour mesurer des objets de petite et moyenne taille.",
    measurementSystem: "Systeme international (SI, sous-multiple)",
    siEquivalent: "1 cm = 0,01 m",
    commonUses: "Couture, mesures corporelles, objets du quotidien",
  },
  {
    locale: "fr",
    sourceSlug: "milimetre",
    slug: "millimetre",
    category: "uzunluk",
    categoryName: "Longueur",
    unit: "mm",
    name: "Millimetre",
    symbol: "mm",
    shortDescription: "Le millimetre vaut un millieme de metre, utilise pour les mesures de haute precision.",
    historySummary:
      "Le millimetre est un sous-multiple du systeme metrique adopte pour l'ingenierie et la fabrication de precision.",
    measurementSystem: "Systeme international (SI, sous-multiple)",
    siEquivalent: "1 mm = 0,001 m",
    commonUses: "Ingenierie mecanique, plans techniques, precision industrielle",
  },
  {
    locale: "fr",
    sourceSlug: "fit",
    slug: "pied",
    category: "uzunluk",
    categoryName: "Longueur",
    unit: "ft",
    name: "Pied",
    symbol: "ft",
    shortDescription: "Le pied est une unite de longueur du systeme imperial, encore utilisee aux Etats-Unis et au Royaume-Uni.",
    historySummary:
      "Historiquement base sur la longueur du pied humain, le pied a ete standardise a 0,3048 metre exactement en 1959 par accord international.",
    measurementSystem: "Systeme imperial/americain",
    siEquivalent: "1 ft = 0,3048 m",
    commonUses: "Immobilier, aviation (altitude), construction aux Etats-Unis",
  },
  {
    locale: "fr",
    sourceSlug: "inc",
    slug: "pouce",
    category: "uzunluk",
    categoryName: "Longueur",
    unit: "in",
    name: "Pouce",
    symbol: "in",
    shortDescription: "Le pouce est une petite unite de longueur imperiale, tres utilisee pour les ecrans et les tuyaux.",
    historySummary:
      "Le pouce tire son nom de la largeur du pouce humain et a ete fixe a exactement 2,54 centimetres en 1959.",
    measurementSystem: "Systeme imperial/americain",
    siEquivalent: "1 in = 2,54 cm",
    commonUses: "Taille des ecrans, diametre des tuyaux, outillage",
  },
  {
    locale: "fr",
    sourceSlug: "yarda",
    slug: "yard",
    category: "uzunluk",
    categoryName: "Longueur",
    unit: "yd",
    name: "Yard",
    symbol: "yd",
    shortDescription: "Le yard vaut 3 pieds et est utilise notamment au football americain et en golf.",
    historySummary:
      "D'origine anglaise, le yard a ete standardise a 0,9144 metre exactement lors de l'accord international de 1959 sur les unites.",
    measurementSystem: "Systeme imperial/americain",
    siEquivalent: "1 yd = 0,9144 m",
    commonUses: "Sport (football americain, golf), textile",
  },
  {
    locale: "fr",
    sourceSlug: "mil",
    slug: "mile",
    category: "uzunluk",
    categoryName: "Longueur",
    unit: "mi",
    name: "Mile",
    symbol: "mi",
    shortDescription: "Le mile terrestre est l'unite de distance routiere aux Etats-Unis et au Royaume-Uni.",
    historySummary:
      "Derive du mille romain, le mile moderne (mile terrestre) a ete fixe a 1609,344 metres exactement.",
    measurementSystem: "Systeme imperial/americain",
    siEquivalent: "1 mi = 1609,344 m",
    commonUses: "Distances routieres aux Etats-Unis et au Royaume-Uni",
  },

  // Surface
  {
    locale: "fr",
    sourceSlug: "metrekare",
    slug: "metre-carre",
    category: "alan",
    categoryName: "Surface",
    unit: "m²",
    name: "Metre carre",
    symbol: "m²",
    shortDescription: "Le metre carre est l'unite SI de base de la surface, celle d'un carre d'un metre de cote.",
    historySummary: "Depuis l'introduction du systeme metrique, le metre carre est l'unite standard des mesures de construction et de terrain.",
    measurementSystem: "Systeme international (SI)",
    siEquivalent: "Unite SI de base de la surface",
    commonUses: "Surface des batiments, superficie des terrains, plans de construction",
  },
  {
    locale: "fr",
    sourceSlug: "hektar",
    slug: "hectare",
    category: "alan",
    categoryName: "Surface",
    unit: "ha",
    name: "Hectare",
    symbol: "ha",
    shortDescription: "L'hectare est une grande unite de surface egale a 10 000 metres carres, surtout utilisee pour les terres agricoles.",
    historySummary: "L'hectare a ete largement adopte pour exprimer facilement de grandes surfaces en agriculture et en gestion fonciere.",
    measurementSystem: "Systeme metrique (hors SI, unite courante)",
    siEquivalent: "1 ha = 10 000 m²",
    commonUses: "Terres agricoles, foresterie, urbanisme",
  },
  {
    locale: "fr",
    sourceSlug: "akre",
    slug: "acre",
    category: "alan",
    categoryName: "Surface",
    unit: "ac",
    name: "Acre",
    symbol: "ac",
    shortDescription: "L'acre est une unite de surface du systeme imperial, tres utilisee en immobilier aux Etats-Unis.",
    historySummary: "Historiquement, l'acre representait la surface qu'une paire de boeufs pouvait labourer en un jour ; elle vaut aujourd'hui exactement 4046,8564224 m².",
    measurementSystem: "Systeme imperial/americain",
    siEquivalent: "1 ac ≈ 4046,86 m²",
    commonUses: "Immobilier et terrains agricoles aux Etats-Unis et au Royaume-Uni",
  },

  // Volume
  {
    locale: "fr",
    sourceSlug: "litre",
    slug: "litre",
    category: "hacim",
    categoryName: "Volume",
    unit: "L",
    name: "Litre",
    symbol: "L",
    shortDescription: "Le litre est l'unite pratique de volume la plus utilisee au quotidien, egale a 0,001 metre cube.",
    historySummary: "Le litre a ete introduit avec le systeme metrique et reste l'unite standard des liquides dans le monde entier.",
    measurementSystem: "Systeme metrique (hors SI, unite courante)",
    siEquivalent: "1 L = 0,001 m³",
    commonUses: "Boissons, carburant, mesures de cuisine",
  },
  {
    locale: "fr",
    sourceSlug: "mililitre",
    slug: "millilitre",
    category: "hacim",
    categoryName: "Volume",
    unit: "mL",
    name: "Millilitre",
    symbol: "mL",
    shortDescription: "Le millilitre vaut un millieme de litre, utilise pour les petites quantites de liquide.",
    historySummary: "Sous-multiple du litre, le millilitre est devenu l'unite standard en medecine et en cuisine pour les petites doses.",
    measurementSystem: "Systeme metrique (hors SI, sous-multiple)",
    siEquivalent: "1 mL = 0,001 L",
    commonUses: "Medicaments, cosmetiques, mesures culinaires precises",
  },
  {
    locale: "fr",
    sourceSlug: "metrekup",
    slug: "metre-cube",
    category: "hacim",
    categoryName: "Volume",
    unit: "m³",
    name: "Metre cube",
    symbol: "m³",
    shortDescription: "Le metre cube est l'unite SI de reference du volume.",
    historySummary: "Le metre cube decoule directement du metre, l'unite de base de longueur, eleve au cube.",
    measurementSystem: "Systeme international (SI)",
    siEquivalent: "Unite SI de reference du volume",
    commonUses: "Gaz naturel, beton, grands volumes industriels",
  },
  {
    locale: "fr",
    sourceSlug: "galon",
    slug: "gallon",
    category: "hacim",
    categoryName: "Volume",
    unit: "gal",
    name: "Gallon (US)",
    symbol: "gal",
    shortDescription: "Le gallon americain est l'unite de volume liquide utilisee aux Etats-Unis, notamment pour l'essence.",
    historySummary: "Le gallon americain (liquide) derive d'anciennes mesures anglaises et differe du gallon imperial britannique.",
    measurementSystem: "Systeme americain (US customary)",
    siEquivalent: "1 gal (US) ≈ 3,785 L",
    commonUses: "Carburant et boissons aux Etats-Unis",
  },

  // Masse
  {
    locale: "fr",
    sourceSlug: "kilogram",
    slug: "kilogramme",
    category: "kutle",
    categoryName: "Masse",
    unit: "kg",
    name: "Kilogramme",
    symbol: "kg",
    shortDescription: "Le kilogramme est l'unite SI de base de la masse.",
    historySummary: "Depuis 2019, le kilogramme est defini a partir de la constante de Planck, remplacant l'ancien prototype en metal conserve a Paris.",
    measurementSystem: "Systeme international (SI)",
    siEquivalent: "Unite SI de base de la masse",
    commonUses: "Poids corporel, expedition, cuisine",
  },
  {
    locale: "fr",
    sourceSlug: "gram",
    slug: "gramme",
    category: "kutle",
    categoryName: "Masse",
    unit: "g",
    name: "Gramme",
    symbol: "g",
    shortDescription: "Le gramme vaut un millieme de kilogramme et sert aux petites quantites de matiere.",
    historySummary: "Le gramme a ete defini a l'origine comme la masse d'un centimetre cube d'eau a 4 °C.",
    measurementSystem: "Systeme international (SI, sous-multiple)",
    siEquivalent: "1 g = 0,001 kg",
    commonUses: "Cuisine, bijouterie, laboratoire",
  },
  {
    locale: "fr",
    sourceSlug: "miligram",
    slug: "milligramme",
    category: "kutle",
    categoryName: "Masse",
    unit: "mg",
    name: "Milligramme",
    symbol: "mg",
    shortDescription: "Le milligramme vaut un millieme de gramme, utilise principalement en pharmacie et en chimie.",
    historySummary: "Sous-multiple du gramme, le milligramme est devenu essentiel pour le dosage precis des medicaments.",
    measurementSystem: "Systeme international (SI, sous-multiple)",
    siEquivalent: "1 mg = 0,001 g",
    commonUses: "Dosage des medicaments, chimie analytique",
  },
  {
    locale: "fr",
    sourceSlug: "ton",
    slug: "tonne",
    category: "kutle",
    categoryName: "Masse",
    unit: "t",
    name: "Tonne",
    symbol: "t",
    shortDescription: "La tonne vaut 1000 kilogrammes et sert a mesurer de grandes masses.",
    historySummary: "La tonne metrique s'est imposee pour exprimer facilement de grandes masses dans l'industrie et le transport.",
    measurementSystem: "Systeme metrique (hors SI, multiple)",
    siEquivalent: "1 t = 1000 kg",
    commonUses: "Fret maritime, industrie lourde, agriculture",
  },
  {
    locale: "fr",
    sourceSlug: "pound",
    slug: "livre",
    category: "kutle",
    categoryName: "Masse",
    unit: "lb",
    name: "Livre",
    symbol: "lb",
    shortDescription: "La livre est l'unite de masse du systeme imperial, tres utilisee aux Etats-Unis.",
    historySummary: "La livre avoirdupois moderne a ete fixee a exactement 0,45359237 kilogramme en 1959.",
    measurementSystem: "Systeme imperial/americain",
    siEquivalent: "1 lb = 0,45359237 kg",
    commonUses: "Poids corporel et alimentation aux Etats-Unis",
  },
  {
    locale: "fr",
    sourceSlug: "ons",
    slug: "once",
    category: "kutle",
    categoryName: "Masse",
    unit: "oz",
    name: "Once",
    symbol: "oz",
    shortDescription: "L'once vaut un seizieme de livre et sert aux petites masses dans le systeme imperial.",
    historySummary: "L'once avoirdupois est utilisee depuis des siecles en Angleterre pour les petites quantites de marchandises.",
    measurementSystem: "Systeme imperial/americain",
    siEquivalent: "1 oz ≈ 28,3495 g",
    commonUses: "Alimentation et cosmetiques aux Etats-Unis",
  },

  // Temperature
  {
    locale: "fr",
    sourceSlug: "santigrat",
    slug: "celsius",
    category: "sicaklik",
    categoryName: "Temperature",
    unit: "C",
    name: "Celsius",
    symbol: "°C",
    shortDescription: "L'echelle Celsius est utilisee dans la majorite du monde, avec 0 °C pour le point de congelation et 100 °C pour l'ebullition de l'eau.",
    historySummary: "Proposee par l'astronome suedois Anders Celsius en 1742, l'echelle a ensuite ete inversee pour donner sa forme actuelle.",
    measurementSystem: "Systeme metrique (echelle courante)",
    siEquivalent: "K = °C + 273,15",
    commonUses: "Meteorologie, cuisine, sciences dans la majorite du monde",
  },
  {
    locale: "fr",
    sourceSlug: "fahrenhayt",
    slug: "fahrenheit",
    category: "sicaklik",
    categoryName: "Temperature",
    unit: "F",
    name: "Fahrenheit",
    symbol: "°F",
    shortDescription: "L'echelle Fahrenheit est utilisee principalement aux Etats-Unis pour la temperature quotidienne.",
    historySummary: "Proposee en 1724 par le physicien allemand Daniel Gabriel Fahrenheit, initialement basee sur un melange refrigerant.",
    measurementSystem: "Systeme americain (echelle courante)",
    siEquivalent: "°C = (°F − 32) × 5/9",
    commonUses: "Meteorologie et cuisine aux Etats-Unis",
  },
  {
    locale: "fr",
    sourceSlug: "kelvin",
    slug: "kelvin",
    category: "sicaklik",
    categoryName: "Temperature",
    unit: "K",
    name: "Kelvin",
    symbol: "K",
    shortDescription: "Le kelvin est l'unite SI de base de la temperature, sans valeurs negatives.",
    historySummary: "Nomme d'apres le physicien William Thomson (Lord Kelvin), le kelvin part du zero absolu, la temperature la plus basse possible.",
    measurementSystem: "Systeme international (SI)",
    siEquivalent: "Unite SI de base de la temperature",
    commonUses: "Recherche scientifique, physique, astronomie",
  },

  // Temps
  {
    locale: "fr",
    sourceSlug: "saniye",
    slug: "seconde",
    category: "zaman",
    categoryName: "Temps",
    unit: "s",
    name: "Seconde",
    symbol: "s",
    shortDescription: "La seconde est l'unite SI de base du temps.",
    historySummary: "Depuis 1967, la seconde est definie a partir de 9 192 631 770 periodes de radiation de l'atome de cesium-133.",
    measurementSystem: "Systeme international (SI)",
    siEquivalent: "Unite SI de base du temps",
    commonUses: "Chronometrage sportif, sciences, informatique",
  },
  {
    locale: "fr",
    sourceSlug: "dakika",
    slug: "minute",
    category: "zaman",
    categoryName: "Temps",
    unit: "min",
    name: "Minute",
    symbol: "min",
    shortDescription: "La minute vaut 60 secondes et est l'unite de temps la plus utilisee au quotidien.",
    historySummary: "La division en 60 unites provient du systeme sexagesimal babylonien, encore utilise aujourd'hui.",
    measurementSystem: "Accepte avec le SI",
    siEquivalent: "1 min = 60 s",
    commonUses: "Emplois du temps, cuisine, sport",
  },
  {
    locale: "fr",
    sourceSlug: "saat",
    slug: "heure",
    category: "zaman",
    categoryName: "Temps",
    unit: "h",
    name: "Heure",
    symbol: "h",
    shortDescription: "L'heure vaut 60 minutes et sert a organiser la journee.",
    historySummary: "La division du jour en 24 heures remonte a l'Egypte antique.",
    measurementSystem: "Accepte avec le SI",
    siEquivalent: "1 h = 3600 s",
    commonUses: "Temps de travail, temps de trajet, emplois du temps",
  },
  {
    locale: "fr",
    sourceSlug: "gun",
    slug: "jour",
    category: "zaman",
    categoryName: "Temps",
    unit: "day",
    name: "Jour",
    symbol: "j",
    shortDescription: "Le jour correspond a une rotation complete de la Terre sur elle-meme, soit 24 heures.",
    historySummary: "La duree du jour est basee sur le cycle jour-nuit observe depuis l'Antiquite.",
    measurementSystem: "Accepte avec le SI",
    siEquivalent: "1 jour = 86 400 s",
    commonUses: "Calendrier, planification, calcul de duree",
  },

  // Vitesse
  {
    locale: "fr",
    sourceSlug: "kilometre-saat",
    slug: "kilometre-heure",
    category: "hiz",
    categoryName: "Vitesse",
    unit: "km/h",
    name: "Kilometre par heure",
    symbol: "km/h",
    shortDescription: "Le kilometre par heure est l'unite standard de vitesse routiere dans la plupart des pays.",
    historySummary: "Adoptee avec le systeme metrique, cette unite est devenue la reference des limitations de vitesse dans le monde entier.",
    measurementSystem: "Systeme metrique (unite courante)",
    siEquivalent: "1 km/h ≈ 0,278 m/s",
    commonUses: "Vitesse des vehicules, limitations de vitesse",
  },
  {
    locale: "fr",
    sourceSlug: "metre-saniye",
    slug: "metre-seconde",
    category: "hiz",
    categoryName: "Vitesse",
    unit: "m/s",
    name: "Metre par seconde",
    symbol: "m/s",
    shortDescription: "Le metre par seconde est l'unite SI de vitesse, utilisee en physique et en meteorologie.",
    historySummary: "Unite derivee directement du metre et de la seconde, standard dans les calculs scientifiques.",
    measurementSystem: "Systeme international (SI)",
    siEquivalent: "Unite SI derivee de la vitesse",
    commonUses: "Vitesse du vent, calculs physiques",
  },
  {
    locale: "fr",
    sourceSlug: "mil-saat",
    slug: "mile-heure",
    category: "hiz",
    categoryName: "Vitesse",
    unit: "mph",
    name: "Mile par heure",
    symbol: "mph",
    shortDescription: "Le mile par heure est l'unite de vitesse routiere aux Etats-Unis et au Royaume-Uni.",
    historySummary: "Derivee du mile terrestre, cette unite reste la norme des panneaux de signalisation americains et britanniques.",
    measurementSystem: "Systeme imperial/americain",
    siEquivalent: "1 mph ≈ 0,447 m/s",
    commonUses: "Vitesse des vehicules aux Etats-Unis et au Royaume-Uni",
  },
  {
    locale: "fr",
    sourceSlug: "knot",
    slug: "noeud",
    category: "hiz",
    categoryName: "Vitesse",
    unit: "knot",
    name: "Noeud",
    symbol: "kn",
    shortDescription: "Le noeud (mille marin par heure) est l'unite standard de vitesse en navigation maritime et aerienne.",
    historySummary: "Le nom vient de la methode historique consistant a compter les noeuds d'une corde jetee a l'eau pour mesurer la vitesse d'un navire.",
    measurementSystem: "Navigation maritime/aerienne",
    siEquivalent: "1 kn ≈ 0,514 m/s",
    commonUses: "Vitesse des navires et des avions",
  },

  // Pression
  {
    locale: "fr",
    sourceSlug: "pascal",
    slug: "pascal",
    category: "basinc",
    categoryName: "Pression",
    unit: "Pa",
    name: "Pascal",
    symbol: "Pa",
    shortDescription: "Le pascal est l'unite SI de pression, egale a un newton par metre carre.",
    historySummary: "Nomme d'apres Blaise Pascal, adopte comme unite SI de pression en 1971.",
    measurementSystem: "Systeme international (SI)",
    siEquivalent: "1 Pa = 1 N/m²",
    commonUses: "Calculs scientifiques et d'ingenierie",
  },
  {
    locale: "fr",
    sourceSlug: "bar",
    slug: "bar",
    category: "basinc",
    categoryName: "Pression",
    unit: "bar",
    name: "Bar",
    symbol: "bar",
    shortDescription: "Le bar est une unite de pression pratique proche de la pression atmospherique moyenne, tres utilisee dans l'industrie.",
    historySummary: "Introduit au debut du XXe siecle par le meteorologue Vilhelm Bjerknes, le bar reste largement utilise malgre l'adoption du pascal.",
    measurementSystem: "Systeme metrique (hors SI)",
    siEquivalent: "1 bar = 100 000 Pa",
    commonUses: "Systemes industriels, compresseurs, meteorologie",
  },
  {
    locale: "fr",
    sourceSlug: "psi",
    slug: "psi",
    category: "basinc",
    categoryName: "Pression",
    unit: "psi",
    name: "PSI",
    symbol: "psi",
    shortDescription: "Le PSI (livre-force par pouce carre) est l'unite de pression du systeme imperial, courante pour les pneus.",
    historySummary: "Le PSI s'est impose avec le systeme imperial americain, particulierement pour la pression des pneus et les systemes hydrauliques.",
    measurementSystem: "Systeme imperial/americain",
    siEquivalent: "1 psi ≈ 6894,76 Pa",
    commonUses: "Pression des pneus, systemes hydrauliques et pneumatiques",
  },
  {
    locale: "fr",
    sourceSlug: "atmosfer",
    slug: "atmosphere",
    category: "basinc",
    categoryName: "Pression",
    unit: "atm",
    name: "Atmosphere standard",
    symbol: "atm",
    shortDescription: "L'atmosphere standard represente approximativement la pression atmospherique moyenne au niveau de la mer.",
    historySummary: "Definie a partir des mesures barometriques de Torricelli au XVIIe siecle, elle sert de reference pour les conditions standard.",
    measurementSystem: "Hors SI (unite de reference)",
    siEquivalent: "1 atm = 101 325 Pa",
    commonUses: "Conditions atmospheriques et de reference",
  },

  // Energie
  {
    locale: "fr",
    sourceSlug: "joule",
    slug: "joule",
    category: "enerji",
    categoryName: "Energie",
    unit: "J",
    name: "Joule",
    symbol: "J",
    shortDescription: "Le joule est l'unite SI d'energie, egale au travail d'une force d'un newton sur une distance d'un metre.",
    historySummary: "Nomme d'apres le physicien anglais James Prescott Joule pour ses travaux sur l'energie et la chaleur.",
    measurementSystem: "Systeme international (SI)",
    siEquivalent: "1 J = 1 N·m",
    commonUses: "Calculs scientifiques et physiques d'energie",
  },
  {
    locale: "fr",
    sourceSlug: "kilovatsaat",
    slug: "kilowattheure",
    category: "enerji",
    categoryName: "Energie",
    unit: "kWh",
    name: "Kilowattheure",
    symbol: "kWh",
    shortDescription: "Le kilowattheure est l'unite standard de facturation de la consommation electrique dans le monde.",
    historySummary: "Adopte avec la generalisation de l'electricite domestique, le kilowattheure reste l'unite de reference des compteurs electriques.",
    measurementSystem: "Systeme metrique (electricite)",
    siEquivalent: "1 kWh = 3 600 000 J",
    commonUses: "Facturation electrique",
  },
  {
    locale: "fr",
    sourceSlug: "kalori",
    slug: "calorie",
    category: "enerji",
    categoryName: "Energie",
    unit: "cal",
    name: "Calorie",
    symbol: "cal",
    shortDescription: "La calorie est l'energie necessaire pour elever d'un degre Celsius la temperature d'un gramme d'eau.",
    historySummary: "Definie au XIXe siecle pour les etudes thermiques, la calorie est aujourd'hui surtout associee a la nutrition.",
    measurementSystem: "Systeme metrique (traditionnel)",
    siEquivalent: "1 cal = 4,184 J",
    commonUses: "Nutrition et chimie",
  },
  {
    locale: "fr",
    sourceSlug: "btu",
    slug: "btu",
    category: "enerji",
    categoryName: "Energie",
    unit: "Btu",
    name: "BTU",
    symbol: "BTU",
    shortDescription: "Le BTU (British Thermal Unit) exprime la capacite des systemes de chauffage et de climatisation.",
    historySummary: "D'origine britannique, le BTU reste largement utilise aux Etats-Unis pour les appareils thermiques.",
    measurementSystem: "Systeme imperial/americain",
    siEquivalent: "1 Btu ≈ 1055,06 J",
    commonUses: "Climatisation et chauffage",
  },

  // Stockage de donnees
  {
    locale: "fr",
    sourceSlug: "bayt",
    slug: "octet",
    category: "veri",
    categoryName: "Stockage de donnees",
    unit: "B",
    name: "Octet",
    symbol: "o",
    shortDescription: "L'octet (8 bits) est l'unite de base pour representer les caracteres et les donnees numeriques.",
    historySummary: "L'octet s'est impose avec le developpement des premiers ordinateurs comme unite standard de traitement des donnees.",
    measurementSystem: "Informatique",
    siEquivalent: "1 o = 8 bits",
    commonUses: "Taille des fichiers, memoire, stockage",
  },
  {
    locale: "fr",
    sourceSlug: "megabayt",
    slug: "megaoctet",
    category: "veri",
    categoryName: "Stockage de donnees",
    unit: "MB",
    name: "Megaoctet",
    symbol: "Mo",
    shortDescription: "Le megaoctet est utilise pour exprimer la taille des fichiers de taille moyenne, comme les photos ou les documents.",
    historySummary: "Avec la croissance des capacites de stockage, le megaoctet est devenu l'unite courante pour les fichiers numeriques.",
    measurementSystem: "Informatique (base 1000 ou 1024)",
    siEquivalent: "1 Mo = 1 000 000 o (ou 1024² o en base binaire)",
    commonUses: "Taille des photos, documents et applications",
  },
  {
    locale: "fr",
    sourceSlug: "gigabayt",
    slug: "gigaoctet",
    category: "veri",
    categoryName: "Stockage de donnees",
    unit: "GB",
    name: "Gigaoctet",
    symbol: "Go",
    shortDescription: "Le gigaoctet est l'unite standard pour exprimer la capacite de stockage des smartphones et ordinateurs.",
    historySummary: "Le gigaoctet s'est impose avec l'essor du stockage numerique de masse (disques durs, cles USB, smartphones).",
    measurementSystem: "Informatique (base 1000 ou 1024)",
    siEquivalent: "1 Go = 1 000 000 000 o (ou 1024³ o en base binaire)",
    commonUses: "Stockage des smartphones, ordinateurs et forfaits internet",
  },

  // Electricite
  {
    locale: "fr",
    sourceSlug: "volt",
    slug: "volt",
    category: "elektrik",
    categoryName: "Electricite",
    unit: "V",
    name: "Volt",
    symbol: "V",
    shortDescription: "Le volt est l'unite SI de difference de potentiel electrique.",
    historySummary: "Nomme d'apres le physicien italien Alessandro Volta, inventeur de la premiere pile electrique.",
    measurementSystem: "Systeme international (SI)",
    siEquivalent: "Unite SI de tension electrique",
    commonUses: "Piles, prises electriques, circuits electroniques",
  },
  {
    locale: "fr",
    sourceSlug: "amper",
    slug: "ampere",
    category: "elektrik",
    categoryName: "Electricite",
    unit: "A",
    name: "Ampere",
    symbol: "A",
    shortDescription: "L'ampere est l'unite SI de base du courant electrique.",
    historySummary: "Nomme d'apres le physicien francais Andre-Marie Ampere, pionnier de l'electromagnetisme.",
    measurementSystem: "Systeme international (SI)",
    siEquivalent: "Unite SI de base du courant electrique",
    commonUses: "Circuits electriques, disjoncteurs, chargeurs",
  },
  {
    locale: "fr",
    sourceSlug: "miliamper",
    slug: "milliampere",
    category: "elektrik",
    categoryName: "Electricite",
    unit: "mA",
    name: "Milliampere",
    symbol: "mA",
    shortDescription: "Le milliampere vaut un millieme d'ampere et sert a mesurer les petits courants en electronique.",
    historySummary: "Sous-multiple de l'ampere, le milliampere est devenu essentiel avec le developpement de l'electronique de precision.",
    measurementSystem: "Systeme international (SI, sous-multiple)",
    siEquivalent: "1 mA = 0,001 A",
    commonUses: "Batteries de smartphones, capteurs, circuits electroniques",
  },

  // Carat d'or
  {
    locale: "fr",
    sourceSlug: "24-ayar-altin",
    slug: "or-24-carats",
    category: "altin_ayar",
    categoryName: "Carat d'or",
    unit: "24K",
    name: "Or 24 carats",
    symbol: "24k",
    shortDescription: "L'or 24 carats est de l'or pur a 99,9 %, la reference du systeme des carats.",
    historySummary: "L'or 24 carats est traditionnellement utilise pour les lingots d'investissement en raison de sa purete maximale.",
    measurementSystem: "Systeme des carats",
    siEquivalent: "99,9 % d'or pur",
    commonUses: "Lingots et investissement en or",
  },
  {
    locale: "fr",
    sourceSlug: "22-ayar-altin",
    slug: "or-22-carats",
    category: "altin_ayar",
    categoryName: "Carat d'or",
    unit: "22K",
    name: "Or 22 carats",
    symbol: "22k",
    shortDescription: "L'or 22 carats contient environ 91,6 % d'or pur et est populaire pour la bijouterie traditionnelle.",
    historySummary: "Tres utilise en Asie du Sud et au Moyen-Orient, il equilibre purete et resistance pour la fabrication de bijoux.",
    measurementSystem: "Systeme des carats",
    siEquivalent: "≈91,6 % d'or pur",
    commonUses: "Bijouterie traditionnelle",
  },
  {
    locale: "fr",
    sourceSlug: "18-ayar-altin",
    slug: "or-18-carats",
    category: "altin_ayar",
    categoryName: "Carat d'or",
    unit: "18K",
    name: "Or 18 carats",
    symbol: "18k",
    shortDescription: "L'or 18 carats contient 75 % d'or pur et est le standard le plus courant pour la bijouterie occidentale.",
    historySummary: "Son bon compromis entre durete et purete en fait la reference des bijouteries en Europe et en Amerique.",
    measurementSystem: "Systeme des carats",
    siEquivalent: "75 % d'or pur",
    commonUses: "Bijouterie occidentale, bagues de mariage",
  },

  // Titre d'argent
  {
    locale: "fr",
    sourceSlug: "999-ayar-gumus",
    slug: "argent-999",
    category: "gumus_ayar",
    categoryName: "Titre d'argent",
    unit: "999",
    name: "Argent 999 (fin)",
    symbol: "999",
    shortDescription: "L'argent 999 est de l'argent pur a 99,9 %, principalement utilise pour les lingots d'investissement.",
    historySummary: "Sa purete maximale en fait le standard prefere pour les produits d'investissement et les lingots d'argent.",
    measurementSystem: "Systeme des milliemes",
    siEquivalent: "99,9 % d'argent pur",
    commonUses: "Lingots et argent d'investissement",
  },
  {
    locale: "fr",
    sourceSlug: "925-ayar-gumus",
    slug: "argent-sterling-925",
    category: "gumus_ayar",
    categoryName: "Titre d'argent",
    unit: "925",
    name: "Argent sterling (925)",
    symbol: "925",
    shortDescription: "L'argent sterling contient 92,5 % d'argent pur et est le standard mondial de la bijouterie en argent.",
    historySummary: "Le standard de l'argent sterling remonte a l'Angleterre du XIIe siecle et reste la norme la plus reconnue au monde.",
    measurementSystem: "Systeme des milliemes",
    siEquivalent: "92,5 % d'argent pur",
    commonUses: "Bijouterie et orfevrerie de table",
  },

];

export function findFrenchUnitPageBySourceSlug(sourceSlug: string) {
  return frenchUnitPages.find((page) => page.sourceSlug === sourceSlug);
}

export function findFrenchUnitPage(category: string, unit: string) {
  return frenchUnitPages.find(
    (page) => page.category === category && page.unit === unit
  );
}
