// Svenska enhetssidor -- integrerade i det nya i18n-systemet.
// Fristaende, nytt fil (andrar inga befintliga tr/en/de/ar/uz/bn/fr/es/pt/it/nl-filer).
// Innehallet ar oversatt direkt fran den turkiska kallan
// (app/converter/unitPages.ts, unitDescriptions-tabellen), inte fran ett
// mellansprak, for att bevara samma djup och faktainnehall som flaggskeppet.
// Bereik begransat till de 13 karnkategorierna som, tillsammans med de 4
// universella verktygen (startsidan), utgor de 17 element som definierar
// sidans identitet.

export type LocalizedSwedishUnitPage = {
  locale: "sv";
  sourceSlug: string;
  slug: string;
  category: string;
  categoryName: string;
  unit: string;
  name: string;
  symbol: string;
  shortDescription: string;
  historySummary: string;
  measurementSystem: string;
  siEquivalent: string;
  commonUses: string;
};

export const swedishUnitPages: LocalizedSwedishUnitPage[] = [
  // Langd
  {
    locale: "sv",
    sourceSlug: "metre",
    slug: "meter",
    category: "uzunluk",
    categoryName: "Längd",
    unit: "m",
    name: "Meter",
    symbol: "m",
    shortDescription: "Metern är den grundläggande längdenheten i Internationella Enhetssystemet. Den används för att mäta avstånd och storlek, från vardagslivet till teknik.",
    historySummary: "Metern uppstod under franska revolutionen, i syfte att ersätta de mätenheter som dittills varierat från region till region med en enda universell och naturbaserad standard. Man övervägde först en definition baserad på en pendels svängningstid, men den övergavs eftersom en pendel påverkas av den lokala tyngdkraften. Istället definierade franska nationalförsamlingen 1791 metern som en tiomiljondel av avståndet från Nordpolen till ekvatorn längs meridianen genom Paris -- ett avstånd som beräknades genom Delambres och Mechains åriga geodetiska mätningar. År 1799 baserades definitionen på en platinastav kallad 'Metre des Archives'; 1889 ersattes staven av en ny standard i platina-iridiumlegering, med 29 kopior utplacerade över hela världen. År 1960 definierades metern inte längre utifrån ett fysiskt föremål, utan utifrån våglängden hos ljuset som en krypton-86-atom sänder ut. Sedan 1983 definieras metern som den sträckan ljus tillryggalägger i vakuum på 1/299 792 458 sekund -- detta gör att metern kan reproduceras med extremt hög precision i vilket laboratorium som helst i världen, utan att behöva en fysisk prototyp.",
    measurementSystem: "Internationella Enhetssystemet (SI)",
    siEquivalent: "SI:s grundläggande längdenhet",
    commonUses: "Byggnation, vetenskap, tillverkning, geometri och allmän mätning",
  },
  {
    locale: "sv",
    sourceSlug: "kilometre",
    slug: "kilometer",
    category: "uzunluk",
    categoryName: "Längd",
    unit: "km",
    name: "Kilometer",
    symbol: "km",
    shortDescription: "Kilometer är en längdenhet lika med 1000 meter. Den används för att uttrycka avstånd mellan städer och geografiska avstånd.",
    historySummary: "Kilometern etablerade sig som ett veulve av metern inom det metriska systemets decimala struktur. Den blev en standardbeteckning för vägar och kartskalor.",
    measurementSystem: "Internationella Enhetssystemet (SI, multipel)",
    siEquivalent: "1 km = 1000 m",
    commonUses: "Vägavstånd, geografi, kartografi och infrastruktur",
  },
  {
    locale: "sv",
    sourceSlug: "santimetre",
    slug: "centimeter",
    category: "uzunluk",
    categoryName: "Längd",
    unit: "cm",
    name: "Centimeter",
    symbol: "cm",
    shortDescription: "Centimeter är en längdenhet lika med en hundradel av en meter. Den är vanlig för att uttrycka små föremål och vardagliga mått.",
    historySummary: "Centimetern utvecklades som en decimal underenhet i det metriska systemet. Den fick brett genomslag eftersom den gjorde mätningar praktiska och lätta att beräkna snabbt.",
    measurementSystem: "Internationella Enhetssystemet (SI, underenhet)",
    siEquivalent: "1 cm = 0,01 m",
    commonUses: "Möbler, textil, antropometri och vardagliga mätningar",
  },
  {
    locale: "sv",
    sourceSlug: "milimetre",
    slug: "millimeter",
    category: "uzunluk",
    categoryName: "Längd",
    unit: "mm",
    name: "Millimeter",
    symbol: "mm",
    shortDescription: "Millimeter är en längdenhet lika med en tusendel av en meter. Den används ofta vid precisa tekniska mätningar.",
    historySummary: "Millimetern fick spridning i takt med industrins och teknikens behov av att mäta mindre toleranser. Den blev en grundläggande underenhet inom tillverknings- och ritningsstandarder.",
    measurementSystem: "Internationella Enhetssystemet (SI, underenhet)",
    siEquivalent: "1 mm = 0,001 m",
    commonUses: "Mekanisk tillverkning, tekniska ritningar, bearbetningstoleranser",
  },
  {
    locale: "sv",
    sourceSlug: "fit",
    slug: "fot",
    category: "uzunluk",
    categoryName: "Längd",
    unit: "ft",
    name: "Fot",
    symbol: "ft",
    shortDescription: "Fot är en längdenhet som används i det brittiska och amerikanska mätsystemet. En internationell fot motsvarar exakt 0,3048 meter.",
    historySummary: "Fot (foot) var historiskt, som namnet antyder, ett ungefärligt mått baserat på den mänskliga fotens längd, och sedan den romerska enheten 'pes' har tiotals olika 'fot'-definitioner mellan 250 och 335 mm använts i olika regioner och epoker. Den fot som så småningom etablerades i England fastslogs 1959 (samma är som tum och engelsk mil också fastslogs) genom en internationell överenskommelse mellan USA, Storbritannien och Samväldsländerna till exakt 0,3048 meter (det vill säga exakt 12 tum).",
    measurementSystem: "Brittiskt och amerikanskt mätsystem",
    siEquivalent: "1 ft = 0,3048 m",
    commonUses: "Arkitektur, byggnadshöjder, luftfart och fältmätningar",
  },
  {
    locale: "sv",
    sourceSlug: "inc",
    slug: "tum",
    category: "uzunluk",
    categoryName: "Längd",
    unit: "in",
    name: "Tum",
    symbol: "in",
    shortDescription: "Tum är en kort längdenhet som används i det brittiska och amerikanska mätsystemet. En tum motsvarar exakt 2,54 centimeter.",
    historySummary: "Ordet tum (inch) härstammar från latinets 'uncia', som betyder 'en tolftedel'. Den äldsta definitionen gjordes 1324 av kung Edward II av England som 'tre korn korn lagda ände mot ände', och denna definition användes i århundraden. Enligt en annan tradition definierade kung David I av Skottland (1100-talet) tummen som bredden vid nageln på en mans tumme. Ett avgörande genombrott kom 1896 när den svenske ingenjören Carl Edvard Johansson, vid tillverkningen av sina precisionsmätblock, i praktiken fastslog tummen till exakt 25,4 mm -- denna 'industriella tum' antogs av brittiska standardiseringsorgan 1930 och amerikanska 1933. Den slutliga internationella överenskommelsen trädde i kraft 1959 (i USA den 1 juli), och sedan dess är en tum exakt definierad som 25,4 millimeter.",
    measurementSystem: "Brittiskt och amerikanskt mätsystem",
    siEquivalent: "1 in = 25,4 mm = 2,54 cm",
    commonUses: "Skärmstorlekar, rörledningar, fastelement och tekniska kataloger",
  },
  {
    locale: "sv",
    sourceSlug: "yarda",
    slug: "yard",
    category: "uzunluk",
    categoryName: "Längd",
    unit: "yd",
    name: "Yard",
    symbol: "yd",
    shortDescription: "Yard är en längdenhet som används i det brittiska och amerikanska mätsystemet. En yard motsvarar exakt 0,9144 meter.",
    historySummary: "Yardens ursprung är inte helt klarlagt, men enligt en vanlig tradition definierade kung Henry I av England på 1100-talet yarden som avståndet från hans nästipp till tummen på hans utsträckta arm. En mer väl dokumenterad utveckling var att officiella bronsstavar, 'yard-stavar', tillverkades som standardreferens i den engelska skattkammaren på 1500-talet. Liksom fot och tum fastslogs även yarden genom den internationella överenskommelsen 1959 till exakt 0,9144 meter (3 fot).",
    measurementSystem: "Brittiskt och amerikanskt mätsystem",
    siEquivalent: "1 yd = 0,9144 m",
    commonUses: "Idrottsplaner, textil, trädgårdsdesign och fältplanering",
  },
  {
    locale: "sv",
    sourceSlug: "mil",
    slug: "engelsk-mil",
    category: "uzunluk",
    categoryName: "Längd",
    unit: "mi",
    name: "Engelsk mil",
    symbol: "mi",
    shortDescription: "Engelsk mil är en längdenhet som används särskilt i USA och Storbritannien. En internationell mil motsvarar 1609,344 meter.",
    historySummary: "Ordet 'mil' kommer från det latinska uttrycket 'mille passus' (tusen steg) -- ett 'steg' räknades som avståndet mellan två nedslag av samma fot. Den romerska milen fastslogs indirekt när Marcus Agrippa år 29 f.Kr. fastställde en standard romersk fot (1 steg = 5 romerska fot, 1 mil = 5000 romerska fot ≈ 1479 meter). I det medeltida England var den 'gamla engelska milen' ett oklart mått på cirka 2,1 km som varierade från region till region. Den avgörande vändpunkten kom 1593: en parlamentslag om mått och vikt under drottning Elizabeth I:s regeringstid behöll den traditionella milstrukturen på 8 furlongs men ökade antalet fot, och fastställde milen till exakt 5280 fot (1760 yard) -- denna definition spreds via det brittiska imperiet och utgör grunden för dagens internationella mil. Den moderna internationella milen fastslogs 1959 till exakt 1609,344 meter.",
    measurementSystem: "Brittiskt och amerikanskt mätsystem",
    siEquivalent: "1 mi = 1609,344 m",
    commonUses: "Vägavstånd, navigation och fältskalor",
  },

  // Area
  {
    locale: "sv",
    sourceSlug: "metrekare",
    slug: "kvadratmeter",
    category: "alan",
    categoryName: "Area",
    unit: "m²",
    name: "Kvadratmeter",
    symbol: "m²",
    shortDescription: "Kvadratmeter är SI:s härledda enhet för area. Den används som grundreferens vid beräkningar av golvyta, tvärsnitt och ytor.",
    historySummary: "Kvadratmetern etablerade sig inom det metriska systemet som en tvådimensionell förlängning av metern. Den blev standardspråket för area i bygg-, mark- och tekniska ritningar.",
    measurementSystem: "Internationella Enhetssystemet (SI)",
    siEquivalent: "SI:s grundläggande areaenhet",
    commonUses: "Arkitektur, inredning, panelytor och tvärsnittsareor",
  },
  {
    locale: "sv",
    sourceSlug: "hektar",
    slug: "hektar",
    category: "alan",
    categoryName: "Area",
    unit: "ha",
    name: "Hektar",
    symbol: "ha",
    shortDescription: "Hektar är en stor areaenhet som särskilt används vid markmätning. 1 hektar motsvarar exakt 10 000 kvadratmeter.",
    historySummary: "Hektar definierades 1795, som en del av det metriska system som franska revolutionen förde med sig, som 100 gånger enheten 'är' (100 m²) och fick namnet med förledet 'hekto-' (hundra). Eftersom den ansågs mycket mer praktisk än ar för att uttrycka stora jordbruks- och skogsarealer, blev den med tiden den globala standardenheten för mark. Som en intuitiv jämförelse är en standardfotbollsplan ungefär 0,7 hektar stor -- vilket gör hektar lätt att greppa i vardagslivet.",
    measurementSystem: "Metriskt system, förenligt med SI",
    siEquivalent: "1 ha = 10 000 m²",
    commonUses: "Jordbruksmark, detaljplaner och stora fastighetsregister",
  },
  {
    locale: "sv",
    sourceSlug: "akre",
    slug: "acre",
    category: "alan",
    categoryName: "Area",
    unit: "ac",
    name: "Acre",
    symbol: "ac",
    shortDescription: "Acre är en stor areaenhet som särskilt används för markmätning i det brittiska och amerikanska mätsystemet. Den motsvarar 4046,8564224 kvadratmeter.",
    historySummary: "Acre utvecklades historiskt från ett synsätt baserat på den markyta ett par oxar kunde plöja på en dag, och används fortfarande som standard markenhet i det brittiska mätsystemet.",
    measurementSystem: "Brittiskt och amerikanskt mätsystem",
    siEquivalent: "1 acre = 4046,8564224 m²",
    commonUses: "Fastighets- och markförsäljning, jordbruksmarksmätning och fastighetsannonser",
  },

  // Volym
  {
    locale: "sv",
    sourceSlug: "litre",
    slug: "liter",
    category: "hacim",
    categoryName: "Volym",
    unit: "L",
    name: "Liter",
    symbol: "L",
    shortDescription: "Liter är en mycket vanlig volymenhet för att uttrycka vätskor och kapaciteter. 1 liter motsvarar 0,001 kubikmeter.",
    historySummary: "Litern definierades 1795 i Frankrike, som en del av det nya mätsystem som franska revolutionen förde med sig, som 'en kubisk decimeter'. År 1901 definierade Generalkonferensen för mått och vikt om litern som 'volymen som upptas av 1 kg rent vatten vid dess maximala densitet (3,98 °C) vid ett tryck av en atmosfär' -- men denna definition gjorde litern något större (cirka 1,000028 gånger) än en kubikdecimeter, eftersom referensens platina-iridium-kilogramprototyp visade sig vara 28 miljondelar större än väntat. Denna avvikelse, som bestod i 63 år, korrigerades 1964 när Generalkonferensen åter definierade litern som exakt 'en kubikdecimeter', direkt kopplad till metern.",
    measurementSystem: "Metriskt system, förenligt med SI",
    siEquivalent: "1 L = 0,001 m³",
    commonUses: "Vätskor, tankvolymer, laboratoriekärl och vardagliga mått",
  },
  {
    locale: "sv",
    sourceSlug: "mililitre",
    slug: "milliliter",
    category: "hacim",
    categoryName: "Volym",
    unit: "mL",
    name: "Milliliter",
    symbol: "mL",
    shortDescription: "Milliliter är en liten volymenhet lika med en tusendel av en liter. Den används för precisa vätskemätningar.",
    historySummary: "Millilitern fick spridning för att på ett tillförlitligt sätt kunna uttrycka små volymer inom läkemedel, laboratoriearbete och matlagning.",
    measurementSystem: "Metriskt system, förenligt med SI",
    siEquivalent: "1 mL = 0,000001 m³",
    commonUses: "Läkemedelsdoser, laboratorieprover och små vätskevolymer",
  },
  {
    locale: "sv",
    sourceSlug: "metrekup",
    slug: "kubikmeter",
    category: "hacim",
    categoryName: "Volym",
    unit: "m³",
    name: "Kubikmeter",
    symbol: "m³",
    shortDescription: "Kubikmeter är SI:s härledda enhet för volym. Den är grundreferensen för stora volymer och tekniska kapaciteter.",
    historySummary: "Kubikmeter definieras som den inre volymen hos en kub vars varje sida är exakt 1 meter, och härleds direkt genom att utvidga metern till tre dimensioner. Eftersom den motsvarar 1000 liter (1 m³ = 1000 L) används den som global standardenhet vid fakturering av naturgas- och vattenförbrukning -- även i Turkiet visar naturgas- och vattenräkningar förbrukningen i kubikmeter. Inom byggbranschen uttrycks även betong- och schaktmängder, och inom industrin tank- och förrådskapaciteter, ofta i denna enhet.",
    measurementSystem: "Internationella Enhetssystemet (SI)",
    siEquivalent: "SI:s grundläggande volymenhet",
    commonUses: "Lagringsvolym, byggnaders innervolym, processtankar och flödesberäkningar",
  },
  {
    locale: "sv",
    sourceSlug: "galon",
    slug: "gallon",
    category: "hacim",
    categoryName: "Volym",
    unit: "gal",
    name: "Gallon (USA)",
    symbol: "gal",
    shortDescription: "Gallon är en enhet som särskilt används i USA för att mäta vätskevolym. En amerikansk gallon motsvarar 3,78541 liter.",
    historySummary: "Den amerikanska gallonen bygger på den medeltida engelska handelstraditionen med 'vingallonen', och fastställdes 1706 under drottning Annes regeringstid till exakt 231 kubiktum (3,785411784 L) -- USA antog officiellt denna definition 1836. Storbritannien gick 1824 en helt annan väg och definierade om sin egen 'imperial gallon' som 'volymen som motsvarar vikten av 10 pund destillerat vatten' (cirka 4,546 L) och avskaffade alla andra galllondefinitioner. På grund av dessa olika ursprung är den brittiska gallonen cirka 20 % större än den amerikanska.",
    measurementSystem: "Amerikanskt mätsystem (US liquid gallon)",
    siEquivalent: "1 gallon (USA) = 3,78541 L = 0,00378541 m³",
    commonUses: "Bränsleförbrukning, amerikanska vätskeprodukters etiketter och köksmått",
  },

  // Massa
  {
    locale: "sv",
    sourceSlug: "kilogram",
    slug: "kilogram",
    category: "kutle",
    categoryName: "Massa",
    unit: "kg",
    name: "Kilogram",
    symbol: "kg",
    shortDescription: "Kilogram är SI:s grundenhet för massa. Den används i stor utsträckning inom handel, laboratoriearbete och teknik.",
    historySummary: "Också kilogrammets ursprung går tillbaka till franska revolutionen: 1795 definierades gram som massan hos 1 kubikcentimeter vatten vid dess smältpunkt (0 °C) -- det vill säga 1 kilogram motsvarade massan hos 1 liter vatten under dessa förhållanden. Men när man insåg att vattnets densitet varierar med temperaturen, tillverkades 1799 en platinaprototyp kallad 'Kilogramme des Archives'; denna gång var referensen massan hos 1 kubikdecimeter vatten vid ~4 °C, där vattnet är som tätast. År 1889 ersattes denna prototyp av en ny cylinder i platina-iridiumlegering, känd som 'Le Grand K', som under 130 år bevarades som världens referenskilogram vid Internationella byrån för mått och vikt i Frankrike. Med tiden upptäcktes att denna cylinder avvek cirka 50 mikrogram från sina samtida kopior -- en ofrånkomlig svaghet i att basera en definition på ett fysiskt föremål. Den 16 november 2018 beslutade Generalkonferensen för mått och vikt att ge kilogrammet en ny definition baserad på Plancks konstant; denna nya definition trädde i kraft den 20 maj 2019, och kilogrammet kan nu reproduceras i vilket laboratorium som helst i världen utan behov av ett fysiskt referensföremål.",
    measurementSystem: "Internationella Enhetssystemet (SI)",
    siEquivalent: "SI:s grundläggande massaenhet",
    commonUses: "Handel, transport, laboratorie- och processberäkningar",
  },
  {
    locale: "sv",
    sourceSlug: "gram",
    slug: "gram",
    category: "kutle",
    categoryName: "Massa",
    unit: "g",
    name: "Gram",
    symbol: "g",
    shortDescription: "Gram är en massaenhet lika med en tusendel av ett kilogram. Den används för att uttrycka livsmedel, laboratorie- och små materiemängder.",
    historySummary: "Gram var den egentliga grundläggande massaenheten i den första definitionen av det franska metriska systemet 1795, och definierades som massan hos 1 kubikcentimeter vatten vid dess smältpunkt. Men eftersom det i praktiken var svårt att omvandla en så liten massa till en precis och reproducerbar standardprototyp, valdes 1799 istället kilogrammet -- 1000 gånger större (massan hos en kubikdecimeter vatten) -- som referensprototyp. Detta historiska val ledde till att kilogrammet blev det enda undantaget bland SI:s sju grundenheter vars namn innehåller ett prefix ('kilo-') -- gram, som ju ger namnet åt enheten, är idag i stället en sekundär enhet definierad som en underenhet av kilogrammet.",
    measurementSystem: "Internationella Enhetssystemet (SI, underenhet)",
    siEquivalent: "1 g = 0,001 kg",
    commonUses: "Livsmedel, kemi, farmaci och precisionsmätning",
  },
  {
    locale: "sv",
    sourceSlug: "miligram",
    slug: "milligram",
    category: "kutle",
    categoryName: "Massa",
    unit: "mg",
    name: "Milligram",
    symbol: "mg",
    shortDescription: "Milligram är en mycket liten massaenhet lika med en tusendel av ett gram. Den har avgörande betydelse vid läkemedels- och laboratoriemätningar.",
    historySummary: "Milligrammet fick större betydelse i takt med att precisionsvågar och analytiska laboratorier utvecklades, särskilt inom hälso- och kemiområdet.",
    measurementSystem: "Internationella Enhetssystemet (SI, underenhet)",
    siEquivalent: "1 mg = 0,000001 kg",
    commonUses: "Läkemedelsdoser, analyser och precisionsformuleringar",
  },
  {
    locale: "sv",
    sourceSlug: "ton",
    slug: "ton",
    category: "kutle",
    categoryName: "Massa",
    unit: "t",
    name: "Ton",
    symbol: "t",
    shortDescription: "Metriskt ton är en stor massaenhet lika med 1000 kilogram. Den används för att uttrycka tunga laster och industriella mängder.",
    historySummary: "Ordet 'ton' härstammar från det medeltida engelska ordet 'tun', som betyder en stor vintunna; eftersom en fylld tunna vägde ungefär ett 'long ton', började ordet också användas som massaenhet. Idag kan tre olika 'ton'-definitioner skapa förvirring: det metriska tonet (exakt 1000 kg, standard i världen och i Turkiet), det i USA vanliga 'short ton' (2000 pund ≈ 907,18 kg), och det i Storbritannien historiskt använda 'long ton' (2240 pund ≈ 1016,05 kg). Även om skillnaden mellan dessa tre värden kan verka liten är det viktigt att tydligt ange vilken 'ton'-definition som används i internationella handels- och logistikavtal.",
    measurementSystem: "Metriskt system, förenligt med SI",
    siEquivalent: "1 t = 1000 kg",
    commonUses: "Logistik, tillverkning, råvaruhandel och tung industri",
  },
  {
    locale: "sv",
    sourceSlug: "pound",
    slug: "pund",
    category: "kutle",
    categoryName: "Massa",
    unit: "lb",
    name: "Pund",
    symbol: "lb",
    shortDescription: "Pund är en massaenhet som används i det brittiska och amerikanska mätsystemet. Ett internationellt pund motsvarar exakt 0,45359237 kilogram.",
    historySummary: "Pund härstammar från den romerska enheten 'libra' (cirka 328,9 gram, indelad i 12 'uncia') -- förkortningen 'lb' kommer direkt härifrån; själva ordet 'pound' kommer från uttrycket 'libra pondo' (en vikt mått med libra). Före normandernas erövring (1066) användes i England det 'saxiska pundet', definierat i silver under kung Offas tid (757-796), där 1 pund silver gav 240 pence. Det 'avoirdupois-pund' som blev vanligt i handeln omkring 1300 var till en början 6992 troy grain, men fastslogs under drottning Elizabeth I:s regeringstid till exakt 7000 troy grain (indelat i 16 uns). Genom 1878 års lag om mått och vikt utsågs en platinacylinder till officiell standardprototyp. Den slutliga internationella överenskommelsen undertecknades den 1 juli 1959: pundet är sedan dess exakt 0,45359237 kilogram; Storbritannien antog formellt denna definition genom 1963 års lag.",
    measurementSystem: "Brittiskt och amerikanskt mätsystem",
    siEquivalent: "1 lb = 0,45359237 kg",
    commonUses: "Detaljhandel, transport, näring och industriella kataloger",
  },
  {
    locale: "sv",
    sourceSlug: "ons",
    slug: "uns",
    category: "kutle",
    categoryName: "Massa",
    unit: "oz",
    name: "Uns",
    symbol: "oz",
    shortDescription: "Uns är en liten massaenhet som används i det brittiska och amerikanska mätsystemet. Ett avoirdupois-uns motsvarar 28,349523125 gram.",
    historySummary: "Ordet 'uns' härstammar från den romerska enheten 'uncia', som delade upp 'libra' (pundets föregångare) i tolv lika delar. Det avoirdupois-uns som används i vardagslivet (28,349523125 g) motsvarar 1/16 av ett pund; men det troy-uns som används i handeln med ädla metaller är annorlunda och tyngre (31,1034768 g) -- därför motsvarar det 'pris per uns' som anges för guld/silver cirka 10 % mer än det uns som används vid vanliga inköp. Troy-unset har fått sitt namn från Troyes, en viktig medeltida handelsmassestad i Frankrike.",
    measurementSystem: "Brittiskt och amerikanskt mätsystem",
    siEquivalent: "1 oz = 28,349523125 g",
    commonUses: "Förpackning, livsmedel och lättare kommersiella mått utanför smycken",
  },

  // Temperatur
  {
    locale: "sv",
    sourceSlug: "santigrat",
    slug: "celsius",
    category: "sicaklik",
    categoryName: "Temperatur",
    unit: "C",
    name: "Celsius",
    symbol: "°C",
    shortDescription: "Celsiusskalan är en av de vanligaste temperaturangivelserna i vardagslivet och tekniken.",
    historySummary: "Celsiusskalan uppfanns 1742 av den svenske astronomen Anders Celsius -- men intressant nog var hans ursprungliga skala tvärtom mot dagens: 0 grader angav vattnets kokpunkt, och 100 grader dess fryspunkt. Skalan vändes 1743 av den franske fysikern Jean-Pierre Christin (i konstruktionen av 'Lyontermometern') till dagens ordning med 0 °C som fryspunkt och 100 °C som kokpunkt; den svenske botanikern Carl Linné gjorde samma vändning oberoende 1744 för sin egen växthustermometer. Skalan kallades länge 'centigrad'; 1948 ändrade Internationella kommittén för mått och vikt officiellt namnet till 'Celsiusgrad', dels för att hedra Celsius minne, dels för att undvika sammanblandning med 'centigrad' som i vissa språk också betyder en hundradels vinkelgrad.",
    measurementSystem: "Temperaturskala som används tillsammans med SI",
    siEquivalent: "För temperaturskillnad: 1 °C = 1 K",
    commonUses: "Väderrapportering, HVAC, processövervakning och vardagliga temperaturvärden",
  },
  {
    locale: "sv",
    sourceSlug: "fahrenhayt",
    slug: "fahrenheit",
    category: "sicaklik",
    categoryName: "Temperatur",
    unit: "F",
    name: "Fahrenheit",
    symbol: "°F",
    shortDescription: "Fahrenheit är en temperaturskala som särskilt är vanlig i USA.",
    historySummary: "Fahrenheitskalan utvecklades 1724 av den i Polen födda, nederländska fysikern Daniel Gabriel Fahrenheit. Han satte nollpunkten till den kallaste temperatur där en blandning av is, vatten och ammoniumklorid (eller havssalt) stabiliserades; 32 grader motsvarade rent vattens fryspunkt, och 96 grader (enligt hans egen mätning) mänsklig kroppstemperatur. Fahrenheit hade fått en finare, bråkdelsfri indelning genom att multiplicera den tidigare Rømer-skalans värden med 4. Åren 1776-77 standardiserade en kommitté inom Royal Society, under ledning av Henry Cavendish, skalan och fastställde vattnets fryspunkt till exakt 32 °F och kokpunkt till exakt 212 °F -- denna korrigering ledde till att normal kroppstemperatur hamnade på det värde vi känner idag, 98,6 °F.",
    measurementSystem: "Brittisk och amerikansk måttradition",
    siEquivalent: "För temperaturskillnad: 1 °F = 5/9 K",
    commonUses: "Amerikanska väderdata, inomhustemperaturer och vissa tekniska kataloger",
  },
  {
    locale: "sv",
    sourceSlug: "kelvin",
    slug: "kelvin",
    category: "sicaklik",
    categoryName: "Temperatur",
    unit: "K",
    name: "Kelvin",
    symbol: "K",
    shortDescription: "Kelvin är SI:s grundenhet för temperatur och representerar den absoluta temperaturskalan.",
    historySummary: "Grunden till Kelvinskalan lades 1848 av den skotske fysikern William Thomson (som senare fick titeln Lord Kelvin); i sin uppsats 'On an Absolute Thermometric Scale' beräknade han, med hjälp av ideala gasers värmeutvidgningskoefficient, att den absoluta nollpunkten låg vid cirka -273 °C -- förbluffande nära dagens värde -273,15 °C. År 1854 arbetade han tillsammans med James Prescott Joule för att göra skalan mer praktisk och förenlig med luftermometrar. Enheten formaliserades 1954 vid den 10:e Generalkonferensen för mått och vikt, genom att vattnets trippelpunkt definierades till exakt 273,16 K; 1967/68 gav den 13:e konferensen enheten namnet 'kelvin'. År 2019 ändrades definitionen ännu mer grundläggande: kelvin bygger nu inte på vattnets trippelpunkt, utan direkt på Boltzmanns konstant (fastslagen till 1,380649 × 10⁻²³ J/K).",
    measurementSystem: "Internationella Enhetssystemet (SI)",
    siEquivalent: "SI:s grundläggande temperaturenhet",
    commonUses: "Termodynamik, vetenskapliga beräkningar och analyser som kräver absolut temperatur",
  },

  // Tid
  {
    locale: "sv",
    sourceSlug: "saniye",
    slug: "sekund",
    category: "zaman",
    categoryName: "Tid",
    unit: "s",
    name: "Sekund",
    symbol: "s",
    shortDescription: "Sekund är SI:s grundenhet för tid. Alla beräkningar av varaktighet och hastighet bygger på den.",
    historySummary: "Historiskt definierades sekunden som 1/86 400 av ett dygn; men man insåg att smärre oregelbundenheter i jordens rotationshastighet gjorde denna definition otillräckligt stabil. Vid Generalkonferensen för mått och vikts 13:e möte 1967 definierades sekunden om i grunden: den definieras nu som exakt 9 192 631 770 perioder av den strålning som motsvarar övergången mellan två grundläggande energinivå hos cesium-133-atomen. Denna definition gjorde det möjligt för atomklockor att reproduceras med samma precision (i storleksordningen en miljarddel) överallt i världen, och kopplade sekunden till en universell referens oberoende av himlakropparnas rörelse.",
    measurementSystem: "Internationella Enhetssystemet (SI)",
    siEquivalent: "SI:s grundläggande tidsenhet",
    commonUses: "Experimenttider, rörelseanalys, dataloggning och tidtagning",
  },
  {
    locale: "sv",
    sourceSlug: "dakika",
    slug: "minut",
    category: "zaman",
    categoryName: "Tid",
    unit: "min",
    name: "Minut",
    symbol: "min",
    shortDescription: "Minut är en praktisk tidsenhet lika med 60 sekunder.",
    historySummary: "Minuten är en historiskt utbredd mellanenhet inom både daglig planering och icke-vetenskaplig tidsuppföljning.",
    measurementSystem: "Utanför SI, men tillåten tillsammans med SI",
    siEquivalent: "1 min = 60 s",
    commonUses: "Möten, korta tidsintervall, träning och processcykler",
  },
  {
    locale: "sv",
    sourceSlug: "saat",
    slug: "timme",
    category: "zaman",
    categoryName: "Tid",
    unit: "h",
    name: "Timme",
    symbol: "h",
    shortDescription: "Timme är en vanlig tidsenhet lika med 3600 sekunder.",
    historySummary: "Timmen har forts vidare från himmelska och mekaniska tidmätningstraditioner till moderna kalender- och skiftsystem.",
    measurementSystem: "Utanför SI, men tillåten tillsammans med SI",
    siEquivalent: "1 h = 3600 s",
    commonUses: "Arbetstider, resor, energiförbrukning och daglig planering",
  },
  {
    locale: "sv",
    sourceSlug: "gun",
    slug: "dygn",
    category: "zaman",
    categoryName: "Tid",
    unit: "day",
    name: "Dygn",
    symbol: "d",
    shortDescription: "Dygn är en grundläggande tidsenhet baserad på jordens en fullständiga rotation kring sin egen axel (soldygnet), lika med 24 timmar (86 400 sekunder).",
    historySummary: "Begreppet dygn är mänsklighetens äldsta och mest universella tidsmått, baserat på solens upp- och nedgång. I den moderna definitionen är 1 dygn fastslaget till exakt 86 400 SI-sekunder (medelvärdet av soldygnet).",
    measurementSystem: "Utanför SI, men tillåten tillsammans med SI",
    siEquivalent: "1 dygn = 86 400 s = 24 timmar",
    commonUses: "Kalenderberäkningar, varaktighets-/åldersberäkningar, resor och projektplanering",
  },

  // Hastighet
  {
    locale: "sv",
    sourceSlug: "kilometre-saat",
    slug: "kilometer-i-timmen",
    category: "hiz",
    categoryName: "Hastighet",
    unit: "km/h",
    name: "Kilometer i timmen",
    symbol: "km/h",
    shortDescription: "Kilometer i timmen är en praktisk hastighetsenhet som är vanlig inom vägtransport.",
    historySummary: "I takt med att väg- och transportsystem blev vanligare standardiserades kilometer i timmen som måttet för körning och resor.",
    measurementSystem: "Metrisk praktisk användning",
    siEquivalent: "1 km/h ≈ 0,277778 m/s",
    commonUses: "Fordonshastigheter, trafikskyltar och fältmätningar",
  },
  {
    locale: "sv",
    sourceSlug: "metre-saniye",
    slug: "meter-per-sekund",
    category: "hiz",
    categoryName: "Hastighet",
    unit: "m/s",
    name: "Meter per sekund",
    symbol: "m/s",
    shortDescription: "Meter per sekund är SI:s härledda enhet för hastighet. Den används som grundreferens inom teknik och fysik.",
    historySummary: "Denna beteckning, som uppstår ur kombinationen av meter och sekund, är det moderna vetenskapliga språk som används som standard för hastighetsmätning.",
    measurementSystem: "Internationella Enhetssystemet (SI)",
    siEquivalent: "SI:s grundläggande hastighetsenhet",
    commonUses: "Vätskor, mekanisk rörelse och vetenskapliga mätningar",
  },
  {
    locale: "sv",
    sourceSlug: "mil-saat",
    slug: "engelsk-mil-i-timmen",
    category: "hiz",
    categoryName: "Hastighet",
    unit: "mph",
    name: "Engelsk mil i timmen",
    symbol: "mph",
    shortDescription: "Engelsk mil i timmen är en hastighetsenhet som särskilt används i USA och Storbritannien.",
    historySummary: "Kombinationen av engelsk mil och timme utgör den grundläggande hastighetsterminologin i den anglo-amerikanska måttraditionen för vägtransport.",
    measurementSystem: "Brittiskt och amerikanskt mätsystem",
    siEquivalent: "1 mph = 1,609344 km/h",
    commonUses: "Väghastigheter, fordonsindustri och fältrapporter",
  },
  {
    locale: "sv",
    sourceSlug: "knot",
    slug: "knop",
    category: "hiz",
    categoryName: "Hastighet",
    unit: "knot",
    name: "Knop",
    symbol: "kn",
    shortDescription: "Knop (nautisk mil per timme) är standardhastighetsenheten inom sjöfart och luftfart, lika med en fart av 1 nautisk mil (1852 meter) i timmen.",
    historySummary: "Namnet knop kommer historiskt från en träbit fastbunden vid ett knutat rep ('chip log') som kastades i vattnet för att mäta fartygs hastighet; genom att räkna hur många knutar som löpte ut på en bestämd tid fick man fartygets fart.",
    measurementSystem: "Utanför SI, standardenhet inom sjöfart/luftfart",
    siEquivalent: "1 knop = 1852/3600 m/s ≈ 0,5144 m/s",
    commonUses: "Fartygs- och flygplanshastighet, vindhastighet (meteorologi), navigationsberäkningar till sjöss",
  },

  // Tryck
  {
    locale: "sv",
    sourceSlug: "pascal",
    slug: "pascal",
    category: "basinc",
    categoryName: "Tryck",
    unit: "Pa",
    name: "Pascal",
    symbol: "Pa",
    shortDescription: "Pascal är den härledda SI-enheten för tryck. Den definieras genom sambandet 1 På = 1 N/m².",
    historySummary: "Enheten är uppkallad efter den franske 1600-talsvetenskapsmannen Blaise Pascal -- Pascal är känd för sitt arbete inom hydrodynamik och hydrostatik samt sina banbrytande tryckexperiment med barometern. Pascals upptäckt att 'tryck som appliceras på en instängd vätska fortplantar sig lika i alla riktningar' (Pascals lag) utgör grunden för hydrauliska system. Enheten antogs formellt som SI-enhet vid Generalkonferensen för mått och vikts 14:e möte 1971 och definierades som newton per kvadratmeter (N/m²).",
    measurementSystem: "Internationella Enhetssystemet (SI)",
    siEquivalent: "SI:s grundläggande tryckenhet, 1 På = 1 N/m²",
    commonUses: "Vetenskapliga beräkningar, materialanalys och referensomvandlingar",
  },
  {
    locale: "sv",
    sourceSlug: "bar",
    slug: "bar",
    category: "basinc",
    categoryName: "Tryck",
    unit: "bar",
    name: "Bar",
    symbol: "bar",
    shortDescription: "Bar är en tryckenhet lika med 100 000 pascal. Den är en mycket vanlig praktisk beteckning inom industri- och utrustningsvisning.",
    historySummary: "Enheten bar introducerades av den norske meteorologen Vilhelm Bjerknes, en av moderna väderleksprognosens pionjärer; namnet kommer från det grekiska ordet 'baros', som betyder 'vikt' (intressant nog användes ordet 'bar' mellan 1793 och 1795 även för en massaenhet motsvarande dagens ton, i det tidiga metriska systemet). 1 bar motsvarar exakt 100 000 pascal och ligger mycket nära medelatmosfärtrycket vid havsnivå (cirka 1,013 bar). Även om bar inte är en officiell SI-enhet används den fortfarande i stor utsträckning av meteorologer och flygbranschen, tack vare att den numeriskt sammanfaller med millibar/hektopascal och är praktisk att använda.",
    measurementSystem: "Metrisk teknisk enhet utanför SI",
    siEquivalent: "1 bar = 100 000 På",
    commonUses: "Kompressorer, hydraulik, pneumatik och servicemanometrar",
  },
  {
    locale: "sv",
    sourceSlug: "psi",
    slug: "psi",
    category: "basinc",
    categoryName: "Tryck",
    unit: "psi",
    name: "PSI",
    symbol: "psi",
    shortDescription: "PSI är förkortningen för 'pound-force per square inch'. Det är en vanlig tryckenhet inom anglo-amerikanska tekniska system.",
    historySummary: "PSI är, som namnet antyder, en sammansatt enhet som bildas genom att dela en kraftenhet (pound-force) med en areaenhet (kvadrattum), och blev vanlig inom brittisk ingenjörstradition på 1800-talet för att uttrycka pannans tryck under ångmaskinernas tidsålder. Även om det metriska systemet har blivit global standard fortsätter PSI att fungera som faktisk branschstandard inom fordonsindustrin (däcktryck), hydrauliska system och amerikansk industriutrustning.",
    measurementSystem: "Brittisk och amerikansk teknisk användning",
    siEquivalent: "1 psi = 6894,757293168 På",
    commonUses: "Däcktryck, hydrauliska system och teknisk service",
  },
  {
    locale: "sv",
    sourceSlug: "atmosfer",
    slug: "atmosfar",
    category: "basinc",
    categoryName: "Tryck",
    unit: "atm",
    name: "Standardatmosfär",
    symbol: "atm",
    shortDescription: "Atmosfär är en tryckenhet baserad på ett referensvärde nära jordatmosfärens genomsnittliga tryck vid havsnivå. Den kallas även standardatmosfär.",
    historySummary: "Atmosfärsenheten fick spridning genom att barometriska mätningar och havsnivåns referenstryck användes som standard jämförelsepunkt i tekniska och vetenskapliga sammanhang. År 1954 definierade den 10:e Generalkonferensen för mått och vikt (CGPM) standardatmosfären till exakt 101 325 På.",
    measurementSystem: "Utanför SI, referensenhet inom meteorologi och teknik",
    siEquivalent: "1 atm = 101 325 På (definierat värde)",
    commonUses: "Referensförhållanden, meteorologi, vakuum och tryckmätningar",
  },

  // Energi
  {
    locale: "sv",
    sourceSlug: "joule",
    slug: "joule",
    category: "enerji",
    categoryName: "Energi",
    unit: "J",
    name: "Joule",
    symbol: "J",
    shortDescription: "Joule är SI:s härledda enhet för energi. Den används för att uttrycka arbete, värme och energimängder.",
    historySummary: "Enheten är uppkallad efter den engelske fysikern James Prescott Joule (1818-1889), för hans arbete som visade sambandet mellan mekaniskt arbete och värme. Namnet föreslogs första gången den 23 augusti 1882, i William Siemens ordforandetal vid British Association for the Advancement of Science; Siemens föreslog att kalla enheten 'joule' till minne av 'mannen som bidragit så mycket till att utveckla den dynamiska värmeteorin'. Enheten antogs officiellt den 31 augusti 1889, vid den andra internationella elektrikerkongressen, tillsammans med enheten watt -- av en tillfällighet gick Joule bort samma är (den 11 oktober 1889). Definitionen uppdaterades 1946 inom ramen för Giorgi-systemet och uttrycktes då direkt, oberoende av elektromagnetiska enheter, som 'det arbete en kraft utför över en sträckan på en meter'.",
    measurementSystem: "Internationella Enhetssystemet (SI)",
    siEquivalent: "SI:s grundläggande energienhet",
    commonUses: "Termodynamik, energibalanser och vetenskapliga beräkningar",
  },
  {
    locale: "sv",
    sourceSlug: "kilovatsaat",
    slug: "kilowattimme",
    category: "enerji",
    categoryName: "Energi",
    unit: "kWh",
    name: "Kilowattimme",
    symbol: "kWh",
    shortDescription: "Kilowattimme är en vanlig energienhet vid elförbrukning.",
    historySummary: "Genom elmätare och faktureringssystem har kilowattimme blivit en av de mest kända enheterna för praktisk energianvändning.",
    measurementSystem: "Teknisk och kommersiell energienhet",
    siEquivalent: "1 kWh = 3,6 MJ",
    commonUses: "Elräkningar, batterikapacitet och förbrukningsjämförelser",
  },
  {
    locale: "sv",
    sourceSlug: "kalori",
    slug: "kalori",
    category: "enerji",
    categoryName: "Energi",
    unit: "cal",
    name: "Kalori",
    symbol: "cal",
    shortDescription: "Kalori (cal) definieras som den energimängd som krävs för att höja temperaturen hos ett gram vatten med 1 °C, och är en energienhet utanför SI. Enligt den termokemiska definitionen motsvarar 1 kalori 4,184 joule.",
    historySummary: "Begreppet kalori infördes på 1800-talet av den franske kemisten Nicolas Clement för att mäta värmemängd, och fick spridning under termodynamikens utvecklingsperiod. Även om SI-enheten joule i stor utsträckning förväntas ersätta den, används den fortfarande i stor utsträckning (som kilokalori) inom näringslära.",
    measurementSystem: "Utanför SI, traditionell energienhet",
    siEquivalent: "1 cal = 4,184 J (termokemisk definition)",
    commonUses: "Kemiska och termodynamiska beräkningar, livsmedelsenergi (via kilokalori)",
  },
  {
    locale: "sv",
    sourceSlug: "btu",
    slug: "btu",
    category: "enerji",
    categoryName: "Energi",
    unit: "Btu",
    name: "BTU",
    symbol: "BTU",
    shortDescription: "BTU (British Thermal Unit) definieras som den energimängd som krävs för att höja temperaturen hos ett pund vatten med 1 °F, och är en energienhet som används i det brittiska/amerikanska mätsystemet.",
    historySummary: "BTU utvecklades i England under ångmaskinernas tidsålder för att mäta värmeenergi, och blev med tiden standardenheten inom värme-/kylbranschen i anglosaxiska länder, främst USA.",
    measurementSystem: "Brittiskt och amerikanskt mätsystem",
    siEquivalent: "1 Btu = 1055,056 J",
    commonUses: "Kapacitet för luftkonditionering och varmare (kyl-/värmeeffekt), naturgasräkningar (USA)",
  },

  // Data-opslag / Datalagring
  {
    locale: "sv",
    sourceSlug: "bayt",
    slug: "byte",
    category: "veri",
    categoryName: "Datalagring",
    unit: "B",
    name: "Byte",
    symbol: "B",
    shortDescription: "Byte är den grundläggande mätenheten för digital data. Den består av 8 bitar och används för att representera ett tecken (bokstav, siffra osv.).",
    historySummary: "Termen 'byte' myntades 1956 av ingenjören Werner Buchholz, som arbetade med IBM:s Stretch-dator, genom att avsiktligt ändra stavningen av ordet 'bite' för att undvika förväxling med ordet 'bit'. Under de första åren kunde en byte ha olika längd, från 1 till 6 bitar, beroende på vilken datorarkitektur som användes; standarden på 8-bitars byte blev i praktiken branschstandard med IBM:s System/360, som lanserades 1964 och var en av tidens mest inflytelserika datorfamiljer.",
    measurementSystem: "Digital dataenhet (databehandlingsstandard)",
    siEquivalent: "1 byte = 8 bit",
    commonUses: "Filstorlek, minneskapacitet och mätning av dataöverföring",
  },
  {
    locale: "sv",
    sourceSlug: "megabayt",
    slug: "megabyte",
    category: "veri",
    categoryName: "Datalagring",
    unit: "MB",
    name: "Megabyte",
    symbol: "MB",
    shortDescription: "Megabyte (MB) är en dataenhet lika med 1 000 000 byte. Den används i stor utsträckning för att uttrycka storleken på foton, musikfiler och korta dokument.",
    historySummary: "I takt med att persondatorer blev vanligare blev megabyte en standardreferensenhet för att uttrycka fil- och diskstorlekar.",
    measurementSystem: "Internationella Enhetssystemet (SI, multipel)",
    siEquivalent: "1 MB = 1 000 000 byte",
    commonUses: "Foton, musikfiler, korta videor och applikationsstorlekar",
  },
  {
    locale: "sv",
    sourceSlug: "gigabayt",
    slug: "gigabyte",
    category: "veri",
    categoryName: "Datalagring",
    unit: "GB",
    name: "Gigabyte",
    symbol: "GB",
    shortDescription: "Gigabyte (GB) är en dataenhet lika med 1 miljard byte. Den används för att uttrycka lagringsutrymme på smartphones, videofiler och RAM-kapacitet.",
    historySummary: "I takt med lagringsteknikens utveckling blev gigabyte standardenheten för att uttrycka disk-, minnes- och mobilenheters kapacitet; skillnaden mellan SI:s (bastal 1000) och datorvärldens traditionella (bastal 1024) användning blir tydligast märkbar just vid denna enhet.",
    measurementSystem: "Internationella Enhetssystemet (SI, multipel)",
    siEquivalent: "1 GB = 1 000 000 000 byte",
    commonUses: "Lagringsutrymme på smartphones och datorer, RAM-kapacitet, videofiler",
  },

  // Elektricitet
  {
    locale: "sv",
    sourceSlug: "volt",
    slug: "volt",
    category: "elektrik",
    categoryName: "Elektricitet",
    unit: "V",
    name: "Volt",
    symbol: "V",
    shortDescription: "Volt är den härledda SI-enheten för elektrisk spänning.",
    historySummary: "Enheten är uppkallad efter den italienske fysikern Alessandro Volta -- Volta uppfann 1800, efter diskussioner med sin kollega Luigi Galvani om 'animal elektricitet', det 'voltaiska batteriet'; genom att upptäcka att zink och silver var det mest effektiva metallparet skapade han världens första apparat som producerade en kontinuerlig elektrisk ström (föregångaren till batteriet). Namnet 'volt' föreslogs mycket senare, 1861, av Latimer Clark och Charles Bright. År 1873 definierade British Association for the Advancement of Science formellt enheterna volt, ohm och farad; 1881 antog den internationella elektrikerkongressen volt som officiell enhet för elektromotorisk kraft (spänning). Vid SI-revideringen 2019 uppdaterades även volts definition, i och med att den elementära elektriska laddningen fastslogs till ett bestämt värde.",
    measurementSystem: "Internationella Enhetssystemet (SI)",
    siEquivalent: "SI:s grundläggande spänningsenhet",
    commonUses: "Elektroniska kretsar, strömförsörjningar och nätspänningar",
  },
  {
    locale: "sv",
    sourceSlug: "amper",
    slug: "ampere",
    category: "elektrik",
    categoryName: "Elektricitet",
    unit: "A",
    name: "Ampere",
    symbol: "A",
    shortDescription: "Ampere är SI:s grundenhet för elektrisk ström.",
    historySummary: "Enheten är uppkallad efter den franske fysikern och matematikern André-Marie Ampère (1775-1836), som lade grunden för elektrodynamiken genom sina studier av elektromagnetism; Ampère byggde vidare på den danske fysikern Hans Christian Ørsteds upptäckter inom området. Ampere utsågs till standardenhet för elektrisk ström genom en internationell överenskommelse som undertecknades vid den internationella elektricitetsutställningen 1881; dess första definition var en tiondel av CGS-systemets elektromagnetiska strömenhet. Fram till SI-revideringen 2019 definierades ampere som den ström som mellan två parallella ledare på 1 meters avstånd från varandra ger upphov till en magnetisk kraft på 2×10⁻⁷ newton per meter; sedan 2019 definieras den istället direkt via multiplar av den elementära elektriska laddningen (fastslagen till 1,602176634×10⁻¹⁹ coulomb).",
    measurementSystem: "Internationella Enhetssystemet (SI)",
    siEquivalent: "SI:s grundläggande strömenhet",
    commonUses: "Strömmätningar, skyddskomponenter och apparatetiketter",
  },
  {
    locale: "sv",
    sourceSlug: "miliamper",
    slug: "milliampere",
    category: "elektrik",
    categoryName: "Elektricitet",
    unit: "mA",
    name: "Milliampere",
    symbol: "mA",
    shortDescription: "Milliampere är en liten strömenhet lika med en tusendel av en ampere.",
    historySummary: "För att låga strömmar ska kunna avläsas bekvämt i elektronik och mätinstrument har beteckningen milliampere fått stor spridning.",
    measurementSystem: "Internationella Enhetssystemet (SI, underenhet)",
    siEquivalent: "1 mA = 0,001 A",
    commonUses: "Elektroniska kretsar, sensorer och lågströmstester",
  },

  // Guldkarat
  {
    locale: "sv",
    sourceSlug: "24-ayar-altin",
    slug: "24-karat-guld",
    category: "altin_ayar",
    categoryName: "Guldkaraat",
    unit: "24K",
    name: "24 karat guld",
    symbol: "24K",
    shortDescription: "24 karat guld är till 99,9 % rent, nästan helt rent guld. Eftersom det är den mjukaste karaten används det oftast i tackor och investeringsprodukter.",
    historySummary: "Karatsystemet är en traditionell juvelerarstandard som uttrycker renhetsgraden i en guldlegering på en skala från 24; 24 karat representerar olegerat, rent guld.",
    measurementSystem: "Juvelerarnas renhetsstandard (karat)",
    siEquivalent: "24 karat = 100 % rent guldinnehåll",
    commonUses: "Guldtackor, investeringsguld och användning som renhetsreferens",
  },
  {
    locale: "sv",
    sourceSlug: "22-ayar-altin",
    slug: "22-karat-guld",
    category: "altin_ayar",
    categoryName: "Guldkaraat",
    unit: "22K",
    name: "22 karat guld",
    symbol: "22K",
    shortDescription: "22 karat guld är en legering där 22/24 (cirka 91,6 %) av innehållet är rent guld. Den är vanlig för armband och traditionella smycken i Turkiet.",
    historySummary: "22 karat har uppstått genom att en liten mängd silver eller koppar legeras in i rent guld för att minska mjukheten och öka hållbarheten, och har blivit den traditionella smyckesstandarden i Turkiet och Mellanöstern.",
    measurementSystem: "Juvelerarnas renhetsstandard (karat)",
    siEquivalent: "22 karat = 91,6 % rent guldinnehåll (22/24)",
    commonUses: "Armband, traditionella smycken och guldgåvor",
  },
  {
    locale: "sv",
    sourceSlug: "18-ayar-altin",
    slug: "18-karat-guld",
    category: "altin_ayar",
    categoryName: "Guldkaraat",
    unit: "18K",
    name: "18 karat guld",
    symbol: "18K",
    shortDescription: "18 karat guld är en legering där 18/24 (75 %) av innehållet är rent guld. Tack vare den höga hållbarheten föredras den för vardagssmycken.",
    historySummary: "18 karat, som är hårdare och mer repbeständigt än rent guld, har blivit den internationella standarden särskilt för ringar och vardagssmycken.",
    measurementSystem: "Juvelerarnas renhetsstandard (karat)",
    siEquivalent: "18 karat = 75 % rent guldinnehåll (18/24)",
    commonUses: "Ringar, halsband, vardagssmycken och diamantinfattningar",
  },

  // Zilvergehalte / Silverhalt
  {
    locale: "sv",
    sourceSlug: "999-ayar-gumus",
    slug: "silver-999",
    category: "gumus_ayar",
    categoryName: "Silverhalt",
    unit: "999",
    name: "Silver 999 (fint)",
    symbol: "999",
    shortDescription: "Silver 999 är till 99,9 % rent, nästan helt rent silver, också kallat 'fint silver'. Eftersom det är mycket mjukt används det främst i tackor och investeringsprodukter snarare än smycken.",
    historySummary: "Till skillnad från guld uttrycks silvrets renhet direkt i promille; 999 representerar olegerat, rent silver och används som renhetsreferens vid handel med ädla metaller.",
    measurementSystem: "Juvelerarnas renhetsstandard (promille)",
    siEquivalent: "999 = 99,9 % rent silverinnehåll",
    commonUses: "Silvertackor, investeringssilver och användning som renhetsreferens",
  },
  {
    locale: "sv",
    sourceSlug: "925-ayar-gumus",
    slug: "sterlingsilver-925",
    category: "gumus_ayar",
    categoryName: "Silverhalt",
    unit: "925",
    name: "Sterlingsilver (925)",
    symbol: "925",
    shortDescription: "Sterlingsilver innehåller 92,5 % rent silver, där resten oftast är koppar. Det är känt världen över som 'sterling silver' och är den mest använda silverstandarden inom smycken.",
    historySummary: "Sterlingsilverstandarden uppstod i England för att motverka rent silvers extrema mjukhet, och har med tiden blivit den faktiska globala standarden för silversmycken och husgeråd.",
    measurementSystem: "Juvelerarnas renhetsstandard (promille)",
    siEquivalent: "925 = 92,5 % rent silverinnehåll (sterlingsilver)",
    commonUses: "Silversmycken, ringar, halsband och silverbestick",
  },
];

export function findSwedishUnitPageBySourceSlug(sourceSlug: string) {
  return swedishUnitPages.find((page) => page.sourceSlug === sourceSlug);
}

export function findSwedishUnitPage(category: string, unit: string) {
  return swedishUnitPages.find(
    (page) => page.category === category && page.unit === unit
  );
}
