// Norske enhetssider -- integrert i det nye i18n-systemet.
// Frittstaende, ny fil (endrer ingen eksisterende tr/en/de/ar/uz/bn/fr/es/pt/it/nl/sv-filer).
// Innholdet er oversatt direkte fra den tyrkiske kilden
// (app/converter/unitPages.ts, unitDescriptions-tabellen), ikke fra et
// mellomsprak, for a bevare samme dybde og faktainnhold som flaggskipet.
// Omfanget er bevisst begrenset til de 13 karnekategoriene som, sammen med
// de 4 universelle verktoyene (forsiden), utgjor de 17 elementene som
// definerer sidens identitet.

export type LocalizedNorwegianUnitPage = {
  locale: "no";
  sourceSlug: string;
  slug: string;
  category: string;
  categoryName: string;
  unit: string;
  name: string;
  symbol: string;
  shortDescription: string;
  historySummary: string;
  measurementSystem: string;
  siEquivalent: string;
  commonUses: string;
};

export const norwegianUnitPages: LocalizedNorwegianUnitPage[] = [
  // Lengde
  {
    locale: "no",
    sourceSlug: "metre",
    slug: "meter",
    category: "uzunluk",
    categoryName: "Lengde",
    unit: "m",
    name: "Meter",
    symbol: "m",
    shortDescription: "Meter er grunnenheten for lengde i Det internasjonale enhetssystemet. Den brukes til a male avstand og storrelse, fra dagliglivet til ingeniorfag.",
    historySummary: "Meteren oppsto under den franske revolusjonen, med mal om a erstatte maleenhetene som frem til da varierte fra region til region, med en enkelt universell og naturbasert standard. Man vurderte forst en definisjon basert pa svingningstiden til en pendel, men denne ideen ble forkastet da man innsa at en pendel pavirkes av lokal tyngdekraft. I stedet definerte den franske nasjonalforsamlingen i 1791 meteren som en titimillionte del av avstanden fra Nordpolen til ekvator langs meridianen gjennom Paris -- en avstand beregnet gjennom flerarige geodetiske malinger utfort av Delambre og Mechain. I 1799 ble definisjonen basert pa en platinastav kalt 'Metre des Archives'; i 1889 ble denne staven erstattet av en ny standard i platina-iridiumlegering, med 29 kopier utplassert over hele verden. I 1960 ble meteren ikke lenger definert ut fra et fysisk objekt, men ut fra bolgelengden til lyset som sendes ut av et krypton-86-atom. Siden 1983 er meteren definert som strekningen lyset tilbakelegger i vakuum pa 1/299 792 458 sekund -- dette gjor at meteren kan reproduseres med ekstremt hoy presisjon i hvilket som helst laboratorium i verden, uten a trenge en fysisk prototype.",
    measurementSystem: "Det internasjonale enhetssystemet (SI)",
    siEquivalent: "SIs grunnleggende lengdeenhet",
    commonUses: "Bygg, vitenskap, produksjon, geometri og generell maling",
  },
  {
    locale: "no",
    sourceSlug: "kilometre",
    slug: "kilometer",
    category: "uzunluk",
    categoryName: "Lengde",
    unit: "km",
    name: "Kilometer",
    symbol: "km",
    shortDescription: "Kilometer er en lengdeenhet lik 1000 meter. Den brukes til a uttrykke avstander mellom byer og geografiske avstander.",
    historySummary: "Kilometeren etablerte seg som et multiplum av meteren innenfor det metriske systemets desimale struktur. Den ble en standard betegnelse for veier og kartmalestokker.",
    measurementSystem: "Det internasjonale enhetssystemet (SI, multiplum)",
    siEquivalent: "1 km = 1000 m",
    commonUses: "Veiavstander, geografi, kartografi og infrastruktur",
  },
  {
    locale: "no",
    sourceSlug: "santimetre",
    slug: "centimeter",
    category: "uzunluk",
    categoryName: "Lengde",
    unit: "cm",
    name: "Centimeter",
    symbol: "cm",
    shortDescription: "Centimeter er en lengdeenhet lik en hundredel av en meter. Den er vanlig for a uttrykke sma gjenstander og hverdagsmal.",
    historySummary: "Centimeteren utviklet seg som en desimal delenhet i det metriske systemet. Den fikk bred bruk fordi den gjorde malinger praktiske og raske a beregne.",
    measurementSystem: "Det internasjonale enhetssystemet (SI, delenhet)",
    siEquivalent: "1 cm = 0,01 m",
    commonUses: "Mobler, tekstil, antropometri og hverdagslige malinger",
  },
  {
    locale: "no",
    sourceSlug: "milimetre",
    slug: "millimeter",
    category: "uzunluk",
    categoryName: "Lengde",
    unit: "mm",
    name: "Millimeter",
    symbol: "mm",
    shortDescription: "Millimeter er en lengdeenhet lik en tusendel av en meter. Den brukes ofte i presise tekniske malinger.",
    historySummary: "Millimeteren ble utbredt etter hvert som industri og ingeniorfag fikk behov for a male mindre toleranser. Den ble en grunnleggende delenhet, saerlig i produksjons- og tegningsstandarder.",
    measurementSystem: "Det internasjonale enhetssystemet (SI, delenhet)",
    siEquivalent: "1 mm = 0,001 m",
    commonUses: "Mekanisk produksjon, tekniske tegninger, bearbeidingstoleranser",
  },
  {
    locale: "no",
    sourceSlug: "fit",
    slug: "fot",
    category: "uzunluk",
    categoryName: "Lengde",
    unit: "ft",
    name: "Fot",
    symbol: "ft",
    shortDescription: "Fot er en lengdeenhet brukt i det britiske og amerikanske malesystemet. En internasjonal fot tilsvarer noyaktig 0,3048 meter.",
    historySummary: "Fot (foot) var, som navnet tilsier, historisk et omtrentlig mal basert pa lengden av en menneskefot, og siden den romerske enheten 'pes' har titalls ulike 'fot'-definisjoner variert mellom 250 og 335 mm avhengig av region og tidsperiode. Foten som etter hvert ble stabil i England, ble endelig fastsatt til noyaktig 0,3048 meter (altsa noyaktig 12 tommer) gjennom en internasjonal avtale i 1959 (samme ar som tomme og engelsk mil ogsa ble fastsatt) mellom USA, Storbritannia og samveldelandene.",
    measurementSystem: "Britisk og amerikansk malesystem",
    siEquivalent: "1 ft = 0,3048 m",
    commonUses: "Arkitektur, byggehoyder, luftfart og feltmalinger",
  },
  {
    locale: "no",
    sourceSlug: "inc",
    slug: "tomme",
    category: "uzunluk",
    categoryName: "Lengde",
    unit: "in",
    name: "Tomme",
    symbol: "in",
    shortDescription: "Tomme er en kort lengdeenhet brukt i det britiske og amerikanske malesystemet. En tomme tilsvarer noyaktig 2,54 centimeter.",
    historySummary: "Ordet 'inch' stammer fra det latinske 'uncia', som betyr 'en tolvtedel'. Den eldste definisjonen ble gitt i 1324 av kong Edward II av England, som 'tre byggkorn lagt ende mot ende', og denne definisjonen ble brukt i arhundrer. Det fortelles ogsa at kong David I av Skottland (1100-tallet) definerte tommen som bredden ved neglebunnen pa en manns tommel. Et vendepunkt kom i 1896 da den svenske ingenioren Carl Edvard Johansson, ved produksjon av presisjonsmaleklosser, i praksis fastsatte tommen til noyaktig 25,4 mm -- denne 'industrielle tommen' ble tatt i bruk av britiske standardorganer i 1930 og amerikanske i 1933. Den endelige internasjonale avtalen tradte i kraft i 1959 (1. juli i USA), og siden den gang er tommen definert som noyaktig 25,4 millimeter.",
    measurementSystem: "Britisk og amerikansk malesystem",
    siEquivalent: "1 in = 25,4 mm = 2,54 cm",
    commonUses: "Skjermstorrelser, rorlegging, festeelementer og tekniske kataloger",
  },
  {
    locale: "no",
    sourceSlug: "yarda",
    slug: "yard",
    category: "uzunluk",
    categoryName: "Lengde",
    unit: "yd",
    name: "Yard",
    symbol: "yd",
    shortDescription: "Yard er en lengdeenhet brukt i det britiske og amerikanske malesystemet. En yard tilsvarer noyaktig 0,9144 meter.",
    historySummary: "Opphavet til yarden er ikke helt klarlagt, men ifolge en utbredt fortelling definerte kong Henrik I av England pa 1100-tallet yarden som avstanden fra hans egen nesetipp til tommelen pa den utstrakte armen. En mer veldokumentert utvikling er at offisielle 'yardstenger' i bronse ble produsert som standardreferanse ved det britiske finansdepartementet pa 1500-tallet. I likhet med fot og tomme ble ogsa yarden endelig fastsatt til noyaktig 0,9144 meter (3 fot) gjennom den internasjonale avtalen i 1959.",
    measurementSystem: "Britisk og amerikansk malesystem",
    siEquivalent: "1 yd = 0,9144 m",
    commonUses: "Idrettsbaner, tekstil, landskapsarbeid og feltplanlegging",
  },
  {
    locale: "no",
    sourceSlug: "mil",
    slug: "engelsk-mil",
    category: "uzunluk",
    categoryName: "Lengde",
    unit: "mi",
    name: "Engelsk mil",
    symbol: "mi",
    shortDescription: "Engelsk mil er en lengdeenhet brukt saerlig i USA og Storbritannia. En internasjonal mil tilsvarer 1609,344 meter.",
    historySummary: "Ordet 'mile' kommer fra det latinske uttrykket 'mille passus' (tusen skritt) -- et 'skritt' ble regnet som avstanden mellom to nedtramp av samme fot. Den romerske milen ble indirekte fastsatt da Marcus Agrippa definerte en standard romersk fot i 29 f.Kr. (1 skritt = 5 romerske fot, 1 mil = 5000 romerske fot ≈ 1479 meter). I middelalderens England var den 'gamle engelske milen' et upresist mal pa om lag 2,1 km som varierte fra region til region. Det avgjorende vendepunktet kom i 1593: en parlamentslov om vekt og mal under dronning Elisabeth I beholdt den tradisjonelle milestrukturen pa 8 furlong, men okte antall fot slik at milen ble fastsatt til noyaktig 5280 fot (1760 yard) -- denne definisjonen spredte seg gjennom det britiske imperiet og dannet grunnlaget for dagens internasjonale mil. Den moderne internasjonale milen ble endelig fastsatt til noyaktig 1609,344 meter i 1959.",
    measurementSystem: "Britisk og amerikansk malesystem",
    siEquivalent: "1 mi = 1609,344 m",
    commonUses: "Veiavstander, navigasjon og feltmalestokker",
  },
  // Areal
  {
    locale: "no",
    sourceSlug: "metrekare",
    slug: "kvadratmeter",
    category: "alan",
    categoryName: "Areal",
    unit: "m²",
    name: "Kvadratmeter",
    symbol: "m²",
    shortDescription: "Kvadratmeter er SIs avledede enhet for areal. Den brukes som grunnleggende referanse i beregning av gulv, tverrsnitt og overflater.",
    historySummary: "Kvadratmeteren etablerte seg i det metriske systemet som den todimensjonale utvidelsen av meteren. Den ble et standard arealsprak i bygg-, tomte- og ingeniortegninger.",
    measurementSystem: "Det internasjonale enhetssystemet (SI)",
    siEquivalent: "SIs grunnleggende arealenhet",
    commonUses: "Arkitektur, interior, panelflater og tverrsnittsareal",
  },
  {
    locale: "no",
    sourceSlug: "hektar",
    slug: "hektar",
    category: "alan",
    categoryName: "Areal",
    unit: "ha",
    name: "Hektar",
    symbol: "ha",
    shortDescription: "Hektar er en stor arealenhet brukt saerlig ved eiendomsmaling. 1 hektar tilsvarer noyaktig 10 000 kvadratmeter.",
    historySummary: "Hektaren ble, som en del av det metriske systemet innfort av den franske revolusjonen, i 1795 definert som 100 ganger enheten 'ar' (100 m²) og fikk navnet sitt fra prefikset 'hekto-' (hundre). Fordi den viste seg langt mer praktisk enn ar for a uttrykke store jordbruks- og skogsarealer, ble den etter hvert den globale standardenheten for arealmaling. Som en intuitiv sammenligning: en standard fotballbane er om lag 0,7 hektar stor -- noe som gjor hektaren lett a forsta i dagliglivet.",
    measurementSystem: "Metrisk system, kompatibelt med SI",
    siEquivalent: "1 ha = 10 000 m²",
    commonUses: "Jordbruksarealer, reguleringsplaner og store tomteregistre",
  },
  {
    locale: "no",
    sourceSlug: "akre",
    slug: "acre",
    category: "alan",
    categoryName: "Areal",
    unit: "ac",
    name: "Acre",
    symbol: "ac",
    shortDescription: "Acre er en stor arealenhet brukt saerlig i det britiske og amerikanske malesystemet ved eiendomsmaling. Den tilsvarer 4046,8564224 kvadratmeter.",
    historySummary: "Acre har historisk utviklet seg fra en tilnaerming basert pa storrelsen pa jordet et par okser kunne pluye pa en dag, og brukes fortsatt som standard arealenhet i det britiske malesystemet.",
    measurementSystem: "Britisk og amerikansk malesystem",
    siEquivalent: "1 acre = 4046,8564224 m²",
    commonUses: "Kjop og salg av eiendom og jord, maling av jordbruksareal og eiendomsannonser",
  },
  // Volum
  {
    locale: "no",
    sourceSlug: "litre",
    slug: "liter",
    category: "hacim",
    categoryName: "Volum",
    unit: "L",
    name: "Liter",
    symbol: "L",
    shortDescription: "Liter er en svaert utbredt volumenhet for a uttrykke vaesker og kapasiteter. 1 liter tilsvarer 0,001 kubikkmeter.",
    historySummary: "Liter ble i 1795 i Frankrike definert som 'en kubikk desimeter', som en del av det nye malesystemet innfort av den franske revolusjonen. I 1901 definerte Generalkonferansen for mal og vekt liter pa nytt som 'volumet til 1 kg rent vann ved sin tetthetsmaksimum-temperatur (3,98 °C) ved 1 atmosfaeres trykk' -- men denne definisjonen gjorde liter noe storre (om lag 1,000028 ganger) enn en kubikk desimeter, fordi platina-iridium-kilogramprototypen som ble brukt som referanse, viste seg a vaere 28 deler per million storre enn forventet. Dette 63 ar lange avviket ble rettet opp i 1964, da Generalkonferansen igjen definerte liter direkte knyttet til meteren, som noyaktig 'en kubikk desimeter'.",
    measurementSystem: "Metrisk system, kompatibelt med SI",
    siEquivalent: "1 L = 0,001 m³",
    commonUses: "Vaesker, tankvolum, laboratoriebeholdere og hverdagslige mal",
  },
  {
    locale: "no",
    sourceSlug: "mililitre",
    slug: "milliliter",
    category: "hacim",
    categoryName: "Volum",
    unit: "mL",
    name: "Milliliter",
    symbol: "mL",
    shortDescription: "Milliliter er en liten volumenhet lik en tusendel av en liter. Den brukes til presise vaeskemalinger.",
    historySummary: "Milliliter ble utbredt for a uttrykke sma volumer palitelig innen medisin, laboratorium og kjokkenmal.",
    measurementSystem: "Metrisk system, kompatibelt med SI",
    siEquivalent: "1 mL = 0,000001 m³",
    commonUses: "Medisindoser, laboratorieprover og sma vaeskevolumer",
  },
  {
    locale: "no",
    sourceSlug: "metrekup",
    slug: "kubikkmeter",
    category: "hacim",
    categoryName: "Volum",
    unit: "m³",
    name: "Kubikkmeter",
    symbol: "m³",
    shortDescription: "Kubikkmeter er SIs avledede enhet for volum. Den er grunnreferansen for store volumer og tekniske kapasiteter.",
    historySummary: "Kubikkmeteren defineres som det indre volumet til en kube der hver side er noyaktig 1 meter, og fremkommer direkte ved a utvide meteren til tre dimensjoner. Fordi den tilsvarer 1000 liter (1 m³ = 1000 L), brukes den verden over som standardenhet ved fakturering av naturgass- og vannforbruk -- ogsa i Norge vises forbruk pa naturgass- og vannregninger i kubikkmeter. Innen byggebransjen uttrykkes ogsa betong- og masseflyttingsmengder, og i industrien tank- og lagerkapasiteter, ofte i denne enheten.",
    measurementSystem: "Det internasjonale enhetssystemet (SI)",
    siEquivalent: "SIs grunnleggende volumenhet",
    commonUses: "Lagringsvolum, bygningsvolum, prosesstanker og stromningsberegninger",
  },
  {
    locale: "no",
    sourceSlug: "galon",
    slug: "gallon",
    category: "hacim",
    categoryName: "Volum",
    unit: "gal",
    name: "Gallon",
    symbol: "gal",
    shortDescription: "Gallon er en enhet brukt saerlig i USA for a male vaskevolum. En amerikansk gallon tilsvarer 3,78541 liter.",
    historySummary: "Gallonen som brukes i USA, bygger pa 'vingallon'-tradisjonen fra middelalderens engelske handel, og ble endelig fastsatt til noyaktig 231 kubikktommer (3,785411784 L) under dronning Anne i 1706 -- USA tok offisielt i bruk denne definisjonen i 1836. Storbritannia gikk derimot en helt annen vei i 1824 og definerte pa nytt sin egen 'britiske gallon' (imperial gallon) som 'volumet tilsvarende vekten av 10 pund destillert vann' (om lag 4,546 L), og opphevet samtidig alle andre gallondefinisjoner. Pa grunn av disse ulike opprinnelsesvalgene er den britiske gallonen om lag 20 % storre enn den amerikanske.",
    measurementSystem: "Amerikansk malesystem (US liquid gallon)",
    siEquivalent: "1 gallon (US) = 3,78541 L = 0,00378541 m³",
    commonUses: "Drivstofforbruk, amerikanske vaskeproduktetiketter og kjokkenmal",
  },
  // Masse
  {
    locale: "no",
    sourceSlug: "kilogram",
    slug: "kilogram",
    category: "kutle",
    categoryName: "Masse",
    unit: "kg",
    name: "Kilogram",
    symbol: "kg",
    shortDescription: "Kilogram er SI-grunnenheten for masse. Den brukes mye innen handel, laboratorium og ingeniorfag.",
    historySummary: "Opprinnelsen til kilogrammet gar ogsa tilbake til den franske revolusjonen: i 1795 ble gram definert som massen til 1 kubikkcentimeter vann ved isens smeltepunkt (0 °C) -- altsa tilsvarte 1 kilogram 1 liter vann under disse forholdene. Men da man oppdaget at vannets tetthet endrer seg med temperaturen, ble det i 1799 laget en platinaprototype kalt 'Kilogramme des Archives'; denne gangen var referansen massen til 1 kubikk desimeter vann ved om lag 4 °C, der vannet er tettest. I 1889 ble denne prototypen erstattet av en ny sylinder i platina-iridiumlegering kjent som 'Le Grand K', og denne ble oppbevart som verdens referansekilogram ved Det internasjonale byra for mal og vekt i Frankrike i 130 ar. Etter hvert ble det oppdaget at denne sylinderen hadde avveket om lag 50 mikrogram fra kopiene laget pa samme tid -- en uunngaelig svakhet ved a basere seg pa et fysisk objekt. Den 16. november 2018 vedtok Generalkonferansen for mal og vekt a innfore en ny definisjon av kilogrammet basert pa Plancks konstant; denne nye definisjonen tradte i kraft 20. mai 2019, og kilogrammet kan na reproduseres i hvilket som helst laboratorium i verden uten a trenge en fysisk prototype.",
    measurementSystem: "Det internasjonale enhetssystemet (SI)",
    siEquivalent: "SIs grunnleggende masseenhet",
    commonUses: "Handel, transport, laboratorium og prosessberegninger",
  },
  {
    locale: "no",
    sourceSlug: "gram",
    slug: "gram",
    category: "kutle",
    categoryName: "Masse",
    unit: "g",
    name: "Gram",
    symbol: "g",
    shortDescription: "Gram er en masseenhet lik en tusendel av et kilogram. Den brukes til a uttrykke mat, laboratorie- og sma stoffmengder.",
    historySummary: "Gram var den opprinnelige grunnleggende masseenheten i den forste definisjonen av det franske metriske systemet i 1795, og ble definert som massen til 1 kubikkcentimeter vann ved isens smeltepunkt. Men fordi det i praksis var vanskelig a omdanne en sa liten masse til en presis og reproduserbar standardprototype, ble kilogrammet -- 1000 ganger storre (massen til 1 kubikk desimeter vann) -- valgt som referanseprototype i 1799. Dette historiske valget forte til at kilogram er det eneste av SIs sju grunnenheter som har et prefiks ('kilo-') i navnet -- mens gram, til tross for a vaere hovedenheten navnet er avledet fra, i dag star som en sekundaer enhet definert som en delenhet av kilogrammet.",
    measurementSystem: "Det internasjonale enhetssystemet (SI, delenhet)",
    siEquivalent: "1 g = 0,001 kg",
    commonUses: "Mat, kjemi, farmasi og presisjonsmaling",
  },
  {
    locale: "no",
    sourceSlug: "miligram",
    slug: "milligram",
    category: "kutle",
    categoryName: "Masse",
    unit: "mg",
    name: "Milligram",
    symbol: "mg",
    shortDescription: "Milligram er en svaert liten masseenhet lik en tusendel av et gram. Den har kritisk betydning i medisin- og laboratoriemalinger.",
    historySummary: "Milligrammet fikk okt betydning saerlig innen helse og kjemi etter hvert som presisjonsvekter og analytiske laboratorier ble utviklet.",
    measurementSystem: "Det internasjonale enhetssystemet (SI, delenhet)",
    siEquivalent: "1 mg = 0,000001 kg",
    commonUses: "Medisindoser, analyser og presise formuleringer",
  },
  {
    locale: "no",
    sourceSlug: "ton",
    slug: "tonn",
    category: "kutle",
    categoryName: "Masse",
    unit: "t",
    name: "Tonn",
    symbol: "t",
    shortDescription: "Metrisk tonn er en stor masseenhet lik 1000 kilogram. Den brukes til a uttrykke tunge laster og industrielle mengder.",
    historySummary: "Ordet 'tonn' stammer fra det middelalderengelske ordet 'tun', som betyr en stor vintonne; fordi en fylt tonne veide omtrent en 'long ton', begynte ordet ogsa a brukes som masseenhet. I dag kan tre ulike 'tonn'-definisjoner skape forvirring: det metriske tonnet (noyaktig 1000 kg, standard i verden og i Norge), det amerikanske 'short ton' (2000 pund ≈ 907,18 kg), og det historisk britiske 'long ton' (2240 pund ≈ 1016,05 kg). Selv om forskjellen mellom disse tre verdiene kan virke liten, er det viktig a tydelig angi hvilken 'tonn'-definisjon som brukes i internasjonale handels- og logistikkavtaler.",
    measurementSystem: "Metrisk system, kompatibelt med SI",
    siEquivalent: "1 t = 1000 kg",
    commonUses: "Logistikk, produksjon, ravarehandel og tungindustri",
  },
  {
    locale: "no",
    sourceSlug: "pound",
    slug: "pund",
    category: "kutle",
    categoryName: "Masse",
    unit: "lb",
    name: "Pund",
    symbol: "lb",
    shortDescription: "Pund er en masseenhet brukt i det britiske og amerikanske malesystemet. Et internasjonalt pund tilsvarer noyaktig 0,45359237 kilogram.",
    historySummary: "Pund stammer fra den romerske enheten 'libra' (om lag 328,9 gram, delt i 12 'uncia') -- forkortelsen 'lb' kommer direkte herfra; selve ordet 'pound' kommer fra uttrykket 'libra pondo' (vekt malt med libra). For den normanniske erobringen (1066) brukte England det 'saksiske pundet', definert ut fra solv under kong Offa (757-796), der 1 pund solv ga 240 penny. Rundt 1300 ble 'avoirdupois-pundet', som ble utbredt i handel, opprinnelig fastsatt til 6992 troy grain, men ble under dronning Elisabeth I fastsatt til noyaktig 7000 troy grain (delt i 16 ounce). Med veiloven av 1878 ble en platinasylinder erklaert offisiell standardprototype. Den endelige internasjonale avtalen ble signert 1. juli 1959: pundet regnes na som noyaktig 0,45359237 kilogram; Storbritannia tok offisielt i bruk denne definisjonen gjennom loven av 1963.",
    measurementSystem: "Britisk og amerikansk malesystem",
    siEquivalent: "1 lb = 0,45359237 kg",
    commonUses: "Detaljhandel, transport, ernaering og industrikataloger",
  },
  {
    locale: "no",
    sourceSlug: "ons",
    slug: "ounce",
    category: "kutle",
    categoryName: "Masse",
    unit: "oz",
    name: "Ounce",
    symbol: "oz",
    shortDescription: "Ounce er en liten masseenhet brukt i det britiske og amerikanske malesystemet. En avoirdupois-ounce tilsvarer 28,349523125 gram.",
    historySummary: "Ordet 'ounce' stammer fra den romerske enheten 'uncia', som delte 'libra' (forloperen til pundet) i tolv like deler. Ounce brukt i dagliglivet, avoirdupois-ounce (28,349523125 g), tilsvarer 1/16 av et pund; men troy-ounce, brukt i edelmetallhandel, er annerledes og tyngre (31,1034768 g) -- derfor tilsvarer 'pris per ounce' oppgitt for gull/solv en enhet som er om lag 10 % tyngre enn ouncen man moter i dagligvarehandelen. Troy-ounce har navnet sitt fra Troyes, en viktig handelsbyen i middelalderens Frankrike.",
    measurementSystem: "Britisk og amerikansk malesystem",
    siEquivalent: "1 oz = 28,349523125 g",
    commonUses: "Emballasje, mat og andre lette kommersielle mal enn smykker",
  },
  // Temperatur
  {
    locale: "no",
    sourceSlug: "santigrat",
    slug: "celsius",
    category: "sicaklik",
    categoryName: "Temperatur",
    unit: "°C",
    name: "Celsius",
    symbol: "°C",
    shortDescription: "Celsius-skalaen er en av de mest brukte temperaturvisningene i dagliglivet og ingeniorfag.",
    historySummary: "Celsius-skalaen ble oppfunnet i 1742 av den svenske astronomen Anders Celsius -- men interessant nok var hans opprinnelige skala det motsatte av dagens: 0 grader representerte vannets kokepunkt, og 100 grader frysepunktet. Skalaen ble snudd i 1743 av den franske fysikeren Jean-Pierre Christin (i utformingen av 'Lyon-termometeret') til dagens ordning med 0 °C for frysing og 100 °C for koking; den svenske botanikeren Carl Linnaeus gjorde ogsa den samme ombyttingen uavhengig i 1744 for sitt eget veksthustermometer. Skalaen ble lenge kalt 'centigrade'; i 1948 endret Den internasjonale komiteen for mal og vekt offisielt navnet til 'grad Celsius', bade for a hedre Celsius og for a unnga at ordet 'centigrade' i enkelte sprak ble forvekslet med en hundredel av en vinkelenhet.",
    measurementSystem: "Temperaturskala brukt sammen med SI",
    siEquivalent: "Ved temperaturforskjell: 1 °C = 1 K",
    commonUses: "Vaer, HVAC, prosessovervaking og daglige temperaturverdier",
  },
  {
    locale: "no",
    sourceSlug: "fahrenhayt",
    slug: "fahrenheit",
    category: "sicaklik",
    categoryName: "Temperatur",
    unit: "°F",
    name: "Fahrenheit",
    symbol: "°F",
    shortDescription: "Fahrenheit er en temperaturskala som saerlig er utbredt i USA.",
    historySummary: "Fahrenheit-skalaen ble utviklet i 1724 av den polskfodte, nederlandske fysikeren Daniel Gabriel Fahrenheit. Han satte nullpunktet til den kaldeste temperaturen der en blanding av is, vann og ammoniumklorid (eller sjosalt) stabiliserte seg; 32 grader tilsvarte rent vanns frysepunkt, og 96 grader (etter hans egen maling) menneskekroppens temperatur. Fahrenheit hadde tatt verdiene fra den tidligere Romer-skalaen og multiplisert dem med 4 for a fa en finere, brokfri inndeling. I 1776-77 standardiserte en komite i Royal Society, ledet av Henry Cavendish, skalaen; vannets frysepunkt ble fastsatt til noyaktig 32 °F og kokepunktet til noyaktig 212 °F -- denne korreksjonen forte ogsa til at normal kroppstemperatur endte pa dagens kjente 98,6 °F.",
    measurementSystem: "Britisk og amerikansk maletradisjon",
    siEquivalent: "Ved temperaturforskjell: 1 °F = 5/9 K",
    commonUses: "Amerikanske vaerdata, innetemperaturer og enkelte tekniske kataloger",
  },
  {
    locale: "no",
    sourceSlug: "kelvin",
    slug: "kelvin",
    category: "sicaklik",
    categoryName: "Temperatur",
    unit: "K",
    name: "Kelvin",
    symbol: "K",
    shortDescription: "Kelvin er SI-grunnenheten for temperatur og representerer den absolutte temperaturskalaen.",
    historySummary: "Grunnlaget for Kelvin-skalaen ble lagt i 1848 av den skotske fysikeren William Thomson (senere Lord Kelvin); i artikkelen 'On an Absolute Thermometric Scale' beregnet han, ved a bruke den termiske ekspansjonskoeffisienten til ideelle gasser, at det absolutte nullpunktet lag pa om lag -273 °C -- overraskende naer dagens verdi pa -273,15 °C. I 1854 samarbeidet han med James Prescott Joule for a gjore skalaen mer praktisk og kompatibel med lufttermometre. Enheten ble formalisert i 1954 ved den 10. Generalkonferansen for mal og vekt, da vannets trippelpunkt ble definert til noyaktig 273,16 K; i 1967/68 ga den 13. konferansen enheten navnet 'kelvin'. I 2019 ble definisjonen endret enda mer fundamentalt: kelvin bygger na ikke lenger pa vannets trippelpunkt, men direkte pa Boltzmann-konstanten (fastsatt til 1,380649×10⁻²³ J/K).",
    measurementSystem: "Det internasjonale enhetssystemet (SI)",
    siEquivalent: "SIs grunnleggende temperaturenhet",
    commonUses: "Termodynamikk, vitenskapelige beregninger og analyser som krever absolutt temperatur",
  },
  // Tid
  {
    locale: "no",
    sourceSlug: "saniye",
    slug: "sekund",
    category: "zaman",
    categoryName: "Tid",
    unit: "s",
    name: "Sekund",
    symbol: "s",
    shortDescription: "Sekund er SI-grunnenheten for tid. Den ligger til grunn for alle beregninger av varighet og hastighet.",
    historySummary: "Sekundet ble historisk definert som 1/86 400 av en dag; men man innsa at sma uregelmessigheter i jordens rotasjonshastighet gjorde denne definisjonen for ustabil. I 1967, pa det 13. mote til Generalkonferansen for mal og vekt, ble sekundet fullstendig omdefinert: det defineres na som noyaktig 9 192 631 770 perioder av straalingen som svarer til overgangen mellom to grunnenerginivaer i cesium-133-atomet. Denne definisjonen gjorde det mulig for atomklokker a reproduseres med samme presisjon (pa milliarddelsniva) overalt i verden, og knyttet sekundet til en universell referanse uavhengig av himmellegemenes bevegelse.",
    measurementSystem: "Det internasjonale enhetssystemet (SI)",
    siEquivalent: "SIs grunnleggende tidsenhet",
    commonUses: "Eksperimenttider, bevegelsesanalyse, dataregistrering og tidtaking",
  },
  {
    locale: "no",
    sourceSlug: "dakika",
    slug: "minutt",
    category: "zaman",
    categoryName: "Tid",
    unit: "min",
    name: "Minutt",
    symbol: "min",
    shortDescription: "Minutt er en praktisk tidsenhet lik 60 sekunder.",
    historySummary: "Minuttet er en mellomenhet som historisk har blitt utbredt bade i daglig planlegging og ikke-vitenskapelig tidsfolging.",
    measurementSystem: "Utenfor SI, tidsenhet brukt sammen med SI",
    siEquivalent: "1 min = 60 s",
    commonUses: "Moter, korte tidsrom, trening og prosessykluser",
  },
  {
    locale: "no",
    sourceSlug: "saat",
    slug: "time",
    category: "zaman",
    categoryName: "Tid",
    unit: "t",
    name: "Time",
    symbol: "t",
    shortDescription: "Time er en utbredt tidsenhet lik 3600 sekunder.",
    historySummary: "Timeenheten har blitt overfort fra himmelske og mekaniske tidsmalingstradisjoner til moderne kalender- og skiftsystemer.",
    measurementSystem: "Utenfor SI, tidsenhet brukt sammen med SI",
    siEquivalent: "1 t = 3600 s",
    commonUses: "Arbeidstid, reise, energiforbruk og daglig planlegging",
  },
  {
    locale: "no",
    sourceSlug: "gun",
    slug: "dogn",
    category: "zaman",
    categoryName: "Tid",
    unit: "d",
    name: "Dogn",
    symbol: "d",
    shortDescription: "Dogn er en grunnleggende tidsenhet lik 24 timer (86 400 sekunder), basert pa en full omdreining av jorden om sin egen akse (soldognet).",
    historySummary: "Begrepet dogn er menneskehetens eldste og mest universelle tidsmal; det bygger pa syklusen med soloppgang og solnedgang. I den moderne definisjonen er 1 dogn fastsatt til noyaktig 86 400 SI-sekunder (gjennomsnittlig soldogn).",
    measurementSystem: "Det internasjonale enhetssystemet (SI, skalert enhet)",
    siEquivalent: "1 dogn = 86 400 s = 24 timer",
    commonUses: "Kalenderberegninger, varighets-/alderberegninger, reise- og prosjektplanlegging",
  },
  // Hastighet
  {
    locale: "no",
    sourceSlug: "metre-saniye",
    slug: "meter-per-sekund",
    category: "hiz",
    categoryName: "Hastighet",
    unit: "m/s",
    name: "Meter per sekund",
    symbol: "m/s",
    shortDescription: "Meter per sekund er SIs avledede enhet for hastighet. Den regnes som grunnleggende referanse i ingeniorfag og fysikk.",
    historySummary: "Denne betegnelsen, som fremkommer ved a kombinere meter og sekund, er det standard vitenskapelige spraket for moderne hastighetsmaling.",
    measurementSystem: "Det internasjonale enhetssystemet (SI)",
    siEquivalent: "SIs grunnleggende hastighetsenhet",
    commonUses: "Stromningslaere, mekanisk bevegelse og vitenskapelige malinger",
  },
  {
    locale: "no",
    sourceSlug: "kilometre-saat",
    slug: "kilometer-i-timen",
    category: "hiz",
    categoryName: "Hastighet",
    unit: "km/t",
    name: "Kilometer i timen",
    symbol: "km/t",
    shortDescription: "Kilometer i timen er en praktisk hastighetsenhet mye brukt i landtransport.",
    historySummary: "Etter hvert som vei- og transportsystemer ble utbredt, ble km/t standard betegnelse for kjoring og reise.",
    measurementSystem: "Metrisk praktisk bruk",
    siEquivalent: "1 km/t ≈ 0,277778 m/s",
    commonUses: "Kjoretoyhastighet, trafikkskilt og feltmalinger",
  },
  {
    locale: "no",
    sourceSlug: "mil-saat",
    slug: "engelsk-mil-i-timen",
    category: "hiz",
    categoryName: "Hastighet",
    unit: "mph",
    name: "Engelske mil i timen",
    symbol: "mph",
    shortDescription: "Engelske mil i timen er en hastighetsenhet brukt saerlig i USA og Storbritannia.",
    historySummary: "Kombinasjonen av mil og time har dannet det grunnleggende hastighetsspraket i den angloamerikanske maletradisjonen for landtransport.",
    measurementSystem: "Britisk og amerikansk malesystem",
    siEquivalent: "1 mph = 1,609344 km/t",
    commonUses: "Veihastigheter, bilindustri og feltrapporter",
  },
  {
    locale: "no",
    sourceSlug: "knot",
    slug: "knop",
    category: "hiz",
    categoryName: "Hastighet",
    unit: "knop",
    name: "Knop",
    symbol: "knop",
    shortDescription: "Knop (nautiske mil i timen) er standard hastighetsenhet i sjofart og luftfart, lik 1 nautisk mil (1852 meter) per time.",
    historySummary: "Navnet knop stammer historisk fra en trebit festet til et knutet tau ('chip log') som ble kastet ut i vannet for a male fartoyets hastighet; tauet, som var knutet med jevne mellomrom, ga fartoyets hastighet ved a telle hvor mange knuter som gikk ut i lopet av en bestemt tid.",
    measurementSystem: "Utenfor SI, standardenhet i sjofart/luftfart",
    siEquivalent: "1 knop = 1852/3600 m/s ≈ 0,5144 m/s",
    commonUses: "Skips- og flyhastighet, vindhastighet (i meteorologi), navigasjonsberegninger",
  },
  // Trykk
  {
    locale: "no",
    sourceSlug: "pascal",
    slug: "pascal",
    category: "basinc",
    categoryName: "Trykk",
    unit: "Pa",
    name: "Pascal",
    symbol: "Pa",
    shortDescription: "Pascal er SIs avledede enhet for trykk. Den defineres ved sammenhengen 1 Pa = 1 N/m².",
    historySummary: "Enheten er oppkalt etter den franske vitenskapsmannen Blaise Pascal fra 1600-tallet -- Pascal er kjent for sitt arbeid innen hydrodynamikk og hydrostatikk, og for sine banebrytende trykkforsok med barometeret. Pascals funn om at 'trykk pafort en lukket vaeske overfores likt i alle retninger' (Pascals lov) danner grunnlaget for hydrauliske systemer. Enheten ble formelt vedtatt som SI-enhet pa det 14. mote til Generalkonferansen for mal og vekt i 1971, og definert som newton per kvadratmeter (N/m²).",
    measurementSystem: "Det internasjonale enhetssystemet (SI)",
    siEquivalent: "SIs grunnleggende trykkenhet, 1 Pa = 1 N/m²",
    commonUses: "Vitenskapelige beregninger, materialanalyse og referanseomregninger",
  },
  {
    locale: "no",
    sourceSlug: "bar",
    slug: "bar",
    category: "basinc",
    categoryName: "Trykk",
    unit: "bar",
    name: "Bar",
    symbol: "bar",
    shortDescription: "Bar er en trykkenhet lik 100 000 pascal. Den er en svaert utbredt praktisk visning pa industri- og utstyrsmalere.",
    historySummary: "Bar-enheten ble lansert av den norske meteorologen Vilhelm Bjerknes, en av pionerene innen moderne vaervarsling; navnet kommer fra det oldgreske ordet 'baros', som betyr 'vekt' (interessant nok ble ordet 'bar' ogsa brukt mellom 1793 og 1795 i det tidlige metriske systemet, om en masseenhet tilsvarende dagens tonn). 1 bar tilsvarer noyaktig 100 000 pascal og ligger svaert naer gjennomsnittlig atmosfaeretrykk ved havniva (om lag 1,013 bar). Selv om bar ikke er en offisiell SI-enhet, brukes den fortsatt mye av meteorologer og luftfartsbransjen i dag, fordi den tallmessig tilsvarer millibar/hektopascal og er praktisk i bruk.",
    measurementSystem: "Metrisk ingeniorenhet utenfor SI",
    siEquivalent: "1 bar = 100 000 Pa",
    commonUses: "Kompressorer, hydraulikk, pneumatikk og servicemanometre",
  },
  {
    locale: "no",
    sourceSlug: "psi",
    slug: "psi",
    category: "basinc",
    categoryName: "Trykk",
    unit: "psi",
    name: "PSI",
    symbol: "psi",
    shortDescription: "PSI er forkortelsen for pound-force per square inch. Den er en utbredt trykkenhet i angloamerikanske tekniske systemer.",
    historySummary: "PSI er, som navnet tilsier, en sammensatt enhet dannet ved a dele en kraftenhet (pound-force) pa en arealenhet (kvadrattomme), og ble utbredt i britisk ingeniortradisjon pa 1800-tallet for a angi kjeletrykk i dampmaskinenes tidsalder. Selv om det metriske systemet er blitt globalt standard, er PSI fortsatt den de facto bransjestandarden innen bilindustri (dekktrykk), hydrauliske systemer og amerikanskproduserte industrikataloger.",
    measurementSystem: "Britisk og amerikansk ingeniorbruk",
    siEquivalent: "1 psi = 6894,757293168 Pa",
    commonUses: "Dekktrykk, hydrauliske systemer og teknisk service",
  },
  {
    locale: "no",
    sourceSlug: "atmosfer",
    slug: "atmosfar",
    category: "basinc",
    categoryName: "Trykk",
    unit: "atm",
    name: "Atmosfaere",
    symbol: "atm",
    shortDescription: "Atmosfaere er en trykkenhet basert pa en referanseverdi naer gjennomsnittlig trykk i jordens atmosfaere ved havniva. Ogsa kalt standard atmosfaere.",
    historySummary: "Atmosfaere-enheten ble utbredt etter hvert som barometriske malinger og havnivareferansetrykk ble brukt som standard sammenligningspunkt i tekniske og vitenskapelige arbeider. I 1954 definerte den 10. Generalkonferansen for mal og vekt (CGPM) standard atmosfaere til noyaktig 101 325 Pa.",
    measurementSystem: "Utenfor SI, referanseenhet i meteorologi og ingeniorfag",
    siEquivalent: "1 atm = 101 325 Pa (definert verdi)",
    commonUses: "Referanseforhold, meteorologi, vakuum- og trykkmalinger",
  },
  // Energi
  {
    locale: "no",
    sourceSlug: "joule",
    slug: "joule",
    category: "enerji",
    categoryName: "Energi",
    unit: "J",
    name: "Joule",
    symbol: "J",
    shortDescription: "Joule er SIs avledede enhet for energi. Den brukes til a uttrykke mengder av arbeid, varme og energi.",
    historySummary: "Enheten ble oppkalt etter den britiske fysikeren James Prescott Joule (1818-1889), etter hans arbeid som klarla sammenhengen mellom mekanisk arbeid og varme. Navnet ble forst foreslatt 23. august 1882, i William Siemens sin presidenttale for British Association for the Advancement of Science; Siemens foreslo a kalle den 'joule', til aere for 'mannen som har bidratt sa mye til a utvikle den dynamiske varmeteorien'. Enheten ble formelt vedtatt 31. august 1889, ved den andre internasjonale elektriske kongress, sammen med enheten watt -- ved et interessant sammentreff dode Joule senere samme ar (11. oktober 1889). Definisjonen ble oppdatert i 1946 innenfor Giorgi-systemet, og ble na uttrykt direkte og uavhengig av elektromagnetiske enheter, som 'arbeidet en kraft utforer over en strekning pa en meter'.",
    measurementSystem: "Det internasjonale enhetssystemet (SI)",
    siEquivalent: "SIs grunnleggende energienhet",
    commonUses: "Termodynamikk, energibalanser og vitenskapelige beregninger",
  },
  {
    locale: "no",
    sourceSlug: "kilovatsaat",
    slug: "kilowattime",
    category: "enerji",
    categoryName: "Energi",
    unit: "kWh",
    name: "Kilowattime",
    symbol: "kWh",
    shortDescription: "Kilowattime er en energienhet mye brukt for a male strømforbruk.",
    historySummary: "Pa grunn av strommalere og faktureringssystemer har kilowattime blitt en av de mest kjente enhetene for praktisk energibruk.",
    measurementSystem: "Teknisk og kommersiell energienhet",
    siEquivalent: "1 kWh = 3,6 MJ",
    commonUses: "Strømregninger, batterikapasitet og forbrukssammenligninger",
  },
  {
    locale: "no",
    sourceSlug: "kalori",
    slug: "kalori",
    category: "enerji",
    categoryName: "Energi",
    unit: "cal",
    name: "Kalori",
    symbol: "cal",
    shortDescription: "Kalori (cal) er en energienhet utenfor SI, definert som energimengden som kreves for a heve temperaturen til ett gram vann med 1 °C. Ifolge den termokjemiske kaloridefinisjonen tilsvarer 1 kalori 4,184 joule.",
    historySummary: "Kaloribegrepet ble lansert pa 1800-tallet av den franske kjemikeren Nicolas Clement for a male varmemengde, og ble utbredt i termodynamikkens utviklingsperiode. Selv om SI-enheten joule i stor grad forventes a erstatte den, brukes den fortsatt mye (som kilokalori) i ernaeringsvitenskapen.",
    measurementSystem: "Utenfor SI, tradisjonell energienhet",
    siEquivalent: "1 cal = 4,184 J (termokjemisk definisjon)",
    commonUses: "Kjemiske og termodynamiske beregninger, matenergi (via kilokalori)",
  },
  {
    locale: "no",
    sourceSlug: "btu",
    slug: "btu",
    category: "enerji",
    categoryName: "Energi",
    unit: "Btu",
    name: "BTU",
    symbol: "Btu",
    shortDescription: "BTU (British Thermal Unit) er en energienhet brukt i det britiske/amerikanske malesystemet, definert som energimengden som kreves for a heve temperaturen til ett pund vann med 1 °F.",
    historySummary: "BTU ble utviklet i England i dampmaskinenes tidsalder for a male varmeenergi, og ble etter hvert standardenheten for oppvarmings-/kjolebransjen i angloamerikanske land, saerlig USA.",
    measurementSystem: "Britisk og amerikansk malesystem",
    siEquivalent: "1 Btu = 1055,056 J",
    commonUses: "Klimaanlegg- og varmerkapasitet (kjole-/varmeeffekt), naturgassregninger (USA)",
  },
  // Datalagring
  {
    locale: "no",
    sourceSlug: "bayt",
    slug: "byte",
    category: "veri",
    categoryName: "Datalagring",
    unit: "B",
    name: "Byte",
    symbol: "B",
    shortDescription: "Byte er den grunnleggende maleenheten for digital data. Den bestar av 8 bit og brukes til a representere ett tegn (bokstav, tall osv.).",
    historySummary: "Betegnelsen 'byte' ble bevisst avledet i 1956 av ingenioren Werner Buchholz ved IBM, som arbeidet med Stretch-datamaskinen, ved a endre skrivematen til ordet 'bite' for a unnga forveksling med ordet 'bit'. I de forste arene kunne en byte vaere ulik lengde -- fra 1 til 6 bit -- avhengig av datamaskinarkitekturen som ble brukt; standarden pa 8-bits byte ble den de facto bransjestandarden med IBMs System/360, som ble lansert i 1964 og var en av tidens mest innflytelsesrike datamaskinfamilier.",
    measurementSystem: "Digital dataenhet (databehandlingsstandard)",
    siEquivalent: "1 byte = 8 bit",
    commonUses: "Filstorrelse, minnekapasitet og dataoverforingsmaling",
  },
  {
    locale: "no",
    sourceSlug: "megabayt",
    slug: "megabyte",
    category: "veri",
    categoryName: "Datalagring",
    unit: "MB",
    name: "Megabyte",
    symbol: "MB",
    shortDescription: "Megabyte (MB) er en dataenhet lik 1 000 000 byte. Den brukes ofte til a uttrykke storrelsen pa bilder, musikkfiler og korte dokumenter.",
    historySummary: "Megabyte ble en standard referanseenhet for a uttrykke fil- og diskstorrelser etter hvert som personlige datamaskiner ble utbredt.",
    measurementSystem: "Det internasjonale enhetssystemet (SI, multiplum)",
    siEquivalent: "1 MB = 1 000 000 byte",
    commonUses: "Bilder, musikkfiler, korte videoer og applikasjonsstorrelser",
  },
  {
    locale: "no",
    sourceSlug: "gigabayt",
    slug: "gigabyte",
    category: "veri",
    categoryName: "Datalagring",
    unit: "GB",
    name: "Gigabyte",
    symbol: "GB",
    shortDescription: "Gigabyte (GB) er en dataenhet lik 1 milliard byte. Den brukes til a uttrykke lagringsplass pa smarttelefoner, videofiler og RAM-kapasitet.",
    historySummary: "Etter hvert som lagringsteknologien utviklet seg, ble gigabyte standard uttrykk for disk-, minne- og mobilenhetskapasitet; forskjellen mellom SI (1000-basert) og den tradisjonelle databehandlingsbruken (1024-basert) blir mest merkbar nettopp i denne enheten.",
    measurementSystem: "Det internasjonale enhetssystemet (SI, multiplum)",
    siEquivalent: "1 GB = 1 000 000 000 byte",
    commonUses: "Lagringsplass pa smarttelefon og datamaskin, RAM-kapasitet, videofiler",
  },
  // Elektrisitet
  {
    locale: "no",
    sourceSlug: "volt",
    slug: "volt",
    category: "elektrik",
    categoryName: "Elektrisitet",
    unit: "V",
    name: "Volt",
    symbol: "V",
    shortDescription: "Volt er SIs avledede enhet for elektrisk spenning.",
    historySummary: "Enheten er oppkalt etter den italienske fysikeren Alessandro Volta -- Volta oppfant 'det voltaiske batteriet' i 1800, som resultat av sin diskusjon med kollegaen Luigi Galvani om 'animalsk elektrisitet'; ved a oppdage at sink og solv var det mest effektive metallparet, skapte han verdens forste apparat som produserte en kontinuerlig elektrisk strom (forloperen til batteriet). Navnet 'volt' ble foreslatt mye senere, i 1861, av Latimer Clark og Charles Bright. I 1873 definerte British Association for the Advancement of Science formelt enhetene volt, ohm og farad; i 1881 vedtok den internasjonale elektriske kongressen volt som den offisielle enheten for elektromotorisk kraft (spenning). Med SI-revisjonen i 2019 ble ogsa definisjonen av volt oppdatert, ved a knytte den elementaere elektriske ladningen til en fast verdi.",
    measurementSystem: "Det internasjonale enhetssystemet (SI)",
    siEquivalent: "SIs grunnleggende spenningsenhet",
    commonUses: "Elektroniske kretser, stromforsyninger og nettspenninger",
  },
  {
    locale: "no",
    sourceSlug: "amper",
    slug: "ampere",
    category: "elektrik",
    categoryName: "Elektrisitet",
    unit: "A",
    name: "Ampere",
    symbol: "A",
    shortDescription: "Ampere er standardenheten for en av SIs grunnleggende storrelser: elektrisk strom.",
    historySummary: "Enheten er oppkalt etter den franske fysikeren og matematikeren Andre-Marie Ampere (1775-1836), som la grunnlaget for elektrodynamikken gjennom sitt arbeid med elektromagnetisme; Ampere bygde her videre pa funnene til den danske fysikeren Hans Christian Orsted. Ampere ble i 1881 erklaert standardenheten for elektrisk strom, gjennom en internasjonal konvensjon signert ved den internasjonale elektriske utstillingen; den forste definisjonen var en tidel av den elektromagnetiske stromenheten i CGS-systemet. Frem til SI-revisjonen i 2019 var ampere definert som strommen som skaper en magnetisk kraft pa 2×10⁻⁷ newton per meter mellom to parallelle ledere med 1 meters avstand; fra 2019 defineres den direkte ut fra multipler av den elementaere elektriske ladningen (fastsatt til 1,602176634×10⁻¹⁹ coulomb).",
    measurementSystem: "Det internasjonale enhetssystemet (SI)",
    siEquivalent: "SIs grunnleggende strømenhet",
    commonUses: "Strommalinger, vernutstyr og apparatmerking",
  },
  {
    locale: "no",
    sourceSlug: "miliamper",
    slug: "milliampere",
    category: "elektrik",
    categoryName: "Elektrisitet",
    unit: "mA",
    name: "Milliampere",
    symbol: "mA",
    shortDescription: "Milliampere er en liten strømenhet lik en tusendel av en ampere.",
    historySummary: "Milliampere-visning ble utbredt for a gjore det enklere a lese lave stromverdier i elektronikk og maleinstrumenter.",
    measurementSystem: "Det internasjonale enhetssystemet (SI, delenhet)",
    siEquivalent: "1 mA = 0,001 A",
    commonUses: "Elektroniske kretser, sensorer og lavstromtester",
  },
  // Gullkarat
  {
    locale: "no",
    sourceSlug: "24-ayar-altin",
    slug: "24-karat-gull",
    category: "altin_ayar",
    categoryName: "Gullkarat",
    unit: "24K",
    name: "24 karat gull",
    symbol: "24K",
    shortDescription: "24 karat gull er 99,9 % rent, naermest helt rent gull. Fordi det er den mykeste karaten, brukes det oftest til barrer og investeringsprodukter.",
    historySummary: "Karatsystemet er en tradisjonell gullsmedstandard som uttrykker renhetsgraden i en gull-legering pa en skala fra 24; 24 karat representerer ulegert, rent gull.",
    measurementSystem: "Gullsmedstandard for renhet (karat)",
    siEquivalent: "24 karat = 100 % rent gullinnhold",
    commonUses: "Gullbarrer, investeringsgull og bruk som renhetsreferanse",
  },
  {
    locale: "no",
    sourceSlug: "22-ayar-altin",
    slug: "22-karat-gull",
    category: "altin_ayar",
    categoryName: "Gullkarat",
    unit: "22K",
    name: "22 karat gull",
    symbol: "22K",
    shortDescription: "22 karat gull er en legering der 22/24 (om lag 91,6 %) av innholdet er rent gull. Den er vanlig for armband og tradisjonelle smykker i Tyrkia.",
    historySummary: "22 karat oppstar ved at en liten mengde solv eller kobber legeres inn i rent gull for a redusere mykheten og oke holdbarheten, og har blitt den tradisjonelle smykkestandarden i Tyrkia og Midtosten.",
    measurementSystem: "Gullsmedstandard for renhet (karat)",
    siEquivalent: "22 karat = 91,6 % rent gullinnhold (22/24)",
    commonUses: "Armband, tradisjonelle smykker og gullgaver",
  },
  {
    locale: "no",
    sourceSlug: "18-ayar-altin",
    slug: "18-karat-gull",
    category: "altin_ayar",
    categoryName: "Gullkarat",
    unit: "18K",
    name: "18 karat gull",
    symbol: "18K",
    shortDescription: "18 karat gull er en legering der 18/24 (75 %) av innholdet er rent gull. Takket vaere den hoye holdbarheten foretrekkes den til dagligsmykker.",
    historySummary: "18 karat, som er hardere og mer ripebestandig enn rent gull, har blitt den internasjonale standarden saerlig for ringer og dagligsmykker.",
    measurementSystem: "Gullsmedstandard for renhet (karat)",
    siEquivalent: "18 karat = 75 % rent gullinnhold (18/24)",
    commonUses: "Ringer, kjeder, dagligsmykker og diamantinnfatninger",
  },
  // Solvinnhold
  {
    locale: "no",
    sourceSlug: "999-ayar-gumus",
    slug: "silver-999",
    category: "gumus_ayar",
    categoryName: "Solvinnhold",
    unit: "999",
    name: "Solv 999 (fint)",
    symbol: "999",
    shortDescription: "Solv 999 er 99,9 % rent, naermest helt rent solv, ogsa kalt 'fint solv'. Fordi det er svaert mykt, brukes det hovedsakelig til barrer og investeringsprodukter fremfor smykker.",
    historySummary: "I motsetning til gull uttrykkes solvets renhet direkte i tusendeler; 999 representerer ulegert, rent solv og brukes som renhetsreferanse ved handel med edle metaller.",
    measurementSystem: "Gullsmedstandard for renhet (tusendeler)",
    siEquivalent: "999 = 99,9 % rent solvinnhold",
    commonUses: "Solvbarrer, investeringssolv og bruk som renhetsreferanse",
  },
  {
    locale: "no",
    sourceSlug: "925-ayar-gumus",
    slug: "sterlingsilver-925",
    category: "gumus_ayar",
    categoryName: "Solvinnhold",
    unit: "925",
    name: "Sterlingsolv (925)",
    symbol: "925",
    shortDescription: "Sterlingsolv inneholder 92,5 % rent solv, der resten som regel er kobber. Det er kjent verden over som 'sterling silver' og er den mest brukte solvstandarden innen smykker.",
    historySummary: "Sterlingsolv-standarden oppsto i England for a motvirke det rene solvets ekstreme mykhet, og har over tid blitt den faktiske globale standarden for solvsmykker og bruksgjenstander.",
    measurementSystem: "Gullsmedstandard for renhet (tusendeler)",
    siEquivalent: "925 = 92,5 % rent solvinnhold (sterlingsolv)",
    commonUses: "Solvsmykker, ringer, kjeder og solvbestikk",
  },
];

export function findNorwegianUnitPageBySourceSlug(sourceSlug: string) {
  return norwegianUnitPages.find((page) => page.sourceSlug === sourceSlug);
}

export function findNorwegianUnitPage(category: string, unit: string) {
  return norwegianUnitPages.find(
    (page) => page.category === category && page.unit === unit
  );
}
