import type { ElementCategory } from "./periodicTableData";

export const elementCategoryLabelsDe: Record<ElementCategory, string> = {
  "alkali-metal": "Alkalimetall",
  "toprak-alkali-metal": "Erdalkalimetall",
  "gecis-metali": "Übergangsmetall",
  "post-gecis-metali": "Andere Metalle",
  "yari-metal": "Halbmetall (Metalloid)",
  ametal: "Nichtmetall",
  halojen: "Halogen",
  "soy-gaz": "Edelgas",
  lantanit: "Lanthanoid",
  aktinit: "Actinoid",
};

// Vollständige deutsche Namen für alle 118 Elemente, per Symbol
// (sprachunabhängiger Schlüssel) statt per TR-Namen, damit sie auch
// von molecularFormulaParser.ts-Konsumenten direkt genutzt werden
// können.
export const elementNamesDeBySymbol: Record<string, string> = {
  H: "Wasserstoff",
  He: "Helium",
  Li: "Lithium",
  Be: "Beryllium",
  B: "Bor",
  C: "Kohlenstoff",
  N: "Stickstoff",
  O: "Sauerstoff",
  F: "Fluor",
  Ne: "Neon",
  Na: "Natrium",
  Mg: "Magnesium",
  Al: "Aluminium",
  Si: "Silicium",
  P: "Phosphor",
  S: "Schwefel",
  Cl: "Chlor",
  Ar: "Argon",
  K: "Kalium",
  Ca: "Calcium",
  Sc: "Scandium",
  Ti: "Titan",
  V: "Vanadium",
  Cr: "Chrom",
  Mn: "Mangan",
  Fe: "Eisen",
  Co: "Kobalt",
  Ni: "Nickel",
  Cu: "Kupfer",
  Zn: "Zink",
  Ga: "Gallium",
  Ge: "Germanium",
  As: "Arsen",
  Se: "Selen",
  Br: "Brom",
  Kr: "Krypton",
  Rb: "Rubidium",
  Sr: "Strontium",
  Y: "Yttrium",
  Zr: "Zirconium",
  Nb: "Niob",
  Mo: "Molybdän",
  Tc: "Technetium",
  Ru: "Ruthenium",
  Rh: "Rhodium",
  Pd: "Palladium",
  Ag: "Silber",
  Cd: "Cadmium",
  In: "Indium",
  Sn: "Zinn",
  Sb: "Antimon",
  Te: "Tellur",
  I: "Iod",
  Xe: "Xenon",
  Cs: "Caesium",
  Ba: "Barium",
  La: "Lanthan",
  Ce: "Cer",
  Pr: "Praseodym",
  Nd: "Neodym",
  Pm: "Promethium",
  Sm: "Samarium",
  Eu: "Europium",
  Gd: "Gadolinium",
  Tb: "Terbium",
  Dy: "Dysprosium",
  Ho: "Holmium",
  Er: "Erbium",
  Tm: "Thulium",
  Yb: "Ytterbium",
  Lu: "Lutetium",
  Hf: "Hafnium",
  Ta: "Tantal",
  W: "Wolfram",
  Re: "Rhenium",
  Os: "Osmium",
  Ir: "Iridium",
  Pt: "Platin",
  Au: "Gold",
  Hg: "Quecksilber",
  Tl: "Thallium",
  Pb: "Blei",
  Bi: "Wismut",
  Po: "Polonium",
  At: "Astat",
  Rn: "Radon",
  Fr: "Francium",
  Ra: "Radium",
  Ac: "Actinium",
  Th: "Thorium",
  Pa: "Protactinium",
  U: "Uran",
  Np: "Neptunium",
  Pu: "Plutonium",
  Am: "Americium",
  Cm: "Curium",
  Bk: "Berkelium",
  Cf: "Californium",
  Es: "Einsteinium",
  Fm: "Fermium",
  Md: "Mendelevium",
  No: "Nobelium",
  Lr: "Lawrencium",
  Rf: "Rutherfordium",
  Db: "Dubnium",
  Sg: "Seaborgium",
  Bh: "Bohrium",
  Hs: "Hassium",
  Mt: "Meitnerium",
  Ds: "Darmstadtium",
  Rg: "Roentgenium",
  Cn: "Copernicium",
  Nh: "Nihonium",
  Fl: "Flerovium",
  Mc: "Moscovium",
  Lv: "Livermorium",
  Ts: "Tenness",
  Og: "Oganesson",
};

export function slugifyElementNameDe(nameDe: string) {
  return nameDe
    .toLocaleLowerCase("de-DE")
    .replace(/ä/g, "ae")
    .replace(/ö/g, "oe")
    .replace(/ü/g, "ue")
    .replace(/ß/g, "ss")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}
