export const countryNamesUz: Record<string, string> = {
  turkiye: "Turkiya",
  almanya: "Germaniya",
  fransa: "Fransiya",
  italya: "Italiya",
  ispanya: "Ispaniya",
  portekiz: "Portugaliya",
  hollanda: "Niderlandiya",
  belcika: "Belgiya",
  isvicre: "Shveytsariya",
  avusturya: "Avstriya",
  "birlesik-krallik": "Buyuk Britaniya (Angliya, Shotlandiya, Uels)",
  irlanda: "Irlandiya",
  danimarka: "Daniya",
  norvec: "Norvegiya",
  isvec: "Shvetsiya",
  finlandiya: "Finlyandiya",
  izlanda: "Islandiya",
  polonya: "Polsha",
  "cek-cumhuriyeti": "Chexiya",
  slovakya: "Slovakiya",
  macaristan: "Vengriya",
  romanya: "Ruminiya",
  bulgaristan: "Bolgariya",
  yunanistan: "Gretsiya",
  hirvatistan: "Xorvatiya",
  sirbistan: "Serbiya",
  "bosna-hersek": "Bosniya va Gertsegovina",
  karadag: "Chernogoriya",
  "kuzey-makedonya": "Shimoliy Makedoniya",
  arnavutluk: "Albaniya",
  kosova: "Kosovo",
  slovenya: "Sloveniya",
  ukrayna: "Ukraina",
  rusya: "Rossiya",
  belarus: "Belarus",
  moldova: "Moldova",
  estonya: "Estoniya",
  letonya: "Latviya",
  litvanya: "Litva",
  kibris: "Kipr (Rum qismi)",
  kktc: "Shimoliy Kipr Turk Respublikasi",
  malta: "Malta",
  lihtenstayn: "Lixtenshteyn",
  luksemburg: "Lyuksemburg",
  monako: "Monako",
  gurcistan: "Gruziya",
  ermenistan: "Armaniston",
  azerbaycan: "Ozarbayjon",
  kazakistan: "Qozog'iston",
  ozbekistan: "O'zbekiston",
  kirgizistan: "Qirg'iziston",
  tacikistan: "Tojikiston",
  turkmenistan: "Turkmaniston",
  "amerika-birlesik-devletleri": "Amerika Qo'shma Shtatlari",
  kanada: "Kanada",
  meksika: "Meksika",
  brezilya: "Braziliya",
  arjantin: "Argentina",
  sili: "Chili",
  kolombiya: "Kolumbiya",
  peru: "Peru",
  ekvador: "Ekvador",
  venezuela: "Venesuela",
  bolivya: "Boliviya",
  paraguay: "Paragvay",
  uruguay: "Urugvay",
  "kosta-rika": "Kosta-Rika",
  panama: "Panama",
  guatemala: "Gvatemala",
  kuba: "Kuba",
  "dominik-cumhuriyeti": "Dominikan Respublikasi",
  jamaika: "Yamayka",
  "porto-riko": "Puerto-Riko",
  japonya: "Yaponiya",
  "guney-kore": "Janubiy Koreya",
  cin: "Xitoy",
  "hong-kong": "Gonkong",
  tayvan: "Tayvan",
  hindistan: "Hindiston",
  pakistan: "Pokiston",
  bangladesh: "Bangladesh",
  "sri-lanka": "Shri-Lanka",
  nepal: "Nepal",
  endonezya: "Indoneziya",
  malezya: "Malayziya",
  singapur: "Singapur",
  tayland: "Tailand",
  vietnam: "Vyetnam",
  filipinler: "Filippin",
  "kamboçya": "Kambodja",
  laos: "Laos",
  myanmar: "Myanma",
  "moğolistan": "Mongoliya",
  avustralya: "Avstraliya",
  "yeni-zelanda": "Yangi Zelandiya",
  fiji: "Fiji",
  misir: "Misr",
  fas: "Marokash",
  tunus: "Tunis",
  cezayir: "Jazoir",
  libya: "Liviya",
  "guney-afrika": "Janubiy Afrika Respublikasi",
  nijerya: "Nigeriya",
  kenya: "Keniya",
  etiyopya: "Efiopiya",
  tanzanya: "Tanzaniya",
  gana: "Gana",
  senegal: "Senegal",
  "birlesik-arap-emirlikleri": "Birlashgan Arab Amirliklari",
  "suudi-arabistan": "Saudiya Arabistoni",
  katar: "Qatar",
  kuveyt: "Quvayt",
  bahreyn: "Bahrayn",
  umman: "Ummon",
  urdun: "Iordaniya",
  lubnan: "Livan",
  israil: "Isroil",
  irak: "Iroq",
  iran: "Eron",
};

export const plugTypeDescriptionsUz: Record<string, string> = {
  A: "Ikkita tekis parallel pin (yersiz) — AQSH/Yaponiya/Kanada turi",
  B: "Ikkita tekis pin + yer pini — AQSH/Kanada turi (yerlangan)",
  C: "Ikkita dumaloq pin (yersiz) — Yevropa standarti",
  D: "Uchta dumaloq pin, uchburchak joylashuv (yerlangan) — eski Britaniya turi",
  E: "Ikkita dumaloq pin + rozetkada yer teshigi — Fransuz turi",
  F: "Ikkita dumaloq pin + yon tomonlarda yer klipsi (Schuko) — Nemis turi",
  G: "Uchta to'g'ri burchakli pin — Britaniya (BS 1363) turi",
  H: "Ikkita qiya dumaloq pin — Isroil turi",
  I: "Uchta tekis pin, V shaklida — Avstraliya/Xitoy turi",
  J: "Ikkita dumaloq pin + yer pini — Shveytsariya turi",
  K: "Ikkita dumaloq pin + yer pini — Daniya turi",
  L: "Ikkita dumaloq pin + o'rtada yer pini — Italyan turi",
  M: "Uchta qalin dumaloq pin — Janubiy Afrika turi",
  N: "Ikki/uch dumaloq pin — Braziliya turi",
  O: "Uch pinli — Tailand turi",
};
