// Turkiye'nin 81 ilinin deniz seviyesinden rakimi (metre). Il merkezi
// referans alinir. Kaynak: birden fazla cografya kaynagiyla capraz
// kontrol edilmis karayolu olcumu degerleri.
export type ProvinceElevation = {
  id: string;
  nameTr: string;
  elevationM: number;
};

export const turkishProvinceElevations: ProvinceElevation[] = [
  { id: "erzurum", nameTr: "Erzurum", elevationM: 1890 },
  { id: "ardahan", nameTr: "Ardahan", elevationM: 1870 },
  { id: "kars", nameTr: "Kars", elevationM: 1768 },
  { id: "hakkari", nameTr: "Hakkari", elevationM: 1748 },
  { id: "van", nameTr: "Van", elevationM: 1727 },
  { id: "agri", nameTr: "Ağrı", elevationM: 1640 },
  { id: "bayburt", nameTr: "Bayburt", elevationM: 1556 },
  { id: "bitlis", nameTr: "Bitlis", elevationM: 1500 },
  { id: "mus", nameTr: "Muş", elevationM: 1404 },
  { id: "sirnak", nameTr: "Şırnak", elevationM: 1350 },
  { id: "yozgat", nameTr: "Yozgat", elevationM: 1301 },
  { id: "sivas", nameTr: "Sivas", elevationM: 1285 },
  { id: "nevsehir", nameTr: "Nevşehir", elevationM: 1250 },
  { id: "nigde", nameTr: "Niğde", elevationM: 1229 },
  { id: "erzincan", nameTr: "Erzincan", elevationM: 1214 },
  { id: "gumushane", nameTr: "Gümüşhane", elevationM: 1153 },
  { id: "bingol", nameTr: "Bingöl", elevationM: 1151 },
  { id: "kayseri", nameTr: "Kayseri", elevationM: 1071 },
  { id: "elazig", nameTr: "Elazığ", elevationM: 1067 },
  { id: "karaman", nameTr: "Karaman", elevationM: 1038 },
  { id: "isparta", nameTr: "Isparta", elevationM: 1035 },
  { id: "afyon", nameTr: "Afyonkarahisar", elevationM: 1021 },
  { id: "konya", nameTr: "Konya", elevationM: 1016 },
  { id: "kirsehir", nameTr: "Kırşehir", elevationM: 978 },
  { id: "aksaray", nameTr: "Aksaray", elevationM: 975 },
  { id: "malatya", nameTr: "Malatya", elevationM: 964 },
  { id: "burdur", nameTr: "Burdur", elevationM: 950 },
  { id: "kutahya", nameTr: "Kütahya", elevationM: 950 },
  { id: "mardin", nameTr: "Mardin", elevationM: 938 },
  { id: "tunceli", nameTr: "Tunceli", elevationM: 914 },
  { id: "usak", nameTr: "Uşak", elevationM: 906 },
  { id: "siirt", nameTr: "Siirt", elevationM: 902 },
  { id: "igdir", nameTr: "Iğdır", elevationM: 860 },
  { id: "ankara", nameTr: "Ankara", elevationM: 850 },
  { id: "gaziantep", nameTr: "Gaziantep", elevationM: 843 },
  { id: "corum", nameTr: "Çorum", elevationM: 801 },
  { id: "kastamonu", nameTr: "Kastamonu", elevationM: 798 },
  { id: "eskisehir", nameTr: "Eskişehir", elevationM: 782 },
  { id: "bolu", nameTr: "Bolu", elevationM: 725 },
  { id: "cankiri", nameTr: "Çankırı", elevationM: 723 },
  { id: "kirikkale", nameTr: "Kırıkkale", elevationM: 700 },
  { id: "diyarbakir", nameTr: "Diyarbakır", elevationM: 670 },
  { id: "adiyaman", nameTr: "Adıyaman", elevationM: 669 },
  { id: "kilis", nameTr: "Kilis", elevationM: 640 },
  { id: "tokat", nameTr: "Tokat", elevationM: 640 },
  { id: "mugla", nameTr: "Muğla", elevationM: 625 },
  { id: "kahramanmaras", nameTr: "Kahramanmaraş", elevationM: 568 },
  { id: "batman", nameTr: "Batman", elevationM: 525 },
  { id: "artvin", nameTr: "Artvin", elevationM: 520 },
  { id: "sanliurfa", nameTr: "Şanlıurfa", elevationM: 518 },
  { id: "bilecik", nameTr: "Bilecik", elevationM: 500 },
  { id: "amasya", nameTr: "Amasya", elevationM: 392 },
  { id: "denizli", nameTr: "Denizli", elevationM: 354 },
  { id: "karabuk", nameTr: "Karabük", elevationM: 258 },
  { id: "kirklareli", nameTr: "Kırklareli", elevationM: 209 },
  { id: "bursa", nameTr: "Bursa", elevationM: 155 },
  { id: "osmaniye", nameTr: "Osmaniye", elevationM: 150 },
  { id: "duzce", nameTr: "Düzce", elevationM: 146 },
  { id: "balikesir", nameTr: "Balıkesir", elevationM: 139 },
  { id: "istanbul", nameTr: "İstanbul", elevationM: 120 },
  { id: "hatay", nameTr: "Hatay", elevationM: 85 },
  { id: "manisa", nameTr: "Manisa", elevationM: 74 },
  { id: "aydin", nameTr: "Aydın", elevationM: 64 },
  { id: "edirne", nameTr: "Edirne", elevationM: 42 },
  { id: "antalya", nameTr: "Antalya", elevationM: 39 },
  { id: "sakarya", nameTr: "Sakarya", elevationM: 31 },
  { id: "adana", nameTr: "Adana", elevationM: 23 },
  { id: "bartin", nameTr: "Bartın", elevationM: 19 },
  { id: "sinop", nameTr: "Sinop", elevationM: 17 },
  { id: "tekirdag", nameTr: "Tekirdağ", elevationM: 10 },
  { id: "trabzon", nameTr: "Trabzon", elevationM: 10 },
  { id: "zonguldak", nameTr: "Zonguldak", elevationM: 10 },
  { id: "mersin", nameTr: "Mersin", elevationM: 6 },
  { id: "rize", nameTr: "Rize", elevationM: 6 },
  { id: "giresun", nameTr: "Giresun", elevationM: 5 },
  { id: "yalova", nameTr: "Yalova", elevationM: 5 },
  { id: "samsun", nameTr: "Samsun", elevationM: 4 },
  { id: "canakkale", nameTr: "Çanakkale", elevationM: 3 },
  { id: "kocaeli", nameTr: "Kocaeli", elevationM: 3 },
  { id: "ordu", nameTr: "Ordu", elevationM: 3 },
  { id: "izmir", nameTr: "İzmir", elevationM: 2 },
];
