export type UnitCategory = string;

export type LocalizedUnitName = {
  name: string;
  slug: string;
};

export type UnitRegistryEntry = {
  id: string;
  category: UnitCategory;
  symbol: string;
  displaySymbol?: string;
  siFactor?: number;
  isTemperature?: boolean;
  tr?: LocalizedUnitName;
  en?: LocalizedUnitName;
  de?: LocalizedUnitName;
  enConversionSlug?: string;
};

export const unitRegistry: UnitRegistryEntry[] = [
  // ---- uzunluk / length / Länge ----
  {
    id: "metre",
    category: "uzunluk",
    symbol: "m",
    siFactor: 1,
    tr: { name: "Metre", slug: "metre" },
    en: { name: "Meter", slug: "meter" },
    de: { name: "Meter", slug: "meter" },
    enConversionSlug: "meters",
  },
  {
    id: "kilometre",
    category: "uzunluk",
    symbol: "km",
    siFactor: 1000,
    tr: { name: "Kilometre", slug: "kilometre" },
    en: { name: "Kilometer", slug: "kilometer" },
    de: { name: "Kilometer", slug: "kilometer" },
    enConversionSlug: "kilometers",
  },
  {
    id: "santimetre",
    category: "uzunluk",
    symbol: "cm",
    siFactor: 0.01,
    tr: { name: "Santimetre", slug: "santimetre" },
    en: { name: "Centimeter", slug: "centimeter" },
    de: { name: "Zentimeter", slug: "zentimeter" },
    enConversionSlug: "centimeters",
  },
  {
    id: "milimetre",
    category: "uzunluk",
    symbol: "mm",
    siFactor: 0.001,
    tr: { name: "Milimetre", slug: "milimetre" },
    en: { name: "Millimeter", slug: "millimeter" },
    de: { name: "Millimeter", slug: "millimeter" },
    enConversionSlug: "millimeters",
  },
  {
    id: "mikrometre",
    category: "uzunluk",
    symbol: "µm",
    siFactor: 0.000001,
    tr: { name: "Mikrometre", slug: "mikrometre" },
    en: { name: "Micrometer", slug: "micrometer" },
    de: { name: "Mikrometer", slug: "mikrometer" },
  },
  {
    id: "nanometre",
    category: "uzunluk",
    symbol: "nm",
    siFactor: 1e-9,
    tr: { name: "Nanometre", slug: "nanometre" },
    en: { name: "Nanometer", slug: "nanometer" },
    de: { name: "Nanometer", slug: "nanometer" },
  },
  {
    id: "fit",
    category: "uzunluk",
    symbol: "ft",
    siFactor: 0.3048,
    tr: { name: "Fit", slug: "fit" },
    en: { name: "Foot", slug: "foot" },
    de: { name: "Fuß", slug: "fuss" },
    enConversionSlug: "feet",
  },
  {
    id: "inc",
    category: "uzunluk",
    symbol: "in",
    siFactor: 0.0254,
    tr: { name: "İnç", slug: "inc" },
    en: { name: "Inch", slug: "inch" },
    de: { name: "Zoll", slug: "zoll" },
    enConversionSlug: "inches",
  },
  {
    id: "yarda",
    category: "uzunluk",
    symbol: "yd",
    siFactor: 0.9144,
    tr: { name: "Yarda", slug: "yarda" },
    en: { name: "Yard", slug: "yard" },
    de: { name: "Yard", slug: "yard" },
    enConversionSlug: "yards",
  },
  {
    id: "mil",
    category: "uzunluk",
    symbol: "mi",
    siFactor: 1609.344,
    tr: { name: "Mil", slug: "mil" },
    en: { name: "Mile", slug: "mile" },
    de: { name: "Meile", slug: "meile" },
    enConversionSlug: "miles",
  },
  {
    id: "deniz-mili",
    category: "uzunluk",
    symbol: "nmi",
    siFactor: 1852,
    tr: { name: "Deniz mili", slug: "deniz-mili" },
    en: { name: "Nautical mile", slug: "nautical-mile" },
    de: { name: "Seemeile", slug: "seemeile" },
  },

  // ---- alan / area / Fläche ----
  {
    id: "metrekare",
    category: "alan",
    symbol: "m²",
    siFactor: 1,
    tr: { name: "Metrekare", slug: "metrekare" },
    en: { name: "Square Meter", slug: "square-meter" },
    de: { name: "Quadratmeter", slug: "quadratmeter" },
    enConversionSlug: "square-meters",
  },
  {
    id: "santimetrekare",
    category: "alan",
    symbol: "cm²",
    siFactor: 0.0001,
    tr: { name: "Santimetrekare", slug: "santimetrekare" },
    en: { name: "Square Centimeter", slug: "square-centimeter" },
    de: { name: "Quadratzentimeter", slug: "quadratzentimeter" },
  },
  {
    id: "milimetrekare",
    category: "alan",
    symbol: "mm²",
    siFactor: 0.000001,
    tr: { name: "Milimetrekare", slug: "milimetrekare" },
    en: { name: "Square Millimeter", slug: "square-millimeter" },
    de: { name: "Quadratmillimeter", slug: "quadratmillimeter" },
  },
  {
    id: "kilometrekare",
    category: "alan",
    symbol: "km²",
    siFactor: 1_000_000,
    tr: { name: "Kilometrekare", slug: "kilometrekare" },
    en: { name: "Square Kilometer", slug: "square-kilometer" },
    de: { name: "Quadratkilometer", slug: "quadratkilometer" },
  },
  {
    id: "hektar",
    category: "alan",
    symbol: "ha",
    siFactor: 10_000,
    tr: { name: "Hektar", slug: "hektar" },
    en: { name: "Hectare", slug: "hectare" },
    de: { name: "Hektar", slug: "hektar" },
    enConversionSlug: "hectares",
  },
  {
    id: "fitkare",
    category: "alan",
    symbol: "ft²",
    siFactor: 0.092903,
    tr: { name: "Fitkare", slug: "fitkare" },
    en: { name: "Square Foot", slug: "square-foot" },
    de: { name: "Quadratfuß", slug: "quadratfuss" },
    enConversionSlug: "square-feet",
  },
  {
    id: "incare",
    category: "alan",
    symbol: "in²",
    siFactor: 0.00064516,
    tr: { name: "İnçkare", slug: "incare" },
    en: { name: "Square Inch", slug: "square-inch" },
    de: { name: "Quadratzoll", slug: "quadratzoll" },
  },
  {
    id: "akre",
    category: "alan",
    symbol: "ac",
    siFactor: 4046.8564224,
    tr: { name: "Akre", slug: "akre" },
    en: { name: "Acre", slug: "acre" },
    de: { name: "Acre", slug: "acre" },
  },

  // ---- hacim / volume / Volumen ----
  {
    id: "metrekup",
    category: "hacim",
    symbol: "m³",
    siFactor: 1,
    tr: { name: "Metreküp", slug: "metrekup" },
    en: { name: "Cubic Meter", slug: "cubic-meter" },
    de: { name: "Kubikmeter", slug: "kubikmeter" },
    enConversionSlug: "cubic-meters",
  },
  {
    id: "litre",
    category: "hacim",
    symbol: "L",
    siFactor: 0.001,
    tr: { name: "Litre", slug: "litre" },
    en: { name: "Liter", slug: "liter" },
    de: { name: "Liter", slug: "liter" },
    enConversionSlug: "liters",
  },
  {
    id: "mililitre",
    category: "hacim",
    symbol: "mL",
    siFactor: 0.000001,
    tr: { name: "Mililitre", slug: "mililitre" },
    en: { name: "Milliliter", slug: "milliliter" },
    de: { name: "Milliliter", slug: "milliliter" },
    enConversionSlug: "milliliters",
  },
  {
    id: "santimetrekup",
    category: "hacim",
    symbol: "cm³",
    siFactor: 0.000001,
    tr: { name: "Santimetreküp", slug: "santimetrekup" },
    en: { name: "Cubic Centimeter", slug: "cubic-centimeter" },
    de: { name: "Kubikzentimeter", slug: "kubikzentimeter" },
  },
  {
    id: "fitkup",
    category: "hacim",
    symbol: "ft³",
    siFactor: 0.0283168,
    tr: { name: "Fitküp", slug: "fitkup" },
    en: { name: "Cubic Foot", slug: "cubic-foot" },
    de: { name: "Kubikfuß", slug: "kubikfuss" },
  },
  {
    id: "inckup",
    category: "hacim",
    symbol: "in³",
    siFactor: 0.0000163871,
    tr: { name: "İnçküp", slug: "inckup" },
    en: { name: "Cubic Inch", slug: "cubic-inch" },
    de: { name: "Kubikzoll", slug: "kubikzoll" },
  },
  {
    id: "galon",
    category: "hacim",
    symbol: "gal",
    siFactor: 0.00378541,
    tr: { name: "Galon", slug: "galon" },
    en: { name: "Gallon", slug: "gallon" },
    de: { name: "Gallone", slug: "gallone" },
  },

  // ---- kutle / mass / Masse ----
  {
    id: "kilogram",
    category: "kutle",
    symbol: "kg",
    siFactor: 1,
    tr: { name: "Kilogram", slug: "kilogram" },
    en: { name: "Kilogram", slug: "kilogram" },
    de: { name: "Kilogramm", slug: "kilogramm" },
    enConversionSlug: "kilograms",
  },
  {
    id: "gram",
    category: "kutle",
    symbol: "g",
    siFactor: 0.001,
    tr: { name: "Gram", slug: "gram" },
    en: { name: "Gram", slug: "gram" },
    de: { name: "Gramm", slug: "gramm" },
    enConversionSlug: "grams",
  },
  {
    id: "miligram",
    category: "kutle",
    symbol: "mg",
    siFactor: 0.000001,
    tr: { name: "Miligram", slug: "miligram" },
    en: { name: "Milligram", slug: "milligram" },
    de: { name: "Milligramm", slug: "milligramm" },
    enConversionSlug: "milligrams",
  },
  {
    id: "ton",
    category: "kutle",
    symbol: "ton",
    displaySymbol: "t",
    siFactor: 1000,
    tr: { name: "Ton", slug: "ton" },
    en: { name: "Tonne", slug: "tonne" },
    de: { name: "Tonne", slug: "tonne" },
    enConversionSlug: "tonnes",
  },
  {
    id: "pound",
    category: "kutle",
    symbol: "lb",
    siFactor: 0.45359237,
    tr: { name: "Pound", slug: "pound" },
    en: { name: "Pound", slug: "pound" },
    de: { name: "Pfund", slug: "pfund" },
    enConversionSlug: "pounds",
  },
  {
    id: "ons",
    category: "kutle",
    symbol: "oz",
    siFactor: 0.028349523125,
    tr: { name: "Ons", slug: "ons" },
    en: { name: "Ounce", slug: "ounce" },
    de: { name: "Unze", slug: "unze" },
    enConversionSlug: "ounces",
  },

  // ---- yoğunluk / density (engine-only, no public pages) ----
  {
    id: "kg-m3",
    category: "yogunluk",
    symbol: "kg/m³",
    siFactor: 1,
    tr: { name: "Kilogram/Metreküp", slug: "kilogram-metrekup" },
    en: { name: "Kilogram per Cubic Meter", slug: "kilogram-per-cubic-meter" },
    de: { name: "Kilogramm/Kubikmeter", slug: "kilogramm-kubikmeter" },
  },
  {
    id: "g-cm3",
    category: "yogunluk",
    symbol: "g/cm³",
    siFactor: 1000,
    tr: { name: "Gram/Santimetreküp", slug: "gram-santimetrekup" },
    en: { name: "Gram per Cubic Centimeter", slug: "gram-per-cubic-centimeter" },
    de: { name: "Gramm/Kubikzentimeter", slug: "gramm-kubikzentimeter" },
  },
  { id: "g-ml", category: "yogunluk", symbol: "g/mL", siFactor: 1000 },
  { id: "kg-l", category: "yogunluk", symbol: "kg/L", siFactor: 1000 },
  { id: "g-l", category: "yogunluk", symbol: "g/L", siFactor: 1 },
  { id: "mg-l", category: "yogunluk", symbol: "mg/L", siFactor: 0.001 },
  { id: "lb-ft3", category: "yogunluk", symbol: "lb/ft³", siFactor: 16.01846337 },
  { id: "lb-in3", category: "yogunluk", symbol: "lb/in³", siFactor: 27679.90471 },
  { id: "lb-gal-us", category: "yogunluk", symbol: "lb/gal (US)", siFactor: 119.826427 },
  { id: "slug-ft3", category: "yogunluk", symbol: "slug/ft³", siFactor: 515.378818 },

  // ---- hız / speed / Geschwindigkeit ----
  {
    id: "metre-saniye",
    category: "hiz",
    symbol: "m/s",
    siFactor: 1,
    tr: { name: "Metre/Saniye", slug: "metre-saniye" },
    en: { name: "Meter per Second", slug: "meter-per-second" },
    de: { name: "Meter pro Sekunde", slug: "meter-pro-sekunde" },
    enConversionSlug: "meters-per-second",
  },
  {
    id: "kilometre-saat",
    category: "hiz",
    symbol: "km/h",
    siFactor: 1000 / 3600,
    tr: { name: "Kilometre/Saat", slug: "kilometre-saat" },
    en: { name: "Kilometer per Hour", slug: "kilometer-per-hour" },
    de: { name: "Kilometer pro Stunde", slug: "kilometer-pro-stunde" },
    enConversionSlug: "kilometers-per-hour",
  },
  { id: "km-s", category: "hiz", symbol: "km/s", siFactor: 1000 },
  {
    id: "mil-saat",
    category: "hiz",
    symbol: "mph",
    siFactor: 1609.344 / 3600,
    tr: { name: "Mil/Saat", slug: "mil-saat" },
    en: { name: "Mile per Hour", slug: "mile-per-hour" },
    de: { name: "Meilen pro Stunde", slug: "meilen-pro-stunde" },
    enConversionSlug: "miles-per-hour",
  },
  { id: "knot", category: "hiz", symbol: "knot", siFactor: 1852 / 3600 },
  { id: "ft-s", category: "hiz", symbol: "ft/s", siFactor: 0.3048 },
  { id: "m-min", category: "hiz", symbol: "m/min", siFactor: 1 / 60 },
  { id: "km-min", category: "hiz", symbol: "km/min", siFactor: 1000 / 60 },
  { id: "cm-s", category: "hiz", symbol: "cm/s", siFactor: 0.01 },
  { id: "isik-hizi", category: "hiz", symbol: "c", siFactor: 299792458 },

  // ---- ivme / acceleration (engine-only) ----
  { id: "m-s2", category: "ivme", symbol: "m/s²", siFactor: 1 },
  { id: "cm-s2", category: "ivme", symbol: "cm/s²", siFactor: 0.01 },
  { id: "mm-s2", category: "ivme", symbol: "mm/s²", siFactor: 0.001 },
  { id: "km-s2", category: "ivme", symbol: "km/s²", siFactor: 1000 },
  { id: "ft-s2", category: "ivme", symbol: "ft/s²", siFactor: 0.3048 },
  { id: "in-s2", category: "ivme", symbol: "in/s²", siFactor: 0.0254 },
  { id: "m-min2", category: "ivme", symbol: "m/min²", siFactor: 1 / 3600 },
  { id: "ft-min2", category: "ivme", symbol: "ft/min²", siFactor: 0.3048 / 3600 },
  { id: "ivme-gal", category: "ivme", symbol: "gal", siFactor: 0.01 },
  { id: "g0", category: "ivme", symbol: "g0", siFactor: 9.80665 },

  // ---- zaman / time / Zeit ----
  {
    id: "saniye",
    category: "zaman",
    symbol: "s",
    siFactor: 1,
    tr: { name: "Saniye", slug: "saniye" },
    en: { name: "Second", slug: "second" },
    de: { name: "Sekunde", slug: "sekunde" },
    enConversionSlug: "seconds",
  },
  { id: "milisaniye", category: "zaman", symbol: "ms", siFactor: 0.001 },
  {
    id: "dakika",
    category: "zaman",
    symbol: "min",
    siFactor: 60,
    tr: { name: "Dakika", slug: "dakika" },
    en: { name: "Minute", slug: "minute" },
    de: { name: "Minute", slug: "minute" },
    enConversionSlug: "minutes",
  },
  {
    id: "saat",
    category: "zaman",
    symbol: "h",
    siFactor: 3600,
    tr: { name: "Saat", slug: "saat" },
    en: { name: "Hour", slug: "hour" },
    de: { name: "Stunde", slug: "stunde" },
    enConversionSlug: "hours",
  },
  { id: "gun", category: "zaman", symbol: "day", siFactor: 86400 },

  // ---- açısal hız (engine-only) ----
  { id: "rad-s", category: "acisal_hiz", symbol: "rad/s", siFactor: 1 },
  { id: "rad-min", category: "acisal_hiz", symbol: "rad/min", siFactor: 1 / 60 },
  { id: "rad-h", category: "acisal_hiz", symbol: "rad/h", siFactor: 1 / 3600 },
  { id: "rpm", category: "acisal_hiz", symbol: "rpm", siFactor: (2 * Math.PI) / 60 },
  { id: "hz", category: "acisal_hiz", symbol: "Hz", siFactor: 2 * Math.PI },
  { id: "deg-s", category: "acisal_hiz", symbol: "°/s", siFactor: Math.PI / 180 },
  { id: "deg-min", category: "acisal_hiz", symbol: "°/min", siFactor: Math.PI / (180 * 60) },
  { id: "deg-h", category: "acisal_hiz", symbol: "°/h", siFactor: Math.PI / (180 * 3600) },

  // ---- kuvvet / tork / momentum (engine-only) ----
  {
    id: "newton",
    category: "kuvvet",
    symbol: "N",
    siFactor: 1,
    tr: { name: "Newton", slug: "newton" },
    en: { name: "Newton", slug: "newton" },
    de: { name: "Newton", slug: "newton" },
  },
  { id: "kilonewton", category: "kuvvet", symbol: "kN", siFactor: 1000 },
  { id: "dyn", category: "kuvvet", symbol: "dyn", siFactor: 0.00001 },
  { id: "lbf", category: "kuvvet", symbol: "lbf", siFactor: 4.4482216 },
  {
    id: "kilogram-kuvvet",
    category: "kuvvet",
    symbol: "kgf",
    siFactor: 9.80665,
    tr: { name: "Kilogram-kuvvet", slug: "kilogram-kuvvet" },
    en: { name: "Kilogram-Force", slug: "kilogram-force" },
    de: { name: "Kilogramm-Kraft", slug: "kilogramm-kraft" },
  },
  {
    id: "newton-metre",
    category: "tork",
    symbol: "N·m",
    siFactor: 1,
    tr: { name: "Newton-metre", slug: "newton-metre" },
    en: { name: "Newton-Meter", slug: "newton-meter" },
    de: { name: "Newtonmeter", slug: "newtonmeter" },
  },
  { id: "kilonewton-metre", category: "tork", symbol: "kN·m", siFactor: 1000 },
  {
    id: "lb-ft",
    category: "tork",
    symbol: "lb·ft",
    siFactor: 1.355817948,
    tr: { name: "Pound-fit (lb-ft)", slug: "pound-fit" },
    en: { name: "Pound-Foot", slug: "pound-foot" },
    de: { name: "Pfund-Fuß", slug: "pfund-fuss" },
  },
  {
    id: "kg-m-s",
    category: "momentum",
    symbol: "kg·m/s",
    siFactor: 1,
    tr: { name: "Kilogram-metre/saniye", slug: "kilogram-metre-saniye" },
    en: { name: "Kilogram-Meter per Second", slug: "kilogram-meter-per-second" },
    de: { name: "Kilogramm-Meter/Sekunde", slug: "kilogramm-meter-sekunde" },
  },
  {
    id: "n-s",
    category: "momentum",
    symbol: "N·s",
    siFactor: 1,
    tr: { name: "Newton-saniye", slug: "newton-saniye" },
    en: { name: "Newton-Second", slug: "newton-second" },
    de: { name: "Newtonsekunde", slug: "newtonsekunde" },
  },
  { id: "lb-ft-s", category: "momentum", symbol: "lb·ft/s", siFactor: 0.138255 },

  // ---- basınç / pressure / Druck ----
  {
    id: "pascal",
    category: "basinc",
    symbol: "Pa",
    siFactor: 1,
    tr: { name: "Pascal", slug: "pascal" },
    en: { name: "Pascal", slug: "pascal" },
    de: { name: "Pascal", slug: "pascal" },
    enConversionSlug: "pascals",
  },
  {
    id: "kilopascal",
    category: "basinc",
    symbol: "kPa",
    siFactor: 1000,
    tr: { name: "Kilopascal", slug: "kilopascal" },
    en: { name: "Kilopascal", slug: "kilopascal" },
    de: { name: "Kilopascal", slug: "kilopascal" },
    enConversionSlug: "kilopascals",
  },
  {
    id: "bar",
    category: "basinc",
    symbol: "bar",
    siFactor: 100000,
    tr: { name: "Bar", slug: "bar" },
    en: { name: "Bar", slug: "bar" },
    de: { name: "Bar", slug: "bar" },
    enConversionSlug: "bars",
  },
  { id: "milibar", category: "basinc", symbol: "mbar", siFactor: 100 },
  {
    id: "atmosfer",
    category: "basinc",
    symbol: "atm",
    siFactor: 101325,
    tr: { name: "Atmosfer", slug: "atmosfer" },
    en: { name: "Atmosphere", slug: "atmosphere" },
    de: { name: "Atmosphäre", slug: "atmosphaere" },
    enConversionSlug: "atmospheres",
  },
  { id: "teknik-atmosfer", category: "basinc", symbol: "at", siFactor: 98066.5 },
  {
    id: "psi",
    category: "basinc",
    symbol: "psi",
    siFactor: 6894.757293168,
    tr: { name: "PSI", slug: "psi" },
    en: { name: "PSI", slug: "psi" },
    de: { name: "PSI", slug: "psi" },
    enConversionSlug: "psi",
  },
  {
    id: "milimetre-civa",
    category: "basinc",
    symbol: "mmHg",
    siFactor: 133.322387415,
    tr: { name: "Milimetre Cıva", slug: "milimetre-civa" },
    en: { name: "Millimeter of Mercury", slug: "millimeter-of-mercury" },
    de: { name: "Millimeter Quecksilbersäule", slug: "millimeter-quecksilbersaeule" },
    enConversionSlug: "millimeters-of-mercury",
  },
  { id: "mmh2o", category: "basinc", symbol: "mmH2O", siFactor: 9.80665 },
  {
    id: "kilogram-kuvvet-santimetrekare",
    category: "basinc",
    symbol: "kgf/cm²",
    siFactor: 98066.5,
    tr: { name: "Kilogram-kuvvet/Santimetrekare", slug: "kilogram-kuvvet-santimetrekare" },
    en: {
      name: "Kilogram-Force per Square Centimeter",
      slug: "kilogram-force-per-square-centimeter",
    },
    de: {
      name: "Kilogramm-Kraft pro Quadratzentimeter",
      slug: "kilogramm-kraft-pro-quadratzentimeter",
    },
    enConversionSlug: "kilogram-force-per-square-centimeter",
  },

  // ---- viskozite (engine-only) ----
  {
    id: "pascal-saniye",
    category: "viskozite_dinamik",
    symbol: "Pa·s",
    siFactor: 1,
    tr: { name: "Pascal-saniye", slug: "pascal-saniye" },
    en: { name: "Pascal-Second", slug: "pascal-second" },
    de: { name: "Pascalsekunde", slug: "pascalsekunde" },
  },
  { id: "milipascal-saniye", category: "viskozite_dinamik", symbol: "mPa·s", siFactor: 0.001 },
  { id: "poise", category: "viskozite_dinamik", symbol: "P", siFactor: 0.1 },
  {
    id: "centipoise",
    category: "viskozite_dinamik",
    symbol: "cP",
    siFactor: 0.001,
    tr: { name: "Santipoise", slug: "santipoise" },
    en: { name: "Centipoise", slug: "centipoise" },
    de: { name: "Centipoise", slug: "centipoise" },
  },
  { id: "m2-s", category: "viskozite_kinematik", symbol: "m²/s", siFactor: 1 },
  { id: "mm2-s", category: "viskozite_kinematik", symbol: "mm²/s", siFactor: 0.000001 },
  { id: "centistoke", category: "viskozite_kinematik", symbol: "cSt", siFactor: 0.000001 },

  // ---- debi_hacimsel / debi_kutlesel (engine-only) ----
  { id: "m3-s", category: "debi_hacimsel", symbol: "m³/s", siFactor: 1 },
  { id: "l-s", category: "debi_hacimsel", symbol: "L/s", siFactor: 0.001 },
  { id: "m3-h-hacimsel", category: "debi_hacimsel", symbol: "m³/h", siFactor: 1 / 3600 },
  { id: "l-min-hacimsel", category: "debi_hacimsel", symbol: "L/min", siFactor: 0.001 / 60 },
  { id: "cfm", category: "debi_hacimsel", symbol: "cfm", siFactor: 0.0283168 / 60 },
  { id: "gpm", category: "debi_hacimsel", symbol: "gpm", siFactor: 0.00378541 / 60 },
  { id: "kg-s", category: "debi_kutlesel", symbol: "kg/s", siFactor: 1 },
  { id: "kg-h", category: "debi_kutlesel", symbol: "kg/h", siFactor: 1 / 3600 },
  { id: "g-s", category: "debi_kutlesel", symbol: "g/s", siFactor: 0.001 },
  { id: "g-h", category: "debi_kutlesel", symbol: "g/h", siFactor: 0.001 / 3600 },

  // ---- enerji / energy / Energie ----
  {
    id: "joule",
    category: "enerji",
    symbol: "J",
    siFactor: 1,
    tr: { name: "Joule", slug: "joule" },
    en: { name: "Joule", slug: "joule" },
    de: { name: "Joule", slug: "joule" },
    enConversionSlug: "joules",
  },
  { id: "kilojoule", category: "enerji", symbol: "kJ", siFactor: 1000 },
  { id: "megajoule", category: "enerji", symbol: "MJ", siFactor: 1_000_000 },
  { id: "watt-saat", category: "enerji", symbol: "Wh", siFactor: 3600 },
  {
    id: "kilovatsaat",
    category: "enerji",
    symbol: "kWh",
    siFactor: 3_600_000,
    tr: { name: "Kilovat-saat", slug: "kilovatsaat" },
    en: { name: "Kilowatt-hour", slug: "kilowatt-hour" },
    de: { name: "Kilowattstunde", slug: "kilowattstunde" },
    enConversionSlug: "kilowatt-hours",
  },
  {
    id: "watt",
    category: "enerji",
    symbol: "W",
    siFactor: 1,
    tr: { name: "Watt", slug: "watt" },
    en: { name: "Watt", slug: "watt" },
    de: { name: "Watt", slug: "watt" },
    enConversionSlug: "watts",
  },
  {
    id: "kilowatt",
    category: "enerji",
    symbol: "kW",
    siFactor: 1000,
    tr: { name: "Kilowatt", slug: "kilowatt" },
    en: { name: "Kilowatt", slug: "kilowatt" },
    de: { name: "Kilowatt", slug: "kilowatt" },
    enConversionSlug: "kilowatts",
  },
  { id: "kalori", category: "enerji", symbol: "cal", siFactor: 4.184 },
  { id: "kilokalori", category: "enerji", symbol: "kcal", siFactor: 4184 },
  { id: "btu", category: "enerji", symbol: "Btu", siFactor: 1055.056 },
  { id: "therm", category: "enerji", symbol: "th", siFactor: 1.05506e8 },
  { id: "quad-btu", category: "enerji", symbol: "quad BTU", siFactor: 1.05506e18 },

  // ---- güç (engine-only, separate from enerji's W/kW) ----
  { id: "guc-watt", category: "guc", symbol: "W", siFactor: 1 },
  { id: "guc-kilowatt", category: "guc", symbol: "kW", siFactor: 1000 },
  { id: "megawatt", category: "guc", symbol: "MW", siFactor: 1_000_000 },
  {
    id: "beygirgucu-metric",
    category: "enerji",
    symbol: "hp",
    siFactor: 735.49875,
    tr: { name: "Beygirgücü", slug: "beygirgucu" },
    en: { name: "Horsepower", slug: "horsepower" },
    de: { name: "PS", slug: "ps" },
  },
  { id: "beygirgucu-mechanical", category: "guc", symbol: "HP", siFactor: 745.7 },
  { id: "cheval-vapeur", category: "guc", symbol: "CV", siFactor: 735.49875 },

  // ---- sıcaklık / temperature / Temperatur (non-linear, no siFactor) ----
  {
    id: "santigrat",
    category: "sicaklik",
    symbol: "C",
    displaySymbol: "°C",
    isTemperature: true,
    tr: { name: "Santigrat", slug: "santigrat" },
    en: { name: "Celsius", slug: "celsius" },
    de: { name: "Celsius", slug: "celsius" },
    enConversionSlug: "celsius",
  },
  {
    id: "fahrenhayt",
    category: "sicaklik",
    symbol: "F",
    displaySymbol: "°F",
    isTemperature: true,
    tr: { name: "Fahrenheit", slug: "fahrenhayt" },
    en: { name: "Fahrenheit", slug: "fahrenheit" },
    de: { name: "Fahrenheit", slug: "fahrenheit" },
    enConversionSlug: "fahrenheit",
  },
  {
    id: "kelvin",
    category: "sicaklik",
    symbol: "K",
    isTemperature: true,
    tr: { name: "Kelvin", slug: "kelvin" },
    en: { name: "Kelvin", slug: "kelvin" },
    de: { name: "Kelvin", slug: "kelvin" },
    enConversionSlug: "kelvin",
  },

  // ---- ısıl iletkenlik / ısı akısı / özgül ısı (engine-only) ----
  { id: "w-mk", category: "isil_iletkenlik", symbol: "W/m·K", siFactor: 1 },
  { id: "kw-mk", category: "isil_iletkenlik", symbol: "kW/m·K", siFactor: 1000 },
  { id: "w-cmk", category: "isil_iletkenlik", symbol: "W/cm·K", siFactor: 100 },
  { id: "btu-hftf", category: "isil_iletkenlik", symbol: "Btu/h·ft·°F", siFactor: 1.730735 },
  { id: "w-m2", category: "isi_akisi", symbol: "W/m²", siFactor: 1 },
  { id: "kw-m2", category: "isi_akisi", symbol: "kW/m²", siFactor: 1000 },
  { id: "cal-cm2s", category: "isi_akisi", symbol: "cal/cm²·s", siFactor: 41840 },
  { id: "j-kgk", category: "ozgul_isi", symbol: "J/kg·K", siFactor: 1 },
  { id: "kj-kgk", category: "ozgul_isi", symbol: "kJ/kg·K", siFactor: 1000 },
  { id: "cal-gk", category: "ozgul_isi", symbol: "cal/g·K", siFactor: 4.184 },
  { id: "btu-lbf", category: "ozgul_isi", symbol: "Btu/lb·°F", siFactor: 4186.8 },

  // ---- debi / elektrik ("core" categories, distinct from *_hacimsel/*_kutlesel/*_gerilim/*_akim) ----
  {
    id: "metrekup-saat",
    category: "debi",
    symbol: "m³/h",
    siFactor: 1 / 3600,
    tr: { name: "Metreküp/Saat", slug: "metrekup-saat" },
    en: { name: "Cubic Meter per Hour", slug: "cubic-meter-per-hour" },
    de: { name: "Kubikmeter pro Stunde", slug: "kubikmeter-pro-stunde" },
    enConversionSlug: "cubic-meters-per-hour",
  },
  {
    id: "litre-dakika",
    category: "debi",
    symbol: "L/min",
    siFactor: 0.001 / 60,
    tr: { name: "Litre/Dakika", slug: "litre-dakika" },
    en: { name: "Liter per Minute", slug: "liter-per-minute" },
    de: { name: "Liter pro Minute", slug: "liter-pro-minute" },
    enConversionSlug: "liters-per-minute",
  },
  {
    id: "volt",
    category: "elektrik",
    symbol: "V",
    siFactor: 1,
    tr: { name: "Volt", slug: "volt" },
    en: { name: "Volt", slug: "volt" },
    de: { name: "Volt", slug: "volt" },
    enConversionSlug: "volts",
  },
  {
    id: "kilovolt",
    category: "elektrik",
    symbol: "kV",
    siFactor: 1000,
    tr: { name: "Kilovolt", slug: "kilovolt" },
    en: { name: "Kilovolt", slug: "kilovolt" },
    de: { name: "Kilovolt", slug: "kilovolt" },
    enConversionSlug: "kilovolts",
  },
  {
    id: "amper",
    category: "elektrik",
    symbol: "A",
    siFactor: 1,
    tr: { name: "Amper", slug: "amper" },
    en: { name: "Ampere", slug: "ampere" },
    de: { name: "Ampere", slug: "ampere" },
    enConversionSlug: "amperes",
  },
  {
    id: "miliamper",
    category: "elektrik",
    symbol: "mA",
    siFactor: 0.001,
    tr: { name: "Miliamper", slug: "miliamper" },
    en: { name: "Milliampere", slug: "milliampere" },
    de: { name: "Milliampere", slug: "milliampere" },
    enConversionSlug: "milliamperes",
  },

  // ---- elektrik_direnc / gerilim / akım / kapasitans / enduktans / yük / manyetik (engine-only) ----
  {
    id: "ohm",
    category: "elektrik_direnc",
    symbol: "Ω",
    siFactor: 1,
    tr: { name: "Ohm", slug: "ohm" },
    en: { name: "Ohm", slug: "ohm" },
    de: { name: "Ohm", slug: "ohm" },
  },
  {
    id: "kiloohm",
    category: "elektrik_direnc",
    symbol: "kΩ",
    siFactor: 1000,
    tr: { name: "Kiloohm", slug: "kiloohm" },
    en: { name: "Kiloohm", slug: "kiloohm" },
    de: { name: "Kiloohm", slug: "kiloohm" },
  },
  {
    id: "megaohm",
    category: "elektrik_direnc",
    symbol: "MΩ",
    siFactor: 1_000_000,
    tr: { name: "Megaohm", slug: "megaohm" },
    en: { name: "Megaohm", slug: "megaohm" },
    de: { name: "Megaohm", slug: "megaohm" },
  },
  { id: "gerilim-volt", category: "elektrik_gerilim", symbol: "V", siFactor: 1 },
  { id: "gerilim-kilovolt", category: "elektrik_gerilim", symbol: "kV", siFactor: 1000 },
  { id: "milivolt", category: "elektrik_gerilim", symbol: "mV", siFactor: 0.001 },
  { id: "akim-amper", category: "elektrik_akim", symbol: "A", siFactor: 1 },
  { id: "akim-miliamper", category: "elektrik_akim", symbol: "mA", siFactor: 0.001 },
  { id: "kiloamper", category: "elektrik_akim", symbol: "kA", siFactor: 1000 },
  {
    id: "farad",
    category: "kapasitans",
    symbol: "F",
    siFactor: 1,
    tr: { name: "Farad", slug: "farad" },
    en: { name: "Farad", slug: "farad" },
    de: { name: "Farad", slug: "farad" },
  },
  {
    id: "milifarad",
    category: "kapasitans",
    symbol: "mF",
    siFactor: 0.001,
    tr: { name: "Milifarad", slug: "milifarad" },
    en: { name: "Millifarad", slug: "millifarad" },
    de: { name: "Millifarad", slug: "millifarad" },
  },
  {
    id: "mikrofarad",
    category: "kapasitans",
    symbol: "µF",
    siFactor: 0.000001,
    tr: { name: "Mikrofarad", slug: "mikrofarad" },
    en: { name: "Microfarad", slug: "microfarad" },
    de: { name: "Mikrofarad", slug: "mikrofarad" },
  },
  {
    id: "nanofarad",
    category: "kapasitans",
    symbol: "nF",
    siFactor: 1e-9,
    tr: { name: "Nanofarad", slug: "nanofarad" },
    en: { name: "Nanofarad", slug: "nanofarad" },
    de: { name: "Nanofarad", slug: "nanofarad" },
  },
  {
    id: "pikofarad",
    category: "kapasitans",
    symbol: "pF",
    siFactor: 1e-12,
    tr: { name: "Pikofarad", slug: "pikofarad" },
    en: { name: "Picofarad", slug: "picofarad" },
    de: { name: "Pikofarad", slug: "pikofarad" },
  },
  {
    id: "henry",
    category: "enduktans",
    symbol: "H",
    siFactor: 1,
    tr: { name: "Henry", slug: "henry" },
    en: { name: "Henry", slug: "henry" },
    de: { name: "Henry", slug: "henry" },
  },
  {
    id: "milihenry",
    category: "enduktans",
    symbol: "mH",
    siFactor: 0.001,
    tr: { name: "Milihenry", slug: "milihenry" },
    en: { name: "Millihenry", slug: "millihenry" },
    de: { name: "Millihenry", slug: "millihenry" },
  },
  {
    id: "mikrohenry",
    category: "enduktans",
    symbol: "µH",
    siFactor: 0.000001,
    tr: { name: "Mikrohenry", slug: "mikrohenry" },
    en: { name: "Microhenry", slug: "microhenry" },
    de: { name: "Mikrohenry", slug: "mikrohenry" },
  },
  {
    id: "coulomb",
    category: "elektrik_yuk",
    symbol: "C",
    siFactor: 1,
    tr: { name: "Coulomb", slug: "coulomb" },
    en: { name: "Coulomb", slug: "coulomb" },
    de: { name: "Coulomb", slug: "coulomb" },
  },
  {
    id: "milicoulomb",
    category: "elektrik_yuk",
    symbol: "mC",
    siFactor: 0.001,
    tr: { name: "Milicoulomb", slug: "milicoulomb" },
    en: { name: "Millicoulomb", slug: "millicoulomb" },
    de: { name: "Millicoulomb", slug: "millicoulomb" },
  },
  {
    id: "mikrocoulomb",
    category: "elektrik_yuk",
    symbol: "µC",
    siFactor: 0.000001,
    tr: { name: "Mikrocoulomb", slug: "mikrocoulomb" },
    en: { name: "Microcoulomb", slug: "microcoulomb" },
    de: { name: "Mikrocoulomb", slug: "mikrocoulomb" },
  },
  {
    id: "nanocoulomb",
    category: "elektrik_yuk",
    symbol: "nC",
    siFactor: 1e-9,
    tr: { name: "Nanocoulomb", slug: "nanocoulomb" },
    en: { name: "Nanocoulomb", slug: "nanocoulomb" },
    de: { name: "Nanocoulomb", slug: "nanocoulomb" },
  },
  { id: "a-m", category: "manyetik_alan", symbol: "A/m", siFactor: 1 },
  { id: "ka-m", category: "manyetik_alan", symbol: "kA/m", siFactor: 1000 },
  { id: "oersted", category: "manyetik_alan", symbol: "Oe", siFactor: 79.5775 },
  { id: "weber", category: "manyetik_aki", symbol: "Wb", siFactor: 1 },
  { id: "miliweber", category: "manyetik_aki", symbol: "mWb", siFactor: 0.001 },
  { id: "mikroweber", category: "manyetik_aki", symbol: "µWb", siFactor: 0.000001 },
  { id: "nanoweber", category: "manyetik_aki", symbol: "nWb", siFactor: 1e-9 },
  { id: "weber-alias", category: "manyetik_aki", symbol: "weber", siFactor: 1 },

  // ---- veri / digital storage ----
  {
    id: "bit",
    category: "veri",
    symbol: "bit",
    siFactor: 0.125,
    tr: { name: "Bit", slug: "bit" },
    en: { name: "Bit", slug: "bit" },
    de: { name: "Bit", slug: "bit" },
  },
  {
    id: "bayt",
    category: "veri",
    symbol: "B",
    siFactor: 1,
    tr: { name: "Bayt", slug: "bayt" },
    en: { name: "Byte", slug: "byte" },
    de: { name: "Byte", slug: "byte" },
  },
  {
    id: "kilobayt",
    category: "veri",
    symbol: "KB",
    siFactor: 1000,
    tr: { name: "Kilobayt", slug: "kilobayt" },
    en: { name: "Kilobyte", slug: "kilobyte" },
    de: { name: "Kilobyte", slug: "kilobyte" },
  },
  {
    id: "megabayt",
    category: "veri",
    symbol: "MB",
    siFactor: 1_000_000,
    tr: { name: "Megabayt", slug: "megabayt" },
    en: { name: "Megabyte", slug: "megabyte" },
    de: { name: "Megabyte", slug: "megabyte" },
  },
  {
    id: "gigabayt",
    category: "veri",
    symbol: "GB",
    siFactor: 1_000_000_000,
    tr: { name: "Gigabayt", slug: "gigabayt" },
    en: { name: "Gigabyte", slug: "gigabyte" },
    de: { name: "Gigabyte", slug: "gigabyte" },
  },
  {
    id: "terabayt",
    category: "veri",
    symbol: "TB",
    siFactor: 1_000_000_000_000,
    tr: { name: "Terabayt", slug: "terabayt" },
    en: { name: "Terabyte", slug: "terabyte" },
    de: { name: "Terabyte", slug: "terabyte" },
  },
  {
    id: "petabayt",
    category: "veri",
    symbol: "PB",
    siFactor: 1_000_000_000_000_000,
    tr: { name: "Petabayt", slug: "petabayt" },
    en: { name: "Petabyte", slug: "petabyte" },
    de: { name: "Petabyte", slug: "petabyte" },
  },
  {
    id: "kibibayt",
    category: "veri",
    symbol: "KiB",
    siFactor: 1024,
    tr: { name: "Kibibayt", slug: "kibibayt" },
    en: { name: "Kibibyte", slug: "kibibyte" },
    de: { name: "Kibibyte", slug: "kibibyte" },
  },
  {
    id: "mebibayt",
    category: "veri",
    symbol: "MiB",
    siFactor: 1024 ** 2,
    tr: { name: "Mebibayt", slug: "mebibayt" },
    en: { name: "Mebibyte", slug: "mebibyte" },
    de: { name: "Mebibyte", slug: "mebibyte" },
  },
  {
    id: "gibibayt",
    category: "veri",
    symbol: "GiB",
    siFactor: 1024 ** 3,
    tr: { name: "Gibibayt", slug: "gibibayt" },
    en: { name: "Gibibyte", slug: "gibibyte" },
    de: { name: "Gibibyte", slug: "gibibyte" },
  },
  {
    id: "tebibayt",
    category: "veri",
    symbol: "TiB",
    siFactor: 1024 ** 4,
    tr: { name: "Tebibayt", slug: "tebibayt" },
    en: { name: "Tebibyte", slug: "tebibyte" },
    de: { name: "Tebibyte", slug: "tebibyte" },
  },
];

export function findUnit(category: string, symbol: string) {
  return unitRegistry.find(
    (unit) => unit.category === category && unit.symbol === symbol
  );
}

export function getUnitsForCategory(category: string) {
  return unitRegistry.filter((unit) => unit.category === category);
}

export function getUnitCategories() {
  return Array.from(new Set(unitRegistry.map((unit) => unit.category)));
}
