import { unitRegistry } from "./unitRegistry";

export type UnitPage = {
  slug: string;
  category: string;
  unit: string;
  name: string;
  symbol: string;
  shortDescription: string;
  historySummary: string;
  measurementSystem: string;
  siEquivalent: string;
  commonUses: string;
};

type UnitDescription = {
  shortDescription: string;
  historySummary: string;
  measurementSystem: string;
  siEquivalent: string;
  commonUses: string;
};

const unitDescriptions: Record<string, UnitDescription> = {
  "metre": {
    shortDescription: "Metre, Uluslararası Birim Sistemi'nde uzunluğun temel birimidir. Günlük yaşamdan mühendisliğe kadar mesafe ve boyut ölçümünde kullanılır.",
    historySummary: "Metre, 18. yüzyılın sonunda evrensel bir ölçü standardı oluşturma amacıyla geliştirildi. Günümüzde tanımı ışığın boşlukta belirli bir zaman aralığında aldığı yola dayanır.",
    measurementSystem: "Uluslararası Birim Sistemi (SI)",
    siEquivalent: "Temel SI uzunluk birimi",
    commonUses: "İnşaat, bilim, üretim, geometri ve genel ölçüm",
  },
  "kilometre": {
    shortDescription: "Kilometre, 1000 metreye eşit bir uzunluk birimidir. Şehirler arası ve coğrafi mesafeleri ifade etmekte kullanılır.",
    historySummary: "Kilometre, metrik sistemin ondalık yapısı içinde metrenin katı olarak yerleşti. Kara yolları ve harita ölçeklerinde standart bir gösterim hâline geldi.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, kat birim)",
    siEquivalent: "1 km = 1000 m",
    commonUses: "Karayolu mesafeleri, coğrafya, haritacılık ve altyapı",
  },
  "santimetre": {
    shortDescription: "Santimetre, metrenin yüzde birine eşit bir uzunluk birimidir. Küçük nesnelerin ve günlük ölçülerin ifade edilmesinde yaygındır.",
    historySummary: "Santimetre, metrik sistemde ondalık alt birim olarak gelişti. Ölçümleri pratik ve hızlı hesaplanabilir hâle getirdiği için geniş kullanım kazandı.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, alt birim)",
    siEquivalent: "1 cm = 0,01 m",
    commonUses: "Mobilya, tekstil, antropometri ve günlük ölçümler",
  },
  "milimetre": {
    shortDescription: "Milimetre, metrenin binde birine eşit bir uzunluk birimidir. Hassas teknik ölçümlerde sık kullanılır.",
    historySummary: "Milimetre, sanayi ve mühendislikte daha küçük toleransların ölçülmesi ihtiyacıyla yaygınlaştı. Özellikle üretim ve çizim standartlarında temel bir alt birim oldu.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, alt birim)",
    siEquivalent: "1 mm = 0,001 m",
    commonUses: "Mekanik üretim, teknik resim, işleme toleransları",
  },
  "fit": {
    shortDescription: "Fit, İngiliz ve Amerikan ölçü sistemlerinde kullanılan bir uzunluk birimidir. Bir uluslararası fit tam olarak 0,3048 metreye eşittir.",
    historySummary: "Fit, eski ölçü geleneklerinde insan ayağına dayalı bir yaklaşımdan doğdu. Farklı bölgesel değerler zamanla bırakıldı ve uluslararası fit 1959'da standartlaştırıldı.",
    measurementSystem: "İngiliz ve ABD ölçü sistemleri",
    siEquivalent: "1 ft = 0,3048 m",
    commonUses: "Mimarlık, bina kotları, havacılık ve saha ölçüleri",
  },
  "inc": {
    shortDescription: "İnç, İngiliz ve Amerikan ölçü sistemlerinde kullanılan kısa bir uzunluk birimidir. Bir inç tam olarak 2,54 santimetreye eşittir.",
    historySummary: "İnç, tarih boyunca insan bedenine dayalı yerel ölçülerden türedi. Modern uluslararası inç 1959 yılından beri tam olarak 25,4 milimetre olarak tanımlanır.",
    measurementSystem: "İngiliz ve ABD ölçü sistemleri",
    siEquivalent: "1 in = 25,4 mm = 2,54 cm",
    commonUses: "Ekran boyutları, borulama, bağlantı elemanları ve teknik kataloglar",
  },
  "yarda": {
    shortDescription: "Yarda, İngiliz ve Amerikan ölçü sistemlerinde kullanılan bir uzunluk birimidir. Bir yarda tam olarak 0,9144 metreye eşittir.",
    historySummary: "Yarda, tarihsel olarak insan adımı ve beden ölçüleriyle ilişkilendirilen bir uzunluk yaklaşımından gelişti. Modern değeri uluslararası anlaşmalarla sabitlendi.",
    measurementSystem: "İngiliz ve ABD ölçü sistemleri",
    siEquivalent: "1 yd = 0,9144 m",
    commonUses: "Spor sahaları, tekstil, peyzaj ve saha planlaması",
  },
  "mil": {
    shortDescription: "Mil, özellikle Amerika Birleşik Devletleri ve Birleşik Krallık'ta kullanılan bir uzunluk birimidir. Bir uluslararası mil 1609,344 metreye eşittir.",
    historySummary: "Milin kökeni Roma dönemindeki bin adımlık mesafe anlayışına uzanır. Modern uluslararası mil 1959 yılında tam olarak 1609,344 metre olarak standartlaştırıldı.",
    measurementSystem: "İngiliz ve ABD ölçü sistemleri",
    siEquivalent: "1 mi = 1609,344 m",
    commonUses: "Karayolu mesafeleri, navigasyon ve saha ölçekleri",
  },
  "metrekare": {
    shortDescription: "Metrekare, alanın SI türetilmiş birimidir. Zemin, kesit ve yüzey hesaplarında temel referans olarak kullanılır.",
    historySummary: "Metrekare, metrenin iki boyutlu uzantısı olarak metrik sistem içinde yerleşti. Yapı, arazi ve mühendislik çizimlerinde standart alan dili hâline geldi.",
    measurementSystem: "Uluslararası Birim Sistemi (SI)",
    siEquivalent: "Temel SI alan birimi",
    commonUses: "Mimarlık, iç mekân, panel yüzeyleri ve kesit alanları",
  },
  "hektar": {
    shortDescription: "Hektar, özellikle arazi ölçümünde kullanılan büyük bir alan birimidir. 1 hektar tam olarak 10000 metrekareye eşittir.",
    historySummary: "Hektar, geniş tarımsal ve coğrafi alanları daha kısa ifade etmek için metrik sistem içinde yaygınlaşmıştır.",
    measurementSystem: "Metrik sistem, SI ile uyumlu",
    siEquivalent: "1 ha = 10000 m²",
    commonUses: "Tarım arazileri, imar planları ve büyük arsa kayıtları",
  },
  "fitkare": {
    shortDescription: "Fitkare, İngiliz ve ABD ölçü sistemlerinde kullanılan bir alan birimidir. Bir kare fit yaklaşık 0,092903 metrekareye eşittir.",
    historySummary: "Fitkare, fit biriminin yapı ve emlak alanındaki yaygın kullanımıyla birlikte yerleşmiştir.",
    measurementSystem: "İngiliz ve ABD ölçü sistemleri",
    siEquivalent: "1 ft² = 0,092903 m²",
    commonUses: "Emlak ilanları, döşeme alanları ve bazı yapı katalogları",
  },
  "donum": {
    shortDescription: "Dönüm, Türkiye'de arazi ve emlak ölçümünde kullanılan geleneksel bir alan birimidir. Modern standarda göre 1 dönüm tam olarak 1000 metrekareye eşittir.",
    historySummary: "Dönüm, Osmanlı döneminden beri kullanılan ve bölgeden bölgeye 900 ile 1600 metrekare arasında değişen eski bir alan birimiydi. 1931'de yürürlüğe giren Ölçüler ve Ayarlar Kanunu ile 1000 metrekare olarak standartlaştırıldı.",
    measurementSystem: "Türkiye'ye özgü geleneksel birim, metrik sisteme entegre",
    siEquivalent: "1 dönüm = 1000 m² = 1 dekar",
    commonUses: "Tarım arazisi, emlak ilanları ve tapu kayıtlarında arazi büyüklüğü",
  },
  "dekar": {
    shortDescription: "Dekar, 1000 metrekareye eşit metrik bir alan birimidir. Türkiye'de dönüm ile eş değerde kullanılır ve tarım arazilerinde yaygındır.",
    historySummary: "Dekar, ondalık metrik sistemin bir parçası olarak 10 ar'a (are) eşit şekilde tanımlanmıştır ve tarımsal alan ölçümünde birçok ülkede kullanılır.",
    measurementSystem: "Metrik sistem, SI ile uyumlu (10 ar)",
    siEquivalent: "1 dekar = 1000 m² = 1 dönüm",
    commonUses: "Tarım arazisi ölçümü, emlak ilanları ve arazi kayıtları",
  },
  "metrekup": {
    shortDescription: "Metreküp, hacmin SI türetilmiş birimidir. Büyük hacimler ve teknik kapasiteler için temel referanstır.",
    historySummary: "Metreküp, metrenin üç boyutlu uzantısı olarak bilim ve mühendislikte temel hacim birimi hâline geldi.",
    measurementSystem: "Uluslararası Birim Sistemi (SI)",
    siEquivalent: "Temel SI hacim birimi",
    commonUses: "Depolama hacmi, bina iç hacmi, proses tankları ve akış hesapları",
  },
  "litre": {
    shortDescription: "Litre, sıvı ve kapasiteleri ifade etmek için çok yaygın kullanılan bir hacim birimidir. 1 litre, 0,001 metreküpe eşittir.",
    historySummary: "Litre, metrik sistem içinde günlük kullanım ile teknik ihtiyacı birleştiren pratik bir hacim birimi olarak yaygınlaşmıştır.",
    measurementSystem: "Metrik sistem, SI ile uyumlu",
    siEquivalent: "1 L = 0,001 m³",
    commonUses: "Sıvılar, tank hacimleri, laboratuvar kapları ve günlük ölçüler",
  },
  "mililitre": {
    shortDescription: "Mililitre, litrenin binde birine eşit küçük bir hacim birimidir. Hassas sıvı ölçümlerinde kullanılır.",
    historySummary: "Mililitre, ilaç, laboratuvar ve mutfak ölçülerinde küçük hacimlerin güvenilir biçimde ifade edilmesi için yaygınlaşmıştır.",
    measurementSystem: "Metrik sistem, SI ile uyumlu",
    siEquivalent: "1 mL = 0,000001 m³",
    commonUses: "İlaç dozları, laboratuvar örnekleri ve küçük sıvı hacimleri",
  },
  "varil": {
    shortDescription: "Varil (bbl), özellikle ham petrol ticaretinde kullanılan standart bir hacim birimidir. 1 varil, 158,987 litreye (42 ABD galonuna) eşittir.",
    historySummary: "Varil birimi, 19. yüzyıl Amerikan petrol endüstrisinde petrolün nakliye fıçılarıyla taşınmasından kalma bir gelenektir; \"mavi varil\" (blue barrel) standardı zamanla uluslararası petrol ticaretinin ortak ölçüsü hâline gelmiştir.",
    measurementSystem: "SI dışı, petrol endüstrisinde uluslararası standart birim",
    siEquivalent: "1 varil (bbl) = 158,987 L = 0,158987 m³",
    commonUses: "Ham petrol fiyatlandırması, petrol üretim/tüketim istatistikleri, enerji piyasası raporları",
  },
  "kilogram": {
    shortDescription: "Kilogram, Uluslararası Birim Sistemi'nde kütlenin temel birimidir. Ticaret, laboratuvar ve mühendislikte yaygın olarak kullanılır.",
    historySummary: "Kilogram önce su kütlesine, sonra fiziksel bir prototipe dayalıydı. 2019'dan itibaren Planck sabitinin sabitlenmiş değeri üzerinden tanımlanmaktadır.",
    measurementSystem: "Uluslararası Birim Sistemi (SI)",
    siEquivalent: "Temel SI kütle birimi",
    commonUses: "Ticaret, taşıma, laboratuvar ve proses hesapları",
  },
  "gram": {
    shortDescription: "Gram, kilogramın binde birine eşit bir kütle birimidir. Gıda, laboratuvar ve küçük maddesel miktarları ifade etmekte kullanılır.",
    historySummary: "Gram, metrik sistemin erken döneminde su kütlesi temelli yaklaşımlardan gelişti ve daha sonra kilogramın alt birimi olarak standartlaştı.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, alt birim)",
    siEquivalent: "1 g = 0,001 kg",
    commonUses: "Gıda, kimya, eczacılık ve hassas ölçüm",
  },
  "miligram": {
    shortDescription: "Miligram, gramın binde birine eşit çok küçük bir kütle birimidir. İlaç ve laboratuvar ölçümlerinde kritik öneme sahiptir.",
    historySummary: "Miligram, hassas terazilerin ve analitik laboratuvarların gelişmesiyle birlikte özellikle sağlık ve kimya alanlarında öne çıktı.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, alt birim)",
    siEquivalent: "1 mg = 0,000001 kg",
    commonUses: "İlaç dozları, analizler ve hassas formülasyonlar",
  },
  "ton": {
    shortDescription: "Metrik ton, 1000 kilograma eşit büyük bir kütle birimidir. Ağır yüklerin ve endüstriyel miktarların ifade edilmesinde kullanılır.",
    historySummary: "Ton, büyük yükleri ve ticari kütleleri daha kısa ifade etmek için metrik sistem içinde yerleşti. Lojistik ve endüstride yaygın kullanım kazandı.",
    measurementSystem: "Metrik sistem, SI ile uyumlu",
    siEquivalent: "1 t = 1000 kg",
    commonUses: "Lojistik, üretim, hammadde ticareti ve ağır sanayi",
  },
  "pound": {
    shortDescription: "Pound, İngiliz ve Amerikan ölçü sistemlerinde kullanılan bir kütle birimidir. Bir uluslararası pound tam olarak 0,45359237 kilograma eşittir.",
    historySummary: "Pound ve lb sembolü Roma dönemindeki libra biriminden gelir. Modern avoirdupois pound 1959 yılında uluslararası olarak sabitlenmiştir.",
    measurementSystem: "İngiliz ve ABD ölçü sistemleri",
    siEquivalent: "1 lb = 0,45359237 kg",
    commonUses: "Perakende, taşımacılık, beslenme ve endüstriyel kataloglar",
  },
  "ons": {
    shortDescription: "Ons, İngiliz ve Amerikan ölçü sistemlerinde kullanılan küçük bir kütle birimidir. Bir avoirdupois ons 28,349523125 grama eşittir.",
    historySummary: "Ons, tarih boyunca farklı ticari ve tıbbi sistemlerde kullanıldı. Modern avoirdupois ons, pound ile olan 1/16 ilişkisi üzerinden standartlaştı.",
    measurementSystem: "İngiliz ve ABD ölçü sistemleri",
    siEquivalent: "1 oz = 28,349523125 g",
    commonUses: "Paketleme, gıda, mücevher dışı hafif ticari ölçüler",
  },
  "okka": {
    shortDescription: "Okka (kıyye), Osmanlı döneminde kullanılan geleneksel bir kütle birimidir. 400 dirheme, yani yaklaşık 1282,945 grama eşittir.",
    historySummary: "Okka, Osmanlı çarşı ve pazarlarında en yaygın kullanılan ağırlık ölçüsüydü; daha büyük ölçüler olan batman ve kantar da okka üzerinden tanımlanırdı. 1931'de yürürlüğe giren Ölçüler ve Ayarlar Kanunu ile okka yürürlükten kaldırılmış, yerini kilograma bırakmıştır.",
    measurementSystem: "Osmanlı dönemi geleneksel kütle birimi (yürürlükte değil)",
    siEquivalent: "1 okka = 400 dirhem = 1282,945 g",
    commonUses: "Osmanlı döneminde çarşı ve pazar alışverişinde ağırlık ölçümü; günümüzde bazı bölgelerde gündelik konuşma dilinde ve tarih araştırmalarında",
  },
  "dirhem": {
    shortDescription: "Dirhem, Osmanlı döneminde kullanılan küçük bir kütle birimidir. Bir okkanın dörtyüzde birine, yaklaşık 3,207 grama eşittir.",
    historySummary: "Dirhem, kıymetli maden, baharat ve ilaç gibi hassas tartım gerektiren küçük miktarların ölçümünde kullanılırdı; okka ile ondalık değil 400'e bölünen bir ilişkisi vardı. Diğer Osmanlı ölçüleri gibi 1931'deki Ölçüler ve Ayarlar Kanunu ile yürürlükten kalkmıştır.",
    measurementSystem: "Osmanlı dönemi geleneksel kütle birimi (yürürlükte değil)",
    siEquivalent: "1 dirhem = 1/400 okka ≈ 3,207 g",
    commonUses: "Osmanlı döneminde kıymetli maden, baharat ve ilaç gibi küçük miktarların tartımı; günümüzde tarih araştırmaları ve eski metinlerin yorumlanması",
  },
  "litra": {
    shortDescription: "Bizans litrası (litra), Bizans İmparatorluğu'nda kullanılan temel kütle birimidir. Metrik karşılığı yaklaşık 324 gramdır.",
    historySummary: "Litra, Roma librası geleneğinden gelir ve Bizans döneminde 12 ounkia'ya (Bizans onsu) bölünürdü; zaman içinde ağırlığı 324 gramdan 319 grama kadar hafifçe değişmiştir. Mal tartımında ve kıymetli metal ölçümünde kullanılırdı.",
    measurementSystem: "Bizans dönemi geleneksel kütle birimi (yürürlükte değil)",
    siEquivalent: "1 litra = 12 ounkia ≈ 324 g",
    commonUses: "Bizans döneminde ticaret ve kıymetli metal tartımı; günümüzde Bizans tarihi ve nümizmatik araştırmaları",
  },
  "ounkia": {
    shortDescription: "Bizans onsu (ounkia), Bizans litrasının on ikide birine eşit bir kütle birimidir. Metrik karşılığı yaklaşık 27 gramdır.",
    historySummary: "Ounkia, Roma unciası geleneğinden gelir ve Bizans'ta litranın alt biriminden olarak günlük tartımlarda kullanılırdı. Modern İngiliz/Amerikan avoirdupois onsundan (28,35 g) farklı bir değere sahiptir.",
    measurementSystem: "Bizans dönemi geleneksel kütle birimi (yürürlükte değil)",
    siEquivalent: "1 ounkia = 1/12 litra ≈ 27 g",
    commonUses: "Bizans döneminde günlük tartım ve küçük miktarların ölçümü; günümüzde Bizans tarihi araştırmaları",
  },
  "metre-saniye": {
    shortDescription: "Metre/saniye, hızın SI türetilmiş birimidir. Mühendislik ve fizikte temel referans kabul edilir.",
    historySummary: "Metre ve saniyenin birleşiminden türeyen bu gösterim, modern bilimsel hız ölçümünün standart dilidir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI)",
    siEquivalent: "Temel SI hız birimi",
    commonUses: "Akışkanlar, mekanik hareket ve bilimsel ölçümler",
  },
  "kilometre-saat": {
    shortDescription: "Kilometre/saat, kara taşımacılığında yaygın kullanılan pratik bir hız birimidir.",
    historySummary: "Yol ve ulaşım sistemlerinin yaygınlaşmasıyla kilometre/saat gösterimi sürüş ve seyahat için standartlaşmıştır.",
    measurementSystem: "Metrik pratik kullanım",
    siEquivalent: "1 km/h ≈ 0,277778 m/s",
    commonUses: "Araç hızları, trafik işaretleri ve saha ölçümleri",
  },
  "mil-saat": {
    shortDescription: "Mil/saat, özellikle ABD ve Birleşik Krallık uygulamalarında kullanılan bir hız birimidir.",
    historySummary: "Mil ve saat birimlerinin birleşimi, kara ulaşımında Anglo-Amerikan ölçü geleneğinin temel hız dilini oluşturmuştur.",
    measurementSystem: "İngiliz ve ABD ölçü sistemleri",
    siEquivalent: "1 mph = 1,609344 km/h",
    commonUses: "Karayolu hızları, otomotiv ve saha raporları",
  },
  "saniye": {
    shortDescription: "Saniye, zamanın SI temel birimidir. Tüm süre ve hız hesaplarının temelinde yer alır.",
    historySummary: "Modern saniye tanımı atomik geçiş frekansına bağlanarak evrensel ve yüksek hassasiyetli hâle getirilmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI)",
    siEquivalent: "Temel SI zaman birimi",
    commonUses: "Deney süreleri, hareket analizi, veri kayıtları ve zamanlama",
  },
  "dakika": {
    shortDescription: "Dakika, 60 saniyeye eşit pratik bir zaman birimidir.",
    historySummary: "Dakika, günlük planlama ile bilimsel olmayan süre takibinde tarihsel olarak yaygınlaşmış bir ara birimdir.",
    measurementSystem: "SI dışı, SI ile birlikte kullanılan zaman birimi",
    siEquivalent: "1 min = 60 s",
    commonUses: "Toplantılar, kısa süreler, egzersiz ve proses çevrimleri",
  },
  "saat": {
    shortDescription: "Saat, 3600 saniyeye eşit yaygın bir zaman birimidir.",
    historySummary: "Saat birimi, göksel ve mekanik zaman ölçüm geleneklerinden modern takvim ve vardiya sistemlerine taşınmıştır.",
    measurementSystem: "SI dışı, SI ile birlikte kullanılan zaman birimi",
    siEquivalent: "1 h = 3600 s",
    commonUses: "Çalışma süreleri, seyahat, enerji tüketimi ve günlük planlama",
  },
  "pascal": {
    shortDescription: "Pascal, Uluslararası Birim Sistemi'nde basıncın türetilmiş birimidir. 1 Pa = 1 N/m² ilişkisiyle tanımlanır.",
    historySummary: "Birim adını Blaise Pascal'dan alır. Akışkanlar ve basınç çalışmalarındaki bilimsel gelişmelerle birlikte SI içinde standart basınç referansı oldu.",
    measurementSystem: "Uluslararası Birim Sistemi (SI)",
    siEquivalent: "Temel SI basınç birimi, 1 Pa = 1 N/m²",
    commonUses: "Bilimsel hesaplar, malzeme analizi ve referans dönüşümler",
  },
  "kilopascal": {
    shortDescription: "Kilopascal, 1000 pascala eşit bir basınç birimidir. Pratik mühendislikte pascaldan daha okunabilir sonuçlar sağlar.",
    historySummary: "Kilopascal, özellikle saha ölçümleri ve mühendislik belgelerinde sayısal okunabilirliği artırdığı için yaygınlaşmıştır.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, kat birim)",
    siEquivalent: "1 kPa = 1000 Pa",
    commonUses: "HVAC, yapı mühendisliği, lastik basıncı ve proses verileri",
  },
  "bar": {
    shortDescription: "Bar, 100000 pascala eşit bir basınç birimidir. Sanayi ve ekipman göstergelerinde çok yaygın bir pratik gösterimdir.",
    historySummary: "Bar, atmosferik büyüklüklere yakın basınçları daha kısa ifade edebilmek için teknik uygulamalarda yaygınlık kazandı. SI dışı olsa da endüstride güçlü şekilde yaşamaya devam etti.",
    measurementSystem: "SI dışı metrik mühendislik birimi",
    siEquivalent: "1 bar = 100000 Pa",
    commonUses: "Kompresörler, hidrolik, pnömatik ve servis manometreleri",
  },
  "atmosfer": {
    shortDescription: "Atmosfer, Dünya atmosferinin deniz seviyesindeki ortalama basıncına yakın bir referans değere dayanan basınç birimidir. Standart atmosfer olarak da anılır.",
    historySummary: "Atmosfer birimi, barometrik ölçümlerin ve deniz seviyesi referans basıncının teknik ve bilimsel çalışmalarda standart bir karşılaştırma noktası olarak kullanılmasıyla yaygınlaştı. 1954 yılında 10. Genel Ağırlıklar ve Ölçüler Konferansı (CGPM) standart atmosferi tam olarak 101 325 Pa olarak tanımladı.",
    measurementSystem: "SI dışı, meteoroloji ve mühendislikte referans birim",
    siEquivalent: "1 atm = 101 325 Pa (tanımlı değer)",
    commonUses: "Referans koşulları, meteoroloji, vakum ve basınç ölçümleri",
  },
  "psi": {
    shortDescription: "PSI, pound-force per square inch ifadesinin kısaltmasıdır. Anglo-Amerikan teknik sistemlerde kullanılan yaygın bir basınç birimidir.",
    historySummary: "PSI özellikle otomotiv, hidrolik ve saha servis geleneği içinde yerleşti. SI birimleri yaygınlaşsa da birçok ekipman etiketi ve katalogta kullanılmaya devam etmektedir.",
    measurementSystem: "İngiliz ve ABD mühendislik kullanımı",
    siEquivalent: "1 psi = 6894,757293168 Pa",
    commonUses: "Lastik basıncı, hidrolik sistemler ve teknik servis",
  },
  "milimetre-civa": {
    shortDescription: "Milimetre cıva, bir cıva sütununun yüksekliğine dayanan bir basınç birimidir. Tıbbi ve laboratuvar ölçümlerinde tarihsel önem taşır.",
    historySummary: "mmHg, cıvalı manometrelerin yaygın olduğu dönemde yerleşti. Özellikle tansiyon ölçümleri ve vakum/atmosfer referansları için kalıcı bir teknik kullanım alanı oluşturdu.",
    measurementSystem: "SI dışı tarihsel mühendislik ve tıbbi birim",
    siEquivalent: "1 mmHg = 133,322387415 Pa",
    commonUses: "Tansiyon ölçümleri, laboratuvar manometreleri ve vakum referansları",
  },
  "kilogram-kuvvet-santimetrekare": {
    shortDescription: "Kilogram-kuvvet/santimetrekare, kuvvet ve alan ilişkisine dayanan SI dışı bir basınç birimidir. Eski göstergelerde ve bazı servis belgelerinde görülür.",
    historySummary: "Bu birim, kilogram-kuvvet kavramının teknik çizelgelerde yaygın kullanıldığı dönemde özellikle pompa, kazan ve mekanik gösterge dünyasında yerleşti.",
    measurementSystem: "SI dışı metrik mühendislik birimi",
    siEquivalent: "1 kgf/cm² = 98066,5 Pa = 0,980665 bar",
    commonUses: "Eski pompa ve kazan göstergeleri, servis kitapçıkları ve analog cihazlar",
  },
  "joule": {
    shortDescription: "Joule, enerjinin SI türetilmiş birimidir. İş, ısı ve enerji miktarlarını ifade etmek için kullanılır.",
    historySummary: "Joule birimi, mekanik iş ve enerji kavramlarının bilimsel standardizasyonuyla birlikte SI içinde temel enerji referansı hâline gelmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI)",
    siEquivalent: "Temel SI enerji birimi",
    commonUses: "Termodinamik, enerji dengeleri ve bilimsel hesaplar",
  },
  "kilovatsaat": {
    shortDescription: "Kilovat-saat, elektrik tüketiminde yaygın kullanılan bir enerji birimidir.",
    historySummary: "Elektrik sayaçları ve faturalandırma sistemleri nedeniyle kilovat-saat, pratik enerji kullanımının en tanınan birimlerinden biri olmuştur.",
    measurementSystem: "Teknik ve ticari enerji birimi",
    siEquivalent: "1 kWh = 3,6 MJ",
    commonUses: "Elektrik faturaları, batarya kapasitesi ve tüketim karşılaştırmaları",
  },
  "watt": {
    shortDescription: "Watt, gücün SI türetilmiş birimidir. Enerjinin aktarım hızını ifade eder.",
    historySummary: "Watt, endüstri ve elektrik mühendisliğinde güç seviyelerini ifade eden temel standart birim hâline gelmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI)",
    siEquivalent: "Temel SI güç birimi",
    commonUses: "Cihaz gücü, motor etiketleri ve enerji sistemleri",
  },
  "kilowatt": {
    shortDescription: "Kilowatt, 1000 watt’a eşit güç birimidir. Tesisat ve ekipman kapasitesinde çok kullanılır.",
    historySummary: "Kilowatt, watt biriminin büyük güç değerlerinde daha okunabilir kullanımı için mühendislik belgelerinde yaygınlaşmıştır.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, kat birim)",
    siEquivalent: "1 kW = 1000 W",
    commonUses: "Elektrik panoları, HVAC ekipmanı, jeneratör ve makine gücü",
  },
  "santigrat": {
    shortDescription: "Santigrat ölçeği, günlük yaşam ve mühendislikte en yaygın sıcaklık gösterimlerinden biridir.",
    historySummary: "Santigrat ölçeği, suyun donma ve kaynama noktalarına dayalı pratik bir sıcaklık sistemi olarak yerleşti.",
    measurementSystem: "SI ile birlikte kullanılan sıcaklık ölçeği",
    siEquivalent: "Sıcaklık farkında 1 °C = 1 K",
    commonUses: "Hava durumu, HVAC, proses takibi ve günlük sıcaklık değerleri",
  },
  "fahrenhayt": {
    shortDescription: "Fahrenheit, özellikle ABD’de yaygın olan bir sıcaklık ölçeğidir.",
    historySummary: "Fahrenheit ölçeği tarihsel olarak Anglo-Amerikan ölçüm pratiğinde yerleşmiş ve günümüzde de geniş kullanıcı tabanını korumuştur.",
    measurementSystem: "İngiliz ve ABD ölçüm geleneği",
    siEquivalent: "Sıcaklık farkında 1 °F = 5/9 K",
    commonUses: "ABD hava durumu verileri, ev içi sıcaklıklar ve bazı teknik kataloglar",
  },
  "kelvin": {
    shortDescription: "Kelvin, sıcaklığın SI temel birimidir ve mutlak sıcaklık ölçeğini temsil eder.",
    historySummary: "Kelvin ölçeği termodinamik sıcaklığı sıfırdan başlatan bilimsel yaklaşımın sonucu olarak geliştirilmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI)",
    siEquivalent: "Temel SI sıcaklık birimi",
    commonUses: "Termodinamik, bilimsel hesaplar ve mutlak sıcaklık gerektiren analizler",
  },
  "metrekup-saat": {
    shortDescription: "Metreküp/saat, hacimsel debiyi ifade eden pratik bir akış birimidir.",
    historySummary: "Bina tesisatı ve proses akışlarında saat tabanlı okuma ihtiyacı nedeniyle bu gösterim geniş kullanım kazanmıştır.",
    measurementSystem: "Teknik hacimsel debi birimi",
    siEquivalent: "1 m³/h ≈ 0,000277778 m³/s",
    commonUses: "Pompa seçimi, HVAC, su ve proses akışları",
  },
  "litre-dakika": {
    shortDescription: "Litre/dakika, küçük ve orta ölçekli akış sistemlerinde okunabilir debi gösterimi sağlar.",
    historySummary: "Dakika bazlı daha küçük akışları izlemek için laboratuvar, servis ve saha uygulamalarında yaygınlaşmıştır.",
    measurementSystem: "Teknik hacimsel debi birimi",
    siEquivalent: "1 L/min ≈ 0,0000166667 m³/s",
    commonUses: "Su hatları, cihaz beslemeleri ve küçük proses akışları",
  },
  "volt": {
    shortDescription: "Volt, elektrik geriliminin SI türetilmiş birimidir.",
    historySummary: "Elektrik potansiyel farkını standartlaştıran volt birimi, modern elektrik ve elektronik sistemlerin temel gösterimlerinden biridir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI)",
    siEquivalent: "Temel SI gerilim birimi",
    commonUses: "Elektronik devreler, güç kaynakları ve şebeke gerilimleri",
  },
  "kilovolt": {
    shortDescription: "Kilovolt, 1000 volt’a eşit gerilim birimidir. Yüksek gerilim sistemlerinde kullanılır.",
    historySummary: "Büyük iletim ve dağıtım seviyelerinin daha kısa ifade edilmesi için kilovolt yaygın teknik kullanıma girmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, kat birim)",
    siEquivalent: "1 kV = 1000 V",
    commonUses: "Şebeke, trafo ve yüksek gerilim ekipmanları",
  },
  "amper": {
    shortDescription: "Amper, elektrik akımının SI temel büyüklüklerinden biri olan standart birimidir.",
    historySummary: "Amper birimi, elektrik yükünün akış hızını ölçmek için geliştirilen uluslararası standardın parçasıdır.",
    measurementSystem: "Uluslararası Birim Sistemi (SI)",
    siEquivalent: "Temel SI akım birimi",
    commonUses: "Akım ölçümleri, koruma elemanları ve cihaz etiketleri",
  },
  "miliamper": {
    shortDescription: "Miliamper, amperin binde birine eşit küçük akım birimidir.",
    historySummary: "Elektronik ve ölçüm cihazlarında düşük akımların rahat okunabilmesi için miliamper gösterimi yaygınlaşmıştır.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, alt birim)",
    siEquivalent: "1 mA = 0,001 A",
    commonUses: "Elektronik devreler, sensörler ve düşük akım testleri",
  },
  "kg-m3": {
    shortDescription: "Kilogram/metreküp (kg/m³), yoğunluğun SI türetilmiş birimidir. Bir maddenin birim hacmindeki kütlesini ifade eder.",
    historySummary: "SI sisteminin temel kütle ve uzunluk birimlerinden türetilen kg/m³, bilimsel ve mühendislik hesaplarında yoğunluk için standart referans birim hâline gelmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, türetilmiş birim)",
    siEquivalent: "Temel SI yoğunluk birimi",
    commonUses: "Malzeme bilimi, akışkanlar mekaniği, meteoroloji ve mühendislik hesapları",
  },
  "bayt": {
    shortDescription: "Bayt (byte), dijital verinin temel ölçü birimidir. 8 bitten oluşur ve bir karakteri (harf, rakam vb.) temsil etmek için kullanılır.",
    historySummary: "Bayt, erken bilgisayar mimarilerinde bir karakterin kodlanması için gereken en küçük pratik veri birimi olarak ortaya çıkmış ve zamanla 8 bit olarak standartlaşmıştır.",
    measurementSystem: "Dijital veri birimi (bilgi işlem standardı)",
    siEquivalent: "1 bayt = 8 bit",
    commonUses: "Dosya boyutu, bellek kapasitesi ve veri iletimi ölçümü",
  },
  "kilobayt": {
    shortDescription: "Kilobayt (KB), 1000 bayta eşit bir veri birimidir. Küçük metin dosyaları ve basit belgelerin boyutunu ifade etmek için kullanılır.",
    historySummary: "Kilobayt, SI ön ek sistemine dayanarak ondalık (1000 tabanlı) olarak tanımlanmıştır; bilgisayar dünyasında zamanla 1024 tabanlı kullanım da yaygınlaşmış, bu da karışıklığa yol açmıştır.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, kat birim)",
    siEquivalent: "1 KB = 1000 bayt",
    commonUses: "Metin dosyaları, basit belgeler ve küçük veri paketleri",
  },
  "megabayt": {
    shortDescription: "Megabayt (MB), 1.000.000 bayta eşit bir veri birimidir. Fotoğraf, müzik dosyası ve kısa belgelerin boyutunu ifade etmek için yaygın kullanılır.",
    historySummary: "Megabayt, kişisel bilgisayarların yaygınlaşmasıyla birlikte dosya ve disk boyutlarının ifade edilmesinde standart bir referans birim hâline gelmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, kat birim)",
    siEquivalent: "1 MB = 1.000.000 bayt",
    commonUses: "Fotoğraflar, müzik dosyaları, kısa videolar ve uygulama boyutları",
  },
  "gigabayt": {
    shortDescription: "Gigabayt (GB), 1 milyar bayta eşit bir veri birimidir. Akıllı telefon depolama alanı, video dosyaları ve RAM kapasitesi ifade etmek için kullanılır.",
    historySummary: "Gigabayt, depolama teknolojilerinin gelişmesiyle birlikte disk, bellek ve mobil cihaz kapasitelerinin standart ifade birimi hâline gelmiş; SI (1000 tabanlı) ile bilgisayar dünyasının geleneksel (1024 tabanlı) kullanımı arasındaki fark bu birimde en çok fark edilir hâle gelmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, kat birim)",
    siEquivalent: "1 GB = 1.000.000.000 bayt",
    commonUses: "Akıllı telefon ve bilgisayar depolama alanı, RAM kapasitesi, video dosyaları",
  },
  "terabayt": {
    shortDescription: "Terabayt (TB), 1 trilyon bayta eşit büyük bir veri birimidir. Harici diskler, sunucu depolama alanı ve büyük veri kümeleri için kullanılır.",
    historySummary: "Terabayt, veri depolama teknolojilerinin ilerlemesiyle birlikte kişisel bilgisayar ve sunucu depolama kapasitelerinin ifade edilmesinde standart hâle gelmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, kat birim)",
    siEquivalent: "1 TB = 1.000.000.000.000 bayt",
    commonUses: "Harici diskler, sunucu depolama, veri merkezleri ve büyük veri kümeleri",
  },
  "petabayt": {
    shortDescription: "Petabayt (PB), 1 katrilyon (10¹⁵) bayta eşit çok büyük bir veri birimidir. Büyük veri merkezleri ve bulut depolama sistemlerinin kapasitesini ifade eder.",
    historySummary: "Petabayt, büyük veri (big data) ve bulut bilişim teknolojilerinin yaygınlaşmasıyla birlikte kurumsal veri merkezi kapasitelerinin ifade edilmesinde standart hâle gelmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, kat birim)",
    siEquivalent: "1 PB = 1.000.000.000.000.000 bayt = 1000 TB",
    commonUses: "Bulut depolama, veri merkezleri, büyük veri analitiği ve bilimsel araştırma arşivleri",
  },
  "bit": {
    shortDescription: "Bit, dijital verinin en küçük birimidir; yalnızca 0 veya 1 değerini alabilir. Bayt dahil diğer tüm veri birimlerinin temelini oluşturur.",
    historySummary: "Bit terimi, 'binary digit' (ikili basamak) ifadesinin kısaltması olarak bilgisayar biliminin ilk yıllarında ortaya çıkmış ve dijital bilginin temel yapı taşı hâline gelmiştir.",
    measurementSystem: "Dijital veri birimi (bilgi işlem standardı)",
    siEquivalent: "8 bit = 1 bayt",
    commonUses: "İnternet bağlantı hızı (Mbps, Gbps), işlemci mimarisi (32-bit, 64-bit) ve veri iletim oranları",
  },
  "kibibayt": {
    shortDescription: "Kibibayt (KiB), 1024 bayta eşit, ikili (binary) tabanlı bir veri birimidir. İşletim sistemlerinin bellek ve disk alanını gerçek şekilde ifade etmesinde kullanılır.",
    historySummary: "Kibibayt, 1998'de IEC (Uluslararası Elektroteknik Komisyonu) tarafından, 1024 tabanlı geleneksel 'kilobayt' kullanımı ile SI'nin 1000 tabanlı kilobayt tanımı arasındaki karışıklığı gidermek amacıyla standartlaştırılmıştır.",
    measurementSystem: "IEC ikili (binary) ön ek sistemi",
    siEquivalent: "1 KiB = 1024 bayt",
    commonUses: "İşletim sistemi bellek ve disk gösterimleri, dosya sistemleri ve RAM kapasitesi hesaplamaları",
  },
  "mebibayt": {
    shortDescription: "Mebibayt (MiB), 1.048.576 bayta (1024 KiB) eşit, ikili tabanlı bir veri birimidir. RAM kapasitesi gibi 1024 tabanlı gerçek bellek ölçümlerinde kullanılır.",
    historySummary: "Mebibayt, IEC'in 1998'de tanımladığı ikili ön ekler ailesinin bir parçasıdır; işletim sistemlerinin 'MB' olarak gösterdiği ama aslında 1024 tabanlı hesapladığı değerleri doğru şekilde ifade etmek için geliştirilmiştir.",
    measurementSystem: "IEC ikili (binary) ön ek sistemi",
    siEquivalent: "1 MiB = 1.048.576 bayt = 1024 KiB",
    commonUses: "RAM kapasitesi, işletim sistemi disk gösterimleri ve bellek yönetimi hesaplamaları",
  },
  "gibibayt": {
    shortDescription: "Gibibayt (GiB), 1.073.741.824 bayta (1024 MiB) eşit, ikili tabanlı bir veri birimidir. Windows ve macOS'un disk/RAM boyutunu gösterirken kullandığı gerçek hesaplama birimidir.",
    historySummary: "Gibibayt, üreticilerin 1000 tabanlı 'GB' pazarlama birimi ile işletim sistemlerinin 1024 tabanlı gerçek hesaplaması arasındaki farkı netleştirmek için IEC tarafından standartlaştırılmıştır; bu fark, yeni bir diskin işletim sisteminde neden üreticinin belirttiğinden daha az göründüğünün asıl nedenidir.",
    measurementSystem: "IEC ikili (binary) ön ek sistemi",
    siEquivalent: "1 GiB = 1.073.741.824 bayt = 1024 MiB",
    commonUses: "İşletim sistemi disk/RAM kapasitesi gösterimi, sunucu bellek ölçümü ve depolama karşılaştırmaları",
  },
  "tebibayt": {
    shortDescription: "Tebibayt (TiB), 1.099.511.627.776 bayta (1024 GiB) eşit, çok büyük ve ikili tabanlı bir veri birimidir. Büyük depolama sistemlerinin gerçek kapasitesini ifade eder.",
    historySummary: "Tebibayt, IEC'in ikili ön ek standardının bir parçası olarak, büyük disk dizilerinin ve sunucu depolama sistemlerinin 1024 tabanlı gerçek kapasitesini 1000 tabanlı pazarlama biriminden ayırt etmek için kullanılır.",
    measurementSystem: "IEC ikili (binary) ön ek sistemi",
    siEquivalent: "1 TiB = 1.099.511.627.776 bayt = 1024 GiB",
    commonUses: "Sunucu depolama dizileri, veri merkezi kapasite planlaması ve büyük RAID sistemleri",
  },
  "ohm": {
    shortDescription: "Ohm (Ω), elektriksel direncin SI birimidir. Bir devrenin akıma ne kadar karşı koyduğunu ifade eder.",
    historySummary: "Ohm, Alman fizikçi Georg Simon Ohm'un akım-gerilim-direnç ilişkisini tanımlayan Ohm Yasası'na atfen adlandırılmış ve elektrik mühendisliğinin temel birimlerinden biri hâline gelmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, türetilmiş birim)",
    siEquivalent: "1 Ω = 1 V/A",
    commonUses: "Devre tasarımı, direnç etiketleri, Ohm Yasası hesaplamaları ve elektronik bileşen seçimi",
  },
  "kiloohm": {
    shortDescription: "Kiloohm (kΩ), 1000 ohma eşit bir direnç birimidir. Elektronik devrelerdeki yaygın direnç değerlerini ifade etmek için kullanılır.",
    historySummary: "Kiloohm, ohm biriminin SI ön ek sistemiyle ölçeklenmesinden doğmuş, özellikle elektronik direnç etiketlerinde (renk kodları) yaygın bir gösterim biçimi hâline gelmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, kat birim)",
    siEquivalent: "1 kΩ = 1000 Ω",
    commonUses: "Elektronik devre direnç değerleri, potansiyometreler ve devre kartı tasarımı",
  },
  "megaohm": {
    shortDescription: "Megaohm (MΩ), 1 milyon ohma eşit büyük bir direnç birimidir. Yüksek dirençli devre elemanları ve izolasyon ölçümlerinde kullanılır.",
    historySummary: "Megaohm, yüksek direnç değerlerinin (izolasyon direnci, hassas ölçüm cihazları) pratik biçimde ifade edilmesi ihtiyacıyla yaygınlaşmıştır.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, kat birim)",
    siEquivalent: "1 MΩ = 1.000.000 Ω",
    commonUses: "İzolasyon direnci testleri, yüksek empedanslı devreler ve hassas ölçüm ekipmanları",
  },
  "farad": {
    shortDescription: "Farad (F), elektriksel kapasitansın SI birimidir. Bir kondansatörün ne kadar elektrik yükü depolayabildiğini ifade eder.",
    historySummary: "Farad, İngiliz bilim insanı Michael Faraday'ın elektromanyetizma alanındaki çalışmalarına atfen adlandırılmıştır; günlük kullanımdaki kondansatörler genellikle farad'ın çok küçük katları ile ifade edilir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, türetilmiş birim)",
    siEquivalent: "1 F = 1 C/V",
    commonUses: "Kondansatör kapasite değerleri, devre tasarımı ve enerji depolama hesaplamaları",
  },
  "milifarad": {
    shortDescription: "Milifarad (mF), 0,001 farada eşit bir kapasitans birimidir. Büyük elektrolitik kondansatörlerin kapasitesini ifade etmek için kullanılır.",
    historySummary: "Milifarad, farad biriminin pratikte kullanılabilir ölçekte ifade edilmesi için SI ön ek sistemiyle türetilmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, alt birim)",
    siEquivalent: "1 mF = 0,001 F",
    commonUses: "Büyük elektrolitik kondansatörler ve güç kaynağı filtreleme devreleri",
  },
  "mikrofarad": {
    shortDescription: "Mikrofarad (µF), 0,000001 farada eşit bir kapasitans birimidir. Elektronik devrelerde en sık karşılaşılan kondansatör birimidir.",
    historySummary: "Mikrofarad, elektronik endüstrisinde kondansatör değerlerinin standart gösterim birimi hâline gelmiş, farad'ın günlük kullanımda en yaygın alt katıdır.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, alt birim)",
    siEquivalent: "1 µF = 0,000001 F",
    commonUses: "Elektronik devre kondansatörleri, filtreleme ve zamanlama devreleri",
  },
  "nanofarad": {
    shortDescription: "Nanofarad (nF), 10⁻⁹ farada eşit küçük bir kapasitans birimidir. Yüksek frekanslı devrelerde ve seramik kondansatörlerde kullanılır.",
    historySummary: "Nanofarad, yüksek frekans elektroniğinde küçük kapasitans değerlerinin pratik ifadesi için SI ön ek sisteminden türetilmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, alt birim)",
    siEquivalent: "1 nF = 0,000000001 F",
    commonUses: "Seramik kondansatörler, yüksek frekans filtreleri ve osilatör devreleri",
  },
  "pikofarad": {
    shortDescription: "Pikofarad (pF), 10⁻¹² farada eşit çok küçük bir kapasitans birimidir. Radyo frekansı devrelerinde ve hassas zamanlama uygulamalarında kullanılır.",
    historySummary: "Pikofarad, radyo frekansı ve yüksek hassasiyetli elektronik uygulamalarda çok küçük kapasitans değerlerinin ifadesi için standart hâle gelmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, alt birim)",
    siEquivalent: "1 pF = 0,000000000001 F",
    commonUses: "Radyo frekansı devreleri, kristal osilatörler ve hassas zamanlama uygulamaları",
  },
  "henry": {
    shortDescription: "Henry (H), elektriksel endüktansın SI birimidir. Bir bobinin manyetik alanda ne kadar enerji depolayabildiğini ifade eder.",
    historySummary: "Henry, Amerikalı bilim insanı Joseph Henry'nin elektromanyetik endüksiyon üzerine yaptığı çalışmalara atfen adlandırılmıştır.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, türetilmiş birim)",
    siEquivalent: "1 H = 1 Wb/A",
    commonUses: "Bobin ve transformatör tasarımı, filtre devreleri ve güç elektroniği",
  },
  "milihenry": {
    shortDescription: "Milihenry (mH), 0,001 henry'e eşit bir endüktans birimidir. Güç kaynağı bobinlerinin ve filtrelerin endüktansını ifade etmek için kullanılır.",
    historySummary: "Milihenry, henry biriminin pratik devre tasarımı ölçeğinde ifade edilmesi için SI ön ek sistemiyle türetilmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, alt birim)",
    siEquivalent: "1 mH = 0,001 H",
    commonUses: "Güç kaynağı bobinleri, filtre devreleri ve anahtarlamalı güç kaynakları",
  },
  "mikrohenry": {
    shortDescription: "Mikrohenry (µH), 0,000001 henry'e eşit küçük bir endüktans birimidir. Yüksek frekanslı radyo frekansı bobinlerinde kullanılır.",
    historySummary: "Mikrohenry, radyo frekansı ve yüksek frekanslı elektronik devrelerde küçük endüktans değerlerinin ifadesi için yaygınlaşmıştır.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, alt birim)",
    siEquivalent: "1 µH = 0,000001 H",
    commonUses: "Radyo frekansı bobinleri, anten devreleri ve yüksek frekans filtreleri",
  },
  "coulomb": {
    shortDescription: "Coulomb (C), elektrik yükünün SI birimidir. Bir devreden geçen toplam elektrik yükü miktarını ifade eder.",
    historySummary: "Coulomb, Fransız fizikçi Charles-Augustin de Coulomb'un elektrostatik kuvvet üzerine yaptığı çalışmalara atfen adlandırılmıştır.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, türetilmiş birim)",
    siEquivalent: "1 C = 1 A·s",
    commonUses: "Batarya kapasitesi hesaplamaları, elektrostatik yük ölçümü ve kondansatör şarj hesapları",
  },
  "milicoulomb": {
    shortDescription: "Milicoulomb (mC), 0,001 coulomb'a eşit bir elektrik yükü birimidir. Küçük ölçekli devrelerde yük miktarını ifade etmek için kullanılır.",
    historySummary: "Milicoulomb, coulomb biriminin pratik devre ölçeğinde ifade edilmesi için SI ön ek sistemiyle türetilmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, alt birim)",
    siEquivalent: "1 mC = 0,001 C",
    commonUses: "Kondansatör şarj hesapları ve küçük ölçekli elektrostatik uygulamalar",
  },
  "mikrocoulomb": {
    shortDescription: "Mikrocoulomb (µC), 0,000001 coulomb'a eşit küçük bir elektrik yükü birimidir. Elektrostatik deneylerde ve hassas ölçümlerde kullanılır.",
    historySummary: "Mikrocoulomb, elektrostatik ve laboratuvar ölçümlerinde küçük yük değerlerinin pratik ifadesi için yaygınlaşmıştır.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, alt birim)",
    siEquivalent: "1 µC = 0,000001 C",
    commonUses: "Elektrostatik deneyler, laboratuvar ölçümleri ve hassas kondansatör hesapları",
  },
  "nanocoulomb": {
    shortDescription: "Nanocoulomb (nC), 10⁻⁹ coulomb'a eşit çok küçük bir elektrik yükü birimidir. Hassas elektrostatik ölçümlerde kullanılır.",
    historySummary: "Nanocoulomb, çok küçük elektrik yükü değerlerinin ifade edilmesi gereken hassas bilimsel ölçümlerde kullanılmak üzere SI ön ek sisteminden türetilmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, alt birim)",
    siEquivalent: "1 nC = 0,000000001 C",
    commonUses: "Hassas elektrostatik ölçümler ve bilimsel laboratuvar deneyleri",
  },
  "ayar-24": {
    shortDescription: "24 ayar altın, %99,9 saflıkta neredeyse tamamen saf altındır. En yumuşak ayar olduğu için genellikle külçe ve yatırım amaçlı ürünlerde kullanılır.",
    historySummary: "Ayar sistemi, altın alaşımındaki saflık oranını 24 birim üzerinden ifade eden geleneksel bir kuyumculuk standardıdır; 24 ayar, alaşımsız saf altını temsil eder.",
    measurementSystem: "Kuyumculuk saflık standardı (ayar / karat)",
    siEquivalent: "24 ayar = %100 saf altın içeriği",
    commonUses: "Külçe altın, yatırımlık altın ve saflık referansı olarak kullanım",
  },
  "ayar-22": {
    shortDescription: "22 ayar altın, içeriğinin 22/24'ü (yaklaşık %91,6) saf altın olan bir alaşımdır. Türkiye'de bilezik ve geleneksel takılarda yaygın kullanılır.",
    historySummary: "22 ayar, saf altının yumuşaklığını azaltıp dayanıklılığını artırmak için az miktarda gümüş veya bakırla alaşımlanmasından doğmuş, Türkiye ve Orta Doğu'da geleneksel takı standardı hâline gelmiştir.",
    measurementSystem: "Kuyumculuk saflık standardı (ayar / karat)",
    siEquivalent: "22 ayar = %91,6 saf altın içeriği (22/24)",
    commonUses: "Bilezik, geleneksel takı ve hediyelik altın ürünler",
  },
  "ayar-18": {
    shortDescription: "18 ayar altın, içeriğinin 18/24'ü (%75) saf altın olan bir alaşımdır. Dayanıklılığı yüksek olduğu için günlük kullanım takılarında tercih edilir.",
    historySummary: "18 ayar, saf altına göre daha sert ve çizilmeye dayanıklı olması nedeniyle özellikle yüzük ve günlük kullanım mücevheratında uluslararası standart hâline gelmiştir.",
    measurementSystem: "Kuyumculuk saflık standardı (ayar / karat)",
    siEquivalent: "18 ayar = %75 saf altın içeriği (18/24)",
    commonUses: "Yüzük, kolye, günlük kullanım mücevherat ve pırlanta montürleri",
  },
  "ayar-14": {
    shortDescription: "14 ayar altın, içeriğinin 14/24'ü (yaklaşık %58,3) saf altın olan bir alaşımdır. Ekonomik ve dayanıklı olduğu için özellikle ABD ve Avrupa'da yaygındır.",
    historySummary: "14 ayar, saf altın oranı daha düşük olduğu için daha uygun fiyatlı ve daha dayanıklı bir alaşım olarak özellikle Kuzey Amerika ve Avrupa mücevherat piyasasında standart hâline gelmiştir.",
    measurementSystem: "Kuyumculuk saflık standardı (ayar / karat)",
    siEquivalent: "14 ayar = %58,3 saf altın içeriği (14/24)",
    commonUses: "Ekonomik mücevherat, günlük takılar ve ABD/Avrupa pazarı ürünleri",
  },
  "mikrometre": {
    shortDescription: "Mikrometre, metrenin milyonda birine eşit çok küçük bir uzunluk birimidir. Hassas mühendislik toleranslarında ve mikroskobik ölçümlerde kullanılır.",
    historySummary: "Mikrometre, üretim ve malzeme mühendisliğinde çok küçük boyutların ve toleransların ifade edilmesi ihtiyacıyla yaygınlaştı; mikron olarak da bilinir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, alt birim)",
    siEquivalent: "1 µm = 0,000001 m = 0,001 mm",
    commonUses: "Üretim toleransları, malzeme kalınlığı, mikroskobik ölçümler ve yarı iletken üretimi",
  },
  "nanometre": {
    shortDescription: "Nanometre, metrenin milyarda birine eşit son derece küçük bir uzunluk birimidir. Işık dalga boyu ve atomik ölçekli boyutların ifadesinde kullanılır.",
    historySummary: "Nanometre, nanoteknoloji ve yarı iletken üretiminin gelişimiyle birlikte çip özellik boyutları ve ışık dalga boyu gibi son derece küçük ölçümlerin standart ifade birimi hâline gelmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, alt birim)",
    siEquivalent: "1 nm = 0,000000001 m",
    commonUses: "Işık dalga boyu, yarı iletken çip üretimi, nanoteknoloji ve optik kaplamalar",
  },
  "deniz-mili": {
    shortDescription: "Deniz mili, denizcilik ve havacılıkta kullanılan, Dünya'nın enlem dairesine dayanan bir uzunluk birimidir. Tam olarak 1852 metreye eşittir.",
    historySummary: "Deniz mili, Dünya üzerindeki bir enlem derecesinin altmışta birine (bir yay dakikasına) dayalı olarak tanımlanmış ve denizcilikte mesafe ile hız (knot) ölçümünün temelini oluşturmuştur.",
    measurementSystem: "Denizcilik ve havacılık ölçü sistemi (SI dışı)",
    siEquivalent: "1 deniz mili = 1852 m",
    commonUses: "Denizcilik ve havacılıkta mesafe ölçümü, seyir hesapları ve knot (deniz mili/saat) hız birimi",
  },
  "arsin": {
    shortDescription: "Arşın, Osmanlı döneminde kullanılan geleneksel bir uzunluk birimidir. En yaygın biçimi olan çarşı arşını 68 santimetreye karşılık gelir.",
    historySummary: "Arşın'ın kullanım alanına göre birden fazla türü vardı: ticarette kullanılan çarşı arşını 68 cm, inşaatta kullanılan mimar arşını (zira-i mimari) ise 24 parmak üzerinden yaklaşık 75,77 cm olarak tanımlanıyordu. 1869'daki metrik ıslahat çalışmalarıyla zirâ-i a'şârî adlı ondalık bir uzunluk ölçüsü kabul edilmiş, 1931'de yürürlüğe giren Ölçüler ve Ayarlar Kanunu ile arşın tamamen yürürlükten kaldırılıp yerini metreye bırakmıştır.",
    measurementSystem: "Osmanlı dönemi geleneksel uzunluk birimi (yürürlükte değil)",
    siEquivalent: "1 arşın (çarşı arşını) = 0,68 m",
    commonUses: "Osmanlı döneminde kumaş, arazi ve inşaat ölçümü; günümüzde tarih araştırmaları ve eski metinlerin yorumlanması",
  },
  "endaze": {
    shortDescription: "Endaze, Osmanlı döneminde özellikle kumaş ölçümünde kullanılan bir uzunluk birimidir. Metrik karşılığı 65 santimetredir.",
    historySummary: "Endaze, her biri dört parmak genişliğinde dört kabzadan oluşan bir ölçü birimiydi ve arşından farklı, daha çok tekstil ve manifatura ticaretinde tercih edilirdi. Diğer Osmanlı ölçüleri gibi 1931'deki Ölçüler ve Ayarlar Kanunu ile yürürlükten kalkmış, yerini metreye bırakmıştır.",
    measurementSystem: "Osmanlı dönemi geleneksel uzunluk birimi (yürürlükte değil)",
    siEquivalent: "1 endaze = 0,65 m",
    commonUses: "Osmanlı döneminde kumaş ve manifatura ölçümü; günümüzde tarih araştırmaları ve eski metinlerin yorumlanması",
  },
  "pous": {
    shortDescription: "Bizans ayağı (pous), Bizans İmparatorluğu'nda kullanılan temel uzunluk birimidir. Metrik karşılığı yaklaşık 31,48 santimetredir.",
    historySummary: "Pous, Antik Yunan uzunluk sisteminden Bizans'a geçmiş ve İstanbul'un 1453'te fethine kadar mimari ile günlük ölçümde kullanılmaya devam etmiştir. Altı pous bir orgyia'ya (Bizans kulacı) eşitti.",
    measurementSystem: "Bizans dönemi geleneksel uzunluk birimi (yürürlükte değil)",
    siEquivalent: "1 pous ≈ 0,3148 m",
    commonUses: "Bizans döneminde mimari, arazi ve günlük mesafe ölçümü; günümüzde Bizans tarihi ve arkeolojisi araştırmaları",
  },
  "orgyia": {
    shortDescription: "Bizans kulacı (orgyia), Bizans döneminde kullanılan ve altı ayak (pous) uzunluğundaki bir mesafe birimidir. Metrik karşılığı yaklaşık 188,88 santimetredir.",
    historySummary: "Orgyia, Antik Yunan kökenli olup kollar iki yana açıldığında parmak uçları arasındaki mesafeye dayanır; Türkçedeki kulaç birimiyle aynı mantıkla tanımlanmıştır. Bizans'ta arazi ve deniz mesafelerinin ölçümünde kullanılmıştır.",
    measurementSystem: "Bizans dönemi geleneksel uzunluk birimi (yürürlükte değil)",
    siEquivalent: "1 orgyia = 6 pous ≈ 1,8888 m",
    commonUses: "Bizans döneminde arazi ve deniz mesafesi ölçümü; günümüzde Bizans tarihi ve arkeolojisi araştırmaları",
  },
  "cig": {
    shortDescription: "Çığ, eski Türklerin kullandığı bir uzunluk birimidir. Kaşgarlı Mahmud'un Dîvânu Lugâti't-Türk adlı eserine göre metrik karşılığı yaklaşık 33,3 santimetredir.",
    historySummary: "Çığ, Kaşgarlı Mahmud'un 11. yüzyılda yazdığı Dîvânu Lugâti't-Türk'te 'Türklerin uzunluk ölçüsü' olarak tanımlanmış ve dönemin Arap ölçüsünün üçte ikisine karşılık geldiği belirtilmiştir. Çince kökenli olduğu, Köktürkler döneminde Çin ile ticari ilişkiler üzerinden dile girdiği düşünülür.",
    measurementSystem: "Eski Türk (Köktürk dönemi) geleneksel uzunluk birimi (yürürlükte değil)",
    siEquivalent: "1 çığ ≈ 0,333 m",
    commonUses: "Eski Türklerde kumaş ve mesafe ölçümü; günümüzde Türk dili tarihi ve Dîvânu Lugâti't-Türk araştırmaları",
  },
  "santimetrekare": {
    shortDescription: "Santimetrekare, metrekarenin on binde birine eşit küçük bir alan birimidir. Küçük yüzeylerin ve kesit alanlarının ifadesinde kullanılır.",
    historySummary: "Santimetrekare, metrik sistemin ondalık yapısı içinde küçük ölçekli alanların pratik biçimde ifade edilmesi için yaygınlaşmıştır.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, alt birim)",
    siEquivalent: "1 cm² = 0,0001 m²",
    commonUses: "Kağıt ve kumaş ölçüleri, kesit alanı hesapları, laboratuvar ve el işi ölçümleri",
  },
  "milimetrekare": {
    shortDescription: "Milimetrekare, metrekarenin milyonda birine eşit çok küçük bir alan birimidir. Kablo kesitleri ve hassas mühendislik alanlarında kullanılır.",
    historySummary: "Milimetrekare, elektrik mühendisliğinde kablo kesit alanlarının ve malzeme mühendisliğinde küçük yüzeylerin ifade edilmesi için standart hâline gelmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, alt birim)",
    siEquivalent: "1 mm² = 0,000001 m²",
    commonUses: "Kablo kesit alanı, hassas parça yüzeyleri ve mühendislik çizimleri",
  },
  "kilometrekare": {
    shortDescription: "Kilometrekare, bir kenarı bir kilometre olan karenin alanına eşit büyük bir alan birimidir. Şehir, ülke ve bölge yüz ölçümlerinde kullanılır.",
    historySummary: "Kilometrekare, coğrafya ve haritacılıkta geniş alanların pratik biçimde ifade edilmesi için metrik sistemin ondalık yapısından türetilmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, kat birim)",
    siEquivalent: "1 km² = 1.000.000 m²",
    commonUses: "Ülke ve şehir yüz ölçümleri, coğrafya, tarım arazisi ve bölgesel planlama",
  },
  "incare": {
    shortDescription: "İnçkare, İngiliz ve Amerikan ölçü sistemlerinde kullanılan küçük bir alan birimidir. Bir kenarı bir inç olan karenin alanına eşittir.",
    historySummary: "İnçkare, İngiliz ölçü sisteminin alan birimleri ailesinde, küçük yüzeylerin ve teknik parça kesitlerinin ifade edilmesi için kullanılagelmiştir.",
    measurementSystem: "İngiliz ve ABD ölçü sistemleri",
    siEquivalent: "1 in² = 0,00064516 m²",
    commonUses: "ABD kaynaklı teknik çizimler, ekran ve parça yüzey alanları",
  },
  "akre": {
    shortDescription: "Akre, özellikle İngiliz ve Amerikan ölçü sistemlerinde arazi ölçümünde kullanılan büyük bir alan birimidir. 4046,8564224 metrekareye eşittir.",
    historySummary: "Akre, tarihsel olarak bir çift öküzün bir günde sürebileceği tarla alanına dayanan bir yaklaşımdan gelişmiş ve günümüzde İngiliz ölçü sisteminde standart arazi birimi olarak kullanılmaya devam etmektedir.",
    measurementSystem: "İngiliz ve ABD ölçü sistemleri",
    siEquivalent: "1 akre = 4046,8564224 m²",
    commonUses: "Emlak ve arazi alım satımı, tarım arazisi ölçümü ve gayrimenkul ilanları",
  },
  "santimetrekup": {
    shortDescription: "Santimetreküp (cm³), metreküpün milyonda birine eşit küçük bir hacim birimidir. Motor silindir hacminden laboratuvar ölçümlerine kadar geniş kullanım alanı vardır.",
    historySummary: "Santimetreküp, mililitre ile sayısal olarak birebir eşit olduğu için hem laboratuvar hem endüstriyel ölçümlerde, özellikle motor hacmi (cc) ifadesinde yaygınlaşmıştır.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, alt birim)",
    siEquivalent: "1 cm³ = 1 mL = 0,000001 m³",
    commonUses: "Motor silindir hacmi (cc), laboratuvar ölçümleri ve küçük nesnelerin hacim hesapları",
  },
  "fitkup": {
    shortDescription: "Fitküp (ft³), İngiliz ve Amerikan ölçü sistemlerinde kullanılan bir hacim birimidir. Bir kenarı bir fit olan küpün hacmine eşittir.",
    historySummary: "Fitküp, İngiliz ölçü sisteminin hacim birimleri ailesinde, özellikle inşaat, nakliye ve depolama hacimlerinin ifade edilmesi için kullanılagelmiştir.",
    measurementSystem: "İngiliz ve ABD ölçü sistemleri",
    siEquivalent: "1 ft³ = 0,0283168 m³",
    commonUses: "ABD kaynaklı inşaat, nakliye konteyner hacmi ve depolama hesapları",
  },
  "inckup": {
    shortDescription: "İnçküp (in³), İngiliz ve Amerikan ölçü sistemlerinde kullanılan küçük bir hacim birimidir. Özellikle motor silindir hacmi ifadesinde (cubic inch) kullanılır.",
    historySummary: "İnçküp, ABD otomotiv endüstrisinde geleneksel olarak motor hacminin 'cubic inch' cinsinden ifade edilmesiyle özdeşleşmiştir.",
    measurementSystem: "İngiliz ve ABD ölçü sistemleri",
    siEquivalent: "1 in³ = 0,0000163871 m³",
    commonUses: "ABD kaynaklı motor hacmi (cubic inch), teknik çizimler ve küçük parça hacimleri",
  },
  "galon": {
    shortDescription: "Galon, özellikle Amerika Birleşik Devletleri'nde sıvı hacmi ölçmek için kullanılan bir birimdir. Bir ABD galonu 3,78541 litreye eşittir.",
    historySummary: "Galon, İngiliz ölçü sisteminden gelişmiş, ABD ve Birleşik Krallık'ta farklı tanımlara sahip (ABD galonu ile İngiliz galonu farklıdır) tarihsel bir sıvı hacim birimidir.",
    measurementSystem: "ABD ölçü sistemi (US liquid gallon)",
    siEquivalent: "1 galon (US) = 3,78541 L = 0,00378541 m³",
    commonUses: "Yakıt tüketimi, ABD kaynaklı sıvı ürün etiketleri ve mutfak ölçüleri",
  },
  "pascal-saniye": {
    shortDescription: "Pascal-saniye (Pa·s), dinamik viskozitenin SI türetilmiş birimidir. Bir akışkanın akışa karşı gösterdiği direnci ifade eder.",
    historySummary: "Pascal-saniye, SI sisteminin basınç ve zaman birimlerinden doğrudan türetilmiştir ve akışkanlar mekaniğinde dinamik viskozitenin standart bilimsel referans birimidir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, türetilmiş birim)",
    siEquivalent: "Temel SI dinamik viskozite birimi: 1 Pa·s = 1 N·s/m²",
    commonUses: "Akışkanlar mekaniği, Reynolds sayısı hesapları, boru hattı tasarımı ve akışkan karakterizasyonu",
  },
  "centipoise": {
    shortDescription: "Santipoise (cP), dinamik viskoziteyi ifade etmek için endüstride yaygın kullanılan bir birimdir. Suyun 20°C'deki viskozitesi yaklaşık 1 cP'dir.",
    historySummary: "Santipoise, CGS sistemindeki poise biriminin binde biridir; motor yağı, boya ve gıda endüstrisinde viskozite değerlerinin pratik ve okunabilir biçimde ifade edilmesi için yaygınlaşmıştır.",
    measurementSystem: "CGS sistemi (SI dışı, alt birim)",
    siEquivalent: "1 cP = 0,001 Pa·s",
    commonUses: "Motor yağı ve madeni yağ viskozite dereceleri, boya ve kaplama endüstrisi, gıda bilimi",
  },
  "kg-m-s": {
    shortDescription: "Kilogram-metre/saniye (kg·m/s), momentumun (devinirlik) SI türetilmiş birimidir. Bir cismin kütlesi ile hızının çarpımını ifade eder.",
    historySummary: "Momentum kavramı klasik mekaniğin temel taşlarından biridir ve kilogram-metre/saniye birimi doğrudan SI'nin temel kütle, uzunluk ve zaman birimlerinden türetilir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, türetilmiş birim)",
    siEquivalent: "Temel SI momentum birimi: 1 kg·m/s = 1 kg × 1 m/s",
    commonUses: "Çarpışma analizleri, roket ve itki hesapları, parçacık fiziği",
  },
  "n-s": {
    shortDescription: "Newton-saniye (N·s), impulsun (itme) SI türetilmiş birimidir ve boyutsal olarak momentum ile aynıdır.",
    historySummary: "Newton-saniye, impuls-momentum teoreminin doğal bir sonucu olarak ortaya çıkar; bir cisme uygulanan kuvvetin zamanla çarpımı, o cismin momentumundaki değişime eşittir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, türetilmiş birim)",
    siEquivalent: "1 N·s = 1 kg·m/s",
    commonUses: "Çarpışma ve darbe analizleri, roket itkisi, spor biyomekaniği",
  },
  "newton-metre": {
    shortDescription: "Newton-metre (N·m), torkun (döndürme momentinin) SI türetilmiş birimidir. 1 metre uzunluğundaki bir kolun ucuna dik olarak uygulanan 1 newtonluk kuvvetin oluşturduğu torku ifade eder.",
    historySummary: "Newton-metre, SI sisteminin temel birimlerinden (kuvvet ve uzunluk) doğrudan türetilmiştir ve mühendislikte döndürme etkisini ifade etmek için standart birim hâline gelmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, türetilmiş birim)",
    siEquivalent: "Temel SI tork birimi: 1 N·m = 1 N × 1 m",
    commonUses: "Motor torku, tork anahtarları, cıvata sıkma değerleri ve mekanik tasarım hesapları",
  },
  "kilogram-kuvvet-metre": {
    shortDescription: "Kilogram-kuvvet-metre (kgf·m, yaygın kısaltmayla \"kgm\"), tork ifade etmek için kullanılan, SI dışı geleneksel bir birimdir. Özellikle eski motor teknik dokümanlarında newton-metre yerine görülür.",
    historySummary: "Kilogram-kuvvet-metre, SI sisteminden önce Avrupa mühendislik pratiğinde yaygın kullanılan bir tork birimiydi; günümüzde yerini büyük ölçüde newton-metreye bırakmış olsa da eski araç motor spesifikasyonlarında ve bazı tork anahtarı göstergelerinde hâlâ karşılaşılır.",
    measurementSystem: "SI dışı, yerçekimine bağlı geleneksel birim",
    siEquivalent: "1 kgf·m = 9,80665 N·m",
    commonUses: "Eski motor torku spesifikasyonları, tork anahtarları, mekanik teknik dokümanlar",
  },
  "lb-ft": {
    shortDescription: "Pound-fit (lb-ft), İngiliz ve Amerikan ölçü sistemlerinde tork ifade etmek için kullanılan geleneksel bir birimdir.",
    historySummary: "Pound-fit, pound-force ve fit (foot) birimlerinin çarpımından türetilmiş olup özellikle ABD kaynaklı otomotiv ve mühendislik dokümanlarında yaygın kullanılır.",
    measurementSystem: "İngiliz ve ABD ölçü sistemleri",
    siEquivalent: "1 lb-ft ≈ 1,355818 N·m",
    commonUses: "ABD kaynaklı motor torku etiketleri, tork anahtarları ve mekanik veri sayfaları",
  },
  "newton": {
    shortDescription: "Newton (N), kuvvetin Uluslararası Birim Sistemi'ndeki türetilmiş birimidir. 1 kg kütleye 1 m/s² ivme kazandıran kuvveti ifade eder.",
    historySummary: "Newton birimi, Isaac Newton'ın hareket yasalarına atfen adlandırılmış ve 1948 yılında Uluslararası Ağırlıklar ve Ölçüler Genel Konferansı tarafından SI birimi olarak resmen kabul edilmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, türetilmiş birim)",
    siEquivalent: "Temel SI kuvvet birimi: 1 N = 1 kg·m/s²",
    commonUses: "Mekanik mühendislik, statik ve dinamik hesaplar, malzeme dayanımı testleri",
  },
  "kilogram-kuvvet": {
    shortDescription: "Kilogram-kuvvet (kgf), yerçekimi ivmesi altında 1 kilogramlık kütlenin uyguladığı kuvveti ifade eden, SI dışı geleneksel bir birimdir.",
    historySummary: "Kilogram-kuvvet, SI sisteminden önce mühendislik pratiğinde yaygın kullanılan bir kuvvet birimiydi; günümüzde yerini büyük ölçüde newtona bırakmış olsa da eski teknik dokümanlarda ve bazı ölçüm cihazlarında hâlâ karşılaşılır.",
    measurementSystem: "SI dışı, yerçekimine bağlı geleneksel birim",
    siEquivalent: "1 kgf = 9,80665 N",
    commonUses: "Eski mühendislik dokümanları, tork anahtarları, yay ve çekme testleri",
  },
  "beygirgucu-metric": {
    shortDescription: "Beygirgücü (hp), özellikle motorlu taşıtlarda motor gücünü ifade etmek için kullanılan geleneksel bir güç birimidir. Metrik beygirgücü 735,49875 watt'a eşittir.",
    historySummary: "Beygirgücü, 18. yüzyılda James Watt tarafından buhar makinelerinin gücünü at gücüyle karşılaştırmak amacıyla ortaya atılmıştır. Metrik versiyonu Avrupa'da otomotiv sektöründe yaygın standart hâline gelmiştir.",
    measurementSystem: "Metrik beygirgücü (PS/CV ailesi, SI dışı)",
    siEquivalent: "1 hp (metrik) = 735,49875 W",
    commonUses: "Otomobil ve motosiklet motor gücü, teknik veri sayfaları ve araç karşılaştırmaları",
  },
  "g-cm3": {
    shortDescription: "Gram/santimetreküp (g/cm³), laboratuvar ve kimya ortamlarında yaygın kullanılan bir yoğunluk birimidir.",
    historySummary: "Metrik sistemin ondalık yapısı içinde küçük ölçekli numunelerin yoğunluğunu pratik biçimde ifade etmek için gram ve santimetreküp birimleri birleştirilmiştir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, alt birim kombinasyonu)",
    siEquivalent: "1 g/cm³ = 1000 kg/m³",
    commonUses: "Kimya laboratuvarları, malzeme yoğunluğu tabloları ve mineraloji",
  },
  "kalori": {
    shortDescription: "Kalori (cal), bir gram suyun sıcaklığını 1°C artırmak için gereken enerji miktarı olarak tanımlanan, SI dışı bir enerji birimidir. Termokimyasal kalori tanımına göre 1 kalori 4,184 joule'e eşittir.",
    historySummary: "Kalori kavramı 19. yüzyılda, Fransız kimyager Nicolas Clément tarafından ısı miktarını ölçmek amacıyla ortaya atıldı ve termodinamiğin gelişim döneminde yaygınlaştı. Günümüzde SI birimi joule'ün yerini büyük ölçüde alması beklense de, beslenim biliminde hâlâ (kilokalori olarak) yaygın kullanılır.",
    measurementSystem: "SI dışı, geleneksel enerji birimi",
    siEquivalent: "1 cal = 4,184 J (termokimyasal tanım)",
    commonUses: "Kimya ve termodinamik hesapları, gıda enerjisi (kilokalori üzerinden)",
  },
  "kilokalori": {
    shortDescription: "Kilokalori (kcal), 1000 kaloriye eşit bir enerji birimidir. Gıda etiketlerinde ve beslenme bilgilerinde görülen \"kalori\" değeri aslında çoğunlukla kilokaloridir (bazen \"büyük Kalori\", büyük K ile, olarak da adlandırılır).",
    historySummary: "Beslenim bilimi geliştikçe, gıdaların enerji içeriğini ifade etmek için küçük kalori biriminin pratik olmadığı görüldü; bunun yerine 1000 katı büyüklüğündeki kilokalori standart hâline geldi. Gıda etiketleme mevzuatlarında bugün de bu birim esas alınır.",
    measurementSystem: "SI dışı, geleneksel enerji birimi",
    siEquivalent: "1 kcal = 4184 J = 4,184 kJ",
    commonUses: "Gıda etiketleri, diyet ve beslenme hesaplamaları, günlük kalori ihtiyacı",
  },
  "btu": {
    shortDescription: "BTU (British Thermal Unit), 1 pound suyun sıcaklığını 1°F artırmak için gereken enerji miktarı olarak tanımlanan, İngiliz/Amerikan ölçü sisteminde kullanılan bir enerji birimidir.",
    historySummary: "BTU, buhar makineleri çağında İngiltere'de ısı enerjisini ölçmek için geliştirildi ve zamanla ABD başta olmak üzere Anglosakson ülkelerde ısıtma/soğutma sektörünün standart birimi hâline geldi.",
    measurementSystem: "İngiliz ve ABD ölçü sistemleri",
    siEquivalent: "1 Btu = 1055,056 J",
    commonUses: "Klima ve ısıtıcı kapasitesi (soğutma/ısıtma gücü), doğalgaz faturaları (ABD)",
  },
  "watt-saat": {
    shortDescription: "Watt-saat (Wh), 1 watt gücün 1 saat boyunca harcadığı veya ürettiği enerji miktarını ifade eden bir birimdir. Genellikle küçük cihazların ve pillerin enerji kapasitesini belirtmek için kullanılır.",
    historySummary: "Watt-saat, elektrik enerjisi ölçümünün yaygınlaşmasıyla birlikte, güç (watt) ile zamanın (saat) çarpımından doğal olarak türetilmiş pratik bir birim olarak ortaya çıkmıştır.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, türetilmiş/pratik birim)",
    siEquivalent: "1 Wh = 3600 J (1 W × 3600 saniye)",
    commonUses: "Pil kapasitesi (mAh yerine Wh), küçük elektronik cihazların enerji tüketimi",
  },
  "kilojoule": {
    shortDescription: "Kilojoule (kJ), 1000 joule'e eşit bir enerji birimidir. Özellikle Avrupa ve Avustralya'daki gıda etiketlerinde kilokalorinin yanında veya yerine kullanılır.",
    historySummary: "Joule biriminin günlük hayattaki enerji miktarlarını ifade etmek için genelde çok küçük kalması nedeniyle, kilojoule pratik bir alt katı olarak yaygınlaşmıştır; birçok ülkenin gıda etiketleme mevzuatında zorunlu tutulur.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, ölçekli birim)",
    siEquivalent: "1 kJ = 1000 J",
    commonUses: "Gıda etiketleri (özellikle AB/Avustralya), beslenme ve enerji hesaplamaları",
  },
  "milibar": {
    shortDescription: "Milibar (mbar), bar biriminin binde biri büyüklüğünde bir basınç birimidir. Meteorolojide atmosfer basıncını ifade etmek için standart olarak kullanılır.",
    historySummary: "Bar birimi 20. yüzyıl başında meteoroloji alanında pratik kullanım için tanımlanmış, atmosfer basıncındaki günlük değişimleri ifade etmek için daha uygun büyüklükte olan milibar alt birimi yaygınlaşmıştır.",
    measurementSystem: "SI dışı, meteorolojide yaygın pratik birim",
    siEquivalent: "1 mbar = 100 Pa = 1 hPa (hektopaskal)",
    commonUses: "Hava durumu raporları, barometrik basınç ölçümü, standart atmosfer basıncı (1013,25 mbar)",
  },
  "knot": {
    shortDescription: "Knot (deniz mili/saat), saatte 1 deniz mili (1852 metre) hıza eşit olan, denizcilik ve havacılıkta kullanılan standart hız birimidir.",
    historySummary: "Knot adı, tarihsel olarak gemilerin hızını ölçmek için suya atılan ve düğümlü bir ipe bağlı tahta parçasından (\"chip log\") gelir; belirli aralıklarla düğümlenmiş ip, belirli sürede kaç düğümün açıldığı sayılarak gemi hızını verirdi.",
    measurementSystem: "SI dışı, denizcilik/havacılıkta standart birim",
    siEquivalent: "1 knot = 1852/3600 m/s ≈ 0,5144 m/s",
    commonUses: "Gemi ve uçak hızı, rüzgâr hızı (meteorolojide), denizcilik seyir hesapları",
  },
  "gun": {
    shortDescription: "Gün, Dünya'nın kendi ekseni etrafında bir tam dönüşünü (güneş günü) esas alan, 24 saate (86.400 saniyeye) eşit temel bir zaman birimidir.",
    historySummary: "Gün kavramı, insanlık tarihinin en eski ve evrensel zaman ölçüsüdür; güneşin doğuşu-batışı döngüsüne dayanır. Modern tanımda 1 gün, tam olarak 86.400 SI saniyesi olarak sabitlenmiştir (ortalama güneş günü).",
    measurementSystem: "Uluslararası Birim Sistemi (SI, ölçekli birim)",
    siEquivalent: "1 gün = 86.400 s = 24 saat",
    commonUses: "Takvim hesapları, süre/yaş hesaplamaları, seyahat ve proje planlama",
  },
  "isik-hizi": {
    shortDescription: "Işık hızı (c), boşluktaki elektromanyetik dalgaların (ışık dahil) yayılma hızıdır ve evrenin en temel fizik sabitlerinden biridir. Değeri tam olarak 299.792.458 m/s'dir.",
    historySummary: "Işık hızının ilk bilimsel ölçümleri 17. yüzyılda Ole Rømer'e kadar uzanır. 1983 yılından beri metrenin resmi SI tanımı, ışığın boşlukta belirli bir sürede aldığı yola dayandığı için ışık hızının değeri artık tanım gereği kesin (sabit) kabul edilir, ölçülen bir değer değildir.",
    measurementSystem: "Uluslararası Birim Sistemi (SI, temel fizik sabiti)",
    siEquivalent: "c = 299.792.458 m/s (tam, tanım gereği)",
    commonUses: "Fizik ve astronomi hesapları, görelilik teorisi, GPS ve uydu haberleşme sistemleri",
  },
};

const unitPageOrder = ["metre","kilometre","santimetre","milimetre","mil","fit","inc","yarda","kilogram","gram","miligram","pound","ton","ons","okka","dirhem","bizans-litrasi","bizans-onsu","pascal","kilopascal","bar","atmosfer","psi","milimetre-civa","kilogram-kuvvet-santimetrekare","metrekare","hektar","fitkare","litre","metrekup","mililitre","santigrat","fahrenhayt","kelvin","saniye","dakika","saat","metre-saniye","kilometre-saat","mil-saat","joule","kilovatsaat","watt","kilowatt","metrekup-saat","litre-dakika","volt","kilovolt","amper","miliamper","kilogram-metrekup","gram-santimetrekup","beygirgucu","newton","kilogram-kuvvet","newton-metre","pound-fit","kilogram-metre-saniye","newton-saniye","pascal-saniye","santipoise","mikrometre","nanometre","deniz-mili","arsin","endaze","bizans-ayagi","bizans-kulaci","cig","santimetrekare","milimetrekare","kilometrekare","incare","akre","donum","dekar","santimetrekup","fitkup","inckup","galon","bit","bayt","kilobayt","megabayt","gigabayt","terabayt","petabayt","kibibayt","mebibayt","gibibayt","tebibayt","ohm","kiloohm","megaohm","farad","milifarad","mikrofarad","nanofarad","pikofarad","henry","milihenry","mikrohenry","coulomb","milicoulomb","mikrocoulomb","nanocoulomb","ayar-24","ayar-22","ayar-18","ayar-14","kalori","kilokalori","btu","watt-saat","kilojoule","milibar","knot","gun","isik-hizi","varil","kilogram-kuvvet-metre"];

export const unitPages: UnitPage[] = unitRegistry
  .filter((entry) => entry.tr && unitDescriptions[entry.id])
  .map((entry) => {
    const description = unitDescriptions[entry.id];

    return {
      slug: entry.tr!.slug,
      category: entry.category,
      unit: entry.symbol,
      name: entry.tr!.name,
      symbol: entry.displaySymbol ?? entry.symbol,
      ...description,
    };
  })
  .sort(
    (a, b) => unitPageOrder.indexOf(a.slug) - unitPageOrder.indexOf(b.slug)
  );

export function findUnitPage(category: string, unit: string) {
  return unitPages.find(
    (unitPage) => unitPage.category === category && unitPage.unit === unit
  );
}
