export type UnitCategory = string;

export type LocalizedUnitName = {
  name: string;
  slug: string;
};

export type UnitRegistryEntry = {
  id: string;
  category: UnitCategory;
  symbol: string;
  displaySymbol?: string;
  siFactor?: number;
  isTemperature?: boolean;
  tr?: LocalizedUnitName;
  en?: LocalizedUnitName;
  de?: LocalizedUnitName;
  enConversionSlug?: string;
};

export const unitRegistry: UnitRegistryEntry[] = [
  // ---- uzunluk / length / Länge ----
  {
    id: "metre",
    category: "uzunluk",
    symbol: "m",
    siFactor: 1,
    tr: { name: "Metre", slug: "metre" },
    en: { name: "Meter", slug: "meter" },
    de: { name: "Meter", slug: "meter" },
    enConversionSlug: "meters",
  },
  {
    id: "kilometre",
    category: "uzunluk",
    symbol: "km",
    siFactor: 1000,
    tr: { name: "Kilometre", slug: "kilometre" },
    en: { name: "Kilometer", slug: "kilometer" },
    de: { name: "Kilometer", slug: "kilometer" },
    enConversionSlug: "kilometers",
  },
  {
    id: "santimetre",
    category: "uzunluk",
    symbol: "cm",
    siFactor: 0.01,
    tr: { name: "Santimetre", slug: "santimetre" },
    en: { name: "Centimeter", slug: "centimeter" },
    de: { name: "Zentimeter", slug: "zentimeter" },
    enConversionSlug: "centimeters",
  },
  {
    id: "milimetre",
    category: "uzunluk",
    symbol: "mm",
    siFactor: 0.001,
    tr: { name: "Milimetre", slug: "milimetre" },
    en: { name: "Millimeter", slug: "millimeter" },
    de: { name: "Millimeter", slug: "millimeter" },
    enConversionSlug: "millimeters",
  },
  {
    id: "mikrometre",
    category: "uzunluk",
    symbol: "µm",
    siFactor: 0.000001,
    tr: { name: "Mikrometre", slug: "mikrometre" },
    en: { name: "Micrometer", slug: "micrometer" },
    de: { name: "Mikrometer", slug: "mikrometer" },
  },
  {
    id: "nanometre",
    category: "uzunluk",
    symbol: "nm",
    siFactor: 1e-9,
    tr: { name: "Nanometre", slug: "nanometre" },
    en: { name: "Nanometer", slug: "nanometer" },
    de: { name: "Nanometer", slug: "nanometer" },
  },
  {
    id: "fit",
    category: "uzunluk",
    symbol: "ft",
    siFactor: 0.3048,
    tr: { name: "Fit", slug: "fit" },
    en: { name: "Foot", slug: "foot" },
    de: { name: "Fuß", slug: "fuss" },
    enConversionSlug: "feet",
  },
  {
    id: "inc",
    category: "uzunluk",
    symbol: "in",
    siFactor: 0.0254,
    tr: { name: "İnç", slug: "inc" },
    en: { name: "Inch", slug: "inch" },
    de: { name: "Zoll", slug: "zoll" },
    enConversionSlug: "inches",
  },
  {
    id: "yarda",
    category: "uzunluk",
    symbol: "yd",
    siFactor: 0.9144,
    tr: { name: "Yarda", slug: "yarda" },
    en: { name: "Yard", slug: "yard" },
    de: { name: "Yard", slug: "yard" },
    enConversionSlug: "yards",
  },
  {
    id: "mil",
    category: "uzunluk",
    symbol: "mi",
    siFactor: 1609.344,
    tr: { name: "Mil", slug: "mil" },
    en: { name: "Mile", slug: "mile" },
    de: { name: "Meile", slug: "meile" },
    enConversionSlug: "miles",
  },
  {
    id: "deniz-mili",
    category: "uzunluk",
    symbol: "nmi",
    siFactor: 1852,
    tr: { name: "Deniz mili", slug: "deniz-mili" },
    en: { name: "Nautical mile", slug: "nautical-mile" },
    de: { name: "Seemeile", slug: "seemeile" },
  },
  {
    id: "astronomik-birim",
    category: "uzunluk",
    symbol: "AU",
    siFactor: 149597870700,
    tr: { name: "Astronomik Birim", slug: "astronomik-birim" },
    en: { name: "Astronomical Unit", slug: "astronomical-unit" },
    de: { name: "Astronomische Einheit", slug: "astronomische-einheit" },
  },
  {
    id: "isik-yili",
    category: "uzunluk",
    symbol: "ly",
    siFactor: 9460730472580800,
    tr: { name: "Işık Yılı", slug: "isik-yili" },
    en: { name: "Light-year", slug: "light-year" },
    de: { name: "Lichtjahr", slug: "lichtjahr" },
  },
  {
    id: "parsek",
    category: "uzunluk",
    symbol: "pc",
    siFactor: 3.0857e16,
    tr: { name: "Parsek", slug: "parsek" },
    en: { name: "Parsec", slug: "parsec" },
    de: { name: "Parsec", slug: "parsec" },
  },
  {
    id: "angstrom",
    category: "uzunluk",
    symbol: "Å",
    siFactor: 1e-10,
    tr: { name: "Angström", slug: "angstrom" },
    en: { name: "Angstrom", slug: "angstrom" },
    de: { name: "Angström", slug: "angstroem" },
  },
  {
    id: "fathom",
    category: "uzunluk",
    symbol: "ftm",
    siFactor: 1.8288,
    tr: { name: "Kulaç (Fathom)", slug: "fathom" },
    en: { name: "Fathom", slug: "fathom" },
    de: { name: "Faden", slug: "faden" },
  },
  {
    id: "arsin",
    category: "uzunluk",
    symbol: "arşın",
    siFactor: 0.68,
    tr: { name: "Arşın", slug: "arsin" },
    en: { name: "Arshin", slug: "arshin" },
    de: { name: "Arschin", slug: "arschin" },
  },
  {
    id: "endaze",
    category: "uzunluk",
    symbol: "endaze",
    siFactor: 0.65,
    tr: { name: "Endaze", slug: "endaze" },
    en: { name: "Endaze", slug: "endaze" },
    de: { name: "Endaze", slug: "endaze" },
  },
  {
    id: "pous",
    category: "uzunluk",
    symbol: "pus",
    siFactor: 0.3148,
    tr: { name: "Bizans Ayağı", slug: "bizans-ayagi" },
    en: { name: "Byzantine Foot", slug: "byzantine-foot" },
    de: { name: "Byzantinischer Fuß", slug: "byzantinischer-fuss" },
  },
  {
    id: "orgyia",
    category: "uzunluk",
    symbol: "orgyia",
    siFactor: 1.8888,
    tr: { name: "Bizans Kulacı", slug: "bizans-kulaci" },
    en: { name: "Byzantine Fathom", slug: "byzantine-fathom" },
    de: { name: "Byzantinische Klafter", slug: "byzantinische-klafter" },
  },
  {
    id: "cig",
    category: "uzunluk",
    symbol: "çığ",
    siFactor: 0.333,
    tr: { name: "Çığ", slug: "cig" },
    en: { name: "Cig", slug: "cig" },
    de: { name: "Çığ", slug: "cig" },
  },

  // ---- alan / area / Fläche ----
  {
    id: "metrekare",
    category: "alan",
    symbol: "m²",
    siFactor: 1,
    tr: { name: "Metrekare", slug: "metrekare" },
    en: { name: "Square Meter", slug: "square-meter" },
    de: { name: "Quadratmeter", slug: "quadratmeter" },
    enConversionSlug: "square-meters",
  },
  {
    id: "santimetrekare",
    category: "alan",
    symbol: "cm²",
    siFactor: 0.0001,
    tr: { name: "Santimetrekare", slug: "santimetrekare" },
    en: { name: "Square Centimeter", slug: "square-centimeter" },
    de: { name: "Quadratzentimeter", slug: "quadratzentimeter" },
  },
  {
    id: "milimetrekare",
    category: "alan",
    symbol: "mm²",
    siFactor: 0.000001,
    tr: { name: "Milimetrekare", slug: "milimetrekare" },
    en: { name: "Square Millimeter", slug: "square-millimeter" },
    de: { name: "Quadratmillimeter", slug: "quadratmillimeter" },
  },
  {
    id: "kilometrekare",
    category: "alan",
    symbol: "km²",
    siFactor: 1_000_000,
    tr: { name: "Kilometrekare", slug: "kilometrekare" },
    en: { name: "Square Kilometer", slug: "square-kilometer" },
    de: { name: "Quadratkilometer", slug: "quadratkilometer" },
  },
  {
    id: "hektar",
    category: "alan",
    symbol: "ha",
    siFactor: 10_000,
    tr: { name: "Hektar", slug: "hektar" },
    en: { name: "Hectare", slug: "hectare" },
    de: { name: "Hektar", slug: "hektar" },
    enConversionSlug: "hectares",
  },
  {
    id: "ar",
    category: "alan",
    symbol: "a",
    siFactor: 100,
    tr: { name: "Ar", slug: "ar" },
    en: { name: "Are", slug: "are" },
    de: { name: "Ar", slug: "ar" },
  },
  {
    id: "fitkare",
    category: "alan",
    symbol: "ft²",
    siFactor: 0.092903,
    tr: { name: "Fitkare", slug: "fitkare" },
    en: { name: "Square Foot", slug: "square-foot" },
    de: { name: "Quadratfuß", slug: "quadratfuss" },
    enConversionSlug: "square-feet",
  },
  {
    id: "incare",
    category: "alan",
    symbol: "in²",
    siFactor: 0.00064516,
    tr: { name: "İnçkare", slug: "incare" },
    en: { name: "Square Inch", slug: "square-inch" },
    de: { name: "Quadratzoll", slug: "quadratzoll" },
  },
  {
    id: "akre",
    category: "alan",
    symbol: "ac",
    siFactor: 4046.8564224,
    tr: { name: "Akre", slug: "akre" },
    en: { name: "Acre", slug: "acre" },
    de: { name: "Acre", slug: "acre" },
  },
  {
    id: "donum",
    category: "alan",
    symbol: "dönüm",
    siFactor: 1000,
    tr: { name: "Dönüm", slug: "donum" },
    en: { name: "Donum", slug: "donum" },
    de: { name: "Dönüm", slug: "doenuem" },
  },
  {
    id: "dekar",
    category: "alan",
    symbol: "dekar",
    siFactor: 1000,
    tr: { name: "Dekar", slug: "dekar" },
    en: { name: "Decare", slug: "decare" },
    de: { name: "Dekar", slug: "dekar" },
  },
  {
    id: "decimal-arazi",
    category: "alan",
    symbol: "decimal",
    siFactor: 40.468564224,
    tr: { name: "Decimal (Arazi)", slug: "decimal-arazi" },
    en: { name: "Decimal (Land)", slug: "decimal-land" },
    de: { name: "Decimal (Grundstück)", slug: "decimal-grundstueck" },
  },
  {
    id: "katha",
    category: "alan",
    symbol: "katha",
    siFactor: 66.8901888,
    tr: { name: "Katha", slug: "katha" },
    en: { name: "Katha", slug: "katha" },
    de: { name: "Katha", slug: "katha" },
  },
  {
    id: "bigha",
    category: "alan",
    symbol: "bigha",
    siFactor: 1337.803776,
    tr: { name: "Bigha", slug: "bigha" },
    en: { name: "Bigha", slug: "bigha" },
    de: { name: "Bigha", slug: "bigha" },
  },

  // ---- hacim / volume / Volumen ----
  {
    id: "metrekup",
    category: "hacim",
    symbol: "m³",
    siFactor: 1,
    tr: { name: "Metreküp", slug: "metrekup" },
    en: { name: "Cubic Meter", slug: "cubic-meter" },
    de: { name: "Kubikmeter", slug: "kubikmeter" },
    enConversionSlug: "cubic-meters",
  },
  {
    id: "litre",
    category: "hacim",
    symbol: "L",
    siFactor: 0.001,
    tr: { name: "Litre", slug: "litre" },
    en: { name: "Liter", slug: "liter" },
    de: { name: "Liter", slug: "liter" },
    enConversionSlug: "liters",
  },
  {
    id: "mililitre",
    category: "hacim",
    symbol: "mL",
    siFactor: 0.000001,
    tr: { name: "Mililitre", slug: "mililitre" },
    en: { name: "Milliliter", slug: "milliliter" },
    de: { name: "Milliliter", slug: "milliliter" },
    enConversionSlug: "milliliters",
  },
  {
    id: "santimetrekup",
    category: "hacim",
    symbol: "cm³",
    siFactor: 0.000001,
    tr: { name: "Santimetreküp", slug: "santimetrekup" },
    en: { name: "Cubic Centimeter", slug: "cubic-centimeter" },
    de: { name: "Kubikzentimeter", slug: "kubikzentimeter" },
  },
  {
    id: "fitkup",
    category: "hacim",
    symbol: "ft³",
    siFactor: 0.0283168,
    tr: { name: "Fitküp", slug: "fitkup" },
    en: { name: "Cubic Foot", slug: "cubic-foot" },
    de: { name: "Kubikfuß", slug: "kubikfuss" },
  },
  {
    id: "inckup",
    category: "hacim",
    symbol: "in³",
    siFactor: 0.0000163871,
    tr: { name: "İnçküp", slug: "inckup" },
    en: { name: "Cubic Inch", slug: "cubic-inch" },
    de: { name: "Kubikzoll", slug: "kubikzoll" },
  },
  {
    id: "galon",
    category: "hacim",
    symbol: "gal",
    siFactor: 0.00378541,
    tr: { name: "Galon", slug: "galon" },
    en: { name: "Gallon", slug: "gallon" },
    de: { name: "Gallone", slug: "gallone" },
  },
  {
    id: "ingiliz-galonu",
    category: "hacim",
    symbol: "imp gal",
    siFactor: 0.00454609,
    tr: { name: "İngiliz Galonu", slug: "ingiliz-galonu" },
    en: { name: "Imperial Gallon", slug: "imperial-gallon" },
    de: { name: "Imperiale Gallone", slug: "imperiale-gallone" },
  },
  {
    id: "varil",
    category: "hacim",
    symbol: "bbl",
    siFactor: 0.158987,
    tr: { name: "Varil (petrol)", slug: "varil" },
    en: { name: "Barrel", slug: "barrel" },
    de: { name: "Barrel", slug: "barrel" },
  },

  // ---- kutle / mass / Masse ----
  {
    id: "kilogram",
    category: "kutle",
    symbol: "kg",
    siFactor: 1,
    tr: { name: "Kilogram", slug: "kilogram" },
    en: { name: "Kilogram", slug: "kilogram" },
    de: { name: "Kilogramm", slug: "kilogramm" },
    enConversionSlug: "kilograms",
  },
  {
    id: "gram",
    category: "kutle",
    symbol: "g",
    siFactor: 0.001,
    tr: { name: "Gram", slug: "gram" },
    en: { name: "Gram", slug: "gram" },
    de: { name: "Gramm", slug: "gramm" },
    enConversionSlug: "grams",
  },
  {
    id: "miligram",
    category: "kutle",
    symbol: "mg",
    siFactor: 0.000001,
    tr: { name: "Miligram", slug: "miligram" },
    en: { name: "Milligram", slug: "milligram" },
    de: { name: "Milligramm", slug: "milligramm" },
    enConversionSlug: "milligrams",
  },
  {
    id: "ton",
    category: "kutle",
    symbol: "ton",
    displaySymbol: "t",
    siFactor: 1000,
    tr: { name: "Ton", slug: "ton" },
    en: { name: "Tonne", slug: "tonne" },
    de: { name: "Tonne", slug: "tonne" },
    enConversionSlug: "tonnes",
  },
  {
    id: "pound",
    category: "kutle",
    symbol: "lb",
    siFactor: 0.45359237,
    tr: { name: "Pound", slug: "pound" },
    en: { name: "Pound", slug: "pound" },
    de: { name: "Pfund", slug: "pfund" },
    enConversionSlug: "pounds",
  },
  {
    id: "grain",
    category: "kutle",
    symbol: "gr",
    siFactor: 0.00006479891,
    tr: { name: "Grain", slug: "grain" },
    en: { name: "Grain", slug: "grain" },
    de: { name: "Grain", slug: "grain" },
  },
  {
    id: "dalton",
    category: "kutle",
    symbol: "Da",
    siFactor: 1.66053906892e-27,
    tr: { name: "Dalton", slug: "dalton" },
    en: { name: "Dalton", slug: "dalton" },
    de: { name: "Dalton", slug: "dalton" },
  },
  {
    id: "ons",
    category: "kutle",
    symbol: "oz",
    siFactor: 0.028349523125,
    tr: { name: "Ons", slug: "ons" },
    en: { name: "Ounce", slug: "ounce" },
    de: { name: "Unze", slug: "unze" },
    enConversionSlug: "ounces",
  },
  {
    id: "okka",
    category: "kutle",
    symbol: "okka",
    siFactor: 1.282945,
    tr: { name: "Okka", slug: "okka" },
    en: { name: "Okka", slug: "okka" },
    de: { name: "Okka", slug: "okka" },
  },
  {
    id: "dirhem",
    category: "kutle",
    symbol: "dirhem",
    siFactor: 0.0032073625,
    tr: { name: "Dirhem", slug: "dirhem" },
    en: { name: "Dirham", slug: "dirham" },
    de: { name: "Dirham", slug: "dirham" },
  },
  {
    id: "litra",
    category: "kutle",
    symbol: "litra",
    siFactor: 0.324,
    tr: { name: "Bizans Litrası", slug: "bizans-litrasi" },
    en: { name: "Byzantine Litra", slug: "byzantine-litra" },
    de: { name: "Byzantinische Litra", slug: "byzantinische-litra" },
  },
  {
    id: "ounkia",
    category: "kutle",
    symbol: "ounkia",
    siFactor: 0.027,
    tr: { name: "Bizans Onsu", slug: "bizans-onsu" },
    en: { name: "Byzantine Ounce", slug: "byzantine-ounce" },
    de: { name: "Byzantinische Ounkia", slug: "byzantinische-ounkia" },
  },
  {
    id: "troy-ons",
    category: "kutle",
    symbol: "ozt",
    siFactor: 0.0311034768,
    tr: { name: "Troy Ons", slug: "troy-ons" },
    en: { name: "Troy Ounce", slug: "troy-ounce" },
    de: { name: "Feinunze", slug: "feinunze" },
    enConversionSlug: "troy-ounces",
  },
  {
    id: "karat",
    category: "kutle",
    symbol: "ct",
    siFactor: 0.0002,
    tr: { name: "Karat", slug: "karat" },
    en: { name: "Carat", slug: "carat" },
    de: { name: "Karat", slug: "karat" },
    enConversionSlug: "carats",
  },

  // ---- yoğunluk / density (engine-only, no public pages) ----
  {
    id: "kg-m3",
    category: "yogunluk",
    symbol: "kg/m³",
    siFactor: 1,
    tr: { name: "Kilogram/Metreküp", slug: "kilogram-metrekup" },
    en: { name: "Kilogram per Cubic Meter", slug: "kilogram-per-cubic-meter" },
    de: { name: "Kilogramm/Kubikmeter", slug: "kilogramm-kubikmeter" },
  },
  {
    id: "g-cm3",
    category: "yogunluk",
    symbol: "g/cm³",
    siFactor: 1000,
    tr: { name: "Gram/Santimetreküp", slug: "gram-santimetrekup" },
    en: { name: "Gram per Cubic Centimeter", slug: "gram-per-cubic-centimeter" },
    de: { name: "Gramm/Kubikzentimeter", slug: "gramm-kubikzentimeter" },
  },
  { id: "g-ml", category: "yogunluk", symbol: "g/mL", siFactor: 1000, tr: { name: "Gram/Mililitre", slug: "gram-mililitre" } },
  { id: "kg-l", category: "yogunluk", symbol: "kg/L", siFactor: 1000, tr: { name: "Kilogram/Litre", slug: "kilogram-litre" } },
  { id: "g-l", category: "yogunluk", symbol: "g/L", siFactor: 1, tr: { name: "Gram/Litre", slug: "gram-litre" } },
  { id: "mg-l", category: "yogunluk", symbol: "mg/L", siFactor: 0.001, tr: { name: "Miligram/Litre", slug: "miligram-litre" } },
  { id: "lb-ft3", category: "yogunluk", symbol: "lb/ft³", siFactor: 16.01846337, tr: { name: "Pound/Fitküp", slug: "pound-fitkup" } },
  { id: "lb-in3", category: "yogunluk", symbol: "lb/in³", siFactor: 27679.90471, tr: { name: "Pound/İnçküp", slug: "pound-inckup" } },
  { id: "lb-gal-us", category: "yogunluk", symbol: "lb/gal (US)", siFactor: 119.826427, tr: { name: "Pound/Galon (US)", slug: "pound-galon" } },
  { id: "slug-ft3", category: "yogunluk", symbol: "slug/ft³", siFactor: 515.378818, tr: { name: "Slug/Fitküp", slug: "slug-fitkup" } },

  // ---- hız / speed / Geschwindigkeit ----
  {
    id: "metre-saniye",
    category: "hiz",
    symbol: "m/s",
    siFactor: 1,
    tr: { name: "Metre/Saniye", slug: "metre-saniye" },
    en: { name: "Meter per Second", slug: "meter-per-second" },
    de: { name: "Meter pro Sekunde", slug: "meter-pro-sekunde" },
    enConversionSlug: "meters-per-second",
  },
  {
    id: "kilometre-saat",
    category: "hiz",
    symbol: "km/h",
    siFactor: 1000 / 3600,
    tr: { name: "Kilometre/Saat", slug: "kilometre-saat" },
    en: { name: "Kilometer per Hour", slug: "kilometer-per-hour" },
    de: { name: "Kilometer pro Stunde", slug: "kilometer-pro-stunde" },
    enConversionSlug: "kilometers-per-hour",
  },
  { id: "km-s", category: "hiz", symbol: "km/s", siFactor: 1000, tr: { name: "Kilometre/Saniye", slug: "kilometre-saniye" } },
  {
    id: "mil-saat",
    category: "hiz",
    symbol: "mph",
    siFactor: 1609.344 / 3600,
    tr: { name: "Mil/Saat", slug: "mil-saat" },
    en: { name: "Mile per Hour", slug: "mile-per-hour" },
    de: { name: "Meilen pro Stunde", slug: "meilen-pro-stunde" },
    enConversionSlug: "miles-per-hour",
  },
  {
    id: "knot",
    category: "hiz",
    symbol: "knot",
    siFactor: 1852 / 3600,
    tr: { name: "Knot", slug: "knot" },
    en: { name: "Knot", slug: "knot" },
    de: { name: "Knoten", slug: "knoten" },
  },
  { id: "ft-s", category: "hiz", symbol: "ft/s", siFactor: 0.3048, tr: { name: "Fit/Saniye", slug: "fit-saniye" } },
  { id: "m-min", category: "hiz", symbol: "m/min", siFactor: 1 / 60, tr: { name: "Metre/Dakika", slug: "metre-dakika" } },
  { id: "km-min", category: "hiz", symbol: "km/min", siFactor: 1000 / 60, tr: { name: "Kilometre/Dakika", slug: "kilometre-dakika" } },
  { id: "cm-s", category: "hiz", symbol: "cm/s", siFactor: 0.01, tr: { name: "Santimetre/Saniye", slug: "santimetre-saniye" } },
  {
    id: "isik-hizi",
    category: "hiz",
    symbol: "c",
    siFactor: 299792458,
    tr: { name: "Işık Hızı", slug: "isik-hizi" },
    en: { name: "Speed of Light", slug: "speed-of-light" },
    de: { name: "Lichtgeschwindigkeit", slug: "lichtgeschwindigkeit" },
  },

  // ---- ivme / acceleration (engine-only) ----
  {
    id: "m-s2",
    category: "ivme",
    symbol: "m/s²",
    siFactor: 1,
    tr: { name: "Metre/saniyekare", slug: "metre-saniyekare" },
    en: { name: "Meter per Second Squared", slug: "meter-per-second-squared" },
    de: { name: "Meter pro Sekundequadrat", slug: "meter-pro-sekundequadrat" },
  },
  { id: "cm-s2", category: "ivme", symbol: "cm/s²", siFactor: 0.01, tr: { name: "Santimetre/saniyekare", slug: "santimetre-saniyekare" } },
  { id: "mm-s2", category: "ivme", symbol: "mm/s²", siFactor: 0.001, tr: { name: "Milimetre/saniyekare", slug: "milimetre-saniyekare" } },
  { id: "km-s2", category: "ivme", symbol: "km/s²", siFactor: 1000, tr: { name: "Kilometre/saniyekare", slug: "kilometre-saniyekare" } },
  {
    id: "ft-s2",
    category: "ivme",
    symbol: "ft/s²",
    siFactor: 0.3048,
    tr: { name: "Fit/saniyekare", slug: "fit-saniyekare" },
    en: { name: "Foot per Second Squared", slug: "foot-per-second-squared" },
    de: { name: "Fuß pro Sekundequadrat", slug: "fuss-pro-sekundequadrat" },
  },
  { id: "in-s2", category: "ivme", symbol: "in/s²", siFactor: 0.0254, tr: { name: "İnç/saniyekare", slug: "inc-saniyekare" } },
  { id: "m-min2", category: "ivme", symbol: "m/min²", siFactor: 1 / 3600, tr: { name: "Metre/dakikakare", slug: "metre-dakikakare" } },
  { id: "ft-min2", category: "ivme", symbol: "ft/min²", siFactor: 0.3048 / 3600, tr: { name: "Fit/dakikakare", slug: "fit-dakikakare" } },
  { id: "ivme-gal", category: "ivme", symbol: "gal", siFactor: 0.01, tr: { name: "Gal (ivme birimi)", slug: "gal-ivme" } },
  {
    id: "g0",
    category: "ivme",
    symbol: "g0",
    siFactor: 9.80665,
    tr: { name: "Yerçekimi ivmesi (g)", slug: "yercekimi-ivmesi" },
    en: { name: "Standard Gravity (g)", slug: "standard-gravity" },
    de: { name: "Erdbeschleunigung (g)", slug: "erdbeschleunigung" },
  },

  // ---- zaman / time / Zeit ----
  {
    id: "saniye",
    category: "zaman",
    symbol: "s",
    siFactor: 1,
    tr: { name: "Saniye", slug: "saniye" },
    en: { name: "Second", slug: "second" },
    de: { name: "Sekunde", slug: "sekunde" },
    enConversionSlug: "seconds",
  },
  { id: "milisaniye", category: "zaman", symbol: "ms", siFactor: 0.001, tr: { name: "Milisaniye", slug: "milisaniye" } },
  {
    id: "dakika",
    category: "zaman",
    symbol: "min",
    siFactor: 60,
    tr: { name: "Dakika", slug: "dakika" },
    en: { name: "Minute", slug: "minute" },
    de: { name: "Minute", slug: "minute" },
    enConversionSlug: "minutes",
  },
  {
    id: "saat",
    category: "zaman",
    symbol: "h",
    siFactor: 3600,
    tr: { name: "Saat", slug: "saat" },
    en: { name: "Hour", slug: "hour" },
    de: { name: "Stunde", slug: "stunde" },
    enConversionSlug: "hours",
  },
  {
    id: "gun",
    category: "zaman",
    symbol: "day",
    siFactor: 86400,
    tr: { name: "Gün", slug: "gun" },
    en: { name: "Day", slug: "day" },
    de: { name: "Tag", slug: "tag" },
  },

  // ---- açısal hız (engine-only) ----
  {
    id: "rad-s",
    category: "acisal_hiz",
    symbol: "rad/s",
    siFactor: 1,
    tr: { name: "Radyan/saniye", slug: "radyan-saniye" },
    en: { name: "Radian per Second", slug: "radian-per-second" },
    de: { name: "Radiant pro Sekunde", slug: "radiant-pro-sekunde" },
  },
  { id: "rad-min", category: "acisal_hiz", symbol: "rad/min", siFactor: 1 / 60, tr: { name: "Radyan/dakika", slug: "radyan-dakika" } },
  { id: "rad-h", category: "acisal_hiz", symbol: "rad/h", siFactor: 1 / 3600, tr: { name: "Radyan/saat", slug: "radyan-saat" } },
  {
    id: "rpm",
    category: "acisal_hiz",
    symbol: "rpm",
    siFactor: (2 * Math.PI) / 60,
    tr: { name: "Devir/dakika (RPM)", slug: "devir-dakika" },
    en: { name: "Revolutions per Minute (RPM)", slug: "rpm" },
    de: { name: "Umdrehungen pro Minute (U/min)", slug: "umdrehungen-pro-minute" },
  },
  { id: "hz", category: "acisal_hiz", symbol: "Hz", siFactor: 2 * Math.PI, tr: { name: "Devir/saniye", slug: "devir-saniye-acisal" } },
  {
    id: "deg-s",
    category: "acisal_hiz",
    symbol: "°/s",
    siFactor: Math.PI / 180,
    tr: { name: "Derece/saniye", slug: "derece-saniye" },
    en: { name: "Degree per Second", slug: "degree-per-second" },
    de: { name: "Grad pro Sekunde", slug: "grad-pro-sekunde" },
  },
  { id: "deg-min", category: "acisal_hiz", symbol: "°/min", siFactor: Math.PI / (180 * 60), tr: { name: "Derece/dakika", slug: "derece-dakika" } },
  { id: "deg-h", category: "acisal_hiz", symbol: "°/h", siFactor: Math.PI / (180 * 3600), tr: { name: "Derece/saat", slug: "derece-saat" } },

  // ---- açı / angle / Winkel ----
  {
    id: "radyan",
    category: "aci",
    symbol: "rad",
    siFactor: 1,
    tr: { name: "Radyan", slug: "radyan" },
    en: { name: "Radian", slug: "radian" },
    de: { name: "Radiant", slug: "radiant" },
  },
  {
    id: "derece",
    category: "aci",
    symbol: "°",
    siFactor: Math.PI / 180,
    tr: { name: "Derece", slug: "derece" },
    en: { name: "Degree", slug: "degree" },
    de: { name: "Grad", slug: "grad" },
  },
  {
    id: "gradyan",
    category: "aci",
    symbol: "gon",
    siFactor: Math.PI / 200,
    tr: { name: "Gradyan", slug: "gradyan" },
    en: { name: "Gradian", slug: "gradian" },
    de: { name: "Gon", slug: "gon" },
  },
  {
    id: "tam-tur",
    category: "aci",
    symbol: "tur",
    siFactor: 2 * Math.PI,
    tr: { name: "Tam Tur", slug: "tam-tur" },
    en: { name: "Full Turn", slug: "full-turn" },
    de: { name: "Vollwinkel", slug: "vollwinkel" },
  },

  // ---- frekans / frequency / Frequenz ----
  {
    id: "hertz",
    category: "frekans",
    symbol: "Hz",
    siFactor: 1,
    tr: { name: "Hertz", slug: "hertz" },
    en: { name: "Hertz", slug: "hertz" },
    de: { name: "Hertz", slug: "hertz" },
  },
  {
    id: "kilohertz",
    category: "frekans",
    symbol: "kHz",
    siFactor: 1000,
    tr: { name: "Kilohertz", slug: "kilohertz" },
    en: { name: "Kilohertz", slug: "kilohertz" },
    de: { name: "Kilohertz", slug: "kilohertz" },
  },
  {
    id: "megahertz",
    category: "frekans",
    symbol: "MHz",
    siFactor: 1_000_000,
    tr: { name: "Megahertz", slug: "megahertz" },
    en: { name: "Megahertz", slug: "megahertz" },
    de: { name: "Megahertz", slug: "megahertz" },
  },
  {
    id: "gigahertz",
    category: "frekans",
    symbol: "GHz",
    siFactor: 1_000_000_000,
    tr: { name: "Gigahertz", slug: "gigahertz" },
    en: { name: "Gigahertz", slug: "gigahertz" },
    de: { name: "Gigahertz", slug: "gigahertz" },
  },

  // ---- kuvvet / tork / momentum (engine-only) ----
  {
    id: "newton",
    category: "kuvvet",
    symbol: "N",
    siFactor: 1,
    tr: { name: "Newton", slug: "newton" },
    en: { name: "Newton", slug: "newton" },
    de: { name: "Newton", slug: "newton" },
  },
  { id: "kilonewton", category: "kuvvet", symbol: "kN", siFactor: 1000, tr: { name: "Kilonewton", slug: "kilonewton" } },
  { id: "dyn", category: "kuvvet", symbol: "dyn", siFactor: 0.00001, tr: { name: "Dyn", slug: "dyn" } },
  { id: "lbf", category: "kuvvet", symbol: "lbf", siFactor: 4.4482216, tr: { name: "Pound-kuvvet", slug: "pound-kuvvet" } },
  {
    id: "kilogram-kuvvet",
    category: "kuvvet",
    symbol: "kgf",
    siFactor: 9.80665,
    tr: { name: "Kilogram-kuvvet", slug: "kilogram-kuvvet" },
    en: { name: "Kilogram-Force", slug: "kilogram-force" },
    de: { name: "Kilogramm-Kraft", slug: "kilogramm-kraft" },
  },
  {
    id: "newton-metre",
    category: "tork",
    symbol: "N·m",
    siFactor: 1,
    tr: { name: "Newton-metre", slug: "newton-metre" },
    en: { name: "Newton-Meter", slug: "newton-meter" },
    de: { name: "Newtonmeter", slug: "newtonmeter" },
  },
  { id: "kilonewton-metre", category: "tork", symbol: "kN·m", siFactor: 1000, tr: { name: "Kilonewton-metre", slug: "kilonewton-metre" } },
  {
    id: "kilogram-kuvvet-metre",
    category: "tork",
    symbol: "kgf·m",
    siFactor: 9.80665,
    tr: { name: "Kilogram-kuvvet-metre", slug: "kilogram-kuvvet-metre" },
    en: { name: "Kilogram-Force Meter", slug: "kilogram-force-meter" },
    de: { name: "Kilogramm-Kraft-Meter", slug: "kilogramm-kraft-meter" },
  },
  {
    id: "lb-ft",
    category: "tork",
    symbol: "lb·ft",
    siFactor: 1.355817948,
    tr: { name: "Pound-fit (lb-ft)", slug: "pound-fit" },
    en: { name: "Pound-Foot", slug: "pound-foot" },
    de: { name: "Pfund-Fuß", slug: "pfund-fuss" },
  },
  {
    id: "kg-m-s",
    category: "momentum",
    symbol: "kg·m/s",
    siFactor: 1,
    tr: { name: "Kilogram-metre/saniye", slug: "kilogram-metre-saniye" },
    en: { name: "Kilogram-Meter per Second", slug: "kilogram-meter-per-second" },
    de: { name: "Kilogramm-Meter/Sekunde", slug: "kilogramm-meter-sekunde" },
  },
  {
    id: "n-s",
    category: "momentum",
    symbol: "N·s",
    siFactor: 1,
    tr: { name: "Newton-saniye", slug: "newton-saniye" },
    en: { name: "Newton-Second", slug: "newton-second" },
    de: { name: "Newtonsekunde", slug: "newtonsekunde" },
  },
  { id: "lb-ft-s", category: "momentum", symbol: "lb·ft/s", siFactor: 0.138255, tr: { name: "Pound-fit/saniye", slug: "pound-fit-saniye" } },

  // ---- basınç / pressure / Druck ----
  {
    id: "pascal",
    category: "basinc",
    symbol: "Pa",
    siFactor: 1,
    tr: { name: "Pascal", slug: "pascal" },
    en: { name: "Pascal", slug: "pascal" },
    de: { name: "Pascal", slug: "pascal" },
    enConversionSlug: "pascals",
  },
  {
    id: "kilopascal",
    category: "basinc",
    symbol: "kPa",
    siFactor: 1000,
    tr: { name: "Kilopascal", slug: "kilopascal" },
    en: { name: "Kilopascal", slug: "kilopascal" },
    de: { name: "Kilopascal", slug: "kilopascal" },
    enConversionSlug: "kilopascals",
  },
  {
    id: "bar",
    category: "basinc",
    symbol: "bar",
    siFactor: 100000,
    tr: { name: "Bar", slug: "bar" },
    en: { name: "Bar", slug: "bar" },
    de: { name: "Bar", slug: "bar" },
    enConversionSlug: "bars",
  },
  {
    id: "milibar",
    category: "basinc",
    symbol: "mbar",
    siFactor: 100,
    tr: { name: "Milibar", slug: "milibar" },
    en: { name: "Millibar", slug: "millibar" },
    de: { name: "Millibar", slug: "millibar" },
  },
  {
    id: "atmosfer",
    category: "basinc",
    symbol: "atm",
    siFactor: 101325,
    tr: { name: "Atmosfer", slug: "atmosfer" },
    en: { name: "Atmosphere", slug: "atmosphere" },
    de: { name: "Atmosphäre", slug: "atmosphaere" },
    enConversionSlug: "atmospheres",
  },
  { id: "teknik-atmosfer", category: "basinc", symbol: "at", siFactor: 98066.5, tr: { name: "Teknik Atmosfer", slug: "teknik-atmosfer" } },
  {
    id: "psi",
    category: "basinc",
    symbol: "psi",
    siFactor: 6894.757293168,
    tr: { name: "PSI", slug: "psi" },
    en: { name: "PSI", slug: "psi" },
    de: { name: "PSI", slug: "psi" },
    enConversionSlug: "psi",
  },
  {
    id: "milimetre-civa",
    category: "basinc",
    symbol: "mmHg",
    siFactor: 133.322387415,
    tr: { name: "Milimetre Cıva", slug: "milimetre-civa" },
    en: { name: "Millimeter of Mercury", slug: "millimeter-of-mercury" },
    de: { name: "Millimeter Quecksilbersäule", slug: "millimeter-quecksilbersaeule" },
    enConversionSlug: "millimeters-of-mercury",
  },
  { id: "mmh2o", category: "basinc", symbol: "mmH2O", siFactor: 9.80665, tr: { name: "Milimetre Su Sütunu", slug: "milimetre-su-sutunu" } },
  {
    id: "torr",
    category: "basinc",
    symbol: "Torr",
    siFactor: 101325 / 760,
    tr: { name: "Torr", slug: "torr" },
    en: { name: "Torr", slug: "torr" },
    de: { name: "Torr", slug: "torr" },
  },
  {
    id: "kilogram-kuvvet-santimetrekare",
    category: "basinc",
    symbol: "kgf/cm²",
    siFactor: 98066.5,
    tr: { name: "Kilogram-kuvvet/Santimetrekare", slug: "kilogram-kuvvet-santimetrekare" },
    en: {
      name: "Kilogram-Force per Square Centimeter",
      slug: "kilogram-force-per-square-centimeter",
    },
    de: {
      name: "Kilogramm-Kraft pro Quadratzentimeter",
      slug: "kilogramm-kraft-pro-quadratzentimeter",
    },
    enConversionSlug: "kilogram-force-per-square-centimeter",
  },

  // ---- viskozite (engine-only) ----
  {
    id: "pascal-saniye",
    category: "viskozite_dinamik",
    symbol: "Pa·s",
    siFactor: 1,
    tr: { name: "Pascal-saniye", slug: "pascal-saniye" },
    en: { name: "Pascal-Second", slug: "pascal-second" },
    de: { name: "Pascalsekunde", slug: "pascalsekunde" },
  },
  { id: "milipascal-saniye", category: "viskozite_dinamik", symbol: "mPa·s", siFactor: 0.001, tr: { name: "Milipaskal-saniye", slug: "milipaskal-saniye" } },
  { id: "poise", category: "viskozite_dinamik", symbol: "P", siFactor: 0.1, tr: { name: "Poise", slug: "poise" } },
  {
    id: "centipoise",
    category: "viskozite_dinamik",
    symbol: "cP",
    siFactor: 0.001,
    tr: { name: "Santipoise", slug: "santipoise" },
    en: { name: "Centipoise", slug: "centipoise" },
    de: { name: "Centipoise", slug: "centipoise" },
  },
  {
    id: "m2-s",
    category: "viskozite_kinematik",
    symbol: "m²/s",
    siFactor: 1,
    tr: { name: "Metrekare/saniye", slug: "metrekare-saniye" },
    en: { name: "Square Meter per Second", slug: "square-meter-per-second" },
    de: { name: "Quadratmeter pro Sekunde", slug: "quadratmeter-pro-sekunde" },
  },
  { id: "mm2-s", category: "viskozite_kinematik", symbol: "mm²/s", siFactor: 0.000001, tr: { name: "Milimetrekare/saniye", slug: "milimetrekare-saniye" } },
  {
    id: "centistoke",
    category: "viskozite_kinematik",
    symbol: "cSt",
    siFactor: 0.000001,
    tr: { name: "Santistok", slug: "santistok" },
    en: { name: "Centistoke", slug: "centistoke" },
    de: { name: "Zentistokes", slug: "zentistokes" },
  },

  // ---- debi_hacimsel / debi_kutlesel (engine-only) ----
  {
    id: "m3-s",
    category: "debi_hacimsel",
    symbol: "m³/s",
    siFactor: 1,
    tr: { name: "Metreküp/saniye", slug: "metrekup-saniye" },
    en: { name: "Cubic Meter per Second", slug: "cubic-meter-per-second" },
    de: { name: "Kubikmeter pro Sekunde", slug: "kubikmeter-pro-sekunde" },
  },
  { id: "l-s", category: "debi_hacimsel", symbol: "L/s", siFactor: 0.001, tr: { name: "Litre/saniye", slug: "litre-saniye" } },
  { id: "m3-h-hacimsel", category: "debi_hacimsel", symbol: "m³/h", siFactor: 1 / 3600, tr: { name: "Metreküp/saat", slug: "metrekup-saat-hacimsel" } },
  { id: "l-min-hacimsel", category: "debi_hacimsel", symbol: "L/min", siFactor: 0.001 / 60, tr: { name: "Litre/dakika", slug: "litre-dakika-hacimsel" } },
  {
    id: "cfm",
    category: "debi_hacimsel",
    symbol: "cfm",
    siFactor: 0.0283168 / 60,
    tr: { name: "Fitküp/dakika (CFM)", slug: "fitkup-dakika" },
    en: { name: "Cubic Feet per Minute (CFM)", slug: "cubic-feet-per-minute" },
    de: { name: "Kubikfuß pro Minute (CFM)", slug: "kubikfuss-pro-minute" },
  },
  {
    id: "gpm",
    category: "debi_hacimsel",
    symbol: "gpm",
    siFactor: 0.00378541 / 60,
    tr: { name: "Galon/dakika (GPM)", slug: "galon-dakika" },
    en: { name: "Gallons per Minute (GPM)", slug: "gallons-per-minute" },
    de: { name: "Gallonen pro Minute (GPM)", slug: "gallonen-pro-minute" },
  },
  {
    id: "kg-s",
    category: "debi_kutlesel",
    symbol: "kg/s",
    siFactor: 1,
    tr: { name: "Kilogram/saniye", slug: "kilogram-saniye" },
    en: { name: "Kilogram per Second", slug: "kilogram-per-second" },
    de: { name: "Kilogramm pro Sekunde", slug: "kilogramm-pro-sekunde" },
  },
  {
    id: "kg-h",
    category: "debi_kutlesel",
    symbol: "kg/h",
    siFactor: 1 / 3600,
    tr: { name: "Kilogram/saat", slug: "kilogram-saat" },
    en: { name: "Kilogram per Hour", slug: "kilogram-per-hour" },
    de: { name: "Kilogramm pro Stunde", slug: "kilogramm-pro-stunde" },
  },
  { id: "g-s", category: "debi_kutlesel", symbol: "g/s", siFactor: 0.001, tr: { name: "Gram/saniye", slug: "gram-saniye" } },
  { id: "g-h", category: "debi_kutlesel", symbol: "g/h", siFactor: 0.001 / 3600, tr: { name: "Gram/saat", slug: "gram-saat" } },

  // ---- enerji / energy / Energie ----
  {
    id: "joule",
    category: "enerji",
    symbol: "J",
    siFactor: 1,
    tr: { name: "Joule", slug: "joule" },
    en: { name: "Joule", slug: "joule" },
    de: { name: "Joule", slug: "joule" },
    enConversionSlug: "joules",
  },
  {
    id: "kilojoule",
    category: "enerji",
    symbol: "kJ",
    siFactor: 1000,
    tr: { name: "Kilojoule", slug: "kilojoule" },
    en: { name: "Kilojoule", slug: "kilojoule" },
    de: { name: "Kilojoule", slug: "kilojoule" },
  },
  { id: "megajoule", category: "enerji", symbol: "MJ", siFactor: 1_000_000, tr: { name: "Megajoule", slug: "megajoule" } },
  {
    id: "watt-saat",
    category: "enerji",
    symbol: "Wh",
    siFactor: 3600,
    tr: { name: "Watt-saat", slug: "watt-saat" },
    en: { name: "Watt-hour", slug: "watt-hour" },
    de: { name: "Wattstunde", slug: "wattstunde" },
  },
  {
    id: "kilovatsaat",
    category: "enerji",
    symbol: "kWh",
    siFactor: 3_600_000,
    tr: { name: "Kilovat-saat", slug: "kilovatsaat" },
    en: { name: "Kilowatt-hour", slug: "kilowatt-hour" },
    de: { name: "Kilowattstunde", slug: "kilowattstunde" },
    enConversionSlug: "kilowatt-hours",
  },
  {
    id: "watt",
    category: "guc",
    symbol: "W",
    siFactor: 1,
    tr: { name: "Watt", slug: "watt" },
    en: { name: "Watt", slug: "watt" },
    de: { name: "Watt", slug: "watt" },
    enConversionSlug: "watts",
  },
  {
    id: "kilowatt",
    category: "guc",
    symbol: "kW",
    siFactor: 1000,
    tr: { name: "Kilowatt", slug: "kilowatt" },
    en: { name: "Kilowatt", slug: "kilowatt" },
    de: { name: "Kilowatt", slug: "kilowatt" },
    enConversionSlug: "kilowatts",
  },
  {
    id: "kalori",
    category: "enerji",
    symbol: "cal",
    siFactor: 4.184,
    tr: { name: "Kalori", slug: "kalori" },
    en: { name: "Calorie", slug: "calorie" },
    de: { name: "Kalorie", slug: "kalorie" },
  },
  {
    id: "kilokalori",
    category: "enerji",
    symbol: "kcal",
    siFactor: 4184,
    tr: { name: "Kilokalori", slug: "kilokalori" },
    en: { name: "Kilocalorie", slug: "kilocalorie" },
    de: { name: "Kilokalorie", slug: "kilokalorie" },
  },
  {
    id: "btu",
    category: "enerji",
    symbol: "Btu",
    siFactor: 1055.056,
    tr: { name: "BTU", slug: "btu" },
    en: { name: "British Thermal Unit", slug: "btu" },
    de: { name: "BTU", slug: "btu" },
  },
  { id: "therm", category: "enerji", symbol: "th", siFactor: 1.05506e8, tr: { name: "Therm", slug: "therm" } },
  { id: "quad-btu", category: "enerji", symbol: "quad BTU", siFactor: 1.05506e18, tr: { name: "Quad BTU", slug: "quad-btu" } },
  {
    id: "elektronvolt",
    category: "enerji",
    symbol: "eV",
    siFactor: 1.602176634e-19,
    tr: { name: "Elektronvolt", slug: "elektronvolt" },
    en: { name: "Electronvolt", slug: "electronvolt" },
    de: { name: "Elektronenvolt", slug: "elektronenvolt" },
  },

  // ---- güç ----
  {
    id: "megawatt",
    category: "guc",
    symbol: "MW",
    siFactor: 1_000_000,
    tr: { name: "Megawatt", slug: "megawatt" },
    en: { name: "Megawatt", slug: "megawatt" },
    de: { name: "Megawatt", slug: "megawatt" },
  },
  {
    id: "beygirgucu-metric",
    category: "guc",
    symbol: "hp",
    siFactor: 735.49875,
    tr: { name: "Beygirgücü", slug: "beygirgucu" },
    en: { name: "Horsepower", slug: "horsepower" },
    de: { name: "PS", slug: "ps" },
  },
  {
    id: "beygirgucu-mechanical",
    category: "guc",
    symbol: "HP",
    siFactor: 745.7,
    tr: { name: "Beygirgücü (Mekanik)", slug: "beygirgucu-mekanik" },
    en: { name: "Horsepower (Mechanical)", slug: "horsepower-mechanical" },
    de: { name: "PS (mechanisch)", slug: "ps-mechanisch" },
  },

  // ---- sıcaklık / temperature / Temperatur (non-linear, no siFactor) ----
  {
    id: "santigrat",
    category: "sicaklik",
    symbol: "C",
    displaySymbol: "°C",
    isTemperature: true,
    tr: { name: "Santigrat", slug: "santigrat" },
    en: { name: "Celsius", slug: "celsius" },
    de: { name: "Celsius", slug: "celsius" },
    enConversionSlug: "celsius",
  },
  {
    id: "fahrenhayt",
    category: "sicaklik",
    symbol: "F",
    displaySymbol: "°F",
    isTemperature: true,
    tr: { name: "Fahrenheit", slug: "fahrenhayt" },
    en: { name: "Fahrenheit", slug: "fahrenheit" },
    de: { name: "Fahrenheit", slug: "fahrenheit" },
    enConversionSlug: "fahrenheit",
  },
  {
    id: "kelvin",
    category: "sicaklik",
    symbol: "K",
    isTemperature: true,
    tr: { name: "Kelvin", slug: "kelvin" },
    en: { name: "Kelvin", slug: "kelvin" },
    de: { name: "Kelvin", slug: "kelvin" },
    enConversionSlug: "kelvin",
  },

  // ---- ısıl iletkenlik / ısı akısı / özgül ısı (engine-only) ----
  {
    id: "w-mk",
    category: "isil_iletkenlik",
    symbol: "W/m·K",
    siFactor: 1,
    tr: { name: "Watt/metre-Kelvin", slug: "watt-metre-kelvin" },
    en: { name: "Watt per Meter-Kelvin", slug: "watt-per-meter-kelvin" },
    de: { name: "Watt pro Meter-Kelvin", slug: "watt-pro-meter-kelvin" },
  },
  { id: "kw-mk", category: "isil_iletkenlik", symbol: "kW/m·K", siFactor: 1000, tr: { name: "Kilowatt/metre-Kelvin", slug: "kilowatt-metre-kelvin" } },
  { id: "w-cmk", category: "isil_iletkenlik", symbol: "W/cm·K", siFactor: 100, tr: { name: "Watt/santimetre-Kelvin", slug: "watt-santimetre-kelvin" } },
  {
    id: "btu-hftf",
    category: "isil_iletkenlik",
    symbol: "Btu/h·ft·°F",
    siFactor: 1.730735,
    tr: { name: "BTU/saat-fit-°F", slug: "btu-saat-fit-f" },
    en: { name: "BTU per Hour-Foot-°F", slug: "btu-per-hour-foot-f" },
    de: { name: "BTU pro Stunde-Fuß-°F", slug: "btu-pro-stunde-fuss-f" },
  },
  {
    id: "w-m2",
    category: "isi_akisi",
    symbol: "W/m²",
    siFactor: 1,
    tr: { name: "Watt/metrekare", slug: "watt-metrekare" },
    en: { name: "Watt per Square Meter", slug: "watt-per-square-meter" },
    de: { name: "Watt pro Quadratmeter", slug: "watt-pro-quadratmeter" },
  },
  {
    id: "kw-m2",
    category: "isi_akisi",
    symbol: "kW/m²",
    siFactor: 1000,
    tr: { name: "Kilowatt/metrekare", slug: "kilowatt-metrekare" },
    en: { name: "Kilowatt per Square Meter", slug: "kilowatt-per-square-meter" },
    de: { name: "Kilowatt pro Quadratmeter", slug: "kilowatt-pro-quadratmeter" },
  },
  { id: "cal-cm2s", category: "isi_akisi", symbol: "cal/cm²·s", siFactor: 41840, tr: { name: "Kalori/santimetrekare-saniye", slug: "kalori-santimetrekare-saniye" } },
  {
    id: "j-kgk",
    category: "ozgul_isi",
    symbol: "J/kg·K",
    siFactor: 1,
    tr: { name: "Joule/kilogram-Kelvin", slug: "joule-kilogram-kelvin" },
    en: { name: "Joule per Kilogram-Kelvin", slug: "joule-per-kilogram-kelvin" },
    de: { name: "Joule pro Kilogramm-Kelvin", slug: "joule-pro-kilogramm-kelvin" },
  },
  { id: "kj-kgk", category: "ozgul_isi", symbol: "kJ/kg·K", siFactor: 1000, tr: { name: "Kilojoule/kilogram-Kelvin", slug: "kilojoule-kilogram-kelvin" } },
  {
    id: "cal-gk",
    category: "ozgul_isi",
    symbol: "cal/g·K",
    siFactor: 4.184,
    tr: { name: "Kalori/gram-Kelvin", slug: "kalori-gram-kelvin" },
    en: { name: "Calorie per Gram-Kelvin", slug: "calorie-per-gram-kelvin" },
    de: { name: "Kalorie pro Gramm-Kelvin", slug: "kalorie-pro-gramm-kelvin" },
  },
  { id: "btu-lbf", category: "ozgul_isi", symbol: "Btu/lb·°F", siFactor: 4186.8, tr: { name: "Btu/pound-Fahrenhayt", slug: "btu-pound-fahrenhayt" } },

  // ---- debi / elektrik ("core" categories, distinct from *_hacimsel/*_kutlesel/*_gerilim/*_akim) ----
  {
    id: "metrekup-saat",
    category: "debi",
    symbol: "m³/h",
    siFactor: 1 / 3600,
    tr: { name: "Metreküp/Saat", slug: "metrekup-saat" },
    en: { name: "Cubic Meter per Hour", slug: "cubic-meter-per-hour" },
    de: { name: "Kubikmeter pro Stunde", slug: "kubikmeter-pro-stunde" },
    enConversionSlug: "cubic-meters-per-hour",
  },
  {
    id: "litre-dakika",
    category: "debi",
    symbol: "L/min",
    siFactor: 0.001 / 60,
    tr: { name: "Litre/Dakika", slug: "litre-dakika" },
    en: { name: "Liter per Minute", slug: "liter-per-minute" },
    de: { name: "Liter pro Minute", slug: "liter-pro-minute" },
    enConversionSlug: "liters-per-minute",
  },
  {
    id: "volt",
    category: "elektrik",
    symbol: "V",
    siFactor: 1,
    tr: { name: "Volt", slug: "volt" },
    en: { name: "Volt", slug: "volt" },
    de: { name: "Volt", slug: "volt" },
    enConversionSlug: "volts",
  },
  {
    id: "kilovolt",
    category: "elektrik",
    symbol: "kV",
    siFactor: 1000,
    tr: { name: "Kilovolt", slug: "kilovolt" },
    en: { name: "Kilovolt", slug: "kilovolt" },
    de: { name: "Kilovolt", slug: "kilovolt" },
    enConversionSlug: "kilovolts",
  },
  {
    id: "amper",
    category: "elektrik",
    symbol: "A",
    siFactor: 1,
    tr: { name: "Amper", slug: "amper" },
    en: { name: "Ampere", slug: "ampere" },
    de: { name: "Ampere", slug: "ampere" },
    enConversionSlug: "amperes",
  },
  {
    id: "miliamper",
    category: "elektrik",
    symbol: "mA",
    siFactor: 0.001,
    tr: { name: "Miliamper", slug: "miliamper" },
    en: { name: "Milliampere", slug: "milliampere" },
    de: { name: "Milliampere", slug: "milliampere" },
    enConversionSlug: "milliamperes",
  },

  // ---- elektrik_direnc / gerilim / akım / kapasitans / enduktans / yük / manyetik (engine-only) ----
  {
    id: "ohm",
    category: "elektrik_direnc",
    symbol: "Ω",
    siFactor: 1,
    tr: { name: "Ohm", slug: "ohm" },
    en: { name: "Ohm", slug: "ohm" },
    de: { name: "Ohm", slug: "ohm" },
  },
  {
    id: "kiloohm",
    category: "elektrik_direnc",
    symbol: "kΩ",
    siFactor: 1000,
    tr: { name: "Kiloohm", slug: "kiloohm" },
    en: { name: "Kiloohm", slug: "kiloohm" },
    de: { name: "Kiloohm", slug: "kiloohm" },
  },
  {
    id: "megaohm",
    category: "elektrik_direnc",
    symbol: "MΩ",
    siFactor: 1_000_000,
    tr: { name: "Megaohm", slug: "megaohm" },
    en: { name: "Megaohm", slug: "megaohm" },
    de: { name: "Megaohm", slug: "megaohm" },
  },
  { id: "gerilim-volt", category: "elektrik_gerilim", symbol: "V", siFactor: 1 },
  { id: "gerilim-kilovolt", category: "elektrik_gerilim", symbol: "kV", siFactor: 1000 },
  { id: "akim-amper", category: "elektrik_akim", symbol: "A", siFactor: 1 },
  { id: "akim-miliamper", category: "elektrik_akim", symbol: "mA", siFactor: 0.001 },
  {
    id: "milivolt",
    category: "elektrik",
    symbol: "mV",
    siFactor: 0.001,
    tr: { name: "Milivolt", slug: "milivolt" },
    en: { name: "Millivolt", slug: "millivolt" },
    de: { name: "Millivolt", slug: "millivolt" },
  },
  {
    id: "kiloamper",
    category: "elektrik",
    symbol: "kA",
    siFactor: 1000,
    tr: { name: "Kiloamper", slug: "kiloamper" },
    en: { name: "Kiloampere", slug: "kiloampere" },
    de: { name: "Kiloampere", slug: "kiloampere" },
  },
  {
    id: "farad",
    category: "kapasitans",
    symbol: "F",
    siFactor: 1,
    tr: { name: "Farad", slug: "farad" },
    en: { name: "Farad", slug: "farad" },
    de: { name: "Farad", slug: "farad" },
  },
  {
    id: "milifarad",
    category: "kapasitans",
    symbol: "mF",
    siFactor: 0.001,
    tr: { name: "Milifarad", slug: "milifarad" },
    en: { name: "Millifarad", slug: "millifarad" },
    de: { name: "Millifarad", slug: "millifarad" },
  },
  {
    id: "mikrofarad",
    category: "kapasitans",
    symbol: "µF",
    siFactor: 0.000001,
    tr: { name: "Mikrofarad", slug: "mikrofarad" },
    en: { name: "Microfarad", slug: "microfarad" },
    de: { name: "Mikrofarad", slug: "mikrofarad" },
  },
  {
    id: "nanofarad",
    category: "kapasitans",
    symbol: "nF",
    siFactor: 1e-9,
    tr: { name: "Nanofarad", slug: "nanofarad" },
    en: { name: "Nanofarad", slug: "nanofarad" },
    de: { name: "Nanofarad", slug: "nanofarad" },
  },
  {
    id: "pikofarad",
    category: "kapasitans",
    symbol: "pF",
    siFactor: 1e-12,
    tr: { name: "Pikofarad", slug: "pikofarad" },
    en: { name: "Picofarad", slug: "picofarad" },
    de: { name: "Pikofarad", slug: "pikofarad" },
  },
  {
    id: "henry",
    category: "enduktans",
    symbol: "H",
    siFactor: 1,
    tr: { name: "Henry", slug: "henry" },
    en: { name: "Henry", slug: "henry" },
    de: { name: "Henry", slug: "henry" },
  },
  {
    id: "milihenry",
    category: "enduktans",
    symbol: "mH",
    siFactor: 0.001,
    tr: { name: "Milihenry", slug: "milihenry" },
    en: { name: "Millihenry", slug: "millihenry" },
    de: { name: "Millihenry", slug: "millihenry" },
  },
  {
    id: "mikrohenry",
    category: "enduktans",
    symbol: "µH",
    siFactor: 0.000001,
    tr: { name: "Mikrohenry", slug: "mikrohenry" },
    en: { name: "Microhenry", slug: "microhenry" },
    de: { name: "Mikrohenry", slug: "mikrohenry" },
  },
  {
    id: "coulomb",
    category: "elektrik_yuk",
    symbol: "C",
    siFactor: 1,
    tr: { name: "Coulomb", slug: "coulomb" },
    en: { name: "Coulomb", slug: "coulomb" },
    de: { name: "Coulomb", slug: "coulomb" },
  },
  {
    id: "milicoulomb",
    category: "elektrik_yuk",
    symbol: "mC",
    siFactor: 0.001,
    tr: { name: "Milicoulomb", slug: "milicoulomb" },
    en: { name: "Millicoulomb", slug: "millicoulomb" },
    de: { name: "Millicoulomb", slug: "millicoulomb" },
  },
  {
    id: "mikrocoulomb",
    category: "elektrik_yuk",
    symbol: "µC",
    siFactor: 0.000001,
    tr: { name: "Mikrocoulomb", slug: "mikrocoulomb" },
    en: { name: "Microcoulomb", slug: "microcoulomb" },
    de: { name: "Mikrocoulomb", slug: "mikrocoulomb" },
  },
  {
    id: "nanocoulomb",
    category: "elektrik_yuk",
    symbol: "nC",
    siFactor: 1e-9,
    tr: { name: "Nanocoulomb", slug: "nanocoulomb" },
    en: { name: "Nanocoulomb", slug: "nanocoulomb" },
    de: { name: "Nanocoulomb", slug: "nanocoulomb" },
  },
  {
    id: "a-m",
    category: "manyetik_alan",
    symbol: "A/m",
    siFactor: 1,
    tr: { name: "Amper/metre", slug: "amper-metre" },
    en: { name: "Ampere per Meter", slug: "ampere-per-meter" },
    de: { name: "Ampere pro Meter", slug: "ampere-pro-meter" },
  },
  { id: "ka-m", category: "manyetik_alan", symbol: "kA/m", siFactor: 1000, tr: { name: "Kiloamper/metre", slug: "kiloamper-metre" } },
  {
    id: "oersted",
    category: "manyetik_alan",
    symbol: "Oe",
    siFactor: 79.5775,
    tr: { name: "Oersted", slug: "oersted" },
    en: { name: "Oersted", slug: "oersted" },
    de: { name: "Oersted", slug: "oersted" },
  },
  {
    id: "weber",
    category: "manyetik_aki",
    symbol: "Wb",
    siFactor: 1,
    tr: { name: "Weber", slug: "weber" },
    en: { name: "Weber", slug: "weber" },
    de: { name: "Weber", slug: "weber" },
  },
  {
    id: "miliweber",
    category: "manyetik_aki",
    symbol: "mWb",
    siFactor: 0.001,
    tr: { name: "Miliweber", slug: "miliweber" },
    en: { name: "Milliweber", slug: "milliweber" },
    de: { name: "Milliweber", slug: "milliweber" },
  },
  { id: "mikroweber", category: "manyetik_aki", symbol: "µWb", siFactor: 0.000001, tr: { name: "Mikroweber", slug: "mikroweber" } },
  { id: "nanoweber", category: "manyetik_aki", symbol: "nWb", siFactor: 1e-9, tr: { name: "Nanoweber", slug: "nanoweber" } },
  { id: "weber-alias", category: "manyetik_aki", symbol: "weber", siFactor: 1 },

  // ---- veri / digital storage ----
  {
    id: "bit",
    category: "veri",
    symbol: "bit",
    siFactor: 0.125,
    tr: { name: "Bit", slug: "bit" },
    en: { name: "Bit", slug: "bit" },
    de: { name: "Bit", slug: "bit" },
  },
  {
    id: "bayt",
    category: "veri",
    symbol: "B",
    siFactor: 1,
    tr: { name: "Bayt", slug: "bayt" },
    en: { name: "Byte", slug: "byte" },
    de: { name: "Byte", slug: "byte" },
  },
  {
    id: "kilobayt",
    category: "veri",
    symbol: "KB",
    siFactor: 1000,
    tr: { name: "Kilobayt", slug: "kilobayt" },
    en: { name: "Kilobyte", slug: "kilobyte" },
    de: { name: "Kilobyte", slug: "kilobyte" },
  },
  {
    id: "megabayt",
    category: "veri",
    symbol: "MB",
    siFactor: 1_000_000,
    tr: { name: "Megabayt", slug: "megabayt" },
    en: { name: "Megabyte", slug: "megabyte" },
    de: { name: "Megabyte", slug: "megabyte" },
  },
  {
    id: "gigabayt",
    category: "veri",
    symbol: "GB",
    siFactor: 1_000_000_000,
    tr: { name: "Gigabayt", slug: "gigabayt" },
    en: { name: "Gigabyte", slug: "gigabyte" },
    de: { name: "Gigabyte", slug: "gigabyte" },
  },
  {
    id: "terabayt",
    category: "veri",
    symbol: "TB",
    siFactor: 1_000_000_000_000,
    tr: { name: "Terabayt", slug: "terabayt" },
    en: { name: "Terabyte", slug: "terabyte" },
    de: { name: "Terabyte", slug: "terabyte" },
  },
  {
    id: "petabayt",
    category: "veri",
    symbol: "PB",
    siFactor: 1_000_000_000_000_000,
    tr: { name: "Petabayt", slug: "petabayt" },
    en: { name: "Petabyte", slug: "petabyte" },
    de: { name: "Petabyte", slug: "petabyte" },
  },
  {
    id: "kibibayt",
    category: "veri",
    symbol: "KiB",
    siFactor: 1024,
    tr: { name: "Kibibayt", slug: "kibibayt" },
    en: { name: "Kibibyte", slug: "kibibyte" },
    de: { name: "Kibibyte", slug: "kibibyte" },
  },
  {
    id: "mebibayt",
    category: "veri",
    symbol: "MiB",
    siFactor: 1024 ** 2,
    tr: { name: "Mebibayt", slug: "mebibayt" },
    en: { name: "Mebibyte", slug: "mebibyte" },
    de: { name: "Mebibyte", slug: "mebibyte" },
  },
  {
    id: "gibibayt",
    category: "veri",
    symbol: "GiB",
    siFactor: 1024 ** 3,
    tr: { name: "Gibibayt", slug: "gibibayt" },
    en: { name: "Gibibyte", slug: "gibibyte" },
    de: { name: "Gibibyte", slug: "gibibyte" },
  },
  {
    id: "tebibayt",
    category: "veri",
    symbol: "TiB",
    siFactor: 1024 ** 4,
    tr: { name: "Tebibayt", slug: "tebibayt" },
    en: { name: "Tebibyte", slug: "tebibyte" },
    de: { name: "Tebibyte", slug: "tebibyte" },
  },

  // ---- altin_ayar / gold karat purity ----
  {
    id: "ayar-24",
    category: "altin_ayar",
    symbol: "24K",
    siFactor: 1,
    tr: { name: "24 Ayar Altın", slug: "24-ayar-altin" },
    en: { name: "24K Gold", slug: "24k-gold" },
    de: { name: "24 Karat Gold", slug: "24-karat-gold" },
  },
  {
    id: "ayar-22",
    category: "altin_ayar",
    symbol: "22K",
    siFactor: 22 / 24,
    tr: { name: "22 Ayar Altın", slug: "22-ayar-altin" },
    en: { name: "22K Gold", slug: "22k-gold" },
    de: { name: "22 Karat Gold", slug: "22-karat-gold" },
  },
  {
    id: "ayar-18",
    category: "altin_ayar",
    symbol: "18K",
    siFactor: 18 / 24,
    tr: { name: "18 Ayar Altın", slug: "18-ayar-altin" },
    en: { name: "18K Gold", slug: "18k-gold" },
    de: { name: "18 Karat Gold", slug: "18-karat-gold" },
  },
  {
    id: "ayar-14",
    category: "altin_ayar",
    symbol: "14K",
    siFactor: 14 / 24,
    tr: { name: "14 Ayar Altın", slug: "14-ayar-altin" },
    en: { name: "14K Gold", slug: "14k-gold" },
    de: { name: "14 Karat Gold", slug: "14-karat-gold" },
  },

  // ---- gumus_ayar / gümüş ayar (saflık) ----
  {
    id: "gumus-999",
    category: "gumus_ayar",
    symbol: "999",
    siFactor: 0.999,
    tr: { name: "999 Ayar Gümüş", slug: "999-ayar-gumus" },
    en: { name: "Fine Silver (999)", slug: "fine-silver" },
  },
  {
    id: "gumus-925",
    category: "gumus_ayar",
    symbol: "925",
    siFactor: 0.925,
    tr: { name: "925 Ayar Gümüş", slug: "925-ayar-gumus" },
    en: { name: "Sterling Silver (925)", slug: "sterling-silver" },
  },
  {
    id: "gumus-900",
    category: "gumus_ayar",
    symbol: "900",
    siFactor: 0.9,
    tr: { name: "900 Ayar Gümüş", slug: "900-ayar-gumus" },
    en: { name: "Coin Silver (900)", slug: "coin-silver" },
  },
  {
    id: "gumus-800",
    category: "gumus_ayar",
    symbol: "800",
    siFactor: 0.8,
    tr: { name: "800 Ayar Gümüş", slug: "800-ayar-gumus" },
    en: { name: "800 Silver", slug: "800-silver" },
  },

  // ---- kan_sekeri / kan sekeri (glukoz) birim donusumu ----
  {
    id: "glukoz-mmol",
    category: "kan_sekeri",
    symbol: "mmol/L",
    siFactor: 1,
    tr: { name: "Milimol/Litre", slug: "milimol-litre" },
    en: { name: "Millimoles per Liter", slug: "millimoles-per-liter" },
  },
  {
    id: "glukoz-mgdl",
    category: "kan_sekeri",
    symbol: "mg/dL",
    siFactor: 1 / 18.016,
    tr: { name: "Miligram/Desilitre", slug: "miligram-desilitre" },
    en: { name: "Milligrams per Deciliter", slug: "milligrams-per-deciliter" },
  },

  // ---- vitamin_d / vitamin D birim donusumu ----
  {
    id: "vitamin-d-nmol",
    category: "vitamin_d",
    symbol: "nmol/L",
    siFactor: 1,
    tr: { name: "Nanomol/Litre", slug: "nanomol-litre" },
    en: { name: "Nanomoles per Liter", slug: "nanomoles-per-liter" },
  },
  {
    id: "vitamin-d-ngml",
    category: "vitamin_d",
    symbol: "ng/mL",
    siFactor: 2.496,
    tr: { name: "Nanogram/Mililitre", slug: "nanogram-mililitre" },
    en: { name: "Nanograms per Milliliter", slug: "nanograms-per-milliliter" },
  },
];

export function findUnit(category: string, symbol: string) {
  return unitRegistry.find(
    (unit) => unit.category === category && unit.symbol === symbol
  );
}

export function getUnitsForCategory(category: string) {
  return unitRegistry.filter((unit) => unit.category === category);
}

export function getUnitCategories() {
  return Array.from(new Set(unitRegistry.map((unit) => unit.category)));
}
