export type UnitCategory = string;

export type LocalizedUnitName = {
  name: string;
  slug: string;
};

export type UnitRegistryEntry = {
  id: string;
  category: UnitCategory;
  symbol: string;
  displaySymbol?: string;
  siFactor?: number;
  isTemperature?: boolean;
  tr?: LocalizedUnitName;
  en?: LocalizedUnitName;
  de?: LocalizedUnitName;
  uz?: LocalizedUnitName;
  enConversionSlug?: string;
};

export const unitRegistry: UnitRegistryEntry[] = [
  // ---- uzunluk / length / Länge ----
  {
    id: "metre",
    category: "uzunluk",
    symbol: "m",
    siFactor: 1,
    tr: { name: "Metre", slug: "metre" },
    en: { name: "Meter", slug: "meter" },
    de: { name: "Meter", slug: "meter" },
    uz: { name: "Metr", slug: "metr" },
    enConversionSlug: "meters",
  },
  {
    id: "kilometre",
    category: "uzunluk",
    symbol: "km",
    siFactor: 1000,
    tr: { name: "Kilometre", slug: "kilometre" },
    en: { name: "Kilometer", slug: "kilometer" },
    de: { name: "Kilometer", slug: "kilometer" },
    uz: { name: "Kilometr", slug: "kilometr" },
    enConversionSlug: "kilometers",
  },
  {
    id: "santimetre",
    category: "uzunluk",
    symbol: "cm",
    siFactor: 0.01,
    tr: { name: "Santimetre", slug: "santimetre" },
    en: { name: "Centimeter", slug: "centimeter" },
    de: { name: "Zentimeter", slug: "zentimeter" },
    uz: { name: "Santimetr", slug: "santimetr" },
    enConversionSlug: "centimeters",
  },
  {
    id: "desimetre",
    category: "uzunluk",
    symbol: "dm",
    siFactor: 0.1,
    tr: { name: "Desimetre", slug: "desimetre" },
    en: { name: "Decimeter", slug: "decimeter" },
    de: { name: "Dezimeter", slug: "dezimeter" },
    uz: { name: "Desimetr", slug: "desimetr" },
    enConversionSlug: "decimeters",
  },
  {
    id: "milimetre",
    category: "uzunluk",
    symbol: "mm",
    siFactor: 0.001,
    tr: { name: "Milimetre", slug: "milimetre" },
    en: { name: "Millimeter", slug: "millimeter" },
    de: { name: "Millimeter", slug: "millimeter" },
    uz: { name: "Millimetr", slug: "millimetr" },
    enConversionSlug: "millimeters",
  },
  {
    id: "mikrometre",
    category: "uzunluk",
    symbol: "µm",
    siFactor: 0.000001,
    tr: { name: "Mikrometre", slug: "mikrometre" },
    en: { name: "Micrometer", slug: "micrometer" },
    de: { name: "Mikrometer", slug: "mikrometer" },
    uz: { name: "Mikrometr", slug: "mikrometr" },
  },
  {
    id: "nanometre",
    category: "uzunluk",
    symbol: "nm",
    siFactor: 1e-9,
    tr: { name: "Nanometre", slug: "nanometre" },
    en: { name: "Nanometer", slug: "nanometer" },
    de: { name: "Nanometer", slug: "nanometer" },
    uz: { name: "Nanometr", slug: "nanometr" },
  },
  {
    id: "pikometre",
    category: "uzunluk",
    symbol: "pm",
    siFactor: 1e-12,
    tr: { name: "Pikometre", slug: "pikometre" },
    en: { name: "Picometer", slug: "picometer" },
    de: { name: "Pikometer", slug: "pikometer" },
    uz: { name: "Pikometr", slug: "pikometr" },
  },
  {
    id: "fit",
    category: "uzunluk",
    symbol: "ft",
    siFactor: 0.3048,
    tr: { name: "Fit", slug: "fit" },
    en: { name: "Foot", slug: "foot" },
    de: { name: "Fuß", slug: "fuss" },
    uz: { name: "Fut", slug: "fut" },
    enConversionSlug: "feet",
  },
  {
    id: "inc",
    category: "uzunluk",
    symbol: "in",
    siFactor: 0.0254,
    tr: { name: "İnç", slug: "inc" },
    en: { name: "Inch", slug: "inch" },
    de: { name: "Zoll", slug: "zoll" },
    uz: { name: "Dyum", slug: "dyum" },
    enConversionSlug: "inches",
  },
  {
    id: "yarda",
    category: "uzunluk",
    symbol: "yd",
    siFactor: 0.9144,
    tr: { name: "Yarda", slug: "yarda" },
    en: { name: "Yard", slug: "yard" },
    de: { name: "Yard", slug: "yard" },
    uz: { name: "Yard", slug: "yard" },
    enConversionSlug: "yards",
  },
  {
    id: "mil",
    category: "uzunluk",
    symbol: "mi",
    siFactor: 1609.344,
    tr: { name: "Mil", slug: "mil" },
    en: { name: "Mile", slug: "mile" },
    de: { name: "Meile", slug: "meile" },
    uz: { name: "Milya", slug: "milya" },
    enConversionSlug: "miles",
  },
  {
    id: "furlong",
    category: "uzunluk",
    symbol: "fur",
    siFactor: 201.168,
    tr: { name: "Furlong", slug: "furlong" },
    en: { name: "Furlong", slug: "furlong" },
    de: { name: "Furlong", slug: "furlong" },
    uz: { name: "Furlong", slug: "furlong" },
  },
  {
    id: "deniz-mili",
    category: "uzunluk",
    symbol: "nmi",
    siFactor: 1852,
    tr: { name: "Deniz mili", slug: "deniz-mili" },
    en: { name: "Nautical mile", slug: "nautical-mile" },
    de: { name: "Seemeile", slug: "seemeile" },
    uz: { name: "Dengiz mili", slug: "dengiz-mili" },
  },
  {
    id: "astronomik-birim",
    category: "uzunluk",
    symbol: "AU",
    siFactor: 149597870700,
    tr: { name: "Astronomik Birim", slug: "astronomik-birim" },
    en: { name: "Astronomical Unit", slug: "astronomical-unit" },
    de: { name: "Astronomische Einheit", slug: "astronomische-einheit" },
    uz: { name: "Astronomik Birlik", slug: "astronomik-birlik" },
  },
  {
    id: "isik-yili",
    category: "uzunluk",
    symbol: "ly",
    siFactor: 9460730472580800,
    tr: { name: "Işık Yılı", slug: "isik-yili" },
    en: { name: "Light-year", slug: "light-year" },
    de: { name: "Lichtjahr", slug: "lichtjahr" },
    uz: { name: "Yorug'lik Yili", slug: "yoruglik-yili" },
  },
  {
    id: "parsek",
    category: "uzunluk",
    symbol: "pc",
    siFactor: 3.0856775814913673e16,
    tr: { name: "Parsek", slug: "parsek" },
    en: { name: "Parsec", slug: "parsec" },
    de: { name: "Parsec", slug: "parsec" },
    uz: { name: "Parsek", slug: "parsek" },
  },
  {
    id: "angstrom",
    category: "uzunluk",
    symbol: "Å",
    siFactor: 1e-10,
    tr: { name: "Angström", slug: "angstrom" },
    en: { name: "Angstrom", slug: "angstrom" },
    de: { name: "Angström", slug: "angstroem" },
    uz: { name: "Angstrem", slug: "angstrem" },
  },
  {
    id: "fathom",
    category: "uzunluk",
    symbol: "ftm",
    siFactor: 1.8288,
    tr: { name: "Kulaç (Fathom)", slug: "fathom" },
    en: { name: "Fathom", slug: "fathom" },
    de: { name: "Faden", slug: "faden" },
    uz: { name: "Fatom", slug: "fatom" },
  },
  {
    id: "arsin",
    category: "uzunluk",
    symbol: "arşın",
    siFactor: 0.68,
    tr: { name: "Arşın", slug: "arsin" },
    en: { name: "Arshin", slug: "arshin" },
    de: { name: "Arschin", slug: "arschin" },  },
  {
    id: "endaze",
    category: "uzunluk",
    symbol: "endaze",
    siFactor: 0.65,
    tr: { name: "Endaze", slug: "endaze" },
    en: { name: "Endaze", slug: "endaze" },
    de: { name: "Endaze", slug: "endaze" },  },
  {
    id: "pous",
    category: "uzunluk",
    symbol: "pus",
    siFactor: 0.3148,
    tr: { name: "Bizans Ayağı", slug: "bizans-ayagi" },
    en: { name: "Byzantine Foot", slug: "byzantine-foot" },
    de: { name: "Byzantinischer Fuß", slug: "byzantinischer-fuss" },
  },
  {
    id: "orgyia",
    category: "uzunluk",
    symbol: "orgyia",
    siFactor: 1.8888,
    tr: { name: "Bizans Kulacı", slug: "bizans-kulaci" },
    en: { name: "Byzantine Fathom", slug: "byzantine-fathom" },
    de: { name: "Byzantinische Klafter", slug: "byzantinische-klafter" },
  },
  {
    id: "cig",
    category: "uzunluk",
    symbol: "çığ",
    siFactor: 0.333,
    tr: { name: "Çığ", slug: "cig" },
    en: { name: "Cig", slug: "cig" },
    de: { name: "Çığ", slug: "cig" },  },

  // ---- o'zbekcha tarixiy uzunlik birliklari (faqat uz, tr/en/de yo'q --
  // bu birliklar Buxoro/Xiva/Qo'qon davriga xos, Turkiyaga tegishli emas) ----
  {
    id: "gaz",
    category: "uzunluk",
    symbol: "gaz",
    siFactor: 0.71,
    uz: { name: "Gaz", slug: "gaz" },
  },
  {
    id: "chaqirim",
    category: "uzunluk",
    symbol: "chaqirim",
    siFactor: 1000,
    uz: { name: "Chaqirim", slug: "chaqirim" },
  },
  {
    id: "tosh",
    category: "uzunluk",
    symbol: "tosh",
    siFactor: 7000,
    uz: { name: "Tosh", slug: "tosh" },
  },
  {
    id: "farsah-uz",
    category: "uzunluk",
    symbol: "farsah",
    siFactor: 6000,
    uz: { name: "Farsah", slug: "farsah" },
  },
  {
    id: "qadam",
    category: "uzunluk",
    symbol: "qadam",
    siFactor: 0.67,
    uz: { name: "Qadam", slug: "qadam" },
  },

  // ---- alan / area / Fläche ----
  {
    id: "metrekare",
    category: "alan",
    symbol: "m²",
    siFactor: 1,
    tr: { name: "Metrekare", slug: "metrekare" },
    en: { name: "Square Meter", slug: "square-meter" },
    de: { name: "Quadratmeter", slug: "quadratmeter" },
    enConversionSlug: "square-meters",
    uz: { name: "Kvadrat metr", slug: "kvadrat-metr" },
  },
  {
    id: "santimetrekare",
    category: "alan",
    symbol: "cm²",
    siFactor: 0.0001,
    tr: { name: "Santimetrekare", slug: "santimetrekare" },
    en: { name: "Square Centimeter", slug: "square-centimeter" },
    de: { name: "Quadratzentimeter", slug: "quadratzentimeter" },
    uz: { name: "Kvadrat Santimetr", slug: "kvadrat-santimetr" },
  },
  {
    id: "milimetrekare",
    category: "alan",
    symbol: "mm²",
    siFactor: 0.000001,
    tr: { name: "Milimetrekare", slug: "milimetrekare" },
    en: { name: "Square Millimeter", slug: "square-millimeter" },
    de: { name: "Quadratmillimeter", slug: "quadratmillimeter" },
    uz: { name: "Kvadrat Millimetr", slug: "kvadrat-millimetr" },
  },
  {
    id: "kilometrekare",
    category: "alan",
    symbol: "km²",
    siFactor: 1_000_000,
    tr: { name: "Kilometrekare", slug: "kilometrekare" },
    en: { name: "Square Kilometer", slug: "square-kilometer" },
    de: { name: "Quadratkilometer", slug: "quadratkilometer" },
    uz: { name: "Kvadrat Kilometr", slug: "kvadrat-kilometr" },
  },
  {
    id: "hektar",
    category: "alan",
    symbol: "ha",
    siFactor: 10_000,
    tr: { name: "Hektar", slug: "hektar" },
    en: { name: "Hectare", slug: "hectare" },
    de: { name: "Hektar", slug: "hektar" },
    enConversionSlug: "hectares",
    uz: { name: "Gektar", slug: "gektar" },
  },
  {
    id: "ar",
    category: "alan",
    symbol: "a",
    siFactor: 100,
    tr: { name: "Ar", slug: "ar" },
    en: { name: "Are", slug: "are" },
    de: { name: "Ar", slug: "ar" },
    uz: { name: "Sotix", slug: "sotix" },
  },
  {
    id: "fitkare",
    category: "alan",
    symbol: "ft²",
    siFactor: 0.09290304,
    tr: { name: "Fitkare", slug: "fitkare" },
    en: { name: "Square Foot", slug: "square-foot" },
    de: { name: "Quadratfuß", slug: "quadratfuss" },
    enConversionSlug: "square-feet",
    uz: { name: "Kvadrat Fut", slug: "kvadrat-fut" },
  },
  {
    id: "incare",
    category: "alan",
    symbol: "in²",
    siFactor: 0.00064516,
    tr: { name: "İnçkare", slug: "incare" },
    en: { name: "Square Inch", slug: "square-inch" },
    de: { name: "Quadratzoll", slug: "quadratzoll" },
    uz: { name: "Kvadrat Dyum", slug: "kvadrat-dyum" },
  },
  {
    id: "yardakare",
    category: "alan",
    symbol: "yd²",
    siFactor: 0.83612736,
    tr: { name: "Yardakare", slug: "yardakare" },
    en: { name: "Square Yard", slug: "square-yard" },
    de: { name: "Quadratyard", slug: "quadratyard" },
    uz: { name: "Kvadrat Yard", slug: "kvadrat-yard" },
    enConversionSlug: "square-yards",
  },
  {
    id: "akre",
    category: "alan",
    symbol: "ac",
    siFactor: 4046.8564224,
    tr: { name: "Akre", slug: "akre" },
    en: { name: "Acre", slug: "acre" },
    de: { name: "Acre", slug: "acre" },
    uz: { name: "Akr", slug: "akr" },
  },
  {
    id: "donum",
    category: "alan",
    symbol: "dönüm",
    siFactor: 1000,
    tr: { name: "Dönüm", slug: "donum" },
    en: { name: "Donum", slug: "donum" },
    de: { name: "Dönüm", slug: "doenuem" },
    uz: { name: "Donum", slug: "donum" },
  },
  {
    id: "feddan",
    category: "alan",
    symbol: "feddan",
    siFactor: 4200.833,
    tr: { name: "Feddan", slug: "feddan" },
    en: { name: "Feddan", slug: "feddan" },
  },
  {
    id: "kirat-arazi",
    category: "alan",
    symbol: "kırat (arazi)",
    siFactor: 175.0347,
    tr: { name: "Kırat (Arazi)", slug: "kirat-arazi" },
    en: { name: "Qirat (Land)", slug: "qirat-land" },
  },
  {
    id: "sehm-arazi",
    category: "alan",
    symbol: "sehm",
    siFactor: 7.2931,
    tr: { name: "Sehm (Arazi Payı)", slug: "sehm-arazi" },
    en: { name: "Sahm (Land Share)", slug: "sahm-land" },
  },
  {
    id: "dekar",
    category: "alan",
    symbol: "dekar",
    siFactor: 1000,
    tr: { name: "Dekar", slug: "dekar" },
    en: { name: "Decare", slug: "decare" },
    de: { name: "Dekar", slug: "dekar" },
    uz: { name: "Dekar", slug: "dekar" },
  },
  {
    id: "decimal-arazi",
    category: "alan",
    symbol: "decimal",
    siFactor: 40.468564224,
    tr: { name: "Decimal (Arazi)", slug: "decimal-arazi" },
    en: { name: "Decimal (Land)", slug: "decimal-land" },
    de: { name: "Decimal (Grundstück)", slug: "decimal-grundstueck" },
  },
  {
    id: "killa",
    category: "alan",
    symbol: "killa",
    siFactor: 4046.8564224,
    tr: { name: "Killa", slug: "killa" },
    en: { name: "Killa", slug: "killa" },
    de: { name: "Killa", slug: "killa" },
  },
  {
    id: "kanal",
    category: "alan",
    symbol: "kanal",
    siFactor: 505.8570768,
    tr: { name: "Kanal", slug: "kanal" },
    en: { name: "Kanal", slug: "kanal" },
    de: { name: "Kanal", slug: "kanal" },
  },
  {
    id: "marla",
    category: "alan",
    symbol: "marla",
    siFactor: 25.29285384,
    tr: { name: "Marla", slug: "marla" },
    en: { name: "Marla", slug: "marla" },
    de: { name: "Marla", slug: "marla" },
  },
  {
    id: "guntha",
    category: "alan",
    symbol: "guntha",
    siFactor: 101.1714105,
    tr: { name: "Guntha", slug: "guntha" },
    en: { name: "Guntha", slug: "guntha" },
    de: { name: "Guntha", slug: "guntha" },
  },
  {
    id: "cent-arazi",
    category: "alan",
    symbol: "cent",
    siFactor: 40.468564224,
    tr: { name: "Cent (Arazi)", slug: "cent-arazi" },
    en: { name: "Cent (Land)", slug: "cent-land" },
    de: { name: "Cent (Grundstück)", slug: "cent-grundstueck" },
  },
  {
    id: "ground",
    category: "alan",
    symbol: "ground",
    siFactor: 222.96729,
    tr: { name: "Ground", slug: "ground" },
    en: { name: "Ground", slug: "ground" },
    de: { name: "Ground", slug: "ground" },
  },
  {
    id: "biswa",
    category: "alan",
    symbol: "biswa",
    siFactor: 126.4642632,
    tr: { name: "Biswa", slug: "biswa" },
    en: { name: "Biswa", slug: "biswa" },
    de: { name: "Biswa", slug: "biswa" },
  },
  {
    id: "katha",
    category: "alan",
    symbol: "katha",
    siFactor: 66.8901888,
    tr: { name: "Katha", slug: "katha" },
    en: { name: "Katha", slug: "katha" },
    de: { name: "Katha", slug: "katha" },
  },
  {
    id: "bigha",
    category: "alan",
    symbol: "bigha",
    siFactor: 1337.803776,
    tr: { name: "Bigha", slug: "bigha" },
    en: { name: "Bigha", slug: "bigha" },
    de: { name: "Bigha", slug: "bigha" },
  },
  {
    id: "tsubo",
    category: "alan",
    symbol: "tsubo",
    siFactor: 3.305785,
    tr: { name: "Tsubo", slug: "tsubo" },
    en: { name: "Tsubo", slug: "tsubo" },
    de: { name: "Tsubo", slug: "tsubo" },
  },

  // ---- hacim / volume / Volumen ----
  {
    id: "metrekup",
    category: "hacim",
    symbol: "m³",
    siFactor: 1,
    tr: { name: "Metreküp", slug: "metrekup" },
    en: { name: "Cubic Meter", slug: "cubic-meter" },
    de: { name: "Kubikmeter", slug: "kubikmeter" },
    uz: { name: "Kub metr", slug: "kub-metr" },
    enConversionSlug: "cubic-meters",
  },
  {
    id: "litre",
    category: "hacim",
    symbol: "L",
    siFactor: 0.001,
    tr: { name: "Litre", slug: "litre" },
    en: { name: "Liter", slug: "liter" },
    de: { name: "Liter", slug: "liter" },
    uz: { name: "Litr", slug: "litr" },
    enConversionSlug: "liters",
  },
  {
    id: "mililitre",
    category: "hacim",
    symbol: "mL",
    siFactor: 0.000001,
    tr: { name: "Mililitre", slug: "mililitre" },
    en: { name: "Milliliter", slug: "milliliter" },
    de: { name: "Milliliter", slug: "milliliter" },
    uz: { name: "Millilitr", slug: "millilitr" },
    enConversionSlug: "milliliters",
  },
  {
    id: "desilitre",
    category: "hacim",
    symbol: "dL",
    siFactor: 0.0001,
    tr: { name: "Desilitre", slug: "desilitre" },
    en: { name: "Deciliter", slug: "deciliter" },
    de: { name: "Deziliter", slug: "deziliter" },
    uz: { name: "Detsilitr", slug: "detsilitr" },
    enConversionSlug: "deciliters",
  },
  {
    id: "santilitre",
    category: "hacim",
    symbol: "cL",
    siFactor: 0.00001,
    tr: { name: "Santilitre", slug: "santilitre" },
    en: { name: "Centiliter", slug: "centiliter" },
    de: { name: "Zentiliter", slug: "zentiliter" },
    uz: { name: "Santilitr", slug: "santilitr" },
    enConversionSlug: "centiliters",
  },
  {
    id: "yemek-kasigi",
    category: "hacim",
    symbol: "yk",
    siFactor: 0.000015,
    tr: { name: "Yemek Kaşığı", slug: "yemek-kasigi" },
    en: { name: "Tablespoon", slug: "tablespoon" },
    de: { name: "Esslöffel", slug: "essloeffel" },
    uz: { name: "Osh Qoshiq", slug: "osh-qoshiq" },
    enConversionSlug: "tablespoons",
  },
  {
    id: "cay-kasigi",
    category: "hacim",
    symbol: "çk",
    siFactor: 0.000005,
    tr: { name: "Çay Kaşığı", slug: "cay-kasigi" },
    en: { name: "Teaspoon", slug: "teaspoon" },
    de: { name: "Teelöffel", slug: "teeloeffel" },
    uz: { name: "Choy Qoshiq", slug: "choy-qoshiq" },
    enConversionSlug: "teaspoons",
  },
  {
    id: "su-bardagi",
    category: "hacim",
    symbol: "sb",
    siFactor: 0.0002,
    tr: { name: "Su Bardağı", slug: "su-bardagi" },
    en: { name: "Turkish Water Glass", slug: "turkish-water-glass" },
    de: { name: "Türkisches Wasserglas", slug: "tuerkisches-wasserglas" },
  },
  {
    id: "santimetrekup",
    category: "hacim",
    symbol: "cm³",
    siFactor: 0.000001,
    tr: { name: "Santimetreküp", slug: "santimetrekup" },
    en: { name: "Cubic Centimeter", slug: "cubic-centimeter" },
    de: { name: "Kubikzentimeter", slug: "kubikzentimeter" },
    uz: { name: "Kub Santimetr", slug: "kub-santimetr" },
  },
  {
    id: "fitkup",
    category: "hacim",
    symbol: "ft³",
    siFactor: 0.028316846592,
    tr: { name: "Fitküp", slug: "fitkup" },
    en: { name: "Cubic Foot", slug: "cubic-foot" },
    de: { name: "Kubikfuß", slug: "kubikfuss" },
    uz: { name: "Kub Fut", slug: "kub-fut" },
  },
  {
    id: "inckup",
    category: "hacim",
    symbol: "in³",
    siFactor: 0.000016387064,
    tr: { name: "İnçküp", slug: "inckup" },
    en: { name: "Cubic Inch", slug: "cubic-inch" },
    de: { name: "Kubikzoll", slug: "kubikzoll" },
    uz: { name: "Kub Dyum", slug: "kub-dyum" },
  },
  {
    id: "galon",
    category: "hacim",
    symbol: "gal",
    siFactor: 0.003785411784,
    tr: { name: "Galon", slug: "galon" },
    en: { name: "US Liquid Gallon", slug: "gallon" },
    de: { name: "Gallone", slug: "gallone" },
    uz: { name: "Gallon", slug: "gallon" },
  },
  {
    id: "quart",
    category: "hacim",
    symbol: "qt",
    siFactor: 0.000946352946,
    tr: { name: "Quart", slug: "quart" },
    en: { name: "US Quart", slug: "quart" },
    de: { name: "Quart", slug: "quart" },
    uz: { name: "Kvarta", slug: "kvarta" },
  },
  {
    id: "ingiliz-quart",
    category: "hacim",
    symbol: "imp qt",
    siFactor: 0.0011365225,
    tr: { name: "İngiliz Quart", slug: "ingiliz-quart" },
    en: { name: "Imperial Quart", slug: "imperial-quart" },
    de: { name: "Imperiale Quart", slug: "imperiale-quart" },
    uz: { name: "Britaniya Kvartasi", slug: "britaniya-kvartasi" },
  },
  {
    id: "sivi-ons",
    category: "hacim",
    symbol: "fl oz",
    siFactor: 0.0000295735295625,
    tr: { name: "Sıvı Ons", slug: "sivi-ons" },
    en: { name: "US Fluid Ounce", slug: "fluid-ounce" },
    de: { name: "Flüssigunze", slug: "fluessigunze" },
    uz: { name: "Suyuqlik Untsiyasi", slug: "suyuqlik-untsiyasi" },
  },
  {
    id: "ingiliz-sivi-ons",
    category: "hacim",
    symbol: "imp fl oz",
    siFactor: 0.0000284130625,
    tr: { name: "İngiliz Sıvı Ons", slug: "ingiliz-sivi-ons" },
    en: { name: "Imperial Fluid Ounce", slug: "imperial-fluid-ounce" },
    de: { name: "Imperiale Flüssigunze", slug: "imperiale-fluessigunze" },
    uz: { name: "Britaniya Suyuqlik Untsiyasi", slug: "britaniya-suyuqlik-untsiyasi" },
  },
  {
    id: "pint",
    category: "hacim",
    symbol: "pt",
    siFactor: 0.000473176473,
    tr: { name: "Pint", slug: "pint" },
    en: { name: "US Pint", slug: "pint" },
    de: { name: "Pint", slug: "pint" },
    uz: { name: "Pinta", slug: "pinta" },
  },
  {
    id: "ingiliz-pint",
    category: "hacim",
    symbol: "imp pt",
    siFactor: 0.00056826125,
    tr: { name: "İngiliz Pint", slug: "ingiliz-pint" },
    en: { name: "Imperial Pint", slug: "imperial-pint" },
    de: { name: "Imperiale Pint", slug: "imperiale-pint" },
    uz: { name: "Britaniya Pintasi", slug: "britaniya-pintasi" },
  },
  {
    id: "peck",
    category: "hacim",
    symbol: "pk",
    siFactor: 0.008809767994375,
    tr: { name: "Peck", slug: "peck" },
    en: { name: "US Peck", slug: "peck" },
    de: { name: "Peck", slug: "peck" },
    uz: { name: "Pek", slug: "pek" },
  },
  {
    id: "bushel",
    category: "hacim",
    symbol: "bu",
    siFactor: 0.03523907016688,
    tr: { name: "Bushel", slug: "bushel" },
    en: { name: "US Bushel", slug: "bushel" },
    de: { name: "Bushel", slug: "bushel" },
    uz: { name: "Bushel", slug: "bushel" },
  },
  {
    id: "ingiliz-galonu",
    category: "hacim",
    symbol: "imp gal",
    siFactor: 0.00454609,
    tr: { name: "İngiliz Galonu", slug: "ingiliz-galonu" },
    en: { name: "Imperial Gallon", slug: "imperial-gallon" },
    de: { name: "Imperiale Gallone", slug: "imperiale-gallone" },
    uz: { name: "Britaniya Galloni", slug: "britaniya-galloni" },
  },
  {
    id: "varil",
    category: "hacim",
    symbol: "bbl",
    siFactor: 0.158987294928,
    tr: { name: "Varil (petrol)", slug: "varil" },
    en: { name: "Barrel", slug: "barrel" },
    de: { name: "Barrel", slug: "barrel" },
    uz: { name: "Barrel", slug: "barrel" },
  },
  {
    id: "kile",
    category: "hacim",
    symbol: "kile",
    siFactor: 0.037,
    tr: { name: "Kile", slug: "kile" },
    en: { name: "Kile", slug: "kile" },
    de: { name: "Kile", slug: "kile" },
  },
  {
    id: "sinik",
    category: "hacim",
    symbol: "şinik",
    siFactor: 0.00925,
    tr: { name: "Şinik", slug: "sinik" },
    en: { name: "Shinik", slug: "shinik" },
    de: { name: "Shinik", slug: "shinik" },
  },

  // ---- kutle / mass / Masse ----
  {
    id: "kilogram",
    category: "kutle",
    symbol: "kg",
    siFactor: 1,
    tr: { name: "Kilogram", slug: "kilogram" },
    en: { name: "Kilogram", slug: "kilogram" },
    de: { name: "Kilogramm", slug: "kilogramm" },
    uz: { name: "Kilogramm", slug: "kilogramm" },
    enConversionSlug: "kilograms",
  },
  {
    id: "gram",
    category: "kutle",
    symbol: "g",
    siFactor: 0.001,
    tr: { name: "Gram", slug: "gram" },
    en: { name: "Gram", slug: "gram" },
    de: { name: "Gramm", slug: "gramm" },
    uz: { name: "Gramm", slug: "gramm" },
    enConversionSlug: "grams",
  },
  {
    id: "miligram",
    category: "kutle",
    symbol: "mg",
    siFactor: 0.000001,
    tr: { name: "Miligram", slug: "miligram" },
    en: { name: "Milligram", slug: "milligram" },
    de: { name: "Milligramm", slug: "milligramm" },
    uz: { name: "Milligramm", slug: "milligramm" },
    enConversionSlug: "milligrams",
  },
  {
    id: "kental",
    category: "kutle",
    symbol: "q",
    siFactor: 100,
    tr: { name: "Kental", slug: "kental" },
    en: { name: "Quintal", slug: "quintal" },
    de: { name: "Doppelzentner", slug: "doppelzentner" },
    uz: { name: "Sentner", slug: "sentner" },
  },
  {
    id: "ton",
    category: "kutle",
    symbol: "ton",
    displaySymbol: "t",
    siFactor: 1000,
    tr: { name: "Ton", slug: "ton" },
    en: { name: "Tonne", slug: "tonne" },
    de: { name: "Tonne", slug: "tonne" },
    uz: { name: "Tonna", slug: "tonna" },
    enConversionSlug: "tonnes",
  },
  {
    id: "pound",
    category: "kutle",
    symbol: "lb",
    siFactor: 0.45359237,
    tr: { name: "Pound", slug: "pound" },
    en: { name: "Pound", slug: "pound" },
    de: { name: "Pfund", slug: "pfund" },
    uz: { name: "Funt", slug: "funt" },
    enConversionSlug: "pounds",
  },
  {
    id: "stone",
    category: "kutle",
    symbol: "st",
    siFactor: 6.35029318,
    tr: { name: "Stone", slug: "stone" },
    en: { name: "Stone", slug: "stone" },
    de: { name: "Stone", slug: "stone" },
    uz: { name: "Stoun", slug: "stoun" },
  },
  {
    id: "grain",
    category: "kutle",
    symbol: "gr",
    siFactor: 0.00006479891,
    tr: { name: "Grain", slug: "grain" },
    en: { name: "Grain", slug: "grain" },
    de: { name: "Grain", slug: "grain" },
    uz: { name: "Grain", slug: "grain" },
  },
  {
    id: "dalton",
    category: "kutle",
    symbol: "Da",
    siFactor: 1.66053906892e-27,
    tr: { name: "Dalton", slug: "dalton" },
    en: { name: "Dalton", slug: "dalton" },
    de: { name: "Dalton", slug: "dalton" },
    uz: { name: "Dalton", slug: "dalton" },
  },
  {
    id: "ons",
    category: "kutle",
    symbol: "oz",
    siFactor: 0.028349523125,
    tr: { name: "Ons", slug: "ons" },
    en: { name: "Ounce", slug: "ounce" },
    de: { name: "Unze", slug: "unze" },
    uz: { name: "Untsiya", slug: "untsiya" },
    enConversionSlug: "ounces",
  },
  {
    id: "okka",
    category: "kutle",
    symbol: "okka",
    siFactor: 1.282945,
    tr: { name: "Okka", slug: "okka" },
    en: { name: "Okka", slug: "okka" },
    de: { name: "Okka", slug: "okka" },  },
  {
    id: "dirhem",
    category: "kutle",
    symbol: "dirhem",
    siFactor: 0.0032073625,
    tr: { name: "Dirhem", slug: "dirhem" },
    en: { name: "Dirham", slug: "dirham" },
    de: { name: "Dirham", slug: "dirham" },  },
  {
    id: "miskal",
    category: "kutle",
    symbol: "miskal",
    siFactor: 0.00481104375,
    tr: { name: "Miskal", slug: "miskal" },
    en: { name: "Miskal", slug: "miskal" },
    de: { name: "Miskal", slug: "miskal" },
  },
  {
    id: "batman",
    category: "kutle",
    symbol: "batman",
    siFactor: 7.69767,
    tr: { name: "Batman", slug: "batman" },
    en: { name: "Batman", slug: "batman" },
    de: { name: "Batman", slug: "batman" },
  },
  {
    id: "litra",
    category: "kutle",
    symbol: "litra",
    siFactor: 0.324,
    tr: { name: "Bizans Litrası", slug: "bizans-litrasi" },
    en: { name: "Byzantine Litra", slug: "byzantine-litra" },
    de: { name: "Byzantinische Litra", slug: "byzantinische-litra" },
  },
  {
    id: "ounkia",
    category: "kutle",
    symbol: "ounkia",
    siFactor: 0.027,
    tr: { name: "Bizans Onsu", slug: "bizans-onsu" },
    en: { name: "Byzantine Ounce", slug: "byzantine-ounce" },
    de: { name: "Byzantinische Ounkia", slug: "byzantinische-ounkia" },
  },
  {
    id: "troy-ons",
    category: "kutle",
    symbol: "ozt",
    siFactor: 0.0311034768,
    tr: { name: "Troy Ons", slug: "troy-ons" },
    en: { name: "Troy Ounce", slug: "troy-ounce" },
    de: { name: "Feinunze", slug: "feinunze" },
    uz: { name: "Troy Untsiya", slug: "troy-untsiya" },
    enConversionSlug: "troy-ounces",
  },
  {
    id: "karat",
    category: "kutle",
    symbol: "ct",
    siFactor: 0.0002,
    tr: { name: "Karat", slug: "karat" },
    en: { name: "Carat", slug: "carat" },
    de: { name: "Karat", slug: "karat" },
    uz: { name: "Karat", slug: "karat" },
    enConversionSlug: "carats",
  },

  // ---- o'zbekcha tarixiy massa birliklari (faqat uz, tr/en/de yo'q --
  // Buxoro/Xiva/Qo'qon/Turkiston davriga xos, Turkiyaga tegishli emas) ----
  {
    id: "miskal-uz",
    category: "kutle",
    symbol: "miskal-uz",
    siFactor: 0.00425,
    uz: { name: "Miskal", slug: "miskal" },
  },
  {
    id: "pud",
    category: "kutle",
    symbol: "pud",
    siFactor: 16.3804815,
    uz: { name: "Pud", slug: "pud" },
  },
  {
    id: "qadoq",
    category: "kutle",
    symbol: "qadoq",
    siFactor: 0.4095,
    uz: { name: "Qadoq", slug: "qadoq" },
  },
  {
    id: "dirhem-uz",
    category: "kutle",
    symbol: "dirhem-uz",
    siFactor: 0.00318,
    uz: { name: "Dirham", slug: "dirham" },
  },
  {
    id: "batman-uz",
    category: "kutle",
    symbol: "batman-uz",
    siFactor: 131.043852,
    uz: { name: "Botmon", slug: "botmon" },
  },

  // ---- yoğunluk / density (engine-only, no public pages) ----
  {
    id: "kg-m3",
    category: "yogunluk",
    symbol: "kg/m³",
    siFactor: 1,
    tr: { name: "Kilogram/Metreküp", slug: "kilogram-metrekup" },
    en: { name: "Kilogram per Cubic Meter", slug: "kilogram-per-cubic-meter" },
    de: { name: "Kilogramm/Kubikmeter", slug: "kilogramm-kubikmeter" },
  },
  {
    id: "g-cm3",
    category: "yogunluk",
    symbol: "g/cm³",
    siFactor: 1000,
    tr: { name: "Gram/Santimetreküp", slug: "gram-santimetrekup" },
    en: { name: "Gram per Cubic Centimeter", slug: "gram-per-cubic-centimeter" },
    de: { name: "Gramm/Kubikzentimeter", slug: "gramm-kubikzentimeter" },
  },
  { id: "g-ml", category: "yogunluk", symbol: "g/mL", siFactor: 1000, tr: { name: "Gram/Mililitre", slug: "gram-mililitre" }, de: { name: "Gramm pro Milliliter", slug: "gramm-pro-milliliter" } },
  { id: "kg-l", category: "yogunluk", symbol: "kg/L", siFactor: 1000, tr: { name: "Kilogram/Litre", slug: "kilogram-litre" }, de: { name: "Kilogramm pro Liter", slug: "kilogramm-pro-liter" } },
  { id: "g-l", category: "yogunluk", symbol: "g/L", siFactor: 1, tr: { name: "Gram/Litre", slug: "gram-litre" }, de: { name: "Gramm pro Liter", slug: "gramm-pro-liter" } },
  { id: "mg-l", category: "yogunluk", symbol: "mg/L", siFactor: 0.001, tr: { name: "Miligram/Litre", slug: "miligram-litre" }, de: { name: "Milligramm pro Liter", slug: "milligramm-pro-liter" } },
  { id: "lb-ft3", category: "yogunluk", symbol: "lb/ft³", siFactor: 16.01846337, tr: { name: "Pound/Fitküp", slug: "pound-fitkup" }, de: { name: "Pfund pro Kubikfuß", slug: "pfund-pro-kubikfuss" } },
  { id: "lb-in3", category: "yogunluk", symbol: "lb/in³", siFactor: 27679.90471, tr: { name: "Pound/İnçküp", slug: "pound-inckup" }, de: { name: "Pfund pro Kubikzoll", slug: "pfund-pro-kubikzoll" } },
  { id: "lb-gal-us", category: "yogunluk", symbol: "lb/gal (US)", siFactor: 119.826427, tr: { name: "Pound/Galon (US)", slug: "pound-galon" }, de: { name: "Pfund pro US-Gallone", slug: "pfund-pro-us-gallone" } },
  { id: "slug-ft3", category: "yogunluk", symbol: "slug/ft³", siFactor: 515.378818, tr: { name: "Slug/Fitküp", slug: "slug-fitkup" }, de: { name: "Slug pro Kubikfuß", slug: "slug-pro-kubikfuss" } },

  // ---- hız / speed / Geschwindigkeit ----
  {
    id: "metre-saniye",
    category: "hiz",
    symbol: "m/s",
    siFactor: 1,
    tr: { name: "Metre/Saniye", slug: "metre-saniye" },
    en: { name: "Meter per Second", slug: "meter-per-second" },
    de: { name: "Meter pro Sekunde", slug: "meter-pro-sekunde" },
    enConversionSlug: "meters-per-second",
    uz: { name: "Metr/Soniya", slug: "metr-soniyaga" },
  },
  {
    id: "kilometre-saat",
    category: "hiz",
    symbol: "km/h",
    siFactor: 1000 / 3600,
    tr: { name: "Kilometre/Saat", slug: "kilometre-saat" },
    en: { name: "Kilometer per Hour", slug: "kilometer-per-hour" },
    de: { name: "Kilometer pro Stunde", slug: "kilometer-pro-stunde" },
    enConversionSlug: "kilometers-per-hour",
    uz: { name: "Kilometr/soat", slug: "km-soat" },
  },
  { id: "km-s", category: "hiz", symbol: "km/s", siFactor: 1000, tr: { name: "Kilometre/Saniye", slug: "kilometre-saniye" }, en: { name: "Kilometer per Second", slug: "kilometer-per-second" }, de: { name: "Kilometer pro Sekunde", slug: "kilometer-pro-sekunde" }, uz: { name: "Kilometr/Soniya", slug: "km-soniyaga" } },
  {
    id: "mil-saat",
    category: "hiz",
    symbol: "mph",
    siFactor: 1609.344 / 3600,
    tr: { name: "Mil/Saat", slug: "mil-saat" },
    en: { name: "Mile per Hour", slug: "mile-per-hour" },
    de: { name: "Meilen pro Stunde", slug: "meilen-pro-stunde" },
    enConversionSlug: "miles-per-hour",
    uz: { name: "Milya/Soat", slug: "milya-soatiga" },
  },
  {
    id: "knot",
    category: "hiz",
    symbol: "knot",
    siFactor: 1852 / 3600,
    tr: { name: "Knot", slug: "knot" },
    en: { name: "Knot", slug: "knot" },
    de: { name: "Knoten", slug: "knoten" },
    uz: { name: "Uzel", slug: "uzel" },
  },
  { id: "ft-s", category: "hiz", symbol: "ft/s", siFactor: 0.3048, tr: { name: "Fit/Saniye", slug: "fit-saniye" }, en: { name: "Foot per Second", slug: "foot-per-second" }, de: { name: "Fuß pro Sekunde", slug: "fuss-pro-sekunde" }, uz: { name: "Fut/Soniya", slug: "fut-soniyaga" } },
  { id: "m-min", category: "hiz", symbol: "m/min", siFactor: 1 / 60, tr: { name: "Metre/Dakika", slug: "metre-dakika" }, en: { name: "Meter per Minute", slug: "meter-per-minute" }, de: { name: "Meter pro Minute", slug: "meter-pro-minute" }, uz: { name: "Metr/Daqiqa", slug: "metr-daqiqaga" } },
  { id: "km-min", category: "hiz", symbol: "km/min", siFactor: 1000 / 60, tr: { name: "Kilometre/Dakika", slug: "kilometre-dakika" }, en: { name: "Kilometer per Minute", slug: "kilometer-per-minute" }, de: { name: "Kilometer pro Minute", slug: "kilometer-pro-minute" }, uz: { name: "Kilometr/Daqiqa", slug: "km-daqiqaga" } },
  { id: "cm-s", category: "hiz", symbol: "cm/s", siFactor: 0.01, tr: { name: "Santimetre/Saniye", slug: "santimetre-saniye" }, en: { name: "Centimeter per Second", slug: "centimeter-per-second" }, de: { name: "Zentimeter pro Sekunde", slug: "zentimeter-pro-sekunde" }, uz: { name: "Santimetr/Soniya", slug: "santimetr-soniyaga" } },
  {
    id: "isik-hizi",
    category: "hiz",
    symbol: "c",
    siFactor: 299792458,
    tr: { name: "Işık Hızı", slug: "isik-hizi" },
    en: { name: "Speed of Light", slug: "speed-of-light" },
    de: { name: "Lichtgeschwindigkeit", slug: "lichtgeschwindigkeit" },
    uz: { name: "Yorug'lik Tezligi", slug: "yorugliktezligi" },
  },

  // ---- ivme / acceleration (engine-only) ----
  {
    id: "m-s2",
    category: "ivme",
    symbol: "m/s²",
    siFactor: 1,
    tr: { name: "Metre/saniyekare", slug: "metre-saniyekare" },
    en: { name: "Meter per Second Squared", slug: "meter-per-second-squared" },
    de: { name: "Meter pro Sekundequadrat", slug: "meter-pro-sekundequadrat" },
  },
  { id: "cm-s2", category: "ivme", symbol: "cm/s²", siFactor: 0.01, tr: { name: "Santimetre/saniyekare", slug: "santimetre-saniyekare" }, de: { name: "Zentimeter pro Sekundequadrat", slug: "zentimeter-pro-sekundequadrat" } },
  { id: "mm-s2", category: "ivme", symbol: "mm/s²", siFactor: 0.001, tr: { name: "Milimetre/saniyekare", slug: "milimetre-saniyekare" }, de: { name: "Millimeter pro Sekundequadrat", slug: "millimeter-pro-sekundequadrat" } },
  { id: "km-s2", category: "ivme", symbol: "km/s²", siFactor: 1000, tr: { name: "Kilometre/saniyekare", slug: "kilometre-saniyekare" }, de: { name: "Kilometer pro Sekundequadrat", slug: "kilometer-pro-sekundequadrat" } },
  {
    id: "ft-s2",
    category: "ivme",
    symbol: "ft/s²",
    siFactor: 0.3048,
    tr: { name: "Fit/saniyekare", slug: "fit-saniyekare" },
    en: { name: "Foot per Second Squared", slug: "foot-per-second-squared" },
    de: { name: "Fuß pro Sekundequadrat", slug: "fuss-pro-sekundequadrat" },
  },
  { id: "in-s2", category: "ivme", symbol: "in/s²", siFactor: 0.0254, tr: { name: "İnç/saniyekare", slug: "inc-saniyekare" }, de: { name: "Zoll pro Sekundequadrat", slug: "zoll-pro-sekundequadrat" } },
  { id: "m-min2", category: "ivme", symbol: "m/min²", siFactor: 1 / 3600, tr: { name: "Metre/dakikakare", slug: "metre-dakikakare" }, de: { name: "Meter pro Minutequadrat", slug: "meter-pro-minutequadrat" } },
  { id: "ft-min2", category: "ivme", symbol: "ft/min²", siFactor: 0.3048 / 3600, tr: { name: "Fit/dakikakare", slug: "fit-dakikakare" }, de: { name: "Fuß pro Minutequadrat", slug: "fuss-pro-minutequadrat" } },
  { id: "ivme-gal", category: "ivme", symbol: "gal", siFactor: 0.01, tr: { name: "Gal (ivme birimi)", slug: "gal-ivme" }, de: { name: "Gal (Beschleunigung)", slug: "gal-beschleunigung" } },
  {
    id: "g0",
    category: "ivme",
    symbol: "g0",
    siFactor: 9.80665,
    tr: { name: "Yerçekimi ivmesi (g)", slug: "yercekimi-ivmesi" },
    en: { name: "Standard Gravity (g)", slug: "standard-gravity" },
    de: { name: "Erdbeschleunigung (g)", slug: "erdbeschleunigung" },
  },

  // ---- zaman / time / Zeit ----
  {
    id: "saniye",
    category: "zaman",
    symbol: "s",
    siFactor: 1,
    tr: { name: "Saniye", slug: "saniye" },
    en: { name: "Second", slug: "second" },
    de: { name: "Sekunde", slug: "sekunde" },
    enConversionSlug: "seconds",
    uz: { name: "Soniya", slug: "soniya" },
  },
  { id: "milisaniye", category: "zaman", symbol: "ms", siFactor: 0.001, tr: { name: "Milisaniye", slug: "milisaniye" }, en: { name: "Millisecond", slug: "millisecond" }, de: { name: "Millisekunde", slug: "millisekunde" }, uz: { name: "Millisoniya", slug: "millisoniya" } },
  {
    id: "dakika",
    category: "zaman",
    symbol: "min",
    siFactor: 60,
    tr: { name: "Dakika", slug: "dakika" },
    en: { name: "Minute", slug: "minute" },
    de: { name: "Minute", slug: "minute" },
    enConversionSlug: "minutes",
    uz: { name: "Daqiqa", slug: "daqiqa" },
  },
  {
    id: "saat",
    category: "zaman",
    symbol: "h",
    siFactor: 3600,
    tr: { name: "Saat", slug: "saat" },
    en: { name: "Hour", slug: "hour" },
    de: { name: "Stunde", slug: "stunde" },
    enConversionSlug: "hours",
    uz: { name: "Soat", slug: "soat" },
  },
  {
    id: "gun",
    category: "zaman",
    symbol: "day",
    siFactor: 86400,
    tr: { name: "Gün", slug: "gun" },
    en: { name: "Day", slug: "day" },
    de: { name: "Tag", slug: "tag" },
    uz: { name: "Kun", slug: "kun" },
  },

  // ---- açısal hız (engine-only) ----
  {
    id: "rad-s",
    category: "acisal_hiz",
    symbol: "rad/s",
    siFactor: 1,
    tr: { name: "Radyan/saniye", slug: "radyan-saniye" },
    en: { name: "Radian per Second", slug: "radian-per-second" },
    de: { name: "Radiant pro Sekunde", slug: "radiant-pro-sekunde" },
  },
  { id: "rad-min", category: "acisal_hiz", symbol: "rad/min", siFactor: 1 / 60, tr: { name: "Radyan/dakika", slug: "radyan-dakika" }, de: { name: "Radiant pro Minute", slug: "radiant-pro-minute" } },
  { id: "rad-h", category: "acisal_hiz", symbol: "rad/h", siFactor: 1 / 3600, tr: { name: "Radyan/saat", slug: "radyan-saat" }, de: { name: "Radiant pro Stunde", slug: "radiant-pro-stunde" } },
  {
    id: "rpm",
    category: "acisal_hiz",
    symbol: "rpm",
    siFactor: (2 * Math.PI) / 60,
    tr: { name: "Devir/dakika (RPM)", slug: "devir-dakika" },
    en: { name: "Revolutions per Minute (RPM)", slug: "rpm" },
    de: { name: "Umdrehungen pro Minute (U/min)", slug: "umdrehungen-pro-minute" },
  },
  { id: "hz", category: "acisal_hiz", symbol: "Hz", siFactor: 2 * Math.PI, tr: { name: "Devir/saniye", slug: "devir-saniye-acisal" }, de: { name: "Umdrehung pro Sekunde", slug: "umdrehung-pro-sekunde" } },
  {
    id: "deg-s",
    category: "acisal_hiz",
    symbol: "°/s",
    siFactor: Math.PI / 180,
    tr: { name: "Derece/saniye", slug: "derece-saniye" },
    en: { name: "Degree per Second", slug: "degree-per-second" },
    de: { name: "Grad pro Sekunde", slug: "grad-pro-sekunde" },
  },
  { id: "deg-min", category: "acisal_hiz", symbol: "°/min", siFactor: Math.PI / (180 * 60), tr: { name: "Derece/dakika", slug: "derece-dakika" }, de: { name: "Grad pro Minute", slug: "grad-pro-minute" } },
  { id: "deg-h", category: "acisal_hiz", symbol: "°/h", siFactor: Math.PI / (180 * 3600), tr: { name: "Derece/saat", slug: "derece-saat" }, de: { name: "Grad pro Stunde", slug: "grad-pro-stunde" } },

  // ---- açı / angle / Winkel ----
  {
    id: "radyan",
    category: "aci",
    symbol: "rad",
    siFactor: 1,
    tr: { name: "Radyan", slug: "radyan" },
    en: { name: "Radian", slug: "radian" },
    de: { name: "Radiant", slug: "radiant" },
    uz: { name: "Radian", slug: "radian" },
  },
  {
    id: "derece",
    category: "aci",
    symbol: "°",
    siFactor: Math.PI / 180,
    tr: { name: "Derece", slug: "derece" },
    en: { name: "Degree", slug: "degree" },
    de: { name: "Grad", slug: "grad" },
    uz: { name: "Daraja", slug: "daraja" },
  },
  {
    id: "gradyan",
    category: "aci",
    symbol: "gon",
    siFactor: Math.PI / 200,
    tr: { name: "Gradyan", slug: "gradyan" },
    en: { name: "Gradian", slug: "gradian" },
    de: { name: "Gon", slug: "gon" },
    uz: { name: "Grad", slug: "grad" },
  },
  {
    id: "tam-tur",
    category: "aci",
    symbol: "tur",
    siFactor: 2 * Math.PI,
    tr: { name: "Tam Tur", slug: "tam-tur" },
    en: { name: "Full Turn", slug: "full-turn" },
    de: { name: "Vollwinkel", slug: "vollwinkel" },
    uz: { name: "To'liq Aylanish", slug: "toliq-aylanish" },
  },

  // ---- frekans / frequency / Frequenz ----
  {
    id: "hertz",
    category: "frekans",
    symbol: "Hz",
    siFactor: 1,
    tr: { name: "Hertz", slug: "hertz" },
    en: { name: "Hertz", slug: "hertz" },
    de: { name: "Hertz", slug: "hertz" },
    uz: { name: "Gerts", slug: "gerts" },
  },
  {
    id: "kilohertz",
    category: "frekans",
    symbol: "kHz",
    siFactor: 1000,
    tr: { name: "Kilohertz", slug: "kilohertz" },
    en: { name: "Kilohertz", slug: "kilohertz" },
    de: { name: "Kilohertz", slug: "kilohertz" },
    uz: { name: "Kilogerts", slug: "kilogerts" },
  },
  {
    id: "megahertz",
    category: "frekans",
    symbol: "MHz",
    siFactor: 1_000_000,
    tr: { name: "Megahertz", slug: "megahertz" },
    en: { name: "Megahertz", slug: "megahertz" },
    de: { name: "Megahertz", slug: "megahertz" },
    uz: { name: "Megagerts", slug: "megagerts" },
  },
  {
    id: "gigahertz",
    category: "frekans",
    symbol: "GHz",
    siFactor: 1_000_000_000,
    tr: { name: "Gigahertz", slug: "gigahertz" },
    en: { name: "Gigahertz", slug: "gigahertz" },
    de: { name: "Gigahertz", slug: "gigahertz" },
    uz: { name: "Gigagerts", slug: "gigagerts" },
  },

  // ---- kuvvet / tork / momentum (engine-only) ----
  {
    id: "newton",
    category: "kuvvet",
    symbol: "N",
    siFactor: 1,
    tr: { name: "Newton", slug: "newton" },
    en: { name: "Newton", slug: "newton" },
    de: { name: "Newton", slug: "newton" },
    uz: { name: "Nyuton", slug: "nyuton" },
  },
  { id: "kilonewton", category: "kuvvet", symbol: "kN", siFactor: 1000, tr: { name: "Kilonewton", slug: "kilonewton" }, de: { name: "Kilonewton", slug: "kilonewton" } },
  { id: "dyn", category: "kuvvet", symbol: "dyn", siFactor: 0.00001, tr: { name: "Dyn", slug: "dyn" }, de: { name: "Dyn", slug: "dyn" } },
  { id: "lbf", category: "kuvvet", symbol: "lbf", siFactor: 4.4482216152605, tr: { name: "Pound-kuvvet", slug: "pound-kuvvet" }, de: { name: "Pound-Force", slug: "pound-force" } },
  {
    id: "kilogram-kuvvet",
    category: "kuvvet",
    symbol: "kgf",
    siFactor: 9.80665,
    tr: { name: "Kilogram-kuvvet", slug: "kilogram-kuvvet" },
    en: { name: "Kilogram-Force", slug: "kilogram-force" },
    de: { name: "Kilogramm-Kraft", slug: "kilogramm-kraft" },
    uz: { name: "Kilogram-Kuch", slug: "kilogram-kuch" },
  },
  {
    id: "newton-metre",
    category: "tork",
    symbol: "N·m",
    siFactor: 1,
    tr: { name: "Newton-metre", slug: "newton-metre" },
    en: { name: "Newton-Meter", slug: "newton-meter" },
    de: { name: "Newtonmeter", slug: "newtonmeter" },
    uz: { name: "Nyuton-Metr", slug: "nyuton-metr" },
  },
  { id: "kilonewton-metre", category: "tork", symbol: "kN·m", siFactor: 1000, tr: { name: "Kilonewton-metre", slug: "kilonewton-metre" }, de: { name: "Kilonewtonmeter", slug: "kilonewtonmeter" } },
  {
    id: "kilogram-kuvvet-metre",
    category: "tork",
    symbol: "kgf·m",
    siFactor: 9.80665,
    tr: { name: "Kilogram-kuvvet-metre", slug: "kilogram-kuvvet-metre" },
    en: { name: "Kilogram-Force Meter", slug: "kilogram-force-meter" },
    de: { name: "Kilogramm-Kraft-Meter", slug: "kilogramm-kraft-meter" },
    uz: { name: "Kilogram-Kuch-Metr", slug: "kilogram-kuch-metr" },
  },
  {
    id: "lb-ft",
    category: "tork",
    symbol: "lb·ft",
    siFactor: 1.355817948,
    tr: { name: "Pound-fit (lb-ft)", slug: "pound-fit" },
    en: { name: "Pound-Foot", slug: "pound-foot" },
    de: { name: "Pfund-Fuß", slug: "pfund-fuss" },
  },
  {
    id: "kg-m-s",
    category: "momentum",
    symbol: "kg·m/s",
    siFactor: 1,
    tr: { name: "Kilogram-metre/saniye", slug: "kilogram-metre-saniye" },
    en: { name: "Kilogram-Meter per Second", slug: "kilogram-meter-per-second" },
    de: { name: "Kilogramm-Meter/Sekunde", slug: "kilogramm-meter-sekunde" },
  },
  {
    id: "n-s",
    category: "momentum",
    symbol: "N·s",
    siFactor: 1,
    tr: { name: "Newton-saniye", slug: "newton-saniye" },
    en: { name: "Newton-Second", slug: "newton-second" },
    de: { name: "Newtonsekunde", slug: "newtonsekunde" },
  },
  { id: "lb-ft-s", category: "momentum", symbol: "lb·ft/s", siFactor: 0.138255, tr: { name: "Pound-fit/saniye", slug: "pound-fit-saniye" }, de: { name: "Pfund-Fuß pro Sekunde", slug: "pfund-fuss-pro-sekunde" } },

  // ---- basınç / pressure / Druck ----
  {
    id: "pascal",
    category: "basinc",
    symbol: "Pa",
    siFactor: 1,
    tr: { name: "Pascal", slug: "pascal" },
    en: { name: "Pascal", slug: "pascal" },
    de: { name: "Pascal", slug: "pascal" },
    enConversionSlug: "pascals",
    uz: { name: "Paskal", slug: "paskal" },
  },
  {
    id: "kilopascal",
    category: "basinc",
    symbol: "kPa",
    siFactor: 1000,
    tr: { name: "Kilopascal", slug: "kilopascal" },
    en: { name: "Kilopascal", slug: "kilopascal" },
    de: { name: "Kilopascal", slug: "kilopascal" },
    enConversionSlug: "kilopascals",
    uz: { name: "Kilopaskal", slug: "kilopaskal" },
  },
  {
    id: "megapascal",
    category: "basinc",
    symbol: "MPa",
    siFactor: 1000000,
    tr: { name: "Megapascal", slug: "megapascal" },
    en: { name: "Megapascal", slug: "megapascal" },
    de: { name: "Megapascal", slug: "megapascal" },
    uz: { name: "Megapaskal", slug: "megapaskal" },
    enConversionSlug: "megapascals",
  },
  {
    id: "hektopascal",
    category: "basinc",
    symbol: "hPa",
    siFactor: 100,
    tr: { name: "Hektopascal", slug: "hektopascal" },
    en: { name: "Hectopascal", slug: "hectopascal" },
    de: { name: "Hektopascal", slug: "hektopascal" },
    uz: { name: "Gektopaskal", slug: "gektopaskal" },
    enConversionSlug: "hectopascals",
  },
  {
    id: "bar",
    category: "basinc",
    symbol: "bar",
    siFactor: 100000,
    tr: { name: "Bar", slug: "bar" },
    en: { name: "Bar", slug: "bar" },
    de: { name: "Bar", slug: "bar" },
    enConversionSlug: "bars",
    uz: { name: "Bar", slug: "bar" },
  },
  {
    id: "milibar",
    category: "basinc",
    symbol: "mbar",
    siFactor: 100,
    tr: { name: "Milibar", slug: "milibar" },
    en: { name: "Millibar", slug: "millibar" },
    de: { name: "Millibar", slug: "millibar" },
    uz: { name: "Millibar", slug: "millibar" },
  },
  {
    id: "atmosfer",
    category: "basinc",
    symbol: "atm",
    siFactor: 101325,
    tr: { name: "Atmosfer", slug: "atmosfer" },
    en: { name: "Atmosphere", slug: "atmosphere" },
    de: { name: "Atmosphäre", slug: "atmosphaere" },
    enConversionSlug: "atmospheres",
    uz: { name: "Atmosfera", slug: "atmosfera" },
  },
  { id: "teknik-atmosfer", category: "basinc", symbol: "at", siFactor: 98066.5, tr: { name: "Teknik Atmosfer", slug: "teknik-atmosfer" }, en: { name: "Technical Atmosphere", slug: "technical-atmosphere" }, de: { name: "Technische Atmosphäre", slug: "technische-atmosphaere" }, uz: { name: "Texnik Atmosfera", slug: "texnik-atmosfera" } },
  {
    id: "psi",
    category: "basinc",
    symbol: "psi",
    siFactor: 6894.757293168,
    tr: { name: "PSI", slug: "psi" },
    en: { name: "PSI", slug: "psi" },
    de: { name: "PSI", slug: "psi" },
    enConversionSlug: "psi",
    uz: { name: "PSI", slug: "psi" },
  },
  {
    id: "milimetre-civa",
    category: "basinc",
    symbol: "mmHg",
    siFactor: 133.322387415,
    tr: { name: "Milimetre Cıva", slug: "milimetre-civa" },
    en: { name: "Millimeter of Mercury", slug: "millimeter-of-mercury" },
    de: { name: "Millimeter Quecksilbersäule", slug: "millimeter-quecksilbersaeule" },
    enConversionSlug: "millimeters-of-mercury",
    uz: { name: "Simob Ustuni Millimetri", slug: "simob-ustuni-millimetri" },
  },
  { id: "mmh2o", category: "basinc", symbol: "mmH2O", siFactor: 9.80665, tr: { name: "Milimetre Su Sütunu", slug: "milimetre-su-sutunu" }, en: { name: "Millimeter of Water", slug: "millimeter-of-water" }, de: { name: "Millimeter Wassersäule", slug: "millimeter-wassersaeule" }, uz: { name: "Suv Ustuni Millimetri", slug: "suv-ustuni-millimetri" } },
  {
    id: "torr",
    category: "basinc",
    symbol: "Torr",
    siFactor: 101325 / 760,
    tr: { name: "Torr", slug: "torr" },
    en: { name: "Torr", slug: "torr" },
    de: { name: "Torr", slug: "torr" },
    uz: { name: "Torr", slug: "torr" },
  },
  {
    id: "kilogram-kuvvet-santimetrekare",
    category: "basinc",
    symbol: "kgf/cm²",
    siFactor: 98066.5,
    tr: { name: "Kilogram-kuvvet/Santimetrekare", slug: "kilogram-kuvvet-santimetrekare" },
    en: {
      name: "Kilogram-Force per Square Centimeter",
      slug: "kilogram-force-per-square-centimeter",
    },
    de: {
      name: "Kilogramm-Kraft pro Quadratzentimeter",
      slug: "kilogramm-kraft-pro-quadratzentimeter",
    },
    enConversionSlug: "kilogram-force-per-square-centimeter",
    uz: { name: "Kilogram-Kuch/Kvadrat Santimetr", slug: "kilogram-kuch-kvadrat-santimetrga" },
  },

  // ---- viskozite (engine-only) ----
  {
    id: "pascal-saniye",
    category: "viskozite_dinamik",
    symbol: "Pa·s",
    siFactor: 1,
    tr: { name: "Pascal-saniye", slug: "pascal-saniye" },
    en: { name: "Pascal-Second", slug: "pascal-second" },
    de: { name: "Pascalsekunde", slug: "pascalsekunde" },
    uz: { name: "Paskal-Soniya", slug: "paskal-soniya" },
  },
  { id: "milipascal-saniye", category: "viskozite_dinamik", symbol: "mPa·s", siFactor: 0.001, tr: { name: "Milipaskal-saniye", slug: "milipaskal-saniye" }, de: { name: "Millipascalsekunde", slug: "millipascalsekunde" } },
  { id: "poise", category: "viskozite_dinamik", symbol: "P", siFactor: 0.1, tr: { name: "Poise", slug: "poise" }, de: { name: "Poise", slug: "poise" } },
  {
    id: "centipoise",
    category: "viskozite_dinamik",
    symbol: "cP",
    siFactor: 0.001,
    tr: { name: "Santipoise", slug: "santipoise" },
    en: { name: "Centipoise", slug: "centipoise" },
    de: { name: "Centipoise", slug: "centipoise" },
  },
  {
    id: "m2-s",
    category: "viskozite_kinematik",
    symbol: "m²/s",
    siFactor: 1,
    tr: { name: "Metrekare/saniye", slug: "metrekare-saniye" },
    en: { name: "Square Meter per Second", slug: "square-meter-per-second" },
    de: { name: "Quadratmeter pro Sekunde", slug: "quadratmeter-pro-sekunde" },
  },
  { id: "mm2-s", category: "viskozite_kinematik", symbol: "mm²/s", siFactor: 0.000001, tr: { name: "Milimetrekare/saniye", slug: "milimetrekare-saniye" }, de: { name: "Quadratmillimeter pro Sekunde", slug: "quadratmillimeter-pro-sekunde" } },
  {
    id: "centistoke",
    category: "viskozite_kinematik",
    symbol: "cSt",
    siFactor: 0.000001,
    tr: { name: "Santistok", slug: "santistok" },
    en: { name: "Centistoke", slug: "centistoke" },
    de: { name: "Zentistokes", slug: "zentistokes" },
  },

  // ---- debi_hacimsel / debi_kutlesel (engine-only) ----
  {
    id: "m3-s",
    category: "debi_hacimsel",
    symbol: "m³/s",
    siFactor: 1,
    tr: { name: "Metreküp/saniye", slug: "metrekup-saniye" },
    en: { name: "Cubic Meter per Second", slug: "cubic-meter-per-second" },
    de: { name: "Kubikmeter pro Sekunde", slug: "kubikmeter-pro-sekunde" },
  },
  { id: "l-s", category: "debi_hacimsel", symbol: "L/s", siFactor: 0.001, tr: { name: "Litre/saniye", slug: "litre-saniye" }, de: { name: "Liter pro Sekunde", slug: "liter-pro-sekunde" } },
  { id: "m3-h-hacimsel", category: "debi_hacimsel", symbol: "m³/h", siFactor: 1 / 3600, tr: { name: "Metreküp/saat", slug: "metrekup-saat-hacimsel" }, de: { name: "Kubikmeter pro Stunde (Volumenstrom)", slug: "kubikmeter-pro-stunde-volumenstrom" } },
  { id: "l-min-hacimsel", category: "debi_hacimsel", symbol: "L/min", siFactor: 0.001 / 60, tr: { name: "Litre/dakika", slug: "litre-dakika-hacimsel" }, de: { name: "Liter pro Minute (Volumenstrom)", slug: "liter-pro-minute-volumenstrom" } },
  {
    id: "cfm",
    category: "debi_hacimsel",
    symbol: "cfm",
    siFactor: 0.028316846592 / 60,
    tr: { name: "Fitküp/dakika (CFM)", slug: "fitkup-dakika" },
    en: { name: "Cubic Feet per Minute (CFM)", slug: "cubic-feet-per-minute" },
    de: { name: "Kubikfuß pro Minute (CFM)", slug: "kubikfuss-pro-minute" },
  },
  {
    id: "gpm",
    category: "debi_hacimsel",
    symbol: "gpm",
    siFactor: 0.003785411784 / 60,
    tr: { name: "Galon/dakika (GPM)", slug: "galon-dakika" },
    en: { name: "US Gallons per Minute (GPM)", slug: "gallons-per-minute" },
    de: { name: "Gallonen pro Minute (GPM)", slug: "gallonen-pro-minute" },
  },
  {
    id: "kg-s",
    category: "debi_kutlesel",
    symbol: "kg/s",
    siFactor: 1,
    tr: { name: "Kilogram/saniye", slug: "kilogram-saniye" },
    en: { name: "Kilogram per Second", slug: "kilogram-per-second" },
    de: { name: "Kilogramm pro Sekunde", slug: "kilogramm-pro-sekunde" },
  },
  {
    id: "kg-h",
    category: "debi_kutlesel",
    symbol: "kg/h",
    siFactor: 1 / 3600,
    tr: { name: "Kilogram/saat", slug: "kilogram-saat" },
    en: { name: "Kilogram per Hour", slug: "kilogram-per-hour" },
    de: { name: "Kilogramm pro Stunde", slug: "kilogramm-pro-stunde" },
  },
  { id: "g-s", category: "debi_kutlesel", symbol: "g/s", siFactor: 0.001, tr: { name: "Gram/saniye", slug: "gram-saniye" }, de: { name: "Gramm pro Sekunde", slug: "gramm-pro-sekunde" } },
  { id: "g-h", category: "debi_kutlesel", symbol: "g/h", siFactor: 0.001 / 3600, tr: { name: "Gram/saat", slug: "gram-saat" }, de: { name: "Gramm pro Stunde", slug: "gramm-pro-stunde" } },

  // ---- enerji / energy / Energie ----
  {
    id: "joule",
    category: "enerji",
    symbol: "J",
    siFactor: 1,
    tr: { name: "Joule", slug: "joule" },
    en: { name: "Joule", slug: "joule" },
    de: { name: "Joule", slug: "joule" },
    enConversionSlug: "joules",
    uz: { name: "Joul", slug: "joul" },
  },
  {
    id: "kilojoule",
    category: "enerji",
    symbol: "kJ",
    siFactor: 1000,
    tr: { name: "Kilojoule", slug: "kilojoule" },
    en: { name: "Kilojoule", slug: "kilojoule" },
    de: { name: "Kilojoule", slug: "kilojoule" },
    uz: { name: "Kilojoul", slug: "kilojoul" },
  },
  { id: "megajoule", category: "enerji", symbol: "MJ", siFactor: 1_000_000, tr: { name: "Megajoule", slug: "megajoule" }, en: { name: "Megajoule", slug: "megajoule" }, de: { name: "Megajoule", slug: "megajoule" }, uz: { name: "Megajoul", slug: "megajoul" } },
  {
    id: "watt-saat",
    category: "enerji",
    symbol: "Wh",
    siFactor: 3600,
    tr: { name: "Watt-saat", slug: "watt-saat" },
    en: { name: "Watt-hour", slug: "watt-hour" },
    de: { name: "Wattstunde", slug: "wattstunde" },
    uz: { name: "Vatt-Soat", slug: "vatt-soat" },
  },
  {
    id: "kilovatsaat",
    category: "enerji",
    symbol: "kWh",
    siFactor: 3_600_000,
    tr: { name: "Kilovat-saat", slug: "kilovatsaat" },
    en: { name: "Kilowatt-hour", slug: "kilowatt-hour" },
    de: { name: "Kilowattstunde", slug: "kilowattstunde" },
    enConversionSlug: "kilowatt-hours",
    uz: { name: "Kilovatt-Soat", slug: "kilovatt-soat" },
  },
  {
    id: "watt",
    category: "guc",
    symbol: "W",
    siFactor: 1,
    tr: { name: "Watt", slug: "watt" },
    en: { name: "Watt", slug: "watt" },
    de: { name: "Watt", slug: "watt" },
    enConversionSlug: "watts",
    uz: { name: "Vatt", slug: "vatt" },
  },
  {
    id: "sogutma-tonu",
    category: "guc",
    symbol: "TR",
    siFactor: 3516.853,
    tr: { name: "Soğutma Tonu", slug: "sogutma-tonu" },
    en: { name: "Ton of Refrigeration", slug: "ton-of-refrigeration" },
    de: { name: "Kältetonne", slug: "kaeltetonne" },
  },
  {
    id: "kilowatt",
    category: "guc",
    symbol: "kW",
    siFactor: 1000,
    tr: { name: "Kilowatt", slug: "kilowatt" },
    en: { name: "Kilowatt", slug: "kilowatt" },
    de: { name: "Kilowatt", slug: "kilowatt" },
    enConversionSlug: "kilowatts",
    uz: { name: "Kilovatt", slug: "kilovatt" },
  },
  {
    id: "kalori",
    category: "enerji",
    symbol: "cal",
    siFactor: 4.184,
    tr: { name: "Kalori", slug: "kalori" },
    en: { name: "Calorie", slug: "calorie" },
    de: { name: "Kalorie", slug: "kalorie" },
    uz: { name: "Kaloriya", slug: "kaloriya" },
  },
  {
    id: "kilokalori",
    category: "enerji",
    symbol: "kcal",
    siFactor: 4184,
    tr: { name: "Kilokalori", slug: "kilokalori" },
    en: { name: "Kilocalorie", slug: "kilocalorie" },
    de: { name: "Kilokalorie", slug: "kilokalorie" },
    uz: { name: "Kilokaloriya", slug: "kilokaloriya" },
  },
  {
    id: "btu",
    category: "enerji",
    symbol: "Btu",
    siFactor: 1055.05585262,
    tr: { name: "BTU", slug: "btu" },
    en: { name: "British Thermal Unit", slug: "btu" },
    de: { name: "BTU", slug: "btu" },
    uz: { name: "BTU", slug: "btu" },
  },
  { id: "therm", category: "enerji", symbol: "th", siFactor: 1.05506e8, tr: { name: "Therm", slug: "therm" }, en: { name: "Therm", slug: "therm" }, de: { name: "Therm", slug: "therm" }, uz: { name: "Term", slug: "term" } },
  { id: "quad-btu", category: "enerji", symbol: "quad BTU", siFactor: 1.05506e18, tr: { name: "Quad BTU", slug: "quad-btu" }, en: { name: "Quad BTU", slug: "quad-btu" }, de: { name: "Quad BTU", slug: "quad-btu" }, uz: { name: "Kvadrillion BTU", slug: "kvadrillion-btu" } },
  {
    id: "elektronvolt",
    category: "enerji",
    symbol: "eV",
    siFactor: 1.602176634e-19,
    tr: { name: "Elektronvolt", slug: "elektronvolt" },
    en: { name: "Electronvolt", slug: "electronvolt" },
    de: { name: "Elektronenvolt", slug: "elektronenvolt" },
    uz: { name: "Elektronvolt", slug: "elektronvolt" },
  },

  // ---- güç ----
  {
    id: "megawatt",
    category: "guc",
    symbol: "MW",
    siFactor: 1_000_000,
    tr: { name: "Megawatt", slug: "megawatt" },
    en: { name: "Megawatt", slug: "megawatt" },
    de: { name: "Megawatt", slug: "megawatt" },
    uz: { name: "Megavatt", slug: "megavatt" },
  },
  {
    id: "beygirgucu-metric",
    category: "guc",
    symbol: "hp",
    siFactor: 735.49875,
    tr: { name: "Beygirgücü", slug: "beygirgucu" },
    en: { name: "Horsepower", slug: "horsepower" },
    de: { name: "PS", slug: "ps" },
  },
  {
    id: "beygirgucu-mechanical",
    category: "guc",
    symbol: "HP",
    siFactor: 745.69987158227022,
    tr: { name: "Beygirgücü (Mekanik)", slug: "beygirgucu-mekanik" },
    en: { name: "Horsepower (Mechanical)", slug: "horsepower-mechanical" },
    de: { name: "PS (mechanisch)", slug: "ps-mechanisch" },
  },
  {
    id: "btu-saat",
    category: "guc",
    symbol: "BTU/h",
    siFactor: 0.29307107,
    tr: { name: "BTU/saat", slug: "btu-saat" },
    en: { name: "BTU per hour", slug: "btu-per-hour" },
    de: { name: "BTU pro Stunde", slug: "btu-pro-stunde" },
  },

  // ---- sıcaklık / temperature / Temperatur (non-linear, no siFactor) ----
  {
    id: "santigrat",
    category: "sicaklik",
    symbol: "C",
    displaySymbol: "°C",
    isTemperature: true,
    tr: { name: "Santigrat", slug: "santigrat" },
    en: { name: "Celsius", slug: "celsius" },
    de: { name: "Celsius", slug: "celsius" },
    uz: { name: "Selsiy", slug: "selsiy" },
    enConversionSlug: "celsius",
  },
  {
    id: "fahrenhayt",
    category: "sicaklik",
    symbol: "F",
    displaySymbol: "°F",
    isTemperature: true,
    tr: { name: "Fahrenheit", slug: "fahrenhayt" },
    en: { name: "Fahrenheit", slug: "fahrenheit" },
    de: { name: "Fahrenheit", slug: "fahrenheit" },
    uz: { name: "Farengeyt", slug: "farengeyt" },
    enConversionSlug: "fahrenheit",
  },
  {
    id: "kelvin",
    category: "sicaklik",
    symbol: "K",
    isTemperature: true,
    tr: { name: "Kelvin", slug: "kelvin" },
    en: { name: "Kelvin", slug: "kelvin" },
    de: { name: "Kelvin", slug: "kelvin" },
    uz: { name: "Kelvin", slug: "kelvin" },
    enConversionSlug: "kelvin",
  },
  {
    id: "rankine",
    category: "sicaklik",
    symbol: "R",
    displaySymbol: "°R",
    isTemperature: true,
    tr: { name: "Rankine", slug: "rankine" },
    en: { name: "Rankine", slug: "rankine" },
    de: { name: "Rankine", slug: "rankine" },
    uz: { name: "Rankin", slug: "rankin" },
  },
  {
    id: "reaumur",
    category: "sicaklik",
    symbol: "Re",
    displaySymbol: "°Ré",
    isTemperature: true,
    tr: { name: "Réaumur", slug: "reaumur" },
    en: { name: "Réaumur", slug: "reaumur" },
    de: { name: "Réaumur", slug: "reaumur" },
    uz: { name: "Reomyur", slug: "reomyur" },
  },

  // ---- ısıl iletkenlik / ısı akısı / özgül ısı (engine-only) ----
  {
    id: "w-mk",
    category: "isil_iletkenlik",
    symbol: "W/m·K",
    siFactor: 1,
    tr: { name: "Watt/metre-Kelvin", slug: "watt-metre-kelvin" },
    en: { name: "Watt per Meter-Kelvin", slug: "watt-per-meter-kelvin" },
    de: { name: "Watt pro Meter-Kelvin", slug: "watt-pro-meter-kelvin" },
  },
  { id: "kw-mk", category: "isil_iletkenlik", symbol: "kW/m·K", siFactor: 1000, tr: { name: "Kilowatt/metre-Kelvin", slug: "kilowatt-metre-kelvin" }, de: { name: "Kilowatt pro Meter-Kelvin", slug: "kilowatt-pro-meter-kelvin" } },
  { id: "w-cmk", category: "isil_iletkenlik", symbol: "W/cm·K", siFactor: 100, tr: { name: "Watt/santimetre-Kelvin", slug: "watt-santimetre-kelvin" }, de: { name: "Watt pro Zentimeter-Kelvin", slug: "watt-pro-zentimeter-kelvin" } },
  {
    id: "btu-hftf",
    category: "isil_iletkenlik",
    symbol: "Btu/h·ft·°F",
    siFactor: 1.730735,
    tr: { name: "BTU/saat-fit-°F", slug: "btu-saat-fit-f" },
    en: { name: "BTU per Hour-Foot-°F", slug: "btu-per-hour-foot-f" },
    de: { name: "BTU pro Stunde-Fuß-°F", slug: "btu-pro-stunde-fuss-f" },
  },
  {
    id: "w-m2",
    category: "isi_akisi",
    symbol: "W/m²",
    siFactor: 1,
    tr: { name: "Watt/metrekare", slug: "watt-metrekare" },
    en: { name: "Watt per Square Meter", slug: "watt-per-square-meter" },
    de: { name: "Watt pro Quadratmeter", slug: "watt-pro-quadratmeter" },
  },
  {
    id: "kw-m2",
    category: "isi_akisi",
    symbol: "kW/m²",
    siFactor: 1000,
    tr: { name: "Kilowatt/metrekare", slug: "kilowatt-metrekare" },
    en: { name: "Kilowatt per Square Meter", slug: "kilowatt-per-square-meter" },
    de: { name: "Kilowatt pro Quadratmeter", slug: "kilowatt-pro-quadratmeter" },
  },
  { id: "cal-cm2s", category: "isi_akisi", symbol: "cal/cm²·s", siFactor: 41840, tr: { name: "Kalori/santimetrekare-saniye", slug: "kalori-santimetrekare-saniye" }, de: { name: "Kalorie pro Quadratzentimeter-Sekunde", slug: "kalorie-pro-quadratzentimeter-sekunde" } },
  {
    id: "j-kgk",
    category: "ozgul_isi",
    symbol: "J/kg·K",
    siFactor: 1,
    tr: { name: "Joule/kilogram-Kelvin", slug: "joule-kilogram-kelvin" },
    en: { name: "Joule per Kilogram-Kelvin", slug: "joule-per-kilogram-kelvin" },
    de: { name: "Joule pro Kilogramm-Kelvin", slug: "joule-pro-kilogramm-kelvin" },
  },
  { id: "kj-kgk", category: "ozgul_isi", symbol: "kJ/kg·K", siFactor: 1000, tr: { name: "Kilojoule/kilogram-Kelvin", slug: "kilojoule-kilogram-kelvin" }, de: { name: "Kilojoule pro Kilogramm-Kelvin", slug: "kilojoule-pro-kilogramm-kelvin" } },
  {
    id: "cal-gk",
    category: "ozgul_isi",
    symbol: "cal/g·K",
    siFactor: 4.184,
    tr: { name: "Kalori/gram-Kelvin", slug: "kalori-gram-kelvin" },
    en: { name: "Calorie per Gram-Kelvin", slug: "calorie-per-gram-kelvin" },
    de: { name: "Kalorie pro Gramm-Kelvin", slug: "kalorie-pro-gramm-kelvin" },
  },
  { id: "btu-lbf", category: "ozgul_isi", symbol: "Btu/lb·°F", siFactor: 4186.8, tr: { name: "Btu/pound-Fahrenhayt", slug: "btu-pound-fahrenhayt" }, de: { name: "BTU pro Pfund-Fahrenheit", slug: "btu-pro-pfund-fahrenheit" } },

  // ---- debi / elektrik ("core" categories, distinct from *_hacimsel/*_kutlesel/*_gerilim/*_akim) ----
  {
    id: "metrekup-saat",
    category: "debi",
    symbol: "m³/h",
    siFactor: 1 / 3600,
    tr: { name: "Metreküp/Saat", slug: "metrekup-saat" },
    en: { name: "Cubic Meter per Hour", slug: "cubic-meter-per-hour" },
    de: { name: "Kubikmeter pro Stunde", slug: "kubikmeter-pro-stunde" },
    enConversionSlug: "cubic-meters-per-hour",
    uz: { name: "Kub Metr/Soat", slug: "kub-metr-soatiga" },
  },
  {
    id: "litre-dakika",
    category: "debi",
    symbol: "L/min",
    siFactor: 0.001 / 60,
    tr: { name: "Litre/Dakika", slug: "litre-dakika" },
    en: { name: "Liter per Minute", slug: "liter-per-minute" },
    de: { name: "Liter pro Minute", slug: "liter-pro-minute" },
    enConversionSlug: "liters-per-minute",
    uz: { name: "Litr/Daqiqa", slug: "litr-daqiqaga" },
  },
  {
    id: "volt",
    category: "elektrik",
    symbol: "V",
    siFactor: 1,
    tr: { name: "Volt", slug: "volt" },
    en: { name: "Volt", slug: "volt" },
    de: { name: "Volt", slug: "volt" },
    enConversionSlug: "volts",
    uz: { name: "Volt", slug: "volt" },
  },
  {
    id: "kilovolt",
    category: "elektrik",
    symbol: "kV",
    siFactor: 1000,
    tr: { name: "Kilovolt", slug: "kilovolt" },
    en: { name: "Kilovolt", slug: "kilovolt" },
    de: { name: "Kilovolt", slug: "kilovolt" },
    enConversionSlug: "kilovolts",
    uz: { name: "Kilovolt", slug: "kilovolt" },
  },
  {
    id: "amper",
    category: "elektrik",
    symbol: "A",
    siFactor: 1,
    tr: { name: "Amper", slug: "amper" },
    en: { name: "Ampere", slug: "ampere" },
    de: { name: "Ampere", slug: "ampere" },
    enConversionSlug: "amperes",
    uz: { name: "Amper", slug: "amper" },
  },
  {
    id: "miliamper",
    category: "elektrik",
    symbol: "mA",
    siFactor: 0.001,
    tr: { name: "Miliamper", slug: "miliamper" },
    en: { name: "Milliampere", slug: "milliampere" },
    de: { name: "Milliampere", slug: "milliampere" },
    enConversionSlug: "milliamperes",
    uz: { name: "Milliamper", slug: "milliamper" },
  },

  // ---- elektrik_direnc / gerilim / akım / kapasitans / enduktans / yük / manyetik (engine-only) ----
  {
    id: "ohm",
    category: "elektrik_direnc",
    symbol: "Ω",
    siFactor: 1,
    tr: { name: "Ohm", slug: "ohm" },
    en: { name: "Ohm", slug: "ohm" },
    de: { name: "Ohm", slug: "ohm" },
    uz: { name: "Om", slug: "om" },
  },
  {
    id: "kiloohm",
    category: "elektrik_direnc",
    symbol: "kΩ",
    siFactor: 1000,
    tr: { name: "Kiloohm", slug: "kiloohm" },
    en: { name: "Kiloohm", slug: "kiloohm" },
    de: { name: "Kiloohm", slug: "kiloohm" },
    uz: { name: "Kiloom", slug: "kiloom" },
  },
  {
    id: "megaohm",
    category: "elektrik_direnc",
    symbol: "MΩ",
    siFactor: 1_000_000,
    tr: { name: "Megaohm", slug: "megaohm" },
    en: { name: "Megaohm", slug: "megaohm" },
    de: { name: "Megaohm", slug: "megaohm" },
    uz: { name: "Megaom", slug: "megaom" },
  },
  { id: "gerilim-volt", category: "elektrik_gerilim", symbol: "V", siFactor: 1 },
  { id: "gerilim-kilovolt", category: "elektrik_gerilim", symbol: "kV", siFactor: 1000 },
  { id: "akim-amper", category: "elektrik_akim", symbol: "A", siFactor: 1 },
  { id: "akim-miliamper", category: "elektrik_akim", symbol: "mA", siFactor: 0.001 },
  {
    id: "milivolt",
    category: "elektrik",
    symbol: "mV",
    siFactor: 0.001,
    tr: { name: "Milivolt", slug: "milivolt" },
    en: { name: "Millivolt", slug: "millivolt" },
    de: { name: "Millivolt", slug: "millivolt" },
    uz: { name: "Millivolt", slug: "millivolt" },
  },
  {
    id: "kiloamper",
    category: "elektrik",
    symbol: "kA",
    siFactor: 1000,
    tr: { name: "Kiloamper", slug: "kiloamper" },
    en: { name: "Kiloampere", slug: "kiloampere" },
    de: { name: "Kiloampere", slug: "kiloampere" },
    uz: { name: "Kiloamper", slug: "kiloamper" },
  },
  {
    id: "farad",
    category: "kapasitans",
    symbol: "F",
    siFactor: 1,
    tr: { name: "Farad", slug: "farad" },
    en: { name: "Farad", slug: "farad" },
    de: { name: "Farad", slug: "farad" },
    uz: { name: "Farad", slug: "farad" },
  },
  {
    id: "milifarad",
    category: "kapasitans",
    symbol: "mF",
    siFactor: 0.001,
    tr: { name: "Milifarad", slug: "milifarad" },
    en: { name: "Millifarad", slug: "millifarad" },
    de: { name: "Millifarad", slug: "millifarad" },
    uz: { name: "Millifarad", slug: "millifarad" },
  },
  {
    id: "mikrofarad",
    category: "kapasitans",
    symbol: "µF",
    siFactor: 0.000001,
    tr: { name: "Mikrofarad", slug: "mikrofarad" },
    en: { name: "Microfarad", slug: "microfarad" },
    de: { name: "Mikrofarad", slug: "mikrofarad" },
    uz: { name: "Mikrofarad", slug: "mikrofarad" },
  },
  {
    id: "nanofarad",
    category: "kapasitans",
    symbol: "nF",
    siFactor: 1e-9,
    tr: { name: "Nanofarad", slug: "nanofarad" },
    en: { name: "Nanofarad", slug: "nanofarad" },
    de: { name: "Nanofarad", slug: "nanofarad" },
    uz: { name: "Nanofarad", slug: "nanofarad" },
  },
  {
    id: "pikofarad",
    category: "kapasitans",
    symbol: "pF",
    siFactor: 1e-12,
    tr: { name: "Pikofarad", slug: "pikofarad" },
    en: { name: "Picofarad", slug: "picofarad" },
    de: { name: "Pikofarad", slug: "pikofarad" },
    uz: { name: "Pikofarad", slug: "pikofarad" },
  },
  {
    id: "henry",
    category: "enduktans",
    symbol: "H",
    siFactor: 1,
    tr: { name: "Henry", slug: "henry" },
    en: { name: "Henry", slug: "henry" },
    de: { name: "Henry", slug: "henry" },
    uz: { name: "Genri", slug: "genri" },
  },
  {
    id: "milihenry",
    category: "enduktans",
    symbol: "mH",
    siFactor: 0.001,
    tr: { name: "Milihenry", slug: "milihenry" },
    en: { name: "Millihenry", slug: "millihenry" },
    de: { name: "Millihenry", slug: "millihenry" },
    uz: { name: "Milligenri", slug: "milligenri" },
  },
  {
    id: "mikrohenry",
    category: "enduktans",
    symbol: "µH",
    siFactor: 0.000001,
    tr: { name: "Mikrohenry", slug: "mikrohenry" },
    en: { name: "Microhenry", slug: "microhenry" },
    de: { name: "Mikrohenry", slug: "mikrohenry" },
    uz: { name: "Mikrogenri", slug: "mikrogenri" },
  },
  {
    id: "coulomb",
    category: "elektrik_yuk",
    symbol: "C",
    siFactor: 1,
    tr: { name: "Coulomb", slug: "coulomb" },
    en: { name: "Coulomb", slug: "coulomb" },
    de: { name: "Coulomb", slug: "coulomb" },
    uz: { name: "Kulon", slug: "kulon" },
  },
  {
    id: "milicoulomb",
    category: "elektrik_yuk",
    symbol: "mC",
    siFactor: 0.001,
    tr: { name: "Milicoulomb", slug: "milicoulomb" },
    en: { name: "Millicoulomb", slug: "millicoulomb" },
    de: { name: "Millicoulomb", slug: "millicoulomb" },
    uz: { name: "Millikulon", slug: "millikulon" },
  },
  {
    id: "mikrocoulomb",
    category: "elektrik_yuk",
    symbol: "µC",
    siFactor: 0.000001,
    tr: { name: "Mikrocoulomb", slug: "mikrocoulomb" },
    en: { name: "Microcoulomb", slug: "microcoulomb" },
    de: { name: "Mikrocoulomb", slug: "mikrocoulomb" },
    uz: { name: "Mikrokulon", slug: "mikrokulon" },
  },
  {
    id: "nanocoulomb",
    category: "elektrik_yuk",
    symbol: "nC",
    siFactor: 1e-9,
    tr: { name: "Nanocoulomb", slug: "nanocoulomb" },
    en: { name: "Nanocoulomb", slug: "nanocoulomb" },
    de: { name: "Nanocoulomb", slug: "nanocoulomb" },
    uz: { name: "Nanokulon", slug: "nanokulon" },
  },
  {
    id: "a-m",
    category: "manyetik_alan",
    symbol: "A/m",
    siFactor: 1,
    tr: { name: "Amper/metre", slug: "amper-metre" },
    en: { name: "Ampere per Meter", slug: "ampere-per-meter" },
    de: { name: "Ampere pro Meter", slug: "ampere-pro-meter" },
  },
  { id: "ka-m", category: "manyetik_alan", symbol: "kA/m", siFactor: 1000, tr: { name: "Kiloamper/metre", slug: "kiloamper-metre" }, de: { name: "Kiloampere pro Meter", slug: "kiloampere-pro-meter" } },
  {
    id: "oersted",
    category: "manyetik_alan",
    symbol: "Oe",
    siFactor: 79.5775,
    tr: { name: "Oersted", slug: "oersted" },
    en: { name: "Oersted", slug: "oersted" },
    de: { name: "Oersted", slug: "oersted" },
    uz: { name: "Ersted", slug: "ersted" },
  },
  {
    id: "weber",
    category: "manyetik_aki",
    symbol: "Wb",
    siFactor: 1,
    tr: { name: "Weber", slug: "weber" },
    en: { name: "Weber", slug: "weber" },
    de: { name: "Weber", slug: "weber" },
    uz: { name: "Veber", slug: "veber" },
  },
  {
    id: "miliweber",
    category: "manyetik_aki",
    symbol: "mWb",
    siFactor: 0.001,
    tr: { name: "Miliweber", slug: "miliweber" },
    en: { name: "Milliweber", slug: "milliweber" },
    de: { name: "Milliweber", slug: "milliweber" },
    uz: { name: "Milliveber", slug: "milliveber" },
  },
  { id: "mikroweber", category: "manyetik_aki", symbol: "µWb", siFactor: 0.000001, tr: { name: "Mikroweber", slug: "mikroweber" }, de: { name: "Mikroweber", slug: "mikroweber" } },
  { id: "nanoweber", category: "manyetik_aki", symbol: "nWb", siFactor: 1e-9, tr: { name: "Nanoweber", slug: "nanoweber" }, de: { name: "Nanoweber", slug: "nanoweber" } },
  { id: "weber-alias", category: "manyetik_aki", symbol: "weber", siFactor: 1 },

  // ---- veri / digital storage ----
  {
    id: "bit",
    category: "veri",
    symbol: "bit",
    siFactor: 0.125,
    tr: { name: "Bit", slug: "bit" },
    en: { name: "Bit", slug: "bit" },
    de: { name: "Bit", slug: "bit" },
    uz: { name: "Bit", slug: "bit" },
  },
  {
    id: "bayt",
    category: "veri",
    symbol: "B",
    siFactor: 1,
    tr: { name: "Bayt", slug: "bayt" },
    en: { name: "Byte", slug: "byte" },
    de: { name: "Byte", slug: "byte" },
    uz: { name: "Bayt", slug: "bayt" },
  },
  {
    id: "kibibit",
    category: "veri",
    symbol: "Kibit",
    siFactor: 128,
    tr: { name: "Kibibit", slug: "kibibit" },
    en: { name: "Kibibit", slug: "kibibit" },
    de: { name: "Kibibit", slug: "kibibit" },
    uz: { name: "Kibibit", slug: "kibibit" },
  },
  {
    id: "mebibit",
    category: "veri",
    symbol: "Mibit",
    siFactor: 131072,
    tr: { name: "Mebibit", slug: "mebibit" },
    en: { name: "Mebibit", slug: "mebibit" },
    de: { name: "Mebibit", slug: "mebibit" },
    uz: { name: "Mebibit", slug: "mebibit" },
  },
  {
    id: "gibibit",
    category: "veri",
    symbol: "Gibit",
    siFactor: 134217728,
    tr: { name: "Gibibit", slug: "gibibit" },
    en: { name: "Gibibit", slug: "gibibit" },
    de: { name: "Gibibit", slug: "gibibit" },
    uz: { name: "Gibibit", slug: "gibibit" },
  },
  {
    id: "tebibit",
    category: "veri",
    symbol: "Tibit",
    siFactor: 137438953472,
    tr: { name: "Tebibit", slug: "tebibit" },
    en: { name: "Tebibit", slug: "tebibit" },
    de: { name: "Tebibit", slug: "tebibit" },
    uz: { name: "Tebibit", slug: "tebibit" },
  },
  {
    id: "kilobit",
    category: "veri",
    symbol: "kbit",
    siFactor: 125,
    tr: { name: "Kilobit", slug: "kilobit" },
    en: { name: "Kilobit", slug: "kilobit" },
    de: { name: "Kilobit", slug: "kilobit" },
    uz: { name: "Kilobit", slug: "kilobit" },
  },
  {
    id: "megabit",
    category: "veri",
    symbol: "Mbit",
    siFactor: 125000,
    tr: { name: "Megabit", slug: "megabit" },
    en: { name: "Megabit", slug: "megabit" },
    de: { name: "Megabit", slug: "megabit" },
    uz: { name: "Megabit", slug: "megabit" },
  },
  {
    id: "gigabit",
    category: "veri",
    symbol: "Gbit",
    siFactor: 125000000,
    tr: { name: "Gigabit", slug: "gigabit" },
    en: { name: "Gigabit", slug: "gigabit" },
    de: { name: "Gigabit", slug: "gigabit" },
    uz: { name: "Gigabit", slug: "gigabit" },
  },
  {
    id: "terabit",
    category: "veri",
    symbol: "Tbit",
    siFactor: 125000000000,
    tr: { name: "Terabit", slug: "terabit" },
    en: { name: "Terabit", slug: "terabit" },
    de: { name: "Terabit", slug: "terabit" },
    uz: { name: "Terabit", slug: "terabit" },
  },
  {
    id: "kilobayt",
    category: "veri",
    symbol: "KB",
    siFactor: 1000,
    tr: { name: "Kilobayt", slug: "kilobayt" },
    en: { name: "Kilobyte", slug: "kilobyte" },
    de: { name: "Kilobyte", slug: "kilobyte" },
    uz: { name: "Kilobayt", slug: "kilobayt" },
  },
  {
    id: "megabayt",
    category: "veri",
    symbol: "MB",
    siFactor: 1_000_000,
    tr: { name: "Megabayt", slug: "megabayt" },
    en: { name: "Megabyte", slug: "megabyte" },
    de: { name: "Megabyte", slug: "megabyte" },
    uz: { name: "Megabayt", slug: "megabayt" },
  },
  {
    id: "gigabayt",
    category: "veri",
    symbol: "GB",
    siFactor: 1_000_000_000,
    tr: { name: "Gigabayt", slug: "gigabayt" },
    en: { name: "Gigabyte", slug: "gigabyte" },
    de: { name: "Gigabyte", slug: "gigabyte" },
    uz: { name: "Gigabayt", slug: "gigabayt" },
  },
  {
    id: "terabayt",
    category: "veri",
    symbol: "TB",
    siFactor: 1_000_000_000_000,
    tr: { name: "Terabayt", slug: "terabayt" },
    en: { name: "Terabyte", slug: "terabyte" },
    de: { name: "Terabyte", slug: "terabyte" },
    uz: { name: "Terabayt", slug: "terabayt" },
  },
  {
    id: "petabayt",
    category: "veri",
    symbol: "PB",
    siFactor: 1_000_000_000_000_000,
    tr: { name: "Petabayt", slug: "petabayt" },
    en: { name: "Petabyte", slug: "petabyte" },
    de: { name: "Petabyte", slug: "petabyte" },
    uz: { name: "Petabayt", slug: "petabayt" },
  },
  {
    id: "kibibayt",
    category: "veri",
    symbol: "KiB",
    siFactor: 1024,
    tr: { name: "Kibibayt", slug: "kibibayt" },
    en: { name: "Kibibyte", slug: "kibibyte" },
    de: { name: "Kibibyte", slug: "kibibyte" },
    uz: { name: "Kibibayt", slug: "kibibayt" },
  },
  {
    id: "mebibayt",
    category: "veri",
    symbol: "MiB",
    siFactor: 1024 ** 2,
    tr: { name: "Mebibayt", slug: "mebibayt" },
    en: { name: "Mebibyte", slug: "mebibyte" },
    de: { name: "Mebibyte", slug: "mebibyte" },
    uz: { name: "Mebibayt", slug: "mebibayt" },
  },
  {
    id: "gibibayt",
    category: "veri",
    symbol: "GiB",
    siFactor: 1024 ** 3,
    tr: { name: "Gibibayt", slug: "gibibayt" },
    en: { name: "Gibibyte", slug: "gibibyte" },
    de: { name: "Gibibyte", slug: "gibibyte" },
    uz: { name: "Gibibayt", slug: "gibibayt" },
  },
  {
    id: "tebibayt",
    category: "veri",
    symbol: "TiB",
    siFactor: 1024 ** 4,
    tr: { name: "Tebibayt", slug: "tebibayt" },
    en: { name: "Tebibyte", slug: "tebibyte" },
    de: { name: "Tebibyte", slug: "tebibyte" },
    uz: { name: "Tebibayt", slug: "tebibayt" },
  },

  // ---- altin_ayar / gold karat purity ----
  {
    id: "ayar-24",
    category: "altin_ayar",
    symbol: "24K",
    siFactor: 1,
    tr: { name: "24 Ayar Altın", slug: "24-ayar-altin" },
    en: { name: "24K Gold", slug: "24k-gold" },
    de: { name: "24 Karat Gold", slug: "24-karat-gold" },
    uz: { name: "24 Karat Oltin", slug: "24-karat" },
  },
  {
    id: "ayar-22",
    category: "altin_ayar",
    symbol: "22K",
    siFactor: 22 / 24,
    tr: { name: "22 Ayar Altın", slug: "22-ayar-altin" },
    en: { name: "22K Gold", slug: "22k-gold" },
    de: { name: "22 Karat Gold", slug: "22-karat-gold" },
    uz: { name: "22 Karat Oltin", slug: "22-karat" },
  },
  {
    id: "ayar-18",
    category: "altin_ayar",
    symbol: "18K",
    siFactor: 18 / 24,
    tr: { name: "18 Ayar Altın", slug: "18-ayar-altin" },
    en: { name: "18K Gold", slug: "18k-gold" },
    de: { name: "18 Karat Gold", slug: "18-karat-gold" },
    uz: { name: "18 Karat Oltin", slug: "18-karat" },
  },
  {
    id: "ayar-14",
    category: "altin_ayar",
    symbol: "14K",
    siFactor: 14 / 24,
    tr: { name: "14 Ayar Altın", slug: "14-ayar-altin" },
    en: { name: "14K Gold", slug: "14k-gold" },
    de: { name: "14 Karat Gold", slug: "14-karat-gold" },
    uz: { name: "14 Karat Oltin", slug: "14-karat" },
  },

  // ---- gumus_ayar / gümüş ayar (saflık) ----
  {
    id: "gumus-999",
    category: "gumus_ayar",
    symbol: "999",
    siFactor: 0.999,
    tr: { name: "999 Ayar Gümüş", slug: "999-ayar-gumus" },
    en: { name: "Fine Silver (999)", slug: "fine-silver" },
    uz: { name: "999 Soflikdagi Kumush", slug: "999-soflikdagi-kumush" },
    de: { name: "Feinsilber (999)", slug: "feinsilber-999" },
  },
  {
    id: "gumus-925",
    category: "gumus_ayar",
    symbol: "925",
    siFactor: 0.925,
    tr: { name: "925 Ayar Gümüş", slug: "925-ayar-gumus" },
    en: { name: "Sterling Silver (925)", slug: "sterling-silver" },
    uz: { name: "925 Soflikdagi Kumush", slug: "925-soflikdagi-kumush" },
    de: { name: "Sterlingsilber (925)", slug: "sterlingsilber-925" },
  },
  {
    id: "gumus-900",
    category: "gumus_ayar",
    symbol: "900",
    siFactor: 0.9,
    tr: { name: "900 Ayar Gümüş", slug: "900-ayar-gumus" },
    en: { name: "Coin Silver (900)", slug: "coin-silver" },
    uz: { name: "900 Soflikdagi Kumush", slug: "900-soflikdagi-kumush" },
    de: { name: "Münzsilber (900)", slug: "muenzsilber-900" },
  },
  {
    id: "gumus-800",
    category: "gumus_ayar",
    symbol: "800",
    siFactor: 0.8,
    tr: { name: "800 Ayar Gümüş", slug: "800-ayar-gumus" },
    en: { name: "800 Silver", slug: "800-silver" },
    uz: { name: "800 Soflikdagi Kumush", slug: "800-soflikdagi-kumush" },
    de: { name: "800er Silber", slug: "silber-800" },
  },

  // ---- kan_sekeri / kan sekeri (glukoz) birim donusumu ----
  {
    id: "glukoz-mmol",
    category: "kan_sekeri",
    symbol: "mmol/L",
    siFactor: 1,
    tr: { name: "Milimol/Litre", slug: "milimol-litre" },
    en: { name: "Millimoles per Liter", slug: "millimoles-per-liter" },
    uz: { name: "Millimol/Litr", slug: "millimol-litr" },
    de: { name: "Millimol pro Liter", slug: "millimol-pro-liter" },
  },
  {
    id: "glukoz-mgdl",
    category: "kan_sekeri",
    symbol: "mg/dL",
    siFactor: 1 / 18.016,
    tr: { name: "Miligram/Desilitre", slug: "miligram-desilitre" },
    en: { name: "Milligrams per Deciliter", slug: "milligrams-per-deciliter" },
    uz: { name: "Milligramm/Detsilitr", slug: "milligramm-detsilitr" },
    de: { name: "Milligramm pro Deziliter", slug: "milligramm-pro-deziliter" },
  },

  // ---- vitamin_d / vitamin D birim donusumu ----
  {
    id: "vitamin-d-nmol",
    category: "vitamin_d",
    symbol: "nmol/L",
    siFactor: 1,
    tr: { name: "Nanomol/Litre", slug: "nanomol-litre" },
    en: { name: "Nanomoles per Liter", slug: "nanomoles-per-liter" },
    uz: { name: "Nanomol/Litr", slug: "nanomol-litr" },
    de: { name: "Nanomol pro Liter", slug: "nanomol-pro-liter" },
  },
  {
    id: "vitamin-d-ngml",
    category: "vitamin_d",
    symbol: "ng/mL",
    siFactor: 2.496,
    tr: { name: "Nanogram/Mililitre", slug: "nanogram-mililitre" },
    en: { name: "Nanograms per Milliliter", slug: "nanograms-per-milliliter" },
    uz: { name: "Nanogramm/Millilitr", slug: "nanogramm-millilitr" },
    de: { name: "Nanogramm pro Milliliter", slug: "nanogramm-pro-milliliter" },
  },
];

export function findUnit(category: string, symbol: string) {
  return unitRegistry.find(
    (unit) => unit.category === category && unit.symbol === symbol
  );
}

export function getUnitsForCategory(category: string) {
  return unitRegistry.filter((unit) => unit.category === category);
}

export function getUnitCategories() {
  return Array.from(new Set(unitRegistry.map((unit) => unit.category)));
}
