import type { Metadata } from "next";
import Link from "next/link";
import EnglishFourierNumberCalculator from "../../../../components/EnglishFourierNumberCalculator";
import { buildFaqSchema, type FaqItem } from "../../../../converter/faqSchema";
import { buildSiteUrl } from "../../../../siteConfig";

const pagePath = "/en/engineering-calculators/dimensionless-numbers/fourier-number-calculator";
const faqItems: FaqItem[] = [
  { question: "What does Fourier number represent?", answer: "It is the ratio of heat diffusion time scale to the time associated with a selected length scale: Fo = αt/L²." },
  { question: "Is a larger Fourier number always better?", answer: "No. It only indicates that more diffusion time has elapsed relative to the selected length. Whether that is desirable depends on the heating or cooling problem." },
  { question: "How does Fourier number relate to Biot number?", answer: "Biot number screens internal versus surface resistance; Fourier number gives the dimensionless time used in transient-conduction solutions." },
];

export const metadata: Metadata = { title: "Fourier Number Calculator (Fo = αt / L²)", description: "Calculate the dimensionless Fourier number from thermal diffusivity, elapsed time and characteristic length with SI and Imperial units.", alternates: { canonical: pagePath, languages: { en: pagePath } }, openGraph: { title: "Fourier Number Calculator", description: "Calculate dimensionless time for transient heat-transfer analysis.", url: buildSiteUrl(pagePath), siteName: "BirimCeviri.app", locale: "en_US", type: "article" } };
function serializeJsonLd(data: object) { return JSON.stringify(data).replace(/</g, "\\u003c"); }

export default function EnglishFourierNumberPage() {
  const breadcrumbSchema = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: buildSiteUrl("/en") }, { "@type": "ListItem", position: 2, name: "Dimensionless Numbers", item: buildSiteUrl("/en/engineering-calculators/dimensionless-numbers") }, { "@type": "ListItem", position: 3, name: "Fourier Number Calculator", item: buildSiteUrl(pagePath) }] };
  return <main className="all-conversions-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(breadcrumbSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(buildFaqSchema(faqItems)) }} /><div className="all-conversions-shell"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/en">Home</Link><span aria-hidden="true">›</span><Link href="/en/engineering-calculators/dimensionless-numbers">Dimensionless Numbers</Link><span aria-hidden="true">›</span><span>Fourier Number Calculator</span></nav><header className="all-conversions-header"><h1>Fourier Number Calculator</h1><p>Calculate the dimensionless time used in transient heat-transfer analysis from thermal diffusivity, elapsed time and characteristic length.</p></header><EnglishFourierNumberCalculator /><article className="category-article-content"><h2>Method and variables</h2><p><strong>Formula:</strong> Fo = αt/L².</p><ul><li><strong>α</strong> — thermal diffusivity</li><li><strong>t</strong> — elapsed time</li><li><strong>L</strong> — characteristic length used by the transient solution</li></ul><h2>Worked example</h2><p>For α = 1.2 × 10⁻⁵ m²/s, t = 60 s and L = 0.01 m, Fo = (1.2 × 10⁻⁵ × 60) / 0.01² = 7.2.</p><h2>How it connects to other tools</h2><p>Use Biot number to screen the resistance model, then Fourier number to place the event in dimensionless time. The final temperature prediction still needs the right geometry and boundary condition.</p><h2>Important limits</h2><p>Fourier number is not a temperature calculation. It does not account for phase change, heat generation, radiation, multilayer construction, property variation or nonuniform boundary conditions.</p><h2>References</h2><ul><li><a href="https://openstax.org/books/college-physics-2e/pages/14-6-conduction" target="_blank" rel="noreferrer">OpenStax: Conduction</a></li><li><a href="https://www.nist.gov/pml/special-publication-811" target="_blank" rel="noreferrer">NIST Guide for the Use of the International System of Units</a></li></ul><h2>Related tools</h2><p><Link href="/en/engineering-calculators/dimensionless-numbers/biot-number-calculator">Biot Number Calculator</Link> · <Link href="/en/calculators/heat-conduction">Heat Conduction Calculator</Link> · <Link href="/en/engineering-calculators/dimensionless-numbers">Dimensionless Numbers Calculators</Link></p></article></div></main>;
}
