import type { Metadata } from "next";
import Link from "next/link";
import EnglishConvectiveHeatTransferCalculator from "../../../../components/EnglishConvectiveHeatTransferCalculator";
import { buildSiteUrl } from "../../../../siteConfig";

const pagePath = "/en/engineering-calculators/heat-transfer/convective-heat-transfer-calculator";

export const metadata: Metadata = { title: "Convective Heat Transfer Calculator (h × A × ΔT)", description: "Calculate heat-transfer rate from a stated convection coefficient, surface area and surface-to-fluid temperature difference.", alternates: { canonical: pagePath, languages: { en: pagePath } }, openGraph: { title: "Convective Heat Transfer Calculator", description: "Calculate Q = h A ΔT from a stated coefficient, area and temperature difference.", url: buildSiteUrl(pagePath), siteName: "BirimCeviri.app", locale: "en_US", type: "article" } };

export default function ConvectiveHeatTransferCalculatorPage() {
  return <main className="all-conversions-page"><div className="all-conversions-shell"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/en">Home</Link><span aria-hidden="true">›</span><Link href="/en/engineering-calculators">Engineering Calculators</Link><span aria-hidden="true">›</span><Link href="/en/engineering-calculators/heat-transfer">Heat Transfer</Link><span aria-hidden="true">›</span><span>Convective Heat Transfer Calculator</span></nav><header className="all-conversions-header"><h1>Convective Heat Transfer Calculator</h1><p>Calculate a first-pass convection heat-transfer rate from a stated h-value, area and driving temperature difference.</p></header><EnglishConvectiveHeatTransferCalculator /><article className="category-article-content"><h2>Method</h2><p>For a stated convection coefficient, Q̇ = h × A × ΔT. The coefficient h must represent the applicable geometry, fluid properties, flow regime and temperature range.</p><h2>Worked example</h2><p>Air with h = 25 W/(m²·K) across a 1 m² surface that is 30 K warmer than the air transfers 25 × 1 × 30 = 750 W under this simple model.</p><h2>Important limits</h2><p>The calculator does not estimate h, include radiation or conduction, or model boundary-layer development. For heat exchangers with changing stream temperatures, use a suitable LMTD or effectiveness-NTU design method.</p><h2>Related tools</h2><p><Link href="/en/engineering-calculators/dimensionless-numbers/nusselt-number-calculator">Nusselt Number Calculator</Link> · <Link href="/en/engineering-calculators/heat-transfer/lmtd-heat-exchanger-calculator">LMTD Heat Exchanger Calculator</Link> · <Link href="/en/engineering-calculators/heat-transfer">Heat Transfer Calculators</Link></p></article></div></main>;
}
