import type { Metadata } from "next";
import Link from "next/link";
import EnglishThinWallCylinderCalculator from "../../../../components/EnglishThinWallCylinderCalculator";
import { buildSiteUrl } from "../../../../siteConfig";

const pagePath = "/en/engineering-calculators/mechanics-materials/thin-wall-cylinder-stress-calculator";
export const metadata: Metadata = { title: "Thin-Wall Cylinder Stress Calculator", description: "Calculate ideal hoop and longitudinal stress in a thin-walled cylindrical pressure boundary from internal pressure, diameter and wall thickness.", alternates: { canonical: pagePath, languages: { en: pagePath } }, openGraph: { title: "Thin-Wall Cylinder Stress Calculator", description: "Calculate ideal thin-wall hoop and longitudinal stress for a stated cylindrical pressure boundary.", url: buildSiteUrl(pagePath), siteName: "BirimCeviri.app", locale: "en_US", type: "article" } };

export default function ThinWallCylinderCalculatorPage() {
  return <main className="all-conversions-page"><div className="all-conversions-shell"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/en">Home</Link><span aria-hidden="true">›</span><Link href="/en/engineering-calculators">Engineering Calculators</Link><span aria-hidden="true">›</span><Link href="/en/engineering-calculators/mechanics-materials">Mechanics &amp; Materials</Link><span aria-hidden="true">›</span><span>Thin-Wall Cylinder Stress Calculator</span></nav><header className="all-conversions-header"><h1>Thin-Wall Cylinder Stress Calculator</h1><p>Estimate ideal hoop and longitudinal stress for a thin-walled cylinder under internal pressure.</p></header><EnglishThinWallCylinderCalculator /><article className="category-article-content"><h2>Method</h2><p>For an ideal thin-walled closed cylinder, hoop stress is σ<sub>h</sub> = pD/(2t), while longitudinal stress is σ<sub>l</sub> = pD/(4t).</p><h2>Worked example</h2><p>A cylinder with 1 MPa internal pressure, 500 mm diameter and 10 mm wall thickness has 25 MPa hoop stress and 12.5 MPa longitudinal stress under this idealized model.</p><h2>Important limits</h2><p>This is only a preliminary thin-wall screen, not a vessel, pipe or tank design. Use the applicable pressure-equipment code and account for material, joints, corrosion, temperature, fatigue, openings, heads and test conditions.</p><h2>References</h2><ul><li><a href="https://ntrs.nasa.gov/api/citations/19750002275/downloads/19750002275.pdf" target="_blank" rel="noreferrer">NASA: hoop and axial stresses in thin-walled cylinders</a></li><li><a href="https://www.nist.gov/pml/special-publication-811" target="_blank" rel="noreferrer">NIST Guide for the Use of the International System of Units</a></li></ul><h2>Related tools</h2><p><Link href="/en/engineering-calculators/mechanics-materials/stress-strain-calculator">Stress &amp; Strain Calculator</Link> · <Link href="/en/engineering-calculators/mechanics-materials/section-properties-calculator">Section Properties Calculator</Link> · <Link href="/en/engineering-calculators/mechanics-materials">Mechanics &amp; Materials Calculators</Link></p></article></div></main>;
}
