import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { DilutionCalculator, MolarityCalculator, PhCalculator } from "../../../components/EnglishChemistryCalculator";
import { CellPotentialCalculator, EquilibriumConstantCalculator, HalfLifeCalculator, MolalityCalculator, MoleCalculator, PercentYieldCalculator, PpmCalculator, StoichiometryCalculator, TitrationCalculator } from "../../../components/EnglishChemistryExpandedCalculators";
import StaticPageLayout from "../../../components/StaticPageLayout";
import { SITE_NAME, buildSiteUrl } from "../../../siteConfig";
import { englishChemistryTools } from "../../../i18n/englishChemistryToolCatalog";

const tools = {
  molarity: { title: "Molarity Calculator", description: "Calculate molarity, amount of solute or solution volume with M = n / V.", component: MolarityCalculator, formula: "M = n / V", explanation: "Molarity is the amount of solute divided by the volume of the final solution. This calculator uses litres for volume and mol for amount of solute.", example: "For 0.50 mol of solute in 0.50 L of solution, M = 0.50 / 0.50 = 1.00 mol/L.", source: { href: "https://goldbook.iupac.org/terms/view/A00295", label: "IUPAC: amount concentration" } },
  ph: { title: "pH Calculator", description: "Calculate pH, pOH, hydrogen-ion concentration or hydroxide-ion concentration at 25 °C.", component: PhCalculator, formula: "pH = −log₁₀[H⁺]; pH + pOH = 14", explanation: "The tool derives the other displayed values from one entered value using the common aqueous 25 °C relationship. In rigorous chemistry, pH is defined using hydrogen-ion activity rather than concentration.", example: "For [H⁺] = 1 × 10⁻⁷ mol/L, pH = 7.00 in this idealised calculation.", source: { href: "https://goldbook.iupac.org/terms/view/P04524", label: "IUPAC: pH" } },
  dilution: { title: "Dilution Calculator", description: "Solve C₁V₁ = C₂V₂ to calculate a stock concentration, stock volume, target concentration or final volume.", component: DilutionCalculator, formula: "C₁V₁ = C₂V₂", explanation: "For a simple dilution, the amount of solute is unchanged while solvent is added. Concentration and volume units must each be consistent across both sides of the equation.", example: "To prepare 400 mL at 0.50 from a 2.00 stock, V₁ = (0.50 × 400) / 2.00 = 100 mL.", source: { href: "https://openstax.org/books/chemistry-2e/pages/3-3-molarity", label: "OpenStax: Molarity and dilution" } },
  mole: { title: "Mole Calculator", description: "Calculate moles, mass and particle count from a molar mass using n = m / M.", component: MoleCalculator, formula: "n = m / M; particles = n × Nₐ", explanation: "A mole links an amount of substance to its mass through molar mass. The particle count uses the exact Avogadro constant, 6.02214076 × 10²³ mol⁻¹.", example: "For 18.015 g of water with a molar mass of 18.015 g/mol, n = 1.000 mol.", source: { href: "https://goldbook.iupac.org/terms/view/A04300", label: "IUPAC: amount of substance" } },
  molality: { title: "Molality Calculator", description: "Calculate molality, solute amount or solvent mass with m = n / kg solvent.", component: MolalityCalculator, formula: "m = n / kg solvent", explanation: "Molality is based on the mass of solvent rather than the volume of solution, so it is useful when solution volume changes with temperature.", example: "0.50 mol of solute dissolved in 0.50 kg of solvent gives a molality of 1.00 mol/kg.", source: { href: "https://goldbook.iupac.org/terms/view/M03975", label: "IUPAC: molality" } },
  ppm: { title: "PPM Calculator", description: "Calculate mass-based concentration in parts per million, solute mass or solvent mass.", component: PpmCalculator, formula: "ppm = (solute mass / solution mass) × 10⁶", explanation: "This calculator treats ppm as a mass fraction scaled by one million. Both mass entries must use the same unit.", example: "1 g of solute in 999 g of solvent gives a 1,000 ppm solution by mass.", source: { href: "https://goldbook.iupac.org/terms/view/P04772", label: "IUPAC: parts per million" } },
  stoichiometry: { title: "Stoichiometry Calculator", description: "Use coefficients from a balanced equation to calculate a theoretical target amount and mass.", component: StoichiometryCalculator, formula: "n(target) = n(known) × coefficient(target) / coefficient(known)", explanation: "Stoichiometric coefficients give the mole ratio in a balanced chemical equation. This tool does not identify a limiting reagent or account for yield.", example: "In 2H₂ + O₂ → 2H₂O, 2.00 mol H₂ corresponds to 2.00 mol H₂O.", source: { href: "https://openstax.org/books/chemistry-2e/pages/4-3-reaction-stoichiometry", label: "OpenStax: Reaction stoichiometry" } },
  "percent-yield": { title: "Percent Yield Calculator", description: "Calculate percent yield, actual yield or theoretical yield for a reaction.", component: PercentYieldCalculator, formula: "percent yield = (actual yield / theoretical yield) × 100", explanation: "The result compares an observed product quantity with the theoretical product quantity calculated from stoichiometry. Use the same unit for both yields.", example: "An actual yield of 8 g from a theoretical yield of 10 g is 80%.", source: { href: "https://openstax.org/books/chemistry-2e/pages/4-3-reaction-stoichiometry", label: "OpenStax: Reaction stoichiometry" } },
  titration: { title: "Titration Calculator", description: "Solve a simple acid-base equivalence relationship for one concentration or volume.", component: TitrationCalculator, formula: "CₐVₐ × acid equivalents = CᵦVᵦ × base equivalents", explanation: "At the equivalence point, acid and base reacting equivalents are equal. The equivalents fields handle acids or bases that donate or accept more than one proton per formula unit.", example: "25.0 mL of 0.100 M monoprotic acid requires 25.0 mL of 0.100 M monobasic base at equivalence.", source: { href: "https://openstax.org/books/chemistry-2e/pages/14-7-acid-base-titrations", label: "OpenStax: Acid-base titrations" } },
  "half-life": { title: "Half-Life Calculator", description: "Calculate remaining amount, initial amount, elapsed time or half-life for exponential decay.", component: HalfLifeCalculator, formula: "N = N₀ × (1/2)^(t/t½)", explanation: "This idealized model applies a constant half-life and is intended for learning and calculation checks. It does not assess radiation exposure, isotope handling or safety.", example: "After two half-lives, 25% of the initial amount remains.", source: { href: "https://openstax.org/books/chemistry-2e/pages/21-2-nuclear-equations", label: "OpenStax: Nuclear chemistry" } },
  kc: { title: "Equilibrium Constant (Kc) Calculator", description: "Calculate Kc from equilibrium concentrations and stoichiometric coefficients.", component: EquilibriumConstantCalculator, formula: "Kc = [products]^coefficients / [reactants]^coefficients", explanation: "Enter equilibrium concentrations for the species included in the expression. The generic four-term form represents aA + bB ⇌ cC + dD.", example: "For A + B ⇌ C with [A] = 1, [B] = 1 and [C] = 2, Kc = 2.", source: { href: "https://openstax.org/books/chemistry-2e/pages/13-2-equilibrium-constants", label: "OpenStax: Equilibrium constants" } },
  "cell-potential": { title: "Cell Potential Calculator", description: "Calculate standard cell potential from cathode and anode standard reduction potentials.", component: CellPotentialCalculator, formula: "E°cell = E°cathode − E°anode", explanation: "The calculator subtracts the anode reduction potential from the cathode reduction potential. A positive standard cell potential is spontaneous as written under standard conditions.", example: "Cu²⁺/Cu at +0.34 V and Zn²⁺/Zn at −0.76 V gives E°cell = +1.10 V.", source: { href: "https://openstax.org/books/chemistry-2e/pages/17-2-galvanic-cells", label: "OpenStax: Galvanic cells" } },
} as const;

type ToolSlug = keyof typeof tools;
type PageProps = { params: Promise<{ tool: string }> };

export function generateStaticParams() { return englishChemistryTools.map(({ slug }) => ({ tool: slug })); }
function getTool(tool: string) { return tools[tool as ToolSlug]; }
export const dynamicParams = false;

export async function generateMetadata({ params }: PageProps): Promise<Metadata> { const { tool: slug } = await params; const tool = getTool(slug); if (!tool) return {}; const path = `/en/chemistry-calculators/${slug}`; return { title: `${tool.title} | ${SITE_NAME}`, description: tool.description, alternates: { canonical: path, languages: { en: path } }, openGraph: { title: tool.title, description: tool.description, url: buildSiteUrl(path), siteName: SITE_NAME, locale: "en_US", type: "website" } }; }
export default async function ChemistryToolPage({ params }: PageProps) {
  const { tool: slug } = await params;
  const tool = getTool(slug);
  const quality = englishChemistryTools.find((item) => item.slug === slug);
  if (!tool || !quality) notFound();
  const Tool = tool.component;
  return <StaticPageLayout locale="en" breadcrumbAriaLabel="Breadcrumb" breadcrumbs={[{ href: "/en", label: "Home" }, { href: "/en/chemistry-calculators", label: "Chemistry Calculators" }, { label: tool.title }]} title={tool.title} description={tool.description} sections={[
    { heading: "Calculator", content: <Tool /> },
    { heading: "Formula and assumptions", content: <><p><strong>{tool.formula}</strong></p><p>{tool.explanation}</p><p><strong>Assumption:</strong> {quality.assumptions}</p></> },
    { heading: "Variables and units", content: <ul className="related-conversion-list">{quality.variables.map((variable) => <li key={variable.symbol}><strong>{variable.symbol}</strong> — {variable.label}{variable.unit ? ` (${variable.unit})` : ""}</li>)}</ul> },
    { heading: "Worked example", content: <p>{tool.example}</p> },
    { heading: "Important limits", content: <p>{quality.limitations}</p> },
    { heading: "Reference and related tools", content: <p><a href={tool.source.href}>{tool.source.label}</a>. Return to <Link href="/en/chemistry-calculators">Chemistry Calculators</Link> for the other tools in this group.</p> },
  ]} />;
}
