import type { Metadata } from "next";
import Link from "next/link";
import EnglishFroudeNumberCalculator from "../../../../components/EnglishFroudeNumberCalculator";
import { buildFaqSchema, type FaqItem } from "../../../../converter/faqSchema";
import { buildSiteUrl } from "../../../../siteConfig";

const pagePath = "/en/engineering-calculators/dimensionless-numbers/froude-number-calculator";
const faqItems: FaqItem[] = [
  { question: "What does Froude number indicate in open-channel flow?", answer: "It compares mean flow speed with shallow-water wave speed. In the usual open-channel interpretation, Fr below 1 is subcritical, Fr equal to 1 is critical and Fr above 1 is supercritical." },
  { question: "What depth should I enter?", answer: "Use hydraulic depth, cross-sectional flow area divided by free-surface top width. For a wide rectangular channel, it is approximately the water depth." },
  { question: "Can I use this for a pressurized pipe?", answer: "Not for the usual open-channel regime interpretation. A full pipe has no free surface, so use pipe-flow, Reynolds-number and pressure-loss tools instead." },
];

export const metadata: Metadata = { title: "Froude Number Calculator (Fr = V / √gD)", description: "Calculate Froude number, mean velocity or hydraulic depth for a clearly scoped open-channel and shallow-water flow screening calculation.", alternates: { canonical: pagePath, languages: { en: pagePath } }, openGraph: { title: "Froude Number Calculator", description: "Screen open-channel flow as subcritical, critical or supercritical from velocity and hydraulic depth.", url: buildSiteUrl(pagePath), siteName: "BirimCeviri.app", locale: "en_US", type: "article" } };
function serializeJsonLd(data: object) { return JSON.stringify(data).replace(/</g, "\\u003c"); }

export default function EnglishFroudeNumberPage() {
  const breadcrumbSchema = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: buildSiteUrl("/en") }, { "@type": "ListItem", position: 2, name: "Dimensionless Numbers", item: buildSiteUrl("/en/engineering-calculators/dimensionless-numbers") }, { "@type": "ListItem", position: 3, name: "Froude Number Calculator", item: buildSiteUrl(pagePath) }] };
  return <main className="all-conversions-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(breadcrumbSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(buildFaqSchema(faqItems)) }} /><div className="all-conversions-shell"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/en">Home</Link><span aria-hidden="true">›</span><Link href="/en/engineering-calculators/dimensionless-numbers">Dimensionless Numbers</Link><span aria-hidden="true">›</span><span>Froude Number Calculator</span></nav><header className="all-conversions-header"><h1>Froude Number Calculator</h1><p>Calculate Froude number, mean velocity or hydraulic depth for shallow-water and open-channel flow screening.</p></header><EnglishFroudeNumberCalculator /><article className="category-article-content"><h2>Method and variables</h2><p>This calculator uses Fr = V/√(gD), where <strong>V</strong> is mean flow velocity, <strong>g</strong> is gravitational acceleration and <strong>D</strong> is hydraulic depth. Hydraulic depth is the flow area divided by the free-surface top width.</p><h2>Worked example</h2><p>With mean velocity V = 2 m/s, hydraulic depth D = 1 m and g = 9.80665 m/s², Fr = 2/√(9.80665 × 1) ≈ 0.639. That is subcritical open-channel flow.</p><h2>How to read the result</h2><p>For the standard open-channel interpretation, Fr &lt; 1 is subcritical (tranquil), Fr = 1 is critical and Fr &gt; 1 is supercritical (rapid). This compares mean flow with shallow-water wave celerity; it is not a turbulence classification.</p><h2>Important limits</h2><p>Use the hydraulic depth appropriate to the cross section and the same representative reach for velocity and depth. This simple screening form does not capture nonuniform velocity, rapidly varied flow, hydraulic jumps, nonhydrostatic effects, sediment transport, air entrainment or a complex channel/structure geometry. Do not apply its open-channel regime label to a fully pressurized pipe.</p><h2>References</h2><ul><li><a href="https://www.fhwa.dot.gov/engineering/hydraulics/pubs/hif19061.pdf" target="_blank" rel="noreferrer">U.S. FHWA: Froude number and open-channel flow regimes</a></li><li><a href="https://www.publications.usace.army.mil/portals/76/publications/engineermanuals/em_1110-2-1416.pdf" target="_blank" rel="noreferrer">U.S. Army Corps of Engineers: hydraulic depth and Froude-number interpretation</a></li></ul><h2>Related tools</h2><p><Link href="/en/calculators/reynolds-number">Reynolds Number Calculator</Link> · <Link href="/en/engineering-calculators/fluids-piping/pipe-flow-calculator">Pipe Flow Rate &amp; Velocity Calculator</Link> · <Link href="/en/engineering-calculators/dimensionless-numbers">Dimensionless Numbers Calculators</Link></p></article></div></main>;
}
