import type { Metadata } from "next";
import Link from "next/link";
import EnglishGrashofNumberCalculator from "../../../../components/EnglishGrashofNumberCalculator";
import { buildFaqSchema, type FaqItem } from "../../../../converter/faqSchema";
import { buildSiteUrl } from "../../../../siteConfig";

const pagePath = "/en/engineering-calculators/dimensionless-numbers/grashof-number-calculator";
const faqItems: FaqItem[] = [
  { question: "What does Grashof number compare?", answer: "Grashof number compares buoyancy effects created by a temperature-driven density difference with viscous effects in a natural-convection problem." },
  { question: "Why use the absolute temperature difference?", answer: "This calculator reports the magnitude used in the conventional dimensionless group. Whether a surface is warmer or cooler than the surrounding fluid still matters when selecting a geometry-specific natural-convection correlation." },
  { question: "Can Grashof number give me a heat-transfer coefficient?", answer: "No. It is an input to a suitable natural-convection correlation, usually together with Prandtl or Rayleigh number, geometry and boundary conditions." },
];

export const metadata: Metadata = { title: "Grashof Number Calculator (Gr = gβΔTL³ / ν²)", description: "Calculate Grashof number for a scoped natural-convection screening problem from thermal expansion, temperature difference, length and kinematic viscosity.", alternates: { canonical: pagePath, languages: { en: pagePath } }, openGraph: { title: "Grashof Number Calculator", description: "Screen buoyancy relative to viscosity in a natural-convection problem.", url: buildSiteUrl(pagePath), siteName: "BirimCeviri.app", locale: "en_US", type: "article" } };
function serializeJsonLd(data: object) { return JSON.stringify(data).replace(/</g, "\\u003c"); }

export default function EnglishGrashofNumberPage() {
  const breadcrumbSchema = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: buildSiteUrl("/en") }, { "@type": "ListItem", position: 2, name: "Dimensionless Numbers", item: buildSiteUrl("/en/engineering-calculators/dimensionless-numbers") }, { "@type": "ListItem", position: 3, name: "Grashof Number Calculator", item: buildSiteUrl(pagePath) }] };
  return <main className="all-conversions-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(breadcrumbSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(buildFaqSchema(faqItems)) }} /><div className="all-conversions-shell"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/en">Home</Link><span aria-hidden="true">›</span><Link href="/en/engineering-calculators/dimensionless-numbers">Dimensionless Numbers</Link><span aria-hidden="true">›</span><span>Grashof Number Calculator</span></nav><header className="all-conversions-header"><h1>Grashof Number Calculator</h1><p>Calculate the buoyancy-to-viscosity ratio used to screen a natural-convection heat-transfer problem.</p></header><EnglishGrashofNumberCalculator /><article className="category-article-content"><h2>Method and variables</h2><p>This page calculates Gr = gβ|ΔT|L<sup>3</sup>/ν<sup>2</sup>. <strong>β</strong> is volumetric thermal expansion coefficient, <strong>ΔT</strong> is surface-to-fluid temperature difference, <strong>L</strong> is the characteristic length and <strong>ν</strong> is kinematic viscosity.</p><h2>Worked example</h2><p>For air approximated at a 303.15 K film temperature, β ≈ 1/303.15 K<sup>−1</sup>. With |ΔT| = 20 K, L = 0.5 m, ν = 1.6 × 10<sup>−5</sup> m²/s and standard gravity, Gr is about 3.2 × 10<sup>9</sup>.</p><h2>Important limits</h2><p>For fluid properties, use a consistent reference state—often a film temperature for external natural convection. The ideal-gas β = 1/T option is only an approximation. Gr alone cannot select a heat-transfer correlation or account for orientation, enclosure effects, radiation, turbulence, phase change, property variation or forced flow.</p><h2>Reference</h2><ul><li><a href="https://ntrs.nasa.gov/api/citations/19950006290/downloads/19950006290.pdf" target="_blank" rel="noreferrer">NASA Technical Report: Grashof, Prandtl and Rayleigh definitions for natural convection</a></li><li><a href="https://simulationresearch.lbl.gov/modelica/releases/v10.0.0/help/Buildings_Fluid_HeatExchangers_BaseClasses.html" target="_blank" rel="noreferrer">Lawrence Berkeley National Laboratory: natural-convection dimensionless groups</a></li></ul><h2>Related tools</h2><p><Link href="/en/engineering-calculators/dimensionless-numbers/prandtl-number-calculator">Prandtl Number Calculator</Link> · <Link href="/en/engineering-calculators/dimensionless-numbers">Dimensionless Numbers Calculators</Link></p></article></div></main>;
}
