// Pomodoro ve aralikli antrenman zamanlayicilarinin metinleri.
export type FocusLang = "tr" | "en" | "de" | "sv" | "no" | "da";

export const pomodoroCopy = {
  de: {
    modes: { work: "Fokus", short: "Kurze Pause", long: "Lange Pause" },
    start: "Start",
    pause: "Pause",
    resume: "Weiter",
    skip: "Überspringen",
    reset: "Zurücksetzen",
    task: "Woran arbeiten Sie gerade?",
    taskPlaceholder: "z. B. Hausaufgaben Mathe, Bericht schreiben",
    session: "Runde",
    today: "Heute",
    pomodoros: "Pomodoros",
    focusMinutes: "Min. Fokus",
    settings: "Einstellungen",
    workMin: "Fokus (Min.)",
    shortMin: "Kurze Pause (Min.)",
    longMin: "Lange Pause (Min.)",
    longEvery: "Lange Pause alle",
    autoStart: "Nächste Runde automatisch starten",
    notify: "Benachrichtigungen senden",
    notifyDenied: "Benachrichtigungen wurden blockiert; der Signalton ertönt trotzdem.",
    history: "Heute erledigt",
    noHistory: "Noch kein Pomodoro abgeschlossen.",
    clearHistory: "Heute löschen",
    done: { work: "Fokuszeit vorbei – Zeit für eine Pause!", short: "Pause vorbei – zurück zum Fokus!", long: "Lange Pause vorbei – bereit für die nächste Runde?" },
    keyboard: "Leertaste: Start / Pause",
  },
  tr: {
    modes: { work: "Odak", short: "Kısa mola", long: "Uzun mola" },
    start: "Başlat",
    pause: "Duraklat",
    resume: "Devam",
    skip: "Atla",
    reset: "Sıfırla",
    task: "Ne üzerinde çalışıyorsun?",
    taskPlaceholder: "ör. Matematik ödevi, rapor yazımı",
    session: "Tur",
    today: "Bugün",
    pomodoros: "pomodoro",
    focusMinutes: "dk odak",
    settings: "Ayarlar",
    workMin: "Odak (dk)",
    shortMin: "Kısa mola (dk)",
    longMin: "Uzun mola (dk)",
    longEvery: "Uzun mola her",
    autoStart: "Sonraki turu otomatik başlat",
    notify: "Bildirim gönder",
    notifyDenied: "Bildirim izni verilmedi; sesli uyarı çalmaya devam eder.",
    history: "Bugün tamamlananlar",
    noHistory: "Henüz tamamlanan pomodoro yok.",
    clearHistory: "Günü temizle",
    done: { work: "Odak süresi bitti — mola zamanı!", short: "Mola bitti — odaklanma zamanı!", long: "Uzun mola bitti — yeni tura hazır mısın?" },
    keyboard: "Boşluk tuşu: başlat / duraklat",
  },
  en: {
    modes: { work: "Focus", short: "Short break", long: "Long break" },
    start: "Start",
    pause: "Pause",
    resume: "Resume",
    skip: "Skip",
    reset: "Reset",
    task: "What are you working on?",
    taskPlaceholder: "e.g. Maths homework, writing a report",
    session: "Session",
    today: "Today",
    pomodoros: "pomodoros",
    focusMinutes: "min focused",
    settings: "Settings",
    workMin: "Focus (min)",
    shortMin: "Short break (min)",
    longMin: "Long break (min)",
    longEvery: "Long break every",
    autoStart: "Start the next session automatically",
    notify: "Send notifications",
    notifyDenied: "Notifications were blocked; the sound alert still plays.",
    history: "Completed today",
    noHistory: "No pomodoros completed yet.",
    clearHistory: "Clear today",
    done: { work: "Focus time's up — take a break!", short: "Break's over — back to focus!", long: "Long break's over — ready for a new round?" },
    keyboard: "Space bar: start / pause",
  },
  sv: {
    modes: { work: "Fokus", short: "Kort paus", long: "Lång paus" },
    start: "Starta",
    pause: "Pausa",
    resume: "Fortsätt",
    skip: "Hoppa över",
    reset: "Återställ",
    task: "Vad arbetar du med?",
    taskPlaceholder: "t.ex. matteläxa, skriva en rapport",
    session: "Pass",
    today: "Idag",
    pomodoros: "pomodoros",
    focusMinutes: "min fokus",
    settings: "Inställningar",
    workMin: "Fokus (min)",
    shortMin: "Kort paus (min)",
    longMin: "Lång paus (min)",
    longEvery: "Lång paus var",
    autoStart: "Starta nästa pass automatiskt",
    notify: "Skicka aviseringar",
    notifyDenied: "Aviseringar blockerades; ljudsignalen spelas ändå.",
    history: "Klart idag",
    noHistory: "Inga avslutade pomodoros ännu.",
    clearHistory: "Rensa idag",
    done: { work: "Fokustiden är slut – dags för paus!", short: "Pausen är slut – tillbaka till fokus!", long: "Den långa pausen är slut – redo för en ny omgång?" },
    keyboard: "Mellanslag: starta / pausa",
  },
  no: {
    modes: { work: "Fokus", short: "Kort pause", long: "Lang pause" },
    start: "Start",
    pause: "Pause",
    resume: "Fortsett",
    skip: "Hopp over",
    reset: "Nullstill",
    task: "Hva jobber du med?",
    taskPlaceholder: "f.eks. matteleksjon, skrive rapport",
    session: "Økt",
    today: "I dag",
    pomodoros: "pomodoroer",
    focusMinutes: "min fokus",
    settings: "Innstillinger",
    workMin: "Fokus (min)",
    shortMin: "Kort pause (min)",
    longMin: "Lang pause (min)",
    longEvery: "Lang pause hver",
    autoStart: "Start neste økt automatisk",
    notify: "Send varsler",
    notifyDenied: "Varsler ble blokkert; lydsignalet spilles likevel.",
    history: "Fullført i dag",
    noHistory: "Ingen fullførte pomodoroer ennå.",
    clearHistory: "Tøm i dag",
    done: { work: "Fokustiden er over – ta en pause!", short: "Pausen er over – tilbake til fokus!", long: "Den lange pausen er over – klar for en ny runde?" },
    keyboard: "Mellomrom: start / pause",
  },
  da: {
    modes: { work: "Fokus", short: "Kort pause", long: "Lang pause" },
    start: "Start",
    pause: "Pause",
    resume: "Fortsæt",
    skip: "Spring over",
    reset: "Nulstil",
    task: "Hvad arbejder du på?",
    taskPlaceholder: "f.eks. matematiklektier, skrive en rapport",
    session: "Runde",
    today: "I dag",
    pomodoros: "pomodoroer",
    focusMinutes: "min. fokus",
    settings: "Indstillinger",
    workMin: "Fokus (min.)",
    shortMin: "Kort pause (min.)",
    longMin: "Lang pause (min.)",
    longEvery: "Lang pause hver",
    autoStart: "Start næste runde automatisk",
    notify: "Send notifikationer",
    notifyDenied: "Notifikationer blev blokeret; lydsignalet afspilles stadig.",
    history: "Fuldført i dag",
    noHistory: "Ingen fuldførte pomodoroer endnu.",
    clearHistory: "Ryd i dag",
    done: { work: "Fokustiden er slut – tid til en pause!", short: "Pausen er slut – tilbage til fokus!", long: "Den lange pause er slut – klar til en ny runde?" },
    keyboard: "Mellemrum: start / pause",
  },
};

export const intervalCopy = {
  de: {
    phases: { prepare: "Bereit machen", work: "Los", rest: "Pause", cooldown: "Fertig" },
    presets: "Fertige Programme",
    custom: "Eigenes Programm",
    prepareSec: "Vorbereitung (s)",
    workSec: "Belastung (s)",
    restSec: "Pause (s)",
    rounds: "Runden",
    round: "Runde",
    total: "Gesamtdauer",
    remaining: "Noch",
    start: "Start",
    pause: "Pause",
    resume: "Weiter",
    reset: "Zurücksetzen",
    skip: "Nächste Phase",
    voice: "Sprachansage",
    beeps: "Piepton in den letzten 3 Sekunden",
    finished: "Training geschafft! 💪",
    fullscreen: "Vollbild",
    exitFullscreen: "Vollbild beenden",
  },
  tr: {
    phases: { prepare: "Hazırlan", work: "Çalış", rest: "Dinlen", cooldown: "Bitti" },
    presets: "Hazır programlar",
    custom: "Kendi programın",
    prepareSec: "Hazırlık (sn)",
    workSec: "Çalışma (sn)",
    restSec: "Dinlenme (sn)",
    rounds: "Tur sayısı",
    round: "Tur",
    total: "Toplam süre",
    remaining: "Kalan",
    start: "Başlat",
    pause: "Duraklat",
    resume: "Devam",
    reset: "Sıfırla",
    skip: "Sonraki faz",
    voice: "Sesli komut",
    beeps: "Son 3 saniye bip",
    finished: "Antrenman tamamlandı! 💪",
    fullscreen: "Tam ekran",
    exitFullscreen: "Tam ekrandan çık",
  },
  en: {
    phases: { prepare: "Get ready", work: "Work", rest: "Rest", cooldown: "Done" },
    presets: "Preset workouts",
    custom: "Your own workout",
    prepareSec: "Get ready (s)",
    workSec: "Work (s)",
    restSec: "Rest (s)",
    rounds: "Rounds",
    round: "Round",
    total: "Total time",
    remaining: "Left",
    start: "Start",
    pause: "Pause",
    resume: "Resume",
    reset: "Reset",
    skip: "Next phase",
    voice: "Voice cues",
    beeps: "Beep on the last 3 seconds",
    finished: "Workout complete! 💪",
    fullscreen: "Full screen",
    exitFullscreen: "Exit full screen",
  },
  sv: {
    phases: { prepare: "Gör dig redo", work: "Kör", rest: "Vila", cooldown: "Klart" },
    presets: "Färdiga program",
    custom: "Eget program",
    prepareSec: "Förberedelse (s)",
    workSec: "Arbete (s)",
    restSec: "Vila (s)",
    rounds: "Varv",
    round: "Varv",
    total: "Total tid",
    remaining: "Kvar",
    start: "Starta",
    pause: "Pausa",
    resume: "Fortsätt",
    reset: "Återställ",
    skip: "Nästa fas",
    voice: "Röstsignaler",
    beeps: "Pip de sista 3 sekunderna",
    finished: "Passet är klart! 💪",
    fullscreen: "Helskärm",
    exitFullscreen: "Avsluta helskärm",
  },
  no: {
    phases: { prepare: "Gjør deg klar", work: "Kjør", rest: "Hvil", cooldown: "Ferdig" },
    presets: "Ferdige programmer",
    custom: "Eget program",
    prepareSec: "Forberedelse (s)",
    workSec: "Arbeid (s)",
    restSec: "Hvile (s)",
    rounds: "Runder",
    round: "Runde",
    total: "Total tid",
    remaining: "Igjen",
    start: "Start",
    pause: "Pause",
    resume: "Fortsett",
    reset: "Nullstill",
    skip: "Neste fase",
    voice: "Talesignaler",
    beeps: "Pip de siste 3 sekundene",
    finished: "Økten er fullført! 💪",
    fullscreen: "Fullskjerm",
    exitFullscreen: "Avslutt fullskjerm",
  },
  da: {
    phases: { prepare: "Gør dig klar", work: "Kør", rest: "Hvil", cooldown: "Færdig" },
    presets: "Færdige programmer",
    custom: "Eget program",
    prepareSec: "Forberedelse (s)",
    workSec: "Arbejde (s)",
    restSec: "Hvile (s)",
    rounds: "Runder",
    round: "Runde",
    total: "Samlet tid",
    remaining: "Tilbage",
    start: "Start",
    pause: "Pause",
    resume: "Fortsæt",
    reset: "Nulstil",
    skip: "Næste fase",
    voice: "Talesignaler",
    beeps: "Bip de sidste 3 sekunder",
    finished: "Træningen er færdig! 💪",
    fullscreen: "Fuld skærm",
    exitFullscreen: "Afslut fuld skærm",
  },
};

export type IntervalPreset = { id: string; tr: string; en: string; de: string; sv: string; no: string; da: string; prepare: number; work: number; rest: number; rounds: number };

export const intervalPresets: IntervalPreset[] = [
  { id: "tabata", tr: "Tabata 20/10 × 8", en: "Tabata 20/10 × 8", de: "Tabata 20/10 × 8", sv: "Tabata 20/10 × 8", no: "Tabata 20/10 × 8", da: "Tabata 20/10 × 8", prepare: 10, work: 20, rest: 10, rounds: 8 },
  { id: "hiit-30", tr: "HIIT 30/30 × 10", en: "HIIT 30/30 × 10", de: "HIIT 30/30 × 10", sv: "HIIT 30/30 × 10", no: "HIIT 30/30 × 10", da: "HIIT 30/30 × 10", prepare: 10, work: 30, rest: 30, rounds: 10 },
  { id: "hiit-40", tr: "HIIT 40/20 × 8", en: "HIIT 40/20 × 8", de: "HIIT 40/20 × 8", sv: "HIIT 40/20 × 8", no: "HIIT 40/20 × 8", da: "HIIT 40/20 × 8", prepare: 10, work: 40, rest: 20, rounds: 8 },
  { id: "emom", tr: "EMOM 60 sn × 10", en: "EMOM 60 s × 10", de: "EMOM 60 s × 10", sv: "EMOM 60 s × 10", no: "EMOM 60 s × 10", da: "EMOM 60 s × 10", prepare: 10, work: 60, rest: 0, rounds: 10 },
  { id: "boxing", tr: "Boks 3 dk × 3 (1 dk ara)", en: "Boxing 3 min × 3 (1 min rest)", de: "Boxen 3 Min. × 3 (1 Min. Pause)", sv: "Boxning 3 min × 3 (1 min vila)", no: "Boksing 3 min × 3 (1 min hvile)", da: "Boksning 3 min. × 3 (1 min. pause)", prepare: 10, work: 180, rest: 60, rounds: 3 },
  { id: "plank", tr: "Plank 45/15 × 5", en: "Plank 45/15 × 5", de: "Plank 45/15 × 5", sv: "Planka 45/15 × 5", no: "Planke 45/15 × 5", da: "Planke 45/15 × 5", prepare: 10, work: 45, rest: 15, rounds: 5 },
];
