// Pomodoro ve aralikli antrenman zamanlayicilarinin metinleri (TR + EN).
export type FocusLang = "tr" | "en";

export const pomodoroCopy = {
  tr: {
    modes: { work: "Odak", short: "Kısa mola", long: "Uzun mola" },
    start: "Başlat",
    pause: "Duraklat",
    resume: "Devam",
    skip: "Atla",
    reset: "Sıfırla",
    task: "Ne üzerinde çalışıyorsun?",
    taskPlaceholder: "ör. Matematik ödevi, rapor yazımı",
    session: "Tur",
    today: "Bugün",
    pomodoros: "pomodoro",
    focusMinutes: "dk odak",
    settings: "Ayarlar",
    workMin: "Odak (dk)",
    shortMin: "Kısa mola (dk)",
    longMin: "Uzun mola (dk)",
    longEvery: "Uzun mola her",
    autoStart: "Sonraki turu otomatik başlat",
    notify: "Bildirim gönder",
    notifyDenied: "Bildirim izni verilmedi; sesli uyarı çalmaya devam eder.",
    history: "Bugün tamamlananlar",
    noHistory: "Henüz tamamlanan pomodoro yok.",
    clearHistory: "Günü temizle",
    done: { work: "Odak süresi bitti — mola zamanı!", short: "Mola bitti — odaklanma zamanı!", long: "Uzun mola bitti — yeni tura hazır mısın?" },
    keyboard: "Boşluk tuşu: başlat / duraklat",
  },
  en: {
    modes: { work: "Focus", short: "Short break", long: "Long break" },
    start: "Start",
    pause: "Pause",
    resume: "Resume",
    skip: "Skip",
    reset: "Reset",
    task: "What are you working on?",
    taskPlaceholder: "e.g. Maths homework, writing a report",
    session: "Session",
    today: "Today",
    pomodoros: "pomodoros",
    focusMinutes: "min focused",
    settings: "Settings",
    workMin: "Focus (min)",
    shortMin: "Short break (min)",
    longMin: "Long break (min)",
    longEvery: "Long break every",
    autoStart: "Start the next session automatically",
    notify: "Send notifications",
    notifyDenied: "Notifications were blocked; the sound alert still plays.",
    history: "Completed today",
    noHistory: "No pomodoros completed yet.",
    clearHistory: "Clear today",
    done: { work: "Focus time's up — take a break!", short: "Break's over — back to focus!", long: "Long break's over — ready for a new round?" },
    keyboard: "Space bar: start / pause",
  },
};

export const intervalCopy = {
  tr: {
    phases: { prepare: "Hazırlan", work: "Çalış", rest: "Dinlen", cooldown: "Bitti" },
    presets: "Hazır programlar",
    custom: "Kendi programın",
    prepareSec: "Hazırlık (sn)",
    workSec: "Çalışma (sn)",
    restSec: "Dinlenme (sn)",
    rounds: "Tur sayısı",
    round: "Tur",
    total: "Toplam süre",
    remaining: "Kalan",
    start: "Başlat",
    pause: "Duraklat",
    resume: "Devam",
    reset: "Sıfırla",
    skip: "Sonraki faz",
    voice: "Sesli komut",
    beeps: "Son 3 saniye bip",
    finished: "Antrenman tamamlandı! 💪",
    fullscreen: "Tam ekran",
    exitFullscreen: "Tam ekrandan çık",
  },
  en: {
    phases: { prepare: "Get ready", work: "Work", rest: "Rest", cooldown: "Done" },
    presets: "Preset workouts",
    custom: "Your own workout",
    prepareSec: "Get ready (s)",
    workSec: "Work (s)",
    restSec: "Rest (s)",
    rounds: "Rounds",
    round: "Round",
    total: "Total time",
    remaining: "Left",
    start: "Start",
    pause: "Pause",
    resume: "Resume",
    reset: "Reset",
    skip: "Next phase",
    voice: "Voice cues",
    beeps: "Beep on the last 3 seconds",
    finished: "Workout complete! 💪",
    fullscreen: "Full screen",
    exitFullscreen: "Exit full screen",
  },
};

export type IntervalPreset = { id: string; tr: string; en: string; prepare: number; work: number; rest: number; rounds: number };

export const intervalPresets: IntervalPreset[] = [
  { id: "tabata", tr: "Tabata 20/10 × 8", en: "Tabata 20/10 × 8", prepare: 10, work: 20, rest: 10, rounds: 8 },
  { id: "hiit-30", tr: "HIIT 30/30 × 10", en: "HIIT 30/30 × 10", prepare: 10, work: 30, rest: 30, rounds: 10 },
  { id: "hiit-40", tr: "HIIT 40/20 × 8", en: "HIIT 40/20 × 8", prepare: 10, work: 40, rest: 20, rounds: 8 },
  { id: "emom", tr: "EMOM 60 sn × 10", en: "EMOM 60 s × 10", prepare: 10, work: 60, rest: 0, rounds: 10 },
  { id: "boxing", tr: "Boks 3 dk × 3 (1 dk ara)", en: "Boxing 3 min × 3 (1 min rest)", prepare: 10, work: 180, rest: 60, rounds: 3 },
  { id: "plank", tr: "Plank 45/15 × 5", en: "Plank 45/15 × 5", prepare: 10, work: 45, rest: 15, rounds: 5 },
];
