import type { Metadata } from "next";
import Link from "next/link";
import EnglishBiotNumberCalculator from "../../../../components/EnglishBiotNumberCalculator";
import { buildFaqSchema, type FaqItem } from "../../../../converter/faqSchema";
import { buildSiteUrl } from "../../../../siteConfig";

const pagePath = "/en/engineering-calculators/dimensionless-numbers/biot-number-calculator";
const faqItems: FaqItem[] = [
  { question: "What does the Biot number compare?", answer: "It compares a solid's internal conduction resistance with its surface convection resistance: Bi = hLc/ks." },
  { question: "What does Bi less than 0.1 mean?", answer: "It is a common first criterion for treating a body as approximately uniform in temperature in a lumped-capacitance analysis, subject to the geometry and boundary conditions." },
  { question: "What is characteristic length?", answer: "For many transient-conduction applications it is the body volume divided by the exposed surface area. The correct definition depends on the model and geometry." },
];

export const metadata: Metadata = { title: "Biot Number Calculator (Bi = hLc / ks)", description: "Calculate the dimensionless Biot number from convection coefficient, characteristic length and solid thermal conductivity with SI and Imperial units.", alternates: { canonical: pagePath, languages: { en: pagePath } }, openGraph: { title: "Biot Number Calculator", description: "Screen internal versus surface thermal resistance for transient heat-transfer analysis.", url: buildSiteUrl(pagePath), siteName: "BirimCeviri.app", locale: "en_US", type: "article" } };
function serializeJsonLd(data: object) { return JSON.stringify(data).replace(/</g, "\\u003c"); }

export default function EnglishBiotNumberPage() {
  const breadcrumbSchema = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: buildSiteUrl("/en") }, { "@type": "ListItem", position: 2, name: "Dimensionless Numbers", item: buildSiteUrl("/en/engineering-calculators/dimensionless-numbers") }, { "@type": "ListItem", position: 3, name: "Biot Number Calculator", item: buildSiteUrl(pagePath) }] };
  return <main className="all-conversions-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(breadcrumbSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(buildFaqSchema(faqItems)) }} /><div className="all-conversions-shell"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/en">Home</Link><span aria-hidden="true">›</span><Link href="/en/engineering-calculators/dimensionless-numbers">Dimensionless Numbers</Link><span aria-hidden="true">›</span><span>Biot Number Calculator</span></nav><header className="all-conversions-header"><h1>Biot Number Calculator</h1><p>Calculate the Biot number to screen whether internal temperature gradients in a solid are likely to matter during convection-driven heating or cooling.</p></header><EnglishBiotNumberCalculator /><article className="category-article-content"><h2>Method and variables</h2><p><strong>Formula:</strong> Bi = hL<sub>c</sub>/k<sub>s</sub>.</p><ul><li><strong>h</strong> — convection heat-transfer coefficient</li><li><strong>L<sub>c</sub></strong> — characteristic length</li><li><strong>k<sub>s</sub></strong> — thermal conductivity of the solid</li></ul><h2>Worked example</h2><p>A solid with h = 25 W/(m²·K), L<sub>c</sub> = 0.01 m and k<sub>s</sub> = 15 W/(m·K) has Bi = 0.0167. This is below 0.1, so a lumped-capacitance estimate may be a reasonable first approximation.</p><h2>How it connects to other tools</h2><p>Use Biot number before a transient lumped-capacitance analysis. Fourier number then describes the dimensionless elapsed time in that analysis.</p><h2>Important limits</h2><p>The Bi ≤ 0.1 rule is not universal validation. Nonuniform convection, multilayer parts, strongly temperature-dependent properties, radiation, internal heat generation and complex geometry can require a more detailed model.</p><h2>References</h2><ul><li><a href="https://openstax.org/books/college-physics-2e/pages/14-6-conduction" target="_blank" rel="noreferrer">OpenStax: Conduction</a></li><li><a href="https://www.nist.gov/pml/special-publication-811" target="_blank" rel="noreferrer">NIST Guide for the Use of the International System of Units</a></li></ul><h2>Related tools</h2><p><Link href="/en/calculators/heat-conduction">Heat Conduction Calculator</Link> · <Link href="/en/engineering-calculators/dimensionless-numbers/prandtl-number-calculator">Prandtl Number Calculator</Link> · <Link href="/en/engineering-calculators/dimensionless-numbers">Dimensionless Numbers Calculators</Link></p></article></div></main>;
}
