import type { Metadata } from "next";
import Link from "next/link";
import EnglishEulerBucklingCalculator from "../../../../components/EnglishEulerBucklingCalculator";
import { buildSiteUrl } from "../../../../siteConfig";

const pagePath = "/en/engineering-calculators/mechanics-materials/euler-buckling-calculator";
export const metadata: Metadata = { title: "Euler Buckling Calculator", description: "Calculate ideal elastic Euler critical load for a slender column from end condition, length, Young's modulus and second moment of area.", alternates: { canonical: pagePath, languages: { en: pagePath } }, openGraph: { title: "Euler Buckling Calculator", description: "Calculate an ideal Euler critical load for a stated slender column and support condition.", url: buildSiteUrl(pagePath), siteName: "BirimCeviri.app", locale: "en_US", type: "article" } };

export default function EulerBucklingCalculatorPage() {
  return <main className="all-conversions-page"><div className="all-conversions-shell"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/en">Home</Link><span aria-hidden="true">›</span><Link href="/en/engineering-calculators">Engineering Calculators</Link><span aria-hidden="true">›</span><Link href="/en/engineering-calculators/mechanics-materials">Mechanics &amp; Materials</Link><span aria-hidden="true">›</span><span>Euler Buckling Calculator</span></nav><header className="all-conversions-header"><h1>Euler Buckling Calculator</h1><p>Estimate ideal elastic critical load for a slender column with a stated support condition.</p></header><EnglishEulerBucklingCalculator /><article className="category-article-content"><h2>Method</h2><p>Euler&apos;s ideal critical load is P<sub>cr</sub> = π<sup>2</sup>EI/(KL)<sup>2</sup>. The effective-length factor K is determined by the selected ideal end condition.</p><h2>Worked example</h2><p>A 2 m pin-ended steel column with E = 200 GPa and I = 8.333 × 10<sup>6</sup> mm<sup>4</sup> has an ideal Euler critical load of about 4,112 kN.</p><h2>Important limits</h2><p>This is an ideal elastic buckling result, not an allowable or factored design capacity. It is appropriate only as a slender-column screening calculation; use the governing structural standard for inelastic behavior, imperfections, load eccentricity and safety factors.</p><h2>References</h2><ul><li><a href="https://ocw.mit.edu/courses/1-050-engineering-mechanics-i-fall-2007/pages/lecture-notes/" target="_blank" rel="noreferrer">MIT OpenCourseWare: beam deformation and Euler buckling</a></li><li><a href="https://www.nist.gov/pml/special-publication-811" target="_blank" rel="noreferrer">NIST Guide for the Use of the International System of Units</a></li></ul><h2>Related tools</h2><p><Link href="/en/engineering-calculators/mechanics-materials/cantilever-beam-deflection-calculator">Cantilever Beam Deflection Calculator</Link> · <Link href="/en/engineering-calculators/mechanics-materials/stress-strain-calculator">Stress &amp; Strain Calculator</Link> · <Link href="/en/engineering-calculators/mechanics-materials">Mechanics &amp; Materials Calculators</Link></p></article></div></main>;
}
